### ISSUE TITLE
[Feature] Generate IEntityTypeConfiguration<T> Mappers

### ISSUE THREAD

**Issue by vertonghenb** [ErikEJ/EFCorePowerTools#100]
Currently all the mapping of the EntityTypes are generated in the function:
 ` protected override void OnModelCreating(ModelBuilder modelBuilder)`. This can become pretty large...
I suggest we create scaffold a  `IEntityTypeConfiguration` file for each entity and use these in the
`OnModelCreating` function.

For example: `Customer.cs`

> CustomerConfiguration.cs
```cs
internal class CustomerConfiguration : IEntityTypeConfiguration<Customer>
{
  public void Configure(EntityTypeBuilder<Customer> builder)
  {
     builder.HasKey(c => c.AlternateKey);
     builder.Property(c => c.Name).HasMaxLength(200);
     // ...
   }
}
```
> DbContext
```cs
// OnModelCreating
builder.ApplyConfiguration(new CustomerConfiguration());
```
Optional:
- Choose a template name suffix

**Comment by Diaskhan** [comment]
Any news about this Feature ?

**Comment by ErikEJ** [comment]
The project is open source and accepts PRs

**Comment by bricelam** [comment]
I've been experimenting over in [bricelam/EFCore.TextTemplating](https://github.com/bricelam/EFCore.TextTemplating) with some code that generates IEntityTypeConfiguration classes.

See also https://github.com/aspnet/EntityFrameworkCore/issues/8434

**Comment by Diaskhan** [comment]
I ve got roslyn generator ! That generates from custom structure metadata! 
@bricelam ? From what kind structure data better generate entity class and entitytypeconfigration ? 

From IEntitytype ?

**Comment by Diaskhan** [comment]
There is also have https://github.com/sergey-kolodiy/PolyGen
Some generator workable !

**Comment by ErikEJ** [comment]
There is also the dotnet global toolhttp://www.loresoft.com/Generate-ASP-NET-Web-API

**Comment by ErikEJ** [comment]
Will implement using https://github.com/lauxjpn/DbContextOnModelCreatingSplitter - initially just a checkbox to enable this!

**Comment by ErikEJ** [comment]
This is now implemented (preview) in the latest daily build!
