### ISSUE TITLE
System.ComponentModel.Win32Exception on reverse engineer.

### ISSUE THREAD

**Issue by freekwernas** [ErikEJ/EFCorePowerTools#1000]
Hi,

Im experiencing some difficulties with the generator, where when I reverse engineer my database I get the following error:

```
System.ComponentModel.Win32Exception (0x80004005): Het systeem kan het opgegeven bestand niet vinden
   at bool System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at bool System.Diagnostics.Process.Start() x 2
   at async Task<string> EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.RunProcessAsync(ProcessStartInfo startInfo)
   at async Task<List<TableModel>> EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.GetTablesInternalAsync(string arguments)
   at async Task<List<TableModel>> EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.GetTablesAsync(string connectionString, DatabaseType databaseType, SchemaInfo[] schemas)
   at async Task<List<TableModel>> EFCorePowerTools.Handlers.ReverseEngineer.TableListBuilder.GetTableDefinitionsAsync(CodeGenerationMode codeGenerationMode)
   at async Task<List<TableModel>> EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.GetTablesAsync(DatabaseConnectionModel dbInfo, CodeGenerationMode codeGenerationMode, SchemaInfo[] schemas)
   at async Task<bool> EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.LoadDataBaseObjectsAsync(ReverseEngineerOptions options, DatabaseConnectionModel dbInfo, Tuple<List<Schema>, string> namingOptionsAndPath)
   at async Task EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.ReverseEngineerCodeFirstAsync(Project project, string optionsPath, bool onlyGenerate)
```
   
  Further technical details
EF Core Power Tools version: 2.5.665

Database engine: SQL Server

Visual Studio version: Microsoft Visual Studio Proffesional 2019 Version 16.10.0

csproj file:
TargetFramework:net5.0
Microsoft.EntityFrameworkCore.Design Version="5.0.6"
Microsoft.EntityFrameworkCore.SqlServer Version="5.0.6"
Microsoft.EntityFrameworkCore.Tools Version="5.0.6"

**Comment by ErikEJ** [comment]
Do you have the dotnet 3.1 runtime installed?

`dotnet --list-runtimes`

If yes, then try to launch manually from the %temp%/efptX.xxx folder:

`efreveng.exe 3 "Data Source=xxx"`

**Comment by freekwernas** [comment]
Hi Erik,

Thanks for the quick response: the following results are returned for the list of runetimes

C:\Users\Freek>dotnet --list-runtimes
Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

when I run the command I get the following error:
![image](https://user-images.githubusercontent.com/18334535/120203763-57a76280-c228-11eb-97a9-556ad65f4852.png)

**Comment by ErikEJ** [comment]
I will try to repro

**Comment by ErikEJ** [comment]
Looks like something went wrong during unzipping to that folder - how many files are in it?

Can you try to rename the folder and try reverse engineering again?

**Comment by freekwernas** [comment]
Fully deleting all files in Temp and re-running it, seems to get me a single step further but the problem still remains (it does now open the menu of what it needs to reverse engineer, but the error persists and it does nothing).

**Comment by ErikEJ** [comment]
So it lists the files now, but you cannot generate code?

**Comment by ErikEJ** [comment]
And what is the error message?

**Comment by ErikEJ** [comment]
(I am not able to reproduce)

**Comment by ErikEJ** [comment]
Ups,  wrong diagnostics command, I need you to run this command from the folder in %temp% :

`efreveng50.exe 3 "Data Source=xxx"`

**Comment by freekwernas** [comment]
The same errors persist after fully deleting
via visual studio:
![image](https://user-images.githubusercontent.com/18334535/120275374-7c93e800-c2b1-11eb-9451-045ac8a6d96e.png)
via cmd:
![image](https://user-images.githubusercontent.com/18334535/120275432-97fef300-c2b1-11eb-978e-f8629c3d7a22.png)

**Comment by ErikEJ** [comment]
Use efreveng50.exe not efreveng.exe please

**Comment by freekwernas** [comment]
I cannot find the efreveng50.exe in the Temp folder.

**Comment by freekwernas** [comment]
Hi Erik, I just got a call from maintenance, apperantly Avast security removes the file efreveng50.exe because it is detected as an idp.genereic, this is likely the problem im currently facing. What do you suggest I do about it and why is it triggering my antivirus in the first place?

**Comment by ErikEJ** [comment]
I have no idea why your anti-virus detects this false positive. Ask for an update or exemption to the scanner.

I will add a clearer error message, if the expected .exe file is not present.
