### ISSUE TITLE
Can't use only stored procedure

### ISSUE THREAD

**Issue by GearTheWorld** [ErikEJ/EFCorePowerTools#1002]
### Describe what is not working as expected.
Can't use only Stored Procedure.  The OK button is disabled if no tables are selected.  We are forced to select at least one table

### Steps to reproduce
Unselect ALL tables and select only stored procedure and the button OK is disabled

### Further technical details
EF Core Power Tools version: (found in About dialog - blue question mark icon on context menu)
**Version 2.5.665.0**

### Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite)

Microsoft SQL Server 2019 (RTM-GDR) (KB4583458) - 15.0.2080.9 (X64) 

SQL Server Management Studio                       15.0.18384.0
SQL Server Management Objects (SMO)	  16.100.46367.54
Microsoft Analysis Services Client Tools		  15.0.19535.0
Microsoft Data Access Components (MDAC)	  10.0.19041.1
Microsoft MSXML						  3.0 6.0 
Microsoft .NET Framework				  4.0.30319.42000
Operating System						  10.0.19042

### Visual Studio version: (e.g., Visual Studio 2019 16.9)
Microsoft Visual Studio Professional 2019
Version 16.9.6

![Issue](https://user-images.githubusercontent.com/8614008/120372276-28d0df80-c341-11eb-852f-ec93fa42ee92.png)

**Comment by ErikEJ** [comment]
The is by design, as the stored procedures requires the prescence of a DbContext.

**Comment by GearTheWorld** [comment]
Strange. I thought you could create the ApplicationDbContext even if you don't add any table.  If I remove the only table in the generated code, it works hence I only have the stored procedures available by the context.

**Comment by ErikEJ** [comment]
Yes, that workaround works.

**Comment by GearTheWorld** [comment]
So it remains as a suggestion!

Here another good suggestion.  The files in the project are a mess when you have tons of tables and stored procedures along with EF own classes.  What would be very elegant is to put everything in a respective folder like 

[EF Classes]
[Tables]
[Stored Procedures]
[Functions] // Future ;)

So when we get in the project it's much easier to find what we're looking for

**Comment by ErikEJ** [comment]
You can create configurations and entities in separate folders already, feel free to create a proposal for stored procedure result classes.

**Comment by ErikEJ** [comment]
You can create configurations and entities in separate folders already, feel free to create a proposal for stored procedure result classes.

**Comment by ErikEJ** [comment]
You can create configurations and entities in separate folders already, feel free to create a proposal for stored procedure result classes.

**Comment by ErikEJ** [comment]
I attempted a fix/hack in the latest daily
