### ISSUE TITLE
EF Core 3.1 or later not found in project

### ISSUE THREAD

**Issue by WalterW** [ErikEJ/EFCorePowerTools#1004]
Describe what is not working as expected.

### Steps to reproduce
When add DBContext diagram

### Further technical details
![image](https://user-images.githubusercontent.com/1876703/120430583-cd870780-c3a9-11eb-9ee6-229c4d91eabd.png)

**Comment by ErikEJ** [comment]
Is EF Core 3.1nuget package installed in the project?

**Comment by WalterW** [comment]
due to some nuget issue now I'm in using the correct version but having the following issue on the DBContext

![image](https://user-images.githubusercontent.com/1876703/120475165-9893a880-c3db-11eb-9189-04b6ef1a1bf4.png)

**Comment by WalterW** [comment]
The issue fix due to some error on the class during building time. thanks ErikEJ
