### ISSUE TITLE
Add Menu item to create compiled model (EF Core 6)

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#1005]
https://www.youtube.com/watch?v=XdhX3iLXAPk 

https://github.com/dotnet/efcore/issues/25135

Create compiled models for all discovered contexts

**Comment by ErikEJ** [comment]
Will await request

**Comment by TimKras** [comment]
@ErikEJ 
Will this feature be added to EF Core Power tools extension?

**Comment by ErikEJ** [comment]
I am reluctant - need to copy a lot of code for this to work.

Why is it important?

**Comment by TimKras** [comment]
We have al very large database schema. First query takes about 1min. 
Compiled models could reduce the startup performance.

**Comment by ErikEJ** [comment]
They are simple to build using the EF Core CLI tools...
