### ISSUE TITLE
[Feature] Manipulate ClassName

### ISSUE THREAD

**Issue by vertonghenb** [ErikEJ/EFCorePowerTools#101]
In a lot of projects the Database Table name is prefixed with stuff like "tbl" but it's rather worthless in a C# class since you'll use a namespace for it.

I suggest to have an opt in function to replace the start or suffix of a tablename to another string for example string.Empty.

- tableName: tblUsers
- className: User;
- ToTable("tblUsers") in the modelbuilder

**Comment by ErikEJ** [comment]
Looks like a duplicate of #14 ?

**Comment by vertonghenb** [comment]
@ErikEJ  correct, I'll close this one in favor of #14
