### ISSUE TITLE
Debugable in x86?

### ISSUE THREAD

**Issue by MisinformedDNA** [ErikEJ/EFCorePowerTools#1010]
The `README.md` says "ensure your build configuration is Debug, x86 (not AnyCPU)." However, a recent [PR](https://github.com/ErikEJ/EFCorePowerTools/pull/955) removed all x86 references in preparation for VS 2022.  Shouldn't x86 be left in for VS 2019 support?

**Comment by ErikEJ** [comment]
The readme should be updated to AnyCPU

**Comment by ErikEJ** [comment]
Fixed
