### ISSUE TITLE
Feature Request: Specify namespace for DbContextExtensions, useful for Multiple DbContexts

### ISSUE THREAD

**Issue by the-super-coder** [ErikEJ/EFCorePowerTools#1012]
I have 6 `DBContexts`, and EFCorePT generates a `DbContextExtensions `class for each `DBContext`, this introduces ambiguity when I am using StoredProcedure methods from multiple `DbContexts `into a repository class.

### Steps to reproduce
1. Add at least 2 `DbContexts`
2. Generate code for both, must include stored procedures (that is when the `DbContextExtensions `come into use).
3. Create a repository and a method in it i.e. `DoSomthing()`.
4. `DoSomething() `will call stored procedures from both `DbContexts `in it, and it will pass `OutputParameter `too.

**Current Result:**
You will notice compile has found ambiguity between which `OutputParamter `class to use, since both `DbContexts`' namespaces have been refereed in the repository and there is a separate copy of `DbContextsExtensions` for each `DbContext ` in their respective namespace.

**Expected Result:**
There should be an option in the Reverse Engineering tool to specify the namespace where to generate the `DbContextExtensions`, so that developer can give a namespace where the extensions can be generated for all `DbContexts`.

### Further technical details
EF Core Power Tools version: 2.5.665 (Not specific to this version only, it has been like this since the support for multiple DbContext was introduced)

Database engine: SQL Server

Visual Studio version: Visual Studio 2019 v16.10.31321.278

**Comment by ErikEJ** [comment]
An easy workaround is to remove all except a single instance of the class.

Probably a better way would be to include the methods in a NuGet package.

**Comment by ErikEJ** [comment]
This can be fixed simply by qualifying the namespace in your repo code.
