### ISSUE TITLE
Using Stored Procedure

### ISSUE THREAD

**Issue by kenbo017** [ErikEJ/EFCorePowerTools#1013]
I'm trying to use a stored procedure.  I tried to follow your instructions from YouTube but something isn't correct.

My first question is regarding the async.  In your YouTube video you called the SP using async.  Are all stored procedures supposed to be called using async?

My second question is in that, when I'm calling the stored procedure I'm not getting the columns of the table I'm retrieving data from as available.  Attached is a screenshot of what I tried to do.  You will see the adaptation from your video.  Then, below that, is commented out the code that was working without issue when using LINQ.  What am I doing wrong?

![Screenshot of SP not working](https://user-images.githubusercontent.com/32583352/120912351-22917a80-c643-11eb-82f8-3948c0e6c476.png)

Also, I apologize that I'm not very familiar with GitHub.  I wanted to create this as a question and not an issue but I don't know how to do that.  If you can instruct me on how to ask question from the community such as this one, I will do so next time.

Describe what is not working as expected.

### Steps to reproduce
Include a complete description that I can redo to reproduce the issue.

### Further technical details
EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)

Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite)

Visual Studio version: (e.g. Visual Studio 2019 16.9)

**Comment by ErikEJ** [comment]
You are calling the async method wrong, you must either make the calling method Async, or use .Result on the method call.

**Comment by kenbo017** [comment]
I tried making the method async and that didn't work.  I don't know what
you mean by using Result on the method call.

Ken Schneider
Schneider Sales and Marketing
312 West Hillcrest Blvd.
Inglewood, CA 90301
ph: 310-680-9544
cell: 310-722-8827
e-mail: ***@***.***


CONFIDENTIALITY NOTICE. This electronic mail transmission may contain
privileged, confidential and/or protected information and is intended only
for the review of the party to whom it is addressed. Any unauthorized use
or disclosure of the information contained herein may be a violation of
federal law. If you have received this transmission in error, please
immediately return it to the sender, delete it and destroy it without
reading it. Unintended transmission shall not constitute the waiver of the
attorney-client or any other privilege.

**Comment by ErikEJ** [comment]
Just add .Result on line 28 (and maybe read up on using Async with .NET?)

**Comment by kenbo017** [comment]
Thanks for the nudge.  The .Result works.  I'll look at the Async.  Would you suggest I use the asyn method for better performance?

**Comment by ErikEJ** [comment]
The benefit of Async depends on your type of app, but generally yes.
