### ISSUE TITLE
VS2019 freeze because of EFCorePowerTools when giving a new SQL Connection

### ISSUE THREAD

**Issue by KilianMERE** [ErikEJ/EFCorePowerTools#1016]
EFCorePowerTools keep Freezing when i try to add a new SQL Server.

When i enter my SQL Server IP everything related to EfCore power tool just freeze, no error message, no responding.
The only way to get the control back is by going through the task manager and Kill devenv.exe.
![bug](https://user-images.githubusercontent.com/49316059/121683995-67436880-cabe-11eb-804c-d1b462d5b73f.png)

I have also tried to install power tools from the Open VSIX Gallery but the Freeze keep happening.
I also tried to use it in a fresh new project but everything freeze the same.

And i found nothing about this behaviour on internet, what powertool is trying to do when i give him the server IP and selecting the authenticating method ?

I apologize for my english, he's not great that's not my native langage.

### Steps to reproduce
There is none, i have done nothing special.

### Further technical details
EF Core Power Tools version: 2.5.671 / 2.5.665

Database engine: SQL Server

Visual Studio version: Visual Studio 2019 16.10.1

**Comment by ErikEJ** [comment]
This is a Visual Studio dialog, what happens if you do the same from Server Explorer?

**Comment by KilianMERE** [comment]
i've found the culprit....sorry for the inconvenience..

So, on our pfsense only one port was open the TCP 1433.
We have opened the other one used by SQL Server so : TCP 1433, 4022, 135, 1434, UDP 1434.

And the problem was solved, i'm really sorry about this issue that is my fault...

Thanks for your time ! :)
