### ISSUE TITLE
Not able to build grpah

### ISSUE THREAD

**Issue by sm-g** [ErikEJ/EFCorePowerTools#102]
It was working with my project half year ago. Now, when I run "Add DbContext model diagram":
	
> System.Exception: Unable to find a supported version of Microsoft.EntityFrameworkCore.dll in folder C:\MY\src\DAL\bin\Debug\net461. Version found: 
>   at EFCorePowerTools.Handlers.ProcessLauncher.DropFiles(String outputPath) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ProcessLauncher.cs:line 149
>   at EFCorePowerTools.Handlers.ProcessLauncher.GetOutput(String outputPath, String projectPath, GenerationType generationType, String contextName, String migrationIdentifier, String nameSpace) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ProcessLauncher.cs:line 55
>   at EFCorePowerTools.Handlers.ModelAnalyzerHandler.Generate(String outputPath, Project project, GenerationType generationType) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ModelAnalyzerHandler.cs:line 39
   
There is dll with version 2.1.1.18157 in the folder.

When I run "View database schema as graph":

![](https://i.imgur.com/SOTe4bM.png)

I have

```
public class MyContextDesignFactory : IDesignTimeDbContextFactory<MyContext>
{
	public MyContext CreateDbContext(string[] args)
	{
		var optionsBuilder = new DbContextOptionsBuilder<MyContext>()
			.UseSqlServer("Server=.;Initial Catalog=notsupported;Integrated Security=true");

		return new MyContext(optionsBuilder.Options);
	}
}
```

Csproj:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net461</TargetFramework>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>
...
  <ItemGroup>
    <PackageReference Include="MassTransit.Automatonymous.Extensions.DependencyInjection" Version="4.1.0.1411-develop" />
    <PackageReference Include="MassTransit.EntityFrameworkCore" Version="4.1.0.1411-develop" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="2.1.1" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="2.1.1" />
    <PackageReference Include="System.Data.Common" Version="4.3.0" />
    <PackageReference Include="StructureMap" Version="4.7.0" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>
</Project>
```

### Further technical details
EF Core Power Tools version: 1.0.654.0
Visual Studio version: 15.8.6

**Comment by ErikEJ** [comment]
The latest released version only support EF Core 2.1.3 and 2.1.0 - the latest daily build supports EF Core 2.1.4 and 2.1.0

**Comment by sm-g** [comment]
@ErikEJ Why 2.1.1 and 2.1.2 could not be supported with 2.1.3 and 2.1.0?

**Comment by ErikEJ** [comment]
Too much work and too much support

**Comment by ErikEJ** [comment]
What is preventing you from using 2.1.4 ?
