### ISSUE TITLE
Executing UDFs form DbContext

### ISSUE THREAD

**Issue by AliBdeir** [ErikEJ/EFCorePowerTools#1020]
Sorry if I'm bringing up a dead issue, but has this been implemented? While I do get the function as a static method, I see no way of actually executing this:

```
[DbFunction("fnGetSchema", "dbo")]
public static string fnGetSchema(string guid)
{
    throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
}
```

I'm not sure I quite understand this. While I do see that #543 is closed, I don't see anything in the documentation concerning this.

**Comment by MisinformedDNA** [comment]
Agreed, it's a little confusing. But basically you can't just call `MyDbContext.fnGetSchema(string)`, you have to call it _as part_ of another query. Something like 

```csharp
myDbContext.Orders.Select(o => MyDbContext.fnGetSchema(o.OrderName))
```

**Comment by ErikEJ** [comment]
Thanks, @MisinformedDNA !

Agree that documentation is lacking!

**Comment by ErikEJ** [comment]
Updated docs

**Comment by AliBdeir** [comment]
Oh that's interesting. Out of curiosity, why does this limitation exist?

**Comment by ErikEJ** [comment]
How is that a limitation?

**Comment by MisinformedDNA** [comment]
For instance, there is no simple EF Core equivalent to `SELECT * FROM fnGetSalesTotal()`.

One could do 

```csharp
double total = dbContext.DbSet<AnyEntity>().Select(_ => MyDbContext.GetSalesTotal()).First();
```

but `AnyEntity` is completely unnecessary for the actual query. It's sure to cause confusion and, I'm guessing, would add some unnecessary overhead.
