### ISSUE TITLE
Error Generating DbContext Diagram

### ISSUE THREAD

**Issue by dan-meier** [ErikEJ/EFCorePowerTools#1023]
I have a class library that accesses Azure SQL Database. The library uses a code-first database design, and all DbContext configurations have been manually created. I was hoping to use EF Core Power Tools to generate an entity diagram.  However, the "Add DbContext Diagram" function fails:

![image](https://user-images.githubusercontent.com/19295873/122485041-dae7e880-cf8a-11eb-85bb-3544f56458cb.png)

Because the class library is referenced by UWP and Xamarin Forms apps, it uses .NET Standard 2.0.  I cannot upgrade to .NET Standard 2.1/.NET Core 3.x because UWP and Xamarin Forms are not yet compatible with .NET Standard 2.1/.NET Core 3.x.

Is there a version of EF Core Power Tools that will allow me to generate an entity diagram for this configuration?

### Further technical details
EF Core Power Tools v2.5.665
EF Core v3.1.9
Visual Studio 2019 v16.10.2
Database engine:  Azure SQL Database

**Comment by ErikEJ** [comment]
Have a look here: https://github.com/ErikEJ/EFCorePowerTools/wiki/Inspect-your-DbContext-model
