### ISSUE TITLE
why are relational databases not working?

### ISSUE THREAD

**Issue by Kahraman-Murat** [ErikEJ/EFCorePowerTools#1026]
why are relational databases not working?
In the EF Power Tools plugin I used before, Table relations could be used and there was also a Map folder under the Model folder.
Should I completely change my codes?
Or how can I use it in related tables?

Visual Studio version: (e.g. Visual Studio 2019 16.9)

**Comment by ErikEJ** [comment]
I do not understand your question, please provide much more detail.

**Comment by Kahraman-Murat** [comment]
Thank you for your answer. I try to explain.

when I use EF Power Tools, the table field can be accessed only with relational tablename.
Example:
string text=db.Table1.Table2.Field1;

when I use EF CORE Power Tools, the table field can be accessed with the combination of the tablename and relational tablename.
Example:
string text=db.Table1.Table1Table2.Field1;

I wonder, wheter there is an opportunity to acces the table field only with relational tablename,when I use EF Core Power Tools.
(I mean like this:  string text=db.Table1.Table2.Field1;)

Is there any setting for this in Reverse Engineer?

Because My code is already completed. I want to apply recent changes in database with EF Core Power Tools.

Thank you

**Comment by ErikEJ** [comment]
You really need to share a full code sample with database table create statements that demonstrates the issue.

Also there is no simple upgrade path from EF6 to EF Core
