### ISSUE TITLE
Migrations tool error, Only .NET Core 3.0+

### ISSUE THREAD

**Issue by mattgenious** [ErikEJ/EFCorePowerTools#1031]
Hi,

I really hope I'm not just using it wrong but I have the following issue.
When I go to open the migrations tool I get the following error message.

```
EF Core Power Tools

Only .NET Core 3.0+ projects are supported - TargetFrameworkMoniker: .NETCoreApp,Version=v6.0
```
<img width="275" alt="Screenshot 2021-06-22 105851" src="https://user-images.githubusercontent.com/3007300/122895926-dafc3580-d348-11eb-9002-be8da50ab7e2.png">

I am running the daily build version 2.5.691 specifically as I understood that this would support .NET 6.
I am using .NET 6.0 preview 5 on Visual Studio Community 2019 Preview - 16.11.0 Preview 2

I got the same error running Visual Studio Community 2019 Preview - 16.11.0 Preview 1 and .NET 6 preview 4.

The setup in question is a based on Postgres and is using Npgsql.EntityFrameworkCore.PostgreSQL 6.0.0-preview4.

**Comment by ErikEJ** [comment]
Currently the migration tool only works with projects targeting .NET 5.0.

The latest daily build support EF Core 6 preview 5!

**Comment by mattgenious** [comment]
Ah I understand now 😄 
Sorry about that 😅

**Comment by ErikEJ** [comment]
As EF Core 6 soon will only run on .NET 6, this will change.
