### ISSUE TITLE
组件错误的删除了文件夹

### ISSUE THREAD

**Issue by TimChen44** [ErikEJ/EFCorePowerTools#1033]
更新模型时（反向工程），项目中的文件夹会被删除（下图中“Extended”和“Partial”），此文件夹中我存放的是我对生成的代码进行扩展的内容。
建议不要删除用户创建的文件夹，谢谢。
When updating the model (reverse engineering) , the folders in the project will be deleted ("Extended" and "Partial" in the figure below). In this folder, I store the contents of my expanded code. 
It is recommended not to delete the folder created by the user, thank you. 

![image](https://user-images.githubusercontent.com/7581981/123019072-58d04780-d402-11eb-854b-32e0e623b2b4.png)

### Steps to reproduce
默认配置进行第二次反向工程

### Further technical details
EF Core Power Tools version: 2.5.691.0

Database engine: SQL Server

Visual Studio version: Visual Studio 2019 16.10.2

**Comment by ErikEJ** [comment]
@eminmesic FYI!

**Comment by ErikEJ** [comment]
@TimChen44 Thanks for reporting this, I have released build .692, which fixes this bug.

Would be grateful if you could confirm the fix.

**Comment by TimChen44** [comment]
经过测试，删除文件夹的问题已经修复。
但是出现了新问题，代码生成完成后，VisualStudio会直接奔溃退出。
After testing, the problem of deleting folders has been fixed.
However, there is a new problem. After the code generation is completed, VisualStudio will crash and exit.

**Comment by ErikEJ** [comment]
I cannot repro. You need to provide more info, from the Event log or elsewhere.

Or share a repro project

**Comment by TimChen44** [comment]
我修复了VisualStudio后，使用奔溃的问题不存在了。谢谢。
After I repaired VisualStudio, the problem of using crash no longer exists. Thank you.

**Comment by ErikEJ** [comment]
Great news, thanks for the update
