### ISSUE TITLE
EF Core 6 (Preview) Use Table and column names directly from database not working

### ISSUE THREAD

**Issue by KayakFisher205** [ErikEJ/EFCorePowerTools#1036]
When I run reverse engineering with it set the EF Core 6 (Preview), I have the check box for Use Table and column names directly from database not working checked, along with using Data Annotations.

### Steps to reproduce
After selecting EF Core 6, selecting the tables, and having Use Table and column names directly from database not working along with Use DataAnnotation attributes to configure the model checked, after selecting OK, I checked the list of tables. Tables that ended with "S" have the "S" dropped.

EF Core 5
![Screenshot 2021-06-30 070844](https://user-images.githubusercontent.com/71768711/123957943-11056f00-d972-11eb-8c44-8017831d9044.png)

EF Core 6
![Screenshot 2021-06-30 070857](https://user-images.githubusercontent.com/71768711/123957965-18c51380-d972-11eb-8cd8-eaa336205375.png)

### Further technical details
EF Core Power Tools version: 2.5.692.0

Database engine: (SQL Server)

Visual Studio version: Version 16.11.0 Preview 2.0

**Comment by ErikEJ** [comment]
Please provide a sample CREATE script and your eft.config.json file

**Comment by KayakFisher205** [comment]
[RequestedFiles.zip](https://github.com/ErikEJ/EFCorePowerTools/files/6741700/RequestedFiles.zip)
If you need anything else, let me know.
I've included the Top Level file, TT_MSP and one of the children, TT_ADDITIONS tables

**Comment by ErikEJ** [comment]
I attempted a fix in the latest daily build
