### ISSUE TITLE
ability to configure conversion from Table Datatype to C# DataType

### ISSUE THREAD

**Issue by nssidhu** [ErikEJ/EFCorePowerTools#1039]
I have geography type on my Table
When doing reverse engineering, it is converted to Geometry type.
Can it be configured to instead generate it as Point in C# code instead of Geometry ?

**Comment by ErikEJ** [comment]
Maybe exclude the column, and manually map it to a point in partial class.

**Comment by ErikEJ** [comment]
See some sample code here: https://github.com/ErikEJ/EFCorePowerTools/issues/572#issuecomment-725603917
