### ISSUE TITLE
Use new meta package

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#104]
https://blogs.msdn.microsoft.com/visualstudio/2018/10/10/simplify-extension-development-with-packagereference-and-the-vssdk-meta-package/

**Comment by Herdo** [comment]
> The VSSDK meta package is right now a prototype that we hope to make default in Visual Studio 2019.
I'm not sure if it's a good idea to include that now. Giving it a try cannot hurt, but I have some concerns with adding the prototype to the master branch.

**Comment by ErikEJ** [comment]
Agree, let us postpone

**Comment by ErikEJ** [comment]
YAGNI
