### ISSUE TITLE
New Option "No parameterless constructor"

### ISSUE THREAD

**Issue by DannySotzny** [ErikEJ/EFCorePowerTools#1040]
If I create the _DBContext_ from an existing database (I always do this after a change) then a StandardConstructor is created with parameters and without parameters. Whereas the one without parameter is not used. (Reverse Engineer)

But when using _AddDbContextPool_ ( [ms docs](https://docs.microsoft.com/en-us/ef/core/performance/advanced-performance-topics?tabs=with-constant#dbcontext-pooling) ) there must be only one constructor (with or without parameter).

It would be great if there was an option to not automatically generate the parameterless constructor. The error occurs unfortunately only at runtime

### Steps to reproduce
Use _AddDbContextPool_ instead of _AddDbContext_

Visual Studio version:  Visual Studio 2019 16.9 (latest)

**Comment by ErikEJ** [comment]
Duplicate of #991 - but a PR to fix this would be most welcome, given the increasing number of users hitting this.

**Comment by ErikEJ** [comment]
A sample PR for adding anew option: https://github.com/ErikEJ/EFCorePowerTools/pull/728/files

**Comment by ErikEJ** [comment]
Fixed in latest daily buidl: https://github.com/ErikEJ/EFCorePowerTools/commit/b85c77de011ecc8e7a714938d840cff6bef7e66a

**Comment by ErikEJ** [comment]
@0xced FYI!
