### ISSUE TITLE
Add SourceLink to all NuGet packages and publish

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#1045]
- [x] Dacpac
- [x] Dacpac 5
- [x] Dgml Builder
- [x] Dgml Builder 5
- [x] SqlQuery

see https://github.com/ErikEJ/EFCorePowerTools/commit/6b0769852cec09ebd9a34f91dda0f337622079a7

**Comment by ErikEJ** [comment]
alos added license info and bumped required nuget version

**Comment by MagicAndre1981** [comment]
Looks like you forgot the entry `<SymbolPackageFormat>snupkg</SymbolPackageFormat>` and the upload of the snupkg file. 
Or add 

```
<PropertyGroup>
 <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
 </PropertyGroup> 
```

to add pdbs directly to the package

**Comment by ErikEJ** [comment]
Looks like DebugType=embedded should work? https://devblogs.microsoft.com/dotnet/producing-packages-with-source-link/

**Comment by ErikEJ** [comment]
@MagicAndre1981  Which package and version are you looking at?

**Comment by MagicAndre1981** [comment]
whenever I get the nightly build update offered in VS2019 I check for last commits and just saw this.

Normally you need to provide the [PDBs with snupkg or added into the package](https://github.com/dotnet/sourcelink#using-source-link-in-net-projects).

**Comment by ErikEJ** [comment]
Not required with "embedded" !
