### ISSUE TITLE
1-to-1 Relationships

### ISSUE THREAD

**Issue by yomer** [ErikEJ/EFCorePowerTools#105]
Hi Erick,
    If I have a table(B) with a Foreign Key from table A, which happens to be unique. Is it possible for EFPower Tools to identify the relationship of both tables as 1-to-1 or do I have to set it manually?

### Steps to reproduce
Table A 
 IdA  AS INT  Primary
x
y

Table B
IdB AS INT Primary
IdA <- FK and Unique constraint
r
s

I was hoping for power tools to build the context class' modelbuilder with that relationship set to 1-to-1. Should that be possible, or am I doing something wrong?

Thanks

**Comment by ErikEJ** [comment]
Could you please share your CREATE TABLE script?

**Comment by yomer** [comment]
This is an example of a table which contains a  a Foreign Key (IdSolicitud), which is set as a UNIQUE constraint. Thanks.

CREATE TABLE [dbo].[AutPos_SolicitudValuacion](
	[IdSolicitudValuacion] [int] IDENTITY(1,1) NOT NULL,
	[IdSolicitud] [int] NOT NULL,
	[ReportesDirectos] [int] NULL,
	[ReportesIndirectos] [int] NULL,
	[FechaModificacion] [datetime] NOT NULL,
 CONSTRAINT [PK_AUTPOS_VALUACION] PRIMARY KEY CLUSTERED 
(
	[IdSolicitudValuacion] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [AK_AutPos_SolicitudValuacion] UNIQUE NONCLUSTERED 
(
	[IdSolicitud] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[AutPos_SolicitudValuacion]  WITH NOCHECK ADD  CONSTRAINT [AutPos_Valuacion_fk0] FOREIGN KEY([IdSolicitud])
REFERENCES [dbo].[AutPos_Solicitud] ([IdSolicitud])
GO

**Comment by yomer** [comment]
CREATE TABLE [dbo].[AutPos_Solicitud](
	[IdSolicitud] [int] IDENTITY(1,1) NOT NULL,
	[IdCat_TipoSolicitud] [int] NOT NULL,
	[IdCat_EstatusSolicitud] [int] NOT NULL,
	[IdEmpleadoElaborador] [int] NOT NULL,
	[Puesto] [nvarchar](100) NOT NULL,
	[IdPuesto] [int] NULL,
	[FechaCreacion] [datetime] NOT NULL,
	[FechaAutorizacion] [datetime] NULL,
	[FechaExportacion] [datetime] NULL,
	[FechaModificacion] [datetime] NOT NULL,
	[IdEmpleadoModificador] [int] NOT NULL,
 CONSTRAINT [PK_AUTPOS_SOLICITUD] PRIMARY KEY CLUSTERED 
(
	[IdSolicitud] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

**Comment by Herdo** [comment]
I tried what's described in the original question.

The short answer: yes, it is possible.*

The longer answer: yes, it is possible, but with the following limitations:
- It won't be a true 1-1 relationship, rather a 1-0..1 relationship
- Navigation properties will be created in both entities
- Only the entity with the FK will have the ID property of the other entity

**Comment by ErikEJ** [comment]
Closing, as this seems like a doc question: https://docs.microsoft.com/en-us/ef/core/modeling/relationships#one-to-one
