### ISSUE TITLE
Stored Procedure listing when reverse engineer is polluted...

### ISSUE THREAD

**Issue by GearTheWorld** [ErikEJ/EFCorePowerTools#1050]
### Describe what is not working as expected.
See a list of stored procedure related to diagram which will never be used and makes the list polluted somehow

### Steps to reproduce
Right click the project, do a REVERSE ENGINEER and expand the stored procedures / dbo 
A list of your stored procedures along with other stored procedures related to diagrams, see image below

![image](https://user-images.githubusercontent.com/8614008/126355424-651c8f2e-5ac5-4263-a679-f41a4788b755.png)

### Further technical details
EF Core Power tools version 2.5.692.0

### Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite)
Microsoft SQL Server 2019 (RTM-GDR) (KB4583458) - 15.0.2080.9 (X64)   Nov  6 2020 16:50:01   Copyright (C) 2019 Microsoft Corporation  Enterprise Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 19043: ) 

### Visual Studio version: (e.g. Visual Studio 2019 16.9)
Visual Studio 2019 Version 16.10.3

**Comment by ErikEJ** [comment]
Possible solutions https://stackoverflow.com/questions/1976248/how-do-i-list-all-non-system-stored-procedures

**Comment by GearTheWorld** [comment]
This is for SSMS, what about the tool?

**Comment by ErikEJ** [comment]
I am just investigating a fix for now.

**Comment by ErikEJ** [comment]
Can you check that this query excludes the diagram stored procedures:

```
SELECT
    ROUTINE_SCHEMA,
    ROUTINE_NAME,
    ROUTINE_TYPE,
    CAST(CASE WHEN (ROUTINE_TYPE = 'FUNCTION' AND DATA_TYPE != 'TABLE') THEN 1 ELSE 0 END AS bit) AS IS_SCALAR
FROM INFORMATION_SCHEMA.ROUTINES
WHERE NULLIF(ROUTINE_NAME, '') IS NOT NULL
AND OBJECTPROPERTY(OBJECT_ID(ROUTINE_NAME), 'IsMSShipped') = 0
and (
            select 
                major_id 
            from 
                sys.extended_properties 
            where 
                major_id = object_id(ROUTINE_NAME) and 
                minor_id = 0 and 
                class = 1 and 
                name = N'microsoft_database_tools_support'
        ) is null 
 
```

**Comment by GearTheWorld** [comment]
It indeed does an excellent job!

**Comment by ErikEJ** [comment]
Fixed in latest daily build, please try it out and let me know.

Latest daily also let's you scaffold only stored procedures, btw.

**Comment by ErikEJ** [comment]
Thanks for the review!
