### ISSUE TITLE
efpt.config.json UiHint relative path to .sqlproj

### ISSUE THREAD

**Issue by spaasis** [ErikEJ/EFCorePowerTools#1052]
Hi and thank you for the awesome tool!

As we're including the efpt config files in git, I was wondering if the database project reference could be defined with a relative path. Currently the path is absolute, meaning that different developers need to change the reference frequently, which causes (a tiny amount) of extra work.

### Steps to reproduce
Solution folder structure:

```
Solution
--APIS
  --API 
    --API.csproj //this is where I'm reverse engineering the model
--Database
  --Database.sqlproj
```

1. Reverse engineer based on a database project
2. The generated efpt.config.json has the absolute .sqlproj path: `"UiHint": "D:\\Users\\User\\Solution\\Database\\Database.sqlproj",` 
3. Attempt to change the path to relative: `"UiHint": "..\\..\\Database\\Database.sqlproj",`
4. Open the Reverse Engineer dialog again - database project selection is empty
5. On a new Reverse Engineer run, the UiHint will be reset back to the absolute path

### Further technical details
EF Core Power Tools version: 2.5.692.0
Database engine: SQL Server
Visual Studio version: Visual Studio 2019 16.9

**Comment by ErikEJ** [comment]
Great idea!

**Comment by ErikEJ** [comment]
I have attempted to implement in the latest daily, would be grateful if you could verify?

**Comment by spaasis** [comment]
That was quick!
Works like a charm. Thanks :)

**Comment by ErikEJ** [comment]
If you like me free tools, I would be grateful for a review on VS Marketplace!

**Comment by spaasis** [comment]
Done, 5/5 for your spectacular work :)

**Comment by ErikEJ** [comment]
Thanks a lot!
