### ISSUE TITLE
Renaming feature does not work if "Use Database Names" is selected

### ISSUE THREAD

**Issue by conficient** [ErikEJ/EFCorePowerTools#1053]
I'm trying this excellent tool for the first time. It's certainly much easier that accepting what `dotnet ef scaffold` decides you get !

I'm moving from a LINQ-to-SQL (L2S) model in .NET Framework, so I'm trying to keep things the same where possible so upgrading to .NET Core is easier.

So in general I want to use 'Use database names' (which is how L2S works mostly) but there are some fields I need to rename. I tried the `efpt.renaming.json` but it only appears to apply if we don't use the database names. I assume this is intended behaviour? Would it be possible to use the rename with the database name option?

### Further technical details
EF Core Power Tools version: 2.5.692

Database engine: SQL Server

Visual Studio version: Visual Studio 2019 16.10.4

**Comment by ErikEJ** [comment]
I think it depends on the EF Core version you target...

**Comment by ErikEJ** [comment]
Ping?

**Comment by conficient** [comment]
I tried both EF5 and EF6 both seemed to ignore the rename file

**Comment by ErikEJ** [comment]
I need a repro in order to investigate, at least a CREATE table script, and the expected/desired outcome

**Comment by conficient** [comment]
OK I created a new .NET Core 5 console app, added EF Core 5.0.8 libraries and pointed the EF PowerTools at a Northwind database. I imported just the customers table, settings as follows:
![image](https://user-images.githubusercontent.com/454494/126863543-48a6d4e9-0933-4d06-9ace-21f173aef91a.png)
Full efpt.config.json is:
```json
{
   "CodeGenerationMode": 0,
   "ContextClassName": "NorthwindContext",
   "ContextNamespace": "ScaffoldTest",
   "DefaultDacpacSchema": null,
   "FilterSchemas": false,
   "IncludeConnectionString": false,
   "ModelNamespace": "ScaffoldTest",
   "OutputContextPath": "Context",
   "OutputPath": "Tables",
   "ProjectRootNamespace": "ScaffoldTest",
   "Schemas": null,
   "SelectedHandlebarsLanguage": 0,
   "SelectedToBeGenerated": 0,
   "Tables": [
      {
         "Name": "[dbo].[Customers]",
         "ObjectType": 0
      }
   ],
   "UiHint": "SVR3.Northwind",
   "UseBoolPropertiesWithoutDefaultSql": false,
   "UseDatabaseNames": true,
   "UseDbContextSplitting": false,
   "UseFluentApiOnly": true,
   "UseHandleBars": false,
   "UseInflector": true,
   "UseLegacyPluralizer": false,
   "UseNoConstructor": false,
   "UseNoNavigations": false,
   "UseNoObjectFilter": false,
   "UseNodaTime": false,
   "UseNullableReferences": false,
   "UseSchemaFolders": false,
   "UseSpatial": false
}
```
The rename file is 
```json
[
   {
      "SchemaName": "dbo",
      "Tables": [
         {
            "Columns": [
               {
                  "Name": "ContactName",
                  "NewName": "PersonName"
               },
               {
                  "Name": "ContactTitle",
                  "NewName": "PersonTitle"
               }
            ],
            "Name": "Customers",
            "NewName": "Customers"
         }
      ],
      "UseSchemaName": false
   }
]
```
It generates the schema with no renames:
```c#
    public partial class Customer
    {
        public string CustomerID { get; set; }
        public string CompanyName { get; set; }
        public string ContactName { get; set; }
        public string ContactTitle { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Region { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
    }
```
I also updated the project to .NET 6 and the EF Core libraries to the current 6 preview versions, got the same result.

The rename only works if I turn off the "Use table and column names directly from the database".

**Comment by ErikEJ** [comment]
>> The rename only works if I turn off the "Use table and column names directly from the database".

Yes, I am able to repro, this looks like it is by design.

**Comment by conficient** [comment]
Ok so no easy way to fix.. thanks for your help

**Comment by ErikEJ** [comment]
No, and I think it makes sense to be by design.
