### ISSUE TITLE
Pluralizer is used even though not selected

### ISSUE THREAD

**Issue by tfq-git** [ErikEJ/EFCorePowerTools#1060]
I was using .net core 3.1 and EF Core Power Tools V2.4.217 in VS2019 Community Edition. I generated models from database with reverse engineer, did not use the singularize/pluralize option so that database table names remain as it is. It worked perfectly for me. If I have 2 tables with names Bill and DefaultValues the below code in generated.

public virtual DbSet<Bill> Bill { get; set; }
public virtual DbSet<DefaultValues> DefaultValues { get; set; }

Recently upgraded to .net 6 and used EF Core Power Tools in VS2022 Community, generated the same but now POCO class is singularized and navigations are pluralized even though I did not select the option to use pluralizer, just as before.

public virtual DbSet<Bill> Bills { get; set; }
public virtual DbSet<DefaultValue> DefaultValues { get; set; }

Is there a way to make the reverse engineer behave like before?

### Further technical details
EF Core Power Tools version: 2.5.692
Database engine: Microsoft SQL Server 2014

Visual Studio version: Microsoft Visual Studio Community 2022 Preview (64-bit) Version 17.0.0 Preview 2.1

**Comment by ErikEJ** [comment]
Please share your efpt.config.json file.

Is that file under source control?

**Comment by tfq-git** [comment]
Thanks for fast response.

Yes, efpt.config.json is under source control. I never tweaked that file though. Below is the content of that file(removed some table names because they are too many, hope that won't be a problem):

`
{
   "CodeGenerationMode": 2,
   "ContextClassName": "URMSContext",
   "ContextNamespace": null,
   "DefaultDacpacSchema": null,
   "FilterSchemas": false,
   "IncludeConnectionString": false,
   "ModelNamespace": "Models.URMS",
   "OutputContextPath": null,
   "OutputPath": "Models\\URMS",
   "ProjectRootNamespace": "ICMS.DAL",
   "Schemas": null,
   "SelectedHandlebarsLanguage": 0,
   "SelectedToBeGenerated": 0,
   "Tables": [
      {
         "Name": "[dbo].[Bill]",
         "ObjectType": 0
      },
      {
         "Name": "[dbo].[DefaultValues]",
         "ObjectType": 0
      }
   ],
   "UiHint": "LAPTOP-71CQ53K2\\TFQDEFAULT.URMS",
   "UseBoolPropertiesWithoutDefaultSql": false,
   "UseDatabaseNames": true,
   "UseDbContextSplitting": false,
   "UseFluentApiOnly": false,
   "UseHandleBars": false,
   "UseInflector": false,
   "UseLegacyPluralizer": false,
   "UseNoConstructor": false,
   "UseNoNavigations": false,
   "UseNoObjectFilter": false,
   "UseNodaTime": false,
   "UseNullableReferences": false,
   "UseSchemaFolders": false,
   "UseSpatial": false
}
`

**Comment by ErikEJ** [comment]
Please provide the create table statements for the tables in question - from the correct database.

I cannot see anything obvious.

**Comment by tfq-git** [comment]
Here are the create commands for the tables generated by SQL Server

`/****** Object:  Table [dbo].[Bill]    Script Date: 7/28/2021 3:03:26 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Bill](
	[BillID] [nvarchar](50) NULL,
	[BillDate] [datetime] NULL,
	[InvoiceID] [nvarchar](50) NULL,
	[SupplierID] [nvarchar](20) NULL,
	[TotalAmount] [money] NULL,
	[Discount] [money] NULL
) ON [PRIMARY]

GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[DefaultValues](
	[FieldId] [char](10) NOT NULL,
	[Value1] [nvarchar](200) NULL,
	[Value2] [nvarchar](200) NULL,
	[Value3] [nvarchar](200) NULL,
	[Value4] [nvarchar](200) NULL,
	[Value5] [nvarchar](200) NULL,
 CONSTRAINT [PK_DefaultValues] PRIMARY KEY CLUSTERED 
(
	[FieldId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


`

**Comment by ErikEJ** [comment]
Have you tried the latest daily build?

There were some missing pieces in EF Core 6 support.

**Comment by georgeemr** [comment]
This is happening to me if I choose EF Core 6 (preview) The tables get pluralized. If I choose EF Core 5 everything works fine.

Visual Studio 2022 17 Preview 2.1

I get:
 public virtual DbSet<Decision> Decisions { get; set; }
Instead of:
 public virtual DbSet<Decision> Decision { get; set; }

**Comment by tfq-git** [comment]
Tried Power Tools latest daily build(2.5.718) with Visual Studio Community 2019 Version 16.10.4 and it works fine.

In VS2022, it said 'The package did not load correctly'(#1046 ). This error message was showing in my previous VS2022 but after updating VS it went away for some time. Now it came back again, so could not test the latest build in VS2022.

**Comment by ErikEJ** [comment]
@georgeemr Fixed in latest daily.
