### ISSUE TITLE
efpt.config.json with all the imported databases

### ISSUE THREAD

**Issue by georgeemr** [ErikEJ/EFCorePowerTools#1061]
I see that in the efpt.config.json the EFCorePowerTools saves the info of the last imported database so the reverse engineer knows what was selected to import the database.
Would be wonderful if in that JSON you can save all the imported databases. Currently, I have 4 databases, and when I want to refresh one database I have to check everything I import (Tables, Functions, Stores, Views) and then update the current folder.

![image](https://user-images.githubusercontent.com/3822009/127559262-f70b7103-a058-4565-9e52-6d1b0c66f767.png)

![image](https://user-images.githubusercontent.com/3822009/127559468-5396b702-e650-406b-aa6a-d4492d4725a3.png)

**Comment by ErikEJ** [comment]
Is it [this feature](https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#using-multiple-dbcontexts-in-the-same-project) you are looking for?

**Comment by ErikEJ** [comment]
Assuming it is, feel free to re-open if not.

**Comment by georgeemr** [comment]
It is. Thank you.
