### ISSUE TITLE
Other DbContext, Entities and configurations get deleted on creation of new DbContext

### ISSUE THREAD

**Issue by AndreErb** [ErikEJ/EFCorePowerTools#1062]
I have a DbContext, Entities and configurations created with EFCorePowerTools.
When I try to create another DbContext, Entities and configurations for another DB on the same Server, the formerly created DbContext, Entities and configurations get deleted. 

It even deletes the folders (namespaces) in which the first context and stuff was created in. I don't know where it knows them from, since I had deleted the "efpt.config.json" before trying to create a new context.

I tried to remove the "efpt.config.json" before creating a new one => Same result
I tried to remove all the DB connections before creating a new one => Same result

The only solution I came up with, was to add a new project to my solution and create the second context and stuff there.

### Further technical details
EF Core Power Tools version: 2.5.692

Database engine: SQL Server

Visual Studio version: Visual Studio 2019 16.10.4

**Comment by ErikEJ** [comment]
Or create the second one on a separate folder?

**Comment by AndreErb** [comment]
That's what I tried, too. Without success. 

In the creation dialog I tried to use different namespaces (which result in project folders) for the Entities and the DbContext. However, even then it deleted the original folders ("DAL", "DAL.Entities"). As I said, I have no clue why it knew about these folders and file, especially as I had deleted the "efpt.config.json" file and restarted VS, before I tried to create the new context.

**Comment by ErikEJ** [comment]
Have you tried a project folder per DbContext (nothing in the root).

I am guessing the feature to clean up insured files kicks in.

**Comment by AndreErb** [comment]
This is my original project structure with the first DBContext
![image](https://user-images.githubusercontent.com/11599017/127655788-802341e2-7ef1-4573-b881-912658abfb8f.png)

Creating a new Context and Entities without specifiying Namespaces/paths removes the DAL folder and anything from before
and the new stuff is created in the root
![image](https://user-images.githubusercontent.com/11599017/127657170-05e0d90d-6350-4ac7-838b-33cc47af09e1.png)
![image](https://user-images.githubusercontent.com/11599017/127657509-9d05aca3-20cd-4953-b340-5f2bd35e15a4.png)

In contrast if I give everything a new path/namespace like "DAL2" and "Entities2" then the new stuff gets created without deleting anything.

**Comment by ErikEJ** [comment]
It is by design, as the cleanup code considers all files below the DbContext to belong to that DbContext.

As mentioned, put each DbContext in a folder on its own.

You can also avoid this by removing the autogenerated header line from each file.

You are the first user reporting this as an issue, so reluctant to introduce special casing as there are numerous ways to work around this.

**Comment by AndreErb** [comment]
Ok, I see.
Thank you for your help and feedback.

**Comment by ErikEJ** [comment]
I have implemented a fix in the latest daily build, would be grateful if you can verify - thanks for reporting this.

**Comment by AndreErb** [comment]
> I have implemented a fix in the latest daily build, would be grateful if you can verify - thanks for reporting this.

@ErikEJ Looks good!
Version 2.5.721 with https://github.com/ErikEJ/EFCorePowerTools/pull/1063 seems to fix it!

Great job and tool!
Thanks again!

**Comment by ErikEJ** [comment]
Thanks. If you like my free tools, I would be grateful for a review on VS Marketplace.
