### ISSUE TITLE
SQL Server nvarchar not mapping in vstudio

### ISSUE THREAD

**Issue by redhattori** [ErikEJ/EFCorePowerTools#1065]
### Further technical details
EF Core Power Tools version: 2.5.692

Database engine: SQL Server

Visual Studio version: Microsoft Visual Studio Community 2019
Version 16.10.4

Hello,

I'm trying to reverse engineer a table and every column that is nvarchar is not being mapped on the model builder in the generated db context. Is this an issue not covered by your tool or is that a setting that we can configure?

Thank you, 
Waiting for your feedback.

 protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.Entity<DummyTable>(entity =>
            {
                entity.Property(e => e.C1).IsFixedLength(true);

                // C2 columns which is nvarchar(50) is not being mapped

                entity.Property(e => e.C3).IsFixedLength(true);
            });

            OnModelCreatingPartial(modelBuilder);
        }

**Comment by ErikEJ** [comment]
Only mappings that are different from convention are created.

Can you share the CREATE TABLE statement?

**Comment by redhattori** [comment]
We noticed that nvarchar is not recognized in any database that we tested. As soon as we changed the c2 column from nchar to nvarchar, it wasn't being mapped anymore. Here is the script for context.

Thank you.

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DummyTable](
	[c1] [nchar](10) NOT NULL,
	[c2] [nvarchar](50) NOT NULL,
	[c3] [nchar](10) NOT NULL
) ON [PRIMARY]
GO
