### ISSUE TITLE
Using Data Annotations still generates Fluent API code

### ISSUE THREAD

**Issue by airwedge123** [ErikEJ/EFCorePowerTools#1066]
Describe what is not working as expected.
When you select "Use DataAnnotation attributes to configure the model" You would expect the fluent API code in OnModelCreating to be removed / substantially reduced.  However, the code remains the same just as when you do not select Use DataAnnotations. Anything configured with Fluent API will override DataAnnotations.  There is some situations that cannot be done with Annotations that may still need to be in the Fluent API section.

### Steps to reproduce
select "Use DataAnnotation attributes to configure the model"

### Further technical details
EF Core Power Tools version: 2.5.692

Database engine: SQL Server

Visual Studio version:16.10.2

**Comment by ErikEJ** [comment]
Which EF Core version do you target?

**Comment by ErikEJ** [comment]
Can you provide a simple repro (CREATE TABLE, efpt.config.json, results with about Data Annotations.

**Comment by airwedge123** [comment]
Sure: https://github.com/airwedge123/FooBar.git. There is a
CreateDatabase.sql file.

Ef Core 5.

In the sample repo, the below overrides what is defined in data annotations
/ is redundant.

                entity.HasOne(d => d.Foo)
                    .WithMany(p => p.Bar)
                    .HasForeignKey(d => d.FooId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Bar_Foo");

**Comment by ErikEJ** [comment]
It is by design, the available data Annotations are limited.

Gets better in EF Core 6.
