### ISSUE TITLE
Feature Request: add base-class / interface for inheritance / POCO

### ISSUE THREAD

**Issue by karli1** [ErikEJ/EFCorePowerTools#1068]
I use the powertools to generate POCO classes for RepoDB. However, some columns are in almost all tables present (e.g. creator of a record), some in a few (e.g. if the row is deleted (aka softdelete)). To create a generic repository, an easy solution would be the usage of various base classes (e.g. defaultEntity, deletableEntity...etc.), which share common columns. 

My request: in the json file, we find already the table names, the excluded columns, now, it would be great if we can add there also a base class / interface for each table (which becomes a POCO).

**Comment by ErikEJ** [comment]
Maybe you can use the Handlebars templates?

**Comment by karli1** [comment]
Had the same thoughts, however failed :) Need to look at the cols/properties first, and if there is e.g. the column "isDeleted" then use the base class "deletableEntity"... etc.

**Comment by ErikEJ** [comment]
I think it is not possible then (using Handlebars).

Maybe a partial class for each Poco, where you inherit the Interface - only needs to be done once, and can survive regeneration.

**Comment by karli1** [comment]
Yes, that is what I did now. Therefore the feature req. :) If the tool supports it (e.g. via JSON) than you don't have to generate the extra partial class.

**Comment by ErikEJ** [comment]
Do you have a proposal for how to proceed?

**Comment by karli1** [comment]
Lets say you have currently this:

```
{
         "ExcludedColumns": [
            "removed",
            "created_at",
            "created_by",
            "modified_at",
            "modified_by"
         ],
         "Name": "[dbo].[changeReason]",
         "ObjectType": 0
      }

```
I would add "DeriveFrom" as an additional property, could be (very simple) just a text-property, which will be used in the handlebars as a field.

**Comment by ErikEJ** [comment]
The solution would not be using Handlebars, there is not interaction on this level. But I understand your suggestion.

@sm15455 Thoughts?

**Comment by ErikEJ** [comment]
@mikependon Any suggestions? (RepoDB wasmentioned) :-)

**Comment by mikependon** [comment]
@ErikEJ - this is a scenario in which a common generator tool like EF Power Tools could not understand (most likely) unless of course you intentionally support it. This would somehow add more complexities if you do everything on the tool itself, specially that this tool is widely used in EF (over micro-ORMs like Dapper and RepoDB).

In my opinion, to support the case above and to limit the changes if possible, there should be at-least a field where you can define a base class.

For my recommendation, you should just keep it simple. Below, I choose which tables and fields.

![image](https://user-images.githubusercontent.com/591015/128769767-0f0a04e1-5f0a-47af-962c-8d96ad2f540e.png)

On the next screen, just give me that base class field to fill-in manually.

![image](https://user-images.githubusercontent.com/591015/128770593-eea8a1e8-6e1d-4385-8f7c-0b39628d2e9f.png)

And if I have multiple base classes, I will redo the steps for the target tables.

Thanks for tagging me here.

**Comment by ErikEJ** [comment]
Maybe #1070 will enable this?

**Comment by ErikEJ** [comment]
Closing in favor of #1070
