### ISSUE TITLE
For reverse engineered procedures, it's not possible to set an initial value for an out parameter

### ISSUE THREAD

**Issue by HimbeersaftLP** [ErikEJ/EFCorePowerTools#1069]
SQL Server procedures allow the executor to define an initial value for parameters declared as "OUTPUT".

The method generated by EF Core Power Tools' reverse engineering feature however, has the direction of the SqlParameter hardcoded to Output (as opposed to InputOutput).

https://github.com/ErikEJ/EFCorePowerTools/blob/380e02a197e49ea7068a0889bd1294a6ea1a0635/src/GUI/RevEng.Core/Procedures/SqlServerStoredProcedureScaffolder.cs#L334

### Steps to reproduce
1. Create a procedure that uses the value of one of its OUTPUT parameters.
2. Use EF Core power Tools to generate the models
3. You will notice, that you cannot provide an input value to the parameter

### Further technical details
EF Core Power Tools version: 2.5.692

Database engine: SQL Server

Visual Studio version: Visual Studio 2019 16.10.4

**Comment by ErikEJ** [comment]
Please provide a full repro using for example Northwind, and I will have a look

**Comment by ErikEJ** [comment]
Are you proposing it should be always "InputOutput" ?

**Comment by ErikEJ** [comment]
Ping?

**Comment by HimbeersaftLP** [comment]
> Are you proposing it should be always "InputOutput" ?

I am not sure about the backwards compatibility of that (also is there a possible performance impact?). On the other hand, I also have no idea if there is another way to decide which one to use, short of making it a global option.

> Please provide a full repro using for example Northwind, and I will have a look

I'll try to as soon as I can, if that is still needed.

Sorry for the late response.

**Comment by ErikEJ** [comment]
Does everything work as expected if you change all Output parameters to Input output?

**Comment by ErikEJ** [comment]
No need for repro - I will try to make it always InputOutput for now, and if issues arise, make a global switch to revert to current implementation.

**Comment by ErikEJ** [comment]
Thanks, I also looked at a tool similar to mine, and it maps all non input parameters as input/output, so I will just change to that.

**Comment by ErikEJ** [comment]
Thanks for reporting this!

**Comment by ErikEJ** [comment]
Fixed in latest daily

**Comment by HimbeersaftLP** [comment]
Thanks ♥️

**Comment by ErikEJ** [comment]
@HimbeersaftLP If you would like this fixed, please provide a repro so I can understand the issue better.
