### ISSUE TITLE
Support Per Config Handlebars Templates

### ISSUE THREAD

**Issue by ebeltran1981** [ErikEJ/EFCorePowerTools#1070]
We use multiple contexts that need different customizations (imports, base context, etc...), the tools seems to use only one templates per project.

![image](https://user-images.githubusercontent.com/1435275/129047277-d66e7fd3-f3f7-4178-b6b8-d66702f5404e.png)

Is it possible to support templates per config? or maybe this is already supported.

### Steps to reproduce
1. Add 2 different config files: efpt.context1.config.json and efpt.context2.config.json
2. From context 1 select the option to use handlebars templates
3. context 2 will reuse the templates from context 1

### Further technical details
EF Core Power Tools version: 2.5.692.0

Database engine: SQL Server

Visual Studio version: 2019.16.10.4

**Comment by ErikEJ** [comment]
Sure, I general it is probably an anti-pattern to have multiple Dbcontext in a single project.

But a CodeTemplates folder per config is probably a reasonable solution.

@tonysneed Is this possible?

**Comment by tonysneed** [comment]
My extension works at the assembly or project level. You can generate as many DbContexts as you want by pointing the tool at different databases. Or by running it from the command line with different parameters.

**Comment by ErikEJ** [comment]
@tonysneed Thanks, can you also specify the root folder for the templates?

**Comment by tonysneed** [comment]
AFAIK, templates folder needs to be at the project root.

**Comment by ebeltran1981** [comment]
> AFAIK, templates folder needs to be at the project root.

Thanks for confirming... is it possible to enable an option that let you use it *relative* to the config file?

My use case needs the template to use a diff dbcontext:
- `public class MyContext1 : SomeBaseContext1 {}` <-- this will use the templates from efpt.context1.config inside MyContext1 folder
- `public class MyContext2 : SomeBaseContext2 {}` <-- this will use the templates from efpt.context2.config inside MyContext2 folder

Something similar to this:
![image](https://user-images.githubusercontent.com/1435275/129194373-25ef97df-ebff-464d-96e3-5a4fd659a528.png)

**Comment by ErikEJ** [comment]
Let me have a closer look!

**Comment by ErikEJ** [comment]
@tonysneed Does this not provide the ability to use templates from another location: https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/RevEng.Core/ServiceProviderBuilder.cs#L83 ?

**Comment by tonysneed** [comment]
This should work.

**Comment by ErikEJ** [comment]
@ebeltran1981 Would a CodeTemplates folder relative to the efpt.config.json file fit the bill?

**Comment by ebeltran1981** [comment]
@ErikEJ: yes it would.
