### ISSUE TITLE
System.Exception: Table list error:  Unhandled exception. System.BadImageFormatException: Could not load file or assembly '---\Temp\efreveng5.2.5.692.0\efreveng50.dll'. 

### ISSUE THREAD

**Issue by plafourca004** [ErikEJ/EFCorePowerTools#1071]
When trying to start a reverse engineering, after connecting to the DB, I get this output error message:

```
System.Exception: Table list error: 
Unhandled exception. System.BadImageFormatException: Could not load file or assembly 'C:\pathToAppdata\Local\Temp\efreveng5.2.5.692.0\efreveng50.dll'. Tentative de chargement d'un programme de format incorrect.
File name: 'C:\pathToAppdata\Local\Temp\efreveng5.2.5.692.0\efreveng50.dll'
-	at List<TableModel> EFCorePowerTools.Handlers.ReverseEngineer.ResultDeserializer.BuildTableResult(string output)
at async Task<List<TableModel>> EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.GetTablesInternalAsync(string arguments)
at async Task<List<TableModel>> EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.GetTablesAsync(string connectionString, DatabaseType databaseType, SchemaInfo[] schemas)
at async Task<List<TableModel>> EFCorePowerTools.Handlers.ReverseEngineer.TableListBuilder.GetTableDefinitionsAsync(CodeGenerationMode codeGenerationMode)
at async Task<List<TableModel>> EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.GetTablesAsync(DatabaseConnectionModel dbInfo, CodeGenerationMode codeGenerationMode, SchemaInfo[] schemas)
at async Task<bool> EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.LoadDataBaseObjectsAsync(ReverseEngineerOptions options, DatabaseConnectionModel dbInfo, Tuple<List<Schema>, string> namingOptionsAndPath)
at async Task EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.ReverseEngineerCodeFirstAsync(Project project, string optionsPath, bool onlyGenerate)

```

"Tentative de chargement d'un programme de format incorrect." meaning Attempt to load a wrongly formatted program

I have tried to empty the temp folder and to reinstall the extension but nothing seems to work

### Steps to reproduce
This is where the main problem is, I have tested to do it on another computer and I don't get the same error.

### Further technical details
EF Core Power Tools version: 2.5.692.0

Database engine: SQL Server

Visual Studio version:
Microsoft Visual Studio Professional 2019
Version 16.9.4

**Comment by ErikEJ** [comment]
Do you have the .net Core 3.1 runtime installed?

Run: dotnet --list-runtimes

**Comment by plafourca004** [comment]
I think so,
![MicrosoftTeams-image](https://user-images.githubusercontent.com/57951515/129337069-86ac01f6-201e-4bcb-a316-04523558598d.png)

**Comment by plafourca004** [comment]
I realized that on the computer where I have the problem, the path to efreveng50.dll has a dot in it.
'C:\Users\xxxxxxxx.xxxxxxx\AppData\Local\Temp\efreveng5.2.5.692.0\efreveng50.dll'
It's not the case on the computer where everything works. I know this can sometimes cause bugs, could this be related ?

**Comment by ErikEJ** [comment]
That listing only shows the x86 runtime..

**Comment by ErikEJ** [comment]
Also, check your path, that it lists the x64 runtime first

**Comment by plafourca004** [comment]
> That listing only shows the x86 runtime..

On the computer on which it works, It only shows the ones not in x86.

**Comment by plafourca004** [comment]
> Also, check your path, that it lists the x64 runtime first

I'm not a big windows user, when you talk about the path, are you talking about the path environment variable ?
If so, the only version in this variable is .net 4

also, I'm using ef core 5

**Comment by ErikEJ** [comment]
Yes, the PATH environment variable, it points to the folder where dotnet.exe is located.

**Comment by ErikEJ** [comment]
You could also try removing/renaming the  efreveng5.2.5.692.0 folder

**Comment by plafourca004** [comment]
> You could also try removing/renaming the efreveng5.2.5.692.0 folder

I already did this.

> Yes, the PATH environment variable, it points to the folder where dotnet.exe is located.

I checked it and yes, the x86 is first. So it might be the cause of the problem. But I don't really want to change the PATH and the order of it because this is not really my pc and a lot of others projects/applications are on this computer. Just changing this order will probably cause a lot of errors elsewhere. 
Do you know any workaround ?

Thanks for your help and sorry for the slow replies.

**Comment by ErikEJ** [comment]
No, I do not know of any workaround, other than temporarily changing the path.
