### ISSUE TITLE
Reverse Engineering: C# reserved keywords in property in SP result class

### ISSUE THREAD

**Issue by viewable** [ErikEJ/EFCorePowerTools#1073]
Classes are generated with C# reserved keywords as property names when stored procedure (SP) returns a dataset with columns named C# reserved keywords.

### Steps to reproduce
Source SP

```sql
CREATE PROCEDURE [dbo].[GET_DATASET]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT TOP 1 
		*
	FROM 
		msdb..sysssislog 
END
GO
```

Generated code

```c#
public partial class GET_DATASETResult
{
    public int id { get; set; }
    public string event { get; set; }
    public string computer { get; set; }
    public string operator { get; set; }
    public string source { get; set; }
    public Guid sourceid { get; set; }
    public Guid executionid { get; set; }
    public DateTime starttime { get; set; }
    public DateTime endtime { get; set; }
    public int datacode { get; set; }
    public byte[] databytes { get; set; }
    public string message { get; set; }
}
```
`event` and `operator` are C# reserved keywords, but are also the column names of the `msdb..sysssislog` table. Thus generated code is a syntax error.

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/

https://docs.microsoft.com/en-us/sql/relational-databases/system-tables/sysssislog-transact-sql

Maybe it's worth forcing `[Column("foobar")]` attributes for properties whose names are C# reserved keywords (especially since renaming doesn't apply to SP results)?

### Further technical details
EF Core Power Tools version: 2.5.692

Database engine: SQL Server

Visual Studio version: Visual Studio 2019 latest

**Comment by viewable** [comment]
This also applies to things like SQL functions/SPs and their input params - can named C# reserved keywords.

e.g.

SP
```sql
CREATE FUNCTION [dbo].[FUNCTION_EXAMPLE]
(
	@string varchar(16),
	@base int
)
RETURNS varchar(16)
AS
BEGIN

	RETURN 'foobar'

END
```

Generated code
```c#
public static string FUNCTION_EXAMPLE(string string, int base)
{
    /**/
}
```

**Comment by ErikEJ** [comment]
Thanks, looks like the correct solution would  be to create a lookup table of all reserved keywords, and then prepend any with "@".

https://stackoverflow.com/questions/4877713/how-to-check-that-a-string-isnt-a-keyword-or-type-in-c-sharp

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/

**Comment by ErikEJ** [comment]
Notice that there is already code in place to catch non-identifiers, but it passes through all keywords:
https://github.com/ErikEJ/EFCorePowerTools/blob/36f96e62853053b23f3bfade4fb265f2edcd2540/src/GUI/RevEng.Core/Routines/SqlServerRoutineScaffolder.cs#L195

**Comment by ErikEJ** [comment]
Thanks for reporting this, I attempted a fix in the latest daily build
