### ISSUE TITLE
Stored Procedure Use with Azure Managed Identities DB Connection

### ISSUE THREAD

**Issue by nholt-isd** [ErikEJ/EFCorePowerTools#1077]
Is there any way to use Stored Procedures when using a Managed Identities connection between an Azure App Service and Azure SQL?

We have a project that uses the Managed Identity for the App Service to connect to the Azure SQL Database. Through DI we have a DB Interceptor that will retrieve the token when targeting an azure database and the user for the connection is not present. Everything has worked fine until we attempted to use a Stored Procedure through the DB Context. The error being returned is stating it can't find a `blank` user name rather than using our interceptor to grab the access token when we deploy to the Azure App. 

![image](https://user-images.githubusercontent.com/53229870/129916228-220cd28c-4010-4d0d-a5db-036785d8c4d3.png)

From what I can tell, the access token is lost when the database connection is duplicated/copied to execute the Stored Procedure in the `DbContextExtensions.cs`. 

### Here are some code samples for our DI and Interceptor:

Code for database DI:
```
services.AddDbContext<DataAccess.Data.Models.NintexContext>(options =>
{
    options.UseSqlServer(Configuration.GetConnectionString("DbConnectionString"));
    options.AddInterceptors(new Application.Infrastructure.AzureAdAuthenticationDbConnectionInterceptor());
});
```

Interceptor Code:
```
public class AzureAdAuthenticationDbConnectionInterceptor : DbConnectionInterceptor
    {
        // See https://docs.microsoft.com/azure/active-directory/managed-identities-azure-resources/services-support-managed-identities#azure-sql
        private static readonly string[] _azureSqlScopes = new[]
        {
            "https://database.windows.net//.default"
        };

        private static readonly TokenCredential _credential = new ChainedTokenCredential(
            new ManagedIdentityCredential(),
            new EnvironmentCredential());

        public override InterceptionResult ConnectionOpening(
            DbConnection connection,
            ConnectionEventData eventData,
            InterceptionResult result)
        {
            var sqlConnection = (SqlConnection)connection;
            if (DoesConnectionNeedAccessToken(sqlConnection))
            {
                var tokenRequestContext = new TokenRequestContext(_azureSqlScopes);
                var token = _credential.GetToken(tokenRequestContext, default);

                sqlConnection.AccessToken = token.Token;
            }

            return base.ConnectionOpening(connection, eventData, result);
        }

        public override async ValueTask<InterceptionResult> ConnectionOpeningAsync(
            DbConnection connection,
            ConnectionEventData eventData,
            InterceptionResult result,
            CancellationToken cancellationToken = default)
        {
            var sqlConnection = (SqlConnection)connection;
            if (DoesConnectionNeedAccessToken(sqlConnection))
            {
                var tokenRequestContext = new TokenRequestContext(_azureSqlScopes);
                var token = await _credential.GetTokenAsync(tokenRequestContext, cancellationToken);

                sqlConnection.AccessToken = token.Token;
            }

            return await base.ConnectionOpeningAsync(connection, eventData, result, cancellationToken);
        }

        private static bool DoesConnectionNeedAccessToken(SqlConnection connection)
        {
            //
            // Only try to get a token from AAD if
            //  - We connect to an Azure SQL instance; and
            //  - The connection doesn't specify a username.
            //
            var connectionStringBuilder = new SqlConnectionStringBuilder(connection.ConnectionString);

            return connectionStringBuilder.DataSource.Contains("database.windows.net", StringComparison.OrdinalIgnoreCase) && string.IsNullOrEmpty(connectionStringBuilder.UserID);
        }
    }
```

### Steps to reproduce
1. Have an Azure App connecting to an Azure SQL DB via Managed Identity
2. Add a Stored Procedure and Create the DBContext via EF Core Power Tools
3. Deploy and Run the app to call the Stored Procedure

### Further technical details
EF Core Power Tools version: 2.5.692

Database engine: Azure SQL

Visual Studio version: Visual Studio 2019 16.10.4

**Comment by ErikEJ** [comment]
Maybe you can use the connection string based approach? https://docs.microsoft.com/en-us/sql/connect/ado-net/sql/azure-active-directory-authentication?view=sql-server-ver15#using-active-directory-managed-identity-authentication and https://erikej.github.io/efcore/azure/2021/04/20/efcore-managed-identity.html

**Comment by nholt-isd** [comment]
Okay thanks, I will give your code change a test and let you know.

I was not aware of the connection string approach for the Managed Identities so I will look into that also.

**Comment by nholt-isd** [comment]
Okay, so I was able to try the code changes and I couldn't find a way to get it to work because the DBContex doesn't have a way to return the SQL Connection as far as I could see... and casting it to a DB Connection still dropped the authentication token.

However, I was finally able to get the Connection String route to work with the Managed Identity Authentication... I think we will go this way because it is a lot cleaner and less middleware code for the token needed in the app. Just note to self, double check that the permissions were set correctly so the account can Execute the SP's. 

Thank you for your insight and help!
