### ISSUE TITLE
U.I. to create migrations bundles

### ISSUE THREAD

**Issue by ajcvickers** [ErikEJ/EFCorePowerTools#1078]
Would be nice to have a gesture in VS to create a bundle. :-)

**Comment by ErikEJ** [comment]
Thoughts about design? An option here, or a seperate menu item?

![image](https://user-images.githubusercontent.com/4169187/130346107-1a3f39a8-4f18-49c7-8382-835a2aa5312d.png)

**Comment by ajcvickers** [comment]
@dotnet/efteam Your chance to have input on the U.I.

**Comment by ajcvickers** [comment]
Note your mentioning the team here works. So /cc @bricelam @roji @AndriySvyryd @maumar @smitpatel @JeremyLikness

**Comment by ErikEJ** [comment]
Thanks, learned something new today!

**Comment by ErikEJ** [comment]
@bricelam I only expect the user to reference .Design - but it looks like a lot of logic for this is in the ef tool, and I guess I have to duplicate all that - or am I looking in the wrong place?

**Comment by bricelam** [comment]
Hmm... You're right, most of the logic for [generating and building the bundle](https://github.com/dotnet/efcore/blob/release/6.0/src/ef/Commands/MigrationsBundleCommand.cs#L37) is in ef.exe (actually a .dll on .NET 6).

You could consider shipping that dll as part of the power tools.

Or it might be easier just to re-implement. It basically generates two files--[Program.cs](https://github.com/dotnet/efcore/blob/release/6.0/src/ef/Generators/BundleProgramGenerator.tt) and [efbundle.csproj](https://github.com/dotnet/efcore/blob/release/6.0/src/ef/Generators/BundleProjectGenerator.tt)--and runs `dotnet publish` on them.

There's also a tiny bit of logic in the PMC command to [match the target framework](https://github.com/dotnet/efcore/blob/main/src/EFCore.Tools/tools/EntityFrameworkCore.psm1#L164) of the startup project that might be interesting.

**Comment by ErikEJ** [comment]
Will not do this due to too much code copy and just 1 upvote
