### ISSUE TITLE
AsNoTracking feature

### ISSUE THREAD

**Issue by Iran-asp** [ErikEJ/EFCorePowerTools#1079]
Is there any option that works like `AsNoTracking()` in EF?

**Comment by ErikEJ** [comment]
Yes, EF Core has no-tracking, but how does that relate to the power Tools??

**Comment by Iran-asp** [comment]
That was my mistake, I just thinking to PowerTool's features and not EF Core.
I tried this piece of code:
`context.ChangeTracker.AutoDetectChangesEnabled = false;`
Thank you.
