### ISSUE TITLE
Getting Error while loading solution

### ISSUE THREAD

**Issue by UweR70** [ErikEJ/EFCorePowerTools#1088]
Exact same issue as describe here
https://github.com/ErikEJ/EFCorePowerTools/issues/247
but for VS 2019.

**Comment by ErikEJ** [comment]
Have you tried repairing VS?

**Comment by ErikEJ** [comment]
Can you share your Activity log?

**Comment by UweR70** [comment]
I´ve de-installed it and re-installed it.
Same behavior .

No
[ActivityLog.txt](https://github.com/ErikEJ/EFCorePowerTools/files/7109834/ActivityLog.txt)
tice:
File type xml ( -> "ActivityLog.xml") is here not supported.
So I changed the file type to "TXT"

**Comment by ErikEJ** [comment]
Did you do a repair of VS?

**Comment by ErikEJ** [comment]
Which VS version? 

Try updating to 16.10 or later.

**Comment by UweR70** [comment]
Hi Eric,
I´ve updated VS to version 16.11.2 and the error seems to disappear!

So please close this issue.

Thanks four your help!

**Comment by ErikEJ** [comment]
I will downgrade the SDK version to 16.0!

**Comment by ErikEJ** [comment]
Downgraded to 16.9 (not 16.0)
