### ISSUE TITLE
ContextDir option

### ISSUE THREAD

**Issue by LouisGordon** [ErikEJ/EFCorePowerTools#109]
If I use Package Manager Console with the Scaffold-DbContext, it now takes a parameter that allows you to output the ContextDir into another directory.  I don't believe this option was always available.

https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/powershell 

> -ContextDir <String> | The directory to put the DbContext file in. Paths are relative to the project directory.

Adding support for this would be quite nice, I'd prefer my context to be in the data directory and the generated models in the Model directory at this point.

**Comment by ErikEJ** [comment]
Please explain the desired directory structure, I think EF Core Power Tools may already be able to accommodate your requirements.

**Comment by ErikEJ** [comment]
As the requested additional inforamtion was never supplied, and given I beleive that you can already do this with the Power Tools, I am closing this. Feel free to re-open as required.
