### ISSUE TITLE
Nullable Reference Types, Handlebars C#, strings

### ISSUE THREAD

**Issue by nobba** [ErikEJ/EFCorePowerTools#1090]
Reverse engineering from SQL Server to C# by using Handlebars. I have set the option for using nullable reference types.
But the output contain neither "default!" or "string?".  
The template has this row for generating property code:
public {{property-type}} {{property-name}} { get; set; }{{#if nullable-reference-types }}{{#unless property-isnullable}} = default!;{{/unless}}{{/if}}

Seeing that template, it seems that the NRT-option is ignored by the Handlebars code generation. Also, "property-type" seems to manage nullable or not (?) automatically, but strings are excluded despite my settings.

I have set the option <Nullable>enable</Nullable> in the project file. I have also tried to add a ScaffoldingDesignTimeServices.cs class in which I set options.EnableNullableReferenceTypes = true;. This is according to the Handlebars documentation and I don´t know the relation from EFCorePowerTools to Handlebars. That is, don´t know if I am supposed to configure Handlebars like that or if this is taken care of by EFCPT "under the surface".

### Steps to reproduce
Reverse engineer from SQL Server using handlebars templates, with NRT setting ON. The table would need to have at least one varchar that is nullable, and one that is not.

### Further technical details
EF Core Power Tools version: 2.5.750.0

Database engine: (SQL Server)

Visual Studio 2019 16.9.6

**Comment by ErikEJ** [comment]
I am not sure that this experimental feature has been integrated with HandelBars just yet.

I will look into an update to enable this support, initial investigations indicate that it is possible.

**Comment by nobba** [comment]
Sound great, thank you!

**Comment by ErikEJ** [comment]
I have attempted a fix in the latest daily, please let me know if that works for you

**Comment by nobba** [comment]
Works like a charm, thank you!

**Comment by ErikEJ** [comment]
Had to revert the fix for now, due to Handlebars regression

**Comment by ErikEJ** [comment]
@nobba Fixed (again) in the latest daily, would be grateful if you could confirm

**Comment by nobba** [comment]
Works at my end!
