### ISSUE TITLE
Split DB Context configuration option removes the DBContext OnConfiguring from the context class

### ISSUE THREAD

**Issue by nobba** [ErikEJ/EFCorePowerTools#1091]
We use the split db context into separate classes option. However, we still want to be able to have the "OnConfiguring" method of the actual DBContext. Despite having this in the DbOnConfiguring.hbs file and including {{{> dbonconfiguring}}} in the DbContext.hbs file, the method is removed, seemingly when the configuration split takes place.
After generation the method is there, but when pressing the "Ok" button when confirming the code generation it disappears at the same time that the individual configuration classes appear in VS Solution Explorer.

### Steps to reproduce
See above

### Further technical details
EF Core Power Tools version:  2.5.750.0

Database engine: SQL Server

Visual Studio version: 2019 16.9

**Comment by ErikEJ** [comment]
What is your setting for IncludeConnectionString ? Have you tried setting it to true ?

**Comment by nobba** [comment]
Setting it to true worked, thank you!
