### ISSUE TITLE
Renaming PK property doesn't persist .HasKey()

### ISSUE THREAD

**Issue by MonikaHencekova** [ErikEJ/EFCorePowerTools#1092]
Renaming properties which are primary keys doesn't persist PK (HasKey).

### Steps to reproduce
Rename any property which is PK and notice that in renames property is no more a primary key.

efpt.renaming.json
`[
   {
      "SchemaName": "dbo",
      "Tables": [
         {
            "Columns": [
               {
                  "Name": "HID",
                  "NewName": "Id"
               }
            ],
            "Name": "Holding",
            "NewName": "Holding"
         }
      ],
      "UseSchemaName": false
   }
]`

in context after renaming entity is no more primary key, .HasKey() is missing on that entity.
`protected override void OnModelCreating(ModelBuilder modelBuilder)
       { modelBuilder.Entity<Customer>(entity =>
            {
                entity.Property(e => e.Id).HasColumnName("CID");
}
       }`

before renaming entity
`protected override void OnModelCreating(ModelBuilder modelBuilder)
       { modelBuilder.Entity<Customer>(entity =>
            {
                entity.HasKey(e => e.CID);
entity.Property(e =>  #e.Cid).HasColumnName("CID");
}
       }`

Is there a way to rename pk properties while still keeping them as primary key?

### Further technical details
EF Core Power Tools version: 2.5.750.0
Database engine: SQL Server
Visual Studio version: Visual Studio 2019 16.9.6

**Comment by ErikEJ** [comment]
HasKey is not needed when the property name is Id! This is by convention

**Comment by MonikaHencekova** [comment]
Thank you @ErikEJ just confirmed that by renaming property to something else and indeed .HasKey() is present.
