### ISSUE TITLE
Daily Build - Package did not load Correctly

### ISSUE THREAD

**Issue by KayakFisher205** [ErikEJ/EFCorePowerTools#1094]
I installed the latest version, 2.5.751.0. It works fine with Microsoft Visual Studio Professional 2022 Preview (64-bit)
Version 17.0.0 Preview 3.1. When I start Microsoft Visual Studio Professional 2019 Preview Version 16.11.2 Preview 1.0 I get Package did not load correctly. Looking at the ActivityLog.xml that is generated, the Error Description is:

 Could not load file or assembly &apos;Community.VisualStudio.Toolkit, Version=16.0.76.268, Culture=neutral, PublicKeyToken=79441d341a79572c&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;System.IO.FileNotFoundException: Could not load file or assembly &apos;Community.VisualStudio.Toolkit, Version=16.0.76.268, Culture=neutral, PublicKeyToken=79441d341a79572c&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;File name: &apos;Community.VisualStudio.Toolkit, Version=16.0.76.268, Culture=neutral, PublicKeyToken=79441d341a79572c&apos;&#x000D;&#x000A;   at EFCorePowerTools.EFCorePowerToolsPackage.&lt;&gt;c__DisplayClass18_0.&lt;&lt;LogError&gt;b__0&gt;d.MoveNext()&#x000D;&#x000A;   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine&amp; stateMachine)&#x000D;&#x000A;   at EFCorePowerTools.EFCorePowerToolsPackage.&lt;&gt;c__DisplayClass18_0.&lt;LogError&gt;b__0()&#x000D;&#x000A;   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.ExecuteJob[T](Func`1 asyncMethod, JoinableTask job)&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()&#x000D;&#x000A;   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run(Func`1 asyncMethod)&#x000D;&#x000A;   at EFCorePowerTools.EFCorePowerToolsPackage.LogError(List`1 statusMessages, Exception exception)&#x000D;&#x000A;   at EFCorePowerTools.EFCorePowerToolsPackage.&lt;InitializeAsync&gt;d__8.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass20_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Threading.JoinableTask.&lt;JoinAsync&gt;d__76.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.GetResult()&#x000D;&#x000A;&#x000D;&#x000A;

I'm not sure I need to install that toolkit, but I didn't have an issue with V2022.

### Steps to reproduce
Start up Microsoft Visual Studio Professional 2019 Preview Version 16.11.2 Preview 1.0, right click the project and select EF Core Power Tools and Reverse Engineer.

I tested version Microsoft Visual Studio Professional 2019 Version 16.11.2 and I didn't see the package loading issue.

### Further technical details
EF Core Power Tools version: 2.5.751.0.

Database engine: SQL Server

Visual Studio version: Microsoft Visual Studio Professional 2019 Preview Version 16.11.2 Preview 1.0

**Comment by ErikEJ** [comment]
Is that file missing from the extension folder on disk?

**Comment by KayakFisher205** [comment]
It seems to be there. Based on the patch of the ActivityLog.xml path, that version of VS is in the 16.0_04a190ef folder. Within that folder's Extension folder, there are 3 folders that contain that DLL. All 3 contain the EFCorePowerTools.dll, with 2 of them being version 2.5.710.0. Those 2 folders are dated 7/14/21, with the folder from today as 9/7/21. I was wondering if I should delete the 2 old folders and try again, or if I should uninstall and cleanup all the folders with  EFCorePowerTools.dll and then install again. Attached a screenshot of the search for the Community.VisualStudio.Toolkit.dll.
![Screenshot 2021-09-07 091000](https://user-images.githubusercontent.com/71768711/132359355-31606ac2-0d0a-4e7d-a269-ef8e26eaf8b2.png)

**Comment by ErikEJ** [comment]
You should do some cleanup, I think

**Comment by KayakFisher205** [comment]
After I uninstalled for Visual studio 2019 and the Preview version and deleting the extra folders, then reinstalling EF Core Tools, there was not issues.

Thanks for your help.
