### ISSUE TITLE
Error using the DGML NuGet package

### ISSUE THREAD

**Issue by jaward916** [ErikEJ/EFCorePowerTools#1095]
Hi, firstly thanks for this extension, it looks like exactly what I've been missing on my EFCore journey!

I have an issue using the DGML creation tools, couldn't figure out how to get the DB context right to use the menu option to Add DGML - I have different appsettings.json files for different configurations, and copying the OnConfiguring override code found on here and putting my SQL connection string in still resulted in "connectionString is null" errors.

So I've tried to run the NuGet package version and create when my project is in Debug mode but it also errors out...
`
Method not found: 'Microsoft.EntityFrameworkCore.Metadata.Internal.DebugView``1<Microsoft.EntityFrameworkCore.Metadata.Internal.Model> Microsoft.EntityFrameworkCore.Metadata.Internal.Model.get_DebugView()'`

### Steps to reproduce

I'm running this from my Program.cs for now, after a few other "setup" methods:

```
public static void CreateDgml(DEV_GEN_1Context context)
        {
            if (context == null) throw new ArgumentNullException(nameof(context));
            var path = Path.GetTempFileName() + ".dgml";
                File.WriteAllText(path, context.AsDgml(), Encoding.UTF8);
                var startInfo = new ProcessStartInfo(path)
                {
                    UseShellExecute = true,
                };
                Process.Start(startInfo);
        }
```

The context is valid at this time, as I am using it to seed initial data in the same scope.

The app is ASP/NetCore 5 all EFCore packages are on 5.0.9

### Further technical details
EF Core Power Tools version: 2.5.750.0 (NuGet pkg version shows as 3.1.4)

Database engine: SQL 2019 Express

Visual Studio version: 2019 (16.11.2)

**Comment by ErikEJ** [comment]
Try updating the dgml package to 5.0!

Maybe time to move it out of preview..

**Comment by jaward916** [comment]
Well that worked, awesome, didn't think to check preview, still avoiding EFCore 6, so don't have it enabled usually!

Thanks for the fast response on this.
