### ISSUE TITLE
efpt.renaming.json not renaming schemas

### ISSUE THREAD

**Issue by rcpokorny** [ErikEJ/EFCorePowerTools#1096]
Love the tool!  However my DBA likes to use schemas everywhere whereas I have common table names in two different schemas.  When I attempt to use the renaming option and perform the reverse engineer, I do not get the expected results.

Here are the two tables:
Book_Fair.Contacts
Salesforce.Contacts

Here is the renaming.JSON:
[
  {
    "UseSchemaName": false,
    "SchemaName": "Book_Fair",
    "Tables": [
      {
        "Name": "Contacts",
        "NewName": "BookfairContacts"
      }
    ]
  },
  {
    "UseSchemaName": false,
    "SchemaName": "Sales_Force",
    "Tables": [
      {
        "Name": "Contacts",
        "NewName": "SalesforceContacts"
      }
    ]
  }
]

Instead of getting what I thought would be BookfairContacts (from Book_Fair schema) and SalesforceContacts (from Salesforce schema), I get Contacts and Contacts1.  This is the dbContext:

        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Contact1> Contacts1 { get; set; }

I am not sure if the renaming feature is working or I have the correct options configured.

System Information:
SQL Server
VS 2019 V 16.9.1
C#, .Net Core 5.0
EF Core Power Tools version 2.5
### Steps to reproduce
Include a complete description that I can redo to reproduce the issue.

**Comment by ErikEJ** [comment]
Looks alright, can you share a sample project and create table statements?

**Comment by rcpokorny** [comment]
Hi Erik,

Thanks for the quick turnaround.

I created a test application to provide an example for you.  Once I completed and tested it, the renaming actually worked.
Comparing to what my production code looked like, the only difference I saw in the ranaming.json were the "Columns" tag.
I added the tag and performed the reverse engineer and the renaming worked in production.

I have a better understanding how to use the renaming file for future use.  My apologies for taking your time, you can close this issue.

Thank you again for the quick response!
Bob



________________________________

**Comment by ErikEJ** [comment]
You can actually do the renaming.from the GUI, and get a correct file created.
