### ISSUE TITLE
Unable to load project assembly at Modelling.EfCoreModelBuilder

### ISSUE THREAD

**Issue by sergxp** [ErikEJ/EFCorePowerTools#1097]
I'm getting 
![image](https://user-images.githubusercontent.com/28748653/132872564-7ed4197a-bf85-48f1-990b-715ca2f05148.png)

When I try to add a migration. This has directly something to do with the latest release. I uninstalled it and reinstalled the latest, I have the same issue. But when I uninstall and install an older version, it works just fine.

### Steps to reproduce
Open Migrations Tool.
Give a migration name
Click "Add migration"

### Further technical details
EF Core Power Tools version: 2.5.750.0

Database engine: SQL Server

Visual Studio version: Microsoft Visual Studio Enterprise 2019 Version 16.11.2

**Comment by ErikEJ** [comment]
Thanks, I will investigate this refactoring bug.

**Comment by ErikEJ** [comment]
I have attempted a fix in the latest daily build, please let me know if that solves the issue
