### ISSUE TITLE
Solution actions stopped working when configuration file is not placed top level in project structure

### ISSUE THREAD

**Issue by krzysiek-b** [ErikEJ/EFCorePowerTools#1098]
When I istall the plugin in VS 2019 and invoke them from solution's context menu nothing happens. No error is displayed. No exception details are printed in the output. VS logs also contain no error information.

Refresh option also does not work.

### Steps to reproduce
Install latest plugin on latest version of VS and try us it.

Is there are other way I can diagnose the issue?

**Comment by ErikEJ** [comment]
Can you share a screenshot? Which menu?

**Comment by krzysiek-b** [comment]
Sure, those two.
![image](https://user-images.githubusercontent.com/6192236/133067964-f686d67e-953a-40c1-9ba8-eaa716729c6d.png)

**Comment by ErikEJ** [comment]
I am not able to repro with latest master.
You could clone and debug to figure out what is wrong.

**Comment by krzysiek-b** [comment]
It leaves execution here
`if (item.Parent as Project == null)
                {
                    return;
                }`

For me parent is PhysicalFolder and this worked fine some time ago.
Has anything changed does the configuration need to be top level now?

**Comment by ErikEJ** [comment]
I have made changes to remove usage of EnvDTE, and those changes may have been buggy, so yes.

Can you share your project structure, so I can better understand the issue? Is efpt.config.json placed in a folder?

**Comment by krzysiek-b** [comment]
Hi, can you please take my PR https://github.com/ErikEJ/EFCorePowerTools/pull/1100 instead

**Comment by ErikEJ** [comment]
Closed in #1100
