### ISSUE TITLE
Visual Studio 2022 Support?

### ISSUE THREAD

**Issue by akeck** [ErikEJ/EFCorePowerTools#1099]
I've come quite depended on EFCorePowerTools when migrating to .net 5.0.
I will start using VS2022 as soon as it's available, but only if EFCorePowerTools are available.

Any good news there? :)

**Comment by akeck** [comment]
Never mind... it's already there... I just saw in the readme.md that there's still only VS2019 :)

**Comment by ErikEJ** [comment]
Thanks, I have updated the readme
