### ISSUE TITLE
[Feature Request] Remove Prefix

### ISSUE THREAD

**Issue by stormrover** [ErikEJ/EFCorePowerTools#110]
Please allow user to specify a prefix for tables and other objects to be "removed" on the reverse engineer process
e.g.: SQL: tblUser -> C#: User

**Comment by ErikEJ** [comment]
You should be abel to use #14 for this (included in latest daily build)

**Comment by stormrover** [comment]
Ok thanks for the prompt reply. 

Not sure on how to use it but I'll post my questions there.
