### ISSUE TITLE
All or nothing Generation : Continue Generating Model in case of error counters

### ISSUE THREAD

**Issue by nssidhu** [ErikEJ/EFCorePowerTools#1103]
EFCore Power Tools works in  All or Nothing mode
Can you add the mode, where it generates all the possible models rather than all or nothing ?

**Comment by ErikEJ** [comment]
I do not understand the question.

Please provide an example/screenshots/better explanation.

**Comment by nssidhu** [comment]
This is related to Reverse Engineering from an existing database.
for example if there is as stored procedure that is referring to table which does not exists, when doing reverse engineering with this tool, it aborts the reverse engineering with error message.
What I am asking is can a flag be added so that it skips the objects that are invalid but continue to generate model for the ones that are valid.

I hope this details will help you understand the problem i am trying to highlight.

**Comment by ErikEJ** [comment]
Can you please share the exact error message, and I will investigate.

**Comment by ErikEJ** [comment]
As far as I can see, an invalid stored proc does not prevent code generation currently.

**Comment by ErikEJ** [comment]
Ping?
