### ISSUE TITLE
Database Project (dacpac) does not generate correctly stored procedure model with computed columns

### ISSUE THREAD

**Issue by eminmesic** [ErikEJ/EFCorePowerTools#1105]
The stored procedure model generator does not work for Database Project (dacpac) when the stored procedure is using a computed column from a table.

### Steps to reproduce
Create a database project or add in the existing one, following two database objects.

CREATE TABLE dbo.TestTable 
(
	Id int identity(1, 1) primary key,
	FirstName nvarchar(50),
	LastName nvarchar(50),
	Name AS CONCAT(FirstName, ' ', LastName)
);

CREATE PROCEDURE dbo.TestProcedure
AS
	SELECT Id, FirstName, LastName, Name
	FROM dbo.TestTable

Now when you try to generate stored procedure **dbo.TestProcedure** it will generate an empty object because it was an exception during generation. If you create these two objects directly into the database and then using the generator on the database it will generate correctly.

Somehow, the database project does not recognize data type for the computed column in the stored procedure even if you add an explicit conversion in table creation. 

A quick fix is an explicit conversion in the stored procedure directly, but that is not a solution from the performance perspective.

![image](https://user-images.githubusercontent.com/9116968/133885041-d496e08e-9f84-4c91-b1a5-faf688d7b50b.png)

EF Core Power Tools version: 2.5.758

Database engine: SQL Server Database Project

Visual Studio 2019 Version 16.11.2

**Comment by ErikEJ** [comment]
@eminmesic This is a known issue: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#sql-server-database-project-dacpac-mapping

**Comment by ErikEJ** [comment]
@eminmesic What is the exact exception you are seeing during code generation?

**Comment by eminmesic** [comment]
@ErikEJ there is no exception if you try to generate through the extension in Visual Studio, because of try-catch of course.

I did some debugging and I found out exception on the line:
`DataTypeHelper.Instance.GetMap(TypeFormat.SqlServerDbType, val.GetReferenced(dac.Column.DataType).FirstOrDefault()?.Name.Parts.Last())`

**Source:** ErikEJ.EntityFrameworkCore.SqlServer.Dacpac.Procedure.cs

This part **val.GetReferenced** cannot read data type and then automatically **GetMap** method failed.

**Comment by ErikEJ** [comment]
I am not aware of any way to improve this.

**Comment by ErikEJ** [comment]
How is `CONCAT(FirstName, ' ', LastName)` represented in the model.xml file inside the .dacpac file?

**Comment by ErikEJ** [comment]
Ping?
