### ISSUE TITLE
EF Core 6 reverse engineering missing features

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#1106]
- [x] Dacpac support
- [x] Handlebars support
- [x] Firebird
- [x] Oracle
- [x] MySQL 
- [x] NodaTime for SQL Server

**Comment by StevenRasmussen** [comment]
Hi @ErikEJ - FYI, I just published a release candidate for the [SimplerSoftware.EntityFrameworkCore.SqlServer.NodaTime](https://www.nuget.org/packages/SimplerSoftware.EntityFrameworkCore.SqlServer.NodaTime/) package that uses the EF Core 6 release candidate.  I tested the scaffold command and it appears to be working as expected.  For more info see [#23](https://github.com/StevenRasmussen/EFCore.SqlServer.NodaTime/issues/23)

**Comment by ErikEJ** [comment]
@StevenRasmussen Thanks, I have included the package in the latest daily

**Comment by tonysneed** [comment]
Released Handlebars tool with support for EF Core 6: [v6.0.0-preview1](https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars/releases/tag/v6.0.0-preview1).

NuGet Package: https://www.nuget.org/packages/EntityFrameworkCore.Scaffolding.Handlebars/6.0.0-preview1

> **Note**: New templates:
> * CSharpDbContext/Partials/DbImports.hbs
> * CSharpDbContext/Partials/DbSets.hbs
> * CSharpEntityType/Partials/Properties.hbs
> * TypeScriptEntityType/Partials/Properties.hbs

**Comment by ErikEJ** [comment]
@tonysneed I am trying to think of a good way to communicate that there are breaking changes, when a user updates from EF Core 5.0 to 6.0 and is already using handlebars? Assume there is no version info inside the template files...

**Comment by tonysneed** [comment]
I understand. It may be the case that users would need to update their templates when upgrading from 5 to 6. However, it would be better if they did not need to touch the templates when upgrading.

The main issue is with skip navigations. The author of the PR changed the templates to make those work. Let me see if I can challenge him to avoid changing the templates.

That said, it may still be necessary because of a needed namespace import, but that change would be minor.

**Comment by tonysneed** [comment]
@ErikEJ v6.0.0-preview2 has updated templates, but the changes are backwards compatible. So users will not need to update customized templates when going from v5 to v6. Also the ReadMe has instructions for upgrading.

**Comment by lauxjpn** [comment]
@ErikEJ Is there still anything missing from the Pomelo package?

**Comment by ErikEJ** [comment]
@lauxjpn not as far as I know, thanks

**Comment by ErikEJ** [comment]
@tonysneed excellent. I will try to get something in to the daily build soon.

**Comment by ErikEJ** [comment]
@tonysneed Handlebars 6 is now in the latest daily build from vsixgallery.com

**Comment by ErikEJ** [comment]
TODO: Add Firebird https://twitter.com/cincura_net/status/1466793555641487361

**Comment by cincuranet** [comment]
I'm keeping track of this. But I'm waiting for stable release (on my side).

**Comment by ErikEJ** [comment]
@cincuranet I just use the reverse engineering bits, assume they work already?

**Comment by cincuranet** [comment]
As far as tests show, yes. :)

**Comment by ErikEJ** [comment]
@cincuranet Dont think you need the explict dependency on EFCore in your package, EFCore.Relational should cover that.

**Comment by cincuranet** [comment]
I know. But I want to be explicit about this.

**Comment by ErikEJ** [comment]
OK? The latest daily build includes support for Firebird with EF Core 6!

**Comment by ErikEJ** [comment]
TODO: Add Oracle provider + enable Oracle ad-hoc connection

**Comment by ErikEJ** [comment]
@alexkeh Oracle support added to latest daily build!

**Comment by alexkeh** [comment]
> @alexkeh Oracle support added to latest daily build!

Awesome! Thanks @ErikEJ

**Comment by tonysneed** [comment]
@ErikEJ A stable version of my Handlebars lib is now available: https://www.nuget.org/packages/EntityFrameworkCore.Scaffolding.Handlebars/6.0.0

**Comment by ErikEJ** [comment]
@tonysneed And no template updates since 6.0 preview 1

**Comment by tonysneed** [comment]
No template updates since 6.0 preview 2. 😄
