### ISSUE TITLE
Reverse Engineer: allow entities imported from views to have a primary key

### ISSUE THREAD

**Issue by attevirtanensykefi** [ErikEJ/EFCorePowerTools#1108]
**Thank you very much for these great tools!**

### Current behaviour
When generating an entity from a view, the entity gets configured not to have a primary key:

```
public void Configure(EntityTypeBuilder<View1> entity)
{
    entity.HasNoKey();

    entity.ToView("View1", "dbo");
    ....
```

Correct me if I'm wrong, but it seems like there is currently no way to change this behavior. It would be nice, if it could be possible to allow the view to have a primary key.

### Suggested behavior
Here's one suggestion:

The following efpt.config.json:
```
{
   "Tables": [
      {
         "Name": "[dbo].[View1]",
         "ObjectType": 3,
         "PrimaryKey": ["View1Id"]
      },
```
Would produce the following configuration:

```
public void Configure(EntityTypeBuilder<View1> entity)
{
    entity.HasKey("View1Id");

    entity.ToView("View1", "dbo");
    ....
```

### Further technical details
EF Core Power Tools version: 2.5.750.0

Database engine: SQL Server

Visual Studio version: Visual Studio 2019 16.11.1

**Comment by ErikEJ** [comment]
You can override the configuration by implementing OnModelCreatingPartial method in a partial class

**Comment by attevirtanensykefi** [comment]
Thank you!

I added a partial for the context with the following code:
```
namespace API.Models {
    public partial class MyContext : DbContext {
        partial void OnModelCreatingPartial(ModelBuilder modelBuilder) {
            modelBuilder.Entity<View1>().HasKey("View1");
        }
    }
```

That causes a  _System.InvalidOperationException: 'The key {'View1Id'} cannot be added to keyless type 'View1'.'_ at the HasKey call.

How should I solve this problem? (I am new with EF Core)

**Comment by ErikEJ** [comment]
I think it is a bug fixed in EF Core 6, you can try:

```
            modelBuilder.Entity<CategorySalesFor1997>().Metadata.IsKeyless = false;
            modelBuilder.Entity<CategorySalesFor1997>().HasKey("CategoryName");

```

**Comment by attevirtanensykefi** [comment]
Unfortunately it does not work.

The initial configuration:
```
public void Configure(EntityTypeBuilder<View1> entity)
{
    entity.HasNoKey();

    entity.ToView("View1", "dbo");
    ....
```
Leads to 

_System.InvalidOperationException: Unable to determine the relationship represented by navigation 'Entity1.View1' of type 'View1'. Either manually configure the relationship, or ignore this property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'._ 

when another entity has View1 as a property (without entity.HasNoKey() it works).

If I add the code you suggested, it still leads to the same exception:
```
public void Configure(EntityTypeBuilder<View1> entity)
{
    entity.HasNoKey();
    entity.Metadata.IsKeyless = false; // this should be moved to another partial
    entity.HasKey("View1Id");          // -- 11 --

    entity.ToView("View1", "dbo");
    ....
```
--> _System.InvalidOperationException: Unable to determine the relationship represented by navigation 'Entity1.View1' of type 'View1'. Either manually configure the relationship, or ignore this property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'._

**Comment by ErikEJ** [comment]
Please provide a complete repro.

Which EF Core version?

**Comment by ErikEJ** [comment]
Are you saying this is not working at all? How come?

```
public void Configure(EntityTypeBuilder<View1> entity)
{
    entity.HasNoKey();

    entity.ToView("View1", "dbo");

```

Try to re-order:
```
    entity.HasNoKey();
    entity.ToView("View1", "dbo");

    entity.Metadata.IsKeyless = false; // this should be moved to another partial
    entity.HasKey("View1Id");          // -- 11 --

```

**Comment by attevirtanensykefi** [comment]
I will provide a repro so that you will understand what I am trying to do. Just entity.HasNoKey(); or no entity.HasNoKey(); works as expected. I did not get entity.Metadata.IsKeyless = false; to work in my use case.

**Comment by ErikEJ** [comment]
Which EF Core version are you using?

**Comment by attevirtanensykefi** [comment]
EF Core 5.0.7

**Comment by ErikEJ** [comment]
I am not able to repro on 5.0.9 either!

**Comment by attevirtanensykefi** [comment]
Thank you! I will make a sample solution of my problem here when I will find time.

**Comment by ErikEJ** [comment]
This will be fixed in EF Core 6 https://github.com/dotnet/efcore/pull/26144
