### ISSUE TITLE
EFCore 5 reverse engineering resulting in broken using statements for some models

### ISSUE THREAD

**Issue by clagraff** [ErikEJ/EFCorePowerTools#1109]
Our generated models are now showing unnecessary (and invalid) using statements after running through the Reverse engineering process. 

![image](https://user-images.githubusercontent.com/1822984/134233068-f43c5616-d64e-43d5-8b3b-f2c08db36f2b.png)

This is not occurring for _all_ of the generated models; there is no clear pattern for which ones are affected by this and which ones are not. 

The exact reproduction steps are listed below. I would like to call out that _not_ checking the `Customize code using Handlebars templates` does _not_ produce the unnecessary and broken `using` statements.

Our Handlebars templates have not changed since 2020, but for completeness I will include them below:

`CodeTemplates/CSharpEntityType/Class.hbs`
```
{{> imports}}

namespace {{namespace}}
{
    {{#if comment}}
    /// <summary>
    /// {{comment}}
    /// </summary>
    {{/if}}
    {{#each class-annotations}}
    {{{class-annotation}}}
    {{/each}}
    public partial class {{class}}
    {
        {{{> constructor}}}
        {{{> properties}}}
    }
}
```

and 

`CodeTemplates/CSharpEntityType/Partials/Imports.hbs`

```
using System;
using System.Collections.Generic;
{{#if use-data-annotations}}
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
{{/if}}
{{#each imports}}
using {{import}};
{{/each}}

```

### Steps to reproduce
No changes were introduced to our Azure MS SQL database.
We go through the Reverse Engineering steps as follows:

- No filter schemas
- EF Core 5 selected
- Variety of tables are chosen for Database Objects.
- Context name, namespace, entity types path, dbContext path are given.
- Use table and column names directly from the database is checked.
- Customize code using Handlebars templates for C# is checked (we believe this to be part of the problem)
- Split DbContext into Configuration classes is checked.
- No other options are checked, we generate our models.

Screenshots of the exact settings below, if that is more useful:

![image](https://user-images.githubusercontent.com/1822984/134232705-104be503-8fc3-43f1-a3aa-f8b7ea4c65c4.png)

![image](https://user-images.githubusercontent.com/1822984/134232748-22f43de3-9ecc-429c-9f9b-bc86459c7731.png)

![image](https://user-images.githubusercontent.com/1822984/134232799-e21258bd-fbd2-44d8-b38e-e5e69b84f9fc.png)

![image](https://user-images.githubusercontent.com/1822984/134232830-d9f290fd-19fe-4721-b4ee-fe43d7c3aac7.png)

### Further technical details
EF Core Power Tools version: 2.5.758.0

Database engine: Azure SQL

Visual Studio version: Microsoft Visual Stuio Community 2019: Version 16.11.2

dotnet SDK version: 5.0.400

**Comment by ErikEJ** [comment]
I have updated the Handlebars lib recently, you may have to restart them.

Also, try to uncheck the config splitting preview feature.

**Comment by clagraff** [comment]
Hi @ErikEJ  if you do not mind providing a little more clarification, I think I am a little confused?

When you say "restart" the Handlebars lib, what do you mean exactly? Do I need to uninstall and reinstall EF Core Power Tools, and in doing so getting the latest Handllebars? Afaik I haven't done anything to get Handlebars specifically, I assume it was included with the latest PowerTools release?

> Also, try to uncheck the config splitting preview feature.

We can give that a try; that said, we've greatly appreciated having our many configs split. I can report back if that fixes it, but ideally we would prefer to have this feature enabled. I will reply back how things go after running w/o it.

**Comment by clagraff** [comment]
> Also, try to uncheck the config splitting preview feature.

I just re-ran without checking the config splitting feature. We still have the same issue of broken, unnecessary unused `using` statements.

**Comment by ErikEJ** [comment]
Let me try to rollback the Handlebars update tomorrow.

**Comment by clagraff** [comment]
> Let me try to rollback the Handlebars update tomorrow.

Okay. Will that mean we need to get a new (or older?) version of the extension tomorrow?

> Also, could you please try to rename the CodeTemplates folder, this will give you a pristine set of Handlebars templates, when running reverse engineering again.

Sure thing!

Thanks for the quick responses.

**Comment by ErikEJ** [comment]
You will get the latest daily with an older version of the Handlebars library (it is a third party lib)

**Comment by ErikEJ** [comment]
I have reverted to Handlebars 5.0.1 in the latest daily build (.769 or later)

**Comment by ErikEJ** [comment]
@tonysneed Does this look familiar?

**Comment by clagraff** [comment]
@ErikEJ tl;dr still not working w/ the daily build.

I uninstalled the extension from my Visual Studios Community 2019, and installed using the latest [Daily Build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f). I renamed our `CodeTemplates` as you had asked. And then tried the entire process.

Maybe I did not do the install correctly, but I was getting errors that CodeTemplates501.zip could not be found in the directory for the extension. So I snagged it from Github and plopped it down. Then it complained that our project didn't have a `CodeTemplates` folder; I had been expecting it would just regenerate it, but maybe not? So I copied it from the zip into our project myself.

Fixed all that, re-ran, and still have the same issue of broken and unnecessary `using` statements.

Daily version I have installed is: 2.5.769.

**Comment by davidhendrickmb** [comment]
FYI I have also had the same problems since the last update.

**Comment by ErikEJ** [comment]
I think I need a repro database schema so I can investigate locally.

Creation of CodeTemplates folder should be automatic, I will investigate why you are getting errors.

**Comment by davidhendrickmb** [comment]
Is the best option to roll back a version? Are old versions available for download?

**Comment by davidhendrickmb** [comment]
![image](https://user-images.githubusercontent.com/18259436/134370205-13d621fa-1769-4d87-948f-71ca37145f04.png)

**Comment by ErikEJ** [comment]
I am actually unable to repro with a new set of templates using the latest Handlebars lib!

Notice how DbImports.hbs looks now:

```
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
{{#if model-namespace}}
using {{model-namespace}};
{{/if}}
{{#each model-imports}}
using {{model-import}};
{{/each}}

```

**Comment by ErikEJ** [comment]
I am not able to repro with the latest Handlebars library and multiple schemas.

I need a repro...

**Comment by davidhendrickmb** [comment]
If I remove this from Imports.hbs it removes the additional usings, but then "using NetTopologySuite.Geometries;" is also removed.
I can try to create a sample database for you, but I don't know that that will produce the issue as it looks like it's when you have existing imported data/templates.
{{#each imports}}
using {{import}};
{{/each}}

**Comment by davidhendrickmb** [comment]
`/****** Object:  Schema [Company]    Script Date: 22/09/2021 17:04:22 ******/
CREATE SCHEMA [Company]
GO
/****** Object:  Schema [Person]    Script Date: 22/09/2021 17:04:22 ******/
CREATE SCHEMA [Person]
GO
/****** Object:  Table [Company].[CompanyTable]    Script Date: 22/09/2021 17:04:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Company].[CompanyTable](
	[CompanyId] [int] IDENTITY(1,1) NOT NULL,
	[CompanyName] [nvarchar](200) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CompanyId] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [Person].[PersonTable]    Script Date: 22/09/2021 17:04:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Person].[PersonTable](
	[PersonId] [int] IDENTITY(1,1) NOT NULL,
	[CompanyId] [int] NULL,
	[PersonName] [nvarchar](200) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[PersonId] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [Person].[PersonTable]  WITH CHECK ADD FOREIGN KEY([CompanyId])
REFERENCES [Company].[CompanyTable] ([CompanyId])
GO
`

**Comment by davidhendrickmb** [comment]
These tables will reproduce it for you. The key is to create 2 schemas and a table in each with a foreign key from one to the other

**Comment by ErikEJ** [comment]
Can you also share the efpt.config.json and your CodeTemplates folder - or even better a complete repro project.

**Comment by davidhendrickmb** [comment]
Of course - sorry for a silly question, but where are the connection strings saved so I can be sure I don't share them?

**Comment by davidhendrickmb** [comment]
[CodeTemplates.zip](https://github.com/ErikEJ/EFCorePowerTools/files/7212331/CodeTemplates.zip)

**Comment by davidhendrickmb** [comment]
Here are the CodeTemplates and JSON - I've just changed the ContextClassName and UiHint in the json file

**Comment by ErikEJ** [comment]
Great, I am able to repro now.

**Comment by ErikEJ** [comment]
So, no matter how far back I revert I still see the issue!

Which EF Core version / extension version did you guys come from?

**Comment by ErikEJ** [comment]
@tonysneed Looks like a regression in Handlebars 5.0

**Comment by davidhendrickmb** [comment]
I have mine set to auto update and don't think it's been that long since the last update, I usually update regularly.

**Comment by tonysneed** [comment]
@davidhendrickmb Great if you could open an issue on my repo: https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars

In the meantime I’ll grab the zip file and repro.

**Comment by davidhendrickmb** [comment]
I assume there's no short term fix for this other than deleting the invalid references every time we do a reverse engineer?

**Comment by ErikEJ** [comment]
Fixed in latest daily

**Comment by davidhendrickmb** [comment]
> Fixed in latest daily

Thanks - I can confirm this works now!

**Comment by tonysneed** [comment]
Fixed this with Handlebars release [v5.0.4](https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars/releases/tag/v5.04).

**Comment by ErikEJ** [comment]
@clagraff @davidhendrickmb A bug fix for this is now available in the latest daily, would be grateful if you could confirm

**Comment by clagraff** [comment]
Hi @ErikEJ 👋 

I can confirm everything is looking correct w/ the latest daily. No unexpected `using` statements. 
Thanks a bunch for your help in resolving this.

**Comment by ErikEJ** [comment]
Thanks for checking!

**Comment by davidhendrickmb** [comment]
Sorry about the delay, I was on holidays. I can also confirm that this is now working correctly. Thanks very much for your help!
