### ISSUE TITLE
SQL server temporal tables support 

### ISSUE THREAD

**Issue by Gerry30** [ErikEJ/EFCorePowerTools#1110]
Describe what is not working as expected.
If you create a sql project with temporal tables such as 
https://docs.microsoft.com/en-us/sql/samples/wide-world-importers-oltp-install-configure?view=sql-server-ver15
EF power tools skips all the history tables 
https://docs.microsoft.com/en-us/sql/relational-databases/tables/temporal-tables?view=sql-server-ver15
it would be great for that to be included only works on  sql 2016 > 

Visual Studio version: (e.g. Visual Studio 2019 16.9)

**Comment by ErikEJ** [comment]
Support for temporal tables should be available with EF Core 6.

**Comment by ErikEJ** [comment]
Support for temporal tables should be available with EF Core 6.

**Comment by ErikEJ** [comment]
I you need support with EF Core 5, you can add the missing columns in a partial class.
