### ISSUE TITLE
Search and notify duplicate foreign keys rather than crash 

### ISSUE THREAD

**Issue by Gerry30** [ErikEJ/EFCorePowerTools#1111]
Sql server 
if there are duplicate foreign keys against a table ef power tools crashes and reports the error through output in visual studio. It would be nice if handled more gracefully with either a dialog message or better still a search and list of duplicates before attempting to build.

**Comment by ErikEJ** [comment]
I fixed this in EF Core 6.

**Comment by ErikEJ** [comment]
Reminder to self: verify that warning bubbles up!
