### ISSUE TITLE
Unable to use the extension in VS2019

### ISSUE THREAD

**Issue by sameer-kumar** [ErikEJ/EFCorePowerTools#1112]
I have installed the latest version of EF Core PowerTools in my VS2019. However, whenever I launch VS IDE or try to use the extension from context menu, I get a warning dialog stating that "The EFCorePowerToolsPackage did not load correctly". This pop-up error window has a link to view ActivityLog.xml too.

### Steps to reproduce
1. Install the latest extension from Extensions > Manage Extensions VS IDE menu option.
2. Relaunch VS IDE
3. Create new .Net Core 3.1 console application.
4. Right-click the project and chose EF Core Power Tools option and select "Reverse Engineer" from context menu.
5. It should NOT display warning/error dialog instead should display expected window.

### Further technical details
EF Core Power Tools version: 2.5.758

Database engine: SQL Server 

Visual Studio version: Visual Studio Enterprise 2019 16.8.5

**Comment by ErikEJ** [comment]
Update VS to 16.9!

**Comment by ErikEJ** [comment]
Please also share the Activity log file

**Comment by sameer-kumar** [comment]
[ActivityLog.xml.txt](https://github.com/ErikEJ/EFCorePowerTools/files/7218433/ActivityLog.xml.txt)

**Comment by sameer-kumar** [comment]
> Update VS to 16.9!

Do you want me to update to 16.9 or latest 16.11.3?

**Comment by ErikEJ** [comment]
Let me have a look at the activity log, but latest VS version is fine.

**Comment by ErikEJ** [comment]
<description>SetSite failed for package [EFCorePowerToolsPackage]Source: &apos;EFCorePowerTools&apos; Description: Object reference not set to an instance of an object.&#x000D;&#x000A;System.NullReferenceException: Object reference not set to an instance of an object.&#x000D;&#x000A;   at EFCorePowerTools.Helpers.Telemetry.TrackException(Exception ex)&#x000D;&#x000A;   at EFCorePowerTools.EFCorePowerToolsPackage.&lt;&gt;c__DisplayClass19_0.&lt;&lt;LogError&gt;b__0&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()&#x000D;&#x000A;   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run(Func`1 asyncMethod)&#x000D;&#x000A;   at EFCorePowerTools.EFCorePowerToolsPackage.LogError(List`1 statusMessages, Exception exception)&#x000D;&#x000A;   at EFCorePowerTools.EFCorePowerToolsPackage.&lt;InitializeAsync&gt;d__8.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass20_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Threading.JoinableTask.&lt;JoinAsync&gt;d__68.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.GetResult()</description>
    <guid>{F4C4712C-CEAE-4803-8E52-0E2049D5DE9F}</guid>

**Comment by ErikEJ** [comment]
I see this, let me have a look at fixing that

**Comment by ErikEJ** [comment]
Something is broken on your system during initialization, but the bug above prevents us from finding the cause. I have implemented a fix for the bug above in the latest daily build.

Please install that, and let me know the outcome (I expect another error to emerge)

**Comment by ErikEJ** [comment]
A VS update is still recommended, btw

**Comment by sameer-kumar** [comment]
The latest version of VS fixed it! I no longer see error/warning dialog about the extension. Thanks for your help!

Now I need to learn how to use the extension. In particular, I have 2 requirements:
1. Split DbContext and Entities in separate projects. 
2. Wrap your extension kick-off logic as a custom nuget package. So that my team members don't have to install the VS extension but just reference nuget package which will bring down entities/context with code templates  customizations so that we have consistency in our environment.

Do you have any docs or pointers for me?

**Comment by ErikEJ** [comment]
Sure, there is a couple of videos here: https://github.com/ErikEJ/EFCorePowerTools and wiki: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering

**Comment by ErikEJ** [comment]
For item 2 please add a new issue with a more detailed description of what you would like to achieve

**Comment by ErikEJ** [comment]
And thanks for your help uncovering the telemetry bug

**Comment by sameer-kumar** [comment]
> For item 2 please add a new issue with a more detailed description of what you would like to achieve

Will do. Thank you!
