### ISSUE TITLE
The required column 'DateTimeIssued' was not present in the results of a 'FromSql' operation.

### ISSUE THREAD

**Issue by nssidhu** [ErikEJ/EFCorePowerTools#1114]
I am getting the following Error, when executing the below code. The error occurs at line _dbContext.Procedures.sp_GetWalkInUserTokenAsync. In the Class DateTimeIssued is declared as nullable.

The error only occurs when i abort the execution form within the stored procedure based on some validation checks.
if it does not fail validations, i do get back the results.
How to make it resilient enough so that it handles return of errors as well as select output?

    OutputParameter<string> ErrorMessage = new OutputParameter<string>();
                    OutputParameter<string> SuccessMessage = new OutputParameter<string>();
                    OutputParameter<int> returnValue = new OutputParameter<int>();

                   var respWalkinToken = await _dbContext.Procedures.sp_GetWalkInUserTokenAsync(WalkingTokenRequest.OrgLocationCategoryID, WalkingTokenRequest.CellPhoneCountryDialingCode, 
                        WalkingTokenRequest.CellPhoneNumber, WalkingTokenRequest.FirstName, WalkingTokenRequest.LastName, ErrorMessage, SuccessMessage, returnValue);

`Error Occured in OrganizationController.ValidateWalkInOTPAndGetToken System.InvalidOperationException: The required column 'DateTimeIssued' was not present in the results of a 'FromSql' operation. at Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.BufferedDataRecord.InitializeFields() at Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.BufferedDataRecord.InitializeAsync(DbDataReader reader, IReadOnlyList`1 columns, CancellationToken cancellationToken) at Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.InitializeAsync(IReadOnlyList`1 columns, CancellationToken cancellationToken) at Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.InitializeAsync(IReadOnlyList`1 columns, CancellationToken cancellationToken) at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken) at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken) at Microsoft.EntityFrameworkCore.Query.Internal.FromSqlQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken) at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.<>c__DisplayClass30_0`2.<b__0>d.MoveNext() --- End of stack trace from previous location --- at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken) at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken) at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken) at Microsoft.EntityFrameworkCore.Query.Internal.FromSqlQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync() at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken) at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken) at GetInLineV6New.Server.DbModels.DbContextExtensions.SqlQueryAsync[T](DbContext db, String sql, Object[] parameters, CancellationToken cancellationToken) in C:\Users\admin\source\repos\GetInLineV6New\GetInLineV6New\Server\DbModels\DbContextExtensions.cs:line 28 at GetInLineV6New.Server.DbModels.GetinLineDbContextProcedures.sp_GetWalkInUserTokenAsync(Nullable`1 OrgLocationCategoryID, String CellPhoneCountryDialingCode, String CellPhoneNumber, String FirstName, String LastName, OutputParameter`1 ErrorMessage, OutputParameter`1 SuccessMessage, OutputParameter`1 returnValue, CancellationToken cancellationToken) in C:\Users\admin\source\repos\GetInLineV6New\GetInLineV6New\Server\DbModels\GetinLineDbContextProcedures.cs:line 1217 at GetInLineV6New.Server.Controllers.OrganizationController.ValidateWalkInOTPAndGetToken(DTO_WalkinTokenRequest WalkingTokenRequest) in C:\Users\admin\source\repos\GetInLineV6New\GetInLineV6New\Server\Controllers\OrganizationController.cs:line 2458`

Here are the classes

```
public virtual async Task<List<sp_GetWalkInUserTokenResult>> sp_GetWalkInUserTokenAsync(Guid? OrgLocationCategoryID, string CellPhoneCountryDialingCode, string CellPhoneNumber, string FirstName, string LastName, OutputParameter<string> ErrorMessage, OutputParameter<string> SuccessMessage, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterErrorMessage = new SqlParameter
            {
                ParameterName = "ErrorMessage",
                Size = 500,
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.VarChar,
            };
            var parameterSuccessMessage = new SqlParameter
            {
                ParameterName = "SuccessMessage",
                Size = 100,
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.VarChar,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "OrgLocationCategoryID",
                    Value = OrgLocationCategoryID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.UniqueIdentifier,
                },
                new SqlParameter
                {
                    ParameterName = "CellPhoneCountryDialingCode",
                    Size = 5,
                    Value = CellPhoneCountryDialingCode ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "CellPhoneNumber",
                    Size = 50,
                    Value = CellPhoneNumber ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "FirstName",
                    Size = 100,
                    Value = FirstName ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "LastName",
                    Size = 100,
                    Value = LastName ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                parameterErrorMessage,
                parameterSuccessMessage,
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_GetWalkInUserTokenResult>("EXEC @returnValue = [dbo].[sp_GetWalkInUserToken] @OrgLocationCategoryID, @CellPhoneCountryDialingCode, @CellPhoneNumber, @FirstName, @LastName, @ErrorMessage OUTPUT, @SuccessMessage OUTPUT", sqlParameters, cancellationToken);

            ErrorMessage.SetValue(parameterErrorMessage.Value);
            SuccessMessage.SetValue(parameterSuccessMessage.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }




 public partial class sp_GetWalkInUserTokenResult
    {
        public Guid? TokenGUID { get; set; }
        public string TokenNumber { get; set; }
        public string OrgLocationID { get; set; }
        public Guid? OrgLocationCategoryID { get; set; }
        public string OrgLocationName { get; set; }
        public string OrgLocationCategoryName { get; set; }
        public DateTimeOffset? DateTimeIssued { get; set; }
        public string TimeZone { get; set; }
    }


```

**Comment by ErikEJ** [comment]
I need a complete repro, but doubt that this is supported, even with ADo.NET

**Comment by nssidhu** [comment]
Got Around it.

Looks like when Calling Stored Procedure your code always expect  Select Statement to be executed.
In may case based on validation i just abort the execution and Select statement is never execute.


	SELECT NULL TokenGUID,NULL TokenNumber,NULL OrgLocationID,NULL  OrgLocationCategoryID,
	       NULL OrgLocationName, NULL  OrgLocationCategoryName, NULL DateTimeIssued, 	NULL  TimeZone;

Since i have too many validation in stored procedure, instead of returning 0 form every if block , i am now throwing error from if blocks and in the catch block i return zero along the above sql.
