### ISSUE TITLE
menu entry missing in VB projects

### ISSUE THREAD

**Issue by kevin-rowe** [ErikEJ/EFCorePowerTools#1115]
Context menu not appearing in VB projects after right click.

### Steps to reproduce
install latest VS extension 2.5.758

create new VB project. console app, or WPF app.

right click project file.

no menu for EF core

### Further technical details

Database engine: PostgreSQL 9.4

Visual Studio version:  VS2019 16.11.0

**Comment by ErikEJ** [comment]
This is by design, the tool currently can only generate C# code.
