### ISSUE TITLE
Does installing SchemaCompare take a long time?

### ISSUE THREAD

**Issue by CaiusJard** [ErikEJ/EFCorePowerTools#1116]
About 10 minutes ago I chose "Compare context to database" and got an error "Installing SchemaCompare 5.1.3 please rety"..

I've tried a few times over the past 10 mins and this message appears every time. I've also tried restarting VS. My project has no build errors btw..

### Steps to reproduce
Not really sure what to put; I installed powerTools, watched a YT video where you went through some stuff at some .net conference (scaffolding, essentially - I've done that already via command line before I knew avout EFCPT) and saw a similar error come up during your vid but it seemed that install was a lot faster and the second time the command (granted, not a compare) was run it just worked..

### Further technical details
EF Core Power Tools version: says 2.5 (fresh install just now)

Database engine: Local SQLS 2017

Visual Studio version: 16.11.2

**Comment by CaiusJard** [comment]
The only other thing I've done with it, by the way, is use it to create an initial migration for my long ago scaff'd context.. It's currently in "there are migrations that haven't been applied" mode

**Comment by ErikEJ** [comment]
Have you tried manually adding that NuGet package to your project?

```
<PackageReference Include="EfCore.SchemaCompare" Version="5.1.3">
  <PrivateAssets>all</PrivateAssets>
  <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
</PackageReference>

```

**Comment by CaiusJard** [comment]
That worked, thank Erik
