### ISSUE TITLE
Results of schema compare are in a modal dialog, preventing code edit..

### ISSUE THREAD

**Issue by CaiusJard** [ErikEJ/EFCorePowerTools#1117]
Not sure if EFCPT or SchemaCompare owns the window that gives the diff result, but I note that it's a modal dialog, so it must be closed before one can use the rest of visual studio, which makes it hard to make any changes to bring differences in line..

If it's an EFCPT owned window, can it be made not modal dialog?

**Comment by ErikEJ** [comment]
It is a EFCPT window.

@sm15455  any ideas?

**Comment by ErikEJ** [comment]
Just make the changes and run the tool again...

**Comment by CaiusJard** [comment]
My point is that I can't make the changes, because it's a modal window; it's blocking visual studio. Should I open another visual studio just so I can get access to a non-blocked program?
