### ISSUE TITLE
Can EFCPT help generate entities that use varchar-backed enums?

### ISSUE THREAD

**Issue by CaiusJard** [ErikEJ/EFCorePowerTools#1119]
In some of my databases/projects I'll have an entity like:

    public partial class Order
    {
        public Order() {...}

        public int OrderId { get; set; }
        
        [Column(TypeName = "varchar(50)")]
        public OrderStatus Status { get; set; }

Namely, the column in the DB looks like `'Shipped'`, the c# enum is like `enum OrderStatus { Packed=0,Shipped=1}` etc

Ordinarily these scaffold as `public string Status { get; set; }` so what I tend to do is scaff my changes into a new folder and then use a diff tool to merge new interesting things into the "real" context models, and ignore these. Sometimes I can create partial classes e.g. if I have a method that impls a complex logic.. but there isn't anything I can really do about the properties so far as I've found

If I could add columns to an ignore list for entities (so the generated entities do not end up with those columns as props, but the context still needs to reference them e.g. `entity.Property(e => e.OrderStatus).HasMaxLength(20).IsUnicode(false);`) then I could put my customized version of the proeprty in the partial, which would be one way.. 
Having a list of "these columns are enum-strings" that maps the SQL column name to the C# enum would be nice though, and having the code generate enum-typed props with the above pattern..

**Comment by ErikEJ** [comment]
Have a look at this section of the wiki: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#choose-database-objects

**Comment by CaiusJard** [comment]
Hah, brilliant, thanks!

**Comment by CaiusJard** [comment]
(One small thing I noticed.. even when you untick a tree node, the parent node still stays with a full tick..but the checkbox at the top of the dialog is tri-state/shows a square for "some elemetns are not selected" ..)

**Comment by ErikEJ** [comment]
@sm15455 FYI

**Comment by CaiusJard** [comment]
Oh, and another thing..

I have an enum called `BatchGroup`.. And I have several tables that have a column `BatchGroup varchar(10)`:

```
ActualModel
Batch
Forecast
```

I can succefully untick "batchgroup" in the batch and forecast tables and generate no property for their entity.. But if I untick it in ActualModel I get:

> The property 'BatchGroup' cannot be added to the type 'ActualModel' because no property type was specified and there is no corresponding CLR property or field. To add a shadow state property, the property type must be specified.

It's the only table it happens with..

**Comment by ErikEJ** [comment]
No idea, I need a repro - is the column part of an index?

**Comment by CaiusJard** [comment]
Yes.. A filtered one if that's relevant..

```
CREATE UNIQUE NONCLUSTERED INDEX [FUIX_ActualModels_CI_PI_BG_A] ON [dbo].[ActualModels]
(
	[Active] ASC,
	[CompanyId] ASC,
	[ProductId] ASC,
	[BatchGroup] ASC
)
INCLUDE([ModelId]) 
WHERE ([Active]=(1))
```

**Comment by ErikEJ** [comment]
Yes, the column exclusion feature is not fully baked yet.

Alternative is to create another enum property and map back and forth.

**Comment by CaiusJard** [comment]
As part of the baking, can I request an extra couple of columns in the treeview, "Entity" and "Context" - I'd like to untick the columns for inclusion in the entity (so i can partial define them myself) but still have them put into the context; i'm finding that by not being in the context the migrations creator is getting some confusion and creating migrations that alter the columns

**Comment by ErikEJ** [comment]
Mixing migrations and reverse engineering is NOT a goal of this tool
