### ISSUE TITLE
Adding a migration always instantly brings a "Build failed" messagebox, but after some seconds the build completes and the migration is created..

### ISSUE THREAD

**Issue by CaiusJard** [ErikEJ/EFCorePowerTools#1121]
If I choose to add a migration I see the project starts to build.. Whether I wait for it to finish or not, if i make a migration (enter text and click add) I see anther build start, then instantly (within half a second) see the error below. If I wait some 5 seconds or so, I see the build finish successfully and the migration is created - it's hence no bother, once you know to just ignore the error message box..

https://user-images.githubusercontent.com/68939130/134647757-576b6258-6b7e-4be2-a129-3d416df992d4.mp4

Appreciate that there's not a lot of info to go on here; any advice on how I can log more stuff to assist with tracking anything down, just let me know

**Comment by ErikEJ** [comment]
Looks like it is related to a bug in the Interop library I use.
