### ISSUE TITLE
EFCPT thinks there are still migrations, if they are removed by the command line, but only the first time I try to add

### ISSUE THREAD

**Issue by CaiusJard** [ErikEJ/EFCorePowerTools#1122]
EFCPT doesn't seem to have ability to remove a migration at the moment so I'm using command line to do it. 

### Steps to reproduce
I *think* this is what I did... (Let me know if they didn't work)

1) make some code change/ add a prop to the context and entity
2) use EFCPT add migrationand actually fully add it with a name etc
3) do `dotnet ef migrations remove` in PM console (after cd'ing to the folder with the csproj) to remove the migration again
4) use EFCPT add migration -> "there are still migrations that haven't been added to the database"
5) click Close
6) use EFCPT add migration -> "ok, tell me the name of the migration"

#### My guess

It might be something to do with building. I think it might be that EFCPT is checking too soon (opening the window in step 3 triggers a build but this build hasn't finished by the time EFCPT decides there are still migrations). If we close the window and open again then the build triggered by step 3 is finished, and it doesn't matter that the build triggered by step 6 isn't finished because there are no changes. The second time the window is opened it asks for migration

Perhaps if we did a manual build (and let it finish) after the manual remove, EFCPT would be OK, but i didnt verify that

### Further technical details
EF Core Power Tools version: 2.5.758

Database engine:SQLS

Visual Studio version: 16.11.2

**Comment by ErikEJ** [comment]
The tool does not monitor the file system or project for changes.

**Comment by ErikEJ** [comment]
Most likely related to https://github.com/VsixCommunity/Community.VisualStudio.Toolkit/issues/158
