### ISSUE TITLE
Reverse Engineer with option "UseDbContextSplitting": true gives compiler error on generated code 

### ISSUE THREAD

**Issue by jonnybee** [ErikEJ/EFCorePowerTools#1123]
Using VS2022 og reverse engineer with target "EF Core 6 (preview) and checking option "Split DbContext into Configuration classes" - then the generated code gives compiler error. There is a mixup in which generated code for Configuration class is written to the DbContext class. My generated code fails on: 

DbContext -  OnModelCreating(): 
```
            modelBuilder.ApplyConfiguration(new Configurations.TableNameConfiguration());

            });    // Does not belong here 

            });    // Does not belong here 

            OnModelCreatingPartial(modelBuilder);
```

And in the corresponding TableConfigurationClass 
```
                entity.HasMany(d => d.ServiceParameter)
                .WithMany(p => p.ProfileParameter)
                .UsingEntity<Dictionary<string, object>>(
                    "ParameterConnection",
                    l => l.HasOne<ServiceParameter>().WithMany().HasForeignKey("ServiceParameterId").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_ParameterConnection_ServiceParameterDefinition"),
                    r => r.HasOne<ProfileParameter>().WithMany().HasForeignKey("ProfileParameterId").HasConstraintName("FK_ParameterConnection_ProfileParameterDefinition"),
                    j =>
                    {
                        j.HasKey("ProfileParameterId", "ServiceParameterId");

                        j.ToTable("ParameterConnection");

                        j.HasIndex(new[] { "ServiceParameterId" }, "IX_ParameterConnection_ServiceParameterId");

            OnConfigurePartial(entity);
```

In my project this happens on 2 Configuration classes - hence 2  * "  });" on DbContext class. 
This is likely connected to Foreign key or Index definitions. 

Correct code should be: 
```
                    j =>
                    {
                        j.HasKey("ProfileParameterId", "ServiceParameterId");

                        j.ToTable("ParameterConnection");

                        j.HasIndex(new[] { "ServiceParameterId" }, "IX_ParameterConnection_ServiceParameterId");
                    });     // Missing in code file - written in DbContext.OnModelCreating method.

            OnConfigurePartial(entity);
        }
```

### Further technical details
EF Core Power Tools version: 2.5.774.0

Database engine: SQL Server

Visual Studio version: Visual Studio 2022 Preview 4.1

**Comment by ErikEJ** [comment]
Are you good at regex?? 😀

**Comment by jonnybee** [comment]
Sorry, no. I can ask around if any of my colleagues are good at regex tho'. :-)

**Comment by jonnybee** [comment]
I assume this is in the DbContextSplitter class that splits the Configuration file from the genereated DbContext?

**Comment by ErikEJ** [comment]
Correct!

**Comment by ErikEJ** [comment]
(This is why the feature is "preview") 😄

**Comment by jonnybee** [comment]
Would it be possible to make the inner code write block end statements as  "} );" , ie: with a space. Then the Regex expression would work correctly.

**Comment by ErikEJ** [comment]
I don't control the block, sorry.

I am able to repro, but I am regex clueless...

**Comment by ErikEJ** [comment]
I can see there is also issues with the code that removes the configuration blocks, but I think I can fix that (since it is not regex!)

**Comment by ErikEJ** [comment]
I think a code based solution is better and more maintainable, let me look into that over the next few days.

**Comment by CaiusJard** [comment]
What regex(es) do you need assist with? Post them up so we can take a look..

**Comment by ErikEJ** [comment]
I am working on a non regex based solution.

**Comment by CaiusJard** [comment]
Might be a good time to mention a stray thought I had last night.. It's kinda like context splitting I think:

the onmodelcreating ends up like:

```
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
       modelBuilder.Entity<A>(entity => ...
       modelBuilder.Entity<B>(entity => ...
       modelBuilder.Entity<C>(entity => ...
```

and navigating is a bit of a nightmare.. If each one of those were put to its own method then the dropdown above the code editor could be used to more easily find the entity to tweak. Perhaps if they were overridable we could put specific customizations in a derived class - call base to do most of the config, and then do the other custom bits (it came out of the "untick certain columns in the Reverse Engineer dialog so I can customize the props in a partial" discussion..)

I'm happy for contexts to be in one file but sometimes the OnModelCreating ends up huuuuuge...

**Comment by ErikEJ** [comment]
If you have so many entities in a single DbContext you have many other issues ...

**Comment by ErikEJ** [comment]
This should now be fixed in the latest daily, please try it out (build .779 or later) and let me know

**Comment by ErikEJ** [comment]
@jonnybee @CaiusJard Any chance you can confirm the fix?

**Comment by jonnybee** [comment]
@ErikEJ yes, works fine for me now 👍
