### ISSUE TITLE
Always generate model configuration builder with HasColumnName/ToTable calls during reverse engineer

### ISSUE THREAD

**Issue by Dasein732** [ErikEJ/EFCorePowerTools#1124]
When scaffolding a DB, if a property or a class has same naming case(eg PascalCase) as its DB counterpart the HasColumnName, ToTable and similar naming constructs wont be added to the model configuration. This causes an issue when renaming domain models and generating migrations later on, since the table/column name is not hardcoded, the migration will atempt to recreate/rename those entries.

### Steps to reproduce
create a table eg:

    CREATE TABLE PartCategory(Id BIGINT NOT NULL PRIMARY KEY, PartIdentifier VARCHAR(20))

generated model:

    public class PartCategory
    {
            public long Id {get;set;}
            public string PartIdentifier {get;set;}
    }

    public class CategoryConfiguration : IEntityTypeConfiguration<PartCategory>
    {
        public void Configure(EntityTypeBuilder<PartCategory> entity)
        {
               entity.HasKey(e => e.Id)
                   .HasName("pk_Id");

              entity.Property(e => e.PartIdentifier )
                   .IsRequired()
                   .HasMaxLength(20)
                   .IsUnicode(false);
        }
    }

Attempting to rename 'PartIdentifier' to 'Identifier' or something else will cause a table rename/drop on next migration.

Desired Behaviour:

    public class PartCategoryConfiguration : IEntityTypeConfiguration<PartCategory>
    {
        public void Configure(EntityTypeBuilder<PartCategory> entity)
        {
               entity.ToTable("PartCategory")
  
               entity.HasKey(e => e.Id)
                   .HasColumnName("Id")
                   .HasName("pk_Id");
  
              entity.Property(e => e.PartIdentifier )
                   .IsRequired()
                   .HasColumnName("PartIdentifier")
                   .HasMaxLength(20)
                   .IsUnicode(false);
        }
    }

If this is not a desired behaviour out of the box for some reason, the generator should have a flag to be as explicit/verbose as possible in order to prevent 'cosmetic' changes from affecting the DB.

### Further technical details
EF Core Power Tools version: 2.5.774.0

Database engine: SQL Server 15(Prolly applies to other rel. engines)

Visual Studio version: Visual Studio 2019 16.11.3

**Comment by Dasein732** [comment]
Ideally this should also generate all of the props that are skipped due to convention.

**Comment by ErikEJ** [comment]
That is just not how the EF Core reverse engineering is designed.
