### ISSUE TITLE
EF Core 3 - namespace has extra dot Project.Data..Models

### ISSUE THREAD

**Issue by gitprohaska** [ErikEJ/EFCorePowerTools#1127]
Hi Erik, 

When reverse engineering from the project containing the context class and generating the models in a separate project the models project contains double dots separating the models namespace from the context namespace. The same thing is happening on a second computer using VS2022. 

I'm running the reverse engineer from a project that targets .NET Standard 2.0. In the screenshot below you can see that it's using separate configurations, but I have tried it without the configuration classes as well. I also have selected in the drop down on the first screen Core 3.

![image](https://user-images.githubusercontent.com/83287930/135136787-a33316bb-b285-4e9d-a508-bf8f4ee15776.png)

I've included a zip file with the project that is not working.

![EF Core Power Tools - Incorrect namespace for models](https://user-images.githubusercontent.com/83287930/135134761-eeeb93e6-c72d-4d46-aa7e-07cc73120eff.PNG)

### Steps to reproduce
I have reproduced this issue in the attached project. 

### Further technical details

![image](https://user-images.githubusercontent.com/83287930/135121949-e9f5ac63-95d0-4ef7-bd5e-8535879fcff1.png)

Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite)

SQL Server Enterprise 2016

Visual Studio version: (e.g. Visual Studio 2019 16.9)

Visual Studio Enterprise 2019
Version 16.11.3

Solution project
[NamespaceErrorSln.zip](https://github.com/ErikEJ/EFCorePowerTools/files/7246207/NamespaceErrorSln.zip)

**Comment by ErikEJ** [comment]
I assume it is this setting:

`   "OutputContextPath": ".",`

**Comment by gitprohaska** [comment]
OK, I put the dot there so that it generates the context and configuration files in the root of the Data project. If I don't put the dot there it generates the configuration files in the Models project. I was thinking that the dot would tell it to put the Data stuff in the current folder/project. 

I hope that makes sense. I don't understand how to configure Power Tools to generate the files in the correct separate projects.

**Comment by ErikEJ** [comment]
I will have a look at your solution

**Comment by gitprohaska** [comment]
Erik,

Now I have the opposite problem. Everything works except that the models now don't have the correct namespace. Doing what you've suggested puts the models in ProjectName.Data without the Models portion of the namespace. So I've reversed the problem. I liked doing it better the other way using the Context project as the root. If only it didn't add the extra dot in the namespace for the models.

![image](https://user-images.githubusercontent.com/83287930/135297403-31fc1b5b-1ec6-4f01-b558-a51256798d7a.png)

**Comment by ErikEJ** [comment]
Move "Models" down to "sub namespace"

**Comment by gitprohaska** [comment]
I can confirm that your suggestion worked. Here is the configuration that I used.

![image](https://user-images.githubusercontent.com/83287930/135305904-ec966bb2-3f72-470d-b42d-1914c0a6da34.png)

**Comment by gitprohaska** [comment]
I also want to add some more information I have when doing this in a different project. I'm using VS2022 here which I don't think makes a difference. This configuration is being run from the Context project and would work if the "using Microsoft.EntityFrameworkCore;" wasn't being included in the model classes.

![image](https://user-images.githubusercontent.com/83287930/135306653-b86d5ec9-bba3-4644-a39b-481574651247.png)

**Comment by ErikEJ** [comment]
The attributes live in that name space, I think.

**Comment by ErikEJ** [comment]
Like: InverseProperty

**Comment by gitprohaska** [comment]
It looks to me like these attributes come from System.ComponentModel.DataAnnotations.Schema. If I comment out using Microsoft.EntityFrameworkCore everything still works. The only problem I'm having with this now is that I don't know where the Index attribute comes from. Ah, I don't know why the image is so large here.

![image](https://user-images.githubusercontent.com/83287930/135309917-ef95a4a2-3528-4634-beb1-2315c3104ca2.png)

**Comment by ErikEJ** [comment]
https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.Abstractions/ !

**Comment by gitprohaska** [comment]
Ah, thank you! And now it does need the using Microsoft.EntityFrameworkCore statement for it to work. Great!

By the way, another thank you for putting together such a great utility for us! This is a lot easier to use than the CLI command when there are a lot of SQL objects to filter.

**Comment by ErikEJ** [comment]
You are welcome, I am always grateful for a review here: https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details
