### ISSUE TITLE
New Feature: Separate validation attributes from schema attributes

### ISSUE THREAD

**Issue by gitprohaska** [ErikEJ/EFCorePowerTools#1129]
I'm wondering if it's feasible to generate the validation attributes on the model classes, but then put the schema attributes/configuration in the separate configuration files. I'm not using migrations and am reverse engineering the models for any major database changes, like new tables. I want to put the schema related stuff in the separate configuration classes and have only the validation attributes on the models.

The logic would be the following
UseDataAnnotations: true && UseConfigurationFiles: true
Put the validation attributes in the model classes and the schema configurations in the configuration classes.

Erik, can you put me to the location in your code where I can look to see how it might be changed? Does anyone else have any interest in this feature addition?

**Comment by ErikEJ** [comment]
I try to avoid pulling in that code, it is maintained in the EF Core repo: https://github.com/dotnet/efcore/blob/release/6.0/src/EFCore.Design/Scaffolding/Internal/CSharpEntityTypeGenerator.cs 

(I have pulled it in for EF Core 3/5 in order to support comments)

**Comment by ErikEJ** [comment]
Actually EF Core does not have validation attributes, all attributes contribute to the model building. So this seems out of scope.

**Comment by gitprohaska** [comment]
Hi Erik,

I actually meant Schema namespace vs non-schema namespace to validation attributes. I thought of Required and StringLength as validation attributes because they are used when doing form validation. Attributes like Index, ForeignKey, Column, and InverseProperty are schema attributes.

Maybe what I asking isn't necessary but I thought it would make sense from a model design perspective to have the schema code done in the configuration classes and the non-schema attributes put directly on the properties.

As always, I appreciate your feedback.

**Comment by ErikEJ** [comment]
All these attributes do not relate to validation, but define the underlying table implementation: https://docs.microsoft.com/en-us/ef/core/modeling/entity-properties?tabs=data-annotations%2Cwithout-nrt

**Comment by gitprohaska** [comment]
Ok, I get what you're saying. I think of some of them as being validation attributes as well due to the fact that ASP.NET and Blazor use these attributes for form validation. So it's handy to have the attributes on the properties to know what validation would be done to the property. The other aspects of the properties configuration doesn't require the same attention during development of a forms based application. In any case, it seems that there isn't much interest in making this change from anyone else. I'll drop the subject.
