### ISSUE TITLE
Context menu not visible for Reverse Engineering

### ISSUE THREAD

**Issue by Zarkos69** [ErikEJ/EFCorePowerTools#113]
Hello,

The context menu item when right clicking a project is not visible. We needs this for (re)generating our models
When right clicking a DbContext file however, the 'Entity framework' contextmenu item is visible, for generation of the View.

I'm using Visual studio 2017 Professional 15.8.8 (Also tried in Community without success)
The project: .NET Framework 4.6.1 Class library c#
Connecting to a MSSQL database server

I have tried reinstalling the VSIX file, also installed latest nightly build.
Now on version: 0.9.60

The EF tools that come with the Visual studio installation are installed (& also the SQL tools)

I also tried this on a different computer, but the same issue occured.
I have also tried to use the following extension: [EntityFramework Reverse POCO Generator](https://marketplace.visualstudio.com/items?itemName=SimonHughes.EntityFrameworkReversePOCOGenerator)

Do you have any suggestions?

**Comment by Zarkos69** [comment]
Hello,

Ok I just realized I posted this in the wrong project. I was ment to post it in EntityFramework6PowerTools.

**Comment by ErikEJ** [comment]
There is no reverse engineering in the EF 6 Power Tools, see the readme: https://github.com/ErikEJ/EntityFramework6PowerTools
