### ISSUE TITLE
Add support for code generation for EF core 2 to simplify migrations for .net framework 4.8

### ISSUE THREAD

**Issue by FrankvdStam** [ErikEJ/EFCorePowerTools#1132]
Thanks for the awesome tool. Works much better than Microsoft's db-scaffold.

I'm running into issues when migrating from EF6 in .net 4.8. I can target EF core 3.0 when reversing from database - the highest version I can target in .net 4.8 is EF core 2.2.6. This means you have to do a lot of manual fixing.

Use EFCP to reverse from existing database. The lowest EFcore I can select when reversing from existing database is 3.0. This will generate the following code:
```C#
public virtual DbSet<SomeView> SomeView{ get; set; }

modelBuilder.Entity<SomeView>(entity =>
{
    entity.HasNoKey(); //This gives an error! introduced in EF core 3.0
    entity.ToView("SomeView");
});
```

However, when you are targeting the highest .net framework version (4.8) before moving to .net core or to .net 5, the highest version of EFcore you can install is 2.2.6. That means you'd have to fix the above code snippet to the following:

```C#
//Change from DbSet to DbQuery
public virtual DbQuery<SomeView> SomeView{ get; set; }

//Change from .Entity to .Query
modelBuilder.Query<SomeView>(entity =>
{
    //This line has to be disabled for all types(.Query or .Entity) - it is not only generated for views but also for entities, but only when there is no primary key defined.
    //entity.HasNoKey(); //This gives an error! introduced in 3.0
    entity.ToView("SomeView");
});
```

Seems to me these are relatively small changes but of course I don't know how it all works under the hood. This would make transitioning far easier for me though, right now I'm going through a couple 100 of these to get the model working.

**Comment by FrankvdStam** [comment]
Oh and sometimes you get this:

```C#
entity.HasKey(e => e.Id).IsClustered(false);
```

Which turns into:
```C#
entity.HasKey(e => e.Id);
//.IsClustered(false);
```

Because IsClustered was apparently also introduced in EF core 3.0

**Comment by ErikEJ** [comment]
EF Core 2.x is out of support, so I do not plan any work for that.

EF Core 3.1 runs under .NET Framework.

**Comment by FrankvdStam** [comment]
oh hell. Thanks for pointing this out. I just looked for the lowest version still supporting .net 4.8 which was 2.2.6. Guess I did all this manual work for nothing ;'(
