### ISSUE TITLE
CS0618 “RelationalIndexBuilderExtensions.HasName<TEntity>(IndexBuilder<TEntity>, string)”已过时:“Use HasDatabaseName() instead.”

### ISSUE THREAD

**Issue by hyhu928** [ErikEJ/EFCorePowerTools#1135]
i use the EF Core Power Tools to reverse sql server db, the models for tables is ok , but the  class derived from DbContext show me some warnnings:

CS0618	“RelationalIndexBuilderExtensions.HasName<TEntity>(IndexBuilder<TEntity>, string)”is Obsolete:“Use HasDatabaseName() instead.”	TodoItem	D:\Repos\NexHis.WebApi\TodoItem\Models\NorthwindContext.cs

I think the most reason is the database version

### Steps to reproduce

Use the SQL Server 2008R2 and other are normal operate

### Further technical details
EF Core Power Tools version: 2.5.774.0

Database engine: SQL Server 2008R2

Visual Studio version: (e.g. Visual Studio 2019 16.11.4)

**Comment by ErikEJ** [comment]
It is because you are running EF Core 5 reverse engineering with a EF Core 6 runtime (or similar mismatch)

**Comment by GearTheWorld** [comment]
What exactly do I have to do to get rid of the error ?

![image](https://user-images.githubusercontent.com/8614008/223203922-cd5b0c0a-f4b1-45d3-97e5-2b951aa01d23.png)

**Comment by ErikEJ** [comment]
Upgrade to .NET 6 and EF Core 6. EF Core 5 and .NET 5 are out of support.

**Comment by GearTheWorld** [comment]
Thanx
