### ISSUE TITLE
Nullable reference types and navigation properties

### ISSUE THREAD

**Issue by mohaaron** [ErikEJ/EFCorePowerTools#1136]
Hi Erik,

I'm not sure if the title is correct, but I'm having an issue with navigation properties on nullable foreign key columns. The property for the physical column is nullable int? ColumnId, but the related navigation property is not marked nullable with a question mark.

This causes an error when EF Core runs the query and I get the error: SqlNullValueException: Data is Null. This method or property cannot be called on Null values.

Without the question mark on MaintainableItem and Asset I get the above error.

        public int? MaintainableItemId { get; set; }
        [ForeignKey(nameof(MaintainableItemId))]
        [InverseProperty("Asset")]
        public virtual MaintainableItem MaintainableItem { get; set; }

        public int? ParentId { get; set; }
        [ForeignKey(nameof(ParentId))]
        [InverseProperty(nameof(Asset.InverseParent))]
        public virtual Asset Parent { get; set; }

If I manually add the question mark to make the navigation properties nullable then I don't get the above error.

        public int? MaintainableItemId { get; set; }
        [ForeignKey(nameof(MaintainableItemId))]
        [InverseProperty("Asset")]
        public virtual MaintainableItem? MaintainableItem { get; set; }

        public int? ParentId { get; set; }
        [ForeignKey(nameof(ParentId))]
        [InverseProperty(nameof(Asset.InverseParent))]
        public virtual Asset? Parent { get; set; }

Why does the reverse engineer process know to put the question mark on int? but doesn't put it on the navigation property for a nullable foreign key?

### Further technical details
EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
2.5.774

Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite)
SQL Server 2019

Visual Studio version: (e.g. Visual Studio 2019 16.9)
Visual Studio Community 2022 Preview (64-bit)
Version 17.0.0 Preview 4.1
.NET 6.0.0-rc.1.21452.10

**Comment by ErikEJ** [comment]
But are you also choosing that when generating code?

**Comment by ErikEJ** [comment]
Please try the latest daily build.

**Comment by ErikEJ** [comment]
I finally found a bug with nullable and EF Core 6, fixed in the latest daily

**Comment by mohaaron** [comment]
Hi Erik,

Thank you! It works!

**Comment by ErikEJ** [comment]
Thanks for the heads up!
