### ISSUE TITLE
Reverse Engineer - Custom Database Column Type Mapping for Postgres

### ISSUE THREAD

**Issue by jinweijie** [ErikEJ/EFCorePowerTools#1137]
Hello @ErikEJ , 

First, thanks for the great tool. We are trying to use EF Power Tools to replace the Entity Developer which we are currently using.

We are using Postgres database and for date time column, we use "timestamp with time zone". With Entity Developer, we are able to generate entity property type DateTimeOffset, which makes other parts of the application easily dealing with time zone. (We know the default mapping of NpgSql for "timestamp with time zone" is DateTime because in actual storage in Postgres is UTC date time).

I tried to customize the handlebar template, but didn't figure out how to get the actual database type property in template (also seems no clear documentation listing all the possible properties for handlebar template).

Also for efpt.config.json, I didn't see any configuration for this purpose.

So is there some possible easy way to customize the data table column type mapping?

Thanks a lot in advance.

### Steps to reproduce
1. Create a table in Postgres with some column using "timestamp with time zone".
2. Reverse engineer to C# entity class using EF Power Tools
3. The property type is DateTime.
4. Would like to have a way to customize it to DateTimeOffset.

### Further technical details
EF Core Power Tools version: 2.5.774

Database engine: Postgres

Visual Studio version: Visual Studio 2019 16.11.4

**Comment by ErikEJ** [comment]
Not sure if this is something I would like to maintain
 @roji - any ideas?

**Comment by roji** [comment]
First, note that some significant changes to timestamp mapping are coming in Npgsql 6.0 - [see this blog post](https://www.roji.org/postgresql-dotnet-timestamp-mapping) and/or [the release notes](https://www.npgsql.org/efcore/release-notes/6.0.html). The most relevant bit here is that the EF Core provider will start mapping DateTime to `timestamp with time zone` by default, and will only ever read and write DateTimes with Kind=Utc for that type.

I believe that UTC DateTime is a good way to represent a UTC timestamp in .NET (and to map to PostgreSQL `timestamp with time zone`), so once you make the switch to 6.0, having `timestamp with time zone` reverse-engineer to DateTime is actually OK. DateTimeOffset is also still supported (as long as the offset is 0), but I'm not sure there's an advantage for using that over UTC DateTime.

Aside from that, you're basically asking for a way to override the default CLR type (DateTime) for a given database type (DateTimeOffset). This kind of mapping change can generally be done via a type mapping plugin - see [this](https://github.com/npgsql/efcore.pg/blob/main/src/EFCore.PG.NodaTime/Storage/Internal/NpgsqlNodaTimeTypeMappingSourcePlugin.cs) for Npgsql's NodaTime plugin as an example. You'd basically override FindMapping to return the DateTimeOffset mapping for `timestamp with time zone` - @ErikEJ's Power Tools should pick up this change automatically.

**Comment by jinweijie** [comment]
Hi @ErikEJ and @roji , thanks for your reply.

I created a commit for this feature. It works nicely for my use case. If you please have a check? If you think it might help, I can create a PR, otherwise, I might just use a custom build, also not a big problem.

https://github.com/jinweijie/EFCorePowerTools/commit/208ea383309f420566664e29922ac26de680b73e

Thanks again.

**Comment by roji** [comment]
OK, that's understandable... In that case, you could think of some feature to allow users to override default mappings, i.e. specify that for a given database type, some arbitrary .NET CLR type should be used instead - that would take care of this. But I can't imagine there being lots of users needing this...

**Comment by ErikEJ** [comment]
Given that this can be achieved in other ways and the very low number of requests for this, using for example a partial class for the entity, this is not something that I plan to add and support.

I will revisit if demand arises.

**Comment by jinweijie** [comment]
Ok, thanks anyway. Just leave a link here in case if somebody also looking for this feature. https://github.com/jinweijie/EFCorePowerTools/commit/208ea383309f420566664e29922ac26de680b73e

Thanks.

**Comment by clintsinger** [comment]
Just to add to this.  I was looking for a way to map my code-first POCO classes to a json column and it appears the only way to do this is to exclude the json column during reverse engineering and then add it again via a partial class of the entity itself and corresponding updates to the DbContext.   

I'd would have loved it if I could have defined in the config the mapping so that each time I run the reverse engineering I get a nice and clean entity object and the appropriate initialization is handled already in the DbContext with out me having to hand write it and track it separately.

**Comment by ErikEJ** [comment]
@clintsinger this issue is closed. If you have any feature requests please create a new issue with sufficient details for me to understand what you are asking for!
