### ISSUE TITLE
Unable to scaffold aggregate columns from mssql view

### ISSUE THREAD

**Issue by tjackadams** [ErikEJ/EFCorePowerTools#1138]
When attempting to reverse engineer a dacpac with a view containing aggregate columns, the columns are not shown in the ui or the final model output.

### Steps to reproduce

Create a view in the database with some aggregate columns 

```mssql
CREATE VIEW [Reporting].[ReportStatistics]
AS
SELECT [ReportVersionId]
	,[UserId]
	,MAX(ISNULL([StartTime], [CreationTime])) AS [LastRunTime]
	,AVG(DATEDIFF(MS, [StartTime], [EndTime])) AS [AverageRunTime]
	,COUNT(1) AS [RunCount]
FROM [Reporting].[RequestAudit]
GROUP BY [ReportVersionId]
	,[UserId]
```

Go through the process of reverse engineering via the dacpac.

![image](https://user-images.githubusercontent.com/2307314/137120495-3aa4e6f5-14d9-42fb-ae17-3f56a12038eb.png)

As you can see the ReportVersionId and UserId columns are available for selection, but the LastRunTime, AverageRunTime and RunCount columns are missing.

Final Output 

```csharp
    public partial class ReportStatistic
    {
        public int ReportVersionId { get; set; }
        public int UserId { get; set; }
    }
```

```csharp
    public partial class ReportStatisticConfiguration : IEntityTypeConfiguration<ReportStatistic>
    {
        public void Configure(EntityTypeBuilder<ReportStatistic> entity)
        {
            entity.HasNoKey();

            entity.ToView("ReportStatistics", "Reporting");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ReportStatistic> entity);
    }
```

### Further technical details
EF Core Power Tools version: 2.5.774.0

Database engine: SQL Server

Visual Studio version: (e.g. Visual Studio 2019 16.9)

**Comment by ErikEJ** [comment]
Correct, this is a documented limitation of .dacpac reverse engineering: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#sql-server-database-project-dacpac-mapping 

If you can find a way of doing this, let me know.
