### ISSUE TITLE
Customize code using Handlebars adds multiple imports (TypeScript)

### ISSUE THREAD

**Issue by davidnjohansson** [ErikEJ/EFCorePowerTools#1140]
When generating TypeScript entities and there are multiple references to a type, the tool imports this type multiple times. This leads to a TypeScript error, _Duplicate identifier "Type"_

I believe it will create as many imports as there are properties belonging to a type.

````
import { Bar } from "./Bar";
import { Bar } from "./Bar";
import { Bar } from "./Bar";

export interface Foo {
    x: Bar;
    y: Bar;
    z: Bar;
}
````

### Steps to reproduce
Have a database schema and a table with at least two FK columns that references a second table. Tick "Customize code using Handlebars template (TypeScript)". This will generate a *.ts interface and it will import a reference to the second table/entity twice.

![DuplicateImports](https://user-images.githubusercontent.com/24542784/137595620-c91a1273-574a-41e5-821d-ab4d3e30c246.png)

### Further technical details
EF Core Power Tools version: 2.5.774.0

Database engine: SQL Server

Visual Studio version: Visual Studio 2019 16.11.5

**Comment by ErikEJ** [comment]
Maybe a Handlebars issue? @tonysneed

**Comment by tonysneed** [comment]
Sounds like it is. I’ll repro.
