### ISSUE TITLE
Error during reverse engineering: System.BadImageFormatException: Could not load file or assembly

### ISSUE THREAD

**Issue by DougTheCoderSA** [ErikEJ/EFCorePowerTools#1141]
When reverse engineering a SQL Server database hosted locally, I receive the error below. I have also tried reverse engineering a DACPAC file, and tried using .Net Core 3.1 and .NET 5.0 versions, and I receive the exact same error.

System.Exception: Table list error: 
Unhandled exception. System.BadImageFormatException: Could not load file or assembly 'C:\Users\Douglas\AppData\Local\Temp\efreveng5.2.5.774.0\efreveng50.dll'. An attempt was made to load a program with an incorrect format.
File name: 'C:\Users\Douglas\AppData\Local\Temp\efreveng5.2.5.774.0\efreveng50.dll'
   at List<TableModel> EFCorePowerTools.Handlers.ReverseEngineer.ResultDeserializer.BuildTableResult(string output)
   at async Task<List<TableModel>> EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.GetTablesInternalAsync(string arguments)
   at async Task<List<TableModel>> EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.GetTablesAsync(string connectionString, DatabaseType databaseType, SchemaInfo[] schemas)
   at async Task<List<TableModel>> EFCorePowerTools.Handlers.ReverseEngineer.TableListBuilder.GetTableDefinitionsAsync(CodeGenerationMode codeGenerationMode)
   at async Task<List<TableModel>> EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.GetTablesAsync(DatabaseConnectionModel dbInfo, CodeGenerationMode codeGenerationMode, SchemaInfo[] schemas)
   at async Task<bool> EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.LoadDataBaseObjectsAsync(ReverseEngineerOptions options, DatabaseConnectionModel dbInfo, Tuple<List<Schema>, string> namingOptionsAndPath)
   at async Task EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.ReverseEngineerCodeFirstAsync(Project project, string optionsPath, bool onlyGenerate)

### Steps to reproduce
1. Create a Console Application targeting .Net 5.0
2. Right-click project and select Reverse Engineer, and EF Core 5.0
3. Select either local SQL Server DB (Hosted on SQL Developer Edition) or a .dacpac file to reverse engineer
4. Click OK.

### Further technical details
EF Core Power Tools version: 2.5.774

Database engine: SQL Server - details below from SELECT @@VERSION
Microsoft SQL Server 2019 (RTM-GDR) (KB4583458) - 15.0.2080.9 (X64)   Nov  6 2020 16:50:01   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 19043: ) 

Visual Studio version: Microsoft Visual Studio Community 2019 - Version 16.11.5

Note that database contains only tables, no views, stored procs, synonyms or any other object type. Some columns do have extended properties - ie description.

**Comment by ErikEJ** [comment]
Make sure the x64 version of dotnet is the first one in your PATH

**Comment by Tksi2021** [comment]
Which "PATH" and where did you make the adjustment?

**Comment by ErikEJ** [comment]
https://www.google.com/amp/s/windowsreport.com/edit-windows-path-environment-variable/%3famp

**Comment by Tksi2021** [comment]
okay I see...
![image](https://user-images.githubusercontent.com/76532468/141504564-b984c913-4839-453c-b9e7-1b8e6b4b95af.png)

**Comment by ErikEJ** [comment]
Yes, pls follow the new link above to fix

**Comment by ErikEJ** [comment]
Closing as it is an external issue

**Comment by EnesTUTUNCU** [comment]
Even my environments are like above ss.

That still happens...

![Screen Shot 2022-06-21 at 19 42 28](https://user-images.githubusercontent.com/34237963/174854249-675d6c5a-9cca-4cf3-a60d-6d13d3517086.png)

**Comment by ErikEJ** [comment]
Do you have the 64 bit runtime installed?

   dotnet --list-runtimes

**Comment by ErikEJ** [comment]
@EnesTUTUNCU  - well, something is broken on your system.

what happens if you run efreveng60.exe from the %temp%\efreveng folder?

**Comment by EnesTUTUNCU** [comment]
@ErikEJ - That's closed as soon as i opened it, i could not see any log in events of win.

Also while trying to open it by using another app (far manager), i realized that gives an error where in ss i attached.

![Screen Shot 2022-06-22 at 11 04 50](https://user-images.githubusercontent.com/34237963/174977334-b93a70c6-9f98-483b-be9c-0fce0a8cb557.png)

**Comment by ErikEJ** [comment]
@EnesTUTUNCU Sorry, the proper way to test is:

    dotnet efreveng60.dll

**Comment by ErikEJ** [comment]
@EnesTUTUNCU yes  that is because dotnet only can find the x86 runtime. Try to repair/ re-install

**Comment by EnesTUTUNCU** [comment]
@ErikEJ i did not get, what should i repair/re-install? If you say dotnet, i've re-installed below setup of dotnet.

https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-6.0.301-windows-x64-installer

**Comment by ErikEJ** [comment]
Yes, that was my proposal

**Comment by intranettechnology** [comment]
Mr Erik,

I really wanna mention something else for everyone.

Actually my issue was special.

I use a virtual os on Mac by using parallel desktop.

Also use a Mac which has M1 chip. That's why the windows is ARM64.

To be able to figure that out, while adding that Dotnet path to system variables. It must be like in the following.

C:\Program Files\dotnet\x64

It was: C:\Program Files\dotnet\
It is: C:\Program Files\dotnet\x64\

And then your tool works properly.

Best regards,

Enes
