### ISSUE TITLE
Temporal tables using 6.0 preview.

### ISSUE THREAD

**Issue by Gerry30** [ErikEJ/EFCorePowerTools#1143]
Describe what is not working as expected.
I created a new test blazor project and used 6.0 preview to create entity classes and context file using 6.0 preview and minimal choices against a sql data base with temporal tables  the the table typically are schema  table  guid text other relation ships then 
similar to 
/****** Object:  Table [Contact].[Contact]    Script Date: 19/10/2021 9:02:45 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [Contact].[Contact](
	[Id] [uniqueidentifier] NOT NULL,
	[ContactId] [int] NOT NULL,
	[CourtesyID] [uniqueidentifier] NULL,
	[GenderID] [uniqueidentifier] NULL,
	[FirstName] [nvarchar](35) NULL,
	[LastName] [nvarchar](35) NULL,
	[DateOfBirth] [datetime2](7) NULL,
	[Image] [varbinary](max) NULL,
	[Avatar] [image] NULL,
	[TId] [int] IDENTITY(1,1) NOT NULL,
	[TenantID] [uniqueidentifier] NULL,
	[Active] [bit] NULL,
	[Deleted] [bit] NULL,
	[CreatedBy] [uniqueidentifier] NULL,
	[LastModifiedBy] [uniqueidentifier] NULL,
	[LastModified] [datetimeoffset](7) NULL,
	[SysStartTime] [datetime2](7) GENERATED ALWAYS AS ROW START NOT NULL,
	[SysEndTime] [datetime2](7) GENERATED ALWAYS AS ROW END NOT NULL,
 CONSTRAINT [PK_Contact] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
	PERIOD FOR SYSTEM_TIME ([SysStartTime], [SysEndTime])
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
WITH
(
SYSTEM_VERSIONING = ON ( HISTORY_TABLE = [Contact].[ContactHistory] )
)
GO

ALTER TABLE [Contact].[Contact] ADD  DEFAULT (newid()) FOR [Id]
GO

ALTER TABLE [Contact].[Contact] ADD  CONSTRAINT [DF_Contact_Active]  DEFAULT ((1)) FOR [Active]
GO

ALTER TABLE [Contact].[Contact] ADD  CONSTRAINT [DF_Contact_LastModified]  DEFAULT (sysdatetimeoffset()) FOR [LastModified]
GO

ALTER TABLE [Contact].[Contact] ADD  CONSTRAINT [DF_Contact_SysStartTime]  DEFAULT (sysutcdatetime()) FOR [SysStartTime]
GO

ALTER TABLE [Contact].[Contact] ADD  CONSTRAINT [DF_Contact_SysEndTime]  DEFAULT (CONVERT([datetime2],'9999-12-31 23:59:59')) FOR [SysEndTime]
GO

ALTER TABLE [Contact].[Contact]  WITH CHECK ADD  CONSTRAINT [FK_Contact_ContactCourtesy] FOREIGN KEY([CourtesyID])
REFERENCES [Reference].[ContactCourtesy] ([Id])
GO

ALTER TABLE [Contact].[Contact] CHECK CONSTRAINT [FK_Contact_ContactCourtesy]
GO

ALTER TABLE [Contact].[Contact]  WITH CHECK ADD  CONSTRAINT [FK_Contact_ContactCreatedBy] FOREIGN KEY([CreatedBy])
REFERENCES [Contact].[Contact] ([Id])
GO

ALTER TABLE [Contact].[Contact] CHECK CONSTRAINT [FK_Contact_ContactCreatedBy]
GO

ALTER TABLE [Contact].[Contact]  WITH CHECK ADD  CONSTRAINT [FK_Contact_ContactGender] FOREIGN KEY([GenderID])
REFERENCES [Reference].[ContactGender] ([Id])
GO

ALTER TABLE [Contact].[Contact] CHECK CONSTRAINT [FK_Contact_ContactGender]
GO

ALTER TABLE [Contact].[Contact]  WITH CHECK ADD  CONSTRAINT [FK_Contact_ContactLastModifiedBy] FOREIGN KEY([LastModifiedBy])
REFERENCES [Contact].[Contact] ([Id])
GO

ALTER TABLE [Contact].[Contact] CHECK CONSTRAINT [FK_Contact_ContactLastModifiedBy]
GO
### Steps to reproduce
Include a complete description that I can redo to reproduce the issue.
if you build with latest general release you get an error in the context  you get an error at ( tb => tb 
 CS1660: Cannot convert lambda expression to type 'string' because it is not a delegate type. on all temporal tables 
         modelBuilder.Entity<Contact>(entity =>
            {
                entity.ToTable("Contact", "Contact");

                entity.ToTable(tb => tb.IsTemporal(ttb =>
    {
        ttb.UseHistoryTable("ContactHistory", "Contact");
        ttb
            .HasPeriodStart("SysStartTime")
            .HasColumnName("SysStartTime");
        ttb
            .HasPeriodEnd("SysEndTime")
            .HasColumnName("SysEndTime");
    }
));

                entity.Property(e => e.Id).HasDefaultValueSql("(newid())");

                entity.Property(e => e.Active).HasDefaultValueSql("((1))");

                entity.Property(e => e.Avatar).HasColumnType("image");

                entity.Property(e => e.CourtesyId).HasColumnName("CourtesyID");

                entity.Property(e => e.FirstName).HasMaxLength(35);

                entity.Property(e => e.GenderId).HasColumnName("GenderID");

                entity.Property(e => e.LastModified).HasDefaultValueSql("(sysdatetimeoffset())");

                entity.Property(e => e.LastName).HasMaxLength(35);

                entity.Property(e => e.TenantId).HasColumnName("TenantID");

                entity.Property(e => e.Tid)
                    .ValueGeneratedOnAdd()
                    .HasColumnName("TId");

                entity.HasOne(d => d.Courtesy)
                    .WithMany(p => p.Contacts)
                    .HasForeignKey(d => d.CourtesyId)
                    .HasConstraintName("FK_Contact_ContactCourtesy");

                entity.HasOne(d => d.CreatedByNavigation)
                    .WithMany(p => p.InverseCreatedByNavigation)
                    .HasForeignKey(d => d.CreatedBy)
                    .HasConstraintName("FK_Contact_ContactCreatedBy");

                entity.HasOne(d => d.Gender)
                    .WithMany(p => p.Contacts)
                    .HasForeignKey(d => d.GenderId)
                    .HasConstraintName("FK_Contact_ContactGender");

                entity.HasOne(d => d.LastModifiedByNavigation)
                    .WithMany(p => p.InverseLastModifiedByNavigation)
                    .HasForeignKey(d => d.LastModifiedBy)
                    .HasConstraintName("FK_Contact_ContactLastModifiedBy");
            });

### Further technical details
EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)

Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite)

Visual Studio version: (e.g. Visual Studio 2019 16.9) vs studio 2022 rc  sql 2016 v 18.7.1

thanks Gerard

**Comment by ErikEJ** [comment]
Closing, feel free to re-open if you can provide a proper repro
