### ISSUE TITLE
Data/Datum/Datas inconsistency in pluralizer

### ISSUE THREAD

**Issue by aterbo** [ErikEJ/EFCorePowerTools#1146]
When using the pluralizer, the word 'data' is treated inconsistently. 

Our Db has plural table names, with one table in question named UserData. We consider 'data' to be both single and plural by our naming convention. We don't use 'datum'.

When I reverse engineer using the normal pluralizer (I believe it's Humanizer?) it converts UserData to UserDatum, which is not the desired outcome. So, I use the option for the EF6 pluralizer which creates the proper UserData object class.

However, in the created AppContext, the DbSet property name for the model converts 'UserData' to 'UserDatas' as follows:

```
public virtual DbSet<Subproject> Subprojects { get; set; }
public virtual DbSet<Territory> Territories { get; set; }
public virtual DbSet<UserData> UserDatas { get; set; }  
```

Is it possible to configure the pluralizer (either with or without the EF6 option) to treat 'data' as both single and plural?

### Steps to reproduce
Create a Db table named Data and reverse engineer with the EF6 pluralizer option

### Further technical details
EF Core Power Tools version: 2.5.774

Database engine: SQL Server

Visual Studio version: Visual Studio 2019 16.11.5

**Comment by ErikEJ** [comment]
You can try the Use database names option.

For the renaming feature, please have a look at the docs in the wiki.

**Comment by ErikEJ** [comment]
Datum issue fixed in latest daily build
