### ISSUE TITLE
Reverse Engineer has a couple issues

### ISSUE THREAD

**Issue by jbeschler** [ErikEJ/EFCorePowerTools#1148]
Hi,
If you use Reverse Engineer for multiple Contexts, the second (and I assume succeeding) contexts overwrite the first.

Also, if you use Reverse Engineer to add one item, the process deletes all previous items in the folder.

### Steps to reproduce
For the first issue:
In a project select Reverse Engineer and follow the steps to RE a database. Then, repeat those steps with a different database. The Context.cs file from the first RE will disappear.

For the second issue:
Run RE again on an existing Context/Database in your project and select a new item in the DB. When RE finishes any entities in the folder will disappear. 

### Further technical details
Version is: 2.5.774.0

Database engine: SQL Server

Visual Studio version: Visual Studio 2019 16.11.5

**Comment by ErikEJ** [comment]
Just generate the code in seperate project folders - and there are additional tips here: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#using-multiple-dbcontexts-in-the-same-project
