### ISSUE TITLE
Can't reverse engineer due to "System.Exception: Table list error"

### ISSUE THREAD

**Issue by jwatkin** [ErikEJ/EFCorePowerTools#1158]
Sometimes when I attempt to reverse engineer a Microsoft SQL Server database, I get this error message after selecting the database/login from the Power Tools dropdown menu and clicking OK:
**System.Exception: Table list error: 
System.InvalidCastException: Unable to cast object of type 'System.DBNull' to type 'System.String'.**

I think, but I'm not certain, it might be because for one of the tables in the database, the database user account doesn't have permission for all of its columns, only some columns. The other columns in this table are restricted.

### Steps to reproduce
Attempt to reverse engineer a database with a user account that for at least one table doesn't have permission to some of its columns. When the reverse engineering process begins, select the database/login from the initial dialog's dropdown menu then click "OK". The exception message will appear in the Visual Studio output pane, set to "Show output from: Extensions".

### Further technical details
EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
2.5.774

Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite)
SQL Server

Visual Studio version: (e.g. Visual Studio 2019 16.9)
Microsoft Visual Studio Enterprise 2019
Version 16.11.5

**Comment by ErikEJ** [comment]
Please start by making sure the user has view definition, and check using the method used by Power Tools

**Comment by jwatkin** [comment]
Hi Erik,

Good news. I've done some experiments with additional database accounts and the issue seems to be just like you said, missing VIEW DEFINITION permissions.

My original suspicion was incorrect. Whether or not an account has SELECT permission on all of the columns of a table has nothing to do with it. I was able to reverse engineer a table for which the account has no SELECT permission but has VIEW DEFINITION permissions for the entire database.

Earlier, I think I was misreading sp_helprotect. The original problem account did have VIEW DEFINITION permission on the table I suspected was the problem, due to a lack of SELECT permissions for 4 of its columns, but it lacked VIEW DEFINITION permissions on the entire database. The account that works has VIEW DEFINITION permissions on the entire database, the way I read what looks like a wildcard symbol '.'.

I did these final experiments with .NET 5.x, EF Core 5.x, Visual Studio 2019.x, and EF Core Power Tools 2.5.804. Is that combination OK to continue to use? I'm hoping I can wait until the official release of .NET 6 and Visual Studio 2022 before I upgrade.

Thank you so much for your support.

Jim

**Comment by ErikEJ** [comment]
So in closing:
- The SQL user account running reverse engineering only needs 'VIEW DEFINITION' rights on database level.
- This can be confirmed by running: `SELECT HAS_PERMS_BY_NAME(DB_NAME(), 'DATABASE', 'VIEW DEFINITION');` when logged on as that user.
- The check above is also executed by Power Tools, and is a useful check.
- There is no need for access to data, so db_datareader access or SELECT permissions ar not required.

**Comment by ErikEJ** [comment]
And yes, you can stay on EF Core 5, that is not important for this issue.

**Comment by ErikEJ** [comment]
I have updated the docs here: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#requirements
