### ISSUE TITLE
Context Microsoft.EntityFrameworkCore error 

### ISSUE THREAD

**Issue by smarteez17** [ErikEJ/EFCorePowerTools#1166]
I create a Class Library  with Target Framework of net 5.0 and then used the tool to create my context and entities. After the tool completed I am getting errors on my Context 

using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;

I tried installing them and still doesnt work. what am I doing wrong here 

Please help

**Comment by smarteez17** [comment]
Here is the error I am getting 
Package Microsoft.EntityFrameworkCore 6.0.0 is not compatible with net5.0 (.NETCoreApp,Version=v5.0). Package Microsoft.EntityFrameworkCore 6.0.0 supports: net6.0 (.NETCoreApp,Version=v6.0)

**Comment by ErikEJ** [comment]
I am most likely auto installing 6, just edit your project to use 5.

**Comment by ErikEJ** [comment]
You need to install EF Core NuGet package in your project!

**Comment by smarteez17** [comment]
Hi What version as version 6.0.0 doesnt work and I throught by checking this it will auto install 

![image](https://user-images.githubusercontent.com/35128168/140942301-6ddd2dfb-8dee-4952-b83c-b5e02e676e5d.png)


![image](https://user-images.githubusercontent.com/35128168/140942101-e41f74ae-3baf-4d18-acc1-368828edc81e.png)

**Comment by ErikEJ** [comment]
I will try to improve the experience

**Comment by smarteez17** [comment]
thank you I had to install ef core  version 5 and ef core Sql to get it to work 

Also something else I picked up it created diff name for Objects when it created the classes for example I have a store Table that link to country and Provinces it create them as Link1 and Link2 in the store class . I check my db and no were I have anything named linked 1 and link 2

**Comment by ErikEJ** [comment]
Please create a new issue with repro details for your second issue.
