### ISSUE TITLE
Options located in VS context menu are gone probably after VS update

### ISSUE THREAD

**Issue by krzysiek-b** [ErikEJ/EFCorePowerTools#1169]
Describe what is not working as expected.

### Steps to reproduce

Please right click on configuration file.
Please notice the Edit and refresh options are gone.

### Further technical details

This seems not work both on VS2022 17.0 and VS2019 (latest update)
I'm not sure if this is connected to extension update as I have the auto update option on.

**Comment by ErikEJ** [comment]
Fixed in latest daily - will update official release soon
