### ISSUE TITLE
Stored procedure return type

### ISSUE THREAD

**Issue by giarico** [ErikEJ/EFCorePowerTools#1171]
When you select a stored procedure, its return type is not generated if you select the option EntityTypes only.
It is generated if you select DBContext only.

I think it should be the opposite.

EF Core version in use: EF Core 6

EF Core Power Tools version: latest

Database engine: SQL Server

Visual Studio version: Visual Studio Community 2022

**Comment by ErikEJ** [comment]
The stored procedures depend on the DbContext...

**Comment by giarico** [comment]
But the generated object is just a simple class.
It has no dependency on entity framework.

**Comment by ErikEJ** [comment]
True, but this is not currently a feature in stored procedure support.

**Comment by ErikEJ** [comment]
Also, the result classes are not entity types! (They are not part of your DbContext)
