### ISSUE TITLE
Using multiple DbContexts in the same project

### ISSUE THREAD

**Issue by JimF42** [ErikEJ/EFCorePowerTools#1172]
### Perceived Issue

In https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#using-multiple-dbcontexts-in-the-same-project it seems to imply that multiple DbContexts can be in the same project (while having them in separate projects is preferable).

Each DbContext has a unique name, but shared the same Models and Data folders.  I can work around the issue by also supplying a unique Models and Data folder name. For example, Db1Models, Db2Models, etc. This technique causes a duplicate DbContextExtensions file to be created--duplicate other than the namespace it is in.

Also, the documentation states there should be a right-click context menu for the efpt.*.config.json files for Edit and Refresh, and they do not exist in either VS 2019 or 2022.

### Steps to reproduce

Create a new command line project and add a new DbContext via _Reverse Engineer_. I had to use a separate project to create a second DbContext as there doesn't appear to be anyway of doing this directly in the current UI.  I then copied over the new efpt.*.config.json and then generated it again after picking the new config.  It created the new DbContext, but also deleted the other one.

### Further technical details

EF Core version in use: EF Core 6

EF Core Power Tools version: 2.5.815.0

Database engine: SQL Server

Visual Studio version: Visual Studio 2019 16.11.6 & Visual Studio 2022 17.0.0

**Comment by ErikEJ** [comment]
Maybe this doc snippet needs to be improved?

>> To generate code for multiple DbContexts in the same project, make sure to use a separate project folder for each DbContext, so the files do not overlap and get overwritten.

>> there should be a right-click context menu for the efpt.*.config.json

Yes, this was broken due to an unfortunate breaking change in a dependency, fixed in latest daily, which will soon become official release

>> I had to use a separate project to create a second DbContext as there doesn't appear to be anyway of doing this directly in the current UI.

Correct, it is not somethin I want to promote, but moving or renaming the first efpt.config.json before creating the second DbContext will remove the need for a seperate project.

**Comment by JimF42** [comment]
Yes, that sounds good. Now, about the duplicate DbContextExtensions.cs file. As an enhancement, how about under Advanced..., an option under Code generation to remove/suppress DbContextExtensions.cs. If I override the sub-namespace and make them the same (that is, both generically Models and Data) I end up with an error pointing out that I have one already. Ideally it would be nice to have the code generator see that there's multiple efot.*.config.json files and do it automagically, but I could settle for a check box and suppress them that way.

I'm new to EF (former diehard LINQ to SQL person) and I use stored procedures extensively. Your project has been a wonderful find for me so I can "move on from L2S"!

Thanks.

**Comment by ErikEJ** [comment]
I have updated the docs slightly.

I think the right way to approach the DbContextExtensions issue would be to install a Nuget package that provides the required extension methods in the project.

**Comment by ErikEJ** [comment]
@JimF42 Just to be clear, are you getting errors because of the duplicate DbContextExtensions.cs file?

**Comment by JimF42** [comment]
@ErikEJ Yes, that is correct. I have otherwise got the two DbContexts running in the same project, but I need to delete one of the DbContextExtensions.cs files.

By the way, as I mentioned before, I'm new to EF (core or otherwise), but I see that EF 6 supports stored procedures with multiple result sets returned. Do you know if EF Core supports that, and if so, do you support that?

**Comment by ErikEJ** [comment]
@JimF42 Do they not have separate / different name spaces? 

>> but I see that EF 6 supports stored procedures with multiple result sets returned. Do you know if EF Core supports that, and if so, do you support that?

No (EF Core does not support any stored procedure mapping) and no (I cannot get metadata about additional result sets, but if you know how to do that....).

**Comment by JimF42** [comment]
@ErikEJ "... **_but if you know how to do that_** ..." as in independent of EF? Yes, I do. I will have to dig up the source code for it though.  Then, you would have to have a way similar to EF 6 and Linq to SQL to say that the sproc is returning multiple resultsets and not just a single.  In L2S it was done via a parent object (`System.Data.Linq.IMultipleResult`). You then called `GetResult<TElement>` to get the result sets. See [IMultipleResults](https://docs.microsoft.com/en-us/dotnet/api/system.data.linq.imultipleresults?view=netframework-4.8) for details.

If you are interested in the code for getting the schema, I can see if I can dig it up.  You are probably already doing most of the work already, you just need to see if there's any more result sets.

**Comment by JimF42** [comment]
@ErikEJ I just realized that I never answered you first question.  No, the DbContexts are not in separate namespaces.  I only have them in separate folders because that is what you software requires, but I took advantage of your override to put them into the same namespace. Other than the one extensions file, they all play happily in the same namespace.

**Comment by ErikEJ** [comment]
If you had separated by name space, I think everything would work fine.

If there are multiple results, I will probably just add a class to hold multiple lists. But looking forward to seeing how. I use sp_describe_first_resultset currently.

**Comment by JimF42** [comment]
@ErikEJ 

> If you had separated by name space, I think everything would work fine.

Yup, understood.  I just didn't want that many different namespaces. I will just continue to delete the extra file(s).

So, as far as decoding the multiple result set, I did it differently than you did. First, a bit of background. I was a die-hard Linq to SQL user, but it had a flaw when using SQLMetal. It would mark fields in the result set as nullable even though they weren't, so I had a program that read in the DBML file, figured out everything that was in there (it was selective) and queried the database for the correct states.  

So, in general what I did was read the DBML for what parameters the stored procedures needed, created a SqlCommand to execute the procedure, but ran it like this:
`schmeaReader = sqlCommand.ExecuteReader(CommandBehavior.SchemaOnly);`

Then, I spun though all of the result sets and fixed up the columns that needed fixing.

> How To Retrieve Column Schema by Using the DataReader GetSchemaTable Method and Visual C# .NET
> http://support.microsoft.com/kb/310107/EN-US/
> http://msdn.microsoft.com/en-us/library/system.data.sqlclient.sqldatareader.getschematable.aspx

I will see if I can post some sample code a bit later.

**Comment by JimF42** [comment]
Here's the code snip. 

[GetSPResultsetSchema.zip](https://github.com/ErikEJ/EFCorePowerTools/files/7583428/GetSPResultsetSchema.zip)

It was taken directly from my app I described above, so it contains some extra code for handling the .DBML XML file that you will have to discard. You will also need a way of discovering the stored procedure's parameters to execute them. For me, it came from the DBML file.

This code also handles Table Valued Functions (via the Select ...) but you will not have to worry about that--only stored procedures can return multiple results.

I also didn't have to worry about generating the c# code. After I patched the DBML file up, I just ran SQLMetal to generate the code from the corrected DBML file.

**Comment by ErikEJ** [comment]
Fantastic - this is the missing piece in stored procedure support in EF Core Power Tools!

Let's create a new issue and discuss design and challenges.

This will definitely be  an opt-in feature, as the tool now executes user code!

**Comment by JimF42** [comment]
@ErikEJ, Great! 

> "Let's create a new issue ..."  ??

 Does that mean you or me?? I don't mind either way--just let me know if you want me to create it.

Thanks

**Comment by ErikEJ** [comment]
Feel free to do it, and link back to important comments in this issue.
