### ISSUE TITLE
#nullable Warning	 

### ISSUE THREAD

**Issue by smarteez17** [ErikEJ/EFCorePowerTools#1174]
Hi There I am getting this Warning	 after running the tool 

The annotation for nullable reference types should only be used in code within a '#nullable' annotations context. Auto-generated code requires an explicit '#nullable' directive in source.

**Comment by ErikEJ** [comment]
Please provide a proper issue description!
Which EF Core  version?
Using handlebars
Project file settings

Also, there was a rollback of something related to this in the latest daily, please try it out and let me know.

**Comment by smarteez17** [comment]
EF Core : 6 
handelbars : No 
VS :2022

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.0" />
  </ItemGroup>

</Project>


I tried rerunning it same warning message

**Comment by ErikEJ** [comment]
Did you try the latest daily?

**Comment by smarteez17** [comment]
Hi @ErikEJ  how do I access the lastest daily ?

**Comment by ErikEJ** [comment]
https://github.com/ErikEJ/EFCorePowerTools#daily-build

**Comment by ErikEJ** [comment]
So the daily build fixed this?

**Comment by smarteez17** [comment]
Yes it did thank you
