### ISSUE TITLE
import the Database its setting the relationship incorrectly

### ISSUE THREAD

**Issue by smarteez17** [ErikEJ/EFCorePowerTools#1175]
In my database I have a Orders table and OrdersItems Table where the relationship is One order to many orderItems

![image](https://user-images.githubusercontent.com/35128168/141453242-9e06e713-d73e-4a44-86b0-abb6f2fab799.png)

When using the tool to import the Database its setting the relationship incorrectly

**Incorrect way** 
**In the Order Class** 
there nothing linking the table 

**In the OrderItem Class**
   public virtual Order Order { get; set; }

**Correct way** 

**In the Order Class**
   public virtual ICollection<OrdersItem > OrdersItemS { get; set; } 

**In the OrderItem Class**
  public virtual Order Order { get; set; } 

So when I call the like this 
  var Lst =  context.Orders.FirstOrDefault().OrderItems.toList();

**Comment by smarteez17** [comment]
I pick up something very interesting If the child table has a primary key then the relationship after using the tool is correct. Will you have able to accommodate both designs styles

**Comment by ErikEJ** [comment]
Foreign key relationships need a primary key, this is by design
