### ISSUE TITLE
updating configuration classes 

### ISSUE THREAD

**Issue by smarteez17** [ErikEJ/EFCorePowerTools#1179]
After using the tool I can split the configuration is a folder but this folder is inside Context folder. Would it be possiable to move it outside context ?

After running the tool I went to the db and made some chnages and deleted a table then run the too. In my entities folder the old table/ class was remove however in the configuration folder it still had a configuration class for the removed tables/Class I had to remove it manually 

EF Core : 6
handelbars : No
VS : 2022

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.0" />
  </ItemGroup>
```

</Project>

**Comment by ErikEJ** [comment]
>> Would it be possiable to move it outside context ?

Sure, you can move them whereever you please after code  generation. Setting a location is not something I plan to implement for this preview feature (waiting for proper implementation in EF Core)

I have had some pushback and bugs relating to removal of obsolete files, so a one time manual removal seems a better solution for the time being.
