### ISSUE TITLE
Choose Database Objects not updating 

### ISSUE THREAD

**Issue by smarteez17** [ErikEJ/EFCorePowerTools#1180]
I am making changes to the database by adding and/or removing tables but the tool is not updating the Choose Database Objects section old tables are still there and the new tables are not 

EF Core : 6
handelbars : No
VS :2022

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.0" />
  </ItemGroup>
```

</Project>

**Comment by ErikEJ** [comment]
Sounds like you are looking at the wrong database then.

**Comment by smarteez17** [comment]
I am not when I make changes to exisit table like add or remove columns it picks up ( I only have one database on the server )

**Comment by smarteez17** [comment]
I unstalled the tool and downloaded the daily updates one and it working now

**Comment by ErikEJ** [comment]
Does the new table have a primary key?

**Comment by smarteez17** [comment]
Yes it does
