### ISSUE TITLE
Reverese engineering - Table model is renamed? 

### ISSUE THREAD

**Issue by tadrian** [ErikEJ/EFCorePowerTools#1181]
Describe what is not working as expected.

I am doing reverese engineering and I am selecting a table named FrmData , but the model created is called FrmDatum
All other tables are named ok. I have no table named FrmDatum in MS SQL Database

is there a limitation for tables with Data in the name?

VS2022 EF 6

**Comment by ErikEJ** [comment]
It is by design, disable the pluralizer or maybe rename the entity?

**Comment by ErikEJ** [comment]
Duplicate of #1146
