### ISSUE TITLE
Right-click options on context menu don't do anything 

### ISSUE THREAD

**Issue by MisinformedDNA** [ErikEJ/EFCorePowerTools#1182]
Right-click options on context menu don't do anything 

### Steps to reproduce

1. Open a solution with a efpt.config.json in either VS2019 or VS2022
2. Right-click efpt.config.json and click "EF Core Power Tools - Edit"

No UI comes up. Nothing happens.

### Workaround

Right-click on project -> EF Core Power Tools -> Reverse Engineer

### Further technical details

EF Core version in use: EF Core 5

EF Core Power Tools version: 2.5.821

Database engine: SQL Server

Visual Studio version: Visual Studio 2019 16.11 and VS 2022

**Comment by ErikEJ** [comment]
My bad - fixed in latest daily
