### ISSUE TITLE
Not selecting a table is deleting the entity during reverse engineering?

### ISSUE THREAD

**Issue by thenrich2009** [ErikEJ/EFCorePowerTools#1186]
When I select the tables I want to add and not select the other tables, the tool is deleting the entitites for the unselected tables. I don't expect this to happen and do not like this destructive behavior. When I select tables, I am specifically telling the tool to take action on those tables and leave everything else alone. Maybe I have tables that go updated in the database yet I still want the entities not to be updated. There could be other examples too.

How about having another checkbox column for deleting the entities? Deleting an entity is not a common use and it's destructive so it's best to have options for this behavior in the UI where the user specifically tells the UI to delete.

Also, I didn't understand what the workaround is from this similar issue:
[https://github.com/ErikEJ/EFCorePowerTools/issues/412](https://github.com/ErikEJ/EFCorePowerTools/issues/412)

**Comment by ErikEJ** [comment]
This is by design, as documented here https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#saving-options-and-running-the-second-time - basically you should no edit the generated files.

You may also be able to use the advanced option show here: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#advanced-visual-studio-options (Run cleanup of obsolete files)

**Comment by thenrich2009** [comment]
I am not editing the generated files. The tool is touching and making changes to entities I didn't select. If I add an index to a table, I don't want it to add it to the dbContext file. 

How do I tell the tool to ignore a whole bunch of tables and not to make changes to their entities and not to make changes in the dbcontext file for them? The UI/UX in the tool looks like an anti pattern. When I select reverse engineer and the tool asks me to select the database objects to reverse engineer, it simply means the objects I selected are the objects I want to reverse engineer. It should not touch the objects I didn't select.

**Comment by ErikEJ** [comment]
Have you tried the advanced option?

I that does not fit the bill, please explain the workflow you are wanting in more detail. 

But as I said, this is probably by design, as reverse engineering is an all or nothing proposition.

**Comment by thenrich2009** [comment]
There are 11 checkboxes in the advanced option. None of them indicates to not delete an entity.
Can you be more specific about the advanced option?

There's no workflow to explain more. If you say it's an all or nothing proposition then I guess there's not much to do.

**Comment by ErikEJ** [comment]
>> Can you be more specific about the advanced option?

Sure, like I already mentioned above: You may also be able to use the advanced option show here: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#advanced-visual-studio-options (Run cleanup of obsolete files)

**Comment by thenrich2009** [comment]
I don't see a Run cleanup of obsolete files option. Using the browser's find, even the words 'cleanup' and 'obsolete' don't exist on the page you linked. What does cleaning up obsolete files have to do with leaving existing entities alone?

I feel you're not understanding what I am saying.

I just used the tool to reverse engineer and wanted to just include the two tables I modified in the database and it deleted 50 entities. This is super annoying!  The UI is not intuitive.

Never mind. I will just do the changes manually. It's much simpler and without annoying surprises.

**Comment by ErikEJ** [comment]
The option is in Tools/Options in Visual Studio.

Sorry to hear you are having a bad experience with this free tool, which has more than 100.000 users, that have never reported issues similar to yours.

Suggest you read through the wiki to understand how the tool works.

**Comment by ErikEJ** [comment]
Or watch the videos?

Or join me fir a Teams session, so we can share screens?
