### ISSUE TITLE
Completion dialog missing in EF Core 6

### ISSUE THREAD

**Issue by GearTheWorld** [ErikEJ/EFCorePowerTools#1189]
Describe what is not working as expected.
When a [**Reverse Engineer**] is completed there's no dialog saying it's completed like before so we never know when it finishes
 
### Steps to reproduce
Reverse Engineer anything you wish

Please include a complete description that I can redo to reproduce the issue.

1. Start EF Core Power tool
2. Connect to a database and select EF Core 6 in the drop down list
3. Select something a table or a stored procedure
4. Complete the reverse operation

### Further technical details

EF Core version in use: (e.g. EF Core 5)
EF Core 6

EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
2.5.832.0

Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)
MS SQL

Visual Studio version: (e.g. Visual Studio 2019 16.11)
Microsoft Visual Studio Community 2022 (64-bit) 
Version 17.0.1

**Comment by ErikEJ** [comment]
It should be visible in the status bar...

**Comment by GearTheWorld** [comment]
Wow, it's not obvious.
Thank you!
