### ISSUE TITLE
'OutputParameter<int?>._value' is inaccessible due to its protection level

### ISSUE THREAD

**Issue by Bhasyakarulu** [ErikEJ/EFCorePowerTools#1190]
With the latest version of our tool, DB context erroring out with the following error: 'OutputParameter<int?>._value' is inaccessible due to its protection level

### Steps to reproduce

Any Stored Procedure that has out parameter.

### Further technical details

EF Core version in use: (e.g. EF Core 5)

EF Core Power Tools version: 2.5.832

Database engine: SQL Server

Visual Studio version: Visual Studio 2019 16.11.7

**Comment by ErikEJ** [comment]
I thought I had fixed that. Could you try the latest daily?

**Comment by Bhasyakarulu** [comment]
When I click on daily build, 404 error page displaying. https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f

**Comment by ErikEJ** [comment]
Works fine for me. 

But I will check build 832 tomorrow, in the meantime you can just make it public.

**Comment by Bhasyakarulu** [comment]
Many thanks, appreciated!

**Comment by ErikEJ** [comment]
I am not able to repro with build .832, try to clear the files and regenerate

**Comment by Bhasyakarulu** [comment]
It is working now, thank you!
