### ISSUE TITLE
EF Core 6 - Reverse Engineer skips table

### ISSUE THREAD

**Issue by dchillman123** [ErikEJ/EFCorePowerTools#1191]
### Steps to reproduce
 
I used EF Core 6 to reverse engineer a sql database - it skipped one table.  When I use EF Core 5, the table is not skipped.
The table has a primary key made of two columns - not sure if that is the issue

CREATE TABLE [dbo].[AspNetUserRoles] (
[UserId] nvarchar(128) NOT NULL,
[RoleId] nvarchar(128) NOT NULL,
CONSTRAINT [PK__AspNetUserRoles_RoleIdUserId]
PRIMARY KEY CLUSTERED ([UserId] ASC, [RoleId] ASC)
WITH ( PAD_INDEX = OFF,
FILLFACTOR = 100,
IGNORE_DUP_KEY = OFF,
STATISTICS_NORECOMPUTE = OFF,
ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON,
DATA_COMPRESSION = NONE )
 ON [PRIMARY]
)
ON [PRIMARY];

### Further technical details

EF Core version in use: EF Core 6

EF Core Power Tools version:2.5.832

Database engine: (SQL Server

Visual Studio version:  Visual Studio 2022 17.0.1

**Comment by ErikEJ** [comment]
Yes, this is a many to may tables, which causes a ["breaking" change](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-6.0/breaking-changes#many-to-many) in EF Core 6 - related issue #1184
