### ISSUE TITLE
Support for ODBC datasource for MySql

### ISSUE THREAD

**Issue by PoulBak** [ErikEJ/EFCorePowerTools#1194]
Describe what is not working as expected.
I upgraded to Visual Studio 2022. Now the old 'MySql Visual Studio integration' for Connector/Net doesn't work. Since it hasn't been developed for many years, I thought, why not use the ODBC driver for MySql, since it's already integrated into Visuel Studio?

So I download and install the MySql ODBC driver. And sure enough, I can create connections via the 'ODBC Data Sources (64-bit)' system tool.
When I open Visual Studio, 'Server explorer' I can see the connections and display the tables in my database.
So I open 'EF Core Power tools' and click 'Add' to add a connection. **I can test the connection successfully!**

**However, when I click 'Ok' the new connection is NOT added to 'EF Core Power tools' connections!**

### Steps to reproduce
Follow the steps above.

Please include a complete description that I can redo to reproduce the issue.

### Further technical details

EF Core version in use: (e.g. EF Core 5)
EF Core 6
EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
2.5.832
Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)
MySql
Visual Studio version: (e.g. Visual Studio 2019 16.11)
2022 (updated)

**Comment by PoulBak** [comment]
![Connection](https://user-images.githubusercontent.com/42176550/142724835-3029b467-fb81-4526-9e20-dca4572fc45d.png)

Screenshot

**Comment by PoulBak** [comment]
![Connection](https://user-images.githubusercontent.com/42176550/142724922-4834dc52-e4cf-4388-883a-1a2926f124c3.png)

Screenshot

**Comment by ErikEJ** [comment]
ODBC datasource is not supported, I am not able to determine the acutual database engine used - but I will add support for MySQL ad-hoc connections https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#ad-hoc-connections

**Comment by PoulBak** [comment]
Ok, as long as I can use MySql, I can live with that.

**Comment by ErikEJ** [comment]
Fixed in latest daily build

**Comment by PoulBak** [comment]
Great, now I have MySql again.

**Comment by tombohub** [comment]
I don't see adhoc mysql in dropdown. Do I need to install something else?

**Comment by ErikEJ** [comment]
Install the daily build from vsixgallery.com
