### ISSUE TITLE
Different custom templates for SQL tables and views ... maybe

### ISSUE THREAD

**Issue by csatnic** [ErikEJ/EFCorePowerTools#1195]
The tool is working as intended ... this item is asking about guidance in terms of workflow.

### Steps to reproduce

I'm using the Handlebars custom templates for C# to customize the generated entity classes and add an interface to each class. The interface is valid for entities generated from database tables because all tables share the columns that the interface is looking for.

However, when I generate entities for SQL views, the views don't have the required interface columns so that custom interface, in the auto-generated file, has to be removed in order for the project to compile. Each time I reverse engineer I leave the previously selected database objects as selected so the generated files for SQL views have to be adjusted again to remove the interface that's not supported in the class.

How can I get away from having to clean up those generated files for SQL views each time I reverse engineer?

Can the template be made 'smart' to only add an interface if certain columns exist?

Can I use different custom templates for tables vs. SQL views?

Any other suggestions?

Thank you.

### Further technical details

EF Core version in use: EF Core 5

EF Core Power Tools version: 2.5.832

Database engine: SQL Server

Visual Studio version: Visual Studio 2019

**Comment by ErikEJ** [comment]
How about not using Handlebars and adding the interface reference in a partial class for your tables only (which will survive code regenertion) ?

**Comment by csatnic** [comment]
That's an interesting idea ... I didn't think of using separate partial classes just to add the interface alone (I thought partial classes usually dealt with properties and methods).

Other than that ... it sounds like not much else can be done at the template level because those templates don't really run code that can actually inspect the objects they're working with? Is that right?

**Comment by ErikEJ** [comment]
Correct, neither Handlebars or Power Tools attempt to load your types and reason over them.

**Comment by csatnic** [comment]
Got it ... thank you very much for the suggestion.
