### ISSUE TITLE
Support multiple result sets from a SQL Server Stored Procedure

### ISSUE THREAD

**Issue by JimF42** [ErikEJ/EFCorePowerTools#1196]
- [x] Discover multiple result sets
- [x] Generate result set classes for modules with multiple
- [x] Generate code to call and hydrate multiple results using Dapper
- [x] Add Tools/Options option to enable this preview feature

SQL Stored Procedures can support sending back multiple results sets. While this is unusual, it sometimes makes sense under special cases and if you want to avoid multiple round trips from the client application.

LINQ to SQL has always supported this and EF 6 also supports this. I would like to see EF Core Power Tools support this for EF Core also.

### Steps to reproduce

Create a stored procedure that issues two different result sets. Run this tool to bring it in and you will only see the first result set is accessible. Do this in LINQ to SQL and you will see that `System.Data.Linq.IMultipleResult` is returned instead of `System.Data.Linq.ISingleResult` and all result sets are available via the `GetResult<TElement>` call.

### Further technical details

EF Core version in use: Any

EF Core Power Tools version: Any

Database engine: SQL Server, but probably Azure SQL too. Unsure if others like Postgres, Oracle, Firebird, SQLite, or MySQL can even do this.

Visual Studio version: Any

**Comment by JimF42** [comment]
See https://github.com/ErikEJ/EFCorePowerTools/issues/1172#issuecomment-975795071 for a c# code snip for performing this task. It's incomplete in the context of this tool, but it should give us a pretty good boost in the right direction.

**Comment by ErikEJ** [comment]
Slightly confused - is this about actual multiple result sets, or different shapes of the same result set?

My understanding of multiple result sets, this will return 3 result sets:

```sql
CREATE PROCEDURE Multi
AS
SELECT * FROM dbo.Shippers
SELECT * FROM dbo.Customers
SELECT * FROM dbo.Country

```

**Comment by JimF42** [comment]
@ErikEJ Sorry about any confusion, but yes, your example is correct. Did I miss something?

**Comment by ErikEJ** [comment]
No problem, I just got confused reading this: https://docs.microsoft.com/en-us/dotnet/api/system.data.linq.imultipleresults?view=netframework-4.8 

This will definitely be an opt-in feature, as the tool now executes user code in order to discover the shape of the additional result sets.

Also, the current approach of simply calling FromSqlRaw in the generated code will not work for the additional result sets, so must use DbCommand / DataReader etc. - basically duplicating what EF Core does so well.

**Comment by JimF42** [comment]
Also, technically, this would also be multiple result sets, even though the schema is the same (but honestly, I'm not sure why anyone would need to do that). 
```
CREATE PROCEDURE Multi
AS
SELECT * FROM dbo.Shippers
SELECT * FROM dbo.Shippers
```
While I do get the opt-in part, the part about "... now executes code ..." it does and it doesn't... I will have to run the SQL Profiler to check, but I believe that under the covers when you ask for SchemaOnly, it actually issues [SET FMTONLY](https://docs.microsoft.com/en-us/sql/t-sql/statements/set-fmtonly-transact-sql?view=sql-server-ver15#:~:text=SET%20FMTONLY%20%28Transact-SQL%29%201%20Syntax%202%20Remarks.%20When,sets%20FMTONLY%20to%20ON.%20...%205%20See%20Also).  There's a large note on that page that says "Don't use this!", but honestly, I have lost track of how many SQL releases it's said that.  There's no other viable option if you are dealing with multiple result sets, so even Microsoft hasn't actually dropped it yet.

Finally, there's one bug with SET FMTONLY that we can't help and nobody else either.  If your stored procedure creates a `#tempTable`, it will fail.  Even SQLMetal itself will fail on this because it uses SET FMTONLY either directly or via SchemaOnly.

**Comment by ErikEJ** [comment]
>> If your stored procedure creates a #tempTable, it will fail. 

Same issue with sp_describe_first_result_set, so no worries.

I think depending on Dapper will be the way to go: https://github.com/DapperLib/Dapper#multiple-results

**Comment by JimF42** [comment]
I haven't looked at your code yet. Do you generate all of your own c# code for the stored procedures? That is, generate the model classes and the stored procedure calls?

I haven't heard of Dapper either, I will have to check it out.

**Comment by ErikEJ** [comment]
yes, the code for the result classes, SqlParameter creation and calling and consuming the result is generated by EF Core Power Tools

**Comment by ErikEJ** [comment]
I will try to create a manual implementation first, to find out what moving parts need to change.

**Comment by ErikEJ** [comment]
@JimF42 I have manually tried out the required changes to the generated code, let me know what you think: https://github.com/ErikEJ/EFCorePowerTools/commit/7d243bb668e66eb12a9374e1f8e91117c58bbce7#diff-552bb2ae8ed868fecd4f93f0510a0e96e48c23ac07b1a7e700d446a62de25078

**Comment by JimF42** [comment]
@ErikEJ I took a quick look at your manual changes. What kind of critique are you looking from me? I'm happy to help where I can, but I am not intimately familiar with what generators like LINQ to SQL create. I've glanced at LINQ to SQL generated code, but I have not studied it. I mostly just use it.

But, in general (understanding you hand coded this in this case) I would point out that the models created would normally be named like `StoredProcedureNameResult1`, `StoredProcedureNameResult2`, `StoredProcedureNameResult3`, etc. Then, after the call is made, then to use `GetResult<TElement>` to get the result sets.  Perhaps this is your design all along and I'm just not seeing that. Or, perhaps you have a different way of getting the result sets (I also have never used EF 6 (non-core), so you may be doing it that way, and that's fine--I just need to learn a new way).

I have also seen it in generated code where if, for example, `StoredProcedureNameResult1` and `StoredProcedureNameResult3` are identical in their schema, then the generated code will not generate `StoredProcedureNameResult3` and the caller is expected to use `StoredProcedureNameResult1`. I can see this going either way.  There's nothing inherent with `IMultipleResults` "knowing" what schemas come in what order--that's left up to the programmer to understand that.

Now, when you get to a point where you would like me to do some testing with your tool and give me some instructions on how to side-load it, I would be more than happy to help. Or, if you want to discuss some design ideas, I will be happy to do that too.  

Thanks for taking time to look into supporting this, by the way.

**Comment by ErikEJ** [comment]
Thanks for the feedback, I will proceed with the experimental implementation.

I have no intention of implementing IMultipleResultSet or anything else resembling linq to sql.

**Comment by ErikEJ** [comment]
This is now implemented in the latest daily build, you must opt-in to the feature for now, as [shown here](https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#advanced-visual-studio-options)

**Comment by JimF42** [comment]
@ErikEJ Great!  I'm out of band for the next several days though, so I will not be able to even look at it until later in the week.

But, when I do get a chance, how do I install this into my VS 2022 since it's not in the normal marketplace?

Thanks

**Comment by ErikEJ** [comment]
Daily build: https://github.com/ErikEJ/EFCorePowerTools#daily-build

**Comment by ErikEJ** [comment]
Closing this, if there are issue, please file a bug

**Comment by ErikEJ** [comment]
@JimF42 Did you manage to try this out?

**Comment by JimF42** [comment]
@ErikEJ  _Oh my gosh_... I have been swamped at home and at work. Let me give it a quick spin in the morning.

**Comment by JimF42** [comment]
I am trying this now, but it is not clear to me which option I use to opt-in to get this feature to work. I'm sure I'm just missing something. I downloaded and installed EF Core Power Tools v2.5.863.vsix.

**Comment by DavidCAllenMI** [comment]
We are using ef core 3 and turning on the option to capture multiple resultsets from store procedures for SQL Server is not working. I only get back one resultset.

**Comment by ErikEJ** [comment]
@DavidCAllenMI what if you choose EF Core 5 or 6?

**Comment by DavidCAllenMI** [comment]
Our project is still using .net 4.8 because that's what the fed gov. has approved.

**Comment by ErikEJ** [comment]
@DavidCAllenMI I have a feeling that this feature has not been enabled for 3.1 for a reason. Please create a new issue instead of adding to this closed one  and I will investigate.
