### ISSUE TITLE
Update Handlebars for 2.1 preview1

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#12]
_From @ErikEJ on March 27, 2018 8:35_

Describe what is not working as expected.

### Steps to reproduce
Include a complete description that I can redo to reproduce the issue.

### Further technical details
Toolbox/Power Tools version: (found in About dialog - blue questionmark icon)

Database engine: (SQlite, SQL Compact or SQL Server)

Visual Studio or SSMS version: (e.g. Visual Studio 2017 15.3, SSMS 17.3)

_Copied from original issue: ErikEJ/SqlCeToolbox#666_

**Comment by ErikEJ** [comment]
_From @OmiCron07 on May 7, 2018 21:40_

When will the templates come back?

**Comment by ErikEJ** [comment]
Only @tonysneed knows ??

**Comment by ErikEJ** [comment]
_From @tonysneed on May 8, 2018 10:48_

I finally have some bandwidth to tackle this. Stay tuned.

**Comment by ErikEJ** [comment]
_From @tonysneed on May 12, 2018 21:38_

Now that EF 2.1 is RC, I plan to update my extensions.  I should have time to get started this week, but I'll definitely get it done within the next two weeks.

**Comment by ErikEJ** [comment]
@tonysneed Ping?

**Comment by ErikEJ** [comment]
Thanks a lot for the update!

**Comment by tonysneed** [comment]
Well that didn't work ... Could use someone to help me sort this out. I've narrowed it down to `RelationalScaffoldingModelFactory.GetTypeScaffoldingInfo`, where this line is returning null:

```
TypeScaffoldingInfo mapping = this._scaffoldingTypeMapper.FindMapping(column.GetUnderlyingStoreType() ?? column.StoreType, column.IsKeyOrIndex(), column.IsRowVersion());
```

**Comment by tonysneed** [comment]
This is without any of my Handlebars templates in the mix.  It's basically just trying to reverse engineer a database from within a unit test.  The EF Core code base does not have an example of doing that, so I'm pretty much on my own.

**Comment by ErikEJ** [comment]
@tonysneed Could you share a branch with actual code, then maybe @bricelam could help? 🙏

**Comment by ErikEJ** [comment]
@tonysneed  Have you look at this: https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/ReverseEngineer20/EFCoreReverseEngineer.cs (not sure it will be of much help)

**Comment by tonysneed** [comment]
@ErikEJ Thanks, having a look.

**Comment by bricelam** [comment]
Here's the heart of our functional tests which generate code from a model, compile it, and load it back: https://github.com/aspnet/EntityFrameworkCore/blob/dev/test/EFCore.Design.Tests/Scaffolding/Internal/ModelCodeGeneratorTestBase.cs

**Comment by tonysneed** [comment]
Perfect, thanks guys. `ConfigureDesignTimeServices` was what I was missing.  I'm unblocked now.

**Comment by tonysneed** [comment]
This issue is resolved with [release 1.0.0-rc1](https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars/releases/tag/v1.0.0-rc1).
The NuGet package has also been published: https://www.nuget.org/packages/EntityFrameworkCore.Scaffolding.Handlebars/1.0.0-rc

**Comment by tonysneed** [comment]
I might be able to help with that .. perhaps fork the Handlebars.Net repo and strongly name it.  Then I can strongly name mine too.  Make your life easier. :)

**Comment by ErikEJ** [comment]
Sounds great - Maybe wait until after I find out if I need to make any changes (I did the last time)

**Comment by ErikEJ** [comment]
https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars/issues/12

**Comment by tonysneed** [comment]
Addressed [here](https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars/issues/12#issuecomment-392224286) and [here](https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars/issues/9#issuecomment-392229067).

**Comment by tonysneed** [comment]
@ErikEJ I went ahead and published the signed package: https://www.nuget.org/packages/EntityFrameworkCore.Scaffolding.Handlebars/1.0.0-rc2.  So just install it normally.
