### ISSUE TITLE
System.IO.FileNotFoundException: Could not load file or assembly Microsoft.Extensions.DependencyInjection, Version=2.1.0.0

### ISSUE THREAD

**Issue by kachalkov** [ErikEJ/EFCorePowerTools#120]
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.DependencyInjection, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.Extensions.DependencyInjection, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at ReverseEngineer20.EfCoreReverseEngineer.GenerateFiles(ReverseEngineerOptions reverseEngineerOptions)
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__2.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 160

### Steps to reproduce
When Reverse Engineering 

### Further technical details
EF Core Power Tools version: 1.0.677

Database engine: (SQL Server)

Visual Studio version: (e.g. Visual Studio 2017 15.8.8)

**Comment by ErikEJ** [comment]
Have you tried reverting to latest released version?

**Comment by kachalkov** [comment]
1.0.677 is the latest one?

**Comment by ErikEJ** [comment]
I mean the officially released version on VS Marketplace - these versions are pre-release!

https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools

**Comment by ErikEJ** [comment]
@Herdo This will not fly - how can we avoid this dependency?

https://github.com/ErikEJ/EFCorePowerTools/commit/0b84d147fdf340e6aec78f7c2b7b190daa456ee3#diff-90b2ef3fc2063b3436df658e010e0942R271

**Comment by ErikEJ** [comment]
Or maybe downgrade to: https://www.nuget.org/packages/Microsoft.Extensions.DependencyInjection/2.1.0 ?

**Comment by weastaugh** [comment]
I'm confused. @ErikEJ are you suggesting we install the Microsoft.Extensions.DependencyInjection package into the project we are Reverse Engineering into? Surely the EFCorePowerTools extension should package this dependency itself? Either way I tried installing the package into my project and it didn't work. I want to use the "Use table and column names directly from the database" feature so reverting to the latest released version is not an option.

**Comment by ErikEJ** [comment]
@Herdo  Let us downgrade to 2.1.0
@weastaugh  The "Use table and column names directly from the database" is already in the released version, but maybe you are thinking of the hidden table and column rename feature? Ie efpt.renaming.json #14

**Comment by ErikEJ** [comment]
Should be fixed in latest daily build
