### ISSUE TITLE
mysqlforvisualstudio1.2.10 an VS2022 not work - is there another way?

### ISSUE THREAD

**Issue by schorges** [ErikEJ/EFCorePowerTools#1201]
I have VS2022 on a workplace and can't reverse a big mysql rmdbs, 
the mysqlforvisualstudio1.2.10 only work on VS2019, not on VS2022
is there a way to add the "Choose Database Connection" in EFCorePT manuell 
in a File ?

**Comment by ErikEJ** [comment]
It is available via adhoc connection in the latest daily build

**Comment by schorges** [comment]
you are my hero, thank you very much!

only manuell change the string after generatet - optional:

`persistsecurityinfo=True;database=musicDb;convertzerodatetime=True`
