### ISSUE TITLE
Direction = ParameterDirection.ReturnValue not set properly

### ISSUE THREAD

**Issue by DickBaker** [ErikEJ/EFCorePowerTools#1207]
Describe what is not working as expected.
The generated code sets the Direction property to the wrong value

### Steps to reproduce
here is an example of some generated code
var parameterreturnValue = new SqlParameter
{
    ParameterName = "returnValue",
    Direction = ParameterDirection.Output,
    SqlDbType = SqlDbType.Int
};

Please include a complete description that I can redo to reproduce the issue.
IMHO the code should be
var parameterreturnValue = new SqlParameter
{
    ParameterName = "returnValue",
    Direction = ParameterDirection.ReturnValue,
    SqlDbType = SqlDbType.Int
};

the ParameterDirection enum has [FlagsAttribute], so the absolute values (Output = 2, ReturnValue = 6) does mean that the unique ReturnValue is OR'ed with Output (so it may suffice as-is in some cases) but is still WRONG

### Further technical details

EF Core version in use: (e.g. EF Core 5)
EF Core 6

EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
2.5.832.0

Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)
MSSQL

Visual Studio version: (e.g. Visual Studio 2019 16.11)
VS2022 EE 17.1.0 Preview 1.1

**Comment by ErikEJ** [comment]
I am not sure you are correct - ReturnValue only works when CommandType = StoredProcedure, no Text.

Have you tried changing to ReturnValue and running the code?

**Comment by ErikEJ** [comment]
Ping?
