### ISSUE TITLE
MySQL Data Source missing

### ISSUE THREAD

**Issue by Arnegeddon** [ErikEJ/EFCorePowerTools#1211]
The MySQL data source is missing when I try to use it in Visual Studio 2022.

Picture 1: EF Core Power Tools (2.5.774) on Visual Studio 2019 (community)
![image](https://user-images.githubusercontent.com/22367996/145302626-a10b46bc-aea4-4849-bf9d-0f57181e0e06.png)

Picture 2: EF Core Power Tools (2.5.832) on Visual Studio 2022 (community)
![image](https://user-images.githubusercontent.com/22367996/145302449-1f43c902-ed2c-4f67-87e8-0d8009db79af.png)

**Comment by ErikEJ** [comment]
You need the MySQL VS Tools, which have not been released yet: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#choose-data-source 

But you can use [ad-hoc connection](https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#custom-connections) with the latest daily build.

**Comment by Arnegeddon** [comment]
Thank you!
