### ISSUE TITLE
Error during Reverse engineer with EF Core 6

### ISSUE THREAD

**Issue by giarico** [ErikEJ/EFCorePowerTools#1212]
During reverse engineer I got this error:
The property or navigation 'Languages' cannot be added to the entity type 'Entity (Dictionary<string, object>)' because a property or navigation with the same name already exists on entity type 'Entity (Dictionary<string, object>)'

If I switch to EF Core 5 all is working correctly.

### Steps to reproduce

I have these tables:

dbo.Entities
dbo.Languages
dbo.EntityLanguages (EntityId --> FK Entities, LanguageId --> FK Languages)
anotherschema.EntityLanguages (EntityId --> FK Entities, LanguageId --> FK Languages)

### Further technical details

EF Core version in use: EF Core 6
EF Core Power Tools version: 2.5
Database engine: SQL Server
Visual Studio version: Visual Studio 2022 (17.0.2)

**Comment by ErikEJ** [comment]
It is a known bug, will be fixed with 6.0.1 or 6.0.2. @AndriySvyryd In the meantime you can enable old-school many to many via the advanced options dialog.
