### ISSUE TITLE
UseNullableReferences: true generates warnings in VS

### ISSUE THREAD

**Issue by stgenov** [ErikEJ/EFCorePowerTools#1213]
EFCore Power Tools Reverse engineer with "UseNullableReferences": true
.NET Core 6.0 project file with <Nullable>enable</Nullable>

The generated file start with the auto-generated directive which is correct.
But visual studio gives the following warning on property which has the string? type:

Warning	CS8669	The annotation for nullable reference types should only be used in code within a '#nullable' annotations context. Auto-generated code requires an explicit '#nullable' directive in source.

The warning is that the file is auto generated (has the // auto-generated... row) but is missing the "#nullable enable" directive.

Solution: add the #nullable just after the <auto-generated> row:

```
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
```

### Further technical details

EF Core version in use: EF Core 6.0
EF Core Power Tools version: 2.5.832.0
Database engine: SQL Server
Visual Studio version: Visual Studio 2022(64-bit) 17.0.2)

csproj file:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.0" />
  </ItemGroup>

</Project>
```

**Comment by ErikEJ** [comment]
Does this apply to both the Entity Classes and the DbContext?

**Comment by ErikEJ** [comment]
I have attempted a fix in the latest daily build

**Comment by stgenov** [comment]
> Does this apply to both the Entity Classes and the DbContext?

Hi Erik, thank you for your swift response!

The DbContext file usually does not contain nullable types - only contains Dbset<T> properties
and property descriptors. So I have no warnings in that file.
But the rule applies - if you have a // auto-generated tag on the file, VS wants you to also have #nullable enabled.

#nullable enabled should only be added if the files generated with Power Tools are with the option "UseNullableReferences": true.

**Comment by ErikEJ** [comment]
Thanks, it should all be implemented in the latest daily then
