### ISSUE TITLE
Unable to reverse engineer an Sql Server Compact 4.0 database

### ISSUE THREAD

**Issue by rmckay49** [ErikEJ/EFCorePowerTools#1214]
Describe what is not working as expected.
Reverse engineer an Sql Server 4.0 database 
### Steps to reproduce
Select 'Reverse Engineer' -> Add -> Data Source Change -> SQL Server Compact 4.0 -> OK -> fill in source with 'C:\Program Files\Microsoft SQL Server Compact Edition\Data\2021_12_11_NinjaTrader.sdf' -> Test Connection -> 'Test connection succeeded -> OK -> OK.  The file drop down menu does not show the path I added.  It's pointing to the database that was displayed initially 'zbook\localdb#477bddf2.Blogging.dbo'.   
Please include a complete description that I can redo to reproduce the issue.
The above steps reproduce the issue
### Further technical details

EF Core version in use: (e.g. EF Core 5)
EF Core 5
EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
2.5.832.0
Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)
SQL Server CE 4.0
Visual Studio version: (e.g. Visual Studio 2019 16.11)
VS 2022 and 2019

**Comment by ErikEJ** [comment]
SQL Server Compact is no longer supported, as there is no EF Core 3 or later provider available.

**Comment by rmckay49** [comment]
ErikEJ,  Thanks for the quick response.  I need to access data from a 3Rd party program that is still using SQL Server Compact and I'm a rank novice with databases.  Do any workarounds exist? Thanks.

**Comment by ErikEJ** [comment]
@rmckay49 There are multiple options:

- [Raw ADO.NET access](https://erikej.github.io/sqlce/2020/08/17/netcore-sql-compact.html) - no reverse engineering
- Use the [EF 6 provider](https://github.com/ErikEJ/EntityFramework6PowerTools/tree/community/src/ErikEJ.EntityFramework.SqlServerCompact) I just published
- Use LINQ to SQL with SQL Server Compact Toolbox to reverse engineer the database and Data Context (saves you some time)
