### ISSUE TITLE
How can I convert the int property to an enumeration type?

### ISSUE THREAD

**Issue by shouhujishu** [ErikEJ/EFCorePowerTools#1215]
Describe what is not working as expected.

### Steps to reproduce
How do I convert the int property to an enumerated type? And the default state will not be restored when the model is refreshed

### Further technical details

EF Core version in use: NET5

EF Core Power Tools version:2.5.832.0

Database engine: mysql

Visual Studio version: vs2019

**Comment by ErikEJ** [comment]
You can create a [NotMapped] Enum property in a partial class https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#extending-the-generated-dbcontext-class-and-entity-classes

**Comment by shouhujishu** [comment]
> 可以在分部类中创建 [未映射] 枚举属性https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#extending-the-generated-dbcontext-class-and-entity-classes

Hello, I can’t get the usage process in the wiki, can you give me more details?

**Comment by ErikEJ** [comment]
Have a look at this: https://github.com/ErikEJ/EFCorePowerTools/issues/572#issuecomment-725603917

**Comment by ErikEJ** [comment]
Ping?

**Comment by shouhujishu** [comment]
> 看看这个： [#572 （评论）](https://github.com/ErikEJ/EFCorePowerTools/issues/572#issuecomment-725603917)



> 看看这个： [#572 （评论）](https://github.com/ErikEJ/EFCorePowerTools/issues/572#issuecomment-725603917)
Hello, the custom writing context and model code EF tool will not be available! I hope that the EF tool will uncheck the database table name. When the context is generated, it will not automatically delete the established model or context of the project. This will facilitate normal use when customizing the model The EF tool will not cause the established model to be deleted because of the exclusion.

**Comment by ErikEJ** [comment]
Read through the wiki to understand how the tool and customizations in partial classes work. 
Use partial classes in separate files

**Comment by ErikEJ** [comment]
Custom [enum mapping](https://github.com/ErikEJ/EFCorePowerTools/issues/1472#issuecomment-1220273164) is now available with EF Core 7 and T4 templates
