### ISSUE TITLE
Customize code using Handlebars,  Handlebars not works in EF Core Power Tools (EF core 6,vs 2022)

### ISSUE THREAD

**Issue by sunqintao** [ErikEJ/EFCorePowerTools#1217]
class.hbs eg

`{{> imports}}

namespace {{namespace}}
{
    {{#if comment}}
    /// <summary>
    /// {{comment}}
    /// </summary>
    {{/if}}
    {{#if class-annotation}}
    {{{class-annotation}}}
    {{/if}}
    public partial class {{class}}:MyBase
    {
        {{{> constructor}}}
        {{{> properties}}}
    }
}
`

![image](https://user-images.githubusercontent.com/13376415/145970094-d55c4079-0bf6-498f-9005-abfc60dda508.png)

result  no MyBase

### Steps to reproduce

Please include a complete description that I can redo to reproduce the issue.

### Further technical details

EF Core version in use: (e.g. EF Core 6)

EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)

Database engine: (SQL Server)

Visual Studio version: (e.g. Visual Studio 2022)

**Comment by ErikEJ** [comment]
maybe start over, by renaming the codetemplates folder?

Otherwise, pls provide repro project/steps

**Comment by ErikEJ** [comment]
Also, which EF Core Power Tools version?

**Comment by ErikEJ** [comment]
You need the latest daily build, I have updated the release notes

**Comment by sunqintao** [comment]
> maybe start over, by renaming the codetemplates folder?
> 
> Otherwise, pls provide repro project/steps

EFCorePowerTools version 2.5.832.0 

Templates Folder "CodeTemplates“?

**Comment by sunqintao** [comment]
EFCorePowerTools version 2.5.861

`    /// <summary>
    ///     /// &#38134;&#34892;&#27969;&#27700;&#36134;&#25143;&#20449;&#24687;
    ///    Type(1&#20844;&#21496;&#36134;&#25143;&#65292;2&#23458;&#25143;&#36134;&#25143;)
    /// </summary>
    public partial class BankInfo:IEntity
    {
}`

**Comment by sunqintao** [comment]
`using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RMS.Data.Entity
{
    /// <summary>
    /// &#19994;&#21153;&#23458;&#25143;&#34920;
    /// </summary>
    public partial class BusinessCustomers :IEntity
    {

        /// <summary>
        /// 业务模型
        /// </summary>
        [Key]
        public int BusinessModel { get; set; }

        /// <summary>
        /// &#23458;&#25143;&#31616;&#31216;
        /// </summary>
        [StringLength(200)]
        public string Name { get; set; } = null!;

        /// <summary>
        /// &#23458;&#25143;&#20840;&#31216;
        /// </summary>
        [StringLength(500)]
        public string? FullName { get; set; }

        /// <summary>
        /// &#23458;&#25143;ID
        /// </summary>
        public Guid CustomerId { get; set; }

        /// <summary>
        /// &#30331;&#38470;&#36134;&#21495;
        /// </summary>
        [StringLength(50)]
        public string? LoginId { get; set; }

        /// <summary>
        /// &#30331;&#38470;&#23494;&#30721;
        /// </summary>
        [StringLength(50)]
        public string? Password { get; set; }

        /// <summary>
        /// SKU&#32534;&#21495;&#30721;&#22836;
        /// </summary>
        [StringLength(2)]
        public string SkuHeadCode { get; set; } = null!;

        /// <summary>
        /// &#29366;&#24577;
        /// </summary>
        public int Status { get; set; }

        /// <summary>
        /// &#22791;&#27880;
        /// </summary>
        public string? Remarks { get; set; }

        /// <summary>
        /// &#21019;&#24314;&#20154;
        /// </summary>
        [StringLength(50)]
        public string CreatedBy { get; set; } = null!;

        /// <summary>
        /// &#21019;&#24314;&#26102;&#38388;
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime CreatedOn { get; set; }

        /// <summary>
        /// &#26368;&#21518;&#26356;&#26032;&#20154;
        /// </summary>
        [StringLength(50)]
        public string LastUpdatedBy { get; set; } = null!;

        /// <summary>
        /// &#26368;&#21518;&#26356;&#26032;&#26102;&#38388;
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime LastUpdatedOn { get; set; }

        /// <summary>
        /// API&#20844;&#38053;
        /// </summary>
        [StringLength(200)]
        public string? ApiKey { get; set; }

        /// <summary>
        /// API&#23494;&#38053;
        /// </summary>
        [StringLength(200)]
        public string? ApiSecret { get; set; }

        /// <summary>
        /// &#22320;&#22336;
        /// </summary>
        [StringLength(200)]
        public string? Address { get; set; }

        /// <summary>
        /// &#32852;&#31995;&#20154;
        /// </summary>
        [StringLength(50)]
        public string? Contact { get; set; }

        /// <summary>
        /// &#30005;&#35805;
        /// </summary>
        [StringLength(25)]
        [Unicode(false)]
        public string? Tel { get; set; }

        /// <summary>
        /// &#29992;&#25143;&#31867;&#22411;
        /// </summary>
        public int? CustomerType { get; set; }

        /// <summary>
        /// &#20648;&#20540;
        /// </summary>
        [Column(TypeName = "decimal(9, 2)")]
        public decimal? Balance { get; set; }
    }
}
`

**Comment by ErikEJ** [comment]
So it is working now! The encoding issue is a well known Handlebars issue.

**Comment by ErikEJ** [comment]
Link to issue: https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars/issues/184

**Comment by sunqintao** [comment]
> Link to issue: [TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#184](https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars/issues/184)

Thx!

**Comment by tonysneed** [comment]
Over the next week [Handlebars.Net](https://github.com/Handlebars-Net/Handlebars.Net) will release a patch to [fix](https://github.com/Handlebars-Net/Handlebars.Net/pull/477) the encoding issue. At that time I will also update my Handlebars library to include the fix.

**Comment by ErikEJ** [comment]
Fixed in  latest daily
