### ISSUE TITLE
Reverse Engineering Functions uses DataTable which does not have using System.Data on top of the file.

### ISSUE THREAD

**Issue by CorsairRO** [ErikEJ/EFCorePowerTools#1218]
Hello, 
First of all thank you for the extraordinary tool that you make there. BIG BIG APPRECIATION...
Basically you should be awarded by Microsoft for making more people to come towards EF Core usage.

Because of their IDIOTIC idea to give up on edmx and use Code First that makes basically EF Core UNUSABLE in real life applications, that has more that 10 tables to use.

i have discovered a possible bug in the tool

Adding functions to reverse engineering, some of my functions have Datatable as parameters / resultsets, probably to resemble the User Defined Types in DB, which is OK.

Just that the MyContext.Functions.cs does NOT include a Using System.Data; at the beginning of the file, therefore the project is not building.

I can of course added it manually, but it is in an autogenerated file that will be overridden next time when i will update my model

Thank you,

### Steps to reproduce

Have a DB function that returns a User Defined Type list

### Further technical details

EF Core version in use: EF Core 6

EF Core Power Tools version: 2.5.832 ( the latest )

Database engine: SQL Server

Visual Studio version: 2022 Current

**Comment by ErikEJ** [comment]
Fixed in latest daily build, thanks for reporting this
