### ISSUE TITLE
Reverse Engineer with underscores leaves an extra underscore at the end

### ISSUE THREAD

**Issue by bcbeatty** [ErikEJ/EFCorePowerTools#122]
### Describe what is not working as expected.
Reverse Engineering with "User Table and column names directly from database" checked and "Customize code using Handlebar" checked with underscores and handlebars leaves an extra underscore at the end of the navigation property:
Ex : FK_Field_ID becomes FK_Field_
### Steps to reproduce
Include a complete description that I can redo to reproduce the issue.

- have existing tables with underscores and foreign keys, where the FK has _Id suffixed.
- Reverse Engineering with "User Table and column names directly from database" checked and optionally "Customize code using Handlebar" checked

- BTW the Scaffold-DbContext command does the same thing

### Further technical details
EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
Version 1.0.664.0

SQL Server Compact 4.0 in GAC - No
SQL Server Compact 4.0 DbProvider - No

SQL Server Compact 4.0 DDEX provider - No
SQL Server Compact 4.0 Simple DDEX provider - Yes

SQLite ADO.NET Provider included: No
SQLite EF6 DbProvider in GAC - No

System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes

Database engine: (SQlite, SQL Compact, SQL Server, Postgres)
Sql Server

Visual Studio version: (e.g. Visual Studio 2017 15.7)
Visual Studio 2017 - version 15.8.8

**Comment by ErikEJ** [comment]
Since scaffold-dbcontext also has this behavior I suggest you raise an issue in the EF Core repo.

**Comment by ErikEJ** [comment]
Closing as there is nothing to do here for the EF Core Power Tools
