### ISSUE TITLE
Feature request: override PK property name to be always be Id

### ISSUE THREAD

**Issue by ducman** [ErikEJ/EFCorePowerTools#1222]
I have an established (old) DB where the PK of each table is named: {TableName}Id

It would be nice to have a feature to reverse engineer to entities with the property named `Id` which maps to the table's PK. This helps keep things a bit consistent for us.

Of course, if the table PK is already named `Id`, there is nothing to do. Same when encountering a table with composite PKs.

**Comment by ErikEJ** [comment]
You should be able to use the regex based renaming with individual override where needed.

**Comment by ducman** [comment]
Sorry, not really sure what you mean by this.

**Comment by ErikEJ** [comment]
I mean [this](https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#custom-renaming-with-efptrenamingjson)

**Comment by ducman** [comment]
Thanks for this. I'm unable to make use of regex since I have no clue what the table/entity name is to match it on the column name when wanting this done for all tables/entities.

Since I only have a few tables to deal with, I manually listed all out with the PK rename. 

Still, it will be nice to have this done across all tables somehow. Unless you have some tricks up your sleeves.

**Comment by ErikEJ** [comment]
You said they started with some letters and ended with Id...

**Comment by ducman** [comment]
Yes but only for the PK column. 

To avoid hand jamming everything, I wrote the below query (on Sql Server 2016 or later) to generate the `efpt.renaming.json` file. It doesn't work with composite PKs; I'll have to tweak it when I run into that scenario. But this will do for now.

```sql
SELECT
    schemas.name AS SchemaName,
    Tables.Name,
    Columns.Name,
    'Id' AS NewName
FROM 
    sys.tables AS Tables
    JOIN sys.schemas
        ON schemas.schema_id = tables.schema_id
    JOIN sys.indexes
        ON indexes.object_id = tables.object_id
        AND indexes.is_primary_key = 1
    JOIN sys.index_columns
        ON index_columns.object_id = indexes.object_id
        AND index_columns.index_id = indexes.index_id
    JOIN sys.columns AS Columns
        ON columns.object_id = tables.object_id
        AND columns.column_id = index_columns.column_id
FOR JSON AUTO
```

**Comment by ErikEJ** [comment]
Excellent, I will add that to the docs!
