### ISSUE TITLE
C# Handlebar customizations are totally ignored in EF Core 6 

### ISSUE THREAD

**Issue by CorsairRO** [ErikEJ/EFCorePowerTools#1223]
Hello again and thank you again for the wonderful tool that you make there.

Because of your tool i start to think about maybe EF Core becomes a really USABLE ORM, as otherwise MS did a great job on it but a CRAP job with removing all the tooling there.

However i have just started with it and i would like to do some basic customization of the generated entities. 
I have read about handlebars and added them in your tool when generating objects.
I have done some customizations to my objects before using old plain .t4 templating, which again i dont understand why MS decided to give up as they are BRILLIANT and they are working for ages.

It created a CodeTemplates folder with CSharpEntityType and CSharpDbContext inside the project, which is fine.
Then i have edited Class.hbs and changed only:
public partial class {{class}} --> : MyBaseClass

Use efpt.config.json right click, refresh => didnt do anything with my objects in the direction that i would like.
Deleting all POCO's and regenerating them => same result

Please let me know if i am just stupid not doing something right or there is an issue with the Handlebars there.

Thank you again for you kindly support and your efforts to make and maintain this wonderful tool

### Steps to reproduce

Please see in description

### Further technical details

EF Core version in use: EF Core 6

EF Core Power Tools version: Latest published version 2.5.832

Database engine: SQL Server

Visual Studio version: VS 2022 17.0.4

**Comment by ErikEJ** [comment]
There are duplicate issues - you must install the daily build - I plan to release a new version to marketplace this weekend  btw
