### ISSUE TITLE
Reverse engineering of 'boolean NOT NULL DEFAULT TRUE' results in bool? type

### ISSUE THREAD

**Issue by jkerrwilson** [ErikEJ/EFCorePowerTools#1225]
When reverse engineering a postgres database, columns defined as ```boolean NOT NULL DEFAULT TRUE``` are being translated into nullable bools in the c# code.

### Steps to reproduce

Have a postgres database with a table containing boolean columns that are defined to be not null with a default of true

Run reverse engineering tool on said table

...

Nullable booleans appear in model definition.

### Further technical details

EF Core version in use: EF Core 6

EF Core Power Tools version: 2.5.832

Database engine: Postgres

Visual Studio version: VS 2022

**Comment by ErikEJ** [comment]
It is by design, and there is an advanced option to disable this behavior

**Comment by jkerrwilson** [comment]
Hi Erik, Could you specify the name of the option for me? Thanks.

**Comment by jkerrwilson** [comment]
It looks like it is "Remove SQL defaults from bool columns".
