### ISSUE TITLE
Entity relations not working after reverse engineering from EF6 EDMX

### ISSUE THREAD

**Issue by RaulFunezp** [ErikEJ/EFCorePowerTools#1226]
Hi Erik,

I have an application working correctly in EF6 using EDMX, the tables are defined as ObservableCollectiones in the T4 template.  After Reverse Engeeniring the relationships between tables do not work well for me.  e.g.:

This works fine:
private Table1? _table1Row
_table1Row = _context.Table1.FirstOrDefault (y => y.Id == _ whatever);

But, I have this error:
CS1061: 'Table1' contains no definition for 'Table2' and no accessible extension method 'Table2' accepting a first argument of type 'Table1' 

In this line:
var _p = _table1Row.Table2.FirstOrDefault (or => or etc ...

Table2 does not shows as a Table1 property.

For testing purposes I installed LazyLoadingProxies and enabled UseLazyLoadingProxies in the OnConfiguring method but to no avail.

I am try to migrate from EF6 EDMX Windows Desktop WPF Azure SQL to EF Core 6 using Visual Studio 2022 v17.0.4.  EF Core Power Tools for Visual Studio 2022 v2.5.832.0

Thanks in advance,
Raul

**Comment by ErikEJ** [comment]
Works fine ? This sounds like a runtime/build issues, and does not really seem to relate to EF Core Power Tools.

But in order to help you, I need a repro project...

**Comment by RaulFunezp** [comment]
I will try to prepare a small example and will let you know.
Thank you

**Comment by ErikEJ** [comment]
Ping?

**Comment by RaulFunezp** [comment]
Hi, I don't have a repo test yet. I show you the class definitions and the test I did today that made Table2 appear as expected, which maybe gives an idea of ​​the origin of the problem.

**Entity Class definitions currently in production, generated using EF6 Database First EDMX Update Model (before EF Core 6 Reverse Engineering):**

**Table 1 EF6**

```
namespace DataModel
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Table1
    {
        public string UserId { get; set; }
        public string UserName { get; set; }
        public int UserRoleId { get; set; }
        ...some more string and datetime properties...

        public virtual Table2 Table2 { get; set; }
    }
}
```
**Table2 EF6**

```
namespace DataModel
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Table2
    {
        public Table2()
        {
            this.Table1 = new ObservableCollection<Table1>();
        }
    
            public int UserRoleId { get; set; }
            public string UserRole { get; set; }
            ...some more string and datetime properties...

        public virtual ObservableCollection<Table1> Table1 { get; set; }
    }
}
```

**Entity Class definitions after EF Core 6 Reverse Engineering:**

**Table1 EF Core 6**

```
using System;
using System.Collections.Generic;

namespace App.Model
{
    public partial class Table1
    {
    public string UserId { get; set; } = null!;
    public string UserName { get; set; } = null!;
    public int UserRoleId { get; set; }
    ...some more string and datetime properties...

        public virtual Table2 UserRoleIdNavigation { get; set; } = null!;
    }
}
```

Table 1 EF Core 6 Model builder:

```
    entity.HasOne(d => d.UserRoleIdNavigation)
        .WithMany(p => p.Table1)
        .HasForeignKey(d => d.UserRoleId)
        .OnDelete(DeleteBehavior.ClientSetNull)
        .HasConstraintName("FK_Table1_Table2");
```

**Table 2 EF Core 6**

```
using System;
using System.Collections.Generic;

namespace App.Model
{
    public partial class Table2
    {
        public Table2()
        {
            Table1 = new HashSet<Table1>();
        }

        public int UserRoleId { get; set; }
        public string? UserRole { get; set; }
        ...some more string and datetime properties...

        public virtual ICollection<Table1> Table1 { get; set; }
    }
}
```
**I made these changes manually today and everything works fine but not a good solution to follow:**

**Table1 EF Core 6 Class definition**
`        public virtual Table2 Table2 { get; set; }`

**Table1 EF Core 6 Model builder**
                entity.HasOne(d => d.Table2)

After this Table 2 appears as a Table1 property as expected but having null value, so I had to install and enable UseLazyLoadingProxies.

Thanks.

**Comment by ErikEJ** [comment]
I need you database schema (CREATE TABLE scripts etc) in order to provide any help

**Comment by RaulFunezp** [comment]
Here are the scripts, please let me know if you need more information.

```
/****** Object:  Table [dbo].[Table1]    Script Date: 21/12/2021 08:38:15 a.m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Table1](
	[UserId] [varchar](30) NOT NULL,
	[UserName] [varchar](60) NOT NULL,
	[UserRoleId] [int] NOT NULL,

 CONSTRAINT [PK_UserNames] PRIMARY KEY CLUSTERED 
(
	[UserName] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


ALTER TABLE [dbo].[Table1]  WITH CHECK ADD  CONSTRAINT [FK_Table1_Table2] FOREIGN KEY([UserRoleId])
REFERENCES [dbo].[Table2] ([UserRoleId])
GO

ALTER TABLE [dbo].[Table1] CHECK CONSTRAINT [FK_Table1_Table2]
GO
```

```
/****** Object:  Table [dbo].[Table2]    Script Date: 21/12/2021 08:51:49 a.m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Table2](
	[UserRoleId] [int] NOT NULL,
	[UserRole] [varchar](40) NULL,
 CONSTRAINT [PK_UserRolIds] PRIMARY KEY CLUSTERED 
(
	[UserRoleId] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

**Comment by ErikEJ** [comment]
generated navigation names in EF Core are simply named differently, you will have to update your code accordingly.

Table2 => UserRoleIdNavigation

**Comment by RaulFunezp** [comment]
Thank you very much.
