### ISSUE TITLE
#nullable disable is not available in c# 7.3

### ISSUE THREAD

**Issue by pedromcrocha** [ErikEJ/EFCorePowerTools#1228]
With last update start apear #nullable disable in context file
My project is still framework 4.8 and the maximum version of C# is 7.3

### Steps to reproduce

just reverse engineer in framework 4.8 project

**Comment by ErikEJ** [comment]
You can use C#8 with .NET Framework.

**Comment by pedromcrocha** [comment]
nice, i go investigate

**Comment by absinghal** [comment]
Have the same issue in .Net standard

C# 8 (Microsoft.Net.Compilers.Toolset package) does not seem to be available in .Net standard.

**Comment by ErikEJ** [comment]
Can you share a snippet of offending code? 

@pedromcrocha @absinghal  and I will look into a fix

**Comment by absinghal** [comment]
`#nullable disable`

Appears at the top of context file as well as entity files.

**Comment by pedromcrocha** [comment]
in context or entity files

// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

**Comment by ErikEJ** [comment]
Thanks, I will implement a fix in the latest daily.

**Comment by ErikEJ** [comment]
I have attempted a fix in the latest daily build, please let me know if that works for you.

**Comment by pedromcrocha** [comment]
works fine, 
thanks Erik
