### ISSUE TITLE
More strict nullable code generation for value types

### ISSUE THREAD

**Issue by Lonsarg** [ErikEJ/EFCorePowerTools#1229]
### The dilema with current behaviour
Note that this issue is not about experimental "nullable reference type" feature for strings, but it is about nullability for values types (booleans, integers,..). But the new "nullable reference type" feature is the reason this dilema occurred to me, since with this new feature strings now have better nullability handling then integers in auto-generated code.

Not null DB fields are currently generated as nullable in autogenerated code (bool?, int?,..) This was (just guesing) done to avoid commiting default values (for example value zero for integers) to database by mistake if not set. But this causes inconsistent and error-prone behaviour for developers, since we are not aware which fields are nullable at compile-time. It is even more confusing if using the new "nullable reference type" feature, since there we now have compile-time check for not null strings while we are still left with no compile-time check for not null value type fields.

### Recommanded change
My recommendation is to handle this via backing fields and customs setters to achieve compile-time nullability check for value types. And since code is better then words, here is currently generated code for fields that are not null:
```
public int? FieldName { get; set; }
```
, and the new suggested code:
```
private int? _fieldName = null;
public int FieldName
{
    get { return _fieldName != null 
              ? _fieldName.Value 
              : throw new InvalidOperationException($"Field {nameof(FieldName)} was not set but it is required."); 
    }
    set { _fieldName = value; }
}
```

This should not break much existing code. It may cause compilation errors for code that was somewhat broken already (but that compiled anyway). So my suggestion is to make the new syntax as default always. But if we want to be extra carefull, we can maybe trigger new syntax only when "nullable reference type" feature is enabled to at least achieve consistent compile-time nullable check for both value and reference types when the feature is turned on.

**Comment by ErikEJ** [comment]
Normally, a NOT NULL int column will be scaffolded a "int", not int?, so you must have an odd default.

Please share a sample schema where this occurs. Assume you are aware of the advanced option in Power Tools that applies to bool columns with a crazy default?

At any rate, this seems more like something you should raise in the EF Core repo, as this tool wraps how things are done there.

**Comment by Lonsarg** [comment]
You are right my mistake on int columns, this does not happen there.

This only happens on bit columns with SQL defaults as you say, and Power Tools already has a flag for this behaviour.

Sorry for this confusion.

**Comment by ErikEJ** [comment]
No worries and happy you find the tool useful
