### ISSUE TITLE
Please ignore mapping fields from base classes to table columns

### ISSUE THREAD

**Issue by CorsairRO** [ErikEJ/EFCorePowerTools#1231]
Hello again,

I have discovered a thing while making all my classes to extend from a base class.
It complains in runtime that the properties doesnt exist in DB, which of course they dont exist there.

I know that i can add the [NotMapped] attribute to properties there and it is working.

But my issue is that my BaseClass is in another Assembly ( which knows nothing about EF Core references ).

I think it would also be nice to either:
- By Default ignoring mapping to base class properties ( if possible - or maybe it is useful to be there like this when you use composition )
- Or at least have an option to apply the [NotMapped] attribute to the base class itself and then ignore all properties from there.
Something along the lines where you can exclude a whole class from trying to serialize 

Thank you.

### Steps to reproduce

Please include a complete description that I can redo to reproduce the issue.

### Further technical details

EF Core version in use: EF Core 6

EF Core Power Tools version: Latest

Database engine: SQL Server

Visual Studio version:  2022 - 17.0.4

**Comment by ErikEJ** [comment]
Wonder if you could use the MetaDataType attribute pattern?

https://github.com/ErikEJ/EFCorePowerTools/issues/412#issuecomment-648789102

**Comment by CorsairRO** [comment]
Well, i dint think they are intended for that purpose. 

I am using MetadataAnnotations currently if EF edmx to add my custom validation logic to partial classes

But i am talking about being polymorphic in C# apps there, this is why i want all my entities to extend from a class, and maybe implement a few interfaces. This is why it would be nice if it would use the NotMapped to the whole base class, and just ignore properties from there to being mapped.

Sort of like you do with NewtonSoft.Json where you can ignore a property, or the whole class

thank you for answering
have a nice day there

**Comment by ErikEJ** [comment]
Maybe you should raise an issue to discuss this in the EF Core repo.

**Comment by CorsairRO** [comment]
OK, so it is not the tool that tries to map classes and properties, but the EF Core stuff.

In this case, thank you for the answer, and for your answers there, and no , thank you, EF Core as it is is just crap and it cannot be used without a nice tool like yours.

So please close the ticket, and again thank you

**Comment by ErikEJ** [comment]
Sorry I was not able to help better.
