### ISSUE TITLE
Suggestion - Stored Procedures result sets rely on very limited sp_describe_first_result_set

### ISSUE THREAD

**Issue by CorsairRO** [ErikEJ/EFCorePowerTools#1235]
Hello again,

I have found out that the resultsets are missing for 90% of the stored procedures.

The issue is that the tool relies on sp_describe_first_result_set which is very limited.
First of all, the SP is not in older versions of SQL Server, which is not necessary a problem, because i have test DB from latest SQL.

Then, the reason why we make SP is to do more complex stuff, like some updates on some tables and return a result set with a few columns, or bunch of columns if we use complex queries and temporary tables to merge results from multiple  queries.
Executing sp_describe_first_result_set in SSMS returns error as soon as it has some indirect recursion or temporary tables ( from MSDN it should so).

My suggestion is if it is possible to have some option at least not to rely on that faulty procedure and instead use the way that edmx was working:
SET FMTONLY ON;
EXEC MyProc @MyParams
I didnt have a single proc failing to scaffold the resultset like that in the last 10 years, while, like i say, the new way fails for tons of procs.

For SP that returns 1-2 columns is not a problem to manually create the resultset, but if we have 20-30 columns than it becomes an issue, not to mention that a change in DB to one of the columns type is not automatically reflected in the object when refreshing model, and it will have to be manually updated.

Thank you very much, and sorry to bother you so much :)

Like i said before, Merry Christmas there, and a Safer New Year

### Steps to reproduce

Please include a complete description that I can redo to reproduce the issue.

### Further technical details

EF Core version in use: (e.g. EF Core 5)

EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)

Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)

Visual Studio version: (e.g. Visual Studio 2019 16.11)

**Comment by ErikEJ** [comment]
Try the new multiresult set feature - see release notes about how to switch it it - it uses set fmtonly

**Comment by CorsairRO** [comment]
Hehe, thank you,

I have tried it right away, and it seems to work, but it has an issue.

If FMTONLY ON returns 3 times the same resultset there are 3 objects generated ( caused by 2-3 IF's inside it )
Which is not an issue, as i can delete the duplicates. 
Just that in ContextProcedures it tries to return all of them. And changing them will be automatically regenerated when refreshing model.

thank you,
have a nice day there

**Comment by ErikEJ** [comment]
I dont see any way to fix that TBH, you can just add a new method in a partial class with the "correct/fixed" implementation.
