### ISSUE TITLE
Reverse-engineering procedures with #temp tables

### ISSUE THREAD

**Issue by tiko514** [ErikEJ/EFCorePowerTools#1236]
Hi All.
When reverse-engineering a procedure that returns data from #temp table, the return type is not being generated, but the method for procedure call returns a list of provided type. An example is provided in [Steps to reproduce]

### Steps to reproduce
Add the following procedure to the DB:

        create procedure Scaffold_Test
        as
        begin
	        select *
	        into #obj
	        from sys.all_objects -- Too lazy to create a dummy table, so used an existing system table
        
	        select *
	        from #obj
        end

When I reverse-engineer the procedure, the following method will be generated in Procedures Context:

        public virtual async Task<List<Scaffold_TestResult>> Scaffold_TestAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
                {
                    var parameterreturnValue = new SqlParameter
                    {
                        ParameterName = "returnValue",
                        Direction = System.Data.ParameterDirection.Output,
                        SqlDbType = System.Data.SqlDbType.Int,
                    };
        
                    var sqlParameters = new []
                    {
                        parameterreturnValue,
                    };
                    var _ = await _context.SqlQueryAsync<Scaffold_TestResult>("EXEC @returnValue = [dbo].[Scaffold_Test]", sqlParameters, cancellationToken);
        
                    returnValue?.SetValue(parameterreturnValue.Value);
        
                    return _;
                }

but the Scaffold_TestResult type is not generated.

This happens when I select EF Core 6 on "Choose Database Connection" dialog.

### Further technical details

EF Core version in use: 6.0 (downgrade is not an option for me)

EF Core Power Tools version: 2.5.866.0
Database engine: SQL Server

Visual Studio version: 2022 17.0.4

**Comment by ErikEJ** [comment]
What should happen given that it is not possible to get any result set shape from the stored procedure?

**Comment by tiko514** [comment]
Scaffold_TestAsync method returns a generic list of entity that does not exist. I believe before an empty model was being created, now the method returns a list of Scaffold_TestResult which is not being generated.

**Comment by ErikEJ** [comment]
I will investigate!

**Comment by ErikEJ** [comment]
I have attempted a fix in latest daily build

**Comment by tiko514** [comment]
Thank you!
