### ISSUE TITLE
Reverse Engineering with HierarchyId-Fields

### ISSUE THREAD

**Issue by Linus62** [ErikEJ/EFCorePowerTools#1240]
I am trying to reverse engineer a DB with HierarchyId in fields, query results and functions (as parameter and result). I always get the type "object?" instead of HierarchyId.
I am using the Nuget-Module **EFCore.SqlServer.HierarchyId**. I saw that they recently added design-time services [Issue 52](https://github.com/efcore/EFCore.SqlServer.HierarchyId/issues/52) but I am not sure how to run it: Is it called by EFCorePowerTools? Is it really fixing my problem?
Please help!

**Comment by ErikEJ** [comment]
Are you talking about stored procedures and functions?

**Comment by Linus62** [comment]
I am talking about table-valued functions and scalar-valued functions. E.g.
`CREATE FUNCTION dbo.funcLocGenerateNewChildHierarchy
( 
	@parentHierarchyId HIERARCHYID -- parent des branches
)
RETURNS HIERARCHYID
AS
BEGIN
	DECLARE @maxChild HIERARCHYID = (SELECT MAX(Hierarchie)	FROM tabLocation WHERE Hierarchie.IsDescendantOf(@parentHierarchyId) = 1);
	RETURN  IIF(@maxChild = @parentHierarchyId, @parentHierarchyId.GetDescendant(NULL, NULL), @parentHierarchyId.GetDescendant(@maxChild, NULL));
END
`
or

`REATE FUNCTION dbo.funcVorgesetzteEinerPerson
( 
	@lngPersonId bigint,
	@intLevel int
)
RETURNS	@vorgesetzte TABLE 
(
	....        
	Hierarchie hierarchyid,
	OrgLevelNo smallint
)
`

**Comment by ErikEJ** [comment]
The package above does not fix your problem.

EF Core does not support mapping of functions, only EF Core.

I suppose I could assume that if anyone picks a function with hirerechyid they would want to depend on the type being present.

Then it would be up to the user to reference either the dotmorten package or the EFCore package.

Thoughts?

**Comment by Linus62** [comment]
Actually if I replace "object?" with "HierarchyId?" (resp. "object" with HierarchyId on mandatory fields) everything works fine. 
If EFCorePowerTools could just leave the type HierarchyId, only the "using Microsoft.EntityFrameworkCore" is lacking (can be added by a partial class).
Would that not be a meaningful enhencement?

**Comment by ErikEJ** [comment]
Yes, that is what I am proposing! Will look into it

**Comment by ErikEJ** [comment]
Or: Can you share a modified project that builds?

**Comment by ErikEJ** [comment]
https://sergiopereira.com/blog/archive/2008/06/udttypename-and-net-data-types-in-sql.html

**Comment by Linus62** [comment]
Hi Eric. I will try it out this afternoon ... By the way: for tables and views I also have to add HierarchyId fields manually. If you are going to fix the issue with the function parameters and results it would be nice if you add generation of HierarchyId fields in tables/views. For newbys you can probably add a hint that EFCore.SqlServer.HierarchyId has to be added.

**Comment by ErikEJ** [comment]
Any updates?

**Comment by Linus62** [comment]
Sorry, I am quite busy...  I would like to send you a database creation SQL script of my DB. Than you  can try by yourself generating reverse-engineering code for it. ok?

**Comment by ErikEJ** [comment]
No, I am interested in this:

How do you call: dbo.funcLocGenerateNewChildHierarchy from ADO.NET?

**Comment by Linus62** [comment]
Actually I am trying to port an unfinished application from .NET 4.8 to .NET6. In the original version I am using the library "EntityFramework.CodeFirstStoreFunctions" [()](https://www.nuget.org/packages/EntityFramework.CodeFirstStoreFunctions/). 
But there are some "magics" I do not really understand how it works....

**Comment by ErikEJ** [comment]
Yeah, you need to move away from that!

**Comment by ErikEJ** [comment]
I have attempted a fix in the latest daily build
