### ISSUE TITLE
Model from Stored Procedure scaffolded in different manner as Tables

### ISSUE THREAD

**Issue by SandroRiz** [ErikEJ/EFCorePowerTools#1245]
Some fields with capital letters like "VATAmount", "PKey" are renamed in camel case (VatAmount, Pkey) when scaffolded from a table (unless you check the proper option "use table names directly from db")

The same fields if scaffolded from a stored procedure that returns the same table are not renamed in the same manner
I would suggest more consistency that is useful when you use automatic procedures to automap the 2 types

### Steps to reproduce

see above

### Further technical details

EF CORE 6
2.5.877
Sql 2019 cu12
VS 2022 17.0.5

**Comment by ErikEJ** [comment]
This is not something I plan to do, it will be breaking and against many other users wishes. You can just rename in your stored procedure.

**Comment by SandroRiz** [comment]
Ok, perfect. Thanks
