### ISSUE TITLE
Feature Request: Add IMyContextProcedures interface class

### ISSUE THREAD

**Issue by nathanh2011** [ErikEJ/EFCorePowerTools#1246]
First of all, thank you for this tool as it is simply amazing and I use it for all my projects now.

I was wondering, in line with the POCO class generation, if you could add a checkbox option to generate another class of stored procedures (SP) for use with Dapper. These functions would have a similar strongly typed parameter list as per the current SP functions (minus the added output return value), use the existing database connection string from the context and return the result set.

For example, if I had two SPs (GetUsers and AddUser) that gets a list of users based on some filters and adds a new user and returns the newly created primary key, your tool could generate something like the following:

```
// Stored Proc GetUsers - takes two optional params UserType and AccountID and returns a list of user objects
public List<GetUsersResult> GetUsers(int? userType, int accountID) {
	using (SqlConnection conn = new SqlConnection(context.Database.GetConnectionString())) {
		string stpName        = "GetUsers";

		DynamicParameters stpParams = new DynamicParameters();
		stpParams.Add("UserType", dbType: DbType.Int32, direction: ParameterDirection.Input);
		stpParams.Add("ReturnDeviceID", dbType: DbType.Int32, direction: ParameterDirection.Input);
			
		var result = conn.Query<GetUSersResult>(stpName, stpParams, commandType: CommandType.StoredProcedure);
			
		return result;
	}
}

// Stored Proc AddUser - takes two params Email and Name and creates a new user and returns the ID of the new record
public int AddUser(string email, string name) {
	using (SqlConnection conn = new SqlConnection(context.Database.GetConnectionString())) {
		string stpName = "GetUsers";

		DynamicParameters stpParams = new DynamicParameters();
		stpParams.Add("Email", dbType: DbType.String, direction: ParameterDirection.Input);
		stpParams.Add("Name", dbType: DbType.String, direction: ParameterDirection.Input);
		stpParams.Add("ReturnID", dbType: DbType.Int32, direction: ParameterDirection.Output);
			
		var result = conn.Execute(stpName, stpParams, commandType: CommandType.StoredProcedure);
			
		return result;
	}
}
```

The reason for this is that it would allow us to keep a strongly typed Dapper SP call so that if we update the database it would update all the functions, therefore adding/removing parameters to our procedures would be reflected in every function call throughout our projects and ensure it gets covered when building.

I use a mix of both EF and Dapper in my projects and this would be an awesome addition to simply use this tool to generate the code and leverage the already established classes and database context.

**Comment by ErikEJ** [comment]
Reluctant to also do this - and supporting this - there are so many hidden corners in stored procedure support. Re-implementing and supporting that for Dapper - not sure.

Could you not just share the generated result set classes?

**Comment by ErikEJ** [comment]
Why not just use EF Core - why do you need to add Dapper to the mix?

**Comment by ErikEJ** [comment]
You can use a pooled DbContextFactory with EF Core 6.

What if the SQL parameters were exposed as a List<SqlParameter> in the generated code?

**Comment by nathanh2011** [comment]
I am not sure the List would make a difference really. It was the simplicity of your generated method with specified parameters I was hoping to duplicate.

No stress, I understand it's not a change you want to support. As I said before I just assumed it might be an easy implementation based on your existing code for generating methods based on SPs.

**Comment by ErikEJ** [comment]
But you could then use the list as the single source of truth for the shape of SQL parameters.

**Comment by ErikEJ** [comment]
There are some related proposals here: https://github.com/ErikEJ/EFCorePowerTools/issues/1128

**Comment by nathanh2011** [comment]
> But you could then use the list as the single source of truth for the shape of SQL parameters.

> There are some related proposals here: #1128

I am not sure how the list or the proposal in #1128 would work to ensure all the required parameters are used, unless you force instantiation only by a constructor. The beautify of what you have is the SP function has all the arguments as required/nullable, so adding a new required param in SQL and rebuilding the model would show a compile error if the code was not updated.

**Comment by ErikEJ** [comment]
You could build the Dynamicparameters based on the list of SqlParameter, then the parameters would always reflect the truth:

```
foreach (var sqlParam in ListOfSqlParameters)
{
   stpParams.Add(sqlParam, dbType: sqlParam.DbType, direction: sqlParam.Direction);
}

```

But maybe that does not solev your issue?? I could be misunderstading or not understanding dapper (like how does the supplied values get passed to the parameters?)

**Comment by nathanh2011** [comment]
Maybe I am not clear, sorry I will try and re-ask the question.

Say for example I have a SP that updates the password for a user. The SP has two parameters, Username and Password. Currently your power tool will generate the following function:

public virtual async Task<int> stpUpdateUserAsync(string Username, string Password, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
  ```
  {
        var parameterreturnValue = new SqlParameter
        {
            ParameterName = "returnValue",
            Direction = System.Data.ParameterDirection.Output,
            SqlDbType = System.Data.SqlDbType.Int,
        };

        var sqlParameters = new []
        {
            new SqlParameter
            {
                ParameterName = "Username",
                Size = 250,
                Value = Username ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.VarChar,
            },
            new SqlParameter
            {
                ParameterName = "Password",
                Size = 256,
                Value = Password ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.NVarChar,
            },
            parameterreturnValue,
        };
        var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[stpUpdateUser] @Username, @Password", sqlParameters, cancellationToken);

        returnValue?.SetValue(parameterreturnValue.Value);

        return _;
    }
```

And what I was asking, could we have an option to create an addition set of SP functions (if you check the box) that do almost the exact same but change the body to user Dapper or just execute the SP without having to create a DB context for performance. So, taking the above, the additional "Dapper" function would look like:

```
public virtual void stpUpdateUserDapper(string Username, string Password)
{
    
    var sqlParameters = new []
    {
        new SqlParameter
        {
            ParameterName = "Username",
            Size = 250,
            Value = Username ?? Convert.DBNull,
            SqlDbType = System.Data.SqlDbType.VarChar,
        },
        new SqlParameter
        {
            ParameterName = "Password",
            Size = 256,
            Value = Password ?? Convert.DBNull,
            SqlDbType = System.Data.SqlDbType.NVarChar,
        }
       
    };

    using (SqlConnection conn = new SqlConnection(_context.Database.GetConnectionString())) {
		string stpName        = "[dbo].[stpUpdateUser]";	
		var _ = conn.Query<GetUSersResult>(stpName, sqlParameters, commandType: CommandType.StoredProcedure);			
		return result;
	}    

    return;
}
```

So it still uses your parameter generation and SP name. Drops any additional return value unless a param is declared as OUT.

And what this gives, is if I update the SQL SP and add a new parameter such as "Salt" as another varchar and reverse the model again. Anywhere in the code that uses this function would need to be updated to provide that new parameter otherwise it would be a compile error.

**Comment by ErikEJ** [comment]
Basically you would like an interface (contract) to be generated then, that your Dapper (or raw ADO.NET) implementation could the implement? If the interface changes, your implementation must be updated.

```
public interface IGetStoredProcedures()
{
   List<GetUsersResult> GetUsers(int? userType, int accountID);
}
```

**Comment by ErikEJ** [comment]
Thoughts?

**Comment by nathanh2011** [comment]
Yea that could work, or maybe as a static class created under the specified namespace from the tool?

**Comment by ErikEJ** [comment]
Glad we could get it boiled down to this.

**Comment by ErikEJ** [comment]
I have attempted to implemement this in the latest daily

**Comment by nathanh2011** [comment]
Hi @ErikEJ I found a slight issue, if the SP has no parameters the interface function is not well formed and has an extra comma before the CancellationToken parameter.

 
![image](https://user-images.githubusercontent.com/38150994/150526907-034a964b-fbff-4dd2-b62b-df120c42c0f9.png)

**Comment by ErikEJ** [comment]
@nathanh2011 I have created an issue for that!
