### ISSUE TITLE
Stored procedure with Geography type causes exceptions when executed

### ISSUE THREAD

**Issue by nathanh2011** [ErikEJ/EFCorePowerTools#1247]
I am getting type mapping exceptions when running a stored procedure with a geography data type defined as a parameter.

The Power Tool generates the stored procedure method with the following parameter defined.
```
 new SqlParameter
  {
      ParameterName = "Location",
      Value = Location ?? Convert.DBNull,
      SqlDbType = System.Data.SqlDbType.Variant,
  },
```

When I call my function (`context.Procedures.stpInsertLocationAsync(...)`) I get the following exception if I have data for the point / Location parameter.

System.AggregateException: 'One or more errors occurred. (No mapping exists from object type NetTopologySuite.Geometries.Point to a known managed provider native type.)'
ArgumentException: No mapping exists from object type NetTopologySuite.Geometries.Point to a known managed provider native type.

And I get the following exception if the point / Location parameter is null.

System.AggregateException: 'One or more errors occurred. (Operand type clash: sql_variant is incompatible with geography)'
SqlException: Operand type clash: sql_variant is incompatible with geography

**Comment by ErikEJ** [comment]
Are you able to fix manually, and in that case how?

**Comment by nathanh2011** [comment]
I must be missing something because this took me a while of digging around to find a workable solution. I can't see how calling a SP with a geography parameter has not been solved by EF + NTS by 2022, so while the below works it is very possible I am not aware of some other simple solution.

To try and work out how to do it I created a small test SP that accepts a geography param and returns the current date/time as an out parameter. I also went back to trying to call the SP manually rather than the function that your scaffolding created just to keep it simple (although the power tool created function works fine when updated) and found the only way send a geography parameter is to send it as a binary parameter from code. 

```
using (var context = DBContext()) {
    Point p = new Point(151.2093, -33.8688);
    p.SRID = 4326;
    
    var geometryWriter = new SqlServerBytesWriter {IsGeography = true};
    var geometryBytes  = geometryWriter.Write(p);
    
    SqlParameter param1 = new SqlParameter() {
	    ParameterName = "@Geo1",
	    Value         = geometryBytes,
	    SqlDbType     = SqlDbType.VarBinary
    };
    SqlParameter param2 = new SqlParameter() {
	    ParameterName = "@DateReturn",
	    SqlDbType = SqlDbType.DateTimeOffset,
	    Direction = ParameterDirection.Output
    };
    
    var result = context.Database.ExecuteSqlRaw("exec stpTestGeography @Geo1, @DateReturn OUT", param1, param2);
}
```

One thing I could not figure out however, was trying to have an output / return geography parameter, setting the param as binary does not work, setting it as a UDT type does but doesn't return the value. But for now, simply being able to send the param as an input is my priority.

Hopefully that all makes sense.

**Comment by nathanh2011** [comment]
I also found setting the parameter as a UDT also does work, but again only if you pass the byte array as the actual value.

```
SqlParameter param1 = new SqlParameter() {
	ParameterName = "@Geo1",
	Value         = geometryBytes,
	SqlDbType     = SqlDbType.Udt,
	UdtTypeName   = "Geography"
}
```

**Comment by ErikEJ** [comment]
Glad it was not so simple!

I will look into the UDT approach! (Should also work for hierarchyid then)

so geometryBytes is of type: `byte[]`

**Comment by nathanh2011** [comment]
> 
> so geometryBytes is of type: `byte[]` ??

Yes it is.

**Comment by ErikEJ** [comment]
CREATE PROCEDURE [dbo].[test] 
	-- Add the parameters for the stored procedure here
	@p1 geography
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    -- Insert statements for procedure here
	SELECT 1
END

**Comment by ErikEJ** [comment]
I have attempted a fix in the latest daily build
