### ISSUE TITLE
Feature Request: Proposal to let decide what model should return a Stored Procedure

### ISSUE THREAD

**Issue by SandroRiz** [ErikEJ/EFCorePowerTools#1248]
Right now if you reverse engineer a SP  (eg. GetCustomers) the tool create a new model called GetCustomersResult and the method returns a List<GetCustomersResult>

Often those sp returns tables that are already scaffolded (eg. table Customers) so it would nice if the return value will be List<Customer>

I guess that understanding from sp source what it returns is very complicated (it could be a select * from #temp where #temp has the same structure of tbl Customers) so the only way is to ask the user if he wants to map the result to an existing table (and if that table is not selected for scaffolding it should be created anyway)

The old dbml designer of linq2sql has this feature where you could "choose" between "**Auto-generated Type**" (like power tools now), an **entity**, a **scalar** (eg a int if the sp returns a count not with an output param) and **None** (for insert/update proc)

I know that it would be not so easy for UI/UX... maybe a dropdown near the sp name?

PLEASE before, investigate if that has EF issue, because changing manually the type returned I had some error from EF about constructing relationship ("Unable to determine the relationship represented by navigation")
Please check this sample
https://github.com/SandroRiz/EFcorePowerTools_SP_Proposal

![0](https://user-images.githubusercontent.com/7381657/149781018-53f3b704-529b-48c2-b8d0-e450e0d37c67.jpg)
![1](https://user-images.githubusercontent.com/7381657/149781050-4d3d874f-e4cc-4d87-9567-31a44a689121.jpg)
![2](https://user-images.githubusercontent.com/7381657/149781058-f5c2e421-d086-4554-a648-1f5611a0b23e.jpg)
![3](https://user-images.githubusercontent.com/7381657/149781062-6e16ef65-3e3f-45f9-86fd-e4069e3ab685.jpg)

**Comment by ErikEJ** [comment]
The error is probably due to this

`    _context.SqlQueryAsync<Product>("..."`

If you look at the implementation of SqlQueryAsync, you will see that it create a new DbContext.

Probably it should be:

`   _context.FromSqlRawAsync<Product>(",,,") `

**Comment by ErikEJ** [comment]
This is not something I want to do, you cannot treat a result from a stored proceure like a IQueryable DbSet.
