### ISSUE TITLE
Camel casing dictionary

### ISSUE THREAD

**Issue by joshmouch** [ErikEJ/EFCorePowerTools#125]
How does this tool determine what a "word" is for the purposes of casing class names, and such?
I'd like to add a few of our common acronyms to this list before the classes are generated.

**Comment by ErikEJ** [comment]
There currently is no way to customize the pluralizer, which is implemented here:

https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/ReverseEngineer20/ReverseEngineer/Pluralizer.cs

**Comment by ErikEJ** [comment]
But a PR to do this would be very welcome...
