### ISSUE TITLE
Foreign Key Links

### ISSUE THREAD

**Issue by davidhendrickmb** [ErikEJ/EFCorePowerTools#1250]
Hi there,

I'm upgrading my projects from Net 5 to Net 6 and thus VS 2022 and EF Core 6.
I'm installed plugin version 2.5.877 into VS2022 today and have some strange changes to the foreign key table connections.
I've a Person table which has a link to a PersonInRole table. This has now been renamed to Roles as the navigation item and Role as the table, causing a lot of my code to break.
Is this something new or something I can disable?
I've also got something similar where I have a Bcc and Cc table that doing to a message table which are now just called Messages and MessagesNavigation, making them very hard to decipher.

Thanks,
David

**Comment by ErikEJ** [comment]
Many to many Entities are no longer a Thing.

A simple git compare should be able to tell you.

**Comment by davidhendrickmb** [comment]
OK thank you for the quick response. 
I'm also getting this error, even though this entity has a PK:
The entity type requires a primary key to be defined. If you intended to use a keyless entity type, call 'HasNoKey' in 'OnModelCreating'.

Would you know why that would be?

**Comment by davidhendrickmb** [comment]
When I enabled "Use many to many entity (EF Core 6)" the references were back correct. 
They do now have specific index names though and I'm wondering if these names differ across dev/UAT/Live will that cause any issues?
I'm also still ahving the primary key issue.

**Comment by ErikEJ** [comment]
>> Would you know why that would be?

No, not without a repro.

**Comment by davidhendrickmb** [comment]
This is the SQL to generate the table:


/****** Object:  Table [dbo].[AccompanimentType]    Script Date: 18/01/2022 16:35:59 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[AccompanimentType](
	[AccompanimentId] [int] IDENTITY(1,1) NOT NULL,
	[AccompanimentText] [nvarchar](50) NULL,
	[SortOrder] [smallint] NULL,
	[RecordCreated] [datetime] NULL,
	[RecordModified] [datetime] NULL,
	[AccompanimentIcon] [nvarchar](50) NULL,
	[Online] [bit] NULL,
 CONSTRAINT [PK_Accompaniment] PRIMARY KEY CLUSTERED 
(
	[AccompanimentId] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[AccompanimentType] ADD  CONSTRAINT [DF_Accompaniment_RecordCreated]  DEFAULT (getdate()) FOR [RecordCreated]
GO

ALTER TABLE [dbo].[AccompanimentType] ADD  CONSTRAINT [DF_Accompaniment_RecordModified]  DEFAULT (getdate()) FOR [RecordModified]
GO

**Comment by davidhendrickmb** [comment]
The first time you run a query on the database it will throw the error.
This is my config, I've removed a couple of items:

{
   "CodeGenerationMode": 2,
   "ContextClassName": "",
   "ContextNamespace": null,
   "DefaultDacpacSchema": null,
   "FilterSchemas": false,
   "IncludeConnectionString": true,
   "ModelNamespace": null,
   "OutputContextPath": null,
   "OutputPath": "Models",
   "ProjectRootNamespace": "TestEfCoreApp",
   "Schemas": null,
   "SelectedHandlebarsLanguage": 0,
   "SelectedToBeGenerated": 0,
   "Tables": [
      {
         "Name": "[dbo].[AccompanimentType]",
         "ObjectType": 0
      }
   ],
   "UiHint": "",
   "UseBoolPropertiesWithoutDefaultSql": false,
   "UseDatabaseNames": false,
   "UseDbContextSplitting": false,
   "UseFluentApiOnly": true,
   "UseHandleBars": true,
   "UseInflector": true,
   "UseLegacyPluralizer": false,
   "UseManyToManyEntity": true,
   "UseNoConstructor": false,
   "UseNoDefaultConstructor": false,
   "UseNoNavigations": false,
   "UseNoObjectFilter": false,
   "UseNodaTime": false,
   "UseNullableReferences": false,
   "UseSchemaFolders": false,
   "UseSpatial": false
}

**Comment by davidhendrickmb** [comment]
[TestEfCoreApp.zip](https://github.com/ErikEJ/EFCorePowerTools/files/7891023/TestEfCoreApp.zip)

**Comment by davidhendrickmb** [comment]
Hopefully this is what you need.

**Comment by ErikEJ** [comment]
Ah - Handlebars! You may need a new set of templates, try renaming/removing the Codetemplates folder

**Comment by davidhendrickmb** [comment]
Unfortunately the error is still there even with a newly generated CodeTemplates folder.

On a side note, is using the "Use many to many entity (EF Core 6)" considered ok? It does have the specific index names mentioned, so if these differ between dev/uat/live databases will that cause me any issues?

**Comment by davidhendrickmb** [comment]
It works if I add the "Key" to the model but obviously this isn't something that can be done at scale

![image](https://user-images.githubusercontent.com/18259436/150124431-cc0c2c5f-4a14-4bfe-9f3c-13b131f37cae.png)

**Comment by davidhendrickmb** [comment]
Sorry about all the messages. When I target EF Core 5, the HasKey parameter is set in the DbContext as below:

![image](https://user-images.githubusercontent.com/18259436/150125985-1672d642-a202-4035-a201-7e5c79958680.png)

**Comment by ErikEJ** [comment]
But not when you target 6.0 even without Handlebars?

**Comment by davidhendrickmb** [comment]
When I target 6.0 and switch off Handlebars the "HasKey" is present. 
It fails when Handlebars is enabled with either the C# or TypeScript format.

**Comment by ErikEJ** [comment]
Please report in the handlebars repo then. 

I am using this: 		

`<PackageReference Include="EntityFrameworkCore.Scaffolding.Handlebars" Version="6.0.2" />`

**Comment by TimKras** [comment]
@davidhendrickmb, a tempoarary workaround is overriding the OnModelCreatingPartial method and add the missing HasKey statements. It works for me.

**Comment by tonysneed** [comment]
@ErikEJ Fixed with Handlebars [v6.0.3](https://www.nuget.org/packages/EntityFrameworkCore.Scaffolding.Handlebars/6.0.3).

**Comment by ErikEJ** [comment]
Great  I will get it in the latest daily tomorrow

**Comment by ErikEJ** [comment]
Fixed in latest daily

**Comment by davidhendrickmb** [comment]
Hi both,

Thank you so much for resolving this so quickly, I can confirm this fixed the issue.

I have another question if I may.
The new model generation includes actual index names in the model. You can see the difference between the old and new in the image below.
I was wondering what the reasoning for this is? If the index for any reason has a different name between our different databases, will this now throw an error?

![image](https://user-images.githubusercontent.com/18259436/150802865-94c14e07-2758-4c07-9cd2-6009861e1723.png)


Many thanks,
David

**Comment by ErikEJ** [comment]
The index names are not used at runtime.

**Comment by davidhendrickmb** [comment]
Super! Thank you again so much!
