### ISSUE TITLE
Microsoft.Data.SqlClient is not supported on this platform

### ISSUE THREAD

**Issue by rmEDFrame** [ErikEJ/EFCorePowerTools#1255]
Visual Studio 2022, .NET 6.0, Blazor Web Assembly App
Dependencies: Microsoft.AspNetCore.Components.WebAssembly(6.0.1), Microsoft.AspNetCore.Components.WebAssembly.DevServer (6.0.1), Microsoft.EntityFrameworkCore (6.0.1), Microsoft.EntityFrameworkCore.SqlServer (6.0.1)

Error: Microsoft.Data.SqlClient is not supported on this platform

Notes: I was able to connect and get data from a Console app, but could not in a Blazor app, using same code in both:

var db = new DBContext();
var get = db.TestTable.ToList();
foreach(var item in get)
{

}

**Comment by ErikEJ** [comment]
How does that relate to Power Tools?

**Comment by rmEDFrame** [comment]
I used Reverse Engineer in EF Core Power Tools to import TestTable from my database in Sql Server Azure and it created the classes the classes TestTable.cs and DBContext.cs.  It works great in a console application (.NET 6) but gives the error when I run the same code in a Blazor web app (.NET 6)
