### ISSUE TITLE
Using custom helpers

### ISSUE THREAD

**Issue by joshmouch** [ErikEJ/EFCorePowerTools#126]
Can you add custom handlebar helpers somehow?

I'm just wondering because the handlebar templates created look a lot like the ones from here:

https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#handlebars-helpers

And that allows for helpers.

**Comment by ErikEJ** [comment]
No, in order to do that, you must use the command line tooling (scaffold dbcontext)
