### ISSUE TITLE
Excluding columns from table not working properly.

### ISSUE THREAD

**Issue by CorsairRO** [ErikEJ/EFCorePowerTools#1264]
Hello again.

I have encountered many errors now because i want to use Table Splitting as suggested in EF Core.
Therefore i wanted some binary columns from a table to be Excluded by code generation in that class.
I have manually added a new details class and mapped it successfully as EF Core Doc says.

BUT, i got lots of errors that i didnt know where they come from at runtime, complaining about columns missing.
Then, looking in the Generated class for the object with EF Core Power Tools the columns are still there .
Then it complains of course because i have 2 mapping properties for one DB Column.

If i go to generated code and comment out those ( that i think should not be there ) then ctx works.

In ef.config.json it saves correctly ExcludeColumn Names MyCOlumn1, 2 and so on...
Just that in the generated class they are still there.

Also ticking the remove default for nullable bools generates the properties as bool? instead of bool. But this is a minor issue as i have already have object initializers that sets the properties.

Thank you in advance,
Have a nice day there

### Steps to reproduce

Please include a complete description that I can redo to reproduce the issue.

### Further technical details

EF Core version in use: EF Core 6

EF Core Power Tools version: latest

Database engine: SQL Server

Visual Studio version: 17.0.4

**Comment by ErikEJ** [comment]
Handlebars?

I need a proper repro in order to help!
