### ISSUE TITLE
Request: Handlebar Support in OnModelCreating method

### ISSUE THREAD

**Issue by pwcrickman** [ErikEJ/EFCorePowerTools#1265]
I am migrating an EF 6 model to EF Core 3.1.  I have noted that the navigation property names within a model .cs class that contain one or more underscores are truncated in the auto-generated class by your tool.  Furthermore the OnModelCreating method code generated in the DBContext class contains the same truncated name.  I am able to override the behavior in the model .cs class by using the handlebar option and editing the CodeTemplates/CSharpEntityType/Partials/Properties.hbs file by updating `nav-property-name` to `nav_property-type`

```cs
{{#if nav-property-collection}}
{{spaces 8}}public virtual ICollection<{{nav-property-type}}> {{nav-property-name}} { get; set; }{{#if nullable-reference-types}} = default!;{{/if}}
{{else}}
{{spaces 8}}public virtual {{nav-property-type}} {{nav-property-name}} { get; set; }{{#if nullable-reference-types}} = default!;{{/if}}
{{/if}}
```
to 
```cs
{#if nav-property-collection}}
{{spaces 8}}public virtual ICollection<{{nav-property-type}}> {{nav-property-type}} { get; set; }{{#if nullable-reference-types}} = default!;{{/if}}
{{else}}
{{spaces 8}}public virtual {{nav-property-type}} {{nav-property-type}} { get; set; }{{#if nullable-reference-types}} = default!;{{/if}}
{{/if}}
```

However there is not an analogous handlebar available for overriding the Entity<T>.HasOne extensions in the OnModelCreating method where the navigation property parameters are further defined.  Could this feature be added?

### Further technical details

EF Core version in use: EF Core 3.1
EF Core Power Tools version: 2.5.877.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Visual Studio version: Visual Studio 2019 16.11.9

**Comment by ErikEJ** [comment]
Sounds like a Handlebars library feature request https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars
