### ISSUE TITLE
unable to add connection when adding connection to sql server

### ISSUE THREAD

**Issue by LKujala** [ErikEJ/EFCorePowerTools#1266]
ran into a problem; restarted VS and problem went away.
error message dialog: "unable to add connection, maybe the provider is not supported: exception has been thrown by the target of an invocation."
about as generic an error message as you can get.

I have run this tool a number of times over the last few months without a problem.

### Steps to reproduce

ver 2.5.877

1 - in solution explorer, right click on project, select EF Core Power Tools + Reverse Engineer
2 - dialog shows up with
- EF Core 6 selected
- sql connection combo box empty
- dacpac combo box set not empty
-  the error is: the sql connection list is populating the dacpac list

3 - click on the "add" new sql connection, fill in and test the sql connection,
4 - the new sql connection from the dialog does not populate the combo box
5 - click on OK, a error dialog is shown, and everything is toast after that.

I know the above steps are totally useless to reproduce; this is more of an FYI than expecting anything to be fixed.
the error was repeatable until I restarted VS, after which the problem went away.
if it comes back I will give you an update.

### Further technical details

EF Core version in use:  EF Core 6

EF Core Power Tools version: 2.5.877

Database engine: SQL Server

Visual Studio version: 17.0.5

**Comment by ErikEJ** [comment]
Maybe corrupt connection in Server Explorer?
