### ISSUE TITLE
FReq: split the "use spatial and hierarchyid" checkboxes

### ISSUE THREAD

**Issue by CaiusJard** [ErikEJ/EFCorePowerTools#1268]
For those people who only use one of them, it prevents an error when `.UseNetTopologySuite().UseHierarchyId());` is added to OnConfiguring but only one relevant extension project is referenced

It's not a train smash, of course; easy to comment out every time a reverse is done!

![image](https://user-images.githubusercontent.com/68939130/151957954-11210457-b326-4aef-87ff-9a56608815c8.png)

**Comment by ErikEJ** [comment]
Thanks for reporting  I will get that fixed.

**Comment by ErikEJ** [comment]
Fixed in latest daily, let me know if it works for you.
