### ISSUE TITLE
Feature Request: If property-comment is JSON, use it to overwrite other handlebars variables

### ISSUE THREAD

**Issue by CaiusJard** [ErikEJ/EFCorePowerTools#1269]
Having turned on handlebars templates for a bit of a play I was hoping I could trick the extension into injecting some non comment during a scaff..

I set a comment in the DB column of:

```
<summary>
        /// Hello world
        /// </summary>
        [MaxLength(123)]
```

To see if I could force some attributes into a context that is fluent configured 

EFCPT seems to split the comment on newlines, and prefix everything with /// (and XML encode) so my hacking was defeated :) but then I realized it wouldn't do what I want anyway, because I was hoping to do a tweak for enums as strings:

    [ColumnType("varchar(16)")]
    public MyStatusEnum Status{get;set;}

and the property type is of course still put down as string..

Hence the feature request: if we could do something like putting some JSON into the DB's comment field, such that it ends up in whatever variable is pumped into `property-comment`, then EFCPT could have a go at de-ser'ing the comment field and if it does de-ser (to a dictionary, say) then it could pump the KeyValuePairs into handlebars variables?

This way I could e.g. set the DB comment to 

```
    { 
      "property-comment": "Status of the order",
      "property-annotations": [ "[Column(TypeName = \"varchar(16)\")]" ], 
      "property-type": "StatusEnum" 
    }
```

And the default handlebars template would pick up the overrides:

```
{{#each property-annotations}}
        {{{property-annotation}}}
{{/each}}
        public {{property-type}} {{property-name}} ...
```

And I'd get the C# I was hoping for:

```
    /// <summary>
    /// Status of the order
    /// </summary>
    [Column(TypeName = "varchar(16)")]
    public StatusEnum OrderStatus {get;set;}
```

Or I could even put my own custom variables in the DB json and write them in the hb template...

**Comment by CaiusJard** [comment]
(Could probably solve the "rename the nav props" ticket with this one too)

**Comment by ErikEJ** [comment]
I have been thinking about this, and not sure it is a path I want to follow.

Also, relying on DB comments may not be possible for everyone.

For enums, you can create a partial class that exposes the enum.

**Comment by CaiusJard** [comment]
> For enums, you can create a partial class that exposes the enum.

But then you need to untick it in the table/column tree, and then it doesn't generate into the fluent. I understand some of the misigivngs about it, but in favor of it:

* using comments to generate [code] is a pattern evident elsewhere (e.g. swagger/swashbuckle generating enhanced openapi specs based on code comments) type interfaces for example) 
* comments on columns are supported in SQLS, Oracle, PG and MySQL at least, probably many other DBs
* it need only be in a dev database the EFCPT generates against 
* it should be a tickable option
* it could be a halfway house to another form of control, such as putting a UI in/ extending the table/column tree with an "overrides" column that is stored in the efcpt.json - it's possibly a relatively trivial amount of dev because the code to pull the comment exists, the UI does (whatever query tool the user likes)
* How about providing it as part of a plugin type system where "DLL X", if present, is loaded and given "here is the property with all its present data, give me a proeprty back with overridden data that I can use"

I'm interested to have a play around with it, and I've located the part of the code that creates the .hbs files, and the part of the code that appears to write the props (so I could modify that, and not even use the hbars.. but I'd prefer it to be part of the "if handlebars are active") but I don't see how the two tie together - never touched any dev with handlebars apart from a tiny bit of javascript umpteen years ago. How are the hbs files used? What part of the code bundles up some variables (values and arrays of values) and says "here you go handlebars; take these hbs files and these key-values like `property-comment: "Status of the order"` and churn out some C#" ? Nothing jumps out at me as the "this is how EFCPT calls on Hbars to use the .hbs files to create .cs"? What part of the code do I need to look at to find it?

**Comment by CaiusJard** [comment]
Can I get a different steer then? I've modified both CommentCSharpEntityTypeGenerator.cs, run it in debug VS2019, but absolutely nothing changed.. I modified both `<autogenerated>` to add a "Hello" -> still no change in the output entities.. Yet I've also modified the assemblyinfo version, and the UI, and those changes are reflected fine...

![image](https://user-images.githubusercontent.com/68939130/152428094-3527b4c0-693e-42b7-9f5e-e3e7c1d456ca.png)
![image](https://user-images.githubusercontent.com/68939130/152428332-759e4db9-e552-407e-8f55-eb573327e2cf.png)

Yet nothing I do in any of the RevEng.* projects seems to take any effect:

![image](https://user-images.githubusercontent.com/68939130/152428971-a4dafc9f-a61d-486d-9eb6-7eca1e5b5241.png)


Any ideas what's going on here?

**Comment by CaiusJard** [comment]
Turned out I don't have 7zip installed so the ef*.zip.exe can't make. Swapped the .cmd files to use e.g. `powershell Compress-Archive .\bin\Release\net6.0\publish\* efreveng60.exe.zip`

**Comment by ErikEJ** [comment]
I use 7 zip for max compression

**Comment by ErikEJ** [comment]
Comment handling is built into EF Core 6 , maling this not feasible.

**Comment by CaiusJard** [comment]
It seems possible to swap out the CSharpEntityTypeGenerator like you do for net5? Or did you deem it a "possible, but becomes a headache keeping up with all their changes"?

**Comment by ErikEJ** [comment]
I really prefer to avoid it if at all possible.

**Comment by CaiusJard** [comment]
Hmm; yes - I've completed the work to do that approach and I can see why

What about to modify the model that is sent to the code generator instead? Leave their generator alone? It's a nuisance that it's not easily mutable but perhaps it can be proxied..
