### ISSUE TITLE
EF Core 6 Power Tools not showing in VS 2022 Version 17.1.0 Preview 5.0

### ISSUE THREAD

**Issue by janseris** [ErikEJ/EFCorePowerTools#1271]
EF Core Power Tools menu is not showing when right-clicking a .NET 6 project using EF Core 6.
efpt.config.json is present in the project.

EF Core version in use: EF Core 6.0.1

EF Core Power Tools version: 2.5.682

Visual Studio version: VS 2022 Version 17.1.0 Preview 5.0

**Comment by ErikEJ** [comment]
I would suggest updating Visual Studio and the extension to the latest Market Place release, .682 does not support VS 2022

**Comment by nstratton-srx** [comment]
Thanks for this comment but it would be nice if the extension could say, VS is incompatible. I spent too much time yesterday watching the installer add this extension, only to have nothing install.
