### ISSUE TITLE
PK Columns NOT named ID are NOT set a .HasKey ?

### ISSUE THREAD

**Issue by CorsairRO** [ErikEJ/EFCorePowerTools#1272]
Hello again,

is it something that your tool is touching when generate, or the stupid idiots from MS do so?
I mean how hard can it be for them to see PK and AUTOINCREMENTED on columns to automatically get in model ?

From my 900+ tables, only 3 or 4 that happened to have the PK Named ID were set.
The rest, nothing, and o course my context isnt starting.

Thank you MS for me having to go and add 900+ .HasKey ( e=>e.MyColumnNOTNamedID ).UseIdentityColumn()

Thank you Erik for you great effort in the tool

### Steps to reproduce

Please include a complete description that I can redo to reproduce the issue.

### Further technical details

EF Core version in use: EF Core 6

EF Core Power Tools version: Latest

Database engine: MS SQL Server / Azure SQL

Visual Studio version: 17.0.5 ( 2022 Current )

**Comment by CorsairRO** [comment]
Update: As with 900+ tables the single context approach is totally unusable, i wait >3 minutes to run a first query over it in a console app, then i have to do the same action in all the other contexts.

Thank you MS for the nice DOWNGRADE from EF6.

**Comment by ErikEJ** [comment]
That does not sound like a general bug but something in your environment.

Please provide a simple repro.

**Comment by ErikEJ** [comment]
For the slow context  you can use optimized context in WF Core 6

**Comment by CorsairRO** [comment]
hehe, now i can see in your Scaffolder that of course you are not doing anything with it, exactly like i've expected, idiots from Microsoft did so.

You are just calling codeGenerator.GenerateModel from Microsoft.EntityFrameworkCore.Scaffolding

So please close this as it is not an issue with your great tool, is an issue with MS and their conventions

**Comment by ErikEJ** [comment]
I would love to see a repro  though

**Comment by CorsairRO** [comment]
> For the slow context you can use optimized context in WF Core 6

I have already tried it but it is also unusable as i cannot have Lazy Loading with it. 
And i win from 3+ minutes => around 2 minutes, which doesnt worth the hassle everytime i update a column in model to complie it, and then run and so on...

I am talking ONLY about first time. Subsequent calls are ok, but maybe MS can explain to my apps users that they have to wait 3 minutes at login in order to be faster than it is today with EF6

**Comment by CorsairRO** [comment]
Hehe, ok, sorry, it was not intended to offend you in any way, just that for me it seems that the guys who work there were never making a REAL DB Centric app. And it is 100% real that this is how it is. 
I have some open support at MS on different topics and they were VERY happy to see some real use cases scenario for their tools which they NEVER thought of, in development stage.

Like your tool added support for Stored Procs and stuff. How are they working in a real app with aa DBA in the team?

**Comment by CorsairRO** [comment]
> I would love to see a repro though

Well, it is like i said, add a table and a PK named MyPKColumnId instead of ID. Set it to autoincrement.
Generated code will have NOTHING about that in OnConfiguring. 
You have to manually go in partial one and add a .HasKey and .UseIdentity

**Comment by CorsairRO** [comment]
Example from one of my tables:

Table : zone => PK => ZoneId int not null, autoincremented
ZoneId column is NOT EVen in the properties, so he sees it as PK column, but not added anything about it => ctx crashes.
`modelBuilder.Entity<zone>(entity =>
            {               
                entity.Property(e => e.Description)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.ZoneName)
                    .HasMaxLength(50)
                    .IsUnicode(false);
               
            });`

**Comment by CorsairRO** [comment]
After investigating all the generated OnConfiguring => NO PK has been set to Any of my entities where it is like i said, int not null, autoincrement.

What is even strange is that ALL Composite PK's are generated correctly
Like this one: entity.HasKey(e => new { e.TaskId, e.CounterCode });

I have just added a new table to my DB with PK -> ID int autoincremented => scaffold works partially ok, adds .HasKey
But instead of .UseIdentity it adds .ValueGenerated Never => i still have to touch ALL the entities in order to be able to insert to the Dbet, otherwise will complain about adding same value in PK

So this is what i am talking about. HUGE difference between scholastic examples and a real Working App.

**Comment by ErikEJ** [comment]
>> Table : zone => PK => ZoneId int not null, autoincremented

The scaffolding does not generate anything if a configuration is covered by convention, as you can see [in the docs](https://docs.microsoft.com/en-us/ef/core/modeling/keys?tabs=data-annotations#configuring-a-primary-key)

If you context is crashing, some thing else must be wrong/broken. What is the error message?

Also, millions of developers use EF Core in production. 

Using 900+ tables in a single DbContext is certainly an anti pattern, and not recommended. Maybe you can share privately with the EF Core team for performance bottleneck investigation?

And agree about the Database First / DBA centric approach, that is why I created this tool!

**Comment by CorsairRO** [comment]
- Ok, thank you for the tip about convention stuff.

- Error Message is like i started to say to you in the thread here:
Exception thrown: 'System.InvalidOperationException' in Microsoft.EntityFrameworkCore.dll
An exception of type 'System.InvalidOperationException' occurred in Microsoft.EntityFrameworkCore.dll but was not handled in user code
The entity type 'zone' requires a primary key to be defined. If you intended to use a keyless entity type, call 'HasNoKey' in 'OnModelCreating'. For more information on keyless entity types, see https://go.microsoft.com/fwlink/?linkid=2141943.

If i go and add myself in partial OnModelCreating a .HasKey ( z=>z.ZoneId ) the message goes away, and now it stops to next one.

- I am not an idiot, not totally at least :) to pretend to work like this. Anyway coming from EF6 i am very used to have 50+ contexts to manage that huge nr of tables. So i am ok to split them like so ( basically i will keep the structure from EF6 ).
So i understand that they cannot do so much for this scenario as even compiled .edmx cannot do it.

Again, difference between scholastic an reality: watching tons of videos about EF Core, pretty much Every presenter says multiple contexts in an app is an anti pattern. And they are even some MVP at Microsoft that pretend this. Even one where you were invited to show your nice tool, some guy from there , dont remember his name says so when you said that your tool supports this

- Millions of developers using it in production : It doesnt necesarily mean it is so great. Apache Log4J configured wrong by MIillions of users is an example. Basically without your nice tool there, i wouldn't even consider moving ANY of my apps to this

- Thank you very much for your effort in making such a nice tool

**Comment by ErikEJ** [comment]
I would be great if you could simply share a CREATE table statement for a table that causes this issue. 
Or a simple DbContext with one entity that exhibits the issue. Sounds like something else is broken.

**Comment by CorsairRO** [comment]
I've been trying to make a repro case here, but it seems that adding only one table doesnt fail the context
I will add some more tables that has relations to it and see when i get the error.

thank you for your help there, and sorry to bother you for things that are not related to your nice tool there.

**Comment by larsholm** [comment]
I'm having this issue as well.. I will try to make a repro. We reverse-engineer 566 tables and none of the configurations contain HasKey, none of the columns are called Id. All primary keys in all tables are called RecordId, like this:

```
	CREATE TABLE [dbo].[AccountAudit](
		[AccountRecordId] [bigint] NOT NULL,
		[AuditCodeRecordId] [bigint] NOT NULL,
		[RecordId] [bigint] IDENTITY(100,1) NOT NULL,
		[UpdatedBy] [bigint] NOT NULL,
		[ChangeDate] [datetime] NOT NULL,
	PRIMARY KEY CLUSTERED 
	(
		[RecordId] ASC
	)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
	) ON [PRIMARY]
```

We use the separate configuration files feature if that helps.
The generated config for above table is:

```
    public partial class AccountAuditConfiguration : IEntityTypeConfiguration<AccountAudit>
    {
        public void Configure(EntityTypeBuilder<AccountAudit> entity)
        {
            entity.HasIndex(e => new { e.AccountRecordId, e.AuditCodeRecordId }, "idx_AccountAudit_Account");

            entity.HasIndex(e => new { e.AuditCodeRecordId, e.AccountRecordId }, "idx_AccountAudit_Code");

            entity.Property(e => e.ChangeDate)
                .HasColumnType("datetime")
                .HasDefaultValueSql("(getutcdate())");

            entity.HasOne(d => d.AccountRecord)
                .WithMany(p => p.AccountAudit)
                .HasForeignKey(d => d.AccountRecordId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_AccountAudit_Account");

            entity.HasOne(d => d.AuditCodeRecord)
                .WithMany(p => p.AccountAudit)
                .HasForeignKey(d => d.AuditCodeRecordId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_AccountAudit_Code");

            entity.HasOne(d => d.UpdatedByNavigation)
                .WithMany(p => p.AccountAudit)
                .HasForeignKey(d => d.UpdatedBy)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__AccountAu__Updat__4C6CEFE6");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<AccountAudit> entity);
    }
```

**Comment by ErikEJ** [comment]
Please create a new issue  with repro details. this is closed.
What happens if you do not use table splitting,,?

@larsholm

**Comment by larsholm** [comment]
Same thing... no HasKey..

```
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("fk_APISource_UpdateUser");
            });

            modelBuilder.Entity<AccountAudit>(entity =>
            {
                entity.HasIndex(e => new { e.AccountRecordId, e.AuditCodeRecordId }, "idx_AccountAudit_Account");

                entity.HasIndex(e => new { e.AuditCodeRecordId, e.AccountRecordId }, "idx_AccountAudit_Code");

                entity.Property(e => e.ChangeDate)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getutcdate())");

                entity.HasOne(d => d.AccountRecord)
                    .WithMany(p => p.AccountAudit)
                    .HasForeignKey(d => d.AccountRecordId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("fk_AccountAudit_Account");

                entity.HasOne(d => d.AuditCodeRecord)
                    .WithMany(p => p.AccountAudit)
                    .HasForeignKey(d => d.AuditCodeRecordId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("fk_AccountAudit_Code");

                entity.HasOne(d => d.UpdatedByNavigation)
                    .WithMany(p => p.AccountAudit)
                    .HasForeignKey(d => d.UpdatedBy)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__AccountAu__Updat__4C6CEFE6");
            });

            modelBuilder.Entity<AccountingArea>(entity =>
```

**Comment by ErikEJ** [comment]
@larsholm Please create a new issue with CREATE TABLE statement and reproduction details.

**Comment by larsholm** [comment]
Just so you know.. if I choose EF Core 5, instead of EF Core 6 in the dropdown on the first dialog 'Choose Database Connection' the issue disappears.

**Comment by ErikEJ** [comment]
@larsholm thanks, still waiting for a new issue with an actual repo...

**Comment by ErikEJ** [comment]
@larsholm Are you using Handlebars?

**Comment by larsholm** [comment]
Yes

**Comment by ErikEJ** [comment]
What happens if you do NOT use Handlebars?? 😆

**Comment by CorsairRO** [comment]
@ErikEJ i didnt use handlebars at all. 

Anyway the problem seems to be fixed partially because i have started to add some entities, and even without having the .HasKey the context was still working to pull data from it. 
I didnt fully test the updates, so the problem might be in my lots of objects from DB that some of them might collide somehow with the PK

**Comment by ErikEJ** [comment]
@larsholm Did the Fix work for you?
