### ISSUE TITLE
Information - MvvmLight is deprecated 

### ISSUE THREAD

**Issue by CorsairRO** [ErikEJ/EFCorePowerTools#1273]
Hello again,

Just to inform you about Mvvm packages getting deprecated.
As i've already told before, i have forked your tool for my internal use at least for the stopping issue with first_result_set on SP.

Also to inform you that my fork works now without any issue after the upgrade and
- replacing the 2 MvvmPackages that you were using with a single one CommunityToolkit.Mvvm.
- refactor all VM to extend from ObservableObject instead of ViewModelBase
- change usings in all VM from Galasoft to
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Messaging;
using CommunityToolkit.Mvvm.Input;
- Search and Replace in all VM RaisePropertyChanged => OnPropertyChanged
- In EF Core Tools Package.cs
- in CreateServiceProvider
replace var messenger = new Messenger() 
with var messenger = new CommunityToolkit.Mvvm.Messaging.WeakReferenceMessenger( );
- Change the signature of the private method HandleShowMessageBoxMessage to have also a first parameter object sender like this
private void HandleShowMessageBoxMessage( ShowMessageBoxMessage msg )
private void HandleShowMessageBoxMessage( object sender, ShowMessageBoxMessage msg )

So this is just to help you if you consider to update the deprecated packages and to tell you that there is no surprise.
Also if you want i can help you to do that change in your tool, so that you dont spend time on refactoring stuff.

Thank you,
have a nice day

### Steps to reproduce

Please include a complete description that I can redo to reproduce the issue.

### Further technical details

EF Core version in use: (e.g. EF Core 5)

EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)

Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)

Visual Studio version: (e.g. Visual Studio 2019 16.11)

**Comment by ErikEJ** [comment]
Thanks for the info, feel free to do a PR

**Comment by CorsairRO** [comment]
Hello,
Like i said, I have sucessfully moved nugets for Community.Toolkit to 17 and removing the deprecated MVVM Light in my fork of your app, and i really want to help there to create a Pull Request for applying these search and replaces in the files in order for you to be more focused on other important issues / nice additions to the tool.

However, the button is inactive for me? Is it something that you allow? or how is this supposed to work. No matter what i do there, the button is just inactive. 
Sorry for my thumbness there, i have never done such a thing, but i would definitively want to help there, if you agree and accept.

Have a nice day

**Comment by ErikEJ** [comment]
Which button??

You must fork the repo, create a branch in your fork, make and test code changes  , push your branch and create a PR.

https://gist.github.com/Chaser324/ce0505fbed06b947d962
