### ISSUE TITLE
EF Core 6 Split DbContext + many to many = false

### ISSUE THREAD

**Issue by airwedge123** [ErikEJ/EFCorePowerTools#1274]
In EF Core 6 if you enable "Split DbContext into Configuration classes" and also have "Use many to many entity " = false, the split DBContext option does not apply.

### Further technical details

EF Core version in use: EF Core 6

EF Core Power Tools version: 2.5.877.0

Database engine: SQL Server

Visual Studio version: Visual Studio 2022 17.0.1

**Comment by ErikEJ** [comment]
I am not able to repro that, please share more details.

**Comment by ErikEJ** [comment]
Ping?

**Comment by airwedge123** [comment]
I created a minimal example: https://github.com/airwedge123/TestEfCore.git

It seems the problem occurs when you have a table that participates in
multiple many to many relationships.

**Comment by ErikEJ** [comment]
Have you tried the latest build of Power Tools? Just released to Marketplace.

**Comment by ErikEJ** [comment]
I will have a closer look at your repro

**Comment by ErikEJ** [comment]
Thanks for reporting this, fixed in latest daily build
