### ISSUE TITLE
EF Core 6 - Reverse Engineering - Class Annotations are not created for a MySQL-DB

### ISSUE THREAD

**Issue by Florent22** [ErikEJ/EFCorePowerTools#1276]
First, thank you very much for your awesome tool!
I just updated from EF Core 3 to Ef Core 6. and using the reverse generation tool I always had a [Table] data annotation attached to my entity classes. 

`[Table("test_table")] public partial class TestTable: INotifyPropertyChanging, INotifyPropertyChanged, ICloneable`

where the string equals the table name within my database. Without that dataAnnotion, I can't create a connection because the corresponding tables were not found. Using the latest version of this tool, the dataAnnotion for the class is not created anymore.

Using handlebars:

`{{{class-annotation}}}
    public partial class {{class}} : INotifyPropertyChanging, INotifyPropertyChanged, ICloneable`

### Further technical details

EF Core 6.0.1

EF Core Power Tools version: 2.5.877.0

Database engine: MySQL (8.0.26)

Visual Studio version: Visual Studio 2022

**Comment by ErikEJ** [comment]
Does it work without Handlebars?

If you updated an existing project, get a new set of Handlebars templates by renaming/moving the `CodeTemplates` folder

**Comment by Florent22** [comment]
I indeed updated an existing project.  Retrieving a new set of Handlebars solved the issue, thank you very much

**Comment by ErikEJ** [comment]
Sadly it is a breaking change that is really hard to catch.
