### ISSUE TITLE
Feature Request: Add Abstract Constructor Method

### ISSUE THREAD

**Issue by Qpirate** [ErikEJ/EFCorePowerTools#1277]
As a developer I would like to extend the constructor of my partial entities so that when I manually create navigations I have the ability to instanciate the objects like the genertated constructor.

[Proposed Acceptance]
A protected abstract method is added to the entity generator 
This method is called on the entities main generated constructor

[Current Usage]
```
///Auto Generated Classes
public class Foo{
	public int Id {get;set;}
}

public class Bar{
	public string Code {get;set;}
}

public partial class FooBar{
	public FooBar(){
		Foo = new HashSet<Foo>();
	}
	
	public ICollection<Foo> Foo{get;set;}
}

///Extension Class
public partial class FooBar{

	public ICollection<Bar> Bar{get;set;}
}
```

[Proposed Update & Usage]
```
///Auto Generated Classes
	public class Foo
	{
		public int Id { get; set; }
	}

	public class Bar
	{
		public string Code { get; set; }
	}

	public partial class FooBar
	{
		public FooBar()
		{
			Foo = new HashSet<Foo>();
			AfterEntityCreated();
		}
		partial void AfterEntityCreated();

		public ICollection<Foo> Foo { get; set; }
	}

	///Extension Class
	public partial class FooBar
	{
		public ICollection<Bar> Bar { get; set; }

		partial void AfterEntityCreated()
		{
			Bar = new HashSet<Bar>();
		}
	}
```

**Comment by ErikEJ** [comment]
Maybe you can use Handlebars templates fir this?

**Comment by Qpirate** [comment]
Hi @ErikEJ How would I do this?

I downloaded the source code and found the configurations for it. but how do I customize them?

**Comment by ErikEJ** [comment]
Handlebars is a seperate repo

**Comment by ErikEJ** [comment]
See the wiki for further advice

**Comment by Qpirate** [comment]
HI ErikEJ,

Thanks Yes that is what i will do
