### ISSUE TITLE
New feature: Option to set a property type to have only get;

### ISSUE THREAD

**Issue by lasbrojen** [ErikEJ/EFCorePowerTools#1278]
I'm a big fan of EF Core Power Tools. I use it exclusively for reverse engineering. It could be cool if there was an option to set a property type to only have a get;.... I already use handlebars to insert interface into entities. But it does not seem that you can use handlebars in this case

![image](https://user-images.githubusercontent.com/5829905/153209615-75a963ea-5593-4a60-a3d5-de8d1df12395.png)

**Comment by ErikEJ** [comment]
Could you explain why you need this?

**Comment by lasbrojen** [comment]
Yeps 😊

That might not be a good idea. And possibly breaks a few patterns if you keep logic both in db and in the code. But I would like to signal to my colleagues who also have to work with this solution that "Created" and "LastModified" are handled in the database.

![image](https://user-images.githubusercontent.com/5829905/153212246-d7f5c956-de8c-4ff8-9d82-a0d9863569a4.png)

**Comment by ErikEJ** [comment]
Or use shadow properties in a partial class? https://docs.microsoft.com/en-us/ef/core/modeling/shadow-properties#configuring-shadow-properties

**Comment by lasbrojen** [comment]
I do not exclude because I still want to show and sort on the values. I will try to look at Shadow and Indexer Properties and if I can make it work with a reverse engineering setup 😊👍
