### ISSUE TITLE
New Feature - Use appsettings.json for Connection String

### ISSUE THREAD

**Issue by jcantrel** [ErikEJ/EFCorePowerTools#1279]
I have started using EF Core Power Tools to reverse engineer our existing applications into our new blazor app. One issue I have run across is that we store our connection string in the appsettings.json file, and use that to connect. With manual scaffolding I can easily do this by just using " Name=ConnectionStrings:NameOfConnection" but with Power Tools I am having to manually add that connection after the scaffolding is complete. 

It would be nice if I could specify this during the reverse engineering process.

**Comment by Qpirate** [comment]
If you are using a database project you should target the dacpac, it ensures that your not getting the customization that developers do on their sql but what is physically checked into your repo.

**Comment by jcantrel** [comment]
There is no database project involved.

**Comment by ErikEJ** [comment]
Do you mean you have to make changes to the generated code? You can just use the constructor that takes a DbContextOptionsBuilder

**Comment by jcantrel** [comment]
Since its best practices to use the appsettings.json file in blazor apps, even just having a field to enter it would be good even if we can't use it for the initial reverse engineering.

At the moment I cannot see a way to achieve this with the Power Tools. Every time I do a rebuild I have to manually change the DbContextOptionsBuilder section.

**Comment by jcantrel** [comment]
I suppose that is a protentional work around, but as I maintain dozens of database connections I was hoping for something that did not require separate code to work.

**Comment by ErikEJ** [comment]
>> but as I maintain dozens of database connections I was hoping for something that did not require separate code to work.

How is that different from having to update generated code??
