### ISSUE TITLE
Please consider nuget publish the components insdie EFCorePowerTools

### ISSUE THREAD

**Issue by timiil** [ErikEJ/EFCorePowerTools#1280]
Very nice and great plugin project :)

We are trying to use the core component inside EFCorePowerTools, but it is not in the VS IDE context.

For example we may need make the procedure 'Database' reverse engine to 'DGML';   so we should need：

DacFxStrongTypedCore
RevEng.Core
RevEng.Core.60
RevEng.Core.Abstractions
RevEng.Shared
ErikEJ.EntityFrameworkCore.6.SqlServer.Dacpac
ErikEJ.EntityFrameworkCore.SqlServer.Dacpac

The above components are NOT publish in nuget, so we may have a little bit hard to use them ,  it is very kind of you if you can consider publish them as the nuget package.   

Thanks :)

**Comment by ErikEJ** [comment]
Actually, ErikEJ.EntityFrameworkCore.6.SqlServer.Dacpac is published to NuGet:
https://www.nuget.org/packages/ErikEJ.EntityFrameworkCore.SqlServer.Dacpac/6.0.1 

But you can call the undocumented command line tool, [see this](https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#requirements).

**Comment by timiil** [comment]
> Actually, ErikEJ.EntityFrameworkCore.6.SqlServer.Dacpac is published to NuGet: https://www.nuget.org/packages/ErikEJ.EntityFrameworkCore.SqlServer.Dacpac/6.0.1
> 
> But you can call the undocumented command line tool, [see this](https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#requirements).

Thanks for you reply sir. i had noticed that one or?two components are published onto nugget. but，seems that it is not all the components those we need to. 

if publish all those components are too complicated to this plugin project, can we just pack all the components into one single nuget reference?

**Comment by ErikEJ** [comment]
No plans to do that.

**Comment by ErikEJ** [comment]
@timiil What exactly is it you want to do - could it be a new feature in the tool itself?

**Comment by timiil** [comment]
> @timiil What exactly is it you want to do - could it be a new feature in the tool itself?

i am trying to generate efcontext and entities assembly on a CLR runtime. using Roslyn and so on to complie.  By reverse engineering from sql server ，mysql，pgsql... so，this task very need your beautiful project but without any IDE

**Comment by ErikEJ** [comment]
There is the command line tool.

**Comment by ErikEJ** [comment]
For anyone watching this issue, this is now planned, and you can find a design proposal [here](https://github.com/ErikEJ/EFCorePowerTools/issues/1751) - looking forward to any comments/suggestions.

**Comment by ErikEJ** [comment]
Preview 1 of the CLI tool is [now available](https://www.nuget.org/packages/ErikEJ.EFCorePowerTools.Cli/7.0.0-preview1#readme-body-tab)

![image](https://user-images.githubusercontent.com/4169187/234258058-2b6def58-f87c-455a-93da-21cd09d9e3f7.png)

**Comment by timiil** [comment]
very nice
