### ISSUE TITLE
Can't Use External Transactions and Retry Strategy with Stored Procedures

### ISSUE THREAD

**Issue by wgm4321** [ErikEJ/EFCorePowerTools#1282]
With the current way store procedures are wrapped, you can't include them in an externally defined and managed unit of work.   Please refer to "[Using Resilient Entity Framework Core Sql Connections and Transactions: Retries with Exponential Backoff](https://devblogs.microsoft.com/cesardelatorre/using-resilient-entity-framework-core-sql-connections-and-transactions-retries-with-exponential-backoff/)".   The article describes how to create an ExecutionStrategy and pass it a delegate as the unit of work to be executed and retries if a transient error occurs.   Within the delegate, the transaction is started and committed.

### Steps to reproduce
Sorry, I don't really have steps to reproduce this because it doesn't seem like it can be done.    The core problem is that you need create the ExecutionStrategy on the dbcontext that will be used for the stored procedure.   However, this is not exposed in the extensions.

You can sort of hack this in by changing the extensions as shown here:
![image](https://user-images.githubusercontent.com/9358312/153723939-e206cf29-fd7d-4761-8671-df1a40df8f99.png)

[DbContextExtensions.txt](https://github.com/ErikEJ/EFCorePowerTools/files/8054280/DbContextExtensions.txt)

Then you can do something like this:
```
        using var databaseContext = new DeadlocktestContext();
        var strategy = databaseContext.Database.CreateExecutionStrategy();
        await strategy.ExecuteAsync(
            async () =>
            {
                using (var transaction = databaseContext.Database.BeginTransaction())
                {
                    await databaseContext.Procedures.Procedure1Async(1);
                    await transaction.CommitAsync();
                }
            }
        );
 ```    

However, it seems like a hack or that there should be a better way.

EF Core version in use: EF Core 6.02
Is Handlebars used: no
EF Core Power Tools version: 2.5.908.0
Database engine: SQL Server
Visual Studio version: Visual Studio 2022

**Comment by ErikEJ** [comment]
Example of new approach:

1: add to partial DbContext (1 line for each result set)

```
        partial void OnModelCreatingPartial(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<TenMostExpensiveProductsResult>().HasNoKey().ToTable(null);
        }

```
2: new call:

    var _ = await _context.Set<TenMostExpensiveProductsResult>().FromSqlRaw<TenMostExpensiveProductsResult>("EXEC @returnValue = [dbo].[Ten Most Expensive Products]", sqlParameters).ToListAsync(cancellationToken);

**Comment by ErikEJ** [comment]
I will look into a refactor of the generated code soon. 

I  the meantime you could maybe make manual changes, and let me know if that solves your issues.

**Comment by ErikEJ** [comment]
I will refactor my code generation  approach to avoid these complexities going forward.

**Comment by ErikEJ** [comment]
Thanks for the heads up. I have not done a lot of testing yet, but will look into it.

**Comment by ErikEJ** [comment]
Hmm.. A bit more complex than anticipated - OnModelCreatingPartial can only be used once, and it should not be in generated code.

**Comment by ErikEJ** [comment]
@wgm4321 This is now in the latest daily, would be very grateful if you could verify

**Comment by wgm4321** [comment]
@ErikEJ 
I tried the latest build and it looks good !    Thanks.
