### ISSUE TITLE
Generate DbContext/Entities based on dgml file

### ISSUE THREAD

**Issue by unruledboy** [ErikEJ/EFCorePowerTools#1283]
Is it possible to generate DbContext/Entities/DDL based on dgml file?

### Steps to reproduce

EFCore Power Tools can reverse-engineer a database and produce DbContext/Entities, that's good for db-first.

We now need to support model first, based on a front-end generated json and will be converted to dgml file. I wonder if the EF Core Power Tools infrastructure can be used for this?

### Further technical details

EF Core version in use: EF Core 6.0.2

Is Handlebars used: no

EF Core Power Tools version: 2.5.908.0

Database engine: SQL Server 2019

Visual Studio version: Visual Studio 2022

**Comment by ErikEJ** [comment]
It cannot, the DGML does not represent the full model, and is read-only. There are some commercial tools that may be able to help you.
