### ISSUE TITLE
Missing schema in dgml

### ISSUE THREAD

**Issue by unruledboy** [ErikEJ/EFCorePowerTools#1284]
There is no schema (like dbo) in the generated dgml file. Can we please include the schema in the generated dgml as Link.Source? Like:

`<Link Source = "dbo.Patient" Target="Patient.Unique" Category="Contains" />`

### Steps to reproduce

1. Obtain an instance of DbContext
2. use ModelExtension.AsDgml to generate a dgml file

### Further technical details

EF Core version in use: EF Core 6.0.2

Is Handlebars used: no

EF Core Power Tools version: 2.5.908.0

Database engine: SQL Server 2019

Visual Studio version: Visual Studio 2022

**Comment by ErikEJ** [comment]
The DGML file does not represent the physical tables in the database, but the logical model. You can use my "SQLite Toolbox" to generate a DGML file from a SQL Server Datbase.
