### ISSUE TITLE
Resolve ambiguous type definitions

### ISSUE THREAD

**Issue by DerMagereStudent** [ErikEJ/EFCorePowerTools#1287]
The problem is that in one of the databases I want to reverse engineer, there is a table called EventHandler. So the created model for the entity is called `EventHandler`, which conflicts with the `System.EventHandler`. I would have to resolve this problem manually every time EF scaffold is executed. For now, this is not a huge problem because I just have to add the line

`using EventHandler = Database.Models.EventHandler;`

But if this would not be the only entity then this could get an annoying problem. So is it possible to automatically specify the whole type name including the namespace to resolve ambiguous type definitions?

### Further technical details

EF Core version in use: EF Core 5

Is Handlebars used: no

EF Core Power Tools version: 2.5.908.0

Database engine: SQL Server

Visual Studio version: VS 2019

**Comment by ErikEJ** [comment]
Can you use the renaming feature?

**Comment by DerMagereStudent** [comment]
It would be great to not rename them since we are currently moving from Linq2Db to EF and a lot of projects depend on these Models. I tried it with Handlebars, like this in the `DbSets.hbs`:

```
{{#each dbsets}}
        public virtual DbSet<{{put-namespace-here}}.{{set-property-type}}> {{set-property-name}} { get; set; }{{#if nullable-reference-types }} = default!;{{/if}}
{{/each}}
```

but unfortunately, neither `model-import` nor `model-namespace` or random tries like `set-property-type-namespace` exists

**Comment by DerMagereStudent** [comment]
It just creates a using statement in all files. I don't know if the priority when it comes to ambiguous type definitions is set to global usings. Regardless, the library uses net5.0 with C#9. Therefore, one has no access to global usings

**Comment by ErikEJ** [comment]
I am using the EF Core code generation, I wonder if this is already a known EF Core issue @roji ?

**Comment by ErikEJ** [comment]
Looks like it may be possible to fix when using EF Core 6 https://github.com/dotnet/EntityFramework.Docs/issues/3390

Why are you using EF Core 5? It is out of support in 3 months.

**Comment by roji** [comment]
We occasionally get this issue in migrations, but I'm not sure I've seen it much for reverse engineering.

I don't know what HandleBars allows, but a `using EventHandler = ...` at the top seems like the ideal solution here (@bricelam is working on built-in templates in EF Core for 7.0, that would allow that as well). I'm not sure global usings can be used for this..

/cc @bricelam @ajcvickers @AndriySvyryd

**Comment by ErikEJ** [comment]
@roji Thanks - I was also unable to find any related issues here or in the EF Core repo.

@DerMagereStudent As you can see, naming your entities like this is an anti-pattern. Does it also not cause issues for consumers of your models?

**Comment by DerMagereStudent** [comment]
@ErikEJ We are using Ef Core 5 (5.0.14) because the next higher version 6.0.0 requires net6.0 and we cannot upgrade everything to net6.0 at the Moment

**Comment by ErikEJ** [comment]
No plans to fix this very local issue and there are multiple manual and automated fixes available.

**Comment by Inplaticular** [comment]
I'm asking for an automated fix which is not the renaming feature. If there is one pls tell me because currently, I have to do it manually. That's what the issue is about

**Comment by ErikEJ** [comment]
Keep in mind that this is free open source software.

If you use Handlebars you can add this to the top of all files, maybe conditionally

      using EventHandler = Database.Models.EventHandler;

**Comment by ErikEJ** [comment]
@DerMagereStudent You can remedy this with the T4 templates in EF Core7
