### ISSUE TITLE
Multiple configurations/multiple entries in efpt.config.json

### ISSUE THREAD

**Issue by DerMagereStudent** [ErikEJ/EFCorePowerTools#1288]
I have to reverse engineer 11 databases. It would be great if the settings would be saved for each database individual so that you don't have to rename the model-/context path, model-/context namespace, context name, ... everytime you want to reverse engineer a given database.

### Further technical details

EF Core version in use: EF Core 5

Is Handlebars used: no

EF Core Power Tools version: 2.5.908.0

Database engine: SQL Server

Visual Studio version: VS 2019

**Comment by ErikEJ** [comment]
You can do that easily, have a look at the wiki
