### ISSUE TITLE
Reverse Engineering bigints

### ISSUE THREAD

**Issue by Andy-Corrigan** [ErikEJ/EFCorePowerTools#1292]
Not sure whether this is an issue or if it's more of a "nice to have" - but when reverse engineering tables that have a bigint column (i.e. an identity column) it automatically maps them to an int; which assumes that the table doesn't need the bigint column. Shouldn't it map bigints to Int64 in C# (or at least have an option to do that)? 

I only noticed that this was the case when tracing an issue with our error logger.

**Comment by Andy-Corrigan** [comment]
The example I'd encountered was this particular table:

CREATE TABLE [logging].[Log] (
    [id]         BIGINT         IDENTITY (1, 1) NOT NULL,
    [severity]   INT            NOT NULL,
    [auditType]  INT            NOT NULL,
    [message]    NVARCHAR (MAX) NOT NULL,
    [source]     NVARCHAR (MAX) NULL,
    [stackTrace] NVARCHAR (MAX) NULL,
    [targetSite] NVARCHAR (500) NULL,
    [timeStamp]  DATETIME       NOT NULL,
    [userID]     INT            NULL,
    CONSTRAINT [PK_Log] PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [FK_Log_ErrorLevels] FOREIGN KEY ([severity]) REFERENCES [logging].[ErrorLevels] ([id]),
    CONSTRAINT [FK_Log_LogMessageTypes] FOREIGN KEY ([auditType]) REFERENCES [logging].[LogMessageTypes] ([id]),
    CONSTRAINT [FK_Log_Person] FOREIGN KEY ([userID]) REFERENCES [people].[Person] ([ID])
);

**Comment by ErikEJ** [comment]
Ping?

**Comment by Andy-Corrigan** [comment]
Sorry, it's the weekend so I'm not currently at work. Off the top of my head it's EF5

**Comment by ErikEJ** [comment]
Any updates, I am unable to repro.

**Comment by Andy-Corrigan** [comment]
[create table statement.txt](https://github.com/ErikEJ/EFCorePowerTools/files/8116240/create.table.statement.txt)
[efptConfig.txt](https://github.com/ErikEJ/EFCorePowerTools/files/8116241/efptConfig.txt)
[faulty bigint to int.txt](https://github.com/ErikEJ/EFCorePowerTools/files/8116242/faulty.bigint.to.int.txt)

These are text files containing the efpt config - the sql table and the C# representation of it (as produced by the reverse engineer tool). 

It turns out that it's EF6, not EF5. If it provides any further context, I'm reverse engineering a database project within the Visual Studio solution (using VS2022) as opposed to a live database.

**Comment by ErikEJ** [comment]
Ah. Maybe you could share the .dacpac then (or a Simplified dacpac for repro) ?

**Comment by Andy-Corrigan** [comment]
[New folder.zip](https://github.com/ErikEJ/EFCorePowerTools/files/8116900/New.folder.zip)

Accidentally double layered the folders, but that's the dacpac

**Comment by ErikEJ** [comment]
I am unable to repro:

        public partial class Log
        {
           public long Id { get; set; }

**Comment by ErikEJ** [comment]
Or with Data Annotations:

    [Table("Log", Schema = "logging")]
    public partial class Log
    {
        [Key]
        [Column("id")]
        public long Id { get; set; }

**Comment by Andy-Corrigan** [comment]
Hmm, how very bizarre

**Comment by ErikEJ** [comment]
Even tried with all your settings from the efpt.config,json file - no dice.

I guess you are using a different table defintion from the one you are sharing.

**Comment by Andy-Corrigan** [comment]
As a test I've just done a reverse engineer myself, seems at some point since I'd last reverse engineered an update has fixed it without my noticing it.
