### ISSUE TITLE
tables with primary key composed of two columns

### ISSUE THREAD

**Issue by dchillman123** [ErikEJ/EFCorePowerTools#1293]
If I choose "EF Core 5" I am able to reverse engineer tables with primary keys composed of two columns.  I select "EF Core 6", the tables with multicolumn primary keys are ignored.
### Steps to reproduce
This table is ignored when using EF Core 6

CREATE TABLE [dbo].[AspNetUserRoles] (
[UserId] nvarchar(128) NOT NULL,
[RoleId] nvarchar(128) NOT NULL,
CONSTRAINT [FK_AspNetUserRoles_AspNetUsers_UserId]
FOREIGN KEY ([UserId])
REFERENCES [dbo].[AspNetUsers] ( [Id] )
ON DELETE CASCADE
,
CONSTRAINT [FK_AspNetUserRoles_AspNetRoles_RoleId]
FOREIGN KEY ([RoleId])
REFERENCES [dbo].[AspNetRoles] ( [Id] )
ON DELETE CASCADE
,
CONSTRAINT [PK__AspNetUserRoles_RoleIdUserId]
PRIMARY KEY CLUSTERED ([UserId] ASC, [RoleId] ASC)
WITH ( PAD_INDEX = OFF,
FILLFACTOR = 100,
IGNORE_DUP_KEY = OFF,
STATISTICS_NORECOMPUTE = OFF,
ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON,
DATA_COMPRESSION = NONE )
 ON [PRIMARY]
)
ON [PRIMARY];

### Further technical details

EF Core version in use: (e.g. EF Core 6)
application EF Core 6
Is Handlebars used: yes/no

EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
 (2.5.908)

Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)
sql server 2016

Visual Studio version: (e.g. Visual Studio 2022)
visual studio 2022

**Comment by ErikEJ** [comment]
They are not ignored, they are not required to be a separate entity.

You can bring back the previous behaviour via the advanced option.

**Comment by dchillman123** [comment]
Thanks – I had not noticed that.



*From:* Erik Ejlskov Jensen ***@***.***>
*Sent:* Saturday, February 19, 2022 10:06 AM
*To:* ErikEJ/EFCorePowerTools ***@***.***>
*Cc:* dchillman123 ***@***.***>; Author <
***@***.***>
*Subject:* Re: [ErikEJ/EFCorePowerTools] tables with primary key composed
of two columns (Issue #1293)



They are not ignored, they are not required to be a separate entity.

You can bring back the previous behaviour via the advanced option.

—
Reply to this email directly, view it on GitHub
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ErikEJ_EFCorePowerTools_issues_1293-23issuecomment-2D1046061712&d=DwMCaQ&c=sdnEM9SRGFuMt5z5w3AhsPNahmNicq64TgF1JwNR0cs&r=EaMiT8Pm9Ou6ZL7-b18rNDVT7IQJCk19B_xDGLFZ54o&m=71lbIPlj2w0k8cIz_B4ORl78vl-0IbpJQwpVKRLInjGoKH1LVrcSio_HlXSFWSdk&s=iWxkSrupUUv-ZSCdx0j3lZhF3u8RIo32Ny0ZY6w2AHM&e=>,
or unsubscribe
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AG6LTJDCQMPH75UCNHW3GSTU37EZDANCNFSM5O2X5Z3A&d=DwMCaQ&c=sdnEM9SRGFuMt5z5w3AhsPNahmNicq64TgF1JwNR0cs&r=EaMiT8Pm9Ou6ZL7-b18rNDVT7IQJCk19B_xDGLFZ54o&m=71lbIPlj2w0k8cIz_B4ORl78vl-0IbpJQwpVKRLInjGoKH1LVrcSio_HlXSFWSdk&s=aoVzVJi3yXSkDbwDOUiJMkqlrYOQ_pu3lofGQuwCSN4&e=>
.
Triage notifications on the go with GitHub Mobile for iOS
<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=sdnEM9SRGFuMt5z5w3AhsPNahmNicq64TgF1JwNR0cs&r=EaMiT8Pm9Ou6ZL7-b18rNDVT7IQJCk19B_xDGLFZ54o&m=71lbIPlj2w0k8cIz_B4ORl78vl-0IbpJQwpVKRLInjGoKH1LVrcSio_HlXSFWSdk&s=dKBh4onNJek6Hsy43zMxKVxb_dmfpLTXWHo7uJ-oSjM&e=>
or Android
<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=sdnEM9SRGFuMt5z5w3AhsPNahmNicq64TgF1JwNR0cs&r=EaMiT8Pm9Ou6ZL7-b18rNDVT7IQJCk19B_xDGLFZ54o&m=71lbIPlj2w0k8cIz_B4ORl78vl-0IbpJQwpVKRLInjGoKH1LVrcSio_HlXSFWSdk&s=v8G6_xgjtp72041rTdrrweHTMX9IwxQdg9MMPjdy2M0&e=>.

You are receiving this because you authored the thread.Message ID: <
***@***.***>

**Comment by ErikEJ** [comment]
I am going to close this, assume case is closed?

**Comment by dchillman123** [comment]
yes



*From:* Erik Ejlskov Jensen ***@***.***>
*Sent:* Sunday, February 20, 2022 7:49 AM
*To:* ErikEJ/EFCorePowerTools ***@***.***>
*Cc:* dchillman123 ***@***.***>; Author <
***@***.***>
*Subject:* Re: [ErikEJ/EFCorePowerTools] tables with primary key composed
of two columns (Issue #1293)



I am going to close this, assume case is closed?

—
Reply to this email directly, view it on GitHub
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ErikEJ_EFCorePowerTools_issues_1293-23issuecomment-2D1046254168&d=DwMCaQ&c=sdnEM9SRGFuMt5z5w3AhsPNahmNicq64TgF1JwNR0cs&r=EaMiT8Pm9Ou6ZL7-b18rNDVT7IQJCk19B_xDGLFZ54o&m=KkEKittbA-l_qjXg3kiv7b8iSItGLfo8dyrwvuKvOferwredubZFRM-uxsvO1mIb&s=uoHBvf0CjLc-3LZi7gA_zuoW7sD6Ewp8ocqVHxOo1WE&e=>,
or unsubscribe
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AG6LTJFX4IPSGDNHO34NWM3U4D5OBANCNFSM5O2X5Z3A&d=DwMCaQ&c=sdnEM9SRGFuMt5z5w3AhsPNahmNicq64TgF1JwNR0cs&r=EaMiT8Pm9Ou6ZL7-b18rNDVT7IQJCk19B_xDGLFZ54o&m=KkEKittbA-l_qjXg3kiv7b8iSItGLfo8dyrwvuKvOferwredubZFRM-uxsvO1mIb&s=zGgO9stn1i5utxXIDLrQ7F7SNhAplPgJjd72B2_-bAg&e=>
.
Triage notifications on the go with GitHub Mobile for iOS
<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=sdnEM9SRGFuMt5z5w3AhsPNahmNicq64TgF1JwNR0cs&r=EaMiT8Pm9Ou6ZL7-b18rNDVT7IQJCk19B_xDGLFZ54o&m=KkEKittbA-l_qjXg3kiv7b8iSItGLfo8dyrwvuKvOferwredubZFRM-uxsvO1mIb&s=GXoRiGWJkwwk7AO3waCFxUb9rbb3B0HFK9c_9rkOgPs&e=>
or Android
<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=sdnEM9SRGFuMt5z5w3AhsPNahmNicq64TgF1JwNR0cs&r=EaMiT8Pm9Ou6ZL7-b18rNDVT7IQJCk19B_xDGLFZ54o&m=KkEKittbA-l_qjXg3kiv7b8iSItGLfo8dyrwvuKvOferwredubZFRM-uxsvO1mIb&s=zMj01v_g9wyNDinSjLHl-xO8odqIamzIkjCPnu5-bcE&e=>.

You are receiving this because you authored the thread.Message ID: <
***@***.***>
