### ISSUE TITLE
Issue calling scalar udf

### ISSUE THREAD

**Issue by rhubarbjustin** [ErikEJ/EFCorePowerTools#1295]
When reverse engineering a scalar user defined function I just get a code stub in the data context:

    __public partial class PMIContext
    {

        [DbFunction("fn_HasRequiredApprovals", "dbo")]
        public static bool? fn_HasRequiredApprovals(Guid? MeasureID)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }__

Should I be able to call a udf from here? Many thanks. Great product!

EF Core version in use: EF Core 5

Is Handlebars used: no

EF Core Power Tools version: 2.5.908.0

Database engine:SQL Server

Visual Studio version: VS 2022

**Comment by rhubarbjustin** [comment]
Many Thanks. I tried that but I get the message "This method can only be called from Entity Framework Core queries"

**Comment by ErikEJ** [comment]
You must share some code to get help.

**Comment by ErikEJ** [comment]
Docs: https://docs.microsoft.com/en-us/ef/core/querying/user-defined-function-mapping

**Comment by ErikEJ** [comment]
Any updates?

**Comment by ErikEJ** [comment]
Closing as no repro provided, feel free to re-open if you can provide repro code.
