### ISSUE TITLE
Generate entities and contexts with 'Internal' access modifier

### ISSUE THREAD

**Issue by wieland91** [ErikEJ/EFCorePowerTools#1297]
When utilizing EFCorePowerTools to reverse engineer a database to generate the foundation of my DAL, it would be great if the contexts and entityModels was not exposed publicly.  

I suggest implementing two selectors; 'access modifier context' and 'access modifier entities' with [Public, Internal]

**Comment by ErikEJ** [comment]
You should be able to do that with the Handlebars templates.

**Comment by wieland91** [comment]
So you can - that's gonna save me time, thanks 👍
