### ISSUE TITLE
Two small glitches in generated code with version 2.5.918

### ISSUE THREAD

**Issue by AFract** [ErikEJ/EFCorePowerTools#1298]
Hello, 
With version 2.5.918 and with the advanced option "use nullable reference types", against .Net 6 / EF 6, I noticed two weirds things :

--- First issue :

1.  I have a table with a column 
`IsEnabled BIT NOT NULL DEFAULT(1)`
It generates the following code :
`public bool? IsEnabled { get; set; }`
Maybe it's intended (to force user to assign manually a value to the field), but I was expecting a non-nullable bool.

--- Second issue :

2. I have two tables as this :
```
CREATE TABLE [ppm].[A]
	(
	Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
           IdB INT NOT NULL,
CONSTRAINT FK_A_B FOREIGN KEY (IdB)
    REFERENCES [ppm].[B](Id))

CREATE TABLE [ppm].[B]
	(
	Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
...);
```

So A points to B.
In "B" generated class, I get this navigation property :
`public virtual A A { get; set; } = null!;`
Where I was expecting
`public virtual A? A { get; set; }`
because there is no guarantee that a A record always exists for a B record (even if the FK is not nullable in A, the A record itself may not exist), so it could perfectly be null.

I have seen the Nullable feature is still experimental, and it does not prevent anything to work, I'm just sharing just in case it could help to improve it further.

Thank you !

**Comment by ErikEJ** [comment]
The first one is by design as you can see from many closed issues in the repo, and not related to nullable reference types.

There is an advanced option to change the behaviour.

The second one may be by design - @roji ?

**Comment by roji** [comment]
> [...] because there is no guarantee that a A record always exists for a B record (even if the FK is not nullable in A, the A record itself may not exist), so it could perfectly be null.

@AFract I'm a bit confused... If the foreign key column (`IdB` above) is non-nullable, that means that there cannot exist a row in A without a corresponding row in B - that's enforced by the foreign key constraint. That is why this gets scaffolded as a non-nullable navigation property. You write that "A record itself may not exist", but in that case no .NET entity instance would be loaded at all, so I'm not sure how that's relevant...

What am I missing?

**Comment by AFract** [comment]
Hello @Roji, 

I'm sorry but you misunderstood (maybe I'm not very clear also).
IdB is not null, but the navigation property I am talking about is the link to A generated in the B class.
B can exist without a A pointing to it, so it should be a nullable.
If forgot to mention that it is a (0, 1) relation instead of a Many one because there is also a constraint 
```
CREATE UNIQUE NONCLUSTERED INDEX [IX_B_A] ON [ppm].[B]
(
	[IdB] ASC
);
```

Here's the complete SQL script : 

```
CREATE TABLE [ppm].[B]
	(
	Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
);

CREATE TABLE [ppm].[A]
	(
	Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    IdB INT NOT NULL,
CONSTRAINT FK_A_B FOREIGN KEY (IdB)
    REFERENCES [ppm].[B](Id))


CREATE UNIQUE NONCLUSTERED INDEX [IX_A_UniqueB] ON [ppm].[A]
(
	[IdB] ASC
);
```

And the generated code :
```

    public partial class A
    {
        public int Id { get; set; }
        public int IdB { get; set; }

        public virtual B IdBNavigation { get; set; } = null!;
    }

	public partial class B
    {
        public int Id { get; set; }

        public virtual A A { get; set; } = null!;
    }
```

I hope it will be clearer with this full example.


@ErikEJ Thank you for your answer; I have just noticed the option "delete default value for booleans" but it is not what I was searching for. To respect default value contrains, it would be meaningful to generate the bool as a non nullable one and assign it a default value in the constructor. But don't worry, it's fine ;)

**Comment by roji** [comment]
@AFract you're right, I did indeed misunderstand - and I think what you're seeing is a bug in EF. I've opened https://github.com/dotnet/efcore/issues/27496 to track it there.
