### ISSUE TITLE
Feature Request: Place sproc Entities in same place as other Entities

### ISSUE THREAD

**Issue by bmainsteleo** [ErikEJ/EFCorePowerTools#1300]
As a feature request, it would be great to be able to support Handlebars as the means to generate the StoredProcedures class that contains all the SP methods, as well as the ability to use Handlebars to customize the entities that are generated.

It would also be helpful if the entities for the SP can go in a different project than the main context too, like you can do for the entities representing the table.

**Comment by bmainsteleo** [comment]
Mostly I would love to have all of the entities together in one place.  Also, if the SP entities could use the same handlebar as the Table-based entities, that would be great.

**Comment by ErikEJ** [comment]
As I and Tony wrote Handlebars is not an option. 

Could we rename this to: Place sproc Entities in same place as other Entities?

**Comment by bmainsteleo** [comment]
Sure, thanks.

**Comment by ErikEJ** [comment]
@bmainsteleo Looks to me like this already works as expected - the Result classes are placed in same folder as all other models, and the ProcedureContext is place with the DbContext.

**Comment by bmainsteleo** [comment]
@ErikEJ The steps we took were:
- Created a project: Demo.Persistence, and reverse engineered with the following settings:
   - Entity Types Sub-namespace: "Entities"
   - What to generate: DbContext Only
   - Naming > Pluralize or singularize.. checked
   - Customize code using Handlebars: C#
   - Advanced > File Layout > Split DbContext into configuration classes
- Created a project: Demo.Persistence.Entities, and reverse engineered with the following settings:
   - EntityTypes path: Entities
   - What to generate: EntityTypes only
   - Naming > Pluralize or singularize.. checked
   - Customize code using Handlebars: C#

To start, we only chose a few tables.  Later on, we eventually added the SP's...  so we didn't just start with every SP in the model.  If you generate SP's after initially creating the model, do you get the same behavior?

For me, generating SPs later yields all of these changes in Demo.persistence:
- DemoContextProcedures.cs
- spGetAllCustomers.cs
- spGetAllOrders.cs

and so on.  Nothing is in Demo.Persistence.Entities.

**Comment by ErikEJ** [comment]
Ah, I tested using project folders not multiple projects.

**Comment by CorsairRO** [comment]
> @bmainsteleo Looks to me like this already works as expected - the Result classes are placed in same folder as all other models, and the ProcedureContext is place with the DbContext.

@ErikEJ : i can confirm that it definitively works fine from this perspective

**Comment by bmainsteleo** [comment]
@CorsairRO what settings are you using because I just tried it, and it is still putting the EF Stored Procedure Result Classes in the Db Context project for me, not the Entity Classes project....  Am I missing a setting somewhere?

cc: @ErikEJ

**Comment by ErikEJ** [comment]
No current plans to support this.
