### ISSUE TITLE
 EFCorePowerTools removes non-autogenerated files

### ISSUE THREAD

**Issue by Bartolomeus-649** [ErikEJ/EFCorePowerTools#1303]
EFCorePowerTools removes files which it neither has created nor marked as auto generated.

A file containing extensions (partial class) to the auto generated classes is deleted when EFCorePowerTools refreshes its files from the  DataBaseProject.

### Steps to reproduce

- Create a file with a partial class to any of the autogenerated classes in the root folder of the DbContext project (MyDbContextProcedures_partial.cs)
- Refresh the DbContext

### Further technical details

EF Core version in use: EF Core 6

Is Handlebars used: no

EF Core Power Tools version: 2.5.918

Database engine: MsSql

Visual Studio version: Visual Studio 2022

**Comment by ErikEJ** [comment]
I think the tool only removes files with the autogenerated header.

You can also disable file removal completely via Tools, Options.

**Comment by Bartolomeus-649** [comment]
if it didn't create the file, then it should not remove it!

**Comment by ErikEJ** [comment]
The tool is not aware of what files it has created other than the autogenerated header. If that is not present the file will not be removed. 

Please share a sample of a removed file.

If you want no files to be removed enable the global option.

**Comment by Bartolomeus-649** [comment]
The file is removed, so rather difficult share it.

**Comment by ErikEJ** [comment]
You do not use source control?

**Comment by Bartolomeus-649** [comment]
source control is only effective after a file has been checked in.
also, the file is completely removed, and didn't end up in the recycle bin

**Comment by ErikEJ** [comment]
I cannot recover your deleted file. 

Should  I switch the default value for the global option?

**Comment by Bartolomeus-649** [comment]
I would add an  option to use the recycle bin when deleting files.
Also I would use an algorithm which restores any file which were deleted and not replaced with a new file with the exact same name.

**Comment by ErikEJ** [comment]
That sounds complex.

I will make file removal opt-in instead of opt-out as it is currently.

**Comment by ErikEJ** [comment]
Moving files to recycle bin has been implemented, thanks for the suggestion
