### ISSUE TITLE
Rev engineering does not take into account multiple columns with same name

### ISSUE THREAD

**Issue by herrbehn** [ErikEJ/EFCorePowerTools#1304]
Describe what is not working as expected.

Having a stored procedure that returns a result set with multiple columns having the same name, makes the generated ...Result class have multiple fields with same name which does not compile. A solution could be to add a number as a postfix of the generated class field columns

### Further technical details

EF Core version in use: EF Core 6

Is Handlebars used: no

EF Core Power Tools version: 2.5.918

Database engine: Azure SQL

Visual Studio version: Visual Studio 2022

**Comment by ErikEJ** [comment]
Yikes.

Could you share a sample?

**Comment by herrbehn** [comment]
Well, apparently I had a stored procedure that returned multiple columns with same name - I think probably the primary and foreign keys in related tables - I have attached a screenshot of the result (including visual studio's red underlining :) )

![image](https://user-images.githubusercontent.com/38879320/157227751-0d5f588d-838a-4625-88bf-81abd91d25c6.png)

**Comment by ErikEJ** [comment]
I will investigate. A proper repro rather than screenshots would be helpful

**Comment by ErikEJ** [comment]
I actually think this will not work. You will have to fix your stored procedure.

**Comment by herrbehn** [comment]
Ok, if you code generator is depending on the names of the columns, you are probably right. 10 years ago, I wrote a reverse engineering piece which was only depending on the position of fields, here is an excerpt

`
         public spGetDefaultUserOrderDataRow Current { get { if (reader != null && !reader.IsClosed) {spGetDefaultUserOrderDataRow r = new spGetDefaultUserOrderDataRow(); r.met_user_id = reader.IsDBNull(0) ? null : (int?) reader.GetInt32(0); 
  r.met_name = reader.IsDBNull(1) ? null :  reader.GetString(1); 
  r.roll_enabled = reader.IsDBNull(2) ? null : (bool?) reader.GetBoolean(2); 
  r.skill_id = reader.IsDBNull(3) ? null : (int?) reader.GetInt32(3); 
  r.met_username = reader.IsDBNull(4) ? null :  reader.GetString(4); 
  r.met_user_id1 = reader.IsDBNull(5) ? null : (int?) reader.GetInt32(5); `

**Comment by ErikEJ** [comment]
The API used to map the results to classes depends on the names of columns.
