### ISSUE TITLE
Feature request: Create multiple dbcontext based on schema

### ISSUE THREAD

**Issue by andreamorello93** [ErikEJ/EFCorePowerTools#1306]
Hi! 

It would be possible to add an option for generating multiple db context based on db schema?

**Comment by ErikEJ** [comment]
Is this not already possible via table selection and multiple efpt.config.json files?

**Comment by andreamorello93** [comment]
thank you for your answer Erik,

yes it's possible but i've to repeat the reverse engineering operation for every single schema (eftp.config.json). 

Is it possible to do that in a one time operation? or maybe there's something i'm missing.

**Comment by ErikEJ** [comment]
Move/rename the efpt.config.json file after each schema, and you only have to do it once per schema:
https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#using-multiple-dbcontexts-in-the-same-project

**Comment by andreamorello93** [comment]
thahk you erik, one more question. with this solution is it possible to run all the efpt.configs renamed trough .net cli starting from dacpac?

**Comment by andreamorello93** [comment]
I think that this doesn't solve my problem.

For example: 

The Db has multiple schemas and i generate multiple db context with scaffolding and renaming configs process as you advised.
next day DBA moves table from a schema to another. Do i need to reverse engineering all configs everytime? if yes is it possible to do in .net cli?

**Comment by ErikEJ** [comment]
Maybe you should [read through the docs?](https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering) :smile:

There is an global option to always include all files. (May include too much?)

There is also schema filtering - but not sure if it is persisted?

And yes, CLI is possible, but "undocumented"

**Comment by andreamorello93** [comment]
Thank you erik,

i was wondering if it could be possible during the wizard instead of this procedure but nevermind. 

About the CLI i can't find anything about

**Comment by ErikEJ** [comment]
Mentioned here: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#requirements !

**Comment by andreamorello93** [comment]
Yes but this is EF core standard scaffolding that does not have dacpac scaffolding which you developed! I was asking if it could be possible scaffolding dacpacs with your extension using CLI

**Comment by ErikEJ** [comment]
No, it is using my tooling and options  with dacpac support.

**Comment by ErikEJ** [comment]
https://github.com/ErikEJ/EFCorePowerTools/issues/340#issuecomment-670929754 !

**Comment by andreamorello93** [comment]
Ok, sorry but trough the documentation it wasn't clear
