### ISSUE TITLE
Correct naming of navigation properties if FK has Id prefix instead suffix

### ISSUE THREAD

**Issue by SandroRiz** [ErikEJ/EFCorePowerTools#1307]
We know that if you have named the FK with the suffix "Id" (eg. CategoryId in a Products table) the corresponding navigation property is created with "correct" name (Category and the ICollection<> Products).

Unfortunately we have a huge existing database where all the FK are written in the form "idEntity",  so NP are created with that Id prefix in front and the ICollection with the "Navigation" word at the end.

Is it something that we could do? 
It would be nice to have an advanced option to decide what is the consistent pattern of the all the FK (prefix or suffix) and then do the renaming according to that

Thanks

**Comment by ErikEJ** [comment]
I have tried and failed, see #211

**Comment by ErikEJ** [comment]
Maybe you can use the regex based column renaming feature?

**Comment by SandroRiz** [comment]
Is it something in the source code, or an external feature (like the handlebar template or the renaming.json) ?

**Comment by ErikEJ** [comment]
Last paragraph here: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#custom-renaming-with-efptrenamingjson

**Comment by SandroRiz** [comment]
Thank you Erik, I will try...
even if one of my favorite quote is "if you have a problem try with regex...then you'll have two problems" :-)

**Comment by ErikEJ** [comment]
I know, but for this case it kind of is useful.
