### ISSUE TITLE
Bit field set as nullable

### ISSUE THREAD

**Issue by dchillman123** [ErikEJ/EFCorePowerTools#1308]
I changed a bit field in a data base table to non-null.  After reverse-engineering, the field in the associated context model remains nullable.  If I manually change it to not nullable and reverse engineer again, it is changed back to nullable.

### Steps to reproduce

Please include a **complete** description or project that I can redo/run to reproduce the issue.

### Further technical details

EF Core version in use: (e.g. EF Core 6)
EF Core 6.0.2

Is Handlebars used: yes/no

EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
2.5.918.0

Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)
sql server 2016
Visual Studio version: (e.g. Visual Studio 2022)
visual studio 2022

**Comment by ErikEJ** [comment]
Have you checked existing issues?

Does it have a default value?

**Comment by dchillman123** [comment]
If existing issues refers to the open issues, I did look at those but
didn’t see anything related to bit fields, but maybe I am searching
incorrectly.



The bit field does have a default value.



*From:* Erik Ejlskov Jensen ***@***.***>
*Sent:* Monday, March 14, 2022 9:47 AM
*To:* ErikEJ/EFCorePowerTools ***@***.***>
*Cc:* dchillman123 ***@***.***>; Author <
***@***.***>
*Subject:* Re: [ErikEJ/EFCorePowerTools] Bit field set as nullable (Issue
#1308)



Have you checked existing issues?

Does it have a default value?

—
Reply to this email directly, view it on GitHub
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ErikEJ_EFCorePowerTools_issues_1308-23issuecomment-2D1066976349&d=DwMCaQ&c=sdnEM9SRGFuMt5z5w3AhsPNahmNicq64TgF1JwNR0cs&r=EaMiT8Pm9Ou6ZL7-b18rNDVT7IQJCk19B_xDGLFZ54o&m=jL4AiGqBldXGiO2OEqKFHXqcJL310D4lzWWBtHkN_njsgzynADF9v1D4au4G-EyY&s=vtkHnO_lCey2xzzz7VlsZQnrQo10S-y2fATZUnLBCAA&e=>,
or unsubscribe
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AG6LTJBG53PWNT7M3SAJTSLU75NOBANCNFSM5QV5PF3A&d=DwMCaQ&c=sdnEM9SRGFuMt5z5w3AhsPNahmNicq64TgF1JwNR0cs&r=EaMiT8Pm9Ou6ZL7-b18rNDVT7IQJCk19B_xDGLFZ54o&m=jL4AiGqBldXGiO2OEqKFHXqcJL310D4lzWWBtHkN_njsgzynADF9v1D4au4G-EyY&s=d6PT3DqXNc8mv1LZeauquuCGkfEfw-G9NXFGHJ7fq0E&e=>
.
Triage notifications on the go with GitHub Mobile for iOS
<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=sdnEM9SRGFuMt5z5w3AhsPNahmNicq64TgF1JwNR0cs&r=EaMiT8Pm9Ou6ZL7-b18rNDVT7IQJCk19B_xDGLFZ54o&m=jL4AiGqBldXGiO2OEqKFHXqcJL310D4lzWWBtHkN_njsgzynADF9v1D4au4G-EyY&s=ea1_zjHyVGSUtYtUdQ5Jv6QlmMBbukbhr_G8tnfN7wE&e=>
or Android
<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=sdnEM9SRGFuMt5z5w3AhsPNahmNicq64TgF1JwNR0cs&r=EaMiT8Pm9Ou6ZL7-b18rNDVT7IQJCk19B_xDGLFZ54o&m=jL4AiGqBldXGiO2OEqKFHXqcJL310D4lzWWBtHkN_njsgzynADF9v1D4au4G-EyY&s=2-4zI2OCvv-c1yVAUF_549ULV-Hmnq_wrsLjZ6WFz0c&e=>.

You are receiving this because you authored the thread.Message ID: <
***@***.***>

**Comment by ErikEJ** [comment]
I meant closed issues...

**Comment by dchillman123** [comment]
Ahh, ok.  I will remember that in the future.  The listed work-around fixes
the issue.  Thanks.







*From:* Erik Ejlskov Jensen ***@***.***>
*Sent:* Monday, March 14, 2022 9:53 AM
*To:* ErikEJ/EFCorePowerTools ***@***.***>
*Cc:* dchillman123 ***@***.***>; Author <
***@***.***>
*Subject:* Re: [ErikEJ/EFCorePowerTools] Bit field set as nullable (Issue
#1308)



I meant closed issues...

—
Reply to this email directly, view it on GitHub
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ErikEJ_EFCorePowerTools_issues_1308-23issuecomment-2D1066983642&d=DwMCaQ&c=sdnEM9SRGFuMt5z5w3AhsPNahmNicq64TgF1JwNR0cs&r=EaMiT8Pm9Ou6ZL7-b18rNDVT7IQJCk19B_xDGLFZ54o&m=awjuRbKSsMBWvOHYiJaYAP4iXKxJxpjIT1jbl099EoaEDh2xdfzFzpcl5MxysiM_&s=wca66tEn9jujlqBqQPVK7g-h0lp5ouiQ3Q6LrRiVLSs&e=>,
or unsubscribe
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AG6LTJB2GW4BNYCD6AWOMZDU75OHNANCNFSM5QV5PF3A&d=DwMCaQ&c=sdnEM9SRGFuMt5z5w3AhsPNahmNicq64TgF1JwNR0cs&r=EaMiT8Pm9Ou6ZL7-b18rNDVT7IQJCk19B_xDGLFZ54o&m=awjuRbKSsMBWvOHYiJaYAP4iXKxJxpjIT1jbl099EoaEDh2xdfzFzpcl5MxysiM_&s=cmFgHYeYQknBST6OLgrJU0oSpjFSiOdqSsGqVsSc9lE&e=>
.
Triage notifications on the go with GitHub Mobile for iOS
<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=sdnEM9SRGFuMt5z5w3AhsPNahmNicq64TgF1JwNR0cs&r=EaMiT8Pm9Ou6ZL7-b18rNDVT7IQJCk19B_xDGLFZ54o&m=awjuRbKSsMBWvOHYiJaYAP4iXKxJxpjIT1jbl099EoaEDh2xdfzFzpcl5MxysiM_&s=Jn22F39XyCsM06arSvP7E4vYVjgGP576pDygNfMyxh0&e=>
or Android
<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=sdnEM9SRGFuMt5z5w3AhsPNahmNicq64TgF1JwNR0cs&r=EaMiT8Pm9Ou6ZL7-b18rNDVT7IQJCk19B_xDGLFZ54o&m=awjuRbKSsMBWvOHYiJaYAP4iXKxJxpjIT1jbl099EoaEDh2xdfzFzpcl5MxysiM_&s=Ud7xLMqGyNWiG9KLpakHqwxqAtljdskodY0FD8FeH3g&e=>.

You are receiving this because you authored the thread.Message ID: <
***@***.***>
