### ISSUE TITLE
General Option "open generated DbContext" not working when set to false

### ISSUE THREAD

**Issue by SandroRiz** [ErikEJ/EFCorePowerTools#1309]
Describe what is not working as expected.

Set to FALSE the option  open generated DbContext
Run a Reverse Engineer (thru panel or thru Refresh)
The DbContext is still opened

### Further technical details

EF Core version in use:  EF Core 6

Is Handlebars used: no

EF Core Power Tools version: (2.5.918.0)

Database engine: (SQL Server)

Visual Studio version: (Visual Studio 2022 - 17.1.1)

**Comment by ErikEJ** [comment]
Thanks for reporting this!

**Comment by GearTheWorld** [comment]
I confirm.
