### ISSUE TITLE
OnModelCreatingGeneratedProcedures not accounting for Multiple Result Sets

### ISSUE THREAD

**Issue by reffu42** [ErikEJ/EFCorePowerTools#1310]
The modelBuilder lines for Stored Procedures with multiple result sets are currently broken. Lines for regular stored procedures generate fine, but lines for procedures with multiple result sets (and model files) are only generating a single line pointing to a non-existent class.

**Example:**
Sproc Name: StoTestSproc
Generated Models: StoTestSprocResult1, StoTestSprocResult2
Generated modelBuilderLine: `modelBuilder.Entity<StoTestSprocResult>().HasNoKey().ToView(null);`

which fails because there is no class StoTestSprocResult.

I realize that the issue is about a preview feature in an experimental daily build, so if this is either already known or not something expected in a stable build, feel free to close.

### Steps to reproduce
1. Create a Database containing at least one stored procedure that returns multiple results.
2. Enable the advanced/preview option "Discover multiple result sets from SQL Stored Procedures"
3. Run EF Core Power tools Reverse Engineer for the given database (should be able to leave most options on default setting)
4. Wait for Reverse Engineer to finish
5. Confirm that multiple Results models are generated for the stored procedures (e.g. ProcedureNameResult1, ProcedureNameResult2, etc...)
6. Open XxxContextProcedures.cs
7. BUG:  Only one line is generated for the stored procedure in OnModelCreatingGeneratedProcedures, and it points to ProcedureNameResult without a suffix, which does not exist

### Further technical details

EF Core version in use:  EF Core 6

Is Handlebars used: no

EF Core Power Tools version: 2.5.935.0 (latest Daily build as of issue creation)

Database engine: SQL Server

Visual Studio version: Visual Studio 2022

**Comment by ErikEJ** [comment]
It is a Bug and I will get it fixed

**Comment by ErikEJ** [comment]
Thanks for  reporting, fixed in latest daily
