### ISSUE TITLE
Feature Request - Option to embed annotation attributes in a single attribute line syntax

### ISSUE THREAD

**Issue by develorem** [ErikEJ/EFCorePowerTools#1311]
Currently the 'reverse engineer' code generates property annotations (attributes) with one set of square brackets around each, eg:
[Required]
[Column("name")]
[StringLength(150)]

However our code standard is to have this:   
[Required, Column("name"), StringLength(150)]

In the handlebars C# template for properties, I can only get the whole annotation as an individual item.
It would be good if I could create a handlebars template for the annotations. Then I could simply change this myself.
Or, make it a flag in the UI given an annotation is quite a small component.

### Steps to reproduce

'Reverse Engineer' any database table, and make sure to check the option:
"Customize code using Handlebars Templates: C#"

### Further technical details

EF Core version in use: EF Core 6
Is Handlebars used: yes
EF Core Power Tools version: 2.5.918
Database engine: SQL Server
Visual Studio version: Visual Studio 2022

**Comment by ErikEJ** [comment]
I get the style from EF Core. You should exclude generated code from your code style analysis.
