### ISSUE TITLE
Bug - InverseProperty sometimes uses string instead of nameof

### ISSUE THREAD

**Issue by develorem** [ErikEJ/EFCorePowerTools#1313]
When generating two entities with a relationship, the system is pretty good at using "nameof(Property)" to specify the InverseProperty. However sometimes it fails and puts the string instead. I believe this happens when there is a namespace clash.

A better solution is to partially, or fully, qualify the namespace.

The reason for this is that our database names are horrible, so we will refactor the property names to something more meaningful after generation. However those refactorings won't apply when strings are hardcoded for the [InverseProperty()] attribute.

### Steps to reproduce

Create two tables in the database where the FK property of one is the name of the actual second table.
Eg. 
TableA
  Id
  Name
TableB
  Id
  TableA   (this is the FK to tableA)
  
Using the above structure, reverse engineer the database tables.
The relationships will be defined with nameof in one direction, but not in the other.

### Further technical details

EF Core version in use: EF Core 6
Is Handlebars used: yes
EF Core Power Tools version: 2.5.918
Database engine: SQL Server
Visual Studio version: Visual Studio 2022

**Comment by ErikEJ** [comment]
It is a known EF Core issue, fixed in 7.0, hoping for a fix for 6.o as well
