### ISSUE TITLE
Support for EF Core 6 when comparing Context to db

### ISSUE THREAD

**Issue by urielzen** [ErikEJ/EFCorePowerTools#1315]
Hi, Thank you so much for this wonderful tool.
I was wondering since EF Core 6 has been out for a while, if there is already a timeline for PowerTools to support it?

Currently I am getting the following error when trying to use `Compare DbContext to database`:

```
Only EF Core 5 is supported.
```

**Comment by ErikEJ** [comment]
You are the first person asking for it! 😄  - I will try to add it.

**Comment by ErikEJ** [comment]
Fixed in latest daily

**Comment by foequeue** [comment]
Thank you - I came looking for this one - got the error and noticed you had fixed it in the daily.  Appreciate it.

**Comment by ErikEJ** [comment]
@foequeue you are welcome. A rating or review is always appreciated.
