### ISSUE TITLE
DbContextExtensions SqlQueryAsync non-entity types

### ISSUE THREAD

**Issue by atlasQED** [ErikEJ/EFCorePowerTools#1317]
Hi @ErikEJ,

DbContextExtensions SqlQueryAsync\<T\> no longer works for arbitrary types (i.e. non-entity POCOs that match the result set columns)

In #1286 the secondary context was removed along with it's model builder call to .Entity\<T\>(), so now only entities that exist on the context may be used:
"System.InvalidOperationException: Cannot create a DbSet for '...' because this type is not included in the model for the context."

EF Core version: EF Core 5
Is Handlebars used: no
EF Core Power Tools version: v2.5.918.0
Database engine: Azure SQL
Visual Studio version: Visual Studio 2022

**Comment by atlasQED** [comment]
Nope. I will give that a try.

**Comment by atlasQED** [comment]
Now I'm a bit confused. Which NuGet package are you referring to?
I can't find a NuGet package associated to EFCorePowerTools - it looks like it's exclusively a VS extension. I couldn't find anything that seems applicable under ErikEJ.*.

To follow up, how would it overcome db.Set\<T\> only working for types found in the DbContext?
Before the change to support stored procedures was made, the extension method did work for arbitrary types that weren't on the context, because the type was added to the secondary context it created, and then used from there.

**Comment by ErikEJ** [comment]
Sorry, not sure why you could not find this: https://www.nuget.org/packages/ErikEJ.EntityFrameworkCore.SqlServer.SqlQuery/6.0.0-preview1

**Comment by atlasQED** [comment]
It's a prerelease that requires net6.0. Updating from ef core 5 to ef core 6 isn't an options for me.

I realize that this is all about a small extension method, and not some kind of bug with the tooling. I just wanted to call attention to the loss of functionality. Thank you!

**Comment by ErikEJ** [comment]
Come on  - there is also an EF Core 5 version: https://www.nuget.org/packages/ErikEJ.EntityFrameworkCore.SqlServer.SqlQuery/5.0.0-preview1
