### ISSUE TITLE
one step create

### ISSUE THREAD

**Issue by yangtutu** [ErikEJ/EFCorePowerTools#1319]
now create db .cs file  need minimum 4 step click everytime,    it's too much trouble,    can i one click create .cs file?
or have cmdline implementation it.

**Comment by ErikEJ** [comment]
Once the efpt.config.sjon config file is there, you can right click it and run the tool, and if you use the general option to always include all objects, you just need 1 click

**Comment by ErikEJ** [comment]
have a look at the wiki!

**Comment by ErikEJ** [comment]
Ping?

**Comment by ErikEJ** [comment]
Closing as I assume this is explained in the docs.

**Comment by yangtutu** [comment]
i get it   ,thank you   !!!
