### ISSUE TITLE
unable to add a DbContext model diagram

### ISSUE THREAD

**Issue by KasperHL** [ErikEJ/EFCorePowerTools#132]
I'm unable to add a DbContext model diagram. Not sure why that is so maybe someone can point me to a solution. Here are a few details:

### Steps to reproduce
1. start a new ASP.NET Core Web Application (ASP.NET Core 2.1 - SDK 2.1.500)
2. install EF Core Power Tools
3. Use EF Core Power Tools to reverse engineer a simple DB (works perfect)
4. Scaffold the model
5. Add AsDgml() extension method using the tool
5. Use EF Core Power Tools to generate a DbContext diagram - fails.

or 

1. Unzip the attached simple project: [EFpowerTest.zip](https://github.com/ErikEJ/EFCorePowerTools/files/2616030/EFpowerTest.zip)
2. scaffold Students
3. PM add-migration initialDB
4. PM update-database
5. Use EF Core Power Tools to generate a DbContext diagram - fails.

### Further technical details
EF Core Power Tools version: 10.664 and 10.669
Database engine: (SQL Server Express)
Visual Studio version: (Visual Studio 2017 15.9.2)

System.ArgumentException: Error:
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.Hosting.Abstractions, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Den angivne fil blev ikke fundet.
File name: 'Microsoft.AspNetCore.Hosting.Abstractions, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' ---> System.IO.FileNotFoundException: Could not load the specified file.

**Comment by ErikEJ** [comment]
Are you able to use the AsDgml method? https://github.com/ErikEJ/EFCorePowerTools/wiki/Inspect-your-DbContext-model#add-asdgml-extension-method

**Comment by KasperHL** [comment]
Looks like I was in fact able to use the AsDgml method! :)

The original bug is still present in my demo project. I've simplified the solution so now you can just download the files and see the bug. The files also contains the working AsDgml method implementation.

Demo project: 
[EFpowerTest_v2.zip](https://github.com/ErikEJ/EFCorePowerTools/files/2619008/EFpowerTest_v2.zip)

Note: 
VS2017 doesn't support DGML files by default so in order to view the generated file you have to run the VS2017 installer and select the DGML editor.

**Comment by ErikEJ** [comment]
this is related to: #50 

I fixed it by updating AspNet.Core app to version 2.1.6, and moving the EF Code to a seperate class libray, and added this:

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("data source=dummy");
        }
        public EFpowerTestContext()
        {
        }
