### ISSUE TITLE
1591 (Missing XML comment) warnings in auto-generated files

### ISSUE THREAD

**Issue by feldmanjared** [ErikEJ/EFCorePowerTools#1320]
C# auto-generated files have 1591 warnings for "Missing XML comment for publicly visible  type or member..."

I was able to remove these warnings for DbContext and EntityType classes by modifying the **DbContext.hbs** / **Class.hbs** Handlebars files and adding the following suppress lines to the beginning and end.

```
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."

...

#pragma warning restore 1591
```

However, the **DbContextExtensions.cs**, **NorthwindContextProcedures.cs**, and individual stored procedure result classes still have these warnings. As far as I can tell there are no Handlebars files to modify these templates.

Ideally, I could reverse engineer and have 0 warnings from all auto-generated files.

### Further technical details

EF Core version in use: EF Core 6

Is Handlebars used: Yes

EF Core Power Tools version: 2.5.918

Database engine: SQL Server

Visual Studio version: Visual Studio 2022

**Comment by ErikEJ** [comment]
Please share your csproj file.

**Comment by ErikEJ** [comment]
What analysers do you have enabled?

**Comment by feldmanjared** [comment]
**.csproj file**:
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	<GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>1701;1702</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="NSwagStudio\xxx.nswag" />
  </ItemGroup>

  <ItemGroup>
    <_WebToolingArtifacts Remove="Properties\PublishProfiles\xxx.pubxml" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="NSwagStudio\xxx.nswag" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="11.0.1" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="11.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="6.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="6.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="NLog" Version="4.7.14" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="4.14.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.2.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="6.3.0" />
    <PackageReference Include="System.IO.Abstractions" Version="16.1.23" />
  </ItemGroup>

</Project>
```

**Analyzers**:
![image](https://user-images.githubusercontent.com/6248671/160880457-5daf75b1-e702-4cc9-a106-a6706f8dea97.png)

**Comment by ErikEJ** [comment]
Move the generated files to a separate project?

**Comment by feldmanjared** [comment]
I could do that and suppress the warnings project-wide but I'd prefer to keep them where they are.

A better solution may be to:

- Add a setting to add the **warning disable** commands to every generated file.
- Add more Handlebars templates so it's possible to add **warning disable** commands to every generated file by the user.

Tools like NSwagStudio add the following to the top of the generated API client:
```
#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
#pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"
#pragma warning disable 8603 // Disable "CS8603 Possible null reference return"
```

Thanks for the tool and getting back to me so promptly.

**Comment by ErikEJ** [comment]
Mixing Handlebars and stored procedures is not possible.

Do you really add XML comments to all your public APIs?

You could add `<NoWarn>1591</NoWarn>`

Adding a multitude of pragmas to each file is not a path I want to take

**Comment by feldmanjared** [comment]
I am trying to eliminate all warnings in the proper way (without project-wide suppression). If I come across something that obviously doesn't need XML comments then I add warning-suppression in that file.

Thanks again or the tooling, I will figure out a solution.
