### ISSUE TITLE
ef core 3 reverse engineer not returning multiple result sets from sprocs when option turned on

### ISSUE THREAD

**Issue by DavidCAllenMI** [ErikEJ/EFCorePowerTools#1322]
We are using ef core 3 and turning on the option to capture multiple resultsets from store procedures for SQL Server is not working. I only get back one resultset.

reverse engineer a multi-resultset sproc from SQL server using EF Core 3

Is Handlebars used: no

EF Core Power Tools version: 2.5.918

Database engine: SQL Server

Visual Studio version:  Visual Studio 2022

**Comment by ErikEJ** [comment]
This is a bug in the latest release version, see #1309 - fixed in latest daily. 

Try that out and let me know - if it works I will updated the official relase.

**Comment by DavidCAllenMI** [comment]
ok it gave me classes for all 3 result sets, but now I got an error in the output window:
Unable to get result set shape for PROCEDURE 'dbo.XREF_LOA_WEAPONS_UPDATE'
Object reference not set to an instance of an object.

This is a stored proc that does not return any result set so the results class that is normally generated has no property fields. It seemed to generate the same class for results as the previous versions:

    public partial class XREF_LOA_WEAPONS_UPDATEResult
    {

Also I have build errors now: There us a using Dapper; in the ContextProcedure.cs generated class that doesn't resolve. What is Dapper? Also I have errors on a DynamicParameters, SqlMapper types.
    }

**Comment by DavidCAllenMI** [comment]
I right-clicked on the DynamicParameters error and it offered to install Dapper which fixed my references. But now it is creating multiple result classes for a bunch of my stored procs which is not correct as it seems to be ignoring the begin/end blocks in the sproc coded so where there are three blocks that execute depending on the input parms and each block ends with the a select statement I get twogenerated results classes. It should be one since each select returns the same result set. I will send you a sample of the sproc code below:

CREATE PROCEDURE [dbo].[PERSON_CHECK_EXISTS_FIN_EF]
	@p_fin VARCHAR(20),
	@p_session_id  UNIQUEIDENTIFIER
--WITH ENCRYPTION  /*Decrypt by AzSQL Decryptor, 2010-04-28 19:08:39*/
AS
BEGIN
	-- Test the session token to validate that the user is a valid user
	EXECUTE SESSION_VERIFY @p_session_id
	IF @@ERROR = 0
	BEGIN
			-- Declare local variable
			DECLARE @v_person_id UNIQUEIDENTIFIER

			-- Find a person based on the parameters supplied (must be a US Citizen)
			SELECT	@v_person_id = p.person_id
			FROM	dbo.TBL_PERSON p
			WHERE	(p.fin = @p_fin)
					AND (p.is_foreign_national = 1)
		
			-- Return the person ID, if found
			IF @v_person_id IS NOT NULL
			BEGIN
				SELECT @v_person_id AS PERSON_ID
			END
			-- Otherwise, return NULL as PERSON_ID
			ELSE
			BEGIN
				SELECT @v_person_id AS PERSON_ID
			END
	END
END
GO

This is generation two result set classes:
    public partial class PERSON_CHECK_EXISTS_FIN_EFResult1
    {
        public Guid? PERSON_ID { get; set; }
    }

and

    public partial class PERSON_CHECK_EXISTS_FIN_EFResult2
    {
        public Guid? PERSON_ID { get; set; }
    }

**Comment by ErikEJ** [comment]
You are writing a lot. 
I assume it is a bug in this experimental feature (not handling procedures without result set)

Can you share a simple sample?

**Comment by DavidCAllenMI** [comment]
Sorry was trying to give you a lot of data to figure it out. This is a simple example: It has two selects at the end but only one executes as they are within an IF and Begin/End blocks. It should give one result set. But it generate two. One for each Begin/End block select.

CREATE PROCEDURE [dbo].[PERSON_CHECK_EXISTS_FIN_EF]
	@p_fin VARCHAR(20),
	@p_session_id  UNIQUEIDENTIFIER
--WITH ENCRYPTION  /*Decrypt by AzSQL Decryptor, 2010-04-28 19:08:39*/
AS
BEGIN
	-- Test the session token to validate that the user is a valid user
	EXECUTE SESSION_VERIFY @p_session_id
	IF @@ERROR = 0
	BEGIN
			-- Declare local variable
			DECLARE @v_person_id UNIQUEIDENTIFIER

			-- Find a person based on the parameters supplied (must be a US Citizen)
			SELECT	@v_person_id = p.person_id
			FROM	dbo.TBL_PERSON p
			WHERE	(p.fin = @p_fin)
					AND (p.is_foreign_national = 1)
		
			-- Return the person ID, if found
			IF @v_person_id IS NOT NULL
			BEGIN
				SELECT @v_person_id AS PERSON_ID
			END
			-- Otherwise, return NULL as PERSON_ID
			ELSE
			BEGIN
				SELECT @v_person_id AS PERSON_ID
			END
	END
END
GO

**Comment by ErikEJ** [comment]
And the ones causing null reference  error?

**Comment by DavidCAllenMI** [comment]
CREATE PROCEDURE [dbo].[ADDRESS_DELETE]
	@p_person_id UNIQUEIDENTIFIER,
	@p_address_id UNIQUEIDENTIFIER,
	@p_session_id  UNIQUEIDENTIFIER
--WITH ENCRYPTION  /*Decrypt by AzSQL Decryptor, 2010-04-28 19:07:32*/
AS
	-- Test the session token to validate that the user is a valid user
	EXECUTE SESSION_VERIFY @p_session_id
	IF @@ERROR = 0
	BEGIN
		DECLARE @v_address_id  UNIQUEIDENTIFIER
		SET @v_address_id = NULL

		UPDATE	dbo.TBL_PERSON
		SET		address_id = @v_address_id
		WHERE   person_id = @p_person_id

		-- Delete the data from the TBL_ADDRESS table
		DELETE
		FROM	dbo.TBL_ADDRESS
		WHERE	address_id = @p_address_id
	END
GO

**Comment by ErikEJ** [comment]
>> As you can see each begin/end block that has a select it treat as a seperate result set.

That is what I get back from the metadata discovery mechanism I use for multiple result sets. You can just use the first result set always based on you knowledge of the behaviour.

**Comment by ErikEJ** [comment]
>> Unable to get result set shape for PROCEDURE 'dbo.SESSION_DELETE_ANONYMOUS'
>> Object reference not set to an instance of an object.

Thanks for trying this experimental feature and reporting this. This is fixed in the latest daily, please try it out and let me know if that solves your issue.

**Comment by DavidCAllenMI** [comment]
So ru saying that when you have multiple begin/end blocks in the sproc with selects, that if they are all the same format that the results will always be returned in the first resultset?

**Comment by ErikEJ** [comment]
If the stored procedure only return a single result set a runtime  yes. What have you tried?

**Comment by DavidCAllenMI** [comment]
When I try to call a procedure with where the tool has generated mutiple result sets I get this error:

The reader has been disposed; this can happen after all data has been consumed
Object name: 'Dapper.SqlMapper+GridReader'.

Here is sample code that I normally use to call sprocs but modified to use result set 1. I am thinking that there must be a different way I have to use but see not doco on that.

                // Create the ResponseVO
                responseVO = new UserCheckExistsPersonRespVO();

                // Execute query
                var result = await _context.Procedures.USER_CHECK_EXISTS_PERSON_EFAsync(
                    p_user_id: requestVO.EntityIdentifier,
                    p_session_id: SessionId);

                if (result.Result1 != null)
                {
                    var foundPerson = result.Result1;
                    responseVO.PersonID = foundPerson[0].PERSON_ID ?? Guid.Empty;
                }

**Comment by DavidCAllenMI** [comment]
also the daily build did not update from the version I had last week.
