### ISSUE TITLE
Possible to compare a given database with current model

### ISSUE THREAD

**Issue by herrbehn** [ErikEJ/EFCorePowerTools#1323]
Describe what is not working as expected.
I’m not sure if this already is possible, but I would like a way of checking if the models really reflect what is in the database. Does power tools support that somehow? And if not, then I have a feature request :)
### Steps to reproduce

Please include a **complete** description or project that I can redo/run to reproduce the issue.

### Further technical details

EF Core version in use: (e.g. EF Core 6)

Is Handlebars used: yes/no

EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)

Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)

Visual Studio version: (e.g. Visual Studio 2022)

**Comment by ErikEJ** [comment]
There is the "Compare DbContext to Database" feature - and also you can script the DbContext as a SQL script, and then use a database schema compare tool

**Comment by herrbehn** [comment]
Perfect! Thanks

Sendt fra min iPhone
