### ISSUE TITLE
Question: can Add DbContext Diagram work with scaffolding generated models?

### ISSUE THREAD

**Issue by Rod-in-NM** [ErikEJ/EFCorePowerTools#1324]
Describe what is not working as expected.

### Steps to reproduce
n/a

Please include a **complete** description or project that I can redo/run to reproduce the issue.

### Further technical details

EF Core version in use: (e.g. EF Core 6)

EF Core 6

Is Handlebars used: yes/no
No

EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
2.5.918.0

Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)
SQL Server

Visual Studio version: (e.g. Visual Studio 2022)
Visual Studio 2022

### Question
This is a question, not an issue. I'd like to know if EF Core Power Tool's `Add DbContext Diagram` will work with the model classes generated by using EF Core 6's `Scaffold-DbContext` command that I issued in Package Manager Console? Or should I delete all of the model classes and the DbContext class I generated previously, then use Ef Core Power Tool's `Reverse Engineer` command instead?

**Comment by ErikEJ** [comment]
I works with any DbContext that follows the rules described in the wiki.
