### ISSUE TITLE
Reverse engineering is inserting bogus connection code within the DBContext.cs

### ISSUE THREAD

**Issue by DavidCAllenMI** [ErikEJ/EFCorePowerTools#1327]
This started yesterday when I got the daily build its inserting this connection code in the last virtual result set. If I delete that everything compiles fine.

        public virtual DbSet<TblVisa> TblVisa { get; set; }
        public virtual DbSet<VwActiveDeployments> VwActiveDeployments { get; set; }
        public virtual DbSet<XrefLoaWeapons> XrefLoaWeapons { get; set; }
        public virtual DbSet<XrefOrgUserRole> XrefOrgUserRole { get; set; }
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. See http://go.microsoft.com/fwlink/?LinkId=723263 for guidance on storing connection strings.
                optionsBuilder.UseSqlServer("Data Source=192.168.200.70\\SPOTDB_DEV1;Initial Catalog=spot;Persist Security Info=True;User ID=sa;Password=spot");
            }
        }

**Comment by ErikEJ** [comment]
Please share a full file  - you can send by email if desired.

**Comment by ErikEJ** [comment]
I was able to reproduce, working on a fix

**Comment by ErikEJ** [comment]
I attempted a fix in the latest daily build, .946 or later
