### ISSUE TITLE
Reverse - Engineer inserting bogus connect information into the DBContext.cs

### ISSUE THREAD

**Issue by DavidCAllenMI** [ErikEJ/EFCorePowerTools#1328]
If I delete the extra code everything compiles.

This is what is being inserted:

        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. See http://go.microsoft.com/fwlink/?LinkId=723263 for guidance on storing connection strings.
                optionsBuilder.UseSqlServer("Data Source=192.168.200.70\\SPOTDB_DEV1;Initial Catalog=spot;Persist Security Info=True;User ID=sa;Password=spot");
            }
        }
[SPOTContext.zip](https://github.com/ErikEJ/EFCorePowerTools/files/8429435/SPOTContext.zip)

**Comment by ErikEJ** [comment]
Did you try the latest daily?

**Comment by DavidCAllenMI** [comment]
juat got 946 and it's not producing the error code now.

**Comment by ErikEJ** [comment]
Thanks for the update

**Comment by DavidCAllenMI** [comment]
I am not sure how to get message to you , but the multiple result sets is working! I just got three back from a sproc. Thanks for all the help. I was able to fix all but one of the other stored procs to stop causing the tool to generate multiple result files also!

**Comment by ErikEJ** [comment]
Wonderful, and thanks for letting me know. 
Wonder if adding a per procedure Configuration option to only consider the first result set for individual procedures could solve this?

**Comment by DavidCAllenMI** [comment]
That would have definitely saved me some work. 😊

**Comment by ErikEJ** [comment]
Would it? You would have to pick each procedure individually and set the option for them?

Or maybe an option to detect that if all result sets have the same shape, they should be "collapsed" to a single result set?

**Comment by DavidCAllenMI** [comment]
If you put a 2nd checkbox in the list of sprocs as the user selects a spoc they could check it this sproc returns only one result. You would only have to check it for one that returning multiples according to the tool and it shouldn’t. In my case there would have been 5 I had to check but it’s taken significant effort to fix them to work with the tool.

**Comment by ErikEJ** [comment]
Thanks, I will consider that.

**Comment by DavidCAllenMI** [comment]
What do I do about the two sprocs that won’t generate results because of TVP?

**Comment by DavidCAllenMI** [comment]
Also I do have that issue still with the TVP stuff

**Comment by ErikEJ** [comment]
@DavidCAllenMI  This is an old issue, please create a new issue describing your exact issue with reporduction steps, and I will try to help
