### ISSUE TITLE
Installing EFCore.Design version 6.0.3, please retry the command

### ISSUE THREAD

**Issue by doggy8088** [ErikEJ/EFCorePowerTools#1332]
Describe what is not working as expected.

### Steps to reproduce

Please include a **complete** description or project that I can redo/run to reproduce the issue.

1. Download my sample repo and open with Visual Studio 2022

    ```sh
    git clone https://github.com/doggy8088/EFCorePowerToolBugReport.git
    cd EFCorePowerToolBugReport
    ```

2. Open `EFCorePowerToolBugReport.csproj` file.  Remove `Microsoft.EntityFrameworkCore.Tools` package from this project.

    Remove the following section:

    ```xml
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="6.0.0">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    ```

3. EF Core Power Tools > Migrations Tool (preview)

    ![image](https://user-images.githubusercontent.com/88981/162621366-46f7f0a3-84d4-4f1f-bd0e-14906d2eec1c.png)

4. The **EF Core Power Tools** did not install the [Microsoft.EntityFrameworkCore.Design](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.Design) or [Microsoft.EntityFrameworkCore.Tools](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.Tools) package for me. It should.

    ![image](https://user-images.githubusercontent.com/88981/162621320-3592fc2d-aa95-4cac-bffd-9d28ac50979a.png)

### Further technical details

EF Core version in use: EF Core 6 (`6.0.3`)

Is Handlebars used: yes

EF Core Power Tools version: `2.5.918.0`

Database engine: `SQL Server` (LocalDB)

Visual Studio version: `Visual Studio 2022`

**Comment by ErikEJ** [comment]
It did not install eventually?

Unless your csproj is a project type or your nuget config is broken it should.

**Comment by doggy8088** [comment]
Yes, it didn't installed eventually. I think my csproj is fine.  You can check [my repo](https://github.com/doggy8088/EFCorePowerToolBugReport). My NuGet.config is fine too.

**Comment by ErikEJ** [comment]
No sure there is anything I can do. I simple call 

     dotnet add package

Maybe change the message?

**Comment by doggy8088** [comment]
Can I see any log in the Output window?

**Comment by ErikEJ** [comment]
No, I do not capture the console log.

**Comment by doggy8088** [comment]
Maybe you can write some logs to a log file for better debugging?

**Comment by doggy8088** [comment]
Can you reproduce the problem I mentioned?

**Comment by ErikEJ** [comment]
I am not at a computer but I will try to repro.

Is your project a asp.net Core 6 project?

**Comment by doggy8088** [comment]
Yes, it's ASP.NET Core 6.

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>9f244dcf-a4fd-4d5c-86e7-e07abe1db0d3</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.3" />
  </ItemGroup>

</Project>
```

**Comment by doggy8088** [comment]
I think I found the bug. You can to add a space after `-v`.

![image](https://user-images.githubusercontent.com/88981/162629141-3cad4b31-7b6f-4147-9b34-e540e8f2271f.png)

**Comment by ErikEJ** [comment]
PR ?

**Comment by doggy8088** [comment]
Done.

**Comment by ErikEJ** [comment]
Thanks for that!
