### ISSUE TITLE
The dialog should close after "Add migration" done or show some message

### ISSUE THREAD

**Issue by doggy8088** [ErikEJ/EFCorePowerTools#1333]
Describe what is not working as expected.

### Steps to reproduce

1. Download my sample repo and open with Visual Studio 2022

    ```sh
    git clone https://github.com/doggy8088/EFCorePowerToolBugReport.git
    cd EFCorePowerToolBugReport
    ```

2. After `Add migration` done, I think the dialog should be closed or show some message.

    ![image](https://user-images.githubusercontent.com/88981/162623412-15159ccb-d6d9-412b-b77a-3b7a0afb8cab.png)

3. I closed the **Manage Migrations in Project EFCorePowerToolBugReport** dialog. Then open **Migrations Tool** again. I think the `Add migration` should change to Database update, but it doesn't.

    ![image](https://user-images.githubusercontent.com/88981/162623320-b21effbe-4eef-49df-96a5-a765af12f4f0.png)

    
### Further technical details

EF Core version in use: EF Core 6 (`6.0.3`)

Is Handlebars used: yes

EF Core Power Tools version: `2.5.918.0`

Database engine: `SQL Server` (LocalDB)

Visual Studio version: `Visual Studio 2022`

**Comment by ErikEJ** [comment]
Sounds like a bug I will investigate

**Comment by ErikEJ** [comment]
I have attempted a fix in the latest daily build, please let me know if that solves your issue.

**Comment by ErikEJ** [comment]
@doggy8088 did you ever try this out?

**Comment by doggy8088** [comment]
Yes, I tested. It's good.

**Comment by ErikEJ** [comment]
Thanks!
