### ISSUE TITLE
Feature request: Add ConnectionStrings:DefaultConnection to secrets.json as an option

### ISSUE THREAD

**Issue by doggy8088** [ErikEJ/EFCorePowerTools#1334]
When using **EF Core Power Tool > Reverse Engineer** feature in a project, I wish this tool have a feature that can add Connection String to the `appsettings.json` config file when I'm in a ASP.NET Core project. That will be very convenient.

**Comment by ErikEJ** [comment]
Should it not be appsettings.Development.json ?

**Comment by doggy8088** [comment]
I think the User Secrets file should be the best place.

**Comment by ErikEJ** [comment]
Agree, but not sure a tool can write to it!?

**Comment by doggy8088** [comment]
You can simple call the `dotnet user-secrets` CLI.

**Comment by doggy8088** [comment]
With the GitHub Copilot's help, this feature might not need anymore. 😆

**Comment by ErikEJ** [comment]
Could you explain?

**Comment by doggy8088** [comment]
Some of my students said they have difficulty with writing connection string by hand. With GitHub Copilot's help, they can get recommended connection string instantly in the editor. So that this features might not needed anymore.

**Comment by ErikEJ** [comment]
Maybe you could teach them about DbConnectionStringBuilder?

**Comment by doggy8088** [comment]
I have an idea. 

Add an options called "Display hints for DI setup and connection strings". If user checked (unchecked by default), after "Reverse Engineer" generated code, show a temp file on the editor area in Visual Studio. The temp files show some guidelines to setup ASP.NET Core which included "Connection Strings" sample json with real connection string value you choose in the EF Core Power Tool UI.

What do you think?

**Comment by ErikEJ** [comment]
I think that would be great and should be enabled by default.

I wish markdown rendering was enabled by default.

But maybe a markdown file would be the Best format anyway.

**Comment by ErikEJ** [comment]
Interested in doing a PR or proposal for the content?

**Comment by doggy8088** [comment]
Where should I put this template of Markdown file?

**Comment by ErikEJ** [comment]
Not important. In RevEng.Core for starters.

**Comment by doggy8088** [comment]
I leaves `[ContextName]` and `[ConnectionString]` as a placeholder for replacement by the tool.

**Comment by ErikEJ** [comment]
Great. I will have a closer look later today.

**Comment by ErikEJ** [comment]
@doggy8088 This has been added to the latest daily, please have a look.

**Comment by doggy8088** [comment]
@ErikEJ 
It works fine. There are two tiny issues.

1. The `DbContext` class shown after code generated and the `PowerToolsReadMe.md` opened as well but hided in another opened tab. It can be ignored easily.

    ![image](https://user-images.githubusercontent.com/88981/166242639-2ae4e8ed-fade-4a14-a8a0-ba0f04ea342c.png)

2. I think Visual Studio is bad for preview Markdown file.  I have installed [Markdown Editor v2](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.MarkdownEditor2) extension.  Is it possible to open Markdown Preview only by default? When I switch to `PowerToolsReadMe.md`, the preview window is quite small by default. 

    ![image](https://user-images.githubusercontent.com/88981/166242894-afb91c27-51ae-4e3e-b24f-79bd959b8215.png)

    It's not a big issue. After I disable this extension. The file shown like this:

    ![image](https://user-images.githubusercontent.com/88981/166244908-4899c507-0c0c-409a-94d3-13754e5db5b8.png)

**Comment by ErikEJ** [comment]
re 1: What do you suggest?? I cannot focus on two documents at the same time, and you may not need to see the readme all the time anyway.

re 2: Maybe a .txt file would be better suited?

**Comment by doggy8088** [comment]
1. I think just keep it that way.
2. I think `.txt` file is okay, probably better than `.md`.

**Comment by ErikEJ** [comment]
A PR with a change to .txt then? 😄

**Comment by doggy8088** [comment]
@ErikEJ done.
