### ISSUE TITLE
Generation of module Parameters that contain reserved words

### ISSUE THREAD

**Issue by glenlewisdd** [ErikEJ/EFCorePowerTools#1336]
If a Procedure or Function from SQL has a parameter that is a C# reserved word, it causes the code file to have errors.

Example, one of the procedures from SQL I have contains a parameter "override" when the signature is created for that procedure it is invalid because "override" is a reserved word.

In your project, you can add a new property to the RevEng.Core.Abstractions.Metadata.ModuleParameter for SignatureName.

And modify your create signature to use the new property name and any of the other methods you have to reference the signature parameters.

You have a reserve word List iRevEng.Core.Modules.SqlServerRoutineScaffolder but the list is private and cannot be accessed.

So I just copied the list into the ModuleParameter class.
```
        public string SignatureName
        {
            get
            {
                if (_keyWords.Contains(Name))
                {
                    return "@" + Name;
                }
                return Name;
            }
        }

        private static readonly HashSet<string> _keyWords = new HashSet<string>
        {
            "abstract",
            "as",
            "base",
            "bool",
            "break",
            "byte",
            "case",
            "catch",
            "char",
            "checked",
            "class",
            "const",
            "continue",
            "decimal",
            "default",
            "delegate",
            "do",
            "double",
            "else",
            "enum",
            "event",
            "explicit",
            "extern",
            "false",
            "finally",
            "fixed",
            "float",
            "for",
            "foreach",
            "goto",
            "if",
            "implicit",
            "in",
            "int",
            "interface",
            "internal",
            "is",
            "lock",
            "long",
            "namespace",
            "new",
            "null",
            "object",
            "operator",
            "out",
            "override",
            "params",
            "private",
            "protected",
            "public",
            "readonly",
            "ref",
            "return",
            "sbyte",
            "sealed",
            "short",
            "sizeof",
            "stackalloc",
            "static",
            "string",
            "struct",
            "switch",
            "this",
            "throw",
            "true",
            "try",
            "typeof",
            "uint",
            "ulong",
            "unchecked",
            "unsafe",
            "ushort",
            "using",
            "virtual",
            "void",
            "volatile",
            "while",
        };
```

I cannot change the parameters due to this is a ERP Procedure that was not created by me.

**Comment by ErikEJ** [comment]
Interested in doing a PR?

Feel free to make the keywords public.

**Comment by ErikEJ** [comment]
Thanks for reporting, fixed in latest daily build

**Comment by glenlewisdd** [comment]
> Interested in doing a PR?
> 
> Feel free to make the keywords public.

Sorry I missed your response here, I was off of work.  

Thank you again for the help and the project you have created.

I do not know all the terminology that is used so the meaning of "PR" I do not know the question here.

**Comment by ErikEJ** [comment]
This has been fixed in the latest daily build...

**Comment by glenlewisdd** [comment]
Okay, I know this is a noob question.  I have never built extensions for VS.  How do I install the daily build or update the extension using the daily builds.

**Comment by ErikEJ** [comment]
No problem- https://github.com/ErikEJ/EFCorePowerTools#daily-build
