### ISSUE TITLE
Table valued function with left joined table generates wrong nullable types

### ISSUE THREAD

**Issue by Dimigergo** [ErikEJ/EFCorePowerTools#1337]
I have created a sample app with a small sql to create two tables queried with table valued function and stored procedure.

As you can see the following picture, the tables contain **not null** integers and the functions have **no return type defined**, only the selects with **left join**.
![error1](https://user-images.githubusercontent.com/11498949/163379251-5da9e682-3726-4dc8-a808-aa353f77a59c.png)

The left joined table int will be nullable, but the main table value remains non nullable. The stored procedure and the function generation are the same symptoms. This is a difference between the Entity Framework 6 (.NET framework), because in that case both of them non nullable types.
![error2](https://user-images.githubusercontent.com/11498949/163379393-0a80cda2-3775-493d-b920-466953d40bd3.png)

### Steps to reproduce

[EFCoreJoinedNullable.zip](https://github.com/ErikEJ/EFCorePowerTools/files/8488643/EFCoreJoinedNullable.zip)

### Further technical details

EF Core Power Tools version: 2.5.918

EF Core version:
Database provider: (Microsoft.EntityFrameworkCore.SqlServer 5.0.16)
Target framework: (.NET 5.0)
Operating system:
Windows 10 (19041)
IDE: (Visual Studio 2022 17.1.3)

**Comment by ErikEJ** [comment]
This does not seem to related to Power Tools but a runtime issue.

**Comment by Dimigergo** [comment]
But Power Tools generates the code, doesn't it?

**Comment by ErikEJ** [comment]
Power Tools generates code very similar or equal to the built in command line tools.

**Comment by ErikEJ** [comment]
Sorry, I missed that this is about the stored procedure result set.

I will have a closer look. 

EF6 and Power Tools most likely use different ways to discover the result set shape.
