### ISSUE TITLE
Stored procedure generation with lock failed to generate return properties

### ISSUE THREAD

**Issue by Dimigergo** [ErikEJ/EFCorePowerTools#1338]
If I have a stored procedure with a lock the generated code doesn't contains return types.
![error0](https://user-images.githubusercontent.com/11498949/163382233-0111df02-e0bc-472b-94da-47750c628325.png)
![error2](https://user-images.githubusercontent.com/11498949/163382430-0b394c6f-56ab-4d65-a7d0-7f91f211ba08.png)

If I uncomment the "lock" line the generation is success:
![error1](https://user-images.githubusercontent.com/11498949/163382488-b41c907b-6db0-4029-807c-e8accbd44358.png)

### Steps to reproduce

[EFCoreTableLock.zip](https://github.com/ErikEJ/EFCorePowerTools/files/8488769/EFCoreTableLock.zip)

### Further technical details

EF Core Power Tools version: 2.5.918

EF Core version:
Database provider: (Microsoft.EntityFrameworkCore.SqlServer 5.0.16)
Target framework: (.NET 5.0)
Operating system:
Windows 10 (19041)
IDE: (Visual Studio 2022 17.1.3)

**Comment by ErikEJ** [comment]
Most likely due to limitations of sp_describe_first_resultset.

Related to #1243

**Comment by ErikEJ** [comment]
You can manually add the return properties in a partial class.
