### ISSUE TITLE
Not working on .NET 7 project

### ISSUE THREAD

**Issue by YuhanKun** [ErikEJ/EFCorePowerTools#1339]
![image](https://user-images.githubusercontent.com/76238985/163384816-dafda053-1b9e-4f49-b991-449dc2955722.png)
Add .NET 7 check to https://github.com/ErikEJ/EFCorePowerTools/blob/5f7bc70e94322c3c7936bfa829445b6ab7af4e26/src/GUI/Shared/Extensions/ProjectExtensions.cs#L185-L188 should resolve the problem
### Steps to reproduce

Open a .NET 7 project in VS2022
Right-click on the project then "EF Core Power Tools > Add DbContext Diagram"

### Further technical details

EF Core version in use: EF Core 6

Is Handlebars used: no

EF Core Power Tools version: 2.5.918.0

Database engine: MySQL

Visual Studio version: Visual Studio 2022

**Comment by ErikEJ** [comment]
Currently .net 7 projects are actually nit supported. Updating the check will not work.

**Comment by YuhanKun** [comment]
> Currently .net 7 projects are actually nit supported. Updating the check will not work.

I see. 
Hope this extension can be support .NET 7 projects soon in the future
Thanks for your great extension. 😁

**Comment by ErikEJ** [comment]
Thanks - if it is for DbContext diagrams I think I can enable quite soon.

**Comment by ErikEJ** [comment]
Closing in favor of #1345

**Comment by ErikEJ** [comment]
@YuhanKun This has now been implemented in the latest daily build. Please let me know if it works for you.
