### ISSUE TITLE
EF Core 7 tasks

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#1345]
Currently the following features and providers are available:
T4 templates, SQL/Azure SQL, Postgres, SQLite, all with spatial

- [x] Add support for modelling with EF7 using .NET 7
- [x] Add reverse engineering support for EF7
- [x] Add support for dropping T4 templates @bricelam
- [x] Add .dacpac support - 161.x package available @dzsquared 
- [x] Add Oracle support @alexkeh
- [x] Add SqlServer NodaTime support @stevenrasmussen 
- [x] Add SqlServer HierarchyId support @bricelam - RC2 package available
- [x] Add Sqlite NodaTime support @khellang 
- [x] Add Handlebars support @tonysneed 
- [x] Add Pomelo support @lauxjpn 
- [ ] Add Firebird support @cincuranet 
- [ ] Add SchemaCompare support  @JonPSmith https://www.nuget.org/packages/EfCore.SchemaCompare/7.0.0 - awaiting request :-)
- [x] Verify #1472 with .tt files

**Comment by ErikEJ** [comment]
Install .NET 7 SDK: https://gist.github.com/FeodorFitsner/c62c323dee76b6c116e6ea699770f587#file-appveyor-yml-L3-L6

**Comment by ErikEJ** [comment]
@KayakFisher205 Yes, it does - have you experienced something else?

**Comment by KayakFisher205** [comment]
No, I was just checking before I ran the tool. I have like 27 in one Database and I added those by hand. Running to the tool, it looks like it added every trigger on a table. I had just added one line and I guess that took care of all of them. This looks a lot cleaner. Thanks for the update.

**Comment by bricelam** [comment]
FYI, I started digging into the Handlebars code in [bricelam:seven](https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars/compare/master...bricelam:EntityFrameworkCore.Scaffolding.Handlebars:seven?w=1). I intend to finish it and send a PR as time allows. /cc @tonysneed

**Comment by ErikEJ** [comment]
Any update on EF 7 support   @lauxjpn @cincuranet @alexkeh ?

**Comment by cincuranet** [comment]
High level tracking for Firebird is [here](https://github.com/FirebirdSQL/NETProvider/issues/1083).

**Comment by alexkeh** [comment]
The plan is for an Oracle EF Core 7 provider to be released by the end of this year.

**Comment by lauxjpn** [comment]
We released [7.0.0-alpha.1](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/releases/tag/7.0.0-alpha.1) of the Pomelo provider today, that supports all features of EF Core 7. The official GA release will be out by the end of the month.

**Comment by vitalyhermonlabs** [comment]
NET7 version isn't creating IndexerProperty for M2M while the previous version was OK

**Comment by ErikEJ** [comment]
@vitalyhermonlabs How does that relate to this issue? If you see a EF Core bug, please report in the EF Core repo, or create a new issue here.

**Comment by tonysneed** [comment]
@ErikEJ @bricelam I release beta1 of the EF core 7 upgrade to Handlebars templates: https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars/releases/tag/v7.0.0-beta1

NuGet package here to test: https://www.nuget.org/packages/EntityFrameworkCore.Scaffolding.Handlebars/7.0.0-beta1

**Comment by ErikEJ** [comment]
@tonysneed Added to latest daily

**Comment by dradermaker** [comment]
From some testing, I was able to reverse engineer a database with triggers when using an actual connection to the database as source. However, the HasTrigger properties were not generated when using the dacpac as a source. Is this the expected behavior ?

**Comment by ErikEJ** [comment]
@dradermaker Good point - just not implemented! I have created: https://github.com/ErikEJ/EFCorePowerTools/issues/1590

**Comment by dradermaker** [comment]
Awesome ! Thanks @ErikEJ ! You have developed a wonderful tool for the community !

**Comment by ErikEJ** [comment]
Thanks  for the kind words, @dradermaker - 
I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details)
