### ISSUE TITLE
Make FMTONLY default discovery method, and enable global fallback to sp_describe_first_result_set

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#1346]
- [x] Add option support
- [x] Enable switch
- [x] test it
- [ ] Fallback to sp_describe_first_result_set if FMTONLY fails (postpone until feedback arrives)

**Comment by ErikEJ** [comment]
@DavidCAllenMI You can fallback individual stored procedures as documented here: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#sql-server-stored-procedures

**Comment by ErikEJ** [comment]
@DavidCAllenMI The global option forces sp_describe_first_result_set for everything

**Comment by DavidCAllenMI** [comment]
Thanks! Your Awesome!!!!

**Comment by DavidCAllenMI** [comment]
Working on it now!!!

**Comment by DavidCAllenMI** [comment]
IT WORKED PERFECT! I have this one sproc that executes other sprocs which execut other sprocs...I was getting back 66 resultsets. I added your flag into the efpt.config.json and got !!! Woo hoo!! your the best!

Question, I am assuming that if someone unchecks the selection to reverse engineer that sproc it will be removed from the efpt.config.json file?

**Comment by ErikEJ** [comment]
Correct. If it is unchecked it is removed from the file.
