### ISSUE TITLE
Support in reverse engineering for multiple target frameworks & versions of EF Core

### ISSUE THREAD

**Issue by johnhenley** [ErikEJ/EFCorePowerTools#1347]
I have several libraries that support various applications using different framework versions, net48, net5, net6, etc. Rather than have different library project, I use a project with multiple target frameworks 
` <TargetFrameworks>netstandard2.0;net6.0</TargetFrameworks>
`
I then use different PackageReferences to pull in the desired versions of EF Core based on the target framework during build. 
`
	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.22" Condition="'$(TargetFramework)' == 'netstandard2.0'" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.4" Condition="'$(TargetFramework)' == 'net6.0'" />
	</ItemGroup>
`
I then select EF Core 3 when running reverse engineer:
![image](https://user-images.githubusercontent.com/9553126/164102355-81a77652-5ada-4d09-8585-50fb92aacec1.png)

When I select higher version of EF Core, I get errors.

In order to support netstandard 2.0, have to use EF Core 3.1.
Is there a way to select multiple versions of EF Core in reverse engineer to match the target EF Core versions?

Also, not sure I understand how EOL for EF Core 3.1 & netstandard 2.0 is 2022, but .net framework 4.8 is not.
So what is roadmap (if any) for someone like me who did what they were told (use netstandard 2.0 + EF Core 3.1 rather than EF6 to support .net framework 4.8) and now I'm kinda stuck :) Any guidance there?

### Further technical details

EF Core version in use: multiple

Is Handlebars used: no

EF Core Power Tools version: 2.5.918

Database engine: SQL Server

Visual Studio version: Visual Studio 2022

**Comment by ErikEJ** [comment]
Not sure I understand. The tool just generates a bunch of files for the selected EF Core version.
If you want diffferent code for each version, you need different .csproj files.

**Comment by johnhenley** [comment]
A .csproj file can support multiple target frameworks, and based on those frameworks, apply different EF Core nuget packages. What would be cool is if instead of this were a list of checkboxes rather than a dropdown, 
![image](https://user-images.githubusercontent.com/9553126/164248421-a287f537-a312-4f29-be96-990ea35d0a81.png)
Then have the tool generate multiple sets of files to different folders, and update the .csproj with conditional includes...`
  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard20'">
   <Compile Include="netstandard20\dbcontext.cs" /> 
   <Compile Include="netstandard20\1.cs" /> 
   <Compile Include="netstandard20\2.cs" /> 
  </ItemGroup>`
  <ItemGroup Condition="'$(TargetFramework)' == 'net6.0'">
   <Compile Include="net60\dbcontext.cs" /> 
   <Compile Include="net60\1.cs" /> 
   <Compile Include="net60\2.cs" /> 
  </ItemGroup>`

**Comment by ErikEJ** [comment]
Thanks. I get the idea but this quite advanced scenario is not something I plan to implement and support. 

You can run the Tool three times and get almost similar results  in particular if you use folder/*.cs in your csproj
