### ISSUE TITLE
Multiline efpt.config.json

### ISSUE THREAD

**Issue by blogcraft** [ErikEJ/EFCorePowerTools#135]
When creating or updating the model the efpt.config.json rewrites itself as single line. For merging purposes it would be best if the default behavior would be to write a multiline file.

Now:
`{  "ContextClassName": "someContext", "DefaultDacpacSchema": null, "IdReplace": false, "IncludeConnectionString": false, "OutputPath": "SomeFolder", "ProjectRootNamespace": "MyAwesomeApp", "SelectedToBeGenerated": 0, "Tables": [ "dbo.table_1", "dbo.table_2", "dbo.table_...", "dbo.table_x" ], "UseDatabaseNames": false, "UseFluentApiOnly": true, "UseHandleBars": false, "UseInflector": false }`

Expected:
```
{
  "ContextClassName": "someContext",
  "DefaultDacpacSchema": null,
  "IdReplace": false,
  "IncludeConnectionString": false,
  "OutputPath": "SomeFolder",
  "ProjectRootNamespace": "MyAwesomeApp",
  "SelectedToBeGenerated": 0,
  "Tables": [
    "dbo.table_1",
    "dbo.table_2",
    "dbo.table_...",
    "dbo.table_x"
  ],
  "UseDatabaseNames": false,
  "UseFluentApiOnly": true,
  "UseHandleBars": false,
  "UseInflector": false
}
```

### Steps to reproduce
Reverse engineer a database.

### Further technical details
EF Core Power Tools version: 1.0.664.0

Database engine: SQL Server

Visual Studio version: Visual Studio 2017 15.9.2

**Comment by ErikEJ** [comment]
I would like not to depend on Newtonsoft.Json - a PR based on the solution here would be appreciated: https://stackoverflow.com/questions/33371606/datacontractjsonserializer-human-readable-json

**Comment by ErikEJ** [comment]
@OmiCron07 - Thanks for your help!
