### ISSUE TITLE
Advanced - Use schema folder separation - Not 

### ISSUE THREAD

**Issue by Damien-Rosenberg** [ErikEJ/EFCorePowerTools#1350]
Describe what is not working as expected.
Its not a problem, its a request :)

### Steps to reproduce
Advanced settings -> File layout -> Use schema folder separation -> selected 
Advanced settings -> File layout -> Split DBContext into Configuration classes -> selected 
It would be useful to have the schema's included in the namespaces of the models
When the configurations are generated it would also be useful to have the configurations generated into schema folders (and namespaces) too.

### Further technical details

EF Core version in use: EF Core 6

Is Handlebars used: yes

EF Core Power Tools version: 2.5.918.0

Database engine: SQL Server

Visual Studio version: Visual Studio 2022

**Comment by ErikEJ** [comment]
Duplicate #1075 ??

**Comment by Damien-Rosenberg** [comment]
It does seem to be - apologies. Thanks for the great tool. Any idea when that will be worked on?

**Comment by ErikEJ** [comment]
I am always open to pull request 😉
