### ISSUE TITLE
DB function - reverse engineer

### ISSUE THREAD

**Issue by gbthakkar** [ErikEJ/EFCorePowerTools#1351]
Describe what is not working as expected.

### Steps to reproduce
(1) Add scalar function in sql server database
(2) Reverser eng. in Blazor 6 using EF core 5
(3) Function does not create called code.

code looks like below.
[DbFunction("GetOpeningBal_Fn", "dbo")]
        public static decimal? GetOpeningBal_Fn(int? ledgerID, DateTime? Date)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

EF Core version in use:  EF Core 5

Is Handlebars used: yes/no : Not sure, what is this.

EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu) : 2.5.918.0

Database engine:  SQL server 

Visual Studio version:  Visual Studio 2022

**Comment by ErikEJ** [comment]
That is how function mappings work - have a look at the docs here:  https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#sql-server-stored-procedures

**Comment by gbthakkar** [comment]
Hi Sir,

I know, you have closed this ticket.
And I request not to take me otherwise because of my language.

I am looking for your help. Because this tool is addictive. Once we start
using it, we can not imagine working without this.

Here is the video I try to record which shows what I am doing and the issue
I am facing.

https://www.youtube.com/watch?v=hcw7gpJDbH0











*Regards,*

*Gaurang Thakkar*

**Comment by ErikEJ** [comment]
Thanks for the video, I need you to share the full error message as text, and the function definition ( you can share privately : ejlskov at Hotmail dot com)

**Comment by ErikEJ** [comment]
It was a bug, fixed in .962 or higher

**Comment by gbthakkar** [comment]
hi Erik,

Thank you for your confirmation. Could you please let me know any expected
date for release so I can download the new version.

Thanks,

*Regards,*

*Gaurang Thakkar*

**Comment by ErikEJ** [comment]
It is released now

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by gbthakkar** [comment]
Oh,.  You are great sir.

**Comment by ErikEJ** [comment]
@gbthakkar Please create a new issue with code (not a video) so I can reproduce the issue.

**Comment by gbthakkar** [comment]
Hi Erik,

Github say that I have posted a comment 2 hours ago. Which is incorrect. I
have not posted anything in last 7-10 days.
And I am using the nightly build 2.5.1145 which working fine for me.
Kinly close this issue and I will open a new one ticket when I will have
something to share with you.
Thanks

*Regards,*

*Gaurang Thakkar*

**Comment by ErikEJ** [comment]
@gbthakkar Great! It think there was some email processing issues!
