### ISSUE TITLE
Change auto-generated Schema in DataAnnotations for db_sysadmin (SQL Server)

### ISSUE THREAD

**Issue by dhornet87** [ErikEJ/EFCorePowerTools#1353]
Is there a way to get the DataAnnotation for a Table with dbo schema (e.g. [Table(xyz), Schema="dbo"]), although the current User is a sysadmin and so his default schema is always dbo?

### Steps to reproduce

One of our Team Members is a sysadmin and every time he tries to ReverseEngineer something, all Tables will get changed. Thats because all generated Models will drop the schema ("dbo") in the DataAnnotation for the table (he is the only one with the sysadmin Role).

Is there a way to change this behavior? 

We already tried to add a efpt.renaming.json file but without success:
[
    "UseSchemaName": false,
    "SchemaName": "dbo"
]

Thanks for your help!!!

### Further technical details

EF Core version in use: (e.g. EF Core 6)
EF Core 6
Is Handlebars used: yes/no
no
EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
2.5.918.0
Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)
SQL Server
Visual Studio version: (e.g. Visual Studio 2022)
Visual Studio 2022

**Comment by ErikEJ** [comment]
Getting the default schema is part of the standard EF Core implementation, and not something that is immediately customizable.  

Maybe ask your sysadmin colleague to use a different set of credentials when reverse engineering? Maybe even create a dedicated account for that?

**Comment by dhornet87** [comment]
okay, good to know and thanks for your help! We will create a dedictated account for him then.

**Comment by ErikEJ** [comment]
This will be fixed without requiring workaround in #1376
