### ISSUE TITLE
Reverse Engineering stored procedures ChangingAndChangedNotificationsWith 

### ISSUE THREAD

**Issue by TimKras** [ErikEJ/EFCorePowerTools#1354]
We use the tool to revers Engeneer an DB (EF Core 3.1).
We use the Handlebar templates to generate models with INotifyPropertyChanged support, so we can enable ChangingAndChangedNotificationsWith on the modelbuilder.
There are also some stored procedures, which are generated, but those results do nog use the handlebars?
We get this runtime exception:
`The entity type '/' is configured to use the 'ChangingAndChangedNotificationsWithOriginalValues' change tracking strategy but does not implement the required 'INotifyPropertyChanged' interface.`

**Comment by ErikEJ** [comment]
Handlebars is a third party library  and has no knowledge of stored procedure result set classes. 

But the generated classes are partial, so you can extend them.

**Comment by ErikEJ** [comment]
I do not think there is any more I can do here, maybe this will improve with T4 templates in EF Core 7?
