### ISSUE TITLE
Unable to get result set shape for FUNCTION 'MY-TABLE_VALUED-FUNCTION' 

### ISSUE THREAD

**Issue by EXT1433S** [ErikEJ/EFCorePowerTools#1356]
Hello, 

as of yesterday, i get the following error when using reverse engineering to refresh my model.

`Unable to get result set shape for FUNCTION 'MY-TABLE_VALUED-FUNCTION'
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
at System.Linq.Enumerable.Contains[TSource](IEnumerable`1 source, TSource value, IEqualityComparer`1 comparer)
at RevEng.Core.Procedures.SqlServerRoutineModelFactory.GetRoutines(String connectionString, ModuleModelFactoryOptions options) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\Routines\SqlServerRoutineModelFactory.cs:line 25`

My function is structured as follows

`CREATE FUNCTION MY-TABLE_VALUED-FUNCTION(@email nvarchar(250))
RETURNS @result TABLE (
    personid int,
    email nvarchar(250),
    eventtitle nvarchar(250),
    startdate datetime,
    enddate datetime,
    instructorname nvarchar(250),
    buildingname nvarchar(250),
    roomname nvarchar(250),
    datasource nvarchar(250),
    groupname nvarchar(250)
)
AS ......`

I have tried the parameter "UseLegacyResultSetDiscovery" without success.
My colleague uses version 2.5.961 and does not have the issue.

EF Core version in use: EF Core 5
EF Core Power Tools version: 2.5.963.0
Database engine: MS SQL Server
Microsoft Visual Studio Professional 2019 Version 16.11.13

**Comment by ErikEJ** [comment]
I will have a look

**Comment by yangxinde** [comment]
I have the same problem, how can I reply to the previous version?

**Comment by ErikEJ** [comment]
Fixed in the latest daily build, please try it out and let me know

**Comment by yangxinde** [comment]
> Fixed in the latest daily build, please try it out and let me know

Thank you, the problem has been fixed.

**Comment by ErikEJ** [comment]
@yangxinde thanks for confirming

**Comment by EXT1433S** [comment]
Works perfectly again, thanks for the quick help
