### ISSUE TITLE
Right-clicking context menu item of efcore tools is not visible

### ISSUE THREAD

**Issue by hichamoussa** [ErikEJ/EFCorePowerTools#1359]
After updating extension yesterday (27/04/2022), the menu item was disappeared from context menu of Right-clicking on a C# project

### Steps to reproduce

Update extension from "Manage extensiosn" Menu
Right-click on c# projet

### Further technical details

EF Core Power Tools version: 2.5.963 and 2.5.966

Database engine: (SQL Server)

Visual Studio version: Microsoft Visual Studio Enterprise 2022 (64-bit) - Version 17.1.5

**Comment by ErikEJ** [comment]
Unable to repro.

**Comment by ErikEJ** [comment]
Maybe a restart and or VS repair?

**Comment by hichamoussa** [comment]
Thank you for your answer, it works with Visual studio repair. I take this opportunity to thank you very much for this excellent and useful extension.
