### ISSUE TITLE
Warning regarding Reverse Engineering

### ISSUE THREAD

**Issue by daveblack93** [ErikEJ/EFCorePowerTools#1362]
Hi,
from today when I use "Reverse Engineering" functionality I got the warning attached that cause a property missing in the Context file (for example auto calculated fields are not moreover imported like before).

![image](https://user-images.githubusercontent.com/63237292/165720284-5b261168-c409-47cd-9315-4fccfae19f7f.png)

Example deleted lines Context file:

```cs
entity.Property(e => e.UnitPrice).HasComputedColumnSql("(case [ShippedQuantity] when (0) then (0) else [TotalPrice]/[ShippedQuantity] end)", true);

entity.Property(e => e.UnitWeight).HasComputedColumnSql("(case [ShippedQuantity] when (0) then (0) else [TotalWeight]/[ShippedQuantity] end)", true);

entity.Property(e => e.Currency).HasDefaultValueSql("('EUR')");
```
These lines are deleted with the last Reverse Engineerding round.

Do I have some missing configuration or depends from some bugs?

### Further technical details

EF Core version in use: EF Core 6

EF Core Power Tools version: 2.5.966.0

Database engine: SQL Server

Visual Studio version: Visual Studio Community 2022 (64-bit) - Version 17.1.6

**Comment by ErikEJ** [comment]
Did you read the error message?

**Comment by daveblack93** [comment]
Hi Erik, yes but I don't understand why appear in this version, using plugin version 2.5.963.0 I haven't this message and I use same database and same VS config. Could you help me please?

Thanks

**Comment by ErikEJ** [comment]
The rights for your database user must have changed?

**Comment by daveblack93** [comment]
Erik I delete the connection from the plugin and setup it again and come back to work.
I'm sure that nothing change on database side but thanks for the support.
