### ISSUE TITLE
Question: generated file naming

### ISSUE THREAD

**Issue by Allann** [ErikEJ/EFCorePowerTools#1363]
## Overview
When I use the reverse engineer function which works great btw, I am presented with a lot of partial classes, also great.  However, these files are named in such a way that it makes it hard to create another partial class that becomes the root of nested files.  Allow me to explain:

- i have a generated file named **Models/Event.cs**
- I now want to extend said class with additional details, but I can't name it Event.cs as well and any other names like Event_more.cs or Event.more.cs will either keep the file at the same nested level or under the generated file.

## Preference -
I would like the generated files to be named as they are but with a suffix, i.e.  Event.generated.cs
Thereby allowing me to create the **User** version of the file to be called Event.cs.  This does a few things:
- nests the generated file UNDER the user version
- makes it really easy to know if a dev has added functionality to generated code
- allows dev to easily see non-generated code as it's the top-level class
- put in place a safety check during code reviews to ensure generated code hasn't been changed thereby no longer reflecting the physical schema.

# Question
Is there a simple way to add a suffix to generated files?  Or would you like a PR to add such a feature?

### Further technical details

EF Core 6 generated from .dacpac

Is Handlebars used: no

EF Core Power Tools version: 2.5.966.0

Database engine: SQL Server

Visual Studio version: 2022

**Comment by Allann** [comment]
Regarding the PR, I assume I'd need to add a new ModuleScaffolderOptions property, i.e.  FilenameSuffix and then apply said suffix to SqlServerRoutineScaffolder.ScaffoldModel at the end where it sets the filenames?
``` cs
var generatedSuffix = scaffolderOptions.Suffix is null ? "" : "." + scaffolderOptions.Suffix;

// looping code removed for brevity

result.AdditionalFiles.Add(new ScaffoldedFile
{
    Code = classContent,
    Path = scaffolderOptions.UseSchemaFolders
        ? Path.Combine(routine.Schema, $"{typeName}{generatedSuffix}.cs")
        : $"{typeName}.{generatedSuffix}.cs"
});

// more blah, blah, blah

Path = Path.GetFullPath(Path.Combine(scaffolderOptions.ContextDir, scaffolderOptions.ContextName + $"{FileNameSuffix}{generatedSuffix}.cs")),
```

Or something to that effect?

**Comment by ErikEJ** [comment]
Yes, but it should be an option, not the dafault behavior

**Comment by ErikEJ** [comment]
Some comments / thoughts:

>> nests the generated file UNDER the user version

This only works for ASP.NET Core apps.

>> makes it really easy to know if a dev has added functionality to generated code

How is that different from the other way round in a PR review - and all generated files have header?

>> allows dev to easily see non-generated code as it's the top-level class

True, but only for asp.net core apps

>> put in place a safety check during code reviews to ensure generated code hasn't been changed thereby no longer reflecting the physical schema.

How is that different from the other way round in a PR review - and all generated files have header?

**Comment by Allann** [comment]
Yes, definitely an opt in option.  And yes totally agree that at the moment nesting only works for Project Sdk="Microsoft.NET.Sdk.Web" types, however, we are "assured" by microsoft that nesting will work for all project types eventually.  Here's hoping.
With the new minimal API hype, many apps will still benefit from the change as they don't push separation of projects instead keeping everything small and within the project.  Let's see what this does to coding standards in a few years of new adopters.
In a PR, well I suppose everyone uses Git these days, so good point, can't disagree with that.

**Comment by ErikEJ** [comment]
@Allann In order to test this kind of change, you can run the efreveng60 command line tool in the debugger with a command line pointing to one of the test files in the efreveng/testfiles folder.

There are scripts in the Scaffoldingtester solution to populate a Northwind or Chinook database.

I  will try to find a good place to document this better.

**Comment by ErikEJ** [comment]
readme.md updated
