### ISSUE TITLE
Feature Request: Improved Null Reference Types Support via SmartAnalyzers.CSharpExtensions.Annotations 

### ISSUE THREAD

**Issue by jamshally** [ErikEJ/EFCorePowerTools#1364]
This is a feature request related to the existing Nullable Reference Types support (experimental) in EFCorePowerTools

In short: this is a suggestion to leverage the [InitRequiredIfNotNull] capability of SmartAnalyzers.CSharpExtensions.Annotations in order to move the responsibility for initialization from the Type, to the consuming code - which seems perfect for this Use Case

### Details
Currently, when the Nullable Reference Types option is enabled, the non-nullable fields get initialized with `null!`, and '#nullable enable' is inserted at the top of the generated files.  

While this is better than having Nullable Reference Types disabled, it still leaves potential for problems when the generated Models are manually instantiated, as there are no guarantees that all the non-nullable fields will be initialized as expected.

There is a Static Code Analysis library called [SmartAnalyzers.CSharpExtensions.Annotations](https://github.com/cezarypiatek/CSharpExtensions) which shifts the responsibility for initialization onto the consuming code. 

Pairing this with the EFCorePowerTools Null Reference Type support would allow the consumer to benefit both from an increased level of Static Code Analysis checks.

### Further Information
Article related to this concept here: https://cezarypiatek.github.io/post/better-non-nullable-handling/

### Further technical details
EF Core version in use: EF Core 6
Is Handlebars used: no
Database engine: Azure SQL
Visual Studio version: Visual Studio 2022

**Comment by ErikEJ** [comment]
Could you provide an example of what needs to change in EF Core Power Tools?

Can you make the changes in a partial file?

**Comment by ErikEJ** [comment]
This seems too localized to a specific 3rd pary Nuget package, not something I plan to implement.
