### ISSUE TITLE
Reverse Engineer - Suggest some Default Values

### ISSUE THREAD

**Issue by doggy8088** [ErikEJ/EFCorePowerTools#1367]
I have some suggestions to discuss.

1. EF Core 5 is the default now. I'd like to suggest change it to EF Core 6 by default.

    ![image](https://user-images.githubusercontent.com/88981/166241205-28cca27d-3ee1-48e1-90d9-883241954614.png)

2. The `EntityTypes path` and `DbContext path` can fill default value directly and remove `(f.ex. xxxx)` part.

    ![image](https://user-images.githubusercontent.com/88981/166241684-b47eb23e-bccc-478e-b997-a8ca14f4f21a.png)

3. See above screenshot. The `Context name` shown `ContosouniversityContext` that extract from my connection string. My database name is actually called `ContosoUniversity`. Is it possible leave database name as is just like `ContosoUniversityContext`?

**Comment by ErikEJ** [comment]
Fine to default to EF6 - PR?

Not so keen on item 2 - too breaking and opinionated.

On 3: The DbContext names is C#-ified, so maybe it loses some casing details. Have a look to see if it can be improved.

**Comment by doggy8088** [comment]
1. Ok. I'll do it in the coming days.
2. That's just a "default value". I think "opinionated" is fine. Better than empty.
3. If you use `dotnet ef dbcontext scaffold`, the generated dbcontext name will be `ContosoUniversityContext`.

**Comment by ErikEJ** [comment]
I suggest creating individual issues instead of piling them up.

I have created a new issue for item 3.

**Comment by doggy8088** [comment]
OK. It's good.
