### ISSUE TITLE
Map Geometry type in func and stored procedures

### ISSUE THREAD

**Issue by Dimigergo** [ErikEJ/EFCorePowerTools#1368]
In issue #1349 the "Geometry" type is corrent not, but the `using NetTopologySuite.Geometries;` line is missing.

EF Core Power Tools: 2.5.966

Sample project is the same:
[EFCore5Geography.zip](https://github.com/ErikEJ/EFCorePowerTools/files/8603599/EFCore5Geography.zip)

**Comment by ErikEJ** [comment]
The docs probably need an Update

Does the call error? Do you have any data in the table?

**Comment by bngapiusr** [comment]
no errors and I have data in the table. I tested the store procedure in ssms and I got some data back.

**Comment by ErikEJ** [comment]
@bngapiusr You a posting in a completely unrelated issue !?

**Comment by ErikEJ** [comment]
@Dimigergo Where is it missing?

**Comment by bngapiusr** [comment]
oh sorry about that. I'll create a new issue.

**Comment by Dimigergo** [comment]
> @Dimigergo Where is it missing?

The top of the generated func or sp .cs. It generates the file with Geometry type, but no using NTS at the top.

**Comment by Dimigergo** [comment]
This is the generated file:

![usingError](https://user-images.githubusercontent.com/11498949/166418010-77da530a-1859-4e11-b3e2-fca1d87aba21.png)

**Comment by ErikEJ** [comment]
Thanks.

**Comment by ErikEJ** [comment]
@Dimigergo Fixed in latest daily build
