### ISSUE TITLE
Stored Procedure Not Returning Results

### ISSUE THREAD

**Issue by bngapiusr** [ErikEJ/EFCorePowerTools#1370]
I'm trying to use EF Core Power Tools version: 2.5.966 to reverse engineer Northwind db but I'm not getting any results when I call the store procedure. 

           using (var db = new NorthwindDbContext())
            {

                var orders = await db.Procedures().CustOrderHistAsync("ALFKI");

                foreach (var order in orders)
                    Console.WriteLine($"{order.ProductName}: {order.Total}");
              }

I'm following the example in the docs.
I noticed the examples has  
                 var orders = await db.GetProcedures().CustOrderHist("ALFKI") and not the async method  
                    db.Procedures().CustOrderHistAsync("ALFKI") that I'm using above. The generated code only provide the async option so I don't know what I'm missing here. 

I'm using EF Core 5.16 and I tested it in VS2019 and VS2022.

Thank you!

**Comment by ErikEJ** [comment]
Connection string?

**Comment by bngapiusr** [comment]
This is what I have in the dbcontext

#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Data Source=.;Initial Catalog=Northwind;Integrated Security=True");
            }

**Comment by ErikEJ** [comment]
@bngapiusr Where do you see that example?

**Comment by ErikEJ** [comment]
@bngapiusr  I am unable to reproduce, I get 11 rows back, assume you database is empty.

**Comment by bngapiusr** [comment]
Support for mapping multiple result sets per procedure is currently in preview and you must opt-in via the global option, see below.
Sample usage of the generated code:

https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#sql-server-stored-procedures

**Comment by bngapiusr** [comment]
Thanks for the update ErikEJ! Yes, I get 11 rows back when I ran it in SSMS.
here is the solution.
[EfCorePowerTools.zip](https://github.com/ErikEJ/EFCorePowerTools/files/8605268/EfCorePowerTools.zip)

**Comment by ErikEJ** [comment]
What are you connecting to in SSMS?

Screenshot?

**Comment by bngapiusr** [comment]
to the northwind database in sql server on my pc

**Comment by ErikEJ** [comment]
Maybe it is not the same instance.

Screenshot please?

**Comment by bngapiusr** [comment]
Screenhot
![Northwind](https://user-images.githubusercontent.com/27658927/166306740-156527f8-dce7-472f-bb7b-581ce7cacc4f.jpg)

**Comment by ErikEJ** [comment]
Please scroll up to the servername

**Comment by bngapiusr** [comment]
![Server](https://user-images.githubusercontent.com/27658927/166307556-41083a9d-1f01-4a79-ab62-fd3c095eed50.jpg)

**Comment by ErikEJ** [comment]
I will have a look at your repro project.

As I said, I cannot reproduce.

**Comment by bngapiusr** [comment]
ok, thank you!

**Comment by ErikEJ** [comment]
You are doing async wrong, it should be something like this:

```csharp
using System;
using System.Threading.Tasks;
using EfCorePowerTools.Northwind.Data;

namespace Northwind.Client
{
    class Program
    {
        static async System.Threading.Tasks.Task Main(string[] args)
        {
            await GetResultsFromStoredProcedure();
        }

        public static async Task GetResultsFromStoredProcedure()
        {
            using (var db = new NorthwindDbContext())
            {

                var results = await  db.GetProcedures().CustOrderHistAsync("ALFKI");

                foreach (var order in results)
                    Console.WriteLine($"{order.ProductName}: {order.Total}");
            }
        }
    }
}

```

**Comment by bngapiusr** [comment]
Thanks a million Erik!! It is working now :)

**Comment by ErikEJ** [comment]
You are welcome, happy to help.
