### ISSUE TITLE
Feature Request: Named DB connection string

### ISSUE THREAD

**Issue by DustinLuck** [ErikEJ/EFCorePowerTools#1375]
The Entity Framework CLI has an option to use a connection string from the appsettings file (https://docs.microsoft.com/en-us/ef/core/managing-schemas/scaffolding?tabs=vs#configuration-and-user-secrets) when reverse engineering the database. I could not find a setting in the EFCore Power Tools to do the same.

If this exists, could someone point me to where it's set? If not, is this something that could be added?

### Further technical details

EF Core version in use: (e.g. EF Core 5)

Is Handlebars used: no

EF Core Power Tools version: 2.5.966.0

Database engine: SQL Server

Visual Studio version: 2022

**Comment by ErikEJ** [comment]
Power Tools does not load or interact with your project, and is therefore not able to load any project configuration - this is by design.
