### ISSUE TITLE
DataAnnotation 'Index' attribute is an ambiguous reference 

### ISSUE THREAD

**Issue by CodeTile** [ErikEJ/EFCorePowerTools#1379]
DataAnnotation 'Index' attribute is an ambiguous reference 

### Steps to reproduce

When reverse engineringing check the checkbox "Use DataAnnotation attributes to configure the model" and press Ok.
The error ```Error	CS0104	'Index' is an ambiguous reference between 'Microsoft.EntityFrameworkCore.IndexAttribute' and 'System.ComponentModel.DataAnnotations.Schema.IndexAttribute'``` is produced.

This is caused by the index attribute on the newly created classes.
```[Index(nameof(MyColumn), Name = "UC_Unique", IsUnique = true)]```
A fix would be to fully quantify the index attribute as below.
```[Microsoft.EntityFrameworkCore.Index(nameof(MyColumn), Name = "UC_Unique", IsUnique = true)]```

How can I fix this issue?

### Further technical details

EF Core version in use: (e.g. EF Core 6)
                     EF Core 5.0.14
Is Handlebars used: no

EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
              Version 2.5.9.66.0
Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)
      SQL EXPRESS
Visual Studio version: (e.g. Visual Studio 2022)
       Visual Studio 2019

**Comment by ErikEJ** [comment]
Do you have a reference to EntityFramework? (Classic EF)

If so remove or refactor.

**Comment by CodeTile** [comment]
Project is a .net 5 class library with no Classic EF

**Comment by ErikEJ** [comment]
This is related, and refers to EF 6 Classic https://github.com/dotnet/efcore/issues/23532 - can you provide a repro project, then I can have a look?

**Comment by CodeTile** [comment]
When I tried to reproduce in a clean solution, the issue does not occur, either in a clean database with the table [Zeytungsdatum]  or when I point to my database.
I am assuming that this issue is caused by an other nuget package referencing Classic EntityFramework.
