### ISSUE TITLE
The procedure with dynamic queries are not creating model

### ISSUE THREAD

**Issue by hhaider-kmnr** [ErikEJ/EFCorePowerTools#1384]
alter PROCEDURE [dbo].[GetSearchLocation]               
 @keyword as nvarchar(max),              
 @existingCityIds as nvarchar(max) = '',    
 @offset as int = 0,      
 @rows as int = 0      
As              
Begin              
 declare @qry as nvarchar(max);                
 Set @qry = 'with #tblMain as (Select'    

 Set @qry = @qry  + ' ROW_NUMBER()over(order by gcity.id) as rowIndex, gc.id as countryId, gc.name as countryName, gs.id as provinceId, gs.name as provinceName, gcity.id as cityId, gcity.name as cityName From general_cities gcity              
 left outer join general_states gs on gs.id=gcity.state_id              
 left outer join general_countries gc on gc.id=gs.country_id '              
 set @qry = @qry + 'Where (gc.name like ''%' + @keyword + '%'' or gs.name like ''%'+ @keyword + '%'' or gcity.name like ''%'+ @keyword + '%'') '              
 If(Len(@existingCityIds) > 0)                  
 Begin                   
  Set @qry = @qry + 'and gcity.id not in (Select item from SplitString('''+ @existingCityIds + ''', '','')) '                  
 End             
 Set @qry = @qry + ') Select * from #tblMain '    
 if(@rows > 0 )    
 Begin    
  declare @limit as int = @offset + @rows    
  Set @qry = @qry + 'Where rowIndex > '''+convert(nvarchar(10), @offset)+''' and rowIndex <= '''+convert(nvarchar(10), @limit)+''' '             
 End     
 exec (@qry)       
 with Result Sets                              
 (
	(
		rowIndex int,                         
		countryId int,       
		countryName nvarchar(max),       
		provinceId int,       
		provinceName nvarchar(max),       
		cityId int,       
		cityName nvarchar(max)                           
	)
 )                 
End

I was creating this dynamic procedures in sql and when I am using reverse engineering process in ef core power tools it does not create the model it creates int 
![error](https://user-images.githubusercontent.com/78336068/167550411-00e98564-3f06-4edf-b9d2-7d7feeb24697.PNG)

**Comment by hhaider-kmnr** [comment]
please help me as quickly as possible thanks

**Comment by ErikEJ** [comment]
What do I get in return for quick help? 😉

Have you tried switching back to the legacy discovery method as described in the wiki?

**Comment by ErikEJ** [comment]
Ping?

**Comment by ErikEJ** [comment]
Duplicate https://github.com/ErikEJ/EFCorePowerTools/issues/1377#issuecomment-1116005233
