### ISSUE TITLE
Trigger script after reverse engineering?

### ISSUE THREAD

**Issue by AchrWasUnavailable** [ErikEJ/EFCorePowerTools#1385]
Hi, 
Is there a way to trigger a script after reverse engineering is done?

I currently have a few T4 templates which generate repositories, validators, services and controllers based on the reverse engineered models. 
These T4 templates are triggered manually with a bat-file after reverse engineering is done, but I would like to incorporate it into the reverse engineering. I could add a build event, but triggering the T4 templates is not necessary each build and it would only slow down the process.

Many thanks!

**Comment by ErikEJ** [comment]
Ping?

**Comment by ErikEJ** [comment]
Implemented in latest daily, thanks for your suggestion
