### ISSUE TITLE
 OnModelCreatingGeneratedProcedures is not called

### ISSUE THREAD

**Issue by sam-wheat** [ErikEJ/EFCorePowerTools#1388]
Thank you for this awesome tool.

Steps to reproduce:

Use reverse engineering to create the DbContext `(MyDb)`. Include at least one stored proc `(MyDbProcedures)`.

Call a stored proc and get this error:

> System.InvalidOperationException : Cannot create a DbSet for 'pGetPortfolioGroupsResult' because this type is not included in the model for the context.

Turns out `pGetPortfolioGroupsResult` is in fact not a DbSet on the model, which causes this line of generated code to fail:

    var _ = await _context.SqlQueryAsync<pGetPortfolioGroupsResult>("EXEC @returnValue = [OCMPM].[pGetPortfolioGroups] @StrategyIDs", sqlParameters, cancellationToken);
	
Calling code:

	List<pGetPortfolioGroupsResult> result = await Db.Procedures.pGetPortfolioGroupsAsync(ids);

After a bit of digging I found that `OnModelCreatingGeneratedProcedures` that exists in `MyDbProcedures` is not being called.
I created a file in a separate folder from `MyDb` and created a partial class with a partial handler for `OnModelCreating`:

	public partial class MyDb
	{
		
		partial void OnModelCreatingPartial(ModelBuilder modelBuilder)
		{
			OnModelCreatingGeneratedProcedures(modelBuilder);
		}
	}

This appears to have fixed it.  Is there a configuration item for this that I should have used?

Separate observation, unrelated to the above:

I noticed this interface is unused: `public interface IMyDbProceduresContract`.  Most likely intended to be used here: `public partial class MyDbProcedures`?
   
EF Core Version: 6.0.5
Handlebars: No
Power Tools Version:  2.5.918.0
SQL Server: 2019
Visual Studio: 2022 17.2

**Comment by ErikEJ** [comment]
This has changed in the later releases, suggest you try to upgrade and rerun reverse engineering.

**Comment by ErikEJ** [comment]
Ping?

**Comment by ErikEJ** [comment]
Unable to repro with latest version, feel free to re-open if you are able to reproduce
