### ISSUE TITLE
Can't create Oracel DB connection

### ISSUE THREAD

**Issue by mos379** [ErikEJ/EFCorePowerTools#1389]
When adding a custom connection using .NET Framework Data Provider for Oracle
I test the connection and then confirm, the popup closes and the dropdown is still empty.

### Steps to reproduce

ASP.NET Core project, 
.NET 6 
EF Core 6 
Oracle.EntityFramework.Core 6.21.61

### Further technical details

EF Core Power Tools version: 2.5.982.0

Database engine: Oracle 11

Visual Studio version: Visual Studio 2022

**Comment by ErikEJ** [comment]
I think that provider is not supported. Use the Oracle ODP.NET Tools  or a custom connection.

**Comment by mos379** [comment]
in VS 2019 ENT I directly see the database connection in the dropDown

**Comment by ErikEJ** [comment]
Maybe the Oracle VS Tools for VS 2022 are not available yet?

So you are unblocked?

**Comment by mos379** [comment]
YEs VS Tools are not available, thanks for the help, I was able to continue.
