### ISSUE TITLE
Reverse Engineering Not Working

### ISSUE THREAD

**Issue by kenbo017** [ErikEJ/EFCorePowerTools#1391]
Describe what is not working as expected.

I have updated my database and am trying to update my project but it isn't working.  I'm seeing a message at the bottom of VS 2022 Community Edition that says, "An error occurred.  See the "Extensions" Output window for details."  The small little bucket animation at the bottom perpetually shows VS is supposedly doing something but nothing happens and my project never updates.  I can't figure out how to view the "Extensions" output window so I can't see the details.

I'm using EF Core 5

I haven't changed anything and it worked a few weeks ago.  I normally right click and my database is selected so I click through my settings that are already set as they were from before and I click to run it.

### Steps to reproduce

Please include a **complete** description or project that I can redo/run to reproduce the issue.

### Further technical details

EF Core version in use: (e.g. EF Core 6)  

Is Handlebars used: yes/no

EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)

Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)

Visual Studio version: (e.g. Visual Studio 2022)
![Screenshot of EF Core Powertools not Working 5-15-22](https://user-images.githubusercontent.com/32583352/168517074-51f4abd9-af35-4916-b45b-5a697a274d8c.png)

**Comment by kenbo017** [comment]
As a follow-up to my issue.  When I go through the reverse engineering dialogue to the point where it shows the tables to update, I do see all of the tables that I've added/updated so I know it is connecting to the database at that point.

**Comment by ErikEJ** [comment]
Have a look at the Extensions pane in the Output window as the error says:

![image](https://user-images.githubusercontent.com/4169187/168528163-18245706-75b5-416a-b096-1ea943a04fa6.png)

**Comment by kenbo017** [comment]
Hi Erik,

Thank you so much for your quick response.  I was able to find the extensions window and the error message.  I told me I had an issue with my Foreign Key.  I was able to find it and correct it in the database, so all is good again.  🙂

Thanks a ton!


KS


Ken Schneider
Schneider Sales and Marketing
312 West Hillcrest Blvd.
Inglewood, CA 90301
ph: 310-680-9544
cell: 310-722-8827
e-mail: ***@***.******@***.***>


CONFIDENTIALITY NOTICE. This electronic mail transmission may contain privileged, confidential and/or protected information and is intended only for the review of the party to whom it is addressed. Any unauthorized use or disclosure of the information contained herein may be a violation of federal law. If you have received this transmission in error, please immediately return it to the sender, delete it and destroy it without reading it. Unintended transmission shall not constitute the waiver of the attorney-client or any other privilege.


________________________________

**Comment by kenbo017** [comment]
Hi Erik,

I have another question.  Now that the reverse engineering worked, I saw your readme notes:


You need to do some setup for your app after "Reverse Engineer" has created the Entity Model classes and DbContext for you.

Here are some hints:

## ASP.NET Core 6.0

1. Register your data context class in your "Program.cs" file.

    builder.Services.AddSqlServer<KennetixDbContext>(builder.Configuration.GetConnectionString("DefaultConnection"));

2. Add "ConnectionStrings" to your configuration file.

    {
        "ConnectionStrings": {
            "DefaultConnection": "Data Source=KS-PC2\MSSQLSERVER01;Initial Catalog=kennetix5;Integrated Security=True"
        }
    }


My question is that, since moving to Core (, there isn't the normal setup file.  I'm confused as to where I'm supposed to put my connection string.  Below is a screenshot of my solution explorer.  It seems as though this got more complicated in Core.  I'm sure there's a reason but I didn't find anything that explained in detail what and where I'm supposed to put the connection string.  I currently have it in the KennetixDbContext.cs file because it worked from there and I'm just working on the development of my program but I would like to put it where it belongs so it works properly.

[cid:657d2bc6-15f9-4aac-a0ee-ff1c562516dd]

Any help would be much appreciated!

Regards,



KS


Ken Schneider
Schneider Sales and Marketing
312 West Hillcrest Blvd.
Inglewood, CA 90301
ph: 310-680-9544
cell: 310-722-8827
e-mail: ***@***.******@***.***>


CONFIDENTIALITY NOTICE. This electronic mail transmission may contain privileged, confidential and/or protected information and is intended only for the review of the party to whom it is addressed. Any unauthorized use or disclosure of the information contained herein may be a violation of federal law. If you have received this transmission in error, please immediately return it to the sender, delete it and destroy it without reading it. Unintended transmission shall not constitute the waiver of the attorney-client or any other privilege.


________________________________

**Comment by ErikEJ** [comment]
Appsettings.json or Appsettings.Development.json

**Comment by kenbo017** [comment]
Hi Erik,

I had tried the appsettings.json file but it never worked.  When I looked at how to get it setup, there were instructions to do this along with some other things you needed to do so the application looked there for the string, but it never worked.  That's why I put it back into the DbContect.cs file.  Below is a screenshot of what I had in there before that didn't work.  Don't I need to tell the application somewhere (perhaps the Dbcontect.cs file) to look in the appsetting.json file, or somehow that the application that it exists since it isn't there by default when creating an application?  Below you'll see I had created two strings that I wanted to be able to use depending on whether I was working locally or in the cloud.

[cid:686536e8-e535-4c0c-a91a-cc6e326e8392]


KS


Ken Schneider
Schneider Sales and Marketing
312 West Hillcrest Blvd.
Inglewood, CA 90301
ph: 310-680-9544
cell: 310-722-8827
e-mail: ***@***.******@***.***>


CONFIDENTIALITY NOTICE. This electronic mail transmission may contain privileged, confidential and/or protected information and is intended only for the review of the party to whom it is addressed. Any unauthorized use or disclosure of the information contained herein may be a violation of federal law. If you have received this transmission in error, please immediately return it to the sender, delete it and destroy it without reading it. Unintended transmission shall not constitute the waiver of the attorney-client or any other privilege.


________________________________

**Comment by ErikEJ** [comment]
Sorry, I think you need to study some guides fie Blazor apps. And again no screenshot to see.

**Comment by kenbo017** [comment]
Hi Erik,

Sorry!  I don't know why you aren't seeing the screenshot.  I've attached it this time.

I haven't been using Blazor so I'm not sure what you are saying.

Regards,


KS


Ken Schneider
Schneider Sales and Marketing
312 West Hillcrest Blvd.
Inglewood, CA 90301
ph: 310-680-9544
cell: 310-722-8827
e-mail: ***@***.******@***.***>


CONFIDENTIALITY NOTICE. This electronic mail transmission may contain privileged, confidential and/or protected information and is intended only for the review of the party to whom it is addressed. Any unauthorized use or disclosure of the information contained herein may be a violation of federal law. If you have received this transmission in error, please immediately return it to the sender, delete it and destroy it without reading it. Unintended transmission shall not constitute the waiver of the attorney-client or any other privilege.


________________________________
