### ISSUE TITLE
Issue with EF Core 6 Comparison

### ISSUE THREAD

**Issue by mkhalford1304** [ErikEJ/EFCorePowerTools#1392]
I get the following warning when trying to run the Compare dbcontext to database function. As you can see from image I'm using EF Core 6 so am unsure why this is happening.

![image](https://user-images.githubusercontent.com/38039371/168552843-7156cd78-a7c6-47e6-adab-61e403bd9dee.png)

**Comment by ErikEJ** [comment]
Maybe you picked the wrong startup project?

**Comment by mkhalford1304** [comment]
No its a very simple single project solution.

**Comment by ErikEJ** [comment]
Please share your .csproj

**Comment by mkhalford1304** [comment]
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702;8618;8602</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>1701;1702;8618;8602</NoWarn>
  </PropertyGroup>
  
  <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.5">
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        <PrivateAssets>all</PrivateAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.5" />
      <PackageReference Include="Syncfusion.Blazor.Grid" Version="20.1.0.55" />
    <PackageReference Include="Syncfusion.Blazor.TreeGrid" Version="20.1.0.55" />
    <PackageReference Include="Syncfusion.Blazor.Charts" Version="20.1.0.55" />
    <PackageReference Include="Syncfusion.Blazor.TreeMap" Version="20.1.0.55" />
    <PackageReference Include="Syncfusion.Blazor.Sparkline" Version="20.1.0.55" />
    <PackageReference Include="Syncfusion.Blazor.Layouts" Version="20.1.0.55" />
    <PackageReference Include="Syncfusion.Blazor.Navigations" Version="20.1.0.55" />
    <PackageReference Include="Syncfusion.Blazor.SplitButtons" Version="20.1.0.55" />
    <PackageReference Include="Syncfusion.Blazor.Spinner" Version="20.1.0.55" />
    <PackageReference Include="Syncfusion.Blazor.DropDowns" Version="20.1.0.55" />
    <PackageReference Include="Syncfusion.Blazor.Notifications" Version="20.1.0.55" />
    <PackageReference Include="Syncfusion.Blazor.Themes" Version="20.1.0.55" />
    <PackageReference Include="Syncfusion.Licensing" Version="20.1.0.55" />
  </ItemGroup>
  
  <ItemGroup>
    <Folder Include="Data\" />
  </ItemGroup>
  

</Project>

**Comment by ErikEJ** [comment]
You need to format the XML as code

**Comment by mkhalford1304** [comment]
Apologies
``` xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702;8618;8602</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>1701;1702;8618;8602</NoWarn>
  </PropertyGroup>
  
  <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.5">
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        <PrivateAssets>all</PrivateAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.5" />
      <PackageReference Include="Syncfusion.Blazor.Grid" Version="20.1.0.55" />
    <PackageReference Include="Syncfusion.Blazor.TreeGrid" Version="20.1.0.55" />
    <PackageReference Include="Syncfusion.Blazor.Charts" Version="20.1.0.55" />
    <PackageReference Include="Syncfusion.Blazor.TreeMap" Version="20.1.0.55" />
    <PackageReference Include="Syncfusion.Blazor.Sparkline" Version="20.1.0.55" />
    <PackageReference Include="Syncfusion.Blazor.Layouts" Version="20.1.0.55" />
    <PackageReference Include="Syncfusion.Blazor.Navigations" Version="20.1.0.55" />
    <PackageReference Include="Syncfusion.Blazor.SplitButtons" Version="20.1.0.55" />
    <PackageReference Include="Syncfusion.Blazor.Spinner" Version="20.1.0.55" />
    <PackageReference Include="Syncfusion.Blazor.DropDowns" Version="20.1.0.55" />
    <PackageReference Include="Syncfusion.Blazor.Notifications" Version="20.1.0.55" />
    <PackageReference Include="Syncfusion.Blazor.Themes" Version="20.1.0.55" />
    <PackageReference Include="Syncfusion.Licensing" Version="20.1.0.55" />
  </ItemGroup>
  
  <ItemGroup>
    <Folder Include="Data\" />
  </ItemGroup>
  

</Project>
```

**Comment by ErikEJ** [comment]
I was able to repro. Looking into a fix

**Comment by ErikEJ** [comment]
Fixed in latest daily build - guess no one uses this feature !?

**Comment by mkhalford1304** [comment]
Great. How do I get hold of the fixed version?

**Comment by ErikEJ** [comment]
Download and install the latest daily build as described in the readme
