### ISSUE TITLE
Ability to specify SProc Interface generation location

### ISSUE THREAD

**Issue by WillClayworth** [ErikEJ/EFCorePowerTools#1393]
When importing a Stored Procedure an Interface is created for the imported Stored Procedures. 

There seems to be no options on where to place the generated interface and it will always gets placed alongside the generated implementation.

It would be nice if there was some level of customisation on this so it can be placed in a separate file & away from the implementation.

**Comment by ErikEJ** [comment]
Feel free to copy and paste it. 

What do you use it for?

**Comment by Pete-Halls** [comment]
I'm working with Will....

Our Interfaces for teh Dbcontexts are actually in a different project. We can't add a reference to the Interface if it is in it's current location as it would create a circular reference

**Comment by ErikEJ** [comment]
I will generate a separate file.

You can then use a post run cmd to Move it

**Comment by ErikEJ** [comment]
Fixed in latest daily
