### ISSUE TITLE
Reuse for Stored And Possibility to decide not to include Navigation Properties between classes And Defining Inheritance

### ISSUE THREAD

**Issue by flencinas** [ErikEJ/EFCorePowerTools#1394]
Great tool but I miss
* Type Reuse for Stored
* Possibility to decide not to include Navigation Properties between classes
* Defining Inheritance

I miss the Entity Framework Designer that allowed all these possibilities for Database First or Reverse Engineering

**Comment by flencinas** [comment]
I was looking at the Handlebars and I have downloaded the code templates for c# (I personally find them very complex)
This is my question how to determine if the prefix or postfix substring of a property name is equal to XX

{{#if property-property-name == "XX" }}
   {{property-property-nameXX}}
{{else}}
   {{property-property-name}}
{{/if}}

Going to the topic of Stored Procedures, it is about those SP that return class types that are already part of the domain
That is, you don't have to create new types for each return of a Stored

For example I have a View called CustomerView

And a Stored called GetCustomerViewByFilter that returns a select from CustomerView currently creates a new type for you and does not allow you to define a specific type as Entity Designer did before

Thnk's

**Comment by ErikEJ** [comment]
>> This is my question how to determine if the prefix or postfix substring of a property name is equal to XX

How does that relate to inheritance?

The "map stored procedure result to an existing type" idea sounds good.

**Comment by flencinas** [comment]
The prefix or postfix is useful when you want to write custom or special Attributes to the code generated 

That's why I ask about the possibility of writing code in the handle bars of the type if (....) some code else other code 

And the "map stored procedure result to an existing type" it's very usefull to reduce and reuse the view and tables in the application domain 

Thnks

**Comment by ErikEJ** [comment]
Could you give an example of the Custom code / special attribute? 

You can always extend the classes as they are partial.

**Comment by ErikEJ** [comment]
I have created #1395

**Comment by flencinas** [comment]
> 

For example a Computed or Custom Attribute for use with DataAnnotations attributes

In the case of attributes, partial classes are not a solution.

**Comment by ErikEJ** [comment]
You can use Metadata buddy class with attribute.

**Comment by flencinas** [comment]
Hello ErikEJ
I see the article about the navigation properties, but the variable "UseNoNavigations": false, is used for all 

But I mean to remove the navigation properties in certain classes or in those classes that have the prefix or suffix POCO in their name

In this way EF Power Tools could deduce in which classes to define navigation properties and in which not, rather than doing it at a global level 

Rgds

**Comment by ErikEJ** [comment]
That is not something I plan to implement and support
