### ISSUE TITLE
Map stored procedure results to existing types 

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#1395]
This feature is about the ability to map a stored procedure result to any existing class, instead of the generated XxxResult class.

This can be an existing entity (keyless or not), or any other class where the shape matches the result set exactly.

Example:

```
{
    "Name": "[dbo].[MultiSet]",
    "ObjectType": 1,
    "MappedType": "MyOtherType"
},

```
From #1394 

Going to the topic of Stored Procedures, it is about those SP that return class types that are already part of the domain
That is, you don't have to create new types for each return of a Stored

For example I have a View called CustomerView

And a Stored called GetCustomerViewByFilter that returns a select from CustomerView currently creates a new type for you and does not allow you to define a specific type as Entity Designer did before

**Comment by ErikEJ** [comment]
Will implement for existing entities for now

**Comment by ErikEJ** [comment]
@flencinas @jerone @raman-kazhadub This has now been added to the latest daily, would be grateful if you could give it a try.

**Comment by raman-kazhadub** [comment]
> @flencinas @jerone @raman-kazhadub This has now been added to the latest daily, would be grateful if you could give it a try.

Hi, I have checked, mapped type works, but EFPT still generates result class that not used anymore. Is it expected?

**Comment by ErikEJ** [comment]
@raman-kazhadub 

>>  Is it expected?

In the current preview yes.
