### ISSUE TITLE
Reverse engineer tables that include a namespace and the optional entity Types path

### ISSUE THREAD

**Issue by wobblybob** [ErikEJ/EFCorePowerTools#1397]
Describe what is not working as expected.
When reverse engineer tables that include a namespace and the optional path (folder), it's tagging the folder name onto the namespace. If I wanted that I could put it on my original namespace, or add it to the sub-namespace. I just want these files generated into a specific folder in my project.

Reverse Engineer using DB Connection, Filter Schemas Not Checked, EF Core 6
Select Tables, Click Ok
Input the Namespace
Input an EntityTypes Path (folder name)
What to Generate: EntityTypes Only
Pluralize Object names checked
Everything else defaults.

When generating the entities for tables, it's tagging the EntityTypes Path onto the namespace. Is this supposed to work like that? I just want my entities saved in a folder with the namespace I entered in the "Namespace" input area. 

EF Core version in use: EF Core 6

Is Handlebars used: No

EF Core Power Tools version: 2.5.966.0

Database engine: Sql Server

Visual Studio version: Visual Studio 2022 Community

**Comment by ErikEJ** [comment]
Please provide a screenshot  so I can provide a  solution.

**Comment by ErikEJ** [comment]
Ping?

**Comment by wobblybob** [comment]
Sorry, I was out of pocket for a couple days, here's the screenshot of my interface
![2022-05-19_16-43-34](https://user-images.githubusercontent.com/5335407/169401435-a3fc47b5-d2e4-4e02-a660-839a60f3f283.png)

**Comment by ErikEJ** [comment]
You can do this to get your desired outcome:

![image](https://user-images.githubusercontent.com/4169187/169483192-fd162d5b-baae-4fca-bafe-25e885c2e73c.png)

**Comment by wobblybob** [comment]
That did work for my Entities. Maybe I don't understand differences between types during generation. 

When selecting "EntityTypes Only" under 'what to generate' it removes my entities for stored procedures? Those seem to be linked to the DbContext generation not the entity types generation. Is that correct?

I'm asking because I have my entity models in one project, but my dbcontext in another project.

**Comment by ErikEJ** [comment]
@wobblybob I am confused - I was basing my help to you on the screenshot you shared - are you saying now that it  does not reflect what you want to do? In that case, you must share what you ACTUALLY want to happen - otherwise how can I help you?

 >> When selecting "EntityTypes Only" under 'what to generate' it removes my entities for stored procedures? Those seem to be linked to the DbContext generation not the entity types generation. Is that correct?
 
 "removes" ? - seems like a duplicate of #1300
