### ISSUE TITLE
investigate possibility for custom naming of dbset, classes and properties

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#14]
_From @ErikEJ on February 22, 2018 9:10_

https://github.com/aspnet/EntityFrameworkCore/blob/dev/src/EFCore.Design/Scaffolding/Internal/RelationalScaffoldingModelFactory.cs 

https://github.com/aspnet/EntityFrameworkCore/issues/11056#issuecomment-368256127

- [x] Get PR for ICandidateNamingService accepted
- [ ] Add support for efpt.renaming.json (drop empty, commented out sample in project, in there is none)
- [ ] add class for renames ColumnRenamer: Table, Old, New & TableRenamer: Old, New
- [ ] Override ICandiadteNamingService, and rename based on json file

_Copied from original issue: ErikEJ/SqlCeToolbox#640_

**Comment by ErikEJ** [comment]
_From @jonreis on March 14, 2018 19:41_

Erik, I really like your Reverse Engineering tool with Handlebars. Great work. Adding these items will be fantastic.

Do think you could add to the list specifying the datatype of the property also? As you know the generated code for Sqlite does not always reflect the datatypes the user wants to use.

**Comment by ErikEJ** [comment]
@jonreis I can, but it is outside the scope of this particular feature, due to the way EF Core reverse engineering is designed.

**Comment by ErikEJ** [comment]
_From @jonreis on March 14, 2018 19:58_

I guess I should download the code and see how everything works before I log requests. It seemed you would be able to change the type while you were renaming the property.

Thanks Erik.

**Comment by ErikEJ** [comment]
No, I just thin you should log this as a seperate issue, the fix for that will no be possible via this feature/fix.

**Comment by ErikEJ** [comment]
_From @statler on April 11, 2018 4:33_

Hi Erik

Any thoughts on when this may be available? Specifically the column renaming

**Comment by ErikEJ** [comment]
@statler  Around the release of 2.1 (was waiting for changes in EF Core, which are now available in in preview-2) - what database provider do you use?

**Comment by ErikEJ** [comment]
_From @statler on April 11, 2018 22:12_

Yes - I followed your links through and saw the commits - do you have a [non release] EFPT commit with the renaming in it, or still a work in progress?

I use full SQL server

**Comment by ErikEJ** [comment]
Not yet, I need preview2, which was just released...

**Comment by ErikEJ** [comment]
_From @OmiCron07 on May 7, 2018 21:40_

Do you have a build now with this feature?

**Comment by ErikEJ** [comment]
Not yet, have been to busy with EF Core provider and my day job

**Comment by statler** [comment]
Just following up on your comment from my review. What I am looking for in this feature is at the more basic end of the scale, essentially I want to be able to configure certain columns, tables and constraints to have specific property names when the reverse engineer occurs. At the moment I do what I can with my DTOs to publish an API which makes sense and can be documented, but I still run into issues with my controllers and their property names on post and put requiring additional work. 

For example, I have a table in the DB which is called WorkType with columns WorkTypeID, WorkType and Description - all of my tables also have some admin columns ModifiedOn, ModifiedBy, UniqueId, HRId, CreatedOn, CreatedBy which I omit with DTOs. Anyway, firstly this obviously causes issues with the WorkType property having the same name as the WorkType object created from the table, so it is renamed WorkType1 when the generation happens. I map the WorkType1 to WorkTypeName with a DTO (which also omits the admin columns). This is then used to deliver all GET responses. I also need to rename to bring column names into alignment with my variable naming policy.

When updates come back in to the api through PUT and POST, they are of course using the DTO - so I now have to process everything that comes back in a put and post as well to translate DTO back to the original model. Everything is in JSON so this would not be necessary if I had a consistent naming across the model and DTO. 

I have a heap of this across the project - at least 40 tables need modification in some way. I have to modify every DTO when I could just automap if the columns were the same. Then as discussed, there is the put/post.

I regenerate the model regularly as the database schema is managed elsewhere and changes need to be reflected in the API, so just updating it after the model generation is not an option as I would have to do it every time.

Hopefully that is clear enough - please let me know if there are any questions - essentially I just need a config JSON something like;

	{
	  "WorkType": {
		"Columns":{
		  "WorkType":"WorkTypeName"
		}
	  },
	  "ATPLot": {
		"Name":"AtpLot",
		"Columns":{
		  "ATPLotID":"AtpLotId"
		}
		"Constraints":{
		  "FK_ATPLot_ApprovedBy","ApprovedByUser"
		}
	  }
	}

**Comment by statler** [comment]
Hi Erik;

Any news on when you may get a chance to do this one? Not hassling, just trying to plan a few things - I understand this ain't the bread winner :)

Cheers
D

**Comment by ErikEJ** [comment]
Given that only 2 users have expressed interest in this, it is on my list, but not high up. Right now I am trying to get a release that works with EF Core 2.1.x out.

**Comment by statler** [comment]
Thanks for the update. Will use shadow properties for now.

**Comment by tomzre** [comment]
@ErikEJ  As I started trying to working on it. Do you think  entire `ICandidateNamingService` interface should be overwritten or the specific method can be overwritten? I found the way to manipulate the names as injecting Extended class `CandidateNamingService ` to the pipe but I don't know is it good way?

**Comment by ErikEJ** [comment]
Yes, override the Interface, and implement a "ReplacingCandidateNamingService" - just call the base implementation for the methods that do not need  overwritten.

You replace the existing interface based on the existence of the json file similar to this:

https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/ReverseEngineer20/EFCoreReverseEngineer.cs#L69

**Comment by tomzre** [comment]
I ended with something like this:

```[
  {
    "UseSchemaName": true,
    "SchemaName": "Work",
    "Tables": [
      {
        "OldTableName": "to_do_list",
        "Columns": [
          {
            "OldColumnName": "list_to_be_done",
            "NewColumnName": "what_ever"
          },
          {
            "OldColumnName": "columnOldName1",
            "NewColumnName": "columnNewName1"
          }
        ]
      }
    ]
  },
  {
    "UseSchemaName": true,
    "SchemaName": "master",
    "Tables": [
      {
        "OldTableName": "to_do_list",
        "Columns": [
          {
            "OldColumnName": "old_name",
            "NewColumnName": "new_name"
          },
          {
            "OldColumnName": "columnOldName1",
            "NewColumnName": "columnNewName1"
          }
        ]
      }
    ]
  }
]
```
As we discussed renaming should be done only if this file is present. I use `UseSchemaName` flag to indicate wheter tables in schema should be Renamed to `SchemaNameTableName`. If this flag is true NewName from abobe json never gonna be used. 
And for columns only custom names should work.

**Comment by tomzre** [comment]
Sorry I forgot about this field in json (already updated). I think the naming convention that u said is more readable. 
I think we need to match column for specific table in schema. Please tell if I am wrong.

**Comment by ErikEJ** [comment]
Yes, that is basically correct. 

I also propose: 

OldColumnName => Name

NewColumnName => NewName

**Comment by tomzre** [comment]
I submitted PR. Please review. There is one problem with inverse property name when generating table names with schemas, schema name in property is skipped. I found a way to use  extension method from EF core repo to get a short name but didn't test it a lot yet.

**Comment by stormrover** [comment]
Probably myself just being a n00b, but I'm unable to find where to place the json with the configurations.

**Comment by ErikEJ** [comment]
In the project with your dbcontext

**Comment by stormrover** [comment]
Thanks for your reply.

I was missing the «var renamingPath = Path.Combine(projectPath, "efpt.renaming.json");» on ReverseEngineerHandler.cs

**Comment by ErikEJ** [comment]
@stormrover The feature is way too secret at the moment, I am considering a checkbox like:

"Add support for Entity and Property renaming (beta)" 

which should add a sample efpt.renaming.json file to the project (if it does not already exist)
