### ISSUE TITLE
Map Geometry type in stored procedures parameter

### ISSUE THREAD

**Issue by Dimigergo** [ErikEJ/EFCorePowerTools#1400]
It is different from the function parameter like #1399, because in this case the parameter should have to be byte[], because the SqlServer SqlDbType.Udt enumeration does not have NTS, and throws Exception. It is only in the stored procedures!!!

![error2](https://user-images.githubusercontent.com/11498949/169847033-d67a3f7b-36df-47bb-a32b-d911a1d7a40c.png)

The corrent parameter: byte[] pPolygon
![error2_ok](https://user-images.githubusercontent.com/11498949/169847866-cc202edb-c0e7-45b7-9a58-e3aac30f1cb5.png)

**Comment by Dimigergo** [comment]
Yes, but only in the stored provedures, because of the SqlParameter SqlDbType enum. :)

**Comment by ErikEJ** [comment]
What if the SqlParameter SqlDbType was different? And what other value should it have in that case?

**Comment by Dimigergo** [comment]
Sorry, I forgot to copy.

```
Specified type is not registered on the target server. NetTopologySuite.Geometries.Polygon, NetTopologySuite, Version=2.0.0.0, Culture=neutral, PublicKeyToken=f580a05016ebada1.
```

![error3](https://user-images.githubusercontent.com/11498949/169867789-b36fbd75-92f6-466d-b74e-1fc7e157a572.png)

**Comment by Dimigergo** [comment]
Please be careful, because this sp function is in the interface at the top of the generated file!

**Comment by ErikEJ** [comment]
I will  - luckily generated in the same class.
