### ISSUE TITLE
Unable to map stored procedure with dynamic pivot columns

### ISSUE THREAD

**Issue by hayronruiz** [ErikEJ/EFCorePowerTools#1402]
I'm trying to map a stored procedure via reverse engineer, the stored procedure returns dynamic pivot columns and i'm getting the following error:

_Unable to get result set shape for PROCEDURE 'dbo.GetData'
The metadata could not be determined because statement 'EXEC sp_executesql  @sql
                    ,@ParmDefinition
                    ,@idData in procedure 'GetData'  contains dynamic SQL.  Consider using the WITH RESULT SETS clause to explicitly describe the result set._

**Microsoft.EntityFrameworkCore v5.0.12**

EF Core Power Tools version: **2.5.877**

Database engine: **SQL Server**

Visual Studio **2019**

**Comment by ErikEJ** [comment]
Have you tried the legacy discovery? 

https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#sql-server-stored-procedures

**Comment by hayronruiz** [comment]
I can't use **UseLegacyResultSetDiscovery** propertie because the class GetDataResult isn't generated at efpt.config.json. Can i add it manually.

Also, i think is important to note that the stored procedure returns an 

`EXEC sp_executesql  @sql
				    ,@ParmDefinition
				    ,@idData`

**Comment by ErikEJ** [comment]
Did you try this (as mentioned above) ??

```json
{
    "Name": "[dbo].[GetData]",
    "ObjectType": 1,
    "UseLegacyResultSetDiscovery": true
},
```

**Comment by ErikEJ** [comment]
Then you have created a stored procedure where no result set shape can be discovered.

If you know the expected result set you can define it ypurself in a partial GetDataResult class.

**Comment by hayronruiz** [comment]
That's the point, my stored procedure returns dynamic columns since i'm using dynamic pivoting and the result set gets from:

`EXEC sp_executesql @sql ,@ParmDefinition ,@idDat`

I can't use the WITH RESULTS SET clause because i don't know the exact result set returned until execution.

**Comment by ErikEJ** [comment]
Sounds like there is no way of doing this in a strongly typed way then !?

**Comment by hayronruiz** [comment]
I had to apply a different approach:

https://entityframeworkcore.com/knowledge-base/53041769/ef-core-query-stored-procedure-map-to-types

**Comment by ErikEJ** [comment]
Good Luck with that
