### ISSUE TITLE
Reverse Engineer User-Defined types?

### ISSUE THREAD

**Issue by sam-wheat** [ErikEJ/EFCorePowerTools#1404]
I have to think someone has asked abut this before - I did search for this several ways and found nothing:

> user-defined data types site:https://github.com/ErikEJ/EFCorePowerTools/issues

Is it possible that Power Tools can reverse engineer and use User-Defined table types?

I imagine the process would look something like this:
User selects User-Defined Table Types to be reverse engineered.  
If user is reverse engineering  views, stored procs, or functions - Power Tools will check if the shape of the result object matches the shape of a user-defined table type.  If yes, that user-defined type will be used.  If no a type will be generated and named the way it works now.

**Comment by ErikEJ** [comment]
I think I need an example to understand this.

The tool supports Table valued functions

Is this related to #1395 ?

**Comment by sam-wheat** [comment]
Yes this is the same as https://github.com/ErikEJ/EFCorePowerTools/issues/1395 however the language in that ticket is not really specific.

>  those SP that return class types that are already part of the domain

I also am referring to class types that are already part of the domain but more specifically they are defined as User-Defined Table Types.

Also I suggest those types be checked agains views and functions as well as stored procs.  There may be some kind of hierarchy but it is beyond me to figure out how that might be used.  For example if a SP calls a function and returns it's result should only one type be created?  Probably.

**Comment by ErikEJ** [comment]
As I said, I need a full example to understand your suggestion.

**Comment by sam-wheat** [comment]
Will a use case example be sufficient? If no, please describe the desired format.

**Comment by ErikEJ** [comment]
A simple console app or unit test, please.

**Comment by sam-wheat** [comment]
Not really sure what to include in the sample app hopefully what I provided is at least a starting point.  More specific use case:

**Motivation:** To reduce the number of objects created by the reverse engineering process by consolidating them based on identical properties

**General workflow:**  The reverse engineering process will work as it does today however a new option will appear on the “Choose Database Objects” dialog that will allow the user to select User-Defined Table Types.  When the process is run, entities will be compared using the process described below to prevent redundant objects from being created.

**Entity Comparison:** Entities will be considered identical if they have the same number of properties and each property has an identical name, data type, and nullability.  The order of properties will not be considered.

**De-duping:** When the scaffolding process is run it will check for duplicate entities in the order shown (this may also be user-defined) :
Tables
User-Defined Table Types
Views
Table-valued Functions
Stored Procedures



**Example:**
A User-Defined Table Type called `CommentPreview` exists with the following structure 

    ID:int,not null
    Comment:varchar, not null


A stored procedure named `pGetComments` exits.  It takes no parameters and returns a table with a structure matching `CommentPreview`.
The following signature will be created in the generated `DbProcedures` class:
`public virtual async Task<List<CommentPreview>> pGetComments() {…}`

[ScaffoldingExample.zip](https://github.com/ErikEJ/EFCorePowerTools/files/8789368/ScaffoldingExample.zip)

**Comment by ErikEJ** [comment]
Thanks for the example. I do not see any usage of the CommentPreview class in the sample ??

As I understand, UDDTs are used for passing data to TVP, for example in a function or stored procedure.

Currently these are mapped to a DataTable. Passing them as a plain `IEnumerable<T>` is [not possible](https://www.sommarskog.se/arrays-in-sql-2008.html#ADONET)

Let's start with #1395 and take it from there.

**Comment by sam-wheat** [comment]
Thanks for looking at this Erik.  Actually, my reason for asking for UDDT's to be considered is more for naming than anything else.
This ticket really is the same as https://github.com/ErikEJ/EFCorePowerTools/issues/1395.  When developing that code you are eventually going to run into the problem of "Which name do I use?".  This ticket gives you a good place to look for a name (UDDTs) and provides a consistent way of choosing a name when you have multiple choices.

Consider an example where we have two stored procs named `pGetActiveCustomersByTerritory` and `pGetActiveCustomersByLastPurchaseDate`.  The shape of the result of both of these SP's is identical.  When de-duping, which name do you use?  Both of them are pretty awful:  `pGetActiveCustomersByTerritoryResult` or  `pGetActiveCustomersByLastPurchaseDateResult`.  Yuk.  

But what if we have a UDDT called `ActiveCustomer` and it has a shape identical to the result of both SPs.  When de-duping, if you look at that object first (per the order described above) you will know immediately to use its name as the name of the result object for the SPs.

**Comment by ErikEJ** [comment]
>> When developing that code you are eventually going to run into the problem of "Which name do I use?". 

Actually no, the user specifies the class (could be an existing EF Core entity or any other known class) to map to manually, no "magic" involved.

I repeat: UDDTs are used for passing data to TVP, for example in a function or stored procedure.

**Comment by sam-wheat** [comment]
> the user specifies the class

Sorry, I do not see that in https://github.com/ErikEJ/EFCorePowerTools/issues/1395 or https://github.com/ErikEJ/EFCorePowerTools/issues/1394.  Can you point me to where that is mentioned?

> I repeat: UDDTs are used for passing data to TVP, for example in a function or stored procedure.

Yes of course they are but they are useful for other things also if you choose to think about them in other ways.

**Comment by ErikEJ** [comment]
Possibly not clear unless you link back to the original discussion.

Still waiting for an example of using a UDDT from C# in "other ways"...

**Comment by ErikEJ** [comment]
I have updated #1395 - please have a look

**Comment by sam-wheat** [comment]
> I have updated https://github.com/ErikEJ/EFCorePowerTools/issues/1395 - please have a look

Sorry - I still don't understand how it will work.  Will the UI prompt the user to input a type name when a SP or function is selected for inclusion the model?

> Still waiting for an example

There is no example because there is no code.  That is what this ticket is about.  The "other way" is to use the name of UDDT as the name of an entity as mentioned above.

**Comment by ErikEJ** [comment]
UI prompt - maybe later, initially manual edit of efpt.config.json

**Comment by leaderanalytics** [comment]
I like this approach much more - it was (is) not clear in the prior tickets that this is the route you are taking.
I still hold that UDDTs are essential here - don't be mad at me lol.

**Comment by ErikEJ** [comment]
Not mad at all!! It would just be great with a code based example : smile:

**Comment by ErikEJ** [comment]
Putting this on hold until #1441 has been implemented ad field tested.
