### ISSUE TITLE
Strange capitalization issue

### ISSUE THREAD

**Issue by caiuaqui** [ErikEJ/EFCorePowerTools#1405]
First of all, thanks for the software.

However I'm having a strange issue when generating the code for a Database First project:

**DB**
```
CREATE TABLE [dbo].[Menu](
 ....
[DataAlteracao] [datetime] NOT NULL,
[UtilizadorAlteracao] [varchar](30) NOT NULL,
[IPAlteracao] [varchar](30) NOT NULL,
 CONSTRAINT [PK_Menu] PRIMARY KEY CLUSTERED 
```
**Generated Code**
```
[Required]
[StringLength(30)]
public string UtilizadorAlteracao { get; set; }

[Required]
[Column("IPAlteracao")]
[StringLength(30)]
public string Ipalteracao { get; set; }
```

I'm not using the `Use table and column names directly from database...` because I specifically want to plurarize the tables myself and using the option  `Use table and column names directly from database...` does not allow renaming tables or columns.
The field "UtilizadorAlteracao" is converted correctly from the database, however the field IPAlteracao is not.
Any reason for this?

These are the options used to generate the code.
![image](https://user-images.githubusercontent.com/6917622/170738979-c0401d03-2f4f-441a-99ec-aa426e79e1bf.png)
![image](https://user-images.githubusercontent.com/6917622/170739333-9782caf2-a03e-4121-8539-8070ca4832e3.png)

Technical Details:
EF Core version in use: EF Core 5
Is Handlebars used: no
EF Core Power Tools version: 2.5.982
Database engine: SQL Server
Visual Studio version: Visual Studio 2019

**Comment by ErikEJ** [comment]
The names are C#-ified. 

Maybe you can use the renaming feature to preserve the case.

**Comment by caiuaqui** [comment]
I just tested the renaming option and honestly it's still a weird case.

Using the UI option to rename, the name shows correctly.

![image](https://user-images.githubusercontent.com/6917622/170744011-917f606b-f8be-41a7-ab4b-4156dbc225e7.png)

Then, in the `efpt.renaming.json`, I have to "force" the correct name to work
```
{
  "Columns": [
     {
        "Name": "IPAlteracao",
        "NewName": "IPAlteracao"
     }
  ],
  "Name": "SilexMenu",
  "NewName": "SilexMenus"
},
```
And, to be honest, since these fields are present in almost all of the tables, it's kinda a laborious task to define FOR ALL OF THEM.

One other question, I could probably use the `Use table and column names directly from database...`. Is there any way to allow table renaming even using the earlier option?

**Comment by ErikEJ** [comment]
You can use a regex for bulk renaming.

**Comment by MisinformedDNA** [comment]
@ErikEJ This is a huge breaking change for us. Suddenly tons of our classes and properties are different than they once were. Our table regex is:

```json
      "TablePatternReplaceWith": "$1",
      "TableRegexPattern": "^[t|v|f|a]_(.+)",
```

So, table `t_ABBRName` was being renamed to `ABBRName`, but now it is suddenly being renamed to `Abbrname`. I'm not sure why we are first seeing this now, but something has clearly changed.

**Comment by MisinformedDNA** [comment]
@ErikEJ OK, I'll test it out.

**Comment by MisinformedDNA** [comment]
It works. Thank you!
