### ISSUE TITLE
Temporal Table: Cannot convert lambda expression to type 'string' because it is not a delegate type 

### ISSUE THREAD

**Issue by PureConsulting** [ErikEJ/EFCorePowerTools#1408]
Describe what is not working as expected.

### Provide steps to reproduce
1. Create a temporal table with ValidFrom and ValidTo columns

Please include a **complete** description or project that I can redo/run to reproduce the issue.
Reverse engineering a SQL Server temporal table and getting the following error:
Cannot convert lambda expression to type 'string' because it is not a delegate type 

### Provide technical details

- EF Core version in use: (e.g. EF Core 6)
- EF Core 6.03

- Is Handlebars used: no/yes

- Is .dacpac used: no/yes
- no

- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
2.5.982

- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)
- Azure SQL

- Visual Studio version: (e.g. Visual Studio 2022)
- VS 2022 17.2

            modelBuilder.Entity<Reservation>(entity =>
            {
                entity.ToTable(tb => tb.IsTemporal(ttb =>
                {
                    ttb.UseHistoryTable("ReservationHistory", "dbo");
                    ttb.HasPeriodStart("ValidFrom").HasColumnName("ValidFrom");
                    ttb.HasPeriodEnd("ValidTo").HasColumnName("ValidTo");
                }
            ));

**Comment by ErikEJ** [comment]
Please share the full stack trace and a full repro.

**Comment by PureConsulting** [comment]
Stack trace of what?  It won't compile.

**Comment by ErikEJ** [comment]
Full repro then...

**Comment by ErikEJ** [comment]
Or at least your .csproj

**Comment by ErikEJ** [comment]
Ping?

**Comment by PureConsulting** [comment]
We are on holiday in the USA so I will get it to you tomorrow.

**Comment by ErikEJ** [comment]
You are mixing EF Core versions I guess, like you did last time :smile: #477

**Comment by PureConsulting** [comment]
Yep, you're right.  Sorry.  That seems like it would be an easy check.

**Comment by ErikEJ** [comment]
>> Easy check

Possibly. If many users were affected I would consider it.
