### ISSUE TITLE
MySQL Bit(1) not null being mapped to ulong

### ISSUE THREAD

**Issue by sufyannisar** [ErikEJ/EFCorePowerTools#1410]
When reverse engineering MySQL table with a BIT(1) Data type column, it gets scaffolded to ulong in class.

### Steps to reproduce

1. A table in MySQL that has a column with BIT(1) data type and default value of b'0'
1. Reverse Engineer it in EF Core 5.

Here is my table script in MySQL:
> CREATE TABLE 'merchants' (
>   'Id' char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT 'uuid()',
>   'Name' varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
>   'MerchantAccountNumber' varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
>   'MobileNumber' varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
>  
>   -- This is the probleming field
>   'IsMerchantRegistered' bit(1) NOT NULL DEFAULT b'0',
>   
>   'MerchantToken' varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
>   'MerchantReferenceId' varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
>   'ExternalMerchantReferenceId' varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
>   'Source' varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
>   'Status' varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
>   'CreatedAt' timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
>   'UpdatedAt' timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
>   PRIMARY KEY ('Id')
> ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

Here is the Generated c# class:

> [Table("merchants")]
> public partial class Merchant
> {
> 	[Key]
> 	public Guid Id { get; set; }
> 	[StringLength(100)]
> 	public string Name { get; set; }
> 	[StringLength(100)]
> 	public string MerchantAccountNumber { get; set; }
> 	[StringLength(100)]
> 	public string MobileNumber { get; set; }
> 	[Column(TypeName = "bit(1)")]
> 	public ulong IsMerchantRegistered { get; set; }
> 	[StringLength(100)]
> 	public string MerchantToken { get; set; }
> 	[StringLength(100)]
> 	public string MerchantReferenceId { get; set; }
> 	[StringLength(100)]
> 	public string ExternalMerchantReferenceId { get; set; }
> 	[StringLength(100)]
> 	public string Source { get; set; }
> 	[StringLength(100)]
> 	public string Status { get; set; }
> 	[Column(TypeName = "timestamp")]
> 	public DateTime CreatedAt { get; set; }
> 	[Column(TypeName = "timestamp")]
> 	public DateTime UpdatedAt { get; set; }
> }

### Technical details

- EF Core version in use: EF Core 5

- Is Handlebars used: No

- Is .dacpac used: No

- EF Core Power Tools version:  2.5.982.0

- MySQL 8.0.29

- Visual Studio 2022

![image](https://user-images.githubusercontent.com/11299649/171101381-c496a5d6-216d-497a-83cc-495ed2c1f811.png)

![image](https://user-images.githubusercontent.com/11299649/171101421-1a29553a-975e-492b-b796-7e032630b7d5.png)

**Comment by ErikEJ** [comment]
I think it is by design - @lauxjpn ?

**Comment by sufyannisar** [comment]
I don't think so, when I scaffold the same database in [LinkPad](https://www.linqpad.net/), I get BIT(1) column mapped as Bool in the model.
![image](https://user-images.githubusercontent.com/11299649/171169129-20cd1a5a-6cbc-4efb-8e56-f25ae887e81a.png)
![image](https://user-images.githubusercontent.com/11299649/171169085-79ab093b-da76-43ab-8206-e928041fce60.png)

**Comment by ErikEJ** [comment]
@lauxjpn Thanks for the explanation!
