### ISSUE TITLE
How do I reverse engineer a single table without touching any other previously generated entities?

### ISSUE THREAD

**Issue by Tony20221** [ErikEJ/EFCorePowerTools#1412]
How do I reverse engineer a single table and leave everything else alone? If I unselect everything and select the modified table, the tool sets Visual Studio to delete all the previously generated entities. Even if I don't make any selection, the result is still deleted entities.

I don't want the tool to do anything extra for me. I just want the tool to modify the corresponding entity for the modified table. I don't want it to replicate all the tables into entities if I didn't select them.

**Comment by ErikEJ** [comment]
There are various options as [described in the wiki](https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#saving-options-and-running-the-second-time) 

>> Even if I don't make any selection, the result is still deleted entities.

How - unless some tables are removed from the source dtabase?

**Comment by Tony20221** [comment]
The wiki just says in order to delete unselect in the tool and to add/update select in the tool. 
Where's the option to ignore tables I don't want it to do anything for them? Don't delete, don't add, don't update theie entities.

Yes it's trying to delete an entity whose table doesn't exist. I don't want it to touch the entity. 
Reverse engineering should be one way operation.  Tables to entities. Why is it looking at the entities and tries to delete the ones that don't have corresponding tables? Is there a setting to disable this feature? Maybe remove the comment line.

**Comment by ErikEJ** [comment]
I dont really understand your workflow and why you are facing issues. But removing the headeris on option, as documented.

**Comment by Tony20221** [comment]
I want to select a single table and update its entity. I don't want any other entity to be touched. Pretend they don't exist. Do you understand this part?
________________________________

**Comment by ErikEJ** [comment]
If there are no changes to any other tables they will not be "touched" despite being selected. 

Your only other option would be to remove the header.

**Comment by Tony20221** [comment]
Your tool seems to be doing a two way syncing instead of one way reversed engineering. 

Two situations:
- A developer might have made a manual change in the entity only and not its table.
- A developer might have decided to keep an entity and remove its table in the database.

In both cases, I don't want the tool to touch these entities. I work on a shared project and those entities are not mine and it's not expected of me to override another developer's decision. This includes removing a comment the tool added. 

It seems there's no way to tell the tool to ignore a table without going to its entity and removing the comment. I find this pretty inflexible.  
Unselecting a table should mean ignore the table, not to delete its entity. There should be an explicit option in the UI for every table whether to delete or ignore a table. Right now unselecting a table means only one thing. Delete the table.
This goes against common expected UI patterns.

**Comment by ErikEJ** [comment]
Let me start by saying that you are the first of more than 200.000 users that have had issues with the workflow.

>> A developer might have made a manual change in the entity only and not its table.

All teh generated entity classes are partial, and clearly marked as generated code. If you want to extend the class, do so in a partial class file that you "own" (as described in the wiki)

>> A developer might have decided to keep an entity and remove its table in the database.

Why ?? In that case, removing the comment will preserve that class.

>> There should be an explicit option in the UI for every table whether to delete or ignore its entity. 

There is a [general option](https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#advanced-visual-studio-options) to never remove any files, that you may find useful.

Hope this help, and happy  to have you as a user of this tool :smile:

**Comment by ErikEJ** [comment]
I do not have any plans of changing this basic workflow. Any actionable suggestions and/or a PR will be considered.
