### ISSUE TITLE
relationship setup problem cant access the child table via the parent

### ISSUE THREAD

**Issue by smarteez17** [ErikEJ/EFCorePowerTools#1413]
Hi 
I have 2 table as per image 

![image](https://user-images.githubusercontent.com/35128168/171854199-6be12ca2-ca40-4699-9faf-f6cf4f99e90e.png)

when I import the table I cant access the child table via the parent. I can only access the parent via the child . 

I need in code to go RiskObservations.Injuries. but can only do this Injuries.RiskObservations

On Creating and update I pass a Object of RiskObservations which has an Injuries and SQL adds the RiskObservations  first and then Injuries but I am not able to do this any more due to I cant access RiskObservations.Injuries this way 

Please can you explain why is this 

Here is the sql 

CREATE TABLE [dbo].[RiskObservations](
	[RiskObservationsId] [bigint] IDENTITY(1,1) NOT NULL,
	[ReportingPeriodId] [bigint] NULL,
	[FinancialPeriodId] [bigint] NULL,
	[RiskStatusId] [bigint] NOT NULL,
	[RiskTypeId] [bigint] NOT NULL,
	[DCId] [bigint] NOT NULL,
	[CapturedDate] [datetime] NULL,
	[CapturedById] [bigint] NULL,
	[ModifiedDate] [datetime] NULL,
	[ModifiedById] [bigint] NULL,
	[StatusObservationId] [uniqueidentifier] NULL,
 CONSTRAINT [PK_RiskObservations] PRIMARY KEY CLUSTERED 
(
	[RiskObservationsId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Injuries](
	[RiskObservationsId] [bigint] NOT NULL,
	[InjuryDate] [datetime] NOT NULL,
	[PatientName] [varchar](50) NOT NULL,
	[InjuryTypeId] [bigint] NOT NULL,
	[InjuryLocationId] [bigint] NOT NULL,
	[InjuryScaleId] [bigint] NOT NULL,
 CONSTRAINT [IX_Injuries] UNIQUE CLUSTERED 
(
	[RiskObservationsId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Injuries]  WITH CHECK ADD  CONSTRAINT [FK_Injuries_RiskObservations] FOREIGN KEY([RiskObservationsId])
REFERENCES [dbo].[RiskObservations] ([RiskObservationsId])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[Injuries] CHECK CONSTRAINT [FK_Injuries_RiskObservations]
GO

**Comment by ErikEJ** [comment]
Could you share the generated classes?

**Comment by smarteez17** [comment]
Hi Sure 

 public partial class RiskObservation
    {
        [Key]
        public long RiskObservationsId { get; set; }
        public long? ReportingPeriodId { get; set; }
        public long? FinancialPeriodId { get; set; }
        public long RiskStatusId { get; set; }
        public long RiskTypeId { get; set; }
        [Column("DCId")]
        public long Dcid { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CapturedDate { get; set; }
        public long? CapturedById { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedDate { get; set; }
        public long? ModifiedById { get; set; }
        public Guid? StatusObservationId { get; set; }
}

[Keyless]
    public partial class Injury
    {
        public long RiskObservationsId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime InjuryDate { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string PatientName { get; set; }
        public long InjuryTypeId { get; set; }
        public long InjuryLocationId { get; set; }
        public long InjuryScaleId { get; set; }

        [ForeignKey("RiskObservationsId")]
        public virtual RiskObservation RiskObservations { get; set; }
    }

**Comment by ErikEJ** [comment]
Because Injuries is Keyless!
