### ISSUE TITLE
Reverse Engineer - DBContext some entities show indexes, others are missing, why?

### ISSUE THREAD

**Issue by Snappee** [ErikEJ/EFCorePowerTools#1414]
I'm using the 'Reverse Engineer' tool to create the DB Classes and context.  Upon reviewing the context, noticed that for some tables, the indexes are brought in and referenced, on others they may not be.  Couple questions:

1) What is the root cause of the situation?   Should the entities in the context show all the indexes (including the Primary key) and if so, why am I not seeing them for some of the entities?

2) Given the above, is this a BUG an incomplete feature of the product or "as designed" for some reason?

3) If it should be generating them, then I am happy to supply the database and/or whatever you need to debug/diagnose the issue.

4) Given that they are NOT there for some key tables, is there anything wrong with manually adding them to the context?  If I do this, will this work be overwritten if I update the tables/context later on?

Disclaimer:  I'm new to EF Core 6 as well as EF Core Power Tools:  So please accept my apologies in advance if I'm asking questions that are unintelligent or have been documented someplace else.  

### Provide steps to reproduce

I created a new .NET6 Winforms application - has a single form in it with no functionality added.  I then used EFPT to 'Reverse Engineer' a SQL Server database --> selected ALL the tables and only one Stored Procedure.   I specified an optional "Database" subdirectory for the entity classes and context, specified that I wanted to use the Database column names and also that I wanted to 'Pluralize' collection definitions.  (I don't think these options have anything to do with my perceived issue).

### Provide technical details

- EF Core version in use: (e.g. EF Core 6)

- Is Handlebars used: no/yes

No

- Is .dacpac used: no/yes

No

- EF Core Power Tools version: (found in About dialog - blue question mark icon on context menu)

Latest daily build - 2.5.1000

- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)

SQL Server 2019

- Visual Studio version: (e.g. Visual Studio 2022)

2022 Professional

**Comment by Snappee** [comment]
Attached screen shots - of one specific table context and the indexes of the table inside of the SQL Management studio
<img width="669" alt="2022-06-03_15-04-25" src="https://user-images.githubusercontent.com/9368303/171931732-a4b03ce4-e89c-493e-bea3-3e45c00f6067.png">
<img width="948" alt="2022-06-03_15-05-08" src="https://user-images.githubusercontent.com/9368303/171931751-dcaf8a6f-a4ab-41a6-9714-2dcd4b42650e.png">

.

**Comment by ErikEJ** [comment]
Why was this closed?

**Comment by Snappee** [comment]
Hey Erik, didn't mean to close this - think I selected the "Close with Comment" . . . instead of "Comment"

**Comment by ErikEJ** [comment]
The information  about indexes is not used by EF Core in any way. So it is by design. That being said, the should still be generated. Are you using Data Annotations?

If you would like me to investigate further please provide a full repro project   including CREATE scripts for a sample table and indexes.

**Comment by Snappee** [comment]
I can create a little solution with a project in it in VS22.  If you want, I can easily just create a backup of the database (it does not have much data in it) - you can then restore it from the backup and be ready to rock in a very short amount of time?

**Comment by ErikEJ** [comment]
Sure, or just a CREATE script for the table and indexes is fine

**Comment by Snappee** [comment]
Hey Erik, appreciate the reply.  Wouldn't you know it, was putting together a simple project today - erased all the older entity classes and context, used EFPT to once again reverse engineer the DB . . . . and of course the indexes are now in the DBContext class.  I have no clue as to why and as for now, I can't replicate it - so it goes.   As I continue to use your product, will report any issues that I see.  Thanks for the great communication.

**Comment by Snappee** [comment]
Since my last post, managed to get the "Compare DBContext to DB" tool working and it shows some missing indexes in the database that are not included in the generated DBContext (using Reverse Engineer).  If you want to explore the reasons why, let me know and I will backup the DB and associated test project and send them your way.  Thanks!

**Comment by Snappee** [comment]
<img width="695" alt="2022-06-06_12-11-04" src="https://user-images.githubusercontent.com/9368303/172203659-a5a51ef1-924d-4307-9839-dbdb15dfc88b.png">
