### ISSUE TITLE
Synchronous Stored Procedures instead of Async  

### ISSUE THREAD

**Issue by raman-kazhadub** [ErikEJ/EFCorePowerTools#1417]
Is there any options to generate stored procedures as not async code?
We have legacy project with a lot of synchronous code, so we need to call all code as sync. I cannot call GetAwaiter().GetResult() on EF Core ExecuteSqlRawAsync  because ConfigureAwait(false) is missing in internal code.

**Comment by ErikEJ** [comment]
What does "missing in internal code" mean?

**Comment by raman-kazhadub** [comment]
It means some EfCore methods doesn't include ConfigureAwait(false). I have .net 4.7.2 asp.net web app and there is a deadlock when call SomeAsyncMethod().GetAwaiter().GetResult(). 
But it doesn't matter. I would like to have some option of EFPT do not generate async code, is there anyone?

**Comment by ErikEJ** [comment]
No, there is no option to do that. And I have no plans to add it, as EF Core .NET Framework support is going away by the end of this year.

**Comment by ErikEJ** [comment]
Are you saying that if I add .ConfigureAwait(false) to the generated code it would work for you?

    var _ = await _context.SqlQueryAsync<CustOrdersDetailResult>("EXEC @returnValue = [dbo].[CustOrdersDetail] @OrderID", sqlParameters, cancellationToken).ConfigureAwait(false);

**Comment by raman-kazhadub** [comment]
> Are you saying that if I add .ConfigureAwait(false) to the generated code it would work for you?
> 
> ```
> var _ = await _context.SqlQueryAsync<CustOrdersDetailResult>("EXEC @returnValue = [dbo].[CustOrdersDetail] @OrderID", sqlParameters, cancellationToken).ConfigureAwait(false);
> ```

No, it doesn't.
Tool generates the following class:
`public static class DbContextExtensions
    {
        public static async Task<List<T>> SqlQueryAsync<T>(this DbContext db, string sql, object[] parameters = null, CancellationToken cancellationToken = default) where T : class
        {
            if (parameters is null)
            {
                parameters = new object[] { };
            }

            if (typeof(T).GetProperties().Any())
            {
                return await db.Set<T>().FromSqlRaw(sql, parameters).ToListAsync(cancellationToken);
            }
            else
            {
                await db.Database.ExecuteSqlRawAsync(sql, parameters, cancellationToken);
                return default;
            }
        }
    }`
    The problem is in ToListAsync and ExecuteSqlRawAsync. they doesn't contain ConfigureAwait(false) and there are deadlocks. https://github.com/dotnet/efcore/issues/28159.
Ыo it would be better if the tool had the ability to generate synchronous code, because it's not possible to use it now from .net framework with a lot of synchronous legacy code. I'm in progress of porting EF6 to EFCore and I have no way to rewrite everything to asynchronous code

**Comment by ErikEJ** [comment]
How about adding ConfigureAwait(false) to those two methods? would that help? (excuse my ignorance)

And if so, you could just do that yourself?

**Comment by raman-kazhadub** [comment]
> How about adding ConfigureAwait(false) to those two methods? would that help? (excuse my ignorance)
> 
> And if so, you could just do that yourself?

It would not, because there are no internal ConfigureAwait(false) in EF Core methods

**Comment by ErikEJ** [comment]
Ah, finally got it. Sorry, [no plans](https://github.com/ErikEJ/EFCorePowerTools/issues/1417#issuecomment-1147058910) to do this, as I said above

**Comment by ErikEJ** [comment]
Reconsidering - suggestions for PR: 
- make sure to make it optional (feel free to hardcode as on in your PR and I will make the implementaion of passing the option from VS) 
- Look at the readme in this repo for smoke testing advice
- Create an alternate version of DbContextExtensions.cs to be included (named for example DbContextExtensions.Sync.cs)
- Feel free to ping me with any other questions!

**Comment by raman-kazhadub** [comment]
@ErikEJ 
I found that https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/Shared/Handlers/ReverseEngineer/ReverseEngineerOptions.cs doesn't contain UseMultipleSprocResultSets option, but test files contain. Is it ok?

**Comment by ErikEJ** [comment]
The ReverseEngineerOptions.cs class represents what is stored in efpt.config.json.

ReverseEngineerCommandOptions.cs represents what is actually passed to the efrevng command line tool and is also a representation of the test files. (so for example the connection string is not persisted in efpt.config,json for security reasons)

Makes sense?

**Comment by raman-kazhadub** [comment]
https://github.com/ErikEJ/EFCorePowerTools/pull/1419

**Comment by ErikEJ** [comment]
I will have a look soon.

**Comment by ErikEJ** [comment]
Imemented (by you, thanks a lot) - available in latest daily build - would be grateful if you could verify.

**Comment by raman-kazhadub** [comment]
> Yes. Did you go to Tools/Options to change the option?

Oh, sorry, it's here. I thought it could be configured via eftp.config.json.

**Comment by ErikEJ** [comment]
Great. And thanks again for your contribution.
