### ISSUE TITLE
See #1414 - didn't want to replicate it here, didn't see a way to "reopen it".  Thanks!

### ISSUE THREAD

**Issue by Snappee** [ErikEJ/EFCorePowerTools#1418]
Describe what is not working as expected.

### Provide steps to reproduce

Please include a **complete** description or project that I can redo/run to reproduce the issue.

### Provide technical details

- EF Core version in use: (e.g. EF Core 6)

- Is Handlebars used: no/yes

- Is .dacpac used: no/yes

- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)

- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)

- Visual Studio version: (e.g. Visual Studio 2022)

**Comment by ErikEJ** [comment]
Sure, still waiting for a proper repro if you want free support...

**Comment by Snappee** [comment]
Here you go.   When you UnZip the project, the representative database is in the "\BackupDatabase" subdirectory.   If you need anything, let me know.   

Have a great day.   Dale


[STAIDBSupport.zip](https://github.com/ErikEJ/EFCorePowerTools/files/8846186/STAIDBSupport.zip)

**Comment by Snappee** [comment]
Hey Erik, threw this together - hopefully it is clear.  As I'm a newbie to your product and EF Core 6 - if my examples are off-base, then just throw them out . . .    Dale

[EntityFrameworkCore-PowerTools-Impressions-V1.docx](https://github.com/ErikEJ/EFCorePowerTools/files/8847796/EntityFrameworkCore-PowerTools-Impressions-V1.docx)
e

**Comment by ErikEJ** [comment]
Names of primary keys are not reverse engineered.

**Comment by Snappee** [comment]
Should the primary keys themselves all be replicated and reverse engineered - across any table that has one?   Why were some not represented in the Context?   If they are not there, should I manually add them - is there ANY benefit in doing so, or does the backend SQL server restructure queries to optimize them?

**Comment by Snappee** [comment]
Thanks again!

**Comment by ErikEJ** [comment]
If a primary key column is called Id or TablenameId EF Core knows by convention that it is the key.

**Comment by Snappee** [comment]
Thank you Sir, didn't mean for you to be in the education business.  ;)
