### ISSUE TITLE
partial IProcedures interface

### ISSUE THREAD

**Issue by raman-kazhadub** [ErikEJ/EFCorePowerTools#1421]
It would be nice to be able to extend IProcedures interface because some large and complex procedures cannot be generated well by EFPT. 
For me generated code returns int, but it should be complex type, so I could write this procedure manually, but it's no way to extend IProcedures now.

**Comment by ErikEJ** [comment]
Have you tried "UseLegacyDiscovery" ?

**Comment by raman-kazhadub** [comment]
> 

yes, it's the same result

**Comment by ErikEJ** [comment]
Cool. Do you have a PR?

**Comment by raman-kazhadub** [comment]
> Cool. Do you have a PR?

https://github.com/ErikEJ/EFCorePowerTools/pull/1422

**Comment by ErikEJ** [comment]
Fixed in latest daily
