### ISSUE TITLE
Question - use handlebars to add EntityBase to tables only

### ISSUE THREAD

**Issue by jwevansgam** [ErikEJ/EFCorePowerTools#1424]
Hello,
 
Is it possible to optionally add a base class to the entities generated using the handlebars templates

I am generating views and tables and I would like to generate the tables with a base class / interface of IEntity but not the views

Many thanks

**Comment by ErikEJ** [comment]
Not with EF Core Power Tools, you will have to adopt the Handlebars library in your own code.
