### ISSUE TITLE
Support F# and VB projects

### ISSUE THREAD

**Issue by xperiandri** [ErikEJ/EFCorePowerTools#1428]
The extension does not work with F# and VB projects, although there are packages that can allow that
https://github.com/efcore/EFCore.FSharp
https://github.com/efcore/EFCore.VisualBasic
I'm particularly interested in F#

### Provide technical details

- EF Core version in use: 6
- EF Core Power Tools version: 2.5.1007
- Database engine: SQL Server
- Visual Studio version: Visual Studio 2022 17.2.3

**Comment by ErikEJ** [comment]
What would you get from this tool, that the packages above does not provide?

**Comment by xperiandri** [comment]
Using UI to perform operaitons

**Comment by ErikEJ** [comment]
Got it!

**Comment by ErikEJ** [comment]
This is not something I plan to do but I will review a PR to enable this. Closing and putting in the backlog milestone

**Comment by ErikEJ** [comment]
No plans to do this
