### ISSUE TITLE
HasDefaultValueSql, HasColumnType, FromSqlRaw does not exist EF6?

### ISSUE THREAD

**Issue by royaldragonit** [ErikEJ/EFCorePowerTools#1430]
### Provide steps to reproduce

Please include a **complete** description or project that I can redo/run to reproduce the issue.

### Provide technical details

- EF Core version in use: (EF Core 6)

- Is .dacpac used: **no**

- EF Core Power Tools version: (2.5.1007)

- Database engine: (**SQL Server**)

- Visual Studio version: 2022
![image](https://user-images.githubusercontent.com/72593390/174100020-0c5927e5-889a-414b-a70c-6f2b2bcd7848.png)
![image](https://user-images.githubusercontent.com/72593390/174100074-f34a704b-2517-4148-b8a3-e310ddcea580.png)

**Comment by ErikEJ** [comment]
Does your project have an EF Core provider installed? 

Pls share your .csproj

**Comment by ErikEJ** [comment]
Ping?

**Comment by ErikEJ** [comment]
Closing as no additional information was provided
