### ISSUE TITLE
Inherite from various base interfaces according to auditable columns in table

### ISSUE THREAD

**Issue by csandun** [ErikEJ/EFCorePowerTools#1431]
I am using various base interfaces like `IAditableBase`, `IEntityBase`,  `ICreatableBase`, and so forth,  according to columns in the tables.  In that case, I want to inherit the relevant base interface at the scaffolding time conditionally.  
If I have one base class,  I can change the handlebar template file including the ```: BaseEntity```. Is there any possibility of adding base interfaces conditionally to the scaffolding entities?

![image](https://user-images.githubusercontent.com/11901975/174287150-02b71f79-8809-44f9-867d-2b94fef8db4f.png)

![image](https://user-images.githubusercontent.com/11901975/174287286-af0dcad2-8018-40f6-ba29-d528062f9880.png)

### technical details

- EF Core version =>  EF Core 6

- Is Handlebars used: yes

- Is .dacpac used: no =>  using server database connection

- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)

- Database engine: (SQL Server)

- Visual Studio version: => Visual Studio 2022

**Comment by ErikEJ** [comment]
No, not unless you use the Handlebars library directly in your own code.

It also sounds like you are mixing database first and domain modelling.
