### ISSUE TITLE
has an invalid type 'DataTable'. Ensure the parameter type can be mapped by the current provider.  

### ISSUE THREAD

**Issue by judejinjin** [ErikEJ/EFCorePowerTools#1433]
Describe what is not working as expected.

### Provide steps to reproduce

Please include a **complete** description or project that I can redo/run to reproduce the issue.

### Provide technical details

- EF Core version in use: (e.g. EF Core 6)

- Is Handlebars used: no/yes

- Is .dacpac used: no/yes

- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)

- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)

- Visual Studio version: (e.g. Visual Studio 2022)

**Comment by judejinjin** [comment]
I'm using EF Core power tool 2.5.1013.0
EF core 6
Visual Studio 2022
Db is SQL Server
using UI to reverse engineer,

Functions that use stringlist are having trouble.
RelationalModelValidator.ValidateDbFunctions(IModel model, IDiagnosticsLogger`1 logger) throws
System.InvalidOperationException: The parameter 'BBGID' for the DbFunction 'BXC.nVision.nVisionBlotter2.Context.NVisionBlotter2DbContext.fnGetCASTParent(System.Data.DataTable)' has an invalid type 'DataTable'. Ensure the parameter type can be mapped by the current provider.

References include 
Microsoft.EntityFrameworkCore 6.0.6

Microsoft.EntityFrameworkCore.Design 6.0.6

Microsoft.EntityFrameworkCore.SqlServer 6.0.6

Please help.

**Comment by ErikEJ** [comment]
Please share a full, runnable repro.

**Comment by judejinjin** [comment]
I choose 'use column names directly from db',  some SPs do select * from multiple tables so there are duplicated table names, it'll be very helpful if generated code can append 1, 2, .. to the column names when there are duplicated column names. Currently, I manually edit and append 1, 2.. to duplicated column names.

**Comment by ErikEJ** [comment]
Please share a example. Not sure your fix will work.

**Comment by ErikEJ** [comment]
You are mixing too many issues in one here..  Please provide repro code and add an issue per problem you encounter.

**Comment by ErikEJ** [comment]
>> I cannot share repo because code is proprietary.

You should be able to provide a SQL scripts that demonstrates the general issue without sharing any customer code.

**Comment by ErikEJ** [comment]
>> I choose 'use column names directly from db', some SPs do select * from multiple tables so there are duplicated table names

That option ha no effect on stored procedure generation, and I already have code to prevent duplcate names in reslut sets:

https://github.com/ErikEJ/EFCorePowerTools/blob/a65143b1f4f1f4bc31133ef450e6a928acd537a4/src/GUI/RevEng.Core/Routines/SqlServerRoutineScaffolder.cs#L208

**Comment by judejinjin** [comment]
Erik, 
I work at a large asset management firm. we're trying to migrate some legacy app to ef core 6. Your tool works great!
here is the function with stringlist parameter
CREATE FUNCTION [dbo].[fnGetRelatedEntitiesForBBG](
	@ID_BB_GLOBAL_COMPANY StringList READONLY
)

EFCore Power tool generates below code
        [DbFunction("fnGetRelatedEntitiesForBBG", "dbo")]
        public IQueryable<fnGetRelatedEntitiesForBBGResult> fnGetRelatedEntitiesForBBG(DataTable ID_BB_GLOBAL_COMPANY)
        {
            return FromExpression(() => fnGetRelatedEntitiesForBBG(ID_BB_GLOBAL_COMPANY));
        }
then when i try to run a simple test - make a connection via context and do a count on a table, it gives me below exception:

System.InvalidOperationException: The parameter 'ID_BB_GLOBAL_COMPANY' for the DbFunction 'BXC.nVision.nVisionBlotter2.Context.NVisionBlotter2DbContext.fnGetRelatedEntitiesForBBG(System.Data.DataTable)' has an invalid type 'DataTable'. Ensure the parameter type can be mapped by the current provider.

  Stack Trace: 
RelationalModelValidator.ValidateDbFunctions(IModel model, IDiagnosticsLogger`1 logger)
RelationalModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
SqlServerModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
ModelRuntimeInitializer.Initialize(IModel model, Boolean designTime, IDiagnosticsLogger`1 validationLogger)
ModelSource.GetModel(DbContext context, ModelCreationDependencies modelCreationDependencies, Boolean designTime)
DbContextServices.CreateModel(Boolean designTime)
DbContextServices.get_Model()

For now, I have commented out all functions that use DataTable parameters.

**Comment by ErikEJ** [comment]
And what is the definition of: @ID_BB_GLOBAL_COMPANY ?

And thanks for the kind words.

**Comment by judejinjin** [comment]
@ID_BB_GLOBAL_COMPANY is  StringList

**Comment by ErikEJ** [comment]
And how is StringList defined (there is no such thing built into SQL Server)

**Comment by ErikEJ** [comment]
Great! I will investigate.

**Comment by ErikEJ** [comment]
I have fixed this in the latest daily by preventing these functions from being generated.

You can [hand code a solution](https://stackoverflow.com/questions/63742915/ef-passing-a-table-valued-parameter-to-a-user-defined-function-from-c-sharp) if needed.

For the two other questions/issues you had above (System.Data + duplicate names) , please create new issues with more repro information.

**Comment by sam-wheat** [comment]
> I have fixed this in the latest daily by preventing these functions from being generated.

I ran into the same issue on v 2.5.1145.

**Comment by ErikEJ** [comment]
@sam-wheat if you did encounter this, please create a new issue with sufficient repro details.
