### ISSUE TITLE
Reverse Engineering UI - does not indicate when it is done; maybe a blocking UI is better

### ISSUE THREAD

**Issue by judejinjin** [ErikEJ/EFCorePowerTools#1436]
Erik,
When I run reverse engineering on a large legacy db, it takes >10 minutes to finish.
Since it runs in the background and doesn't block anything, I don't know when it is finished.
Initially it was even a little confusing:  I build the solution successfully after 1 minute and then build will fail after 5 minutes when it generates context code that calls the functions/SPs which have the glitches/issues I submitted separately.

I think it is better to make it blocking and show some status/summary when reverse engineering is finished.

- EF Core version in use:  EF Core 6

- Is Handlebars used: no

- Is .dacpac used: no

- EF Core Power Tools version: 2.50.1013

- Database engine: SQL Server

- Visual Studio version: Visual Studio 2022

**Comment by judejinjin** [comment]
Erik,
i'm using SQL server 2019. my legacy db is big:
1. 353 files are generated within seconds for tables and dbcontext
2. after a pause of 5-10 minutes, 414 more files are generated for functions/SPs
3. total files generated are 767 files and 4.3 MB

**Comment by ErikEJ** [comment]
So: 

**Parameters**

I am running a query for each stored procedure to get the parameters and one to get the the result set shape. 

The parameter query could possibly be refactored to run only once.

**Result set shape**

I use 2 types of queries to get the result set shape, one of which invokes the stored procedure, the other one looks at metadata.

By default I use the one that invokes the stored procedure.

Wonder what happen if you switch to using the other, you can do that via the [global option](https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#advanced-visual-studio-options) 

- 'Use sp_describe_first_result_set only for stored procedure result set discovery'

**Comment by ErikEJ** [comment]
I have minimized number of database roundtrips in latest daily, would be great if you could give it a try.

**Comment by ErikEJ** [comment]
Ping?

**Comment by judejinjin** [comment]
i tried. 2.50.1014 version. it still takes > 10 mins. now it pops up a dialog telling me to check output window for error, output windows has a message saying some functions cannot be generated due to TVP.

**Comment by ErikEJ** [comment]
Did you also try the general option to change the discovery mode?

**Comment by judejinjin** [comment]
Erik,
how do i set the general option? i can't see this option in the UI.

**Comment by ErikEJ** [comment]
Via Tools, Options as described in the link above.

**Comment by ErikEJ** [comment]
>> i tried. 2.50.1014 version.

Sorry, you actually need 2.5.1016 or later to try "less roundtrips" out.

**Comment by judejinjin** [comment]
Erik,
using 1017 version and set that global option to true, it finished in about 1 min. 
thanks!

**Comment by ErikEJ** [comment]
Ping?

What is the timing without the change of the global option?
