### ISSUE TITLE
New lines at the end of newly created classes

### ISSUE THREAD

**Issue by Superflemme** [ErikEJ/EFCorePowerTools#144]
Describe what is not working as expected.

When reverse engineering a database, the files that are updated or created have a new line after the last closing brace at the end of the file. This causes our coding style to complain.

### Steps to reproduce
Enable code styling on your project
Reverse engineer
Watch all the classes have one new line too many

### Further technical details
EF Core Power Tools version: Any
Visual Studio version: Visual Studio 2017

**Comment by ErikEJ** [comment]
Fix should go here: https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/ReverseEngineer20/EFCoreReverseEngineer.cs#L191

**Comment by ErikEJ** [comment]
Fixed in the latest daily build 😄
