### ISSUE TITLE
Would it be possible to add attributes with Reverse engineering. In particular [JsonIgnore] to virtual objects.

### ISSUE THREAD

**Issue by ronaldpschutte** [ErikEJ/EFCorePowerTools#1441]
I have issues in my Blazor app with circular referenced objects. This because of the navigation objects. I know there are ways around this by using Newtonsoft, but this does not always work. Sometimes objects get serialized in external libs. Like the Azure Eventgrid and expects an object.

Adding [JsonIgnore] to an attribute works fine with System.Text.Json, but the reverse engineer will remove this. I would like to be able to add the attribute to all virtual objects when generating.

Great thanks. Love this tools.

**Comment by ErikEJ** [comment]
Thanks for the kind words!

I general it is not a good idea to use you DAL classes as DTOs.

I think you can use [MetadataTypeAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.metadatatypeattribute?view=net-6.0) to inject the attribute

**Comment by ErikEJ** [comment]
Have you tried ModelMetaDataAttribute (I assume you use ASP.NET Core) 

https://stackoverflow.com/questions/34576921/asp-net-core-metadatatype-attribute-not-working

**Comment by SandroRiz** [comment]
Yes, if you look to my project I tried with a console app that generate a json file and with a minimal webapi

With both MetadataType and ModelMetadataType JsonIgnore is not applied
