### ISSUE TITLE
The Tool doesn't see my custom helpers from IDesignTimeServices using ConfigureDesignTimeServices

### ISSUE THREAD

**Issue by kaidef812** [ErikEJ/EFCorePowerTools#1442]
I'm used Handlebars .net patterns with custom helpers and properties. When used scaffold dbcontext command from terminal all worked, but, when trying to use this tool it doesn't see any custom helpers. Does this tool support custom helpers for Handlebars?
And with command I set directories for models and context into another library. Is it possible with tool?

- EF Core version in use: 3.1.6
- Is Handlebars used: yes
- EFCore.Scaffolding.Handlebars: 3.8.2
- Is .dacpac used: no
- EF Core Power Tools version: 2.5.1041
- Database engine: SQL Server
- Visual Studio version: Visual Studio 2022

**Comment by ErikEJ** [comment]
>> . Does this tool support custom helpers for Handlebars?

No. It does not know anything about and existing code in your project, which is by design


>> Is it possible with tool?

Yes.
