### ISSUE TITLE
EF Core Power Tools Package does not load in VS2019 since Version 2.5.1041

### ISSUE THREAD

**Issue by benni1972** [ErikEJ/EFCorePowerTools#1445]
The EF Core Power Tools Package was automatically updated to latest version 2.5.1041

Since then, when starting VS2019 and loading a project or even when starting a new one, I get the following warning:

>Microsoft Visual Studio
>
>The 'EFCorePowerToolsPackage' package did not load correctly.
>
>
>The problem may have been caused by a configuration change or by the installation of another extension. You can get more >information by examining the file 'C:\Users\battra01\AppData\Roaming\Microsoft\VisualStudio\16.0_2dd9bf82\ActivityLog.xml'.
>
>
>Restarting Visual Studio could help resolve this issue.
>
>
>Continue to show this error message?

When checking the activity log, as stated in the warning dialog I find the following information regarding the package:

`
  <entry>
    <record>1034</record>
    <time>2022/07/06 05:29:28.924</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [EFCorePowerToolsPackage]Source: &apos;EFCorePowerTools&apos; Description: Could not load file or assembly &apos;Community.VisualStudio.Toolkit, Version=16.0.445.0, Culture=neutral, PublicKeyToken=79441d341a79572c&apos; or one of its dependencies. Das System kann die angegebene Datei nicht finden.&#x000D;&#x000A;System.IO.FileNotFoundException: Could not load file or assembly &apos;Community.VisualStudio.Toolkit, Version=16.0.445.0, Culture=neutral, PublicKeyToken=79441d341a79572c&apos; or one of its dependencies. Das System kann die angegebene Datei nicht finden.&#x000D;&#x000A;File name: &apos;Community.VisualStudio.Toolkit, Version=16.0.445.0, Culture=neutral, PublicKeyToken=79441d341a79572c&apos;&#x000D;&#x000A;   at EFCorePowerTools.EFCorePowerToolsPackage.&lt;InitializeAsync&gt;d__11.MoveNext()&#x000D;&#x000A;   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine&amp; stateMachine)&#x000D;&#x000A;   at EFCorePowerTools.EFCorePowerToolsPackage.InitializeAsync(CancellationToken cancellationToken, IProgress 1 progress)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass20_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.GetResult()&#x000D;&#x000A;&#x000D;&#x000A;WRN: Protokollierung der Assemblybindung ist AUS.&#x000D;&#x000A;Sie k&#x00F6;nnen die Protokollierung der Assemblybindungsfehler aktivieren, indem Sie den Registrierungswert [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) auf 1 festlegen.&#x000D;&#x000A;Hinweis: Die Protokollierung der Assemblybindungsfehler f&#x00FC;hrt zu einer gewissen Leistungseinbu&#x00DF;e.&#x000D;&#x000A;Sie k&#x00F6;nnen dieses Feature deaktivieren, indem Sie den Registrierungswert [HKLM\Software\Microsoft\Fusion!EnableLog] entfernen.&#x000D;&#x000A;</description>
    <guid>{F4C4712C-CEAE-4803-8E52-0E2049D5DE9F}</guid>
    <hr>80070002</hr>
    <errorinfo></errorinfo>
  </entry>
`

(Sorry, some parts are in german!)

But it seems that the required dependency "Community.VisualStudio.Toolkit" (version 16.0.445.0) cannot be found on my machine.

I'm not sure if this is somhow intended and I have to install this seperately, as there was no problem with EF Core Power Tools, before it upgraded to the latest version,

Technical details:

- EF Core version in use: irrelevant

- Is Handlebars used: no

- Is .dacpac used: irrelevant

- EF Core Power Tools version: 2.5.1041

- Database engine: irrelevant

- Visual Studio version: Visual Studio 2019

**Comment by ErikEJ** [comment]
Are you running the latest VS 2019 version?

Have you tried VS 2022?

**Comment by benni1972** [comment]
Thanks for your quick reply!

I've just upgraded VS2019 to the latest version and now the package loads as expected!
