### ISSUE TITLE
Ability to select the Context Base Class instead of DBContext

### ISSUE THREAD

**Issue by b-giavotto** [ErikEJ/EFCorePowerTools#1446]
Would be perfect the ability to choose the name of the DBContext Base Class.
Plus the Generated OnModelCreating should call the base implemetation as the first line.... 
partial void OnModelCreatingPartial(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
/* Following the implementation of actual OnModelCreating*/
        }

**Comment by ErikEJ** [comment]
You should be able to do that with the Handlebars templates and a partial DbContext class.

**Comment by b-giavotto** [comment]
I do not know  handlerbars, can you point me to some link?
Thx, in advance

**Comment by ErikEJ** [comment]
Sure: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#customize-code-using-handlebars
