### ISSUE TITLE
Cannot detect postgresql partition table

### ISSUE THREAD

**Issue by chang196700** [ErikEJ/EFCorePowerTools#1447]
Cannot detect postgresql partition table.

### Provide technical details

- EF Core version in use: EF Core 6

- Is Handlebars used: no

- Is .dacpac used: no

- EF Core Power Tools version: 2.5.1041.0

- Database engine: Postgres

- Visual Studio version: Visual Studio 2022

**Comment by ErikEJ** [comment]
You really need to tell me more - for starters I know nothing about Postgres

**Comment by chang196700** [comment]
I can provide a simple example。

```sql
create table simple
(
    id           integer generated by default as identity,
    order_number varchar not null,
    constraint simple_pkey
        primary key (id, order_number)
)
    partition by LIST (order_number);
create table simple_123 partition of simple for values in ('123');
create table simple_456 partition of simple for values in ('456');
```

Using the tool in VS can't display the partition main table, but the sub tables are displayed.

**Comment by ErikEJ** [comment]
I am simply showing what the DatabaseModel generated by the postgres provider returns. And I do not know what partition tables are. Maybe @roji can help?

**Comment by roji** [comment]
Table partitioning isn't yet supporting in the Npgsql provider, see https://github.com/npgsql/efcore.pg/issues/1035. You can still use raw SQL in your migrations to manually set up partitions as you wish.

**Comment by 2mik** [comment]
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/9930867/1f873db7-91cf-48c0-a56e-0fabfd2aab9e)
For example, there is hourly_data table which is partitioned. The tool can display existing partitions, but does not display the table itself. If there a table currently has no partitions, it is not displayed. Is is possible to skip partitions but reverse engineer the table?

**Comment by ErikEJ** [comment]
@2mik The tool get's the table list from the provider, and the provider has not yet been updated to support partitions https://github.com/ErikEJ/EFCorePowerTools/issues/1447#issuecomment-1179730020

**Comment by 2mik** [comment]
Got it. Just added a screenshot that can be useful for others in similar situation. May be in the future, the provider can provide more, and the issue could be resolved.
Do you know if this issue is relevant for databases other than PostgreSQL?

**Comment by ErikEJ** [comment]
@2mik @roji Partitioning is SQL Server is completely transparent, just appears like a single table (I think all tables are in principle partioned but must just with a single partition)

**Comment by roji** [comment]
Opened https://github.com/npgsql/efcore.pg/issues/2934 to track at least ignoring partitions when scaffolding.

**Comment by 2mik** [comment]
Thank you.
