### ISSUE TITLE
Any way to download previous version of Tools

### ISSUE THREAD

**Issue by Manvish1230** [ErikEJ/EFCorePowerTools#1450]
We are seeing many errors when running reverse engineer option related to SQL Stored procedures which we did not see earlier.
Nothing has been changed to schema classes.

I tried "UseLegacyResultSetDiscovery": true  option and I still see the same issue

Unable to get result set shape for PROCEDURE '******_Views'.
Invalid object name 'Database..table'

Can you please provide a link for a older version of this tool?

Thanks

**Comment by Manvish1230** [comment]
never mind, I found **EF_Core_Power_Tools_v2.5.982.vsix** in my system and this extension worked. Reverse Engineer task completed successfully.
I also disabled the automatic update of tool extension in visual studio

If anyone run into similar issue, please let me know i can share EF_Core_Power_Tools_v2.5.982.vsix extension 

Thanks

**Comment by ErikEJ** [comment]
The errors were there before they were just not reported.

**Comment by kevinfr06** [comment]
> 



> never mind, I found **EF_Core_Power_Tools_v2.5.982.vsix** in my system and this extension worked. Reverse Engineer task completed successfully. I also disabled the automatic update of tool extension in visual studio
> 
> Thanks

Hello,

Can you send me your version  ?
Regards,
Kevin
