### ISSUE TITLE
The requested data provider not found. Maybe it isnt installed

### ISSUE THREAD

**Issue by saigkill** [ErikEJ/EFCorePowerTools#1458]
I created a sqlite database, and tried the Powertools Reverse Engineering. I added a Connectionstring and the test connection was successful. Clicking on "OK" results in the errormessage in the title. 

### Provide steps to reproduce

Checkout https://dev.azure.com/saigkill/JobApplicationManager/_git/JobApplicationManager?version=GBdevelop
Add Database
Use the DB from Assets/Database/JobApplicationManager.sqlite3

### Installed Nugets
`
<PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.7" />
<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.7" />
<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="6.0.7" />
<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.Core" Version="6.0.7" />
<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="6.0.7" />
`

### Provide technical details

- EF Core version in use: (e.g. EF Core 6)
EF Core 6

- Is Handlebars used: no/yes

- Is .dacpac used: no/yes
no

- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
2.5.982.0

- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)
SQLite

- Visual Studio version: (e.g. Visual Studio 2022)
Visual Studio 2022

**Comment by saigkill** [comment]
Custom Connection (havent seen that) works as expected. Thank you very much :-)

**Comment by ErikEJ** [comment]
Great! Wonder how I could make it more visible?

**Comment by ErikEJ** [comment]
@saigkill I have updated the UX for adding connections, woould be grateful if you could try it out and let me know what you think.

**Comment by saigkill** [comment]
@ErikEJ I just tested it now. I think this UX is more intuitive. Thank you :-)

**Comment by ErikEJ** [comment]
@saigkill Great, thanks for the feedback!
