### ISSUE TITLE
Unable to get migration status

### ISSUE THREAD

**Issue by saigkill** [ErikEJ/EFCorePowerTools#1459]
I created some Models and a DBContext with the Reverse Engineering Tool, what was successful. I added the Context to my App.xaml.cs.

Now i tried to use the Migration Tools for manage my first migration. Currently i'm getting:
<img width="340" alt="image" src="https://user-images.githubusercontent.com/75621/179985687-dda7f446-13e5-4250-ae40-28edc3bfec96.png">

That case i haven't found in the docs.

### Provide steps to reproduce

Checkout https://dev.azure.com/saigkill/JobApplicationManager/_git/JobApplicationManager?version=GBdevelop
Use Migrations Tool.

### Installed Nugets
`
<PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.7" />
<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.7" />
<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="6.0.7" />
<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.Core" Version="6.0.7" />
<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="6.0.7" />
`

### Provide technical details

- EF Core version in use: (e.g. EF Core 6)
EF Core 6 with .NET6

- Is Handlebars used: no/yes

- Is .dacpac used: no/yes
no

- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
2.5.982.0

- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)
SQLite

- Visual Studio version: (e.g. Visual Studio 2022)
Visual Studio 2022

**Comment by saigkill** [comment]
- You must be able to build the project 😄
Thats possible. :-)

- Make sure you have the correct Startup project set in Visual Studio (should be the executable project or web app).
I think WinUI3 apps having the App.xaml.cs as Startup point.

- The model inspection tool (an external process launched by Visual Studio) can be [blocked by a virus scanner or similar](https://github.com/ErikEJ/EFCorePowerTools/issues/363)
Checked Virus Scanner. But it doesnt have any issues from today.

- The model inspection tool requires a compatible .NET Core runtime to be installed.
Currently used:
`.NET SDK (gemäß "global.json"):
 Version:   6.0.302
 Commit:    c857713418

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.302\

global.json file:
  Not found

Host:
  Version:      6.0.7
  Architecture: x64
  Commit:       0ec02c8c96

.NET SDKs installed:
  6.0.300 [C:\Program Files\dotnet\sdk]
  6.0.302 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]`

- Your DbContext must be configured with a specific provider, or you will get this [error](https://github.com/ErikEJ/EFCorePowerTools/issues/431): No database provider has been configured for this DbContext.
Currently used Context:
`public partial class MyDBContext : DbContext
	{
		private static readonly string Caller = GetCaller.MapCaller(GetCaller.Caller.JobApplicationManager);

		public MyDBContext()
		{
		}

		public MyDBContext(DbContextOptions<MyDBContext> options)
			: base(options)
		{
		}

		public virtual DbSet<Certificate> Certificates { get; set; }
		public virtual DbSet<Company> Companies { get; set; }
		public virtual DbSet<EmploymentCert> EmploymentCerts { get; set; }
		public virtual DbSet<JobApplication> JobApplications { get; set; }

		protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
		{
			if (!optionsBuilder.IsConfigured)
			{
				//string datasource = "Data Source=" + Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), Caller) + "\\Assets\\Database\\JobApplicationManager.sqlite3";
				string datasource =
					"C:\\Users\\Admin\\AppData\\Roaming\\JobApplicationManager\\JobApplicationManager.sqlite3";

				optionsBuilder.UseSqlite(datasource);
			}
		}

		protected override void OnModelCreating(ModelBuilder modelBuilder)
		{
			modelBuilder.Entity<JobApplication>(entity =>
			{
				entity.Property(e => e.Id).ValueGeneratedNever();
			});

			OnModelCreatingPartial(modelBuilder);
		}

		partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
	}`

- If you cannot view the model graph, follow the advice [here](https://stackoverflow.com/questions/43405698/directed-graph-markup-language-no-longer-recognized-with-visual-studio-2017) to install the viewer.
The DGML editor is also installed.

Curerent output:
System.InvalidOperationException: Unable to collect model information
   at async Task EFCorePowerTools.Handlers.ModelAnalyzerHandler.GenerateAsync(string outputPath, Project project, GenerationType generationType)

AFAIU it should work.

**Comment by ErikEJ** [comment]
I will have a look when I cool down 🌞

**Comment by ErikEJ** [comment]
I cannot build it, which VS workloads do I need to install ? (I usually build .NET Core xplat app like console and and web)

**Comment by saigkill** [comment]
In general i have .NET Desktopdevelopment, Desktopdevelopment with C++ and Development with UWP. It was generated with Template Studio for WinUI. Maybe it fetches further dependencies.

**Comment by ErikEJ** [comment]
It does not, but it probably should to improve the user experience:
https://github.com/microsoft/TemplateStudio/blob/main/code/TemplateStudioForWinUICs/source.extension.vsixmanifest#L28

**Comment by ErikEJ** [comment]
Works fine on my PC with VS 17.2.5

**Comment by saigkill** [comment]
Just now i built a minimal example (on [1](https://github.com/saigkill/Test/tree/master/JobApplicationManager) ):

1. Created new project with the Windows Template Studio.
2. Used the Reverse Engineer with the delivered SQLite DB in Assets.
3. Added in App.xaml.cs: `services.AddSqlite<MyDBContext>(context.Configuration.GetConnectionString("DefaultConnection"));`
4. Added a Default Connection in appsettings.json
5. Added some new Nuget packages.

With that project i'm getting "Unable to get Migration Status". 

For what exactly the Migration Tool searches for?

**Comment by ErikEJ** [comment]
First you must be able to use migrations from the command line. Otherwise the tool will never work. Can you provide repro steps that demonstrates that?

**Comment by saigkill** [comment]
1. Checkout the Test repo on https://github.com/saigkill/Test
2. Go inside the project level (where the csproj lives)
3. Add-Migration Initial -c MyDBContext -o Data

In my case i'm getting:
Build started...
Build succeeded.

But no further stuff.

**Comment by ErikEJ** [comment]
Looks like you are mixing up powershell and dotnet command line options. 

If the issue remains please create a simpler repo and report to the EF Core repo, as this is not related to EF Core Power Tools.
