### ISSUE TITLE
Can't use DBContext Diagramm

### ISSUE THREAD

**Issue by lokutus777** [ErikEJ/EFCorePowerTools#1462]
Describe what is not working as expected.
Error on calling menu "Add DbContext Diagramm"

Error:
System.IO.FileNotFoundException: Could not load file or assembly 'PresentationFramework, Version=6.0.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Das System kann die angegebene Datei nicht finden.
File name: 'PresentationFramework, Version=6.0.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

### Provide steps to reproduce
choose in conext menu: EF Core Power Tools/Add DbContext Diagramm

Please include a **complete** description or project that I can redo/run to reproduce the issue.
new project for Framework: .net 6
use a direct connection to a MS SQL Server Database
use Reverese engineering
try to see the diagramm.

### Provide technical details

- EF Core version in use: (e.g. EF Core 6)
Framework: .net 6

- Is Handlebars used: no/yes
?

- Is .dacpac used: no/yes
no

- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
Version 2.5.1063.0

- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)
MS SQL Server 2019

- Visual Studio version: (e.g. Visual Studio 2022)
Version VS 2022

Thank you for your great work! :-)

Best regards,
Andreas

**Comment by ErikEJ** [comment]
Are you running the tool from the "correct" project - see the [wiki](https://github.com/ErikEJ/EFCorePowerTools/wiki/Inspect-your-DbContext-model#challenges)

**Comment by lokutus777** [comment]
Yes. It's not the executable project, it's another project. The project "DatabaseCore"  has DbContext and the entities and on that project I try to call the diagramm.

**Comment by ErikEJ** [comment]
So it works now or??

**Comment by lokutus777** [comment]
The error message is gone away but I don't see any entities.
I only see the base class of my DbConext ;-)

**Comment by ErikEJ** [comment]
I need a repro project from you in order to help

**Comment by lokutus777** [comment]
With Reverse Engineering we have created the  DbContext class NoRADbContext.
After that we changed the base class from DbContext zu NoRADbContextBase.
In that base class the sqlconnection is created OnConfiguring().

I have seen the diagramm after the follwing steps:
I have restored the base class for the autogenerated DbContext-class to DbContext.
I have trasfered the logic of my base class in the autogenerated DbContext class.
After that I see the diagramm.

**Comment by ErikEJ** [comment]
Cool, assume you are aware of ways to avoid making changes to the autogenerated files?

**Comment by lokutus777** [comment]
Not yet

**Comment by ErikEJ** [comment]
I have some advice here: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#extending-the-generated-dbcontext-class-and-entity-classes

**Comment by lokutus777** [comment]
I have restored the autogenerated DbContext class but with inheritance to our base class.
I moved it to a separate folder, away from the base class. 
Now the diagram works pretty well. Hurra! :-)

Thanks a lot for your quick response and your time. :-)
Have a nice weekend. 
God bless you.

Best regards and greetings from Germany,
Andreas

**Comment by lokutus777** [comment]
.... And now I know, that for both DbContext classes (autogenerated and base class) are made diagrams, one for each.
My changes has only changed the order how they are displayed ..... ;-)
