### ISSUE TITLE
Generated class configuration conflicts with entity class

### ISSUE THREAD

**Issue by nglara** [ErikEJ/EFCorePowerTools#1465]
In our application, we use tables called Exposure as the master table and we have ExposureConfiguration where we save the settings on how we use the Exposure. When I reverse engineer the database, EFPT generates configuration files along with the database context. Two examples of these configurations are ExposureConfiguration which is intended for Exposure entity and ExposureConfigurationConfiguration which is intended for ExposureConfiguration entity. 

### Provide steps to reproduce

- Right click on efpt.config.json
- Select database connection and click Ok
- Select tables and click Ok
- Dialog pops up and click Ok

## EFPT config:
   "CodeGenerationMode": 0,
   "ContextClassName": "MyContextBase",
   "ContextNamespace": null,
   "DefaultDacpacSchema": null,
   "FilterSchemas": false,
   "IncludeConnectionString": false,
   "ModelNamespace": null,
   "OutputContextPath": "BaseDataContexts",
   "OutputPath": "Models",
   "ProjectRootNamespace": "My.Report.TestData",
   "Schemas": null,
   "SelectedHandlebarsLanguage": 0,
   "SelectedToBeGenerated": 0,
   "UiHint": "Localhost\\SQLEXPRESS.My-Local",
   "UseBoolPropertiesWithoutDefaultSql": false,
   "UseDatabaseNames": false,
   "UseDbContextSplitting": false,
   "UseFluentApiOnly": true,
   "UseHandleBars": false,
   "UseHierarchyId": false,
   "UseInflector": true,
   "UseLegacyPluralizer": false,
   "UseManyToManyEntity": true,
   "UseNoConstructor": true,
   "UseNoDefaultConstructor": false,
   "UseNoNavigations": false,
   "UseNoObjectFilter": false,
   "UseNodaTime": false,
   "UseNullableReferences": false,
   "UseSchemaFolders": false,
   "UseSpatial": false

- EF Core version in use: (e.g. EF Core 5  and 6)

- Is Handlebars used: no

- Is .dacpac used: no

- EF Core Power Tools version: 2.5.1057

- Database engine: SQL Server

- Visual Studio version: VS Professional 2022

**Comment by ErikEJ** [comment]
You could rename the Entity?

**Comment by ErikEJ** [comment]
Using the built in renaming feature...
