### ISSUE TITLE
missing reference for Unicode attribute

### ISSUE THREAD

**Issue by naji-makhoul** [ErikEJ/EFCorePowerTools#1466]
i have a table class generated with EFCorePowerTools when it finish to generate all classes visual studio 2019 give me error:
"The type or namespace name 'Unicode' could not be found (are you missing a using directive or an assembly reference?)
"

```
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DBContext.Models
{
    public partial class Labels
    {
        [Key]
        public int LabelCode { get; set; }
        [Key]
        [StringLength(5)]
        **[Unicode(false)]**
        public string Language { get; set; }
        [StringLength(500)]
        public string Description { get; set; }
    }
}
```

EFCorePowerTools version : 2.5.1068.0

**Comment by ErikEJ** [comment]
You must use EF Core 6 in your project, I assume that is no the case (UnicodeAttribute was added in EF Core 6)

**Comment by naji-makhoul** [comment]
I use EF Core 5.0.17 with net core 5.0 right now , there is no option to ignore the Unicode attribute  ?

**Comment by ErikEJ** [comment]
Yes - pick EF Core 5 during [reverse engineering](https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#reverse-engineer---launch)

**Comment by naji-makhoul** [comment]
Tahnk you :)

**Comment by ErikEJ** [comment]
@naji-makhoul You are aware that EF Core 5 is no longer supported?

**Comment by naji-makhoul** [comment]
@ErikEJ yes i know ...  i will upgrade my project to .net 6.0  soon.. its on my task list when moving to visual studio 2022 next week

thank you
