### ISSUE TITLE
Option to generate many to many join tables explictly

### ISSUE THREAD

**Issue by robalexclark** [ErikEJ/EFCorePowerTools#1468]
I was using EF power tools recently to reverse engineer a db that had a basic join table with the two foreign key fields and no other fields. Reverse engineering this table omitted it from the context (as I would have expected) and generated a many to many between the generated entities. However in my app I struggled to get this to play nice with savechanges so in the end had to create a temp field in the db, reverse engineer and then delete out the field from the db and entities. Manually working with this entity was much easier than leaving it to the framework to figure out the updates (which it was doing incorrectly).

Can we please have an option to generate many to many join tables explictly as an entity, rather than them being omitted.

**Comment by ErikEJ** [comment]
It is there already in advanced options... how can I Make the docs better??

**Comment by ErikEJ** [comment]
Ping?

**Comment by robalexclark** [comment]
I see it now, along with other things in advanced that I should maybe try like nullable reference types

So part of the problem is that I didn;t look under Advanced to see this option, but also I don't know what some of these settings do. I looked at this github site for information on each but couldn't find it. Is it possible to add a link on each option to so extra information?

**Comment by ErikEJ** [comment]
It is [documented here](https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#choose-advanced-options) - but that option seem to be missing. I could add a link? (and also from the main options page)

**Comment by ErikEJ** [comment]
>> So part of the problem is that I didn;t look under Advanced to see this option,

Adding links to advanced dialog will not help if you did not open it...

**Comment by ErikEJ** [comment]
I will consider adding a link on the main options page...

**Comment by robalexclark** [comment]
I think a link from the main dialog to the wiki would be really useful - thanks.

**Comment by ErikEJ** [comment]
Added link to docs in latest daily
