### ISSUE TITLE
Feature Request: Multi-language support for pluralization

### ISSUE THREAD

**Issue by AdalbertKhoolsaat** [ErikEJ/EFCorePowerTools#1469]
Coming from [this blog post](https://erikej.github.io/efcore/2020/04/26/ef-core-pluralization.html), it could be of great help if EF Core Power Tools also supported pluralization in other languages than English, provided a Humanizer package for the desired language exists. 

The fact that using EF Core Power Tools for pluralization would not require adding any design code and NuGet packages to make this work, makes it much more preferable over going the EF Core-route with custom pluralization.

**Comment by ErikEJ** [comment]
Do you create code in C# with classes and properties in your native language??

**Comment by AdalbertKhoolsaat** [comment]
I do not, but sadly people before me have done so, both in the code they wrote as well as the code generated from tables/views and columns with non-English naming.

We are currently attempting to migrate and overhaul a particular internal API service on an older version of EF, but all the naming is to remain as-is. Otherwise it would impact an additional 25 services, and nobody likes that.

**Comment by ErikEJ** [comment]
Comments?

**Comment by ErikEJ** [comment]
Not something I plan to do.
