### ISSUE TITLE
Error when comparing modesl

### ISSUE THREAD

**Issue by weedkiller** [ErikEJ/EFCorePowerTools#1470]
Hello Erick, I am fan of your tools 👍🏾 

My goal is to create a new DB, given just the bare list of Models classes. So, I was trying to create a new DB from a project that already has the Models/Classes.

Before I began, I tried to run the Compare command, I keep getting the following error, can you please help. Am I doing something wrong, what are the steps to create a DB, from the list of the models using your tools.

![image](https://user-images.githubusercontent.com/21086190/183308555-4600b2ab-6b37-40c0-a3ba-a52e6a5f8d31.png)

**Comment by ErikEJ** [comment]
It sounds like you should use the ability to script the DbContext  as SQL in order to create the database (or just use Migrations)

**Comment by ErikEJ** [comment]
Ping?

**Comment by weedkiller** [comment]
Sorry let me clarify, first your tool is really a life saver.. it addresses some of the needs, I hope you grow it.


I have a list of models (POCO entities, CarModel, PersonModel.cs etc), I wanted to script the DB context from the namesspace of the models and then compare with DB.

_________

I tried this, to load the models from the ASP Core `models` namespace, and create it, rather _unsuccessfully_

```
protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            var entityMethod = typeof(DbModelBuilder).GetMethod("Entity");
            var theList = Assembly.GetExecutingAssembly().GetTypes()
                      .Where(t => t.Namespace == "DealerShip.Data.Models")
                      .ToList();
            foreach (var item in theList)
            {
                entityMethod.MakeGenericMethod(item)
                               .Invoke(modelBuilder, new object[] { });
            }
            base.OnModelCreating(modelBuilder);
        }
```

**Comment by ErikEJ** [comment]
I thin that is not a feature of this tool, you need to start with either a DbContext or an existing database.
