### ISSUE TITLE
Suggestion: improve name and description for the option to use `sp_describe_first_result_set`

### ISSUE THREAD

**Issue by IanKemp** [ErikEJ/EFCorePowerTools#1471]
The option appears as follows in Visual Studio 2022 (EF Core Power Tools 2.5.1068):

![image](https://user-images.githubusercontent.com/1726434/183432134-cd165cd2-3f75-4189-9ad0-03f8a9e8eaf7.png)

My suggestion is to update it to the following:

Text: "Allow alternate result set discovery" (I appreciate this is still quite wordy, especially compared to the other options, but it needs to be IMO)
Description: "Falls back to sp_describe_first_result_set if SET FMTONLY fails when attempting to retrieve stored procedure result sets" (from the description you used in #1346)

**Comment by ErikEJ** [comment]
Sounds helpful - interested in doing a PR?

**Comment by ErikEJ** [comment]
I am on it!

**Comment by ErikEJ** [comment]
The docs were wrong - it should be:

        [DisplayName(@"Use alternate result set discovery")]
        [Description("Use sp_describe_first_result_set to retrieve stored procedure result sets")]
