### ISSUE TITLE
Is it possible to rename generated entity files?

### ISSUE THREAD

**Issue by IanKemp** [ErikEJ/EFCorePowerTools#1476]
The Handlebars templates allow users to customise the generated entity **code**, but (as far as I can see) not the filenames. In my case I'd like to name the files as `<EntityType>.generated.cs` so that [Roslyn skips code analysis for these](https://docs.microsoft.com/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2022#configure-generated-code) - is this currently possible to configure?

* If so, please advise how.
* If not, please can this be upgraded to a feature request to add this capability?

**Comment by ErikEJ** [comment]
The generated files already have a header that prevents code analysis:

```xml
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
```

**Comment by IanKemp** [comment]
> The generated files already have a header that prevents code analysis:
> 
> ```
> // <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
> ```

Yes, but that can't be put in a `.gitignore` file, plus Roslyn has to actually open and inspect the file first to determine that it doesn't need to run analysis on it versus being able to skip that step by just going on the filename.

This is more of a question/feature request for a generic "customise generated filenames" function.

**Comment by ErikEJ** [comment]
> Roslyn has to actually open and inspect the file first to determine that it doesn't need to run analysis on it versus being able to skip that step by just going on the filename.

I am guessing that Roslyn has all file content available for it anyway.

This is not something I plan to implement and support.
