### ISSUE TITLE
Entities are not converted to pascal case when columns are renamed using json config

### ISSUE THREAD

**Issue by deraoryo3** [ErikEJ/EFCorePowerTools#1478]
At First, thanks and I love this tool.
 
### Provide steps to reproduce

My condition  is almost same as this issue.
[isusue1440](https://github.com/ErikEJ/EFCorePowerTools/issues/1440)
And table renaming works quite well for this closed issue, but column renaming don't work as table renaming do. 
With efpt.renaming.json, column name isn't converted into PascalCase.

- Without efpt.renaming.json
"PREFIX_APPLE_NAME" renamed into "PrefixAppleName"

- With efpt.renaming.json
"PREFIX_APPLE_NAME" renamed into "APPLE_NAME"
```json
[
   {
      "ColumnPatternReplaceWith": "",
      "ColumnRegexPattern": "PREFIX_",
      "SchemaName": "dbo",
      "TablePatternReplaceWith": "",
      "TableRegexPattern": "^.*?_",
      "Tables": [ ],
      "UseSchemaName": false
   }
]
```

### Provide technical details

- EF Core version in use: EF Core 6

- Is Handlebars used: no

- Is .dacpac used: no

- EF Core Power Tools version: 2.5.1068

- Database engine: (SQL Server)

- Visual Studio version: Visual Studio 2019

**Comment by ErikEJ** [comment]
Thanks for the kind words.

Can you share a sample CREATE TABLE script?

**Comment by ErikEJ** [comment]
I implemented a fix for this in the latest daily build, would be grateful if you could try it out.

I would be very grateful for a rating or review on Visual Studio Marketplace.

**Comment by ErikEJ** [comment]
I have reverted this fix, you must use an explicit column renaming instead.
