### ISSUE TITLE
Exception after VS update

### ISSUE THREAD

**Issue by alekoo73** [ErikEJ/EFCorePowerTools#1482]
System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at TView EFCorePowerTools.EFCorePowerToolsPackage.GetView<TView>()
   at async Task<bool> EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.ChooseDataBaseConnectionAsync(ReverseEngineerOptions options)
   at async Task EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.ReverseEngineerCodeFirstAsync(Project project, string optionsPath, bool onlyGenerate, bool fromSqlProj)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

After installing preview update VS 2022 Version 17.4.0 Preview 1.0

Power tools version 2.5.1068

 EF Core version 6.0

**Comment by ErikEJ** [comment]
Did it work with 17.2 / 17.3 ?

**Comment by ErikEJ** [comment]
Also, try to remove the %temp%\efpt folders and run again

**Comment by alekoo73** [comment]
> Did it work with 17.2 / 17.3 ?

Yes ,worked fine just before updating

**Comment by alekoo73** [comment]
> Also, try to remove the %temp%\efpt folders and run again

Tried , but the same result 

System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.DependencyInjection, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.Extensions.DependencyInjection, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at IServiceProvider EFCorePowerTools.EFCorePowerToolsPackage.CreateServiceProvider()
   at async Task EFCorePowerTools.EFCorePowerToolsPackage.InitializeAsync(CancellationToken cancellationToken, IProgress<ServiceProgressData> progress)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at TView EFCorePowerTools.EFCorePowerToolsPackage.GetView<TView>()
   at async Task<bool> EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.ChooseDataBaseConnectionAsync(ReverseEngineerOptions options)
   at async Task EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.ReverseEngineerCodeFirstAsync(Project project, string optionsPath, bool onlyGenerate, bool fromSqlProj)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

**Comment by ErikEJ** [comment]
Sorry, I meant %temp%\efreveng* folders

**Comment by ErikEJ** [comment]
OK, I am able to reproduce with 17.4 preview 1 - investigating....

**Comment by ErikEJ** [comment]
@aarnott Another binding redirect issue? (I will try to update to a newer version, but maybe it is a larger issue?)

**Comment by ErikEJ** [comment]
@alekoo73 

I have updated Microsoft.Extensions.DependencyInjection and Microsoft.Extensions.DependencyInjection.Abstractions to 5.0.0, and it seems to work with both 17.3 and 17.4.

I implemented a fix for this in the latest daily build, would be grateful if you could try it out.

I would be very grateful for a rating or review on Visual Studio Marketplace.

**Comment by alekoo73** [comment]
> Sorry, I meant %temp%\efreveng* folders

I'd deleted all the content of temp folder

**Comment by alekoo73** [comment]
> Microsoft.Extensions.DependencyInjection

![image](https://user-images.githubusercontent.com/16359687/184342588-6eb94d34-69e7-4224-8afa-ea4524e1c233.png)
There arae dependencies of my project ,All versions are last .Can't see why it is askking for old versions of Microsoft.Extensions.DependencyInjection.

**Comment by ErikEJ** [comment]
The dll is a dpedendency of the extension, not your project.

Please try the latest daily build.

**Comment by alekoo73** [comment]
> 



> The dll is a dedendency of the extension, not your project.
> 
> Please try the latest daily build.

I ve tried to reinstall extensions ,but results are the same .Even about dialog is not showing ,run as admin not helping either.

**Comment by ErikEJ** [comment]
Using the latest daily build?? https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f (version 1.0.1082)

**Comment by alekoo73** [comment]
> Using the latest daily build?? https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f (version 1.0.1082)

Really helped,thanks a lot.Why VS is not automatically installing latest version ,Should I always use this download page ?

**Comment by ErikEJ** [comment]
VS uses MarketPlace for "official" builds, and the on-going changes I make are published to VSIX Gallery - think of it as a way to post "preview" version with fixes. 

Once you confirm that it works for you, I will consider publishing to Marketplace.

I would be very grateful for a rating or review on Visual Studio Marketplace.

**Comment by AArnott** [comment]
@ErikEJ I don't see any binding redirects for Microsoft.Extensions.DependencyInjection.Abstractions at all in 17.4. Were there any before? I wonder if VS just happened to ship the version you needed (3.1) in 17.2, and then it upgraded the versions it consumed in 17.3, breaking you. I'll check whether 5.x is compatible with 3.1 and if so, a binding redirect sounds appropriate.

**Comment by AArnott** [comment]
Binary compatibility looks good. We should be able to add the binding redirect. Can you file a Feedback Ticket about this, @ErikEJ, and share the link here so I can route?

**Comment by ErikEJ** [comment]
@AArnott I have updated to 5 and it works in both 17.3 and 17.4

**Comment by AArnott** [comment]
That's fine, but it'll break again when VS upgrades this dependency again unless a binding redirect is in place. And if your own extension ever has an inconsistent dependency version, you'll be irreparably broken. For example if you depend on lib X which needs 5.0, and VS ships 6.0, even after you upgrade your own dependency to 6.0, lib X still wants 5.0, which not only doesn't ship with VS at that point, but you may need the 5.0 and 6.0 types to be seen by the CLR as equivalent.
