### ISSUE TITLE
Import Source Models into an power tools as a new dbContext

### ISSUE THREAD

**Issue by fasteddys** [ErikEJ/EFCorePowerTools#1484]
VS 2022

Hello Erik, I am very impressed with your features, I am trying a tool to see if I can speed up some work.

Can I please ask for some help here, we have a few legacy projects, where I am trying your tool to _upgrade into EF_. In the previous version, they used `Models/Entities` ,`ADO `with `SP's/StoreProcs`. 

As I upgrade _inside_ the `model `namespace, since we have all/list all the code/objects/entities/models without a DB context, can you add some help on `how to import those source/entities to the power tools/designer ` is it done by these methods? I apologize I was reading the help and could not figure it out, I think its not natively there, but if you can point me to some ideas I can try and do a PR

- [ ] by drag and drop 
- [ ] or right click import namespace
- [ ] or right click import the models/entities in the solution tree

What code should I look at to achieve this, do you have an event I could hook or code to, can you please give me some guidance on adding a list of objects from a names space into a new DBContext

**Comment by ErikEJ** [comment]
You can create a DbContext vlass and add the classes to it as DbSets - and then create a migration. 

It is limited how much Power Tools can help you with that.
