### ISSUE TITLE
Feature Request: Support efpt.postrun.ps1

### ISSUE THREAD

**Issue by JimF42** [ErikEJ/EFCorePowerTools#1485]
This is not an issue, but a feature request. You support executing a `efpt.postrun.cmd` command file. Please also consider supporting a `efpt.postrun.ps1` PowerShell file for those of us to prefer using PowerShell.

Not a huge deal for me, just a "nice to have".

**Comment by ErikEJ** [comment]
You should be able to do:

     PowerShell -File C:\TEMP\Script.ps1

or even

    pwsh -File C:\TEMP\Script.ps1

**Comment by JimF42** [comment]
True, it's that there needs to be two files instead of one. One cmd, one ps1.

**Comment by ErikEJ** [comment]
Yeah, but there is no simple way to just launch a powershell file.
