### ISSUE TITLE
Use column names from db with pluralizer

### ISSUE THREAD

**Issue by raman-kazhadub** [ErikEJ/EFCorePowerTools#1486]
I would like to use column names from database (e.g. UserID) with pluralizer. 
Before 2.5.1082 the following regexps in efpt.renaming.json worked for me:
 "ColumnPatternReplaceWith": "$0",
 "ColumnRegexPattern": "^.+$"

But they are not working now and it renames UserID to UserId. How can I fix this?

- EF Core version in use: EF Core 3 (because of .NET Framework)

- Is Handlebars used: no

- Is .dacpac used: no

- EF Core Power Tools version: 2.5.1082

- Database engine: SQL Server

- Visual Studio version: Visual Studio 2022

-  Use Database Names: no

- Use pluralizer: yes

**Comment by ErikEJ** [comment]
Can you share a repro schema and your desired outcome and I will have a look

**Comment by raman-kazhadub** [comment]
@ErikEJ 
SQL:
CREATE TABLE Users (UserID int);

efpt.config.json:
...
 "Tables": [
    {
      "Name": "[dbo].[Users]",
      "ObjectType": 0
    }]
    
efpt.renaming.json:
...
"ColumnPatternReplaceWith": "$0",
"ColumnRegexPattern": "^.+$"

Before 2.5.1082 version (Expected):
User.cs model with property UserID

2.5.1082 version (Actual):
User.cs class property UserId

**Comment by ErikEJ** [comment]
In order to preserve casing, you must add the exceptions to the renaming file:

```json
[
  {
    "UseSchemaName": false,
    "SchemaName": "dbo",
    "ColumnRegexPattern": "$0",
    "ColumnPatternReplaceWith": "^.+$",
    "Tables": [
      {
        "Name": "Users",
        "Columns": [
          {
            "Name": "UserID",
            "NewName": "UserID"
          }
        ]
      }
    ]
  }
]
```
You could potentially [automate this](https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#custom-renaming-with-efptrenamingjson) based on your existing database

**Comment by raman-kazhadub** [comment]
> In order to preserve casing, you must add the exceptions to the renaming file:
> 
> ```json
> [
>   {
>     "UseSchemaName": false,
>     "SchemaName": "dbo",
>     "ColumnRegexPattern": "$0",
>     "ColumnPatternReplaceWith": "^.+$",
>     "Tables": [
>       {
>         "Name": "Users",
>         "Columns": [
>           {
>             "Name": "UserID",
>             "NewName": "UserID"
>           }
>         ]
>       }
>     ]
>   }
> ]
> ```
> 
> You could potentially [automate this](https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#custom-renaming-with-efptrenamingjson) based on your existing database

We have 30 databases with 850 tables. This is not a good option

**Comment by ErikEJ** [comment]
I understand - but this was a bug fix none the less.

I am not good a regex - what are you tring to achive with it?  Seems you do not really need it !?

**Comment by raman-kazhadub** [comment]
> I understand - but this was a bug fix none the less.
> 
> I am not good a regex - what are you tring to achive with it? Seems you do not really need it !?

I just copied this trick from other issue. It was about Plurizer doesnt work with UseDatabaseNames option

**Comment by ErikEJ** [comment]
Try without, there were some changes for that with EF Core 6 I think.

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

**Comment by raman-kazhadub** [comment]
> I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

I have checked, it works fine now. Thank you a lot!
