### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by umityankarenbesofted** [ErikEJ/EFCorePowerTools#1495]
![Screenshot_1](https://user-images.githubusercontent.com/105009527/185642533-dc9175e2-9487-459c-8c36-5917f06a477b.png)

**Comment by ErikEJ** [comment]
Have you consulted the user guide?

https://github.com/ErikEJ/EFCorePowerTools/wiki/Inspect-your-DbContext-model

**Comment by umityankarenbesofted** [comment]
fixed

**Comment by ErikEJ** [comment]
Great, what was the issue? (Maybe the docs could be improved)
