### ISSUE TITLE
Extension did not load 

### ISSUE THREAD

**Issue by karenpayneoregon** [ErikEJ/EFCorePowerTools#1496]
Describe what is not working as expected.

First off, unsure if this was because of Visual Studio or not. Either way I resolved the following but wanted to it be known so feel free to close it.

### Provide steps to reproduce
Opened Visual Studio 2022, received message EF Power Tools did not load properly. All options from right clicking on Solution Explorer for EF Power Tools will not display.

**Note** The solution has 159 projects, on another attempt I opened a solution with two projects, same results.

Go to Visual Studio options, EF Power Tools page, see An error occurred loading this property page. 

Please include a **complete** description or project that I can redo/run to reproduce the issue.

After seeing "did not load properly" I tried to reverse engineer but nothing happened.

### Provide technical details

- EF Core version in use: (e.g. EF Core 6)

Both EF Core 5 and EF Core 6

- Is Handlebars used: no/yes
- 
No

- Is .dacpac used: no/yes

No

- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)

This dialog will not show

- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)

Never got here

- Visual Studio version: (e.g. Visual Studio 2022)

Visual Studio 2022, 17.3.0

This is a brand new computer, Windows 10, 32G ram.

I uninstalled EF Power Tools, reinstalled and ended up working

**Comment by ErikEJ** [comment]
#1492
