### ISSUE TITLE
VS market place rating

### ISSUE THREAD

**Issue by LKujala** [ErikEJ/EFCorePowerTools#1501]
Erik: I recently rated EF Core Power Tools in VS market place and you responded by asking what can be done to make it 5 star.

First: I have no idea how to respond to your comment on VS market place, which is why I am responding here (entirely inappropriate approach). 

Second: I have been using power tools for almost a year now; been through a few version upgrades of the tool. was using EF designer for EF6 for 10 years, just switched over to EF core last year. so that is what I am comparing power tools against.

Third: I have had a few instances where the code gen just bombed out; at that point the code is in a catch 22 state: until the code that caused the code gen to fail is fixed, the code gen wont work; but because the code gen failed cant fix the code that caused the code gen to fail. >> resolution is to use git to rollback changes to a known good state and reapply code changes until problem is resolved. (I dont have any examples to provide details).

Four: my main bug bear with all developers (including myself) is quality of documentation. This is something I nag all of my staff about.
* Quick Start is great
* documentation of options can be a bit better: what would help me is to see before / after code snips that show what a code option actually does: eg what code does the "default" setting generate (before) versus what code is generated with an option turned on (after). I can do this manually (and have) but figuring out functionality through trial and error chews up time.
* to me, good documentation is effectively the "regression test plan". If you regression test a feature, that feature needs to be in the documentation; and if a feature is in the documentation, it needs to be regression tested.

Five: the T4 template is the big thing I wanted to see... just noticed this is now available, but only for EFC7 (I am still working with EFC6). I am currently using Handlebar templates. Will be checking out the T4 templates.

**Comment by ErikEJ** [comment]
Thanks. There are not so many actionable items on your list. So Improved docs with sample code would be the main  thing. 

Thinking about the best format - a git based solution of some kind seems like a possible approach.

**Comment by LKujala** [comment]
Actually git could work.

  *   Have a Demo app.
  *   Enable each option, generate code, check in changes, tag it.
  *   To view results, walk the commit list

----------------------------------------
Lance Kujala
MBA, BSc, Acc.Dir

Driftwood Technology Inc
----------------------------------------

**Comment by ErikEJ** [comment]
Yeah. Have to think about how to compare with "vanilla" code though

**Comment by ErikEJ** [comment]
>> so that is what I am comparing power tools against.

Not really sure that is a vaild comparision - two completely different products

**Comment by LKujala** [comment]
For my purposes I need to reverse engineer a database into entities for both EF and EFC; that is the only functionality I am comparing. Power tools does a really good job of that.

**Comment by ErikEJ** [comment]
Thanks for the kind words!

**Comment by ErikEJ** [comment]
@LKujala  I have created a new issue for the docs improvements - looking forward to the review update ;-)
