### ISSUE TITLE
Uppercase always converted to PascalCase

### ISSUE THREAD

**Issue by Hamata6** [ErikEJ/EFCorePowerTools#1503]
Hi, we use your extension with great appreciation for some months now. 
Since version 2.5.1057 the reverse engineering of the database brings us problems: Multiple consecutive cases in table names as well as column names are since that version always converted to PascalCase.
Because we generated our Entities project months ago (with an old version of the extension), all our Entities are named as we want. But since version 2.5.1057 (because of #1440 I guess) it is always converted to PascalCase and we don't want that, because our code already uses the old Entity names. That would give us huge refactor work.
See screenshot below for an example.

![image](https://user-images.githubusercontent.com/24777262/187163997-245c47ba-f049-4ec7-bf06-c8e46147b418.png)

My suggestion would be to add an option to disable the conversion to PascalCase, because otherwise we have to refactor our whole code because of the naming problem. 
I do have an renaming.json that strips some prefixes like "tbl" of the table names, but adding renaming for around 1000 tables to that file is almost impossible.

I have seen #1489 and I tried with the latest daily build (2.5.1113) but it still does not work.

### Provide steps to reproduce
efpt.config.json
```json
{
    "CodeGenerationMode": 2,
    "ContextClassName": "MyDbContext",
    "ContextNamespace": null,
    "DefaultDacpacSchema": null,
    "FilterSchemas": false,
    "IncludeConnectionString": false,
    "ModelNamespace": null,
    "OutputContextPath": "Context",
    "OutputPath": "Models",
    "ProjectRootNamespace": "Entities",
    "Schemas": null,
    "SelectedHandlebarsLanguage": 0,
    "SelectedToBeGenerated": 0,
    "Tables": [//snip],
    "UiHint": "MyConnection",
    "UseBoolPropertiesWithoutDefaultSql": false,
    "UseDatabaseNames": false,
    "UseDbContextSplitting": true,
    "UseFluentApiOnly": true,
    "UseHandleBars": true,
    "UseHierarchyId": false,
    "UseInflector": true,
    "UseLegacyPluralizer": false,
    "UseManyToManyEntity": true,
    "UseNoConstructor": false,
    "UseNoDefaultConstructor": true,
    "UseNoNavigations": false,
    "UseNoObjectFilter": false,
    "UseNodaTime": false,
    "UseNullableReferences": true,
    "UseSchemaFolders": true,
    "UseSpatial": false
}
```

efpt.renaming.json (partial):
```json
[{
      "ColumnPatternReplaceWith": "",
      "ColumnRegexPattern": "^(vch|bit|dtm|int|dec|nvc|sin|chr|nch)",
      "SchemaName": "dbo",
      "TablePatternReplaceWith": "",
      "TableRegexPattern": "^tbl",
      "Tables": [ ],
      "UseSchemaName": true
}]
```

Example SQL:
```SQL
CREATE TABLE [dbo].[tblGGD](
	[vchThisIsUPPERCASE] [nvarchar](7) NULL
)
```

Expected output: `GGD.ThisIsUPPERCASE`

### Provide technical details

- EF Core version in use: EF Core 6

- Is Handlebars used: yes C#

- Is .dacpac used: no

- EF Core Power Tools version: 2.5.1057+ and also tried 2.5.1113

- Database engine: SQL Server

- Visual Studio version: Visual Studio 2022

**Comment by ErikEJ** [comment]
It is not Pascal case. 

I will investigate the issue, do not understand the column issue, has been reverted in the latest daily.

**Comment by ErikEJ** [comment]
I am not able to reproduce the column naming issue. Just added a test in latest commit.

Would a global option to remove proper casing when using regex be OK?

**Comment by Hamata6** [comment]
Thanks for your very quick reaction.

> It is not Pascal case.

I mean the output, the output of your extension is Pascal case right? My input indeed is random-case (you name it ;))

> I am not able to reproduce the column naming issue. Just added a test in latest commit.

Wait, let me check for the column issue. I'll reply soon.

**Comment by ErikEJ** [comment]
I have implemented a fix in the latest daily - notice there is a new option in Tools/Options relating to this

**Comment by ErikEJ** [comment]
Fix was broken...

**Comment by Hamata6** [comment]
@ErikEJ  Thanks for your fix. I download version 1116 and it works as expected after setting the new option at Tools>Options for this issue to true. Didn't know there were options hidden there. 

I guess the column name issue was part of the table name issue because that was fixed as well!

Last small question:
Is it possible to put that option in the efpt.config.json (because of version control) so that all our team members do not have to set this option manually?

Thank you so much!

**Comment by ErikEJ** [comment]
>> Is it possible to put that option in the efpt.config.json (because of version control) so that all our team members do not have to set this option manually?

Yes, I just wanted you to verify the fix first

**Comment by ErikEJ** [comment]
"PreserveCasingWithRegex": true option added in latest daily
