### ISSUE TITLE
DateTime not null if HasDefaultValueSql

### ISSUE THREAD

**Issue by panoskj** [ErikEJ/EFCorePowerTools#1504]
I can't open #876 but I am facing the same issue.

Simply create a table with a `datetime` column in SQL Server. Then set the default value of the column to `getdate()`. Finally, run Scaffold-DBContext on it.

The resulting model contains a `DateTime` property (edit: I would expect `DateTime?` here).

Now, if you use EF to insert a new instance into the table and its DateTime column has not been initialized explicitly, then the `default(DateTime)` value is inserted and you get an error from SQL Server.

One would expect that in this case, the `getdate()` function would be used as a default value.

You can see the expected behavior if you create a `bit` column and set its default value to `0` in SQL Server. In this case, Scaffold-DBContext will display the message:

> The column 'ColumnName' would normally be mapped to a non-nullable bool property, but it has a default constraint. Such a column is mapped to a nullable bool property to allow a difference between setting the property to false and invoking the default constraint. See https://go.microsoft.com/fwlink/?linkid=851278 for details.

So I would expect something similar for `datetime` columns as well.

**Comment by ErikEJ** [comment]
So as I asked for in #876 - please provide a full example.

**Comment by panoskj** [comment]
You are right. I tried to make a minimal example and it worked as intended. I can't figure out how I came across this.
