### ISSUE TITLE
Improve docs with code samples

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#1505]
TODO:

- [x] custom sub-namespace for DbContext class (by default path will be used)
- [x] optional subfolder path for entity classes in the current project (for example Models)
- [x] optional subfolder path for DbContext class in the current project, or even a full path to anywhere on your disk
- [x] pluralize or singularize generated names (entity class names singular and DbSet names plural)
- [x] use table and column names from the database
- [x] to use DataAnnotation attributes rather than the fluent API (as much as possible)
- [x] to not include the current connection string in the generated code
- [x] optionally add the relevant EF Core packages to the project

/cc @LKujala

**Comment by ErikEJ** [comment]
@lkujala I have created the first sample - please have a look at let me know what you think about the format (and content)

Link in main docs: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#choose-options

Sample: https://github.com/ErikEJ/EFCorePowerTools/blob/master/samples/context_name/sample.md

**Comment by LKujala** [comment]
Erik:

Yes: that is exactly what I was looking for.

For example, there are a number of links explaining options: { Namespace. Entity Type Path, Entity Type sub-namespace, db context path, db context sub-name space} (Update Reverse Engineering wiki page · Issue #290 · ErikEJ/EFCorePowerTools (github.com)<https://github.com/ErikEJ/EFCorePowerTools/issues/290#issuecomment-543131112> …. If these examples are bundled up into the before / after that is great.

The other documentation approach I like to emphasize is the: “why” does this option exist and “why” you should (or should not) change it.
For example: Entity Types Path.
I set this option to organize the project folder structure so “generated” code is separated from “hand written” code.
This becomes a visual indicator of what code can be modified directly and what code is updated through code generation templates.



----------------------------------------
Lance Kujala
MBA, BSc, Acc.Dir

778.838.0877
Driftwood Technology Inc
----------------------------------------

**Comment by ErikEJ** [comment]
TODO:

- [ ] custom sub-namespace for DbContext class (by default path will be used)
- [ ] optional subfolder path for entity classes in the current project (for example Models)
- [ ] optional subfolder path for DbContext class in the current project, or even a full path to anywhere on your disk
- [ ] pluralize or singularize generated names (entity class names singular and DbSet names plural)
- [ ] use table and column names from the database
- [ ] to use DataAnnotation attributes rather than the fluent API (as much as possible)
- [ ] to not include the current connection string in the generated code
- [ ] optionally add the relevant EF Core packages to the project

**Comment by ErikEJ** [comment]
@LKujala This has now been implemented, looking forward to an updated review ;-)

**Comment by LKujala** [comment]
for the "path" examples, its not blindingly obvious that the filename now includes the folder as well.
on the "pluralize" example you added a comment after the file name... this helps focus attention on what is different. (initially I was just looking at the code not the file name).

I like the code examples. keeps the main document concise, but demonstrates how the option(s) function.

**Comment by ErikEJ** [comment]
@LKujala Feel free to create a PR  - all files are in the /samples folder

**Comment by ErikEJ** [comment]
@LKujala I have added a not about the file move - looking forward to an updated review ;-)
