### ISSUE TITLE
Reverse Engineer - Additional Provider Support

### ISSUE THREAD

**Issue by knight1219** [ErikEJ/EFCorePowerTools#1506]
Is there a way currently to provide additional database provider support through a custom provider library? Like could I build a provider that enabled DB2 support for the Reverse Engineer tool that would appear in the "Custom Connections" dialog drop down.

### Provide technical details

- EF Core Power Tools version: 2.5.1088.0

- Database engine: Db2

- Visual Studio version:  Visual Studio 2022 preview

**Comment by ErikEJ** [comment]
There sure is, all the tool needs is a .NET (Core) based provider that supports the EF Core Reverse engineering APIs. And someone to test the implementation!
