### ISSUE TITLE
Reverse Engineering: Foreign Keys ON DELETE behaviour not set

### ISSUE THREAD

**Issue by ChristofColle-VIVES** [ErikEJ/EFCorePowerTools#1507]
The "**ON DELETE CASCADE**" definition in SQL doesn't translate to a **.OnDelete(DeleteBehavior.Cascade)** statement in EFCore.

### Provide steps to reproduce

Create 3 tables. 
Tables B & C should have a foreign key reference to table A.
**Don't** provide a ON DELETE definition for the FK on table B.
The FK in table C however should be defined with **ON DELETE CASCADE**.

Reverse Engineer your DB tables with EF Core Power Tools.
Compare the generated EF code for tables B & C.

The FK on table B will have a **.OnDelete(DeleteBehavior.ClientSetNull)** statement.
The FK on table C won't have any .OnDelete(...) statement.

### Provide technical details

- EF Core version in use: EF Core 6

- Is Handlebars used: no

- Is .dacpac used: no (generated from a SQL Server Database Project)

- EF Core Power Tools version: 2.5.1088.0

- Database engine: SQL Server

- Visual Studio version: Visual Studio 2022 Community Edition

**Comment by ErikEJ** [comment]
I think the default values are not generated in code.
