### ISSUE TITLE
Generate Migration Builder Code from EfPowertools

### ISSUE THREAD

**Issue by Diaskhan** [ErikEJ/EFCorePowerTools#1509]
Hi gyues.

I have one idea, and few questions.

First for all great thanks to U.

1.For example we have two colums in table.

It possible to generate from Interface  column folowwing code
```
migrationBuilder.AlterColumn<Guid>(
    name: "OrganisationToId",
    table: "Interactions",
    nullable: false);
```
And create column statement.

2.For example we have two indexes.
It possible to generate this code
```
migrationBuilder.CreateIndex(
    name: "IX_Interactions_OrganisationToId",
    table: "Interactions",
    column: "OrganisationToId");
```

this functionality has needed, it make some routine procedures easier to handle.

Its almost the same as SMSS tool
![image](https://user-images.githubusercontent.com/15046677/187966918-22ccefdc-3efd-4a08-8b48-6ae7b03ae91c.png)

but for ef core, not for SQL

**Comment by ErikEJ** [comment]
I do not understand the use case. There is a dedicated migrations feature in the tool.

**Comment by Diaskhan** [comment]
The case is foollowing.

Sometimes we create different indexes in Dev DB. 
and trying to realize wich index is best, sometimes need to change i size of column 
(for example change nvarchar(max) to nvarchar(450), to create composite index)

And after all manipulations and otpimizations, i need to generate some typical code
```
migrationBuilder.AlterColumn<Guid>(
    name: "OrganisationToId",
    table: "Interactions",
    nullable: false);
```

**Comment by ErikEJ** [comment]
Why not just update your model configuration  and create a new migration??
