### ISSUE TITLE
SQLite database contains no objects

### ISSUE THREAD

**Issue by rkreisel** [ErikEJ/EFCorePowerTools#1510]
Trying to reverse engineer a Sqlite db. Walking through the dialog boxes 
I am trying to add a new connection.
I choose SqlIte Provider and click Ok.
I then specify the connection string to the file (Data Source=_MyDBname_.db). I click Test and it reports success. 
Then I click Ok and get an error "Unable to find the requested .Net Framework Data Provider. It may not be installed."

In my various attempts to get it to work I have installed a boatload of Nuget packages. But I may still be missing some.
`
   <ItemGroup>
        <PackageReference Include="AutoMapper" Version="11.0.1" />
        <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="11.0.0" />
        <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
        <PackageReference Include="Devart.Data.SQLite.EFCore" Version="6.0.0" />
        <PackageReference Include="MailKit" Version="3.3.0" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="6.0.8" />
        <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="6.0.8" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.8">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="6.0.8" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
        <PackageReference Include="System.Data.SQLite" Version="1.0.116" />
        <PackageReference Include="System.Data.SQLite.Core" Version="1.0.116" />
        <PackageReference Include="System.Data.SQLite.EF6" Version="1.0.116" />
        <PackageReference Include="System.Data.SQLite.EF6.Migrations" Version="1.0.112" />
        <PackageReference Include="System.Data.SQLite.Linq" Version="1.0.116" />
        <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.22.1" />
    </ItemGroup>` 

### Provide technical details
EF Core 6.x
Handlebars used: no
.dacpac used: no
EF Core Power Tools version: 2.5
Database engine: SQLite
Visual Studio version: 2022 (17.3.2)

This is a brand new machine and all the dev software has been recent loaded. 
The .net dev tools were exclusively .net 6, until I noticed that the error message referes to .net framework, so I installed the 4,8 framework dev tools as well.
I am trying to create a .Net 6 console app at the present (just to eliminate as many variables as possible for diagnosis)

**Comment by ErikEJ** [comment]
How are you adding a new connection?

 Have you tried installing VS.data.sqlite?

Have you tried a custom connection?

In other words which DDEX / custom provider are you using?

Maybe share screenshots?

**Comment by ErikEJ** [comment]
I suspect you are pointing to an empty database file. Make sure to use a full path in your connection string, not just the file name.

**Comment by ErikEJ** [comment]
Where did you press Test ? I cannot not see a Test button on the Custom Connection form.

Could you share a screen shot (by replying on the Github repo, not via email)

**Comment by ErikEJ** [comment]
I have created https://github.com/bricelam/VS.Data.Sqlite/issues/30 - please let me know if I misunderstood you last message.

**Comment by rkreisel** [comment]
I was referring to the reason I didn’t think to use the full path when I was trying with the built-in Sqlite connection. ☹

**Comment by ErikEJ** [comment]
Got it - as I wrote the VS.Data.Sqlite fix should help

**Comment by ErikEJ** [comment]
@rkreisel This is fixed in the latest version of the VS.Data.Sqlite DDEX provider, update it in VS.

https://github.com/bricelam/VS.Data.Sqlite/commit/820824967f084aed6476c8193121a32bfb2a42e2
