### ISSUE TITLE
multiple database

### ISSUE THREAD

**Issue by Zeshan-Munir** [ErikEJ/EFCorePowerTools#1513]

**Comment by Zeshan-Munir** [comment]
Mistakenly opened.

**Comment by Zeshan-Munir** [comment]
@ErikEJ 
Sorry, I was searching an old issue where the multiple database configs stuff was discussed a while ago. While searching not sure how did I ended-up opening this.

Can this be deleted?

**Comment by ErikEJ** [comment]
No problem, I just closed it
