### ISSUE TITLE
Question - plugin for VS for Mac/Jetbrains Rider

### ISSUE THREAD

**Issue by fepettersen** [ErikEJ/EFCorePowerTools#1516]
Hi
Sorry if this is documented somewhere where I cannot find it.

We have a new colleague on our team who is using mac. He was not able to install the EF Core power tools plugin in VS for mac. Is there a separate build for VS for mac (and/or Jetbrains Rider)?

Regards

**Comment by ErikEJ** [comment]
The extension is only available for Visual Studio on Windows. 

It is possible to extract the command line based tooling and run it as [a command line tool](https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#requirements)

**Comment by fepettersen** [comment]
Okay, thanks. Maybe I will look into this myself if I get the time :) Thanks for an awesome tool!

**Comment by ErikEJ** [comment]
For Rider, I think there is a tool to launch reverse engineering...

**Comment by ErikEJ** [comment]
For anyone watching this issue, this is now planned, and you can find a design proposal [here](https://github.com/ErikEJ/EFCorePowerTools/issues/1751) - looking forward to any comments/suggestions.
