### ISSUE TITLE
Option to not overwrite models, when reverse-engineering?

### ISSUE THREAD

**Issue by herrbehn** [ErikEJ/EFCorePowerTools#1517]
I use EF CorePowerTools only to generate classes for stored procedures. I maintain models for the tables myself, but if I deselect tables in the checkbox when using reverse engineering, the model-classes are deleted. If I keep the tick in the checkbox, they get overwritten which is not what I want (I have for instance added enums to certain columns instead of their database datatype int).
Could this be a future option please?

**Comment by ErikEJ** [comment]
There are multiple ways to handle this already: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#saving-options-and-running-the-second-time

There is also the Tools/Options option: 
"Run Cleanup of Obsolete files: Set this to false if you do not want to have the tool to remove files that are no longer in use."

https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#advanced-visual-studio-options

**Comment by ErikEJ** [comment]
>> I have for instance added enums to certain columns instead of their database datatype int

You can do that in a partial class.

**Comment by ErikEJ** [comment]
Ping?
