### ISSUE TITLE
Question - override "Prefer async calls" for specific procedure import

### ISSUE THREAD

**Issue by devuros** [ErikEJ/EFCorePowerTools#1518]
Hi,

I was reading through the documentation. I saw there is an option in Visual Studio settings to "Prefer async calls" when reverse engineering stored procedures. I works without a hitch, but I have one procedure that I would like to call synchronously. Is it possible to do change it in the json settings like it is for "Use alternate result set discovery" per database object?

Many thanks,
Uros

**Comment by ErikEJ** [comment]
This is not something I plan to do, you can just generate and preserve the async code in a partial class, and then generate sync code.

**Comment by devuros** [comment]
Thank you very much for the quick reply! I did just as you suggested.
