### ISSUE TITLE
Support usage without installation of the Oracle Developer Tools for Visual Studio

### ISSUE THREAD

**Issue by jackmang** [ErikEJ/EFCorePowerTools#1522]
Currently, as far as I can determine, you MUST install the ODT for Visual Studio in order to use the EFCorePowerTools for an Oracle database.  My presumption is that this is required in order to support setting up the connection using the VS server connection tool GUI bits.  I have found that the scaffolding tool that is supplied by VS using power shell, which I believe the Power Tools are based on somehow, does not require the ODT for Visual Studio.  You can simply include the connection string in the command line.

Would it be possible to do something similar for the Power Tools?  The connection string could be in the json file perhaps?

This is particularly applicable to Oracle because they usually take a year or more to release an ODT for VS when a new version of VS is released.  This means I'm always needing to use the older version of VS when working with EF for an Oracle DB.

### Provide steps to reproduce

This works (but not as well as EFCorePowerTools):
VS2022
Scaffold-DbContext "Data Source=myOracleDb:1521/myinstance;User Id=mydbuser;Password=password" Oracle.EntityFrameworkCore -Context MyContext -schemas MYSCHEMA

Using the EFCorePowerTools in VS 2022 does not work because the connection generation GUI doesn't have the options for Oracle and Oracle Managed driver.  There is an option to use the Microsoft driver, but the notes on that specifically tell you not to use it and to install the ODT for VS.  There is no ODT for VS 2022 available at this time.

Using the EFCorePowerTools in VS 2019 works, but only if you install the ODT for VS.

I sure hope I haven't missed something and waste you time here.  :)

Great tool, especially for SQL Server.  % star review submitted.

### Provide technical details

- EF Core version in use: EF Core 6

- Is Handlebars used: no

- Is .dacpac used: no

- EF Core Power Tools version: 2.5.1142.0

- Database engine: Oracle

- Visual Studio version: 2022

**Comment by ErikEJ** [comment]
You should be able to use a custom connection as described in the docs: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#choose-data-source - so just a connection string

**Comment by jackmang** [comment]
I will try that again.  It wasn't working for me this morning, but maybe I missed a parameter.

**Comment by ErikEJ** [comment]
Please do. Let me know how I can improve the sample connection string.

**Comment by jackmang** [comment]
As one might expect, you are correct.  That worked.

I used the same connection string as in my Issue description.
1 - Selected "Add Custom Connection" as described in the wiki and then
2 - Gave it a name
3 - Selected "Oracle" from the drop-down
4 - Used a connection string in this format:
     Data Source=myOracleHostName:1521/MyInstanceName;User Id=mydbuser;Password=password

The only difference, as we are discussing, is that I don't have the ODT for VS installed (since it doesn't exist for VS2022).

It might be helpful to populate the "Sample" field on the "Add Custom Connection" dialog with something.  The sample value is blank for Oracle and MySQL.

Thank you for your patience and an excellent and free tool.  I can't imagine what it is like for an individual to provide such good support for something like this.
5 Stars!

**Comment by ErikEJ** [comment]
The missing samples was a bug, fixed in latest daily.

I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details)

**Comment by jackmang** [comment]
> The missing samples was a bug, fixed in latest daily.
> 
> I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details)

Already did.  5 Stars
