### ISSUE TITLE
Feature Suggestion for Model Namespace

### ISSUE THREAD

**Issue by FeraMJ** [ErikEJ/EFCorePowerTools#1524]
Describe what is not working as expected.

### Provide steps to reproduce

Please include a **complete** description or project that I can redo/run to reproduce the issue.

### Provide technical details

- EF Core version in use: (e.g. EF Core 6)

- Is Handlebars used: no/yes

- Is .dacpac used: no/yes

- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)

- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)

- Visual Studio version: (e.g. Visual Studio 2022)

**Comment by FeraMJ** [comment]
Hello. I have a specific use case where the models of a specific API controller are used throughout the app, and it is therefore useful to have them in the root namespace (rather than add "using" lines to every class). The EF Core PowerTools allows for custom namespaces for models. That is great. The limitation is that it only allows "sub-namespaces".

If there were a "use root" option, that would be great. In the example below, I enter "DELETE" and then search/replace it out each time I rerun Reverse Engineering.

![image](https://user-images.githubusercontent.com/113781143/191636855-3ec23a9e-8490-4cac-879e-45c76133f0f7.png)

**Comment by ErikEJ** [comment]
So you want the namespace for the entities to be "Codify" and the DbContext namespace should be "Codify.Areas.Core.Data" ??

**Comment by ErikEJ** [comment]
I think you can leave the "Namespace" text box empty, and define an explict namespace for Entity and DbContext in the sub-namespace text boxes

**Comment by FeraMJ** [comment]
You are correct. That did the job. Thanks again!

![image](https://user-images.githubusercontent.com/113781143/191726550-1d7c675b-907e-4aa1-b566-b63f1ddc8b6b.png)

**Comment by ErikEJ** [comment]
I have added this example to the docs
