### ISSUE TITLE
Need old build (version)

### ISSUE THREAD

**Issue by gbthakkar** [ErikEJ/EFCorePowerTools#1526]
Since I have EF core version 5 on the project. New version does not show the EF 5 in the dropdown now.
So I think I need to go back to old version of EF core power tool.

But I could not find source where I can download the old version.

Please guide

Describe what is not working as expected.

### Provide steps to reproduce

Please include a **complete** description or project that I can redo/run to reproduce the issue.

### Provide technical details

- EF Core version in use: (e.g. EF Core 5)

- EF Core Power Tools version: (2.5.1142.0)

- Database engine: (SQL Server 2012)

- Visual Studio version:  2022

**Comment by ErikEJ** [comment]
That sounds like a bug. Please share your .csproj file.

**Comment by gbthakkar** [comment]
Hi,

Thank you for your quick response
here is the csproj file

<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference
Include="AutoMapper.Extensions.Microsoft.DependencyInjection"
Version="11.0.0" />
    <PackageReference Include="BoldReports.Net.Core" Version="4.1.86" />
    <PackageReference
Include="Microsoft.AspNetCore.Components.DataAnnotations.Validation"
Version="3.2.0-rc1.20223.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore"
Version="5.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design"
Version="5.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers;
buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer"
Version="5.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools"
Version="5.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers;
buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="Syncfusion.Blazor.Calendars"
Version="19.4.0.40" />
    <PackageReference Include="Syncfusion.Blazor.PdfViewerServer.Windows"
Version="19.4.0.40" />
    <PackageReference Include="Syncfusion.Blazor.RichTextEditor"
Version="19.4.0.40" />
    <PackageReference Include="Syncfusion.Pdf.Net.Core" Version="19.4.0.40"
/>
    <PackageReference Include="Syncfusion.XlsIO.Net.Core"
Version="19.4.0.40" />
  </ItemGroup>

<ItemGroup>
<None Include="ReportsFiles\**">
<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
</None>
</ItemGroup>


</Project>




*Regards,*

*Gaurang Thakkar*

**Comment by ErikEJ** [comment]
Fixed in latest daily build. 

I assume you are aware that EF Core 5 is no longer supported (since may 2022)

**Comment by gbthakkar** [comment]
Hi,

Thank you so much for the quick fix. The new build works great now.

I assume you are aware that EF Core 5 is no longer supported (since may
2022) - oh, I will upgrade the project to EF 6.Thanks

*Regards,*

*Gaurang Thakkar*

**Comment by fbessone** [comment]
Hi,

** dumb question warning **

i have the same issue: i have a solution with 4 projects and one (the one that holds viewmodels, entities etc) is still on EF Core 5,
If i install the extension from Market Place i get the  **2.5.1142** version of 17/09/2022 which still misses the EF Core 5 option.
How can i apply this fix?

Thanks
--

**Comment by gbthakkar** [comment]
Yes, that is correct.

with latest fix (nightly build) it works now....

*Regards,*

*Gaurang Thakkar*

**Comment by fbessone** [comment]
:) Thanks
How can i do that? Googling around i found another extension (Open VSIX Gallery) that should permit it.
Is there a clever solution without using another extension?
Thanks!

**Comment by ErikEJ** [comment]
@fbessone there is a link to the latest daily build in the release notes and redme here. It will solve your issue. 

You really should upgrade to EF Core 6 as EF Core 5 is no longer a supported product.

**Comment by gbthakkar** [comment]
Hi fbessone,

That is not another solution but the nightly build version.
You are having 2.5.1142 and this is 2.5.1145. Go get it and it will work.

Below is the direct link for the same.
https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f


*Regards,*

*Gaurang Thakkar*

**Comment by fbessone** [comment]
Hi @ErikEJ and @gbthakkar 
thanks for helping me!
I never had the need to dig in nighly builds and i was a bit lost

I'll upgrade as soon as i fix an upgrade conflict
Again, thanks to both of you!

Regards
