### ISSUE TITLE
Pascal Case Issue

### ISSUE THREAD

**Issue by arkhokhar** [ErikEJ/EFCorePowerTools#1527]
I want to create database table classes names in Pascal Case in VS2022 with MySQL, my tables name in lowercase in MySQL.

I am using latest version EF Core Power Tools. please help

##Current
Userlogin.cs

##Required
UserLogin.cs

**Comment by ErikEJ** [comment]
Userlogin.cs is not "lowercase" ??

I think your only option is to use the renaming feature.
