### ISSUE TITLE
When using DataAnnotations, Index dataAnnotation is ambigious defined

### ISSUE THREAD

**Issue by TimKras** [ErikEJ/EFCorePowerTools#1528]
- EF Core 6

- Is Handlebars used: yes

- Is .dacpac used: no

- EF Core Power Tools version: 2.5.1142

- Database engine: SQL Server

- Visual Studio version: Visual Studio 2022

![image](https://user-images.githubusercontent.com/5257192/193006754-f9135763-aefe-41a5-8466-fbb769be218d.png)

**Comment by ErikEJ** [comment]
I guess you are mixing the code generation version and the EF Core package in use in your project...

**Comment by TimKras** [comment]
@ErikEJ I don't think so.
Started from a new project, I was able to reproduce the problem.
- ![image](https://user-images.githubusercontent.com/5257192/193101470-b03540a3-2ad1-4d26-a32e-9526f19dc852.png)
- Add a reference to LinqKit to the project:
`  <ItemGroup>
	  <PackageReference Include="LinqKit" Version="1.2.2" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.9" />
  </ItemGroup>`

When you remove the reference to LinqKit the error is gone...

**Comment by ErikEJ** [comment]
You are using a package that depends on EntityFramework.

That will not work together with EF Core.
