### ISSUE TITLE
Compilation issue for recent version of the tools for SQL Server temporal tables only

### ISSUE THREAD

**Issue by rhubarbjustin** [ErikEJ/EFCorePowerTools#1529]
### Provide steps to reproduce
Great product! but one of the recent versions causes a compilation issue on my existing project for SQL Temporal Tables only. I came back to a project after a month or so, so I'm not sure which version caused the issue. Is there any way for me to download historical versions as a temporary measure? Many thanks.

### Provide technical details
See this image of the context.cs file

![XCycfDPDGC](https://user-images.githubusercontent.com/64858761/193265238-ce71374f-03d4-4526-b6ce-3c3fc3da658e.png)

- EF Core version in use: (e.g. EF Core 6)
EF Core 6
- Is Handlebars used: no/yes
No
- Is .dacpac used: no/yes
No
- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
2.5.1142.0
- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)
SQL Server 2017
- Visual Studio version: (e.g. Visual Studio 2022)
2022

**Comment by ErikEJ** [comment]
You are most likely mixing code generation version and runtime version.

Please share your .csproj and efpt.config.json

**Comment by rhubarbjustin** [comment]
Hi. Here they are:

[ManagementSystem.Data.csproj.txt](https://github.com/ErikEJ/EFCorePowerTools/files/9685506/ManagementSystem.Data.csproj.txt)
[efpt.config.json.txt](https://github.com/ErikEJ/EFCorePowerTools/files/9685507/efpt.config.json.txt)

Thanks

**Comment by ErikEJ** [comment]
You need the latest daily build and then pick EF Core 5. Please note that EF Core 5 is no longer supported since May this year.
