### ISSUE TITLE
What determines whether System.Data.SqlClient or Microsoft.Data.SqlClient is used?

### ISSUE THREAD

**Issue by CaiusJard** [ErikEJ/EFCorePowerTools#1531]
Having real trouble using EFCPT with SQLAzure and Active Directory Interactive auth, but on only one of our dev machines; the others are all fine

### Provide steps to reproduce

We perform a reverse engineer in a NET6 console app project, using EFCPT. We perform it side by side on two machines that are similar (same versions of VS2022, EFCPT etc, but they are used by different people for slightly different things, dev wise, and do have some differences in installed softwares, such as PowerBI)

We add custom connection; use the sample provided for SQLAzure but modify it for our particular DB (host name, database name, username), ensure the value of Auth= parameter is _Active Directory Interactive_

One of them can reverse a DB just fine, the other fails with an error:

```
System.ArgumentException: Cannot find an authentication provider for 'ActiveDirectoryInteractive'.
   at SqlFedAuthToken System.Data.SqlClient.SqlInternalConnectionTds.GetFedAuthToken(SqlFedAuthInfo fedAuthInfo)
   at void System.Data.SqlClient.SqlInternalConnectionTds.OnFedAuthInfo(SqlFedAuthInfo fedAuthInfo)
   at bool System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, out bool dataReady)
   at bool System.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
   at void System.Data.SqlClient.SqlInternalConnectionTds.CompleteLogin(bool enlistOK)
...
```

I've encountered issues before with older versions of the SqlClient library not understanding "ActiveDirectoryInteractive" - I think it has to be at least V2.1 - but even installing V5 from nuget into the project, still brings errors that mention System.Data.SqlClient rather than Microsoft.Data.SqlClient and the error message doesn't change. Other forms of AD auth seem supported on this particular machine but the puzzle is why interactive doesn't work properly here, when it does elsewhere

Is the wrong client lib being used here? How is it being picked up? Is there something that needs uninstalling? 

### Provide technical details

- EF Core version in use: EF Core 6

- EF Core Power Tools version: vLatest (20/09/2022)

- Database engine: Azure SQL

- Visual Studio version: Visual Studio 2022 17.2.6

**Comment by CaiusJard** [comment]
As a followup investigation to this we made EFCPT work by using ActiveDirectoryPassword, and putting the user's password into the custom conn str in EFCPT. We ticked on "put the connnection string in code" then changed the code by removing the password=xxx and altering the auth value to ActiveDirectoryInteractive. The code works fine; the app runs and a web browser appears and prompts for auth, then the app continues when auth is granted

We copied proven-working the connection string back into EFCPT's custom dialog when adding another connetion, but it still doesn't work in EFCPT Reverse:

If the Auth parameter value is ActiveDirectoryInteractive (with no spaces), the error message is "Invalid value for Authentication parameter". If the Auth parameter value is Active Directory Interactive (with spaces), the error message is "Cannot find an authentication provider for 'ActiveDirectoryInteractive'"

I'm now reasonably convinced EFCPT is using a wrong or old client library, but where is it getting it from and how can it be changed?

**Comment by ErikEJ** [comment]
System.Data.SqlClient is used for some rights validation and this check should be skipped for Azure connections but due to the missing spaces in the keyword it is not. 

I will fix that.

The auth error you are getting is most likely due to a bad VS azure auth configuration on the single machine facing issues.

**Comment by CaiusJard** [comment]
How do I fix or manipulate "a bad VS azure auth configuration" - are we saying that VS itself is signed into the Azure AD, and there is some problem with that/we need to reset or re-enter credentials?

**Comment by ErikEJ** [comment]
I think you can check in Tools/Options...

**Comment by ErikEJ** [comment]
Actually: ActiveDirectoryIntegrated is not a valid connection string key value.
