### ISSUE TITLE
Feature Request: Add tickbox to suppress default constructor generation in the context

### ISSUE THREAD

**Issue by CaiusJard** [ErikEJ/EFCorePowerTools#1532]
Reverse engineering generates a partial class for the context, and I leverage this to have another partial elsewhere that has a constructor thus:

        public MyContext(DbContextOptions<MyContext> options) : base(options)
        {
            Database.SetCommandTimeout(120);
        }

Minor problem is that every time I do a reverse, the generated partial class gains an empty constructor with the same signature, and I have to delete it

It'd be nice to have some configurable way of disabling this constructor generation, or have that generated constructor call some other partial method that I can provide an implementation of

**Comment by ErikEJ** [comment]
I think there is already an advanced option for that; https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#choose-advanced-options

**Comment by ErikEJ** [comment]
You can also set the command timeout via the connection string these days (a feature I implemented for SqlClient)

**Comment by CaiusJard** [comment]
By the way, I didn't get any joy specifying the command timeout in the connstr for a reverse:

![image](https://user-images.githubusercontent.com/68939130/194113534-00a4d116-b238-45d9-8dc7-153556312300.png)

MSDN mentions it in relation to Microsoft.Data.SqlConnection:

![image](https://user-images.githubusercontent.com/68939130/194113857-92e6463f-e028-4e63-8b2d-bec6c723aed2.png)

but the System.Data.SqlConnection does not appear to make a similar observation, or even have a timeout relating to commands. I note the error message in the extensions window comes from System.Data rather than Microsoft.Data, so essentially I think I cannot set this parameter in EFCPT for EFCPT to put it into the code, but presumably I can use it in my code (supply my own, slightly different conn str to code, after I do a reveng without this keyword)

**Comment by ErikEJ** [comment]
You can set it during runtime! (But not design time) - but that should not be a problem???

**Comment by CaiusJard** [comment]
Yeap, that's what I'll do - sometimes I'm lazy and tick the box to let EFCPT do it for me (especially with ActiveDirectoryInteractive, so there are no passwords in code) into the context...
