### ISSUE TITLE
Feature Request: ability to edit connection strings

### ISSUE THREAD

**Issue by CaiusJard** [ErikEJ/EFCorePowerTools#1533]
Presently we have to delete the existing conenction string and make a new one, it seems.. And I've lost count of the number of times today I've re-typed my database, server and user name after copying from the Sample box in custom connection (Azure SQL). 

I think i've accidentally made a Postgres connection with SQLS details in at least 3 times and had to make yet another..

..and yes, I'm a spanner and I forget to copy so I can just paste and tweak (but then maybe I do remember to copy, but about 5 minutes after, I go and copy some code, and then realize that clipboard history is off..)

..so, here's my minor request for having an Edit next to the Delete [X] button that removes a connection; it would be really nice.. Even if it just univerally pops the custom editor with the connstr preloaded and we type changes manually, would be a boost..

**Comment by ErikEJ** [comment]
For security reasons I am not going to implement this.

**Comment by CaiusJard** [comment]
But that kinda doesn't make sense when all one has to do to reveal a working connection string is run through the wizard again and tick on "put the connection string in code" ..

**Comment by ErikEJ** [comment]
"kinda" - checking that box is user initiated...

**Comment by ErikEJ** [comment]
That people trust the tool to store their passwords securely, just like Server Explorer connections does.

**Comment by CaiusJard** [comment]
Then I can only refer to my previous comment that the tool still offers a way to have it divulge their password, so adding an edit button wouldn't appear to significantly weaken the position..
