### ISSUE TITLE
Suppress generation of Stored Procedure result types configured with MappedType

### ISSUE THREAD

**Issue by CharlieSaab** [ErikEJ/EFCorePowerTools#1534]
Describe what is not working as expected.

### Provide steps to reproduce

After specifying my own type in the `MappedType` field for a stored procedure in the `empt.config.json` file, the code is generated correctly. But a `<sp_name>Result` class is still generated, which won't be used, and a corresponding line added to the context model building code.

Could this be suppressed when `MappedType` has been supplied in the config?

### Provide technical details

- EF Core version in use: (e.g. EF Core 6)
EF Core 6

- Is Handlebars used: no/yes
No

- Is .dacpac used: no/yes
No

- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
2.5.1142

- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)
SQL Server 

- Visual Studio version: (e.g. Visual Studio 2022)
2022 17.3.3

**Comment by ErikEJ** [comment]
It could. Just waiting for feedback from users of this feature first.

**Comment by CharlieSaab** [comment]
@ErikEJ Many thanks.

**Comment by ErikEJ** [comment]
@CharlieSaab 
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

**Comment by ErikEJ** [comment]
I plan a release to VS marketplace mid November, if that is what you mean by "generally available"
