### ISSUE TITLE
Removing an Entity from being generated does not remove the file. (T4)

### ISSUE THREAD

**Issue by TimKras** [ErikEJ/EFCorePowerTools#1538]
When un-checking an previous selected table, the related Entity Class file is not remove when using the T4 generation.

- EF Core version in use: (e.g. EF Core 7 RC1)
![image](https://user-images.githubusercontent.com/5257192/194861922-7a6d0cb1-074a-4cf6-bb7b-e9d34e3dbbaa.png)

- Is T4 used: yes

- Database engine: SQL Server

- Visual Studio version: Visual Studio 2022

**Comment by TimKras** [comment]
Adding the `// <auto-generated>` comment does not seem to work.

**Comment by ErikEJ** [comment]
And the comment must be on the very first line of the file...

**Comment by ErikEJ** [comment]
Ping?

**Comment by TimKras** [comment]
I can confirm it is working now. We had an extra space before the `// <auto-generated>`

**Comment by ErikEJ** [comment]
Great - I have also updated the docs with this info
