### ISSUE TITLE
EF Core 7 - Remove Default Context constructor not working

### ISSUE THREAD

**Issue by TimKras** [ErikEJ/EFCorePowerTools#1539]
In EF Core 7, no default constructor is generated. Not sure if this is by design, but this options does nothing:
![image](https://user-images.githubusercontent.com/5257192/194936402-883d9759-8e5b-4989-83d0-10e05e5560bd.png)

**Comment by ErikEJ** [comment]
It is by design, yes: https://github.com/dotnet/efcore/issues/23515 (I you choose "no connection string")

**Comment by ErikEJ** [comment]
I have updated the label in the latest daily build:

    Remove default DbContext constructor (EF Core 3 & 6)

**Comment by ErikEJ** [comment]
Reopening - I was mixing thing up. This should also be implemented for EF Core 7

**Comment by TimKras** [comment]
> @TimKras >>In EF Core 7, no default constructor is generated.
> 
> I see a default constructor!

I don't really understand?

**Comment by ErikEJ** [comment]
When running EF Core 7 reverse engineering a default constructor us being generated.

And for EF 7 the option above has no effect but it should

**Comment by ErikEJ** [comment]
@TimKras Fixed in latest daily build - sorry for the delay.
