### ISSUE TITLE
Warning  configure a value converter using 'HasConversion' for store procedure compute decimal column

### ISSUE THREAD

**Issue by ppk11654** [ErikEJ/EFCorePowerTools#1544]
Describe what is not working as expected.

If my store procedure has a compute decimal column such as : (column1 * column2) as ComputeColumn
![image](https://user-images.githubusercontent.com/11578477/195491572-082df0e4-f2c7-4924-955a-020ad1e3e222.png)

, when the project compiler running is ok , but consol will show : 
![image](https://user-images.githubusercontent.com/11578477/195490504-6bfb847c-067c-45df-abe6-43724d10c7f4.png)
what's the better way to fix it ?

Thanks!
Jacky

### Provide technical details

- EF Core 6

- Is Handlebars used: no

- Is T4 used: no

- Is .dacpac used: yes

- EF Core Power Tools version: 2.5.1145

- Database engine: SQL Server 2019

- Visual Studio version: 2022

**Comment by ErikEJ** [comment]
It is just a warning - but you should be able to get rid of it with something like this:

```csharp
public partial class NorthwindContext : DbContext
{
    partial void OnModelCreatingPartial(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Product>().Property(p => p.UnitPrice).HasPrecision(18, 2);
    }
}

```

**Comment by ppk11654** [comment]
Got it, Thanks!

**Comment by ErikEJ** [comment]
You are welcome.

I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details)
