### ISSUE TITLE
I need to use EntityFrameworkCore 2.1.0 (Legacy Project)

### ISSUE THREAD

**Issue by gabrielangelocarvalho** [ErikEJ/EFCorePowerTools#1545]
Hi, 

We have a legacy project running, 
Microsoft.EntityFrameworkCore.SqlServer" Version="2.1.0"

Where can i find old versions  extensions of EF Power tools?

Could you help me.

Thanks in advance.

**Comment by ErikEJ** [comment]
I am not able to help you and 2.1 has been out of support since August 21, 2021. EF Core Power Tools support 3.1 or later.

**Comment by CaiusJard** [comment]
Most things EFCPT can do can also be done with command line. I'd urge you to consider upgrading your EFCore though
