### ISSUE TITLE
Package info

### ISSUE THREAD

**Issue by acondello** [ErikEJ/EFCorePowerTools#1547]
HI Erik,

first of all many many thanks for your extension, I think it's very helpful.

Here's my question: I had to move to VS 2022 for Mac and I noticed that the extensions gallery is empty. As far as I understood it's something not yet fully implemented and, furthermore, the package is different between win and mac, so it's not possible to install it manually form the market place.

Do you have a plan to create the Mac version as well?

Thanks

**Comment by ErikEJ** [comment]
Sorry. No plans for that, as the current package runs on .NET Framework only. As you can see in the docs, you can run some of it as a command line tool on Mac

**Comment by acondello** [comment]
ok, thanks anyway for the great job
