### ISSUE TITLE
Feature Request - Custom DB Context Configurations files output path

### ISSUE THREAD

**Issue by wize1** [ErikEJ/EFCorePowerTools#1551]
Hi, is it possible to add output path for context configurations classes? 

So user can separate auto generated classes from his own custom ones. For example, by putting auto generated classes into "Generated" subfolder.

### Provide steps to reproduce

Run EF Core Power Tools Reverse Engineer

In Advance options select "Split DB Context into Configurations classes"

### Provide technical details

- EF Core version in use: (e.g. EF Core 7)

- Is Handlebars used: any

- Is T4 used: any

- Is .dacpac used: any

- EF Core Power Tools version: 2.5.1041

- Database engine: any

- Visual Studio version: Visual Studio 2022

**Comment by ErikEJ** [comment]
Not sure what you mean. They are put into a Configurations folder today, and you can put your custom ones anywhere else.

**Comment by wize1** [comment]
> Not sure what you mean. They are put into a Configurations folder today, and you can put your custom ones anywhere else.

I don't need them in Configuration folder, I need them in folder Configurations\Generated (or any other folder that fits more to my project structure) and my own classes i put into Configurations folder. That way developer knows that anything that is in Generated must not be modified as changes maybe lost and his modification must go into separate partial class which will extend generated file.

I think it should be pretty easy to implement and gives even more flexibility on structure of project.

**Comment by ErikEJ** [comment]
This is no something I plan to implement for this preview feature. 
There are many opinions about the location of these files.
Feel free to move them elsewhere. 
Also, you can just add you own files in the same folder, can call them AlbumConfiguration.Custom.cs

**Comment by wize1** [comment]
> This is no something I plan to implement for this preview feature. There are many opinions about the location of these files. 

I think every developer has his own preference on how to structure his project. My humble opinion it is always better to give option to the user to customize his own experience, especially as you said "there are many opinions of location of these files".

It was just an idea for the feature... If it is bad idea, then I'm sorry. :)

**Comment by ErikEJ** [comment]
Exactly, that is why this feature is still in "preview" - and will probably never be ready for prime time if you look closely at the current implementation.

I am waiting for EF Core to support this natively, it looks like it will appear soon for EF Core 7.

**Comment by wize1** [comment]
Oh I understand now. My apologies then, please close this request.

**Comment by CaiusJard** [comment]
"developer knows that anything that is in Generated must not be modified as changes maybe lost"

Do not modify any file that has `//<autogenerated>...` at the top. To apply modifications you can create partial classes in most cases and put your partial classes anywhere you want..

**Comment by wize1** [comment]
Yes, I solved it by just outputting it to 'Generated' folder and partial customizations go to folder higher, that way I have clear view of what is modified, from what is auto generated.
