### ISSUE TITLE
Request - Support Shared Projects

### ISSUE THREAD

**Issue by jkerrwilson** [ErikEJ/EFCorePowerTools#1552]
I'd love to see support for running EFPT in a shared project, which does not appear to currently be possible.

This would allow for the generation of model files and DbContext in a shared source which would notably allow for customizable extension of models and contexts by importing projects.

My specific use case for this is keeping a single copy of the generated DbContext in a shared location, but having different partial implementations in different microservices.

**Comment by ErikEJ** [comment]
Why can you not use a standard class library?

**Comment by ErikEJ** [comment]
Ping?

**Comment by ErikEJ** [comment]
You could fo the same with linked files.

**Comment by jkerrwilson** [comment]
Thanks I'll look into that.

**Comment by ErikEJ** [comment]
With the new project format it is a one liner.
