### ISSUE TITLE
Related Tables

### ISSUE THREAD

**Issue by bboolukos** [ErikEJ/EFCorePowerTools#1553]
### Provide steps to reproduce

I'm using EF Power Tools but the thing I'm not sure about is when I run for example a GET on a table that has related data the schema shows the related tables but the response only shows the database table columns. I need the nested values. I have a view which joins the tables but they are flat in the response body but I need to be a nested values for Angular controls to access. 

For example:
Table UserRole:  UserID, RoleID

Model built:

`namespace RelatedData.Models
{
    [Table("UserRole")]
    public partial class UserRole
    {
        [Key]
        public int UserID { get; set; }
        [Key]
        public int RoleID { get; set; }
        [Required]
        [StringLength(100)]
        [Unicode(false)]
        public string CreationLoginID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreationTime { get; set; }

        [ForeignKey("RoleID")]
        [InverseProperty("UserRoles")]
        public virtual Role Role { get; set; }
        [ForeignKey("UserID")]
        [InverseProperty("UserRoles")]
        public virtual User User { get; set; }
    }
}`

I was hoping that the response body would show related nested data from table UserRole and User table. Looks like EF Power tools understands that relationship. Would like to add to the Controller somehow.

- EF Core version in use: (e.g. EF Core 7)
   EF CORE 6

- Is Handlebars used: no/yes
- No

- Is T4 used: no/yes
- No

- Is .dacpac used: no/yes
- No

- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)

Version 2.5.1145.0

- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)
SQL SERVER

- Visual Studio version: (e.g. Visual Studio 2022)
VS2022

**Comment by ErikEJ** [comment]
This does not seem to relate to EF Core Power Tools.  Please ask a question with  a runnable sample in the EF Core repo
