### ISSUE TITLE
I don't see Table Valued Functions anymore

### ISSUE THREAD

**Issue by yosboss** [ErikEJ/EFCorePowerTools#1555]
I don't see Table Valued Functions anymore.
I was able to see them before.
Now my already generated function is deleted if I did a "Reverse engineer".

![image](https://user-images.githubusercontent.com/46021847/197653594-6f326343-bf7a-40d2-a46f-11e75e7abe55.png)

### technical details :

- EF Core version in use: (e.g. EF Core 5)

- Is Handlebars used: no

- Is T4 used: no

- Is .dacpac used: no

- EF Core Power Tools version: 2.5.1145.0

- Database engine: SQL Server

- Visual Studio version: Visual Studio 2022

**Comment by ErikEJ** [comment]
Either your account does not have rights to see them or you are using a database without the functions.

**Comment by ErikEJ** [comment]
Ping?

**Comment by yosboss** [comment]
> Either your account does not have rights to see them or you are using a database without the functions.

Hello, sorry for my late reply !
I have a function, rights are correct (integrated security), I am the only user, I have sql express in my machine.
I'm almost sure that nothing has changed, it was working, now it isn't.

any other thoughts ?

**Comment by ErikEJ** [comment]
You would have to share you database schema and EF Core version chosen with me, othewise I cannot help further.

**Comment by ErikEJ** [comment]
Closing as the additional info was not supplied

**Comment by yosboss** [comment]
Hello, 

To be precised, I was talking about "Table Valued Functions".

EF Core version : 5.0.11
database schema : dbo (or are you talking about the whole t-sql schema ?)

(sorry for the late response)

Thanks,

**Comment by ErikEJ** [comment]
@yosboss I am takling about a SQL script that creates a tvf that is not listed.

**Comment by yosboss** [comment]
the simpliest tvf that I create is not showing.
![image](https://user-images.githubusercontent.com/46021847/213118384-4144eac4-81d7-4543-9db1-48588e4ec4b9.png)

**Comment by ErikEJ** [comment]
I will have a look

**Comment by yosboss** [comment]
OK, noted!
Thanks

**Comment by ErikEJ** [comment]
@yosboss let me know if you need an unsupported older build that supports EF Core 5

**Comment by yosboss** [comment]
I have update to .net6, and to EF Core 7.
Now I see the TVF.

Thanks again
