### ISSUE TITLE
EF Core 7 - Reverse Engineer stored procedures parameter name issue

### ISSUE THREAD

**Issue by gaglia** [ErikEJ/EFCorePowerTools#1556]
Hello,

I am trying to use EF Core 7 (Preview) to perform Reverse Engineer and I have noticed a strange thing.
In the generation of the code for the SQL Server stored procedures, the "_" character is removed from the name of the stored parameters.

This causes the stored run-time to fail because the parameter with the correct name as defined in the database is not passed.

Example I have a parameter @AttivitaChild_Flg the reverse Engineer create this without "_"

 new SqlParameter
{
    ParameterName = "AttivitaChildFlg",
    Value = AttivitaChildFlg ?? Convert.DBNull,
    SqlDbType = System.Data.SqlDbType.Bit,
}

If I run the same Reverse Engineer using EF Core 6 the names of the parameters with the "_" character are not changed and therefore the execution of the stored works correctly:

 new SqlParameter
{
    ParameterName = "AttivitaChild_Flg",
    Value = AttivitaChild_Flg ?? Convert.DBNull,
    SqlDbType = System.Data.SqlDbType.Bit,
}

Can you check if it happens to you too?

Many thanks in advance

Technical information:

- EF Core version in use: EF Core 7 (Preview)

- Is Handlebars used: no

- Is T4 used: no

- Is .dacpac used: no

- EF Core Power Tools version: 2.5.1172

- Database engine: SQL Server

- Visual Studio version: Visual Studio 2022 17.4.0 Preview 4.0

**Comment by ErikEJ** [comment]
Please share a sample stored proc and I will investigate. There should be no difference between 6 and 7.

**Comment by gaglia** [comment]
I attach the generated datacontext and the stored procedures in which I noticed the problem: sp_ZZ_Desk_GetAttivitaDashboard

Thanks for the feedback

[iMioGestDeskContext.zip](https://github.com/ErikEJ/EFCorePowerTools/files/9867302/iMioGestDeskContext.zip)
[sp_ZZ_Desk_GetAttivitaDashboard.zip](https://github.com/ErikEJ/EFCorePowerTools/files/9867312/sp_ZZ_Desk_GetAttivitaDashboard.zip)

**Comment by ErikEJ** [comment]
Thanks I was able to repro. 

I will look into a fix soon.

**Comment by gaglia** [comment]
Great 
Thank you very much

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details)

**Comment by gaglia** [comment]
Hi ErikEJ,

I confirm that the problem is solved

Thanks so much for the quick support!

I will not fail to leave my rating on the Visual Studio Marketplace

Thanks again

**Comment by sean-bloch** [comment]
I actually came here to search for this bug before filing. Good to see there was a previous fix, I will see if my tools version was just  out of date. In my case, I noticed that my associated unit test failed to build because "_" were previously in the parameters of the generated models (they are in the procedure parameters) , and were not in the model when I rebuilt from PowerTools.
