### ISSUE TITLE
Update Handlebars Scaffolding to v1.7.1

### ISSUE THREAD

**Issue by tonysneed** [ErikEJ/EFCorePowerTools#156]
I fixed some bugs and added features, so it would be good for you to update the package reference to [v1.7.1](https://www.nuget.org/packages/EntityFrameworkCore.Scaffolding.Handlebars/1.7.1).

Cheers,
Tony

**Comment by ErikEJ** [comment]
Have you made all Navigation "virtual" now (by default) ? - (EF Core 2.2 Rev Eng does that)

**Comment by tonysneed** [comment]
I did update the templates, but let me check on the navigation properlies. If those need changing I can do that and release an update.

**Comment by tonysneed** [comment]
@ErikEJ Hang on.  Just published [v1.7.2](https://www.nuget.org/packages/EntityFrameworkCore.Scaffolding.Handlebars/1.7.2) with the virtual navigation properties.

**Comment by ErikEJ** [comment]
Done!
