### ISSUE TITLE
Add DbContext Diagram throws an exception with EFcore6

### ISSUE THREAD

**Issue by gilyadid** [ErikEJ/EFCorePowerTools#1560]
Add DbContext Diagram throws an exception as follows:
_System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.Hosting.Abstractions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified._

It seems that the above file which the tool is looking for along with that version does not exist anywhere.
Looking for it in the NuGet system, I couldn't find any suitable package with that specific version, trying to install a previous version didn't remedy this.

###  steps to reproduce
Using Visual Studio 2022, Create an empty net6 standard project.
Add nuget packages to the project:
- Microsoft.EntityFrameworkCore 6.0.10
- Microsoft.EntityFrameworkCore.SqlServer 6.0.10
- Microsoft.EntityFrameworkCore.Tools 6.0.10

Use the tool to reverse engineer any database with those options:
First Screen:  select EFCore6
Second Screen: select all tables
Third Screen:
  mark V on "Pluralize or singularize gene..."
  mark V on "Use table and column names directly.."
  Everything else keep unmarked including all options in the "Advanced.." screen.
Click Ok, let the tool generate everything.
Once it finished right click the project, select the EF Core Power tools popup menu and choose to 'Add DbContext Diagram' from the tool menu.

### Provided technical details
- EF Core version in use: 6.0.10
- Is Handlebars used: no
- Is T4 used: no
- Is .dacpac used: no
- EF Core Power Tools version: 2.5.1145.0
- Database engine: SQL Server Express
- Visual Studio version: Visual Studio 2022

**Comment by ErikEJ** [comment]
You need to run this from an executable project, not from a .NET Standard project.

**Comment by ErikEJ** [comment]
There is also some [tips here](https://github.com/ErikEJ/EFCorePowerTools/wiki/Inspect-your-DbContext-model#challenges)

**Comment by gilyadid** [comment]
Same issue when trying to run it from the executable project. (I tried
Asp.Net Core with .Net6 and with Console application)

**Comment by ErikEJ** [comment]
In order to assist you further I need s repro project.

**Comment by ErikEJ** [comment]
Ping?

**Comment by gilyadid** [comment]
Hi Eric,

I managed to see that feature work on a clean project with console
application and a DB with a single table.
So I no longer think it's a bug on your end, I will compare the working
example vs. my solution till I can figure it out.

Thank you so much!

ahhm.. Eric, It is not common to have an opportunity to write to a giant
like you, I think you may have a say in MS which few people have.
So i'd like to share two things with you:

1. The edmx, schema editing feature we had in past entity-frameworks was
more than just a good-to-have addition - they were essential.
Every company I worked with before asp.net core used edmx files. It was
extremely convenient since we usually get to work with
some legacy databases that are badly structured and the fastest way to see
the full picture in one place was laying out the schema
on Edmx and start coloring it, moving the tables around to figure the
connections and so forth.
Other schema tools out there - don't give that experience the same, there
is always something missing in them.

Another point is that in today's situation, I get to see databases with
related hand-written db-contexts filled with thousands of problems.
So your tool is saving a lot of people as most of us will delete the hand
written db-context and generate new one from your tool.
This means the most popular practice today is using the DB-First approach.
But I do miss the Schema-First approach, I think it was the best approach.
Having a schema we can change and DB-Context align to it along a database
is tons of time saving.

2. VS2022 came out with the Hot-Reload feature, but Edit-And-Continue is
broken.
I have learned that the person who was in charge to lead the repairs for
Edit-And-Continue is no longer working in MS.
This means the developers are getting experience from hell while debugging
and many consider switching to JetBrain products.

I do not know if you can do something about those 2 issues, but if you can
- please go for it :)

Thanks again,
Gil.

**Comment by ErikEJ** [comment]
Sorry  neither of these are anything I can contribute to.
