### ISSUE TITLE
Renaming Navigations Design Proposal

### ISSUE THREAD

**Issue by R4ND3LL** [ErikEJ/EFCorePowerTools#1562]
@R4ND3LL please submit a draft PR!

_Originally posted by @ErikEJ in https://github.com/ErikEJ/EFCorePowerTools/issues/211#issuecomment-1297642675_

@ErikEJ, I have the fork/branch created.  I don't have a whole lot of time to devote to this; Can you give me a couple of suggestions as to where this code would be best added into your solution?      

This feature requires a couple of nuget packages (like Microsoft.CodeAnalysis.CSharp.Workspaces).  It will look for the new renaming-nav json file, load it, and process the renames on the already-generated code.

There are a couple of options for WHEN this can take place:
- At end of "Reverse Engineer" process (my preference)
- Manually invoked by user via a new menu option.

Let me know what you think.

**Comment by ErikEJ** [comment]
If you can just share what you have I will do the work of adding it to the workflow. 

It should just happen at the end of reverse engineering if a renaming-nav.json file exists.

**Comment by R4ND3LL** [comment]
Created the draft PR.   if this works for you, we can then possibly look at adding the feature for generating the renaming rule files from EDMX.  This would definitely be a new menu option.  

The goal being to be able to delete the EDMX from the sln afterwards as there will be no need for it.

**Comment by ErikEJ** [comment]
That would be really powerful (EDMX support) - a failed related effort was Made before - I think you can use parts of it.

I will look at your pr, but would really prefer to have this in the RevEng Core projects instead of in the VSIX project. I will investigate if it is possible to use the added packages with .NET 6

**Comment by R4ND3LL** [comment]
This was copied from my .Net 6 solution so yes, it can be moved over as-is.  Pushing it down makes sense, I'm just not very familiar with your sln structure.  

I understand why direct EDMX support was dropped in favor of the rule files.  You really wouldnt want the edmx sticking around, requiring you to maintain the structure as the DB schema changes over time.   Extracting rule files and deleting the edmx is the way to go.  

I potentially see use for one more rule file:  Enum type to property mapping.

**Comment by ErikEJ** [comment]
Perfect. I will try to refactor. General approach going forward is to move as much logic as possible down to the command line tool.

**Comment by ErikEJ** [comment]
You can do Enum type to property mapping in the t4 template. See the docs for an example.

**Comment by R4ND3LL** [comment]
> You can do Enum type to property mapping in the t4 template. See the docs for an example.

Yes I read about that.  I'm thinking that the T4 may be able to read the enum rule file automatically, that way the mapping doesn't have to be written into the T4 by hand.     I'm working with about 10 EF6 projects and would like to automate as much as possible.

**Comment by ErikEJ** [comment]
Yeah, anything goes with T4

**Comment by ErikEJ** [comment]
I see now why you have the code in the VSIX, btw.

**Comment by ErikEJ** [comment]
@R4ND3LL Would appreciate a review of this PR: https://github.com/ErikEJ/EFCorePowerTools/pull/1565 

Once approved you can test it in the daily build, and maybe contribute some documentation?

Thanks for the effort!
