### ISSUE TITLE
Compare DBContext to Database hiding differences

### ISSUE THREAD

**Issue by jreddeko** [ErikEJ/EFCorePowerTools#1564]
Problem:

All differences with a log level of 1 or 2 in 'Compare DBContext to database' are hidden unless there is a least one difference with a log level of 0.

Here is how to reproduce this issue:

1. Run Compare DBContext to database, notice their are two differences.  One difference is an incorrectly named PK which does not need to be expanded to be seen. The other difference is in the BusinessTerritory table which needs to be expanded to be seen.

![image](https://user-images.githubusercontent.com/2381580/199274654-763f74e5-6bcc-47b0-b6f0-e77c6460597e.png)

![image](https://user-images.githubusercontent.com/2381580/199274857-b1de9bc3-4c7e-4cae-812a-b6ffebc6789a.png)

2. Fix only the PK difference then run Compare DBContext to database again. Now no differences are shown.

![image](https://user-images.githubusercontent.com/2381580/199275334-2e6dcca7-87bf-4faf-8f14-8402b96efe6e.png)

4. However, if you uncheck 'Show Differences Only' then navigate to the BusinessTerritory table and expand it the difference is still there

![image](https://user-images.githubusercontent.com/2381580/199272666-a551dc65-c4fb-45e2-b368-b72ed35bbd5c.png)

### Provide technical details

- EF Core version in use: 7.0.0-preview.1.22076.6
- Is Handlebars used: no
- Is T4 used: no
- Is .dacpac used: no
- EF Core Power Tools version: 2.5.1145
- Database engine: SQL Server
- Visual Studio version: Visual Studio 2022

**Comment by ErikEJ** [comment]
Good analysis. Interested in doing a PR?

**Comment by jreddeko** [comment]
Sure I'll give it a try when I have some free time.  Thanks!

**Comment by ErikEJ** [comment]
Can you share a model and a create table script that demonstrates this, then I will have a look

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details)

**Comment by jreddeko** [comment]
Yes, works perfect now.  Thank you!

**Comment by ErikEJ** [comment]
Great and thanks for the heads up.
