### ISSUE TITLE
Property renaming experiment follow up

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#1567]
- [x] Create a better model (using concepts like classes and properties)
- [x] Rename the renaming file to efpt.property-renaming.json 😄 
- [x] Provide better feedback from process via output window
- [x] Investigate options to move to CLI tool

**Comment by ErikEJ** [comment]
Maybe, I have not given this a lot of thought, let's ensure that the basic functionality is in place and has been tested.

**Comment by ErikEJ** [comment]
Great! I will follow up here.

**Comment by ErikEJ** [comment]
@R4ND3LL  I have done the breaking changes, some polish still needed, but you can proceed with the EDMX related feature. Could you explain a bit more about it?

**Comment by ErikEJ** [comment]
@R4ND3LL I have created some initial [docs here](https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#custom-renaming-with-efptproperty-renamingjson), do they make sense?

**Comment by ErikEJ** [comment]
@R4ND3LL I have attempted to move the renaming to the CLI tool, but the loaded Roslyn project does not contain any documents. 

You can debug efreveng project with src\GUI\efreveng\TestFiles\fulltest.json as parameter to debug

You can use this script to build the database schema: test\ScaffoldingTester\ScaffoldingTester\Northwind.sql

**Comment by ErikEJ** [comment]
I fixed it with this commit https://github.com/ErikEJ/EFCorePowerTools/commit/99505ab4bd08466f7f4f35cff9b2f10c9a3bf82f

Still getting this error when loading project using the Roslyn extension method:

[Failure] Msbuild failed when processing the file 'C:\Code\Github\EFCorePowerTools\test\ScaffoldingTester\ScaffoldingTester5\ScaffoldingTester5.csproj' with message: The imported project "C:\Program Files\dotnet\sdk\6.0.402\15.0\Microsoft.Common.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Program Files\dotnet\sdk\6.0.402\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.props

**Comment by ErikEJ** [comment]
And had to revert due to this:

 Currently, this will successfully rename the model properties but it does NOT process the references from the Configuration
 classes.  This is likely because Roslyn is not resolving information about EntityTypeBuilder<> such that it
 can identify the model property references.

**Comment by R4ND3LL** [comment]
> And had to revert due to this:
> 
> Currently, this will successfully rename the model properties but it does NOT process the references from the Configuration classes. This is likely because Roslyn is not resolving information about EntityTypeBuilder<> such that it can identify the model property references.

You're aware this comment is related to the "fallback load procedure" only correct?   The primary load procedure (using LoadExistingProject) has worked in all my tests so far and has never reached the fallback.  In my tests, properties and all references throughout project are renamed correctly.    

For the fallback only, Configuration class references are left unchanged. The fallback is a WIP.

**Comment by ErikEJ** [comment]
Yes I am aware.

I am getting the msbuild error mentioned above when using the CLI. And then 0 documents are present in the project.

**Comment by R4ND3LL** [comment]
Currently on master?  Brave not using a branch! lol   
I'll have a look

**Comment by ErikEJ** [comment]
It has something to do with MSbuild locations I think

**Comment by ErikEJ** [comment]
The feature only kicks in if a renaming file exists

**Comment by R4ND3LL** [comment]
> @R4ND3LL I have done the breaking changes, some polish still needed, but you can proceed with the EDMX related feature. Could you explain a bit more about it?

It may be later today before I can test.  In the meantime, let's discuss the EDMX feature.  This feature will take an EDMX path as a parameter, parse it, and output the various rule files into the target project root.  I don't see the need for any other options at the moment.   But I do see this being invokable from cmd line like: "exe -EdmxRuleGen <path.edmx>"

To reduce some of the guesswork on my part, if you want, you can create a branch and the VSIX menu entry, and lay out some class stubs as you want them positioned.  Then I can do a PR on the branch and fill in the stubs.

**Comment by ErikEJ** [comment]
@R4ND3LL Let's start with a library that just creates the output, and add all the VS sugar coating later. I have checked in a stub project (in master) - you can then update your fork, and create a PR branch.

Project name is: EdmxRenamingGenerator

**Comment by ErikEJ** [comment]
Giving up on CLI integration for now

**Comment by R4ND3LL** [comment]
I hit the same issue as you.  The MSBuildLocator seems to resolve SDK 3.1 from the CLI, but 6.0 from my test app.  I suspect this causes the empty document list....  looking deeper.  

On a side note, have you considered allowing the CLI caller to simply target a project, and build up an instance of ReverseEngineerCommandOptions by loading the efpt.config.json (and other resources) from there?  Should be easy enough to do.  The only thing potentially missing is the connection string?  I would imagine users would find this convenient (not having to build another json doc)

**Comment by ErikEJ** [comment]
>> On a side note, have you considered allowing the CLI caller to simply target a project, and build up an instance of ReverseEngineerCommandOptions by loading the efpt.config.json (and other resources) from there?

I think that is what I am doing already???

**Comment by ErikEJ** [comment]
>> I hit the same issue as you. The MSBuildLocator seems to resolve SDK 3.1 from the CLI, but 6.0 from my test app. I suspect this causes the empty document list.... looking deeper.

I is working fine today when called from VS. That is fine for me.

**Comment by R4ND3LL** [comment]
> > > On a side note, have you considered allowing the CLI caller to simply target a project, and build up an instance of ReverseEngineerCommandOptions by loading the efpt.config.json (and other resources) from there?
> 
> I think that is what I am doing already???

From what I can tell, efreveng can take "fulltest.json" as an argument (this is what I'm doing now).  I don't see that it can take a project folder path arg.

**Comment by ErikEJ** [comment]
A project path is contained in that file!

**Comment by R4ND3LL** [comment]
I must not be explaining myself correctly.  I know the path is in the json file, I updated fulltest.json to use my local project.

What I'm saying is instead of running 
> efreveng.exe fulltest.json

which requires the user to build the fulltest.json file, it would be nice if you could just run
> efreveng.exe c:\code\myproject

The above would recognize that this is a project folder and load the efpt.*.json files and combine into an options arg and pass that on to ReverseEngineerRunner as usual

better yet, if you were currently in your project folder, you could just run
> efreveng.exe .

**Comment by ErikEJ** [comment]
Got it. Yeah, currently running the tool from the command line is not supported (and therefore not designed). It is a little more complex than you describe as a project can contain multiple Configurations/DbContexts

**Comment by R4ND3LL** [comment]
I guess the uptake of the CLI is hampered by the current packaging.  
If the CLI was distributed via chocolately or npm it would likely have a broader reach, hitting those on Rider and other OSes.  
I can see the rule gen+roslyn stuff being useful to anyone that runs scaffolding via command line. 
If there's call for it, maybe I can deploy it that way.

**Comment by ErikEJ** [comment]
I have no current plans to do and support that. I think you maybe  misunderstand item four on the checklist..
