### ISSUE TITLE
Behavior with multiple same-name connections needs minor improvement

### ISSUE THREAD

**Issue by CaiusJard** [ErikEJ/EFCorePowerTools#1569]
Enter the reverse engineering process

Create a custom connection with name X

Create another custom connection with name X (it doesn't matter if it's the same provider or not)

Now two connections with the same name appear in the drop down

Delete one of them

The other still appears in the dropdown, but cannot be deleted: "Unable to remove connection: Unable to delete credential"

Cancel out of the dialog

Re-enter the reverse process

Both connections are gone

---

If we cancel out without deleting a connection then re-enter, there is only one (the latest). It looks like adding a new one with the same name leaves the old one in the UI (and temporarily usable until the dialog is closed) but not in whatever back end storage the UI is loaded from?

**Comment by ErikEJ** [comment]
Why do you need custom connections?

**Comment by CaiusJard** [comment]
Active Directory Interactive auth isn't a member of the standard dropdown

**Comment by ErikEJ** [comment]
Got it

**Comment by CaiusJard** [comment]
(Though it looks like the same can be replicated with the standard route, if we connect twice to the same host and DB)

**Comment by ErikEJ** [comment]
You can add duplicate standard connections, but I see no issue with deleting them...
