### ISSUE TITLE
View reverse engineer is not creating properties for calculated columns

### ISSUE THREAD

**Issue by luca-g** [ErikEJ/EFCorePowerTools#1570]
Reverse engineer for sql server view is not creating properties for calculated columns

CREATE VIEW [dbo].[V1]
AS
  SELECT 
	  case when a.t1=0 then null else (d.n-a.t1)/a.t1 end t1a

- EF Core version in use: EF Core 6
- EF Core Power Tools version: 2.5.1145
- Database engine: SQL Server
- Visual Studio version: Visual Studio 2022 Community

**Comment by ErikEJ** [comment]
Are you using a .dacpac - then this is a [documented limitation](https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#sql-server-database-project-dacpac-mapping)

**Comment by luca-g** [comment]
I have a database project in the solution "sqlproj"

**Comment by ErikEJ** [comment]
Yes, that is a .dacpac
