### ISSUE TITLE
Clean up server history V2.4.51

### ISSUE THREAD

**Issue by Moorepheus** [ErikEJ/EFCorePowerTools#1576]
Describe what is not working as expected.

I need a way to clean up the server history.  We have retired/upgraded some server instances We are using V2.4.51 to support this legacy software.  IS this possible?

**Comment by ErikEJ** [comment]
Please elaborate, I do not understand what you are referring to.

**Comment by Moorepheus** [comment]
Sorry, I could have been more clear

***@***.***

Thank You

    Mark Moore

**Comment by ErikEJ** [comment]
You are still unlcear 😄 - but if you are referring to the list of data connections, these can be removed in Server Explorer

**Comment by Moorepheus** [comment]
Yes, I want to remove servers from that list.

Thank you, I just don’t know why I didn’t think of that. Been a long couple weeks for me…

Thanks

    Mark Moore
