### ISSUE TITLE
Context class name changed using EF Core 7

### ISSUE THREAD

**Issue by dchillman123** [ErikEJ/EFCorePowerTools#1577]
Describe what is not working as expected.
I am investigating moving a project to Core 7 from Core 6.  When I reverse-engineered the database using "EF Core 7" the context name changes -
the context name is defined as "CDPS_SOMBContext" in the dialog.  the generated context class is renamed to "CDPSSOMBContext"

If I re-generate using "EF Core 6", the context name reverts to "CDPS_SOMBContext"

Is that the expected behavior for "EF Core 7"?

### Provide technical details

- EF Core version 7

- Is Handlebars used: no

- Is T4 used: no

- Is .dacpac used: no

- EF Core Power Tools version: 2.5.1201.0

- Database engine: (SQL Server 216)

- Visual Studio version: ( Visual Studio 2022 17.4.0)

**Comment by ErikEJ** [comment]
I think it could be related to https://github.com/dotnet/efcore/issues/29450 - can you try the command line scaffolding to confirm?

**Comment by dchillman123** [comment]
I haven’t actually used command line scaffolding but will put it on my list
of things to do.



*From:* Erik Ejlskov Jensen ***@***.***>
*Sent:* Wednesday, November 9, 2022 7:09 AM
*To:* ErikEJ/EFCorePowerTools ***@***.***>
*Cc:* dchillman123 ***@***.***>; Author <
***@***.***>
*Subject:* Re: [ErikEJ/EFCorePowerTools] Context class name changed using
EF Core 7 (Issue #1577)



I think it could be related to dotnet/efcore#29450
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_dotnet_efcore_issues_29450&d=DwMCaQ&c=sdnEM9SRGFuMt5z5w3AhsPNahmNicq64TgF1JwNR0cs&r=EaMiT8Pm9Ou6ZL7-b18rNDVT7IQJCk19B_xDGLFZ54o&m=RNu-XI90S_5kM-goff3-YIzaIEyIaUzEsS961SG4IurxRZpinEhJRAiM6ttgc2YW&s=9T5bUvLDAOZaf2up5wbJLNqNMZfvjsDppKYyxvJPSWs&e=>
- can you try the command line scaffolding to confirm?

—
Reply to this email directly, view it on GitHub
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ErikEJ_EFCorePowerTools_issues_1577-23issuecomment-2D1308820713&d=DwMCaQ&c=sdnEM9SRGFuMt5z5w3AhsPNahmNicq64TgF1JwNR0cs&r=EaMiT8Pm9Ou6ZL7-b18rNDVT7IQJCk19B_xDGLFZ54o&m=RNu-XI90S_5kM-goff3-YIzaIEyIaUzEsS961SG4IurxRZpinEhJRAiM6ttgc2YW&s=tjhnEQeOd97ff1iJiQ7v9smx--uydbKCgoSW_J3U4k4&e=>,
or unsubscribe
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AG6LTJAXK7ELZ6EAJAAIII3WHOV7NANCNFSM6AAAAAAR3O6PUQ&d=DwMCaQ&c=sdnEM9SRGFuMt5z5w3AhsPNahmNicq64TgF1JwNR0cs&r=EaMiT8Pm9Ou6ZL7-b18rNDVT7IQJCk19B_xDGLFZ54o&m=RNu-XI90S_5kM-goff3-YIzaIEyIaUzEsS961SG4IurxRZpinEhJRAiM6ttgc2YW&s=U-O_gWK0kwo46o01Sq9w_LYTnkRwsWfyTh56vNOvb28&e=>
.
You are receiving this because you authored the thread.Message ID: <
***@***.***>

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details)

**Comment by dchillman123** [comment]
I just ran the reverse engineer with ef7, and the issue with then name of
the context is gone.   Thanks



Dan



*From:* Erik Ejlskov Jensen ***@***.***>
*Sent:* Tuesday, November 15, 2022 12:58 AM
*To:* ErikEJ/EFCorePowerTools ***@***.***>
*Cc:* dchillman123 ***@***.***>; Author <
***@***.***>
*Subject:* Re: [ErikEJ/EFCorePowerTools] Context class name changed using
EF Core 7 (Issue #1577)



I implemented a fix for this in the latest daily build
<https://urldefense.proofpoint.com/v2/url?u=https-3A__www.vsixgallery.com_extension_f4c4712c-2Dceae-2D4803-2D8e52-2D0e2049d5de9f&d=DwMCaQ&c=sdnEM9SRGFuMt5z5w3AhsPNahmNicq64TgF1JwNR0cs&r=EaMiT8Pm9Ou6ZL7-b18rNDVT7IQJCk19B_xDGLFZ54o&m=7JfQDdCxnQxgInFxtw_JumeHe38xOxhh5TgLCznHUcLV1TvIRLZScxYyl1jk0VE1&s=ZMAMmKPay_HpTZYZHjUEf_C52Ngy88JP7DTqPwTcAIs&e=>,
would be grateful if you could try it out.

I would be very grateful for a rating or review on Visual Studio Marketplace
<https://urldefense.proofpoint.com/v2/url?u=https-3A__marketplace.visualstudio.com_items-3FitemName-3DErikEJ.EFCorePowerTools-26ssr-3Dfalse-23review-2Ddetails&d=DwMCaQ&c=sdnEM9SRGFuMt5z5w3AhsPNahmNicq64TgF1JwNR0cs&r=EaMiT8Pm9Ou6ZL7-b18rNDVT7IQJCk19B_xDGLFZ54o&m=7JfQDdCxnQxgInFxtw_JumeHe38xOxhh5TgLCznHUcLV1TvIRLZScxYyl1jk0VE1&s=uDk6TcF5FdYemk-b5HFmhPTzgfT8XdNVT--zqFlj0zo&e=>

—
Reply to this email directly, view it on GitHub
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ErikEJ_EFCorePowerTools_issues_1577-23issuecomment-2D1314924336&d=DwMCaQ&c=sdnEM9SRGFuMt5z5w3AhsPNahmNicq64TgF1JwNR0cs&r=EaMiT8Pm9Ou6ZL7-b18rNDVT7IQJCk19B_xDGLFZ54o&m=7JfQDdCxnQxgInFxtw_JumeHe38xOxhh5TgLCznHUcLV1TvIRLZScxYyl1jk0VE1&s=dq0CdMYTNplrXKY8US0xolxODU3WVaj3QL5fKBMFdts&e=>,
or unsubscribe
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AG6LTJHENIM5VJPCO5TS5CDWIM7ADANCNFSM6AAAAAAR3O6PUQ&d=DwMCaQ&c=sdnEM9SRGFuMt5z5w3AhsPNahmNicq64TgF1JwNR0cs&r=EaMiT8Pm9Ou6ZL7-b18rNDVT7IQJCk19B_xDGLFZ54o&m=7JfQDdCxnQxgInFxtw_JumeHe38xOxhh5TgLCznHUcLV1TvIRLZScxYyl1jk0VE1&s=HP9xWq7so6bzNJsQ1brrXRQXzH0nLv-1ZTFDT6n6RdA&e=>
.
You are receiving this because you authored the thread.Message ID: <
***@***.***>
