### ISSUE TITLE
Extension doesn't work anymore after the latest updates: "Value cannot be null. Parameter name: provider"

### ISSUE THREAD

**Issue by MarcoGiorgi** [ErikEJ/EFCorePowerTools#1578]
After the latest updates, I'm not able anymore to open the extension 
If I click on "Reverse Engineer" or simply on "About" I get the following error on all my projects where I have successfully used EF Core Power Tools until a few days ago:
```
System.ArgumentNullException: Value cannot be null.
Parameter name: provider
   at T Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService<T>(IServiceProvider provider)
   at TView EFCorePowerTools.EFCorePowerToolsPackage.GetView<TView>()
   at void EFCorePowerTools.Handlers.AboutHandler.ShowDialog()
```
I've tried to remove and reinstall the extension but I still have the same issue.

### Provide steps to reproduce

just click on about or reverse engineer...

### Provide technical details

- EF Core version in use: EF Core 6.4.4

- Is Handlebars used: no

- Is T4 used: no

- Is .dacpac used: no

- EF Core Power Tools version: 2.5.1201

- Database engine: SQL Server 2019

- Visual Studio version: Visual Studio 2022

**Comment by MarcoGiorgi** [comment]
> 

Wow Erik, your faster than .NET7!!
this is the version of VS: Microsoft Visual Studio Community 2022 (64-bit) Version 17.0.2

I've tried a repair but nothing change

**Comment by Layfown** [comment]
`System.IO.FileNotFoundException: Impossible de charger le fichier ou l'assembly 'Microsoft.Bcl.AsyncInterfaces, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' ou une de ses dépendances. Le fichier spécifié est introuvable.
Nom de fichier : 'Microsoft.Bcl.AsyncInterfaces, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at IServiceProvider EFCorePowerTools.EFCorePowerToolsPackage.CreateServiceProvider()
   at async Task EFCorePowerTools.EFCorePowerToolsPackage.InitializeAsync(CancellationToken cancellationToken, IProgress<ServiceProgressData> progress)`

**Comment by ErikEJ** [comment]
@MarcoGiorgi try to update your very old VS install

**Comment by ErikEJ** [comment]
@Layfown please create a new issue for this unrelated issue and provide the requested details.

**Comment by MarcoGiorgi** [comment]
> @MarcoGiorgi try to update your very old VS install

After updating Visual Studio to the latest version EF Core Power Tools has started to work again without any issues.
I've checked also on another PC, using VS 17.1.0 and the same version of EF Core Power Tools was working fine.
So I confirm it was only a problem related to my old Visual Studio version.
Many thanks Erik for your invaluable support and this fantastic tool.

**Comment by ErikEJ** [comment]
Thanks for the kind words.

I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?
itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details)
