### ISSUE TITLE
ef core power tools now working in Visual Studio 2019 after Updating to newes version

### ISSUE THREAD

**Issue by fbihda** [ErikEJ/EFCorePowerTools#1580]
System.ArgumentNullException: Value cannot be null.
Parameter name: provider
   at T Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService<T>(IServiceProvider provider)
   at TView EFCorePowerTools.EFCorePowerToolsPackage.GetView<TView>()
   at async Task<bool> EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.ChooseDataBaseConnectionAsync(ReverseEngineerOptions options, Project project)
   at async Task EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.ReverseEngineerCodeFirstAsync(Project project, string optionsPath, bool onlyGenerate, bool fromSqlProj)

**Comment by ddulkevich-entrypoint** [comment]
Same issue

**Comment by ErikEJ** [comment]
Which VS version exactly (as you were asked when you created this issue)

**Comment by fbihda** [comment]
Microsoft Visual Studio Community 2019
Version 16.11.21

**Comment by ddulkevich-entrypoint** [comment]
> Same issue
Microsoft Visual Studio Community 2019
Version 16.11.16

**Comment by fbihda** [comment]
Visual studio Professional edition Version 16.11.17 same problem

**Comment by ErikEJ** [comment]
I will investigate. Why are you still using 2019?

**Comment by fbihda** [comment]
I am working with Oracle Developer Tools for Visual Studio and there are only support for Visual studio 2019

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

**Comment by ErikEJ** [comment]
Any news?

**Comment by fbihda** [comment]
I installed it and it working again.
Thank you very much to fixing.
:)

**Comment by ddulkevich-entrypoint** [comment]
> I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

It working again for me. Thank you very much!

**Comment by ErikEJ** [comment]
Thanks, I will get the fix pushed to MarketPlace soon.

I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details)
