### ISSUE TITLE
EF Core 3

### ISSUE THREAD

**Issue by andykavan** [ErikEJ/EFCorePowerTools#1581]
Describe what is not working as expected.

Update EF Core Power tools to 2.5.1201

Why does "EF Core 3" appear in the bottom left drop down - what does this mean?  why can I not select EFCore 5

- Visual Studio version:  Visual Studio 2022

**Comment by ErikEJ** [comment]
Because EF Core 5 is no longer supported. I support EF Core 3.1, 6 and 7
