### ISSUE TITLE
ICollection property not generating set

### ISSUE THREAD

**Issue by mrunks** [ErikEJ/EFCorePowerTools#1582]
If I select EF Core 6 the property get and set is created for a virtual ICollection, but if I select EF Core 7 then only a get is generated.  

Is there a way to default having both the set and get created for ICollections properties without using a T4 template ?

**Comment by ErikEJ** [comment]
I dont understand - please share some sample code.

**Comment by ErikEJ** [comment]
Ah, you mean this:

    public virtual ICollection<Order> Orders { get; } = new List<Order>();

It is by design - why would you need a setter. and yes, if you need it, use a T4 template customization

**Comment by mrunks** [comment]
Thanks I ended up using separate customization as you suggested.  In .NET 6 setters were available by default.

**Comment by ErikEJ** [comment]
@mrunks I have added this to the ideas for a "super" template

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
