### ISSUE TITLE
Error while Reverse Engineer or About since last Update

### ISSUE THREAD

**Issue by Layfown** [ErikEJ/EFCorePowerTools#1583]
Hello, 
Since the last update, we are unable to use this tool, when using Reverse Engineer or About ( for exemple ) we get this error:

`System.ArgumentNullException: La valeur ne peut pas être null.
Nom du paramètre : provider
   at T Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService<T>(IServiceProvider provider)
   at TView EFCorePowerTools.EFCorePowerToolsPackage.GetView<TView>()
   at void EFCorePowerTools.Handlers.AboutHandler.ShowDialog()`

At startup of VS we also have this error 
`System.IO.FileNotFoundException: Impossible de charger le fichier ou l'assembly 'Microsoft.Bcl.AsyncInterfaces, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' ou une de ses dépendances. Le fichier spécifié est introuvable.
Nom de fichier : 'Microsoft.Bcl.AsyncInterfaces, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at IServiceProvider EFCorePowerTools.EFCorePowerToolsPackage.CreateServiceProvider()
   at async Task EFCorePowerTools.EFCorePowerToolsPackage.InitializeAsync(CancellationToken cancellationToken, IProgress<ServiceProgressData> progress)`

VS 2019 
`_Microsoft Visual Studio Professional 2019
Version 16.11.21
VisualStudio.16.Release/16.11.21+33027.164
Microsoft .NET Framework
Version 4.8.04084

Version installée : Professional

.NET Core Debugging with WSL   1.0
.NET Core Debugging with WSL

ASP.NET and Web Tools 2019   16.11.110.1451
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.11.110.1451
Pour plus d'informations, visitez https://www.asp.net/

Azure Functions and Web Jobs Tools   16.11.110.1451
Azure Functions and Web Jobs Tools

Common Azure Tools   1.10
Fournit des services courants utilisables par Microsoft Azure Mobile Services et Microsoft Azure Tools.

Entity Framework Core Power Tools   2.5
Adds useful design-time EF Core DbContext features to the Visual Studio Solution Explorer context menu.

Extension IntelliCode   1.0
Informations détaillées sur l'extension Visual Studio IntelliCode

Extensions des outils de conteneur Visual Studio   1.0
Affichez, gérez et diagnostiquez les conteneurs dans Visual Studio.

Gestionnaire de package NuGet   5.11.2
Gestionnaire de package NuGet dans Visual Studio. Pour plus d'informations sur NuGet, visitez https://docs.nuget.org/

Microsoft Azure Tools pour Visual Studio   2.9
Prise en charge des projets Azure Cloud Services

Microsoft Continuous Delivery Tools pour Visual Studio   0.4
Simplification de la configuration des pipelines Azure DevOps à partir de l'IDE Visual Studio.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Outils Azure App Service v3.0.0   16.11.110.1451
Outils Azure App Service v3.0.0

Outils C#   3.11.0-4.22108.8+d9bef045c4362fbcab27ef35daec4e95c8ff47e1
Composants C# utilisés dans l'IDE. Selon votre type de projet et vos paramètres, une version différente du compilateur peut être utilisée.

Outils TypeScript   16.0.30526.2002
Outils TypeScript pour Microsoft Visual Studio

Outils Visual Basic   3.11.0-4.22108.8+d9bef045c4362fbcab27ef35daec4e95c8ff47e1
Composants Visual Basic utilisés dans l'IDE. Selon votre type de projet et vos paramètres, une version différente du compilateur peut être utilisée.

Package hôte de l'adaptateur de débogage de Visual Studio Code   1.0
Couche d'interopérabilité pour l'hébergement d'adaptateurs de débogage Visual Studio Code dans Visual Studio

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Razor (ASP.NET Core)   16.1.0.2122504+13c05c96ea6bdbe550bd88b0bf6cdddf8cde1725
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   16.0.62205.05200
Microsoft SQL Server Data Tools

Visual F# Tools   16.11.0-beta.21514.6+b6c2c4f53ea3a08fa603ea93d6d2f808a62a21d1
Microsoft Visual F# Tools

Visual Studio Tools pour Conteneurs   1.0
Visual Studio Tools pour Conteneurs

Visual Studio Tools pour Docker   1.2
Développez, exécutez et validez vos applications ASP.NET Core dans l'environnement cible. Appuyez sur F5 pour exécuter votre application directement dans un conteneur avec débogage ou sur CTRL+F5 pour modifier et actualiser votre application sans avoir à recréer le conteneur.`_

Thank you in advance for your answer.

**Comment by Layfown** [comment]
My bad, looks like it has been fixed in the "Visual Studio 2019 was broken #1580" issue

**Comment by ErikEJ** [comment]
Yes, you need the latest daily - will publish to MarketPlace very soon
