### ISSUE TITLE
Singularize entities just stopped working.

### ISSUE THREAD

**Issue by randalltomes** [ErikEJ/EFCorePowerTools#1584]
Describe what is not working as expected.

### Provide steps to reproduce

If you have a table named "StateCodes" and have "Pluralize or Singularize" is checked, "Use table and column names" is checked. Reverse engineer used to generate the entity class as "StateCode.cs". That was working like that a week ago and for the past year. I use this tool every few days. Now it is stuck on Pluralize and generates the entity class as "StateCodes.cs"

### Provide technical details

- Latest stable release. Yes

- Is Handlebars used: no/yes ??

- Is T4 used: no/yes ?

- Is .dacpac used: no/yes ?

- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu) ?

- Database engine: SQL Server

- Visual Studio version: The same issue is true in 2019 and 2022

**Comment by ErikEJ** [comment]
Which EF Core version??

**Comment by randalltomes** [comment]
It was 5.0.11 and .Net 5. Upgrading to .Net 6 and EF Core 7 it works again.
