### ISSUE TITLE
EF Core PowerTools 1206 - only EF Core 3

### ISSUE THREAD

**Issue by SvenCronenberg** [ErikEJ/EFCorePowerTools#1585]
Since our EF-Core PowerTools have been upgraded to 2.5.1206, we get when opening "Reverse engeneer" only the option to generate "EF Core 3" code. Ef Core 5 and higher are missing. This make EF Core Powertools unuseable for us - we had to downgrad manually to 
an older version (2.5.966) to continue working...

Any idea - do we need to upgrade .NET perhaps?

- we are using
Visual Studio 2019
.NET 5 (planning to upgrade to .NET 6 in the next months)
EF Core 5

We use .dacpac but no T4.

Our SQL Server is 14.0.2042.3

**Comment by ErikEJ** [comment]
.NET 5 and EF Core 5 are no longer supported. 

If you need a recent unsupported build that supports EF Core 5 let me know and will share a link to it privately.

**Comment by devuros** [comment]
> .NET 5 and EF Core 5 are no longer supported.
> 
> If you need a recent unsupported build that supports EF Core 5 let me know and will share a link to it privately.

Hi @ErikEJ ,

Could you please provide the link to EF Core 5 build mentioned above?

Kind regards

**Comment by ErikEJ** [comment]
@devuros  Please email me ejlskov at hotmail dot com - remember that .NET 5 is no longer supported and will not receive any security updates.
