### ISSUE TITLE
How to obtain the correct `IDatabaseModelFactory` to get the `DatabaseModel` of the database

### ISSUE THREAD

**Issue by JonPSmith** [ErikEJ/EFCorePowerTools#1586]
Hi @ErikEJ,

I'm trying to create a EF Core 7 version of my [EfCore.SchemaCompare](https://github.com/JonPSmith/EfCore.SchemaCompare) but the way to create a `IDatabaseModelFactory` has changed. Have you an example of how to create the a `IDatabaseModelFactory` for different providers, e.g. SQL Server, Sqlite?

**Comment by ErikEJ** [comment]
Nothing has changed there:

   serviceCollection.AddSingleton<IDatabaseModelFactory, CrmDatabaseModelFactory>();

(I only support SQL Server with schema compare at the moment)

**Comment by ErikEJ** [comment]
Ping?

**Comment by JonPSmith** [comment]
Hi @ErikEJ,

I only have access to the EF Core services, which doesn't contain the `IDatabaseModelFactory` service. I haven't changed the code for getting the relevant `DatabaseModelFactory` for many years and I'm a bit rusty. I'll have another look at it again and maybe ping you if I get stuck.

Thanks for your help.

**Comment by ErikEJ** [comment]
Thanks for the tip!
