### ISSUE TITLE
Visual Studio 2019 install Fails with missing dependency

### ISSUE THREAD

**Issue by Orgbrat** [ErikEJ/EFCorePowerTools#159]
Extension fails to install with missing dependency error for Visual Studio MPF 15.0

### Further technical details
EF Core Power Tools version: 2.2.0

Database engine: (SQlite, SQL Compact, SQL Server, Postgres)

Visual Studio version: Visual Studio 2019 16.0 Preview 1.1

**Comment by Orgbrat** [comment]
I downloaded the latest daily build and still get the same error.

**Comment by ErikEJ** [comment]
Fixed now! https://blogs.msdn.microsoft.com/visualstudio/2018/09/26/how-to-upgrade-extensions-to-support-visual-studio-2019/ (Removed Microsoft.VisualStudio.MPF.15.0 reference)
