### ISSUE TITLE
Add triggers to .dacpac based DatabaseModel (for EF Core 7)

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#1590]

**Comment by ErikEJ** [comment]
@dradermaker 
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

**Comment by dradermaker** [comment]
> @dradermaker I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

Installed the daily build and reverse engineered a database with triggers from a dacpac. Everything worked as expected. The generated DbContext now generates the HasTriggers property correctly.

Thhanks @ErikEJ

**Comment by ErikEJ** [comment]
Great! I will also update the NuGet package now.
