### ISSUE TITLE
Table names broken in EF Core 7 Reverse Engineering

### ISSUE THREAD

**Issue by mtbayley** [ErikEJ/EFCorePowerTools#1594]
Upgrading to EF Core 7 from 6 removes explicit table names. (Use table names from database)

### Steps to reproduce

Update EF Core 6 autogenerated code to EF Core 7

![image](https://user-images.githubusercontent.com/34929316/203417980-94b61141-e98b-4728-9196-53d152159fe1.png)

![image](https://user-images.githubusercontent.com/34929316/203418318-76d2fb57-dcdf-4206-a6ea-8af082de1487.png)

### Technical details

- EF Core version in use: EF Core 7

- Is Handlebars used: No

- Is T4 used: No

- Is .dacpac used: No

- EF Core Power Tools version: 2.5.1217

- Database engine: SQL Server

- Visual Studio version: Visual Studio 2022 Preview 17.5.0

**Comment by ErikEJ** [comment]
I think this is a known EF Core 7 bug, will hopefully be fixed in 7.0.2 or later.

/cc @bricelam
