### ISSUE TITLE
Need Schema name in Handlebars template

### ISSUE THREAD

**Issue by greyknight79** [ErikEJ/EFCorePowerTools#1595]
Need the schema name made available in the Handlebars templates.

### Provide steps to reproduce

Would like to be able to do the following in the Handlebar template
[Table("{{schema}}{{class}}")]

### Provide technical details

- EF Core version in use: EF Core 7

- Is Handlebars used: yes

- Is T4 used: no

- Is .dacpac used: no

- EF Core Power Tools version: 2.5.1206

- Database engine: SQL Server

- Visual Studio version: Visual Studio 2022

**Comment by ErikEJ** [comment]
Please ask in the [Handlebars repo](https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars)
