### ISSUE TITLE
EFCore 7 reverse engineering does not install the needed packages

### ISSUE THREAD

**Issue by LuciferSam8086** [ErikEJ/EFCorePowerTools#1597]
### Provide steps to reproduce
I am using the database reverse engineering function.

If I click the "Install the EFCore provider"  checkbox (sorry I'm using the Italian translation), nothing happens in EFCore 7.
If I use EFCore 6 everything works correctly.

The checkbox is the one with the red rectangle
![immagine](https://user-images.githubusercontent.com/118576915/203874257-bc629ed8-af4c-4e83-ad20-2255941dbe9f.png)

### Provide technical details

- EF Core version in use: EFCore 7

- Is Handlebars used: no

- Is T4 used: no

- Is .dacpac used: no

- EF Core Power Tools version: 2.5.1260.0

- Database engine: SQLite

- Visual Studio version: Visual studio 2022

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details)
