### ISSUE TITLE
Setter removed from Entity for Child Entities in EF 7

### ISSUE THREAD

**Issue by btcalit** [ErikEJ/EFCorePowerTools#1598]
This piggybacks on [#1582](https://github.com/ErikEJ/EFCorePowerTools/issues/1582) and [#1587](https://github.com/ErikEJ/EFCorePowerTools/issues/1587), of which both are marked closed.   @ErikEJ asked in both threads why would someone want to reassign the navigation property.  In my case we have several places where we sort the collection after it has been returned from the database.

`class.Students = class.Students.OrderBy(s => s.Property).ToList();`

Obviously a trivial example.  The collection of class.Students could have been originally retrieved from the database with or without a sort.  It could have been added to after the original query, etc.  However we need the final collection sorted in place.  Of course there are work arounds like clearing the original collection and adding to it a sorted one, using .Sort(), or customizing the T4 templates. However I'm trying to understand whether our usage goes against best practices?  What is the proper/recommended way of solving this?  There must be a reason why child properties are now read only.  This was not clear from both closed items referenced above.

**Comment by ErikEJ** [comment]
Does your entity classes serve multiple purposes? Maybe you need to rethink that?

**Comment by btcalit** [comment]
> Does your entity classes serve multiple purposes? Maybe you need to rethink that?

Maybe?  If we consider anything beyond retrieval of data to be beyond the scope of entities then yes.  Lets say your business layer retrieves the above mentioned class and its associated students from the database.  The business layer determines that the list of students should also contain a student by the name of John Smith.  Therefore it adds it to the collection.  It then returns the new list to services layer, which in turn serializes the data to JSON to return to the client.

If DTOs are used, we typically don't convert to DTOs in the business layer but in the services layer.  As such would you introduce yet another set of objects to fulfill this basic requirement of sorting the child collection?

**Comment by ErikEJ** [comment]
I am sure @bricelam has a good rreason for this change. In any case, using T4 would solve your issue (and I would not consider that a "workaround")

**Comment by ErikEJ** [comment]
@btcalit yes, I am not very good at collecting the warnings. I will try to improve that. 

Using the standard tooling you should see the warning.

**Comment by ErikEJ** [comment]
I will also consider adding a check to Power Tools if there is new templates available.

**Comment by btcalit** [comment]
Thanks @ErikEJ, a check within the Power Tools would be the perfect solution.  I'm assuming none of use that are using the Power Tools are also using the standard tooling, so that current warning within the T4 itself is all but useless.  From my perspective this is the biggest downside to customizing with T4, I'm worried I'd fall behind with old templates and not know when it is appropriate to update them.

**Comment by ErikEJ** [comment]
@bricelam which service would be best to override in order to collect the scaffolding warnings in a list of strings?

**Comment by ErikEJ** [comment]
@btcalit I have created #1601 and #1602

**Comment by ErikEJ** [comment]
@btcalit See explanation and som tips here:  https://github.com/ErikEJ/EFCorePowerTools/issues/1587#issuecomment-1344808549

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by btcalit** [comment]
@ErikEJ I was able to Reverse Engineer with "Customize code using templates" unchecked and I see the setters.

One question, in the release notes it states "Collection setters for EF Core 7 added back (via EF Core 7.0.5)".  My project still references 7.0.4 when I went through the reverse engineering process and it appears to have worked.  Where does 7.0.5 come into play?

**Comment by ErikEJ** [comment]
>> Where does 7.0.5 come into play?
@btcalit Good question! The reverse engineering "engine" is packed as a .NET command line tool, and that tool now uses EF Core 7.0.5.
