### ISSUE TITLE
Custom type mapping

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#16]
_From @mbeckenbach on February 3, 2018 9:40_

This project is awesome! It feels just like the db first workflow is coming back. But there is one feature that I am really missing.

In EF6 DB First, there is this amazing feature of mapping external types to properties.
This can be perfectly be used for transforming an integer culumn into a C# enum.

EF Core supports enum properties and maps those to integer columns in the database.

When doing a reverse engineer, all integer columns get generated as integer properties as it should be. Then one can simply change a properties type to some enum type, which exists in the project. Works great.

But when repeating the reverse engineer process to update the generated model from database, the file will be overwritten, which removes the modification of the properties type.

So I was thinking about how it would be possible to preserve this modification.

One way of doing this could be to create a code template for a specific class file. I had a look at EntityFrameworkCore.Scaffolding.Handlebars by @tonysneed but I dont see a way for doing this.

Another idea was to extend the efpt.config.json with an array of type mappings, that could be applied after code generation. Could something like that be implemented in your tool?

```json
{
  "ContextClassName": "EfcoretestContext",
  "DatabaseType": 2,
  "IdReplace": false,
  "IncludeConnectionString": true,
  "OutputPath": "Models",
  "ProjectRootNamespace": "EFCoreTest",
  "SelectedToBeGenerated": 0,
  "Tables": [ "dbo.Posts", "dbo.Users" ],
  "UseDatabaseNames": false,
  "UseFluentApiOnly": true,
  "UseHandleBars": true,
  "UseInflector": true,
  "TypeMappings": [
    { "Column": "dbo.Posts.Category", "Type": "Enums.Categories" }
  ]
}
```

_Copied from original issue: ErikEJ/SqlCeToolbox#621_

**Comment by ErikEJ** [comment]
Anything goes, and the tool is open source and welcomes contributions!

Could you show an example of what a class with a Enum would look like before and after this?

**Comment by ErikEJ** [comment]
_From @mbeckenbach on February 4, 2018 7:57_

Hi @ErikEJ, good to hear that.

A typical example for my use case would be like this. You have a custom enum in some folder/namespace and a generated class like the ones below.

```c#
namespace EFCoreTest.Enums
{
    public enum Categories
    {
        SomeCategory = 0,
        AnotherCategory = 1,
        MoreCategories = 2
    }
}
```

```c#
namespace EFCoreTest.Models
{
    public partial class Post
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public int Category { get; set; }
    }
}
```

After transformation the class would simply look like this:

```c#
public partial class Post
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public Enums.Categories Category { get; set; }
    }
```

**Comment by ErikEJ** [comment]
OK. since I just get the generated files, maybe it would be better with

```
 "TypeMappings": [
    { "Class:"Post", "Property":"Category", "Type": "Enums.Categories" }
  ]
```
Do a PR, perhaps?

https://github.com/ErikEJ/SqlCeToolbox/blob/master/src/GUI/ReverseEngineer20/EFCoreReverseEngineer.cs#L130

**Comment by ErikEJ** [comment]
_From @mbeckenbach on February 6, 2018 6:54_

I have never edited a vs extension. But i'll try at weekend. :-)
Thanks for the hint on the line.

**Comment by ErikEJ** [comment]
Great, let me know if you hit any stumbling blocks! (It is a bit more involved than a standard Nuget library)

**Comment by tonysneed** [comment]
My Handlebars library handles this scenario now.  See the project [ReadMe](https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#handlebars-helpers-and-transformers) for an example of adding an enum transformation and mapping it with a partial method.

**Comment by tonysneed** [comment]
Just need to check, how are helper and transform methods are added when using EF Core PT’s?

**Comment by ErikEJ** [comment]
There are many options to do this, while preserving the modifications when reverse engineering is run a second time:

For the Enum, create at MyTypeEnum property in the partial entity class.

For special translations, use the OnModelCreating partial method to modify the model with Value Conversions https://docs.microsoft.com/en-us/ef/core/modeling/value-conversions

**Comment by AlexVPerl** [comment]
Thank you for creating this tool. I was looking for Enum mapping as well and came across this post. 

I tried adding the following to efpt.renaming.json but it didn't have any effect:
"TypeMappings": [
    { "Class:"Post", "Property":"Category", "Type": "Enums.Categories" }
  ]

Could you please clarify what's the recommended way of mapping Enums with EF Core Power Tools? Thanks!

**Comment by ErikEJ** [comment]
@AlexVPerl create a NonMapped enum property in a partial class

**Comment by AlexVPerl** [comment]
@ErikEJ thank you for prompt reply. Do you mean an Enum wrapper property that would set/get persisted numeric value? 

If so, I was trying to avoid that since then EF will do in memory filtering when Enum is mentioned in the LINQ query.

Above, there is a mention of using OnModelCreating partial method with Value Conversions - this would be ideal. But it doesn't seem possible since all columns will be mapped in the auto generated class, and EF won't allow mapping 2 properties to single column. Having a way to ignore a column when using Rev. Eng. auto generation would make it possible to manually do Value Conversions for it. Or is there another way?

Thanks.

**Comment by ErikEJ** [comment]
At the moment this is not supported. Happy to receive ideas or a PR for implementation.

**Comment by jamshally** [comment]
> @ErikEJ thank you for prompt reply. Do you mean an Enum wrapper property that would set/get persisted numeric value?
> 
> If so, I was trying to avoid that since then EF will do in memory filtering when Enum is mentioned in the LINQ query.
> 
> Above, there is a mention of using OnModelCreating partial method with Value Conversions - this would be ideal. But it doesn't seem possible since all columns will be mapped in the auto generated class, and EF won't allow mapping 2 properties to single column. Having a way to ignore a column when using Rev. Eng. auto generation would make it possible to manually do Value Conversions for it. Or is there another way?
> 
> Thanks.

@AlexVPerl , @ErikEJ  - I am also looking for a way to Map an enum value to a string. If I understand correctly, the one thing blocking @AlexVPerl's suggested solution was the ability to ignore a column. Well, it seems that this feature was recently added via a pull request: https://github.com/ErikEJ/EFCorePowerTools/issues/572

I'm going to give that a go, but leaving this train of thought here for others to help save them some time. I'll make another note if I have anything interesting to report

**Comment by jamshally** [comment]
> I'm going to give that a go, but leaving this train of thought here for others to help save them some time. I'll make another note if I have anything interesting to report

- Well, for me, good news and bad news... it looks like ignoring a column is new baked right into the UI! (Nice feature@ErikEJ)
- In my case, it seems I can not ignore the column I want to transform into an Enum because it part of the primary key... so, I will find a different approach

**Comment by ErikEJ** [comment]
Create a proper, surrogate primary key?

**Comment by ErikEJ** [comment]
Custom [enum mapping](https://github.com/ErikEJ/EFCorePowerTools/issues/1472#issuecomment-1220273164) is now available with EF Core 7 and T4 templates
