### ISSUE TITLE
no pop  'select database' window

### ISSUE THREAD

**Issue by yuittgithub0115** [ErikEJ/EFCorePowerTools#1604]
vs2019 + MariaDB 
when i use EF Core Power Tools, Reverse Engineer ,there no pop window to select database,  throw an exception:
System.ArgumentNullException: ......null.
parameter name:provider
  at T Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService<T>(IServiceProvider provider)
  at TView EFCorePowerTools.EFCorePowerToolsPackage.GetView<TView>()
  at async Task.......................
  at async Task EFCorePowerTools.Handlers.ReverseEngineer..........

**Comment by ErikEJ** [comment]
Which Power Tools version?

**Comment by ErikEJ** [comment]
Ping?

**Comment by ErikEJ** [comment]
I beleive this is fixed in the latest version of the tool - duplicate of #1580
