### ISSUE TITLE
MySQL - Database First, DateTime MaxLength InvalidCastException

### ISSUE THREAD

**Issue by mludlum** [ErikEJ/EFCorePowerTools#1605]
These fields are generated from a mysql table
        [MaxLength(6)]
        public DateTime StartDate { get; set; }
        [MaxLength(6)]
        public DateTime? EndDate { get; set; }

The table's fields look like this:
| StartDate          | datetime(6)  | NO   | MUL | NULL                  |                   |
| EndDate            | datetime(6)  | YES  | MUL | NULL                  |                   |

This confuses EF Core into thinking it's a string field because there is a MaxLength attribute.  The 6 is for fractional seconds.

I'm getting this exception when inserting a record.  
    InvalidCastException: The field of type System.DateTime must be a string, array or ICollection type.

Removing the attribute or converting the mysql field to datetime without fractional seconds fixes the problem.
I can convert many of my datetime fields to just datetime, but there are some where I need milliseconds.

**Comment by ErikEJ** [comment]
Sounds like a MySQL provider issue. Please report in the Pomelo repo
