### ISSUE TITLE
Visual Studio for Mac Support

### ISSUE THREAD

**Issue by tpitman** [ErikEJ/EFCorePowerTools#1606]
Any chance this can be made to run on MacOS (Intel and M1)?

If not, does anyone have a suggestion for something similar that does?

**Comment by ErikEJ** [comment]
The standard command line tooling does. And you should be able to run the tool from the command line as mentioned [in the docs](https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#requirements)

**Comment by tpitman** [comment]
I am not sure even how to install it. When I go to the extensions menu in Visual Studio on Mac and search, it doesn't come up. I think the extensions list for Mac are very limited.

The download from the marketplace is a vsix file and those are windows only as far as I know.

So the question is how do I install the extension on Mac so I can even use the command line as you suggest?

**Comment by tpitman** [comment]
Also, this is an M1 mac, so anything that requires Intel won't run as far as I know.

**Comment by ErikEJ** [comment]
You need to download the vsix and extract the cli zip inside it. 

The target CPU issue can be fixed.

**Comment by tpitman** [comment]
I downloaded the vsix and changed the extension to .zip and extracted it. Which file(s) are the cli and where do I put them?

How do I fix the target CPU issue?

As I was just reading through your work arounds I realized most of your examples are for SQL Server. I am using a Postgres DB. Does this work with that and get all its information from the project or do I have to manually do something?

**Comment by tpitman** [comment]
I decided to just try the command line that you mentioned. I used the following:

`dotnet ef dbcontext scaffold Name=ConnectionStrings:DatabaseConnection Npgsql.EntityFrameworkCore.PostgreSQL --project MyProject.Api.Data --startup-project MyProject.Api`

This succeeded in making the classes. There are some differences in the way the DbContext gets generated versus what I usually like. Here is what I normally do:

	public class DatabaseContext : DbContext
	{
		public DbSet<UserEntity> Users { get; set; }
		public DbSet<AddressEntity> Addresses { get; set; }
		public DbSet<FirmEntity> Firms { get; set; }

		public DatabaseContext(DbContextOptions options) : base(options) { }

		protected override void OnModelCreating(ModelBuilder modelBuilder)
		{
			base.OnModelCreating(modelBuilder);

			modelBuilder.Entity<AddressEntity>()
				.HasOne(a => a.User)
				.WithMany(u => u.Addresses)
				.HasForeignKey(x => x.UserId);

			modelBuilder.Entity<UserEntity>()
				.HasOne(u => u.FirmOwner)
				.WithOne(f => f.Owner)
				.HasForeignKey<UserEntity>(x => x.UserId);
		}
	}

Here is what that command line generated:

    public partial class NationalAccessContext : DbContext
    {
        public DatabaseContext()
        {
        }

        public DatabaseContext(DbContextOptions<DatabaseContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Address> Addresses { get; set; }

        public virtual DbSet<User> Users { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            => optionsBuilder.UseNpgsql("Name=ConnectionStrings:DatabaseConnection");

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Address>(entity =>
            {
                entity.ToTable("Address");

                entity.HasIndex(e => e.UserId, "IX_Address_UserId");

                entity.HasOne(d => d.User).WithMany(p => p.Addresses).HasForeignKey(d => d.UserId);
            });

            modelBuilder.Entity<User>(entity =>
            {
                entity.ToTable("User");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }

The big question, however, is what does your tool bring to the system? I was able to perform that command line without using your stuff because I couldn't install it. All of the above I guess comes built into dotnet core?

**Comment by ErikEJ** [comment]
The advantages of my tool us described in the wiki. A number of features like function and stored procedure mapping is SQL Server only.

**Comment by tpitman** [comment]
Colleagues of mine swear by your tool and that is why I was hoping it worked on the MacOS version of Visual Studio.

Please understand my questions were just to understand what I a missing out on. Sounds like a lot from both you and my colleagues.

Maybe some day it will be available on MacOS. I can only hope so....

Thank you for all your hard work and baring with my questions...

**Comment by ErikEJ** [comment]
I am wondering if you actually read the link from the docs mentioned above?

https://github.com/ErikEJ/EFCorePowerTools/issues/340#issuecomment-670929754

**Comment by tpitman** [comment]
I did. I have not actually gone through those steps yet, but will take a look.

I will have to try opening the solution in VS for Mac and see if maybe I can build some of the tools for Mac. Who knows, maybe it will all work.

Thank you again. You efforts for the community are greatly appreciated.

**Comment by ErikEJ** [comment]
For anyone watching this issue, this is now planned, and you can find a design proposal [here](https://github.com/ErikEJ/EFCorePowerTools/issues/1751) - looking forward to any comments/suggestions.

**Comment by ErikEJ** [comment]
Preview 1 of the CLI tool is [now available](https://www.nuget.org/packages/ErikEJ.EFCorePowerTools.Cli/7.0.0-preview1#readme-body-tab)

![image](https://user-images.githubusercontent.com/4169187/234258058-2b6def58-f87c-455a-93da-21cd09d9e3f7.png)
