### ISSUE TITLE
[Feature request] Add menu option for quick Reverse Engineer

### ISSUE THREAD

**Issue by janseris** [ErikEJ/EFCorePowerTools#1607]
Everything is working as expected but when I am making a lot of changes to the database in a lot of steps, I need to refresh EF models frequently.
To do that, I have to (assuming I have already at least once successfully reverse engineered the database schema for this project):
1. rightclick the project
2. select EF Core Power Tools 
3. select Reverse Engineer
4. click OK (in Choose Database Connection dialog)
5. click OK (in Choose Database Objects dialog)
6. click OK (in Generate EF Core Model in project {ProjectName} dialog)

It would be nice if instead of steps 3,4,5,6 I could click an option called something like `"Reverse Engineer with last used settings"`  or `"quick Reverse Engineer"`.

**Comment by ErikEJ** [comment]
Have you tried right clicking the efpt.config.json file?
