### ISSUE TITLE
Generated Methods for Procedures with default (null) values

### ISSUE THREAD

**Issue by WycoffJohn** [ErikEJ/EFCorePowerTools#1608]
Describe what is not working as expected.

Reverse engineer stored procedure with default value. (I am using null but I assume this would occur for any default value).
```
create procedure pr_sel_fannyCakes
	 @isButtermilk bit
	,@syrupFlavor varchar(50) = null

as

if (@syrupFlavor is not null) begin
	-- Do something
end

select *
from fannyCake fc
where isButtermilk = @isButtermik
go
```

### Provide technical details
Generated procedure method will look something like:
```
public virtual async Task<List<pr_sel_fannyCakesResult>> pr_sel_fannyCakesAsync(bool isButtermilk, string syrupFlavor, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default) {
            ...
            var _ = await _context.SqlQueryAsync<pr_sel_fannyCakesResult>("EXEC @returnValue = [dbo].[pr_sel_fannyCakes] @isButtermilk, @syrupFlavor", sqlParameters, cancellationToken);
        }
```

The method does not allow you to omit the nullable parameter. It should look like this:
```
public virtual async Task<List<pr_sel_fannyCakesResult>> pr_sel_fannyCakesAsync(bool isButtermilk, string? syrupFlavor = null, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default) {
            ...
            var _ = await _context.SqlQueryAsync<pr_sel_fannyCakesResult>("EXEC @returnValue = [dbo].[pr_sel_fannyCakes] @isButtermilk, @syrupFlavor", sqlParameters, cancellationToken);
        }
```
Note the default value on the syrupFlavor parameter.

With this you can then omit the parameter from the method call vs needing to set each parameter with a default to its default value. (Duplicating code that is already in the stored proc).

One downside, because C# requires params with a default at the end, this would of course change the order of parameters in the C# method to not match the stored proc parameter order.

- EF Core Power Tools version: 2.5.1219.0
- Database engine: Microsoft SQL Server 2019 (RTM) - 15.0.2000.5 (X64)
- Visual Studio version: Visual Studio 2022

**Comment by ErikEJ** [comment]
Can you share your csproj file?

Maybe related to nullable reference types?

**Comment by ErikEJ** [comment]
Also, there is not a supported way to get the default values of parameters - https://stackoverflow.com/questions/6992561/is-there-a-solution-for-getting-the-default-value-of-the-parameters-of-a-given-s

**Comment by ErikEJ** [comment]
Ping?

**Comment by ErikEJ** [comment]
Closing as the additional requested info was never provided

**Comment by WycoffJohn** [comment]
Sorry @ErikEJ I didn't see your response. I will put together a sample project and post in the next week or two.

In the meantime, if you just don't supply the parameter with the default value, SQL will use the default value. Otherwise if you supply NULL, SQL will use NULL ignoring the default value.

Also, my "should look like this" example wasnt exactly correct. IF no value was supplied for the syrupFlavor param the SQL command text should look like this:
`"EXEC @returnValue = [dbo].[pr_sel_fannyCakes] @isButtermilk"`
Note the missing @syrupFlavor.

But from reading the link you provided, if you have no way to get the default param AND no way to determine if the param has a default I dont know if there is anything you can do about this.

Can you tell if a param is "nullable"? I *think* once a sql param has a default value it becomes nullable. If the param is nullable and no param value was supplied in the method call then omit the sql param from the sql command text. SQL will use the default value.

However, what if the default is say an int of 5 for example. You may not be able to tell if the method caller did not provide a param value or explicitly set the value to NULL, thus intending to send NULL as the param.

I will dig into this more and post a comment back.
FYI, later on in that SO link you supplied there are some answers about obtaining the default param values although I didn't read deep into it and it seemed hokey.

**Comment by ErikEJ** [comment]
I really need a repro from you.
