### ISSUE TITLE
Reverse engineer Postgres Functions? is this possible as you we use this in place of stored procs on postgres 

### ISSUE THREAD

**Issue by Skyhikeeper** [ErikEJ/EFCorePowerTools#1610]
Using visual studio 2022 and postgres 14 
I would like to know if it is possible to reverse engineer the functions from postgres, I have done the tables and the views but all outstanding it the functions 

Terence

**Comment by ErikEJ** [comment]
It is possible, but it is not something I have currently implemented. Happy to assist if someone steps up to do it.
