### ISSUE TITLE
Possible enhancement

### ISSUE THREAD

**Issue by mrunks** [ErikEJ/EFCorePowerTools#1612]
I would like to have additional .T4 files in be read when the power tools are used and have the same behavior for output as exists for EntityType.T4

For example the CodeTemplates folder "could" have the following:
     EntityType.T4
     EntityServicesT4
     EntityController.T4
     EntityView.t4
     EntityWhatever.T4

     
The power tools would generate a file for each table just like the behavior for generating models from the content in EntityType.T4 

So if I had the following Table:

Person
Address
Phone
Company

I would the following files generated:

Person.cs  
PersonService.cs
PersonService.cs
PersonWhatever.cs

Address.cs
AddressService.cs
AddressController.cs
AddressWhatever.cs

Currently I just have two EntityType.T4 files with different content and I run one rename it and then the other, but having the PowerTools read any file in the folder and treat it with the same behavior as EntityType.t4 would be nice.

**Comment by ErikEJ** [comment]
How do you specify a file name of EntityTypeController ?

**Comment by mrunks** [comment]
I would imagine EntityTypeController.t4 would have a filename generated as whatever the Class is plus controller.
For the person table it would be  PersonController.cs

In my example above I used the Names EntityService, EntityController, but that probably should have read "EntityType" since that is what PowerTools uses as the placeholder for the class name.   If I had to specify "EntityType" as the prefix that would be perfect.

**Comment by ErikEJ** [comment]
> I would imagine EntityTypeController.t4 would have a filename generated as whatever the Class is plus controller.

Can you do that today? And if, so how?

**Comment by mrunks** [comment]
Just to clarify I can create any folder name CodeTemplatesXXX and it will iterate them and parse the EntityType.T4 file spit out code ? And I could have "n" number of folders with an entityType.T4 file in each doing their own thing?  

Also if i named the output extension= "Service.cs" that means it would create  PersonService.cs for example ?

If so then this enhancement would be exactly what I need. Awesome!

**Comment by ErikEJ** [comment]
Your understanding is correct.

I will keep you posted on progress.

**Comment by ErikEJ** [comment]
I had another look. The path to the templates is actually hardcoded to "CodeTemplates/EFCore" 
 https://github.com/dotnet/efcore/blob/main/src/EFCore.Design/Scaffolding/TemplatedModelGenerator.cs

So you need to place the folder structure in various folders, something like:

/CodeTemplates/EFCore
/Views/CodeTemplates/EFCore
/Services/CodeTemplates/EFCore

**Comment by mrunks** [comment]
So are you going to look for any "codeTemplates" in the project or will I have to specify those exact names?   For example
If i did  /Temp/CodeTemplates/EFCore  you would know how to find that path ?  Or I would have to make sure I did "Services" or "Views"?

**Comment by ErikEJ** [comment]
I will locate any folders automagically

**Comment by mrunks** [comment]
This works great thanks!

**Comment by ErikEJ** [comment]
Nice. I will add this to the docs then

**Comment by BaldyFreak** [comment]
> I implemented this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.
> 
> If it works for you I will update the docs with a description of this feature.

excellent feature!!!

**Comment by ErikEJ** [comment]
@BaldyFreak Which words were causing you trouble?

**Comment by BaldyFreak** [comment]
> @BaldyFreak Which words were causing you trouble?

noting
