### ISSUE TITLE
RE NET 6 Blazor - No database provider has been configured for this DbContext

### ISSUE THREAD

**Issue by schorges** [ErikEJ/EFCorePowerTools#1615]
On a new Project with actual packets on ReverseEngine fails to connect to my DB.

Add the Connection String to the appsettings.json load successfull
My Program.cs:
```

var connectionString = builder.Configuration.GetConnectionString("DefaultConnection");

builder.Services.AddMySql<MyDbContext>(connectionString, ServerVersion.AutoDetect(connectionString));
```

with include the string it works fine, but on uncheck to include string the  OnConfiguringMethode was not autogenerate

```
 protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseMySql("server=servername;user id=test;password=test;persistsecurityinfo=True;database=myDb;convertzerodatetime=True", Microsoft.EntityFrameworkCore.ServerVersion.Parse("10.4.21-mariadb"));
            }
        }
```

- EF Core version in use: EF Core 7 also in EF Core 6 
- NET 6 Blazor

- Is Handlebars used: no/yes

- Is T4 used: no/yes

- Is .dacpac used: no

- EF Core Power Tools version: 2.5.1225.0

- Database engine: MySql  Pomelo.EntityFrameworkCore.MySql
- Visual Studio version: Visual Studio 2022

**Comment by ErikEJ** [comment]
You should inject you Options in the constructor. And never include your connection string in code.

**Comment by schorges** [comment]
When i run the Reverse Engine and add the connection string in program.cs from appsettings.json, become the error  "No Database Provider has been..."

**Comment by ErikEJ** [comment]
In need a repro, sounds like you are doing something wrong.

**Comment by schorges** [comment]
Is it normal that on uncheck the " ConnectionString to Code..." it is not create the OnConfiguring(DbContextOptionsBuilder...
Method on

**Comment by ErikEJ** [comment]
Yes, it is

**Comment by schorges** [comment]
Is it possible to add an other service to builder on Program.cs ?
I have set a breakpoint to :

```
public MyDbContext(DbContextOptions<SimonwebContext> options)
        : base(options)
    {
    
```
but the point will not be reached. I'm onl add:

`builder.Services.AddMySql<SimonwebContext>(builder.Configuration.GetConnectionString("DefaultConnection"), ServerVersion.AutoDetect(builder.Configuration.GetConnectionString("DefaultConnection")));`

**Comment by ErikEJ** [comment]
I have no idea what you are talking about, if you want help please share a full repro

**Comment by schorges** [comment]
Sorry, I don't want upload a repo here.

I have found a Solution:

1. Reverse Engiering and NOT Include connectionstring to Code
2. 2. Add "ConnectionStrings" to your configuration file descript in PowerToolReadMe.txt (secrets.json, appsettings.Development.json or appsettings.json).
```

    {
        "ConnectionStrings": {
            "DefaultConnection": "server=simnas2deb;user id=simon;password=03078980;persistsecurityinfo=True;database=simon;convertzerodatetime=True"
        }
    }

```
3. Create Partial DbContext File to keep them when recreating like this:
```
using Microsoft.EntityFrameworkCore;

namespace TestDB.Data
{
    public partial class MyDbContext : DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                IConfigurationRoot configuration = new ConfigurationBuilder()
                   .SetBasePath(Directory.GetCurrentDirectory())
                   .AddJsonFile("appsettings.json")
                   .Build();                
                optionsBuilder.UseMySql(configuration.GetConnectionString("DefaultConnection"), ServerVersion.AutoDetect(configuration.GetConnectionString("DefaultConnection")));
            }
        }
    }
}

```
And now everything works fine!

No changes on Program.cs, this does not work for me...
