### ISSUE TITLE
Pluralization mistakes

### ISSUE THREAD

**Issue by sgartner-cityofboise** [ErikEJ/EFCorePowerTools#1617]
This problem may be within the EF6 pluralizer and out of your control, but I figured I'd submit it and get a ruling.
I am reverse engineering from a SQL Server database which includes the following reference table:

    CREATE TABLE AppSecApplication.HealthStatus
    (
        HealthStatusId INT           CONSTRAINT PK_HealthStatus PRIMARY KEY CLUSTERED
       ,Name           NVARCHAR(50)  NULL
       ,Description    NVARCHAR(MAX) NULL
       ,SortOrder      INT           NOT NULL --- The order to be used for displaying this list (not alphabetically by default).
    );

The class that it generates is:

    [Table("HealthStatu", Schema = "AppSecApplication")]
    public partial class HealthStatu
    {
        [Key]
        public int HealthStatusId { get; set; }
        [StringLength(50)]
        public string Name { get; set; }
        public string Description { get; set; }
        public int SortOrder { get; set; }
    }

The data context it generated was:

    public virtual DbSet<HealthStatu> HealthStatus { get; set; }

        modelBuilder.Entity<HealthStatu>(entity =>
        {
            entity.HasKey(e => e.HealthStatusId)
                .HasName("pk_HealthStatus");

            entity.Property(e => e.HealthStatusId).ValueGeneratedNever();
        });

- EF Core version in use: EF Core 6

- Is Handlebars used: no

- Is T4 used: no

- Is .dacpac used: no

- EF Core Power Tools version: 2.5.1219.0
- I used the EF6 Pluralizer (if I uncheck this, I get the proper singularization/pluralization of HealthStatus)
- I checked Pluralize or singularize generated object names (English)

- Database engine: SQL Server

- Visual Studio version: Visual Studio 2022

I thought maybe I could fix this with efpt.renaming.json, but after looking at the documentation for that I'm not now sure it was intended to fix pluralization problems, but more about renaming tables and columns.

**Comment by ErikEJ** [comment]
Rename the table via efpt.renaming.json to something not ending in Status or stop using the broken pluralizer which never will receive any updates/fixes.
