### ISSUE TITLE
Automatically adding clarifying using statements

### ISSUE THREAD

**Issue by sgartner-cityofboise** [ErikEJ/EFCorePowerTools#1618]
When generating code for my SQL Server database, I have a table called "Environment."  Unfortunately, there is also an Environment in System.  When I generate the code using Scaffold-DbContext, it adds the following to the context class:

using Environment = IT.ApplicationSecurityAdmin2.DAL.Models.Environment;

which EFPT did not generate (so the file does not compile without modification).  It would be great if Power Tools compared the generated class names against the four packages it includes by default:

        System;
        System.Collections.Generic;
        Microsoft.EntityFrameworkCore;
        Microsoft.EntityFrameworkCore.Metadata;

and adds the appropriate clarifications.

Is there a workaround, aside from editing the generated file every time, to fix this with the version I have?

- EF Core version in use: EF Core 6

- Is Handlebars used: no

- Is T4 used: no

- Is .dacpac used: no

- EF Core Power Tools version: 2.5.1219.0

- Database engine: SQL Server

- Visual Studio version: Visual Studio 2022

**Comment by ErikEJ** [comment]
Rename the class via efpt.renaming.json to something other than Environment.

**Comment by ErikEJ** [comment]
Power Tools does not load your code (unlike the command line tool) - this is by design.

**Comment by ErikEJ** [comment]
In EF Core 7 you can also use T4 templates and add the using to the DbContext.t4 file
