### ISSUE TITLE
Something must have changed over the past few days as the feature is no longer working.

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#1621]
Something must have changed over the past few days as the feature is no longer working. I have tried uninstalling and reinstalling the latest extension.  And have the following Two folder structures in place

CodeTemplates
       EFCore
             DbContext.T4

Process
      CodeTemplates
              EFCore
                  EntityType.T4

Last Thursday the extension would pick up EntityType.T4 under the process folder and generate code but after installing version 2.5.1234  code is not being generated from the EntityType.T4 under the Processs path.  Is there something else that might have caused it to stop. I updated visual studio but then tried to reinstall the extension with no luck.

_Originally posted by @mrunks in https://github.com/ErikEJ/EFCorePowerTools/issues/1499#issuecomment-1357739405_

**Comment by ErikEJ** [comment]
@mrunks I have created a seperate issue for this!

I have added validation that both templates are present in the folder copy.

Did it work for you if only EntityType.t4 was present?

**Comment by mrunks** [comment]
Last week it worked when I only had EntityType.T4 under a different directory.  Thats is how I assumed it work as well so I do not necessarily need a dbcontext for each subfolder.  Or is a dbcontext required even if it is not used for each folder ?

**Comment by ErikEJ** [comment]
I will update the check to look for either one or the other.

**Comment by ErikEJ** [comment]
Fixed in latest daily, if you can confirm the fix I will update the MarketPlace release

**Comment by mrunks** [comment]
I just uninstalled .1234 and installed .1235 and it works again as before.   Thanks!
