### ISSUE TITLE
Oracle reverse engineering not completing processing

### ISSUE THREAD

**Issue by karenpayneoregon** [ErikEJ/EFCorePowerTools#1623]
Describe what is not working as expected.

### Provide steps to reproduce

Reverse engineer Oracle database.

- Add connection with EF Core 7 selected and current Oracle NuGet package 7.21.8 already installed
- Test connection, good
- Click OK
- Goes back to `Choose Database Connection` dialog
- Choose tables never appears

If I manually create a DbContext with a connection string and one model this works without Power Tools.

Note, SQL-Server reverse engineering is working.

Please include a **complete** description or project that I can redo/run to reproduce the issue.

### Provide technical details

- EF Core version in use: (e.g. EF Core 7)
EF Core 7

- Is Handlebars used: no/yes
No
- Is T4 used: no/yes
No
- Is .dacpac used: no/yes
No
- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
2.5.1236
- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)
Oracle
- Visual Studio version: (e.g. Visual Studio 2022)
VS2022 17.4.3

**Comment by ErikEJ** [comment]
What type of connection do you create? There is no built in VS 20220 support from Oracle, and you must use a "Custom Connection"

**Comment by karenpayneoregon** [comment]
I tried using a custom connection

`Data Source=XXXX;Persist Security Info=True;Enlist=false;Pooling=true;Statement Cache Size=10;User ID=XXX;Password=XXX;`

**Comment by ErikEJ** [comment]
Is that a valid Oracle connection string??

**Comment by karenpayneoregon** [comment]
Excluding the `XXX` yes as I validated this from another project which I manually scaffold and read back data.

**Comment by karenpayneoregon** [comment]
Okay, I tried again using the connection string.

- Select defined connection string
- At bottom of screen indicates loading....
- Five minutes later presents tables/views
- Configure
- Run

**Notes**
Using paid version [Toad](https://www.quest.com/products/toad-for-oracle/) the schema browser loads up in one to two seconds

So Power Tools is working and guessing there may be interference possibly with anti-virus software as when reverse engineering SQL-Server located on the network is instantaneous. Difference between Oracle and SQL-Server perhaps a different security model?

**Comment by ErikEJ** [comment]
That must be due to the schema queries generated by the Oracle EF Core provider..

@alexkeh FYI

**Comment by alexkeh** [comment]
Is there a way to collect a trace with timestamps? That could tell us what query is taking a long time to execute.

**Comment by ErikEJ** [comment]
@alexkeh is it not possible to do that Server side?

**Comment by alexkeh** [comment]
@ErikEJ Yes, but server side tracing is more complex to deal with when diagnosing a single connection problem. If there's other DB connectivity, you have to filter out other sessions and isolate on the specific session being used. DBAs do this all the time, but no so much among app developers.

Of course, the assumption is that it's a slow running query, but there could be a provider slowness or client issue, which a client trace would capture.

If there is no tracing at the app level, the next best option is Oracle client network (SQL*Net) tracing, which basically records what's being done on the  Oracle client side and timestamps how long each step takes.

**Comment by ErikEJ** [comment]
@karenpayneoregon Are there many objects in the database?

**Comment by karenpayneoregon** [comment]
There are over 180 tables, views and sequences (sorry for the late reply). Its a mature schema build over 20 years and this is the dev environment, not staging or prod.
