### ISSUE TITLE
Insufficient control over Humanizer Pluralizer

### ISSUE THREAD

**Issue by JonruAlveus** [ErikEJ/EFCorePowerTools#1624]
Hi, I'm hitting an issue with the Humanizer IPluralizer on table names ending Data (desired = tblUserData => UserData) becoming Datum (actual = tblUserData => UserDatum). While I understand that datum is treated as the plural of data, I don't really want it to be pluralised (for at least the table names). I cannot currently control the table name pluralization. I already override the table name to remove the tbl (tired both by hand and by using a regex) and it looks like, no matter the overrides set, I can't stop the pluralizer doing it's thing.

What I'd like to be able to do would be a way to control either:

1. What type of entities gets the pluralizer applied (for example I really do want pluralised navigation properties, but not table names)
2. A way to override the pluralizer with a list of words to ignore (or .EndsWith)

I think 1 might be impossible due to the inheritance of RelationalScaffoldingModelFactory and it only taking a single IPluralizer. 2 might be possible through DI on the constructor of the HumanizerPluralizer class, or a static property, with a list of words to ignore or something like that, coming from a json file somewhere.

Let me know your thoughts! I haven't tried handlebars or T4, but I don't think they'd help in this instance?

### Provide steps to reproduce

Have a table called tblUserData. Use Humanizer Pluralizer and override the name in renaming.json. When reverse engineering, the model/class generated is UserDatum.

### Provide technical details

- EF Core version in use: EF Core 3

- Is Handlebars used: no

- Is T4 used: no

- Is .dacpac used: no

- EF Core Power Tools version: 2.5.1236

- Database engine: SQL Server

- Visual Studio version: Visual Studio 2022

**Comment by ErikEJ** [comment]
If you are able to create a test that shows that you can override with Humanizer then I will consider adding this to the tool.

https://github.com/Humanizr/Humanizer/blob/main/readme.md

**Comment by ErikEJ** [comment]
Ping?

**Comment by JonruAlveus** [comment]
Pong?

I wish I could extend Humanizer like that 😉 But I was thinking of something that goes in the Humanizer IPluralizer around Humanizer. I’m putting together a PR to show what I mean, probably tomorrow now.

**Comment by JonruAlveus** [comment]
I've finally got the PR together but to be honest I got a little lost in the code! Essentially what I'm thinking is a new section in the schema, just a string list, that gets looped over and applied as Uncountables to humanizer. After that, I'm not really sure where to go, there's a lot of code here!  Essentially it's where in the code it should set the uncountables that I couldn't work out.

Let me know what you think.

https://github.com/ErikEJ/EFCorePowerTools/pull/1632

**Comment by ErikEJ** [comment]
Please add a test for the word UserData

**Comment by JonruAlveus** [comment]
Sorry should have done that to start with. Done now.

**Comment by ErikEJ** [comment]
Great. I will have a closer look.

**Comment by ErikEJ** [comment]
>> but to be honest I got a little lost in the code!

I dont blame you, it is a bit complex sine the actual reverse engineering is a .net command line tool.

It also looks like "Uncountables" is the best approach to excluding a word completely.

**Comment by JonruAlveus** [comment]
Thanks for your efforts on this. When might we be likely to see this merged/the tool be updated? No rush from my end given it's the Christmas season 👍

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out. I have also updated the [docs](https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#pluralization)

I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details)

**Comment by JonruAlveus** [comment]
Just tried this in a local test environment, works exactly as planned, thanks.

**Comment by ErikEJ** [comment]
Great to know, and thanks for the heads up! Did you have a look at the now docs and did they make sense?
