### ISSUE TITLE
Reverse Engineer for EF Core 3.1 not working

### ISSUE THREAD

**Issue by kevinfr06** [ErikEJ/EFCorePowerTools#1628]
Nothing happens when I run Reverse Engineer.
It was working a few days ago.
Nothing in Output.
Any of menu items works. Nothing happens too.

Describe what is not working as expected.

### Provide steps to reproduce

Clic on "Reverse Engineer"

### Provide technical details

- EF Core version in use: 3.1

- Is Handlebars used: yes

- Is T4 used: yes

- Is .dacpac used: no

- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu) 2.5.1236

- Database engine: SQL Server

- Visual Studio version: Visual Studio 2022

**Comment by ErikEJ** [comment]
It is not a lot of info but I will try to reproduce.

**Comment by kevinfr06** [comment]
Hi Erik,
I update my Visual Studio to the last version, and now it s working.
