### ISSUE TITLE
Reverse Engineer - Primary Keys

### ISSUE THREAD

**Issue by pedrosanguineti** [ErikEJ/EFCorePowerTools#163]
Currently all the tables that do not have a PK are blocked and generates issues with projects that already had tables without PK selected or that cannot be changed and need to be selected regardless of having or not a PK. Besides, the configuration file structure change (primary key boolean attribute) creates issues when using git to track tables to be added after the update.

### Steps to reproduce
Right Click Project -> EF Core Power Tools -> Reverse Engineer -> Select database.

### Further technical details
EF Core Power Tools version: 2.2.2.0
Database engine: SQL Server
Visual Studio version: Visual Studio 2017 15.9.4

**Comment by ErikEJ** [comment]
Yes, breaking change, try to start over (remove the efpt.config.json file)
