### ISSUE TITLE
Incorrect C# type code generation for not nullable bit field with default constraints

### ISSUE THREAD

**Issue by raman-kazhadub** [ErikEJ/EFCorePowerTools#1631]
For not nullable bit field with default (1) constraint EFPT generates bool? property in C# model.

### steps to reproduce

```
CREATE TABLE [dbo].[TestTable](
    [NotNullBitWithDefaultConstraint0] [bit] NOT NULL,
    [NotNullBitWithDefaultConstraint1] [bit] NOT NULL
)
 
ALTER TABLE [dbo].[TestTable] ADD  CONSTRAINT [DF_TestTable_NotNullBitWithDefaultConstraint0]  DEFAULT ((0)) FOR [NotNullBitWithDefaultConstraint0]
GO

ALTER TABLE [dbo].[TestTable] ADD  CONSTRAINT [DF_TestTable_NotNullBitWithDefaultConstraint1]  DEFAULT ((1)) FOR [NotNullBitWithDefaultConstraint1]
GO
```

Actual result:
```
public partial class TestTable
{
    public bool NotNullBitWithDefaultConstraint0 { get; set; }
    public bool? NotNullBitWithDefaultConstraint1 { get; set; }
}
```

Expected result:
```
public partial class TestTable
{
    public bool NotNullBitWithDefaultConstraint0 { get; set; }
    public bool NotNullBitWithDefaultConstraint1 { get; set; }
}
```

### Provide technical details

- EF Core version in use: EF Core 3.1

- Is Handlebars used: no

- Is T4 used: no

- Is .dacpac used: no

- EF Core Power Tools version: 2.5.1236

- Database engine: SQL Server

- Visual Studio version: Visual Studio 2022 (Version 17.4.3)

**Comment by ErikEJ** [comment]
This is by design as described in [the wiki](https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#choose-advanced-options)
