### ISSUE TITLE
Reverse Engineer gives error

### ISSUE THREAD

**Issue by anthonysaliba** [ErikEJ/EFCorePowerTools#1638]
Using Visual Studio 2022 and installed EF Core Power Tools (today 1st January 2023) from Visual Studio Extensions.

I see the tool when I right click on the project name but as soon as I select Reverse Engineer I get in the output for Extensions

System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.Bcl.AsyncInterfaces, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at IServiceProvider EFCorePowerTools.EFCorePowerToolsPackage.CreateServiceProvider()
   at async Task EFCorePowerTools.EFCorePowerToolsPackage.InitializeAsync(CancellationToken cancellationToken, IProgress<ServiceProgressData> progress)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

- EF Core version in use is 7.0.1 for SQLServer
- The project is a Blazor solution.

**Comment by ErikEJ** [comment]
Which VS version exactly?

**Comment by anthonysaliba** [comment]
This is VS2022 Community Edition (64bit)  Version 17.0.4

**Comment by ErikEJ** [comment]
That is quite old - What happens if you update to 17.4 ?

**Comment by ErikEJ** [comment]
Also, are you running .NET Framework 4.8 ?

You can check with this: https://learn.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed#use-powershell-to-check-for-a-minimum-version

**Comment by anthonysaliba** [comment]
I am upgrading now I will let you know how it goes.
Thanks

**Comment by anthonysaliba** [comment]
VS2022 upgraded, it is now version 17.4.3 running Net Framework 4.8.04161 and all seems to be working. I will actual do DB migration later but EF Power Tools are running and I can connect to DB and select the tables.

Many thanks

**Comment by ErikEJ** [comment]
Thanks. So you were not running. NET FW 4.8 before?

**Comment by anthonysaliba** [comment]
I am not sure about Net FW as I started upgrading as soon as I receive your email and did not have the chance to check the FW.

I thank you for your prompt support and at the same time  I also have to thank you for the excellent product. I used it before  that is why I was concerned when it didn't work although I was sure that it was something related to my setup.

**Comment by ErikEJ** [comment]
Great, I have just made an update to the installer to ensure that the extension does not install without .NET Framework 4.8 installed.

I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details)
