### ISSUE TITLE
Link for an old version, for ex. 2.5.1236

### ISSUE THREAD

**Issue by alexei-lazari** [ErikEJ/EFCorePowerTools#1639]
In last version disappeared support for simple POCO classes without navigation. But i am still using it in some cases. VS updated the extension automatically and now i can't use that useful feature as before.
Can i get somehow one of preceding version, for ex 2.5.1236 before will be some examples how to achieve this with T4?
I did not found a way to rollback...

Thanks a lot for the great tool!

**Comment by ErikEJ** [comment]
I have an example t4template listed in [the docs](https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#customize-code-using-t4-templates)

You can also for a while download an older build [from here](https://github.com/ErikEJ/EFCorePowerTools/tree/master/tools)

**Comment by alexei-lazari** [comment]
Thats greate! Thanks a LOT!!!

**Comment by ErikEJ** [comment]
Which solution did you go with?

I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details)

**Comment by alexei-lazari** [comment]
I used VS2019 to generate POCO classes in old format. T4 is something, which i want to use in near future, but for today some projects are targeting EF 3.1. I know it's time is gone and i want to upgrade projects, but not today :-). It's necessary some time for that.
Can i ask you why you removed those potions for POCO classes? I understand, that progress is good and we must use new features when they exists. But, for this concrete case, may be its too early to switch/drop those options.
I think it's more easy to check 1-2 checkboxes in options, than to use T4 templates. It's good to have more ways, to do something similar, if it possible.
If there will be some asks about this from others, you can count me as first vote to return those options, if this is possible and not difficult to maintain.

In any way, thanks a lot for incredible quick answer and you question. Have a greate success in this new year!

p.s.
I left a review on VS Marketplace.

**Comment by ErikEJ** [comment]
I appreciate what you are saving, but this feature was a incomplete hack as you can see from several issues in this repo. 

T4 fits the bill perfectly. You can even use the templates without requiring EF Core7 or .NET 6!

Thanks for the review.

**Comment by alexei-lazari** [comment]
If it can be used without EF7 - it's great! I will try it, in some time, certainly.
Thanks for the tip!
