### ISSUE TITLE
Add support for EF Core 2.2.1 for .NET and .NET Core

### ISSUE THREAD

**Issue by botondbotos** [ErikEJ/EFCorePowerTools#164]
EF Core 2.2.1 is not supported on .NET and .NET Core.

### Steps to reproduce

- Create a new .NET Core 2.2 class library project
- Add the Microsoft.EntityFrameworkCore.SqlServer 2.2.1 NuGet package to the project
- Right click on the project, choose "EF Core PowerTools" -> Add DbContext model diagram"

The following error message appears in the build output windows:
```
System.ArgumentException: Error:
System.ArgumentException: No EF Core DbContext types found in the project
   at ReverseEngineer20.EfCoreModelBuilder.GetDbContextTypes(DbContextOperations operations) in C:\Code\EFCorePowerTools\src\GUI\efpt\EFCoreModelBuilder.cs:line 76
   at ReverseEngineer20.EfCoreModelBuilder.BuildResult(String outputPath, Boolean generateDdl) in C:\Code\EFCorePowerTools\src\GUI\efpt\EFCoreModelBuilder.cs:line 34
   at ReverseEngineer20.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efpt\Program.cs:line 44

Parameter name: processResult
   at EFCorePowerTools.Handlers.ModelAnalyzerHandler.Generate(String outputPath, Project project, GenerationType generationType) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ModelAnalyzerHandler.cs:line 49
```

### Further technical details
EF Core Power Tools version: 2.2.4.0

Database engine: SQL Server

Visual Studio version: Visual Studio 2017 15.9.5

**Comment by ErikEJ** [comment]
Fixed in latest daily build, please let me know if it fixes your issue

**Comment by botondbotos** [comment]
I can confirm that the issue is fixed in the latest daily build.

**Comment by ErikEJ** [comment]
Thanks for verifying, and thanks for reporting this

**Comment by patricknolan** [comment]
Hi @ErikEJ could the latest version with this fix be uploaded to Visual Studio Marketplace as well?

**Comment by ErikEJ** [comment]
@patricknolan  Absolutely, just waiting a few days for the dust to settle, fir example #172 - but if you can verify #172 for me, it will happen earlier

**Comment by patricknolan** [comment]
Thanks @ErikEJ I downloaded and installed the latest nightly build and still get the same error.

I'm using Visual Studio 2019 Preview 

And I'm referencing
Microsoft.NETCore.App v2.0.0
Microsoft.EntityFrameworkCore.Design v3.0.0-preview.18572.1
Microsoft.EntityFrameworkCore.SqlServer v3.0.0-preview.18572.1
Microsoft.EntityFrameworkCore.Tools v3.0.0-preview.18572.1

**Comment by ErikEJ** [comment]
Thanks ! The tool does not support 3.0-preview!

**Comment by patricknolan** [comment]
Thanks @ErikEJ any immediate plans to support 3.0-preview? Just trying to decide if EFCorePowerTools is an option for a new project we're starting.

**Comment by ErikEJ** [comment]
@patricknolan What Power Tools features do you want to use? - Reverse Engineer will work just fine when using 3.0.
