### ISSUE TITLE
[Feature request] Propagate MSDescription property from table name to DbSet collection name

### ISSUE THREAD

**Issue by janseris** [ErikEJ/EFCorePowerTools#1640]
![image](https://user-images.githubusercontent.com/64279914/210258314-e7e04c57-fb22-4b0f-80b9-d852bedae43b.png)
MSDescription from SQL Server is shown on the data type.
This is not visible on the DbSet collection.

It would be very useful if the description was propagated there.
![image](https://user-images.githubusercontent.com/64279914/210258441-caf2b1bc-428c-4ae6-a18a-2f26be0912b8.png)

I think that it (either `<inheritdoc>` or explicit copy of the description) would not collide with anything that can be generated from SQL Server via EF Core Power tools because nothing is generated as a XML documentation comment on a DbSet when scaffolding.

**Comment by ErikEJ** [comment]
T4 to the rescue:

DbContext.t4:

```csharp
<#
    foreach (var entityType in Model.GetEntityTypes().Where(e => !e.IsSimpleManyToManyJoinEntityType()))
    {
        if (!string.IsNullOrEmpty(entityType.GetComment()))
        {
#>
    /// <summary>
    /// <#= code.XmlComment(entityType.GetComment()) #>
    /// </summary>
<#
        }
#>
    public virtual DbSet<<#= entityType.Name #>> <#= entityType.GetDbSetName() #> { get; set; }
```

NorthwindContext.cs:

```
    /// <summary>
    /// Shipper table comment
    /// </summary>
    public virtual DbSet<Shipper> Shippers { get; set; }

```
