### ISSUE TITLE
Add DateOnly/TimeOnly mapping support

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#1642]

**Comment by IanKemp** [comment]
@ErikEJ is this dependent on the version of EF Core being used, i.e. will this only work with EF Core 8? Or is it possible to use this with downlevel EF Core versions e.g. v6, as long as you're generating for .NET 6+?

**Comment by IanKemp** [comment]
And I assume I'll also need MS.Data.SqlClient 5.1.0 or newer for [the support that you merged into it for `DateOnly` and `TimeOnly`](https://github.com/dotnet/SqlClient/pull/1813)?

**Comment by IanKemp** [comment]
> You just need my package as mentioned in the wiki. (It will pull in the correct M.D.S. version)

[This one?](https://github.com/ErikEJ/EFCore.SqlServer.DateOnlyTimeOnly)

**Comment by ErikEJ** [comment]
@IanKemp Correct!
