### ISSUE TITLE
How to create setter for navigation properites

### ISSUE THREAD

**Issue by mtbayley** [ErikEJ/EFCorePowerTools#1643]
Using the latest version of this extension, I noticed that the navigation properties no longer have a setter. Has something changed recently surrounding this? I use the setter extensively in my application.

![image](https://user-images.githubusercontent.com/34929316/210394972-7de8fabd-7465-4d90-9f84-466cf8d15974.png)

**Comment by ErikEJ** [comment]
It is because you use EF core 7 scaffolding.

But needing a setter should not be required..

Otherwise you could bring it back with T4 templates.

**Comment by ErikEJ** [comment]
A fix for this [is considered](https://github.com/dotnet/efcore/issues/30286#issuecomment-1431244084) by the EF Core team, and I have included the fix in the latest daily (if you use T4 templates)

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
