### ISSUE TITLE
DbContext OnConfiguring doesn't check IsConfigured for EF7 reverse engineer

### ISSUE THREAD

**Issue by juergenil** [ErikEJ/EFCorePowerTools#1647]
**EF Core 7 reverse engineer doesn't check, if DbContextOptionsBuilder is already configured.**

### Steps to reproduce
Reverse Engineering of a Sql Server table into a DotNet 7 library.
After enabling the option "include connection string in generated code", a method "OnConfiguring" is added to the generated context class.
Code of this method depends on selection at the first wizard screen (EF Core 6 / EF Core 7).
For EF Core 7, it isn't checked anymore, if the DbContextOptionsBuilder is already configured.
This is not correct, as the method always configures SqlServer.    
This will fail, if the context class is used together with another provider, e.g. during unit tests.     
For me, a workaround is to disable the option "include connection string..." as I don't need it.
But I think, the default behavior was "enabled" in some older versions of EF Core Power Tools.  

```csharp
// code for EF Core 6: 
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
{
  if (!optionsBuilder.IsConfigured)
  {
    optionsBuilder.UseSqlServer("...");
  }
}
```

```csharp
// code for EF Core 7:
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
  => optionsBuilder.UseSqlServer("...");
```

### Technical details
- EF Core version in use: EF Core 7
- Is Handlebars used: no
- Is T4 used: no
- Is .dacpac used: no
- EF Core Power Tools version: 2.5.1258
- Database engine: SQL Server 2019
- Visual Studio version: 2022 17.4.3

**Comment by ErikEJ** [comment]
Interesting - it is an EF Core product change, I am sure  @bricelam had a good reason for it.

I think the general trend is to avoid "OnConfiguring" in your DbContext.

**Comment by bricelam** [comment]
@ajcvickers Did we have a good reason for this? 😉

Was it because the scenario has been satisfied by `--no-onconfiguring` instead? Or it broke DbContext pooling? I can't remember the specifics.

**Comment by ajcvickers** [comment]
@bricelam @ErikEJ It's because the idea that you would configure the database provider inside your DbContext in some cases, but only if the context is not configured already, isn't generally useful. Also, it means that people may leave the configuration in OnConfiguring in their context when it isn't being used, possibly even with a connection string in it. So, if you're not using OnConfiguring for this, then pass the flag `--no-onconfiguring`. And if you really want both, then a) tell us why; I'm interested! and b) use the T4 template to do it.

**Comment by ErikEJ** [comment]
@ajcvickers Makes a lot of sense  - Power Tools defaults to no-onconfiguring and has for ages.

**Comment by ErikEJ** [comment]
@mhkolk You are backing up the wrong tree...

300000 users profit from EF Core Power Tools.

**Comment by mhkolk** [comment]
> @mhkolk You are backing up the wrong tree...
> 
> 300000 users profit from EF Core Power Tools.

I don't see EF Core Power Tools mentioned anywhere within the EF Core docs at MS docs site. Not prominently in any way, for sure.

**Comment by mhkolk** [comment]
> @mhkolk You are backing up the wrong tree...
> 
> 300000 users profit from EF Core Power Tools.

Oic now, it's your product. 😁

**Comment by wijnsema** [comment]
@ErikEJ Power 

> Tools defaults to no-onconfiguring and has for ages.

Why decide this for the user? Should by optional.
