### ISSUE TITLE
Table-valued functions are not appearing when choosing database objects

### ISSUE THREAD

**Issue by nhamawi** [ErikEJ/EFCorePowerTools#1649]
Table-valued functions are not appearing when choosing database objects; only scalar value functions are appearing. I cannot say when this started happening as the VS 2022 has been auto-updating and I'm not sure what version we last used in our project to generate code. However, it would be a great feature to include the version number in a comment in the generated code.

**Comment by nhamawi** [comment]
This is regarding 2.5.1258

**Comment by ErikEJ** [comment]
I am not able to reporduce (unless you target EF Core 3.1?)

This is the query I run to get the list of scalar and TVP functions:


```sql
SELECT
    ROUTINE_SCHEMA,
    ROUTINE_NAME,
    CAST(CASE WHEN (DATA_TYPE != 'TABLE') THEN 1 ELSE 0 END AS bit) AS IS_SCALAR
FROM INFORMATION_SCHEMA.ROUTINES
WHERE NULLIF(ROUTINE_NAME, '') IS NOT NULL
AND OBJECTPROPERTY(OBJECT_ID(QUOTENAME(ROUTINE_SCHEMA) + '.' + QUOTENAME(ROUTINE_NAME)), 'IsMSShipped') = 0
AND (
            select 
                major_id 
            from 
                sys.extended_properties 
            where 
                major_id = object_id(QUOTENAME(ROUTINE_SCHEMA) + '.' + QUOTENAME(ROUTINE_NAME)) and 
                minor_id = 0 and 
                class = 1 and 
                name = N'microsoft_database_tools_support'
        ) IS NULL 
AND ROUTINE_TYPE = N'FUNCTION'

```
