### ISSUE TITLE
Duplicate Partial Method in Generated DbContext Class

### ISSUE THREAD

**Issue by tonysneed** [ErikEJ/EFCorePowerTools#165]
A `OnModelCreatingPartial` partial method is generated in the DbContext class when selecting the Handlebars templates option. This is in addition to the `OnModelCreatingExt` partial method already generated by the Handlebars scaffolding extension. Only the `OnModelCreatingExt` partial method should be inserted.

```csharp
        OnModelCreatingExt(modelBuilder);

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingExt(ModelBuilder modelBuilder);

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
```

**Comment by tonysneed** [comment]
Does not cause a build failure, but the `OnModelCreatingPartial` is no longer needed, now that my Handlebars library adds the partial method. I submitted #168 to remove the duplicate partial method.

**Comment by ErikEJ** [comment]
But people are not always using Handlebars !?

**Comment by tonysneed** [comment]
Oh yeah, forgot. :) Perhaps it can be added only when they are not using Handlebars.

**Comment by ErikEJ** [comment]
>> Perhaps it can be added only when they are not using Handlebars.

Yes, that it how it should be fixed! 😄

**Comment by tonysneed** [comment]
I'll go ahead and do that.

**Comment by tonysneed** [comment]
[Done](ce568c0e009d8b0a779d15d3f732abe914fbde78)! 😄
