### ISSUE TITLE
Relationships generator

### ISSUE THREAD

**Issue by JuanIrigoyen** [ErikEJ/EFCorePowerTools#1650]
Hi Eric. In previous versions of EF Power Tools, there was the possibility to avoid the generation of relationships with other entities, for us it is very important because we work with thousands of entities and we do not expose relationships in our entities, we only use POCO entities, in this last version it is not possible to override this behavior, is it possible somehow to keep it? Thank you.

**Comment by JuanIrigoyen** [comment]
If it is not possible to change this behavior, is it possible to download a previous version of this tool?

**Comment by ErikEJ** [comment]
Yes, for a while you can download an older build, see #1639 

I have also added T4 support for no navigations in the latest daily build: https://github.com/ErikEJ/EFCorePowerTools/issues/1646#issuecomment-1370783173

**Comment by JuanIrigoyen** [comment]
Thank you very much Eric!!!
