### ISSUE TITLE
EF Core 6 and EF Core 7 seems have inconsistent model class output

### ISSUE THREAD

**Issue by doggy8088** [ErikEJ/EFCorePowerTools#1653]
Describe what is not working as expected.

### Provide steps to reproduce

1. Restore my `Demo` database.

    [Demo.zip](https://github.com/ErikEJ/EFCorePowerTools/files/10380956/Demo.zip)

    I have two table. One is `Customer` and the other is `CustomerAddress`. It's relationship is 1-to-many.

2. If I use EF Core 6 to generate models, the `Customer` model looks like this:

    ```cs
    public partial class Customer
    {
        public Customer()
        {
            CustomerAddress = new HashSet<CustomerAddress>();
        }

        public long Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<CustomerAddress> CustomerAddress { get; set; }
    }
    ```

3. If I use EF Core 7 to generate models, the `Customer` model looks like this:

    ```cs
    public partial class Customer
    {
        public long Id { get; set; }

        public string Name { get; set; }

        public virtual ICollection<CustomerAddress> CustomerAddress { get; } = new List<CustomerAddress>();
    }
    ```

    The navigation property `CustomerAddress` become a **read-only** property. Is it by design? but why?

### Provide technical details

- EF Core version in use: EF Core 7

- Is Handlebars used: no

- Is T4 used: no

- Is .dacpac used: no

- EF Core Power Tools version: 2.5.1258

    ![image](https://user-images.githubusercontent.com/88981/211511763-c2419b0e-7fb0-4a84-b6ce-081ad305035a.png)

- Database engine: SQL Server 2019 (EXPRESS)

- Visual Studio version: Visual Studio 2022

**Comment by ErikEJ** [comment]
Yes, it is by design and duplicate https://github.com/ErikEJ/EFCorePowerTools/issues/1587#issuecomment-1344808549

**Comment by ErikEJ** [comment]
A fix for this [is considered](https://github.com/dotnet/efcore/issues/30286#issuecomment-1431244084) by the EF Core team, and I have included the fix in the latest daily (if you use T4 templates)
