### ISSUE TITLE
SQLite Reverse Engineering Not Working.

### ISSUE THREAD

**Issue by baylf2000** [ErikEJ/EFCorePowerTools#1655]
I followed the directions in the wiki but have been unable to get SQLite Reverse Engineering to work as expected.

### Provide steps to reproduce

Once the "Choose Database Connection" dialog is open, click "Add" and choose "Add Database Connection". Click "Change" to select a different data source. In the "Change Data Source" dialog, select "SQLite" from the list and click OK. In the "Connection Properties" dialog, select "Browse" to choose the SQLite database file. Then click "OK".

Each time I am returned to the "Choose Database Connection" dialog with no visible changes. The drop down remains empty. The "OK" button is still greyed out.

### Provide technical details

- EF Core version in use: (e.g. EF Core 7)

Have tried with EF Core 6 and EF Core 7 projects with the same result.

- EF Core Power Tools version: (found in About dialog - blue question mark icon on context menu)

v2.5.1258

- Visual Studio version: (e.g. Visual Studio 2022)

Visual Studio 2022 (v 17.4.4)
Packages:
Microsoft.EntityFrameworkCore 7.0.2
Microsoft.EntityFrameworkCore.Sqlite 7.0.2
Microsoft.EntityFrameworkCore.Tools 7.0.2

**Comment by ErikEJ** [comment]
Have you tried adding a connection in Server Explorer?

**Comment by ErikEJ** [comment]
Ping?

**Comment by baylf2000** [comment]
@ErikEJ I feel the need to say that when someone takes the time to report a detailed issue to you, closing the issue after only 5 days without ever @'ing the person reporting the issue so that they are notified of your response is incredibly disrespectful and unprofessional.

**Comment by baylf2000** [comment]
If I add a new connection in Server Explorer first, then it does work correctly.

**Comment by ErikEJ** [comment]
@baylf2000 you should always get notifications from issues you created.

I am not sure there is anything I can fo here , but I will take another look.

**Comment by ErikEJ** [comment]
@baylf2000 I was finally able to repro!

I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

If you can confirm the fix, I will publish a new release to MarketPlace soon.
