### ISSUE TITLE
Can't use EF Core Power Tools 2.5.1258 with Visual Studio 17.0.8 LTSC

### ISSUE THREAD

**Issue by SvenKunz-SPK** [ErikEJ/EFCorePowerTools#1656]
Yesterday I've updated my EF Core Tools 2.5.918 to 2.5.1258. The installation process was succesful and Visual Studio shows that the actual version is installed BUT when I open an Project and I want to use EF Core Tools - Reverse Engineer, i get this error:

```
_System.IO.FileNotFoundException: Die Datei oder Assembly "Microsoft.Bcl.AsyncInterfaces, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden.
Dateiname: "Microsoft.Bcl.AsyncInterfaces, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51"
   at IServiceProvider EFCorePowerTools.EFCorePowerToolsPackage.CreateServiceProvider()
   at async Task EFCorePowerTools.EFCorePowerToolsPackage.InitializeAsync(CancellationToken cancellationToken, IProgress<ServiceProgressData> progress)

System.ArgumentNullException: Der Wert darf nicht NULL sein.
Parametername: provider
   at T Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService<T>(IServiceProvider provider)
   at TView EFCorePowerTools.EFCorePowerToolsPackage.GetView<TView>()
   at async Task EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.ReverseEngineerCodeFirstAsync()_
```
The Old Version 2.5.918 don't have this problem. In the testproject I use EF 6 to access a SQL Server DB. The TargetFramework is net6.0 

Microsoft Visual Studio Enterprise 2022:
Version 17.0.18
VisualStudio.17.Release.LTSC.17.0/17.0.18+33214.273
Microsoft .NET Framework
Version 4.8.03761

**Comment by ErikEJ** [comment]
That is an old VS version. Suggest you Update (as you can see from similar issues here)

**Comment by SvenKunz-SPK** [comment]
I've updated the VS yesterday but we have to use the  VS LTSC Version (Long Term Servicing Channel)
LTSC Version 17.0.18 is the newest available.

**Comment by ErikEJ** [comment]
I that case maybe you have to revert to an old build. You can find a VS 2019 support build in the Tools folder in this repo.

**Comment by SvenKunz-SPK** [comment]
I've installed version 2.5.1236 and that works. Thank you for support and your great software.

**Comment by ErikEJ** [comment]
Sadly it means you are stuck with that version. I will investigate a fix and hope you can help me confirming it.

**Comment by SvenKunz-SPK** [comment]
Yes no problem. I'm working in a financial institute and therefore we decided to install the LTSC - Version of Visual Studio 2022.
Last update yesterday. Microsoft installer says: My Version 17.0.8 is actual.

Here is the full information of my VS 2022: Perhaps it can help you:

Microsoft Visual Studio Enterprise 2022
Version 17.0.18
VisualStudio.17.Release.LTSC.17.0/17.0.18+33214.273
Microsoft .NET Framework
Version 4.8.03761

Installierte Version: Enterprise

.NET Core-Debugging mit WSL   1.0
.NET Core-Debugging mit WSL

ASP.NET and Web Tools 2019   17.0.800.6825
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   17.0.800.6825
Weitere Informationen finden Sie unter https://www.asp.net/.

Azure App Service Tools v3.0.0   17.0.800.6825
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   17.0.800.6825
Azure Functions and Web Jobs Tools

C#-Tools   4.0.1-1.22180.6+4103de12b5aaf8448fe1c16edb36f48aff57399e
C#-Komponenten, die in der IDE verwendet werden. Abhängig von Ihrem Projekttyp und den zugehörigen Einstellungen kann eine andere Version des Compilers verwendet werden.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Entity Framework Core Power Tools   2.5
Adds useful design-time EF Core DbContext features to the Visual Studio Solution Explorer context menu.

Erweiterung zum Debuggen von Momentaufnahmen   1.0
Detaillierte Informationen zur Visual Studio-Erweiterung zum Debuggen von Momentaufnahmen

Erweiterungen der Visual Studio-Containertools   1.0
Hiermit werden Container in Visual Studio angezeigt, verwaltet und diagnostiziert.

Microsoft Azure-Tools für Visual Studio   2.9
Support für Azure Cloud Services-Projekte

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio-Tools für Container   1.2
Jetzt können Sie Ihre ASP.NET Core-Anwendung in der Zielumgebung entwickeln, ausführen und überprüfen. Drücken Sie F5, um die Anwendung direkt in einem Container mit Debugfunktionen auszuführen, oder STRG+F5 zum Bearbeiten und Aktualisieren Ihrer Anwendung, ohne den Container erneut erstellen zu müssen.

NuGet-Paket-Manager   6.0.2
NuGet-Paket-Manager in Visual Studio. Weitere Informationen zu NuGet finden Sie unter https://docs.nuget.org/.

Office Developer Tools für Visual Studio   17.0.31730.00
Microsoft Office Developer Tools für Visual Studio

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Razor (ASP.NET Core)   17.0.0.2156603+e9cd763349a080127b6519ffbec0123949a4c385
Stellt Sprachdienste für ASP.NET Core Razor bereit.

SQL Server Data Tools   17.0.62110.20190
Microsoft SQL Server Data Tools

SQL Server Reporting Services   16.0.20243.0
Designer für Microsoft SQL Server Reporting Services 
Version 16.0.20243.0

TypeScript-Tools   17.0.1001.2002
TypeScript-Tools für Microsoft Visual Studio

Visual Basic-Tools   4.0.1-1.22180.6+4103de12b5aaf8448fe1c16edb36f48aff57399e
Visual Basic-Komponenten, die in der IDE verwendet werden. Abhängig von Ihrem Projekttyp und den zugehörigen Einstellungen kann eine andere Version des Compilers verwendet werden.

Visual F# Tools   17.0.0-beta.21522.2+6d626ff0752a77d339f609b4d361787dc9ca93a5
Microsoft Visual F# Tools

Visual Studio-Tools für Container   1.0
Visual Studio-Tools für Container

Visual Studio Code-Debugadapter-Hostpaket   1.0
Interopebene zum Hosten der Visual Studio Code-Adapter in Visual Studio

Visual Studio IntelliCode   2.2
KI-gestützte Entwicklung für Visual Studio.

Workflow Manager Tools 1.0   1.0
Dieses Paket enthält die erforderlichen Visual Studio-Integrationskomponenten für Workflow Manager.

**Comment by SvenKunz-SPK** [comment]
It works. Thank you very much!
