### ISSUE TITLE
Great tool! There would be nice to see option to implement IdentityDbContext

### ISSUE THREAD

**Issue by Filipowicz251** [ErikEJ/EFCorePowerTools#1657]
Hi

This tool is really great. It would be even greater if there would be option to add a context which would inherit from IdentityDbContext. This is an issue for everyone who want to register context as

`builder.Services
       .AddIdentity<IdentityUser, IdentityRole>()
       .AddEntityFrameworkStores<SomeDbContext>()
       .AddDefaultTokenProviders();`
       
 Such registered DataContext have to inherit from IdentityDbContext.

**Comment by ErikEJ** [comment]
Have you read the wiki about extending the generated code?
