### ISSUE TITLE
Remove default DbContext constructor option not being followed

### ISSUE THREAD

**Issue by rer145** [ErikEJ/EFCorePowerTools#1658]
An upgrade to v2.5.1258 appears to have broken the default DbContext construction generation option.

On January 9, 2023, I updated to v2.5.1258. I noticed when I went to re-run Reverse Engineer on my existing project, my database connection was gone. This was performed on the same machine I had been using for months with success. My existing efpt.config.json was still intact.

All my defaults were seemingly in place when I added 2 new tables to my setup, but the DbContext file generated two constructors. One was empty, and the other one had the DbContextOptions parameter). Previously, only the 2nd constructor was generated, no empty, default constructor was present.

![image](https://user-images.githubusercontent.com/874002/213027264-0eb4b13a-a159-41b6-9d98-c9a5f4e3fdaf.png)

Looking at the efpt.config.json file, I noticed the following changes were made:

![image](https://user-images.githubusercontent.com/874002/213025602-13b37226-6235-4a10-adc3-a119cd72a7db.png)

The checkbox in the UI for removing the default constructor is checked, as expected. However, the default constructor is still generated.

![image](https://user-images.githubusercontent.com/874002/213025469-9a89953c-7afd-4d46-9331-90bb3abe6556.png)

Changing UseNoDefaultConstructor to false updates the UI so the checkbox is not checked, and generates the default constructor.
Changing UseNoDefaultConstructor to true updates the UI so the checkbox is checked, and generates the default constructor.
Adding back UseNoConstructor does nothing, as it is then removed from the config file automatically.

- EF Core version in use:  EF Core 6
- Is Handlebars used: no
- Is T4 used: no
- Is .dacpac used: no
- EF Core Power Tools version: 2.5.1258
- Database engine: SQL Server
- Visual Studio version: VS 2022

**Comment by ErikEJ** [comment]
@rer145 Thanks for reporting this. The two removed options are not related to this, they relate to the entity classes, not the DbContext.

I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

**Comment by ErikEJ** [comment]
@rer145 Did you have a chance to test this?

**Comment by rer145** [comment]
Hi @ErikEJ my apologies for the delay in testing. I just tested v2.5.1272 and it appears to work as expected now. Thank you for the quick turnaround and help!

**Comment by ErikEJ** [comment]
@rer145 Thanks for the heads up - I will push a new release to marketplace now.

I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details)
