### ISSUE TITLE
Support Handlebars Helper and Transform Functions

### ISSUE THREAD

**Issue by tonysneed** [ErikEJ/EFCorePowerTools#166]
In general it would be good to support extensibility of the code generation process by allowing registration of services via `IServiceCollection`.  This is needed to support adding helper and transform functions, but it could also be useful for replacing other registered services, `ICSharpDbContextGenerator` or `ICSharpEntityTypeGenerator`.  I would suggest using the same mechanism as the EF Core CLI tooling, which is to look for a class that implements `IDesignTimeServices` and call `ConfigureDesignTimeServices`, passing the `IServiceCollection` created in `EfCoreReverseEngineer`.

This would allow devs to add something like the following to the project to register a Handlebars helper function.

```csharp
public class ScaffoldingDesignTimeServices : IDesignTimeServices
{
    public void ConfigureDesignTimeServices(IServiceCollection serviceCollection)
    {
        var myHelper = (helperName: "my-helper", helperFunction: (Action<TextWriter, Dictionary<string, object>, object[]>) MyHbsHelper);

        // Add optional Handlebars helpers
        serviceCollection.AddHandlebarsHelpers(myHelper);
    }

    // Sample Handlebars helper
    void MyHbsHelper(TextWriter writer, Dictionary<string, object> context, object[] parameters)
    {
        writer.Write("// My Handlebars Helper");
    }
}
```

Relates to #16, #126.

**Comment by tonysneed** [comment]
@ErikEJ If you agree with this approach, I would be happy to submit a PR to search for and use an `IDesignTimeServices` implementation.

**Comment by ErikEJ** [comment]
EF Core Power Tools runs from VS, completely outside any user code. So I cannot see how this will ever be invokde?

**Comment by tonysneed** [comment]
EF core CLI has a similar problem. It should be possible via reflection or late bound invocation.

**Comment by tonysneed** [comment]
Would you consider a PR?

**Comment by ErikEJ** [comment]
You will be entering a world of pain ,but go ahead. I cannot see how you can load types without compiling, and then you have the joy of non present dependencies and .net core etc

**Comment by tonysneed** [comment]
At first I was thinking of non-compilation for a simple scenario of adding Handlebars helpers in a single file. But I’m thinking now this is not such a good idea.

Full extensibility is really what is needed, and that requires compiling, which of course is what the EF Core CLI does. If its OK, let me experiment a bit with this.

**Comment by ErikEJ** [comment]
Should we close this?

**Comment by tonysneed** [comment]
Give me a bit more time ... still working on it. 🙉

**Comment by tonysneed** [comment]
OK, I got this to work -- sort of. 😄 We could offer support for adding design-time services _only_ if they are defined in a NET Standard class library, **not** a .NET Core app or class library.

Here is a [demo project](https://github.com/tonysneed/DesignTimeServicesLoader).

@ErikEJ Let me know what you think of this approach. I have a PR pretty much ready to go.

**Comment by bricelam** [comment]
EF Core tools run out-of-process. We effectively run the user's app but call into our entry points in EFCore.Design (which is a dependency of their project).

AFAIK, the XAML and WinForms designers are also going out-of-process so they execute in the same environment and with the same dependencies as the app. It is indeed a world of pain, and each tool needs to invent it's own inter-process communication protocol.

**Comment by tonysneed** [comment]
Closing this issue because of the difficulty implementing the feature in a reliable fashion. However, users may still use the EF Core command-line tooling to add design-time services such as Handlebars helpers.
