### ISSUE TITLE
Issue with tool and reference on Index within the tables. 

### ISSUE THREAD

**Issue by glconsultingservice** [ErikEJ/EFCorePowerTools#1660]
Describe what is not working as expected.

### Provide steps to reproduce
I just selected my database and setup the options to include "Use DataAnnotations attributes to configure the model"

Error	CS0104	'Index' is an ambiguous reference between 'Microsoft.EntityFrameworkCore.IndexAttribute' and 'System.ComponentModel.DataAnnotations.Schema.IndexAttribute'	

`
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DB
{
    [Table("bAPHB")]
    [Index(nameof(VendorGroupId), nameof(BatchTransType), Name = "User_IX_bAPHB_VendorGroup_BatchTransType_37B21E49-8A71-45FE-8039-A6CEB4BAF46F")]
    public partial class APBatchHeader
.....
`

Each table that has an index in it causes a reference error.  I turned off Handlebars to see if that was the issue but it wasn't.

The issue is the Index is in:
System.ComponentModel.DataAnnotations
and
Microsoft.EntityFrameworkCore

No sure what to do, or how to resolve the issue without updating each file every time I refresh the database.

### Provide technical details
- EF Core version in use: (e.g. EF Core 7)
EF Core 7.0.2
- Is Handlebars used: no/yes
Yes
- Is T4 used: no/yes
No
- Is .dacpac used: no/yes

- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
2.5.1258
- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)
SQL Server
- Visual Studio version: (e.g. Visual Studio 2022)
VS 2022

**Comment by ErikEJ** [comment]
@glconsultingservice  Ping?
