### ISSUE TITLE
Microsoft SQL - reverse engineer - bool column with default value not null becomes nullable bool?

### ISSUE THREAD

**Issue by Balvert** [ErikEJ/EFCorePowerTools#1662]
I have a table with a boolean:

CREATE TABLE [dbo].[XXX(
        <columns rmoved>
	[Enabled] [bit] NOT NULL
 CONSTRAINT [PK_XXX] PRIMARY KEY CLUSTERED 

ALTER TABLE [dbo].[XXXX] ADD  CONSTRAINT [DF_XXXX_Enabled]  DEFAULT ((1)) FOR [Enabled]

However the model created is:

public bool? Enabled { get; set; }

When I drop the default i get:

public bool Enabled { get; set; }

**Comment by ErikEJ** [comment]
It is by design and there is an advanced option to disable it - I suggest you read the wiki: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#choose-advanced-options

Did you just post a review with a question about the efpt.config.json context menu?

**Comment by Balvert** [comment]
Yes I did.
But is is my mistake, I right-clicked the project and not the .json.
