### ISSUE TITLE
Reverse engineering throws invalidoperationexception 

### ISSUE THREAD

**Issue by ManMog** [ErikEJ/EFCorePowerTools#1663]

**Comment by ManMog** [comment]
Reverse engineering throws this exception after adding tables and views:
fail: System.InvalidOperationException: No se pueden resolver tipos hasta que ITypeIdentityResolutionService haya comenzado el procesamiento de los ensamblados en cola.
en Microsoft.DotNet.DesignTools.Protocol.Types.AssemblySearchingTypeIdentityResolutionService.TryGetType(TypeIdentity typeIdentity, Boolean ignoreCase, Type& type)
                           en Microsoft.DotNet.DesignTools.Protocol.Types.AssemblySearchingTypeIdentityResolutionService.ResolveNamedType(TypeIdentity typeIdentity, TypeIdentityResolutionOptions options)
                           en Microsoft.DotNet.DesignTools.Protocol.Types.TypeIdentityResolutionService.ResolveType(TypeIdentity typeIdentity, TypeIdentityResolutionOptions options)
                           en Microsoft.DotNet.DesignTools.Client.Types.BaseTypeResolutionService.GetType(String name, Boolean throwOnError, Boolean ignoreCase)

- EF Core 7
- EF Core Power Tools version: 2.5.1258
- Database engine: MySQL
- Visual Studio version: 2022

**Comment by ErikEJ** [comment]
I do not see any reference to Power Tools in that call stack

**Comment by ManMog** [comment]
Sorry it was my first post on github and I accidentally saved. I hav modified the issue.

**Comment by ErikEJ** [comment]
Could you please share the full stack trace??

**Comment by ManMog** [comment]
The only thing it shows is this output, although I have verified that it only happens in a windows forms project, and it does not happen in a class library
![output](https://user-images.githubusercontent.com/123097023/213505094-e00d5da5-3636-471b-bf0a-293e854bfe32.jpg)

**Comment by ManMog** [comment]
Maybe it is related to this problem https://github.com/dotnet/winforms/issues/7182

**Comment by ErikEJ** [comment]
Please share a repro project and your exact Visual Studio version

**Comment by ManMog** [comment]
Microsoft Visual Studio Enterprise 2022 (64 bits) - Current Versión 17.4.4
The database is large (more than 100 tables), but if you want i'll send you the schema

[WinFormsApp3.zip](https://github.com/ErikEJ/EFCorePowerTools/files/10459067/WinFormsApp3.zip)

**Comment by ErikEJ** [comment]
Ok, I will take a look some time. Sounds like you have a simple workaround?

**Comment by ManMog** [comment]
In principle it will not affect me, because it was a test project and I was planning to make a class library in which it works well. Thank you.
[bd_mysql.zip](https://github.com/ErikEJ/EFCorePowerTools/files/10459327/bd_mysql.zip)

**Comment by ErikEJ** [comment]
I am not able to reproduce.
