### ISSUE TITLE
Compare dbContext to Database required .NET 3+, but running .NET 7

### ISSUE THREAD

**Issue by jtsom** [ErikEJ/EFCorePowerTools#1665]
Describe what is not working as expected.
When attempting to do "Compare dbContext to database" command, an error dialog is shown:

![image](https://user-images.githubusercontent.com/13488/213517476-540d7409-f50f-469c-a398-55c956ad92d0.png)

Yet this project, is .NET 7

![image](https://user-images.githubusercontent.com/13488/213517595-a193b71a-fc5a-4685-93a3-c2e993dd5e25.png)

### Provide steps to reproduce

Right click .NET 7 project, choose Compare dbContext to database. See error.

### Provide technical details

- EF Core version in use: (e.g. EF Core 7)
EF Core 7

- Is Handlebars used: no/yes
No
- Is T4 used: no/yes
No
- Is .dacpac used: no/yes
No
- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
2.5.1258
- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)
SQL Server
- Visual Studio version: (e.g. Visual Studio 2022)
Version 17.5.0 Preview 3.0

**Comment by ErikEJ** [comment]
Compare has actually not been implemented for EF Core 7 yet. I was waiting until someone asked for it.

**Comment by jtsom** [comment]
Ok sounds fair. Was just confused by the message. Thanks!

**Comment by ErikEJ** [comment]
Do you really need this?

**Comment by jtsom** [comment]
I honestly wasn't sure what it was going to do, thought it may be helpful (checking if my dbContext was up to date with the database, and if I needed to regenerate). I hadn't used the command before - I just noticed it was there, actually.

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

**Comment by jtsom** [comment]
Seems to work, thought I did get a couple errors before I got a successful compare. If I get them again, I'll post them. Thanks!
