### ISSUE TITLE
Can we use EFCorePowerTools with VS Code?

### ISSUE THREAD

**Issue by gbthakkar** [ErikEJ/EFCorePowerTools#1668]
Hi,

Sorry for creating issue rather than a question here.
Because I could not find the place to ask you a question.

Q: can we use this VS code? if yes, how?

**Comment by ErikEJ** [comment]
@gbthakkar You are very welcome to create questions!

No, this extension is for Visual Studio. Are you developing C# apps in VS Code?

But you can run the tool as [an undocumented command line tool](https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#requirements)

**Comment by gbthakkar** [comment]
Hi,

I am using Visual Studio 2022
and my son has to use VS code in his company. Because his company does not
plan to buy VS 2022 at present.

I try to look at the link you have provided. I am not able to conclude much.
Because, without option selection dialog box, it looks difficult to
understand about command line arg information to be supplied.







*Regards,*

*Gaurang Thakkar*

**Comment by ErikEJ** [comment]
Did you not read the link from the wiki. You can initially create aconfig file in VS.

**Comment by ErikEJ** [comment]
For anyone watching this issue, this is now planned, and you can find a design proposal [here](https://github.com/ErikEJ/EFCorePowerTools/issues/1751) - looking forward to any comments/suggestions.
