### ISSUE TITLE
No Code Generated using Postgres

### ISSUE THREAD

**Issue by polanfong** [ErikEJ/EFCorePowerTools#167]
Describe what is not working as expected.

Code generation was working up until recently but now it does not run. The current files are not being updated and no alert to say it has run.

### Steps to reproduce
Include a complete description that I can redo to reproduce the issue.

Regenerating via an existing configuration:
- Right click on project and choose 'EFCore Power Tools' > 'Reverse Engineer'
- Choose connection string that was previously configured, click OK
- Choose tables that were previously selected, click OK
- Pluralize and Use DataAnnotation checkboxes ticked, all else cleared, click OK

No warning/error or confirmation appears and files are not updated.

I tried to start fresh with a new connection string but the same thing happens. I have this extension update automatically so I'm suspecting the recent update (dated 14/1/2019) has a regression.

### Further technical details
EF Core Power Tools version: 
Version 2.2.4.0
SQL Server Compact 4.0 in GAC - No
SQL Server Compact 4.0 DbProvider - No
SQL Server Compact 4.0 DDEX provider - No
SQL Server Compact 4.0 Simple DDEX provider - Yes
SQLite ADO.NET Provider included: 1.0.107.0
SQLite EF6 DbProvider in GAC - No
System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes

Database engine: Postgres
(Npgsql-4.0.3 ADO.NET Data Provider for PostgreSQL installed)

Visual Studio version: Visual Studio Professional 2017 15.8.5

**Comment by ErikEJ** [comment]
I removed support for NpgSQL temporarily and forgot to bring it back.

**Comment by ErikEJ** [comment]
https://github.com/ErikEJ/EFCorePowerTools/commit/a62e167f99eb538a1bbbfe5f41e8f406329cab45#diff-5c84c68ae86788b550fb8d273dc18266

**Comment by chrisvmake** [comment]
Will there be a release with this fix soon? I tried the daily build but I get a different error from that. Alternatively, is it possible for me to rollback to a previous release version?

**Comment by ErikEJ** [comment]
@chrisvmake you also use postgres?

**Comment by chrisvmake** [comment]
Yes I do.

**Comment by ErikEJ** [comment]
I have attempted a fix in the latest daily build, please let me know if it works for you.

**Comment by chrisvmake** [comment]
It looks like that worked. Thank you!

**Comment by ErikEJ** [comment]
@polanfong Are you able to confirm as well?

**Comment by polanfong** [comment]
All good now, thanks for the quick fix!

**Comment by ErikEJ** [comment]
Yes, only via daily build currently

**Comment by tonykaralis** [comment]
Do you perhaps know when there will be another stable release? Brilliant tool by they way, saved me much pain setting things up quickly.

**Comment by ErikEJ** [comment]
The daily build is currently the most stable release - I am awaiting resolution of #172 before I release to MarketPlace

**Comment by ErikEJ** [comment]
Marketplace release updated
