### ISSUE TITLE
EF Core Columns With User Defined Data Type w/Defaults Not Generated

### ISSUE THREAD

**Issue by ChuckMusgrave** [ErikEJ/EFCorePowerTools#1670]
When reverse engineering a database, table columns/fields that use a UDDT (User Defined Data Type) with a default value don't have the default values generated in the context file.

Similar fields which use the base datatype with a default value on the column are generated without issue.
![EF Core PT Issue](https://user-images.githubusercontent.com/56409954/214916736-7e097e17-8509-445d-8931-1a33d72df661.png)

In the picture, the ACCIDENT_TYPE_MSTR has a UDDT on two columns. The UDDT has a default bool value of 0. The generated code doesn't include the columns with the default. However, for the REPORTING_MSTR table, the WEB_FLG (same datatype, tinyint) has a default of 0 and does generate the proper code for the default value.

The CLI for EF Core 2.2 did generate the defaults. I haven't checked the CLI for 7.0.2, but...it doesn't generate the many to many tables we need so EFCPT seems to be the better option.

Thank you!

Please include a **complete** description or project that I can redo/run to reproduce the issue.

- Is Handlebars used: yes
- Is T4 used: no
- Is .dacpac used: no
EFCore 7.0.2
VS 2022 (17.4.4)
EF Core PT - 2.5.1258
Microsoft SQL Server 2019 (RTM-CU18) (KB5017593) - 15.0.4261.1 (X64)

**Comment by ErikEJ** [comment]
Please share some repro sql script rather than screenshots

**Comment by ChuckMusgrave** [comment]
Sure, only so much I can share as this is an enterprise level, proprietary item, but...hope this helps.

In addition, here the settings I'm using in EFCPT.
![EFCPT Settings](https://user-images.githubusercontent.com/56409954/214947294-37c3c075-1e61-43b6-a501-fb39e2798b2a.png)

[EF-GeneratedCSharp.txt](https://github.com/ErikEJ/EFCorePowerTools/files/10513263/EF-GeneratedCSharp.txt)
[EF-SqlScript.txt](https://github.com/ErikEJ/EFCorePowerTools/files/10513264/EF-SqlScript.txt)

If there's something more specific you're looking for, please let me know.

**Comment by ErikEJ** [comment]
Just a CREATE script that demonstrates the issue

**Comment by ChuckMusgrave** [comment]
I think that's what I provided but running EFCPT against this should do the job.

[EF-SqlScript2.txt](https://github.com/ErikEJ/EFCorePowerTools/files/10513495/EF-SqlScript2.txt)

**Comment by ErikEJ** [comment]
I will have a look, thank you

**Comment by ErikEJ** [comment]
2.2 is a very old EF Core version, I think the defaults are redundant and filtered out here https://github.com/dotnet/efcore/blob/main/src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs#L859 - pretty sure this was added after 2.2

**Comment by ErikEJ** [comment]
Also, using Handlebars blurs the picture

**Comment by ChuckMusgrave** [comment]
It does look like they're (mistakenly) filtered out and, upon testing the old and new versions (2.2 vs 7.0), there's definitely a difference (which is why I logged the issue). 2.2 did record the default where as 7.0 does not (logs null if field is not set/null).

I saw no immediate way to configure anything to recognize the fact that columns are using a UDDT or identify it has a null default and therefore cannot apply any coding in templates (handlebars or T4) to set the defaults upon creation.

Seems like a bug/missing functionality(?).

**Comment by ErikEJ** [comment]
I do not see any defaults defined in my repro attempt with EF Core 7, and that is by design (an explicit default of 0 for a tinyint does not make sense, because the CLR default for byte is always 0)

**Comment by ErikEJ** [comment]
Ah, I was using your second script, and the columns there are NOT NULL"!

**Comment by ChuckMusgrave** [comment]
Ah, yeah, my bad.

**Comment by ErikEJ** [comment]
Also, in your first sample script - I think you may have been confused...

CREATE TABLE [dbo].[ACCIDENT_TYPE_MSTR](
	[AUTO_ACCIDENT_FLG] [dbo].[BOOL] **NOT NULL**,
	[ENABLE_FLG] [dbo].[BOOL] NOT NULL,

**Comment by ChuckMusgrave** [comment]
I did, please leave the columns nullable to see the issue.

**Comment by ErikEJ** [comment]
I did - but your user defined type is defined like this after creation! 😄 

`CREATE TYPE [dbo].[BOOL] FROM [tinyint] NOT NULL`

**Comment by ChuckMusgrave** [comment]
It still produces the issue and I can enter a NULL for the boolean field. Unfortunately, I didn't create the database, I just have to use it :)

![NullableColumnForNonNullableDefault](https://user-images.githubusercontent.com/56409954/215096382-befa3954-24f1-4b95-bd2e-2eefe1bad819.png)

**Comment by ChuckMusgrave** [comment]
![NullValue](https://user-images.githubusercontent.com/56409954/215096763-34a89170-ecf6-4caa-b7e2-dce8d1c557d0.png)

**Comment by ErikEJ** [comment]
"the issue" ?? The fact that this is missing from your EF Core mapping for table 1?

`.HasDefaultValueSql("((0))")`

**Comment by ChuckMusgrave** [comment]
Yes, as it was done in 2.2 but not now in 7.0.

**Comment by ErikEJ** [comment]
I am not able to find any evidence that this worked with 2.2.

I suggest you create an issue in the EF Core repo with a correct repro script.

**Comment by ChuckMusgrave** [comment]
Regardless of whether you can find evidence, are you saying that a default not applied is correct functionality?

**Comment by ErikEJ** [comment]
No, I consider it a bug - that's why I suggest you create an issue in the EF Core repository

**Comment by ChuckMusgrave** [comment]
Very good, thank you.
