### ISSUE TITLE
Microsoft.AspNetCore.Mvc.Core missing

### ISSUE THREAD

**Issue by Joshi234** [ErikEJ/EFCorePowerTools#1671]
When using the Migration Tools and creating a new Migration I'm getting this error:
![image](https://user-images.githubusercontent.com/46032261/215171391-156ada08-ea58-4d17-b66b-76ff58109d27.png)

Why would it require this and even after installing it doesn't work. 

Tried both EF Core 6 and 7 and using verion 2.5.1277 of EF Core Power Tools. Also using SQL Server and Visual Studio 2022.

**Comment by ErikEJ** [comment]
You need to run this from your app or at least set the correct Startup project in VS

**Comment by Joshi234** [comment]
So basically I have an asp.net core application and a libriary for handeling the ef core stuff, so I can't change the startup project to the ef core library and when I run this on my app it tells me I don't have a db context in that project. What am I supposed to do? This setup has worked fine before so I'm confused

**Comment by ErikEJ** [comment]
Please provide a repro project and I will investigate...

**Comment by Joshi234** [comment]
[Idle Trading Simulator.zip](https://github.com/ErikEJ/EFCorePowerTools/files/10522756/Idle.Trading.Simulator.zip)
Here is the project.
Thank's for your time!

**Comment by ErikEJ** [comment]
remove this reference from both projects:

`    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.2.5" /> `

**Comment by ErikEJ** [comment]
Ping?

**Comment by Joshi234** [comment]
Wasn't able to test it yet, gonna be able to test it on Saturday

**Comment by ErikEJ** [comment]
Assume this is working, feel free to re-open if not
