### ISSUE TITLE
Wrong table name in many to many

### ISSUE THREAD

**Issue by giarico** [ErikEJ/EFCorePowerTools#1674]
Using "pluralize or singularize generated object names" the join table name is wrong.
I have to change it manually to make the application run.

Table name on DB is "UserProfilesEntities".
With EF6 the name was the same, but with this line of code that is now disappeared:
j.ToTable("UserProfilesEntities")

entity.HasMany(d => d.Entities).WithMany(p => p.UserProfiles)
                .UsingEntity<Dictionary<string, object>>(
                    **"UserProfilesEntity",**
                    r => r.HasOne<Entity>().WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_UserProfilesEntities_Entities"),
                    l => l.HasOne<UserProfile>().WithMany()
                        .HasForeignKey("UserProfileId")
                        .HasConstraintName("FK_UserProfilesEntities_UserProfiles"),
                    j =>
                    {
                        j.HasKey("UserProfileId", "EntityId");
                    });

Tested with:
- EF Core 7
- SQL Server
- Visual Studio 2022

**Comment by ErikEJ** [comment]
It is an EF Core Bug and will be fixed in 7.0.3 mid Feb

**Comment by giarico** [comment]
Thank you, I close the issue because is not related to the tool

**Comment by ErikEJ** [comment]
The fix will be available in EF Core Power Tools in a couple of weeks.

I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details)
