### ISSUE TITLE
Unable to find the requested .Net Framework Data Provider with SQLite Provider

### ISSUE THREAD

**Issue by clive-taylor** [ErikEJ/EFCorePowerTools#1675]
When entering the connection string for ‘Reverse Engineer’ using ‘SQLite Provider (Simple for EF6 by ErikEJ)’ I receive the following message ‘Unable to find the requested .Net Framework Data Provider.  It may not be installed.’ 

The ‘Test Connection’ button displays succeeded even if the connection string is empty.

EF Core Power Tools V2.5.1277
EF Core V6.0.5
SQLite V3.31.0
VS2022

**Comment by ErikEJ** [comment]
You should use VS.Data.Sqlite DDEX provider instead, see https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#choose-data-source

**Comment by clive-taylor** [comment]
I missed that. Thank you for your help.

**Comment by ErikEJ** [comment]
I recently clarified the docs so it was easy to miss
