### ISSUE TITLE
Table relation with itself

### ISSUE THREAD

**Issue by YAS-SIIN** [ErikEJ/EFCorePowerTools#1678]
I have a table that joined with itself, like this :

```
public class Stuff
{  
    public int Id { get; set; }
    public string? Title{ get; set; } 
    public int ChildId { get; set; }
                                                             
    public virtual ICollection<Stuff> Stuffs{ get; set; }
}
```

But when I use Scaffold, It makes two classes like this : 

```
public class Stuff
{  
    public stringId { get; set; }
    public string? Title{ get; set; } 
    public string ChildId { get; set; }
                                                             
    public virtual ICollection<Stuff> Stuffs{ get; set; }
}

public class Stuff1
{  
    public int Id { get; set; }
    public string? Title{ get; set; } 
    public int ChildId { get; set; }
                                                             
    public virtual ICollection<Stuff> Stuffs{ get; set; }
}
```

How can I fix this issue?

### Provide technical details

- EF Core version in use:  EF Core 7
- Is Handlebars used: yes
- Is T4 used: yes
- Is .dacpac used: yes
- EF Core Power Tools version: 2.5.1277
- Database engine: SQL Server
- Visual Studio version: Visual Studio 2022

**Comment by ErikEJ** [comment]
Please share your CREATE TABLE script

**Comment by ErikEJ** [comment]
Ping?

**Comment by YAS-SIIN** [comment]
Sorry for my delay. I was busy.
Here you are : 
```
CREATE TABLE [TRD].[StuffCollectionTest](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[Title] [nvarchar](500) NOT NULL, 
	[ChildId] [bigint] NULL,
 CONSTRAINT [PK_StuffCollectionTest] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
  
```

ALTER TABLE [TRD].[StuffCollectionTest]  WITH CHECK ADD  CONSTRAINT [FK_StuffCollectionTest_StuffCollectionTestCodingParent] FOREIGN KEY([ChildId])
REFERENCES [TRD].[StuffCollectionTest] ([Id])
GO

**Comment by ErikEJ** [comment]
I am unable to repro, get this:

public partial class StuffCollectionTest
{
    public long Id { get; set; }

    public string Title { get; set; }

    public long? ChildId { get; set; }

    public virtual StuffCollectionTest Child { get; set; }

    public virtual ICollection<StuffCollectionTest> InverseChild { get; } = new List<StuffCollectionTest>();
}


public partial class ParentsContext : DbContext
{
    public virtual DbSet<StuffCollectionTest> StuffCollectionTest { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<StuffCollectionTest>(entity =>
        {
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(500);

            entity.HasOne(d => d.Child).WithMany(p => p.InverseChild)
                .HasForeignKey(d => d.ChildId)
                .HasConstraintName("FK_StuffCollectionTest_StuffCollectionTestCodingParent");
        });
    }

**Comment by YAS-SIIN** [comment]
Is this created with scaffold?

**Comment by ErikEJ** [comment]
Yes

**Comment by ErikEJ** [comment]
I need a better repro then

**Comment by YAS-SIIN** [comment]
I solved that. I had a mistake. thank you very much.
