### ISSUE TITLE
Reverse engineer in EF Core 6 not generating class for a table (works in EF Core 3) 

### ISSUE THREAD

**Issue by gunnars04** [ErikEJ/EFCorePowerTools#1679]
The class for the table dbo.GunnaUserRole is not being genrated in EF Core 6 (is being generated in EF Core 3) . I'm using SQL Server.

Tables:

```
CREATE TABLE [dbo].[GunnaRole](
	[RoleId] [int] IDENTITY(1,1) primary key,
	[RoleName] [nvarchar](50) NULL)

CREATE TABLE [dbo].[GunnaUser](
	[UserId] [int] IDENTITY(100,1) primary key,
	[NationalId] [varchar](10) NULL)

CREATE TABLE [dbo].[GunnaUserRole](
	[RoleId] [int] NOT NULL,
	[UserId] [int] NOT NULL,
	CONSTRAINT PK_GunnaUserRole PRIMARY KEY (RoleId,UserId),
	FOREIGN KEY (RoleId) REFERENCES dbo.GunnaRole(RoleId),
	FOREIGN KEY (UserId) REFERENCES dbo.GunnaUser(UserId)
)
```

The generated class (in EF Core 3):

```
namespace MyAPI.Databases
{
    [Table("GunnaUserRole", Schema = "dbo")]
    public partial class GunnaUserRole
    {
        [Key]
        public int RoleId { get; set; }
        [Key]
        public int UserId { get; set; }

        [ForeignKey(nameof(RoleId))]
        [InverseProperty(nameof(GunnaRole.GunnaUserRole))]
        public virtual GunnaRole Role { get; set; }
        [ForeignKey(nameof(UserId))]
        [InverseProperty(nameof(GunnaUser.GunnaUserRole))]
        public virtual GunnaUser User { get; set; }
    }
}
```

I'm using handlebars.

Could it happen that this is a changed behavior? In EF Core 6 the Role property is now in the GunnaUser Class (it was before in the Class GunnaUserRole above):

```
namespace MyAPI.Databases
{
    [Table("GunnaUser", Schema = "dbo")]
    public partial class GunnaUser
    {
        public GunnaUser()
        {
            Role = new HashSet<GunnaRole>();
        }

        [Key]
        public int UserId { get; set; }
        [StringLength(10)]
        [Unicode(false)]
        public string NationalId { get; set; }

        [ForeignKey("UserId")]
        [InverseProperty("User")]
        public virtual ICollection<GunnaRole> Role { get; set; }
    }
}

```
Thanks,
Gunnar

**Comment by ErikEJ** [comment]
It is by design, many to many is no longer generated (not needed). You can  get the old behaviour via an advanced option.

**Comment by gunnars04** [comment]
Thanks 👍

**Comment by ErikEJ** [comment]
I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details)

**Comment by GearTheWorld** [comment]
I upgraded my project from .net5 to .net7 and when doing reverse engineering I get a new Attribute called Unicode on all properties of all entities as I see in the above example however it doesn't find that.  What exactly has to be done to make EF Core work without intervention when doing the reverse with 7

**Comment by ErikEJ** [comment]
@GearTheWorld which EF Core version does your project use??

**Comment by GearTheWorld** [comment]
2.5.1277

![image](https://user-images.githubusercontent.com/8614008/219158765-194d57e9-4fd5-460a-aa93-9155ebd45054.png)

![image](https://user-images.githubusercontent.com/8614008/219158916-a2e22490-ea79-4b38-ade5-ac032ae071ef.png)

**Comment by GearTheWorld** [comment]
![image](https://user-images.githubusercontent.com/8614008/219161710-cf99e042-067a-4593-a5cd-15fe34066b7c.png)

![image](https://user-images.githubusercontent.com/8614008/219161869-080522ff-eafa-4701-b448-c9e05b8ea9f9.png)

**Comment by ErikEJ** [comment]
@GearTheWorld I meant the EF Core version referenced in your .csproj!

**Comment by GearTheWorld** [comment]
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Globals">
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="CubiDataStore.csproj.vspscc" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="5.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="5.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.10" />
  </ItemGroup>

</Project>

**Comment by ErikEJ** [comment]
When using EF Core 6 or 7 scaffolding, you must also use the version 6 ir 7 packages. 

Also, version 5 is out of support.

**Comment by GearTheWorld** [comment]
I'm not sure I understand.  I upgraded the project to .NET 7.  I don't know what else I should do.  Can you give me some details ?

**Comment by ErikEJ** [comment]
I do not see any reference to .NET 7 or EF Core 7 in your .csproj above

**Comment by GearTheWorld** [comment]
Oh I see now I understand.  I have to go in Nuget Packages and update all

**Comment by ErikEJ** [comment]
@GearTheWorld Correct. And change the target framework in your. Csproj
