### ISSUE TITLE
ADD DB context diagram: No EF Core DbContext types found in the project

### ISSUE THREAD

**Issue by Sgorbinid** [ErikEJ/EFCorePowerTools#1680]
### Problem
ADD DB context diagram doesn't produce the .dgml and in the extension output i get:
```
System.InvalidOperationException: Error:
System.ArgumentException: No EF Core DbContext types found in the project
   at Modelling.EfCoreModelBuilder.GetDbContextTypes(DbContextOperations operations) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\EFCoreModelBuilder.cs:line 91
   at Modelling.EfCoreModelBuilder.BuildResult(String outputPath, String startupOutputPath, Boolean generateDdl) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\EFCoreModelBuilder.cs:line 35
   at Modelling.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\Program.cs:line 56

   at async Task EFCorePowerTools.Handlers.ModelAnalyzerHandler.GenerateAsync(string outputPath, Project project, GenerationType generationType)

```

### Provide technical details

- EF Core version in use: 6

- Is Handlebars used: no

- Is T4 used: no

- Is .dacpac used: no

- EF Core Power Tools version: 2.5.1277

- Database engine: SQL Server, Oracle

- Visual Studio version: Visual Studio 2022

### The VS solution
**I have a NET 6 c# project Ch.Ne.Sien.GuApiSecurity.Peristence containing the DbContext (EpayDbContext)**
    \<PackageReference Include="Devart.Data.Oracle.EFCore" Version="10.0.0" />
    \<PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.2.0" />
    \<PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.6" />
    \<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="6.0.0" />
    \<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.6">
      \<PrivateAssets>all</PrivateAssets>
      \<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    \</PackageReference>
    \<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="6.0.6" />
    \<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.6" />
    \<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="6.0.6">
      \<PrivateAssets>all</PrivateAssets>
      \<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    \</PackageReference>

**I have a NET 6 c# project Ch.Ne.Sien.GuApiSecurity.Web as executable**
    \<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.6">
      \<PrivateAssets>all</PrivateAssets>
      \<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    \</PackageReference>

As a matter of fact, I developped first another solution with the same NuGet packages and .NET 6, but with Program.cs, Main method and Startup.cs ... the usual way.
Here ADD DB context diagram worked fine.

```
//Sturtup.cs
public void ConfigureServices(IServiceCollection services)
...
services.AddDbContext<EpayDbContext>(options =>
            options.UseOracle(configuration.GetConnectionString("DbContextEPay")));
```

Than I took my sources and copied them in another solutions with same projects and same NuGets, but no Startup.cs and Program.cs only, without Main method and using WebApplicationBuilder.
Here ADD DB context diagram is not working and i get the error I mentioned earlier.
```
WebApplicationBuilder builder = WebApplication.CreateBuilder(args);
...
builder.AddRequiredServices();
..
public static WebApplicationBuilder AddRequiredServices(this WebApplicationBuilder builder)
        {
            builder.Services.
...
AddDbContext<EpayDbContext>(options =>
                options.UseOracle(configuration.GetConnectionString("DbContextEPay")));
```

So I figured that without Startup the Designer can't find the DbContext anymore...
I have read here [https://github.com/ErikEJ/EFCorePowerTools/wiki/Inspect-your-DbContext-model](https://github.com/ErikEJ/EFCorePowerTools/wiki/Inspect-your-DbContext-model)
... I don't know what "or make other design time helpers available" means ...
So I added parameter less constructor and onconfiguring in the exact order
```
 public EpayDbContext()
    {
    }
    // I had only this in my original
    public EpayDbContext(DbContextOptions<EpayDbContext> options) : base(options)
    {
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        if (!optionsBuilder.IsConfigured)
        {
            optionsBuilder.UseSqlServer("Data Source=.");
        }
    }
```
But the error is still there.

What can I do ?

**Comment by ErikEJ** [comment]
Make sure to run from the correct project. If still broken, share a repro project snd I will have a look.

**Comment by Sgorbinid** [comment]
Hi, you received the invitation : I shared my repo with you.
Thanks

**Comment by ErikEJ** [comment]
I cannot build you project, it uses a private NuGet feed.

**Comment by ErikEJ** [comment]
Still not able to build.

**Comment by Sgorbinid** [comment]
Hi, I have simplified a lot the solution, and now you should be able to build easily.
And I have also determined what causes the error to show : it's the Ch.Ne.Sien.GuApiSecurity.Application/Epay/Issuers/Queries/GetIssuerQueryHandler.

If you delete that file all EF Core Power Tools start to work again.
If you put it back in, the error message shows again.

Could you verify what's going on ? should I create another issue ?

**Comment by ErikEJ** [comment]
There is still too much code to look at - I assume DI is activating something during design time that fails.
