### ISSUE TITLE
No PostgreSQL database type in "Add Custom Connection" Dialog

### ISSUE THREAD

**Issue by cetindogu** [ErikEJ/EFCorePowerTools#1681]
No PostgreSQL in "ConnectionDialog"
![image](https://user-images.githubusercontent.com/7325611/216933871-1a1335c9-7ff5-46e2-9699-3a154f890b4a.png)

### Provide steps to reproduce

- Right Click on Project

- "Choose EF Core Power Tools" -> "Reverse Enggineering" Item 

- There is no "PostgreSQL" database type choice in "Add Custom Connection" Dialog 

Please include a **complete** description or project that I can redo/run to reproduce the issue.

### Provide technical details

- EF Core Power Tools version: 1277
- Database engine: PostgreSQL
- Visual Studio version: Visual Studio 2022 EnterPrise

**Comment by ErikEJ** [comment]
Yes, you no longer need a custom connection: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#choose-data-source
