### ISSUE TITLE
Allow generated class members to have same name as generated classes when casing differs

### ISSUE THREAD

**Issue by philipstratford** [ErikEJ/EFCorePowerTools#1684]
If a database table contains a column with the same name as the table itself, in the generated class the member corresponding to that column will have a number appended to its name.

To reproduce:

1. Create a database table named UiText.
2. Add a `VARCHAR(100)` column to the table named UiKey and set it as the primary key.
3. Add a `NVARCHAR(1000)` column to the table named UiText.
4. In Visual Studio, launch the EF Power Tools Reverse Engineer tool and specify a connection to the database. Click OK.
5. In the _Choose Database Objects_ dialog leave all objects checked.
6. In the _Generate EF Core Model in..._ dialog, specify whatever context name and namespace are desired. Check the _Use table and column names directly from the database_ box. Click OK.

The generated class will look like this:
````
public partial class UIText
{
    public string UiKey { get; set; }

    public string UiText1 { get; set; }
}
````
The member corresponding to the UiText column has been renamed UiText1. I can't see any reason for this to be necessary, since if I manually rename the member to UiText in this class and the context class, the solution builds and runs without any issues.

### Provide technical details

- EF Core version in use: EF Core 7

- Is Handlebars used: No

- Is T4 used: No

- Is .dacpac used: No

- EF Core Power Tools version: 2.5.1277

- Database engine: SQL Server

- Visual Studio version: 2022

**Comment by ErikEJ** [comment]
Please share a CREATE TABLE script and I will have a look.

**Comment by ErikEJ** [comment]
I think this has been done to prevent compiler error: CS0542 

https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0542 

But maybe the check could be case sensitive?

If you feel there is an issue here, I suggest you report  in the EF Core repository.

**Comment by ErikEJ** [comment]
I have created https://github.com/dotnet/efcore/issues/30237
