### ISSUE TITLE
HasTriggers not added with EFCore 7

### ISSUE THREAD

**Issue by lsiepel** [ErikEJ/EFCorePowerTools#1688]
From this issue:  https://github.com/ErikEJ/EFCorePowerTools/issues/1345 i learned that adding HasTriggers (due to this [breaking change](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/breaking-changes#sqlserver-tables-with-triggers) ) while reverse engineering is supported. Unfortunately, i have a case where this does not seem to work.

Offcourse, let me know if you need anything else to analyse this problem. 

When i apply this schema and json, the 
Schema: https://1drv.ms/u/s!AnMcxmvEeupwjqVc431dzHgq-GUX6Q?e=zzLDvA 
Contains three tables: with Gebruikersgroep and Autorisatieonderdeel both holding a trigger that performs actions agains Autorisatie when an insert is in play.

efpt.config.json
```
   {
"CodeGenerationMode": 2,
   "ContextClassName": "TestDBContext",
   "ContextNamespace": null,
   "DefaultDacpacSchema": null,
   "FilterSchemas": false,
   "IncludeConnectionString": false,
   "ModelNamespace": "Models",
   "OutputContextPath": "Data",
   "OutputPath": "Models\\TestDB",
   "PreserveCasingWithRegex": true,
   "ProjectRootNamespace": "TestDB.Data.EFCore",
   "Schemas": null,
   "SelectedHandlebarsLanguage": 0,
   "SelectedToBeGenerated": 0,
   "Tables": [
      {
         "Name": "[dbo].[Autorisatie]",
         "ObjectType": 0
      },
      {
         "Name": "[dbo].[AutorisatieOnderdeel]",
         "ObjectType": 0
      },
      {
         "Name": "[dbo].[Gebruikersgroep]",
         "ObjectType": 0
      }
   ],
   "UiHint": "DatabaseServer.TestDB",
   "UseBoolPropertiesWithoutDefaultSql": false,
   "UseDatabaseNames": true,
   "UseDbContextSplitting": false,
   "UseFluentApiOnly": false,
   "UseHandleBars": true,
   "UseHierarchyId": false,
   "UseInflector": false,
   "UseLegacyPluralizer": false,
   "UseManyToManyEntity": false,
   "UseNoConstructor": false,
   "UseNoDefaultConstructor": false,
   "UseNoNavigations": false,
   "UseNoObjectFilter": false,
   "UseNodaTime": false,
   "UseNullableReferences": false,
   "UseSchemaFolders": false,
   "UseSpatial": false,
   "UseT4": false
}
```

Versions:
- EF Core version in use: EF Core 7.0.2
- Is Handlebars used: yes
- Is T4 used: no
- Is .dacpac used: no
- EF Core Power Tools version: 2.5.1277
- Database engine: SQL Server 
- Visual Studio version: Visual Studio 2022

**Comment by ErikEJ** [comment]
You can set HasTriggers in partial class - suggest you create an issue in the EF Core repo, this is not something that can be fixed in Power Tools

**Comment by lsiepel** [comment]
I thought that according to [this comment](https://github.com/ErikEJ/EFCorePowerTools/issues/1345#issuecomment-1280904888) it was supported. Just out of curiosity, can you share some light why this would need to be fixed in EF Core and not in powertools? 
I thought that if power tools checked the schema and stumbles accross some triggers, they would be added to the model generated files.

Thanks for the  workaround suggestion with the partial classes.

**Comment by ErikEJ** [comment]
@lsiepel Possibly not for your special case

**Comment by lsiepel** [comment]
Still don't know why it is special and why this cannot be fixed here.

**Comment by ErikEJ** [comment]
@lsiepel I have not investigated deeply, but please create an issue in the EF Core repo - EF Core Power Tools build on top of the built in EF Core tooling.

**Comment by ErikEJ** [comment]
If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
