### ISSUE TITLE
Oracle Connection  through EF Core Power Tools

### ISSUE THREAD

**Issue by rajeshkotekar** [ErikEJ/EFCorePowerTools#1689]
Describe what is not working as expected.

I have downloaded and installed "Oracle Developer to VS 2022" and "EF Power tools".  While try to connect to oracle DB its successful please refer below screenshot.

![image](https://user-images.githubusercontent.com/19171079/218455865-e4d0af77-426f-403f-bf2b-9b7752f3c788.png)

After connection property "OK". Doesn't capture the connection string to proceed further to build "Model" Screen.

![image](https://user-images.githubusercontent.com/19171079/218456316-e14f4e06-9470-4719-a09d-fd34c67af799.png)
  

Please include a **complete** description or project that I can redo/run to reproduce the issue.

### Provide technical details

- EF Core version in use: (e.g. EF Core 7) EF Core 6

- Is Handlebars used: no/yes - No

- Is T4 used: no/yes - No

- Is .dacpac used: no/yes - No

- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
![image](https://user-images.githubusercontent.com/19171079/218456316-e14f4e06-9470-4719-a09d-fd34c67af799.png)

- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL) - Oracle 12C

- Visual Studio version: (e.g. Visual Studio 2022) -   Visual Studio 2022

**Comment by ErikEJ** [comment]
You should use the "OPD.NET Managed Driver" not "OracleClient" as mentioned in [the wiki](https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#choose-data-source)

![image](https://user-images.githubusercontent.com/4169187/218460691-eb10dc19-d62b-4739-8759-0d82a90e60a1.png)

**Comment by rajeshkotekar** [comment]
Thank you very much. Provided solution works for me.

**Comment by ErikEJ** [comment]
I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details)
