### ISSUE TITLE
EFCorePowerTools features do not work

### ISSUE THREAD

**Issue by duhovich** [ErikEJ/EFCorePowerTools#169]
When choosing Migration tools an error occurs:
![image](https://user-images.githubusercontent.com/22120606/51320556-e3a9fc80-1a68-11e9-93ba-2974a380f32e.png)
then:
![image](https://user-images.githubusercontent.com/22120606/51320587-f7556300-1a68-11e9-8f14-0566abda400c.png)

> Parameter name: processResult
>    at EFCorePowerTools.Handlers.ModelAnalyzerHandler.Generate(String outputPath, Project project, GenerationType generationType) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ModelAnalyzerHandler.cs:line 49

in console
### Steps to reproduce
DBContext:
` 
using ContosoUniversity.Models;

using Microsoft.EntityFrameworkCore;

namespace ContosoUniversity.Models
{

    public class SchoolContext : DbContext
    {

        public SchoolContext(DbContextOptions<SchoolContext> options) : base(options)
        {
        }

        public DbSet<Course> Courses { get; set; }
        public DbSet<Enrollment> Enrollment { get; set; }
        public DbSet<Student> Student { get; set; }
        public DbSet<Department> Departments { get; set; }
        public DbSet<Instructor> Instructors { get; set; }
        public DbSet<OfficeAssignment> OfficeAssignments { get; set; }
        public DbSet<CourseAssignment> CourseAssignments { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Course>().ToTable("Course");
            modelBuilder.Entity<Enrollment>().ToTable("Enrollment");
            modelBuilder.Entity<Student>().ToTable("Student");
            modelBuilder.Entity<Department>().ToTable("Department");
            modelBuilder.Entity<Instructor>().ToTable("Instructor");
            modelBuilder.Entity<OfficeAssignment>().ToTable("OfficeAssignment");
            modelBuilder.Entity<CourseAssignment>().ToTable("CourseAssignment");

            modelBuilder.Entity<CourseAssignment>()
                .HasKey(c => new { c.CourseID, c.InstructorID });
        }
    }
}`

### Further technical details

> Version 2.2.4.0
> 
> SQL Server Compact 4.0 in GAC - No
> SQL Server Compact 4.0 DbProvider - No
> 
> SQL Server Compact 4.0 DDEX provider - No
> SQL Server Compact 4.0 Simple DDEX provider - Yes
> 
> 
> SQLite ADO.NET Provider included: 1.0.107.0
> SQLite EF6 DbProvider in GAC - No
> 
> System.Data.SQLite DDEX provider - No
> SQLite Simple DDEX provider - Yes
> 
> Database engine: (SQlite, SQL Compact, SQL Server, Postgres)

![image](https://user-images.githubusercontent.com/22120606/51320892-f113b680-1a69-11e9-9552-17a88891e92a.png)

**Comment by ErikEJ** [comment]
Only EF Core 2.1.0, 2.1.4, 2.2.0 and 2.2.1 are supported with .NET Framework based projects
