### ISSUE TITLE
Error occurs: Installing EFCore.Design version 7.0.2, please retry the command

### ISSUE THREAD

**Issue by meetkerasiya** [ErikEJ/EFCorePowerTools#1690]
Describe what is not working as expected.

### Provide technical details

- EF Core version in use: EF Core 7

- Is Handlebars used: no

- Is T4 used: no

- Is .dacpac used: no

- EF Core Power Tools version:  2.5.1277

- Database engine: SQL Server

- Visual Studio version: Visual Studio 2022

![image](https://user-images.githubusercontent.com/69452272/218636738-bb907a89-113b-4a30-92a1-bb64f82ddda3.png)

**Comment by ErikEJ** [comment]
This is by design, please provide full repro steps and I will explain.

**Comment by meetkerasiya** [comment]
So basically If I install the Design package manually, it's working fine.
It's not installing package by itself/

**Comment by ErikEJ** [comment]
Maybe some error happens duing app package ?

**Comment by ErikEJ** [comment]
see https://github.com/ErikEJ/EFCorePowerTools/issues/1682

**Comment by ErikEJ** [comment]
>> This is by design, please provide full repro steps and I will explain.

Please provide more details, like which feature are you trying to use.

**Comment by meetkerasiya** [comment]
Now it's working after I installed Design package myself.

**Comment by ErikEJ** [comment]
Glad you got it working.

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by ErikEJ** [comment]
@meetkerasiya Maybe this is the fix (space in path to project?)

     var args = $"add \"{project.FullPath}\" package {packageId} ";
