### ISSUE TITLE
Postgres engine is missing

### ISSUE THREAD

**Issue by rmszc81** [ErikEJ/EFCorePowerTools#1692]
Hello,
what happened to the Postgres option? It disappeared after the last upgrade.

**Comment by ErikEJ** [comment]
It is still there, but moved - dupilcate of #1681

**Comment by rmszc81** [comment]
Hell yeah @ErikEJ, it works like a charm! great! awesome!
Thank you for this great tool, it helps a lot brother!
My apologies for not paying attention on the other tickets already solved.
I'll close the ticket now!

**Comment by ErikEJ** [comment]
I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details)
