### ISSUE TITLE
T4 template for scaffolding entities ignores using

### ISSUE THREAD

**Issue by pwolfson** [ErikEJ/EFCorePowerTools#1698]
Per the EntityType.t4 template, using includes by, by default, "System" and "System.Collections.Generic". When I remove those two entries, and run the tool, the generated Entities still have the "System" import, which is additional/extra code that is not being used.

### Provide steps to reproduce
To reproduce, edit the default EntityType.t4 template file to the following:
var using = new List<string>();

Then run the tool to generate entities.

Please include a **complete** description or project that I can redo/run to reproduce the issue.

### Provide technical details

- EF Core version in use: EF Core 7

- Is Handlebars used: no

- Is T4 used: yes

- Is .dacpac used: no

- EF Core Power Tools version: 2.5.1277

- Database engine: SQL Server

- Visual Studio version: Visual Studio 2022

**Comment by ErikEJ** [comment]
What is the issue? You can just remove them??

Or am I misunderstanding

**Comment by pwolfson** [comment]
The issue is that EF Core Power Tools is not respecting the T4 template's "using" statements when you try to eliminate the default selections. We tried to eliminate those defaults as we use style cop in our environment and it flags all our classes that have unnecessary using statements. The impact of this is low, but wanted to report this bug.

**Comment by ErikEJ** [comment]
Please provide a sample of you modified template, where does the line you mention go??

**Comment by ErikEJ** [comment]
You could also add autogenerated tag in the template?

**Comment by pwolfson** [comment]
See line 37 in the template file:

var usings = new List<string>();

As you can see I removed the default elements from that array, which were System and System.Collections.Generic. Now, when EF Core Power Tools runs and performs the Reverse Engineering process, the Entities it generates no longer contain the System.Collections.Generic using statement, however the System using statement is still present.

`<#@ template hostSpecific="true" #>
<#@ assembly name="Microsoft.EntityFrameworkCore" #>
<#@ assembly name="Microsoft.EntityFrameworkCore.Design" #>
<#@ assembly name="Microsoft.EntityFrameworkCore.Relational" #>
<#@ assembly name="Microsoft.Extensions.DependencyInjection.Abstractions" #>
<#@ parameter name="EntityType" type="Microsoft.EntityFrameworkCore.Metadata.IEntityType" #>
<#@ parameter name="Options" type="Microsoft.EntityFrameworkCore.Scaffolding.ModelCodeGenerationOptions" #>
<#@ parameter name="NamespaceHint" type="System.String" #>
<#@ import namespace="System.Collections.Generic" #>
<#@ import namespace="System.ComponentModel.DataAnnotations" #>
<#@ import namespace="System.Linq" #>
<#@ import namespace="System.Text" #>
<#@ import namespace="Microsoft.EntityFrameworkCore" #>
<#@ import namespace="Microsoft.EntityFrameworkCore.Design" #>
<#@ import namespace="Microsoft.Extensions.DependencyInjection" #>
<#
    if (EntityType.IsSimpleManyToManyJoinEntityType())
    {
        // Don't scaffold these
        return "";
    }
    var enumList = new List<(string EntityTypeName, string PropertyName, string? EnumType)>();
    enumList.Add( ("User", "UserType", "UserType") );
    enumList.Add( ("User", "MFAType", "MFAType") );
    enumList.Add( ("User", "ColorSchemaType", "ColorSchemaType") );
    enumList.Add( ("UserTypeSetting", "UserType", "UserType") );
    enumList.Add( ("UserTypeSetting", "MFAType", "MFAType") );
    enumList.Add( ("SecurityEventLog", "SecurityEventType", "SecurityEventType") );
    enumList.Add( ("Merchant", "MerchantType", "MerchantType") );
    enumList.Add( ("Merchant", "AgencyType", "AgencyType") );
    enumList.Add( ("AuditLog", "AuditLogActionType", "AuditLogActionType") );

    var services = (IServiceProvider)Host;
    var annotationCodeGenerator = services.GetRequiredService<IAnnotationCodeGenerator>();
    var code = services.GetRequiredService<ICSharpHelper>();

    var usings = new List<string>();

    if (Options.UseDataAnnotations)
    {
        usings.Add("System.ComponentModel.DataAnnotations");
        usings.Add("System.ComponentModel.DataAnnotations.Schema");
        usings.Add("Microsoft.EntityFrameworkCore");
    }

    if (!string.IsNullOrEmpty(NamespaceHint))
    {
#>
namespace <#= NamespaceHint #>;

<#
    }

    if (!string.IsNullOrEmpty(EntityType.GetComment()))
    {
#>
/// <summary>
/// <#= code.XmlComment(EntityType.GetComment()) #>
/// </summary>
<#
    }

    if (Options.UseDataAnnotations)
    {
        foreach (var dataAnnotation in EntityType.GetDataAnnotations(annotationCodeGenerator))
        {
#>
<#= code.Fragment(dataAnnotation) #>
<#
        }
    }
#>
public partial class <#= EntityType.Name #>
{
<#
    var firstProperty = true;
    foreach (var property in EntityType.GetProperties().OrderBy(p => p.GetColumnOrder() ?? -1))
    {
        if (!firstProperty)
        {
            WriteLine("");
        }

        if (!string.IsNullOrEmpty(property.GetComment()))
        {
#>
    /// <summary>
    /// <#= code.XmlComment(property.GetComment(), indent: 1) #>
    /// </summary>
<#
        }

        if (Options.UseDataAnnotations)
        {
            var dataAnnotations = property.GetDataAnnotations(annotationCodeGenerator)
                .Where(a => !(a.Type == typeof(RequiredAttribute) && Options.UseNullableReferenceTypes && !property.ClrType.IsValueType));
            foreach (var dataAnnotation in dataAnnotations)
            {
#>
    <#= code.Fragment(dataAnnotation) #>
<#
            }
        }

        usings.AddRange(code.GetRequiredUsings(property.ClrType));

        var enumTuple = enumList.SingleOrDefault(t => t.EntityTypeName == EntityType.Name && t.PropertyName == property.Name);
        var needsNullable = Options.UseNullableReferenceTypes && property.IsNullable && !property.ClrType.IsValueType;
        var needsInitializer = Options.UseNullableReferenceTypes && !property.IsNullable && !property.ClrType.IsValueType;
        var propertyType = enumTuple.EnumType ?? code.Reference(property.ClrType);
#>
    public <#= propertyType #><#= needsNullable ? "?" : "" #> <#= property.Name #> { get; set; }<#= needsInitializer ? " = null!;" : "" #>
<#
        firstProperty = false;
    }

    foreach (var navigation in EntityType.GetNavigations())
    {
        WriteLine("");

        if (Options.UseDataAnnotations)
        {
            foreach (var dataAnnotation in navigation.GetDataAnnotations(annotationCodeGenerator))
            {
#>
    <#= code.Fragment(dataAnnotation) #>
<#
            }
        }

        var targetType = navigation.TargetEntityType.Name;
        if (navigation.IsCollection)
        {
#>
    public virtual ICollection<<#= targetType #>> <#= navigation.Name #> { get; } = new List<<#= targetType #>>();
<#
        }
        else
        {
            var needsNullable = Options.UseNullableReferenceTypes && !(navigation.ForeignKey.IsRequired && navigation.IsOnDependent);
            var needsInitializer = Options.UseNullableReferenceTypes && navigation.ForeignKey.IsRequired && navigation.IsOnDependent;
#>
    public virtual <#= targetType #><#= needsNullable ? "?" : "" #> <#= navigation.Name #> { get; set; }<#= needsInitializer ? " = null!;" : "" #>
<#
        }
    }

    foreach (var skipNavigation in EntityType.GetSkipNavigations())
    {
        WriteLine("");

        if (Options.UseDataAnnotations)
        {
            foreach (var dataAnnotation in skipNavigation.GetDataAnnotations(annotationCodeGenerator))
            {
#>
    <#= code.Fragment(dataAnnotation) #>
<#
            }
        }
#>
    public virtual ICollection<<#= skipNavigation.TargetEntityType.Name #>> <#= skipNavigation.Name #> { get; } = new List<<#= skipNavigation.TargetEntityType.Name #>>();
<#
    }
#>
}
<#
    var previousOutput = GenerationEnvironment;
    GenerationEnvironment = new StringBuilder();

    foreach (var ns in usings.Distinct().OrderBy(x => x, new NamespaceComparer()))
    {
#>
using <#= ns #>;
<#
    }

    WriteLine("");

    GenerationEnvironment.Append(previousOutput);
#>
`

**Comment by ErikEJ** [comment]
I am guessing that the system using is always being scaffolded regardless.

As I said, you can add an autogenerated tag to avoid code analysis warnings

**Comment by ErikEJ** [comment]
The using is added if you have properties like for example DateTime - appears to happen in the EF Core sacffolding pipeline, so not something I can change 

 @bricelam FYI

**Comment by bricelam** [comment]
You'll probably need to remove them at the end of the template just before the actual code is generated. Fluent API calls and the types of properties in you model also affect the usings--these get added throughout the template.

See also https://github.com/dotnet/efcore/issues/28672

**Comment by ErikEJ** [comment]
@bricelam Thanks for confirming
