### ISSUE TITLE
Visual studio crashes when trying to install EF Core packages after 17.5 update

### ISSUE THREAD

**Issue by lucora** [ErikEJ/EFCorePowerTools#1703]
I'm having during the reverse engineering process visual studio hangs while trying to install the EF Core nuget packages. If you omit the option to install them everything works fine.

- EF Core version in use: (EF Core 7)
- Visual Studio version: (Visual Studio 2022  ==  17.5 )

Thank you for developing this extension it's really cool.

Best regard
Luca

**Comment by ErikEJ** [comment]
hangs or crashes? Ih hang, I think it is because I wait for the install to complete, I will just make it fire and forget.

**Comment by ErikEJ** [comment]
If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

**Comment by lucora** [comment]
Done!

Il giorno ven 24 feb 2023 alle ore 13:48 Erik Ejlskov Jensen <
***@***.***> ha scritto:
