### ISSUE TITLE
Generate Stored Proc model class in Pascal Case

### ISSUE THREAD

**Issue by vsdotnetguy** [ErikEJ/EFCorePowerTools#1704]
First, thank you so much Erik for this excellent utility.  My firm uses it to rev engineer both table and stored procedures.  For legacy apps being converted to Blazor, we often work with legacy stored procedures.  We love the generated sproc model classes but wonder if EF Core PT can be configured to generate Pascal Case instead of Snake Case.  We currently use a separate utility and would like to skip that step if possible.  Please advise.

Thx...Bob Baldwin
aka VSDotNetGuy

**Comment by ErikEJ** [comment]
Could you share an example and I will have a look.

**Comment by ErikEJ** [comment]
I think stored procedures and functions can be renamed like tables: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#custom-renaming-with-efptrenamingjson (I have just updated the docs)

**Comment by vsdotnetguy** [comment]
Does this also affect the stored procedure result class property renaming?

**Comment by ErikEJ** [comment]
Not sure - what have you tried?

**Comment by vsdotnetguy** [comment]
Nothing quite yet.  We will take a look and get back on this.

**Comment by ErikEJ** [comment]
I am going to close this. Feel free to reopen with any updates.
