### ISSUE TITLE
DDL SQL Index on xml field

### ISSUE THREAD

**Issue by MikeCley** [ErikEJ/EFCorePowerTools#1708]
If table has an xml field with index View DbContext SQL command compose script
CREATE INDEX [IX_Location_Svg] ON [LocationMaps] ([Svg]);

that cause parse error "Column [Svg] in table [LocationMaps] is of type that is invalid for use as a key column in an index. "

Original index created:
`CREATE PRIMARY XML INDEX [IX_Location_Svg] ON [dbo].[LocationMaps](	[Svg])
`

**Comment by ErikEJ** [comment]
can you share the full stack trace?

**Comment by ErikEJ** [comment]
And maybe a repro CREATE script?

**Comment by MikeCley** [comment]
CREATE TABLE [dbo].[LocationMaps](
	[Id] [uniqueidentifier] NOT NULL,
	[Code] [nvarchar](25) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Description] [nvarchar](250) NULL,
	[LocationId] [uniqueidentifier] NOT NULL,
	[Svg] **[xml]** NOT NULL,
	[SourceFile] [image] NULL,
	[RowVersion] [timestamp] NOT NULL,
 CONSTRAINT [PK_LocationMap] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
CREATE PRIMARY **XML** INDEX [IX_Location_Svg] ON [dbo].[LocationMaps]
(
	[Svg]
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

**Comment by ErikEJ** [comment]
Can you share the full error stack?

**Comment by ErikEJ** [comment]
I am able to reverse engineer your table based on the script above - so when and where does the error occur?

**Comment by MikeCley** [comment]
Let table has an index on xml field.
Nice tool generate [Index("Svg", Name = "IX_Location_Svg")] attribute.
Then View DbContext SQL generate CREATE INDEX [IX_Location_Svg] ON [LocationMaps] ([Svg]);
Parse SQL throw "Column [Svg] in table [LocationMaps] is of type that is invalid for use as a key column in an index. "

**Comment by ErikEJ** [comment]
Ah! Do not expect EF Core to know about xml indexes. The SQL generated by this feature does nit roundtrip all possible schema properties
