### ISSUE TITLE
System.InvalidOperationException when using user-defined table type

### ISSUE THREAD

**Issue by t67if43r43** [ErikEJ/EFCorePowerTools#1711]
When using EF Core Powertools Reverse Engineering on a Table-Value-Function (TVF) which takes user-defined table type (UDT) as parameters, the application will throw a 'System.InvalidOperationException'.

```
Exception thrown: 'System.InvalidOperationException' in Microsoft.EntityFrameworkCore.Relational.dll
An exception of type 'System.InvalidOperationException' occurred in Microsoft.EntityFrameworkCore.Relational.dll but was not handled in user code
The parameter 'UserDefinedIdTable' for the DbFunction '*.GetDataViaTVF(System.Data.DataTable)' has an invalid type 'DataTable'. Ensure the parameter type can be mapped by the current provider.
```
### Steps to reproduce

The user-defined table type _UserDefinedIdTable_ is defined as:
```
CREATE TYPE [dbo].[UserDefinedIdTable] AS TABLE (
[Id] INT NOT NULL
);
```

The method generated by EF Core Powertools looks like this:
  ```
      [DbFunction("GetDataViaTVF", "dbo")]
        public IQueryable<GetDataViaTVFResult> GetDataViaTVF(DataTable UserDefinedIdTable)
        {
            return FromExpression(() => GetDataViaTVF(UserDefinedIdTable));
        }
```

### Provide technical details

- EF Core version in use: EF Core 6.0.14

- Is Handlebars used: yes

- Is T4 used: no

- Is .dacpac used: no

- EF Core Power Tools version: 2.5.1296

- Database engine: SQL Server

- Visual Studio version: Visual Studio 2022 Version 17.5.0

**Comment by ErikEJ** [comment]
Does this happen when using the function?

**Comment by ErikEJ** [comment]
Actually the function should not have been scaffolded, and you should see a warning like:

`Unable to scaffold FUNCTION 'dbo.FuncWithTvpParameter' as it has TVP parameters.
`

**Comment by ErikEJ** [comment]
Please share a full repro SQL script to create the function and the table type.

**Comment by t67if43r43** [comment]
1. The exception is thrown when calling `_context.Database.GetDbConnection()` from within a controller.
2. The function will scaffold without a warning for me. 
3. It occured to me that this might be an EF Core issue and not related to EF Core Powertools.

**Comment by ErikEJ** [comment]
But EF Core Power Tools should not generate the code. 

If you do not want to share a script I will close this. EF Core does not support this type of function currently.
