### ISSUE TITLE
Updating extension

### ISSUE THREAD

**Issue by mrunks** [ErikEJ/EFCorePowerTools#1712]
I have noticed that trying to update the existing extension in visual studio 2022 it times out.  It might be the company I am at but wondered if others have experienced problems.  I am able to download it from the Visual Studio Market Place and install it.
Was wondering if the location that is tied to updating the extension has changed or has anyone else experienced the download timeout ?

- Visual Studio version: (e.g. Visual Studio 2022)

**Comment by ErikEJ** [comment]
I am guessing it is a transient MarketPlace issue.

**Comment by mrunks** [comment]
I am not familiar with what you mean by transient ? Could you explain in more detail ?

**Comment by ErikEJ** [comment]
A point in time error, maybe due to some resource abuse or other issue on the Server Hastings the file.

**Comment by ErikEJ** [comment]
Also, the package size has increased a lot kately due to ARM support, but I have tried to Shrink it in the latest daily

**Comment by mrunks** [comment]
And to confirm, the location of where the package is hosted has not changed, only the file size then ?

**Comment by ErikEJ** [comment]
Are you talking about the latest daily on VSIX Gallery or the VS MarketPlace ??

**Comment by mrunks** [comment]
I am referring to updating the extension from within Visual Studio 2022.  I click to update it and it times out like either the download is being blocked by my company or maybe I cannot access the location of where the extension resides.  

But if I go to the here:

https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools

I have no problem.

**Comment by ErikEJ** [comment]
Should absolutely be the same place - it could be company networking/restrictions.
