### ISSUE TITLE
Using renaming.json overriding the default naming schema

### ISSUE THREAD

**Issue by prokopec-simon** [ErikEJ/EFCorePowerTools#1716]
Hi!

Until now I've been manually correcting generated names of models from tables. Now that I have added renaming.json it overrides the default model renaming schema completely. **Is there any way to apply both custom renaming and the default renaming schema?**

The renaming config:

  {
    "ColumnPatternReplaceWith": "",
    "ColumnRegexPattern": "^(TABPREFIX_)|^(VIEWPREFIX_)",
    "SchemaName": "dbo",
    "TablePatternReplaceWith": "",
    "TableRegexPattern": "^(TABPREFIX_)|^(VIEWPREFIX_)",
    "Tables": [],
    "UseSchemaName": false
  }

### Behaviour description:

**Behaviour without renaming.json:**
TABPREFIX_User -> TabprefixUser 
TABPREFIX_OD_CustomUser -> TabprefixOdCustomUser
TABPREFIX_JOINS -> TabprefixJoins
_I'd then replace "Tabprefix" with "", resultin in User, OdCustomUser, Joins)_

**Behaving with renaming.json:**
TABPREFIX_User -> User
TABPREFIX_OD_CustomUser -> OD_CustomUser
TABPREFIX_JOINS -> JOINS
_Replacing works correctly but completely overrides the default behaviour, resulting in case being 1:1 copied from SQL._

**Expected behaviour:**
TABPREFIX_User -> User
TABPREFIX_OD_CustomUser -> OdCustomUser
TABPREFIX_JOINS -> Joins

---

- EF Core version in use: EF Core 6
- Is Handlebars used: yes
- Is T4 used: no
- Is .dacpac used: no
- EF Core Power Tools version: 2.5.1296
- Database engine: SQL Server
- Visual Studio version: Visual Studio 2022

---

**_Thanks for any assistance in advance. <3_**

**Comment by ErikEJ** [comment]
LOL! 

Do you have "Use Database Names" selected?

**Comment by prokopec-simon** [comment]
I do not, this is the configuration I use. Glad I made you laugh with my advanced techniques haha.

![image](https://user-images.githubusercontent.com/97883441/222681754-a697401e-1092-49c7-8ac3-a9f1106b02f7.png)

**Comment by ErikEJ** [comment]
Ah. Handlebars... can you try to remove that from the equation.

**Comment by prokopec-simon** [comment]
I tried generating it without the handlebars and if using renaming.json it still results in the same naming schema.

**Comment by prokopec-simon** [comment]
I am an idiot. I found the thing causing this - power tools config.json has this config option:
"**PreserveCasingWithRegex**" and it's set to true by default, so until I added the renaming regex it didn't get applied, setting it to false seems to result in the expected behaviour.

Thank you for your assistance.

**Comment by ErikEJ** [comment]
Cool! Yes, I was trying to remember that setting - when I changed the default it caused a lot of anger, so I made it optional.

**Comment by ErikEJ** [comment]
If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
