### ISSUE TITLE
Property renaming extremely slow

### ISSUE THREAD

**Issue by luis-barreira** [ErikEJ/EFCorePowerTools#1719]
I am in the process of migrating a very large project from .Net Framework 4.8 to .NET 7 and I have chosen your excellent tool to generate the classes for our database.

Almost everything is working fine but the renaming of navigation properties is extremely slow. The database is big, more than 300 tables, and some of the navigation properties generated by the entity framework have attrocious names, so I created a efpt.property-renaming.json file with the desired renames (a little over 3000 lines).

It all works, but it takes a long time: the model classes are created in about 5 / 6 seconds with the original names and then apparently nothing more happens. Some 20 / 30 minutes later the names of the navigation properties are changed, apparently all at the same time (cannot be completely sure about this, I can't check all the generated files, there's too many of them).

**Comment by ErikEJ** [comment]
>> (a little over 3000 lines).

OMG! Interesting!

Are you able to share the schema (privately) ? 

I will look for some low hanging fruits...

**Comment by ErikEJ** [comment]
You could also launch a debugger and step through  src\GUI\Shared\Helpers\RoslynEntityPropertyRenamer.cs to find out what takes so long. Issue probably is that Roslyn needs to go through all 300 files for each rename.

Why do you need to rename all your navigations?

**Comment by ErikEJ** [comment]
Had a quick look at the code, yes, each file in your Models folder (and it's subfolders) are checked for each rename.

Since it is navigations, it is required.

**Comment by luis-barreira** [comment]
Yes, I can share with you the schema (privately).
I am not renaming all the navigations, only some that are created with strange names. The database uses a "strange" naming scheme where all field names have a prefix that identifies the table where they belong, for example, all the fields in the "_users_" table are called "_usr_fieldname_" (except for foreign keys from other tables), so the id for this table is "_usr_id_". This results in some other table having a navigation property called "_usr_idNavigation_" (this is to be renamed to something more meaningful).

**Comment by ErikEJ** [comment]
Looking forward!

**Comment by luis-barreira** [comment]
How can I send it to you?

**Comment by ErikEJ** [comment]
Email me ejlskov at Hotmail dot com

**Comment by luis-barreira** [comment]
Sent.

**Comment by ErikEJ** [comment]
OK, for each rename operation the code needs to find the relevant documents and do the replace. You have 224 classes so at least  224 renames. 

Unfortunately if is the call to do the actual renaming in Roslyn `Renamer.RenameSymbolAsync` that takes a long time. If I remove it the whole process takes 60 seconds on my PC.

My best suggestion is to create multiple projects with each a subset of your entire schema.

I have improved feedback by adding a progress bar in the latest daily.

@R4ND3LL Do you have any other suggestions?

**Comment by R4ND3LL** [comment]
@ErikEJ you're correct, the Roslyn refactoring calls are not the fastest.  For large projects, it will definitely take some time.

As you know, I have developed features specifically around upgrading from legacy EF (with EDMX) to EF core 6/7 in my project [Entity Framework Ruler](https://github.com/R4ND3LL/EntityFrameworkRuler) (EFR)

While the Roslyn refactoring approach is still supported, the main workflow in EFR involves tapping into EF Core's design time scaffolding process and applying all changes to the model during the scaffolding phase itself, removing any need to use Roslyn.  This workflow is capable of applying changes to HUGE database models with barely any impact on the overall scaffolding execution time.  

I've even added support for many other features such as entity inheritance (TPH, TPT, TPC), table splitting (multiple entities based on the same table, each with their own column subset), design time navigations (that were built in the EDMX but not in the DB), navigation support for views, etc..

@luis-barreira I would suggest you try [EFR](https://github.com/R4ND3LL/EntityFrameworkRuler) if performance is a priority, or if need any of the above mentioned EDMX based features.

**Comment by ErikEJ** [comment]
@R4ND3LL thanks gor the kind words about your tool. I had a look at your code. Is navigation renaming not still using Roslyn???

**Comment by R4ND3LL** [comment]
> @R4ND3LL thanks for the kind words about your tool. I had a look at your code. Is navigation renaming not still using Roslyn???

The [command line tool](https://www.nuget.org/packages/EntityFrameworkRuler/) is used to generate the json model file from an EDMX, as well as apply the json rules to an existing (already scaffolded) project **using Roslyn**.  So yes, this does use Roslyn.  This process supports only renaming and type changing.

Alternatively, the [Design](https://www.nuget.org/packages/EntityFrameworkRuler.Design/) nuget package only needs to be referenced by the EF Core project, then when you run the EF scaffolding command all rules will be applied at runtime and **_does not_ use Roslyn**.    This process supports all the advanced features like table splitting, inheritance, etc.

At this point, the [VS extension](https://marketplace.visualstudio.com/items?itemName=Randell.EF-Ruler) can also be used to generate the json model from EDMX instead of the command line tool.  The extension also provides a full model editor.
