### ISSUE TITLE
Reverse Engineering Settings Windows Frame to small?

### ISSUE THREAD

**Issue by mohrf** [ErikEJ/EFCorePowerTools#1721]
I assume it is a simple size problem of the context definition window. It looks like the window frame is set to small now.
I am missing a few options, at all the button to start the reverse engineering... pls see the screenshot

![grafik](https://user-images.githubusercontent.com/93774983/223391641-2e084fb4-b91e-4439-8e8b-e3ead63f140c.png)

Btw. great tool, and usually a life saver.
 

### Provide steps to reproduce
Open the Reverse Engineering option and navigate to the context definition view.

### Provide technical details
- EF Core version in use:  EF Core 6
- EF Core Power Tools version: 2.5.1319 (Issue started with 2.5.1316)
- Database engine: SQL Server, Azure SQL
- Visual Studio version: Visual Studio 2022

**Comment by ErikEJ** [comment]
What is you screen magnification setting?

**Comment by ErikEJ** [comment]
I have tried to make the form slightly higher, notice that some options have been moved to the advanced dialog

I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

**Comment by ErikEJ** [comment]
@mohrf Any news?

**Comment by mohrf** [comment]
@ErikEJ the frame is now resizeable, therefore I am able to see all options and controls again.
 Still I suggest to set the min size correctly to show all options and controls. 

current min size frame:
![grafik](https://user-images.githubusercontent.com/93774983/223661886-b8328f86-02e0-4635-aa1b-765e63d4cecf.png)

suggested min size frame:
![grafik](https://user-images.githubusercontent.com/93774983/223662103-8e0bb49e-bccd-4128-a44d-38fe70c280b3.png)

Thank you for the quick reaction and support.

**Comment by mohrf** [comment]
My settings are: 2560 x 1440

**Comment by ErikEJ** [comment]
And your magnification display setting?

**Comment by mohrf** [comment]
100% - nothing unusual

![grafik](https://user-images.githubusercontent.com/93774983/223687868-5586e6b9-5085-40fd-97d0-0b9b1025fec6.png)

**Comment by ErikEJ** [comment]
This is my screen at same resolution and scaling:

![image](https://user-images.githubusercontent.com/4169187/223716598-bbf7496e-7ea4-43d2-a4a9-7dcbb3e2e470.png)

This is with a large VS Environment font size (18) 

![image](https://user-images.githubusercontent.com/4169187/223717495-7124d4b4-6d36-44bd-bb09-a54080499962.png)

(Not prettry, but still works)

**Comment by mohrf** [comment]
Dunno what to tell you Erik. As long as the form is resizeable, I can live with it.
On the other hand, it will not hurt to resize it bigger as it needs to be I guess. Perhaps then I can still all.

If you wanna check it it out directly, I can open a Teamviewer session with you or test another version. Up to you.

**Comment by ErikEJ** [comment]
@mohrf Issue is it I make it bigger, it is too big for everyone else....

**Comment by mohrf** [comment]
yeah, I guess ppl act like this...
Check the vid, I would suggest a size as shown at the end of the vid. 
In my opinion it i snot too big (for all).
But at the end it is up to you. As long as you keep it resizeable I can still live with it.

https://user-images.githubusercontent.com/93774983/223748576-66961da9-c437-45c7-93fe-cd41046a8492.mp4

**Comment by ErikEJ** [comment]
I see all the buttons when the form opens !?

**Comment by ErikEJ** [comment]
I will make more changes if I get more reports of this.

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

**Comment by mohrf** [comment]
Hi Erik

Looks perfect to me.

![grafik](https://user-images.githubusercontent.com/93774983/224299393-94011eb6-6bed-4a75-ae3b-8ac0b0e999e1.png)

**Comment by ErikEJ** [comment]
Finally! I am a WPF idiot..
