### ISSUE TITLE
Enum Migrations

### ISSUE THREAD

**Issue by davidhendrickmb** [ErikEJ/EFCorePowerTools#1722]
Hi there,

Would it be possible to generate enum classes based on data in tables in the database?

Thanks,
David

**Comment by davidhendrickmb** [comment]
Perhaps a future potential feature?

**Comment by ErikEJ** [comment]
The tool does not have knowledge of the classes in the project. Do it is going to be difficult/ error prone.

**Comment by davidhendrickmb** [comment]
Apologies if I'm over simplifying it. I was thinking that as part of the reverse engineer process you could have an extra section entitled "Enum Tables" or similar. The schema is retrieved from the database so I thought the data in the table could also be generated and then an enum created as opposed to the class. I suppose you would need to have a clearly defined column naming strategy. 

![image](https://user-images.githubusercontent.com/18259436/223408297-137c2ee2-50ec-4792-bd8c-dfc85b2eccfc.png)

**Comment by ErikEJ** [comment]
Ok, but then what about the mapping between the Enum and tables using the Enuum?

**Comment by davidhendrickmb** [comment]
That's a fair point. Could you generate the class as normal and add the enums to a separate namespace?

**Comment by ErikEJ** [comment]
I could do many things, but is it what all users want - if not, it quickly becomes a special casing nightmare.

**Comment by ErikEJ** [comment]
@davidhendrickmb Have you seen [this](https://github.com/ErikEJ/EFCorePowerTools/issues/1472#issuecomment-1220273164)

**Comment by ErikEJ** [comment]
I believe the current support for enums is sufficient for the majority of use cases.
