### ISSUE TITLE
Compatible with Mac?

### ISSUE THREAD

**Issue by ecoffman** [ErikEJ/EFCorePowerTools#1723]
Can this be run on a Mac? I cannot figure out how that is done.... if possible. Thanks.

**Comment by ErikEJ** [comment]
No, it is a .NET Framework .DLL - but the main functionality is also available as an (unsupported) command line tool, as described in [the wiki](https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#requirements)

**Comment by ErikEJ** [comment]
For anyone watching this issue, this is now planned, and you can find a design proposal [here](https://github.com/ErikEJ/EFCorePowerTools/issues/1751) - looking forward to any comments/suggestions.

**Comment by ErikEJ** [comment]
Preview 1 of the CLI tool is [now available](https://www.nuget.org/packages/ErikEJ.EFCorePowerTools.Cli/7.0.0-preview1#readme-body-tab)

![image](https://user-images.githubusercontent.com/4169187/234258058-2b6def58-f87c-455a-93da-21cd09d9e3f7.png)
