### ISSUE TITLE
Property default value

### ISSUE THREAD

**Issue by Denn1B01** [ErikEJ/EFCorePowerTools#1724]
Hello,
i have a question concerning the reverse engineering. 
Is there a way to configure the settings to set entity property "HasDefaultValueSql(null)" in the OnModelCreation method?
Its a big issue, columns that allow nulls were filled with empty strings by default for example.

Thank you in advance :)

### Provide technical details

EF Core 7

- EF Core Power Tools version: 2.5.1277

- Database engine: SQL Server

- Visual Studio version: Visual Studio 2022

**Comment by ErikEJ** [comment]
Please provide an example of a CREATE script, actual outcome and expected outcome.

**Comment by ErikEJ** [comment]
for the CREATE script I meant the CREATE TABLE script, pls.

I think you just need to remove the wrong defaults, and HasDefaultValueSql(null) is the same a no HasDefaultValueSql at all.

**Comment by Denn1B01** [comment]
i see the issue now
[CreateTable.txt](https://github.com/ErikEJ/EFCorePowerTools/files/10910658/CreateTable.txt)

Bad philosophy from the developer of the database, to give every field a default value :(

Thank you!

**Comment by ErikEJ** [comment]
So you can fix it?

**Comment by Denn1B01** [comment]
Just workaround with set HasDefaultValueSql(null) or delete the rows. Maybe there is a option in the future to ignore default values in EF Core Power Tools

**Comment by ErikEJ** [comment]
There is an option to ignore 0 default values on bool columns

**Comment by ErikEJ** [comment]
@Denn1B01 I hope you are aware that yoy can override in a partial class that does not get overwritten?

**Comment by Denn1B01** [comment]
You mean override the OnModelCreating(ModelBuilder modelBuilder) method in a partial context class? 
Thats impossible i think. Maybe i can inherit the context in a new class and and override the OnModelCreating(ModelBuilder modelBuilder)

**Comment by ErikEJ** [comment]
There is a partial method OnModelCreatingPartial that you can implement in a partial class. Read the docs!

**Comment by Denn1B01** [comment]
A cool thank you. That will do the trick :)

**Comment by ErikEJ** [comment]
If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
