### ISSUE TITLE
Advanced settings changes not being saved

### ISSUE THREAD

**Issue by WycoffJohn** [ErikEJ/EFCorePowerTools#1726]
Just updated EFCorePowerTools and the setting for Advanced > Mapping > Map DateOnly and TimeOnly is not being retained.

### Provide steps to reproduce

Once Map DateOnly and TimeOnly is enabled, the setting to disable it does not retain and is still enabled on next reverse engineer.

1) Open Advanced and select Mapping > Map DateOnly and TimeOnly.
2) Complete reverse engineer.
3) Perform another Reverse Engineer, this time uncheck Map DateOnly and TimeOnly. Complete Reverse Engineer.
4) Perform another Reverse Engineer, Map DateOnly and TimeOnly is still checked.

### Provide technical details

- EF Core version in use: (e.g. EF Core 7) - CF Core 6

- Is Handlebars used: no/yes No

- Is T4 used: no/yes - No

- Is .dacpac used: no/yes - I dont think so

- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu) - 2.5.1316

- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL) SQL Server 2019

- Visual Studio version: (e.g. Visual Studio 2022) VS 2022

**Comment by ErikEJ** [comment]
Why do you not want it enabled?

You can revert this behavior via the new general setting in Tools/Options: Set mappings based on data types in use

**Comment by ErikEJ** [comment]
Are you good??

**Comment by ErikEJ** [comment]
This good default behaviour can be disabled globally. 

I will update the docs to make the new behavior better documented.

**Comment by WycoffJohn** [comment]
The issue is that the setting is not being saved. It will save it when you enable it. But then it will not save when you disable it. I have to uncheck this option each time I reverse engineer.

FYI, I personally would like to have this enabled but my code is expected DateTime and I do not have the time to refactor everything right now so I am leaving this option as unchecked.

**Comment by ErikEJ** [comment]
You can use the the option in Tool/Options to disable thus behaviour..does that not work for you??

**Comment by WycoffJohn** [comment]
> You can use the the option in Tool/Options to disable this behaviour..does that not work for you??

I do not see any option for Map DateOnly and TimeOnly under Tools > Options > EF Core Power Tools

**Comment by iancarter** [comment]
Just want to chime in here and say I have the same issue. I also don't see any settings related to this in Tools -> Options -> EF Core Power Tools. I'd love for this setting to save as 'disabled' when you disable it.

As for why, it's a mix of refactoring time and because of "could not be mapped because it is of type x" issues that don't appear to be solved by the ErikEJ.EntityFrameworkCore.SqlServer.DateOnlyTimeOnly package.

**Comment by ErikEJ** [comment]
The setting is called Set mappings based on data types in use.

You need to enable it as shown in the readme that opens after reverse engineering  with;

.UseDateOnlyTimeOnly

I will Update the description of this option to make this clearer.

**Comment by iancarter** [comment]
> The setting is called Set mappings based on data types in use.
> 
> You need to enable it as shown in the readme that opens after reverse engineering with;
> 
> .UseDateOnlyTimeOnly
> 
> I will Update the description of this option to make this clearer.

Wanted to follow up and say the 'Set mappings based on data types in use.' setting did what I needed. Thank you for your patience :)

I did try '.UseDateOnlyTimeOnly' but I still ran into the same mapping issues. Thanks again!

**Comment by ErikEJ** [comment]
@iancarter Happy to look into the mapping issues if you can share a repro.

And for sure the docs and title of that option needs improved.

**Comment by nikriaz** [comment]
Same problem here. I have the "Date" data type in SQL, which is mapped to DateOnly type during reverse engineering. Then, I'm getting EF 7.0 runtime error that DateOnly mapping is not supported. Hence, I have to go to EF Power Tool advanced settings and uncheck Map DateOnly and TimeOnly, then everything works as expected. 

However, I have to uncheck it every time before reverse engineering, this setting is not saved. It looks like some other checkboxes in settings/advanced settings are memorized (not sure about all of them) but "Map DateOnly and TimeOnly" certainly is not.

What is really strange, is that I used the same database and same code base for months and never got this EF runtime error and never had to change EF Power Tools advanced settings. Now I have to uncheck this setting every time. It looks like something was updated (Visual Studio, EF PowerTools or EF itself) that started to cause this error.

**Comment by nikriaz** [comment]
> Why do you not want it enabled?
> 
> You can revert this behavior via the new general setting in Tools/Options: Set mappings based on data types in use

Set mapping based in data type is actually what I need. I just don't want to map data types which are not supported by EF, like DateOnly, And apparently it used to work with all defaults, this problem is something new.

**Comment by ErikEJ** [comment]
@nikriaz It IS supported with EF Core 6 and 7, just install the supporting package and add .UsDateOnlyTimeOnly() to your DbContextOptions.

See the wiki for more details  or read the PowerToolsReadme that pops up after reverse engineering.

**Comment by WycoffJohn** [comment]
So this issue is fixed or just the description updated?

**Comment by WycoffJohn** [comment]
> So this issue is fixed or just the description updated?

I see you are saying this is default behavior now. Got it! However I do have to say this is not normal expected behavior with a checkbox settings. Especially considering other checkbox settings in this project do not behave the same way

**Comment by ErikEJ** [comment]
@WycoffJohn  I agree

Maybe the checkboxes should be read-only when this option is on?

**Comment by ErikEJ** [comment]
@WycoffJohn  Latest daily:

![image](https://user-images.githubusercontent.com/4169187/224495644-bd8b7292-95ca-4082-8165-ace9180e1dc8.png)

**Comment by nikriaz** [comment]
@ErikEJ Actually, even if these data types are supported (with some extra effort), I need to refactor my code to accommodate this. This is something that I would skip now. 

Honestly, I'm okay with removing this checkbook and map Date only to DateTime, as it used to be all the time and as my entire code based on. The only annoying thing is that I have to go there and uncheck it every time. Sometimes I forget to do so and then my app breaks up on the error.

**Comment by ErikEJ** [comment]
@nikriaz You just have to go to Tools/Options once !?

**Comment by nikriaz** [comment]
... but you said it's only possible to disable mapping based on data types entirely? My app is in an active development phase and new entities are adding regularly.  I suspect that disabling this setting will affect the base functionality of reverse engineering, isn't it? At least it sounds like that. The Date only field is very old but I can't remove it yet. 

Just to give you a bit more background, I have three totally independent apps that share the same database. This is why I can't (or don't want to) use Code First, and  enjoy EF Power Tools reverse engineering feature that really make my life easier.

**Comment by ErikEJ** [comment]
@nikriaz I think you misunderstood. It only concerns the mappings that are not currently navitively supported by EF Core, like spatial, hierarcyid and date and time.

**Comment by ErikEJ** [comment]
I think I will make this opt-in rather than opt out....

**Comment by ErikEJ** [comment]
@nikriaz I have made some changes and updated the docs:  https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#mapping 

![image](https://user-images.githubusercontent.com/4169187/224532377-80e63558-9d38-43fc-a862-056e9792b670.png)

Let me know what you think - maybe the label text needs rephrasing?

**Comment by nikriaz** [comment]
@ErikEJ Thank you very much for the detailed explanation. Now I got it. I think the latest version makes it very clear. Thank you very much for your work!!

**Comment by ErikEJ** [comment]
@nikriaz thanks for all your feedback. I have decided to remove that feature based on  it.

**Comment by ErikEJ** [comment]
If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by nikriaz** [comment]
Yes, I like your tool very much, will certainly do. 

BTW, the latest implementation from your screenshot with an opt-in approach was beautiful. I don't think it needs to be removed.

**Comment by ErikEJ** [comment]
@nikriaz >> the latest implementation from your screenshot with an opt-in approach was beautiful. I don't think it needs to be removed.

Thanks, but in order for this to work, the required extensions must be installed.. It got to complex and messy.
