### ISSUE TITLE
[FEATURE] Opt out of Read Me file after running Reverse Engineering

### ISSUE THREAD

**Issue by philipstratford** [ErikEJ/EFCorePowerTools#1729]
Every time I run the reverse engineering process the Power Tools Read me file opens. I can't see a way to alter the configuration to disable this behaviour so it'd be nice to maybe be able to check a box saying "Don't show Read Me" or something similar.

**Comment by ErikEJ** [comment]
Just check it 😄 - "Open Generated DbContext" https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#advanced-visual-studio-options
