### ISSUE TITLE
 EF Core 7 schema -> the default DbContext constructor does not generate

### ISSUE THREAD

**Issue by MatthiasBedard** [ErikEJ/EFCorePowerTools#1737]
When generating in EF Core 7 the default DbContext constructor does not generate unless you select "Include connection string in generated code".

It appears the behavior of "Remove default DbContext constructor" is being applied without selecting it in the advanced settings.

**Comment by ErikEJ** [comment]
Which extension version? 

There was a bug in that area at one point

**Comment by ErikEJ** [comment]
That is actually by design with EF Core 7 - why do you need the dafault constructor?

**Comment by ErikEJ** [comment]
If you really need it, you can use T4 templates and modify DbContext.t4

**Comment by MatthiasBedard** [comment]
Latest version 2.5.1315.  Reason for needing this is project I upgraded from ef 6  depends on the default constructor for all using statements.

Thanks for the response.

**Comment by MatthiasBedard** [comment]
> If you really need it, you can use T4 templates and modify DbContext.t4

I'm not familiar with T4 templates. If you could point me in the right direction for handling this it would be much appreciated.   Big fan of EF power tools. It has saved me a lot of headaches! 🙏

**Comment by ErikEJ** [comment]
Actually, you can just create a partial DbContext class with the default constructor!
@MatthiasBedard
