### ISSUE TITLE
Map DateOnly is not saved

### ISSUE THREAD

**Issue by EXT1433S** [ErikEJ/EFCorePowerTools#1739]
The Option for Map DateOnly is automaticly set to true every time i use **EF Core PowerTools - Edit**

![grafik](https://user-images.githubusercontent.com/77621412/224724685-859256ca-fbef-41e4-b7e7-c3a9824063f6.png)

![grafik](https://user-images.githubusercontent.com/77621412/224723723-60b09778-57d2-48ca-b8f3-2460427d49ca.png)

When the Checkbox is removed everything works fine, except if i do a "**EF Core PowerTools - Edit**" again, this setting is not renemberd.

Refresh works fine but Edit ignores the last setting for this Checkbox.

### Provide technical details

- EF Core 6

- EF Core Power Tools version: 2.5.1338

- SQL Server

- Visual Studio 2022

PS.
Wouldn't know what to do without your Extension :-)

**Comment by CallumBateson** [comment]
I am also experiencing this issue, similarly, the "Install the EF Core provider package in project" selection is not saved either.

**Comment by CallumBateson** [comment]
> @CallumBateson This has been changed in the latest release - which version are you running?

Ah I'm still on 2.5.1316.

**Comment by ErikEJ** [comment]
@CallumBateson @EXT1433S This is a bug in the latest release.

@EXT1433S The checkbox to install packages is calculated as required, but most likely degraded due to the DateOnly Bug.

**Comment by ErikEJ** [comment]
@EXT1433S do you have a date or time column in your database ?

**Comment by ErikEJ** [comment]
@EXT1433S I am unable to reproduce with .1338 - and your screenshot does not look like .1338 - suggest you restart / re-install

**Comment by EXT1433S** [comment]
Yes multiple.--Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 13.03.23, 15:49 schrieb Erik Ejlskov Jensen ***@***.***>:

   
  @EXT1433S do you have a date or time column in your database ?

**Comment by EXT1433S** [comment]
Thanks for looking into it. I will try a re-install and give you feedback tomorrow. --Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 13.03.23, 17:22 schrieb Erik Ejlskov Jensen ***@***.***>:

   
  @EXT1433S I am unable to reproduce with .1338 - and your screenshot does not look like .1338 - suggest you restart / re-install

**Comment by ErikEJ** [comment]
If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by EXT1433S** [comment]
Will do 👍--Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 13.03.23, 17:24 schrieb Erik Ejlskov Jensen ***@***.***>:

   
  If you like my free tools, I would be very grateful for a rating or review on Visual Studio Marketplace or even a one-time or monthly sponsorship

**Comment by ErikEJ** [comment]
@EXT1433S Great, thanks or the heads up!
