### ISSUE TITLE
Reverse Engineering Doesn't Respect Index Column Order Settings

### ISSUE THREAD

**Issue by SailorTurkey** [ErikEJ/EFCorePowerTools#174]
While reverse engineering from Database Index Order, And Included Columns gets mixed up.

### Steps to reproduce
Example Index T-SQL Script:

/****** Object:  Index [IX_ptsLPRSData_Station+Duration]    Script Date: 03/02/2019 01:49:42 ******/
CREATE NONCLUSTERED INDEX [IX_ptsLPRSData_Station+Duration] ON [dbo].[ptsLPRSData]
(
	[StationId] ASC,
	[Id] ASC
)
INCLUDE ( [Duration])

What EFCorePowerTools Generates:

 entity.HasIndex(e => new { e.Duration, e.Id, e.StationId })
.HasName("IX_ptsLPRSData_Station+Duration");

Expected Output:

entity.HasIndex(e => new { e.IstasyonId, e.Id })
.HasName("IX_ptsLPRSData_Station+Duration");
.ForSqlServerInclude("Duration");

FYI EfCorePowerTools doesnt respect neither index order (StationId THEN Id), nor included column specification (include Duration like a regular column)

### Further technical details
EF Core Power Tools version:  2.2.11.0

Database engine: SQL Server 2017

Visual Studio version: Visual Studio 2017 15.9.3

**Comment by ErikEJ** [comment]
Are you generating from a SSDT project or a live database?

**Comment by SailorTurkey** [comment]
Sorry for late reply, i am connecting to a live database, via "Choose Database Connection" dialog, then choosing tables to reverse engineer. Using options below. Handlebars are used for class creation, DbContext handlebar settings left untouched
![image](https://user-images.githubusercontent.com/32933607/52182983-717d3a00-2814-11e9-9b26-79b9b83c52cb.png)

**Comment by ErikEJ** [comment]
It looks to me like a EF Core bug - are you able to test with "Scaffold-DbContex" ?

**Comment by SailorTurkey** [comment]
Yes, confirmed with Scaffold-DbContext command. It produces the same (wrong) conversion

     entity.HasIndex(e => new { e.Duration, e.StationId, e.Id })
                    .HasName("IX_ptsLPRSData_Station+Duration");

**Comment by ErikEJ** [comment]
Thanks, in that case it is an EF Core bug, and you should report an issue here: https://github.com/aspnet/EntityFrameworkCore/issues/new
