### ISSUE TITLE
vs2022&ODBC test successful but no connection

### ISSUE THREAD

**Issue by gaozejie** [ErikEJ/EFCorePowerTools#1742]
Describe what is not working as expected.

### Provide steps to reproduce

1、add database connection
![1](https://user-images.githubusercontent.com/16096320/225205397-c053193d-4176-4bd9-bfef-9b7487faf340.png)

2、dataSource select Microsoft ODBC and create new dsn use DM8 ODBC DRIVER
![2](https://user-images.githubusercontent.com/16096320/225205945-d7d6ab59-b51c-4f55-bd8b-338f0e764fc6.png)

3、test successful
![3](https://user-images.githubusercontent.com/16096320/225205621-aa21fdec-b4f8-41f5-8124-97834b37b907.jpg)

4、but there is no connection
![4](https://user-images.githubusercontent.com/16096320/225206059-cd42cfc0-b1e1-479a-8d88-3e3f982b37cf.jpg)

### Provide technical details

- EF Core version in use: EF Core 6.0.14

- Is Handlebars used: no

- Is T4 used: no

- Is .dacpac used: no

- EF Core Power Tools version: 2.5.1338

- Database engine: DM8(china dameng)

- Visual Studio version: Visual Studio 2022

**Comment by ErikEJ** [comment]
Power Tools only supports a fixed set of drivers that have a corresponding EF Core Provider . This is not one. Is there an EF Core provider for this?

**Comment by gaozejie** [comment]
yes , i can use code first with their EF Core driver。I use Microsoft ODBC datasource with Power Tools ，the connection can be tested successfully，but i cannot select after saving .

**Comment by ErikEJ** [comment]
The driver needs to be added explicitly to EF Core Power Tools.

**Comment by ErikEJ** [comment]
Ir looks like the driver is only available for EF core 5 which is out of support
