### ISSUE TITLE
Unable to get result set shape for PROCEDURE

### ISSUE THREAD

**Issue by mseebruch** [ErikEJ/EFCorePowerTools#1744]
Hey, we're starting to use EF Core 7 with Database First. We have issues generating the code for our Procedures.
There seem to be two error in general. One is about invalid object names for temp tables and one is about converting varchar to int.

These procedures are working just fine when executing them with good old SQL-Commands from C#. What are we doing wrong?
Sorry for code-formatting, but either Git has trouble with code inside spoilers or I'm just too stupid.

<details> 
  <summary>
    Unable to get result set shape for PROCEDURE 'dbo.uspRef_getOrg'.
    Ungültiger Objektname "#poolsAndOrgs".
  </summary>
CREATE OR ALTER PROCEDURE [dbo].[uspRef_getOrg]
(
   @orgID				INT          = NULL
   ,@selectFullTree		BIT          = 0
   ,@orgIDParent		INT          = NULL
   ,@mandID				INT          = NULL
   ,@orgName			VARCHAR(200) = NULL
   ,@orgTag				VARCHAR(100) = NULL
   ,@orgCode			VARCHAR(20)  = NULL
   ,@poolID				INT			 = NULL
   ,@isHidden			BIT			 = NULL
   ,@currentUserID		INT
)
AS
BEGIN
	DECLARE
		@updatedByProcedureID INT
		,@userID INT = @currentUserID
		,@myObjectName VARCHAR(400) = OBJECT_NAME(@@PROCID)

	EXEC [Heimdall].[dbo].[uspRef_getUpdateProcedureID]
		@procedureName = @myObjectName
		,@currentUserID = @userID
		,@updateProcedureID = @updatedByProcedureID OUTPUT

	BEGIN TRY
		DECLARE
			@mandWithOrg BIT
			,@databaseName NVARCHAR(50)
			,@stmt NVARCHAR(max)

		SELECT @mandWithOrg = [Heimdall].[dbo].[fx_isMandWithOrg](@mandID, @currentUserID)

		SELECT @databaseName = databaseName
		FROM
			trfsDatabase db
		JOIN
			sync.trfsMand m
				ON db.databaseID = m.databaseID
		WHERE
			[mandID] = @mandID

		DROP TABLE IF EXISTS [#poolsAndOrgs]

		--SQL Prompt formatting off
		CREATE TABLE #poolsAndOrgs 
		( 
			poolID INT
			,orgID INT 
		)
		--SQL Prompt formatting on
		IF ( @poolID IS NOT NULL AND @mandID IS NOT NULL )
		BEGIN
			SET @stmt = '
		
			INSERT INTO #poolsAndOrgs (poolID, orgID)
			SELECT poolID, orgID
			FROM ' + @databaseName + '.dbo.trfxPoolOrg
			WHERE mandID = @pMandID
			AND poolID = @pPoolID
			'

			EXEC sp_executesql
				@stmt
				,N'@pMandID INT, @pPoolID INT'
				,@pMandID = @mandID
				,@pPoolID = @poolID
		END

		IF ( @selectFullTree = 0 OR @orgID IS NULL )
		BEGIN
			SELECT
				[o].[orgID]
				,[o].[orgIDParent]
				,[TO].[orgName] AS [orgParentName]
				,[o].[mandID]
				,[TM].[mandTag]
				,[o].[orgName]
				,[o].[orgTag]
				,[o].[orgCode]
				,[o].[isHidden]
			FROM
				[sync].[trfmOrg] AS [o]
			INNER JOIN
				[sync].[trfsMand] AS [TM]
					ON [o].[mandID] = [TM].[mandID]
			LEFT JOIN
				[sync].[trfmOrg] AS [TO]
					ON [o].[orgIDParent] = [TO].[orgID]
			WHERE
				( @orgID IS NULL OR [o].[orgID] = @orgID )
				AND ( @mandID IS NULL OR [o].[mandID] = @mandID )
				AND ( @orgName IS NULL OR [o].[orgName] LIKE @orgName )
				AND ( @orgTag IS NULL OR [o].[orgTag] LIKE @orgTag )
				AND ( @orgCode IS NULL OR [o].[orgCode] LIKE @orgCode )
				AND ( @orgIDParent IS NULL OR [o].[orgIDParent] = @orgIDParent )
				AND ( @isHidden IS NULL OR o.isHidden = @isHidden )
				AND
				(
					@mandWithOrg = 0
					OR [o].[orgID] IN ( SELECT [orgID] FROM [Heimdall].[dbo].[fx_getOrgIDsForUser](@currentUserID) AS [FGOIFU] )
				)
				AND ( @poolID IS NULL OR o.orgID IN ( SELECT orgID FROM #poolsAndOrgs ))
			ORDER BY
				[orgIDParent]
				,[orgTag]
		END
		ELSE IF ( @selectFullTree = 1 AND @orgID IS NOT NULL )
		BEGIN
			SELECT
				[orgID]
				,[orgIDParent]
				,[mandID]
				,[orgName]
				,[orgTag]
				,[orgCode]
				,[isHidden]
			FROM
				[dbo].[fxRef_GetOrgTree]([dbo].[fxRef_getOrgRoot](@orgID))
			WHERE
				@mandWithOrg = 0
				OR [orgID] IN ( SELECT [orgID] FROM [Heimdall].[dbo].[fx_getOrgIDsForUser](@currentUserID) AS [FGOIFU] )
			ORDER BY
				[orgIDParent]
				,[orgTag]
		END
	END TRY
	BEGIN CATCH
		DECLARE @errSeverity INT = ERROR_SEVERITY()
		DECLARE @errString NVARCHAR(MAX)

		SET @errString = ISNULL(ERROR_MESSAGE(), 'NULL') + CHAR(10) + CHAR(13) + 'in Zeile ' + CAST(ISNULL(ERROR_LINE(), 'NULL') AS VARCHAR(10)) + CHAR(10) + CHAR(13) + '' + ISNULL(ERROR_PROCEDURE(), ISNULL(OBJECT_NAME(@@PROCID), 'NULL'));

		RAISERROR(@errString, @errSeverity, 1)

		RETURN -1
	END CATCH

	RETURN 0
END
</details>

<details> 
  <summary>
  Unable to get result set shape for PROCEDURE 'dbo.uspRef_getOrgForUser'.
  Fehler beim Konvertieren des varchar-Werts "NULL" in den int-Datentyp.
  </summary>
USE Heimdall
GO

CREATE OR ALTER PROCEDURE [dbo].[uspRef_getOrgForUser]
	@userID INT
	,@currentUserID INT
AS
BEGIN
	DECLARE
		@updatedByProcedureID INT
		,@myObjectName VARCHAR(400) = OBJECT_NAME(@@procId);

	EXEC [uspRef_getUpdateProcedureID]
		@procedureName = @myObjectName
		,@currentUserID = @currentUserID
		,@updateProcedureID = @updatedByProcedureID OUTPUT;

	BEGIN TRY
		SELECT
			[TOU].[orgUserID] --(PK, int, not null)
			,[TOU].[orgID] --(int, not null)
			,[TOU].[userID] --(int, not null)
		FROM
			[dbo].[trfxOrgUser] AS [TOU]
		WHERE
			[TOU].[userID] = ISNULL(@userID, @currentUserID)
	END TRY
	BEGIN CATCH
		DECLARE @errSeverity INT = ERROR_SEVERITY()
		DECLARE @errString NVARCHAR(MAX)

		SET @errString = ISNULL(ERROR_MESSAGE(), 'NULL') + CHAR(10) + CHAR(13) + 'in Zeile ' + CAST(ISNULL(ERROR_LINE(), 'NULL') AS VARCHAR(10)) + CHAR(10) + CHAR(13) + '' + ISNULL(ERROR_PROCEDURE(), ISNULL(OBJECT_NAME(@@PROCID), 'NULL'));

		RAISERROR(@errString, @errSeverity, 1)

		RETURN -1
	END CATCH

	RETURN 0;
END
</details>

### Technical Details
- EF Core version in use: EF Core 7
- Is Handlebars used: Yes
- Is T4 used: No
- Is .dacpac used: No
- EF Core Power Tools version: 2.5.1293
- Database engine: SQL Server
- Visual Studio version: Visual Studio 2022

This issues appears either when using EF 6 or EF 7 for generation.

![image](https://user-images.githubusercontent.com/128034098/225570181-3f1d114c-4d41-4ed9-8da6-106e5b4943c9.png)

**Comment by ErikEJ** [comment]
@mseebruch Determining the result shape of a stored procedure is hard. 

I suggest you read the docs for the various options that are availble - let me know if using these fails.

https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#sql-server-stored-procedures

**Comment by ErikEJ** [comment]
If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by ghendric** [comment]
I have this issue as well and added a data contract to the stored proc but that didn't help since EF can work with that. Any suggestions that don't include rewriting the stored procedure?

**Comment by ErikEJ** [comment]
@ghendric Did you try the options described here? https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#sql-server-stored-procedures
