### ISSUE TITLE
Customized T4 Templates... how to create them?

### ISSUE THREAD

**Issue by dbarasch** [ErikEJ/EFCorePowerTools#1745]
This issue is more of a request for help, rather than a literal issue.  I understand that you can customize T4 templates, specifically the DbContext.t4 and EntityType.t4 files, or by adding your own within a .../CodeTemplates/EFCore folder.

I figure it would make no sense to customize the provided EntityType or DbContext templates since these can be overwritten by a release.  If I am wrong, please let me know.

So I figure Ill add a new t4 file within a Codetemplate/EFCore folder structure.  Easy enough.  I added a new InterfaceType.t4 to generate interfaces for my entities.  But just to test, I added a simple text "TEST" to the file.

![File1](https://user-images.githubusercontent.com/52629301/226186296-881e82c5-18bf-48fe-a7c2-b8d4c8e831eb.png)

So I go to regenerate the entities using the refresh command, and it generated files with generated code, which was not was I was expecting.  I was expecting a separate generated file, each with "TEST" as I had entered in the template.

![File2](https://user-images.githubusercontent.com/52629301/226186504-f514811b-0965-4785-86c5-11509a7df7ce.png)

So where do I go from here?  There is no documentation of "hooking" into the process and generating custom files.

Should I modify the DbContext or Entitytype T4 files?
What happens when there is an update, how do I preserve my customizations?

**Comment by ErikEJ** [comment]
>> since these can be overwritten by a release. If I am wrong, please let me know. 

You are wrong, they are part of your source code (which if course is under source control)

Unless you explicitly choose to replace them with a newer version they will remain.

Only the two files named DbContext.t4 and EntityType.t4 are processed by the EF Core tooling.

Maybe you will find [my dotnetconf presentation](https://learn.microsoft.com/en-us/events/dotnetconf-2022/t4-goodness-with-entity-framework-core-7) useful?

**Comment by ErikEJ** [comment]
@dbarasch Let me know if you need more help,

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
