### ISSUE TITLE
Compare .NET 7 support ? 

### ISSUE THREAD

**Issue by Montago** [ErikEJ/EFCorePowerTools#1746]
I'm missing .NET 7 support. 

EF Core PowerTools complain that i need Core 3.0+ when trying to reverse engineer a DB in a .NET 7 project.

**Comment by ErikEJ** [comment]
That sounds wrong. EF Core 7 is supported.

Which extension version?

Your csproj file?

The exact error message?

**Comment by Montago** [comment]
thanks for the quick reply, yes im doing a "compare db with dbcontext" 

![image](https://user-images.githubusercontent.com/456040/226613964-2b2abe36-70d8-4da2-9c36-d887cc1e961c.png)

a little context: 

I reverse engineered the DB some time ago. 
But now when doing BulkDelete / BulkInsert using EF Core Bulk Extensions, im getting an error that 
"CREATE TABLE permission denied in database 'Daekbranchen'."

Which is quite odd considering that i dont have any migrations for this Context and that all tables are in place. 

it's true that the user context doesnt have Create Table authorization - so im wondering why it needs it....

**Comment by ErikEJ** [comment]
I have improved the message - sounds like you did not really need the feature, but were grasping for straws?

**Comment by Montago** [comment]
Thanks for the help - yes i didn't need the feature at this point in time. I sounds nice though :D 

and yes, i needed something to point me in the right direction :)

**Comment by ErikEJ** [comment]
If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by ErikEJ** [comment]
Suddenly realized why it is not implemented - the EfCompare package requires .NET 7.0 and EF Core 7.0 runs fine under .NET 6

@jpsmith thoughts

**Comment by JonPSmith** [comment]
Hi @ErikEJ,

I decided to release for the EfCore.SchemaCompare package for each .NET version. That's different from what I do with my other NuGet packages where I use multiple frameworks.

The reason of why I have version-per-.NET is because I want to see if the new EF Core version solves some limitations in the package, e.g. Table-per-Type or Table-per-Class classes. So far I haven't found any metadata that solves this.

PS. I'm retired now (yes, I am old) but I am still working on my open-source projects.

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.
