### ISSUE TITLE
Reverse engineering with functions only

### ISSUE THREAD

**Issue by geraldhe** [ErikEJ/EFCorePowerTools#1748]
I can't do reverse engineering if there is only a function available. I can select the function, but the "OK"-button stays grayed out:
![image](https://user-images.githubusercontent.com/6449016/226901036-0c40b386-47c9-4663-9c44-985cb7a0fd94.png)

If there is a additional view/table available (and selected!), the OK button is clickable - and everything works.

### Provide steps to reproduce

Use a database, where the user is only allowed to access a function (no table, view, ...) - or a database with only functions.

### Provide technical details

- EF Core version in use: EF Core 7

- Is Handlebars used: no

- Is T4 used: no

- Is .dacpac used: no

- EF Core Power Tools version: 2.5.1338

- Database engine: SQL Server

- Visual Studio version: Visual Studio 2022

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by geraldhe** [comment]
Yes, it works now 👍 Thanks for the fix!
