### ISSUE TITLE
Adding [Obsolete] attribute on some table columns.

### ISSUE THREAD

**Issue by muhlisatac** [ErikEJ/EFCorePowerTools#1750]
Hi
I want to add [Obsolete] attribute on some table columns. Is there a pre-built way? 
If not, is it possible to add a feature like if i add 'Obsolete' text on database table column description or add an extended property then generated table column has [Obsolete] attribute?

**Comment by ErikEJ** [comment]
You can do that with the t4 templates:

Modify EntityType.t4, line 79:

```csharp
        if (!string.IsNullOrEmpty(property.GetComment()))
        {
#>
    /// <summary>
    /// <#= code.XmlComment(property.GetComment(), indent: 1) #>
    /// </summary>
<#
            if (property.GetComment() == "Obsolete")
            {
#>
    [Obsolete]
<#            
            }
        }
```

Result:

```csharp
public partial class Category
{
    public int CategoryId { get; set; }

    /// <summary>
    /// Obsolete
    /// </summary>
    [Obsolete]
    public string? Description { get; set; }
}


```

**Comment by ErikEJ** [comment]
If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by muhlisatac** [comment]
Ty very much. Will try it soon.
