### ISSUE TITLE
Create cross platform dotnet global tool

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#1751]
Why? EF Core Power Tools reverse engineering at this point includes an abundance of features that are unavailable or hard to achieve with the default command line tooling, and providing these features on other platforms is requested by a number of users.

Additional features include: 
- stored procedure and functions mapping (for Azure SQL / SQL Server)
- advanced stored procedure result set discovery options
- use EF 6 classic pluralizer
- customize Humanizer pluralizer (exclude words)
- drop T4 templates
- warn if t4 templates are old
- remove obsolete files
- treat bool default values more like users expect
- split DbContext into EntityConfiguration classes
- enable type mappings (spatial, hierarchyid, DateOnly, TimeOnly, NodaTime)
- rename table and column names
- provide instructions on packages to install and DI configuration

**Syntax**

`efcpt "<connection string/.dacpac path>" <provider name/abbreviation>`

**Examples**

`efcpt "server=.;database=Chinook" Microsoft.EntityFrameworkCore.SqlServer`

`efcpt "server=.;database=Chinook" mssql`

`efcpt "/mydatabase.dacpac" mssql`

**Must haves**

- [x] Create initial net6.0 tool project supporting EF Core 7
- [x] package name: `ErikEJ.EFCorePowerTools.Cli`, tool name; efcpt
- [x] Use https://www.nuget.org/packages/CommandLineParser/ 
- [x] use new config file format, create class and serialization (see below) in RevEng.Common
- [x] add mapping of provider names and aliases
- [x] add mapper to internal options format - also merge with existing epft.renaming.json file in RevEng.Common
- [x] Auto create config file on first run with good defaults if it does not exist
- [x] propose useful default DbContext name
- [x] help with samples (using command line help features)
- [x] Improve output (Spectre.Console)
- [x] versioning and publishing to NuGet (will do manually initially)
- [x] Update objects list on each run (and preserve "exclude" and sproc options)
- [x] Show instructions for DI config and package install after running
- [x] compose and drop "readme"
- [x] add package readme
- [x] Use json schema for config file - located in repo
- [x] include and drop t4 templates if opted in
- [x] obsolete template warning

**After preview 1** (to be ported/refactored from VS extension)

- [x] Support EF Core 6/8 - explicit older/newer version of tool

**TBD**

- [x] banner? (Using Figgle perhaps?)
- [x] enable wildcard object filtering

**Unsupported features** (currently)

- navigation renaming
- column exclusions
- schema filter
- merging of .dacpacs
- default .dacpac schema

@bricelam @ajcvickers FYI

**Comment by ErikEJ** [comment]
adresses #1723 #1668 #1606 #1566 #1516 #1280 #1150 #996 #532 #469 #409 #340

**Comment by ErikEJ** [comment]
{
  "$schema": "https://github.com/tbd",
  "tables": [
      {
         "name": "[dbo].[Categories]"
      },
      {
         "name": "[dbo].[CustomerCustomerDemo]"
      }
  ],
  "modules": [
      {
         "name": "[dbo].[Alphabetical list of products]"
      },
      {
         "name": "[dbo].[Category Sales for 1997]"
      }
  ],
  "functions": [
      {
         "name": "[dbo].[FunctionA]"
      },
      {
         "name": "[dbo].[FunctionB]"
      }
  ],
  "code-generation":
  { }
}

{
   "CodeGenerationMode": 3,
   "ContextClassName": "NorthwindContext",
   "ContextNamespace": null,
   "DefaultDacpacSchema": null,
   "FilterSchemas": false,
   "IncludeConnectionString": true,
   "ModelNamespace": null,
   "OutputContextPath": null,
   "OutputPath": "Models",
   "PreserveCasingWithRegex": true,
   "ProjectRootNamespace": "Ef7Playground",
   "Schemas": null,
   "SelectedHandlebarsLanguage": 2,
   "SelectedToBeGenerated": 0,
   "Tables": [
      {
         "Name": "[dbo].[__MigrationHistory]",
         "ObjectType": 0
      },
      {
         "Name": "[dbo].[Categories]",
         "ObjectType": 0
      },
      {
         "Name": "[dbo].[CustomerCustomerDemo]",
         "ObjectType": 0
      },
      {
         "Name": "[dbo].[CustomerDemographics]",
         "ObjectType": 0
      },
      {
         "Name": "[dbo].[Customers]",
         "ObjectType": 0
      },
      {
         "Name": "[dbo].[Employees]",
         "ObjectType": 0
      },
      {
         "Name": "[dbo].[EmployeeTerritories]",
         "ObjectType": 0
      },
      {
         "Name": "[dbo].[Order Details]",
         "ObjectType": 0
      },
      {
         "Name": "[dbo].[Orders]",
         "ObjectType": 0
      },
      {
         "Name": "[dbo].[Person]",
         "ObjectType": 0
      },
      {
         "Name": "[dbo].[Products]",
         "ObjectType": 0
      },
      {
         "Name": "[dbo].[Region]",
         "ObjectType": 0
      },
      {
         "Name": "[dbo].[Shippers]",
         "ObjectType": 0
      },
      {
         "Name": "[dbo].[Specials]",
         "ObjectType": 0
      },
      {
         "Name": "[dbo].[StringSplitResults]",
         "ObjectType": 0
      },
      {
         "Name": "[dbo].[Suppliers]",
         "ObjectType": 0
      },
      {
         "Name": "[dbo].[Territories]",
         "ObjectType": 0
      },
      {
         "Name": "[dbo].[Alphabetical list of products]",
         "ObjectType": 3
      },
      {
         "Name": "[dbo].[Category Sales for 1997]",
         "ObjectType": 3
      },
      {
         "Name": "[dbo].[Current Product List]",
         "ObjectType": 3
      },
      {
         "Name": "[dbo].[Customer and Suppliers by City]",
         "ObjectType": 3
      },
      {
         "Name": "[dbo].[Invoices]",
         "ObjectType": 3
      },
      {
         "Name": "[dbo].[Order Details Extended]",
         "ObjectType": 3
      },
      {
         "Name": "[dbo].[Order Subtotals]",
         "ObjectType": 3
      },
      {
         "Name": "[dbo].[Orders Qry]",
         "ObjectType": 3
      },
      {
         "Name": "[dbo].[Product Sales for 1997]",
         "ObjectType": 3
      },
      {
         "Name": "[dbo].[Products Above Average Price]",
         "ObjectType": 3
      },
      {
         "Name": "[dbo].[Products by Category]",
         "ObjectType": 3
      },
      {
         "Name": "[dbo].[Quarterly Orders]",
         "ObjectType": 3
      },
      {
         "Name": "[dbo].[Sales by Category]",
         "ObjectType": 3
      },
      {
         "Name": "[dbo].[Sales Totals by Amount]",
         "ObjectType": 3
      },
      {
         "Name": "[dbo].[Summary of Sales by Quarter]",
         "ObjectType": 3
      },
      {
         "Name": "[dbo].[Summary of Sales by Year]",
         "ObjectType": 3
      },
      {
         "Name": "[dbo].[CustOrderHist]",
         "ObjectType": 1
      },
      {
         "Name": "[dbo].[CustOrdersDetail]",
         "ObjectType": 1
      },
      {
         "Name": "[dbo].[CustOrdersOrders]",
         "ObjectType": 1
      },
      {
         "Name": "[dbo].[Employee Sales by Country]",
         "ObjectType": 1
      },
      {
         "Name": "[dbo].[MultiSet]",
         "ObjectType": 1
      },
      {
         "Name": "[dbo].[OutputScenarios]",
         "ObjectType": 1
      },
      {
         "Name": "[dbo].[Sales by Year]",
         "ObjectType": 1
      },
      {
         "Name": "[dbo].[SalesByCategory]",
         "ObjectType": 1
      },
      {
         "Name": "[dbo].[SpecialTypes]",
         "ObjectType": 1
      },
      {
         "Name": "[dbo].[Ten Most Expensive Products]",
         "ObjectType": 1
      },
      {
         "Name": "[dbo].[FuncWithTvpParameter]",
         "ObjectType": 2
      },
      {
         "Name": "[dbo].[ISOweek]",
         "ObjectType": 2
      },
      {
         "Name": "[dbo].[tvp]",
         "ObjectType": 2
      }
   ],
   "UiHint": "DG-PF2WPPLD\\SQLEXPRESS.Northwind",
   "UncountableWords": [
      "Status",
      "Data"
   ],
   "UseBoolPropertiesWithoutDefaultSql": false,
   "UseDatabaseNames": false,
   "UseDateOnlyTimeOnly": true,
   "UseDbContextSplitting": false,
   "UseFluentApiOnly": true,
   "UseHandleBars": false,
   "UseHierarchyId": true,
   "UseInflector": true,
   "UseLegacyPluralizer": false,
   "UseManyToManyEntity": false,
   "UseNoDefaultConstructor": false,
   "UseNoObjectFilter": false,
   "UseNodaTime": false,
   "UseNullableReferences": true,
   "UseSchemaFolders": false,
   "UseSpatial": true,
   "UseT4": true
}

**Comment by karenpayneoregon** [comment]
I think support should be only support EF Core 6 and 7

**Comment by ErikEJ** [comment]
@karenpayneoregon you mean also EF Core 6?

**Comment by MisinformedDNA** [comment]
I'm not necessarily opposed to a new config file, but I'm curious as to your reasoning. Doesn't that create a lot of extra work? Do you envision the UI supporting the new config format in the future?

**Comment by ErikEJ** [comment]
@MisinformedDNA great feedback. 

The existing format is quite flat and has some quirky names. 

Yes, someone could create a ui on top, but I also plan to publish a json schema to help the basic editing experience in for example VS code.

**Comment by ErikEJ** [comment]
Also, there are some unique challenges in terms of refreshing the object list, that does not match the current format.

**Comment by CZEMacLeod** [comment]
@ErikEJ My only comment on the config format just now is it might be nice to make the name for tables etc. support regex or some sort of wildcard, and a mechanism to overwrite/redefine a table.
```json
  "tables": [
      {
         "regex": "\\[dbo\\]\\.\\[.*\\]"
      },
      {
         "regex": "\\[dbo\\]\\.\\[Old.*\\]",
         "exclude": true
      }
  ],
```
Maybe the escaped regex format isn't the best idea, but you get my meaning.
```json
  "tables": [
      {
         "wildcard": "[dbo].[*]"
      },
      {
         "wildcard": "[dbo].[Old*]"
         "exclude": true
      }
  ],
```

**Comment by ErikEJ** [comment]
@CZEMacLeod thanks for the idea.

I currently plan to update the object list on each run, and add/remove objects based on the current state of the source database. Unsure how that would play with your suggestion. Could potentially be a future improvement perhaps?

**Comment by CZEMacLeod** [comment]
@ErikEJ I think this can work together - Add any objects that do not match an existing entry (wildcard or otherwise).
Remove any objects that do not match any entry - this could remove my example of `"wildcard": "[dbo].[Old*]"` when there are no more `Old*` tables under dbo or perhaps for a `wildcard` or `regex` type entry, just issue warning that it matched no items.
Certainly, it could be a future improvement, but I feel that it is often the case that you would group stuff either by schema, prefix or otherwise in the name.
I certainly would have something like
```json
{
  "wildcard": "*_OLD"
  "exclude": true
},
{
  "wildcard": "*_BACKUP"
  "exclude": true
}
```
in my configuration.

**Comment by ErikEJ** [comment]
@CZEMacLeod Excellent suggestion, I will add it to the list!

**Comment by ErikEJ** [comment]
@CZEMacLeod 

What do you mean by "and a mechanism to overwrite/redefine a table." ?

**Comment by CZEMacLeod** [comment]
@ErikEJ Simply that it doesn't stop at the first match.
```json
  "tables": [
      {
         "wildcard": "[dbo].*",
	 "exclude": false
      },
      {
         "wildcard": "[dbo].Old*",
	 "exclude": true
      },
      {
         "name": "[dbo].[Oldtable]",
         "exclude": false
      }
  ],
  "stored-procedures": [
      {
         "wildcard": "[dbo].Category*",
	 "mapped-type": "Category"
      },
      {
         "wildcard": "[dbo].*_Legacy",
         "use-legacy-resultset-discovery": true,
      },
	  {
         "name": "[dbo].[Category_Sales_By_Customer_Legacy]",
         "mapped-type": "Customer"
      }
   ],
```
Such that `dbo.oldtable` is first included, then excluded, then overwritten again as include.
Also, the mapped-type for `[dbo].[Category_Sales_By_Customer_Legacy]` is first set to `Category` then overwritten as `Customer`.
And `Category_Sales_By_Customer_Legacy` has the `use-legacy-resultset-discovery` property set to true also.

**Comment by ErikEJ** [comment]
@CZEMacLeod  Interesting.

So the initial config could be something like


     { "wildcard": "*", 	 "exclude": false },

**Comment by CZEMacLeod** [comment]
@ErikEJ Technically yes - although I think the idea of adding any entries not matching to the list helps manage things. Once you have added your specific wildcards (and removed the explicit named entries) you would not expect to see any changes/warnings when you run the tool. If you start with just include everything in the config, you don't get that ability to see what has changed/fallen outside expected parameters.
However, for 'simple' operation, then yes, the default template could use that as the config. I guess it would depend on the user level, and how much control/visibility you want over the operation.

**Comment by ErikEJ** [comment]
@CZEMacLeod I think explicitly listing all current objects on each invocation of the tool would make most sense, and then any filters and exclusions would apply in order during code generation. 

Thoughts?

**Comment by CZEMacLeod** [comment]
@ErikEJ Sounds good. I think it will become more apparent when the tool is in use and you get feedback from users, but I think we are aligned on the feature anyway.

**Comment by ErikEJ** [comment]
@CZEMacLeod I think one of the biggest challenges of this tool is how to provide a good UX for ongoing object additions/removals. And some sort of filtrering can certainly help here.

**Comment by MisinformedDNA** [comment]
What are you envisioning for the UI? VS plugin (new or reuse existing)? VS Code or Azure Data Studio extensions? Stand-alone app?

Our are you envisioning a pure CLI UI like the .NET Upgrade Assistant?

**Comment by ErikEJ** [comment]
>> What are you envisioning for the UI?

Nothing currently, that is not the point of this issue. But if someone in the community can contribute a UI on top of this in VS Code, that would be great. But again, out of scope for this effort.

**Comment by ErikEJ** [comment]
Preview 1 of the CLI tool is [now available](https://www.nuget.org/packages/ErikEJ.EFCorePowerTools.Cli/7.0.0-preview1#readme-body-tab)

![image](https://user-images.githubusercontent.com/4169187/234258058-2b6def58-f87c-455a-93da-21cd09d9e3f7.png)

**Comment by biiiipy** [comment]
Took it for a spin and from the generated code, it looks good, but I haven't done any unit/regression tests on it yet.
On thing though - please don't regenerate `efcpt-readme.md` file on each run, on the first run (when efcpt-config.json gets generated) is enough :) . Although, at least for me, it would be enough to just output a link to the documentation in this repo and put that same content here (I don't think it provides that much of a value to generate actual connection string example based on the generation context)

**Comment by biiiipy** [comment]
Also, it would be great if this tool was also available as a simple nuget package, and not as a DotnetTool. Then we could include them ir our own cmd tools, workflows without separate installation.

**Comment by ErikEJ** [comment]
@biiiipy it is a one liner to install- but please create a new issue if you think it will add value

**Comment by Eternal21** [comment]
Great.  I can finally uninstall Visual Studio and move completely to JetBrains.

**Comment by ErikEJ** [comment]
@biiiipy building a standalone tool would require me to build lsrge binaries for all platforms with no mechanism for updates  so it is not something I plan to do

**Comment by ErikEJ** [comment]
@Eternal21 OK. Which feature in Power Tools do you use that are not part of the builtin tool?

**Comment by Eternal21** [comment]
@ErikEJ I was just using Reverse Engineer functionality: https://github.com/ErikEJ/EFCorePowerTools/issues/996

**Comment by antonio1612** [comment]
Hello is the migrations tool available on the cli?

**Comment by ErikEJ** [comment]
@antonio1612 no.  Why do you need it? Just use dotnet ef

**Comment by antonio1612** [comment]
> ef

Thank you so much, I'm new to .Net and didn't knew that you could do that, thank you

**Comment by ErikEJ** [comment]
@antonio1612 Welcome to .NET - I recommend referring to the docs https://learn.microsoft.com/en-us/ef/core/cli/
