### ISSUE TITLE
Subscription to ChangeTracker.StateChanged events

### ISSUE THREAD

**Issue by nikriaz** [ErikEJ/EFCorePowerTools#1753]
Can you please advise how to subscribe to ChangeTracker.StateChanged events but keep reverse engineering automatic-generated DbContext file intact?

This works in the original file:
```
public partial class MyContext : DbContext
{
    public MyContext(DbContextOptions<MyContext> options)
        : base(options)
    {
        ChangeTracker.StateChanged += OnEntityStateChanged;
    }
```

This doesn't work in a separate file:
```
public partial class MyContext
{
    public MyContext() : base()
    {
        ChangeTracker.StateChanged += OnEntityStateChanged;
    }
```

Or maybe you can advise a way how to subscribe to events outside from default DbContext constructor. So little information how to use it, and most SO posts suggest to put subscription into default constructor.

**Comment by ErikEJ** [comment]
Which EF Core version?

**Comment by ErikEJ** [comment]
Then you can use the t4 template to modify the constructor

**Comment by nikriaz** [comment]
Great, I'll try. I completely forgot about this option. Thank you.

**Comment by ErikEJ** [comment]
Cool, let me know if you need additional advice
