### ISSUE TITLE
Wrong EF Core Version option selected if Project targets Net 8.0 (preview2)

### ISSUE THREAD

**Issue by KayakFisher205** [ErikEJ/EFCorePowerTools#1754]
When the Project is setup as Net 8.0, running Edit against a efpt.config.json file, the Drop down for 'Choose Your EF Core version' only lists EF Core 3. Changing the project back to Net 7.0, the list contains 6 and 7. Did noticed it will also change the CodeGenerationMode from 3 to 1 if I use the tool on the database.

For now, I've switched this project back to 7.0.

I suspect you haven't started net 8.0 yet

- EF Core version in use: (e.g. EF Core 7) Version 2.5.1358

- Is Handlebars used: no

- Is T4 used: no

- Is .dacpac used: no

- Database engine: (SQL Server)

- Visual Studio version: Visual Studio 2022 (Version 17.6.0 Preview 2.0)

**Comment by ErikEJ** [comment]
Did you want to use EF Core 7 in a .NET 8 project?

**Comment by KayakFisher205** [comment]
yes, I was just looking to do the reverse engineering and update some tables. I was thinking if it just kept the dropdown for 6 and 7 thats perfect for now.

**Comment by ErikEJ** [comment]
Sure, I will fix that.

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

**Comment by KayakFisher205** [comment]
Looks good.

**Comment by ErikEJ** [comment]
Thanks gor the heads up.
