### ISSUE TITLE
Postgresql

### ISSUE THREAD

**Issue by duanegarman** [ErikEJ/EFCorePowerTools#1755]
In a previous version of the power tools (2.5.1296), I could create connections to postgresql database by creating a custom connection by pasting in a connection string.  In this newest version of EF Core Power Tools, it forces selection of a DB connection type (Azure SQL DB, Firebird, MySQL) which prevents me from being able to scaffold from my Postgresql DB.  Is there another way to build a custom connection to a DB without using one of these DB connection types or add a new connection type to the list for Postgres?  The syntax for the connection string I use is:

Server=aaa;Port=####;Database=bbb;User Id=ccc;Password=ddd;

EF Core 7.0.0
EF Core Power Tools - 2.5.1338
.dacpac used - no
Database engine - postgres
Visual Studio Enterprise 2022 Version 17.5.0

**Comment by duanegarman** [comment]
I was also trying to find the older version 2.5.1296 so I could downgrade, but cannot find it anywhere.  If it still exists somewhere, can someone please point me in the direction to find it?

**Comment by ErikEJ** [comment]
Look at the wiki pls. You just need to install EF Core Power Pack and use the DDEX provider via standard Server Explorer connection

**Comment by duanegarman** [comment]
Thank you Erik!!

**Comment by ErikEJ** [comment]
@duanegarman You are very welcome.

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
