### ISSUE TITLE
Code indentation got worse

### ISSUE THREAD

**Issue by MisinformedDNA** [ErikEJ/EFCorePowerTools#1757]
The `DbContext` file now uses file-scoped namespaces, which leaves some of the code indented too far:

```csharp
namespace SomeNamespace;

public partial class SomeContext : DbContext
{
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
            modelBuilder.ApplyConfiguration(new Configurations.UserConfiguration());

        OnModelCreatingPartial(modelBuilder);
    }
}
```

In the configuration files, it looks like it expects a file-scoped namespaces and the code isn't indented far enough:

```csharp
namespace SomeNamespace
{
    public partial class UserConfiguration : IEntityTypeConfiguration<User>
    {
        public void Configure(EntityTypeBuilder<User> entity)
        {
            entity.Property(e => e.Department)
            .HasMaxLength(50)
            .IsUnicode(false);
        }
    }
}
```

### Provide technical details

- EF Core version in use: EF Core 7

- Is Handlebars used: no

- Is T4 used: no

- Is .dacpac used: no

- EF Core Power Tools version: 2.5.1219.0

- Database engine: SQL Server

- Visual Studio version: Visual Studio 2022

**Comment by ErikEJ** [comment]
I assume you are using the experimental configuration splitting feature? 

This will eventually be replaced with a t4 based supported implementation.

**Comment by MisinformedDNA** [comment]
OK thanks.

**Comment by ErikEJ** [comment]
Feel free to submit a PR to fix this..

**Comment by MisinformedDNA** [comment]
If it's going to be replaced, then I'll just wait.
