### ISSUE TITLE
Reverse engineering with Firebird

### ISSUE THREAD

**Issue by tarsisff** [ErikEJ/EFCorePowerTools#1758]
It doesn't map/convert the firebird's type BigInt. It ignores the field and if it is a primary key, doesn't generate the class at all.

**Comment by ErikEJ** [comment]
Sounds like a Firebird provider issue, @cincuranet can maybe help?

**Comment by cincuranet** [comment]
@tarsisff Can you show me a repro?

**Comment by tarsisff** [comment]
Sure, here it goes

In PowerToolsReadMe.md

Some issues were discovered during reverse engineering, consider addressing them:
Could not find type mapping for column 'CIDADES.ID_GAFNET' with data type 'BIGINT '. Skipping column.
Could not find type mapping for column 'CLIENTES.ID_PAIS' with data type 'BIGINT '. Skipping column.
Could not find type mapping for column 'CLIENTES.ID_TIPOCLIENTE' with data type 'BIGINT '. Skipping column.
Could not find type mapping for column 'CLIENTES.ID_GAFNET' with data type 'BIGINT '. Skipping column.
Unable to scaffold the index 'FK_CLIENTESID_PAIS'. The following columns could not be scaffolded: ID_PAIS.
Unable to scaffold the index 'FK_CLIENTETIPOCLIENTE'. The following columns could not be scaffolded: ID_TIPOCLIENTE.
Could not find type mapping for column 'COMISSOES.CONTADOR' with data type 'BIGINT '. Skipping column.
Could not find type mapping for column 'COMISSOES.ID_ITEMRECEBER' with data type 'BIGINT '. Skipping column.
Could not find type mapping for column 'COMISSOES.ID_GAFNET' with data type 'BIGINT '. Skipping column.
Could not scaffold the primary key for 'COMISSOES'. The following columns in the primary key could not be scaffolded: CONTADOR.
Unable to generate entity type for table 'COMISSOES' since its primary key could not be scaffolded.

In the context file

// Unable to generate entity type for table 'COMISSOES' since its primary key could not be scaffolded. Please see the warning messages.
        // Unable to generate entity type for table 'FIXOS' since its primary key could not be scaffolded. Please see the warning messages.
        // Unable to generate entity type for table 'INVENTARIO' since its primary key could not be scaffolded. Please see the warning messages.
        // Unable to generate entity type for table 'ITEMCOMP' since its primary key could not be scaffolded. Please see the warning messages.
        // Unable to generate entity type for table 'ITEMNF' since its primary key could not be scaffolded. Please see the warning messages.
        // Unable to generate entity type for table 'NOTASESTORNADAS' since its primary key could not be scaffolded. Please see the warning messages.
        // Unable to generate entity type for table 'NOTASFISCAISRETORNO' since its primary key could not be scaffolded. Please see the warning messages.

I'm using Firebird 2.5


________________________________
De: Jiri Cincura ↹ ***@***.***>
Enviado: quarta-feira, 5 de abril de 2023 04:06
Para: ErikEJ/EFCorePowerTools ***@***.***>
Cc: tarsisff ***@***.***>; Mention ***@***.***>
Assunto: Re: [ErikEJ/EFCorePowerTools] Reverse engineering with Firebird (Issue #1758)


@tarsisff<https://github.com/tarsisff> Can you show me a repro?

**Comment by ErikEJ** [comment]
@tarsisff a Create table script would be helpful.

**Comment by tarsisff** [comment]
OK, there it goes

CREATE TABLE INVENTARIO (
    CONTADOR            NUMEROSEQUENCIAL NOT NULL /* NUMEROSEQUENCIAL = BIGINT DEFAULT 0 NOT NULL */,
    DATA                DATE NOT NULL,
    ID_PRODUTO          NUMEROSEQUENCIAL /* NUMEROSEQUENCIAL = BIGINT DEFAULT 0 NOT NULL */,
    CUSTOMEDIO          CUSTOPRODUTO /* CUSTOPRODUTO = NUMERIC(18,7) DEFAULT 0 NOT NULL */,
    QTDESTOQUE          QTDPRODUTO /* QTDPRODUTO = NUMERIC(18,7) DEFAULT 0 NOT NULL */,
    SINCRONIZADOGAFNET  CHAR(1) DEFAULT 0,
    ID_GAFNET           BIGINT
);
________________________________
De: Erik Ejlskov Jensen ***@***.***>
Enviado: sexta-feira, 7 de abril de 2023 09:44
Para: ErikEJ/EFCorePowerTools ***@***.***>
Cc: tarsisff ***@***.***>; Mention ***@***.***>
Assunto: Re: [ErikEJ/EFCorePowerTools] Reverse engineering with Firebird (Issue #1758)


@tarsisff<https://github.com/tarsisff> a Create table script would be helpful.

**Comment by tarsisff** [comment]
The problem is with the fields that  uaresing that domain

CREATE DOMAIN NUMEROSEQUENCIAL AS
BIGINT
DEFAULT 0
NOT NULL;
________________________________
De: Erik Ejlskov Jensen ***@***.***>
Enviado: sexta-feira, 7 de abril de 2023 09:44
Para: ErikEJ/EFCorePowerTools ***@***.***>
Cc: tarsisff ***@***.***>; Mention ***@***.***>
Assunto: Re: [ErikEJ/EFCorePowerTools] Reverse engineering with Firebird (Issue #1758)


@tarsisff<https://github.com/tarsisff> a Create table script would be helpful.

**Comment by ErikEJ** [comment]
Seems like you should report this issue here: https://github.com/FirebirdSQL/NETProvider
