### ISSUE TITLE
Version / release history document

### ISSUE THREAD

**Issue by csatnic-av** [ErikEJ/EFCorePowerTools#176]
Thank you very much @ErikEJ for the work you put in supporting this great tool.

I have a question / suggestion ... if this already exists please let me know where to find it as I wasn't able to: would you consider creating a version / release history document to highlight what was included in a particular release version of the tool? 

Sure - we can always look at commit logs but even there it's not clear what commits are included in what version ... and even more - not everybody can fully understand the intricacies for all the code complexities that are included in a particular commit.

I think it would be beneficial to have a release history document where you highlight changes made in a particular release version for the tool.

It looks like github has support for this kind of info but there is nothing on that page:

https://github.com/ErikEJ/EFCorePowerTools/releases

Here's an example of one such release history page:

https://github.com/gitextensions/gitextensions/releases/

Thank you.

**Comment by ErikEJ** [comment]
Great suggestion, it has simply been an matter of priorities given my limited, unpaid time. I will create a wiki page with details about updates and fixes the next time I release a daily build to VS Marketplace.

**Comment by ErikEJ** [comment]
Done
