### ISSUE TITLE
Change name of DBSet during Reverse Engineering

### ISSUE THREAD

**Issue by dvdeynden** [ErikEJ/EFCorePowerTools#1760]
I am trying to reverse engineer a database with table names that are rather _technical_  and have a _readable_ portion in Dutch (and this has remain like that). With the rename feature I can make sure that the generated entity classes have good and readable names and that these are kept for eventual future re-reverse engineering of the same database. 

So far so good ... but the names of the generated DBSets are the same as the entity names, where one would expect the plural of these entity names. I have tried  'pluralize or singularize' but that obviously doesn't work well with non-english languages, I also had a look at Handlebars and T4 customization but I have not found an easy way to influence the  `{{set-property-name}}` or the `entityType.GetDbSetName()`  

I can of course change/replace each DBSet name but that means I have to do it all over when the db is re-reverse engineered.

### Suggestion: 
When selecting and editing the objects in the _Choose Your Database Objects_ dialog, show an advanced renaming dialog (only with F2?) where one can not only enter the `NewName` but also a `NewNamePlural` and adapt the corresponding classes accordingly. The `NewNamePlural` can then be used for the DBSet name and eventualy also for NavigationProperties that reference a collection of entities. 

### To reproduce
`CREATE TABLE [dbo].[RT_Landcodes] ( ...`

and in the _efpt.renaming.json_ file, make sure you have

```
            "Columns": [ ],
            "Name": "RT_Landcodes",
            "NewName": "Land"
```
this will result in a generated _dbcontext.cs_  file with :
`public virtual DbSet<Land> Land { get; set; }`   

where I would like to have 
`public virtual DbSet<Land> Landen { get; set; }`     <--- Landen is the plural of Land

### Technical details

- EF Core version in use: **EF Core 7**

- Is Handlebars used: **no**

- Is T4 used: **no**

- Is .dacpac used: **no**

- EF Core Power Tools version: **Version 2.5.1338**

- Database engine: **SQL Server**

- Visual Studio version: **Visual Studio 2022**

**Comment by ErikEJ** [comment]
Settings DbSet names via renaming wont work - it is more complex than that.

Have you tried the property renaming feature?

**Comment by dvdeynden** [comment]
No haven't tried property renaming. Found reference to it somewhere but can't find it back. Any docs?

Regards,
Dirk

**Comment by ErikEJ** [comment]
Docs are in the docs here:

https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#custom-renaming-with-efptproperty-renamingjson

**Comment by dvdeynden** [comment]
Mange tak ... I'll have a look

Dirk

**Comment by dvdeynden** [comment]
Property renaming did the trick ... made a json file to deal with my DBContext class and changed the name of all the DBSets. A pity that it requires a 'renaming.json' and a separate 'property-renaming.json' file to accomplish changing from a technical DB table name to a readable DBSet name, but eventual future reverse engineering will be consistent (as long as I keep both files in sync).

Thanks,
Dirk

**Comment by ErikEJ** [comment]
Great!

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
