### ISSUE TITLE
filter properties of base type

### ISSUE THREAD

**Issue by SkipNiemeyer** [ErikEJ/EFCorePowerTools#1761]
in the EntityType.t4 file, I am attempting to modify the Entity classes to inherit from a base class. Adding the name of the base class works as intended, but duplicates the base class properties (not unexpected). However, when attempting to filter the properties of the base from the properties of the type it is creating.

### Provide steps to reproduce
existing code from EntityType.t4 
  public partial class <#= EntityType.Name #>
  {
  <#
      var firstProperty = true;
      foreach (var property in EntityType.GetProperties().OrderBy(p => p.GetColumnOrder() ?? -1))
      {
          ...
modification:
  public partial class <#= EntityType.Name #> : MyEntity
  {
  <#
      var firstProperty = true;
      foreach (var property in EntityType.GetProperties()
          .Where(p => !typeof(MyEntity).GetProperties().Select(i => i.Name).Contains(p.Name))
          .OrderBy(p => p.GetColumnOrder() ?? -1))
      {
          ...
### Provide technical details

- EF Core version in use: (e.g. EF Core 7)

- Is Handlebars used: no

- Is T4 used: yes

- Is .dacpac used: no

- EF Core Power Tools version: 2.5.1338

- Database engine: SQL Server

- Visual Studio version: Visual Studio 2022

**Comment by SkipNiemeyer** [comment]
Forgot to mention: The error I'm getting is: 'An error occurred. See the "Extensions" Output window for details.', and I am not sure how to find that  "Extensions" Output window as well, as nothing shows in the "normal" output window

**Comment by ErikEJ** [comment]
First test your code in OnModelCreating.

There is an Output window named Extensions
