### ISSUE TITLE
Specified table name is being ignored

### ISSUE THREAD

**Issue by MisinformedDNA** [ErikEJ/EFCorePowerTools#1766]
AnimalSpecies is renamed to AnimalSpecy.

### Provide steps to reproduce

1. Add a table named `t_AnimalSpecies`
2. Reverse engineer the DB
    3. Rename the table to `AnimalSpecies`

EXPECTED: Creates the type `AnimalSpecies`

ACTUAL: Creates the type `AnimalSpecy`

```cs
public virtual DbSet<ProductSpecy> ProductSpecies { get; set; }
```

I've tried with and without the EF6 pluralizer.

I've also tried with a regex to rename the table, but also no help.

```json
"TablePatternReplaceWith": "$1",
"TableRegexPattern": "^[t|v|f|a]_(.+)",
```

Humanizer does make [species](https://github.com/Humanizr/Humanizer/blame/1bdd7a1bad03fd001d04fc0e252d279b4e785818/src/Humanizer/Inflections/Vocabularies.cs#L112) an uncountable.

### Provide technical details

- EF Core version in use: EF Core 6

- Is Handlebars used: no

- Is T4 used: no

- Is .dacpac used: no

- EF Core Power Tools version: 2.5.1219.0

- Database engine: SQL Server

- Visual Studio version: Visual Studio 2022

**Comment by ErikEJ** [comment]
Have you tried naming the whole word uncountable via the config file?

**Comment by MisinformedDNA** [comment]
Are you referring to the efpt.renaming.json file? That got generated properly per the repro steps.

Our are you saying there is a way to mark AnimalSpecies as an uncountable?

**Comment by ErikEJ** [comment]
>> Our are you saying there is a way to mark AnimalSpecies as an uncountable?

Yes: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#pluralization

**Comment by MisinformedDNA** [comment]
Perfect.
