### ISSUE TITLE
NewName Option not Woeking

### ISSUE THREAD

**Issue by krossley** [ErikEJ/EFCorePowerTools#1767]
Describe what is not working as expected.

I can't get the "NewName" flag to work.

Please include a **complete** description or project that I can redo/run to reproduce the issue.

`{
  "CodeGenerationMode": 3,
  "ContextClassName": "CoinCatalogContext",
  "ContextNamespace": null,
  "DefaultDacpacSchema": null,
  "FilterSchemas": false,
  "IncludeConnectionString": true,
  "ModelNamespace": null,
  "OutputContextPath": null,
  "OutputPath": "Entites",
  "PreserveCasingWithRegex": true,
  "ProjectRootNamespace": "ReflectionApp",
  "Schemas": null,
  "SelectedHandlebarsLanguage": 0,
  "SelectedToBeGenerated": 0,
  "Tables": [
    {
      "Name": "[dbo].[Buffalo Nickel NGC]",
      "NewName": "[dbo].[Buffalo Nickel NG]",
      "ObjectType": 0
    },
    {
      "Name": "[dbo].[Buffalo Nickel PCGS]",
      "ObjectType": 0
    }
  ],
  "UseSchemaName": false,
  "UiHint": "BRYANS-X1\\SQLEXPRESS.CoinCatalog",
  "UncountableWords": null,
  "UseBoolPropertiesWithoutDefaultSql": false,
  "UseDatabaseNames": false,
  "UseDateOnlyTimeOnly": false,
  "UseDbContextSplitting": false,
  "UseFluentApiOnly": true,
  "UseHandleBars": false,
  "UseHierarchyId": false,
  "UseInflector": false,
  "UseLegacyPluralizer": false,
  "UseManyToManyEntity": false,
  "UseNoDefaultConstructor": false,
  "UseNoObjectFilter": false,
  "UseNodaTime": false,
  "UseNullableReferences": false,
  "UseSchemaFolders": false,
  "UseSpatial": false,
  "UseT4": false
}`

- EF Core version in use: (e.g. EF Core 7)
EF Core 7
- Is Handlebars used: no/yes
No
- Is T4 used: no/yes
No
- Is .dacpac used: no/yes
Not sure what that is, sorry.
- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
2.5.1372
- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)
Sql Express
- Visual Studio version: (e.g. Visual Studio 2022)
VS 2022

**Comment by ErikEJ** [comment]
Remove the schema name and brackets

**Comment by krossley** [comment]
Erik,
Thank you for your reply.  I have tried what you suggested but I was not able to get it to work.  Below is the code where I removed the Schema flag.  

`   "CodeGenerationMode": 2,
   "ContextClassName": "CoinCatalogContext",
   "ContextNamespace": null,
   "DefaultDacpacSchema": null,
   "FilterSchemas": false,
   "IncludeConnectionString": true,
   "ModelNamespace": null,
   "OutputContextPath": null,
   "OutputPath": "Models",
   "PreserveCasingWithRegex": true,
   "ProjectRootNamespace": "ReflectionApp",

   "SelectedHandlebarsLanguage": 0,
   "SelectedToBeGenerated": 0,
   "Tables": [
    {
      "Name": "[dbo].[Buffalo Nickel NGC]",
      "NewName": "[dbo].[Buffalo Nickel NG]",
      "ObjectType": 0
    },
      {
         "Name": "[dbo].[Buffalo Nickel PCGS]",
         "ObjectType": 0
      }
   ],
   "UiHint": "bryans-x1\\sqlexpress.CoinCatalog.dbo",
   "UncountableWords": null,
   "UseBoolPropertiesWithoutDefaultSql": false,
   "UseDatabaseNames": false,
   "UseDateOnlyTimeOnly": false,
   "UseDbContextSplitting": false,
   "UseFluentApiOnly": true,
   "UseHandleBars": false,
   "UseHierarchyId": false,
   "UseInflector": false,
   "UseLegacyPluralizer": false,
   "UseManyToManyEntity": false,
   "UseNoDefaultConstructor": false,
   "UseNoObjectFilter": false,
   "UseNodaTime": false,
   "UseNullableReferences": false,
   "UseSchemaFolders": false,
   "UseSpatial": false,
   "UseT4": false
}`

**Comment by ErikEJ** [comment]
Let me be more precise ( and suggest you read the wiki!)

You need to replace 

      [dbo].[Buffalo Nickel NGC]

With

       Buffalo Nickel NGC

**Comment by krossley** [comment]
Erik,
Thank you for your reply.  I read the wiki first before contacting you.  This is what I have tried without success.

`   "Tables": [
      {
        "Name": "[dbo].[Buffalo Nickel NGC]",
         "NewName": "Buffalo Nickel NG",
         "ObjectType": 0
      },


I also tried this
   "Tables": [
      {
        "Name": "Buffalo Nickel NGC",
         "NewName": "Buffalo Nickel NG",
         "ObjectType": 0
      },`

**Comment by ErikEJ** [comment]
Please share your create table statement  
 The second attempt might work, but unsure about all the spaces in the name

**Comment by krossley** [comment]
Erik,
It's still not working. I will update on it later tonight.

**Comment by ErikEJ** [comment]
The original name is the full table name. I think.

**Comment by krossley** [comment]
Erik,
"Name": "BuffaloNickelNgc", //This code is what your tool named it on the reverse engineer of the table.
    "NewName": "BuffaloNickelNGc" // This is what I am trying to rename too.  notice the NGc opposed to Ngc.  Does the above code in the JSON file above look correct?

**Comment by ErikEJ** [comment]
I will have another look, not sure if a change in just casing works.

**Comment by ErikEJ** [comment]
You need to use

```json
           "Name": "Buffalo Nickel NGC",
          "NewName": "BuffaloNickelNgc"
```

**Comment by krossley** [comment]
Erik,
That did the trick!  Sorry that was such a hassle.  Than you so much for your help,

**Comment by ErikEJ** [comment]
Cool! 
If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by krossley** [comment]
Done! and Done!
Thanks again Erik!
