### ISSUE TITLE
[Request] Property renaming misses models that are put in a separate project

### ISSUE THREAD

**Issue by MisinformedDNA** [ErikEJ/EFCorePowerTools#1769]
In order to match existing EDMX config, I am creating the `DbContext` in one project and the models in another project. This causes the property renamer to miss those models. Is there something that can be done so the renamer processes those?

### Provide steps to reproduce

1. Create an efpt.config.json with:

```json
"OutputContextPath": ".",
"OutputPath": "..\\ModelProject",
```

2. Create an efpt.property-renaming.json file:

```json
{
  "Classes": [
    {
      "Name": "Table1",
      "Properties": [
        {
          "Name": "Data",
          "NewName": "NewData"
        }
      ]
    }
  ]
}
```

### Provide technical details

- EF Core version in use: EF Core 6

- Is Handlebars used: no

- Is T4 used: no

- Is .dacpac used: no

- EF Core Power Tools version: 2.5.1372

- Database engine: SQL Server

- Visual Studio version: Visual Studio 2022

**Comment by ErikEJ** [comment]
Correct, that is a limitation of this experimental feature. Not aware of any workarounds other than moving files after code generation...
