### ISSUE TITLE
DateOnly type not working for Storep Procedure parameter

### ISSUE THREAD

**Issue by TimKras** [ErikEJ/EFCorePowerTools#1771]
Given this Stored Procedure:

`CREATE PROCEDURE Test @Datum date
AS
BEGIN
	return 1;
END`

And reverse engineer with this option checked:
![image](https://user-images.githubusercontent.com/5257192/233434953-fa6c5cec-c393-4165-bb60-32bfb066076f.png)

results in this method: 
![image](https://user-images.githubusercontent.com/5257192/233435117-fc274ed0-5575-4039-ab75-51daadc8e557.png)
with a DateTime parameter in stead of a DateOnly parameter.

EDIT: same problem for return values of Stored Procedures.

**Comment by ErikEJ** [comment]
The mapping only applies to Tables and views at the moment.

Could you show me a sample stored procedure?

**Comment by ErikEJ** [comment]
@TimKras Did you test this?

**Comment by TimKras** [comment]
@ErikEJ, Having some issues with the latest Daily Build: #1776

**Comment by TimKras** [comment]
@ErikEJ Confirmed it is working. (both parameters and return values).

Thanks!

**Comment by ErikEJ** [comment]
Great and thanks for the heads up (and Bug report)
