### ISSUE TITLE
The entire data set is loaded into memory with ToListAsync() when executing the procedure

### ISSUE THREAD

**Issue by superrnovae** [ErikEJ/EFCorePowerTools#1773]
When executing the procedure with `SqlQueryAsync`, the entire data set is asynchronously loaded into memory with `ToListAsync()`.
Wouldn't it be better to use `AsAsyncEnumerable()` on the IQueryable so that the data set can be asynchronously enumerated and return IAsyncEnumerable?

This would require having `Microsoft.Bcl.AsyncInterfaces` package installed on projects targeting netstandard 2.0 (for EFCore3)
   
Also, thanks for your hard work on this amazing tool, it's a time saver.

**Comment by ErikEJ** [comment]
Yeah, currently I also support 3.1. I plan to stop doing that soon, maybe then will be a good time to start using that. 

Have you confirmed that doing that would actually work?

**Comment by ErikEJ** [comment]
Did you test this?

**Comment by superrnovae** [comment]
> Did you test this?

Hello. I will test it in the morning (in like 9 hours and let you know the result).

**Comment by superrnovae** [comment]
Sorry for the delay. I was finally able to test it. Yes, yielding IAsyncEnumerable with `await foreach` from the `SqlQueryAsync` works without issues.

**Comment by ErikEJ** [comment]
Interested in doing a PR?

**Comment by ErikEJ** [comment]
(Do not worry to much about 3.1, I will remove support for that any day now)

**Comment by ErikEJ** [comment]
@superrnovae Have you changed your mind?

**Comment by superrnovae** [comment]
> @superrnovae Have you changed your mind?

Hello, no I haven't, I was away for vacation, but I will create a pull request this weekend.

**Comment by ErikEJ** [comment]
Cool. I have just dropped support for 3.1, btw

**Comment by ErikEJ** [comment]
Moving to backlog for now, will reconsider if more ask for it.
