### ISSUE TITLE
Can't install to VS 2019

### ISSUE THREAD

**Issue by misseill** [ErikEJ/EFCorePowerTools#1774]
Hey there, 

Thank you for this great tool! We have been using it on our project successfully for YEARS. 

### Provide steps to reproduce

My co-worker recently reinstalled VS Professional 2019, and cannot find the EF Core Power Tools extension in Extension Manager > Online > Search. Additionally, he had it listed in Roaming Extension Manager list, with an enabled Stop Roaming button and a disabled Download button. 

I had him download the latest EF Core Power Tools (EF_Core_Power_Tools_v2.5.1378.vsix). If he double clicks the file or if he right-clicks to Open With and chooses either :
C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe (from the EF Core log)
or 
C:\Program Files (x86)\Common Files\Microsoft Shared\MSEnv\VSLauncher.exe (from internet suggestions)
he gets the same error (attached).

![image](https://user-images.githubusercontent.com/17883746/233735352-4e0508e2-d866-4136-bdeb-38332a358ebb.png)

### Provide technical details

- EF Core install version 2.5.1378 (Although the rest of the team has 2.5.1234 installed)
- Is Handlebars used: no
- Is T4 used: no
- Is .dacpac used: yes
- Database engine: SQL Server
- Visual Studio version: Professional 2019, 16.11.25

Please let me know if I can provide any additional helpful info, and again thank you so much. 

Erika

**Comment by ErikEJ** [comment]
Why are you stiil using VS 2019?

VS 2019 is no longer supported, but you can find an old version of the tool here: https://github.com/ErikEJ/EFCorePowerTools/tree/master/tools/VS2019Support

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by misseill** [comment]
We have to use what has been supplied. Thank you so much for the link to the older version! I will surely leave a review and send a donation!

**Comment by misseill** [comment]
Also thank you for the very quick reply!

**Comment by misseill** [comment]
Sorry for not knowing this - I was expecting a vsix and not a zip - how do you install?

**Comment by ErikEJ** [comment]
Rename the file to .vsix

**Comment by misseill** [comment]
THANK YOU!

**Comment by shazibzaffar** [comment]
I have the same issue but I'm using VS 2022 community preview on an ARM machine
tried downloading from marketplace also ef core is showing up under roaming tab
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/2164093/d237c9d0-e4e9-40a3-927d-c12d4b35cf1a)

**Comment by ErikEJ** [comment]
@shazibzaffar Why do you think it is the same issue? I do not support VS ARM64, but you can use the command line version on ARM64 if you are looking for the reverse engineering feature.

**Comment by shazibzaffar** [comment]
ok thankyou i'll give it a try
