### ISSUE TITLE
Publish CLI tools as a standalone Nuget package

### ISSUE THREAD

**Issue by biiiipy** [ErikEJ/EFCorePowerTools#1778]
It would be great if EFCPT Dotnet CLI tool was also available as a simple nuget package. Although it's simple to install as a tool, the usage is harder than a Nuget package, which we could include in our own tooling, workflows without having to install and use cmd interface.
It's probably is a niche feature, but it (probably) doesn't require new functionality, just a new package.

**Comment by ErikEJ** [comment]
I am not sure what you mean by NuGet package, the tool already is a NuGet package !?

**Comment by ErikEJ** [comment]
That is not something I plan to support and maintain.
