### ISSUE TITLE
Renaming file in not read with ErikEJ.EFCorePowerTools.Cli

### ISSUE THREAD

**Issue by ng-julien** [ErikEJ/EFCorePowerTools#1779]
the efpt.renaming.json is not taken into account by the tool

### Provide steps to reproduce

My file is at the root of the project, but this one is not taken into account

### Provide technical details

- EF Core version in use: EF Core 6 and 7

- Is Handlebars used: no

- Is T4 used: no

- Is .dacpac used: no

- EF Core Power Tools version: ErikEJ.EFCorePowerTools.Cli --version 7.0.0-preview2

- Database engine: SQL Server

- Visual Studio version: N/A

**Comment by ng-julien** [comment]
fix available here https://github.com/ErikEJ/EFCorePowerTools/commit/758d5aabdfe6affc49d141c14e868a8ef8f11c7c
thank you for everything

**Comment by ErikEJ** [comment]
@ng-julien Have you verified the fix?

**Comment by ng-julien** [comment]
Yes I just tested, the problem is fixed

**Comment by ErikEJ** [comment]
Cool, I will upload preview 3 to NuGet, thanks a lot for trying out the preview.

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
