### ISSUE TITLE
Best way to manage decimals in stored procedures

### ISSUE THREAD

**Issue by rasaconsulting-sandy** [ErikEJ/EFCorePowerTools#1784]
I use EF Core Power Tools to reverse engineer my database models and have some stored procedures in them.   

I'm getting the following warning message on my stored procedure Decimal members:

_No store type was specified for the decimal property 'xxx' on entity type 'sp_xxxResult'. This will cause values to be silently truncated if they do not fit in the default precision and scale. Explicitly specify the SQL server column type that can accommodate all the values in 'OnModelCreating' using 'HasColumnType', specify precision and scale using 'HasPrecision', or configure a value converter using 'HasConversion'._

**What is your recommended approach to fix this without messing up the auto-generated classes?**  

The recommended ways is to annotate the decimal property or extend the OnModelCreating method (e.g. http://jameschambers.com/2019/06/No-Type-Was-Specified-for-the-Decimal-Column/).  Both of these methods appear to be difficult to implement:
- the annotation would mean adding text to auto-generated class files which would then be required to be updated each time the model was refreshed
- the OnModelCreating method doesn't implement the stored procedures - they have their own 'OnModelCreatingGeneratedProcedures' method.  

I've tried a couple of variations of extending the OnModelCreating and OnModelCreatingGeneratedProcedures classes using partial classes but haven't had any success to date.

Tech details:
EF Core 7.0.5
Handlebars used: no
T4 used: no
.dacpac used: no
EF Core Power Tools version: 2.5.1378 (7.0.3 in Nuget Packages)
Database engine: SQL Server
Visual Studio version: Visual Studio 2022

**Comment by ErikEJ** [comment]
Maybe the tool should add an attribute to the class. Can you share and example and test if a manually added attribute works?

**Comment by rasaconsulting-sandy** [comment]
Sounds good - I'm preparing an example now.  Thanks.

**Comment by rasaconsulting-sandy** [comment]
[EFPowerToolsDecimalExample.zip](https://github.com/ErikEJ/EFCorePowerTools/files/11358141/EFPowerToolsDecimalExample.zip)
Here is a sample solution with a sample db backup included - is this what you needed?

**Comment by ErikEJ** [comment]
More just an example of a stored procedure that causes the warning and a sample I'd a "fixed" result set  if possible

**Comment by rasaconsulting-sandy** [comment]
The database backup file I provided has one table in the database with 3 decimal columns in it:
<img width="397" alt="image" src="https://user-images.githubusercontent.com/69283328/235285953-c87fc87b-75b5-455e-a3c8-1081541034ce.png">

There is one example stored procedure included as well - sp_WeatherForecast (I've attached the file separately now with a .txt extension instead of .sql which wasn't allowed):
[stored proc file.txt](https://github.com/ErikEJ/EFCorePowerTools/files/11358473/stored.proc.file.txt)

The warnings I'm getting are:
![image](https://user-images.githubusercontent.com/69283328/235287016-b7551d05-88d3-4158-bdd0-3787fdc15445.png)

The fix is either to apply an annotation to the relevant columns - e.g.:

<img width="469" alt="image" src="https://user-images.githubusercontent.com/69283328/235286282-4fc1f586-225a-4c4e-b400-04e992ac9aca.png">

or to add the relevant decimal size to the OnModelCreating method - e.g.:

<img width="740" alt="image" src="https://user-images.githubusercontent.com/69283328/235286315-1b977426-f44b-445b-9ec1-a1bd6066d5a8.png">

_ref: http://jameschambers.com/2019/06/No-Type-Was-Specified-for-the-Decimal-Column/_

I've added the following decimal size information to the OnModelCreatingGeneratedProcedures method and it appears to have resolved the warning:

<img width="852" alt="image" src="https://user-images.githubusercontent.com/69283328/235286943-c9dc0240-f6a0-4d29-b2ec-59307fc6f6e7.png">


I'm looking forward to testing the fix in the EF Power Tools!

Sandy

**Comment by ErikEJ** [comment]
@rasaconsulting-sandy Thanks, I will invistigate adding the attribute to the result set classes

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by rasaconsulting-sandy** [comment]
Awesome thanks!  I'll get back to you once I've tested.

**Comment by rasaconsulting-sandy** [comment]
The update looks good.

I tested it on my project and there were no longer error warnings for the decimals.  Also it looks like there was another fix - SQL procedure parameters that were declared as DATE were previously written as DATETIME when the PowerTool did it's magic.  I noticed that this is now fixed to DATE and I've reversed my workarounds I'd had in place to accommodate DATETIME.  Once I did this everything worked as expected. 

Thanks!
Sandy

**Comment by ErikEJ** [comment]
Thanks for the heads up - yes, proper support for date and time => DateOnly / TimeOnly was added recently.

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by rasaconsulting-sandy** [comment]
I've made a one-time sponsorship and will consider a monthly sponsorship at the point that my project goes into production and starts generating an income.  Thanks for providing it.  I will also review on VS Marketplace - I have done this previously also under my other account. 
Thanks again.

**Comment by ErikEJ** [comment]
@rasaconsulting-sandy Much appreciated!

**Comment by djad442** [comment]
I have generated the code using C# Handlebar templates. Getting the same error for all decimal-type properties. Any idea how to modify the templates?

"No store type was specified for the decimal property"
