### ISSUE TITLE
CLI: efcpt-config.json how to set default exclude to true

### ISSUE THREAD

**Issue by rattar001** [ErikEJ/EFCorePowerTools#1786]
I have database that contains too many tables and view.
I would like to generate just 4 - 5 tables and views and exclude all others.

For now, in my efcpt-config.json I must set "exclude" of all table I don't want to generate.

How can I setup efcpt-config.json to generate only table that show in json and auto exclude all others ?

**Comment by rattar001** [comment]
{
      "wildcard": "*",
      "exclude": true
}
is not worked for me. 
After I use this and regenerate  wildcard is disappear and replace with all others table and views

<img width="425" alt="image" src="https://user-images.githubusercontent.com/39193150/235566354-40898f33-ef26-45dd-b513-53735f1f376e.png">

**Comment by ErikEJ** [comment]
@rattar001 it is a proposed feature! Not implemented yet. But do you think it could work for you?

**Comment by ErikEJ** [comment]
I have now published preview 5, please let me know if it solves your issue.

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
