### ISSUE TITLE
EF Core Power Tools context menu loads for one Project but not for the other.

### ISSUE THREAD

**Issue by Michael-ICS** [ErikEJ/EFCorePowerTools#1788]
Describe what is not working as expected.

### Provide steps to reproduce
Please see short video on the issue:
https://youtu.be/YW2L6ZaMJyw

- I recently updated my visual studio instance when prompted by Microsoft, however, the last time I regenerated the database files was quite a while ago and I have updated Visual Studio several times from the first time I generated the efpt.config.json file.
- I uninstalled and reinstalled EF Core Power Tools in Visual Studio 2022
- I restarted Visual Studio with a clean start
- Regardless if I load one or more than one Visual Studio instance the problem persists. I can load the single project and it will not launch the context menu.

Please note as a diagnostic step, I copied the contents of the efpt.config.json file where the context menu is failing to load into the project where the context menu is working, and it worked correctly in my other project. It only seems to hate my QA project.

Please include a **complete** description or project that I can redo/run to reproduce the issue.
Here are the details of the project that the context menu fails to load for:
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <LangVersion>latest</LangVersion>
        <TargetFramework>net6.0</TargetFramework>
        <AssemblyName>Si.Qa.Edu.Data</AssemblyName>
        <RootNamespace>Si.Qa.Edu.Data</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <IsPackable>false</IsPackable>
        <Configurations>Debug;Release;Development;Testing;Staging;Production;Automation</Configurations>
    </PropertyGroup>

    <ItemGroup>
      <Compile Remove="Context\**" />
      <EmbeddedResource Remove="Context\**" />
      <None Remove="Context\**" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.16" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.16" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="6.0.16">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.5.0" />
        <PackageReference Include="Shared.Utilities.Data.Qa" Version="6.2023.413.5" />
        <PackageReference Include="Shared.Utilities.Qa" Version="6.2023.413.5" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Helpers\" />
    </ItemGroup>

</Project>

### Provide technical details

- EF Core version in use: (e.g. EF Core 7)
EF Core 6 or 7

- Is Handlebars used: no/yes

- Is T4 used: no/yes

- Is .dacpac used: no/yes

- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
2.5.1378

- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)
SQL Server

- Visual Studio version: (e.g. Visual Studio 2022)
Microsoft Visual Studio Enterprise 2022
Version 17.5.5
VisualStudio.17.Release/17.5.5+33627.172
Microsoft .NET Framework
Version 4.8.09037

Installed Version: Enterprise

Visual C++ 2022   00476-80000-00000-AA955
Microsoft Visual C++ 2022

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools   17.5.320.55692
ASP.NET and Web Tools

ASP.NET Web Frameworks and Tools 2012   17.5.320.55692
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   17.5.320.55692
Azure App Service Tools v3.0.0

Azure Data Lake Tools for Visual Studio   2.6.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   17.5.320.55692
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.5000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   4.5.2-3.23171.7+d17f741546fad2786cbd6394d08619544e53a36d
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   17.0.22336.2
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Entity Framework Core Power Tools   2.5
Adds useful design-time EF Core DbContext features to the Visual Studio Solution Explorer context menu.

Extensibility Message Bus   1.4.3 (main@2a4517a)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Linux Core Dump Debugging   1.0.9.33414
Enables debugging of Linux core dumps.

Microsoft Azure Hive Query Language Service   2.6.5000.0
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.6.5000.0
Language service for Azure Stream Analytics

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.5.9 (11975e6)
Support for debugging Mono processes with Visual Studio.

Node.js Tools   1.5.50105.3 Commit Hash:882de61a7c99ae988d4c62029301292a3e0b1d56
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   6.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Office Developer Tools for Visual Studio   17.0.33303.00
Microsoft Office Developer Tools for Visual Studio

Python - Django support   17.0.22336.2
Provides templates and integration for the Django web framework.

Python - Profiling support   17.0.22336.2
Profiling support for Python projects.

Python with Pylance   17.0.22336.2
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Razor (ASP.NET Core)   17.5.2.2316603+9f1b6856460af1e592d387ebef416eadddac453f
Provides languages services for ASP.NET Core Razor.

SlowCheetah - XML config transforms   1.0
This package enables you to transform your app.config or any other XML file based on the build configuration. It also adds additional tooling to help you create XML transforms.

SQL Server Data Tools   17.2.40120.0
Microsoft SQL Server Data Tools

Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   17.0.20105.2003
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.5.2-3.23171.7+d17f741546fad2786cbd6394d08619544e53a36d
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Linux Development   1.0.9.33414
Visual C++ for Linux Development

Visual F# Tools   17.5.0-beta.23053.5+794b7c259d9646a7eb685dad865aa27da7940a21
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.

Xamarin   17.5.0.173 (d17-5@33e727c)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.5.3.46 (remotes/origin/d17-5@e4dd80b2bb)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   13.2.0.0 (d17-5/797e2e1)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 6dd9def
    Java.Interop: xamarin/java.interop/main@149d70fe
    SQLite: xamarin/sqlite/3.40.0@fdc1e34
    Xamarin.Android Tools: xamarin/xamarin-android-tools/main@9f02d77

**Comment by ErikEJ** [comment]
I have updated the MarketPlace release with a fix for this.

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
