### ISSUE TITLE
Generated DbContext.OnModelCreating is different in different environments using same codebase, database and EF Core Power Tools versions

### ISSUE THREAD

**Issue by djswilly** [ErikEJ/EFCorePowerTools#1789]
We are using EF Core Power Tools to reverse engineer our DbContext and Entity Types for a team project. The efpt.config.json is in source control. For some team members, running `EF Core Power Tools - Refresh` now removes the following line from the top of the generated OnModelCreating:
```
modelBuilder.UseCollation("Latin1_General_CI_AS");
```

### Provide steps to reproduce
For an existing database with Collation `Latin1_General_CI_AS` and existing DbContext with UseCollation specified in OnModelCreating:
 - run `EF Core Power Tools - Edit` or `EF Core Power Tools - Refresh` for Tables only from `efpt.config.json` in Visual Studio
 - observe the following line being removed from the top of the generated OnModelCreating for some team members:
```
modelBuilder.UseCollation("Latin1_General_CI_AS");
```
We are using the same database backup and the same branch of the same project.

Update: It appears as if the server collation is involved. If the server collation matches the database collation, the line is removed. For team members with a different server collation (`SQL_Latin1_General_CP1_CI_AS`) the line is re-added. Before we upgraded to EF Core 6, the following line appeared in OnModelCreating regardless of the server collation:
```
modelBuilder.HasAnnotation("Relational:Collation", "Latin1_General_CI_AS");
```

### Provide technical details
- EF Core version in use: EF Core 6
- Is Handlebars used: no
- Is T4 used: no
- Is .dacpac used: no
- EF Core Power Tools version: 2.5.1429
- Database engine: Microsoft SQL Server Developer (64-bit) 15.0.2101.7
- Visual Studio version: Microsoft Visual Studio Professional 2022 (64-bit) - Current Version 17.5.5

**Comment by ErikEJ** [comment]
@djswilly Yes, as you noted, this was changed in EF Core 6 - to avoid it make sure everyone has the same environment, including same server collation.

**Comment by ErikEJ** [comment]
>> `modelBuilder.HasAnnotation("Relational:Collation", "Latin1_General_CI_AS");`

That looks more like a bug in scaffolding that this annotation was not removed.

No issue in it not being set, it adds no value in a database first scenario, it is for Migrations creating a database with the desired collation

**Comment by ErikEJ** [comment]
If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
