### ISSUE TITLE
Generating of a custom namespace for my entity classes

### ISSUE THREAD

**Issue by Slash88** [ErikEJ/EFCorePowerTools#1792]
Hi,
I'm facing an "issue" when generate my entity classes.

I want  to put my generated entities in a subfolder called "Models" but I want that their namespace doesn't include the word "Models".

This scenario is possible by leaving empty the key `ProjectRootNamespace` and fill `ModelNamespace` in `efpt.config.json` and re-generate the code.
See the example below.
![image](https://user-images.githubusercontent.com/46223464/236262999-c3ab699c-1615-4ab1-bec9-da184e48b462.png)

However, this is not possible through the wizard because of the warning  "Namespace is required"
![image](https://user-images.githubusercontent.com/46223464/236262683-12bc6a12-add2-4127-b36a-07038bead16e.png)

How I can solve this issue?
I would like to avoid having to manually edit the file `efpt.config.json` every time after running the wizard.

Thanks in advance to anyone who can help me

Best regards

### Provide technical details

- EF Core version in use:  EF Core 6

- Is Handlebars used: no

- Is T4 used: no

- Is .dacpac used: no

- EF Core Power Tools version: 2.5.1429
- Database engine: SQL Server

- Visual Studio version: Visual Studio 2022

**Comment by ErikEJ** [comment]
Does this help? https://github.com/ErikEJ/EFCorePowerTools/blob/master/samples/entitypath.md

**Comment by Slash88** [comment]
Hi Erik, 
thank you for your reply and many thanks for your awesome tool!

Yes, of course I've already read the wiki of the project and I configured the tool using that document. 
The problem is that I wanted to set the namespace of the classes the default namespace of the project (my project's name is `Project.Example.Repository.Entities`).

Through the wizard I've set the Project Name and if I set the OutputPath with the word _Models_ the namespace become `Project.Example.Repository.Entities.Models`.

If I set the `ModelNamespace ` key with _Project.Example.Repository.Entities_ the namespace become `Project.Example.Repository.Entities.Project.Example.Repository.Entities.`

To avoid having this situation I clear the ProjectRootNaspace in `_efpt.config.json_` and keep the ModelNamespace key. By this way I've the desidered namespace and I able to refresh the tool everytime.

If I wanted to add a new tables by the wizard, that it is not possible because of the warning above.

I founded a workaround to split the default namespace: fill a part in ProjectNamespace and a part in EntityTypes sub-namespace.

![image](https://user-images.githubusercontent.com/46223464/236390888-fd45ad40-5299-4af7-9342-a6b82b539c9b.png)
![image](https://user-images.githubusercontent.com/46223464/236390838-55f59bee-e894-495f-83f9-53a6d598a284.png)
![image](https://user-images.githubusercontent.com/46223464/236391089-726b84f0-d648-488f-82a0-040630196e40.png)

Since it is possible to leave empty the "ProjectRootNamespace" in efpt.config.json, maybe it is only a UI issue?

**Comment by ErikEJ** [comment]
Glad you found a workaround, I am going to keep requiring a root namespace. 

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
