### ISSUE TITLE
Improvement proposals for EF Core Power Tools

### ISSUE THREAD

**Issue by JuanIrigoyen** [ErikEJ/EFCorePowerTools#1793]
Remove navigations from entity classes option is not available in the last version.
Namespace generated in different projects in clean architectures

### Provide steps to reproduce

[Improvement proposals for EF Core Power Tools.pdf](https://github.com/ErikEJ/EFCorePowerTools/files/11404684/Improvement.proposals.for.EF.Core.Power.Tools.pdf)

### Provide technical details

- EF Core version in 3
- Is Handlebars used: no
- Is T4 used: no
- Is .dacpac used: no/yes
- EF Core Power Tools version: Only can use the 2.5.1145 version
- Database engine: (SQL Server, Azure SQL, SQLite)
- Visual Studio version: (e.g. Visual Studio 2022)

**Comment by ErikEJ** [comment]
Instead of a bucket with proposals I suggest posing individual issues the next time.

For POCO you can use the T4 POCO template. 

For namespaces, you can set in advanced dialog.

If that does not work for you, then please create individual issues we can discuss.

**Comment by ErikEJ** [comment]
>> Only can use the 2.5.1145 version and version is 3.

I am phasing out support for EF Core 3 and only support the latest version of the extension, sorry.
