### ISSUE TITLE
How to rename navigation property?

### ISSUE THREAD

**Issue by MarvinNorway** [ErikEJ/EFCorePowerTools#1794]
We have a table called `TaskInApplication` - the Power Tools generate a navigation property `TaskInApplications` for this, but we obviously want it to be called `TasksInApplication`.
We were able to achieve this by modifying `DbContext.t4`, but is there a better way to do this?

**Comment by ErikEJ** [comment]
Property renaming as described in the wiki sounds like what you are looking for.

**Comment by ErikEJ** [comment]
Ping?

**Comment by MarvinNorway** [comment]
@ErikEJ Thank you! I'll check it out. Is that a new feature? I could have sworn that the last time I checked the documentation, there was only something about table renaming...

**Comment by ErikEJ** [comment]
Yes, relatively new
