### ISSUE TITLE
CLI tool does not support "OutputContextPath"

### ISSUE THREAD

**Issue by Layla-P** [ErikEJ/EFCorePowerTools#1796]
In the GUI, I can specify a directory for the DB Context. I cannot update the `efcpt-config.json` with a similar command to create a directory for the DbContext.

### Provide steps to reproduce

- Generated code using CLI command.
- Updated the config file with the following:
```csharp
 "file-layout": {
    "output-path": "Models",
    "output-context-path": "Data"
  },
```
I also tried it with `OutputContextPath` just in case.
- set soft delete to true
- run the CLI command again
### Provide technical details

- EF Core version in use: (e.g. EF Core 7)
EF Core 7
- Is Handlebars used: no/yes
no
- Is T4 used: no/yes
no
- Is .dacpac used: no/yes
no
- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
7.0.0-preview5
- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)
SQL Server,
- Visual Studio version: (e.g. Visual Studio 2022)
VS Studio 2022 Enterprise

**Comment by ErikEJ** [comment]
Hmm.. I wanted to the config file to be lean, but it seems to be backfiring.

Did you not get help from your text editor?

```json
"file-layout": {
    "output-path": "Models",
    "output-dbcontext-path": "Data"
  },

```
![image](https://user-images.githubusercontent.com/4169187/236492979-e4f6b492-e60f-4044-9660-4af4b82ed962.png)

**Comment by Layla-P** [comment]
I did not - but then VS can be very petty about when it lets me have intellisense.  I went to the config file generated by the GUI to get values.

**Comment by ErikEJ** [comment]
Wonder what I could do to make this experience better? (The editor I use is VS Code)

**Comment by ErikEJ** [comment]
Wonder if linking to this (needs updated) would help: https://github.com/ErikEJ/EFCorePowerTools/blob/master/samples/efcpt-config.json

**Comment by ErikEJ** [comment]
Let's see if I get similar questions in the future, then I will think about a way to address this

**Comment by ErikEJ** [comment]
Fixed in the latest master build
