### ISSUE TITLE
Error with Data Annotations when Column has multiple attributes

### ISSUE THREAD

**Issue by KayakFisher205** [ErikEJ/EFCorePowerTools#1798]
When Editing an entity set, I have a stored procedure that has a field with a long name that has to have brackets around it. Recently, EF Core Power Tools has been adding Column Attributes with the TypeName set when Decimals. With this stored procedure, I get an error in the class.
It creates the attributes as 
 [Column("Electric Energy (kWh/ton)",]
 [Column(TypeName = "decimal(38,10)")]
 public decimal? ElectricEnergykWhton { get; set; }

but it should put them together as 
 [Column("Electric Energy (kWh/ton)",TypeName = "decimal(38,10)")]

### Provide steps to reproduce
Have a decimal field who name has invalid characters like / and spaces, i.e. 

select (SUM(electric_energy) / 127) / COUNT(fiscalMonthNum) AS [Electric Energy (kWh/ton)]

where electric_energy is decimal(38,10)

- EF Core version 7.0

- Handlebars used: no

- T4 used: no

- .dacpac used: no

- EF Core Power Tools version: 2.5.1436

- Database engine: SQL Server 2019

- Visual Studio version: Visual Studio 2022 Version 17.6.0 Preview 6.0

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.
