### ISSUE TITLE
Scaffolding warnings when generating context and models for AdventureWorks 2019

### ISSUE THREAD

**Issue by robeverett** [ErikEJ/EFCorePowerTools#1799]
I am building a .net 7.0 web api with Entity Framework Core version 7.
I get the following list of issues.

Could not find type mapping for column 'HumanResources.Employee.OrganizationNode' with data type 'hierarchyid'. Skipping column.
The column 'HumanResources.Employee.SalariedFlag' would normally be mapped to a non-nullable bool property, but it has a default constraint. Such a column is mapped to a nullable bool property to allow a difference between setting the property to false and invoking the default constraint. See https://go.microsoft.com/fwlink/?linkid=851278 for details. The column 'HumanResources.Employee.CurrentFlag' would normally be mapped to a non-nullable bool property, but it has a default constraint. Such a column is mapped to a nullable bool property to allow a difference between setting the property to false and invoking the default constraint. See https://go.microsoft.com/fwlink/?linkid=851278 for details. Unable to scaffold the index 'IX_Employee_OrganizationLevel_OrganizationNode'. The following columns could not be scaffolded: OrganizationNode. Unable to scaffold the index 'IX_Employee_OrganizationNode'. The following columns could not be scaffolded: OrganizationNode. Could not find type mapping for column 'Person.Address.SpatialLocation' with data type 'geography'. Skipping column. The column 'Person.StateProvince.IsOnlyStateProvinceFlag' would normally be mapped to a non-nullable bool property, but it has a default constraint. Such a column is mapped to a nullable bool property to allow a difference between setting the property to false and invoking the default constraint. See https://go.microsoft.com/fwlink/?linkid=851278 for details. Could not find type mapping for column 'Production.Document.DocumentNode' with data type 'hierarchyid'. Skipping column. Could not scaffold the primary key for 'Production.Document'. The following columns in the primary key could not be scaffolded: DocumentNode. Unable to generate entity type for table 'Production.Document' since its primary key could not be scaffolded. The column 'Production.Product.MakeFlag' would normally be mapped to a non-nullable bool property, but it has a default constraint. Such a column is mapped to a nullable bool property to allow a difference between setting the property to false and invoking the default constraint. See https://go.microsoft.com/fwlink/?linkid=851278 for details. The column 'Production.Product.FinishedGoodsFlag' would normally be mapped to a non-nullable bool property, but it has a default constraint. Such a column is mapped to a nullable bool property to allow a difference between setting the property to false and invoking the default constraint. See https://go.microsoft.com/fwlink/?linkid=851278 for details. Could not find type mapping for column 'Production.ProductDocument.DocumentNode' with data type 'hierarchyid'. Skipping column. Could not scaffold the primary key for 'Production.ProductDocument'. The following columns in the primary key could not be scaffolded: DocumentNode. Unable to generate entity type for table 'Production.ProductDocument' since its primary key could not be scaffolded. The column 'Purchasing.Vendor.PreferredVendorStatus' would normally be mapped to a non-nullable bool property, but it has a default constraint. Such a column is mapped to a nullable bool property to allow a difference between setting the property to false and invoking the default constraint. See https://go.microsoft.com/fwlink/?linkid=851278 for details. The column 'Purchasing.Vendor.ActiveFlag' would normally be mapped to a non-nullable bool property, but it has a default constraint. Such a column is mapped to a nullable bool property to allow a difference between setting the property to false and invoking the default constraint. See https://go.microsoft.com/fwlink/?linkid=851278 for details. The column 'Sales.SalesOrderHeader.OnlineOrderFlag' would normally be mapped to a non-nullable bool property, but it has a default constraint. Such a column is mapped to a nullable bool property to allow a difference between setting the property to false and invoking the default constraint. See https://go.microsoft.com/fwlink/?linkid=851278 for details.

I've been told that installing EFCorePowerTools, then generating the context would solve this.
Would I then be able to declare hierarchyid data type in C# code  and would the other issues be resolved too ?

**Comment by ErikEJ** [comment]
@robeverett  First of all, these are just warnings, nothing is broken.

hierarchyId: You can go to Advanced options and enable hierarchyid mapping (and install the supporting package) as [described here](https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#mapping)

bool warning: You can go to advanced options and choose the "remove defaults from bool" [option](https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#choose-advanced-options)

**Comment by ErikEJ** [comment]
To get hierachy support and remove the warnings yes.

The preferred workflow is that you always allow the generated code to be overwritten.

**Comment by robeverett** [comment]
Great, thanks.
