### ISSUE TITLE
Reverse Engineer randomly not generating [Key] annotation. (My PKs are not named 'Id')

### ISSUE THREAD

**Issue by yomer** [ErikEJ/EFCorePowerTools#180]
Erik,
I'm having this bug randomly when doing a reverse engineering on my DB. I have for example two tables with a Primary Key each. They are not named "Id", but after the process is complete, one entity has the [key] annotation and the other doesn't. It seems to be random. Checking other entities, the underscore in the name of the Primary Key doesn't seem to affect the outcome.

Steps to reproduce:
Reverse Engineer->Select  Connection->Select Tables ->

Dialog:
![capture20190213153403826](https://user-images.githubusercontent.com/1246242/52745507-d539fc80-2fa4-11e9-9988-5a8d7f102ab5.png)

EFCorePowerTools: 2.2.12
Visual Studio 2017 v15.8.7
.NET Core 2.1.4

Extract from the efpt.config.json file
{"HasPrimaryKey":true,"Name":"dbo.Arr_Cat_MontoGasolina"},{"HasPrimaryKey":true,"Name":"dbo.Arr_Cat_Paso"}

![capture20190213150924173](https://user-images.githubusercontent.com/1246242/52745549-edaa1700-2fa4-11e9-8d29-c0f2851cf8a7.png)
![capture20190213150957359](https://user-images.githubusercontent.com/1246242/52745550-edaa1700-2fa4-11e9-9dd3-33b680effcee.png)
![capture20190213151024039](https://user-images.githubusercontent.com/1246242/52745551-edaa1700-2fa4-11e9-83af-fd87bd79cad8.png)

**Comment by ErikEJ** [comment]
Could you provide sample CREATE TABLE statements?

**Comment by yomer** [comment]
Of course...

```
CREATE TABLE [dbo].[Arr_Cat_MontoGasolina](
	[IdCat_MontoGasolina] [int] IDENTITY(1,1) NOT NULL,
	[MontoGasolina] [int] NOT NULL,
	[Borrado] [bit] NOT NULL,
 CONSTRAINT [PK_Arr_Cat_MontoGasolina] PRIMARY KEY CLUSTERED 
(
	[IdCat_MontoGasolina] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[Arr_Cat_MontoGasolina] ADD  DEFAULT ((0)) FOR [Borrado]
GO
```
------------------------------------------------

```
CREATE TABLE [dbo].[Arr_Cat_Paso](
	[IdCat_Paso] [int] IDENTITY(1,1) NOT NULL,
	[Paso] [nvarchar](30) NOT NULL,
	[Borrado] [bit] NOT NULL,
 CONSTRAINT [PK_Arr_Cat_Pasos] PRIMARY KEY CLUSTERED 
(
	[IdCat_Paso] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[Arr_Cat_Paso] ADD  DEFAULT ((0)) FOR [Borrado]
GO
```

**Comment by ErikEJ** [comment]
I was able to repro - looks like an EF Core bug, but cannot see why this happens @bricelam ?

**Comment by bricelam** [comment]
Strange. @yomer can you submit a new issue on [aspnet/EntityFrameworkCore](https://github.com/aspnet/EntityFrameworkCore) to help us track this bug and get it fixed?

**Comment by ErikEJ** [comment]
Closing, as this appears to be a EF Core issue

**Comment by yomer** [comment]
The odd thing is that I don't recall updating my EFCore library recently. While EFCore Power Tools is set on auto update. I'm currently on version 2.1.4 of EFCore. 

The keys were being generated correctly the last time I updated my model a month or so ago.

**Comment by bricelam** [comment]
I think the power tools use their own version of EF (not the one used by the project)

**Comment by ErikEJ** [comment]
Power Tools reverse engineering use EF Core 2.2.0

**Comment by yomer** [comment]
Got it. I will have to downgrade EFCore Power Tools to an earlier version to be able to keep working with my model. 

Is the commit from Dec 12, 2018 the last one with EFCore 2.1.4?

I already submitted the issue to the EFCore Team

**Comment by ErikEJ** [comment]
yes, I have uploaded the releated daily build here: (rename from zip => vsix)
[EFCorePowerTools.1.0.715.zip](https://github.com/ErikEJ/EFCorePowerTools/files/2885536/EFCorePowerTools.1.0.715.zip)

**Comment by yomer** [comment]
Thank you!

**Comment by smitpatel** [comment]
This is not an issue.
`[PK_Arr_Cat_MontoGasolina]` name matches `PK_` + table name hence we don't have to spit out `HasName` in OnModelCreating so we put `Key` attribute.

`[PK_Arr_Cat_Pasos]` name has format `PK_` + tableName + `s` which forces us to use `HasKey().HasName()` in OnModelCreating. To avoid redundant configuration, we don't put `Key` attribute.

**Comment by ErikEJ** [comment]
Perfect - thanks @smitpatel !

**Comment by yomer** [comment]
@smitpatel Thanks for the fast response. 

So having a database first approach, I should make sure that all my PK names are declared with the [PK_ + table name] pattern, correct? Which would trigger the HasName OnModelCreating and Key(Data Annotation) behavior.

**Comment by smitpatel** [comment]
> Which would trigger the HasName OnModelCreating and Key(Data Annotation) behavior.

Which would trigger Key(Data Annotation) behavior and avoid the HasName OnModelCreating.

**Comment by yomer** [comment]
> > Which would trigger the HasName OnModelCreating and Key(Data Annotation) behavior.
> 
> Which would trigger Key(Data Annotation) behavior and avoid the HasName OnModelCreating.

Yes, sorry. I was referring to that. Very well, I'll rename my PKs in the schema. Thanks again Mr. Patel, and thanks @ErikEJ  for the follow up.
