### ISSUE TITLE
DbContextSplitting stopped working in version 2.5.1378 (April 20, 2023)

### ISSUE THREAD

**Issue by NorwegianKiwi** [ErikEJ/EFCorePowerTools#1800]
First, thank you for a fantastic tool!

We have been using EF Core Power Tools in our Database First project for some time now, and up to and including version 2.5.1338 it was working as expected, but after installing version 2.5.1378 (and it continued to be broken in 2.5.1429), the `OnModelCreating()`-method in our DbContext-class stopped having lines of
```
modelBuilder.ApplyConfiguration(new Configurations.MyEntityConfiguration());
```
and instead had all the code from the configurations instead.

None of the settings in efpt.config.json have been changed, and it still contains
```
"UseDbContextSplitting": true,
```

Our project uses EF Core 6 in a .NET 6 ASP NET Core project, and our database is SQL Server.
We use Visual Studio 2022.

We are not using Handlebars, T4 or dacpac.

**Comment by NorwegianKiwi** [comment]
I was trying to make a minimal repro, and I discovered that the bug only occurred when I included one specific table.
In particular, if I add the following two tables (`Element` and `Relation`), it breaks. But if I only include one of them (either one) it is ok:
```
CREATE DATABASE ReproSplitContextDB;
USE ReproSplitContextDB

CREATE TABLE Element (
	id VARCHAR(50) NOT NULL,
	title VARCHAR(50) NOT NULL,
	CONSTRAINT PK_Element PRIMARY KEY (id)
)

CREATE TABLE Relation (
    parentId VARCHAR(50) NOT NULL,
    childId VARCHAR(50) NOT NULL,
    CONSTRAINT PK_Relation PRIMARY KEY (parentId, childId),
    CONSTRAINT FK_Relation_Element_child FOREIGN KEY (childId) REFERENCES Element (id),
    CONSTRAINT FK_Relation_Element_parent FOREIGN KEY (parentId) REFERENCES Element (id)
)
```

**Comment by ErikEJ** [comment]
Can you share the non split DbContext?

**Comment by ErikEJ** [comment]
I will have a closer look, interestingly no changes were made to the implementation between these versions:

https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/RevEng.Core/DbContextSplitter.cs

**Comment by ErikEJ** [comment]
@NorwegianKiwi I am not able to repro with the llatest master code, and your supplied database script.

As I said, the code is quite brittle, wonder if you have something in place that replaces the space indentation with tabs somehow?

**Comment by NorwegianKiwi** [comment]
Hm, that is strange. I tried again from scratch, using the DB-code that I posted here to create the DB (in SSMS), then:
* Opened Visual Studio 2022 and created a brand new C# Class Library (using all the defaults)
* Right-clicked the project, selected EF Core Power Tools -> Reverse Engineer
* Added the newly created DB, chose EF Core 6 (checking that it was 2.5.1429), clicked OK
* Selected the tables, clicked OK
* Didn't change any of the default values except clicking "Advanced..." and checking "Split DbContext into Configuration classes (preview)" and clicking OK (on the advanced window) and then OK again.
* Looked at the class `ReproSplitContextDBContext`: The `OnModelCreating()`-method does not reference any configuration classes, and no configuration classes were generated.

I then tried this again on a different machine (with its own local development SQL Server), with the same result.

If I uncheck the `Relation` table (i.e. only import the `Element` table), a configuration class is generated.

When you ask "wonder if you have something in place that replaces the space indentation with tabs somehow?", where do you mean?

Could it have something to do with a setting in the SQL Server? Or do you have any other suggestions to what I can try to vary to get the same result as you?

**Comment by ErikEJ** [comment]
Provide a full schema for the database you are reverse engineering- you could also try with another database. 

No immediate other suggestions.

**Comment by ErikEJ** [comment]
Maybe close the Power Tools repository and step through the splitter code with a debugger?

**Comment by NorwegianKiwi** [comment]
So I was going to debug the splitter code, but saw that the bug didn't occur when compiling and running the code myself (doing the reverse engineering in the "second" Visual Studio instance). Then I tried checking out the code at various commit points (including the latest from master, and also at some earlier dates) and compiling my own vsix-files and install them (they all were installed as version "2.5.0"), and none of these had the bug either. But then I reinstalled the "official" 2.5.1429 vsix release, and the bug was back.

Could it be that I have compiled the code with a different set of conditional compilation symbols, or some other setting that would make a difference? When you tried to reproduce, did you use the "official" release?

**Comment by ErikEJ** [comment]
@NorwegianKiwi Yes, I tested with the latest official build.

You cannot really debug that way, as the vsix simply launches a command line tool included in a .zip file with the vsix. 

You need to launch the tool directly by starting efeveng60 with a path to a file that looks similar to efpt.config.json but with some additional info, see src\GUI\efreveng60\TestFiles\efptChinookM2M.json for an example.

(Sorry it is a bit complex)

**Comment by ErikEJ** [comment]
@NorwegianKiwi Made another attempt. I am able to repro if i pick EF Core 7 but not with EF Core 6 picked in the wizard. maybe you can share your efpt.config.json file?

**Comment by ErikEJ** [comment]
@NorwegianKiwi Yes, but in your original post you said EF Core 6!

**Comment by ErikEJ** [comment]
I will look into the EF Core 7 bug

**Comment by ErikEJ** [comment]
Still completely unable to repro with EF Core 6.
.

**Comment by ErikEJ** [comment]
Hooray - I am finally able to repro with .1429 extension also for EF Core 6.

**Comment by NorwegianKiwi** [comment]
That is great news! I must admit I am very curious what made a difference...

**Comment by ErikEJ** [comment]
I still have no clue

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), - builde 1443 or later - would be grateful if you could try it out.

**Comment by NorwegianKiwi** [comment]
Unfortunately, when I chose EF Core 7 in the dropdown, the bug was back (for both the repro project and our original project).

(I have posted a comment on the Marketplace --- as I said there, thank you so much for spending time making and updating this tool, it is greatly appreciated! I will also see if I can get my company to agree to a sponsorship.)
