### ISSUE TITLE
Handle updates on tables where the PK is not the Identity Column

### ISSUE THREAD

**Issue by rdangolIVM** [ErikEJ/EFCorePowerTools#1802]
I have a table that has and ID Column which is and Identity column that autoincrements, and a second column which is the actual Primary Key column. When I update this table, I get an exception that auto incremented columns cannot be updated.

This is what the tool generates.
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/129194958/44cde209-ec37-4cca-bd94-4442831be3dd)

This is what it should generate to fix this issue.
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/129194958/441876e7-09d3-4df8-af51-86a0d71bd10b)

I got the solution from this StackOverflow answer. https://stackoverflow.com/a/68777236

However, this fix isn't permanent since it gets overwritten, every time I reverse engineer. Can this be fixed?

**Comment by ErikEJ** [comment]
Please share a CREATE script and simple repro that causes the error.

**Comment by rdangolIVM** [comment]
CREATE TABLE [dbo].[tbl_SalesTicketAggregate](
	[RID] [int] IDENTITY(1,1) NOT NULL,
	[Code] [varchar](20) NOT NULL,
 CONSTRAINT [PK_tbl_SalesTicketAggregate] PRIMARY KEY CLUSTERED 
(
	[Code] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

**Comment by ErikEJ** [comment]
@rdangolIVM Are you also able to share a simple repro (C# code console app/Unit test) ?

**Comment by rdangolIVM** [comment]
Not sure how I can do that. 

All I did was reverse engineer this table and updated the entity.

**Comment by ErikEJ** [comment]
@rdangolIVM Share your code to do that then?

**Comment by ErikEJ** [comment]
You can create a partial DbContext class and implement the OnModelCreatingPartial(modelBuilder); method and make your changes there. 

@bricelam @roji Is this a known bug?

**Comment by rdangolIVM** [comment]
I will try the partial context class. 

Not sure how much this will help. We are using repository pattern. This is the gist of what I'm trying to do.

	public async Task UpdateAsync(string code, int salesPeriodNumber)
	{
		try
		{
			var aggregate = await _salesTicketAggregateRepositoryAsync.GetFirstOrDefaultAsync(s => s.Code == code);

			if (aggregate is not null)
				aggregate.SalesPeriodNumber = salesPeriodNumber;

			_salesTicketAggregateRepositoryAsync.Update(aggregate);
			_unitOfWork.Commit();
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.Message);
            throw;
        }
    }

**Comment by bricelam** [comment]
> Is this a known bug?

Hmm, we might have an issue on our backlog for this, but it's probably best to just file a new one.

@rdangolIVM Can you file this on the [dotnet/efcore](https://github.com/dotnet/efcore) repo?

**Comment by ErikEJ** [comment]
@rdangolIVM The table you posted above is not updateable. 

Please post a full repo, I am not able to reproduce, as this seems to be by design.

Program.cs:

```csharp
using Microsoft.EntityFrameworkCore;

var db = new GuidDbContext();

db.Database.EnsureDeleted();
db.Database.EnsureCreated();

db.TblSalesTicketAggregate.Add(new TblSalesTicketAggregate
{
    Code = "A",
});

await db.SaveChangesAsync();


public partial class TblSalesTicketAggregate
{
    public int Rid { get; set; }

    public string Code { get; set; }
}

public partial class GuidDbContext : DbContext
{
    public GuidDbContext()
    {
    }

    public virtual DbSet<TblSalesTicketAggregate> TblSalesTicketAggregate { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=.\\SQLEXPRESS;Initial Catalog=Guid.Db;Integrated Security=True;Encrypt=false");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TblSalesTicketAggregate>(entity =>
        {
            entity.HasKey(e => e.Code);

            entity.ToTable("tbl_SalesTicketAggregate");

            entity.Property(e => e.Code)
                .HasMaxLength(1)
                .IsUnicode(false);
            entity.Property(e => e.Rid)
                .ValueGeneratedOnAdd()
                .HasColumnName("RID");
        });
    }
}

```

**Comment by rdangolIVM** [comment]
Inserts are fine. I can add new records just fine. Try to update an existing record. That is what I was having issues with.

**Comment by ErikEJ** [comment]
Could you then PLEASE Update the create table script to be realistic - it only contains key colums at the moment

**Comment by rdangolIVM** [comment]
I'm sorry, I just removed the other columns for brevity. 

CREATE TABLE [dbo].[tbl_SalesTicketAggregate](
[RID] [int] IDENTITY(1,1) NOT NULL,
[Code] varchar NOT NULL,
[Description] varchar null,
CONSTRAINT [PK_tbl_SalesTicketAggregate] PRIMARY KEY CLUSTERED
(
[Code] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

**Comment by ErikEJ** [comment]
@rdangolIVM I have updated my repro attempt above, do still not get any errors!

**Comment by rdangolIVM** [comment]
@ErikEJ I'm not sure what to say. I have realized that I don't need to make updates to this table. So, I'm not going to need this to work. I can close the issue.
