### ISSUE TITLE
Reverse Engineer no longer working due to missing config

### ISSUE THREAD

**Issue by LlamaNL** [ErikEJ/EFCorePowerTools#1803]
When trying to Reverse Engineer my database, all previous config have gone missing and trying to reconfigure the power tools throws up several errors.

### Provide steps to reproduce
1. Rightclick project and click Reverse Engineer. > configs missing ![empty config](https://i.imgur.com/xUftcSw.png)
2. Click Add > Add database connection. > throws this error twice ![sql error](https://i.imgur.com/OF1oUsH.png)
3. Configuration screen appears for SQL connection, pressing test connection works ![success](https://i.imgur.com/apOxRpV.png)
4. Pressing anything but cancel results in this screen > throws this error ![errors](https://i.imgur.com/Bjkwx0v.png)

### Provide technical details
- EF Core version in use: EFCore 7
- Is Handlebars used: no
- Is T4 used: no
- Is .dacpac used: no
- EF Core Power Tools version: 2.5.1429
- Database engine: SQL Server
- Visual Studio version: Visual Studio 2022 Enterprise

**Comment by ErikEJ** [comment]
@LlamaNL Looks like you VS might be in a not so good state. Which VS version are you on?

**Comment by LlamaNL** [comment]
@ErikEJ Microsoft Visual Studio Professional 2022 (2) (64-bit) - Current Version 17.5.5

I just tried reverse engineer on the VS2022 preview version and that seems to work.
I tried uninstalling and reinstalling EFCore Power Tools on current but that had no effect.
Perhaps I need to remove some faulty config files?

**Comment by ErikEJ** [comment]
I think you might have some bad entries in Server Explorer - try to remove them all

**Comment by LlamaNL** [comment]
You're right, this seems to be a visual studio issue, I'll look there for my answers, sorry to bother you.
