### ISSUE TITLE
"Remove default DbContext constructor" option not being applied

### ISSUE THREAD

**Issue by IKIKN** [ErikEJ/EFCorePowerTools#1804]
Hi,

Even though I selected the "Remove default DbContext constructor" option in the Advanced menu, a constructor is still being generated in the DbContext file, preventing me to add a constructor in my partial class.

In my config json file, I do have "UseNoDefaultConstructor": true".

- EF Core version in use: EF Core 7
- Is Handlebars used: No
- Is T4 used: No
- Is .dacpac used: No
- EF Core Power Tools version: 2.5.1429
- Database engine: SQLite
- Visual Studio version: Visual Studio 2022

**Comment by ErikEJ** [comment]
Could you share an example?

**Comment by IKIKN** [comment]
Sure.

Here are a few screenshots with a very simple db :

![1](https://github.com/ErikEJ/EFCorePowerTools/assets/31113585/ead9ea3f-547a-4ccd-a273-88ab895bfc6b)
![2](https://github.com/ErikEJ/EFCorePowerTools/assets/31113585/df9278d1-5cfd-4bce-8228-40d9d4b1e50a)
![3](https://github.com/ErikEJ/EFCorePowerTools/assets/31113585/cd4bd58a-b238-4530-8cf5-35ff40d4dee0)
![4](https://github.com/ErikEJ/EFCorePowerTools/assets/31113585/181e54bf-b0e4-4a68-9cf4-3d7713468957)

**Comment by IKIKN** [comment]
> The default constructor would be
> 
> ```cs
> public GtpContext() { }
> ```
> 
> If you want to remove the other constructor, you'll need to use templates as it is acting as designed.

Are you sure?

When I uncheck the option, the same constructor is being automatically created as well: 

    public GtpContext(DbContextOptions<GtpContext> options)
        : base(options)
    {
    }

No constructor without parameter is created, whether the parameter is enabled or not.

**Comment by ErikEJ** [comment]
@IKIKN EF Core 7 never generates a parameterless constructor. I will Update the docs (and maybe the label)

**Comment by ErikEJ** [comment]
@IKIKN I have updated the docs

**Comment by ErikEJ** [comment]
@IKIKN as @MisinformedDNA wrote, your only option then is to use T4 templates. But I do not understand what addtional code you need to add to your constructor, could you share an example.

**Comment by IKIKN** [comment]
Ok, thanks for clarifying.

For instance, if I want to call 
`Database.EnsureCreated();`
on the constructor, so that it is automatically created if it doesn't exist when my DbContext is added on startup.

**Comment by ErikEJ** [comment]
@IKIKN That does not sound like a good approach, you should use anexternal mechanism (maybe migrations) to create/update your database schema. EnsureCreated is only for testing purposes.
