### ISSUE TITLE
reverse engineering

### ISSUE THREAD

**Issue by viveknariya** [ErikEJ/EFCorePowerTools#1810]
I want to customize dbcontext, to map my database column to fluent api, using some logic. how can i do that?

I used default ef-templates(T4) and tried customizing it, but not able to get what i want.

is there an any other way?

should i create T4 from scratch? if yes then what is way/approch?

**Comment by ErikEJ** [comment]
You need to provide more details

**Comment by viveknariya** [comment]
IOtype NUMERIC(1,0)
this is one one columns of my db(MSSQL SERVER) table
when i run scaffolding cmd, it will give
public decimal IOtype {get; set;}
instead of that 
i want
public bool IOtype {get; set;}

**Comment by ErikEJ** [comment]
Not possible. Create an additional property in  a partial class and map back and forth to IOType
