### ISSUE TITLE
Reverse engineer dialog box does not pick up the database name from json file

### ISSUE THREAD

**Issue by gbthakkar** [ErikEJ/EFCorePowerTools#1814]
Describe what is not working as expected.
When we try to run the reverse engineering tool again, it does not pick the database name (connection string) from efpt.cofig.json file.

### Provide steps to reproduce
you tube video for the same
https://youtu.be/CxyExuUE1IU

Please include a **complete** description or project that I can redo/run to reproduce the issue.

### Provide technical details

- EF Core version in use:  EF Core 6

- Is Handlebars used: no/yes

- Is T4 used: no/yes

- Is .dacpac used: no/yes

- EF Core Power Tools version:  2.5.1145.0

- Database engine: SQL Server

- Visual Studio version:  Visual Studio 2022

**Comment by ErikEJ** [comment]
Please use the latest released version.

Also, maybe have a look in Server Explorer in VS and clean up some obsolete connections

**Comment by gbthakkar** [comment]
Server Explorer in VS- made a trick.
Thank you Sir.

I am closing this issue.

**Comment by gbthakkar** [comment]
Hi Erik,

Server Explorer in VS- made a trick.
Thank you Sir.

I am closing this issue.

*Regards,*

*Gaurang Thakkar*
