### ISSUE TITLE
Allow excluding the DbContext property name from rename functionality

### ISSUE THREAD

**Issue by dougclutter** [ErikEJ/EFCorePowerTools#1817]
Describe what is not working as expected.

The table rename is a brilliant help; thank you so much for this!  I would like to suggest a small enhancement.

I append "Entity" to all table names so it is clear they are for EF.  For example, if I have a table named `ClassInstructors`, I would like a class named `ClassInstructorEntity` (works), a config class named `ClassInstructorEntityConfiguration` (works), and a `DbSet<ClassInstructorEntity>` property named `ClassInstructors`.

Instead of a property named `ClassInstructors`, the Reverse Engineering creates a property named `ClassInstructorEntities`. If you could add a flag like "DoNotRenameDbContextProperties" that would be a tremendous help.

Please include a **complete** description or project that I can redo/run to reproduce the issue.

(See above)

- EF Core version in use: (e.g. EF Core 7)

EF Core 7

- Is Handlebars used: no/yes

No

- Is T4 used: no/yes

Thanks to your wonderful rename capabilities, we don't need to use templates!!

- Is .dacpac used: no/yes

yes

- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)

2.5.1429

- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)

SQL Server

- Visual Studio version: (e.g. Visual Studio 2022)

17.6.2

**Comment by ErikEJ** [comment]
I think you need to use the property renaming experimental feature for that.

**Comment by ErikEJ** [comment]
Ping?

**Comment by dougclutter** [comment]
Hi Erik - sorry for the delay in my reply.  The **efpt.property-renaming.json** partially solved this problem for me.

As an example, let's say I have this in my **efpt.renaming.json**:
```json
[ { "Tables": [
  { "Name": "Classes", "NewName": "ClassEntity" }
] } ]
```
...and then I add **efpt.property-renaming.json**:
```json
{ "Classes": [
  { 
    "Name": "ClassEntity",
    "Properties": [ { "Name": "ClassInstructorEntities", "NewName": "ClassInstructors" } ]
  }
] }
```
Doing the above fixes up the `ClassInstructors` navigation property nicely.

Unfortunately, my DbContext still contains:
```cs
    public virtual DbSet<ClassEntity> ClassEntities { get; set; }
```
instead of the desired:
```cs
    public virtual DbSet<ClassEntity> Classes { get; set; }
```

I've attached full eftp.*.json files.
[efpt.zip](https://github.com/ErikEJ/EFCorePowerTools/files/11709597/efpt.zip)

**Comment by ErikEJ** [comment]
Have you tried this? 

```json
{ "Classes": [
  { 
    "Name": "ClassEntity",
    "Properties": [ { "Name": "ClassInstructorEntities", "NewName": "ClassInstructors" } ]
  },
  { 
    "Name": "UniversityDbContext",
    "Properties": [ { "Name": "ClassEntities", "NewName": "Classes" } ]
  },
] }
```
