### ISSUE TITLE
Question about installing EF power tools without being Admin

### ISSUE THREAD

**Issue by xheox** [ErikEJ/EFCorePowerTools#1818]
I can access the DB of one client only through a VM they provided but could not install EF power tools as I am not admin.
Is there a way to install EF Power tools without the need to be an admin ? 
I can probably do whatever the installer is doing manually 

- EF Core Power Tools version: 
- Visual Studio version: 2022

**Comment by ErikEJ** [comment]
Could you use the CLI (requires .NET runtime) ?

**Comment by xheox** [comment]
Yes I was able to install ErikEJ.EFCorePowerTools.Cli but could not find documentation on how to use it
Only this https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/efcpt/readme.md

**Comment by ErikEJ** [comment]
What docs are you missing. There is also a.link to the general docs explaining options. And built in help.

**Comment by ErikEJ** [comment]
I have added a link to a two minute demo video to the readme.

**Comment by xheox** [comment]
Thanks @ErikEJ 
Sorry my bad. 
I was reading the doc on the phone and a bit late at night. 
I did not see the "Run the tool" part.
Thanks.
