### ISSUE TITLE
Error when querying from Table with Fields having DateTimeOffSet Defaults

### ISSUE THREAD

**Issue by KayakFisher205** [ErikEJ/EFCorePowerTools#1821]
I have a table where there are 2 fields, 
[ErrorStart] [datetimeoffset](7) NULL,
[LastUpdated] [datetimeoffset](7) NOT NULL,

that has the default values set:

ALTER TABLE [dbo].[PS_UpdateStatusInfo] ADD  CONSTRAINT [DF_PS_UpdateStatusInfo_ErrorStart]  DEFAULT (sysdatetimeoffset()) FOR [ErrorStart]
ALTER TABLE [dbo].[PS_UpdateStatusInfo] ADD  CONSTRAINT [DF_PS_UpdateStatusInfo_LastUpdated]  DEFAULT (sysdatetimeoffset()) FOR [LastUpdated]

When I query the table (it only has one row), I get an error 
The property 'TimeStamped' cannot be configured as 'ValueGeneratedOnUpdate' or 'ValueGeneratedOnAddOrUpdate' because it's part of a key and its value cannot be changed after the entity has been added to the store.

Its a long trace so I will attach as a file (error.txt)

### Provide steps to reproduce
When I try to get the row
       using var _l2repl = _serviceProvider.CreateScope().ServiceProvider.GetRequiredService<AzureReplContext>();
       var updateStatus = _l2repl.PS_UpdateStatusInfo.Where(x => x.ID == 0).FirstOrDefault();
The error occurs. 

I found something thats similar at [ValueGeneratedOnUpdate() and ValueGeneratedOnAddOrUpdate() not working for DateTimeOffset property #19765](https://github.com/dotnet/efcore/issues/19765)

I am not sure how its related myself.
[error.txt](https://github.com/ErikEJ/EFCorePowerTools/files/11602338/error.txt)

### Provide technical details

- EF Core version in use: EF Core 7

- Is Handlebars used: no

- Is T4 used: no

- Is .dacpac used: no

- EF Core Power Tools version: 2.5.1479

- Database engine: SQL Server

- Visual Studio version: Microsoft Visual Studio Enterprise 2022 Preview Version 17.7.0 Preview 1.0

**Comment by KayakFisher205** [comment]
Here is the script for the table

CREATE TABLE [dbo].[PS_UpdateStatusInfo](
	[UpdateInProgress] [int] NOT NULL,
	[LastUpdated] [datetimeoffset](7) NOT NULL,
	[RunningTime] [int] NULL,
	[EafLmfDBRunningTime] [int] NULL,
	[EafLmfCLRRunningTime] [int] NULL,
	[CasterDBRunningTime] [int] NULL,
	[HotMillRunningTime] [int] NULL,
	[EqfRunningTime] [int] NULL,
	[ErrorFlag] [bit] NOT NULL,
	[ID] [int] NOT NULL,
	[ErrorStart] [datetimeoffset](7) NULL,
 CONSTRAINT [PK_PS_UpdateStatusInfo] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[PS_UpdateStatusInfo] ADD  CONSTRAINT [DF_PS_UpdateStatusInfo_UpdateInProgress]  DEFAULT ((0)) FOR [UpdateInProgress]
GO

ALTER TABLE [dbo].[PS_UpdateStatusInfo] ADD  CONSTRAINT [DF_PS_UpdateStatusInfo_LastUpdated]  DEFAULT (sysdatetimeoffset()) FOR [LastUpdated]
GO

ALTER TABLE [dbo].[PS_UpdateStatusInfo] ADD  CONSTRAINT [DF_PS_UpdateStatusInfo_EafLmfCLRRunningTime]  DEFAULT ((0)) FOR [EafLmfCLRRunningTime]
GO

ALTER TABLE [dbo].[PS_UpdateStatusInfo] ADD  CONSTRAINT [DF_PS_UpdateStatusInfo_ErrorFlag]  DEFAULT ((0)) FOR [ErrorFlag]
GO

ALTER TABLE [dbo].[PS_UpdateStatusInfo] ADD  CONSTRAINT [DF_PS_UpdateStatusInfo_DefaultValue]  DEFAULT ((1)) FOR [ID]
GO

ALTER TABLE [dbo].[PS_UpdateStatusInfo] ADD  CONSTRAINT [DF_PS_UpdateStatusInfo_ErrorStart]  DEFAULT (sysdatetimeoffset()) FOR [ErrorStart]
GO

**Comment by ErikEJ** [comment]
I see no column named TimeStamped !?

**Comment by KayakFisher205** [comment]
I know. There are 2 tables in the database that have them, EfCore Tools create them like:
modelBuilder.Entity<PS_CurrentlyCuttingCoils>(entity =>
        {
            entity.HasKey(e => new { e.updated, e.TimeStamped }).HasName("PK_PS_CurrentlyCutting");

            entity.Property(e => e.updated).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.TimeStamped)
                .IsRowVersion()
                .IsConcurrencyToken();
        });
        
        modelBuilder.Entity<PS_CasterLaserWidth>(entity =>
        {
            entity.Property(e => e.updated).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.TimeStamped)
                .IsRowVersion()
                .IsConcurrencyToken();
        });

However, I have no clue if they are being referenced and why. I edited the efpt.config.json, removing those tables, and the error is gone. 

I said I was using EF Core 7, but I see the Nugets are for 8.0.0-preview4.23259.3
I don't really need those 2 tables with the TimeStamps and I'll keep them out for now, but I can't understand how they are being referenced on a different table query.

**Comment by ErikEJ** [comment]
I need the schema for those tables as well if you would like me to investigate. Assume there is some foreign key relationship?

**Comment by ErikEJ** [comment]
Please share a fully runnable console app, and I will have a look.

**Comment by KayakFisher205** [comment]
[DemoForErik.zip](https://github.com/ErikEJ/EFCorePowerTools/files/11604267/DemoForErik.zip)
Hopefully this is what you can use. I put the tables in the database and there is a user readwrite with the password as readwrite.

when I tested it on the server, the error was created.

**Comment by ErikEJ** [comment]
Itt is an EF Core bug, it just gets very confused with your very quirky table design of a composite primary key with a rowversion and datetime column

You can remove this to work around the bug:

```csharp
entity.Property(e => e.TimeStamped)
                .IsRowVersion()
                .IsConcurrencyToken();
```

```sql
CREATE TABLE [dbo].[PS_CasterLaserWidth](
	[Currentlaserwidth] [float] NULL,
	[updated] [datetime] NOT NULL,
	[TimeStamped] [timestamp] NOT NULL,
 CONSTRAINT [PK_PS_CasterLaserWidth] PRIMARY KEY CLUSTERED 
(
	[updated] ASC,
	[TimeStamped] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
```

```csharp
public partial class PS_CasterLaserWidth
{
    public double? Currentlaserwidth { get; set; }

    public DateTime updated { get; set; }

    public byte[] TimeStamped { get; set; } = null!;
}

        modelBuilder.Entity<PS_CasterLaserWidth>(entity =>
        {
            entity.HasKey(e => new { e.updated, e.TimeStamped });

            entity.Property(e => e.updated)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.TimeStamped)
                .IsRowVersion()
                .IsConcurrencyToken();
        });

```

**Comment by ErikEJ** [comment]
I have created a bug report here: https://github.com/dotnet/efcore/issues/31004
