### ISSUE TITLE
Audit Trail the execution SQL Statement

### ISSUE THREAD

**Issue by TTLGSYA** [ErikEJ/EFCorePowerTools#1822]
Question/Enhancement
We need to Audit Trail every SQL Statement that interact with the DB - Is there such SQL Audit Trail feature to Turn ON in EF Core Power Tool
If we need to add this SQL Audit Trail feature by ourselves, where would you recommend to put in the code that would affected ALL SQL components?  DBContext and DBContextProcedures

Thanks.

**Comment by ErikEJ** [comment]
Command interception or logging both seem useable in this case.

It is not really related to EF Core Power Tools in any way.

You can also audit on the server level, in my opinion the best option
