### ISSUE TITLE
Improve t4 error reporting 

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#1826]
See https://github.com/dotnet/efcore/issues/31005

**Comment by ErikEJ** [comment]
@AchrWasUnavailable 
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by AchrWasUnavailable** [comment]
@ErikEJ I took the default DbContext.t4, added a single line of code and intendedly misspelled "Host" and left out the semicolon to trigger a compile error.
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/105279038/d6d8da62-3834-4887-b7e7-c89f6d0ce8b5)

After running the Reverse Engineer, I only see the following in the output window from "Extensions":
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/105279038/d7b17965-1de9-4283-bfd7-d86579f85dc1)

When running the same line in a tt-file, I see the following output in:
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/105279038/9846077f-0e9e-447f-a41f-3d40b393decb)

When running the samen DbContext.t4 with the dotnet ef dbcontext scaffold command, I see the following output:
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/105279038/d4b9826b-6d03-4047-8ad0-6eb40cf3b9cf)

**Comment by ErikEJ** [comment]
are you running build 1484 or newer?

**Comment by ErikEJ** [comment]
Ah, Visual Studio fails after reverse engineering - I will investigate

**Comment by ErikEJ** [comment]
@AchrWasUnavailable Please try build 1485, I belive it is fixed now

**Comment by AchrWasUnavailable** [comment]
@ErikEJ It works perfectly! Thnx! +5 on VS Market Place!
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/105279038/d8155921-ecf2-42ca-83d9-ca04af6f4658)

**Comment by ErikEJ** [comment]
@AchrWasUnavailable Great, and thanks for your help improving the tool!
