### ISSUE TITLE
OutputPatameter class

### ISSUE THREAD

**Issue by flencinas** [ErikEJ/EFCorePowerTools#1827]
Describe what is not working as expected.
why in the code generated  class OutputParameter<TValue>thow exception is value not set

                if (!_valueSet)
                    throw new InvalidOperationException("Value not set.");

Throwing an exception forces us to go and correct this part of the code every time we do a refresh.

   public TValue Value
         {
             get
             {
                 if (!_valueSet)
                     throw new InvalidOperationException("Value not set.");

                 return _value;
             }
         }

removing the part that if it does not have a value, it does not throw an exception

       if (!_valueSet)
                     throw new InvalidOperationException("Value not set.");

This happens to us because in our code we sometimes ask if the parameter has a value but as it is now the property throws an exception and we think it doesn't make sense

A suggestion would be to define the OutputParameter class as partial and virtual to the Value property so that we can change that behavior without having to make changes every time we do a refresh.

### Provide steps to reproduce

Please include a **complete** description or project that I can redo/run to reproduce the issue.

### Provide technical details

- EF Core version in use: (e.g. EF Core 7)

- Is Handlebars used: no
- Is T4 used: yes

- Is .dacpac used: no

- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)

- Database engine: SQL Server 

- Visual Studio version: (e.g. Visual Studio 2022)

**Comment by ErikEJ** [comment]
Maybe you are using the API wrong, but I  need to see an example of your Co summing code
