### ISSUE TITLE
Desmark [Column(TypeName = "decimal(18,0)")]

### ISSUE THREAD

**Issue by rafaelparenza** [ErikEJ/EFCorePowerTools#1828]
Mark off

This annotation is bad for those who use if and else in procedures. How to uncheck it?

`[Column(TypeName = "decimal(18,0)")]`

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/48654547/29c3b083-e874-424a-8e83-deeb23a64084)

### Provide technical details

- EF Core version in use: 6

- EF Core Power Tools version: 2.5.1429

- Database engine: (SQL Server)

- Visual Studio version: 2022

**Comment by ErikEJ** [comment]
Could you share an example and an error message?

**Comment by rafaelparenza** [comment]
It wouldn't be an error, I just have two types of return in the procedure, one returns a decimal (18.0) and another (18.2).
In some old version it didn't put this annotation
[Column(TypeName = "decimal(18,0)")]
As you can see in the image above, I updated the efpowertools version and it started to add this connotation.

Within my procedure I use "ifs and elses", which makes them different types in the return, so my variable "valorHora", which refers to money, has no decimal places.

**Comment by rasputino** [comment]
Could you share the DDL of the table?

**Comment by ErikEJ** [comment]
What runtime issues are you facing because of this?

**Comment by rafaelparenza** [comment]
Of execution none, just losing the decimal places of the field. I'm solving with browser replace

**Comment by ErikEJ** [comment]
If you revert the if in your stored proc you get the correct code generated?

**Comment by rafaelparenza** [comment]
> Se você reverter o if em seu proc armazenado você obtém o código correto gerado?


Yes, because we use the standard of declaring the return in the procedure before writing it, so all our procedures have this declaration for the entity framework power tools.

```
if @declaracaoPraApi = 1 -- this snippet is never executed and serves only to generate the procedure fields in the entity framework power tools
	begin
	DECLARE @string varchar(max) = null,
	@guid uniqueidentifier =null,
	@int int = null,
	@bool bit = null,
	@date datetime = null,
	@smallInt smallint = null,
	@decimal decimal = null,
	@bit tinyint = null

	SELECT
	@decimal as ValueMoney
end
```
even if you set the @decimal to @decimal decimal(18,2) = null, The same problem would occur if the dba placed a return (18,5) 

And it also doesn't make sense to put this delimiter in the backend.

In the old version it did not return this [Column(TypeName = "decimal(18,0)")]
which was great, because we could control the decimal places in the procedure

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
