### ISSUE TITLE
T4 for SQLServer Stored Procedures

### ISSUE THREAD

**Issue by OzBob** [ErikEJ/EFCorePowerTools#1830]
I am attempting to write a new implementation of EF Stored Procedures, 
https://github.com/ErikEJ/EFCorePowerTools/blob/af0b2b040dd8e739f46c184ab07c1e69f8742688/src/GUI/RevEng.Core.60/Procedures/SqlServerStoredProcedureScaffolder.cs#L599
to match the System.Data.SqlClient examples here:

https://learn.microsoft.com/en-us/dotnet/framework/data/adonet/sql/linq/how-to-use-stored-procedures-that-take-parameters#example-1
and
https://learn.microsoft.com/en-us/dotnet/framework/data/adonet/sql/linq/how-to-return-rowsets

The T4 templates when choose "Add T4 Scaffolding Templates" from the context menu on EFCoreTool in VS2022, none of the t4 fileshave Stored Procedure code or references to SqlParameter etc.

I aim to replace the 'raw sql' approach 

```
            var _ = await _context.SqlQueryAsync<SprocspDoStuffResponse>("EXEC @returnValue = [dbo].[spDoStuff] @TableId", sqlParameters, cancellationToken);
```

with:

```
[Function(Name="dbo.CustOrderTotal")]
[return: Parameter(DbType="Int")]
public int CustOrderTotal([Parameter(Name="CustomerID", DbType="NChar(5)")] string customerID, [Parameter(Name="TotalSales", DbType="Money")] ref System.Nullable<decimal> totalSales)
{
    IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), customerID, totalSales);
    totalSales = ((System.Nullable<decimal>)(result.GetParameterValue(1)));
    return ((int)(result.ReturnValue));
}
```

If the T4 for sprocs is not available then I'll look at forking and adding an option for different types of sproc generated EF code.

- "Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.8"

- Is Handlebars used: no

- Is T4 used: yes

- Is .dacpac used: no

- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
v2.5.1429, 

- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)
SQL SERVER

- Visual Studio version: (e.g. Visual Studio 2022)
2022 preview

**Comment by ErikEJ** [comment]
@OzBob I doubt you can do that, the code sample is for LINQ to SQL (veru old shcool tech and no longer supported)

**Comment by OzBob** [comment]
@ErikEJ i can live without the linq to sql, but was more interested in replacing the raw sql text for storedprocs and using ```SqlQueryAsync```  with lower level commands.

```
using (SqlConnection connection = base.GetNewConnection()){
	SqlCommand cmd = new SqlCommand();
	Int32 rowsAffected;
	cmd.CommandText = ((MethodInfo)(MethodInfo.GetCurrentMethod()));
	cmd.CommandType = CommandType.StoredProcedure;
	cmd.Parameters.AddWithValue("Param1", 1);
	cmd.Parameters.AddWithValue("Param2", "txt");
	cmd.Connection = connection;
	connection.Open();
	rowsAffected = cmd.ExecuteNonQuery();
	connection.Close();
	return rowsAffected;
}
```

**Comment by ErikEJ** [comment]
Why lower level commands? Then you need to do all the property mapping manually...

**Comment by ErikEJ** [comment]
Ping?

**Comment by OzBob** [comment]
@ErikEJ I was trying to think of a more eloquent response, but I'll put this one here and build on it.

Assuming string interpolation of the query text:
```
var _ = await _context.SqlQueryAsync<SprocspDoStuffResponse>("EXEC @returnValue = [dbo].[spDoStuff] @TableId", sqlParameters, cancellationToken);
```
is slower than naming the storedprocedure in the SqlCommand text.

This assumes ADO.Net is not just taking the command and doing string concatenation to make a "SqlQueryAsync". Which now I say it out loud is probably what it is doing.

**Comment by ErikEJ** [comment]
>> This assumes ADO.Net is not just taking the command and doing string concatenation

Hm. You have a few assumptions here - the sqlParameters are certainly not "string concatenated", but passed as an object.

So the only performance difference with be the parsing of the SQL statement to determine the stored procedure name.

It would be helpful to see some actual Benchmark.NET measurements to determine any actual performance benefit rather than assumptions.

**Comment by OzBob** [comment]
I agree that benchmarks would be useful to facilitate comparing if the change is useful. 

Metrics between sending a complete Exec statement as a string and a named command would only be relevant if '''context.SqlQueryAsync<SprocspDoStuffResponse>("EXEC''' sends a string for sqlserver to interpret, or is interpreted into ado.net commands?


How could I find out what is done with the exec string?

**Comment by ErikEJ** [comment]
FromSQL sets CommandType to Text, never stored procedure, as EF Core has no knowledge of them. And uses  standard sp_executesql execution. You could easily see that from a SQL Profiler session
