### ISSUE TITLE
When generating a class the name is not the same as the table name

### ISSUE THREAD

**Issue by FrqSalah** [ErikEJ/EFCorePowerTools#1831]
Describe what is not working as expected.

### Provide steps to reproduce

Create a table with two uppercase letters (e.g., compteATerme). Then try to reverse engineer the database. The entity created will be named compteAterme (the 't' letter will not be uppercase)

### Provide technical details

- EF Core version in use: 3.1

- EF Core Power Tools version: 2.5.1372

- Database engine: SQL Server

- Visual Studio version: Visual Studio 2022 - 17.5.2

**Comment by ErikEJ** [comment]
Have you tried Use Database names oe the renaming feature?

**Comment by FrqSalah** [comment]
I just tried and yesthe renaming feature work perfectly
