### ISSUE TITLE
Provide option to ignore existing DbContext.OnConfiguring method

### ISSUE THREAD

**Issue by dougclutter** [ErikEJ/EFCorePowerTools#1832]
Describe what is not working as expected.

1. Add an `OnConfiguring` method override to a DbContext.
2. Run EFPT Reverse Engineer 
3. Note that the `OnConfiguring` method has been removed

Please include a **complete** description or project that I can redo/run to reproduce the issue.

- EF Core version in use: (e.g. EF Core 7)

EF Core 7

- Is Handlebars used: no/yes

No

- Is T4 used: no/yes

No

- Is .dacpac used: no/yes

Yes

- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)

2.5.1429

- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)

SQL Server

- Visual Studio version: (e.g. Visual Studio 2022)

Visual Studio 2022

**Comment by ErikEJ** [comment]
Sounds like you are doing something wrong. 

You should do it in a partial class, the generated DbContext will be overwritten by default. Suggest you read the wiki.

**Comment by dougclutter** [comment]
Sorry Erik!  I missed that.

**Comment by ErikEJ** [comment]
@dougclutter glad you got it figured out!
