### ISSUE TITLE
Add Schema name in Entity Namespace

### ISSUE THREAD

**Issue by tkardaridis** [ErikEJ/EFCorePowerTools#1833]
Hi,
Consider having two tables with the same name in different schema. e.g.
Meteogen.Assets
Greenbyte.Assets

On reverse engineering is there any way, either with handlebars or anything else, to add the schema name in the namespace of the entities? 
for example

namespace MyDb.Meteogen
{
public partial class Assets...
}

namespace MyDb.Greenbyte
{
public partial class Assets...
}

**Comment by ErikEJ** [comment]
A PR for this feature was just merged  but I need to update the tools to enable it (I think) - keeping this open to remind me to do it

**Comment by tkardaridis** [comment]
Awesome. I will wait for that... thanks a lot. That will be a great feature.

**Comment by ErikEJ** [comment]
You can try the latest build, it might just work (consider it an experimental feature) . And looking forward to your feedback.
