### ISSUE TITLE
Havin a a composite key on a temporal table with foreign key constraints leads to entity type not beign generated when reverse engineering

### ISSUE THREAD

**Issue by aalho** [ErikEJ/EFCorePowerTools#1834]
Hi!

I am facing an issue when I try to reverse engineer a database and noticed that one table in a schema did not get it's coresponding entity fiole generated.

I tried to debug this and found out that if these conditions are met this issue can be reproduced:

- Have three tables with one of them with composite primary key and foreign keys that are part of that composite key referencing the other two tables

-  Have the table with composite key to be a temporal table
-  **When using .dacpac generation will work!**

### Here's an sql script that can be used to create the tables that produces this issue:
```
CREATE TABLE [dbo].[TableOne] (
    [Id] INT NOT NULL,
    CONSTRAINT [PK_TableOne] PRIMARY KEY NONCLUSTERED ([Id] ASC)
);
GO

CREATE TABLE [dbo].[TableTwo] (
    [Id] INT NOT NULL,
    CONSTRAINT [PK_TableTwo] PRIMARY KEY NONCLUSTERED ([Id] ASC)
);
GO

CREATE TABLE [dbo].[TableThree] (
    [TableOne_Id]  INT                                         NOT NULL,
    [TableTwo_Id]  INT                                         NOT NULL,
    [SysStartTime] DATETIME2 (7) GENERATED ALWAYS AS ROW START NOT NULL,
    [SysEndTime]   DATETIME2 (7) GENERATED ALWAYS AS ROW END   NOT NULL,
    CONSTRAINT [PK_TableThree] PRIMARY KEY NONCLUSTERED ([TableOne_Id] ASC, [TableTwo_Id] ASC),
    CONSTRAINT [FK_TableThree_TableOne] FOREIGN KEY ([TableOne_Id]) REFERENCES [dbo].[TableOne] ([Id]), --Disable one of these FK's and code generation will work
    CONSTRAINT [FK_TableThree_TableTwo] FOREIGN KEY ([TableTwo_Id]) REFERENCES [dbo].[TableTwo] ([Id]), --Disable one of these FK's and code generation will work
    PERIOD FOR SYSTEM_TIME ([SysStartTime], [SysEndTime])
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE=[dbo].[H_TableThree], DATA_CONSISTENCY_CHECK=ON));
GO
```

### Provide steps to reproduce

1. Run that above SQL-script to (empty)database.
2. Reverse engineer that database to Entity models.
3. Notice that TableThree.cs is not generated
4. Remove one of the **foreign key** constraints from TableThree **OR** remove the temporal stuff from table three
5. Reverse engineer again
6. TableThree.cs is generated

### Provide technical details

- EF Core version in use: **EF Core 7 and EF Core 6**

- Is Handlebars used: **no**

- Is T4 used: **no**

- Is .dacpac used: **no. If .dacpac is used this issue does not reproduce**

- EF Core Power Tools version: **2.5.1429**

- Database engine: **SQL Server (16.0.1050.5)**

- Visual Studio version: **Visual Studio 2022**

**Comment by ErikEJ** [comment]
Think about what you mean by "work" here. Not scaffolding a many to many to entity is by design.

The .dacpac scaffolding model comes from a different (my) codebase.

The symptoms could maybe indicate a bug in EF Core.

Would be great if you could create a slightly better commented repo and maybe post it in the EF Core repository

**Comment by ErikEJ** [comment]
Also, try to mark the temporal system columns as "HIDDEN"

**Comment by ErikEJ** [comment]
Ping?
