### ISSUE TITLE
Report unsupported Connection providers

### ISSUE THREAD

**Issue by jespersh** [ErikEJ/EFCorePowerTools#184]
A thing I think could help during Reverse Engineering, is all the available/user connections that could be found, but also tell that these particular connections providers are unsupported.

Like if I added an ODBC connection to mysql and expected that to work, then I'd at least know instead of it not showing up at all.

**Comment by ErikEJ** [comment]
Maybe it is better if I update the wiki page here? https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering

**Comment by ErikEJ** [comment]
I have updated the wiki post
