### ISSUE TITLE
Login failed error on mac m2

### ISSUE THREAD

**Issue by cem1835** [ErikEJ/EFCorePowerTools#1841]
I tried to use efcpt cli command but I have an error. that returned a login failed error but I am sure of my connection string. Also I looked to command and it was searching ef-cpt config in my user folder and I created a sample config

my command:

efcpt "Data Source=1.1.1.1;Initial Catalog=MyDB;User ID=MyDb;Password=mypassowrd;TrustServerCertificate=True;" mssql

my config:

{
    "ContextClassName": "ServicemanagerdbContext",
    "DefaultDacpacSchema": null,
    "IdReplace": false,
    "IncludeConnectionString": false,
    "OutputContextPath": "Persistence",
    "OutputPath": "DatabaseModels\/Entities",
    "ProjectRootNamespace": "ServiceManager.Repository",
    "SelectedToBeGenerated": 0,
    "Tables": [
    ],
    "UseDatabaseNames": true,
    "UseFluentApiOnly": true,
    "UseHandleBars": false,
    "UseInflector": false
}

error:
Microsoft.Data.SqlClient.SqlException: Login failed for user 'MyDb'.
  at void Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException   
     exception, bool breakConnection, Action<Action> wrapCloseInAction)         
  at void Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(          
     TdsParserStateObject stateObj, bool callerHasConnectionLock, bool          
     asyncClose)                                                                
  at bool Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior,    
     SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet   
     bulkCopyHandler, TdsParserStateObject stateObj, out bool dataReady)        
  at bool Microsoft.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior,       
     SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet   
     bulkCopyHandler, TdsParserStateObject stateObj)                            
  at void Microsoft.Data.SqlClient.SqlInternalConnectionTds.CompleteLogin(bool  
     enlistOK)                                                                  
  at void Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(    
     ServerInfo serverInfo, string newPassword, SecureString newSecurePassword, 
     bool ignoreSniOpenTimeout, TimeoutTimer timeout, bool withFailover)        
  at void Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(    
     ServerInfo serverInfo, string newPassword, SecureString newSecurePassword, 
     bool redirectedUserInstance, SqlConnectionString connectionOptions,        
     SqlCredential credential, TimeoutTimer timeout)                            
  at void Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(    
     TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential 
     credential, string newPassword, SecureString newSecurePassword, bool       
     redirectedUserInstance)                                                    
  at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(                   
     DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions,  
     SqlCredential credential, object providerInfo, string newPassword,         
     SecureString newSecurePassword, bool redirectedUserInstance,               
     SqlConnectionString userConnectionOptions, SessionData reconnectSessionData
     , bool applyTransientFaultHandling, string accessToken, DbConnectionPool   
     pool)                                                                      
  at DbConnectionInternal Microsoft.Data.SqlClient.SqlConnectionFactory.        
     CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, 
     object poolGroupProviderInfo, DbConnectionPool pool, DbConnection          
     owningConnection, DbConnectionOptions userOptions)     

- EF Core version in use: EFCore 6

- Is Handlebars used: no

- Is T4 used: no

- Is .dacpac used: no

- EF Core Power Tools version:  EF Core Power Tools CLI 6.0.0-rc.1 for EF Core 2

- Database engine: (SQL Server)

- Visual Studio version: no, cli

**Comment by ErikEJ** [comment]
Please Update to the latest version.

Can you use the same connection string with other tools?

You do not need the config file, what makes you think it is needed?

**Comment by cem1835** [comment]
> Please Update to the latest version.

> Can you use the same connection string with other tools?

> You do not need the config file, what makes you think it is needed?

1- I updated it to [6.0.0-rc.3], still the same.
2- Yes, same connection
3- I know but I just saw in the terminal after running the command:

EF Core Power Tools CLI 6.0.0-rc.1 for EF Core 2
https://github.com/ErikEJ/EFCorePowerTools

config file: /Users/cemtugut/efcpt-config.json

**Comment by ErikEJ** [comment]
The tool will create a config file for you, the message is just to indicate where it is located.

What other command line tools work?

Do you have a Turkish "i" letter in your connection string?

**Comment by ErikEJ** [comment]
Which .NET 6 runtime version do you have installed?

**Comment by cem1835** [comment]
I don't have Turkish i in my connection.
I copied and paste my connection string from the appsettings

my sdks:
dotnet --list-sdks
6.0.408 [/usr/local/share/dotnet/sdk]
7.0.302 [/usr/local/share/dotnet/sdk]

**Comment by ErikEJ** [comment]
What is 1.1.1.1?

Do you use a Turkish code page?

The error indicates that either password or user name is problematic.

I am running out of ideas...

**Comment by cem1835** [comment]
btw, it works on windows with efcore powertools UI. FYI

**Comment by ErikEJ** [comment]
What machine is your SQL Server located on?

**Comment by ErikEJ** [comment]
Ping?

**Comment by cem1835** [comment]
> What machine is your SQL Server located on?

I don't know but I will learn. About testing with another password, I have to create a new database. I can't change right now.
I will give my feedback today.

**Comment by ErikEJ** [comment]
Feel free to re-open with more info
