### ISSUE TITLE
Error installing extension on Visual Studio 17.6.4 (ARM 64) (Mac m2)

### ISSUE THREAD

**Issue by gjfonte** [ErikEJ/EFCorePowerTools#1843]
Hi. I am trying to install the extension but it fails with the following error:

This extension cannot be installed because the following references are missing:
**Microsoft.VisualStudio.Component.GraphDocument**

### Steps to reproduce

Normal installation from Manage Extensions in Visual Studio. Click Install and fails when I close VS and the extension starts the installation.

### Technical details

- Visual Studio Enterprise 2022 (ARM 64-bit) Version 17.6.4
- Windows 11 Pro 22H2 (Build 22621.1848) ARM (running on a MacbookPro M2 Max with Parallels 18.3.1)

- Install log:

27/06/2023 17:23:36 - Extension cannot be installed to the following products due to missing prerequisites:
27/06/2023 17:23:36 - 	Visual Studio Enterprise 2022
27/06/2023 17:23:36 - 		-------------------------------------------------------
27/06/2023 17:23:36 - 		Identifier   : Microsoft.VisualStudio.Component.GraphDocument
27/06/2023 17:23:36 - 		Name         : 
27/06/2023 17:23:36 - 		Version      : [17.0,)
27/06/2023 17:23:36 - 		Error        : The prerequisite specified does not exist
27/06/2023 17:23:38 - Blocking processes:
27/06/2023 17:23:38 - InstallProgressPage ChangeType: 'SingleTarget' operationCount: '2' Text: 'Modifying Visual Studio Enterprise 2022...'
27/06/2023 17:23:38 - The following target products have been selected...
27/06/2023 17:23:38 - 	Visual Studio Enterprise 2022
27/06/2023 17:23:38 - Beginning to install extension to Visual Studio Enterprise 2022...
27/06/2023 17:23:38 - Instantiate download manager silently: False
27/06/2023 17:23:42 - Install Error : Microsoft.VisualStudio.ExtensionManager.MissingReferencesException: This extension cannot be installed because the following references are missing:
-Microsoft.VisualStudio.Component.GraphDocument (Microsoft.VisualStudio.Component.GraphDocument)
   at Microsoft.VisualStudio.ExtensionManager.EngineUtilities.EnsureNoMissingReferences(IEnumerable`1 missingRefs)
   at Microsoft.VisualStudio.ExtensionManager.PackageInstaller.PrepareEngineInstall(IDependencyGraph dGraph, IDependencyComparisonSeed seed, Component vsixComponent, Boolean isProductComponent, Int32& totalInstallationSteps)
   at Microsoft.VisualStudio.ExtensionManager.InstallModule.PerformSetupEngineInstall(InstallableExtensionImpl extensionToInstall, Boolean installPerMachine, Boolean isPackComponent, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion, IInstalledExtension& newExtension)
   at Microsoft.VisualStudio.ExtensionManager.InstallModule.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.InstallModule.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.InstallModule.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)

**Comment by ErikEJ** [comment]
Try to manually add the DGML editor from the VS installer, and then retry.

**Comment by gjfonte** [comment]
> Try to manually add the DGML editor from the VS installer, and then retry.

Hi ErikEJ, I can't see the DGML editor in the individual components list (it should be in Individual Component > Code tools > DGML Editor).

Can this be something related with the ARM version of Visual Studio?

**Comment by ErikEJ** [comment]
Maybe, but others have been able to run on ARM64 !?

**Comment by ErikEJ** [comment]
Have you tried searching for it?

**Comment by gjfonte** [comment]
This is all I've got in the tools section:

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/4131055/24717ae4-dd29-4071-ae46-fc95b7f3b464)

Visual Studio Enterprise 2022 (ARM 64-bit) Version 17.6.4

**Comment by nmg196** [comment]
Yeah mine looks different on the normal Intel / x64 build.  It seems the ARM distribution of VS 2022 doesn't include this. So that begs the question, how have others managed to get EFPT to install??

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/8134047/88f4375f-c878-4453-84b5-68d8a9e68029)

**Comment by ErikEJ** [comment]
Hmm.. maybe it was changed in 17.6 ?

Let me try a daily build without that requirement and see how that goes

**Comment by ErikEJ** [comment]
Have you tried "search components" ??

**Comment by nmg196** [comment]
I am working with Gil - yes we have. It's definitely not there on Gil's arm64 machine (MacBook with M2 processor).  
We are both running the same build of VS 2022 Enterprise but his is the arm64 and mine is the x64. The component list is different between the two systems as per the screenshots above.

**Comment by ErikEJ** [comment]
My extension creates DGML diagrams and the viewer is required in order to open them.

**Comment by gjfonte** [comment]
Do you know if there is any link to install DGML manually?

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

**Comment by nmg196** [comment]
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/8134047/4bb4bc0a-536a-49f3-b235-5c4b69f95f5c)

Getting closer!   It now installs OK but gives this error.  We're starting to think that using a ARM PC for development isn't currently viable (June 2023 if anyone reads this in the future). 

Error is "The type initializer for "Microsoft.Data.SqlClient.TdsParser" threw an exception"

**Comment by ErikEJ** [comment]
You could also try a custom Azure SQL connection

**Comment by ErikEJ** [comment]
Ping?

**Comment by gjfonte** [comment]
The daily build installation worked, but then we found more issues when creating the connections to the database (local, Azure, etc). We gave up as we thought we will keep finding problems by using the Arm version of Visual Studio. 
Thank you for your support

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.
