### ISSUE TITLE
MultiSubNet failover flag in Connection Properties\Advanced Properties

### ISSUE THREAD

**Issue by garyholbrook** [ErikEJ/EFCorePowerTools#1845]
Describe what is not working as expected.
It is inserting "Multi Subnet Failover" instead of "MultiSubnetFailover" into the connection string.
### Provide steps to reproduce
change the value from False to True and click OK
Please include a **complete** description or project that I can redo/run to reproduce the issue.
We use HA servers for our Sql Servers, and the correct name/value pair is "MultiSubnetFailover=True", and you can substitute "yes" for "true".
### Provide technical details
The work around is to add this name/value pair into your connection string after you have generated the model.

- EF Core version in use: (e.g. EF Core 7)
EF Core 7
- Is Handlebars used: no/yes
No
- Is T4 used: no/yes
Yes
- Is .dacpac used: no/yes
No
- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
2.5.1429
- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)
Sql Server 2019
- Visual Studio version: (e.g. Visual Studio 2022)
Visual Studio 2022

**Comment by ErikEJ** [comment]
I will investigate, but generally it is not advisable to generate the connection string in code, it should reside in external configuration.

**Comment by ErikEJ** [comment]
@garyholbrook Both versions are valid values: https://learn.microsoft.com/en-us/dotnet/api/microsoft.data.sqlclient.sqlconnection.connectionstring?view=sqlclient-dotnet-standard-5.1

**Comment by mikeholczer** [comment]
This issue still exists. @ErikEJ let me know if you want me to open a new issue. This isn't about generating a connecting string in code. It's about using the UI provided by the reverse engineering option. When using the advanced options to set `Multi Subnet Failover` to `True` and then trying to add the connection this error is displayed:
![image](https://github.com/user-attachments/assets/f841465a-185b-4101-9b40-f5b3f6103698)

**Comment by mikeholczer** [comment]
Is there a way I can manually edit the connecting strings stored by EFCore Power Tools to try removing the spaces? It's not clear to me where the tool is storing the connecting strings it saves for it's own use.

**Comment by ErikEJ** [comment]
I think you pick the wrong provider or your stored connection uses the "old" provider. The connections are stored in Server Explorer 

@mikeholczer Please create a new issue with exact repro details if you want support!

**Comment by mikeholczer** [comment]
@ErikEJ not sure what the difference is, but when I go through the Server Explorer UI, I'm able to set MultiSubnetFailover without issue, so I'll just go that route going forward. Thanks.

**Comment by ErikEJ** [comment]
@mikeholczer it would still be nice to get exact repro steps with screenshots to find out what the actual issue is!
