### ISSUE TITLE
Reverse Engineer, Refresh and Edit actions are deleting existing entities.

### ISSUE THREAD

**Issue by wft-github** [ErikEJ/EFCorePowerTools#1846]
**Steps to reproduce**

When I tried to reverse engineer to add a couple of new tables to the existing EF project it tagged a couple of already existing entities for deletion and **the primary keys for those tables contain all the columns in the table**. 

This was not an issue before in VS 2019 with older version of EF Core Power Tools.

Attached is an example of one of those tables.

**Technical details**

- EF Core version in use: EF Core 6

- Is Handlebars used: no

- Is T4 used: no

- Is .dacpac used: no

- EF Core Power Tools version: 2.5.1429

- Database engine: SQL Server

- Visual Studio version: Visual Studio 2022

[PlayerAlert.zip](https://github.com/ErikEJ/EFCorePowerTools/files/11937987/PlayerAlert.zip)

**Comment by wft-github** [comment]
I did notice that on the entities that are getting tagged for deletion the primary key comprises all columns of the table.

**Comment by ErikEJ** [comment]
As requested when you create an issue, please provide enough info for me replicate it.

**Comment by wft-github** [comment]
> As requested when you create an issue, please provide enough info for me replicate it.

When I tried to reverse engineer to add a couple of new tables to the existing EF project it tagged a couple of already existing entities for deletion and the primary keys for those tables contain all the columns in the table. This was not an issue before in VS 2019 with older version of EF Core Power Tools. 

Attached is an example of one of those tables that are getting tagged for deletion.

[PlayerAlert.zip](https://github.com/ErikEJ/EFCorePowerTools/files/11937932/PlayerAlert.zip)

**Comment by ErikEJ** [comment]
I will have a look. What does "tagged for deletion" actually mean?

**Comment by ErikEJ** [comment]
Is it many to many tables? In that case they are no longer scaffolded with EF Core 6. There is an advanced option to preserve rhem though.

**Comment by wft-github** [comment]
> I will have a look. What does "tagged for deletion" actually mean?

It is deleting the Entity classes for those tables after reverse engineering. 

![Git-Changes](https://github.com/ErikEJ/EFCorePowerTools/assets/137302066/275b6a70-889b-4ae2-bf38-a1102c68ff8b)

**Comment by wft-github** [comment]
> Is it many to many tables? In that case they are no longer scaffolded with EF Core 6. There is an advanced option to preserve rhem though.

Erik,
They are many to many tables and using the advanced option to preserve them fixed the issue. 
Thank you for your assistance.

**Comment by ErikEJ** [comment]
Happy to help! 

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
