### ISSUE TITLE
Navigation issue while generating

### ISSUE THREAD

**Issue by irfandar** [ErikEJ/EFCorePowerTools#1847]
Describe what is not working as expected.

### Provide steps to reproduce

I want to split my db into two or more dbcontexts; one base and others who will inherit from the base. All works well except the navigation properties. Consider this a **User** table in BaseDbContext used in **Employee** table in OtherDbContext. While I am generating the code for the OtherDbContext I Skip the **User** table (since it is already present in the BaseDbContext both class and DbSet property) it does not generate the Navigation Property in **Employee** Class for the **User** Class. There should be checkbox which when checked should generate all the navigation properties even if the table was not selected
Thanks

### Provide technical details

- EF Core version in use: (e.g. EF Core 7)

- Is Handlebars used: No

- Is T4 used: No

- Is .dacpac used: No

- EF Core Power Tools version: 2.5.1429

- Database engine: SQL Server

- Visual Studio version: (e.g. Visual Studio 2022)

**Comment by ErikEJ** [comment]
Using Database Model First with base and inherited contexts is really not supported, you will have to fix up in a partial class.

**Comment by ErikEJ** [comment]
Maybe Database First is not for you? @irfandar
