### ISSUE TITLE
OnConfiguring -> Could be...

### ISSUE THREAD

**Issue by DiegoStefanon** [ErikEJ/EFCorePowerTools#1852]
Good morning
I was wondering if it would be possible to set the OnConfiguring method in reverse engineering ...
If there was a text box where to set a default text because inserting the configuration string is not optimal...

If such a feature already exists then excuse me...

Thank you for your kind attention and many good things...

Bye

**Comment by ErikEJ** [comment]
It is unclear what you are trying to achieve. You should avoid OnConfiguring and just use the constructor that takes DbContextOptuons.

Could you share some code please.

**Comment by DiegoStefanon** [comment]
Hello Erik
the question is very simple...
I want the possibility to have some code inside OnConfiguring like this and not only the query string choice :

 protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
            // < put my custom code HERE to insert in an optional field in Power Tools >        
    }


Many thanks for your kind effort

**Comment by ErikEJ** [comment]
What custom code do you need in there?

**Comment by ErikEJ** [comment]
Ping?
