### ISSUE TITLE
Reverse engineer options

### ISSUE THREAD

**Issue by LordSimpson** [ErikEJ/EFCorePowerTools#1853]
Hi

Currently trailing a work-flow on a project with frequent use of the reverse engineer option and have a couple of questions.

Is there any ability to change the suffix for stored procedure result naming or change the stored procedure naming conventions to match C# naming. The database I'm working with uses underscore naming conventions so ideally instead of it currently generating as 
"PROCEDURE_NAME_HEREResult", I would like to instead have either "PROCEDURE_NAME_HERE_RESULT" or preferably "ProcedureNameHereResult"

Secondly is there any quick re-run "reverse engineer" option. As application and database are being developed in tandem I'm frequently needing to use the reverse engineer function without changing any parameters to update to match the database, having a 1 click "run again as last time" or command line i could run would be perfect.

Thanks for any help!

**Comment by ErikEJ** [comment]
>> Is there any ability to change the suffix for stored procedure result naming

Not at the moment, why is it important, when consuming you can just use `var` ?

>> Secondly is there any quick re-run "reverse engineer" option. 

Sure, as described in the [docs](https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#saving-options-and-running-the-second-time)

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
