### ISSUE TITLE
Is my issue on EF or some update i need to do with your EFCore tools? Help!

### ISSUE THREAD

**Issue by balajeek** [ErikEJ/EFCorePowerTools#1854]
I am not sure if this is EFCorePowerTools issue or Microsoft EF latest update made some changes on how updates are done:
Having said that, my c# project the update to database was working fine before i took a break of around 3 months.  I came back and first thing i did is to open visual studio and updated all packages from nuget, (that includes from EF updates too) .
Now the same code that worked before throws me error that it can't update the table when a trigger is enabled on the table.

Here is the error message i get:
```
Microsoft.EntityFrameworkCore.DbUpdateException
  HResult=0x80131500
  Message=Could not save changes because the target table has database triggers. Please configure your entity type accordingly, see https://aka.ms/efcore-docs-sqlserver-save-changes-and-triggers for more information.
  Source=Microsoft.EntityFrameworkCore.SqlServer

Inner Exception 1:
SqlException: The target table 'tblExcelRecord' of the DML statement cannot have any enabled triggers if the statement contains an OUTPUT clause without INTO clause.

```

### Provide steps to reproduce
1. Create webapi project with .net core
2. Create a method to update a table
3. Inside the method do a database update, something like this:
```
  tblEmp e = new tblEmp()
  e.name = "john";
  e.phone = "999-999-9999"
  DB.SaveChanges();

```
4. Then call the api either from postman or other tool.

Please include a **complete** description or project that I can redo/run to reproduce the issue.
Its a webapi project, you call a api to update the table in this case
When you step thru the project the error is trigger at DB.SaveChanges() line

### Provide technical details

- EF Core version in use: 7.0.8

- Is Handlebars used: (don't know what this is)

- Is T4 used: (don't know what this is)

- Is .dacpac used: (don't know what this is)

- EF Core Power Tools version: 2.5.1429

- Database engine: (SQL Server 2017)

- Visual Studio version:  2022 version 17.5.1

**Comment by ErikEJ** [comment]
Please provide the information requested when you created this issue  otherwise I am going to close this issue, and you will not get any support.

**Comment by ErikEJ** [comment]
It is a runtime issue, maybe due to a computed column. Configure the table with HasTriggers();
