### ISSUE TITLE
Missing Context Menu

### ISSUE THREAD

**Issue by ab997** [ErikEJ/EFCorePowerTools#1857]
Right click on data project: ef core context menu is missing

### Provide steps to reproduce

Install VS2022 17.6.4 (also tried on 17.5.5 -> it used to work here) and Extension version 2.5.1514

Right click on existing project that used EFCore Power Tools to scaffold database. Context menu is missing

Tried: repairing VS, reinstalling VS, disabling / enabling extension, reinstalling extension, deleting cached folders of VS and extension, using older version of extension

### Provide technical details

- EF Core version in use: tried 6.0.14 and 7.0.8

- Is Handlebars used: no

- Is T4 used: no

- Is .dacpac used: no

- EF Core Power Tools version: 2.5.1514

- Database engine: SQL Server

- Visual Studio version: Visual Studio 2022 17.6.4 (also tried on 17.5.5 -> it used to work here)

**Comment by ErikEJ** [comment]
Please share the  .csproj file

**Comment by ErikEJ** [comment]
@ab997 Please share the .csproj file

**Comment by ab997** [comment]
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Geni.Common.VarsAndNotify.Abstractions" Version="1.1.4" />
    <PackageReference Include="Geni.Common.VarsAndNotify.Trading" Version="1.2.61" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="7.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AutoSendSchedule.Common\AutoSendSchedule.Common.csproj" />
  </ItemGroup>

</Project>

I am also providing screenshot of my and my colleague's screen for the same project

![working](https://github.com/ErikEJ/EFCorePowerTools/assets/58363787/5aaf1bf0-50b5-471e-bdb4-f5561eb73534)

![notworking](https://github.com/ErikEJ/EFCorePowerTools/assets/58363787/96a7cfac-16bc-4881-bddf-1f1c48798ffd)

**Comment by ErikEJ** [comment]
So it works for your colleague but nog for you? Using exact same VS version and extension version?

**Comment by ErikEJ** [comment]
I need a repro.

**Comment by ab997** [comment]
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/58363787/60b5a872-493a-4bed-b32e-544f510bbf11)
I see that it is enabled, and I tried enabling / disabling and reintalling

**Comment by ErikEJ** [comment]
@ab997  

>> So it works for your colleague but not for you? Using exact same VS version and extension version?

>> I need a repro.

**Comment by ErikEJ** [comment]
@ab997 Maybe check the ActivityLog.xml file also

**Comment by ab997** [comment]
Few more information in case you find anything helpful:
1.) activitylog.xml contained no mention of this extension
2.) im going to install it today on another computer (but i dont expect i will encounter any issues)
3.) on my machine where it does not work, i can't even find it in tools -> cusotmize window (this screenshot is provided by colleague)
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/58363787/61573f0f-e7f9-4a39-b65d-8e36453bf105)

**Comment by ErikEJ** [comment]
Repair VS!

**Comment by ErikEJ** [comment]
I am out of ideas, did you try another instance of VS? And you never replied to my two questions.

**Comment by ab997** [comment]
Yes sorry, I tried different versions of both VS and extension, including versions that used to work for me and version that currently work on machines of my colleagues.

I received a 2nd machine and installed latest VS and extensions and it works no problem, as expected. Something really strange happened on my original machine and we can't figure it out.

**Comment by ErikEJ** [comment]
@ab997 Would a screen share session help?

**Comment by ab997** [comment]
We can try, it will be interesting to see what went wrong. I am installing newest Visual Studio version 17.6.5 right now. I am expecting that on the original machine it (still) won't work, and on the new machine it will work.

Which time works for you?

**Comment by ErikEJ** [comment]
@ab997 I am in CET (Central Europe) timezone  - so between 8 - 15 CET would be fine

**Comment by ab997** [comment]
I am CET as well and this time is OK for me

**Comment by ErikEJ** [comment]
Feel free to reach out via email, and I will invite to a Teams call - ejlskov at hotmail dot com

**Comment by ab997** [comment]
I have sent you an email. Thanks

**Comment by ErikEJ** [comment]
@ab997 Could you try the latest build (.1538) when it is published?

**Comment by ab997** [comment]
The machine which had the bug is not available to me anymore

**Comment by ErikEJ** [comment]
Problem solved! :-D
