### ISSUE TITLE
How to implement table splitting?

### ISSUE THREAD

**Issue by GET-Paul** [ErikEJ/EFCorePowerTools#1858]
I am using the Power Tools to speed up an EFCore7 rebuild of an old EF6 database first desktop application. Some of our larger tables used table splitting to keep some of the lesser needed data from constantly being pulled down. [https://learn.microsoft.com/en-us/ef/core/modeling/table-splitting#table-splitting](url)

How would I go about implementing this in a way that it was applied every time I refreshed my power tools config?

**Comment by ErikEJ** [comment]
Implement OnModelCreatingPartial in a partial DbContext class and add the 2 spilt entities there?

**Comment by ErikEJ** [comment]
You could also just use projection to a DTO perhaps?

**Comment by GET-Paul** [comment]
DTO projection would work perfectly in this case. Thanks. Was so focused on reproducing the ef6 edmx that this hadn't occurred to me.

I'll have a play with what can be done in OnModelCreatingPartial as a side task though.

**Comment by ErikEJ** [comment]
If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
