### ISSUE TITLE
When upgrading to the latest version of the tool, an error is reported when using the CodeFirst migration tool

### ISSUE THREAD

**Issue by vipwan** [ErikEJ/EFCorePowerTools#1859]
Describe what is not working as expected.

It should be related to the removal of **Netcore3** support 

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/13956765/06c0dcdd-60a2-457e-a936-923854447712)

- EF Core version in use: EF Core 7

- EF Core Power Tools version: 2.5.1514

- Database engine: SQL Server

- Visual Studio version: Visual Studio 2022

**Comment by vipwan** [comment]
> Maybe, ut I doubt it. Do you have the .NET 7 runtime installed?

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/13956765/8e02d12e-cd95-4cc7-8025-dd6b02364a88)

**Comment by ErikEJ** [comment]
I will try to repro.

**Comment by ErikEJ** [comment]
@vipwan I am unable to repro, makes sure you set the correct startup project and that your project builds.

See this for more tips: https://github.com/ErikEJ/EFCorePowerTools/wiki/Inspect-your-DbContext-model#challenges

**Comment by vipwan** [comment]
> 
The issue has been resolved due to upgrading Microsoft.EntityFrameworkCore.* 7.0.7 - > 7.0.8 , jsut requires a rollback version   😭

**Comment by ErikEJ** [comment]
Great news, and thanks for the update.

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
