### ISSUE TITLE
Need alternate  Solution to use with EF Core 3.1 

### ISSUE THREAD

**Issue by SapkalArun** [ErikEJ/EFCorePowerTools#1860]
My projects are using EF Core 3.1 with postgreSQL and i am  not in the  position  to migrate them in a flash to EF Core 7.0  . i took update for EF Core Power tools  yesterday since then i am not able to refresh  my  entity as in latest version the  support for EF core 3.2 removed  . 

is  there  any alternative  available  to  use EF Core Power tools with supporting EF Core 3.1 .  

My work is  completly stuck due to this . Please  help me .

**Comment by ErikEJ** [comment]
@SapkalArun Assume you are aware that .NET 3.1 went out of support last year? But you can download an unsupported older version of the extension from the tools folder in this repo.

**Comment by ErikEJ** [comment]
If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by SapkalArun** [comment]
Hi ErikEJ , I tried everything  possible  to  install  the unsupported VSIX in tools  folder but not  able to install those  VSIX  . Requesting  you  if possible  please  provide  the  steps  how I can install those  VSIX  in my VS.  It will  really help  me  . blocked   since past  two days  .

**Comment by ErikEJ** [comment]
Download the .zip file, rename to .vsix abd double click to install

**Comment by ErikEJ** [comment]
If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
