### ISSUE TITLE
no supported target frameworks found in project

### ISSUE THREAD

**Issue by RogerVolScout** [ErikEJ/EFCorePowerTools#1863]
Reverse engineer fails

### Provide steps to reproduce

In visual studio 2022. load solution, right-mouse db project, select "EF Core Power Tools" --> "Reverse Engineer"

open output tab, select extensions.  

System.InvalidOperationException: no supported target frameworks found in project
   at (CodeGenerationMode UsedMode, IList<CodeGenerationItem> AllowedVersions) EFCorePowerTools.Helpers.ReverseEngineerHelper.CalculateAllowedVersions(CodeGenerationMode codeGenerationMode, Version minimumVersion)
   at async Task<bool> EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.ChooseDataBaseConnectionAsync(ReverseEngineerOptions options, Project project)
   at async Task EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.ReverseEngineerCodeFirstAsync(Project project, string optionsPath, bool onlyGenerate, bool fromSqlProj)

### Provide technical details

- EF Core version in use: (e.g. EF Core 2.2.6)

- Is Handlebars used: no

- Is T4 used: no

- Is .dacpac used: no

- EF Core Power Tools version: 2.5.1514

- Database engine: Azure SQL

- Visual Studio version: Visual Studio 2022

**Comment by RogerVolScout** [comment]
Digging into the changes I see that core 226 and framework are no longer supported.  

https://github.com/ErikEJ/EFCorePowerTools/commit/ea19125527ef6f4987bebee39361dfc17a91cb49

**Comment by Michael7181** [comment]
Same here with EF 3. No longer supported. Where can I download the previous version?

**Comment by vipwan** [comment]
> Same here with EF 3. No longer supported. Where can I download the previous version?

#1860

**Comment by ErikEJ** [comment]
Download the .zip file, rename to .vsix abd double click to install

**Comment by ErikEJ** [comment]
If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by RogerVolScout** [comment]
> Download the .zip file, rename to .vsix and double click to install

this works well, but VS 2022 does NOT honor unchecking the "Automatically update this extension" box.  

Regularly I have to uninstall the later version, and reinstall 2.5.1429, even when I uncheck the box.  

Love your tools, just wish using the older version did not just become complicated.

**Comment by ErikEJ** [comment]
@RogerVolScout this is not something I can assist you with, please report a bug to Visual Studio Community.

Why do you need to start on .1429??

**Comment by RogerVolScout** [comment]
1429 is the last release that still  reverse engineers to EF 2.2.6.  2.2.6 still works with framework 4.7 - 4.8.

**Comment by ErikEJ** [comment]
Thanks, but 2 and 3 are completely out of support.

**Comment by ErikEJ** [comment]
@RogerVolScout correct, 3.1 is the last version that works with .NET Framework
