### ISSUE TITLE
EF Core Not loading 

### ISSUE THREAD

**Issue by stevedrew41075** [ErikEJ/EFCorePowerTools#1869]
SetSite failed for package [EFCorePowerToolsPackage]Source: 'EFCorePowerTools' Description: Method not found: 'Microsoft.VisualStudio.Threading.JoinableTaskFactory Microsoft.VisualStudio.Shell.ThreadHelper.get_JoinableTaskFactory()'. System.MissingMethodException: Method not found: 'Microsoft.VisualStudio.Threading.JoinableTaskFactory Microsoft.VisualStudio.Shell.ThreadHelper.get_JoinableTaskFactory()'. at EFCorePowerTools.EFCorePowerToolsPackage.<InitializeAsync>d__11.MoveNext() at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine) at EFCorePowerTools.EFCorePowerToolsPackage.InitializeAsync(CancellationToken cancellationToken, IProgress`1 progress) at Microsoft.VisualStudio.Shell.AsyncPackage.<>c__DisplayClass21_0.<<Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize>b__1>d.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e) at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)

### Provide steps to reproduce

I added xUnit Dependency Injection on 7/11/2023 and rebooted VS2022 after running for many days and the above error popped up.  EF Core shows a last update on 7/10/2023 but I did not use it in the last few days so I an not certain when the error started.  I uninstalled EF Core and reinstalled an the error did not go away.  Closed and reopened VS2022 Community many times.

### Provide technical details

- EF Core version in use: (e.g. EF Core 7) - 2.5.15.14 

- Is Handlebars used: no/yes: I don't think so.

- Is T4 used: no/yes

- Is .dacpac used: no/yes

- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)

- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)

- Visual Studio version: (e.g. Visual Studio 2022)  VS 2022 Community

**Any help would be appreciated!**

**Comment by stevedrew41075** [comment]
Nevermind, it resolved by applying VS2022 updates.

**Comment by stevedrew41075** [comment]
Closed

**Comment by ErikEJ** [comment]
@stevedrew41075 Someone else reported this, would be nice to know which VS version you were using before the update

**Comment by stevedrew41075** [comment]
Sorry, I didn’t record it.
