### ISSUE TITLE
reverse engineering with if condition

### ISSUE THREAD

**Issue by HosamNouri** [ErikEJ/EFCorePowerTools#187]
Please could you help me to use reverse engineering with if condition like "{{#ifCond property-name "FirstName"}}" to generate a new attribute in a specific condition

**Comment by ErikEJ** [comment]
I assume you are referring to the Handlebars template? @tonysneed  - maybe you can assist?

**Comment by tonysneed** [comment]
@HosamNouri To accomplish this you will need to use [Handlebars Helpers and Transformers](https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#handlebars-helpers-and-transformers), which is only available from the command-line (not using the EF Core Power Tools) with the [EF Core CLI](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet).

**Comment by ErikEJ** [comment]
Closing, as this is not something that can be done using EF Core Power Tools
