### ISSUE TITLE
Unsupported version of the tool (.net 5.0)

### ISSUE THREAD

**Issue by mustafabaskoylu** [ErikEJ/EFCorePowerTools#1871]
I am using .NET core 5 and entity framework core 5. I have been using EF Core Power Tools for 1 year. 
I got the following error message when trying to use the updated version.

![efpowertools](https://github.com/ErikEJ/EFCorePowerTools/assets/82473619/5abc7f4c-3b74-4685-8238-96d8e5a454f6)

I found out that the current version of EF Core Power Tools no longer supports .net 5.0

When I searched the subject on the net, I saw that the following similar problem was shared from the link below.

https://stackoverflow.com/a/74971139

Can you provide an unsupported version of the tool that works with EF core 5.

**Comment by ErikEJ** [comment]
I assume both of you are aware that .NET 5 has been out of support for more than a year:

https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core#lifecycle

**Comment by ErikEJ** [comment]
@mustafabaskoylu What prevents you from updating to EF Core 6?

**Comment by ErikEJ** [comment]
You can download an unsupported build from here: https://github.com/ErikEJ/EFCorePowerTools/tree/master/tools%2FVS2019Support

**Comment by mustafabaskoylu** [comment]
I don't have time to upgrade to 6.0 yet as it is a large and heavily developed project. Thank you for your support

Best regards
