### ISSUE TITLE
ef core power tools does not work with tables with a key of 2 columns

### ISSUE THREAD

**Issue by phinq190778** [ErikEJ/EFCorePowerTools#1872]
Hi teacher Erik
I'm having an error of ef core power tools that doesn't work with tables with a key of 2 columns
![twotable](https://github.com/ErikEJ/EFCorePowerTools/assets/56870914/0d8363fd-902f-4bf4-b6c1-650a00594671)
and here is the command to create the table
CREATE TABLE [dbo].[Menu](
	[Code] [nvarchar](50) NOT NULL,
	[Text] [nvarchar](250) NULL,
	[IconCls] [nvarchar](50) NULL,
	[State] [nvarchar](50) NULL,
	[ParentCode] [nvarchar](50) NULL,
	[Active] [bit] NULL,
 CONSTRAINT [PK_Menu] PRIMARY KEY CLUSTERED 
(
	[Code] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[ACCOUNT](
	[Users] [nvarchar](50) NOT NULL,
	[UsersName] [nvarchar](50) NULL,
	[Password] [nvarchar](50) NULL,
	[Birthday] [nvarchar](50) NULL,
	[Mobile] [nvarchar](50) NULL,
	[Address] [nvarchar](50) NULL,
	[IdNhanVIen] [nvarchar](50) NULL,
 CONSTRAINT [PK_ACCOUNT] PRIMARY KEY CLUSTERED 
(
	[Users] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[RoleGroup](
	[RoleCode] [nvarchar](50) NOT NULL,
	[RoleName] [nvarchar](250) NULL,
 CONSTRAINT [PK_Roles] PRIMARY KEY CLUSTERED 
(
	[RoleCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[RoleGroupMenu](
	[RoleCode] [nvarchar](50) NOT NULL,
	[MenuCode] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_RoleGroupMenu] PRIMARY KEY CLUSTERED 
(
	[RoleCode] ASC,
	[MenuCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[RoleGroupMenu]  WITH CHECK ADD  CONSTRAINT [FK_RoleGroupMenu_Menu] FOREIGN KEY([MenuCode])
REFERENCES [dbo].[Menu] ([Code])
GO

ALTER TABLE [dbo].[RoleGroupMenu] CHECK CONSTRAINT [FK_RoleGroupMenu_Menu]
GO

ALTER TABLE [dbo].[RoleGroupMenu]  WITH CHECK ADD  CONSTRAINT [FK_RoleGroupMenu_RoleGroup] FOREIGN KEY([RoleCode])
REFERENCES [dbo].[RoleGroup] ([RoleCode])
GO

ALTER TABLE [dbo].[RoleGroupMenu] CHECK CONSTRAINT [FK_RoleGroupMenu_RoleGroup]
GO

CREATE TABLE [dbo].[RoleGroupUser](
	[RoleCode] [nvarchar](50) NOT NULL,
	[Users] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_RoleGroupUser] PRIMARY KEY CLUSTERED 
(
	[RoleCode] ASC,
	[Users] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[RoleGroupUser]  WITH CHECK ADD  CONSTRAINT [FK_RoleGroupUser_ACCOUNT] FOREIGN KEY([Users])
REFERENCES [dbo].[ACCOUNT] ([Users])
GO

ALTER TABLE [dbo].[RoleGroupUser] CHECK CONSTRAINT [FK_RoleGroupUser_ACCOUNT]
GO

ALTER TABLE [dbo].[RoleGroupUser]  WITH CHECK ADD  CONSTRAINT [FK_RoleGroupUser_RoleGroup] FOREIGN KEY([RoleCode])
REFERENCES [dbo].[RoleGroup] ([RoleCode])
GO

ALTER TABLE [dbo].[RoleGroupUser] CHECK CONSTRAINT [FK_RoleGroupUser_RoleGroup]
GO
Can you help me to know the cause?

**Comment by phinq190778** [comment]
I am using **ef core power tools=>Reverse Engineer**

**Comment by ErikEJ** [comment]
@phinq190778 This is by design: https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-6.0/breaking-changes#many-to-many

I have an advanced option to bring the many to many table back if you think you need it.

**Comment by phinq190778** [comment]
does that mean ef core power tool can't handle this case?

**Comment by ErikEJ** [comment]
No, it can handle it ...

**Comment by phinq190778** [comment]
Thank you, I used a way to add a non-key column to those 2 tables and it worked.
