### ISSUE TITLE
Feature request: flag to control temporal table support from DACPAC

### ISSUE THREAD

**Issue by IanKemp** [ErikEJ/EFCorePowerTools#1873]
While it's great that you've [added this support](https://github.com/ErikEJ/EFCorePowerTools/issues/1851), it unfortunately has the potential to massively break code originally using older versions of EFPT that were generating these temporal start/end properties, if said code is referencing those properties for whatever reason.

In our case it is to ignore them when mapping from generated DB entity to DTO, which means this change also requires us to update our codebase to remove all those mappings... not optimal. Of course, if you were actually using these properties for querying or display, then you will be much worse off.

Please can you add a flag to control whether the new behaviour, or the legacy non-temporal-aware behaviour, is used? Sensible default would be to ON but in our case we'd disable it until we had some capacity to clean up all the references to the temporal properties.

**This might actually be a bug, since in our SQL these columns are _not_ marked with the `hidden` attribute.** 

### Provide technical details

- Exact Visual Studio version: Visual Studio Professional 2022 17.6.5

- EF Core Power Tools version: 2.5.1535

- Database engine: SQL Server 2019

- EF Core version in use: EF Core 6

- Is Handlebars used: no

- Is T4 used: no

- Is .dacpac used: yes

**Comment by IanKemp** [comment]
All I can say is that we haven't changed anything in our DB project, the only thing that's changed is the version of EFPT, and previously these properties were always being generated. The SQL:

```sql
CREATE TABLE [dbo].[Something]
(
    [Id] INT IDENTITY(1,1) NOT NULL,
    [SysStartTimeUtc] DATETIME2 GENERATED ALWAYS AS ROW START CONSTRAINT DF_Something_SysStart DEFAULT SYSUTCDATETIME(),
    [SysEndTimeUtc] DATETIME2 GENERATED ALWAYS AS ROW END CONSTRAINT DF_Something_SysEnd DEFAULT CONVERT(DATETIME2, '9999-12-31 23:59:59.9999999'),
    [RowVersion] TIMESTAMP NOT NULL,
 CONSTRAINT [PK_Something] PRIMARY KEY CLUSTERED
(
    [Id] ASC
)WITH (
    PERIOD FOR SYSTEM_TIME (SysStartTimeUtc, SysEndTimeUtc)
) ON [PRIMARY]
WITH(SYSTEM_VERSIONING = ON (HISTORY_TABLE = [dbo].[Something_History],  DATA_CONSISTENCY_CHECK = ON))
GO
```

Previously generating against a DACPAC containing this SQL would result in `SysStartTimeUtc` and `SysEndTimeUtc` properties on the generated `Something` entity; as of 2.5.1535 it does not.

**Comment by ErikEJ** [comment]
@IanKemp You are correct, but scaffolding from a live database would not include the columns either. They were included by mistake when scaffolding from a .dacpac earlier.

**Comment by IanKemp** [comment]
Ah, that would explain it. From my team's viewpoint it is a bug or regression in EFPT since the new version causes our code to break... even though the EFPT change causing that breakage is actually a fix for previously incorrect behaviour! So while we'd appreciate a flag to allow for the old "buggy" behaviour from EFPT, I can understand why you'd be reluctant to add such.

As such I'm going to tell my team to stick to EFPT version 2.5.1429 until we get some time to fully analyse our usages of these properties and determine if we can get away with just removing them and using the newer versions of EFPT. If not we'll stick to 2.5.1429 until we do the jump to .NET 8 and EF Core 8 after those releases.

**Comment by ErikEJ** [comment]
@IanKemp Cool. They are actually available as "shadow" properties, and can be referred to as such:

https://learn.microsoft.com/en-us/ef/core/modeling/shadow-properties#accessing-shadow-properties

**Comment by IanKemp** [comment]
@ErikEJ Sorry to bother again, but do you know if it's possible to download a specific (old) version of EFPT? I tried using https://www.vsixgallery.com/extensions/f4c4712c-ceae-4803-8e52-0e2049d5de9f/EF%20Core%20Power%20Tools%20v2.5.1429.vsix but regardless of the version number I use in the URL, that always gives me the latest nightly build...

**Comment by ErikEJ** [comment]
As I said earlier, the missing properties are actually available as "shadow" properties, and can be referred to as such:

https://learn.microsoft.com/en-us/ef/core/modeling/shadow-properties#accessing-shadow-properties

But I have a couple of completely unsupported builds available in the tools folder in this repo
