### ISSUE TITLE
Only showing 2 menu

### ISSUE THREAD

**Issue by rekhasf** [ErikEJ/EFCorePowerTools#1877]
Only showing this two menu
others menu is missing (reverse engineering, etc)
Version 2.5.1544
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/66454118/863ec129-d717-4970-953f-6913c16a218c)

**Comment by ErikEJ** [comment]
EF Core 3.1 and 5 are no longer supported, you should consider upgrading to a supported version. In the tools folder in this repo you can get an older unsupported build.
