### ISSUE TITLE
Renaming collections and entities during reverse engineering

### ISSUE THREAD

**Issue by jwatkin** [ErikEJ/EFCorePowerTools#188]
For the following examples, how would one instruct the reverse engineering operation to use the name mappings with an external file provided during the reverse engineering operation?

The "collection name" would be used for the DbSet name and any other Dolphin collections that might be generated. Assume there are more tables included in this operation.

**EXAMPLE 1**
Table Name: group_of_dolphins
Collection Name: PodOfDolphins
Entity Name: Dolphin

If the "Example 1" mapping isn't possible, what about this easier example:

**EXAMPLE 2**
Table Name: group_of_dolphins
Collection Name: Dolphins
Entity Name: Dolphin

This is for Entity Framework Core 2.2.2.

My apologies if I've overlooked some documentation. I've tried experimenting with an efpt.renaming.json file, but I couldn't make it work.

Thank you.

**Comment by ErikEJ** [comment]
The renaming feature is currently lacking documentation. 

What does "could not make it work" mean??

**Comment by jwatkin** [comment]
I meant that my attempt at using an efpt.renaming.json file didn't have any effect on the reverse engineering of the database. I'm most likely doing something wrong. I was guessing, but I tried every combination I could think of.

Let me try it again and I will document my steps and post them here afterwards. Unless, you have a better idea. Thank you for all of your work on this.

**Comment by ErikEJ** [comment]
Did you place the file in the project folder (with the csproj file)?

**Comment by jwatkin** [comment]
Yes.

**Comment by jwatkin** [comment]
Is this the correct file format for the efpt.renaming.json file?
[https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/EFCorePowerTools/efpt.renaming.json](https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/EFCorePowerTools/efpt.renaming.json)

**Comment by ErikEJ** [comment]
Yes, that is the format

**Comment by ErikEJ** [comment]
See https://github.com/ErikEJ/EFCorePowerTools/issues/128#issuecomment-439692246

**Comment by jwatkin** [comment]
It's working now, perfectly! Thank you.

I'm guessing that when I tried it previously I must have made a mistake in my UseSchemaName or SchemaName setting. Unfortunately, I didn't preserve that file. Here are the settings that work for me.
`[
  {
    "UseSchemaName": false,
    "SchemaName": "dbo",
    "Tables": [
      {
        "Name": "course_sched",
        "NewName":  "CourseOfferings",
        "Columns": [
          {
            "Name": "subj_area_cd",
            "NewName": "SubjectArea"
          }
        ]
      }
    ]
  }
]`

**Comment by ErikEJ** [comment]
Great, I have already logged an issue to make this feature more visible, and I should also publish a wiki post.

**Comment by jwatkin** [comment]
I've discovered what I was originally doing wrong before we fixed my issue. In my `efpt.renaming.json` file I had originally used a table name value of `dbo.course_sched`, which is incorrect and will fail silently because presumably the table can't be found. The correct table name value is `course_sched`, without the `dbo.` prefix, as shown in my sample `efpt.renaming.json` file above.

However, in the separate and different `efpt.config.json` file generated by `EF Core Power Tools`, the table names do use the `dbo.` prefix. `efpt.config.json` is a different file, for a different purpose, and consequently has a different layout.

**Comment by ErikEJ** [comment]
That makes sense, good input to the wiki post

**Comment by intomneato** [comment]
@ErikEJ 
This thread is the closest I've found to my issue, but I'm either still missing something or trying to do something that can't be done. Hoping for some guidance...
Two central tables in my sql server database are Organizations and Locations. Locations already had OrganizationId and lots of code querying that data (An organization has many locations). I need to add BillToOrganizationId to Locations for new features paid for by a different Organization. So now there's two FKs back to Organizations on Locations and I get two Location collections on my Organization object once reverse engineered with power tools. 
Is there a way to rename one of these collections?
I end up with:
LocationOrganizations = new HashSet<Location>();
LocationBillToOrganizations = new HashSet<Location>();
This breaks existing code looking for Organizations.Locations now called LocationOrganizations. I could attempt some find/replace in solution, but I also find it semantically unpleasant so a rename would be preferred. I don't care so much about the other collection being called LocationBillToOrganizations as it won't be used so much and will be used exclusively in new code. I dropped the constraint on the new BillTo field and reran the reverse engineer and got back to the Organizations.Locations I was looking for. So the two keys are the issue
Suggestions on renaming one of the collections?   Thanks so much.

**Comment by ErikEJ** [comment]
@intomneato  Have you tried a renaming file?

**Comment by intomneato** [comment]
yes, it looked like this... I'm not sure I did it right...
[
  {
    "UseSchemaName": false,
    "SchemaName": "dbo",
    "Tables": [
      {
        "Name": "Organizations",
        "Columns": [
          {
            "Name": "LocationOrganizations",
            "NewName": "Locations"
          }
        ]
      }
    ]
  }
]

**Comment by ErikEJ** [comment]
I think this is not possible, sorry

**Comment by intomneato** [comment]
Okay.  Thanks for your time

**Comment by pmonte** [comment]
I also experienced probs ranaming a column using efpt.renaming.json. In my case the problem was (well, is) that everything is working fine unless I check "Use table and column name directy from the database". With that option checked the column is NOT renamed. @ErikEJ should I open an issue? Can you look into this?

**Comment by ErikEJ** [comment]
Please open a new issue

**Comment by pmonte** [comment]
Thanks, done: https://github.com/ErikEJ/EFCorePowerTools/issues/407#issue-638347190
