### ISSUE TITLE
Non-checked database objects

### ISSUE THREAD

**Issue by boiche** [ErikEJ/EFCorePowerTools#1881]
Steps to reproduce

1. Create a git branch
2. Push a mapped context to it
3. Create second git branch
4. Merge first branch into second
5. Open 'Reverse Engineer'
6. Head to 'Choose Your Database Objects'

Expected result: All already mapped elements are checked

Actual result: Some of the mapped object are not checked. This leads to removing them from the context when completing reverse engineer.

Тechnical details

- Visual Studio version: Visual Studio Community 2022 17.5.4
- EF Core Power Tools version: 2.5.1429
- Database engine: MS SQL Server
- EF Core version in use: 7.0.5
- Is Handlebars used: no
- Is T4 used: no
- Is .dacpac used: no

**Comment by ErikEJ** [comment]
How are you treating the efpt.config.json file?

**Comment by ErikEJ** [comment]
Ping?

**Comment by boiche** [comment]
I expected all mapped entities to be checked. Otherwise some mapped objects when unchecked are removed from the context and I'm aware of it when I create PRs. Haven't dived into the code base, but I think the tool should be checking what Entities and/or DbSets has the prompted context already mapped.
About the efpt.config.json I don't change it manually. Whatever the EF Power Tools decide affect this .json.

**Comment by ErikEJ** [comment]
The best I can offer is the advanced option to include all objects, it is up to you to review changes to the config file.
