### ISSUE TITLE
Stored Procedure Default Schema

### ISSUE THREAD

**Issue by airwedge1** [ErikEJ/EFCorePowerTools#1882]
I have a requirement where I need to store database tables in a variable schema per implementation.  This was pretty straight forward by using OnModelCeratingPartial and calling HasDefaultSchema.  However, the stored procedures are hard coded in the power tools template.  I'd like to see this adjusted to for example: _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [" + _context.Model.GetDefaultSchema()+"]

### Provide technical details

- Exact Visual Studio version: 17.6.4

- EF Core Power Tools version: 2.5.1544

- Database engine: SQL Server

- EF Core version in use: EF Core 7

- Is Handlebars used: no

- Is T4 used: no

- Is .dacpac used: no

**Comment by ErikEJ** [comment]
Interested in doing a PR?

**Comment by ErikEJ** [comment]
@airwedge1 I think it should be an opt-in option to avoid regressions

**Comment by ErikEJ** [comment]
@airwedge1 Maybe you could just do this in a post-processing script? Using postrun.cmd ?

**Comment by airwedge1** [comment]
I agree.



________________________________
