### ISSUE TITLE
Feature Request: nameof(<TDbEntity>) instead of "TDbEntity"

### ISSUE THREAD

**Issue by visionarycoder** [ErikEJ/EFCorePowerTools#1883]
# Feature Request
Please change from the magic-string used to name the table to leverage nameof(MyTable).

## Existing:
```
modelBuilder.Entity<MyTable>(entity =>
        {
            ...
            entity.ToTable("MyTable");
            ...
         }
```

## Requested:
```
modelBuilder.Entity<MyTable>(entity =>
        {
            ...
            entity.ToTable(nameof(MyTable);
            ...
         }
```

**Comment by ErikEJ** [comment]
@visionarycoder This is by design, as the table name can be a non-C# identifier.

**Comment by ErikEJ** [comment]
"A table.silly" is a perfectly valid table name with SQL Server.
