### ISSUE TITLE
Comment Encoding Issue for Traditional Chinese Users

### ISSUE THREAD

**Issue by aa846301** [ErikEJ/EFCorePowerTools#1885]
- Exact Visual Studio version:Visual Studio Community 2022 17.6.3

- EF Core Power Tools version: 2.5.1429

- Database engine: SQL Server

- EF Core version in use: EF Core 5
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/6349108/e2c63a94-c43a-4f25-99a1-6229e16e5ad2)

- Is Handlebars used: no

- Is T4 used: no

- Is .dacpac used: no
![螢幕擷取畫面 2023-07-19 182233](https://github.com/ErikEJ/EFCorePowerTools/assets/6349108/0ac07a28-2b0c-4349-8adf-7e6623eea8a8)

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/6349108/842d8446-72ef-4a8f-a070-712f2404dbe7)

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/6349108/b2040b4c-88cb-4d63-83f5-dfe3cf40f2cd)

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/6349108/645a2ee5-c673-492f-8feb-90e0e5f1b20e)

I am a Traditional Chinese user. When I use EF Core Power Tools to reverse engineer my database, I've noticed that Chinese comments are encoded, similar to the issue #1093 that was previously reported. Can you please help me understand why this is happening and how it can be resolved?

Thank you in advance for your help.

**Comment by ErikEJ** [comment]
You are using an old, unsupported version of the extension and of EF Core. As I read #1093 this issue no longer occurs when using EF Core 6 with Handlebars.

**Comment by aa846301** [comment]
Alright, my company restricts the version we use, but when I tried it on the updated .NET 6, this issue did not occur. Thank you for your reply.
