### ISSUE TITLE
Server Connection String Not Complete on new and Changes on Update

### ISSUE THREAD

**Issue by rdelgado-ii** [ErikEJ/EFCorePowerTools#1886]
Recently, I change the EF Core Version to 7.  This required the "TrustServerCertificate=True".  I first tried to recreate the strings using the dialog and it did not add this to the connection string in the datacontextfile.  I then manually added it.  I found that the next time I edited the data, the trustservercerificate was no longer there and had to manually add it back.

1. It is not saving trustservercerificate when creating a new connection.
2. It is removing it when updating the datacontext.

### Provide technical details

- Exact Visual Studio version: 2022 17.5.3

- EF Core Power Tools version: 2.5.1554

- Database engine: SQL Server

- EF Core version in use:  EF Core 7

- Is Handlebars used: no

- Is T4 used: no

- Is .dacpac used: no/yes

**Comment by ErikEJ** [comment]
You should avoid generating the connection string for obvious reasons.

That being said, please provide exact repro steps, for example with screenshots.

**Comment by rdelgado-ii** [comment]
You are absolutely correct.  Just having unchecking the save connection string has corrected the issue and it is now using the proper connection strings.

To reproduce was nothing more than using the power tools edit utility, do whatever and save at the end.  The connection string in the datacontext had the trustservercerticate removed.  Also just creating a new connection and would not save it either.

Thanks
