### ISSUE TITLE
I have lost the Reverse Engineer functionality, how can I fix it

### ISSUE THREAD

**Issue by khanhtungmtp** [ErikEJ/EFCorePowerTools#1888]
"I have lost the Reverse Engineer functionality, how can I fix it?" I am using Microsoft Visual Studio Community 2022 (64-bit) - Version 17.6.5, EF Core Power Tools :Version	2.5.1544. screenshot [https://drive.google.com/file/d/153DkR_IU6fKVhz-N1BtiahG9TUvsz7Bi/view?usp=sharing](url)

**Comment by ErikEJ** [comment]
@khanhtungmtp It is because I have stopped supporting EF Core 5 and earlier, they are out of support. You can download an older unsupported build of the extension from the tools folder in this repo, but you should update to a supported version.
