### ISSUE TITLE
EF Core PowerTools is causing slowdown in .NET Framework 4.7.2 solution

### ISSUE THREAD

**Issue by Montago** [ErikEJ/EFCorePowerTools#1889]
I have a .NET Framework 4.7.2 solution which is slowed down by this extension. 

The solution is an Outlook Addin + MVC5 website with Swagger API + Microsoft API Helppage. 

The slowdown doesnt happen for other .NET Framework 4.7.2 projects and doesn't happen with .NET 6-7 projects neither. 

There are 2 EDMX files in the web project, both created with the native EDMX tool in Visual Studio. 

I'm running Visual Studio 2022 version 17.6.5 (newest stable release)

**Comment by Montago** [comment]
It's Visual Studio itself which is slowed down. 
I dont use EF Core PowerTools for this project. 

I'm not sure if i can share the project - it's quite finicky to get up and running and contain sensitive code..

**Comment by ErikEJ** [comment]
I "just" need the .csproj files (basically the header of them) - to see if I can reproduce. Otherwise it is very hard for me to provide support for you.

**Comment by Montago** [comment]
It seems that the slowdown only occurs when right clicking on the Project to open the context menu.

**Comment by Montago** [comment]
> I "just" need the .csproj files (basically the header of them) - to see if I can reproduce. Otherwise it is very hard for me to provide support for you.

I'll send you the csproj file

**Comment by Montago** [comment]
[ADTOutlookCRMWebAddInWeb.zip](https://github.com/ErikEJ/EFCorePowerTools/files/12105456/ADTOutlookCRMWebAddInWeb.zip)

here you go

**Comment by ErikEJ** [comment]
I am unable to reproduce - how do you determine that it is Power Tools causing the slowdown? Maybe a screen share session would help?

**Comment by Montago** [comment]
After some investigation and help from you erik, 

I found the cause of the problem is that THIS distinct project has 600 MB / 90.000 node_modules installed. 

After deleting them, the context menu has no longer any problems. 

So i guess its a mix of Visual Studio 2022 and the EF PowerTools Extension acting funny.
