### ISSUE TITLE
Is it possible to use TimeStamp attribute? 

### ISSUE THREAD

**Issue by nikriaz** [ErikEJ/EFCorePowerTools#1890]
Many thanks for the great tool you're maintaining. 

Quick question: Is the TimeStamp attribute for the EF built-in concurency handling somehow supported? MS SQL.

**Comment by ErikEJ** [comment]
Do you mean with reverse engineering? Yes, it is - timestamp/rowversion

**Comment by nikriaz** [comment]
Yes, in reverse engineering. Would you be so kind to explain how to use this? Should I create some specific column in SQL or may be create another part of partial class and annotate a property? Sorry for asking - can't find this in docs

**Comment by ErikEJ** [comment]
You just need to add a timestamp/rowversion column to your table, and reverse engineer.

https://learn.microsoft.com/en-us/ef/core/saving/concurrency?tabs=data-annotations#native-database-generated-concurrency-tokens
