### ISSUE TITLE
Multiple Attributes

### ISSUE THREAD

**Issue by karls4** [ErikEJ/EFCorePowerTools#1892]
When reverse generating a stored proc that has spaces in the column name and a column type of decimal it generates two [Column] attributes which throws an error.

Please see below error

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/22108543/13029b65-c80c-4f93-9262-b2603ca2536c)

Whats needed to fix it
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/22108543/9134b64d-a803-4492-9323-506e11e96d76)

**Comment by karls4** [comment]
Hi, I'm currently using 2.5.1429

**Comment by ErikEJ** [comment]
2.5.1429 is an unsupported version of the tool, and this has been fixed in the latest version.
