### ISSUE TITLE
Feature Suggestion - Source Control Auto Checkout

### ISSUE THREAD

**Issue by rhubarbjustin** [ErikEJ/EFCorePowerTools#1893]
Create a bug report to help improve the tools, propose a new feature, or just ask a question.

### Provide steps to reproduce

Feature Suggestion

### Provide technical details

Hi Erik. Thanks for creating this tool. I've not found a better way of reverse engineering databases. One suggestion I have is for the tool to automatically check out files that are being changed from TFS or GIT in the visual studio environment. I don't know how easy this would be to achieve. This would just avoid having to check out the entire data project before running Reverse Engineer.

**Comment by ErikEJ** [comment]
@rhubarbjustin I do not understand the need for that with git ...

**Comment by rhubarbjustin** [comment]
Hi. Sorry, you are right. I am using TFS in Azure Dev Ops which has the check in/out model which is why I have the issue. I guess this is somewhat old fashioned now.

**Comment by ErikEJ** [comment]
Yeah, maybe consider swithcing to git: https://learn.microsoft.com/en-us/devops/develop/git/migrate-from-tfvc-to-git
