### ISSUE TITLE
Missing Refresh on eftp.config.json file

### ISSUE THREAD

**Issue by rbrynteson** [ErikEJ/EFCorePowerTools#1895]
Create a bug report to help improve the tools, propose a new feature, or just ask a question.

### Provide steps to reproduce
Just curious if there is a place to force the Power Tools - Refresh.  This has worked fine for months (years) but when I right click on the eftp.config.json file, I no longer have the option to do a refresh.

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/17522044/f2d38533-8227-4918-ba1b-4b2ff1193624)

However, if I right-click on the solution, I clearly can see the Power Tools installed.

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/17522044/a5c20abb-1657-46db-b1ba-ad0b60c784e5)

I have tried disabled, restart VS Studio, enable, restart.  Also, removed completed and added back in.  Doesn't work in this one solution anymore.  On the same computer, different solution, the refresh button appears and works fine.

### Provide technical details

- Exact Visual Studio version: (e.g. Visual Studio 2022 17.6.2)
Visual Studio 17.7.0 Preview 5

- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
2.5.1544

- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)
Azure SQL

- EF Core version in use: (e.g. EF Core 7)
EF Core 5.0.17

- Is Handlebars used: no/yes
No

- Is T4 used: no/yes
No

- Is .dacpac used: no/yes
No

**Comment by ErikEJ** [comment]
Most likely because EF Core 3.1 is no longer supported, including any .NET Framework projects.

There is an old, unsupported package available if you really need it.

**Comment by rbrynteson** [comment]
OK, I've been holding off but this is the kick in the pants needed.  I'll upgrade the project to .NET 7/Core 7.

**Comment by ErikEJ** [comment]
Cool. 
If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by huatoanduong** [comment]
Hi Erik,

I'm facing a same issue,

Where can I find the old package?

Thank you

**Comment by huatoanduong** [comment]
Really thanks,

It was a known technical debt, but upgrading whole system will require a huge effort.
We have a plan to upgrade to .net 7 this Sep

Thanks again,
