### ISSUE TITLE
Installation Issue?

### ISSUE THREAD

**Issue by CliffConway** [ErikEJ/EFCorePowerTools#1896]
I have started using VS2022 and the power tools install and work as usual. However, I have had to re-install VS2019 (related to a project that uses MySQL) but after re-installing VS2019 the power tools are no longer an option in VS2019 (Presumably because the power tool installer (VSIX) was installed at a time when VS2019 was not installed?). Is the only way around this to de-install power tools and re-install them to ensure the tool is added to VS2019? How to de-install power tools?

Thanks in advance

**Comment by ErikEJ** [comment]
Visual Studio 2019 is no longer supported by this tool. But you can Uninstall via extension mananger, and then use an old unsupported installer available in the tools folder in this repo.

**Comment by CliffConway** [comment]
The fact that I need to access an MySQL database and the Oracle tools does not yet support VS2022 but does support VS2019 and your tool does not support VS2019 is a headache.

Where can I get an old installer for VS2019 - I have tried looking but cannot find one.

Thanks in advance,

Cliff

**Comment by ErikEJ** [comment]
You can use MySQL with EF Core Power Tools in VS 2022 as [described in the wiki](https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#custom-connections)

The older, unsupported package is in the tools folder in the source repo here.

**Comment by CliffConway** [comment]
Apologies for more questions.

I followed the wiki and I got as far as the section titled "Choose database objects" and then I got a screen with lots of icons of my database tables' names instead of the expected screen with the tree selection tools for the tables. I suspect this might be because to get to the previous section (where I selected MySQL and supplied my connection string) I selected the "EF Core Power Tools" in my VS Solution Explorer and the options were:-

- Visualise Database Scheme (preview)

- About

I suspect I have done something wrong at the installation of the Power Tools. Does this make sense? Can you tell what I am doing wrong?

Thanks in advance,

Cliff

**Comment by ErikEJ** [comment]
What Power Tools version are you running and what type of project do you have? (Share the top of your .csproj file)

Sounds like you are NOT running the older version.

**Comment by CliffConway** [comment]
Thanks Erik,

I am running version 2.5.1544 and after your previous email about the ability to run in VS2022 i download and installed the most recent version (I believe).

Top part of .csprog file :-

<?xml version="1.0" encoding="utf-8"?>
<edmx:Edmx Version="3.0" xmlns:edmx="http://schemas.microsoft.com/ado/2009/11/edmx">

<edmx:Runtime>

<edmx:StorageModels>
<Schema Namespace="joomlatheme_elecessenModel.Store" Provider="MySql.Data.MySqlClient" ProviderManifestToken="8.0.33.1" Alias="Self" xmlns:store="http://schemas.microsoft.com/ado/2007/12/edm/EntityStoreSchemaGenerator" xmlns:customannotation="http://schemas.microsoft.com/ado/2013/11/edm/customannotation" xmlns="http://schemas.microsoft.com/ado/2009/11/edm/ssdl">
<EntityType Name="ps_address">
<Key>
<PropertyRef Name="id_address" />
</Key>
<Property Name="id_address" Type="uint" StoreGeneratedPattern="Identity" Nullable="false" />
<Property Name="id_country" Type="uint" Nullable="false" />
<Property Name="id_state" Type="uint" Nullable="false" />
<Property Name="id_customer" Type="uint" Nullable="false" />

**Comment by ErikEJ** [comment]
Cool, but the latest version only supports EF Core 6 and 7

**Comment by CliffConway** [comment]
Agh!! Thanks Erik for all your help

Cliff
