### ISSUE TITLE
EF Core power tools latest version 2.5.1544 is not working for .net core 2.2 project

### ISSUE THREAD

**Issue by nirushinevis** [ErikEJ/EFCorePowerTools#1897]
What is the supported EF core power tools version for .NET core 2.2 project. Can you please provide the link to download the VSIX. Latest version is not supported and I cant see the "Reverse Engineer" option as well.

**Comment by ErikEJ** [comment]
There is no supported or unsupported EF Core Power Tools package for 2.2. There is an unsupported package for 3.1

**Comment by nirushinevis** [comment]
After I installed EF Core power tools latest version 2.5.1544, "Reverse Engineer" option is not available. 
![ef](https://github.com/ErikEJ/EFCorePowerTools/assets/136785044/84b3551c-5cdf-4013-9425-59b71aa0b46c)

**Comment by ErikEJ** [comment]
Correct, only EF Core 5 and 6 are supported, all older version are out of support. You can find an older unsupported version of the package in the tools folder in this repo.

**Comment by nirushinevis** [comment]
Ok, thanks a lot for the quick response.
