### ISSUE TITLE
[Unicode(false)] attribute and HasNoKey() configuration problem on reverse engineering from DB

### ISSUE THREAD

**Issue by PatrykWalaski** [ErikEJ/EFCorePowerTools#1898]
Hey, i've noticed 2 problems, maybe there is a solution to them that i'am missing but i thought i'll leave some feedback and maybe You could help me or fix these things in next update @ErikEJ if You will consider them as real bugs 😅 

1.

First problem - on reverse engineering a table from database the [Unicode(false)] is added as attribute to a string type properties but the library that is needed to use that attribute isn't added to the file, with hundreds of files it creates a little bit of a problem:
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/40343930/c95c8c25-259e-44bd-8933-8e4da067efcd)

2.

Second problem - On the tables WITHOUT primary key the configuration for specific entitity is created without 
`entity.HasNoKey() `
so you have to specify and create custom configs for each table, with a lot of configurations it is as well a problem, for example:
```
CREATE TABLE [EXAMPLE](
	[NAME] [varchar](100) NULL,
	[DATE_FROM] [datetime] NULL,
	[DATET_TO] [datetime] NULL,
	[AMOUNT] [INT] NULL
) 
```
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/40343930/42fd1c9c-f209-4347-bf17-9074bb5b3a06)

- Exact Visual Studio version: Visual Studio 2022

- EF Core Power Tools version: 2.5.1544

- Database engine: SQL Server

- EF Core version in use: EF Core 6

- Is Handlebars used: yes

- Is T4 used: no

- Is .dacpac used: no

**Comment by ErikEJ** [comment]
It would have been nice with two seperate issues...

Re 1: I assume you are generating the entities in a seperate project? If so  you can just add this small package: https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.Abstractions/

Re 2: what if you do not split the DbContext? (Which I assume you do, you are sharing very few details!)

**Comment by ErikEJ** [comment]
Re 1: you are unclear, but do you mean that the using statement is missing? If so, please provide details about the options you are using (your epft.config.json file)

**Comment by PatrykWalaski** [comment]
My bad, should have been 2 issues as you said, sorry.

1. Yes, all my DB related stuff are in seperate project than my API - got two projects Project.API and Project.DAL for db stuff. 
I've tried adding this package to the Project.DAL and regenerated the classes - problem still persists, "using Microsoft.EntityFrameworkCore;" still missing and the unicode attribute gives an error. I've also tried adding the package You mentioned to both projects, still didn't work. Tried to add only to main API project and didn't work as well. 
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/40343930/2f11e50c-44ba-43e4-9200-a1754e9cbc45)

3. I don't have split DbContext, i have all DbSets in one AppDbContext class that is generated automatically with Reverse Engineer option from power tools.

Can't provide you a project repo, iam not an owner 😞

**Comment by PatrykWalaski** [comment]
"CodeGenerationMode": 2,
   "ContextClassName": "AppDbContext",
   "ContextNamespace": null,
   "DefaultDacpacSchema": null,
   "FilterSchemas": false,
   "IncludeConnectionString": false,
   "ModelNamespace": "Generated",
   "OutputContextPath": "Data",
   "OutputPath": "Generated",
   "PreserveCasingWithRegex": true,
   "ProjectRootNamespace": "Project.API.DAL",
   "Schemas": null,
   "SelectedHandlebarsLanguage": 0,
   "SelectedToBeGenerated": 0,
   "T4TemplatePath": null,  
 "UncountableWords": null,
   "UseBoolPropertiesWithoutDefaultSql": false,
   "UseDatabaseNames": false,
   "UseDateOnlyTimeOnly": false,
   "UseDbContextSplitting": true,
   "UseFluentApiOnly": false,
   "UseHandleBars": true,
   "UseHierarchyId": false,
   "UseInflector": false,
   "UseLegacyPluralizer": false,
   "UseManyToManyEntity": false,
   "UseNoDefaultConstructor": false,
   "UseNoObjectFilter": false,
   "UseNodaTime": false,
   "UseNullableReferences": false,
   "UseSchemaFolders": false,
   "UseSchemaNamespaces": false,
   "UseSpatial": false,
   "UseT4": false

**Comment by PatrykWalaski** [comment]
2. I've set UseDbContextSplitting to false, tried to regenerate code, still the entity is missing "entity.HasNoKey()".

**Comment by ErikEJ** [comment]
So your example table demonstrates both issues?

**Comment by PatrykWalaski** [comment]
Yes, exactly.

1. Missing using Microsoft.EntityFrameworkCore;
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/40343930/67cdf79f-e499-44a4-adbd-623b153541d7)
after adding it's ok:
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/40343930/b97c9aa4-82f7-4531-82c6-fba92dd225a3)

2. Missing 
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/40343930/eac48fee-3fa2-44c0-9888-3af22da1a7f9)
With error in logs: 
`The entity type 'Example' requires a primary key to be defined. If you intended to use a keyless entity type, call 'HasNoKey' in 'OnModelCreating'`
After adding this i can send requests to my controllers, no errors in logs.
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/40343930/b8a557ea-9cde-414b-aae1-271e1fe13fb2)

**Comment by ErikEJ** [comment]
Handlebars! Do you really need it - seems like there are multiple bugs/issues. 

Have you migrated from an older version and not forced an update of the templates perhaps?

Otherwise, you should report an error in the Handlebars for EF Core repo.

Without Handlebars I get this, wich builds and looks fine!

```csharp
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Ef7Playground.Models
{
    [Keyless]
    [Table("EXAMPLE")]
    public partial class Example
    {
        [Column("NAME")]
        [StringLength(100)]
        [Unicode(false)]
        public string? Name { get; set; }
        [Column("DATE_FROM", TypeName = "datetime")]
        public DateTime? DateFrom { get; set; }
        [Column("DATET_TO", TypeName = "datetime")]
        public DateTime? DatetTo { get; set; }
        [Column("AMOUNT")]
        public int? Amount { get; set; }
    }
}
```

**Comment by PatrykWalaski** [comment]
Thanks a lot for help! It was handlebars, disabled it and it works perfectly now.

**Comment by ErikEJ** [comment]
@PatrykWalaski You are welcome!

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
