### ISSUE TITLE
Support views

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#19]
_From @OmiCron07 on April 2, 2018 15:7_

What is currently possible to do to support views?

_Copied from original issue: ErikEJ/SqlCeToolbox#679_

**Comment by ErikEJ** [comment]
PRs accepted! - possibly generate POCO classes from selected views, at least

**Comment by ErikEJ** [comment]
Moving to Backlog

**Comment by ErikEJ** [comment]
Yes, this cannot be implemented unless the EF Core team makes changes, I have later found that out.

**Comment by funky81** [comment]
Noted. Anyway, have you try Query Types in EF Core 2.1
https://docs.microsoft.com/en-us/ef/core/modeling/query-types

If I can export views to Query Types, it will be sufficient for my project.

**Comment by ErikEJ** [comment]
Yes, but this issue talks about code generation of QueryTypes, I think.

**Comment by MgSam** [comment]
This [issue](https://github.com/aspnet/EntityFrameworkCore/issues/827) in EF Core suggests it can support views. 

Are you saying that is inaccurate?

**Comment by ErikEJ** [comment]
Yes, EF Core 2.1 supports QueryTypes, and you can add these to the DbContext using the OnModelCreatingPartial method.

EF Core Power Tools is based on the built-in scaffolding feature, and that feature does not currently support Views

**Comment by CarlVerret** [comment]
Hi, any update on this ?
Thanks

**Comment by ErikEJ** [comment]
The EF Core feature for scaffolding views has been postponed to 3.0.
