### ISSUE TITLE
Column BIT with DEFAULT 1 not add HasDefaultValueSql

### ISSUE THREAD

**Issue by gaglia** [ErikEJ/EFCorePowerTools#1906]
Hi,

I have verified that in the case of BIT type columns that have a default value set to ((1)) the default value is not reported in the model configuration.

I created a small solution with this sample table:

`CREATE TABLE [dbo].[__EFTestDefault](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[TestBoolDef] [bit] NOT NULL,
	[TestIntDef] [int] NOT NULL,
 CONSTRAINT [PK_EFTestDefault] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[__EFTestDefault] ADD  CONSTRAINT [DF___EFTestDefault_TestBool1]  DEFAULT ((1)) FOR [TestBoolDef]
GO

ALTER TABLE [dbo].[__EFTestDefault] ADD  CONSTRAINT [DF___EFTestDefault_TestIntDef]  DEFAULT ((1)) FOR [TestIntDef]
GO`

After reverse engineering, the default is created for the INT type field but not for the BIT one:

`protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<__EFTestDefault>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_EFTestDefault");

            entity.Property(e => e.TestIntDef).HasDefaultValueSql("((1))");
        });

        OnModelCreatingPartial(modelBuilder);
    }`

I would expect to have the default set for the BIT column as well.

I await your feedback
A thousand thanks

### Provide technical details

- Visual Studio 2022 17.6.5

- EF Core Power Tools version: 2.5.1544

- Database engine: SQL Server

- EF Core version in use: EF Core 7

- Is Handlebars used: no

- Is T4 used: yes

- Is .dacpac used: no

[EF7DefaultTest.zip](https://github.com/ErikEJ/EFCorePowerTools/files/12216134/EF7DefaultTest.zip)

**Comment by ErikEJ** [comment]
I am not able to repro - maybe you have the "Remove SQL default from bool columns" option enabled? https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#code-generation

**Comment by gaglia** [comment]
You're right, I had the option turned on:

"UseBoolPropertiesWithoutDefaultSql": true,

Yesterday I had seen in past posts that this option was mentioned but I was unable to locate it.

Thank you
