### ISSUE TITLE
How to force a BIT field of a View to be not nullable?

### ISSUE THREAD

**Issue by SandroRiz** [ErikEJ/EFCorePowerTools#1909]
I have a View where a field is sure not null (is CASE.. 1 ELSE 0 ...)
It is reversed engineered as bool?  
Is there any option to force as not nullable (bool) 

### Provide technical details

-  Visual Studio 2022 17.6.5

- EF Core Power Tools version: 2.5.1544

- Database engine: (SQL Server 2019)

- EF Core version in use: (e.g. EF Core 6)

- Is Handlebars used: no

- Is T4 used: no

- Is .dacpac used: no

**Comment by ErikEJ** [comment]
Use the advanced option, as documented: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#choose-advanced-options
