### ISSUE TITLE
Escape xml reserved characters when generating dgml

### ISSUE THREAD

**Issue by rkreisel** [ErikEJ/EFCorePowerTools#191]
Describe what is not working as expected.

### Steps to reproduce
Include a complete description that I can redo to reproduce the issue.

### Further technical details
EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)

Database engine: (SQlite, SQL Compact, SQL Server, Postgres)

Visual Studio version: (e.g. Visual Studio 2017 15.7)

**Comment by rkreisel** [comment]
When creating DGML output, my db had a computational column in the sql which contained "<=5". Once generated, the XML could not be viewed in the DGML viewer until I found that error in the content and replaced it with "&lt;".

I suspect ">" will also cause a problem. :(

**Comment by ErikEJ** [comment]
This is fixed in the latest daily build, thanks for reporting this
