### ISSUE TITLE
[QUESTION] Database and custom objects

### ISSUE THREAD

**Issue by LuciferSam86** [ErikEJ/EFCorePowerTools#1913]
Hello there,
this is a question.

We have a Database written in SQL Server, and in the future something in PostgreSQL, too.
Our product is a CRM where, sometimes, we create a new field, table, or procedure for a particular customer which stays only in the customer database.
Every object has the suffix "x_" when is custom.

We would like to have the same project with subfolders with those customizations and those folders will call them with the customer name manually when we will scaffold the database.

Do you have suggestions for making something like this?

thanks!

**Comment by ErikEJ** [comment]
No anything that involved EF Core, no.
