### ISSUE TITLE
ICollection are always { get; }

### ISSUE THREAD

**Issue by dorofino** [ErikEJ/EFCorePowerTools#1914]
Why is that when i reverse engineer all my table relationships are created as ICollection { get; } forcing me to create a new DTO class with ICollection  { get; set; } ???

**Comment by ErikEJ** [comment]
That has been fixed long ago. Which extension  version do you use?

**Comment by dorofino** [comment]
> That has been fixed long ago. Which extension version do you use?

Hi Eric, thank you for getting back to me to soon.
I'm using 2.5.1338 > EF Core 7 

Do I need to check any checkbox?

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/1240729/2a1b3274-c9fd-4b0a-8fd2-19d4fd28b8af)

**Comment by ErikEJ** [comment]
No checkboxes, just Update to the latest supported version (older extension versions are not supported)

**Comment by dorofino** [comment]
Perfect, thank you.

It works. next time I will check for the latest version before posting. 

Thank you

**Comment by ErikEJ** [comment]
Cool! 
If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
