### ISSUE TITLE
Question/Feature Request: out parameters instead/with of OutputParameter

### ISSUE THREAD

**Issue by Blackclaws** [ErikEJ/EFCorePowerTools#1916]
So in order to integrate even more seamless into a standard codebase it would be great if stored procedures that have output parameters would expose them in their C# representations as ```out``` variables instead of just OutputParameter.

OutputParameters have to be assigned to a variable before being passed to the function while out parameters can just be variable declared in the function call. Is there any specific reason why the signature is OutputParameter right now?

**Comment by Blackclaws** [comment]
I found out why you actually can't do it while trying to make an example. Async methods can't use the out keyword in their parameters, I forgot about that. 

Another possibility would be to return the OutputParameters as part of a named result tuple, significantly cutting down on parameters to the method. The caller would then be able to just deconstruct the interesting results from the result tuple.

**Comment by Blackclaws** [comment]
Right on trying to make an example of that I found out that MSSQL Stored Procedures do not distinguish pure output from input/output parameters. So that solution is out as well it seems as you can't pass input to those input/output parameters then.  Seems like OutputParameter is sort-of the best solution.

The only possibility would be duplicating the parameters and default initializing them with null and then passing the result in the returned tuple, but I think that would not just break a ton of backwards compatibility it would also be up to the individual which solution they like better.

**Comment by ErikEJ** [comment]
Yeah, I suddenly remembered about input values
