### ISSUE TITLE
Table Renaming Postfix

### ISSUE THREAD

**Issue by dleggen** [ErikEJ/EFCorePowerTools#1917]
Is there any way that a model can have a string postfixed to the name? We would like to postfix "DbModel" to all of our table names if at all possible.  We are already removing text from the start of our table names.

### Provide steps to reproduce a bug

Please include a **complete** description of the issue or link to a project that I can run to reproduce the issue.

### Provide technical details

- EF Core Power Tools version: 2.5.1544

- Exact Visual Studio version: Visual Studio 2022 17.7.0 Preview 6.0

- Database engine: Oracle

- EF Core version in use: EF Core 7

- Is Handlebars templates used: no

- Is T4 templates used: yes

- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
Sure,  you can do this, as documented in the wiki:

`[ { "SchemaName": "dbo", "TablePatternReplaceWith": "$0Entity", "TableRegexPattern": "^.+$", "UseSchemaName": false } ]`

**Comment by dleggen** [comment]
I failed to give a better example of how our tables are named. They're usually named something like "SgtPersonAccount" but we would rather them be named as "PersonAccountDbModel". Is that still possible?

**Comment by ErikEJ** [comment]
Yes, with explicit renaming or some very clever regex (don't ask me) - please read the docs!

**Comment by ErikEJ** [comment]
If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
