### ISSUE TITLE
Pluralization problem during reverse engineering

### ISSUE THREAD

**Issue by trofimich** [ErikEJ/EFCorePowerTools#1918]
Pluralize works incorrectly and I don't see ways to fix it via configuration.
Sample: 
Database table "**Gas**".
The Reverse engineering produces the next result in a _DbContext_:
 `   public virtual DbSet<Ga> Gas { get; set; }`

Expected result:
  `  public virtual DbSet<Gas> Gases { get; set; }`

In _efpt.config.json_:
  ```
   "UseDatabaseNames": false,
   "UseInflector": true,
   "UseLegacyPluralizer": false,
```

In https://github.com/Humanizr/Humanizer#pluralize
I see an option "_inputIsKnownToBeSingular_". Shouldn't its value be configurable from _efpt.config.json_? 
It would be good to be able to add words into Humanizer Vocabulary also.

**Comment by ErikEJ** [comment]
Have you tried adding uncountable words?

https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#pluralization

**Comment by ErikEJ** [comment]
If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by trofimich** [comment]
As i know, word "gas" from my sample is countable: https://grammarist.com/usage/gases-gasses/

**Comment by ErikEJ** [comment]
```json
   "UncountableWords": [
    "Gas"
   ],
```

This is what the tool  can offer, and I have no plans for additional Humanizer customizations.
