### ISSUE TITLE
efpt.renaming.json skipping and removing a table on scaffolding

### ISSUE THREAD

**Issue by hoagsie** [ErikEJ/EFCorePowerTools#1919]
### Provide steps to reproduce a bug

This is mostly a question/maybe bug report.

I have an `efpt.renaming.json` definition with an entry that looks like so.

```
[
   {
      "SchemaName": "Retail",
      "Tables": [
         {
            "Columns": [ ],
            "Name": "POSSystemType",
            "NewName": "POSSystemType"
         }
      ],
      "UseSchemaName": false
   }
]
```

This scaffolds fine when it is alone. However, when I add the other tables from that schema (as I'm trying to preserve frequent `POS` and `SKU` usage), then this entry specifically gets skipped and removed after the scaffold run with the UI tool. The other tables are scaffolded as expected. There is also a table entry after this one which also gets scaffolded as expected.

I tried pairing down the renaming file to just two entries like so.

```
[
  {
    "SchemaName": "Retail",
    "Tables": [
      {
        "Columns": [
          {
            "Name": "POSSystemId",
            "NewName": "POSSystemId"
          },
          {
            "Name": "SKU",
            "NewName": "SKU"
          }
        ],
        "Name": "ItemSKU",
        "NewName": "ItemSKU"
      },
      {
        "Columns": [
        ],
        "Name": "POSSystemType",
        "NewName": "POSSystemType"
      }
    ],
    "UseSchemaName": false
  }
]
```

Upon running again the `POSSystemType` table entry is removed. The `ItemSKU` table entry remains. It seems like the moment another entry is in the list `POSSystemType` gets ignored/removed. Going again back to just that entry as the only one and running the tool again produces expected output and `POSSystemType` is still there.

I saw mention of doing renamings with the UI tool, but I haven't seen a way to do that. I was thinking maybe if I define these in the UI as I've seen hinted at then I could do a diff and see if there's a mismatch. Would you be so kind as to point out where/how that's done?

I generated my renamings file programmatically with some custom code and did the JSON generation with a standard `JsonSerializer.Serialize` so it's valid json. Over the course of my experiments I also re-validated the json as well.

### Provide technical details

- EF Core Power Tools version: 2.5.1544

- Exact Visual Studio version: 2022 17.7.0

- Database engine: SQL Server

- EF Core version in use: 7

- Is Handlebars templates used: seen with either

- Is T4 templates used: seen with either

- Is a SQL Server .dacpac used: no

Here is my redacted config.

```
{
   "CodeGenerationMode": 3,
   "ContextClassName": "[context name]",
   "ContextNamespace": null,
   "DefaultDacpacSchema": null,
   "FilterSchemas": false,
   "IncludeConnectionString": false,
   "ModelNamespace": null,
   "OutputContextPath": null,
   "OutputPath": "Scaffold",
   "PreserveCasingWithRegex": true,
   "ProjectRootNamespace": "[project root]",
   "Schemas": null,
   "SelectedHandlebarsLanguage": 0,
   "SelectedToBeGenerated": 0,
   "T4TemplatePath": null,
   "Tables": [...big list of tables...],
   "UiHint": "[connection name]",
   "UncountableWords": null,
   "UseBoolPropertiesWithoutDefaultSql": false,
   "UseDatabaseNames": false,
   "UseDateOnlyTimeOnly": true,
   "UseDbContextSplitting": true,
   "UseFluentApiOnly": false,
   "UseHandleBars": false,
   "UseHierarchyId": false,
   "UseInflector": false,
   "UseLegacyPluralizer": false,
   "UseManyToManyEntity": true,
   "UseNoDefaultConstructor": true,
   "UseNoObjectFilter": false,
   "UseNodaTime": false,
   "UseNullableReferences": true,
   "UseSchemaFolders": true,
   "UseSchemaNamespaces": true,
   "UseSpatial": false,
   "UseT4": false
}
```

**Comment by ErikEJ** [comment]
I need a repro with CREATE schema/table statements in order for me to help you.

You can use F2 as described in the docs to do UI based renaming.

**Comment by mh-rrs** [comment]
Thank you for that. I tried the F2 option. Giving a custom name, like even `POSSystemTypeFoo`, worked. However, just echoing the name to preserve existing casing did not. Here is the complete create script.

```
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [Retail].[POSSystemType](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_POSSystemType] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
```

**Comment by ErikEJ** [comment]
Please show what you expected versus the actual result. I do not understand the issue.

**Comment by hoagsie** [comment]
Sorry, I could have sworn I had. Problems with being too close to the issue! The issue is the resulting class gets generated as `PossystemType`. The casing of `POS` in all uppercase is not preserved. All the other tables in the `renaming` file keep the casings as expected. In any case that the table entry is silently removed from the file on its own seems like a bug to me as well. If something couldn't be found or there is some kind of conflict I would hope to see an error message of some kind. Nothing is mentioned in the generated `ReadMe` that is shown after using the tool. To summarize:

- Casing is not preserved
- The entry is silently removed
- No error or logging output about the removal (either from the Extensions Output or generated `ReadMe`)

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/20057078/6da26248-465d-4db8-beb9-db81a78697e3)

**Comment by ErikEJ** [comment]
Please share the efpt.renaming.json file that you use for the table.

And please explain what you mean by "the entry is removed"

**Comment by hoagsie** [comment]
Those code blocks in the OP are actual file contents. I will post a more explicit before/after though.

Here is an example ` efpt.renaming.json` I used in trying to test.

Before scaffolding:
```
[
  {
    "SchemaName": "Retail",
    "Tables": [
      {
        "Columns": [
          {
            "Name": "POSSystemId",
            "NewName": "POSSystemId"
          },
          {
            "Name": "SKU",
            "NewName": "SKU"
          }
        ],
        "Name": "ItemSKU",
        "NewName": "ItemSKU"
      },
      {
        "Columns": [
        ],
        "Name": "POSSystemType",
        "NewName": "POSSystemType"
      }
    ],
    "UseSchemaName": false
  }
]
```
I also tried a variant that removes the extraneous newline on the empty `Columns` array.

This is the same `efpt.renaming.json` after scaffolding:
```
[
  {
    "SchemaName": "Retail",
    "Tables": [
      {
        "Columns": [
          {
            "Name": "POSSystemId",
            "NewName": "POSSystemId"
          },
          {
            "Name": "SKU",
            "NewName": "SKU"
          }
        ],
        "Name": "ItemSKU",
        "NewName": "ItemSKU"
      }
    ],
    "UseSchemaName": false
  }
]
```

`POSSystemType` is gone. If you'd be open to a private email, I could also send you a screen recording.

**Comment by ErikEJ** [comment]
Please share the CREATE statement for ItemSKU. Also, please try without schema folders and schema namespaces (both preview/experimental features). Also, try without Data Annotations.

**Comment by ErikEJ** [comment]
I am unable to repro with your single table create script and the following config files (casing is preserved, and the entry stays)

```json
[
   {
      "SchemaName": "Retail",
      "Tables": [
         {
            "Columns": [ ],
            "Name": "POSSystemType",
            "NewName": "POSSystemType"
         }
      ],
      "UseSchemaName": false
   }
]
```


```json
{
   "CodeGenerationMode": 3,
   "ContextClassName": "NorthwindContext",
   "ContextNamespace": null,
   "DefaultDacpacSchema": null,
   "FilterSchemas": false,
   "IncludeConnectionString": true,
   "ModelNamespace": null,
   "OutputContextPath": null,
   "OutputPath": "Models",
   "PreserveCasingWithRegex": true,
   "ProjectRootNamespace": "Ef7Playground",
   "Schemas": null,
   "SelectedHandlebarsLanguage": 2,
   "SelectedToBeGenerated": 0,
   "T4TemplatePath": null,
   "Tables": [
      {
         "Name": "[Retail].[POSSystemType]",
         "ObjectType": 0
      }
   ],
   "UiHint": "",
   "UncountableWords": [
      "Status",
      "Data"
   ],
   "UseBoolPropertiesWithoutDefaultSql": false,
   "UseDatabaseNames": false,
   "UseDateOnlyTimeOnly": true,
   "UseDbContextSplitting": true,
   "UseFluentApiOnly": true,
   "UseHandleBars": false,
   "UseHierarchyId": true,
   "UseInflector": false,
   "UseLegacyPluralizer": false,
   "UseManyToManyEntity": false,
   "UseNoDefaultConstructor": false,
   "UseNoObjectFilter": false,
   "UseNodaTime": false,
   "UseNullableReferences": true,
   "UseSchemaFolders": true,
   "UseSchemaNamespaces": true,
   "UseSpatial": true,
   "UseT4": false
}
```

**Comment by hoagsie** [comment]
I tried once with all the experimental and preview features that you mentioned disabled but I kept data annotations on. That did not work. I tried again with data annotations also disabled in addition to disabling the others. That did not work either.

Yes, the single entry version works as expected as I stated in my OP. It is only when there are at least two entries for me that it gets removed. Here is a slimmed down version of the `ItemSKU` table that I am allowed to share. The same data is there but the relationships to other tables has been removed.

```
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [Retail].[ItemSKU](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[POSSystemId] [int] NOT NULL,
	[ItemMasterId] [int] NOT NULL,
	[UnitId] [int] NOT NULL,
	[SKU] [varchar](20) NOT NULL,
	[LastExportUTC] [datetime] NULL,
	[IsDeleted] [bit] NOT NULL,
	[CreatedBy] [int] NOT NULL,
	[CreatedOn] [datetime] NOT NULL,
	[ModifiedBy] [int] NOT NULL,
	[ModifiedOn] [datetime] NOT NULL,
 CONSTRAINT [PK_RetailItemSKU] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
```

And the related entry that I have in my `renaming` file is as before which is such.

```
[
  {
    "SchemaName": "Retail",
    "Tables": [
      {
        "Columns": [
          {
            "Name": "POSSystemId",
            "NewName": "POSSystemId"
          },
          {
            "Name": "SKU",
            "NewName": "SKU"
          }
        ],
        "Name": "ItemSKU",
        "NewName": "ItemSKU"
      },
      {
        "Columns": [
        ],
        "Name": "POSSystemType",
        "NewName": "POSSystemType"
      }
    ],
    "UseSchemaName": false
  }
]
```

**Comment by ErikEJ** [comment]
Thanks for finally sharing enough information for a proper repro! I will have a look tomorrow

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.
