### ISSUE TITLE
Generating models, not supported sqlserver geography 

### ISSUE THREAD

**Issue by bao2314483** [ErikEJ/EFCorePowerTools#192]
Generating models, not supported sqlserver geography

**Comment by ErikEJ** [comment]
Please share more details and exact error messages

**Comment by bricelam** [comment]
When using `Scaffold-DbContext`, you need to install the Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite package first. I'm not sure if that'll work with the Power Tools tough. @ErikEJ you may need to reference that package directly and call `SqlServerNetTopologySuiteDesignTimeServices.ConfigureDesignTimeServices()` from somewhere.

There are similar packages for SQLite and PostgreSQL.

**Comment by ErikEJ** [comment]
Fixed in latest dail build, pls let me know if it works for you!

**Comment by ErikEJ** [comment]
This is fixed in the latest daily build, please let me know if it works for you

**Comment by ErikEJ** [comment]
Ping?

**Comment by bao2314483** [comment]
no,i use vs2017 install efcore power tools
sqlserver table
``
CREATE TABLE test(
[Id] [uniqueidentifier] NOT NULL,
[DestCoordinates] [geography] NOT NULL
)
``
,but Generating models find entity lack property.
``
public partial class test
    {
        public Guid Id { get; set; }
    }
``
be missing DestCoordinates property

**Comment by ErikEJ** [comment]
Did you install the latest daily build?
