### ISSUE TITLE
CLI Initialization?

### ISSUE THREAD

**Issue by RonFieldsUBH** [ErikEJ/EFCorePowerTools#1921]
Hey ErikEJ,
First of all thanks for what you do and how you contribute to this community. It is much appreciated.

### Technical details
- Visual Studio 2022 (latest update) on my ARM version of Windows 11 running on Parallels on an M1 Mac.
- .NET 7 razor pages solution
 
### Issue with CLI
- :( I was disappointed to see that EFCPT support for ARM was dropped but I am trying to use the CLI (in  my ARM dev environment) to create my entities and dbContext. The issue I am having is that I can find no way to configure the CLI to run to exclude objects before I run the command. The first time I run it (it creates the efcpt-config.json file), but it defaults to include every object in the schema (which is A LOT of tables, sprocs, functions, etc.). Initially, I wind up with hundreds of models and everything in a folder called Models. Is there anyway to run the efcpt command and give it some initialization so that I can avoid having all this extra code created the first time? I'd also like to be able to set the output paths (for models/context) initially as well. I followed the instructions to modify the efcpt-config file use the excludeWildcard "*" and I was able to get that to work but only after the initial run was complete and then I was forced to do a bunch of cleanup.

**Comment by ErikEJ** [comment]
Run the command in any folder, and the tweak the config to suit you?

Create it from scratch in VS Code?

Re ARM VS support - it turned into a support nightmare as VS ARM is very crippled.

**Comment by ErikEJ** [comment]
@RonFieldsUBH Thoughts?

**Comment by ErikEJ** [comment]
@RonFieldsUBH To get rid of unneeded files, enable soft delete:

```json
"code-generation":
  { 
     "soft-delete-obsolete-files": true,
  },

```

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.
