### ISSUE TITLE
Rename navigation and collection properties possible issue

### ISSUE THREAD

**Issue by caiuaqui** [ErikEJ/EFCorePowerTools#1922]
Hello,

I'm using the experimental rename navigation and collection properties renamer and I have the following issue:

I have two tables as you can see :

- Operacoes
- OperacoesAnexos

```
CREATE TABLE [dbo].[OperacaoAnexos](
	[Organizacao] [varchar](15) NOT NULL,
	[Operacao] [varchar](15) NOT NULL,
	[Anexo] [int] NOT NULL,
 CONSTRAINT [PK_OperacaoAnexos] PRIMARY KEY CLUSTERED 
(
	[Organizacao] ASC,
	[Operacao] ASC,
	[Anexo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE TABLE [dbo].[Operacoes](
	[Organizacao] [varchar](15) NOT NULL,
	[Operacao] [varchar](15) NOT NULL,
 CONSTRAINT [PK_Operacao] PRIMARY KEY CLUSTERED 
(
	[Organizacao] ASC,
	[Operacao] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[OperacaoAnexos]  WITH CHECK ADD  CONSTRAINT [FK_OperacaoAnexos_Operacoes] FOREIGN KEY([Organizacao], [Operacao])
REFERENCES [dbo].[Operacoes] ([Organizacao], [Operacao])
GO
ALTER TABLE [dbo].[OperacaoAnexos] CHECK CONSTRAINT [FK_OperacaoAnexos_Operacoes]
GO
```
This is the content from the efpt.property-renaming json file

```
{
  "Classes": [
    {
      "Name": "OperacaoAnexos",
      "Properties": [
        {
          "Name": "O",
          "NewName": "Operacoes",
          "AlternateName": "O"
        }
      ]
    }
  ]
}
```

```
public partial class OperacaoAnexos
{
    [Key]
    [StringLength(15)]
    [Unicode(false)]
    public string Organizacao { get; set; }
    [Key]
    [StringLength(15)]
    [Unicode(false)]
    public string Operacao { get; set; }
    [Key]
    public int Anexo { get; set; }

    [ForeignKey("Organizacao,Operacao")]
    [InverseProperty("OperacaoAnexos")]
    public virtual Operacoes Operacoes { get; set; }
}

public partial class Operacoes
{
    public Operacoes()
    {
        OperacaoAnexos = new HashSet<OperacaoAnexos>();
    }

    [Key]
    [StringLength(15)]
    [Unicode(false)]
    public string Organizacao { get; set; }
    [Key]
    [StringLength(15)]
    [Unicode(false)]
    public string Operacao { get; set; }

    [InverseProperty("O")]
    public virtual ICollection<OperacaoAnexos> OperacaoAnexos { get; set; }
}
```
And, as you can see, the renaming works perfectly. The property "O" is renamed to "Operacoes" on _OperacoesAnexos_ class.
However, on the _Operacoes_ class, the InverseProperty is still on the old name "O".

If i try on run the project, I get the following exception:
> [InverseProperty] attributes on navigation 'OperacaoAnexos.Operacoes' and on navigation 'Operacoes.OperacaoAnexos' are not pointing to each other. 

I know that I can easily edit the file manually but that's not a solution at all, because if I need to generate the code again all these changes will be gone.

To sum this all up, my question is: is this issue a possible bug on the renaming property functionality or it might be related to this .NET Core bug ([bug](https://github.com/dotnet/efcore/issues/14278)).

Technical details
- EF Core Power Tools version: 2.5.1544 
- Exact Visual Studio version: Visual Studio 2022 17.7.1
- Database engine: SQL Server
- EF Core version in use: EF Core 6
- Is Handlebars templates used: no
- Is T4 templates used: no
- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
I think you need to define renaming of Operacoes in your config file as well.

**Comment by caiuaqui** [comment]
Okay, but the problem still persists.

The [InverseProperty] property still has the old  navigation name "O".

```
{
  "Classes": [
    {
      "Name": "OperacaoAnexos",
      "Properties": [
        {
          "Name": "O",
          "NewName": "Operacoes",
          "AlternateName": "Operacoes"
        }
      ]
    },
    {
      "Name": "Operacoes",
      "Properties": [
        {
          "Name": "OperacaoAnexos",
          "NewName": "OperacaoAnexos",
          "AlternateName": "OperacaoAnexos"
        }
      ]
    }
  ]
}
```

> Operacoes class

```
        [InverseProperty("O")]
        public virtual ICollection<OperacaoAnexos> OperacaoAnexos { get; set; }
```

> OperacaoAnexos class

 ```
      [ForeignKey("Organizacao,Operacao")]
      [InverseProperty("OperacaoAnexos")]
      public virtual Operacoes Operacoes { get; set; }
```

**Comment by ErikEJ** [comment]
I think you cannot use property renaming for this  as it is strings. You can use postrun.cmd to do some string replacements.
