### ISSUE TITLE
Error when adding DbContext Diagram

### ISSUE THREAD

**Issue by royvandertuuk** [ErikEJ/EFCorePowerTools#1923]
### Issue
When trying to add the DbContext diagram via a console app that has a reference to the C# library containing the DbContext, I get the error below.

```   at async Task EFCorePowerTools.Handlers.ModelAnalyzerHandler.GenerateAsync(string outputPath, Project project, GenerationType generationType)
System.InvalidOperationException: Error:
System.ArgumentException: No EF Core DbContext types found in the project
   at Modelling.EfCoreModelBuilder.GetDbContextTypes(DbContextOperations operations) in C:\Code\Github\EFCorePowerTools\src\GUI\efpt30.core\EFCoreModelBuilder.cs:line 87
   at Modelling.EfCoreModelBuilder.BuildResult(String outputPath, String startupOutputPath, Boolean generateDdl) in C:\Code\Github\EFCorePowerTools\src\GUI\efpt30.core\EFCoreModelBuilder.cs:line 37
   at Modelling.EfCoreModelBuilder.GenerateDebugView(String outputPath, String startupOutputPath) in C:\Code\Github\EFCorePowerTools\src\GUI\efpt30.core\EFCoreModelBuilder.cs:line 24
   at Modelling.Program.Main(String[] args) in C:\Code\Github\EFCorePowerTools\src\GUI\efpt30.core\Program.cs:line 60
```

### Steps to reproduce a bug
1. Clone the repository `https://github.com/royvandertuuk/EFCorePowertoolIssue`
2. Set the `ConsoleApp` as the startup project
3. Right click on the `ConsoleApp` project
4. navigate to `EF Core Power Tools` menu
5. Click on `Add DbContext Diagram`
6. The error mentioned above is displayed in the extensions output window

### Technical details

- EF Core Power Tools version: 2.5.1544
- Microsoft Visual Studio Version 17.7.1
- Database engine: SQL Server
- EF Core version in use:  EF Core 7
- Is Handlebars templates used: no
- Is T4 templates used: no
- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
Fix be adding this to the .Data project, and generating from it:

```xml
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="7.0.10">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="7.0.10" />
  </ItemGroup>

```

**Comment by royvandertuuk** [comment]
Thank you, this solves my issue!

Did I miss something in the documentation? 
I read the page https://github.com/ErikEJ/EFCorePowerTools/wiki/Inspect-your-DbContext-model, perhaps this page can be improved to help avoid this problem for others. The main confusion for me was that the documentation states that the tool must be executed from an executable or web project.

**Comment by ErikEJ** [comment]
Yeah, I thought about this when troubleshooting this, I have a hunch it mainly applies to web projects

**Comment by ErikEJ** [comment]
I have updated the docs
