### ISSUE TITLE
Database first - default values from int and bit are ignored

### ISSUE THREAD

**Issue by westner** [ErikEJ/EFCorePowerTools#1926]
Hello,

I have a table

CREATE TABLE [dbo].[Test]
(
    [Id]      INT            IDENTITY (1, 1) NOT NULL,
    [Active]  BIT            DEFAULT ((1)) NOT NULL,
)

When I generate the classes using "Reverse Engineer" the deault values are not transfered in the classes.

I would expect something like

            modelBuilder.Entity<Test>(entity =>
            {
                entity.Property(e => e.Active).HasDefaultValueSql("((1))");
            });

Is there a setting to create the defaults?

Bye

Stefan

**Comment by ErikEJ** [comment]
Please fill in requested details when creating an issue, otherwise I cannot offer free support!

**Comment by westner** [comment]
Technical details as requested

- EF Core Power Tools version: 2.5.1595
- Exact Visual Studio version: Visual Studio 2022 17.7.2
- Database engine: SQL Server 2019
- EF Core version in use: EF Core 6
- Is Handlebars templates used: NO
- Is T4 templates used: NO
- Is a SQL Server .dacpac used: NO

**Comment by ErikEJ** [comment]
Thanks! I am unable to reproduce:


```csharp
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<Test>(entity =>
    {
        entity.HasNoKey();

        entity.ToTable("Test");

        entity.Property(e => e.Active)
            .IsRequired()
            .HasDefaultValueSql("((1))");

        entity.Property(e => e.Id).ValueGeneratedOnAdd();
    });

    OnModelCreatingPartial(modelBuilder);
}

```

**Comment by ErikEJ** [comment]
Maybe the use running the reverse enigneering is lacking rights in the database? see https://github.com/ErikEJ/EFCorePowerTools/issues/515
