### ISSUE TITLE
efpt.property-renaming.json not being applied (Could not load file or assembly Microsoft.CodeAnalysis.Workspaces)

### ISSUE THREAD

**Issue by MrZander** [ErikEJ/EFCorePowerTools#1929]
### Provide steps to reproduce a bug
1.) Have a efpt.property-renaming.json 
2.) Refresh the model

The property renaming does not get applied, Extensions output gives the following exception:
```
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.CodeAnalysis.Workspaces, Version=4.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.CodeAnalysis.Workspaces, Version=4.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Task<List<string>> EFCorePowerTools.Helpers.RoslynEntityPropertyRenamer.ApplyRenamingRulesAsync(Model model, string projectPath, string contextFolder, string modelsFolder)
   at async Task EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.ApplyNavigationRenamersAsync(Project project, string referenceRenamingPath, ReverseEngineerOptions options)
```

This is on a fresh re-install of the extension.
I know the feature is experimental, but any workaround would be appreciated as it makes our lives a whole lot easier.

### Provide technical details

- EF Core Power Tools version: 2.5.1595

- Exact Visual Studio version: Visual Studio 2022 17.5.3

- Database engine: SQL Server

- EF Core version in use: EF Core 7

- Is Handlebars templates used: no

- Is T4 templates used: no

- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
You are not on the latest VS version, try an update

**Comment by MrZander** [comment]
Yep, that was it.  Simple enough.

Mange tak!

**Comment by ErikEJ** [comment]
A good reason to keep this feature experimental!
