### ISSUE TITLE
[QUESTION] : DB Scaffolding from Oracle and Datatypes

### ISSUE THREAD

**Issue by LuciferSam86** [ErikEJ/EFCorePowerTools#1930]
Hello there,
it looks like there is a bug for the .NET package Oracle.EntityFrameworkCore because it converts a NUMBER(4,0) to Byte.

Is there a trick with a T4 model, for convert from byte to int those fields?

Thanks!

**Comment by ErikEJ** [comment]
I would imagine you could do something similar to this: https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-8.0/breaking-changes#mitigations
