### ISSUE TITLE
Question: Which data provider is needed for SQLite

### ISSUE THREAD

**Issue by karenpayneoregon** [ErikEJ/EFCorePowerTools#1931]
### Provide steps to reproduce a bug

Please include a **complete** description of the issue or link to a project that I can run to reproduce the issue.
- Reverse engineer SQLite database using your data provider from the SQLite Compact ToolBox add connection string, click test connection, get Test connection succeed.
- Press OK
- Get Unable to find the requested .Net Framework Data Provider. It may not be installed as per image.

### Provide technical details

- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)

2.5.1595

- Exact Visual Studio version: (e.g. Visual Studio 2022 17.6.5)

17.7.2

- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)

SQLite

- EF Core version in use: (e.g. EF Core 7)

Microsoft.EntityFrameworkCore.Sqlite 7.0.0

- Is Handlebars templates used: no/yes

No

- Is T4 templates used: no/yes

No

- Is a SQL Server .dacpac used: no/yes

No

![A1](https://github.com/ErikEJ/EFCorePowerTools/assets/17032797/a0e9b155-f8fd-4f5b-b805-9a0cb09fe157)

**Comment by ErikEJ** [comment]
@karenpayneoregon I have switched to using the DDEX provider created by @bricelam as [described in the wiki](https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#choose-data-source)

**Comment by karenpayneoregon** [comment]
Thanks Erick
