### ISSUE TITLE
Failed to install on Mac M1 Max (Ventura) running Parallels 19 Pro

### ISSUE THREAD

**Issue by YanivC** [ErikEJ/EFCorePowerTools#1932]
Since Microsoft still hasnt solved the issue with DB servers explorer on ARMs was so happy when I found this but cant install it.

Tried to install but failed, adding log file below.

9/7/2023 9:08:17 AM - Microsoft VSIX Installer
9/7/2023 9:08:17 AM - -------------------------------------------
9/7/2023 9:08:17 AM - vsixinstaller.exe version:
9/7/2023 9:08:17 AM - 17.7.2192+5ac9365ac0
9/7/2023 9:08:17 AM - -------------------------------------------
9/7/2023 9:08:17 AM - Command line parameters:
9/7/2023 9:08:17 AM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,\\Mac\Home\Downloads\EF_Core_Power_Tools_v2.5.1595.vsix
9/7/2023 9:08:17 AM - -------------------------------------------
9/7/2023 9:08:17 AM - Microsoft VSIX Installer
9/7/2023 9:08:17 AM - -------------------------------------------
9/7/2023 9:08:18 AM - Initializing Install...
9/7/2023 9:08:18 AM - Searching for applicable products...
9/7/2023 9:08:19 AM - Found installed product - Visual Studio Professional 2022
9/7/2023 9:08:19 AM - Found installed product - Global Location
9/7/2023 9:08:19 AM - Extension Details...
9/7/2023 9:08:19 AM - 	Identifier         : f4c4712c-ceae-4803-8e52-0e2049d5de9f
9/7/2023 9:08:19 AM - 	Name               : EF Core Power Tools
9/7/2023 9:08:19 AM - 	Author             : ErikEJ
9/7/2023 9:08:19 AM - 	Version            : 2.5.1595
9/7/2023 9:08:19 AM - 	Description        : Useful design-time DbContext features, added to the Visual Studio Solution Explorer context menu.

When right-clicking on a C# project, the following context menu functions are available:
Reverse Engineer - Generates POCO classes, derived DbContext and Code First mapping for an existing database or SQL Server Database project (.dacpac).
Migrations Tool - Manage EF Core Migrations in the project: View status, Add Migration, Update Database
Add DbContext Model Diagram - Adds a DGML graph from your DbContext Model.
View DbContext Model SQL DDL - View a SQL DDL script from your DbContext Model.
About - Displays version and other diagnostic information about your Visual Studio instance. 
        
9/7/2023 9:08:19 AM - 	Locale             : en-US
9/7/2023 9:08:19 AM - 	MoreInfoURL        : https://github.com/ErikEJ/EFCorePowerTools/wiki/
9/7/2023 9:08:19 AM - 	InstalledByMSI     : False
9/7/2023 9:08:19 AM - 	SupportedFrameworkVersionRange : [4.8,)
9/7/2023 9:08:19 AM - 	SignatureState     : Unsigned
9/7/2023 9:08:19 AM - 	Supported Products : 
9/7/2023 9:08:19 AM - 		Microsoft.VisualStudio.Community
9/7/2023 9:08:19 AM - 			Version : [17.0,18.0)
9/7/2023 9:08:19 AM - 			ProductArchitecture : amd64
9/7/2023 9:08:19 AM - 	References         : 
9/7/2023 9:08:19 AM - 	Prerequisites      : 
9/7/2023 9:08:19 AM - 		-------------------------------------------------------
9/7/2023 9:08:19 AM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
9/7/2023 9:08:19 AM - 		Name         : Visual Studio core editor
9/7/2023 9:08:19 AM - 		Version      : [17.0,)
9/7/2023 9:08:19 AM - 		-------------------------------------------------------
9/7/2023 9:08:19 AM - 		Identifier   : Microsoft.VisualStudio.Component.GraphDocument
9/7/2023 9:08:19 AM - 		Name         : DGML editor
9/7/2023 9:08:19 AM - 		Version      : [17.0,)
9/7/2023 9:08:19 AM - Signature Details...
9/7/2023 9:08:19 AM - 	Extension is not signed.
9/7/2023 9:08:19 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData) in D:\a\_work\1\s\src\product\extensionManager\installer\VSIXInstaller\Services\ExtensionService.cs:line 186
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData) in D:\a\_work\1\s\src\product\extensionManager\installer\VSIXInstaller\Services\ExtensionService.cs:line 28
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported) in D:\a\_work\1\s\src\product\extensionManager\installer\VSIXInstaller\Services\ExtensionPackService.cs:line 101
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported) in D:\a\_work\1\s\src\product\extensionManager\installer\VSIXInstaller\Services\ExtensionPackService.cs:line 42
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported) in D:\a\_work\1\s\src\product\extensionManager\installer\VSIXInstaller\App.xaml.cs:line 272
   at VSIXInstaller.App.Initialize() in D:\a\_work\1\s\src\product\extensionManager\installer\VSIXInstaller\App.xaml.cs:line 230
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by ErikEJ** [comment]
Please which VS version and processor arch?

**Comment by ErikEJ** [comment]
Assuming it is VS ARM, then the extension does not support ARM64, you can use the command line version instead

**Comment by YanivC** [comment]
Hi Erik,

Yes its the ARM64. I searched the github page to see if that was mentioned
anywhere before bothering you but couldn't find it. Command line tool? I
couldnt find that repo, I only found the SqlCeCmd and SqlCeMigrator.

Thank you!
Yaniv Chokron CSM, CSD, CSPO

**Comment by ErikEJ** [comment]
I have updated the docs

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.
