### ISSUE TITLE
EF Core 5

### ISSUE THREAD

**Issue by scotnotis** [ErikEJ/EFCorePowerTools#1933]
Hello Mr. EJ, 

Thank you for creating this tool. It worked great on EF Core 5. 
Please how can I make it work again on EF Core 5? 
Can I use an older version, even if it deprecated. I mostly need the "Add DbContext Model Diagram".

Thanks.

**Comment by ErikEJ** [comment]
Assume you are aware that EF Core 5 is completly out of support?

But yes, I have some older unsupported versions here: https://github.com/ErikEJ/EFCorePowerTools/tree/master/tools 

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
