### ISSUE TITLE
After updating, not all entities are created and some navigation type fields were created

### ISSUE THREAD

**Issue by CarlosClavelJr** [ErikEJ/EFCorePowerTools#1936]
It doesn't add tables from my base

### Provide steps to reproduce a bug
I had another version that I don't remember what it was, and after updating, the tool does not bring me all the tables, and they have a primary key. Also in a table that he brought me, when I make a query it gives me an error:
" Unable to determine the relationship represented by navigation 'TableB.IdProducto' of type 'ICollection<TableC>'. Either manually configure the relationship, or ignore this property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.' "

The strange thing is that I am consulting table A, hich has a relationship with table B, but table B has no relationship with table C, the field Idproducto does not exist in table B, that is strange.

I want to clarify that my project builds the entities separately from the dbcontexto, and I use the "Entity Types Only" option in one project, and in the other project "DbContext Only". This is how the project was created and it was working.

### Provide technical details

- EF Core Power Tools version: 2.5.1595

- Exact Visual Studio version:  Visual Studio 2022 Versión 17.7.3

- Database engine: (SQL Server 2019 )

- EF Core version in use:  EF Core 6

- Is Handlebars templates used:  no

- Is T4 templates used: no

- Is a SQL Server .dacpac used: no
![issue](https://github.com/ErikEJ/EFCorePowerTools/assets/67576875/891f9d54-25e7-4ed4-b845-738d9fee0e65)

![other](https://github.com/ErikEJ/EFCorePowerTools/assets/67576875/5620b9de-b805-4f7c-855c-a0bc28952fb6)
![contextonly](https://github.com/ErikEJ/EFCorePowerTools/assets/67576875/d7023b7c-2ae7-4cdf-b3e8-bf189dc35266)
![entityonly](https://github.com/ErikEJ/EFCorePowerTools/assets/67576875/9a4d2ecf-ab0c-4d89-b668-b7a5828db1b6)

**Comment by ErikEJ** [comment]
Maybe try to bring back the many to many entity classes

**Comment by CarlosClavelJr** [comment]
In the "EF Core Power tools" configuration when doing reverse engineer?

**Comment by ErikEJ** [comment]
Correct, option 4 in Advanced options

**Comment by ErikEJ** [comment]
You also need to recreate the DbContext using the new version with EF Core 6 many to many support

**Comment by CarlosClavelJr** [comment]
Yes, that helped, thank you very much
