### ISSUE TITLE
New Configuration option: Skip Navigation Properties

### ISSUE THREAD

**Issue by ftrueck** [ErikEJ/EFCorePowerTools#1937]
It would be very handy to have the option to completely skip Navigation Properties in the generated model. Sometimes you just want the entities without any navigation stuff and it would really be helpful if I do not have to modify any code generation template to achieve this.

**Comment by ErikEJ** [comment]
Have you tried the T4 POCO template option?

**Comment by ftrueck** [comment]
I am trying it at the moment. Thanks for the tip. 

But: I am running into issues it seems.
When I reverse engineer, I get the message that the template version was not correct. Looking into the template for DbContext I see version 7.03 instead of 7.04 that was expected. Deleting the CodeTemplates folder does generate the same T4 template with version 7.03.

Additionally it seems the POCO template does not include the changed namespace. The POCO classes contain the namespace suffix ".POCO" which is not added to the DBContext as using.

Lastly the DbContext Code still contains the OnModelCreating section where there are .HasOne and .HasMany entries. For POCO not ideal, as this is broken then and not working.

**Comment by ftrueck** [comment]
But hold on, it seem there was an update to the extensions within the last days. I first will update and then check again.

**Comment by ErikEJ** [comment]
In that case, I think T4 will be the way to go for you.

**Comment by ftrueck** [comment]
I do not have any aversion against Navigation Properties. I like them. 
But there is a problem with them in my case.
I have a int-property that is linked to another table in the database (referencial integrity).
This column can not be null. The database reverse engineering generates a navigation property that also may not be null.
This is where my problem starts: On deserialization the Json Deserializer throws an exception because the navigation property may not be null. As the web-api client is also automatically generated I can not simply change the code as every time i update the client from the API my changes are overwritten again. I can also not inherit from the client generated class to override the behaviour because the client uses its generated classes.
