### ISSUE TITLE
CLI - UseDbContextSplitting support 

### ISSUE THREAD

**Issue by tomadj** [ErikEJ/EFCorePowerTools#1938]
Hi @ErikEJ, 

I'am testing EFCorePowerTools in CLI mode. Like GUI its very great ! 

The UseDbContextSplitting option (generate ef configuration in seperate files) it is available in CLI mode ? 

Thank's ! 

Thomas

**Comment by ErikEJ** [comment]
Yes, the "only" unsupported features are listed here: https://github.com/ErikEJ/EFCorePowerTools/issues/1751#issue-1640570143

**Comment by tomadj** [comment]
I found the "split-dbcontext-preview" option in the "file-layout" node

Thank's !
