### ISSUE TITLE
EF Power Tools Context menu missing

### ISSUE THREAD

**Issue by kotto70** [ErikEJ/EFCorePowerTools#1939]
Migration to a new Windows 11 desktop for development, using Visual Studio 2022 17.7.4, working on .net 6 WebApi project.  

After initial setup of Visual Studio 2022, installing EF Power Tools, and loading my existing WebAPI project, I'm unable to see the EFCorePowerTools context menu when right-clicking on the project.  I've use EFCorePowerTools on many projects on several different windows platforms for years and never experienced this issue.  The EFCorePowerTools shows as installed in VS Extensions, however it does not appear in the VS Options.

I've tried...

1. Installing PowerTools from inside Visual Studio and directly from the VS marketplace download.
2. Reset my VS settings and reload PowerTools
3. Installed as admin user

### Provide technical details

- EF Core Power Tools version: 2.5.1607

- Exact Visual Studio version: Visual Studio 2022 17.7.4

- Database engine: SQL Server 

- EF Core version in use: EF Core 6

- Is Handlebars templates used: no

- Is T4 templates used: no

- Is a SQL Server no

**Comment by kotto70** [comment]
> Can your share your .csproj file?
> 
> The tool now checks if the project uses a supported .NET version.

`<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Migrations\**" />
    <EmbeddedResource Remove="Migrations\**" />
    <None Remove="Migrations\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Contexts\DataContext.cs" />
    <Compile Remove="Contexts\PublisherDCITellerContext.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="12.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="7.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="7.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="7.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="7.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="7.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="7.0.0" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.2.23" />
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Scripts\Constants\DCITeller_EntityConstants.sql">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\Constants\DCITeller_EntityFlags.sql">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\Constants\DCITeller_EntityLookup.sql">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\Constants\DCITeller_PageXRefs_Create.sql">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\Constants\DCITeller_TellerSchemas.sql">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\Create\DCITellerCommon_Defaults.sql">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\Create\DCITeller_CreateDatabase.sql">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\Create\DCITeller_Testing_Dashboard.sql">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\Initialize\DCITeller_Defaults.sql">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\Initialize\DCITeller_Defaults_AdminMenus.sql">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\Initialize\DCITeller_Defaults_Assign_PageXRefs.sql">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\Initialize\DCITeller_Defaults_AuditObjects.sql">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\Initialize\DCITeller_Defaults_Messages.sql">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\Create\DCITeller_Testing_UserDrawers.sql">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\Initialize\DCITeller_Defaults_AdminMenus.sql">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\Initialize\DCITeller_Defaults_AuditObjects.sql">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\Create\DCITeller_InsertDefaultAdminMenus.sql">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\Initialize\DCITeller_Defaults.sql">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\Create\DCITeller_Testing_SampleData.sql">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\Initialize\DCITeller_Defaults_Messages.sql">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\Initialize\DCITeller_Defaults_TellerMenus.sql">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\Initialize\DCITeller_RefreshDatabase.sql">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\Create\DCITeller_SyncIdentityTellerUsers.sql">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\Create\DCITeller_TellerFunctionsPageReference.sql">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\Tools\DCITeller_AddPrinter.sql">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\Tools\DCITeller_AddUserMenuOption.sql">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\Tools\DCITeller_DeleteTransactionsForADay.sql">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\Tools\DCITeller_FindAllUserBusinessWithTransactionCounts.sql">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\Tools\DCITeller_MoveTellerBusinessToAnotherUser.sql">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\Tools\DCITeller_SYS_Documents_AddImage.sql">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Contexts\Reporting\" />
  </ItemGroup>


</Project>
`

**Comment by kotto70** [comment]
[DCI.Teller.DataAccess.csproj.txt](https://github.com/ErikEJ/EFCorePowerTools/files/12620392/DCI.Teller.DataAccess.csproj.txt)

See attached.  However, I'm not seeing this issue with the same project file on another workstation, using the same VS and EF Power Tools version.

**Comment by ErikEJ** [comment]
Try to ensure Power Tools are enabled in extension manager, and/or do a VS repair.

**Comment by kotto70** [comment]
- I verified EF Power Tools was enabled in Extension Manager.  It was enabled.
- I completed the repair of VS 2022 using the Visual Studio Installer.
- Visual Studio launched as a first-time user, with all settings reset to default installation.
- I selected the EF Power Tools from the Extension Manager for download.
- Upon VS exit, I completed the EF Power Tools installation.
- Relaunch VS while loading project and context menu is still NOT present and does not appear in VS Options.
- I again confirmed that EF Power Tools was shown has installed and was enabled via the VS Extension Manager.

**Comment by ErikEJ** [comment]
Please share (privately) a full solution or try an older version from the tools folder here.

**Comment by ErikEJ** [comment]
You could also share your activity log.xml file

**Comment by ErikEJ** [comment]
Based on your observations, something is preventing the extension from loading or causing it to crash during load. 

https://devblogs.microsoft.com/visualstudio/troubleshooting-extensions-with-the-activity-log/

**Comment by kotto70** [comment]
I'm not seeing anything in the VS activityLog.xml, however I'm attaching the VSIX installer log.  

[dd_VSIXInstaller_20230918114507_4558.log](https://github.com/ErikEJ/EFCorePowerTools/files/12651500/dd_VSIXInstaller_20230918114507_4558.log)

**Comment by ErikEJ** [comment]
Did you launch with the /Log command line option?

**Comment by kotto70** [comment]
See attached.

[ActivityLog1.xml.txt](https://github.com/ErikEJ/EFCorePowerTools/files/12651626/ActivityLog1.xml.txt)

**Comment by kotto70** [comment]
I see errors in the activity log but I'm not sure what would be causing the extension to not properly install.

**Comment by ErikEJ** [comment]
I am running out of ideas. Try to install another VS SKU (for example Community) and try to install the extension into that. Then we know if it is your machine or your VS instance that is broken.

**Comment by kotto70** [comment]
I finally completely uninstalled Visual Studio 2022, and all remnants of previous versions including user profiles.  I then reinstalled Visual Studio 2022 and the extension installed successfully.  Although it's unclear exactly what was causing the issue, I'm glad it's fixed and I appreciate your help in troubleshooting the issue.

**Comment by ErikEJ** [comment]
If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
