### ISSUE TITLE
Is an older version available?

### ISSUE THREAD

**Issue by EnterAUserName12** [ErikEJ/EFCorePowerTools#1940]
The current version does not work with VS2019. 
How can I get an older version of the extension?

TY

**Comment by ErikEJ** [comment]
Why are you not using Visual Studio 2022?

But you can download an unsupported version of the extension from [here](https://github.com/ErikEJ/EFCorePowerTools/tree/master/tools)

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by EnterAUserName12** [comment]
TY 
still on 2019 because of licensing costs
