### ISSUE TITLE
Feature Request Or How To.

### ISSUE THREAD

**Issue by dcbrewster** [ErikEJ/EFCorePowerTools#1941]
Is it possible to run "Reverse Engineer" within the "Pre-build Events" with in Visual Studio?

It would be nice to ensure the build is using the latest information from the database structure, functions and stored procedures.

Thanks.

**Comment by ErikEJ** [comment]
You could use the [CLI edition](https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/efcpt/readme.md) for that, yes.

**Comment by dcbrewster** [comment]
Thanks very much.

Great work.

 

Dave

**Comment by ErikEJ** [comment]
@dcbrewster you are very welcome.

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
