### ISSUE TITLE
Where can I download older version of this tool? 

### ISSUE THREAD

**Issue by shivanaru** [ErikEJ/EFCorePowerTools#1942]
Searched everywhere but I could not find older version of this tool. I am on .Net core 3.1 so the version that works with .Net core 3.1 is what I am looking for. 

Thanks!

**Comment by ErikEJ** [comment]
Assume you are aware that .NET Core 3.1 / EF Core is no longer supported?

But you can download an unsupported version of the extension from [here](https://github.com/ErikEJ/EFCorePowerTools/tree/master/tools)

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by shivanaru** [comment]
Hi Erik,

I already downloaded it from the locations you mentioned here but there is
no installation file (exe or vsix) in it that I could use. Is there another
way to install it? Please advise.

Thank you!

**Comment by ErikEJ** [comment]
Rename the .zip to .vsix and install

**Comment by shivanaru** [comment]
I tried that but that didn't work.
