### ISSUE TITLE
Reverse Engineer no longer shows up on the menu

### ISSUE THREAD

**Issue by NickThomas01** [ErikEJ/EFCorePowerTools#1943]
Repro:
Right click on project, hover over EF Core Power Tools, only the Visualize Database Schema and About appear as menu options.
 Missing reverse engineer option.  Worked when I last used it, prolly a couple of days ago.  Not this morning.

Rebooted system, restarted VS, reinstalled EF Core PT.  Not necessarily in that order.  No change.

Not sure what happened last night or whenever, could be an auto update issue?

EF Core PT version 2.5.1607.
VS 2022 version 17.1.5
App is  NETCore 5.
No handlebars in this app.
No T4 templates
No SQLServer dacpac

**Comment by ErikEJ** [comment]
The tool no longer supports .NET Core 5 which is out of support. Update to .NET 6 or later or download an unsupported version from the tools folder here.

**Comment by NickThomas01** [comment]
Hi Erik,
This app is scheduled to go to .NET 8 in November.  But, I found an older install file of your product and installed that.  All good now.  That musta been the issue as I saw a new version on 9/12 which is prolly what sent things south for this app.  I also turned off auto update.  Until November anyway.

Thanks,
Tom

From: Erik Ejlskov Jensen ***@***.***>
Sent: Friday, September 15, 2023 12:16 PM
To: ErikEJ/EFCorePowerTools ***@***.***>
Cc: Nicholas, Tom ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [ErikEJ/EFCorePowerTools] Reverse Engineer no longer shows up on the menu (Issue #1943)

Warning: This Email may contain a virus or could be a phishing attempt. Please inspect the contents before opening any attachments or links

The tool no longer supports .NET Core 5 which is out of support. Update to .NET 6 or later or download an unsupported version from the tools folder here.

-
Reply to this email directly, view it on GitHub<https://usg02.safelinks.protection.office365.us/?url=https%3A%2F%2Fgithub.com%2FErikEJ%2FEFCorePowerTools%2Fissues%2F1943%23issuecomment-1721730234&data=05%7C01%7Ctom.nicholas%40cppcorp.com%7Cc0ad2408d54a488cec8008dbb62026a5%7Cf1d8c7b0a51c42429663639a00b900c2%7C0%7C0%7C638304021429177456%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=B%2B14VGq0xJJIGR1atImCcSYHg8jQbW7UCD6JGAeeC%2Bs%3D&reserved=0>, or unsubscribe<https://usg02.safelinks.protection.office365.us/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FBCTLVZXTAFF5NTHITVGCMN3X2SSNXANCNFSM6AAAAAA42BIUTA&data=05%7C01%7Ctom.nicholas%40cppcorp.com%7Cc0ad2408d54a488cec8008dbb62026a5%7Cf1d8c7b0a51c42429663639a00b900c2%7C0%7C0%7C638304021429177456%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vo06BKaWfKOcA2oV%2BWJp0KRUPRzGytjGWjPs%2FcP3DGw%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

________________________________

---------------
CONFIDENTIALITY WARNING: This email may contain privileged or confidential information and is for the sole use of the intended recipients. Unauthorized disclosure or use of this communication is prohibited. If you believe that you have received this email in error, please notify the sender immediately and delete it from your system.

EXPORT WARNING: These commodities, technical data or software may be subject to the export control of either the International Traffic in Arms Regulations (ITAR) or the Export Administration Regulations (EAR) and may not be exported without the authorization of either the Department of State or the Department of Commerce prior to export. Export includes disclosure and or access to Commodities, technical data or software by foreign nationals whether located in the United States or Abroad. This requirement applies equally to foreign national employees of U.S. Companies and their foreign subsidiaries.

**Comment by ErikEJ** [comment]
@NickThomas01 you are very welcome.

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
