### ISSUE TITLE
I cannot install the EF Core Power Tools due the message: System.ArgumentException: An item with the same key has already been added.

### ISSUE THREAD

**Issue by marceloatmartins** [ErikEJ/EFCorePowerTools#1945]
Create a bug report, feature proposal, or ask a question.

NOTICE: A bug report without sufficient technical and repro details and version information WILL BE CLOSED WITHOUT ANY FURTHER ACTION.

### Provide steps to reproduce a bug

I'm just trying to install the EF_Core_Power_Tools_v2.5.1607.vsix , but appears the message: An item with the same key has already been added.

### Provide technical details

- EF Core Power Tools version: EF_Core_Power_Tools_v2.5.1607.vsix

- Exact Visual Studio version: Microsoft Visual Studio Community 2022 (64-bit) - Version 17.7.3

[dd_VSIXInstaller_20230919201011_59c8.log](https://github.com/ErikEJ/EFCorePowerTools/files/12667223/dd_VSIXInstaller_20230919201011_59c8.log)

Thanks in advance.

**Comment by ErikEJ** [comment]
Try to remove other extensions or run a VS repair, looks like an installer issue.

**Comment by ErikEJ** [comment]
Ping? @marceloatmartins

**Comment by marceloatmartins** [comment]
Sorry by the delay, Thanks ErikEJ, certainly it was a installation bug in VS 2022, I've uninstalled it and re-install a brand new, so I was able to install the EF Core Power Tools without no issue. Uhuuuuuuuuuuuuuu, anyone do not catch me now.

**Comment by ErikEJ** [comment]
Great news!

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
