### ISSUE TITLE
Add option to generate configuration for all properties of tables

### ISSUE THREAD

**Issue by cezarlamann** [ErikEJ/EFCorePowerTools#1946]
Hi ErikEJ, how have you been?

First of all, Thank you for such a great tool! While playing with it, I have observed that unless the columns have any restrictions/defaults (max length, defaults, etc.) or different DB names than the generated ones, the properties don't appear on the configuration files.

Is there a way to make an option to include all properties (and their map to the db columns) regardless of whether they have the same name or not (especially when the option "Use the table and column names directly from the database" is not marked)?

I don't know if you're generating the configuration classes through a T4 template or through something else, but I believe this should not be very difficult for you since you're going through all the properties anyway to generate the models and configurations.

The reason is that some people in my project like to have explicit mappings for all properties 😂 .

Thank you in advance!

**Comment by ErikEJ** [comment]
EF Core scaffolding always skips any conventional configuration by design. I you want more explicit configuration, Data annotations could be any option.

**Comment by ErikEJ** [comment]
@cezarlamann Ping?

**Comment by cezarlamann** [comment]
Hi ErikEJ. Thank you for your prompt reply! I'll look into the results of using annotations instead of fluent mapping.
