### ISSUE TITLE
EF Power Tools does not create classes to match DB.  Some stored procs are missing

### ISSUE THREAD

**Issue by pcapozzi** [ErikEJ/EFCorePowerTools#1947]
Create a bug report, feature proposal, or ask a question.

NOTICE: A bug report without sufficient technical and repro details and version information WILL BE CLOSED WITHOUT ANY FURTHER ACTION.

### Provide steps to reproduce a bug

Please include a **complete** description of the issue or link to a project that I can run to reproduce the issue.

I am running a simple reverse engineer.  These sprocs : ShowChargingSummary4YearUser, 
GetTimeOfDayConstraints
GetUserData
GetUserDataEmail
GetUserDataFromEmail
ShowChargingSummary4Year
ShowChargingSummary4YearUser

DO NOT SHOW UP IN MODEL
 
### Provide technical details

- EF Core Power Tools version: 25.1607

- Exact Visual Studio version:17.7.4

- Database engine: Sql server

- EF Core version in use: (e.g. EF Core 7)  7

- Is Handlebars templates used: no/yes don't know, so probably not

- Is T4 templates used: no/yes don't know, so probably not

- Is a SQL Server .dacpac used: no/yes don't know, so probably not

[EVPOWERdb.zip](https://github.com/ErikEJ/EFCorePowerTools/files/12725047/EVPOWERdb.zip)

**Comment by ErikEJ** [comment]
@pcapozzi  There are no database objects in the attached script

**Comment by pcapozzi** [comment]
Sorry, I should have remembered that I have been fooled by that before in
SQL Server.

Here is a full script.

Thanks for getting back to me.

Regards,

PatC

**Comment by ErikEJ** [comment]
Where is the full script? You must reply on Github and upload an attachment

**Comment by pcapozzi** [comment]
Ok will do.

**Comment by pcapozzi** [comment]
Here is the script.  Thanks for your quick response on this.

[evpoweall.zip](https://github.com/ErikEJ/EFCorePowerTools/files/12731144/evpoweall.zip)

**Comment by ErikEJ** [comment]
@pcapozzi Did you not see these warnings in the Extensions output window?

warning: Unable to scaffold PROCEDURE 'dbo.GetUserData' as it has duplicate result column names: 'id'.
warning: Unable to scaffold PROCEDURE 'dbo.GetUserDataEmail' as it has duplicate result column names: 'id'.
warning: Unable to scaffold PROCEDURE 'dbo.GetUserDataFromEmail' as it has duplicate result column names: 'id'.
warning: Unable to scaffold PROCEDURE 'dbo.ShowChargingSummary4Year' as it has duplicate result column names: 'Month'.
warning: Unable to scaffold PROCEDURE 'dbo.ShowChargingSummary4YearUser' as it has duplicate result column names:
'Month'.

**Comment by pcapozzi** [comment]
Hi Erilk,

I looked high and low for the 'Extensions output window' but could not find
it. I googled it to no avail.
Sorry for the trouble.  Just for further clarification, how do you find
that particular window?

Sorry for the bother.

Regards,

PatC

**Comment by ErikEJ** [comment]
View menu, Output, and select "Extensions" from the dropdown on top

**Comment by pcapozzi** [comment]
Thanks very much for the information.
