### ISSUE TITLE
EF Core Power Tools having problem with stored procedure with sql statement string

### ISSUE THREAD

**Issue by phinq190778** [ErikEJ/EFCorePowerTools#1949]
Hello @ErikEJ  
i have problem using REVERSE ENGINEER of EF Core Power Tools having problem with stored procedure with sql statement string 
let's say I have stored procedure;
alter PROCEDURE [dbo].[GETPRODUCT] @SupplierID INT=0,@CategoryID INT=0
AS
BEGIN
declare @sql nvarchar(max);
declare @sqlWhere nvarchar(max);
SET @sqlWhere=' WHERE 1=1 '
IF @SupplierID>0
	SET @sqlWhere=@sqlWhere+' AND SupplierID='+CONVERT (VARCHAR(50), @SupplierID,128)
IF @CategoryID>0
	SET @sqlWhere=@sqlWhere+' AND CategoryID='+CONVERT (VARCHAR(50), @CategoryID,128)
SET @sql='SELECT * FROM Products'+@sqlWhere
exec sp_executesql @sql
END
when I use EF Core Power Tools' REVERSE ENGINER it doesn't return list it returns int

public virtual async Task(int) GETPRODUCTAsync(int? SupplierID, int? CategoryID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
{
    var parameterreturnValue = new SqlParameter
    {
        ParameterName = "returnValue",
        Direction = System.Data.ParameterDirection.Output,
        SqlDbType = System.Data.SqlDbType.Int,
    };

    var sqlParameters = new []
    {
        new SqlParameter
        {
            ParameterName = "SupplierID",
            Value = SupplierID ?? Convert.DBNull,
            SqlDbType = System.Data.SqlDbType.Int,
        },
        new SqlParameter
        {
            ParameterName = "CategoryID",
            Value = CategoryID ?? Convert.DBNull,
            SqlDbType = System.Data.SqlDbType.Int,
        },
        parameterreturnValue,
    };
    var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[GETPRODUCT] @SupplierID, @CategoryID", sqlParameters, cancellationToken);

    returnValue?.SetValue(parameterreturnValue.Value);

    return _;
}

Please tell me why it doesn't work and how to fix it

**Comment by ErikEJ** [comment]
@phinq190778 It is because it is not possible to discover the result set shape from dynamic SQL

**Comment by phinq190778** [comment]
Thank you @ErikEJ
