### ISSUE TITLE
Use or provide option for ApplyConfigurationFromAssembly when splitting dbcontext

### ISSUE THREAD

**Issue by PilotBob** [ErikEJ/EFCorePowerTools#1950]
When generating the code with the split-dbcontext-preview to true the code is generating a:

modelBuilder.Applyconfiguration(new Configurations.ModelTypeConfiguration());

for each configuration file / model.

Is it possible to generate instead:

modelBuilder.ApplyConfigurationsFromAssembly(typeof(DbContextTypeName).Assembly);

or provide an option for same? This will reduce the size of the dbcontext file substantially for large models.

Perhaps it is done this way to allow for AOT since the current method doesn't need reflection?

### Provide technical details

- EF Core Power Tools CLI version: 8.0.0-rc.11

- Database engine: SQL Server

- EF Core version in use: EF 8 rc1

- Is Handlebars templates used: no

- Is T4 templates used: no

- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
I think it will add complexity when classes are located in a different assembly.

**Comment by PilotBob** [comment]
Given you are generating the DbContext and the Configuration files are generated into the same path as the Dbcontext, won't the configuration files always be in the same Assembly as the DbContext?

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by PilotBob** [comment]
Hi, I'm using the CLI. Is there a tools install version that I can test this with?

**Comment by ErikEJ** [comment]
I have created #1957

**Comment by ErikEJ** [comment]
@PilotBob  I have published rc.12 now

**Comment by ErikEJ** [comment]
I had a feeling this would backfire! I will revert for now soon.

**Comment by ErikEJ** [comment]
I have reverted this, .ApplyConfigurationsFromAssembly is not a viable general solution.

I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

**Comment by PilotBob** [comment]
I always expected you would add it as an option. :)

**Comment by ErikEJ** [comment]
If I get more votes I will consider. But no one else have ever asked for it..
