### ISSUE TITLE
Install on VS 2022 Community Edition

### ISSUE THREAD

**Issue by largebergo** [ErikEJ/EFCorePowerTools#1951]
Create a bug report, feature proposal, or ask a question.

NOTICE: A bug report without sufficient technical and repro details and version information WILL BE CLOSED WITHOUT ANY FURTHER ACTION.

### Provide steps to reproduce a bug

I cannot install EF Core Power Tools on VS 2022 on Windows 11 using Parallels on Mac OS Sonoma.

### Provide technical details

- EF Core Power Tools version: (2.5.1607)

- Exact Visual Studio version: (Visual Studio Community 2022 Arm 64 17.7.4)

**Comment by ErikEJ** [comment]
VS ARM is not supported, use the CLI instead.

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.
