### ISSUE TITLE
Don't create Procedures class if there are no procedures

### ISSUE THREAD

**Issue by MisinformedDNA** [ErikEJ/EFCorePowerTools#1953]
efcpt will create a ContextProcedures class even when there are no stored procedures. This creates unnecessary noise. Additioanlly, if the DB has stored procedures but none are generated, the ContextProcedures class should also not be generated.

### Provide steps to reproduce a bug

1. Find a DB that has no stored procedures
2. Run efcpt on that DB

EXPECTED:

The ContextProcedures class is not created.

ACTUAL:

The ContextProcedures is created.

### Provide technical details

- EF Core Power Tools version: 7.0.0-rc.11

- Database engine: SQL Server

- EF Core version in use: EF Core 7

- Is Handlebars templates used: no

- Is T4 templates used: no

- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
Is it different in the VS extension?

**Comment by MisinformedDNA** [comment]
Yes.

**Comment by ErikEJ** [comment]
Check the efcpt-config.json file for objects that do not belong in the database, I found a bug relating to getting rid of them in the CLI code.

**Comment by ErikEJ** [comment]
Also, do you have soft delete enabled?

**Comment by MisinformedDNA** [comment]
I took another look, and it is correct most of the time. However, the class is created if an initial catalog isn't specified, which was my mistake.

**Comment by ErikEJ** [comment]
Cool. Your report Exposed a bug if you changed data source
