### ISSUE TITLE
Why was UseNoNavigations removed?

### ISSUE THREAD

**Issue by MisinformedDNA** [ErikEJ/EFCorePowerTools#1954]
I have some migration code (moving data from one DB to another), but with [UseNoNavigations removed](https://github.com/ErikEJ/EFCorePowerTools/commit/f5fde29a74add326a10bf2efc71223d3a05e7bfa), I'm getting EF Core attach errors. I created a Handlebar template, that skips adding the properties to the class, but then all the configuration files break and I don't see a way to customize those.

What are my options?

### Provide technical details

- EF Core Power Tools version: 2.5.1607

- Exact Visual Studio version: Visual Studio 2022 17.7.3

- Database engine: SQL Server

- EF Core version in use: EF Core 7

- Is Handlebars templates used: yes

- Is T4 templates used: no

- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
I think you can use T4 templates.

**Comment by ErikEJ** [comment]
NoNavigation was replaced with the POCO T4 template (which also demonstrates how you can remove navigations in the standard T4 template)

**Comment by MisinformedDNA** [comment]
I few things:

- I get this error every time, I regenerate the model: "The latest T4 template version could not be found, looking for 'Template version: 703' in the T4 file - please update your T4 templates, for example by renaming the CodeTemplates folder."
- I get this prompt every time I open a generated file: 

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/1784452/6b85a82f-8145-4330-862d-bdfa45109214)

- It also broke the build. While the POCOs do not have navigations, the Configuration files are still trying to access them like they are.

Is there a way for me to install a preview version where UseNoNavigations still exists? This is blocking me from getting my actual work done. I need more time to figure out the templates.

**Comment by ErikEJ** [comment]
Are you using the POCO templates?

They are mainly for use in non-EF scenarios. 

The line ending warning could be related to your Github settings?

I have a couple of older unsupported build in the tools folder in this repo, no idea if they have the NoNavigstions feature.

**Comment by MisinformedDNA** [comment]
> Are you using the POCO templates?
> 
> They are mainly for use in non-EF scenarios.

But this is EF Core Power Tools. UseNoNavigations was an extremely useful feature for those practicing DDD.

So, to replace UseNoNavigations, I have to use POCO templates and stop using EF Core?

**Comment by ErikEJ** [comment]
DDD <=> reverse engineering.

As I wrote in my first reply, I think you can use the t4 templates. If that is not possible, maybe you can create a PR? You are the first and only user missing it ...

**Comment by Montago** [comment]
I'd like to pitch in that i would like to disable NavigationProperties. 

currently they are causing problems 

- When serializing JSON, eventhough LazyLoading is disabled !
- LINQ'ing seem to take effect, Group By cant be translated into SQL (which is also caused if you group by on nullable columns)

**Comment by ErikEJ** [comment]
I will bring it back

**Comment by ErikEJ** [comment]
Created #1962 to also add this to CLI edition

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

**Comment by Montago** [comment]
Testing now.. 

My WCF project has been messing up all day and i finally narrowed it down to EFCore Navigation properties that automatically link up on my return object (gaaah) 

So I appreciate this update very much !

**Comment by Montago** [comment]
well, my SQL Data connector thing broke in Visual Studio .. cant connect to the SQL Servers in the Server List window. 

and EF Core Power Tools coudn't show my SQL Server connection... 

I'm repairing my Visual Studio now :-/

**Comment by Montago** [comment]
The update seems to work now, 1 hour later after a setback. 

I disabled the navigation properties and they are now gone !

AND - my project it working now !

Thanks !

**Comment by ErikEJ** [comment]
@Montago great, thanks for confirming
