### ISSUE TITLE
Triggers are not configured with Handlebars template

### ISSUE THREAD

**Issue by MisinformedDNA** [ErikEJ/EFCorePowerTools#1955]
### Provide steps to reproduce a bug

1. Find/create a DB with triggers on one of the DBs
2. Reverse engineer the DB

Without templates:

```cs
entity.ToTable("SomeTable", "dbo", tb =>
{
    tb.HasTrigger("tr_SomeTable");
});
```

With Handlebar templates:

```cs
entity.ToTable("SomeTable", "dbo");
```

### Provide technical details

- EF Core Power Tools version: 2.5.1607

- Exact Visual Studio version: Visual Studio 2022 17.7.3

- Database engine: SQL Server

- EF Core version in use: EF Core 7

- Is Handlebars templates used: no

- Is T4 templates used: no

- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
Please report in the Handlebars repo
