### ISSUE TITLE
Multiple efpt.config.json

### ISSUE THREAD

**Issue by acattani123** [ErikEJ/EFCorePowerTools#1956]
Create a bug report, feature proposal, or ask a question.

NOTICE: A bug report without sufficient technical and repro details and version information WILL BE CLOSED WITHOUT ANY FURTHER ACTION.

### Provide steps to reproduce a bug

Please include a **complete** description of the issue or link to a project that I can run to reproduce the issue.

### Provide technical details

- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)

- Exact Visual Studio version: (e.g. Visual Studio 2022 17.6.5)

- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)

- EF Core version in use: (e.g. EF Core 7)

- Is Handlebars templates used: no/yes

- Is T4 templates used: no/yes

- Is a SQL Server .dacpac used: no/yes

**Comment by acattani123** [comment]
I manage reverse engineering with 2 contexts in my project. EFPT can manage the 2 contexts but produces only one efpt.config.json which has the configuration of the last context updated. So, it cannot maintain tables and other parameters of each context separately, but every time it update a context the last context information overwrites the other one. It would be desirable to have 2 two or more contexts tracked separately, with their own config file. Thank you for the great job.

**Comment by ErikEJ** [comment]
There a multiple ways to do this, despite it being an anti-pattern, as described in the docs: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#using-multiple-dbcontexts-in-the-same-project

**Comment by ErikEJ** [comment]
@acattani123 you are very welcome.

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
