### ISSUE TITLE
Error when reverse engineering on .NET Framework with EF Core 3.1

### ISSUE THREAD

**Issue by weastaugh** [ErikEJ/EFCorePowerTools#1959]
### Provide steps to reproduce a bug

I've been successfully using EF Core Power Tools in a .NET Framework project referencing EF Core 3.1 but now (presumably after the latest update) I'm getting the error: 

`.NET 5 and earlier projects are no longer supported`

The `EF Core Power Tools` context menu option is then greyed out.

Can you make it work for my scenario or make an earlier version available?

### Provide technical details

- EF Core Power Tools version: 2.5.1607

- Exact Visual Studio version: Visual Studio 2022 17.7.5

- Database engine: SQL Server

- EF Core version in use: EF Core 3.1

- Is Handlebars templates used: n/a

- Is T4 templates used: n/a

- Is a SQL Server .dacpac used: no

- .NET version in use: .NET Framework 4.8

**Comment by ErikEJ** [comment]
@weastaugh EF Core 3.1 is out of support, but you can download an unsupported extension installer from the tools folder in this repository

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by weastaugh** [comment]
Hi @ErikEJ 

Thanks for that. Is this the correct file you're referring to?

https://github.com/ErikEJ/EFCorePowerTools/blob/master/tools/EFCore31Support/EF_Core_Power_Tools_v2.5.1429.vsix.zip

The zip file doesn't have a .vsix file in it. Can you provide guidance on how to install it?

Thanks!

**Comment by ErikEJ** [comment]
Yes, just rename to .vsix and double click.
