### ISSUE TITLE
publish CLI rc.12

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#1964]

**Comment by clintsinger** [comment]
Where is the CLI?  I believe I have been all over this project and everything leads me to this empty page.

https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/efcpt/readme.md

Has it been moved?

**Comment by ErikEJ** [comment]
I moved it  but did not Update the link. I have done that now.
