### ISSUE TITLE
EFCore and Trigger warnings

### ISSUE THREAD

**Issue by o0JoeCool0o** [ErikEJ/EFCorePowerTools#1965]
Im using reverse engineer a lot and was wondering if there is a way to specify HasTrigger for databases with triggers as I get the dreaded OUTPUT Sql clause / no triggers allowed for EFCore error. I can fix it by adding it manually to the context.cs but then it gets overwritten on the next reverse engineer operation.

**Comment by ErikEJ** [comment]
Please provide the details requested when creating issues, otherwise I cannot assist you.

As far as I know, EF Core 7 or later scaffolds HasTrigger automatically

**Comment by ErikEJ** [comment]
See #1512

**Comment by ErikEJ** [comment]
@o0JoeCool0o Ping?
