### ISSUE TITLE
.Net 8 Support

### ISSUE THREAD

**Issue by teeravee** [ErikEJ/EFCorePowerTools#1966]
There are features (Migration Tool and Compare DbContext to database) that cannot run on EF Core 8 (8.0.0-rc.2.23480.1) and Visual Studio 2022 (17.8.0 Preview 3.0).

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/1845881/2c65d302-d68e-48ad-a358-baa9409282ed)

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/1845881/dc8dda79-3e8e-4c68-8f20-ec7abb7a8dc1)

**Comment by ErikEJ** [comment]
.NET 8 is fully supported, the first error is caused by your DbContext, see some tips here: https://github.com/ErikEJ/EFCorePowerTools/wiki/Inspect-your-DbContext-model

The Compare tool is not available for .NET 8, it depends on a third party library that has not yet been updated.

**Comment by ErikEJ** [comment]
Compare tool added in latest daily build
