### ISSUE TITLE
Question: Run rebuild from Code at runtime for custom fields

### ISSUE THREAD

**Issue by glewisformsol** [ErikEJ/EFCorePowerTools#1968]
This is more a question than an issue, I have a requirement on my project. 

I am syncing data from an online API in where I will get the meta data of the objects and create the tables and fill the table.  95% of the properties are standard and do not change.  But the system allows for custom fields to be added, those fields then will be sent over in the meta data and the json data (table data) when I call the API. 

I have multiple environments this API is calling from (multiple customers).  Each environment has a separate Database I am syncing the data into.  Each database the tables can differ from one another because of the Custom Fields and Custome Tables added to their ERP environment.  

I am trying to find an easier way of managing the Strong typed classes to add them at runtime when the sync occurs for the different environments.  I know I can add to the class the new fields, but I don't know how to map those to the EF Core at runtime.

I have everything working except the addition of the custom records, the sync the merging of data all of it.  I just need to find a way to use EF Core to manage the new fields that are added at runtime.  

I am using the EF ado execute command to update and manage the tables as the structure changes.  I was thinking maybe I could leverage the power tools I used to scaffold the database and then recompile the DLL via code.  Since the project is setup as a windows service project.  Then installed on the customers SQL Server.   All the settings for each customer are stored in a central Server that the service calls on to know the database structure based on the Meta Data from the API calls.  

I would like to stick to the EF Core due to the Z Entity Framework because of its bulk merge functionality.  

Thank you for anyone willing to give me a path forward to custom fields at runtime or code to kick the power tools and recompile.

**Comment by ErikEJ** [comment]
EF Core is based on strongly typed classes, and not the right tool for this. Also, an app cannot rebuild itself.

**Comment by glewisformsol** [comment]
Thank you for your time, if you have any suggestions I would be open to it.  

I know there are other developers who have to work with custom fields in their system, how would you approach this?

**Comment by ErikEJ** [comment]
Store metadata about the custom fields and tables and generate SQL statements based on the metadate and use the metadata to present the additional fields.

**Comment by glewisformsol** [comment]
I am using the API to grab the data and store into the local Database so they can create custom reporting and mine the data, the whole project is to translate the api data into SQL DB tables.  I started with EF Core because of it's powerful tool to merge data sets quickly.  I guess I will have to go back to pure ADO but it doesn't have a good method for getting the data then bulk merging into the local DB.

I will have to go back to the design and see if there are other technologies for handling this. 

using the EF Core I was able to grab the data and merge in a second or two.  ADO just to traverse the data takes a long time to then compare and test what needs to be updated/inserted/deleted. I am working with 100's of tables EF Core solved the main issues but limited me to non custom fields.

**Comment by ErikEJ** [comment]
You are using an EF Core extension to generate MERGE statements. They can also be generated by your code.

**Comment by glewisformsol** [comment]
I will run SQL profiler and capture what they are doing, I suspect they are creating temp tables then using the SQL Merge syntax for the merge into the destination table.   I will look into that, thank you so much for your insight.

**Comment by glewisformsol** [comment]
I did find this article I will try it first before redoing my project it may be a rabbit hole lol but i will try it. 

https://www.thinktecture.com/en/entity-framework-core/ef-core-user-defined-fields-and-tables/
https://github.com/thinktecture-labs/article-ef-core-user-defined-fields-and-tables/
