### ISSUE TITLE
Reverse Engineering is not an option

### ISSUE THREAD

**Issue by JeeveshSharmaWork** [ErikEJ/EFCorePowerTools#1969]
### Provide steps to reproduce a bug

i was using VS 2022 17.6.2, EF Core Power Tools was working fine, then i upgraded to VS 2022 17.7.5, which didn't work on my laptop and resulted in Blue Screen of Death whenever opened, so i rolled back to 17.6.2, and then installed EF Core Power Tools which were removed when i rollbacked, now there is no option for Reverse Engineer. There are only two options : 
   1.) Visualize Database Schema 2.) About

### Provide technical details

- EF Core Power Tools version: 2.5.1607

- Exact Visual Studio version:  Visual Studio 2022 17.6.2

- Database engine: MySQL

- EF Core version in use: 6.4.4

- Is Handlebars templates used: no

- Is T4 templates used: no

- Is a SQL Server .dacpac used: no

<img width="430" alt="Screenshot 2023-10-19 104646" src="https://github.com/ErikEJ/EFCorePowerTools/assets/120725441/390df44e-30e1-4862-9bbf-20ec28175e3c">

**Comment by ErikEJ** [comment]
Is you project .NET 6.0 or newer, older versions are no longer supported?

**Comment by ErikEJ** [comment]
@JeeveshSharmaWork Ping?
