### ISSUE TITLE
Create Interface based DbContext

### ISSUE THREAD

**Issue by nssidhu** [ErikEJ/EFCorePowerTools#1970]
Currently the dB context that is created is a Concrete Class.

Like here

public partial class XXXXADBContext : DbContext
{
    public XXXXADBContext (DbContextOptions<XXXXADBContext > options)
        : base(options)
    {
    }

}

.....

I am using Blazor Project where i have separated my Project into several Class Libraries Project
One of the Project is Model, which contains DTO and Fluent Validators.
One of the Fluent validations need to get data from Database.
It would be nice if i could use Interface to inject Dbcontext here.

public class UserStoryValidator : AbstractValidator<UserStory>
{
    private readonly YourDbContext _dbContext;

    public UserStoryValidator(YourDbContext dbContext)
    {
        _dbContext = dbContext;

        RuleFor(x => x.StateOfIncidentID_FK)
            .Must(IsStateOfResidenceSelected)
            .WithMessage("Please select a State of Residence.");
    }

    private bool IsStateOfResidenceSelected(Guid stateId)
    {
        // Use _dbContext to query the database here
        var state = _dbContext.States.FirstOrDefault(s => s.Id == stateId);

        return state != null;
    }
}

To enable such use case Can EF Core generate Interface based DbContext, so that interface can be injected in other Projects ?

==================================================================================

NOTICE: A bug report without sufficient technical and repro details and version information WILL BE CLOSED WITHOUT ANY FURTHER ACTION.

### Provide steps to reproduce a bug

Please include a **complete** description of the issue or link to a project that I can run to reproduce the issue.

### Provide technical details

- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)

- Exact Visual Studio version: (e.g. Visual Studio 2022 17.6.5)

- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)

- EF Core version in use: (e.g. EF Core 7)

- Is Handlebars templates used: no/yes

- Is T4 templates used: no/yes

- Is a SQL Server .dacpac used: no/yes

**Comment by ErikEJ** [comment]
You can just Inject the derived DbContext, no interface is needed.  

If that does not help, I need a full repo as stated when you create new issues.
