### ISSUE TITLE
How to Reverse Engineer an Sqlite DB 

### ISSUE THREAD

**Issue by mwardell-Katmai** [ErikEJ/EFCorePowerTools#1972]
I am attempting to use Reverse Engineer on my sqlite Db.
I have VS 2022 17.7/5
I also have the Power Pack installed
and an existing Sqlite DB
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/139899254/2fa40d52-2988-41bf-8941-2d1989073b6e)

I am having trouble on the Reverse Engineering Dialog to connect to my DDEX (Provided by VisualStidio.Data.Sqlite)
What do i need to do get this in 'Reverse?'
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/139899254/1408f9bf-cc59-4907-bf55-271cece44dc1)

**Comment by ErikEJ** [comment]
In Choose Your Data Connection, choose "Add" => "Add Database Connection" => "Change" button:

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/4169187/ac7c8ddd-1f01-47c2-8952-2796833fa222)

Point to your database file, and it will be selected on the dropdwon list

**Comment by mwardell-Katmai** [comment]
Thanks! That Worked

**Comment by ErikEJ** [comment]
Were the docs unclear ? Maybe I should add more details?

**Comment by ErikEJ** [comment]
I have updated the docs: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#choose-data-source

**Comment by mwardell-Katmai** [comment]
no I confused myself... I had another tool VisualStudio.Data.Sqlite That was a so-called DDEX provider. As soon as I focused on the Native Data Connections I had it all! Thanks. 

Do you  know if people are succeeding on Android and iOS with EF? in MAUI? Thanks for your help.

**Comment by ErikEJ** [comment]
Re MAUI - yes, it works with Sqlite.
