### ISSUE TITLE
Omitting InverseProperties

### ISSUE THREAD

**Issue by jasonsheridan79** [ErikEJ/EFCorePowerTools#1974]
Erik,

Love the tool, use it on a daily basis!  Apologies if it's in the User Guide, I did look through it, but might have missed it; is there a setting to not have the tool generate the backward InverseProperty Attribute when reverse engineering?  In my project, I have quite a few downward only lookup tables and I don't need or want my lookup POCOs to have upward visibility.  I know I can just remove them myself, that's what I inevitably do, but curious if there's a setting to not allow that to make refreshes quicker and easier in this scenario.    

### Provide technical details

- EF Core Power Tools version: 2.5.1569

- Exact Visual Studio version: Visual Studio 2022 17.7.0

- Database engine: SQL Server

- EF Core version in use: EF Core 7

- Is Handlebars templates used: no

- Is T4 templates used: no

- Is a SQL Server .dacpac used: no (live db connection)

**Comment by ErikEJ** [comment]
Maybe Use no navigations? Just added in the latest release?

**Comment by jasonsheridan79** [comment]
Awesome, I'll check it out, thank you!

**Comment by ErikEJ** [comment]
Alternatively:

Create views on top of the lookup tables and unselect the base lookup tables - you could even rename the views to have same names as the base lookup tables.

**Comment by ErikEJ** [comment]
If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by jasonsheridan79** [comment]
Done and done, enjoy a case of beer on me!

**Comment by jasonsheridan79** [comment]
I tried the no navigations option, it worked, but too well, that's a bit of a case of using a hammer to kill a fly.  It worked as advertised, no relationships at all.  What I'm looking for is if you have a table Thing, and Thing has a foreign key relationship to table Status.  I'd like the POCO to reflect exactly that:

```
public partial class Thing
{
    [Key]
    public Guid ThingId { get; set; }

    public Guid StatusId { get; set; }

    [ForeignKey("StatusId")]
    public Status Status { get; set; }
}

public partial class Status
{
    [Key]
    public Guid StatusId { get; set; }

    public string Name { get; set; }
}
```

Whereas a I'm seeing:

```
public partial class Status
{
    [Key]
    public Guid StatusId { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Thing> Thing{ get; set; } = new List<Thing>();
} 
```
   
I'm looking to get rid of the ICollection<Thing> property that looks back at the parent.  I just don't need it, there is no connection in the database from Status > Thing, it's only Thing > Status.  Maybe that would be the setting, "Map only direct navigation references", help reduce EF bloat. 

And it's fine, right now I have the tool do its thing, then I go and do a manual migration using Beyond Compare to make sure I only bring references I want, it really isn't difficult.  It would just be nice to tell me team, hey, this is how you do an update to EF, click here and here.

**Comment by ErikEJ** [comment]
@jasonsheridan79 You are the first user in the known universe to be asking for this - I think t4 templates wil be the best option. Foreign keys represent a two way connection between tables, and that is what the scaffolding reflects.

**Comment by jasonsheridan79** [comment]
Lol, that's funny, now I feel special.  

But, really?  If I was writing my c# POCO as code-first, I wouldn't write it like that, with a built-in circular reference.  It would be Foo can have one Bar (or many, depending on the situation), and Bar just has its own properties, not a reference back to many Foos.  If I wanted all the Foos with a Bar of Status A, I would just write that as context.Foos.Where(e => e.Bar.Status == "A"), not context.Status.Where(e => e.Id =="A").Include(e => e.Foos).  I mean, I know foreign keys are "two way", but they are set on just one table, Bar doesn't necessarily know about Foo in the database, the foreign key is set on Foo, or a Foo_Bar joiner.

Either way, your tools are still a big help, and massaging the output to look how I want is very much a first world problem.  No big deal, I was just asking if there was a setting in PowerTools I wasn't seeing to stop circular references.
