### ISSUE TITLE
Reverse Engineer - Handlebars.registerHelper

### ISSUE THREAD

**Issue by chpo69** [ErikEJ/EFCorePowerTools#198]
Is it possible to use Handlebars.registerHelper? I would like make customize properties !

Simple example :
`
    Handlebars.registerHelper('GetNavPropertyName', function(navPropertyName) {
    return navPropertyName;
    });

{{#each properties}}
{{#each property-annotations}}
{{spaces 8}}{{{property-annotation}}}
{{/each}}
{{spaces 8}}public {{property-type}} {{property-name}} { get; set; }
{{/each}}
{{#if nav-properties}}

{{#each nav-properties}}
{{#each nav-property-annotations}}
{{spaces 8}}{{{nav-property-annotation}}}
{{/each}}
{{#if nav-property-collection}}
{{spaces 8}}public virtual ICollection<{{nav-property-type}}>
    {{nav-property-name}} { get; set; }
    {{else}}
    {{spaces 8}}public virtual {{nav-property-type}} {{GetNavPropertyName nav-property-name}} { get; set; }
    {{/if}}
    {{/each}}
    {{/if}}
`

**Comment by ErikEJ** [comment]
No, it is not, unfortunately
