### ISSUE TITLE
Generated code doesn't have a default constructor

### ISSUE THREAD

**Issue by amenkes** [ErikEJ/EFCorePowerTools#1980]
`  using var dbContext = new ReportDbContext(); // gives error because:`

```
public partial class ReportDbContext : DbContext
{
    public ReportDbContext(DbContextOptions<ReportDbContext> options)
        : base(options)
    {
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        OnModelCreatingGeneratedProcedures(modelBuilder);
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}

```
However the examples show that you can without passing 'options'.

I have a console app, with this:

```
 var configuration = new ConfigurationBuilder()
     .SetBasePath(Directory.GetCurrentDirectory())
     .AddJsonFile("appsettings.json", optional: false)
     .AddEnvironmentVariables()
     .Build();

 services.Configure<Settings>(options => configuration.GetSection(Constants.SettingsConstants.SettingSection).Bind(options));
 services.AddDbContext<ReportDbContext>(options => options.UseSqlServer(configuration.GetConnectionString("DefaultConnection")));


```

and in appsettings.json

"connectionStrings":
{
	"defaultConnection": "Data Source=xxxxxx\\dev2008;Initial Catalog=MyDbGoesHere;Integrated Security=True;"
},
"settings":
{
	"reports":
	{
		"modelSearch":
		{
			"name": "Searched Models {0} to {1}"
		},
		....
...

So, what am I missing?

**Comment by ErikEJ** [comment]
You are not supplying any of the information required when creating an issue here.

But no constructor is by design. If you need one, you can add it in a partial class, or it will also appear if you include your connection string in the generated code.

**Comment by ErikEJ** [comment]
Also, you can just use standard Microsoft Dependency injection, and inject a instance via your class constructor.
