### ISSUE TITLE
Pluralizer needs option to not singularize.

### ISSUE THREAD

**Issue by pj6** [ErikEJ/EFCorePowerTools#1983]
Regarding the "pluralize or singularize generated object names" option in the Reverse Engineer feature:

Since SQL table names should always be singular, there should be an option to turn singularization off.

Recommending this change because singularization changes table names like OrderStatus to OrderStatu.

- EF Core Power Tools version: 2.5.1639
- Visual Studio 2022 17.7.0
- Database engine: SQL Server
- EF Core 7

**Comment by ErikEJ** [comment]
That is a pluralizer "bug" that you can override as described in the wiki with "uncountable words"
