### ISSUE TITLE
how ef core power tools knows/infers that the relation is one-to-one or one-to-many ?

### ISSUE THREAD

**Issue by rasoul-tiebreak** [ErikEJ/EFCorePowerTools#1984]
how ef core power tools knows/infers that the relation is one-to-one or one-to-many ?

**Comment by ErikEJ** [comment]
Based on the foreign key relationship.

**Comment by rasoul-tiebreak** [comment]
I have entity/table BonusPromotionCode, BonusPromotionCodeVaultPackage ,BonusPromotionCodeBrand , both BonusPromotionCodeVaultPackage  and BonusPromotionCodeBrand [have a column](https://prnt.sc/Ul_Mz-vzw-SG) BonusPromotionCodeId as FK int Not null to BonusPromotionCode. but generate code is different .

  entity.HasOne(d => d.BonusPromotionCode)
                    .**WithMany**(p => p.BonusPromotionCodeBrands)
                    .HasForeignKey(d => d.BonusPromotionCodeId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                 .HasConstraintName("FK_BonusPromotionCodeBrandsBonusPromotionCodeId_BonusPromotionCodesBonusPromotionCodeId");

And

entity.HasOne(d => d.BonusPromotionCode)
                    .**WithOne**(p => p.BonusPromotionCodeVaultPackage)
                    .HasForeignKey<BonusPromotionCodeVaultPackage>(d => d.BonusPromotionCodeId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_BonusPromotionCodeVaultPackagesBonusPromotionCodeId_BonusPromotionCodesBonusPromotionCodeId");

**Comment by ErikEJ** [comment]
Share you table schema, and you can probably see why

**Comment by rasoul-tiebreak** [comment]
Thank u

**Comment by rasoul-tiebreak** [comment]
There was a unique constraint there

**Comment by rasoul-tiebreak** [comment]
by creating  database diagram in mssql server, found out that there is a unique constraint that make relation one to one.
