### ISSUE TITLE
scaffold with dacpac reference in CLI

### ISSUE THREAD

**Issue by k0zi** [ErikEJ/EFCorePowerTools#1985]
I've created a hierarchical Db structure. 2 sql project, one is using the other as dacpac reference. I'm using the following command to scaffold my dacpac:

dotnet ef dbcontext scaffold "C:\Dev\Sources\Multibase\Webshop\bin\Debug\Webshop.dacpac" ErikEJ.EntityFrameworkCore.SqlServer.Dacpac --verbose --project "C:\Dev\Sources\Multibase\Webshop.EfCore\Webshop.EfCore.csproj" --output-dir "Models" --force

Because there are foreign keys that refer to the tables in the other dacpac, the process exited (throws exception):
"System.InvalidOperationException : Sequence contains no elements"

I've downloaded the source code, and modifieded the DacpacTest.cs CanEnumerateTables test case, loaded my dacpac, and it throws the same exception. After I changed line 29 to this:
`var factory = new SqlServerDacpacDatabaseModelFactory(new SqlServerDacpacDatabaseModelFactoryOptions { MergeDacpacs = true });`
It works well.

Is that possible to use the MergeDacpacs options in command line?

Using the latest version of .NET 7 and EF Core

**Comment by ErikEJ** [comment]
>> Is that possible to use the MergeDacpacs options in command line?

No, not with the Nuget package - but if you are interested I could consider adding it to the Power Tools CLI (command line tool) ?

**Comment by k0zi** [comment]
I've a large legacy SQL database in sqlproj, and I've tried to build a CI/CD pipeline, to generate C# object and packages in command line, so I'm interested :)

**Comment by ErikEJ** [comment]
I have uploaded rc.14 with this feature enabled.

**Comment by k0zi** [comment]
I've reconfigured my project tried the tool, but still throws exception
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/3050610/61d2ed03-846d-4088-aec5-1e5dfea8df20)
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/3050610/23401b65-c8fc-4ef9-b8e4-c90bbf67665d)
I've made a test project. I'm trying to find the problem

**Comment by ErikEJ** [comment]
@k0zi Please share a sample .dacpac or database project, and I will have a look.

**Comment by ErikEJ** [comment]
@k0zi Did you enable the "merge-dacpacs" option?

**Comment by k0zi** [comment]
Sorry, my fault. The first run said the Merge-dacpacs is true, and the second run is from the .json config file overwrites it to false. After edited the .json file, and set the option to true, it worked well, all the items generated.
