### ISSUE TITLE
CLI features discussion

### ISSUE THREAD

**Issue by clintsinger** [ErikEJ/EFCorePowerTools#1989]
I'm looking to use the CLI in my project and I have been unable to find whether I can do the following things.   If they aren't available, I'll go ahead and open them as feature requests.  This is more a discussion about the various concepts.  One thing that I didn't find clear is what you can do in the VS extension vs the CLI.   It looks like they are independent so if a feature exists in the VS extension, it might not yet be available in the CLI?

1) Namespace specific tables/entities
I have various tables that I would like to put into their own folder/namespace but still share the same DbContext.   This is to help keep the entities organized by function rather than the default behavior of putting them all in the same folder.   

    For example, this would put the `Organization` entity into the `Accounts` namespace of the project (including putting it into the corresponding folder based on a setting of how to handle namspacing)
```
{
  "tables": [
    {
       "name":  "organization",
       "namespace": "Accounts"
    }
  ]
}
```

2) Column type assignments
There are situations where you may want to override the type that is associated with a column.  This is especially true for JSON columns where the database doesn't know anything about what the type should be.   By defining the type explicitly then the reverse engineering process will assign a explicit type instead of assigning it to the default, such as `string` for a JSON column.   The developer would have to ensure that the type exists, either in the same project as the entity or imported as a dependency.
```
{
  "tables": [
    {
       "name":  "organization",
       "columns": [
          "name": "address",
          "type": "Accounts.PostalAddress"
       ]
    }
  ]
}
```

Another example, would be assigning an `enum` type to a column.   This may have to be treated specially due to how enums are handled in different database providers.   For example, postgresql has an `enum` column type.  For other databases, it may also require adding a conversion to `int` or `string` depending on what the column type is defined as.

```
{
  "tables": [
    {
       "name":  "organization",
       "columns": [
          "name": "status",
          "type": "Accounts.AccountStatus"
       ]
    }
  ]
}
```
Where `AccountStatus` is an enum type defined code-first in the `Accounts` namespace.

3) Renaming tables and/or columns
This feature is already available with the extension but isn't clear if it works with the the CLI.  If it isn't yet available for the CLI, I'd like to propose that it is included as part of the `efcpt-config.json` file and not an separate file like the VS extension requires.
```
{
  "tables": [
    {
       "name":  "tblOrganization",
       "new-name": "Organization"
       "columns": [
          "name": "postal_address",
          "new-name": "Address"
       ]
    }
  ]
}
```

There should also be an option for global renaming.  For example, say someone wanted to add `Entity` to the end of the file and class names.   This is sort of possible via the T4 scripts (it doesn't appear to do file renaming) but something this common and simple shouldn't have to resort to modifying the T4.

4) Excluding columns
Currently one is able to exclude tables but there doesn't appear to be a similar option to exclude a column.

```
{
  "tables": [
    {
       "name":  "organization",
       "columns": [
          "name": "internal_column",
          "exclude": true
       ]
    }
  ]
}
```

5) Separate DbContext implementations
In relation to the namespace option, some people will want to have a common DbContext and others will want to have a DbContext by namespace.  There should be an option to say how you want the DbContext's to be created.

**Comment by ErikEJ** [comment]
Very few features have not (yet) been implemented in the CLI edition. There are some hints [here](https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/RevEng.Shared/Cli/CliConfigMapper.cs#L84)

1: Not implemented (in VS or CLI), you can put files in folders based on the table schema name

2: Not implemented - but you could do it with T4 templates. Enum support is already in the supplied T4 templates.

3: Renaming is implemented in CLI. Same seperate file and format as in the VS extension. Global renaming can be done va regex renaming in the renaming.json file.

4: Excluding columns is a very comple topic, and not implemented in CLI for that exact reason.

5: You can generate a many DbContexts as you want as documented in the wiki.

**Comment by ErikEJ** [comment]
For 2 you could also add the type property in a partial class and do the mapping to and from the base column. I am not sure that mapping directly would work with EF Core queries.

**Comment by clintsinger** [comment]
While T4 is great for customization, it has the downside of being somewhat difficult to work with and the feature set isn't shared with others.    I think that these features would make sense to be baked into the base functionality for everyone to easily access.

I was confused by your response for 1.   You said it isn't implemented but then you said "you can put files in folders based on table schema name".  Do you have documentation or an example of what you mean?

**Comment by ErikEJ** [comment]
https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#file-layout lists the feature and it's config name

**Comment by ErikEJ** [comment]
>>  I think that these features would make sense to be baked into the base functionality for everyone to easily access.

Sure, but someone has to maintain these features.
