### ISSUE TITLE
Package load error about missing assembly Community.VisualStudio.Toolkit

### ISSUE THREAD

**Issue by eduarddejong** [ErikEJ/EFCorePowerTools#1990]
Hi, I after experiencing the same error on different systems, and both on my home computer as well as on my work laptop, my conclusion is that there must be a problem that needs attention.
A week ago I uninstalled and reinstalled the EF Core Tools package after several repeated errors.
That seemed to have temporarily fixed the issue, but today it happend again.

### Provide steps to reproduce a bug

Please include a **complete** description of the issue or link to a project that I can run to reproduce the issue.

I opened a new Visual Studio instance and choose to create a new console project.
Or I open a recent project.
This error appears. I click Yes everytime because I don't plan to disable this amazing package.

The message refers to a file called ActivityLog.xml created by Visual Studio in my user profile AppData directory:

The exception message (Sorry for the Dutch language, the error is that the file is not found, If you need things translated or clarified further, let me know):
```
SetSite failed for package [EFCorePowerToolsPackage]Source: 'EFCorePowerTools' Description: Kan bestand of assembly Community.VisualStudio.Toolkit, Version=17.0.507.0, Culture=neutral, PublicKeyToken=79441d341a79572c of een van de afhankelijkheden hiervan niet laden. Het systeem kan het opgegeven bestand niet vinden.
System.IO.FileNotFoundException: Kan bestand of assembly Community.VisualStudio.Toolkit, Version=17.0.507.0, Culture=neutral, PublicKeyToken=79441d341a79572c of een van de afhankelijkheden hiervan niet laden. Het systeem kan het opgegeven bestand niet vinden.
File name: 'Community.VisualStudio.Toolkit, Version=17.0.507.0, Culture=neutral, PublicKeyToken=79441d341a79572c'
   at EFCorePowerTools.EFCorePowerToolsPackage.<InitializeAsync>d__13.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at EFCorePowerTools.EFCorePowerToolsPackage.InitializeAsync(CancellationToken cancellationToken, IProgress`1 progress)
   at Microsoft.VisualStudio.Shell.AsyncPackage.<>c__DisplayClass21_0.<<Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)
   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)

WRSCH: registratie van assembly-bindingen is uitgeschakeld.
Als u assembly-bindingsfouten wilt registreren, stelt u de registerwaarde [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) in op 1.
Opmerking: er is een prestatiestraf gekoppeld aan de registratie van assembly-bindingsfouten.
Als u deze functie wilt uitschakelen, verwijdert u de registerwaarde [HKLM\Software\Microsoft\Fusion!EnableLog].`
```

And here a screenshot of the section in this XML file as shown by a web browser using markup:
![afbeelding](https://github.com/ErikEJ/EFCorePowerTools/assets/86660027/d85eb1e0-2562-4ef6-9ef9-40673468ab57)

### Provide technical details

- EF Core Power Tools version:
  2.5.1648

- Exact Visual Studio version:
  Microsoft Visual Studio Professional 2022 (64-bit) - Current
  Version 17.7.6

- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)
  We work with SQL Server here.

- EF Core version in use: (e.g. EF Core 7)
  The error happens in projects unrelated to EF Core. The error is generated by the package when opening totally unrelated projects.

- Is Handlebars templates used: no/yes
  Unrelated to the problem.

- Is T4 templates used: no/yes
  Unrelated to the problem.

- Is a SQL Server .dacpac used: no/yes
  Unrelated to the problem.

**Comment by ErikEJ** [comment]
I am unable to repro, sorry. try a re-install / VS repair. Are you able to use with another VS edition / machine?

**Comment by eduarddejong** [comment]
H, I both experienced it on my home machine as well as on my work machine. Both a week ago as well as today.

My home machine has Visual Studio Community installed.

My work machine has Visual Studio Professional.

Both use different user accounts as well, my work machine is in a domain too.

In order to try other Visual Studio versions, I would first have to install these.

Like past week, reinstalling the extension seemed to temporarily fix it for now, but I think it might come back.
Maybe I have some specific configuration that causes the problem, that's possible. But I am not a Visual Studio Extensions expert.

Does the EF Core Tools extension actually use Community.VisualStudio.Toolkit? Where can I find that file?
Maybe, when the error happens again, I can try to see if the file is still there on my system, then we can find out of something is actually removing it or that some other problem occurs.

**Comment by ErikEJ** [comment]
Yes, it uses the file, you can find all files belonging to an extension under <userprofile>\AppData\Local\Microsoft\VisualStudio

**Comment by ErikEJ** [comment]
@eduarddejong Could you pletase share the full ActivityLog.xml file instead of just a screen shot?
