### ISSUE TITLE
Schema suffix when UseSchemaNamespace is enabled

### ISSUE THREAD

**Issue by glasody** [ErikEJ/EFCorePowerTools#1991]
Hi there,

I've noticed that when using scaffolding with the `UseSchemaNamespaces` configuration enabled, it appends "Schema" after the schema name in the namespace.
This seems out of line as it does not align with what the `UseSchemaFolders` configuration is generating.
I assumed that because the folder name is generated with just the schema name, it would be the same for the entity namespace when schema namespaces is used.
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/9078067/d1554d01-9783-400d-a33e-20e4c4226a78)

It seems to be a hardcoded value suffix as seen here:
https://github.com/ErikEJ/EFCorePowerTools/blob/464b055fc2b5aeb0ba96677261e85cb848166fe8/src/GUI/RevEng.Core.60/ReverseEngineerScaffolder.cs#L393

Is there a way to customize this suffix or turn it off so it aligns with what the `UseSchemaFolders` feature does? I'm trying to scaffold tables from multiple schemas so setting the `ModelNamespace` instead of using `UseSchemaNamespaces` is out of the question.

I assume there is some reasoning behind the decision about appending the word "Schema" in the namespace generation.

Thank you

### Provide steps to reproduce a bug

Generate scaffold with `UseSchemaNamespaces` and `UseSchemaFolders` enabled.

### Provide technical details

- EF Core Power Tools version: 2.5.1648

- Exact Visual Studio version: Visual Studio 2022 17.7.6

- Database engine: SQL Server

- EF Core version in use: EF Core 7 (7.0.13)

- Is Handlebars templates used: no

- Is T4 templates used: yes

- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
Thanks for trying out this experimental feature - see the discussion [here](https://github.com/ErikEJ/EFCorePowerTools/pull/1829#issuecomment-1580761370)

**Comment by glasody** [comment]
@ErikEJ thanks for the explanation 😁

**Comment by maxisam** [comment]
But can we have the folder with suffix as well?
