### ISSUE TITLE
 EF Core Power Tools and Oracle

### ISSUE THREAD

**Issue by KaiWenF** [ErikEJ/EFCorePowerTools#1992]
This is not so much a bug as it is a question.  I cannot find and help nor any example on connect the  EF Core Power Tools to an Oracle database.  Can anyone please share some information on how this is done?

Thanks
Kai

**Comment by ErikEJ** [comment]
Please read the extensive guide in the wiki

**Comment by ErikEJ** [comment]
Wiki link: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#choose-data-source
