### ISSUE TITLE
Will ExcludedColumns be added to EF Core Power Tools CLI?

### ISSUE THREAD

**Issue by jinweijie** [ErikEJ/EFCorePowerTools#1993]
Hi @ErikEJ ,

Thanks for developing the Cli tool, it's great!

A quick question please, I have a jsonb column in Postgres and I would like to map it to JsonDocument type, however, currently since there's no option to specify the custom mapping, I was trying to skip the column and use a partial class to add that column. 

I found the option `ExcludedColumns` only exists in GUI tool but not in Cli yet. So just would like to know if there's a plan to add also to Cli? Or do you have any other suggestions to do this (jsonb column mapping for example)?

Thanks in advance!

**Comment by ErikEJ** [comment]
@jinweijie I do not have any plans to do this, as I cannot constrain the columns that can be excluded in the CLI as I can in the GUI. You can use T4 templates for this.
