### ISSUE TITLE
Reverse engineer for postgresql seems broken in .net8 RC2

### ISSUE THREAD

**Issue by bhadragol** [ErikEJ/EFCorePowerTools#1994]
Greetings!
I'm unable to use this tool to reverse engineer postgres database for the columns that have numeric(_,_) columns in the latest version of this extension. It was working pretty fine before last few updates. The poco models are generated successfully, but the numeric columns with decimal precision are skipped. There is no such issue in .net 7 project only with .net RC2 I'm using currently.

Under the extensions filter, these are the errors thrown:
```
Some issues were discovered during reverse engineering, consider addressing them:
Could not find type mapping for column 'public.lt_invoice.subtotal' with data type 'numeric(14,6)'. Skipping column.
Could not find type mapping for column 'public.lt_invoice.discount' with data type 'numeric(14,6)'. Skipping column.
Could not find type mapping for column 'public.lt_invoice.service_charge' with data type 'numeric(14,6)'. Skipping column.
Could not find type mapping for column 'public.lt_invoice.tax' with data type 'numeric(14,6)'. Skipping column.
Could not find type mapping for column 'public.lt_invoice.grand_total' with data type 'numeric(14,6)'. Skipping column.
Could not find type mapping for column 'public.lt_invoice.paid_amount' with data type 'numeric(14,6)'. Skipping column.
```

No exception thrown by the extension so that I could look for possible problem. Also if I alter the column for ex:  numeric(14,6) to just numeric, the extension generates poco class correctly (with decimal property).

### Provide steps to reproduce a bug
- Create a postgresql database
- Create a table with few columns and add columns: rate numeric(14,6), qty numeric(12,4),  total numeric(14,6)
- Create a .net 8 RC2 project 
- Try to reverse engineer to generate models and dbcontext from the database

I'm using postgres 16, the latest version as of raising this issue.

### Provide technical details
- EF Core Power Tools version: 5.5.1658, same in latest from visual studio extensions page 
- Exact Visual Studio version: Visual Studio 2022 17.8.0 Preview 6.0
- Database engine: Postgres 16 (PostgreSQL 16.0, compiled by Visual C++ build 1935, 64-bit)
- EF Core version in use: EF Core 8 RC2
- Is Handlebars templates used: no
- Is T4 templates used: no
- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
@roji Any thoughts?

**Comment by ErikEJ** [comment]
@bhadragol What happen if you use the built-in commands?

**Comment by bhadragol** [comment]
> @bhadragol What happen if you use the built-in commands?

Will you please elaborate on built-in commands? I have not used that yet!

**Comment by roji** [comment]
Will wait to hear - if the same errors are there via the EF cmdline tool, I'll definitely take a look.

**Comment by bhadragol** [comment]
@ErikEJ, @roji  
I tried to generate models the way instructed. Same problem in the .net scaffold as well. Here are the logs:

**Scaffold-DbContext "Server=127.0.0.1;Port=5433;Database=db_name;User Id=postgres;Password=admin;" Npgsql.EntityFrameworkCore.PostgreSQL -OutputDir Models**

```

The Entity Framework tools version '7.0.13' is older than that of the runtime '8.0.0-rc.2.23480.1'. Update the tools for the latest features and bug fixes. See https://aka.ms/AAc1fbw for more information.
To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
Could not find type mapping for column 'public.lt_subscription.current_product_qty' with data type 'numeric(12,4)'. Skipping column.
Could not find type mapping for column 'public.lt_invoice_settlement.grand_total' with data type 'numeric(16,6)'. Skipping column.
Could not find type mapping for column 'public.lt_invoice_settlement.charges' with data type 'numeric(16,6)'. Skipping column.
Could not find type mapping for column 'public.lt_invoice_settlement.grand_total_ex' with data type 'numeric(16,6)'. Skipping column.
Could not find type mapping for column 'public.lt_invoice_settlement.cash' with data type 'numeric(16,6)'. Skipping column.
Could not find type mapping for column 'public.lt_invoice_settlement.cheque' with data type 'numeric(16,6)'. Skipping column.
```

I could not sort-out the first warning message: 

> The Entity Framework tools version '7.0.13' is older than that of the runtime '8.0.0-rc.2.23480.1.

Project file is as follows. I tried using console application.
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.DotNet.Scaffolding.Shared" Version="8.0.0-rc.2.23509.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0-rc.2.23480.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="8.0.0-rc.2.23480.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Analyzers" Version="8.0.0-rc.2.23480.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.0-rc.2.23480.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.0-rc.2.23480.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.0-rc.2" />
  </ItemGroup>

</Project>
```


Thanks.

**Comment by ErikEJ** [comment]
@bhadragol This does not seems Power Tools specific, suggest you create an issue with a proper repro (table create script) in the EF Core repository)

**Comment by roji** [comment]
And FYI this has already been fixed (https://github.com/npgsql/efcore.pg/pull/2901)

**Comment by ErikEJ** [comment]
Great!

**Comment by bhadragol** [comment]
@ErikEJ , @roji 

Hello,
I looked at mentioned threads:

> FYI I can see this happening, have opened https://github.com/npgsql/efcore.pg/issues/2920 to track this and will look into it ASAP.
> And FYI this has already been fixed (https://github.com/npgsql/efcore.pg/pull/2901)


Unfortunately, I couldn't fix the problem in my end. The problem is still there. Here are the steps I did.
- Visual studio preview up to date
- .net8 RC2 up to date
- Reinstalled the efcore power tools extensions from vs marketplace
- updated the dotnet efcore tools to this one: dotnet-ef --version 8.0.0-rc.2.23480.1 [link](https://www.nuget.org/packages/dotnet-ef/8.0.0-rc.2.23480.1)
- restarted both visual studio and computer

Here is the simple database script: postgresql 16 
```
CREATE TABLE IF NOT EXISTS public.tbl_product
(
    id uuid NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    min_qty numeric(12,4) NOT NULL,
    sales_rate numeric(16,6) NOT NULL,
    created_on timestamp without time zone NOT NULL,
    CONSTRAINT tbl_product_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.tbl_product
    OWNER to postgres;
```

And the attempt to scafold:
**PM> Scaffold-DbContext "Server=127.0.0.1;Port=5433;Database=ef_db;User Id=postgres;Password=admin;" Npgsql.EntityFrameworkCore.PostgreSQL -OutputDir Models**
```
Build started...
Build succeeded.
To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
Could not find type mapping for column 'public.tbl_product.min_qty' with data type 'numeric(12,4)'. Skipping column.
Could not find type mapping for column 'public.tbl_product.sales_rate' with data type 'numeric(16,6)'. Skipping column.
```

Is there anything that I'm missing?
Should I have to create an issue in another repository? If so, where?

Thank you.

**Comment by roji** [comment]
https://github.com/npgsql/efcore.pg/pull/2901 (the PR that fixes this) was merged post-rc2. The actual release (in a couple weeks) will contain the fix.
