### ISSUE TITLE
Aliasing/Renaming in Table selection process and using DisplayName attribute on model

### ISSUE THREAD

**Issue by angus-grant** [ErikEJ/EFCorePowerTools#1995]
It would be great if the aliasing/renaming feature on the table selection form would pass this through to the DisplayName attribute for the model property.
At the moment it completely renames the model property.
Obviously spaces can't be used on model property names. :)

And you also have to clear the "Use table and column names directly from the database" checkbox
Would be good if that option could be ticked to preserve names from DB, but then also create properties DisplayName attributes

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/45915404/a68ebb58-ab51-45cd-9234-18b085412343)

Display name attribute in model (I manually created this after model generation)
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/45915404/a85e7021-8111-4a58-8d71-aeff44c47360)

Display name on web form.
This way you could decorate the model properties with human-readable content.
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/45915404/1424c254-b691-499c-a8ff-fee7d7cd03b6)

**Comment by ErikEJ** [comment]
I am not sure the scaffolding sets a DisplayName attribute??

Also  using the generated classes as your view model is not something I recommend.

**Comment by ErikEJ** [comment]
@angus-grant You could decorate with the description from your database, creating DisplayName is not something I plan to do
