### ISSUE TITLE
Stored procedure decimals

### ISSUE THREAD

**Issue by nikriaz** [ErikEJ/EFCorePowerTools#1998]
I've seen this question in closed issues. Sorry for asking again but I'm struggling to understand what I have to do to get rid of warning:

`|WARN|Microsoft.EntityFrameworkCore.Model.Validation|No store type was specified for the decimal property 'TotalSum' on entity type 'CalculateYearlyPaidResult'. This will cause values to be silently truncated if they do not fit in the default precision and scale. Explicitly specify the SQL server column type that can accommodate all the values in 'OnModelCreating' using 'HasColumnType', specify precision and scale using 'HasPrecision', or configure a value converter using 'HasConversion'. `

I tried to add `modelBuilder.Entity<CalculateYearlyPaidResult>().Property(p => p.TotalSum).HasPrecision(10, 2);` to `protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)` It works but washing out on every Reverse Engineering run.

I also tried to enable "Data Annotations" in options as previous discussions somehow referred to it. Data Annotations enabled but not for  my POCO stored procedure scaffolded class:

```
    public partial class CalculateYearlyPaidResult
    {
        public decimal? TotalSum { get; set; }
    }
```
This final lines of my sp:

```
    -- Calculate total sum
    DECLARE @TotalSum DECIMAL(10,2) = @DirectSum + @IndirectSum;

    -- Return the total sum
    SELECT @TotalSum AS TotalSum;
```
What else should I do? 

Thank you for your great tool and your efforts!

**Comment by nikriaz** [comment]
Okay, added the following into separate file and it seems it works. Is it correct and expected?

```
    partial void OnModelCreatingPartial(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<CalculateYearlyPaidResult>(entity =>
        {
            entity.Property(e => e.TotalSum).HasColumnType("decimal(10, 2)");
        });
    }
```

**Comment by ErikEJ** [comment]
Looking at #1828 it looks like I should make the dataannotation an option, and off by default.

**Comment by ErikEJ** [comment]
@nikriaz This seems to be related as well: https://github.com/dotnet/efcore/issues/27438

**Comment by nikriaz** [comment]
Yes, it seems it is related.

For the data annotations, if you talk about this settings, it is off but if I enable it, data annotations are created for normal model classes but not for scaffolded class which belongs to the stored procedure (example above)

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/52108512/e4ad0c56-b862-4a27-bf02-0443d1ff4967)

**Comment by ErikEJ** [comment]
No, I am referring to the special casing of adding data annotations to the stored procedure result set class.[

**Comment by ErikEJ** [comment]
I will make the data annotation of decimal default to be enabled, and add an option to turn it off to support #1828

**Comment by ErikEJ** [comment]
Bring back https://github.com/ErikEJ/EFCorePowerTools/commit/d8535ab926f4aabb3407cf5ef38da16619819ade but make it optional and on by default

**Comment by ErikEJ** [comment]
Original issue is #1784

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
