### ISSUE TITLE
SQL Server triggers in EF Core 7

### ISSUE THREAD

**Issue by fmelink** [ErikEJ/EFCorePowerTools#1999]
Hi, great tool! Unfortunately we can't migrate to EF7 because the tool does not implement the workaround for a breaking change. See "[SQL Server tables with triggers or certain computed columns now require special EF Core configuration](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/breaking-changes?tabs=v7#sqlserver-tables-with-triggers)" for more information.

### Steps to reproduce
1. Create a table with a trigger in SQL Server.
1. Use EF Core Power Tools to reverse-engineer it.
1. Inspect the generated code.

#### Expected result
The generated code marks the table as having a trigger.

#### Actual result
The generated code doesn't have the table marked.

### Technical details

- EF Core Power Tools version: 2.5.1648

- Exact Visual Studio version: Visual Studio 2022 17.6.2

- Database engine: SQL Server 15.0.2104 Express

- EF Core version in use: EF Core 7

- Is Handlebars templates used: no

- Is T4 templates used: no

- Is a SQL Server .dacpac used: no

**Comment by fmelink** [comment]
My bad, I'm just an idiot! The tool does add HasTrigger.

**Comment by ErikEJ** [comment]
Assume duplicate of #1997
