### ISSUE TITLE
Possibility to introduce templating for on-model-creating method

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#20]
_From @mbharodia on April 12, 2018 13:46_

Here is handle bar template for DbContext

_{{> dbimports}}
namespace {{namespace}}
{
public partial class {{class}} : DbContext
    {
        {{> dbsets}}
        {{#if entity-type-errors}}
        {{#each entity-type-errors}}
        {{spaces 8}}{{{entity-type-error}}}
        {{/each}}
        {{/if}}
{{{on-configuring}}}
{{{on-model-creating}}}    
    }   
}_

on-model-creating injects 

` protected override void OnModelCreating(ModelBuilder modelBuilder)`

I like to do the following

`protected override void OnModelCreating(ModelBuilder modelBuilder)`
`{`

      `//code generated by the tool goes here//`

      `//my own code that I could add using template//`
      `OnModelCreatingPartial(modelBuilder);`
`}`

The way template has been designed right now, I am not able to inject the following (or I may not know)

` OnModelCreatingPartial(modelBuilder)`

Here is my updated template to introduce partial method

_{{> dbimports}}
namespace {{namespace}}
{
public partial class {{class}} : DbContext
    {
        {{> dbsets}}
        {{#if entity-type-errors}}
        {{#each entity-type-errors}}
        {{spaces 8}}{{{entity-type-error}}}
        {{/each}}
        {{/if}}
{{{on-configuring}}}
{{{on-model-creating}}}    
partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }   
}_

As DbContext is partial class already, I can have another partial class and add required code as per my requirements. I think this provides me an easier way to extend the functionality using PARTIAL setup.

I think the above is already available in EF6 POCO Generated and it has been useful to me in many instances. I am just wondering whether there is any possibility of doing the same thing.

I highly appreciate your recommendation or feedback or any help in this regard

_Copied from original issue: ErikEJ/SqlCeToolbox#695_

**Comment by ErikEJ** [comment]
PRs are very welcome - does this work for you as desired?

**Comment by ErikEJ** [comment]
Looks like it is related to https://github.com/ErikEJ/SqlCeToolbox/issues/683

**Comment by ErikEJ** [comment]
_From @mbharodia on April 12, 2018 15:26_

Hi Eric:

The tool you have developed is really useful.

Earlier I used POCO generator for EF 6 and I had an opportunity to extend the context class using partial methods. I have come across many occasions, when I needed to extend the partial context class generated by the tool due to the legacy databases were not designed to support domain driven development; for example, missing Primary Key and Foreign Key did not enable the tool to generate required relationships between parent and child objects.

This can be easily fixed if there is an opportunity to extend this context class by manually writing some code using fluent APIs.

Thanks, and have a good day!


Regards,
Mayur

**Comment by ErikEJ** [comment]
I will try to simply always add the two extra lines:

       OnModelCreatingPartial(modelBuilder);
        
and
      
      partial void OnModelCreatingPartial(ModelBuilder modelBuilder);

**Comment by ErikEJ** [comment]
_From @mbharodia on April 15, 2018 20:15_

Okay. Thanks a lot for your help!

**Comment by ErikEJ** [comment]
@mbharodia Fixed in latest daily build (no Handlebars required)

**Comment by ErikEJ** [comment]
_From @mbharodia on April 28, 2018 13:12_

Thank you so much Erik!

**Comment by ErikEJ** [comment]
Please let me know if it solves your issue!

**Comment by ErikEJ** [comment]
_From @mbharodia on April 30, 2018 17:54_

Hi Erik: 

It looks like that it is not working as per the expectation. When I got the latest daily build, it generated the following code.

```
namespace CCData.DataContext
{
    public partial class CustomCareDataContext : DbContext
    {
        public virtual DbSet<Account> Accounts { get; set; }       

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Account>(entity =>
            {
                entity.ToTable("accounts");

                entity.Property(e => e.AccountId).HasColumnName("account_id");

                entity.Property(e => e.AccountIsVerified)
                    .IsRequired()
                    .HasColumnName("account_is_verified")
                    .HasMaxLength(3)
                    .IsUnicode(false)
                    .HasDefaultValueSql("('NRQ')");

                entity.Property(e => e.AccountOpeningBalance)
                    .HasColumnName("account_opening_balance")
                    .HasColumnType("numeric(8, 2)");

                entity.Property(e => e.AccountOpeningDate)
                    .HasColumnName("account_opening_date")
                    .HasColumnType("datetime");

                entity.Property(e => e.AccountStatus)
                    .IsRequired()
                    .HasColumnName("account_status")
                    .HasMaxLength(3)
                    .IsUnicode(false)
                    .HasDefaultValueSql("('ACT')");

                entity.Property(e => e.CompanyId).HasColumnName("company_id");

                entity.HasOne(d => d.Company)
                    .WithMany(p => p.Accounts)
                    .HasForeignKey(d => d.CompanyId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_accounts_companies");
            });
            
        }

    }
            OnModelCreatingPartial(modelBuilder);
}
```
I think that the correct code should be like the following. Please pay attention to "OnModelCreatingPartial" at two different places below.

```
namespace CCData.DataContext
{
    public partial class CustomCareDataContext : DbContext
    {
        public virtual DbSet<Account> Accounts { get; set; }
       

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Account>(entity =>
            {
                entity.ToTable("accounts");

                entity.Property(e => e.AccountId).HasColumnName("account_id");

                entity.Property(e => e.AccountIsVerified)
                    .IsRequired()
                    .HasColumnName("account_is_verified")
                    .HasMaxLength(3)
                    .IsUnicode(false)
                    .HasDefaultValueSql("('NRQ')");

                entity.Property(e => e.AccountOpeningBalance)
                    .HasColumnName("account_opening_balance")
                    .HasColumnType("numeric(8, 2)");

                entity.Property(e => e.AccountOpeningDate)
                    .HasColumnName("account_opening_date")
                    .HasColumnType("datetime");

                entity.Property(e => e.AccountStatus)
                    .IsRequired()
                    .HasColumnName("account_status")
                    .HasMaxLength(3)
                    .IsUnicode(false)
                    .HasDefaultValueSql("('ACT')");

                entity.Property(e => e.CompanyId).HasColumnName("company_id");

                entity.HasOne(d => d.Company)
                    .WithMany(p => p.Accounts)
                    .HasForeignKey(d => d.CompanyId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_accounts_companies");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);

    }
            
}
```
Additionally, handlebar setup stopped working. I know that you have mentioned that this build is for "no handlebar" support. I guess it is still good to have handlebar to do some customization if needed.

The above explanation may not make sense if I have missed anything that you wanted me to look into before running the templates for your latest daily build. Please let me know your feedback.

**Comment by ErikEJ** [comment]
Hmmm... Tried a diferent approach in the latest build

**Comment by ErikEJ** [comment]
@mbharodia I have attempted a fix in the latest daily build, would be grateful if you could try it out

**Comment by mbharodia** [comment]
Hi Erick. That worked well! Thank you. 

I am not sure whether it is a lot to ask further, however, is it possible to do the same with POCO classes?

```
 public partial class Audit
    {
        public Audit()
        {
            **OnModelCreatingPartial();**
        }
        public int AuditId { get; set; }
        public string AuditEntityType { get; set; }
        public string AuditEntityJson { get; set; }
        public DateTime AuditCreateDate { get; set; }
        public string AuditCreatedBy { get; set; }

        **partial void OnModelCreatingPartial();**
    }
```
Additionally, I don't see handle bar support. Earlier it was easier for me to add extra Using statements to classes generated. 

I create POCO classes and DbContext in a separate project and Using Statement is needed in DbContext so that it can reference the project with POCO classes. I am wondering whether handle bar support is going be supported or not.

However, I really appreciate your help with the above.

**Comment by ErikEJ** [comment]
@mbharodia The poco classes are already partial, and OnMoldeCreating does not make any sense here.

The Handlebars feature is temporarily disabled, see #12

**Comment by ErikEJ** [comment]
@mbharodia Handlebars are back in latest daily build
