### ISSUE TITLE
Why was SqlQueryValueAsync method removed when upgraded from version 6 to 7?

### ISSUE THREAD

**Issue by ricfwolff** [ErikEJ/EFCorePowerTools#2000]
Hello, Erik!

Talking about the **SqlServer.SqlQuery** feature, why was **SqlQueryValueAsync** method removed when you upgraded from version 6 to 7? I was going to upgrade my project and noticed that it is missing.
What's the proposed substitute?

### technical details:

- EF Core Power Tools version: 7

- Exact Visual Studio version: N/A

- Database engine: SQL Server

- EF Core version in use: EF Core 7

- Is Handlebars templates used: no

- Is T4 templates used: no

- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
Are you referring to the NuGet package??

**Comment by ricfwolff** [comment]
Yes.
This method here:
https://github.com/ErikEJ/EFCorePowerTools/blob/3053d8f81cf76e3d3387f61d26e31e8c9609b9ac/src/GUI/ErikEJ.EntityFrameworkCore.6.SqlServer.SqlQuery/DbContextExtensions.cs#L39

Does not exist in v7:
https://github.com/ErikEJ/EFCorePowerTools/blob/3053d8f81cf76e3d3387f61d26e31e8c9609b9ac/src/GUI/ErikEJ.EntityFrameworkCore.7.SqlServer.SqlQuery/DbContextExtensions.cs

**Comment by ErikEJ** [comment]
@ricfwolff It is not part of the product (in EF Core 7): https://www.learnentityframeworkcore.com/raw-sql/sql-query
