### ISSUE TITLE
ORA-01795 when trying to reverse engineer more than 1000 tables

### ISSUE THREAD

**Issue by akeck** [ErikEJ/EFCorePowerTools#2001]
When trying to reverse engineer more than 1000 tables from an Oracle database, EFCorePowerTools fail with oracle error ORA-01795.

That's what I found:

> ORA-01795: maximum number of expressions in a list is 1000.
> 
> Issue: When user selects long list of values (greate or qual to 1000 values/expression) for IN/OR list of where clause, system throws error: “ORA-01795: maximum number of expressions in a list is 1000”
> 
> Root Cause: Oracle IN / OR list has limit of 1000 (actually its 999) number of expression/value list.
> 
> Proposed Solution: You need to split the list of expressions into multiple sets (using OR) and each should be less than 1000 list/expressoin combine using IN / Or list.

Would it be possible to add this? :)

Error:

> Oracle.ManagedDataAccess.Client.OracleException (0x80004005): ORA-01795: maximum number of expressions in a list is 1000
>    at OracleInternal.ServiceObjects.OracleConnectionImpl.VerifyExecution(Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, SqlStatementType sqlStatementType, Int32 arrayBindCount, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
>    at OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteReader(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, OracleDataReaderImpl& rdrImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[] scnForExecution, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, Int64& internalInitialLOBFS, Int64 internalInitialJSONFS, OracleException& exceptionForArrayBindDML, OracleConnection connection, IEnumerable`1 adrianParsedStmt, Boolean isDescribeOnly, Boolean isFromEF)
>    at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteReader(Boolean requery, Boolean fillRequest, CommandBehavior behavior)
>    at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
>    at Oracle.EntityFrameworkCore.Scaffolding.Internal.OracleDatabaseModelFactory.GetTablesCombined(DbConnection connection, Func`3 tableFilter, DatabaseModel databaseModel, Func`2 schemaFilter, List`1 paramList)
>    at Oracle.EntityFrameworkCore.Scaffolding.Internal.OracleDatabaseModelFactory.Create(DbConnection connection, IEnumerable`1 tables, IEnumerable`1 schemas)
>    at Oracle.EntityFrameworkCore.Scaffolding.Internal.OracleDatabaseModelFactory.Create(DbConnection connection, DatabaseModelFactoryOptions options)
>    at Oracle.EntityFrameworkCore.Scaffolding.Internal.OracleDatabaseModelFactory.Create(String connectionString, DatabaseModelFactoryOptions options)
>    at RevEng.Core.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions, Boolean removeNullableBoolDefaults, Boolean excludeNavigations, Boolean dbContextOnly, Boolean entitiesOnly, Boolean useSchemaFolders, Boolean useSchemaNamespaces) in C:\Code\Github\EFCorePowerTools\src\GUI\RevEng.Core.60\ReverseEngineerScaffolder.cs:line 458
>    at RevEng.Core.ReverseEngineerScaffolder.GenerateDbContext(ReverseEngineerCommandOptions options, List`1 schemas, String outputContextDir, String modelNamespace, String contextNamespace, String projectPath, String outputPath) in C:\Code\Github\EFCorePowerTools\src\GUI\RevEng.Core.60\ReverseEngineerScaffolder.cs:line 94
>    at RevEng.Core.ReverseEngineerRunner.GenerateFiles(ReverseEngineerCommandOptions options) in C:\Code\Github\EFCorePowerTools\src\GUI\RevEng.Core.60\ReverseEngineerRunner.cs:line 78
> 
> 

best regards
Alexander

**Comment by ErikEJ** [comment]
You should not include 1000 tables in a DbContext!

Do you see the list of tables, then exclude some.

Anyway, it sounds like something that must be fixed in the Oracle provider

@akeck

**Comment by ErikEJ** [comment]
Ping?

**Comment by akeck** [comment]
sorry for the late answer...
it's not a bug in the Oracle provider. It's a hard limit of the server itself. You also cannot e.g. use more than 1000 items in a WHERE IN clause. The provider can't do anything about it. One just have to split the query into 999 row chunks. The limit is actually 999 although the error message says 1000... Oracle...
And yes, you should not include 1000+ tables in a DbContext, but it's only a subset of the SAP database we need in our applications.
By the way, a range select possibility (click first, shift click last) would be of GREAT help sometimes :)

**Comment by ErikEJ** [comment]
Let me put it another way; my code does not create any queries, I use an EF Core api to get the table list. This api is implemented by the provider writer, in this case Oracle. @alexkeh - so you need to address this with Oracle support.
