### ISSUE TITLE
InvalidOperationException with serialization with EF Power Tools

### ISSUE THREAD

**Issue by wsyeager** [ErikEJ/EFCorePowerTools#2006]
### I'm getting the following error in the below code block with the **Stars or boldfaced**
public static class DbContextExtensions
{
    public static async Task<List<T>> SqlQueryAsync<T>(this DbContext db, string sql, object[] parameters = null, CancellationToken cancellationToken = default) where T : class
    {
        if (parameters is null)
        {
            parameters = new object[] { };
        }

        if (typeof(T).GetProperties().Any())
        {
            **return await db.Set<T>().FromSqlRaw(sql, parameters).ToListAsync(cancellationToken);**
        }
        else
        {
            await db.Database.ExecuteSqlRawAsync(sql, parameters, cancellationToken);
            return default;
        }
    }
}

System.InvalidOperationException: The type 'System.Threading.ExecutionContext&' of property 'Context' on type 'System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[System.Collections.Generic.List`1[SpiritWMSApiCore2.Models.Unitech_ASNInfo_BOLResult],SpiritWMSApiCore2.Models.SIRISContextProcedures+<Unitech_ASNInfo_BOLAsync>d__56]' is invalid for serialization or deserialization because it is a pointer type, is a ref struct, or contains generic parameters that have not been replaced by specific types.

### While searching for a resolution, I found the following, but still do not know how to resolve the error:
The error message you're seeing, `System.InvalidOperationException: The type 'System.Threading.ExecutionContext&' of property 'Context' on type 'System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[System.Collections.Generic.List`1[SpiritWMSApiCore2.Models.Unitech_ASNInfo_BOLResult],SpiritWMSApiCore2.Models.SIRISContextProcedures+<Unitech_ASNInfo_BOLAsync>d__56]' is invalid for serialization or deserialization because it is a pointer type, is a ref struct, or contains generic parameters that have not been replaced by specific types.`, is a .NET error that typically occurs when you're trying to serialize or deserialize a type that is not supported.

In your case, the type `System.Threading.ExecutionContext&` is causing the issue because it's a pointer type, a ref struct, or contains generic parameters that have not been replaced by specific types.

Here are a few potential solutions:

1. **Avoid serializing unsupported types**: If possible, avoid serializing types that are not supported. This includes pointer types, ref structs, and types with generic parameters that have not been replaced by specific types.

2. **Replace generic parameters with specific types**: If your type contains generic parameters, replace them with specific types before serialization.

3. **Use a custom serializer**: If the built-in .NET serializers do not meet your needs, consider using a custom serializer that can handle more complex types.

Remember to always test your changes in a safe and controlled environment before deploying them to production. If you're still having trouble, consider reaching out to the .NET community or Microsoft for further assistance.

**Comment by ErikEJ** [comment]
I need a full repro... runnable stored procedure definition

**Comment by wsyeager** [comment]
Here you go Erik. Thanks so much for checking into this... I've attached the below zip file.

[InvalidOp_Error.zip](https://github.com/ErikEJ/EFCorePowerTools/files/13383199/InvalidOp_Error.zip)

**Comment by wsyeager** [comment]
Forgot to include the SPROC definition:
public partial interface ISIRISContextProcedures
{
xxxx
Task<List<Unitech_ASNInfo_BOLResult>> Unitech_ASNInfo_BOLAsync(string SiteId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
)


### Creating the SPROC: **Stars** or boldfaced below
public partial class SIRISContext
{
    private ISIRISContextProcedures _procedures;

    public virtual ISIRISContextProcedures Procedures
    {
        get
        {
            if (_procedures is null) _procedures = new SIRISContextProcedures();
            return _procedures;
        }
        set
        {
            _procedures = value;
        }
    }

    public ISIRISContextProcedures GetProcedures()
    {
        return Procedures;
    }

    protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<BOL_Id_CreateResult>().HasNoKey().ToView(null);
        modelBuilder.Entity<Can_DeleteResult>().HasNoKey().ToView(null);
        modelBuilder.Entity<CreateBOLManualResult>().HasNoKey().ToView(null);
        modelBuilder.Entity<GetNumberOfParsResult>().HasNoKey().ToView(null);
        modelBuilder.Entity<Load3PLCartonScans_UnitechResult>().HasNoKey().ToView(null);
        modelBuilder.Entity<PalletInfoResult>().HasNoKey().ToView(null);
        modelBuilder.Entity<ShippingBOL_SaveResult>().HasNoKey().ToView(null);
        **modelBuilder.Entity<Unitech_ASNInfo_BOLResult>().HasNoKey().ToView(null);**
        modelBuilder.Entity<Unitech_InventoryDataResult>().HasNoKey().ToView(null);
        modelBuilder.Entity<Unitech_PalletInventoryResult>().HasNoKey().ToView(null);
        modelBuilder.Entity<Unitech_ValidateBolDataResult>().HasNoKey().ToView(null);
        modelBuilder.Entity<Unitech_ValidateInboundDataResult>().HasNoKey().ToView(null);
    }
}

**Comment by ErikEJ** [comment]
Are you using await properly? See the sample of usage in the wiki!

**Comment by wsyeager** [comment]
Yes... thx
I overlooked the original code there by not having an awaitable:
`var inboundAsn = **await** db.Unitech_ASNInfo_BOLAsync(SiteID);`
