### ISSUE TITLE
DbContextSplitter Configuration File when multiple schema contains same table names.

### ISSUE THREAD

**Issue by Aamirkhan10218** [ErikEJ/EFCorePowerTools#2008]
The Problem is that i am using DbContextSplit option from advance screen and it is accurately generating configuration files in my mentioned assembly but actually issue is that i have db with more than 50 schemas and most of them are contains same table name like Store.Prouct and Book.Product . the config files are not generating wrt to schema. please help how to fix.

**Comment by ErikEJ** [comment]
Have you read the wiki??
