### ISSUE TITLE
Return type of <List> does not does not translate properly in calling method with EF Power Tools

### ISSUE THREAD

**Issue by wsyeager** [ErikEJ/EFCorePowerTools#2009]
### The following method inside the Procedures.cs class returns a type of <List>
`public virtual async Task<List<GetNumberOfParsResult>> GetNumberOfParsAsync(string bol, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
{
    var parameterreturnValue = new SqlParameter
    {
        ParameterName = "returnValue",
        Direction = System.Data.ParameterDirection.Output,
        SqlDbType = System.Data.SqlDbType.Int,
    };

    var sqlParameters = new []
    {
        new SqlParameter
        {
            ParameterName = "bol",
            Size = 20,
            Value = bol ?? Convert.DBNull,
            SqlDbType = System.Data.SqlDbType.VarChar,
        },
        parameterreturnValue,
    };
    var _ = await _context.SqlQueryAsync<GetNumberOfParsResult>("EXEC @returnValue = [3PL].[GetNumberOfPars] @bol", sqlParameters, cancellationToken);

    returnValue?.SetValue(parameterreturnValue.Value);

    return _;
}`

### Here is the calling method:
`[HttpGet]
[Route("OutboundOrder/GetOrderByBol/BOL")]
[ProducesResponseType(StatusCodes.Status200OK, Type = typeof(BOLInput))]
public async Task<IActionResult> GetOrderByBolAsync(string Bol)
{
    OutboundOrder? oo = await db.OutboundOrders.Where(o => o.Bol == Bol).FirstOrDefaultAsync();
    if (oo == null)
    {
        return NotFound();
    }
    var pars = db.GetNumberOfParsAsync(Bol).**FirstOrDefault**();
}`

There is no 'FirstOrDefault' method here which there supposed to be since it's returning a <List>
See the attached file which shows the only methods to choose from:
[List_Options.docx](https://github.com/ErikEJ/EFCorePowerTools/files/13385340/List_Options.docx)

### Here is the model class for 'GetNumberOfParsResult' in the top code block
`namespace SpiritWMSApiCore2.Models
{
    public partial class GetNumberOfParsResult
    {
        public string bol { get; set; }
        [Column("n_pars", TypeName = "decimal(18,0)")]
        public decimal? n_pars { get; set; }
    }`

**Comment by ErikEJ** [comment]
You must use await!!
