### ISSUE TITLE
Managing connection profiles under the "Choose Database Connection" dialog

### ISSUE THREAD

**Issue by LaurenceFrost** [ErikEJ/EFCorePowerTools#201]
From the following location:

EF Core Power Tools -> Reverse Engineer

I am prompted with a "Choose Database Connection" dialog. Is there a way to remove entries from the dropdown box? Currently it lists lots of databases which I have previously reverse engineered, and I'd like to remove some.

Thanks.

**Comment by ErikEJ** [comment]
Yes, you can open "Server Explorer" and remove them from there.

**Comment by ErikEJ** [comment]
A button to remove the selected connection has been added to the latest daily build.
