### ISSUE TITLE
Supporting EF3 

### ISSUE THREAD

**Issue by scottManning42** [ErikEJ/EFCorePowerTools#2011]
We have a project that needs to support .NET standard 2.0 and EF 3 code.  Is there a way to get an older version of the EF Core Power tools that will generate EF3 code?  Or is there a way to generate EF 3 code with the current Power Tool release?  I was using an older version of the EFCorePowerTools, but recently updated the tool and saw that it only generates EF6 and EF7 code.  If it is not possible to get an older version of the extension or have the current extension generate EF3 code, do you know of another extension that will reverse engineer a database and generate EF3 code?

**Comment by ErikEJ** [comment]
There is an older unsupported version of the tool that works with EF Core 3 in the tools folder in this repo.

But you should really move forward!

**Comment by scottManning42** [comment]
Thanks for the details.  I do have a quick question.  We have a .NET standard 2.X library that is using EF 3.X.  The library is used by two very large projects.  One project is .NET Framework 4.8 and the other is .NET 6.  From my understanding, only Standard 2.X is supported by both .NET 6 and Framework 4.8.  Any version of EF higher than 3 is not supported in .NET standard 2.X.  I have tried to move my .NET standard 2 library to EF 6, but I get the error that EF6 is not compatible.  Sadly, the .NET framework project is way too large to support a re-write.  Do you know if there is any other way to work with EF6 or higher in a .NET standard 2 library?

**Comment by ErikEJ** [comment]
@scottManning42 If you must support both .NET Framework and .NET 6/8 you must stay on EF core 3.1 and use .NET Standard 2.0.

**Comment by scottManning42** [comment]
Thanks.  That is what I am reading.  I wish Microsoft would have allowed EF core 6 or higher in .NET standard or have Framework support .NET 6

**Comment by ErikEJ** [comment]
@scottManning42 That would have hindered the rapid evolution of .NET 8, 9 etc. You need to investigate how to move away from .NET Framework. Feel free to reach out for advice on how to do this.
