### ISSUE TITLE
Situation where entities are generated with postfixes like "1" to handle duplicates

### ISSUE THREAD

**Issue by Aamirkhan10218** [ErikEJ/EFCorePowerTools#2012]
### Provide steps to reproduce a bug
A Database that contains multiple schema with same name. 
Here is the brief description about the fault. EF Core power tool -Reverse Engineering adding postfix of 1 when different schema has same table name. Screenshots are also provided please have a look.
 

### Provide technical details

- EF Core Power Tools version: 2.5.1678

- Exact Visual Studio version: Visual Studio 2022 Version 17.9.0 Preview 1.0

- Database engine: SQL Server

- EF Core version in use: EF Core 7

**Comment by ErikEJ** [comment]
Since you are not providing any repro details I am going to close this
