### ISSUE TITLE
Reverse Engineering adding Postfix  "1" when multiple schema has same table name.

### ISSUE THREAD

**Issue by Aamirkhan10218** [ErikEJ/EFCorePowerTools#2013]
Provide steps to reproduce a bug
A Database that contains multiple schema with same name.
Here is the brief description about the fault. EF Core power tool -Reverse Engineering adding postfix of 1 when different schema has same table name. Screenshots are also provided please have a look.

Steps To Reproduce:-
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/38729443/67dfd43c-0c04-4962-95b4-4db4a5b445df)

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/38729443/35b0459b-f70e-480f-86c1-3e1b879b3581)

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/38729443/48ef4848-4aa8-4053-89a9-7225275c0952)

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/38729443/9fa6821e-0600-4ff2-bf0d-b615789209f5)

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/38729443/efb4c762-dc02-4e80-8f83-f53efa656497)

Output:-

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/38729443/90a3a8f0-64c8-41a6-8416-f7de5e4e3a6b)

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/38729443/17e15f42-2188-41ac-ad20-bbd1b8c91c2a)

Provide technical details
EF Core Power Tools version: 2.5.1678

Exact Visual Studio version: Visual Studio 2022 Version 17.9.0 Preview 1.0

Database engine: SQL Server

EF Core version in use: EF Core 7

**Comment by ErikEJ** [comment]
Sharing screen shots is not a repro, I need a runnable repro with SQL scripts and your efpt.config.json file

**Comment by Aamirkhan10218** [comment]
i am not able to share my DB script and efpt.config.json .
Can you please use these screenshots for reference and try to reproduce the fault. It is very urgent for us because we totally depend on you extension.

**Comment by ErikEJ** [comment]
If it is urgent you can sponsor me for a year a get a online consultation. I am not able to help you offline without scripts.
