### ISSUE TITLE
Adding more useful/programmatic Handlebars helpers

### ISSUE THREAD

**Issue by tlechnerMII** [ErikEJ/EFCorePowerTools#2015]
I notice that there is a severe lack of functionality for basic logic when using handlebars.  There is documentation for how to add our own helpers, but my understanding is that we cannot use the EFCorePowerTools extension as is, but need to use the commandline.  Since I'm using a .dacpac to scaffold my project, this would seem less than ideal, because I'm not finding good examples, and I'm generally happy to use the existing logic of the extension with its UI support.

I was wondering if we could add some helpful logical helpers to the EFCorePowerTools extension, such as "eq" which could be used in conditional statements like:

{{#if (eq property-annotation '[Key]')}}some output{{/if}}

I'm trying to do some logic that is dependent upon the primary key property (namely for an entity to implement an interface IEntity<T> where T is the type of the primary key).

Perhaps a small library of simple programmatic helpers would be sufficient to let most developers write more flexible templates?

Another option might be to allow the EFCorePowerTools extension to load a dll from another project at runtime which has the customized helper logic we might want to incorporate.  However, this sounds like it could be a more complicated solution instead of my first suggestion.

**Comment by ErikEJ** [comment]
I don't plan to do additional work to improve Handkebars support, but will work on the T4 experience instead.

**Comment by ErikEJ** [comment]
@tlechnerMII There is currently no way to invoke Handlebars helpers, and as mentioned above, I have no plans to change that. Have a look at the T4 issue here for ideas.

T4 code is actually invoked by my tooling, allowing you to do any kind of customization. 

May I ask why you need Handlebars in the first place?

**Comment by tlechnerMII** [comment]
My first post explained an example of what I was hoping to achieve. I wanted to identify the property that was the primary key, and use the property type in an interface IEntity&lt;T&gt;, where T corresponded to the ID's type. To do this, I need to trigger something to happen when the property-annotation has a value of '[Key]'.  This is currently not possible.

My suggestion is to add an 'equals' helper or 'eq' or something of that effect such that I could template something like:

`public partial class {{class}} : IEntity{{#each property}}{{#each property-annotations}}{{#if (eq property-annotation '[Key]')}}<{{{property-type}}}>{{/if}}{{/each}}{{/each}}`

Currently '#if' only allows you to reference template variables that are booleans.  This is extremely limiting, as it means we can only do logic on boolean variables that are being captured by the engine.

My offer is not for me to write my own code to be called dynamically by EF Core Power Tools. Rather, if I performed the work for you to build a helper such as 'eq' (perhaps more if it might make sense) into EF Core Power Tools (wrote the helpers and registered them as part of _this_ repository), would you consider my work and incorporate it (provided I address any concerns you have via a code-review process)?

I know I am unfamiliar with your work, but in my attempt to understand what's going on it looks like we could interject new helpers within ServiceProviderBuilder.cs:

```
#if !CORE80
            if (options.UseHandleBars)
            {
                serviceCollection.AddHandlebarsScaffolding(hbOptions =>
                {
                    hbOptions.ReverseEngineerOptions = ReverseEngineerOptions.DbContextAndEntities;
                    hbOptions.LanguageOptions = (LanguageOptions)options.SelectedHandlebarsLanguage;
                });
                serviceCollection.AddSingleton<ITemplateFileService>(provider
                    => new CustomTemplateFileService(options.OptionsPath));

                // ----------------------------------------------------------------------------------
                // Added example code of how to extend handlebars to include new helpers.
                // ----------------------------------------------------------------------------------
                serviceCollection.AddHandlebarsHelpers(("my-helper", (writer, context, parameters) =>
                    writer.Write($"// My Handlebars Helper: {context["class"]}")
));
            }
#endif
```

If this doesn't sound like the right thing to do, maybe I can work with the [EntityFrameworkCore.Scaffolding.Handlebars](https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars) project to natively support a more robust command set and then the community could benefit from these changes whether they use EF Core Power Tools or not.

**Comment by ErikEJ** [comment]
@tlechnerMII as I wrote, I do not plan to enhance Handlebars support (and maintain it going firward). Feel free to help improve the base library...

**Comment by tlechnerMII** [comment]
I realize I didn't answer your question about Handlebars ... We were also targetting EF Core 6, and not 7; I don't think EF Core 7 supports T4. I will have to see if we can move to EF Core 7, it may be an option.

For users of EF Core 6 though, I think one is stuck using Handlebars.

**Comment by ErikEJ** [comment]
Correct re EF Core 6, which ends support in less than a year
