### ISSUE TITLE
Support for Simultaneous Use?

### ISSUE THREAD

**Issue by Vogel612** [ErikEJ/EFCorePowerTools#2019]
I'm working in a team where the majority of other devs are using Visual Studio together with the extension.
Personally I prefer using CLI-based tooling for buildsteps (primarily because that's a lot easier to reproduce in a CI/CD context), so I've been getting around using VSCode and the basic dotnet tools.

When I try to use the cli tool provided from this repo with a configuration file generated from the Visual Studio extension, that fails miserably.
As far as I can tell the two configuration mechanisms are mutually incompatible since the cli-config uses [`CliConfig`](https://github.com/ErikEJ/EFCorePowerTools/blob/b541fac0161604e4a93aca14602d8dfe4a217fd8/src/GUI/RevEng.Shared/Cli/Configuration/CliConfig.cs), which imposes a kebab-case property naming for the serialized JSON and is stored in a file named `efcpt.config.json`.
In opposition to that, the Visual Studio extension uses PascalCase for configuration based off the [`ReverseEngineerOptions`](https://github.com/ErikEJ/EFCorePowerTools/blob/b541fac0161604e4a93aca14602d8dfe4a217fd8/src/GUI/Shared/Handlers/ReverseEngineer/ReverseEngineerOptions.cs)

Am I correct in assuming that mixing these two modes of interacting with EFCorePowerTools reverse engineering is not supported?
Are there any plans of unifying the configuration behavior between these two and exposing the extension functionality to the CLI?

**Comment by ErikEJ** [comment]
No, the two config files Server different purposes, since the cli does not have a UI. For example regarding table selection/Exclusion.
