### ISSUE TITLE
DbContext DbSet returning null

### ISSUE THREAD

**Issue by wsyeager** [ErikEJ/EFCorePowerTools#2021]
Create a bug report, feature proposal, or ask a question.

NOTICE: A bug report without sufficient technical and repro details and version information WILL BE CLOSED WITHOUT ANY FURTHER ACTION.

- Visual Studio 2022 4.8.09037)

- Database engine: (SQL Server)

- EF Core version in use: (e.g. EF Core 8)

- Is Handlebars templates used: **no**/yes

- Is T4 templates used: **no**/yes

- Is a SQL Server .dacpac used: **no**/yes

### Provide steps to reproduce a bug
 **Just trying to get a list of InboundScanLoad data.**
### Code in order of execution
`public class PalletteCartonCountController : ControllerBase
{
    **private SIRISContextProcedures db = new SIRISContextProcedures();**

    [HttpGet]
    [Route("PalletteCartonCount/GetLastScanForBOL/Bol")]
    [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(InboundScansLoad))]
    [ProducesResponseType(StatusCodes.Status204NoContent, Type = typeof(InboundScansLoad))]
    public ObjectResult GetLastScanForBOL(string Bol)
    {
        try
        {
            //Get list of BOL's matching incoming Bol
            List<InboundScansLoad> isl = new List<InboundScansLoad>();
           ** isl = db.InboundScansLoads**
                        .Where(c => c.Order == Bol).OrderBy(c => c.Id).ToList();

            if (isl.Count() > 0)`

`namespace SpiritWMSApiCore2.Models;

public partial class SIRISContext : DbContext
{
    string envPlatform = "";

    public SIRISContext()
    {
        string environment = Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT");
        envPlatform = "appsettings." + environment + ".json";
    }`

`    private ISIRISContextProcedures _procedures;

    public virtual ISIRISContextProcedures Procedures
    {
        get
        {
            if (_procedures is null) _procedures = new SIRISContextProcedures();
            return _procedures;
        }
        set
        {
            _procedures = value;
        }
    }

    public ISIRISContextProcedures GetProcedures()
    {
        return Procedures;
    }

    protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<BOL_Id_CreateResult>().HasNoKey().ToView(null);
        modelBuilder.Entity<Can_DeleteResult>().HasNoKey().ToView(null);
        modelBuilder.Entity<CreateBOLManualResult>().HasNoKey().ToView(null);
        modelBuilder.Entity<GetNumberOfParsResult>().HasNoKey().ToView(null);
        modelBuilder.Entity<Load3PLCartonScans_UnitechResult>().HasNoKey().ToView(null);
        modelBuilder.Entity<PalletInfoResult>().HasNoKey().ToView(null);
        modelBuilder.Entity<ShippingBOL_SaveResult>().HasNoKey().ToView(null);
        modelBuilder.Entity<Unitech_ASNInfo_BOLResult>().HasNoKey().ToView(null);
        modelBuilder.Entity<Unitech_InventoryDataResult>().HasNoKey().ToView(null);
        modelBuilder.Entity<Unitech_PalletInventoryResult>().HasNoKey().ToView(null);
        modelBuilder.Entity<Unitech_ValidateBolDataResult>().HasNoKey().ToView(null);
        modelBuilder.Entity<Unitech_ValidateInboundDataResult>().HasNoKey().ToView(null);
    }
}

public partial class SIRISContextProcedures : ISIRISContextProcedures
{
    **private SIRISContext _context = new SIRISContext();**
    SqlConnection con = null;

    public virtual DbSet<BolvalidationControl> BolvalidationControls { get; set; }

    public virtual DbSet<Carrier> Carriers { get; set; }

    public virtual DbSet<CartonMasterBol> CartonMasterBols { get; set; }

    public virtual DbSet<HomeOfficeSubscription> HomeOfficeSubscriptions { get; set; }

    public virtual DbSet<InboundOrder> InboundOrders { get; set; }

    **public virtual DbSet<InboundScansLoad> InboundScansLoads { get; set; }**`

`public class PalletteCartonCountController : ControllerBase
{
    **private SIRISContextProcedures db = new SIRISContextProcedures()**

**isl = db.InboundScansLoads
            .Where(c => c.Order == Bol).OrderBy(c => c.Id).ToList();**'

'public partial class SIRISContextProcedures : ISIRISContextProcedures
{
    **private SIRISContext _context = new SIRISContext();**
    SqlConnection con = null;

    public virtual DbSet<BolvalidationControl> BolvalidationControls { get; set; }

    public virtual DbSet<Carrier> Carriers { get; set; }

    public virtual DbSet<CartonMasterBol> CartonMasterBols { get; set; }

    public virtual DbSet<HomeOfficeSubscription> HomeOfficeSubscriptions { get; set; }

    public virtual DbSet<InboundOrder> InboundOrders { get; set; }

    **public virtual DbSet<InboundScansLoad> InboundScansLoads { get; set; }**'

' catch (Exception ex)
 {
     **throw;**
 }'
###

![Screenshot 2023-11-27 103612](https://github.com/ErikEJ/EFCorePowerTools/assets/3451337/0af42107-38d0-464a-a6a1-c5f8de224f8f)

![Screenshot 2023-11-27 104003](https://github.com/ErikEJ/EFCorePowerTools/assets/3451337/6ef3b973-0a92-40c8-b6cb-167a2b1604b4)

![Screenshot 2023-11-27 104041](https://github.com/ErikEJ/EFCorePowerTools/assets/3451337/5b542f9c-17b5-4f57-84fe-315e5a5ab8ae)

**Notice that db.InboundScansLoads is null**

**Comment by ErikEJ** [comment]
Or al least share a full stack trace

**Comment by wsyeager** [comment]
[SpiritWMSApiCore2.zip](https://github.com/ErikEJ/EFCorePowerTools/files/13477704/SpiritWMSApiCore2.zip)

Erik, I've uploaded the project.  Just substitute '5' on line 19:
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/3451337/83917076-e8c0-473c-bc4d-8fa1c5e0267a)


The files that are executed are below:
![Screenshot 2023-11-27 112840](https://github.com/ErikEJ/EFCorePowerTools/assets/3451337/00f3ca85-0958-4795-8e84-88de4135b719)

**Comment by ErikEJ** [comment]
Do you have a script to create and populate the database, I need runnable code, pls.

**Comment by wsyeager** [comment]
> Or al least share a full stack trace

Heree is the stack trace.


> Or al least share a full stack trace

[st7.zip](https://github.com/ErikEJ/EFCorePowerTools/files/13477948/st7.zip)

**Comment by wsyeager** [comment]
> > Do you have a script to create and populate the database, I need runnable code, pls.
> 
> Here is the script... [inboundscansload_script.zip](https://github.com/ErikEJ/EFCorePowerTools/files/13477886/inboundscansload_script.zip)

btw, this bol will return success: BRGA3230426160915 which is in the db
'5' will return not found: 5

> > Do you have a script to create and populate the database, I need runnable code, pls.
> 
> Here is the script... [inboundscansload_script.zip](https://github.com/ErikEJ/EFCorePowerTools/files/13477886/inboundscansload_script.zip)

btw, CartonId is the PK with an Identity value by 1

**Comment by ErikEJ** [comment]
Thanks, I will have a look.

**Comment by ErikEJ** [comment]
Stored procedure do not use DbSets  - they just return a result class.

But maybe I finally understand what your question is about- you want to map a result from a stored procedure to an Entity class??

In that case, please read the wiki to ser how that can be done.

**Comment by ErikEJ** [comment]
As I wrote earlier  the stored procedures are not related to DbSets. 

The code in the screenshot above is not generated by my tool, so I cannot offer you free support on that.

**Comment by ErikEJ** [comment]
Ah! Glad you got it figured out.

**Comment by wsyeager** [comment]
> > > Ah! Glad you got it figured out.
> > 
> > 
> > Erik, when using the reverse engineering for the tables, after adding another table to an exisitng one that already got created, it wipes out the one that got created.
> > I must be doing something wrong when creating the additional table.
> 
> initial after adding 2 tables: ![image](https://private-user-images.githubusercontent.com/3451337/286028521-d3f4e09c-6fbd-4752-a37e-f02636bf5795.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExMjEyODYsIm5iZiI6MTcwMTEyMDk4NiwicGF0aCI6Ii8zNDUxMzM3LzI4NjAyODUyMS1kM2Y0ZTA5Yy02ZmJkLTQ3NTItYTM3ZS1mMDI2MzZiZjU3OTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjdUMjEzNjI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmMxOTFkYTkzZjkyODg4ZWRjM2U0Mjc4NDg4MGUwOTM4MTRjZjJlNjFmOTlhNmQ1ODQzNGU3NTNmNzc4MDYxZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LLu1U-XzhbvJtdBqeNyWBKet6d6CXzFKlxxfzlzFwDA)
> 
> after adding third table. the above gets wiped out. ![image](https://private-user-images.githubusercontent.com/3451337/286028743-b03c77cd-a2a3-42c4-b04b-8b8007493a48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExMjEyODYsIm5iZiI6MTcwMTEyMDk4NiwicGF0aCI6Ii8zNDUxMzM3LzI4NjAyODc0My1iMDNjNzdjZC1hMmEzLTQyYzQtYjA0Yi04YjgwMDc0OTNhNDgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjdUMjEzNjI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2U0YmVhNWU1M2JjZjc2ZTI4MjNjMjI2NzNjNzhiZjM0M2VjMzZkNzliZWMzMWY3YmZhZjEyNDZjNTdhMzIxNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Rbl0xNYezRUNHkTl3HDsTLcEmkrIoBM_K74a9yuZNLE)

i didn't read the wiki properly. i can create multiple ones at the same time.

**Comment by ErikEJ** [comment]
As I wrote long ago, pls read the wiki 😉

**Comment by wsyeager** [comment]
Ive resolved everything now. It's cool. Great product!

Main thing is that I wasn't creating the tables and sprocs in one shot which affected the way I was interpreting the tool.

Thx for your help.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ErikEJ** [comment]
So great you managed to get it to work for you!

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
