### ISSUE TITLE
V 2.5.1694 not showing list of tables

### ISSUE THREAD

**Issue by benbattershell** [ErikEJ/EFCorePowerTools#2024]
Tool version V2.5.1694 in my VS2022 (Version 17.8.1) ; data base engine is SQL Express 2022 (16.0.1105.1);  EF Core 7
Does not show list of tables;  my project is a core mvc for Windows; I right click on my MODELS folder and select ADD/New ITem..
In the data tab I have your EF data tools installed.  It prompts me for the Database connection; I enter that connection into and then click OK... And then nothing happens... The tool does not show me the list of tables in the DB.

This worked great my previous machine.  (SQL Express 2014) VS (17.6.3); EF 7
Sorry, I don't know about Handlebars or T4 or dpac

NOTICE: A bug report without sufficient technical and repro details and version information WILL BE CLOSED WITHOUT ANY FURTHER ACTION.

### Provide steps to reproduce a bug

Please include a **complete** description of the issue or link to a project that I can run to reproduce the issue.

### Provide technical details

- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)

- Exact Visual Studio version: (e.g. Visual Studio 2022 17.6.5)

- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)

- EF Core version in use: (e.g. EF Core 7)

- Is Handlebars templates used: no/yes

- Is T4 templates used: no/yes

- Is a SQL Server .dacpac used: no/yes

**Comment by ErikEJ** [comment]
Please check the "Extensions" output window for error messages.

**Comment by benbattershell** [comment]
Erik,

 

Thank you!!!!!

The output window showed me that I needed the Core V6 runtime.  I installed that it is working…

 

Thank you so much.  Your tool is great for a guy (like me) that wants to start with the database.

 

…benb

 

Ben Battershell

RoamingCode, Inc.

600 Eastwood Ave

Fort Worth, TX 76107

 ***@***.***> ***@***.***

 <http://www.roamingcode.com> www.roamingcode.com

CELL PHONE: 512-694-2647

**Comment by benbattershell** [comment]
Fixed!!!...benb

**Comment by ErikEJ** [comment]
Wonder if I could Warn better if dotnet is not installed.

**Comment by ErikEJ** [comment]
Keeping this open to improve the error message.

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.
