### ISSUE TITLE
System.Threading.Tasks.TaskCanceledException error using context.Database.ExecuteSqlRawAsync on only this one method

### ISSUE THREAD

**Issue by wsyeager** [ErikEJ/EFCorePowerTools#2025]
Create a bug report, feature proposal, or ask a question.

NOTICE: A bug report without sufficient technical and repro details and version information WILL BE CLOSED WITHOUT ANY FURTHER ACTION.

### Provide steps to reproduce a bug

Erik, attached is the solution at the bottom...

Here is the script for creating the table & data:
[script.zip](https://github.com/ErikEJ/EFCorePowerTools/files/13504579/script.zip)

You just need to execute the "Put" method in the "ShippingNotificationController" within the Controllers folder called "ShippingNotification_Update".
Just select the input variables from the only record I included in the DB table.

image

[SpiritWMSApiCore2.zip](https://github.com/ErikEJ/EFCorePowerTools/files/13503989/SpiritWMSApiCore2.zip)

@wsyeager
Author
[wsyeager](https://github.com/wsyeager) commented [29 minutes ago](https://github.com/ErikEJ/EFCorePowerTools/issues/2023#issuecomment-1832546425)
Use the data inside the only record in the DB table for input going into the DB. It's failing where the breakpoint is above with the following error:

This will execute the below method inside the SIRISContextProcedures.cs file:
var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnvalue = [3PL].[BOL_Update] @bol, https://github.com/kit, @carrier, https://github.com/shipdate", sqlParameters, cancellationToken);
returnValue?.SetValue(parameterreturnValue.Value);
return _;

Error
System.Threading.Tasks.TaskCanceledException
HResult=0x8013153B
Message=A task was canceled.
Source=Microsoft.EntityFrameworkCore.Relational
StackTrace:
at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.d__70.MoveNext()
at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.d__70.MoveNext()
at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.d__66.MoveNext()
at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.d__14.MoveNext()
at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.d__17.MoveNext()
at SpiritWMSApiCore2.Models.SIRISContextProcedures.<BOL_UpdateAsync>d__6.MoveNext() in C:\Users\WYeager\source\repos\SpiritWMSApiCore2\Models\SIRISContextProcedures.cs:line 237
at SpiritWMSApiCore.Controllers.ShippingNotificationController.d__5.MoveNext() in C:\Users\WYeager\source\repos\SpiritWMSApiCore2\Controllers\ShippingNotificationController.cs:line 63

### Provide technical details

- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
- 2.5.1694

- Exact Visual Studio version: (e.g. Visual Studio 2022 17.6.5)
- 4.8.09037

- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)
- SQL Server

- EF Core version in use: (e.g. EF Core 7)
- EF Core 8

- Is Handlebars templates used: **no**/yes

- Is T4 templates used: **no**/yes

- Is a SQL Server .dacpac used: **no**/yes

**Comment by wsyeager** [comment]
> Is this a duplicate??

yes, but I believe I have provided you the necessary items you asked for to test with now.

**Comment by ErikEJ** [comment]
@wsyeager Your code is wrong (and your repro does not include the stored procedure script)

This controller implementation works as expected (and follow the sample code from my wiki, I wish you had given it a closer look)

Notice that I just use the SirisContext.Procedures property!

and I do not use "public async void"

```
using Microsoft.AspNetCore.Mvc;
using SpiritWMSApiCore2.Models;

namespace SpiritWMSApiCore.Controllers
{
    [ApiController]
    public class ShippingNotificationController : ControllerBase
    {
        private SIRISContext db;

        public ShippingNotificationController(SIRISContext context)
        {
            db = context;
        }

        [HttpPut]
        [Route("ShippingNotification/bolId")]
        public async Task Put(string bolId, [FromBody] ShippingNotification_Update shippingNotification)
        {
            var result = await db.Procedures.BOL_UpdateAsync(bolId, s.Kit, s.Carrier, s.ShipDate);
        }
    }
}

```

**Comment by wsyeager** [comment]
> @wsyeager Your code is wrong (and your repro does not include the stored procedure script)
> 
> This controller implementation works as expected (and follow the sample code from my wiki, I wish you had given it a closer look)
> 
> Notice that I just use the SirisContext.Procedures property!
> 
> and I do not use "public async void"
> 
> ```cs
> using Microsoft.AspNetCore.Mvc;
> using SpiritWMSApiCore2.Models;
> 
> namespace SpiritWMSApiCore.Controllers
> {
>     [ApiController]
>     public class ShippingNotificationController : ControllerBase
>     {
>         private SIRISContext db;
> 
>         public ShippingNotificationController(SIRISContext context)
>         {
>             db = context;
>         }
> 
>         [HttpPut]
>         [Route("ShippingNotification/bolId")]
>         public async Task Put(string bolId, [FromBody] ShippingNotification_Update shippingNotification)
>         {
>             var result = await db.Procedures.BOL_UpdateAsync(bolId, s.Kit, s.Carrier, s.ShipDate);
>         }
>     }
> }
> ```

Thanks Erik. My mistake with the void and I modified the code as you said using the SirisContext.Procedures.

I have a quick question... I need to set a Command timeout in one of the methods for a stored procedure. Where would I place that code within this method?
`public virtual async Task<List<Load3PLCartonScans_UnitechResult>> Load3PLCartonScans_UnitechAsync(bool? Validate, string Bol, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
{
    var parameterreturnValue = new SqlParameter
    {
        ParameterName = "returnValue",
        Direction = System.Data.ParameterDirection.Output,
        SqlDbType = System.Data.SqlDbType.Int,
    };

    var sqlParameters = new []
    {
        new SqlParameter
        {
            ParameterName = "Validate",
            Value = Validate ?? Convert.DBNull,
            SqlDbType = System.Data.SqlDbType.Bit,
        },
        new SqlParameter
        {    
            ParameterName = "Bol",
            Size = 25,
            Value = Bol ?? Convert.DBNull,
            SqlDbType = System.Data.SqlDbType.VarChar,
        },
        parameterreturnValue,
    };
    var _ = await _context.SqlQueryAsync<Load3PLCartonScans_UnitechResult>("EXEC @returnValue = [3PL].[Load3PLCartonScans_Unitech] @Validate, @Bol", sqlParameters, cancellationToken);

    returnValue?.SetValue(parameterreturnValue.Value);

    return _;
}`

**Comment by ErikEJ** [comment]
```csharp
_context.Database.SetCommandTimeout(60);
```
