### ISSUE TITLE
Plans on supporting Visual Studio 2022 (ARM64)

### ISSUE THREAD

**Issue by mmarquesbr** [ErikEJ/EFCorePowerTools#2026]
Hi Erick,

**Congrats on this great extension!** Any plans to implement support for Visual Studio ARM64?

**Comment by ErikEJ** [comment]
If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
