### ISSUE TITLE
Error when importing a stored procedure from a DACPAC file = empty result class generated

### ISSUE THREAD

**Issue by hjrb** [ErikEJ/EFCorePowerTools#2027]
1.  Create a solution with a SQL Database Project Database1
2. Add a simple table e.g.
CREATE TABLE [dbo].[SomeTable]
(
	[Id] INT NOT NULL PRIMARY KEY,
	[Data] nvarchar(100)
)
3.) Add a simple stored procedure
CREATE PROCEDURE [dbo].[GetSomeData]
AS
	SELECT * From SomeTable
RETURN 0
4.) Add two assembly projects to the solution DBContextFromDPAC and DBContextFromSQLDB
7.) Run the Reverse Engineer command using the DPAC file of the Databas1 project. 
Generates this code for GetSomeDataResult.cs
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ClassLibrary1.Models
{
    public partial class GetSomeDataResult
    {
// empty, result columns missing
    }
}

8.) Deploy the SQL Database Projectd Database1 to a local SQL Server 2022instance / database (might also occur with over versions/SKUs of MS SQL)
7.) Run the Reverse Engineer command using a new connection to the deployed database
9.)  Generates this code for GetSomeDataResult.cs
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DBContextFromSQLDB.Models
{
    public partial class GetSomeDataResult
    {
// that are the correct columns
        public int Id { get; set; }
        public string Data { get; set; } 
    }
}

The whole code and solution is available at https://github.com/hjrb/EFCorePowerToolsIssue/tree/master. Should be easy to reproduce.
Obviously the DPAC meta data provider for the stored procedure does not provide the correct information.
The SQL Database Projects are kind of helpful but they by far do not catch all issues when compiling. Pretty often I get errors in the SQL code when trying to deploy even though the project compiled happily. 
I would recommend to always compare the generated DB Context classes between what REALLY exists in the DB and what is defined in the SQL Database project.
If you discover that this is an issue with the underlying MS libraries (likely) let me know. I might be able to open an issue at MS and get professional support.

Thanks for providing this great tool! Love it. Use it every day. DB first forever! :-)

**Comment by ErikEJ** [comment]
Thanks, I will have a look, this is actually documented [here](https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#sql-server-database-project-dacpac-mapping)

**Comment by hjrb** [comment]
Thank you for the link. I'll use the SQL Server connection for now. As I said if you need support from MS i'm willing to open a ticket on behalf of you. You just need to find reproduceable issue in an MS library.

**Comment by ErikEJ** [comment]
As I said, I will have a closer look to see if I can improve anything. For example not using "SELECT *"

**Comment by ErikEJ** [comment]
If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by hjrb** [comment]
Already rated 5 stars. Sorry - I'm using it professionally and I guess my (conservative) company does not support github sponsorships. Maybe a one-time payment - but most likely HUGE administrative effort.

**Comment by hjrb** [comment]
Already rated 5 stars. Sorry - I'm using it professionally and I guess my (conservative) company does not support github sponsorships. Maybe a one time payment - but HUGE administrative effort.
