### ISSUE TITLE
[question]: database first support for JSON_VALUE & JSON_QUERY / ToJson()

### ISSUE THREAD

**Issue by rallets** [ErikEJ/EFCorePowerTools#2030]
Hi, I was wondering is it possible to enrich somehow the db metadata to be able to get a Model that can use the latest `EF Core 8` support to `Json values`? 
I refer to the new EF core 8 `ToJson()` (and similar) in the `Code First` approach in the `model builder`.

If I am correct, the db column should be a `nvarchar(max)` and then is in the model builder that we can define that column `AsJson()` and get benefit of the new features. Or am I wrong?

Thank you

**Comment by ErikEJ** [comment]
You can override any configuration in partial classes and override OnModelCreatingPartial

**Comment by rallets** [comment]
Ah thanks 🙏 I didn't know about `OnModelCreatingPartial`, it should then allow to add the Json info needed

**Comment by rallets** [comment]
I'm not currently working on that project, but I could have the opportunity to try this scenario at some point the next year. I will keep updated this post then 👍
