### ISSUE TITLE
Problem with Reverse Engineering in .NET Core 3.1 EF Project in Visual Studio 2022

### ISSUE THREAD

**Issue by zdenekkovararicoma** [ErikEJ/EFCorePowerTools#2031]
Hello, in Visual Studio 2022 Version 17.8.3, I have installed the EF Core Power Tool 2.5.1694 extension. It works fine in other projects, but I have an older project with .NET Core 3.1 and in the EF data project, EF Core Power Tools does not offer the Reverse Engineering option at all with the current epft.config.json. If I rename epft.config.json, then after restarting VS 2022, the Reverse Engineering option is offered, but it throws the error message ‘.NET 5 and earlier is not supported’. What can I do to make Reverse Engineering work? There used to be a version selection dropdown in the past.

**Comment by ErikEJ** [comment]
@zdenekkovararicoma EF Core 3.1 is out of support. I have an old unsupported installer in the tools folder in this repo that you might be able to use.
