### ISSUE TITLE
DateOnly type not working for SQL Function parameter

### ISSUE THREAD

**Issue by Marco-Mauri** [ErikEJ/EFCorePowerTools#2032]
Given this Function:

CREATE FUNCTION [ltpl].[udf_GetBrands]
(	
	@atDate		date
	,@customerId int
	,@tradeCategoryIDs nvarchar(max)
	,@userName		nvarchar(255)
)
RETURNS TABLE 
AS
....

with the "Map DateOnly and TimeOnly" checked the tool generate the following code:

[DbFunction("udf_GetBrands", "ltpl")]
public IQueryable<udf_GetBrandsResult> udf_GetBrands(DateTime? atDate, int? customerId, string tradeCategoryIDs, string userName)
{
    return FromExpression(() => udf_GetBrands(atDate, customerId, tradeCategoryIDs, userName));
}

using a DateTime parameter instead of a DateOnly one

**Comment by ErikEJ** [comment]
@Marco-Mauri Does the function work if you manually change to a DateOnly? parameter?

**Comment by Marco-Mauri** [comment]
Yes, I've just tried.
If I manually set the type to DateOnly and then rerun the application all works as expected (using EF Core 8.0)

**Comment by ErikEJ** [comment]
@Marco-Mauri Cool, I will look into a fix for this, it would be helpful if you could provide complete repro sample scripts

**Comment by Marco-Mauri** [comment]
I've created a minimal project to replicate the situation
[TestDateSQLFunction.zip](https://github.com/ErikEJ/EFCorePowerTools/files/13597324/TestDateSQLFunction.zip)

The function called DateTestFunction was created automatically by the tool, instead the one called DateTestFunctionManual was created manually by me changing only the type.

I've also noticed the same problem in the entity created for the results of the function.

The sql function used in the tests was the following:

CREATE FUNCTION DateTestFunction
(	
	@TheDate date
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT @TheDate AS DateColumn
)

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), (.1707 or later) would be grateful if you could try it out.

**Comment by ErikEJ** [comment]
If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by Marco-Mauri** [comment]
I just checked and now it works perfectly.
I've also added a 5 star review.
