### ISSUE TITLE
'RelationalEntityTypeBuilderExtensions.HasComment<TEntity>(EntityTypeBuilder<TEntity>, string?)' is obsolete

### ISSUE THREAD

**Issue by HGSandhagen** [ErikEJ/EFCorePowerTools#2033]
If a comment for a table is defined in SQL Server, the generated code in DbContext contains:

            modelBuilder.Entity<MyTable>(entity =>
            {
                entity.ToTable("MyTable");

                entity.HasComment("Description of  MyTable");
                .....
           }

When compile this there is a warning:

Warning	CS0618	'RelationalEntityTypeBuilderExtensions.HasComment<TEntity>(EntityTypeBuilder<TEntity>, string?)' is obsolete: 'Configure this using ToTable(t => t.HasComment()) instead.'

Expectation: Generated code should be changed to 
        entity.ToTable("MyTable", t => t.HasComment("Description of  MyTable"))
to avoid this warning.

- EF Core Power Tools version: 2.5.1694
- Exact Visual Studio version: Visual Studio 2022 17.8.3
- Database engine: SQL Server
- EF Core version in use: EF Core 8
- Is Handlebars templates used: no
- Is T4 templates used: no
- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
Have you re-generated the code targeting EF Core 8?

**Comment by HGSandhagen** [comment]
Sorry, my fault. I used "Refresh" in Visual Studio not Edit. Now this works.
