### ISSUE TITLE
[Feature] Add Korean localization

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#2034]
Languages or language updates:

- [x] Korean
- [x] Japanese
- [x] Polish (in progress)
- [x] Russian
- [x] French updates
- [x] Italian updates
- [x] Turkish updates
- [x] Czech
- [x] German
- [x] Zh hant
- [x] Portugese (Brazil)
- [x] Zh Hans updates
- [x] Spanish updates

Guide: 

- Fork and clone the repo
- Open in VS 2022
- Open the /src/GUI/EFCorePowerTools.sln file
- Open the EFCorePowerTools project
- In the Locales folder, copy each *.en.resx file to your language, f.ex. *.de.resx
- Translate the strings in the newly created files (maybe install the extension to understand context)
- In the root folder copy VSpackage.en.resx to your language, f.ex.  VSpackage.de.resx and translate
- In the root folder, copy EFCorePowerToolsPackage.en.vsct to your language, f.ex. EFCorePowerToolsPackage.de.vsct and translate all `<ButtonText>` entries
- Create a Pull Request with your changes!

Any contributor gets 1 hour of free consultancy!

List of [supported languages](https://learn.microsoft.com/en-us/visualstudio/install/install-visual-studio?view=vs-2022#step-6---install-language-packs-optional)

**Comment by ErikEJ** [comment]
@rasputino @sm15455 @Varorbc @sinankeskin @omatrot

Would be very grateful if you could have another look at the state of your translations - I have added a number of texts in English to your localized files (or they are missing completely)

It concerns the .resx files in the Locales folder, the EFCorePowerToolsPackage.xx.vsct file and VSPackage.xx.resx files in the root project folder.

@omatrot A EFCorePowerToolsPackage.fr.vsct file for context menu translations is missing from your side.

Thanks for all your help!

**Comment by ErikEJ** [comment]
[latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f) should fix missing context menu translations for all lanuages.

**Comment by sinankeskin** [comment]
Unfortunately I'm not in the  .NET world anymore. Thanks for the great effort 🙏

**Comment by ErikEJ** [comment]
@rasputino Do you do an compare on the .resx files ? - @Varorbc did find some updates...

**Comment by paulowirth** [comment]
Do you still need a Brazilian Portuguese  contributor?

**Comment by ErikEJ** [comment]
@paulowirth Someone else has said yes already, will let you know if he meant it..

**Comment by paulowirth** [comment]
> @paulowirth Someone else has said yes already, will let you know if he meant it..

Sure thing. Just let me know.

**Comment by doggy8088** [comment]
I contributed `zh-Hant` translation.

**Comment by rasputino** [comment]
> @rasputino Do you do an compare on the .resx files ? - @Varorbc did find some updates...

Yes, I did. I checked the git history of all .resx and .vsct files from the original pull request. And I checked it again with [ResX Resource Manager](https://github.com/dotnet/ResXResourceManager).

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/2887216/6a5f3f5b-1044-414d-9ff8-02b497e40f83)

**Comment by ErikEJ** [comment]
@paulowirth Someone else did pt-BR!

**Comment by diegomodolo** [comment]
I thought it was marked because we've talked on twitter about I doing it, but thanks for letting me know.

**Comment by hayriozler** [comment]
I'll start Turkish translation

**Comment by ErikEJ** [comment]
@hayriozler Keep in mind, that it "just" needs an update, adding missing translations. (Compare the en-us files with the current tr files)

**Comment by hayriozler** [comment]
> @hayriozler Keep in mind, that it "just" needs an update, adding missing translations. (Compare the en-us files with the current tr files)

I've seen that @sinankeskin  has already added the Turkish support. I'll check it, if something is missing or needs to be updated, I will create a PR.

**Comment by AlexRadch** [comment]
I'll start the Russian translation

**Comment by ChaosEngine** [comment]
I'll try to help with Polish localization.

**Comment by ErikEJ** [comment]
@AndrewKeepCoding ありがとう - awesome

**Comment by ErikEJ** [comment]
Thanks everyone for their help with this - we are down to one missing language now.

**Comment by preco21** [comment]
@ErikEJ Hi, although I have no experience with EFCore, @KOZ39 and me are working on the initial Korean translation after seeing your post on [X](https://x.com/erikej/status/1802290415778902087). @KOZ39 will open a PR once it's ready. (ETA 1~2 day)

Work in progress on the fork: https://github.com/KOZ39/EFCorePowerTools/tree/ko

**Comment by preco21** [comment]
The Korean translation is ready to go: https://github.com/ErikEJ/EFCorePowerTools/pull/2403#issuecomment-2189530399

**Comment by ErikEJ** [comment]
A huge thanks to everyone that made this possible! The extension is now localized in all available Visual Studio languages /cc @madskristensen
