### ISSUE TITLE
HasColumnName gets removed from Configuration files when upgrading from EF 7 to EF 8

### ISSUE THREAD

**Issue by Hamata6** [ErikEJ/EFCorePowerTools#2041]
We have an entities project which is last time reverse engineered using EF Core 7 and your tool.
Now when we set the target of the project to NET 8 and start reverse engineering, there are many changes to the configuration files, which are almost all deletions of the .HasColumnName() methods. These calls are needed because our property names are not the exact same name as the DB column names. See below screenshot for an example:

<img width="1050" alt="afbeelding" src="https://github.com/ErikEJ/EFCorePowerTools/assets/24777262/db979b15-aee4-4acc-87f6-b205e436ecb0">

Not sure if it has to do with your tool or is part of the C# HandleBars, but I guess you can tell me :)

### Provide steps to reproduce a bug

<details>
<summary>efpt.config.json (Tables shortended)</summary>

```
{
   "CodeGenerationMode": 3,
   "ContextClassName": "DbContext",
   "ContextNamespace": null,
   "DefaultDacpacSchema": null,
   "FilterSchemas": false,
   "IncludeConnectionString": false,
   "ModelNamespace": null,
   "OutputContextPath": "Context",
   "OutputPath": "Models",
   "PreserveCasingWithRegex": true,
   "ProjectRootNamespace": "Entities",
   "Schemas": null,
   "SelectedHandlebarsLanguage": 0,
   "SelectedToBeGenerated": 0,
   "T4TemplatePath": null,
   "Tables": [ <shortened> ],
   "UiHint": null,
   "UncountableWords": null,
   "UseBoolPropertiesWithoutDefaultSql": false,
   "UseDatabaseNames": false,
   "UseDateOnlyTimeOnly": false,
   "UseDbContextSplitting": true,
   "UseDecimalDataAnnotationForSprocResult": true,
   "UseFluentApiOnly": true,
   "UseHandleBars": true,
   "UseHierarchyId": false,
   "UseInflector": true,
   "UseLegacyPluralizer": false,
   "UseManyToManyEntity": true,
   "UseNoDefaultConstructor": true,
   "UseNoNavigations": false,
   "UseNoObjectFilter": false,
   "UseNodaTime": false,
   "UseNullableReferences": true,
   "UseSchemaFolders": true,
   "UseSchemaNamespaces": false,
   "UseSpatial": false,
   "UseT4": false
}
```

</details>

<details>
<summary>efpt.renaming.json (Tables shortended)</summary>

```
[
   {
      "ColumnPatternReplaceWith": "",
      "ColumnRegexPattern": "^(vch|bit|dtm|int|dec|nvc|sin|chr|nch|tin|txt|bin)",
      "SchemaName": "dbo",
      "TablePatternReplaceWith": "",
      "TableRegexPattern": "^tbl",
      "Tables": [ {
        "Columns": [
           {
              "Name": "vchAddressLine",
              "NewName": "Description"
           }
         ],
        "Name": "tblAddressLine",
        "NewName": "AddressLine"
       } ],
      "UseSchemaName": true
   }
]
```

</details>

### Technical details

- EF Core Power Tools version: 2.5.1707

- Exact Visual Studio version: Visual Studio 2022 17.8.3

- Database engine: SQL Server

- EF Core version in use: EF Core 8

- Is Handlebars templates used: yes, C#

- Is T4 templates used: no

- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
What happens if you does not use Handlebsrs?

And do you really need to?

At any rate, sounds like a Handlebars bug, must be reported in the Handlebars repo.

**Comment by Hamata6** [comment]
Thank you for your quick response. If I don't use any kind of templates (or for example T4), the HasColumnName property does still exist.  So I'm going to report it at the HandleBars repo.

Do I really need to use Handlebars? I don't know. Our project was generated with it, so when I now reverse engineer I don't want to check 1800 changed files. Would be easier to just check a small number (the ones who contain the breaking changes of EF 8 (nullable bools, DateTime -> DateOnly)) instead of going through them all ;)

**Comment by ErikEJ** [comment]
Ok, so if you disable Handlebars 1800 files change?

You can opt out of DateTime => DateOnly if you want...

**Comment by Hamata6** [comment]
No those breaking changes are not a problem for me, I actually like the DateOnly and the not nullable booleans.
And yes, 1800 files, because our database consists of a LOT of tables ;)
And because those configuration files where previously generated using HandleBars, when I uncheck to not use HandleBars, practically all configuration files will change (mostly just only whitespace/enters). But that is to be expected.

**Comment by ErikEJ** [comment]
If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
