### ISSUE TITLE
EF Power Tools for .Net 7

### ISSUE THREAD

**Issue by wsyeager** [ErikEJ/EFCorePowerTools#2043]
Erik, can I use **.Net Core 7** with your **EF Core reverse engineering**? I see on your site where it says for **EF Core reverse engineering**, the **.NET 6.0 or .NET 8.0 x64 runtime must be installed.** Providing I can use .Net Core 7 with the reverse engineering, can I use the rest of your EF Power Tools?

- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
- 2.5.1707

- Exact Visual Studio version: (e.g. Visual Studio 2022 17.6.5)
- 17.8

- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)
- SQL Server

- EF Core version in use: (e.g. EF Core 7)
- EF Core 7

- Is Handlebars templates used: **no**/yes

- Is T4 templates used: **no**/yes

- Is a SQL Server .dacpac used: **no**/yes

**Comment by ErikEJ** [comment]
Yes, EF Core 7 runs under .NET 6 and .NET 7. But my tools require .NET 6 runtime.

You can check with:


dotnet --list-runtimes

**Comment by wsyeager** [comment]
I currently have EF .Net Core 8 and have been using your tools (even the reverse engineering) without any issues.

If I want to use .Net Core 7, are you also saying I need to have .Net Core 6 on the application server as well?

**Comment by wsyeager** [comment]
> It appears I have versions 6, 7, & 8 on my machine: ![image](https://private-user-images.githubusercontent.com/3451337/289965250-39ce49f7-1ad1-4ca2-be55-803901440d39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0MDYxNDYsIm5iZiI6MTcwMjQwNTg0NiwicGF0aCI6Ii8zNDUxMzM3LzI4OTk2NTI1MC0zOWNlNDlmNy0xYWQxLTRjYTItYmU1NS04MDM5MDE0NDBkMzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTJUMTgzMDQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjQ4YzRkZTJiYzU0NDgzOTkzYmYwOTcxYWY1ODJjM2Y2OGY5NTZkMTgxZjEwNmI5NDRjZjc4ZDhjMjU2Zjk3NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.P2ffHmEzQr09WTVaAB-p3dpC7GtMatE0BA68ofWTvkc)
> 
> So I need to make sure that .Net Core **6 & 7** are installed on the application server; correct?

Does it matter if I download the **32 or 64** bit versions for .Net 6 & 7?

**Comment by ErikEJ** [comment]
You only need .NET 6 on your developer PC, not on your server.

**Comment by wsyeager** [comment]
> You only need .NET 6 on your developer PC, not on your server.

OK. just want to make sure I'm understanding you correctly. I'm going to uninstall .Net 8 on my PC.

My server team wants to use .Net 7. I see there are **separate** downloads for .Net 6 and .Net 7. Which version of the frameworks do I need to put on the server? 

I went through all the packages I had in .Net 8 on my PC and need to downgrade 2 packages to work with .Net 7.

I also need to install version 8 (Microsoft.AspNetCore.App.Ref) for .Net 7.
I also need to install version 7.07 (Microsoft.NETCore.App.Ref) for .Net 7.

**Comment by ErikEJ** [comment]
You need to target net7.0 in your .csproj file, not mess with .App.

And install .NET 7. 

You can have multiple .net versions installed.

**Comment by ErikEJ** [comment]
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
  </PropertyGroup>

```
