### ISSUE TITLE
[Feature Request] - Adding folder path for tablefunction classes

### ISSUE THREAD

**Issue by FlorianASI** [ErikEJ/EFCorePowerTools#2044]
Dear Dev Team,

is it possible to add a folder path for table function classes like the 'DbContext path' ?
Currently all tablefunction classes will be stored in my main 'models' folder without schema subfolder or something else.

After adding tons of tablefuntions, there is no good overview and structure in the project.
Please take a look at my attached screenshot.

Thank you! 👍 
Regrads.

![github-ef-tools-request](https://github.com/ErikEJ/EFCorePowerTools/assets/119456011/d5d0c7e1-e305-44aa-8828-fe8a430f3ceb)

**Comment by ErikEJ** [comment]
I am reluctant, there are so many opinions on how to do this. 

You could do some file movement in the eftp.postrun.cmd  file?

**Comment by FlorianASI** [comment]
Dear @ErikEJ thanks for that hint!
Now everything works like charm 🥇

**Comment by ErikEJ** [comment]
Great! 

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
