### ISSUE TITLE
NpgSql (PostgreSql) option is missing in the database dropdown list

### ISSUE THREAD

**Issue by dev-vkagrawal** [ErikEJ/EFCorePowerTools#2046]
Hello, I am using VS 2022 and EF Core Power tools latest version. I am using .Net 6 framework with EF Core 6. 
When I try to add connection in reverse engineering, I do not see option to select PostgreSQL DB as connection type. I see only 3 options.
1. Azure SQL DB
2. Firebird
3. MySQL

Please help how can I add PostgreSQL DB connection under Reverse Engineering?

**Comment by ErikEJ** [comment]
@dev-vkagrawal In short: Install "EF Core Power Pack" - read the docs for detailed info: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#choose-data-source

**Comment by dev-vkagrawal** [comment]
@ErikEJ  thank you for prompt and straight forward reply. I installed the "EF Core Power Pack" and now I can add PostgreSQL connection.

**Comment by ErikEJ** [comment]
Great!

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
