### ISSUE TITLE
C# DateOnly Type getting error within EntityFramework Power Tools

### ISSUE THREAD

**Issue by wsyeager** [ErikEJ/EFCorePowerTools#2047]
Create a bug report, feature proposal, or ask a question. I'm hoping you can take a look at these screen shots and decipher what might be wrong. It seems self explanatory. If you need me to do so, I certainly will. 

Erik, here are the frameworks I have on my local machine:
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/3451337/0a5b0f3f-e7dc-48f0-91a5-60d99b9a7c66)

I've been using a .Net 8 solution without any issues. When I am targeting a .Net 7 version of the same exact solution, 
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/3451337/412b5903-bd31-475a-aab2-b06c800e5708)

I'm getting the following error:
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/3451337/36555113-ad92-4973-a37a-8fbbb025f4c4)

This is the model that was created from the Powertools:
![model](https://github.com/ErikEJ/EFCorePowerTools/assets/3451337/c1acebbd-3f51-4933-a5f4-884f2f8bb826)

It is failing when it calls this stored procedure:
![sproc call](https://github.com/ErikEJ/EFCorePowerTools/assets/3451337/ea184b45-e2eb-4cbb-957f-e10e8f942e53)

Here are the .Net 7 dependencies I am using:
![dependencies](https://github.com/ErikEJ/EFCorePowerTools/assets/3451337/1f261e0b-2c85-4ef5-82fc-12a424b09d0e)

Here is the call to the SPROC, failing where the breakpoint is unlike the .Net 8 version which has no issue.
![sproc call](https://github.com/ErikEJ/EFCorePowerTools/assets/3451337/7e654905-fd60-4eb6-9723-ae032e0c80d8)

The SPROC doesn't have anything to do with the DateOnly type as seen by only the 3 columns below:
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/3451337/fdbb9c05-0ee3-4504-8a35-c49eaa67ea19)

It seems like it has to do something with the model that the EF PowerTools creates for C# 11??? and EF 7?

### Provide steps to reproduce a bug

Please include a **complete** description of the issue or link to a project that I can run to reproduce the issue.

### Provide technical details

- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
- 2.5.1707

- Exact Visual Studio version: (e.g. Visual Studio 2022 17.6.5)
- 17.8.0
- 
- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)
- Sql Server: 18.12.1

- EF Core version in use: (e.g. EF Core 7)
- 7
- 
- Is Handlebars templates used: no/yes
- no
-
- Is T4 templates used: no/yes
- no
- 
- Is a SQL Server .dacpac used: no/yes
- no

**Comment by ErikEJ** [comment]
You need to run scaffolding again using the EF Core 7 option, or use my DateOnly support package- https://www.nuget.org/packages/ErikEJ.EntityFrameworkCore.SqlServer.DateOnlyTimeOnly 

I do not understand any goid reason for downgrading to a .net version that goes out of support soon.

In addition I will not provide support based on screen shots instead of text.

**Comment by wsyeager** [comment]
> You need to run scaffolding again using the EF Core 7 option, or use my DateOnly support package- https://www.nuget.org/packages/ErikEJ.EntityFrameworkCore.SqlServer.DateOnlyTimeOnly
> 
> I do not understand any goid reason for downgrading to a .net version that goes out of support soon.
> 
> In addition I will not provide support based on screen shots instead of text.

I **completely** agree with your assessment of "I do not understand any goid reason for downgrading to a .net version that goes out of support soon.". Management here thinks that .net core 8.0 is unstable until it moves up several releases.

**Comment by wsyeager** [comment]
> > You need to run scaffolding again using the EF Core 7 option, or use my DateOnly support package- https://www.nuget.org/packages/ErikEJ.EntityFrameworkCore.SqlServer.DateOnlyTimeOnly
> > I do not understand any goid reason for downgrading to a .net version that goes out of support soon.
> > In addition I will not provide support based on screen shots instead of text.
> 
> I **completely** agree with your assessment of "I do not understand any goid reason for downgrading to a .net version that goes out of support soon.". Management here thinks that .net core 8.0 is unstable until it moves up several releases.

I'll use your DateOnly support package. thx.

To run scaffolding again using the EF Core 7 option, which option would I run in the EF PowerTools? Would I have to Reverse Engineer the tables & sprocs again?

**Comment by wsyeager** [comment]
> > > You need to run scaffolding again using the EF Core 7 option, or use my DateOnly support package- https://www.nuget.org/packages/ErikEJ.EntityFrameworkCore.SqlServer.DateOnlyTimeOnly
> > > I do not understand any goid reason for downgrading to a .net version that goes out of support soon.
> > > In addition I will not provide support based on screen shots instead of text.
> > 
> > 
> > I **completely** agree with your assessment of "I do not understand any goid reason for downgrading to a .net version that goes out of support soon.". Management here thinks that .net core 8.0 is unstable until it moves up several releases.
> 
> I'll use your DateOnly support package. thx.
> 
> To run scaffolding again using the EF Core 7 option, which option would I run in the EF PowerTools? Would I have to Reverse Engineer the tables & sprocs again?

I'm still getting the same error even after installing the package:
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/3451337/832a0820-d44f-4cfb-9712-5423bc0afb88)

**Comment by wsyeager** [comment]
> > > > You need to run scaffolding again using the EF Core 7 option, or use my DateOnly support package- https://www.nuget.org/packages/ErikEJ.EntityFrameworkCore.SqlServer.DateOnlyTimeOnly
> > > > I do not understand any goid reason for downgrading to a .net version that goes out of support soon.
> > > > In addition I will not provide support based on screen shots instead of text.
> > > 
> > > 
> > > I **completely** agree with your assessment of "I do not understand any goid reason for downgrading to a .net version that goes out of support soon.". Management here thinks that .net core 8.0 is unstable until it moves up several releases.
> > 
> > 
> > I'll use your DateOnly support package. thx.
> > To run scaffolding again using the EF Core 7 option, which option would I run in the EF PowerTools? Would I have to Reverse Engineer the tables & sprocs again?
> 
>

> > > > You need to run scaffolding again using the EF Core 7 option, or use my DateOnly support package- https://www.nuget.org/packages/ErikEJ.EntityFrameworkCore.SqlServer.DateOnlyTimeOnly
> > > > I do not understand any goid reason for downgrading to a .net version that goes out of support soon.
> > > > In addition I will not provide support based on screen shots instead of text.
> > > 
> > > 
> > > I **completely** agree with your assessment of "I do not understand any goid reason for downgrading to a .net version that goes out of support soon.". Management here thinks that .net core 8.0 is unstable until it moves up several releases.
> > 
> > 
> > I'll use your DateOnly support package. thx.
> > To run scaffolding again using the EF Core 7 option, which option would I run in the EF PowerTools? Would I have to Reverse Engineer the tables & sprocs again?
> 
> **I'm still getting the same error even after installing the package**: ![image](https://private-user-PM> cd C:\Users\WYeager\source\repos\SpiritWMSApiCore2\
PM> dotnet add package ErikEJ.EntityFrameworkCore.SqlServer.DateOnlyTimeOnly --version 7.0.6
  Determining projects to restore...
  Writing C:\Users\WYeager\AppData\Local\Temp\tmpwohdvq.tmp
info : X.509 certificate chain validation will use the default trust store selected by .NET for code signing.
info : X.509 certificate chain validation will use the default trust store selected by .NET for timestamping.
info : Adding PackageReference for package 'ErikEJ.EntityFrameworkCore.SqlServer.DateOnlyTimeOnly' into project 'C:\Users\WYeager\source\repos\SpiritWMSApiCore2\SpiritWMSApiCore2.csproj'.
info : Restoring packages for C:\Users\WYeager\source\repos\SpiritWMSApiCore2\SpiritWMSApiCore2.csproj...
info :   CACHE https://api.nuget.org/v3/vulnerabilities/index.json
info :   CACHE https://api.nuget.org/v3/vulnerabilities/vulnerability.base.json
info :   CACHE https://api.nuget.org/v3/vulnerabilities/vulnerability.update.json
info : Package 'ErikEJ.EntityFrameworkCore.SqlServer.DateOnlyTimeOnly' is compatible with all the specified frameworks in project 'C:\Users\WYeager\source\repos\SpiritWMSApiCore2\SpiritWMSApiCore2.csproj'.
info : PackageReference for package 'ErikEJ.EntityFrameworkCore.SqlServer.DateOnlyTimeOnly' version '7.0.6' updated in file 'C:\Users\WYeager\source\repos\SpiritWMSApiCore2\SpiritWMSApiCore2.csproj'.
info : Assets file has not changed. Skipping assets file writing. Path: C:\Users\WYeager\source\repos\SpiritWMSApiCore2\obj\project.assets.json
log  : Restored C:\Users\WYeager\source\repos\SpiritWMSApiCore2\SpiritWMSApiCore2.csproj (in 338 ms).

**Comment by ErikEJ** [comment]
You need to enable DateOnly time mapping option as documented.

**Comment by wsyeager** [comment]
> You need to enable DateOnly time mapping option as documented.

Got it... Thanks so much for your patience Erik... Once I get squared away, I'm going to give a great review on your tools...
builder.Services.AddDbContext<SIRISContext>(
        options => options.UseSqlServer(builder.Configuration.GetConnectionString("SirisContext"), x => x.UseDateOnlyTimeOnly()));
