### ISSUE TITLE
Lastest Version Throws Exception: Microsoft.Data.SqlClient

### ISSUE THREAD

**Issue by POET-Jesse-Jones** [ErikEJ/EFCorePowerTools#2048]
Bug Report

NOTICE: A bug report without sufficient technical and repro details and version information WILL BE CLOSED WITHOUT ANY FURTHER ACTION.

### Provide steps to reproduce a bug

**Using VS2022 17.8.3**
<img width="204" alt="image" src="https://github.com/ErikEJ/EFCorePowerTools/assets/83102926/4e89dfef-548c-4526-a45a-0c5def9b3cb0">

**Working with a .Net 6.0 Project → Right Click > Reverse Engineer**
<img width="418" alt="image" src="https://github.com/ErikEJ/EFCorePowerTools/assets/83102926/0609b2c5-f379-4275-b6a4-f2b0c82bdb76">

**Choosing to Add Database Connection**
<img width="362" alt="image" src="https://github.com/ErikEJ/EFCorePowerTools/assets/83102926/fdfb6edc-8e68-4710-8d0b-de78102f09ca">

**Clicking the 'Add Database Connection' in the above screenshot immediately throws the following error**
<img width="428" alt="image" src="https://github.com/ErikEJ/EFCorePowerTools/assets/83102926/bcb67679-c48d-4682-80d4-7a7e3fc94721">

**The Project has Microsoft.Data.SqlClient 5.1.2**
<img width="280" alt="image" src="https://github.com/ErikEJ/EFCorePowerTools/assets/83102926/2f699da2-b14f-4f2c-962c-5cd9d0fb3163">

### Provide technical details

- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
**Version 2.5.1707**

- Exact Visual Studio version: (e.g. Visual Studio 2022 17.6.5)
**VS2022 17.8.3**

- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)
**SQL Server**

- EF Core version in use: (e.g. EF Core 7)
**EF Core 7** (7.0.13)
<img width="206" alt="image" src="https://github.com/ErikEJ/EFCorePowerTools/assets/83102926/0616e98c-504e-4d8c-8e38-e6e326c37716">

- Is Handlebars templates used: no/yes
**No**

- Is T4 templates used: no/yes
**No**
- Is a SQL Server .dacpac used: no/yes
**No**

**Comment by ErikEJ** [comment]
Looks like VS cannot find the dll (what you use in your project is not relevant here).

Can you create a connection via Server Explorer? If not, run a VS repair

**Comment by POET-Jesse-Jones** [comment]
After running VS Repair everything is working as expected. The issue did seem to be VS2022 as I was not able to connect using Server Explorer until after the VS Repair.

Closing Issue - Thanks!

**Comment by POET-Jesse-Jones** [comment]
After running VS Repair everything is working as expected. The issue did seem to be VS2022 as I was not able to connect using Server Explorer until after the VS Repair.

Closing Issue - Thanks!
