### ISSUE TITLE
Reverse Engineering does not work with Oracle database

### ISSUE THREAD

**Issue by tapeshmehta227** [ErikEJ/EFCorePowerTools#2049]
Reverse Engineering does not work with oracle database. The connection is established fine

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/1623585/26b95f5d-e1d5-44eb-883c-5f656fcd1171)

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/1623585/ae68183d-751b-4333-8ff5-019e1baca2fe)
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/1623585/34d30374-7f5c-451b-863e-47929115ba71)

Once we click OK we get the below dialog box:

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/1623585/0ea941a1-975f-4738-ab5b-11a45989e785)

Tools used: 

Visual Studio 2022 17.8.2, 
EF Core Power Tools 2.5.1707, 
SQL Developer 21.4.3, 
EF Core version 8

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

**Comment by tapeshmehta227** [comment]
Thanks for the quick reply. I downloaded and installed the latest build but now it gives a different error in the Extensions Output window

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/1623585/ad29eb5a-ec84-410e-b39b-14ee4e0cdc54)

Please let me know. Thank you.

**Comment by ErikEJ** [comment]
You have a borken connection is Server Explorer, open it and clean them up.

**Comment by tapeshmehta227** [comment]
Server Explorer had connection to other databases I deleted all of them and have just one now but get this error of access denied:

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/1623585/10034856-e477-42db-85a7-e7b39a396b8e)

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/1623585/06c896d7-5f7b-470c-8e90-f5edd7cfe8e9)

Please let me know.

**Comment by ErikEJ** [comment]
Wow, this is an uphill battle!

Looks like a virus scanner or similar is fighting file deletions.

Try again, or manually delete your %temp%\efreveng*.* folders

**Comment by tapeshmehta227** [comment]
Thanks I was unable to delete the file manually as well! 

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/1623585/82f240c6-fafb-44e6-9d2f-b689b57b0da8)
I went to Task Manager and terminated all .Net host manually then deleted the folder you advised.

Started VS and ran it again now it was stuck at this screen:

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/1623585/2e30211a-2c4f-47ac-b3af-99d91a7a809f)

and after 15-20 seconds I get this screen:

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/1623585/a76bcd57-634a-4df8-bc8c-9c30adee8f04)

But nothing happens the next dialog box doesn't come up. Neither does any error show up.

Please let me know. We're getting close I think!

**Comment by ErikEJ** [comment]
Hard to tell - Have you checked the extensions Output window for messages?

**Comment by tapeshmehta227** [comment]
The extensions option was not available this time perhaps because nothing got printed anywhere:

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/1623585/e57bd6f3-3417-4b5e-9436-f41422e5fbcd)

**Comment by tapeshmehta227** [comment]
I also created a console application in .Net 7 this time and tried to use EF core power tools with EF Core 7 but still the same issue. It just gets stuck:

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/1623585/e5c46e54-81de-4f08-8ec8-3c063c50bb9f)

But when I click the chat button it says no background task running yet it keeps showing Loading database objects:

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/1623585/f6f02d0d-b5ae-4559-892c-16392f290f21)

**Comment by ErikEJ** [comment]
No idea - is it a large database?

You could also try the command line edition, to see if you get any error messages (I have just published build 8.0.1718 with Oracle support)

**Comment by tapeshmehta227** [comment]
Yes it is a large database. Let me try cli and I will the post in some time.

**Comment by ErikEJ** [comment]
Maybe you need longer connection/command timeouts

**Comment by tapeshmehta227** [comment]
Actually only number of Views are more around 100. Tables are around 50 only. It does open pretty fast in SQL Developer GUI tool but with CLI it is waiting there since 5 minutes

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/1623585/59d7c40f-7234-491c-bb19-765e98724bc0)

It's just stuck here nothing is happening. I will let it run for few more minutes.

**Comment by ErikEJ** [comment]
It is most likely a bug in the Oracle provider, I cannot help you with this, sorry.

**Comment by ErikEJ** [comment]
@alexkeh FYI

**Comment by ErikEJ** [comment]
@tapeshmehta227 What if you try with the EF Core 6 or 7 version of the code generation in VS?

**Comment by tapeshmehta227** [comment]
Hi @ErikEJ yeah I tried that already and it did not work. Interesting scaffold dbcontext CLI does work with -tables option. I generated about 30 tables and it worked although it took around 6 minutes. Without tables it simply won't work. It hangs.

Here is the scaffold dbcontext command that worked:

Scaffold-DbContext "User Id=myuserid;Password=mypassword;Data Source=myip:1521/FAMOUS;" -OutputDir Models\Famous -Context FamousContext -Tables V_DW_COMPANY,V_DW_LOGISTICSLOADHEADER_106,V_DW_LOGISTICSLOADHEADER_13,V_DW_LOGISTICSLOADHEADER_134,V_DW_LOGISTICSLOADHEADER_152,V_DW_LOGISTICSLOADHEADER_174,V_DW_LOGISTICSLOADHEADER_2,V_DW_LOGISTICSLOADHEADER_74,V_DW_LOGISTICSLOADHEADER_78,V_DW_LOGISTICSLOADHEADER_86,V_DW_LOGISTICSLOADHEADER_88,V_DW_LOGISTICSLOADHEADER_92,V_DW_LOGISTICSLOADHEADER,V_DW_LOGISTICSLOADHEADER_144,V_DW_LOGISTICSLOADCUSTOMERS,V_DW_LOGISTICSLOADDROP,V_DW_LOGISTICSSHIP,V_DW_LOGISTICSSHIP_NOT_LLC,V_DW_TPS_MACROPOINT,V_DW_TPS_SONOLOADS,V_DW_TPS_MACROPOINT_NEW,V_DW_LOGISTICSLOADHDR_144_NEW,V_DW_TPS_LOADPUANDPONUMBER,TPS_EMAILGROUP,V_DW_TPS_ARAPMERGE_144 Oracle.EntityFrameworkCore -force -UseDatabaseNames

So for now I am ok. But I think the issue is with EF core power tools otherwise even scaffold dbcontext would not have worked. Shall I try this with CLI version of EF Core Power Tools?

**Comment by ErikEJ** [comment]
Try scaffold-dbcontext without specifying tables, it will be similar to what Power Tools does to get the list of all objects.

**Comment by ErikEJ** [comment]
And it should never take 6 minutes, som something is broken in the provider query.

**Comment by tapeshmehta227** [comment]
Yeah that's correct. Without tables parameter it just hangs similar to EF Core Power Tools.

**Comment by ErikEJ** [comment]
Closing as this is an external Oracle issue

**Comment by alexkeh** [comment]
@tapeshmehta227 Most likely, the EF Core Power Tools is not hung, it's waiting for some SQL to finish processing. 

If you use scaffold-dbcontext with the verbose flag (-Verbose), it will generate a trace file to tell which scaffolding operations are taking a long time. Run the scaffold with the verbose flag until it completes. You can send Oracle the trace, dotnet_us(at)oracle.com, We'll see what improvements can be made to the generated SQL.
