### ISSUE TITLE
FMTONLY SP wiki suggestion

### ISSUE THREAD

**Issue by anatoliy-savchak** [ErikEJ/EFCorePowerTools#2050]
Feature proposal to add wiki workaround for expected no result stored procedures reverse engineering issues (SQL Server only).

`if not exists(select sessionproperty('fmtonly')) begin set fmtonly off; return; end`

The EF Core will not always determine if SP should not return any resultset, especially when dynamic SQL is involved. As workaround the statement above will make EFCorePowerTools execution with set fmtonly on to receive desired outcome.

One should keep in mind that select sessionproperty('fmtonly') will have no results only if fmtonly is on. Thus the exists statement.

**Comment by ErikEJ** [comment]
Could you orovide a more complete example?

**Comment by anatoliy-savchak** [comment]
Having this SP in SQL Server:
```
create or alter procedure test(@name varchar(64))
as begin
	-- workaround: if not exists(select sessionproperty('fmtonly')) begin set fmtonly off; return; end
	declare @dsql nvarchar(max) = concat('set @outname = (select top 1 t.TABLE_NAME from INFORMATION_SCHEMA.', @name,' t)');

	declare @outname nvarchar(max);
	exec sp_executesql @dsql, @params = N'@outname nvarchar(max) output', @outname = @outname output;
	
	print @outname
end
go

exec test 'TABLES'

```
Action of EFCorePowerTools.ReverseEngineer with this SP will fail with:
Unable to get result set shape for procedure 'test'. Invalid object name 'INFORMATION_SCHEMA.t'..

**Comment by ErikEJ** [comment]
What if you use sp_describe_first_resultset?

**Comment by ErikEJ** [comment]
OK, I just tested using sp_describe_first_resultset, same issue (a warning and empty result set class is produced)

I have attempted to update the docs, let me know what you think:

https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#sql-server-stored-procedures

**Comment by anatoliy-savchak** [comment]
Awesome, thanks!!
