### ISSUE TITLE
ValueGeneratedOnAdd( ) problem with Oracle Database

### ISSUE THREAD

**Issue by akeck** [ErikEJ/EFCorePowerTools#2054]
Hello,

whenever I reverse engineer tables in our (3rd party) Oracle database, I have the same problem:

"The properties x,y,z... are configured to use 'Identity' value generator and are mapped to the same table . Only one column per table can be configured as 'Identity'"

Can you add an option to disable adding ValueGeneratedOnAdd( ) to the generated context class?
Every time, I have to add a table to a context, I have to remove all occurrences.
Searching for the problem I found that I'm not the only one with this problem.
An option to disable this would be extremely helpful.

**Comment by ErikEJ** [comment]
@akeck It sounds like an issue that should be addressed with Oracle support - assume it is the  same issue if you use the standard command line tools?

**Comment by akeck** [comment]
Yes, it's the same problem with the command line tools.
From what I understand, it's not a problem of Oracle, but with the database structure.

See this article: [https://forums.oracle.com/ords/apexds/post/problem-scaffolding-oracledb-using-entityframeworkcore-9083](url)
I found countless other articles of people with this problem. The recommendation was always to remove ValueGeneratedOnAdd( ) from the generated code.

Since it's an 3rd party database, we read data from (our ERP system), I have to deal with what I have.
So I was hoping, that this would be a small change.

**Comment by ErikEJ** [comment]
OK! Could you add more details on the fix your are proposing?

(I.e. generated code before and after the fix)

If I create a fix I also need your commitment to assist with testing!

**Comment by akeck** [comment]
This is a sample snipped of the generated code:
-------------------------------------------
        modelBuilder.Entity<ACP_S_FIRM2>(entity =>
        {
            entity.HasKey(e => new { e.FIRM_NR, e.FIRM2_FILIAL_NR, e.FIRM2_SPRACH_CD }).HasName("SYS_C0017931");

            entity.Property(e => e.FIRM_NR)
                .HasMaxLength(3)
                .IsUnicode(false)
                **.ValueGeneratedOnAdd();**
            entity.Property(e => e.FIRM2_FILIAL_NR)
                .HasMaxLength(3)
                **.IsUnicode(false)**
                .ValueGeneratedOnAdd();
 ...
-------------------------------------------

And that's what it looks after my search and replace:
-------------------------------------------
        modelBuilder.Entity<ACP_S_FIRM2>(entity =>
        {
            entity.HasKey(e => new { e.FIRM_NR, e.FIRM2_FILIAL_NR, e.FIRM2_SPRACH_CD }).HasName("SYS_C0017931");

            entity.Property(e => e.FIRM_NR)
                .HasMaxLength(3)
                .IsUnicode(false)
                ;
            entity.Property(e => e.FIRM2_FILIAL_NR)
                .HasMaxLength(3)
                .IsUnicode(false)
                ;
...
-------------------------------------------

I can of course help you with testing, no problem!

**Comment by ErikEJ** [comment]
So "ValueGeneratedOnAdd()" should not be used anywhere when working with Oracle??

**Comment by akeck** [comment]
From what I understand, the problem only appears when the database design is bad, so excluding it should be optional and by default, it should behave as it is now.
But if this option is enabled, it should completely be removed.
As far as I know, the problem occurs only with bad designed Oracle databases, so other DBMS shouldn't have this issue.

**Comment by ErikEJ** [comment]
@akeck 

I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

`   "RemoveValueGeneratedOnAdd": false,`

**Comment by ErikEJ** [comment]
@akeck Build .1725 or later...

**Comment by akeck** [comment]
Working great, thank you! 
I of course not only tool a look on the generated code, but also did a few tests on the database.
Everything working fine now!

Thank you for the fast help!

**Comment by ErikEJ** [comment]
If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
