### ISSUE TITLE
No longer when NOT NULL bit field with default value of 1

### ISSUE THREAD

**Issue by dmcerlean** [ErikEJ/EFCorePowerTools#2057]
Steps to reproduce

In SQL Server, create a table which contains a BIT NOT NULL field. Assign a default value of 1 and save the table.

Then, generate the model in Visual Studio (reverse engineer).

Current result

The BIT field is created as a **NON** nullable bool type (bool ?).

This used to be a feature not a bug. but now it no longer makes the bit nullable  [required] 

Expected result

The BIT field should become a nullable bool type (bool ?).

Technical details

EF Core Power Tools version: 2.5.1707

Exact Visual Studio version: Microsoft Visual Studio Community 2022 (64 bits) - Current Version 17.8.2

Database engine: SQL Server

EF Core version in use: EF Core 8.0.0

Is Handlebars templates used: no

Is T4 templates used: no

Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
@dmcerlean >> This used to be a feature not a bug. but now it no longer makes the bit nullable [required]

Assume you are referring to pre EF Core 8 days?

I believe this is now by design - @ajcvickers ?

**Comment by dmcerlean** [comment]
yes, we are now using core 8 and    "CodeGenerationMode": 4,

core 7 :
    [Required]
    public bool? Active { get; set; }

 core 8 :
   public bool Active { get; set; }

**Comment by ErikEJ** [comment]
It is a new feature in EF Core 8: 

https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-8.0/whatsnew#database-defaults-for-booleans
