### ISSUE TITLE
efpt.renaming.json Totally Ignored

### ISSUE THREAD

**Issue by CorsairRO** [ErikEJ/EFCorePowerTools#2058]
Hello,

I have discovered that from some point in time, i dont remember exactly when, the Table/Column Renaming option has just silently stopped working

I have tried ALL the options until now and combination of:
- UseT4 / Not Use T4
- Use HandleBars / NotUse
- UseDatabaseNames / Not use them

0) I have scratched my head to make it work.
1) As you know from before i have forked your tool to my VS here and i am maintaining it locally for my personal use, by removing ALL the things that you work hard to maintain there. Literally i want ONLY RevEng, Not any CLI and stuff, and Always on SQL Server and Always on .NET8 for example. 

2) First suspicion that i had there was the file is not loaded correctly. And indeed it was not.
Issue found in CustomNameOptionsExtensions => customNamingOptions is null there and returned null
using ( var ms = new MemoryStream( Encoding.UTF8.GetBytes( File.ReadAllText( optionsCustomNamePath , Encoding.UTF8 ) ) ) ) {
	var ser = new DataContractJsonSerializer( typeof( List<Schema> ) );
	var customNamingOptions = ser.ReadObject( ms ) as List<Schema>;
	return new Tuple<List<Schema> , string>( customNamingOptions , optionsCustomNamePath );
}

If i replace it with plain Newtonsoft.Json it returns fine the deserialized content, as i debugged it and stepped through it.
var test = File.ReadAllText( optionsCustomNamePath , Encoding.UTF8 );
List<Schema> aResult = Newtonsoft.Json.JsonConvert.DeserializeObject<List<Schema>>( test );
return new Tuple<List<Schema> , string>( aResult , optionsCustomNamePath );

I dont know what to do further on as it seems it is NOT so easy to test the Reveng.Core because it is run by the console app ( thank you microsoft for your stupid ideas to remove totally support in VS for EF )

Thank you very much as always for your GREAT effort to maintain such a nice and useful tool

### Provide steps to reproduce a bug
Example of epft.renaming.json
[
    {
        "UseSchemaName": false,
        "SchemaName": "dbo",
        "Tables": [
            {
                "Name": "manufacturer",
                "NewName": "Mymanufacturer",
                "Columns": [
                    {
                        "Name": "Manufacturer",
                        "NewName": "ManufacturerName"
                    },
                    {
                        "Name": "Manufacturer1",
                        "NewName": "ManufacturerName"
                    }
                ]
            },
            {
                "Name": "MySP_Result",
                "NewName": "TestResult"
            }

        ]
    }
]

### Provide technical details

- EF Core Power Tools version: Latest

- Exact Visual Studio version: (e.g. Visual Studio 2022 17.8.3)

- Database engine: SQL Server

- EF Core version in use: (e.g. EF Core 8)

- Is Handlebars templates used: no

- Is T4 templates used: yes

- Is a SQL Server .dacpac used: no

**Comment by CorsairRO** [comment]
Hehe, thank you for that, sorry, what i meant is debugging, not testing.

I know that the command line works to be tested separatedly, and this is nice. 
But because the command line is Published exe and called by VSIX, debugging code in RevEng.Core from Visual Studio VSIX Extension is not working, and it makes sense, as it just do some delegation to the command line Program.cs to do stuff.

Sorry for my wrong terms there.
Thank you again for your fast answers always.

I think at some point in time it was working ok, as i was doing lots of tests before having the courage to even think to move edmx to ef core. 
But now it just silently doing nothing, just ignoring the rename file.
I thouhgt i was stupid removing something from there, but like i said ( basically this is why i sent this issue here ) it happens also in the current published version of the VSIX from Marketplace.

**Comment by ErikEJ** [comment]
Please share your actual renaming file (zipped for example)  and I will have a look. Debugging is a simple/easy as testing!

**Comment by CorsairRO** [comment]
Hello,
I have added 10 tables and different columns trying to see if it has anything to do with the data in my DB.
It doesnt, it just silently ignores ALL the entities. 

I just took the example found here: https://erikej.github.io/efcore/2020/09/07/ef-core-power-tools-renaming-advanced.html
And modified the table name to 1 of my tables on 2 columns.
NewName is NOT set to Table OR to any of the columns, this is why i concluded it is somehow ignored.

I tried that in 10 different tables to be sure it is not coming from my DB.

thank you

**Comment by ErikEJ** [comment]
Show me the money, otherwise I cannot help.

**Comment by CorsairRO** [comment]
Hello, ok, i have put the example in here as it is very small

CREATE TABLE dbo.manufacturer(
[ManufacturerId] [int] IDENTITY(1,1) NOT NULL,
[Manufacturer] [varchar](250) NOT NULL
)
ManufacturerId is the PK. DB is legacy one and i cannot change the columns or PK names there as it will disturb production apps.

Like i said, i happens to ANY table that i add there in renaming, this is why i said i suspect it is just ignoring.
Note: I use T4 to reveng the DB. I tried removing that from efpt.config.json thinking the T4 messes up, but same result. 

As usual, thank you for your replies, and for your effort to maintain an indispensible tool

efpt.renaming.json:
[
  {
    "UseSchemaName": false,
    "SchemaName": "dbo",
    "Tables": [
      {
        "Name": "manufacturer",
        "NewName": "MyManufacturer",
        "Columns": [
          {
            "Name": "Manufacturer", // This is the real column name in DB
            "NewName": "ManufacturerName1"
          },
          {
            "Name": "Manufacturer1", // This is the column name that EF translates to. I tried to put both to see
            "NewName": "ManufacturerName"
          }
        ]
      }
    ]
  }
}

**Comment by ErikEJ** [comment]
Please attach/zip the efpt.renaming.json file rather than pasting it.

**Comment by ErikEJ** [comment]
I am unable to repro with build .1726

**Comment by ErikEJ** [comment]
Ah, in your example the column and table name differs only in casing - that is an EF Core bug, that was only very recently resolved - see https://github.com/dotnet/efcore/issues/30237

**Comment by CorsairRO** [comment]
Hello,
ok, thank you, i got it for columns as the column differs in casing only from table name.
But what about the whole table?
Name = "manufacturer"
NewName = "MyManufacturer"
Why is that one ignored also?

**Comment by ErikEJ** [comment]
I will investigate when you share the actual file with me!

**Comment by CorsairRO** [comment]
OK, sorry for that, i forgot to upload it as you requested
[efpt.renaming.json](https://github.com/ErikEJ/EFCorePowerTools/files/13737384/efpt.renaming.json)

**Comment by ErikEJ** [comment]
Renaming works fine for me based on your file and schema (I removed the non-working column renamers)

```json
[
  {
    "UseSchemaName": false,
    "SchemaName": "dbo",
    "Tables": [
      {
        "Name": "manufacturer",
        "NewName": "MyManufacturer",
        "Columns": []
      },
      {
        "Name": "usp_app_lookup_AircraftInfoResult",
        "NewName": "MyTable"
      }
    ]
  }
]

```
