### ISSUE TITLE
How to generate missing coalesced fields from views

### ISSUE THREAD

**Issue by ocdaBilly** [ErikEJ/EFCorePowerTools#2059]
I'm currently on EF Core 7, and trying to reverse engineer database views from an older legacy project with coalesce fields that are not coming over and was wondering if I'm missing a configurable item or two.
I have the following structure: a code table, views into the code table, and table using those codes... 
for example:

CREATE VIEW ListPersons
  AS
SELECT 
[Persons].Id,
[Persons].LastName,
[Persons].FirstName,
[Persons].ComplexCode,
ListComplexionCodes.[Value] as Complexion,
[Persons].GenderCode,
ListGenderCodes.[Value] as Gender,
FROM [Persons] LEFT OUTER JOIN
		 ListComplexionCodes ON [Persons].ComplexCode = ListComplexionCodes.Code 
		 LEFT OUTER JOIN
		 ListGenderCodes ON [Persons].GenderCode = ListGenderCodes.Code

when I use reverse engineering, it comes back missing Complexion and Gender:

public partial class ListPerson
{
    public int Id { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string? LastName { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string? FirstName { get; set; }

    [StringLength(6)]
    [Unicode(false)]
    public string? ComplexCode { get; set; }

    [StringLength(6)]
    [Unicode(false)]
    public string? GenderCode { get; set; }
}

This also happens on a coalesced field... like:
CREATE VIEW ListCards 
  AS
SELECT 
[Persons].Id as PersonId, 
COALESCE([Cards].Id, 0) as CardId,
[Persons].LastName,
[Persons].FirstName,
[Cards].CardTypeCode,
ListCardTypeCodes.[Value] as CardType,
FROM [Persons] LEFT OUTER JOIN
     [Cards] on [Cards].PersonId = [Persons].Id LEFT OUTER JOIN
		ListCardTypeCodes ON [Cards].CardTypeCode = ListCardTypeCodes.Code 

would return a class that's missing the coalesced CardId as well as the CardType

public partial class ListCard
{
    public int PersonId { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string? LastName { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string? FirstName { get; set; }

    [StringLength(6)]
    [Unicode(false)]
    public string? CardTypeCode { get; set; }
}

the List[Field]Code views are of the type:
CREATE VIEW ListGenderCodes
	AS SELECT * FROM Codes
	where Category = 'gender'

And code table looks like this:
CREATE TABLE [Codes] (
    [Id]      INT           IDENTITY (1, 1) NOT NULL,
    [Category]    VARCHAR (40)  NOT NULL,
    [Code]        VARCHAR (6)   NOT NULL,
    [Value]       VARCHAR (255) NOT NULL,
    [ExpirationDate]    DATETIME NULL,
    [CreatedBy]           VARCHAR (25)    NOT NULL,
    [CreatedDate]           DATETIME        NOT NULL,
    [ModifiedBy]          VARCHAR (25)    NOT NULL,
    [ModifiedDate]          DATETIME        NOT NULL,
    CONSTRAINT [PK_Codes] PRIMARY KEY CLUSTERED ([Id] ASC)
);
GO
CREATE NONCLUSTERED INDEX [IX_Codes]
    ON [Codes]([Category] ASC, [Code] ASC);

[Edit to add: just an FYI, my workaround is to create a separate partial class to add the missing fields, but I was hoping to not have to repeatedly do this as there are a lot of views]

Thanks in advance

**Comment by ErikEJ** [comment]
.dacpac or from what??

**Comment by ErikEJ** [comment]
Maybe avoid SELECT * ?

**Comment by ocdaBilly** [comment]
> Maybe avoid SELECT * ?

If you're referring to 
CREATE VIEW ListGenderCodes
AS SELECT * FROM Codes
where Category = 'gender'

this is what is created: 
public partial class ListGenderCode
{
    public int Id { get; set; }

    [StringLength(40)]
    [Unicode(false)]
    public string Category { get; set; } = null!;

    [StringLength(6)]
    [Unicode(false)]
    public string Code { get; set; } = null!;

    [StringLength(255)]
    [Unicode(false)]
    public string Value { get; set; } = null!;

    [Column(TypeName = "datetime")]
    public DateTime? ExpirationDate { get; set; }

    [StringLength(25)]
    [Unicode(false)]
    public string CreatedBy { get; set; } = null!;

    [Column(TypeName = "datetime")]
    public DateTime CreatedDate { get; set; }

    [StringLength(25)]
    [Unicode(false)]
    public string ModifiedBy { get; set; } = null!;

    [Column(TypeName = "datetime")]
    public DateTime ModifiedDate { get; set; }
}


So it -can- reverse engineer the select * correctly, it seems.

**Comment by ErikEJ** [comment]
Are you using a .dacpac??

**Comment by ErikEJ** [comment]
I am going to close this, as none of the information requested for a new issue was supplied. Feel free to create a new issue with all the requested information supplied.

**Comment by ocdaBilly** [comment]
Dude, I don't work 24 hours, you asked 10 hours ago... closed already? really?


no, I'm not using a .dacpac.  

Did you even contemplate trying to create a view with a coalesce field and reverse engineering to see if you can replicate the issue I'm seeing? or are you not supporting this product.

**Comment by ErikEJ** [comment]
If you provide full repro scripts for all involved objects (tables and views) I will have a look. 

Yes, I support this free product for anyone willing to follow the simple issue guidelines.

**Comment by ocdaBilly** [comment]
the create view and create table scripts are in the original issue information... what else do I need to supply?

**Comment by ocdaBilly** [comment]
I stand corrected, I did not provide the card and person table snippets.   This should be close enough

CREATE TABLE [Persons] (
    [Id]              INT             IDENTITY (1, 1) NOT NULL,
[LastName] VARCHAR(50) NULL, 
[FirstName] VARCHAR(50) NULL, 
    [GenderCode]               VARCHAR(6)        NULL,
    [DescentCode]           VARCHAR (6)     NULL,
    [ComplexCode]           VARCHAR (6)     NULL,
    [ExpirationDate]    DATETIME NULL,
    [CreatedBy]           VARCHAR (25)    NOT NULL,
    [CreatedDate]           DATETIME        NOT NULL,
    [ModifiedBy]          VARCHAR (25)    NOT NULL,
    [ModifiedDate]          DATETIME        NOT NULL,
    CONSTRAINT [PK_Persons] PRIMARY KEY CLUSTERED ([Id] ASC)
);

CREATE TABLE [Cards]
(
    [Id] INT NOT NULL IDENTITY,
    [EffectiveDate]     DATETIME NULL,
    [ExpirationDate]    DATETIME NULL,
    [PersonId] INT NOT NULL,
    [CreatedBy]           VARCHAR (25)    NOT NULL,
    [CreatedDate]           DATETIME        NOT NULL,
    [ModifiedBy]          VARCHAR (25)    NOT NULL,
    [ModifiedDate]          DATETIME        NOT NULL,
    CONSTRAINT [PK_Cards] PRIMARY KEY ([Id]), 
    CONSTRAINT [FK_Card_ToPersons] FOREIGN KEY ([PersonId]) REFERENCES [Persons]([Id]))

**Comment by ErikEJ** [comment]
Thanks, I will have a look. Is this on Azure SQL or local SQL Server ?

**Comment by ocdaBilly** [comment]
local SQL Server 2022 Datacenter (10.0) Version 15.0.4345.5

I'm running VSEnterprise 2022 Version 17.7.6

NuGet says everything is updated to latest 7.0.13 versions (I'm not ready to go to 8 just yet)

**Comment by ErikEJ** [comment]
Please Update to latest version- .1718 - in order to get support.

**Comment by ocdaBilly** [comment]
updated to 1718.  same behavior.

I tried something with the joins, not sure if it'll help, but  here's what I've noticed 
assume the following in the select list:
          Complexions.[Value] as Complexion,

if I use:
		 LEFT OUTER JOIN 
		 Codes Complexions on Complexions.Code = [Persons].ComplexCode and Complexions.Category = 'complex' 

it will add the Complexion field in the c# object...

but if I change it back to:
		 LEFT OUTER JOIN 
		 ListComplexionCodes Complexions on Complexions.Code = [Persons].ComplexCode

it fails.   This is after I changed ListComplexionCodes to:

CREATE VIEW ListComplexionCodes
	AS SELECT
        [Id],
        [Category],
        [Code],
        [Value],
        [ExpirationDate]
	FROM Codes
	where Category = 'complex'


instead of select *

**Comment by ErikEJ** [comment]
I think it could be because the account you use does not have "view definition" rights. Check the Extensions output window for warnings.

**Comment by ocdaBilly** [comment]
i've got view definition rights.  extensions output window is empty after running EF refresh or EF Edit

**Comment by ErikEJ** [comment]
I am unable to repro 

(I do not have ListCardTypeCodes defintion, so unable to test that)

Having this schema:

```sql
CREATE TABLE [Persons] (
[Id] INT IDENTITY (1, 1) NOT NULL,
[LastName] VARCHAR(50) NULL,
[FirstName] VARCHAR(50) NULL,
[GenderCode] VARCHAR(6) NULL,
[DescentCode] VARCHAR (6) NULL,
[ComplexCode] VARCHAR (6) NULL,
[ExpirationDate] DATETIME NULL,
[CreatedBy] VARCHAR (25) NOT NULL,
[CreatedDate] DATETIME NOT NULL,
[ModifiedBy] VARCHAR (25) NOT NULL,
[ModifiedDate] DATETIME NOT NULL,
CONSTRAINT [PK_Persons] PRIMARY KEY CLUSTERED ([Id] ASC)
);

CREATE TABLE [Cards]
(
[Id] INT NOT NULL IDENTITY,
[EffectiveDate] DATETIME NULL,
[ExpirationDate] DATETIME NULL,
[PersonId] INT NOT NULL,
[CreatedBy] VARCHAR (25) NOT NULL,
[CreatedDate] DATETIME NOT NULL,
[ModifiedBy] VARCHAR (25) NOT NULL,
[ModifiedDate] DATETIME NOT NULL,
CONSTRAINT [PK_Cards] PRIMARY KEY ([Id]),
CONSTRAINT [FK_Card_ToPersons] FOREIGN KEY ([PersonId]) REFERENCES Persons)

CREATE TABLE [Codes] (
[Id] INT IDENTITY (1, 1) NOT NULL,
[Category] VARCHAR (40) NOT NULL,
[Code] VARCHAR (6) NOT NULL,
[Value] VARCHAR (255) NOT NULL,
[ExpirationDate] DATETIME NULL,
[CreatedBy] VARCHAR (25) NOT NULL,
[CreatedDate] DATETIME NOT NULL,
[ModifiedBy] VARCHAR (25) NOT NULL,
[ModifiedDate] DATETIME NOT NULL,
CONSTRAINT [PK_Codes] PRIMARY KEY CLUSTERED ([Id] ASC)
);
GO

CREATE NONCLUSTERED INDEX [IX_Codes]
ON [Codes]([Category] ASC, [Code] ASC);
GO


CREATE VIEW ListGenderCodes
AS SELECT * FROM Codes
where Category = 'gender'


CREATE VIEW ListComplexionCodes
AS SELECT
[Id],
[Category],
[Code],
[Value],
[ExpirationDate]
FROM Codes
where Category = 'complex'

CREATE VIEW ListPersons
AS
SELECT
[Persons].Id,
[Persons].LastName,
[Persons].FirstName,
[Persons].ComplexCode,
ListComplexionCodes.[Value] as Complexion,
[Persons].GenderCode,
ListGenderCodes.[Value] as Gender
FROM [Persons] LEFT OUTER JOIN
ListComplexionCodes ON [Persons].ComplexCode = ListComplexionCodes.Code
LEFT OUTER JOIN
ListGenderCodes ON [Persons].GenderCode = ListGenderCodes.Code

--CREATE VIEW ListCards
--AS
--SELECT
--[Persons].Id as PersonId,
--COALESCE([Cards].Id, 0) as CardId,
--[Persons].LastName,
--[Persons].FirstName,
--[Cards].CardTypeCode,
--ListCardTypeCodes.[Value] as CardType,
--FROM [Persons] LEFT OUTER JOIN
--[Cards] on [Cards].PersonId = [Persons].Id LEFT OUTER JOIN
--ListCardTypeCodes ON [Cards].CardTypeCode = ListCardTypeCodes.Code

```
I get this class with EF Core 7:

```csharp
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace net6.0.Models;

public partial class ListPerson
{
    public int Id { get; set; }

    public string? LastName { get; set; }

    public string? FirstName { get; set; }

    public string? ComplexCode { get; set; }

    public string? Complexion { get; set; }

    public string? GenderCode { get; set; }

    public string? Gender { get; set; }
}
```

**Comment by ocdaBilly** [comment]
That's strange... I notice your output doesn't have the data annotations but mine does...
[StringLength(50)]
[Unicode(false)]
public string? LastName { get; set; }

[StringLength(50)]
[Unicode(false)]
public string? FirstName { get; set; }

I'm not at work, so I can test if turning off data annotations would make a difference... I'll check on Wednesday when I have access.

Here's the code for the ListCardTypesCode view, sorry I left that out.

CREATE VIEW ListCardTypesCode 
AS SELECT
[Id],
[Category],
[Code],
[Value],
[ExpirationDate]
FROM Codes
where Category = 'cardtypes'

**Comment by ErikEJ** [comment]
With Data Annotations:

```csharp
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace net6.0.Models;

[Keyless]
public partial class ListPerson
{
    public int Id { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string? LastName { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string? FirstName { get; set; }

    [StringLength(6)]
    [Unicode(false)]
    public string? ComplexCode { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string? Complexion { get; set; }

    [StringLength(6)]
    [Unicode(false)]
    public string? GenderCode { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string? Gender { get; set; }
}

```

**Comment by ocdaBilly** [comment]
Thank you for looking into this.  Since you can't repro this on your end but it's happening on mine, let's close this for now unless someone else has the same issues and can provide additional point of reference.
