### ISSUE TITLE
EF Core Powertool does not recognize field from stored procedure result

### ISSUE THREAD

**Issue by ngamanning** [ErikEJ/EFCorePowerTools#2061]
My SQL stored procedure returns following schema :
ROW_NUMBER() OVER (ORDER BY m.ClientNumber, m.MatterNumber) AS ID
Name Varchar(max) 

It was working fine and the C# model was generated with ID field as property correctly, before I updated EFCore Power Tool using Visual Studio Extensions.
Now, out of nowhere the property ID is missing from the generated C# model, and when I added in using Partial implementation, I get error "System.InvalidOperationException: The required column 'ID' was not present in the results of a 'FromSql' operation.". 

###  technical details

- EF Core Power Tools version: 2.5.1718

- Exact Visual Studio version: Visual Studio Enterprise 2022 (Version 17.8.3)

- Database engine: SQL Server

- EF Core version in use: EF Core 8.0

- Is Handlebars templates used: no

- Is T4 templates used: no

- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
Did you also switch EF Core version?

**Comment by ErikEJ** [comment]
Please provide complete SQL scripts for a repro and I will have a look...

**Comment by ErikEJ** [comment]
@ngamanning  Ping?

**Comment by ngamanning** [comment]
[scripts.txt](https://github.com/ErikEJ/EFCorePowerTools/files/13780517/scripts.txt)
@ErikEJ script attached.

**Comment by ngamanning** [comment]
Well, the error magically disappears this morning. I think I might have needed to reboot my computer after the EFCore Power Tool installation to get it to work.
