### ISSUE TITLE
[Feature] DbContextExtensions in EF8 do not require existing DbSets

### ISSUE THREAD

**Issue by CorsairRO** [ErikEJ/EFCorePowerTools#2062]
Hello,

Just a suggestion, to adapt the DbContextExtensions SqlQueryAsync method to not require DbSets anymore as EF Core 8 says that it is working without.
I have changed it in my stripped version and it works fine, i REMOVED 100 DbSets created for nothing there cluterring my context.

My changes to the code ( commented is the previous way )

```csharp
if ( typeof( T ).GetProperties( ).Any( ) ) {
	//return await db.Set<T>().FromSqlRaw(sql, parameters).ToListAsync(cancellationToken);
	return await db.Database
		.SqlQueryRaw<T>( sql , parameters )
		.ToListAsync( cancellationToken );
}

```

Made it after checking EF8 Documentation: [(https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-8.0/whatsnew#raw-sql-queries-for-unmapped-types)]

Otherwise, thank you again for your effort making such a nice tool, hope you had a nice and peaceful Christmas with your family, wish a better New Year 2024.

### Provide steps to reproduce a bug

Please include a **complete** description of the issue or link to a project that I can run to reproduce the issue.

### Provide technical details

- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)

- Exact Visual Studio version: (e.g. Visual Studio 2022 17.6.5)

- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)

- EF Core version in use: (e.g. EF Core 7)

- Is Handlebars templates used: no/yes

- Is T4 templates used: no/yes

- Is a SQL Server .dacpac used: no/yes

**Comment by ErikEJ** [comment]
So have a EF Core 8 version of DbContextExtensions, and this avoids adding DbSets to the stored procedure partial DbContext?

**Comment by CorsairRO** [comment]
I dont know how you want/plan to integrate there in the tool as you want to be very backwards compatible in EF/.NET Versions
As i am always using EF8 on .NET8 now in my version i have just did that change and it is working fine.
Thank you

**Comment by ErikEJ** [comment]
Thanks for the suggestion, I encountered what I think is an EF Core bug while imlementing, so postponing for now:

https://github.com/dotnet/efcore/issues/32680

**Comment by CorsairRO** [comment]
Sorry for the late reply here, and Happy New Year 2024

1) The model was working fine without DbSets for mapping SP results. It becomes messed up and doesnt work anymore as soon as i have added the first TVF to the Model.

2) No matter what i do it just doesnt want to work anymore.
I have even created a fake DbSet<MyTVF_Result> ( thinking it should work similar to SP)  , make sure that HasNoKey is set to it and called the previous way for functions, with DbSet<T> ...
In DbContextExtensions I have added an if sql.StartsWith("EXEC") call new way, else call old way.

3) The error occurs when calling ANY SP from the model, therefore i can confirm it is something internal in EF Core like i could see in the discussion you had there with ajvickers from ef team.
Removing TVF from model makes it work again.

We hope that this will be fixed in the next update of EF 8 as i have just got rid of the unnecesarry DbSets for SP that are not needed and just cluterring my already complex model

thank you for the nice tool,
have a nice day there.

**Comment by ErikEJ** [comment]
@CorsairRO Correct, as stated above this is an EF Core bug, that I think is being fixed for EF Core 8.0.3 (or maybe 8.0.2)

**Comment by ErikEJ** [comment]
@CorsairRO 
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

**Comment by CorsairRO** [comment]
@ErikEJ I didnt test the latest daily build, BUT...
As soon as i have seen EF Core 8.0.2 i have added function to my simplified tool and it works fine.

**Comment by ErikEJ** [comment]
@CorsairRO How is your simplified tool better than the vanilla product?

**Comment by CorsairRO** [comment]
Well...
0) I am always updating the tool to use latest .NET8 and latest  EF Core. I dont care to support old versions at all.
This simplifies a lot the project.
1) I have erased all the unwanted features except RevEng.
2) I have adapted it to checkout files in DevOps TFS before trying to generate objects
3) I have REMOVED all the options from reveng, just using the same hardcoded in all my projects ( keep table names, not using NODA and other stuff from there ). 
4) I removed the graphical tool and just manually edit the .config.json, much faster
5) As my apps are always WPF or MAUI ,all my objects ( INCLUDING the ones coming from SP ) i make them OBSERVABLE : INPC
and validatabale : INotifyDataErrorChanged
The T4 gave me the option for doing that for tables and views but NOT for resultsets coming from SP.
6) I did lots of optimizations there not to write the files if not changed
7) DbContextExtensions i store them in the root of my data project so that all DbContexts use the exact same.
8) Because my projects have 1000+ tables i have added an option in json to put the files in namespaces inside the same project ( this also adds them to FOLDERS inside the project when generating ) so that when i add partial classes they go in natural namespace not having to remove/add/adjust namespaces.
9) Still because of 1000+ tables i REMOVED all automatic FK from T4, and i manually add them where i need to run queries with .Include
10) I always use SQl Server, therefore removed all unwanted db options/providers including Not using DatabaseProject for that.
I dont remember now other customizations, but now i can adapt easily my subset of tools for my needs easily.

Also because as you know i am NOT familiar at ALL with GIT Source COntrol, i am using TFS for 20+ years now, i was lazy and trying to not go into that path. Anyway for my company i dont see any sense in that GIT.
If i have a solution with 20 projects i dont see any point in creating a branch of all of them just to add a property in a database class from a table and then have to go to all flows there like PR/Commits and so on.
I checkout EXCLUSIVELY files and the same goes for my team and GIT canniot have that. I have investigated.

**Comment by CorsairRO** [comment]
Therefore i wouldnt say at all it is much better.
It is just more suitable for my daily needs and also easy to customize more it i want.
Anyway, thank you for your effort in maintaining an indispensible tool for developping real applications, not the crap they MS markets all day long with Code First. This approach of them is just a BAD joke
