### ISSUE TITLE
Allow Stored Procedure to be flagged as single result instead of 'List'

### ISSUE THREAD

**Issue by zaceverett** [ErikEJ/EFCorePowerTools#2067]
If I have a Stored Procedure that returns data via a 'Select' but it will only ever return a single row. EG selecting a row from a table specifying a 'Where' on the primary key.

I would like to be able to 'Flag' this SP, perhaps in efpt.config.json and then reverse engineer to produce code to return a single result instead of the default` Task<List<Result>>` may be just `Task<Result>`.

**Comment by ErikEJ** [comment]
So it retrun no result set at all? Then see the docs: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#sql-server-stored-procedures

**Comment by zaceverett** [comment]
Sorry Erik, original comment hid some of the code.

The SP would still return a result set but would always just be a single row eg

SELECT OrderId, CustomerName, OrderDate FROM Orders WHERE OrderId = 1

This would always return a single row result set, so ideally i'd like to be able to flag this fact so the scaffolding code would create code like `Task<Result>` instead of `Task<List<Result>>`

I'm not sure if this is even possible and may be something where I have to roll my own Stored Procedure call etc.

**Comment by ErikEJ** [comment]
So the current situation is that the code works, but you dislike the method signature? 

Maybe you could just add a method with a nicer signature in a partial class?

**Comment by ErikEJ** [comment]
@zaceverett Ping?
