### ISSUE TITLE
How to handle databases made up from multiple dacpacs?

### ISSUE THREAD

**Issue by westy** [ErikEJ/EFCorePowerTools#2069]
Hi Erik,

Looking to start our migration from .NET Framework to .NET this year, and one of the first steps I wanted to do is figure out what I'm going to do about data access.
Using EF Core seems like the obvious, and standard answer, rather than trying to port our existing database access code libraries.

I have played around with your EF Core Power Tools before, to point at an existing database, and it works well.
This is not where I really want to be though.

Our product databases use dacpacs from multiple database projects, that ultimately produce dacpacs.

We have a shared "common" framework that has a database project containing tables, views and sprocs, and then another shared database project that contains access management tables, views and sprocs. We then generally have another database project for a specific product that builds on top of the other two, adding more tables, views and sprocs. All are deployed "as one" though, rather than separate databases.

I want to end up, ideally, with a class library for each of these database projects that contain models for that dacpac.
Easy enough I thought, I have generated models for the lowest level without issue.
When I try for the next level up, that builds on top of the lower level, I get issues though.

It manifests as the following, but I suspect that this is just the first error, and is a symptom of it not having the sequences defined in the base project, but I suspect there are many other issues queued up after this one:
`EF Core Power Tools
Table list error:
System.InvalidOperationException: Sequence contains no elements at void
System.Linq.ThrowHelper.ThrowNoElementsException0
at Source
System.Linq.Enumerable.First<TSource> (lEnumerable<TSourc e> source) at void
ErikEJ.EntityFrameworkCore.Sq/Server.Scaffolding.Sq/ServerDa cacDatabaseModelFactory.GetForeignKeys(TSqITable table,
DatabaseModel dbModel) +(DatabaseTable t) => (} in C:/Code/Github/EFCorePowerTools/src/GUl/ErikEJ.EntityFrame
workCore.SqlServer.Dacpac/Scaffolding/SqlServerDacpacData
baseModelFactory.cs:line 235
at Source
System.Linq.Enumerable.TryGetSingle<TSource> (lEnumerable
‹TSource> source, Func<TSource, bool> predicate, out bool found)
at TSource
System.Linq.Enumerable.SingleOrDefault< TSource>(IEnumera
ble< TSource> source, Func<TSource, bool> predicate)| at void
ErikEJ.EntityFrameworkCore.Sq/Server.Scaffolding.SqlServerDa
cpacDatabaseModelFactory.GetForeignKeysTSqITable table,
DatabaseModel dbModel) in
C:/Code/Github/EFCorePowerTools/src/GUl/ErikEJ.EntityFrame
workCore.SqlServer.Dacpac/Scaffolding/SqlServerDacpacData
baseModelFactory.cs: line 234
at DatabaseModel
ErikEJ.EntityFrameworkCore.SqlServer.Scaffolding.Sq|ServerDa
cpacDatabaseModelFactory.Create(string connectionString, DatabaseModelFactoryOptions options) in
C:/Code/Github/EFCorePowerTools/src/GUl/ErikEJ.EntityFrame
workCore.Sq/Server.Dacpac/Scaffolding/Sq|ServerDacpacData baseModelFactory.cs:line 138
at List< DatabaseTable>
RevEng.Core.TableListBuilder.GetTableDefinitions in
C:/Code/Github/EFCorePowerTools/src/GUl/RevEng.Core.60/Ta bielistBuilder.cs:line 115
at List< TableModel >
RevEng.Core.TableListBuilder.GetTableModels0 in
C:/Code/Github/EFCorePowerTools/src/GUl/RevEng.Core.60/Ta bielistBuilder.cs:line 41
at async Task<int> EfReveng.Program.Main(string] args) in C:/Code/Github/EFCorePowerTools/src/GUl/efreveng60/Progra m.cs:line 53
`

I'm wondering if this is something you have tried, and whether you have any suggestions on an approach.

One thought occurs to me, in that I generate for the database, and then try and split by hand, but not sure how the projects would then work together.
Any ideas of suggestions you may have gratefully received!

Oh, and Happy New Year!

Cheers,
Westy

**Comment by ErikEJ** [comment]
Have you tried the "merge dacpacs" option?

**Comment by westy** [comment]
Hi Erik,

Thanks for getting back to me. That does indeed allow the dacpac from the middle of the stack to be loaded without displaying that error, so that's great!

It looks like what I'll end up with is a project containing the models for the lowest in the stack and the middle though, and then when I select the highest level dacpac I'll end up with all three.
I can obviously try and split by hand, but it'll be quite painful.

I was hoping for a means to just include the content actually in the specified dacpac, or have different namespaces for each I suppose. I really want to end up in a position where I have a project for each database project in each source code repo...

I notice the regexp option for filtering things to import. Perhaps that could also be used to control the source dacpac, but looks like it's purely on the object name.

One option could be that I figure out what to include by hand, and hope that gets saved in a config file, then can re-use that for imports at each "tier".
I'll continue tinkering and see if this gets me anywhere.

Thanks for your input, I really appreciate it!

Westy

**Comment by ErikEJ** [comment]
The tool supports multiple config files with different selections, that would be a way forward based on your chosen .dacpac structure.
