### ISSUE TITLE
Table list error

### ISSUE THREAD

**Issue by disl** [ErikEJ/EFCorePowerTools#2070]
### Provide steps to reproduce a bug

1. right mouse button EF CPT -> Reverse Engineering 
2. add database connection
3. print OK  

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/1278236/9da044d5-d715-4f2f-9d6d-3146d5735da3)

### Provide technical details

- EF Core Power Tools version: 2.5.1750

- Exact Visual Studio version: 17.6.10

- Database engine: SQL Server

- EF Core version in use: EF Core 7

- Is Handlebars templates used: no

- Is T4 templates used: no

- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
Your .NET installation is perhaps broken...

**Comment by disl** [comment]
You are right, after a reinstallation of .NET Core 6.0 reverse engineering action was successful. Thank you very much!
