### ISSUE TITLE
It would be great if you could map xml over sql to XElement in C#

### ISSUE THREAD

**Issue by royaldragonit** [ErikEJ/EFCorePowerTools#2091]
**My store**
```
CREATE PROCEDURE Ji_AddOrderItem
	@FacId INT = 0,
	@Floor INT = 0,
	@Table INT = 0,
	@FoodId INT = 0,
    @ListToppingIdXml XML
AS
BEGIN
SELECT 1
END
```
Code Generate by this tool in .NET 8
`Task<int> Ji_AddOrderItemAsync(int? FacId, int? Floor, int? Table, int? FoodId, string ListToppingIdXml, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);`

**Comment by ErikEJ** [comment]
@royaldragonit Why was this closed?
