### ISSUE TITLE
Possible problem with collection naming

### ISSUE THREAD

**Issue by paul-paulgower** [ErikEJ/EFCorePowerTools#2093]
EF Power Tools: 2.5.1648

Visual Studio Enterprise 2022: 17.5.2

SQL Server, no DACPAC

We have a possible problem with identically named tables in 2 different schemas causing issues in the models created.

I have created a simple DB with 2 schemas (I have attached a script file to generate all tables)

This is our renaming.json file:

[
   {
      "SchemaName": "Schema1",
      "TablePatternReplaceWith": "",
      "TableRegexPattern": "$",
      "UseSchemaName": true
   },
   {
      "SchemaName": "Schema2",
      "TablePatternReplaceWith": "",
      "TableRegexPattern": "$",
      "UseSchemaName": true
   }
]

The problem is exposed in the following generated model:

public partial class Schema1TemplateContentParameter
    {
        public Schema1TemplateContentParameter()
        {
            Schema1PageWebPartVersionTemplateParameter = new HashSet<Schema1PageWebPartVersionTemplateParameter>();
        }

        public int TemplateContentParameterId { get; set; }
        public int TemplateId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int ParameterTypeId { get; set; }
        public string DefaultValue { get; set; }
        public string GroupName { get; set; }
        public string Help { get; set; }
        public bool IsRequired { get; set; }
        public string Options { get; set; }
        public DateTime DateCreated { get; set; }
        public DateTime DateUpdated { get; set; }

        public virtual Schema1ParameterType ParameterType { get; set; }
        public virtual Schema1Template Template { get; set; }
        public virtual ICollection<Schema1PageWebPartVersionTemplateParameter> Schema1PageWebPartVersionTemplateParameter { get; set; }
    }

The collection of type <Schema1PageWebPartVersionTemplateParameter> at the bottom of the file has been renamed to Schema1PageWebPartVersionTemplateParameter rather than PageWebPartVersionTemplateParameter which we were expecting.

Is it possible for us to generate our expected name in any way?

[testing DB.txt](https://github.com/ErikEJ/EFCorePowerTools/files/13919693/testing.DB.txt)

NOTICE: A bug report without sufficient technical and repro details and version information WILL BE CLOSED WITHOUT ANY FURTHER ACTION.

### Provide steps to reproduce a bug

Please include a **complete** description of the issue or link to a project that I can run to reproduce the issue.

### Provide technical details

- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)

- Exact Visual Studio version: (e.g. Visual Studio 2022 17.6.5)

- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)

- EF Core version in use: (e.g. EF Core 7)

- Is Handlebars templates used: no/yes

- Is T4 templates used: no/yes

- Is a SQL Server .dacpac used: no/yes

**Comment by ErikEJ** [comment]
I think you may need to use PropertyRenaming for this 

https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#custom-renaming-with-efptproperty-renamingjson

**Comment by ErikEJ** [comment]
Ping?

**Comment by paul-paulgower** [comment]
Thanks.  Will try it outSent from my Galaxy
-------- Original message --------From: Erik Ejlskov Jensen ***@***.***> Date: 14/01/2024  09:29  (GMT+00:00) To: ErikEJ/EFCorePowerTools ***@***.***> Cc: paul-paulgower ***@***.***>, Author ***@***.***> Subject: Re: [ErikEJ/EFCorePowerTools] Possible problem with collection naming (Issue #2093) 
Ping?

**Comment by paul-paulgower** [comment]
The following is the generated class after running the Reverse Engineer

public partial class Schema1PageWebPartVersionTemplate
    {
        public Schema1PageWebPartVersionTemplate()
        {
            Schema1PageWebPartVersionTemplateParameter = new HashSet<Schema1PageWebPartVersionTemplateParameter>();
        }

        public int PageWebPartVersionTemplateId { get; set; }
        public int PageWebPartVersionId { get; set; }
        public int TemplateId { get; set; }
        public string Name { get; set; }
        public int DisplayOrder { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public DateTime DateCreated { get; set; }
        public DateTime DateUpdated { get; set; }

        public virtual Schema1PageWebPartVersion PageWebPartVersion { get; set; }
        public virtual Schema1Template Template { get; set; }
        public virtual ICollection<Schema1PageWebPartVersionTemplateParameter> Schema1PageWebPartVersionTemplateParameter { get; set; }
    }


I would like the final property name to be "PageWebPartVersionTemplateParameter" rather than "Schema1PageWebPartVersionTemplateParameter"

I have tried the following efpt.property-renaming.json file:


  {
    "Classes": [
      {
        "Name": "Schema1PageWebPartVersionTemplate",
        "Properties": [
          {
            "Name": "Schema1PageWebPartVersionTemplateParameter",
            "NewName": "PageWebPartVersionTemplateParameter",
            "AlternateName": "Paul"
          }
        ]
      }
    ]
  }


But this has had no effect.

Is this possible?

Thanks

**Comment by ErikEJ** [comment]
@paul-paulgower Which EF Core version do you target?

**Comment by ErikEJ** [comment]
@paul-paulgower I am not able to repro, property renaming works fine for me. But for a complete repro, please upload a .zip file with all 2 or 3 releated config files.

**Comment by paul-paulgower** [comment]
Please find attached a ZIP of the website I am using for testing.  Many thanks
[Testing.zip](https://github.com/ErikEJ/EFCorePowerTools/files/13960863/Testing.zip)

**Comment by ErikEJ** [comment]
@paul-paulgower With Handlebars disabled, everything works as expected.

**Comment by paul-paulgower** [comment]
Thanks – will investigate

**Comment by paul-paulgower** [comment]
Many thanks again

 

My problem was caused by an earlier version of Visual Studio 2022.  Upgrading to the latest version fixed the problem
