### ISSUE TITLE
Problem on finding EF Core Power Tools CLI entry page

### ISSUE THREAD

**Issue by doggy8088** [ErikEJ/EFCorePowerTools#2094]
There is an SEO issue I'd like to mention. 

The **EF Core Power Tools CLI** (a.k.a. `efcpt`) is really hard to find at first time when googling the keyword `EF Core Power Tools CLI`. I can find the repo (this one) for sure. But when I search on the page with "EF Core Power Tools CLI" will not finding anything. When finding "CLI" still find nothing about the entry link. So that I have to read whole page one paragraph at a time to see where is the right link to enter.

Of course, I can find `Cross platform command line tool - efcpt` section finally. But the [**here**](https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/efcpt.7/readme.md) link is broken at this moment. It need to be fixed.

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/88981/76859ed4-3667-48b9-be3a-b938cb39646e)

Here are the things I want to suggest:

1. Rephrase section title from `Cross platform command line tool - efcpt` to `EF Core Power Tools CLI - efcpt`
2. Fix the **here** link.

**Comment by ErikEJ** [comment]
Thanks, the link is already fixed, I will improve the headline

**Comment by ErikEJ** [comment]
@doggy8088 Updated now, let me know what you think

**Comment by doggy8088** [comment]
LGTM. 👍
