### ISSUE TITLE
Allow pluralize/singularize option with custom renaming?

### ISSUE THREAD

**Issue by sunnylarr** [ErikEJ/EFCorePowerTools#2103]
## Technical Details

EF Power Tools: 2.5.1514

Visual Studio Professional 2022: 17.7.6

EF Core version used: EF Core 7

## Question

Hello, we're wondering if it is possible to use the Naming option to "Pluralize or singularize the generated object names" before executing the custom renaming according to our `efpt.renaming.json` file.

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/2934506/915c9c66-13a0-4e24-a033-f98fab12146c)

This is an example of our `efpt.renaming.json`:

```
[
   {
      "SchemaName": "dbo",
      "TablePatternReplaceWith": "$0Dto",
      "TableRegexPattern": "^.+$",
      "Tables": [ ],
      "UseSchemaName": false
   }
]
```

To follow current conventions, we'd like to just append a `Dto` postfix to our generated class names, but also singularize any plural table names beforehand.

For example, when we have a table name like `Users`, we would like EF Power Tools to generate `UserDto` and also a DbSet of `Users` respectively.

Is this possible with the current EF Power Tools? Or is this a feature that can be implemented? Thank you.

**Comment by ErikEJ** [comment]
You can use the .t4 templates to do this, it is not something I plan to support in any other ways

**Comment by ErikEJ** [comment]
There are some sample customized templates here: https://github.com/ErikEJ/EFCorePowerTools/tree/master/samples/CodeTemplates/EFCore
