### ISSUE TITLE
[Feature]  Add ability to exclude columns in tables in the CLI config 

### ISSUE THREAD

**Issue by jwyza-pi** [ErikEJ/EFCorePowerTools#2106]
# Proposal 

This was mentioned in #2102, but presently the CLI config doesn't support the ability to exclude columns like the VS Plugin version.  This proposal would add that functionality by supporting an array object inside of the table.  Looking something like this:

```json

{
    "tables": [
        {
            "name": "[dbo].[User]",
            "excluded-columns": [
                "PasswordHash",
                "RetiredColumnName",
                "SomeOtherColumnWeDontWant"
            ]
        }
    ]
}

**Comment by ErikEJ** [comment]
The issue is that this increases the risk of the tool generating an invalid model, as not all columns can be excluded, for example if they are primary or foreign keys, or participate in an index. In the GUI these columns can be disabled, so it is not possible to select them.

**Comment by ErikEJ** [comment]
Yes, I think something like that must be implemented as part of this.

**Comment by ErikEJ** [comment]
There is isPrimaryKey and isForeignKey properties on each column model object returned from TablelistBuilder that can be inspected.

Interested in doing a PR?

**Comment by jwyza-pi** [comment]
Possibly, seems like a relatively low lift since that data is part of the TablelistBuilder and it appears from what I found that the determination of if the column can be excluded or not is based on the `isPrimaryKey && isForeignKey` being false.

Looking at it. we're in an interesting conundrum based on that other change made in #2104.  Because we don't fetch the object lists when "refresh-object-lists" is false, we can't validate the excluded columns when that's set.  It might be that reverting that and going back to checking each time is needed.  It's not ideal, but the 2 parts seem mutually exclusive.  

One other alternative would be that if the config file contains excluded columns, we go ahead and fetch the tables again regardless (but don't update the object list if the refresh-object-lists is false) so that it can be validated.  Then for folks who don't use the excludedcolumns functionality, they get the speed bump of not re-querying the DB schema.  It's slightly more complicated, but gives us the benefit of both things.  

I think it comes down to if you want the extra complexity in the code base or if you'd rather it go back to just always fetching the schema regardless of if that setting is presently set.

**Comment by ErikEJ** [comment]
I think we should just revert to always getting the full object list from TableListBuilder, it seems quite useful

**Comment by jwyza-pi** [comment]
Just put up a Draft PR with a couple questions on it if you wouldn't mind reviewing :).  Thanks.

**Comment by jwyza-pi** [comment]
@ErikEJ Do you know roughly when this will be released in the non-nightly builds? thanks!

**Comment by ErikEJ** [comment]
@jwyza-pi I plan a release right after EF Core 8.0.2 has been released, aound 14th Feb I imagine. 

Out of curiosity - what prevents you from simply using the nightly build?

**Comment by jwyza-pi** [comment]
Mostly just a function of having to tell my co-workers to remember to install the nightly build and then remembering to go and install the non-nightly build when it's released :).  If I have a date then I can set a calendar reminder to make sure folks go switch back from the bleeding edge build to the stable release.

Thanks for the info!
