### ISSUE TITLE
[Bug] Mermaidjs Generation when column names have spaces in them breaks

### ISSUE THREAD

**Issue by jwyza-pi** [ErikEJ/EFCorePowerTools#2108]
### Provide steps to reproduce a bug

If you have a table that has spaces in its name, the mermaidjs generation will generate invalid output. (I can't fathom _why_ you'd put spaces in the column names, but hey, it happens apparently....)

so if the column is `Some Column With Space`, it'd pop out as

```
MyTable { 
    Some Column With Space nvarchar(255) 
}
```

but it should be
```
MyTable { 
    SomeColumnWithSpace nvarchar(255) 
}
```

It seems there is [already code](https://github.com/ErikEJ/EFCorePowerTools/blob/10d66b8b2dbda844fdbb7b67ee2a30c38a0fbc17/src/Core/RevEng.Core.60/Mermaid/DatabaseModelToMermaid.cs#L33) in the generation that handles this scenario for table names, so it probably just needs to have the same logic applied to the columns themselves.

### Provide technical details
EF Core Power Tools version: efcpt.7 7.1.41+a4ba35549504ee4de50b3d23fa874f7ecbb5cb81

Exact Visual Studio version: N/A (CLI)

Database engine: Azure SQL

EF Core version in use: 7.0.14

Is Handlebars templates used: no

Is T4 templates used: yes

Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
Interested in doing a PR 😄 ??

**Comment by ErikEJ** [comment]
If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
