### ISSUE TITLE
Add T4 Scaffolding Templates to a .NET 8 Project adds the wrong version / Template Version Tag

### ISSUE THREAD

**Issue by TomBruns** [ErikEJ/EFCorePowerTools#2109]
Thank you for the great tool!

I am running into this error message...
![Snap2](https://github.com/ErikEJ/EFCorePowerTools/assets/13077238/c21a3045-e406-4ad4-9b8f-0e392f498bc1)

This is what is in the t4 template files that were added by this extension ..
```
// Template version: 703 - please do NOT remove this line   <=======
if (!ProductInfo.GetVersion().StartsWith("7.0"))
{
    Warning("Your templates were created using an older version of Entity Framework. Additional features and bug fixes may be available. See https://aka.ms/efcore-docs-updating-templates for more information.");
}
```

### Provide steps to reproduce a bug
1. Create a new .NET 8 Console Project
2. Right click on project > EF Core Power Tools > Add T4 Scaffolding Templates
3. Right click on project > EF Core Power Tools > Reverse Engineer
4. Choose Your EF Core Version > EF Core 8
5. Select tables....
6. Select checkbox ```Customize code using templates "C# - T4"```
7. Click Ok to generate and the error occurs

### Provide technical details

- EF Core Power Tools version: **2.6.72**

- Exact Visual Studio version: **Visual Studio 2022 17.8.4**

- Database engine: **SQL Server**

- EF Core version in use: **EF Core 8**

- Is Handlebars templates used: **no**

- Is T4 templates used: **yes**

- Is a SQL Server .dacpac used: **no**

**Comment by ErikEJ** [comment]
@TomBruns I will investiage 

But you should just let the wizard add the templates, no need to go through the extra menu item.

**Comment by ErikEJ** [comment]
@TomBruns I can see that menu item is hardcoded to EF Core 7 - changing to EF Core 8 going forward

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

**Comment by TomBruns** [comment]
Confirmed, thank you!

**Comment by ErikEJ** [comment]
If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
