### ISSUE TITLE
Reverse Engineer tools makes value within `HasDefaultValueSql("value")` lowercase

### ISSUE THREAD

**Issue by taurit** [ErikEJ/EFCorePowerTools#2116]
### Provide steps to reproduce a bug

1. Create a console project in Visual Studio (alternatively, I attach a minimal one that allows to reproduce the issue: [lowercase-default-value-repro-project.zip](https://github.com/ErikEJ/EFCorePowerTools/files/14009528/lowercase-default-value-repro-project.zip))
2. Create a `SQL Server Database Project` in the solution
3. Add a table with a `NVARCHAR(N)` column and a `DEFAULT` value containing some uppercase characters, for example:
    ```sql
    CREATE TABLE [dbo].[Person]
    (
        [Id] INT NOT NULL PRIMARY KEY,
        [Name] NVARCHAR NOT NULL,

        -- The relevant line:
        [Country] NVARCHAR(100) NOT NULL DEFAULT 'United States AaBbCc'
    )
    ```
4. Use EF Core Power Tools -> Reverse Engineer. Use `Database (.dacpac)` option, keep other settings at their defaults
5. Note that in the generated code, the default value was converted to lowercase (here, `'united states aabbcc'`):

    ```c#
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Person>(entity =>
        {
            entity.ToTable("Person");
    
            // ...
            entity.Property(e => e.Country)
                .IsRequired()
                .HasMaxLength(100)
                // The relevant line:
                .HasDefaultValueSql("'united states aabbcc'");
            // ...
        });
    
        OnModelCreatingPartial(modelBuilder);
    }
    ```

Expected: the `HasDefaultValueSql` should preserve the character case. Otherwise, entities might be created with a different value than intended.

### Provide technical details

- EF Core Power Tools version: 2.6.72

- Exact Visual Studio version: Microsoft Visual Studio Professional 2022 17.8.5

- Database engine: SQL Server, SQLite, probably other as well

- EF Core version in use:EF Core 8

- Is Handlebars templates used: no

- Is T4 templates used: no, yes (both cases tested)

- Is a SQL Server .dacpac used: yes

### Comments

I guess it's relatively rare to have a database design where we need default values for a NVarchar columns, but since I stumbled upon this issue, I leave a question whether this is by design, or (what seems more likely to me) could be considered a bug in the tool?

Thanks!

**Comment by ErikEJ** [comment]
Thanks, it seems like a .dacpac related bug for sure.

https://github.com/ErikEJ/EFCorePowerTools/blob/13ca9e04e02bf1f6fb11fab273c2ed880e09d5ec/src/Nupkg/ErikEJ.EntityFrameworkCore.SqlServer.Dacpac/Scaffolding/SqlServerDacpacDatabaseModelFactory.cs#L402

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

**Comment by taurit** [comment]
> I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

I tested in v2.6.88, solves the issue for us. Thank you!

A small note is that it didn't only affect `NVARCHAR` values, but server function names (like `GETUTCDATE()`) as well . This is totally acceptable for me, and perhaps it's an expected behavior overall, but might be slightly confusing for someone to see such changes when they update the add-on:

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/7702278/6dd529c5-ea6e-4d25-92d1-cdd30e093155)

**Comment by ErikEJ** [comment]
It is correct to use the user entered value, so users most accept this change in casing

**Comment by ErikEJ** [comment]
If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
