### ISSUE TITLE
I have multiple models in project, when i try to update the model, it show last generated model and selected tables. 

### ISSUE THREAD

**Issue by swap407** [ErikEJ/EFCorePowerTools#2118]
I am converting my old project from EF6 to EF Core (.NET 8). I have multiple models in a single project. when i try to update a
 model, it show last generated model selected tables. and i have deselect them, reselect table for a model which i am working and then generate it. 
it a lot of time wasting work i am doing. 

### Provide steps to reproduce a bug

1. generate two separate model in single project with 10 different tables each. (e.g. names- 'model1' & 'model2')
2. now i want to update model1 and want to add new 11th table.
3. select project->right click->reverse engineer-> select connection string-> click ok-> you get 'model2' selected table (because its last generated model)
4. why it wont have model1 tables or is there any way to get it.

### Provide technical details

- EF Core Power Tools version: 2.5.1718
- Exact Visual Studio version: Visual Studio 2022 17.8.5
- Database engine: SQL Server
- EF Core version in use: EF Core 8 & .NET 8
- Is Handlebars templates used: dont know. probably  no.
- Is T4 templates used: dont know. probably  no.
- Is a SQL Server .dacpac used: no

**Comment by swap407** [comment]
Thanks, it worked out.

**Comment by ErikEJ** [comment]
If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
