### ISSUE TITLE
3.1 compatible?

### ISSUE THREAD

**Issue by Newetor** [ErikEJ/EFCorePowerTools#2119]
Hello, would it be possible to get a version where .net 3.1 is compatible? I don't have the chance to upgrade projects and i need to use this tool in the last update for security reasons.

**Comment by ErikEJ** [comment]
What do you mean by "last update" ?

**Comment by Newetor** [comment]
I mean that I want to be able to use EFCoreTools in the last version, but with the additional support for .NET 3.1. Would it be possible or I have to manually add it somehow?

**Comment by ErikEJ** [comment]
It is not possible, and I have no plans to add support, as EF Core 3.1 has been out of support for a long time now. I can offer you an older version of the tool that works with EF Core 3.1
