### ISSUE TITLE
Can't get CRUD scaffolding to work after running "Reverse Engineer", get reflection error

### ISSUE THREAD

**Issue by Catfang** [ErikEJ/EFCorePowerTools#2120]
I am trying something that appears very straight-forward, but am getting stuck. Maybe I'm not using the correct process?

High-level description: I have an existing DB with two tables and a single SP. I can reverse engineer the DB using EFPowerTools and operation completes without issue. However, if I then try to scaffold a new page based on one of the created Models, I get an error: "**Error - There was an error running the selected code generator: 'Could not get the reflection type for DbContext : EFPowerToolsDemo.Data.DemoDbContext'** ". I'm not sure how to proceed. Full details are below.

### Provide steps to reproduce a bug

- Created new project using "ASP.NET Core Web App (Razor Pages) template. Using .Net 8.0 (LTS) with no authentication type. Built project to verify code. Added "Models" and "Data" folders to root project.
- Right-clicked on project name, EF Core Power Tools => Reverse Engineer. Choose the DB and EF Core version of 8.0. Picked the two tables and the SP. Set "EntityTypes path" to Models. Checked "Use DataAnnotation attributes to configure the model". Under Advanced... added Data folder to DbContext path. Click okay, let it run, then built the project to verify all the new code is functional.
- Add 'NewPage' folder under Pages. Right-click on the new folder and Add => New Scaffolding Item... and then pick the Razor Pages using Entity Framwork (CRUD) option. Set Model class to generated model. Set DbContext class to generated context. Hit "add" and code creation starts, but error is thrown during process that ends the operation.
- **Error - There was an error running the selected code generator: 'Could not get the reflection type for DbContext : EFPowerToolsDemo.Data.DemoDbContext'**

### Provide technical details

- EF Core Power Tools version: 2.6.72

- Exact Visual Studio version: Microsoft Visual Studio Professional 2022 (64-bit) - Current, Version 17.8.5

- Database engine: SQL Server Enterprise (GA)

- EF Core version in use: EF Core 8

- Is Handlebars templates used: no

- Is T4 templates used: no

- Is a SQL Server .dacpac used: no

I tried this from scratch twice to make sure I didn't miss anything.

**Comment by ErikEJ** [comment]
Sorry. Ask in an ASP.NET support forum, not related to EF Core Power Tools

**Comment by Catfang** [comment]
If I setup the project without using EF Core Power Tools, it works fine. Sure seems like it has something to do with EF Core Power Tools!

**Comment by ErikEJ** [comment]
Have you tried not including the stored procedure?

**Comment by ErikEJ** [comment]
I need a sample database schema that reproduces the issue if you want my help

**Comment by Catfang** [comment]
I'm sorry I missed your replies earlier today and I really appreciate your help. I did try removing the stored procedure, and everything behaved exactly as before, except that the error was different: _There was an error running the selected code generator: 'Unable to resolve service for type 'Microsoft.EntityFrameworkCore.DbContextOptions`[EFPowerToolsDemo.Demo.DemoDbContext]' while attempting to activate 'EFPowerToolsDemo.Data.DemoDbContext'.'_ 

However, your ask about the schema jogged some braincells and made me realize that the two tables have incorrectly defined primary keys. I will have to get with my DBA in the morning to have them fixed, but I'm now 90% sure that that's the culprit here. You are/were correct that it's not related to EF Core Power Tools.

Thank you again for getting back to me, and creating an extremely useful tool!

**Comment by ErikEJ** [comment]
If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by ErikEJ** [comment]
It is an ASP.NET core issue,  the tooling you are using is maintainer by the ASP.NET core team.

**Comment by Catfang** [comment]
This is in my Extensions Output after [only] clicking 'Reverse Engineer' and then 'Compare DbContext to Database'. (So no scaffolding.)

`System.InvalidOperationException: Error:
Microsoft.EntityFrameworkCore.Design.OperationException: Unable to create a 'DbContext' of type 'MR_OperationsContext'. The exception 'Unable to resolve service for type 'Microsoft.EntityFrameworkCore.DbContextOptions`1[EFPowerToolsDemo.Data.MR_OperationsContext]' while attempting to activate 'EFPowerToolsDemo.Data.MR_OperationsContext'.' was thrown while attempting to create an instance. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728
 ---> System.InvalidOperationException: Unable to resolve service for type 'Microsoft.EntityFrameworkCore.DbContextOptions`1[EFPowerToolsDemo.Data.MR_OperationsContext]' while attempting to activate 'EFPowerToolsDemo.Data.MR_OperationsContext'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass20_5.<FindContextTypes>b__13()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Modelling.EfCoreCompareBuilder.GetCompareResult(String outputPath, String startupOutputPath, String connectionString, String dbContexts) in C:\Code\Github\EFCorePowerTools\src\GUI\efpt60.core\EFCoreCompareBuilder.cs:line 46
   at Modelling.EfCoreCompareBuilder.GenerateSchemaCompareResult(String outputPath, String startupOutputPath, String connectionString, String dbContexts) in C:\Code\Github\EFCorePowerTools\src\GUI\efpt60.core\EFCoreCompareBuilder.cs:line 25
   at Modelling.Program.Main(String[] args) in C:\Code\Github\EFCorePowerTools\src\GUI\efpt60.core\Program.cs:line 36

   at async Task<IEnumerable<CompareLogModel>> EFCorePowerTools.Handlers.Compare.CompareHandler.GetComparisonResultAsync(string outputPath, Project project, DatabaseConnectionModel connection, string[] contextNames)
   at async Task EFCorePowerTools.Handlers.Compare.CompareHandler.HandleComparisonAsync(string outputPath, Project project)
`

**Comment by Catfang** [comment]
That's just creating the project, and then using EF Core Power Tools, nothing else.

**Comment by ErikEJ** [comment]
Did you check the link in the error message? Or look at the Power Tooks wiki?
