### ISSUE TITLE
Errors with procedures and functions inside non-dbo schemas

### ISSUE THREAD

**Issue by robbforce** [ErikEJ/EFCorePowerTools#2123]
Hi, we have an access library for a database and are using a database first methodology. The database is being modified regularly, so we want to be able to "Refresh" without any manual edits. However, I'm seeing a few issues when reverse engineering a database with schemas. I realize schema support is experimental, but didn't see these reported:

- Stored procedures are missing the Schema suffix in their namespace. (Can the suffix be optional?)
- TVFs/functions are not created within their matching schema folder and are missing their schema namespace.
- Contexts for stored procedures do not build with using statements for the schema namespaces. I tried adding these via Handlebars templates, by adding the model namespace to DbImports, but the scaffolding option appears to be ignored for procedure and function contexts.
- When a table name is identical to a table in another schema, scaffolding appends a 1 to the end of the table name in the model file and class.

### Provide steps to reproduce a bug

Reverse engineer a database with schemas in addition to dbo, that contain procedures and functions.

### Provide technical details

- EF Core Power Tools version: v2.6.72, but also tried v2.6.91

- Exact Visual Studio version: Visual Studio 2022 17.8.5

- Database engine: SQL Server

- EF Core version in use: EF Core 7

- Is Handlebars templates used: yes, to add the model and schema namespaces to the contexts.

- Is T4 templates used: no

- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
I suggest you use t4 rather than Handlebars.

For the stored procedure issues,  please provide repro schema. And maybe describe encountered issues.

There is also the option to run some post processing.

**Comment by robbforce** [comment]
> I suggest you use t4 rather than Handlebars.
> 
Ok, I'll switch over to T4.

> For the stored procedure issues, please provide repro schema. And maybe describe encountered issues.
> 
Attached is a script to build a database with a non-dbo schema that has a proc and tvf. Also attached is the efpt config file I used to reproduce the issues.
[demo.zip](https://github.com/ErikEJ/EFCorePowerTools/files/14058746/demo.zip)

1. The procedure will not have the same namespace as the table. Example for a schema named "ad": proc will have x.Models.ad, table will have x.Models.adSchema.
2. The tvf file is created outside the schema subfolder, so it has the root Models namespace.
3. The context and interface for the proc are missing the Models and Schema namespace, so VS is unable to find the entities.

> There is also the option to run some post processing.
>
Can this be done with a template? Or are you referring to something else?

**Comment by ErikEJ** [comment]
Thanks, I will have a look

> Can this be done with a template? Or are you referring to something else?

You can run efpt.postrun.cmd after reverse engineering and do anything in there.

**Comment by ErikEJ** [comment]
> When a table name is identical to a table in another schema, scaffolding appends a 1 to the end of the table name in the model file and class.

You can work around this by renaming one of the tables using the renaming feature

**Comment by ErikEJ** [comment]
I implemented a fix for the broken build in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

(issue 3 was a bug)

- for issue 4, I have outlined a workaround above

- for issue 1 and 2, please create individual issues for these, if you think they are important

**Comment by ErikEJ** [comment]
For more info on the "Schema" suffix: https://github.com/ErikEJ/EFCorePowerTools/pull/1829#issuecomment-1580761370

**Comment by ErikEJ** [comment]
Just did an update to add the missing "Schema" suffix to stored proc result sets also, so this fixes 1

**Comment by robbforce** [comment]
Excellent, thank you for the quick turn around! The new commits fixed my issues with the namespaces for the procs.

> You can work around this by renaming one of the tables using the renaming feature

I had tried this, but it doesn't pick up "tablename1", so I think the 1 must be added after the rename feature runs or it's just not seeing the "tablename1" in the collection to rename.  I should be able to pick this up in the postrun you pointed out.

> You can run efpt.postrun.cmd after reverse engineering and do anything in there.

Ah! Ok, I found it in the docs. It could use a separate header. I'll see what I can do with it and post some examples later.

**Comment by ErikEJ** [comment]
> I had tried this, but it doesn't pick up "tablename1"

It should not be looking for tablename1, but the original table name! (in the correct schema)

Can you share a non-working efpt.renaming.json file?

**Comment by robbforce** [comment]
> It should not be looking for tablename1, but the original table name! (in the correct schema)
> 
> Can you share a non-working efpt.renaming.json file?

I had tried a renaming file with the original and keeping the same name, but that still adds a 1 to the end. If I set "UseSchemaName" to true, then it does rename the table, but with the schema name prefix in the class name.

Attached is the renaming file in the demo.
[demo.zip](https://github.com/ErikEJ/EFCorePowerTools/files/14087320/demo.zip)

**Comment by ErikEJ** [comment]
@robbforce You need to rename to another name to avoid the name collision

**Comment by robbforce** [comment]
No, it's all good. Thanks for checking. I finished writing a postrun script last Friday and got everything where I want. It's a polyglot script and thought I'd send it over if you wanted to included an example in docs or repo. I'll be working on the demo script today and get that back over to you on the postrun issue I submitted.
