### ISSUE TITLE
efpt.postrun.cmd might not be executing

### ISSUE THREAD

**Issue by robbforce** [ErikEJ/EFCorePowerTools#2124]
### Provide steps to reproduce a bug

This is in reference to the 4th bullet point in [issue 2123](https://github.com/ErikEJ/EFCorePowerTools/issues/2123). I have a library project with multiple database models, so I've stored the matching efpt.config.json and efpt.postrun.cmd within the database subfolders. I added a simple rename command to postrun, but I can't tell if it's running after a refresh. No change occurs on the file and I don't see anything in the extension output, like a cmd error message. The readme says it should run the file afterwards. Could a message be added that a postrun file was found and executed? And some output from the commands?

`ren Models\dim\SomeTable1.cs Models\dim\SomeTable.cs`

Updated demo attached:
[demo.zip](https://github.com/ErikEJ/EFCorePowerTools/files/14068669/demo.zip)

### Provide technical details

- EF Core Power Tools version: v2.6.93
- Exact Visual Studio version: Visual Studio 2022 17.8.5
- Database engine: SQL Server
- EF Core version in use: EF Core 7
- Is Handlebars templates used: no
- Is T4 templates used: no
- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
@robbforce 

Add a line with a "pause" command to confirm it is excuted.

 It must be in the same folder as your epft.config.json file

**Comment by robbforce** [comment]
The files are in the same sub folder. I added a pause at the start of postrun, but nothing popped up or otherwise happened and power tools completed the refresh with the usual dialog at the end.

**Comment by ErikEJ** [comment]
Ah! What happens if you just go through the dialogs?

**Comment by robbforce** [comment]
From the edit context item, it's the same. The cmd file doesn't hit "pause" and the normal dialog pops up at the end.

**Comment by ErikEJ** [comment]
Please try from the Reverse engineering menu item on the project context menu. If that does not work, please provide a simple repro project

**Comment by robbforce** [comment]
It's the same from all the context menu options, Reverse Engineer, Edit, or Refresh. The cmd file doesn't seem to run and the pause never happens. Maybe it's something to do with the sub folder pathing?

Demo VS2022 project attached with the folders and separate config files. SQL script to build the database is in the _scripts solution folder.
[Demo.zip](https://github.com/ErikEJ/EFCorePowerTools/files/14091433/Demo.zip)

**Comment by ErikEJ** [comment]
Thanks, I will have a look

**Comment by ErikEJ** [comment]
Interesting - the file was saved in UTF8 with BOM format, so could not be executed. I changed the encoding to ANSI, and it ran fine.

**Comment by ErikEJ** [comment]
I will update the docs!

**Comment by robbforce** [comment]
> Interesting - the file was saved in UTF8 with BOM format, so could not be executed. I changed the encoding to ANSI, and it ran fine.

Ah, that is interesting. I created the file from inside VS2022, through the add items menu and selected a command file. Wonder why that would use a format that won't run in a command prompt... Thanks for the assist!

**Comment by robbforce** [comment]
Hi @ErikEJ , here's a sample script of what I devised for our project. I needed to do a few find & replace actions, which are easier to do in powershell, so went with a polylgot script that executes the batch file as a powershell script. It executes renaming, find & replace, moving and deleting actions on the scaffolded files:
[efpt.postrun.zip](https://github.com/ErikEJ/EFCorePowerTools/files/14168936/efpt.postrun.zip)
