### ISSUE TITLE
Just wanted to say THANK YOU !

### ISSUE THREAD

**Issue by netbitshift** [ErikEJ/EFCorePowerTools#213]
This extension saved my bacon!  I was pulling my hair out trying to find a way to handle lazyloading with my EF Core model - **AND** be able to use a workflow that involves Db schema changes and then updating my EF model.  

It took me a while to figure out the reverse engineering menu and where the generated files go, but it just worked!  And it was fast!  Man, how could Microsoft leave out something like this?

Microsoft, are you listening???  You need to pull this in with the framework or something...
I understand how lazyloading is not always the most performant, but some scenarios it just fits and it saves a lot of re-work.

By the way, I am also using the reverse poco generator on an existing project using EF 6.x and it works great.  What lead me to that was looking for a way to be rid of the dreaded EDMX file that is the bane of all source control merge conflicts!

**Comment by ErikEJ** [comment]
Thanks for the kind words!

**Comment by bricelam** [comment]
> How could Microsoft leave out something like this

We have such awesome MVPs that take care of it for us!

> You need to pull this in with the framework

It would take about a year to get it through our rigorous branding, UX, localization, and accessibility requirements. Then a full-time resource just to keep it shipping inside VS. Honestly, I think our time is better spent working on many-to-many and TPT. 😉

**Comment by ErikEJ** [comment]
@netbitshift - agree on Brice's words. 
I can ship daily builds, and have community PRs, this would never happen with a MS owned extension. 

And I very much appreciate PRs from the community, have a look a the issue list
