### ISSUE TITLE
Revert EF Core 8 navigation naming fix

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#2143]
- [x] Try in VS extension
- [x] Collect feedback
- [x] Add to CLI
- [x] Document

https://github.com/dotnet/efcore/issues/32981#issuecomment-1927173537

**Comment by ErikEJ** [comment]
@hallidev @bclementfidx 
I plan to make this an opt-in to not break too many users.

"UseLegacyNavigationNaming" for example

**Comment by hallidev** [comment]
I recommend "UseImprovedNavigationNaming" but "Legacy" works too :)

**Comment by ErikEJ** [comment]
I am considering "UsePrefixNavigationNaming" ...

**Comment by ErikEJ** [comment]
@hallidev @bclementfidx 

I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

**Comment by bclementfidx** [comment]
This worked for me, appreciate it! A lot of our devs use the cli.. so we're hoping the efcore team will revert this soon

**Comment by ErikEJ** [comment]
@bclementfidx This fix is also included the EF Core Power Tools CLI!

**Comment by ErikEJ** [comment]
@lupusbytes FYI
