### ISSUE TITLE
Trouble reverse engineering a mysql db with foreign keys of different column sizes  

### ISSUE THREAD

**Issue by rbanks54** [ErikEJ/EFCorePowerTools#2147]
I trying to reverse engineer a legacy MySQL database, where GUIDs are used for IDs and stored as strings using different column types. 

Consider this example:
```
CREATE TABLE A {
  `Id` varchar(40) NOT NULL,
  `B_Id` varchar(40),
  PRIMARY KEY (`Id`),
  KEY `FK_B_Id` (`B_Id`),
  CONSTRAINT `FK_B_Id` FOREIGN KEY (`B_Id`) REFERENCES `B` (`Id`) ON DELETE CASCADE
}
```
and in the referenced table, I have
```
CREATE TABLE B { 
  `Id` char(36) NOT NULL,
  PRIMARY KEY (`Id`)
}
```

Even though the columns are different lengths, and one uses `char` while the other uses `varchar`, MySQL treats this configuration as a valid foreign key (https://dev.mysql.com/doc/refman/8.0/en/create-table-foreign-keys.html).

When trying to reverse engineer this DB, the power tools throw an exception indicating that there is a type mismatch.

`System.InvalidOperationException: The types of the properties specified for the foreign key {'B_Id' : string} on entity type 'A (Dictionary<string, object>)' do not match the types of the properties in the principal key {'Id' : Guid} on entity type 'B (Dictionary<string, object>)'. Provide properties that use the same types in the same order.`

The Id in Table B is being detected as a GUID (char(36)) while the B_Id column in table A is detected as a string (varchar(40)). Both are correctly detected, but this breaks the FKey because the CLR types are different.

I don't think it's technically a bug, but it does block me from reverse engineering the database.

Would it be possible to provide a configuration option to override the CLR Type of specific SQL columns types so I could manually override `A.Id` and `A.B_Id` to be GUIDs?

Something like the `efpt.renaming.json` approach, perhaps?
```
[
  {"varchar(40)": "System.Guid"},
  {"char(40)": "System.Guid"}
]
```

### Provide technical details

- EF Core Power Tools version: 2.6.72

- Exact Visual Studio version: Visual Studio 2022 17.8.6

- Database engine: MySQL

- EF Core version in use: EF Core 8

- Is Handlebars templates used: no

- Is T4 templates used: no

- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
It sounds like this should be fixed in the provider. Are you using the Pomelo provider?

**Comment by ErikEJ** [comment]
Ping?

**Comment by rbanks54** [comment]
Yes. It's Pomelo (v8.0 beta 2)

I don't think it's an issue with Pomelo, though. It's doing the right thing and detecting the 36 character column as a GUID, it's detecting the 40 character column as a string. The existing DB is the problem which is why I'm curious if we can override the reverse engineered column types so that the foreign keys work.

I think you're suggesting there's a way to override the type detection in Pomelo so I'll have a look and see what I can see :)

**Comment by rbanks54** [comment]
Ah!... that helped me to get a context generated.

I set `GuidFormat=None;` in the connection string (based on docs for MySQLConnector.NET) and now I at least have a generated context.  Of course, all the columns that should map to GUIDs are now strings, but it's a start.

**Comment by rbanks54** [comment]
I ended up using EF8's scaffolding approach. Why? Because I created a custom type mapping to force the varchar(40) columns to be handled as Guids using this code:

```
public class GuidMySqlDesignTimeServices : MySqlDesignTimeServices
{
    public override void ConfigureDesignTimeServices(IServiceCollection serviceCollection)
    {
        base.ConfigureDesignTimeServices(serviceCollection);

        serviceCollection.AddScoped<IRelationalTypeMappingSourcePlugin, CustomGuidTypeMappingSourcePlugin>();
    }
}

public class CustomGuidTypeMappingSourcePlugin : IRelationalTypeMappingSourcePlugin
{
    public RelationalTypeMapping FindMapping(in RelationalTypeMappingInfo mappingInfo)
    {
        //We have old DB columns that use 40 characters to store Guids
        //This is a custom mapping override to deal with this problem. 
        return (mappingInfo.ClrType is null || mappingInfo.ClrType == typeof(System.String))
                && (mappingInfo.Size == 40 || mappingInfo.Size == 36)
                ? new MySqlGuidTypeMapping(MySqlConnector.MySqlGuidFormat.Char36).Clone(mappingInfo)
                : null;
    }
}
``` 

This ends up generating code like this:
```
public partial class Member
{
    public Guid Id { get; set; }
    //...
}

//and in DBContext...

    modelBuilder.Entity<Member>(entity =>
    {
        entity.HasKey(e => e.Id).HasName("PRIMARY");
        entity.ToTable("member");
        entity.Property(e => e.Id).HasColumnType("varchar(40)");
        //...
    }
```

Thanks for pointing me in the right direction. While it would be nice for the power tool to handle this scenario, I realize it's not a common scenario and probably not worth supporting. The work around seems like it'll be good enough for now.

**Comment by ErikEJ** [comment]
Not something I plan to implement and support, no
