### ISSUE TITLE
[Feature] using EFCore Powertools configuration Files with the CLI or CLI Config with PowerTools.

### ISSUE THREAD

**Issue by M4rtinSc** [ErikEJ/EFCorePowerTools#2148]
We have a Team which uses VS on Windows and VSCode on MacOS, it would be nice to share the config files between the CLI and the VS PowerToools

**Comment by ErikEJ** [comment]
They are too different  - but you can use the CLI on all platforms

**Comment by kingmotley** [comment]
Shame.  Most of my team uses Rider, so the VS PowerTools is a no-go.  I had incorrectly assumed that the CLI had feature parity as  the VS scaffold, and could reuse the same config files between them.  Why doesn't the VS PowerTools just call the CLI behind the scenes?

**Comment by ErikEJ** [comment]
@kingmotley This is an old closed issue. The two tools are now much closer in parity, and the VS Tool can now read a cli config file. (Not write)

Essentially both tools use my internal CLI behind the scenes.


If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by maxisam** [comment]
This is a shame. I was hoping the same things as well. It is still an amazing tool tho. Thanks!

**Comment by maxisam** [comment]
Is there a list for different functionalities?

**Comment by maxisam** [comment]
never mind, found it
https://github.com/ErikEJ/EFCorePowerTools/issues/1751#issue-1640570143

**Comment by ErikEJ** [comment]
@maxisam 
All these are in the CLI, and documented in the wiki.

Also. the VS tool can read a CLI config.

"UseSchemaFolders": true,
"UseSchemaNamespaces": true,
"UseDbContextSplitting": true

**Comment by maxisam** [comment]
Thanks! I actually couldn't find related information from the wiki

https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/RevEng.Shared/Cli/Configuration/FileLayout.cs

based on above code, it seems like they are still in preview? It does work fine from my testing.

**Comment by ErikEJ** [comment]
Did you look in the right place?

https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#file-layout

![image](https://github.com/user-attachments/assets/40e98d41-13fd-4b61-b84a-9780de16cb7f)

And yes, they are in preview, and I reserve the right to remove them or change them in the future.

**Comment by maxisam** [comment]
Thanks! Hope you don't remove them 🙏
