### ISSUE TITLE
Using the CLI, can you add an option to not scaffold view, stored procedures, and functions?

### ISSUE THREAD

**Issue by bclementfidx** [ErikEJ/EFCorePowerTools#2149]
when I run the efcpt command, it generates the efcpt-config.json with all of the tables, stored procedures, and functions.
If I delete the stored procedures and functions from the config file and run the command again, it simply puts them back.

Is there a way I can prevent it from scaffolding the stored procedures and functions? In the "code-generations" section, if i set "type" to "entities" then it will skip all of that extra generation of view/sproc/function stuff... but then it doesnt do the dbcontext.

**Comment by ErikEJ** [comment]
Did you read the readme ??

**Comment by bclementfidx** [comment]
I read the readme. The generated efcpt-config.json doesnt include the "refresh-object-lists" under code-generation automatically.. so when I do add it and set it to false, it is still adding the views, stored-procedures, and functions. Is that what you were referring to?

**Comment by ErikEJ** [comment]
Having that on, then you can remove any unwanted objects

**Comment by ErikEJ** [comment]
You need the latest nightly.. a new version is due next week

**Comment by bclementfidx** [comment]
We really need the ability to not have it generate the views/functions/stored procedures. Even if this "refresh-object-lists": false works ... that means that if someone creates a new table then they'll have to go into this json and add it to scaffold it.

**Comment by ErikEJ** [comment]
Have you tried the exclude option??

**Comment by bclementfidx** [comment]
That will work for us, thank you

**Comment by ErikEJ** [comment]
If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
