### ISSUE TITLE
an Error

### ISSUE THREAD

**Issue by mzy666888** [ErikEJ/EFCorePowerTools#215]
Right click your project -> EF Core Power Tools -> Migrations Tool
 run  an error.
![image](https://user-images.githubusercontent.com/2587129/57175338-5060cf80-6e7d-11e9-8e0c-b6706f3de61c.png)

### Steps to reproduce
I use in the Project:https://github.com/mzy666888/PetaPocoEfCoreMvc

### Further technical details
EF Core Power Tools version: 2.2.12.0

Database engine: Mariadb

Visual Studio version: Visual Studio 2017 15.9.11

**Comment by ErikEJ** [comment]
Please try the latest daily build...

**Comment by ErikEJ** [comment]
Closing...
