### ISSUE TITLE
Does not allow me to use EF 7 with .Net 8

### ISSUE THREAD

**Issue by gbthakkar** [ErikEJ/EFCorePowerTools#2150]
I have recently updated the .Net version from 7 to 8.
keeping all other reference as is. Meaning, the EF 7 on project file.

When I try to reverse engineer with version 2.6.72, it does not show "EF Core 7" in EF version selection dropdown.

![2024-02-10_19-19-07](https://github.com/ErikEJ/EFCorePowerTools/assets/39617998/4ddfa7e7-31df-4109-9fe4-ce5cba5b89ed)

Create a bug report, feature proposal, or ask a question.

NOTICE: A bug report without sufficient technical and repro details and version information WILL BE CLOSED WITHOUT ANY FURTHER ACTION.

### Provide steps to reproduce a bug

Please include a **complete** description of the issue or link to a project that I can run to reproduce the issue.

### Provide technical details

- EF Core Power Tools version: 2.6.72

- Exact Visual Studio version: Visual Studio 2022 17.8.6

- Database engine: SQL Server

- EF Core version in use:  EF Core 7

- Is Handlebars templates used: No

- Is T4 templates used: No

- Is a SQL Server .dacpac used: No

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

**Comment by gbthakkar** [comment]
Hi,
I downloaded the latest daily build and it work as expected. Thank you.

**Comment by ErikEJ** [comment]
If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
