### ISSUE TITLE
Support for a simple property custom type mapping without using T4 templates

### ISSUE THREAD

**Issue by timotyturini** [ErikEJ/EFCorePowerTools#2151]
Hello,
I saw the possible approach for Enums mapping with T4 in #1499 and i suppose it could be adopted as well for custom ValueObjects (as long as we manually map the ef conversion ofc), but it is pretty verbose and very (emphasis on this) unpleasant to mantain as the application grows.

We are actively using EFPT in our projects and loving the simplicity and maintainability of manual mapping in JSON files for property renaming.

Just like the **efpt.property-renaming.json**, could it be an **_efpt.property-type-mapping.json_**, or something similar?

Given the ValueObject
```
namespace MyProject.Core.ValueObjects;
public readonly record struct CustomerId(int Value);
```

And the POCO "anemic" entities
```
public partial class Customer
{
    public int Id { get; set; }
    // other props
}

public partial class Order
{
    public int CustomerId { get; set; }
    // other props
}
```

The JSON file could be structured something like this
```
{
    "Classes": [
        {
            "Name": "Customer",
            "Properties": [
                {
                    "Name": "Id",
                    "NewTypeFullName": "MyProject.Core.ValueObjects.CustomerId"
                }
            ]
        },
        {
            "Name": "Order",
            "Properties": [
                {
                    "Name": "CustomerId",
                    "NewTypeFullName": "MyProject.Core.ValueObjects.CustomerId"
                }
            ]
        }
    ]
}
```

And the POCO "rich" expected result
```
public partial class Customer
{
    public MyProject.Core.ValueObjects.CustomerId Id { get; set; }
    // other props
}

public partial class Order
{
    public MyProject.Core.ValueObjects.CustomerId CustomerId { get; set; }
    // other props
}
```

Could it be feasible?

### Provide technical details
- EF Core Power Tools version: 2.6.72
- Exact Visual Studio version: Visual Studio 2022 17.8.6
- Database engine: SQL Server, MySQL
- EF Core version in use: 6 and 8
- Is Handlebars templates used: no
- Is T4 templates used: no
- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
It think this will easily cause unbuildable code, so reluctant

Maybe you could use [eftp.postrun.cmd](https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#saving-options-and-running-the-second-time) ?

**Comment by ErikEJ** [comment]
Also, property renaming is an experimental feature, with a number of pitfalls.

**Comment by timotyturini** [comment]
> It think this will easily cause unbuildable code, so reluctant
> 
> 
> 
> Maybe you could use [eftp.postrun.cmd](https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#saving-options-and-running-the-second-time) ?

T4 likewise can led to unbuildable code: I personally think that in both cases it's a developer responsibility to write down the correct type and keep foreign keys type-aligned with the parent key.
