### ISSUE TITLE
[Question]I encountered some problems during the installation. My computer's CPU is based on the ARM architecture, and the version of Visual Studio is 2022. The following error log occurred during installation.

### ISSUE THREAD

**Issue by MayDay-wpf** [ErikEJ/EFCorePowerTools#2154]
2024/2/12 23:33:13 - Microsoft VSIX Installer
2024/2/12 23:33:13 - -------------------------------------------
2024/2/12 23:33:13 - vsixinstaller.exe version:
2024/2/12 23:33:13 - 17.8.2368+6fbeaa1954
2024/2/12 23:33:13 - -------------------------------------------
2024/2/12 23:33:13 - Command line parameters:
2024/2/12 23:33:13 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,\\Mac\Home\Downloads\EF_Core_Power_Tools_v2.6.72.vsix
2024/2/12 23:33:13 - -------------------------------------------
2024/2/12 23:33:13 - Microsoft VSIX Installer
2024/2/12 23:33:13 - -------------------------------------------
2024/2/12 23:33:18 - Initializing Install...
2024/2/12 23:33:18 - 正在搜索适用的产品...
2024/2/12 23:33:25 - 找到的已安装产品 - Visual Studio Community 2022
2024/2/12 23:33:25 - 找到的已安装产品 - 全局位置
2024/2/12 23:33:25 - 扩展详细信息...
2024/2/12 23:33:25 - 	Identifier         : f4c4712c-ceae-4803-8e52-0e2049d5de9f
2024/2/12 23:33:25 - 	Name               : EF Core Power Tools
2024/2/12 23:33:25 - 	Author             : ErikEJ
2024/2/12 23:33:25 - 	Version            : 2.6.72
2024/2/12 23:33:25 - 	Description        : Useful design-time DbContext features, added to the Visual Studio Solution Explorer context menu.

When right-clicking on a C# project, the following context menu functions are available:
Reverse Engineer - Generates POCO classes, derived DbContext and Code First mapping for an existing database or SQL Server Database project (.dacpac).
Migrations Tool - Manage EF Core Migrations in the project: View status, Add Migration, Update Database
Add DbContext Model Diagram - Adds a DGML graph from your DbContext Model.
View DbContext Model SQL DDL - View a SQL DDL script from your DbContext Model.
About - Displays version and other diagnostic information about your Visual Studio instance. 
        
2024/2/12 23:33:25 - 	Locale             : en-US
2024/2/12 23:33:25 - 	MoreInfoURL        : https://github.com/ErikEJ/EFCorePowerTools/wiki/
2024/2/12 23:33:25 - 	InstalledByMSI     : False
2024/2/12 23:33:25 - 	SupportedFrameworkVersionRange : [4.8,)
2024/2/12 23:33:37 - 	SignatureState     : ValidSignature
2024/2/12 23:33:37 - 	SignedBy           : Open Source Developer, Erik Ejlskov Jensen
2024/2/12 23:33:37 - 	Certificate Info   : 
2024/2/12 23:33:37 - 		-------------------------------------------------------
2024/2/12 23:33:37 - 		[Subject]       : CN="Open Source Developer, Erik Ejlskov Jensen", O=Open Source Developer, L=Hillerod, S=Zealand, C=DK
2024/2/12 23:33:37 - 		[Issuer]        : CN=Certum Code Signing 2021 CA, O=Asseco Data Systems S.A., C=PL
2024/2/12 23:33:37 - 		[Serial Number] : 1099D484A9FBD3763360BC5422DE0B2E
2024/2/12 23:33:37 - 		[Not Before]    : 2024/1/17 15:23:38
2024/2/12 23:33:37 - 		[Not After]     : 2025/1/16 15:23:37
2024/2/12 23:33:37 - 		[Thumbprint]    : E610BFFCC22D3B9D2FBA806D416A6B115F461710
2024/2/12 23:33:37 - 	支持的产品              : 
2024/2/12 23:33:37 - 		Microsoft.VisualStudio.Community
2024/2/12 23:33:37 - 			Version : [17.0,18.0)
2024/2/12 23:33:37 - 			ProductArchitecture : amd64
2024/2/12 23:33:37 - 	引用                 : 
2024/2/12 23:33:37 - 	系统必备               : 
2024/2/12 23:33:37 - 		-------------------------------------------------------
2024/2/12 23:33:37 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
2024/2/12 23:33:37 - 		Name         : Visual Studio core editor
2024/2/12 23:33:37 - 		Version      : [17.0,)
2024/2/12 23:33:37 - 		-------------------------------------------------------
2024/2/12 23:33:37 - 		Identifier   : Microsoft.VisualStudio.Component.GraphDocument
2024/2/12 23:33:37 - 		Name         : DGML editor
2024/2/12 23:33:37 - 		Version      : [17.0,)
2024/2/12 23:33:37 - 		-------------------------------------------------------
2024/2/12 23:33:37 - 		Identifier   : Microsoft.VisualStudio.Component.VisualStudioData
2024/2/12 23:33:37 - 		Name         : Data sources and service references
2024/2/12 23:33:37 - 		Version      : [17.0,)
2024/2/12 23:33:37 - 签名详细信息...
2024/2/12 23:33:37 - 	Extension is signed with a valid signature.
2024/2/12 23:33:37 - VSIXInstaller.NoApplicableSKUsException: 此扩展不能安装在任何当前安装的产品上。
   在 VSIXInstaller.ExtensionService.GetInstallableDataImpl(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   在 VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   在 VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   在 VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   在 VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   在 VSIXInstaller.App.Initialize()
   在 System.Threading.Tasks.Task`1.InnerInvoke()
   在 System.Threading.Tasks.Task.Execute()

**Comment by ErikEJ** [comment]
I do not support the VS ARM edition, it is crippled.

You can use the CLI on ARM

**Comment by MayDay-wpf** [comment]
> I do not support the VS ARM edition, it is crippled.
> 
> You can use the CLI on ARM



> 我不支持VS ARM版本，它是残废的。
> 
> 您可以在 ARM 上使用 CLI

thank you very much

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.
