### ISSUE TITLE
EF Core Power Tools  Reverse engineer - Table list error

### ISSUE THREAD

**Issue by chenbinkellum888** [ErikEJ/EFCorePowerTools#2157]
Hello ErikEJ,
      I used EF Core Power Tools to do Reverse engineering, first step to connect Database, click "Confirm" should go to table page. but jump out a error with message "Table list error: Unable to launch external process", and got Json string as follow picture.
![error](https://github.com/ErikEJ/EFCorePowerTools/assets/150498847/4d3f7ab3-675a-45c7-a3e6-037c84c2125c)

- EF Core Power Tools version: 2.6.72
- Exact Visual Studio version: Visual Studio 2022 17.8.6

- Database engine: SQL Server 2019

- EF Core version in use: EF Core 8

- Is Handlebars templates used: no

- Is T4 templates used: no

- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
What have you tried?

**Comment by ErikEJ** [comment]
According to the web  it is some piece of software interfering with the console app used by reverse engineering.  Virus scanner or similar.

**Comment by chenbinkellum888** [comment]
Thanks，I changed  a computer, everything was ok now! Same process.

**Comment by ErikEJ** [comment]
@chenbinkellum888 Thanks for the heads up.
