### ISSUE TITLE
Table valued function with bigint PK generates int

### ISSUE THREAD

**Issue by Dimigergo** [ErikEJ/EFCorePowerTools#2159]
Hello! 

I use the following versions:
- Visual Studio 17.9.0
- EF Core 6
- EF Core Power Tools 2.6.72
- SQLServer 11.0.6251

The following program generates the wrong type:
[EFCoreFuncBigintPK.zip](https://github.com/ErikEJ/EFCorePowerTools/files/14280181/EFCoreFuncBigintPK.zip)

The tblLCResults table contains bigint primary key (ResId).
The generation of the table is ok, long generated.
The funcGetRes return type (funcGetResResult) type is int not long, this is the problem.

![error1](https://github.com/ErikEJ/EFCorePowerTools/assets/11498949/6d9dca63-6267-46f7-bb25-eacdfc367e3b)

**Comment by ErikEJ** [comment]
I am not able to repro, I get this generated based on your .sql script:

```csharp
public partial class funcGetResResult
{
    public int ChChannel { get; set; }
    public long? ResId { get; set; }
    public long? ResLongId { get; set; }
}

```

**Comment by Dimigergo** [comment]
Is it possible that the first generation is ok, but if I modify the func inside, the refresh make it wrong?
I remember, that the first time it was good (long), but I can't reproduce the good (long) type.

**Comment by ErikEJ** [comment]
>  but if I modify the func inside, the refresh make it wrong?

Please provide details by what exactly you mean by this? Otherwise I am unable to help you

**Comment by Dimigergo** [comment]
Ok.

**Comment by Dimigergo** [comment]
Sorry, something is weird. In a new database, I can't reproduce the bug. I have to investigate, what cause the problem. If I found it I will reopen the issue. 

Thanks!

**Comment by ErikEJ** [comment]
If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
