### ISSUE TITLE
DbContext Model menu actions cause FileNotFoundException - Microsoft.VisualStudio.ProjectSystem, Version=16.0.0.0

### ISSUE THREAD

**Issue by tsurrdurr** [ErikEJ/EFCorePowerTools#216]
Hello, I'm having problems using the diagram building functionality and this library overall for the first time. 

### Steps to reproduce
Right click the project that contains class inheriting from DbContext -> EF Core Power Tools -> Add DbContext Model Diagram. 
VS builds the project and then displays an error in output window.

### Further technical details
EF Core Power Tools version: latest build from feed (2.2.60)

.NET version: Core 2.2

Error message in output window:
```
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.ProjectSystem, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.VisualStudio.ProjectSystem, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at EFCorePowerTools.Extensions.ProjectExtensions.GetCspProperty(Project project, String propertyName)
   at EFCorePowerTools.Handlers.ProcessLauncher.GetOutput(String outputPath, String projectPath, GenerationType generationType, String contextName, String migrationIdentifier, String nameSpace) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ProcessLauncher.cs:line 94
   at EFCorePowerTools.Handlers.ModelAnalyzerHandler.Generate(String outputPath, Project project, GenerationType generationType) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ModelAnalyzerHandler.cs:line 62
```

Database engine: Postgres

Visual Studio version: Visual Studio 2017 15.9.11 (latest).

I've tried installing [ProjectSystem 16.0.374-pre](https://www.nuget.org/packages/Microsoft.VisualStudio.ProjectSystem/16.0.374-pre) via NuGet in the project i've tried to use EFCorePowerTools with, but to no avail. Same version is used in current EFCorePowerTools code version, but the current version of the source code seems to be different from the one in the latest build from the feed (e.g. line numbers in stack trace don't match the current code line numbers).

I am very confused at the moment, am I missing something?

**Comment by tsurrdurr** [comment]
Haven't had the chance yet, but I will try it later on my home PC.

**Comment by tsurrdurr** [comment]
Performed the described actions in VS 2019, everything works just fine.

**Comment by ErikEJ** [comment]
I will try to repro with VS 2017 15.9.11

**Comment by jespersh** [comment]
It might not even fault if you have 2019 installed on the same machine as 2017. Just a thought FYI

**Comment by ErikEJ** [comment]
@jespersh  Ah - that is my case! will test on machine with only VS 2017

**Comment by tsurrdurr** [comment]
I actually have checked it on the same machine on which it hadn't worked for me before.  
The same exact project currently can have model successfully generated in VS 2019 but not in VS 2017.

**Comment by ErikEJ** [comment]
Closing, a unable to repro and no other users have reported this

**Comment by SanjayForGitHub** [comment]
Hi 

I am facing the same issues with latest VS 2017. I don't have VS 2019.

Thank
Sanjay

**Comment by ErikEJ** [comment]
@sanjayforgithub which Power Tools and VS versions are in use?

**Comment by SanjayForGitHub** [comment]
Hello @ErikEJ 

Thanks for the quick response. below are the details.

Visual Studio Enterprise Edition - 15.9.13
EF Core Power Tools - 2.2.63

Thanks
Sanjay

**Comment by ErikEJ** [comment]
Attempted to fix in the latest daily build, please try it out and let me know.

**Comment by MagicAndre1981** [comment]
I now get this in `activitylog.xml`

> SetSite failed for package [EFCorePowerToolsPackage]Source: 'EFCorePowerTools' Description: Die Datei oder Assembly "Microsoft.VisualStudio.ProjectSystem, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden. System.IO.FileNotFoundException: Die Datei oder Assembly "Microsoft.VisualStudio.ProjectSystem, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden. File name: 'Microsoft.VisualStudio.ProjectSystem, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'at EFCorePowerTools.EFCorePowerToolsPackage.<InitializeAsync>d__11.MoveNext()at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)at EFCorePowerTools.EFCorePowerToolsPackage.InitializeAsync(CancellationToken cancellationToken, IProgress`1 progress)at Microsoft.VisualStudio.Shell.AsyncPackage.<>c__DisplayClass17_0.<<Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize>b__1>d.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)at Microsoft.VisualStudio.Services.VsTask.GetResult()

Don't [use 16.x nuget packages](https://github.com/ErikEJ/EFCorePowerTools/blob/63f712944ee268d519711d484e07ef5f66e0255d/src/GUI/EFCorePowerTools/EFCorePowerTools.csproj#L397), only 15.x to keep 2017 compatibility.

**Comment by ErikEJ** [comment]
For this particular package I am forced to use the 16.0 version. Looks like the file is not included in the vsix package !?

**Comment by MagicAndre1981** [comment]
ok, I saw you [made the change here](https://github.com/ErikEJ/EFCorePowerTools/commit/17b079ccc756def5cdeb69bae9306eafe95ea035). The DLL is not part of `EF Core Power Tools v2.2.79.vsix`

**Comment by ErikEJ** [comment]
I have now force added the dll in the latest daily build.

**Comment by SanjayForGitHub** [comment]
![image](https://user-images.githubusercontent.com/20337556/61611736-382d6f00-ac7a-11e9-8daa-f6e850ea7b0c.png)
![image](https://user-images.githubusercontent.com/20337556/61611763-49767b80-ac7a-11e9-8a94-9232a32ae9a4.png)
Getting above when clicking Migration Tool Preview

**Comment by ErikEJ** [comment]
@SanjayForGitHub Wich EF Core Power Tools version?
Can you share a repro project?

**Comment by SanjayForGitHub** [comment]
I downloaded your latest daily build an hour back and run it. 

I have two class library projects, One is domain and another one is Application layer.

In application layer, I have a class for DbContext, see below and from Application project I am clicking on Add DbContent Model diagram, getting errors.

System.NullReferenceException: Object reference not set to an instance of an object.
   at EFCorePowerTools.Extensions.ProjectExtensions.GetCspProperty(Project project, String propertyName) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Extensions\ProjectExtensions.cs:line 51
   at EFCorePowerTools.Handlers.ProcessLauncher.GetOutput(String outputPath, String projectPath, GenerationType generationType, String contextName, String migrationIdentifier, String nameSpace) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ProcessLauncher.cs:line 94
   at EFCorePowerTools.Handlers.ModelAnalyzerHandler.Generate(String outputPath, Project project, GenerationType generationType) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ModelAnalyzerHandler.cs:line 62
---------------------------------------------------------------------------------------------------------------

using Microsoft.EntityFrameworkCore;
using Sandbox.Domain;
using System;

namespace Sandbox.Application
{
    public class EmployeeDbContext:DbContext
    {
        public EmployeeDbContext() {
        }
        public DbSet<Person>  Person{ get; set; }
        public DbSet<Employee> Employee { get; set; }
    }
}

**Comment by MagicAndre1981** [comment]
> I have now force added the dll in the latest daily build.

works, I no longer get the message in ActivityLog.xml. I had the extension installed for testing some time ago and haven't used it recently and only noticed now the error.

**Comment by ErikEJ** [comment]
@SanjayForGitHub 
You did not answer any of my questions:

Which EF Core Power Tools version?

Please share a repro project!

**Comment by ikalkov** [comment]
I have the same issue as @SanjayForGitHub
Visual Studio 2017 - 15.9.14
.NET Framework - 4.7.03062
EF Core Power Tools - 2.2.82.0

**Comment by ErikEJ** [comment]
@ikalkov This does not relate to the original issue (whihc is closed as fixed) here, please create a new issue with a repro project, and I will investigate.

**Comment by anshumandikshit** [comment]
Hi ErikEJ
I have the same issue as @SanjayForGitHub
Visual Studio 2017 - 15.9.6
.NET Framework - 4.7.03190
EF Core Power Tools - 2.2.63


System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.ProjectSystem, Version=16.0.0.0, Culture=neutral

**Comment by ErikEJ** [comment]
Maybe update to latest VS build - or maybe you need VS 2019 for this feature to work.

**Comment by anshumandikshit** [comment]
@ErikEJ  VS 2017 is fully updated .But cant change to VS2019 due to project dependency

**Comment by ErikEJ** [comment]
Not that I know of, maybe you need to install .NET Core support?

**Comment by anshumandikshit** [comment]
.NET core has alrady been Installed .The application I am making is in .NET core webAPI and React as frontend

**Comment by ErikEJ** [comment]
Why not open the solution in VS 2019, create the diagram, and move on?
