### ISSUE TITLE
SP Return Properties not being generated after upgrading to 2.6.140

### ISSUE THREAD

**Issue by tkardaridis** [ErikEJ/EFCorePowerTools#2162]
Hi all.
After upgrading on 2.6.140 and trying to reverse engineer my database, i realize that all the results objects from SPs are empty. See the attached image comparing the previous object with the newly generated from 2.6.140.

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/40442450/7330603d-e642-4e66-9f12-84a82ee7cb34)

**Comment by ErikEJ** [comment]
Please answer all the questions when creating new issues here, and provide repro steps (at least a SQL script)
