### ISSUE TITLE
suggested way to handle reverse engineering of JSON fields

### ISSUE THREAD

**Issue by rustygutter** [ErikEJ/EFCorePowerTools#2165]
My question is related to #2030 and #2151.  I am working on a database first EF core-enable app (SQL Server) where a number of table columns are holding JSON structures I'd like to reference in code.  

I'm using the partial class/method functionality to call OnModelCreatingPartial() in a separate file to handle all the conversions between JSON text and pre-made C# classes.  This is super handy b/c I can continue to run the reverse engineer process and not have to re-enter that code in the auto-generated DbContext.

Just as an example, the following is how I'm mapping [Asset].[AssetMetadata] to a C# class called AssetMetadata:
` partial void OnModelCreatingPartial(ModelBuilder modelBuilder)    
 {
     modelBuilder.Entity<Asset>()
         .Property(e => e.AssetMetadata)
         .HasConversion(
             v => JsonConvert.SerializeObject(v, new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore }),
             v => JsonConvert.DeserializeObject<AssetMetadata>(v));
`

The "problem" is that I still have to manually go into the auto-generated class files and change the default "string" property for each JSON field-sourced property:

`public partial class Asset
{
    public AssetMetadata AssetMetadata { get; set; }
    //public string AssetMetadata { get; set; }
`

Is there a way to avoid this manual reassignment of property type? Something like the partial class/method function OnModelCreatingPartial() ?  

Or to put it another way: is there some easy way to tell EFCorePowerTools how to reverse engineer table columns meant to hold JSON into the desired / equivalent C# class?  

It seems like t4 files might be a way, but I'm honestly a bit confused by the t4 scripting and it doesn't feel like a particularly "simple" way to achieve my goal in any case.  There must be others who are doing what I want to know, so I'd like to hear what people are doing or what the suggested workflow should be.  Any references to examples would be appreciated. :-)

**Comment by ErikEJ** [comment]
Search and replace after scaffolding?

**Comment by rustygutter** [comment]
OK.  Maybe trigger a simple Powershell rename script from efpt.postrun.cmd?  That doesn't sound too bad.
