### ISSUE TITLE
Add Prefix for Virtual Objects and Collections.

### ISSUE THREAD

**Issue by tpspencer** [ErikEJ/EFCorePowerTools#2166]
I love your PowerTool.  It is so much better than using the command line tools.  Thank you.

We have a database that has about 400 tables in it.
There are lots of one to many relationships.
We wrote our own "EF" framework back in the stone ages and are attempting to move to using EF Core.

One problem we see is with the generated Entities.

Take the Company, Branch, Person example of a contact list.

One Company has many Branch rows
One Branch has many Person rows
The standard T4 templates generate these virtual objects and collections for the related tables.

**Company**
	public virtual ICollection<Branch> Branch { get; set; } = new List<Branch>();

**Branch**
    public virtual Company Company { get; set; }
    public virtual ICollection<Person> Person { get; set; } = new List<Person>();

**Person**
	public virtual Branch Branch { get; set; }

The our framework generated the objects and collections with Obj and Col prefixes.

**Company**
	public virtual ICollection<Branch> **Col**Branch { get; set; } = new List<Branch>();

**Branch**
    public virtual Company **Obj**Company { get; set; }
    public virtual ICollection<Person> **Col**Person { get; set; } = new List<Person>();

**Person**
	public virtual Branch **Obj**Branch { get; set; }

We have a huge code base and would like to avoid the searching and replacing to update our code to reflect the default virtual objects and collections.

I wonder if you could add variables to allow me to specify prefixes for virtual object and collections?

I am aware that I can tweak the T4 templates myself, but having this feature built in would be nice.

Thank you for the great tool.

**Comment by ErikEJ** [comment]
This very opinionated and specific request is a very good use case for t4 IMHO. But thanks for the kind words.

**Comment by tpspencer** [comment]
Ok, I will use the T4s.  
Thank you.
