### ISSUE TITLE
Visual Studio ARM Support

### ISSUE THREAD

**Issue by scottkuhl** [ErikEJ/EFCorePowerTools#2172]
Please add support for Visual Studio on ARM.

**Comment by ErikEJ** [comment]
I tried, but VS ARM has too many limitations. You can use the CLI edition on ARM.

**Comment by scottkuhl** [comment]
Fair enough.  Thanks for the quick response.

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.
