### ISSUE TITLE
RevEng: Table specific namespaces and folders

### ISSUE THREAD

**Issue by spaasis** [ErikEJ/EFCorePowerTools#2173]
Hi,

Is there a way to reverse engineer tables and configurations in their own folders and namespaces? There already is `UseSchemaFolders` and `UseSchemaNamespaces`,  so basically the same thing but for the (possibly renamed) table names.
In a "vertical slice architecture" these files would go together, separated from all the other entities:
- SampleEntities
  - Commands
  - Queries
  - ...
  - SampleEntity.cs
  - SampleEntityConfiguration.cs
- OtherEntities
  - ...
  - OtherEntity.cs
  - OtherEntityConfiguration.cs 

I had a quick look accross the source code and didn't find anything existing to support this. Could T4 be of use here, or would this need to a direct part of the scaffolding itself?

Thanks for this amazing tool!

**Comment by ErikEJ** [comment]
You could move the files after generation with efpt.postrun.cmd?

**Comment by ErikEJ** [comment]
Or a seperate DbContext per vertical slice?

**Comment by spaasis** [comment]
> You could move the files after generation with efpt.postrun.cmd?

Hmm, that could certainly work rather easily for the file locations but the namespacing would require some effort.

> Or a seperate DbContext per vertical slice?

Could work for some projects, but having tens (or hundreds..) of DbContexts seems quite untenable.

Both of these are valid options to reach the required result, so I'm closing the issue. Thanks for the very quick reply!
