### ISSUE TITLE
Can't install the EF Core Power Tools extension (The call to DuplicateHandle failed)

### ISSUE THREAD

**Issue by 0xced** [ErikEJ/EFCorePowerTools#2177]
<details>
<summary>Using Visual Studio 17.9.0</summary>
Microsoft Visual Studio Professional 2022
Version 17.9.0
VisualStudio.17.Release/17.9.0+34607.119
Microsoft .NET Framework
Version 4.8.09037

Installed Version: Professional

Visual C++ 2022   00476-80000-00000-AA873
Microsoft Visual C++ 2022

ASP.NET and Web Tools   17.9.195.45391
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.9.195.45391
Azure App Service Tools v3.0.0

C# Tools   4.9.0-3.24081.11+989117396f26e5453ff157df610d22ce45b6b0a9
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

NuGet Package Manager   6.9.1
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.9.2.2408002+5aec2f1744a2273d3e7157cc4cc1986f87f524d4
Provides languages services for ASP.NET Core Razor.

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   17.0.30103.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.9.0-3.24081.11+989117396f26e5453ff157df610d22ce45b6b0a9
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.9.0-beta.23614.3+a521e1cd420beb56c15faf6836184fadd2b7937a
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.
</details>

Here's the install log:
```
19.02.2024 15:12:50 - Microsoft VSIX Installer
19.02.2024 15:12:50 - -------------------------------------------
19.02.2024 15:12:50 - vsixinstaller.exe version:
19.02.2024 15:12:50 - 17.9.3174+fce230bb0d
19.02.2024 15:12:50 - -------------------------------------------
19.02.2024 15:12:50 - Command line parameters:
19.02.2024 15:12:50 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\vsixinstaller.exe,/appidinstallpath:C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\devenv.exe,/skuName:Pro,/skuVersion:17.9.34607.119,/appidname:Microsoft Visual Studio Professional 2022,/culture:en-US,/noep,C:\Users\cedric\AppData\Local\Temp\VSIXnzkbkv0h.vsix,/callingprocessid:9912,/installas:3500
19.02.2024 15:12:50 - -------------------------------------------
19.02.2024 15:12:50 - Microsoft VSIX Installer
19.02.2024 15:12:50 - -------------------------------------------
19.02.2024 15:12:51 - System.ComponentModel.Win32Exception (0x80004005): The call to DuplicateHandle failed
   at VSIXInstaller.UserImpersonationHelper.DuplicateSuppliedToken(IntPtr token, UInt32 callingProcessId)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

Not sure how to fix this. 😕

**Comment by ErikEJ** [comment]
Neither am I 😄 - maybe some security software interfering with the installer. At any rate, this does not seem like an issue with EF Core Power Tools

**Comment by 0xced** [comment]
Well, I opened `C:\Users\cedric\AppData\Local\Temp\VSIXnzkbkv0h.vsix` (found in the logs) directly from the Windows Explorer and installation worked. Damn computers! 🤦
