### ISSUE TITLE
EF Core 3.0 support for Modelling

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#218]

**Comment by NotAClue** [comment]
Hi Erik, I messaged you on the market place, I assume this is where you wanted to chat?

**Comment by ErikEJ** [comment]
@NotAClue - you should be able to add a .NET Core 2.2 project to your solution, that uses EF Core 2.2.4, then  link to the DbContext files and classes and generate the diagram in this project.

**Comment by NotAClue** [comment]
Thx, I'll give that a try 👍

**Comment by jespersh** [comment]
One of the EF Core 3.0 changes is the `.HasNoKey()`
For MySQL provider that might mean we can generate DbSets for views and non-primarykey.
https://github.com/ErikEJ/EFCorePowerTools/blob/21937357b6617f1f386aa70d2520ae7c7d66e661/src/GUI/EFCorePowerTools/Helpers/EnvDTEHelper.cs#L233-L234

**Comment by ErikEJ** [comment]
Yes, views will be supported with 3.0, and of course some related table list changes will be required for each provider. In addition, the provider code that creates the DatabaseModel must be updated to support views.

**Comment by wondering639** [comment]
> @NotAClue - you should be able to add a .NET Core 2.2 project to your solution, that uses EF Core 2.2.4, then link to the DbContext files and classes and generate the diagram in this project.

Erik, could you kindly provide some step by step instructions for that? I am using VS 2019 Preview & ASP.NET Core 3 Preview. As there are also change to the Startup.cs between ASP.NET Core 2 and ASP.NET Core 3, it's unfortunately not done by just copying the Models ): I am lacking the knowledge to adapt everything though (still new to ASP.NET Core).
As an alternative, would it be possible to provide a preview version of the EF Core Power Tools that simply don't check for the .NET Core Version one is running? Thanks.

**Comment by ErikEJ** [comment]
Good idea, can you share the first lines from your csproj file?

**Comment by wondering639** [comment]
> Good idea, can you share the first lines from your csproj file?

Sure. Guess you are mainly interested in the TargetFramework, but as the .csproj file is not that long, here's the complete one:
`<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="3.0.0-preview5-19227-01" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.0.0-preview5.19227.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.0.0-preview5.19227.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="3.0.0-preview5.19227.9" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.0.0-preview5-19264-04" />
  </ItemGroup>

</Project>`

This is from an ASP.NET Core project running on NET Core 3 Preview 5, created using Visual Studio 2019 Preview. Let me know if you need more information.

**Comment by ErikEJ** [comment]
@wondering639 You should be able to run "Reverse engineering" with the current codebase - but maybe you are looking for another feature?

**Comment by wondering639** [comment]
@ErikEJ  Yes, indeed - I want to use the "Add DbContext Model Diagram" which however gives me 
![image](https://user-images.githubusercontent.com/25722498/59147483-59087080-89fc-11e9-8a5b-0ea916597acc.png)
My assumption is that of course no new EF Core 3 features will work without any adoption of the PowerTools Core, but shouldn't some basic stuff work that is currently blocked artificially by the version check?

**Comment by ErikEJ** [comment]
@wondering639 Sadly, creating the Model Diagram is no "basic stuff", and the block is not artificial.

**Comment by wondering639** [comment]
@ErikEJ OK, thanks for clarifying that. 

I expected this because of
> @NotAClue - you should be able to add a .NET Core 2.2 project to your solution, that uses EF Core 2.2.4, then link to the DbContext files and classes and generate the diagram in this project.
but seems I am lacking some context here ;-)

**Comment by ErikEJ** [comment]
I plan to start work on this in July, and be based on the latest preview (6 or 7 by then)

**Comment by ErikEJ** [comment]
An early preview of EF Core Power Tools that can create DGML diagrams, migrations and related features (not reverse engineering) using EF Core 3.0 preview 7 is now available.

- You must have latest VS 2019 preview installed (or enable preview features in VS 2019)
- You must have the .NET Core 3.0 SDK and runtime installed. 
- You must install the Microsoft.EntityFrameworkCore.Design 3.0 preview 7 package in you project.

- Any other issue will be added to this comment as they transpire.

- Download and rename the attached file to .vsix, double click to install.

[EFCorePowerTools.vsix.zip](https://github.com/ErikEJ/EFCorePowerTools/files/3489929/EFCorePowerTools.vsix.zip)

**Comment by psoszynski** [comment]
Installed but get (on EF Core 3.0 preview 7) getting: "EF Core Power Tools. Currently only .NET Framework and .NET Core 2.0 projects are supported - TargetFrameworkMoniker: .NETCoreApp,Version=v3.0". Any idea why?

**Comment by ErikEJ** [comment]
I forgot to update the vsix version, it should be 2.3 now (new -zip file up)

**Comment by ErikEJ** [comment]
This is now in the latest daily build (preview8 bits)
