### ISSUE TITLE
EFCorePowerTools in Mac: what are the options?

### ISSUE THREAD

**Issue by kostoman69** [ErikEJ/EFCorePowerTools#2180]
CATEGORY: ask a question.

Q: For the users that do not use Visual Studio, you suggested a cross platform dotnet tool for reverse engineering  (preview edition). The link that provides information about that tool is currently dead!!! (https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/efcpt.7/readme.md). Especially now, that Microsoft discontinues Visual Studio for Mac and recommends to start developing C# projects using VS Code, is there any plan to have EF Power Tools as a VS Code extension?

**Comment by ErikEJ** [comment]
Where did you find the link, it will get it fixed (there has been some restrcuture lately)

For VS Code and Mac, you can use my EF Core Power Tools CLI, it is no longer in preview (where did you see my suggestion) ?

**Comment by kostoman69** [comment]
> where did you see my suggestion) ?

https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering
Section Requirements second paragraph

**Comment by ErikEJ** [comment]
Thanks, updated
