### ISSUE TITLE
File-scoped namespaces

### ISSUE THREAD

**Issue by ddulkevich-entrypoint** [ErikEJ/EFCorePowerTools#2181]
Is it possible to disable file-scoped namespace syntax in generated files?

- EF Core Power Tools version: 2.6.140

- Exact Visual Studio version: Visual Studio 2022 17.8.6

- EF Core version in use: EF Core 7

**Comment by ErikEJ** [comment]
If you target EFCore 6, yes, or use t4 templates

**Comment by ddulkevich-entrypoint** [comment]
@ErikEJ We have a project started with .NET Core 3.x. There are a lot of files without file-scoped syntax. We've decided not to remove the braces from namespaces, and we'd also like to have the generated files in the same style.

It would be great if EFCorePowerTools had an option to generate files with braces.

**Comment by ErikEJ** [comment]
Thanks. I think it is relatively simple to do with the t4 templates
