### ISSUE TITLE
Handlebars C# on-model-creating

### ISSUE THREAD

**Issue by tkardaridis** [ErikEJ/EFCorePowerTools#2187]
Hi, I would like to ask a question.
I have split my DbContext into two files, the AppDbContextBase one with a few DbSets that i don't want to reverse engineer with EF Core PowerTools and the AppDbContext that inherits from base and this is the one generated always by EF Core PowerTools. I hava enabled the handlebars in order to change the inheritance of the context file to inherit from my Base but i need also to add the following 

base.OnModelCreating(modelBuilder);

in on-model-creating in order the generated cotnext to call also the model creating of the base. How can i do that?
Any suggestions?

**Comment by ErikEJ** [comment]
@tkardaridis Should be simple to do with the t4 templates, I am not a Handlebars expert
