### ISSUE TITLE
Cannot connect to MySQL server with custom port in connection string

### ISSUE THREAD

**Issue by DukeGamma** [ErikEJ/EFCorePowerTools#2190]
### Provide steps to reproduce a bug
Cannot use custom port in MySQL connection string, e.g. Server=serveraddress,customport. Attempting to connect will give error until I change the server port to the default 3306 and remove port from connection string.

### Provide technical details

- EF Core Power Tools version: 2.6.140

- Exact Visual Studio version: Visual Studio 2022 (64-bit) 17.9.1

- Database engine: MySQL

- EF Core version in use: EF Core 8

- Is Handlebars templates used: N/A

- Is T4 templates used: N/A

- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
This does not seem like a Power Tools issue

**Comment by justinpenguin45** [comment]
Same issue - sure seems like a power tools issue to me

**Comment by DukeGamma** [comment]
> Same issue - sure seems like a power tools issue to me

It has to be, because it works when I use the default port. It doesn't work if I use a custom port that I've confirmed works with MySQL Workbench.

**Comment by ErikEJ** [comment]
I know too little about MySQL. Can you provide more details with some sample connection string?

**Comment by DukeGamma** [comment]
If I set up my router to forward port 12345 to 3306 on the server hosting MySQL, and use the following connection string it will not connect, but I can connect to MySQL using the MySQL Workbench with port 12345:

`static readonly string connectionString = "Server=serveraddress.synology.me; Port=12345; User ID=dbadmin; Password=dbpassword; Database=dbname";`

If I forward port 3306 to 3306 on the server hosting MySQL and use the following connection string it does work:

`static readonly string connectionString = "Server=serveraddress.synology.me; Port=3306; User ID=dbadmin; Password=dbpassword; Database=dbname";`

**Comment by ErikEJ** [comment]
Thanks  - could you try to connect via a small console app that uses the Pomelo provider?

**Comment by ErikEJ** [comment]
@DukeGamma Ping?
