### ISSUE TITLE
COMException when trying to open Script migrations

### ISSUE THREAD

**Issue by ChrisonSimtian** [ErikEJ/EFCorePowerTools#2191]
I get the following error message when trying to open the Script Migrations resulting from my migrations:
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/2966166/f3e4dd49-7aa0-429d-aafb-4422af198da7)

### Provide steps to reproduce a bug
Create migrations via Migrations Wizzard
Click on the "Script migrations" button at the end of the wizzard

### Provide technical details

- EF Core Power Tools version: 2.6.140
- Exact Visual Studio version: Visual Studio 2022 17.10.0
- Database engine: SQL Server
- EF Core version in use: 8.0.2
- Is Handlebars templates used: no
- Is T4 templates used: no
- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
Issue with VS unable to open .sql files. Fixed in VS 17.9.1 - dunno about preview.

**Comment by ChrisonSimtian** [comment]
Apparently not, anyway glad its not an issue with your power tools and thanks for making this awesome tool 😁
