### ISSUE TITLE
Reverse Engineering Not Setting Int Default Value(0)

### ISSUE THREAD

**Issue by scholarrx-pelka** [ErikEJ/EFCorePowerTools#2196]
EFPT version: 2.6.140
.Net 8/EF Core 8

In MS SQL:
CREATE TABLE [dbo].[TestDefaultValues](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[TestIntDefaultValue] [int] NOT NULL,
	[TestIntDefaultValue2] [int] NOT NULL,
 CONSTRAINT [PK_TestDefaultValues] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

**ALTER TABLE [dbo].[TestDefaultValues] ADD  CONSTRAINT [DF_TestDefaultValues_TestIntDefaultValue]  DEFAULT ((0)) FOR [TestIntDefaultValue]
GO**

ALTER TABLE [dbo].[TestDefaultValues] ADD  CONSTRAINT [DF_TestDefaultValues_TestIntDefaultValue2]  DEFAULT ((2)) FOR [TestIntDefaultValue2]
GO

Reverse engineers to Config file:
  public void Configure(EntityTypeBuilder<TestDefaultValue> entity)
  {
      entity.ToTable("TestDefaultValues", "brx");
      **entity.Property(e => e.TestIntDefaultValue);**
      entity.Property(e => e.TestIntDefaultValue2).HasDefaultValue(2);
      OnConfigurePartial(entity);
  }

Entity:
public partial class TestDefaultValue
{
    public int Id { get; set; }
    public int TestIntDefaultValue { get; set; }
    public int TestIntDefaultValue2 { get; set; }
}

Migration:
  migrationBuilder.CreateTable(
      name: "TestDefaultValues",
      schema: "brx",
      columns: table => new
      {
          Id = table.Column<int>(type: "int", nullable: false)
              .Annotation("SqlServer:Identity", "1, 1"),
          **TestIntDefaultValue = table.Column<int>(type: "int", nullable: false),**
          TestIntDefaultValue2 = table.Column<int>(type: "int", nullable: false, defaultValue: 2)
      },
      constraints: table =>
      {
          table.PrimaryKey("PK_TestDefaultValues", x => x.Id);
      });

SQL:

CREATE TABLE [brx].[TestDefaultValues] (
    [Id] int NOT NULL IDENTITY,
    **[TestIntDefaultValue] int NOT NULL,**
    [TestIntDefaultValue2] int NOT NULL DEFAULT 2,
    CONSTRAINT [PK_TestDefaultValues] PRIMARY KEY ([Id])
);

**Comment by ErikEJ** [comment]
This is by design in EF Core 8.

**Comment by scholarrx-pelka** [comment]
If the reverse engineering would create this configuration: entity.Property(e => e.TestIntDefaultValue)**_.HasDefaultValue(0)_**;
Then the correct default value would be set when creating the table.

Our problem is that we have a stored procedure outside of EF that is nserting values without TestIntDefaultValue and it's failing:

INSERT INTO [dbo].TestDefaultValues([TestIntDefaultValue2])
	VALUES(123)

**Comment by ErikEJ** [comment]
Ah, sorry, missed it was a migration. You cannot rely on round tripping from reverse engineering to migration! It is a choice you make - either one or the other.

**Comment by ErikEJ** [comment]
Because the default .net value is 0, so no need to define it. 

You cannot use the code generated by reverse engineering for migrations.

**Comment by Zarepheth** [comment]
I was having the same problem. The database requires a Default Constraint to automatically populate fields with a default value. However, .Net initializes primitives with a defined default. I am guessing this is messing up the reverse engineering when trying to use the result for a migration.

My work around is to use partial class files to manually add the necessary fluent api calls. To find what/where needs manual attention, I do a diff between the database reverse engineered and the database targeted by the migration.

I was hoping for reverse engineering that would round-trip in a migration, but Erik says that's not possible. 😢 I suspect it would require significant development effort by the EF Core team and 3rd party tool creators.
