### ISSUE TITLE
Computed columns breaking in EF Core 7

### ISSUE THREAD

**Issue by rer145** [ErikEJ/EFCorePowerTools#2199]
### Provide steps to reproduce a bug

I have a table with a computed column. Simply, I have one column called `Name` and a computed column called `NameSortComp`, which calls a user-defined function (scalar value) to generate a "sortable" version of the Name field.  

Example: 
Name = "Court 1"
NameSortComp = "Court 0001"

After upgrading to EF Core 7, I regenerated my entities and configuration files, but a basic add/update entity call to a table with a computed column fails with the following error:

```
Could not save changes because the target table has computed column with a function that performs data access. Please configure your entity type accordingly, see https://aka.ms/efcore-docs-sqlserver-save-changes-and-computed-columns for more information.,

Column 'inserted.NameSortComp' cannot be referenced in the OUTPUT clause because the column definition contains a subquery or references a function that performs user or system data access. A function is assumed by default to perform data access if it is not schemabound. Consider removing the subquery or function from the column definition or removing the column from the OUTPUT clause.
```

See:  https://aka.ms/efcore-docs-sqlserver-save-changes-and-computed-columns

Reading that article, I created a partial class and added the following, and it works.

```
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace MYNAMESPACE.Configurations
{
	public partial class MYTABLENAMEConfiguration
	{
		partial void OnConfigurePartial(EntityTypeBuilder<MYTABLENAME> entity)
		{
			entity.ToTable(x => x.HasTrigger("NameSortComp_Trigger"));
		}
	}
}
```

Should the Reverse Engineer script do this automatically? It's fixable with the partial class, but should this be inside the scope of the tool itself?

### Provide technical details

- EF Core Power Tools version: 2.5.1718

- Exact Visual Studio version: VS 2022 17.9.0 Community (64-bit)

- Database engine: Microsoft SQL Server 2019 (RTM-GDR) (KB5029377) - 15.0.2104.1 (X64)   Aug 16 2023 00:09:21   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 19045: ) (Hypervisor) 

- EF Core version in use: EF Core 7

- Is Handlebars templates used: yes

- Is T4 templates used: no

- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
The tool only discovers triggers, so this is the correct fix.

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by nikriaz** [comment]
@rer145 You fix is a bit confusing, could you please add more details what you exactly did?
Named your scalar function "NameSortComp_Trigger" or it's just dummy name or you actually created dummy empty trigger?

**Comment by ErikEJ** [comment]
@rer145 It is HasTrigger that is important, the name can be anything

**Comment by nikriaz** [comment]
Sounds like the fix above is for EF 7 only. According to the Microsoft Docs referenced above, for EF 8+ correct fix is:

```
public partial class MyDbContext
{
    partial void OnModelCreatingPartial(ModelBuilder modelBuilder)

    {
        modelBuilder.Entity<MYTABLENAME>()
            .ToTable(tb => tb.UseSqlOutputClause(false));
    }
}
```

**Comment by ErikEJ** [comment]
@nikriaz Thanks for sharing!
