### ISSUE TITLE
Overwriting option on the existing models on select/deselect tables

### ISSUE THREAD

**Issue by ydlkrishna** [ErikEJ/EFCorePowerTools#22]
And also, is there any way to overwrite the existing models when we modify the models by select/unselect the tables?

### Steps to reproduce
Include a complete description that I can redo to reproduce the issue.

### Further technical details

Toolbox/Power Tools version: 4.7.568.0

Database engine: SQL Server 2017

Visual Studio or SSMS version: Visual Studio 2017 15.6.5

**Comment by ErikEJ** [comment]
Please clarify - you can remove the unneeded files manually?

**Comment by ydlkrishna** [comment]
Let's take the scenario where couple of tables are modified by adding/removing the columns. If I generate the model, the existing model is not getting overwritten with modifications. Everytime I got to delete the model first and then creat it again.

**Comment by ErikEJ** [comment]
That is not neccessary - please provide detailed repro steps, I am unable to repro. What type of project??

May be a VS issue, have you tried closing and re-opening the solution/project?

**Comment by ErikEJ** [comment]
Any news?

**Comment by ErikEJ** [comment]
Feel free to re-open if you can provide more detailed info
