### ISSUE TITLE
Add time elapsed

### ISSUE THREAD

**Issue by talley** [ErikEJ/EFCorePowerTools#220]
Please add time elapsed(on dialog box) for generating entities.

**Comment by Herdo** [comment]
@talley Could you be a little bit more specific, please?
`Time elapsed` since when?
`dialog box` - on which one?

**Comment by talley** [comment]
Something like "It took 4.34 milliseconds to generate entities" on the dialog box that appear after generating entities.

**Comment by ErikEJ** [comment]
I think there already is time elapsed? Can you share a screen shot of the dialog box?

**Comment by talley** [comment]
![EF Core Dialog](https://user-images.githubusercontent.com/6354720/58047184-7fca3a00-7b15-11e9-84de-186268f811dd.png)

**Comment by talley** [comment]
It will be nice if you can add something like "Model generated successfully in 3.4 milliseconds". Your tool is a life saver.

**Comment by ErikEJ** [comment]
Thanks, I will look into this

**Comment by talley** [comment]
Thank you and May God blesses you!

**Comment by ErikEJ** [comment]
The duration is displayed in the status bar
