### ISSUE TITLE
After reverse engineering a database, subsequent migrations turn some UDF and stored proc output classes into tables

### ISSUE THREAD

**Issue by Zarepheth** [ErikEJ/EFCorePowerTools#2201]
Ask questions.

Do the generated files have extension points where we can tell EF Core to not map certain classes to tables when creating migrations? Specifically, a point we can use outside the generated files so that a subsequent reverse engineering run will not erase our modifications.

**Comment by ErikEJ** [comment]
Why are you mentioning reverse engineering and migrations in the same paragraph? If you use reverse engineering, use other methods than migrations to maintain your schema, using migrations is a pit of failure.

The generated classes are partial, so just create a partial class with your modifications. As mentioned in the wiki, you can completely disable file cleanup, or remove the "autogenerated" header.
