### ISSUE TITLE
Support for previous versions of EFCore Power Tools

### ISSUE THREAD

**Issue by darianf** [ErikEJ/EFCorePowerTools#2202]
I've been using EFCore Power Tools within a .NET 4.8 project using EFCore 3, for several months. That combination was needed due to legacy reasons - other assemblies involved necessitated those versions. I've just switched computer and needed to re-install the extension but support has been dropped for that combination. Can we please have somewhere to download previous versions of the extension?

**Comment by ErikEJ** [comment]
You can find some unsupported older installlers here: https://github.com/ErikEJ/EFCorePowerTools/tree/archive/tools

EF Core 3 has been out of support for more that one year now.

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by kotirouthu** [comment]
> You can find some unsupported older installlers here: https://github.com/ErikEJ/EFCorePowerTools/tree/archive/tools
> 
> EF Core 3 has been out of support for more that one year now.
> 
> If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

Hi Erik,,
Is there anyway to find the version 2.5.1718 . Since we have worked on this version and it's a stable version.

**Comment by ErikEJ** [comment]
@kotirouthu No
