### ISSUE TITLE
Reverse engineering storing procedure issue

### ISSUE THREAD

**Issue by nikriaz** [ErikEJ/EFCorePowerTools#2204]
I specifically love EF Power Tools how it fethes storing procedures, it's really great. 
However, in this particular case it does not work fully automated.

Warning:
```
Unable to get result set shape for procedure 'dbo.GenerateRequests'. Incorrect syntax near 'INCREMENT'.
Invalid object name 'PersonalId_'..
```
and I believe it relates to the way how I deal with Sequences. As of my best knowledge, sequences does not support names as variables. Therefore, to have conditional sequences I use dynamic SQL:

```
DECLARE @SequenceName NVARCHAR(255) = CONCAT('PersonalId_', CAST(@CustomerId AS NVARCHAR(10)));
          DECLARE @SQL NVARCHAR(MAX) = CONCAT('CREATE SEQUENCE ', QUOTENAME(@SequenceName),
                                              ' AS INT START WITH ', @StartValue,
                                              ' INCREMENT BY 1;');
```
                                              
   SP output is pretty traditional: 
   `SELECT RequestId, PersonalId FROM @InsertedIds;  `                                      

It works well. It's also works well when I manually add properties into generated class. EFPT just cannot recognize output shape.

**Comment by ErikEJ** [comment]
What have you tried? Did you read the wiki about the two different result set discovery methods? If neither of these work, you must do the mapping yourself.

**Comment by ErikEJ** [comment]
At any rate  I need a full repro on order to help, not script fragments

**Comment by nikriaz** [comment]
Thank you for quick reply, I totally forgot about SET FMTONLY vs. sp_describe_first_result_set but when tried, latter one didn't help either. Now warning is 
`"Unable to get result set shape for procedure 'dbo.GenerateRequests'. The metadata could not be determined because statement 'EXEC sp_executesql @SQL' in procedure 'GenerateRequests'  contains dynamic SQL.  Consider using the WITH RESULT SETS clause to explicitly describe the result set.."`
but I cannot use WITH RESULT SETS because my dynamic SQL does not produce results (or I don't know how to use it).

I added another file for the same empty partial class that EFPT generates, and it works. I also tried custom mapping, and it also works but reverse engineering still produces warning. So, basically if obtaining result shape for my SP is problematic maybe you just can advise how to get rid of the warning with every generating. 

[sp.zip](https://github.com/ErikEJ/EFCorePowerTools/files/14472417/sp.zip)

**Comment by ErikEJ** [comment]
@nikriaz Thanks - I also need the definition of the "REQUESTS" table in order to repro / investigate.

I have no plans to add a "remove the warning" option:
- You could change the stored procedure definition over time
- The tool or engine could get smarter

**Comment by nikriaz** [comment]
Sent by email
