### ISSUE TITLE
Retain Existing Data Annotations

### ISSUE THREAD

**Issue by mkhalford1304** [ErikEJ/EFCorePowerTools#2209]
Is it possible in the current version of the tool to retain any Validation Data Annotations on the class when running the tool?

If we manually add any to defined classes they are removed when we next run the tool.

Example if we have 
[Required(ErrorMessage = "Invalid Case Qty")]
[Range(1, int.MaxValue, ErrorMessage = "Invalid Case Qty")]
public int? PodCaseQty { get; set; }

after running tool we get
public int? PodCaseQty { get; set; }

**Comment by ErikEJ** [comment]
Look at the comment (and issue) here: https://github.com/ErikEJ/EFCorePowerTools/issues/1441#issuecomment-1850497597
