### ISSUE TITLE
Incorrect POCO class name

### ISSUE THREAD

**Issue by code-fire** [ErikEJ/EFCorePowerTools#221]
Generated POCO class name has not the expected value while reverse-enginneering from DB to models, for table names ending by "ges".
Instead of just removing the latest char 's', it replaces the 'ges' by 'x'.

### Steps to reproduce
Having a table name ending with "ges", like "Oranges" or "Exchanges".
Reverse engineer from DB to models.

POCO class name will be "Organx" or "Exchanx" insteaf of "Orange" or "Exchange".

### Further technical details
EF Core Power Tools version: 2.2.12.0

EF Core version: 2.2.0

Database engine: SQL Server

Visual Studio version: Visual Studio 2017 15.9.12

**Comment by ErikEJ** [comment]
Assume you are using pluralization?

**Comment by ErikEJ** [comment]
@theprateik Maybe you can help, the offending piece of code:

             if (TryInflectOnSuffixInWord(
                 suffixWord,
                new[] { "inges", "anges", "ynges" },
                (s) => s.Remove(s.Length - 3, 3) + "x",
                out newSuffixWord))
            {
                return prefixWord + newSuffixWord;
            }

**Comment by code-fire** [comment]
Yes

David Monticelli
Sent with my iPhone

**Comment by theprateik** [comment]
@ErikEJ sure, I can certainly look into this.

**Comment by jespersh** [comment]
Could we just replace the code with a nuget package to loosen the maintenance of various words?
Thinking about https://github.com/sarathkcm/Pluralize.NET

**Comment by ErikEJ** [comment]
Excellent idea!!

**Comment by ErikEJ** [comment]
PR anyone? 🤡  ?

**Comment by ErikEJ** [comment]
Changed to use a better pluralizer (Pluralize.NET) in latest daily build

**Comment by code-fire** [comment]
thanks

**Comment by jespersh** [comment]
@ErikEJ nice. Didn't take you any time to replace lmao

**Comment by ErikEJ** [comment]
BUT as you can see from the test changes, @jespersh there is no perfect pluralizer

**Comment by jespersh** [comment]
@ErikEJ maybe it should be noted that the pluralizer is for single english words. Looking at https://github.com/sarathkcm/Pluralize.NET/issues/10 it seems like two words

**Comment by ErikEJ** [comment]
As I wrote, I would not consider this a real issue
