### ISSUE TITLE
Microsoft.Data.SqlClient 5.0.0.0 missing

### ISSUE THREAD

**Issue by t-ompal** [ErikEJ/EFCorePowerTools#2211]
Repro steps:

1. Install Exstension
2. Rightclick C# project
3. Select EF Core PowerTools -> Reverse Engineer
4. "Choose your data connection" dialog is displayed
5. Select: Add... -> Add Database Connection

The following error dialog is displayed:

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/161338963/6a8a8481-3a4b-4257-9e90-bd6d560b605c)

### Provide technical details

- EF Core Power Tools version: 2.6.140

- Exact Visual Studio version:  Visual Studio 2022 17.9.2

_Info below deemed irrelevant since it never gets that far._

- Database engine: SQL Server
- EF Core version in use: (e.g. EF Core 7)
- Is Handlebars templates used: no/yes
- Is T4 templates used: no/yes
- Is a SQL Server .dacpac used: no/yes

**Comment by ErikEJ** [comment]
This is a Visual Studio error. Try a repair

**Comment by t-ompal** [comment]
Repai fixed it.

**Comment by ErikEJ** [comment]
If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by PolkageistHS** [comment]
I have the same issue when trying to view the database tables or refresh from an efpt.config.json file.  Repair has not fixed it.  Visual Studio 17.10.1, ECPT 2.6.287, with zero other add-ons installed.  

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/9247381/d697735c-cb8c-4c56-a0cd-51cf94825559)

**Comment by PolkageistHS** [comment]
Rolling back to VS 2022 17.9.7 does not seem to have fixed it.  I'm not sure what's going on, since it was working until last Friday 6/7 without any issues. Is there an older version of the extension I can download?

**Comment by ErikEJ** [comment]
@PolkageistHS Have you tried a repair?

**Comment by PolkageistHS** [comment]
> @PolkageistHS Have you tried a repair?

Twice, plus the rollback to an earlier VS 2022.  No dice.

**Comment by PolkageistHS** [comment]
@ErikEJ  Full uninstall and reinstall of VS 2022 did not fix it. 

However, changing the EF Core version in the GUI from 8 to 7 does display the Table Selector window without giving that error. I'm able to run it only with EF Core 7, but not with 8.

**Comment by ErikEJ** [comment]
Ah! Try to nuke the efpt8.x folder in your temp directory, I think it could be the unzipping of the tool that had failed.

**Comment by PolkageistHS** [comment]
That was exactly the issue.  Deleting the folders in Temp cleared it all up.  Thank you so much!
