### ISSUE TITLE
Duplicate files when using 2 DB contexts in one project

### ISSUE THREAD

**Issue by maverick543** [ErikEJ/EFCorePowerTools#2213]
We have a strange issue when making updates (adding or refreshing) to the EF Core data project.
In our project there our two datacontexts (on different databases). When adding a table with the powertools extention to one of them we see the code files added to both of the contexts. 

They are in separate folders, the efpt configs have different names like efpt.db1.config.json and all code should be generated in separate folders. 

Project structure (folders)
- DB1
    DB1DbContext.cs
    table1.cs
    etc
- DB2
    DB2DbContext.cs
    tableA.cs
    etc
efpt.db1.config.json
efpt.db2.config.json

When adding table9 to DB1 the new cs is added to the DB1 folder, but also the entire set of .cs files from DB2 is added.

Info:
VS 2022 17.9.2
EFPT 2.6.140
EF Core 8 (.NET 8)
T4 template are used
DB engine: SQL Server

**Comment by ErikEJ** [comment]
Have you consulted the wiki about working with multiple DbContexts?

**Comment by maverick543** [comment]
Yes. https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#using-multiple-dbcontexts-in-the-same-project
we have this setup exactly as described. 
And when updating on of them, we end up with all the files of that one in the other context also.

**Comment by ErikEJ** [comment]
Closing as no repro was provided
