### ISSUE TITLE
Reverse engineer - pluralized navigation property name is wrong

### ISSUE THREAD

**Issue by justinpenguin45** [ErikEJ/EFCorePowerTools#2215]
We have a table named 'premium' - the pluralized form of this table (for relationships) from reverse engineering is 'premia' instead of 'premiums' - is this a bug or is there a way to control this (without affecting other auto generated names)

**Comment by ErikEJ** [comment]
You can exclude it from the pluralizer as described in the wiki.

**Comment by justinpenguin45** [comment]
Thank you. I did not see a way to exclude only particular ones, I thought
it was all or none. Can you provide a link to where it details how to
exclude only certain ones?

**Comment by ErikEJ** [comment]
Sure - https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#pluralization

**Comment by ErikEJ** [comment]
Disable pluralization and use renaming?
