### ISSUE TITLE
its me again, the pre-release guy, support for dotnet 9 prereleases possible?

### ISSUE THREAD

**Issue by notBlubbll** [ErikEJ/EFCorePowerTools#2216]
powertools 2.6..173

dotnet 9 prerelease 1

vs 17.10.0 preview 1.0

efcore 8

after updating the target for net 9 it says

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/149101422/524cf92a-35c3-45c7-b61d-80e9b1681cc4)

**Comment by ErikEJ** [comment]
So you are asking for the ability to use the EF core 8 scaffolding with a net9.0 project?

**Comment by notBlubbll** [comment]
> So you are asking for the ability to use the EF core 8 scaffolding with a net9.0 project?

Indeed, currently when i need to update my generated models i need to either do it manually or change the target version in the csproj to net 8 so efcorepowertools lets me regenerate the context and model definitions and then change back the target to net 9

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

**Comment by notBlubbll** [comment]
> I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

I removed the extension completely and reinstalled, but it sadly still detects the wrong version

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/149101422/cd4cda44-b10e-42fe-b901-33a98aa5f3d1)


![image](https://github.com/ErikEJ/EFCorePowerTools/assets/149101422/adb534e2-e08c-42a6-9cb7-3c4fe338d1ed)

**Comment by ErikEJ** [comment]
Did you download the daily build linked above??

**Comment by notBlubbll** [comment]
> Did you download the daily build linked above??

yes indeed

**Comment by ErikEJ** [comment]
Which exact version?

**Comment by notBlubbll** [comment]
> Which exact version?

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/149101422/56713401-4d0f-4610-b612-373c49c2c048)
that one from vsix as seen in the screenshot and mentioned in it, x.175

**Comment by ErikEJ** [comment]
Ok, let me try to install .net 9 and test

**Comment by ErikEJ** [comment]
Found my bug!

**Comment by notBlubbll** [comment]
> Found my bug!

yeah tried out 2.6.176 and found it to be workin, thanks for your time
