### ISSUE TITLE
Installation error on Windows on Arm64

### ISSUE THREAD

**Issue by ruesan** [ErikEJ/EFCorePowerTools#2217]
Hi,
I got an error while trying to install on a Windows  on Arm64.
Error message and Visual Studio information below.

Am I missing sth.?

Thanks and best regards
Rüdiger

 10.03.2024 21:17:19 - Microsoft VSIX Installer
10.03.2024 21:17:19 - -------------------------------------------
10.03.2024 21:17:19 - vsixinstaller.exe version:
10.03.2024 21:17:19 - 17.9.3177+74e032ebbd
10.03.2024 21:17:19 - -------------------------------------------
10.03.2024 21:17:19 - Command line parameters:
10.03.2024 21:17:19 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Downloads\EF_Core_Power_Tools_v2.6.140.vsix
10.03.2024 21:17:19 - -------------------------------------------
10.03.2024 21:17:19 - Microsoft VSIX Installer
10.03.2024 21:17:19 - -------------------------------------------
10.03.2024 21:17:20 - Initializing Install...
10.03.2024 21:17:20 - Er wird nach passenden Produkten gesucht...
10.03.2024 21:17:21 - Installiertes Produkt gefunden - Visual Studio Enterprise 2022
10.03.2024 21:17:21 - Installiertes Produkt gefunden - Globaler Pfad
10.03.2024 21:17:21 - Erweiterungsdetails...
10.03.2024 21:17:21 - 	Identifier         : f4c4712c-ceae-4803-8e52-0e2049d5de9f
10.03.2024 21:17:21 - 	Name               : EF Core Power Tools
10.03.2024 21:17:21 - 	Author             : ErikEJ
10.03.2024 21:17:21 - 	Version            : 2.6.140
10.03.2024 21:17:21 - 	Description        : Useful design-time DbContext features, added to the Visual Studio Solution Explorer context menu.

When right-clicking on a C# project, the following context menu functions are available:
Reverse Engineer - Generates POCO classes, derived DbContext and Code First mapping for an existing database or SQL Server Database project (.dacpac).
Migrations Tool - Manage EF Core Migrations in the project: View status, Add Migration, Update Database
Add DbContext Model Diagram - Adds a DGML graph from your DbContext Model.
View DbContext Model SQL DDL - View a SQL DDL script from your DbContext Model.
About - Displays version and other diagnostic information about your Visual Studio instance. 
        
10.03.2024 21:17:21 - 	Locale             : en-US
10.03.2024 21:17:21 - 	MoreInfoURL        : https://github.com/ErikEJ/EFCorePowerTools/wiki/
10.03.2024 21:17:21 - 	InstalledByMSI     : False
10.03.2024 21:17:21 - 	SupportedFrameworkVersionRange : [4.8,)
10.03.2024 21:17:22 - 	SignatureState     : ValidSignature
10.03.2024 21:17:22 - 	SignedBy           : Open Source Developer, Erik Ejlskov Jensen
10.03.2024 21:17:22 - 	Certificate Info   : 
10.03.2024 21:17:22 - 		-------------------------------------------------------
10.03.2024 21:17:22 - 		[Subject]       : CN="Open Source Developer, Erik Ejlskov Jensen", O=Open Source Developer, L=Hillerod, S=Zealand, C=DK
10.03.2024 21:17:22 - 		[Issuer]        : CN=Certum Code Signing 2021 CA, O=Asseco Data Systems S.A., C=PL
10.03.2024 21:17:22 - 		[Serial Number] : 1099D484A9FBD3763360BC5422DE0B2E
10.03.2024 21:17:22 - 		[Not Before]    : 17.01.2024 08:23:38
10.03.2024 21:17:22 - 		[Not After]     : 16.01.2025 08:23:37
10.03.2024 21:17:22 - 		[Thumbprint]    : E610BFFCC22D3B9D2FBA806D416A6B115F461710
10.03.2024 21:17:22 - 	Unterstützte Produkte : 
10.03.2024 21:17:22 - 		Microsoft.VisualStudio.Community
10.03.2024 21:17:22 - 			Version : [17.0,18.0)
10.03.2024 21:17:22 - 			ProductArchitecture : amd64
10.03.2024 21:17:22 - 	Verweise           : 
10.03.2024 21:17:22 - 	Voraussetzungen    : 
10.03.2024 21:17:22 - 		-------------------------------------------------------
10.03.2024 21:17:22 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
10.03.2024 21:17:22 - 		Name         : Visual Studio core editor
10.03.2024 21:17:22 - 		Version      : [17.0,)
10.03.2024 21:17:22 - 		-------------------------------------------------------
10.03.2024 21:17:22 - 		Identifier   : Microsoft.VisualStudio.Component.GraphDocument
10.03.2024 21:17:22 - 		Name         : DGML editor
10.03.2024 21:17:22 - 		Version      : [17.0,)
10.03.2024 21:17:22 - 		-------------------------------------------------------
10.03.2024 21:17:22 - 		Identifier   : Microsoft.VisualStudio.Component.VisualStudioData
10.03.2024 21:17:22 - 		Name         : Data sources and service references
10.03.2024 21:17:22 - 		Version      : [17.0,)
10.03.2024 21:17:22 - Signaturdetails...
10.03.2024 21:17:22 - 	Extension is signed with a valid signature.
10.03.2024 21:17:22 - VSIXInstaller.NoApplicableSKUsException: Diese Erweiterung kann auf den derzeit installierten Produkten nicht installiert werden.
   bei VSIXInstaller.ExtensionService.GetInstallableDataImpl(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   bei VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   bei VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   bei VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   bei VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   bei VSIXInstaller.App.Initialize()
   bei System.Threading.Tasks.Task`1.InnerInvoke()
   bei System.Threading.Tasks.Task.Execute()

   
   
Microsoft Visual Studio Enterprise 2022
Version 17.9.2
VisualStudio.17.Release/17.9.2+34622.214
Microsoft .NET Framework
Version 4.8.09032

Installed Version: Enterprise

Visual C++ 2022   00476-80000-00000-AA299
Microsoft Visual C++ 2022

ASP.NET and Web Tools   17.9.197.37128
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.9.197.37128
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   17.9.197.37128
Azure Functions and Web Jobs Tools

C# Tools   4.9.0-3.24121.1+a98c90d56455379836dd5c845b35fa932b00cfa3
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Extensibility Message Bus   1.4.39 (main@e8108eb)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Node.js Tools   1.5.50908.1 Commit Hash:c294679b821c4b8f7f9c6db3827b7655db80fc28
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   6.9.1
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.9.2.2412004+684740676513b3b208d5bd5b7f8786dab8d287b7
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.9.51.1
Microsoft SQL Server Data Tools

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   17.0.30103.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.9.0-3.24121.1+a98c90d56455379836dd5c845b35fa932b00cfa3
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.9.0-beta.23614.3+a521e1cd420beb56c15faf6836184fadd2b7937a
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

Xamarin   17.9.0.138 (d17-9@60c2b9b)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.9.3.0 (remotes/origin/d17-9@f174974f91)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   13.2.2.0 (d17-5/45b0e14)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: d9a6e87
    Java.Interop: xamarin/java.interop/d17-5@149d70fe
    SQLite: xamarin/sqlite/3.40.1@68c69d8
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-5@ca1552d

**Comment by ErikEJ** [comment]
Arm64 is not supported. You can use the CLI on ARM.

**Comment by ErikEJ** [comment]
ARM64 is supported now
