### ISSUE TITLE
Where clause not working

### ISSUE THREAD

**Issue by davidhendrickmb** [ErikEJ/EFCorePowerTools#222]
Hi there,

I'm using EFCorePowerTools in a .Net Std class library and calling it from .Net Core 2.2.
Whenever I try to pass a where condition as below, it does not get send to SQL as you can see in the second screenshot. 
I used the reverse engineer functionality to produce this

![image](https://user-images.githubusercontent.com/18259436/58340889-d650b480-7e44-11e9-8bda-c262d7cf5137.png)

![image](https://user-images.githubusercontent.com/18259436/58340990-1a43b980-7e45-11e9-9085-1893316cdebc.png)

Thanks,
David

**Comment by davidhendrickmb** [comment]
Whats also strange is that when I include another entity, it doesn't actually get including in the SQL call and ends up making a second SQL call.

![image](https://user-images.githubusercontent.com/18259436/58342570-a60b1500-7e48-11e9-8f36-b170c835acd0.png)

**Comment by jespersh** [comment]
This has nothing to do with this project, but the query generator doesn't know what to do with the ".Equals(..., StringComparison.OrrdinalIgnoreCase)".

See this: https://github.com/aspnet/EntityFrameworkCore/issues/1222

**Comment by davidhendrickmb** [comment]
> This has nothing to do with this project, but the query generator doesn't know what to do with the ".Equals(..., StringComparison.OrrdinalIgnoreCase)".
> 
> See this: [aspnet/EntityFrameworkCore#1222](https://github.com/aspnet/EntityFrameworkCore/issues/1222)
> There are some workarounds out there: https://stackoverflow.com/questions/48216762/how-do-i-make-contains-case-insensitive-in-ef-core-2?rq=1

That you for that, I didn't realise it wasn't supported in EF Core, very strange!
Using a standard "==" seems to work and doesn't appear to be case sensitive (we're backed by a SQL DB).

You wouldn't happen to know why there are 2 queries being produced when I'm using the Include would you?

Thanks again.

**Comment by ErikEJ** [comment]
EF Core 2.x has made a decision for you that making 2 calls is smarter
