### ISSUE TITLE
Overwriting

### ISSUE THREAD

**Issue by AlejandroJorba** [ErikEJ/EFCorePowerTools#2225]
I have a relatively large database, and I'm organizing the models into folders. I would like to know if there's a way for all the models to be generated in the same context without overwriting it. Currently, I'm manually creating the context within each folder, copying the DbSets and model builders into the main context of the folder. Is there a way to do this automatically without overwriting it? I speak Spanish and I'm translating this issue with ChatGPT. I wouldn't know how to explain it in English; it seems complicated.  Thank you.
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/74878915/c51560f2-d367-4e54-be63-b12797d7da86)

**Comment by ErikEJ** [comment]
No. You can organise by schema. How would the tool know which folder to.put each entity in???

**Comment by AlejandroJorba** [comment]
This would generate the entities in the 'General' folder and also a context within that same folder
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/74878915/bc587962-c565-40ce-b692-5e39acb859bb)
But if I put 'models' here, it would generate it in the main folder. My question is whether there is a possibility that in the case of choosing the main folder, it doesn't overwrite the previous context but instead adds the new entities?
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/74878915/b241cad6-226d-47cf-809d-909b08162c99)

**Comment by ErikEJ** [comment]
Your best option will be to generate all files in the main folder and add some commands to move them in a efpt.postrun.cmd file
