### ISSUE TITLE
Unable To Generate Many To Many Models

### ISSUE THREAD

**Issue by AlexVPerl** [ErikEJ/EFCorePowerTools#2226]
First, I'd like to thank you for creating and supporting this extension. Its a must have in .NET developer workflow!

I'm having an issue generating Many-To-Many models, I've added a composite key in the join table and tried playing around with options but still not able to generate it. Perhaps you could point out to something that I've missed. 

Thanks in advance!

**Including details below:**

**1st table** 
```
CREATE TABLE [dbo].[Place](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Country] [nvarchar](255) NULL,
	[Region] [nvarchar](255) NULL,
	[City] [nvarchar](255) NULL,
 CONSTRAINT [PK_place] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
```

**2nd table**
```
CREATE TABLE [dbo].[Person](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](max) NULL,
	[DisplayName] [nvarchar](4000) NULL,
	[Description] [nvarchar](4000) NULL,
 CONSTRAINT [PK_person] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
```

**Many-to-many table:**
```
CREATE TABLE [dbo].[Person_Place](
	[PersonId] [int] NOT NULL,
	[PlaceId] [int] NOT NULL,
 CONSTRAINT [PK_Person_Place_1] PRIMARY KEY CLUSTERED 
(
	[PersonId] ASC,
	[PlaceId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Person_Place]  WITH CHECK ADD  CONSTRAINT [FK_Person__Place_Person] FOREIGN KEY([PersonId])
REFERENCES [dbo].[Person] ([Id])
GO

ALTER TABLE [dbo].[Person_Place] CHECK CONSTRAINT [FK_Person__Place_Person]
GO

ALTER TABLE [dbo].[Person_Place]  WITH CHECK ADD  CONSTRAINT [FK_Person_Place__Place] FOREIGN KEY([PlaceId])
REFERENCES [dbo].[Place] ([Id])
GO

ALTER TABLE [dbo].[Person_Place] CHECK CONSTRAINT [FK_Person_Place__Place]
GO
```

**Settings:**
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/6545404/4fd77528-1e11-45be-ab03-78cc0c2381ba)

**Environment details:**
- SQL Server 2022
- .NET 8
- EF 8
- EF Core Power Tools 2.6.140
- VS 2022 17.9.2

**Comment by ErikEJ** [comment]
Try to not use Handlebars! 

And have you updated the templates or are they old?

**Comment by AlexVPerl** [comment]
Thanks for the reply.

I'm using Handlebars to customize generated models & context, if not to use them what should be the alternative?

Templates could be old, how could I check that?

**Comment by AlexVPerl** [comment]
Quick update:

I just tried switching to C# T4 Templates to test it out, but unfortunately the Many-to-many properties are still not generated. 

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/6545404/dbc4efcf-183e-47d7-aa1d-36aa84cb5fc7)

I also selected "Add T4 Scaffolding Templates" option before I tried generating models, I'm assuming this updates the existing templates
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/6545404/4d4c571b-8ef2-427a-8307-6b7665d80a83)

**Comment by ErikEJ** [comment]
Rename your codetemplates folder to get the latest templates

**Comment by ErikEJ** [comment]
Hmm.. I will have a look in a couple of days, see another related issue, so could be a bug.

**Comment by AlexVPerl** [comment]
> Rename your codetemplates folder to get the latest templates

Thanks. Just tried renaming, a new folder was generated with T4 templates only (no handlebars), I then tried to Reverse Engineer using both C# - T4 & C# - T4 (POCO) options but still same result. Including a screenshot of templates for reference:
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/6545404/b7f9439e-579d-442f-83b3-59ab34f05de9)

**Comment by AlexVPerl** [comment]
> Hmm.. I will have a look in a couple of days, see another related issue, so could be a bug.

Much appreciated!

**Comment by ErikEJ** [comment]
@AlexVPerl I am not able to repro, are you selecting all three tables? 

If still stuck, I need your templates af efpt.config.json file

**Comment by AlexVPerl** [comment]
@ErikEJ thank you for trying to reproduce this. 

I also created an empty project w/ separate DB to isolate things and eliminate possibility that there was something in my main solution that was causing this. I used the default EF Core Power Tools settings, just selected "Use Many to many entity".

However, only navigation properties are generated. I'm not able to generate Many-to-many properties (ie: Person.Places or Place.Persons) - what could be wrong?

I'm trying to generate many-to-many mapping properties as shown in this Microsoft documentation: https://learn.microsoft.com/en-us/ef/core/modeling/relationships/many-to-many

**Microsoft Example:**
```
public class Post
{
    public int Id { get; set; }
    public List<PostTag> PostTags { get; } = [];
    **public List<Tag> Tags { get; } = [];**
}

public class Tag
{
    public int Id { get; set; }
    public List<PostTag> PostTags { get; } = [];
    **public List<Post> Posts { get; } = [];**
}

public class PostTag
{
    public int PostsId { get; set; }
    public int TagsId { get; set; }
    public Post Post { get; set; } = null!;
    public Tag Tag { get; set; } = null!;
}
```

I'm sharing all details below, including the efpt.config.json

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/6545404/146f3506-3894-46d1-afc2-d88c4cc6f6b3)

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/6545404/94e4dc1b-0bcf-4bc9-b3c2-67bf5449327a)

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/6545404/dba6e0f3-81bd-44f5-9a18-529b5aebc0e4)

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/6545404/2e770e06-0f1e-4e74-8490-7d4efae0b1c8)

**efpt.config.json**
```
{
   "CodeGenerationMode": 4,
   "ContextClassName": "SampleTestContext",
   "ContextNamespace": null,
   "DefaultDacpacSchema": null,
   "FilterSchemas": false,
   "IncludeConnectionString": false,
   "ModelNamespace": null,
   "OutputContextPath": null,
   "OutputPath": "Models",
   "PreserveCasingWithRegex": true,
   "ProjectRootNamespace": "SampleTestManyToMany",
   "Schemas": null,
   "SelectedHandlebarsLanguage": 2,
   "SelectedToBeGenerated": 0,
   "T4TemplatePath": null,
   "Tables": [
      {
         "Name": "[dbo].[Person]",
         "ObjectType": 0
      },
      {
         "Name": "[dbo].[Person_Place]",
         "ObjectType": 0
      },
      {
         "Name": "[dbo].[Place]",
         "ObjectType": 0
      }
   ],
   "UiHint": "db-1\\sql2022.SampleTest.dbo",
   "UncountableWords": null,
   "UseBoolPropertiesWithoutDefaultSql": false,
   "UseDatabaseNames": false,
   "UseDateOnlyTimeOnly": true,
   "UseDbContextSplitting": false,
   "UseDecimalDataAnnotationForSprocResult": true,
   "UseFluentApiOnly": true,
   "UseHandleBars": false,
   "UseHierarchyId": false,
   "UseInflector": true,
   "UseLegacyPluralizer": false,
   "UseManyToManyEntity": true,
   "UseNoDefaultConstructor": false,
   "UseNoNavigations": false,
   "UseNoObjectFilter": false,
   "UseNodaTime": false,
   "UseNullableReferences": false,
   "UsePrefixNavigationNaming": false,
   "UseSchemaFolders": false,
   "UseSchemaNamespaces": false,
   "UseSpatial": false,
   "UseT4": false
}
```

Generated models:

**Person**
```
public partial class Person
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string DisplayName { get; set; }

    public string Description { get; set; }

    public virtual ICollection<PersonPlace> PersonPlaces { get; set; } = new List<PersonPlace>();
}
```
**Place**
```
public partial class Place
{
    public int Id { get; set; }

    public string Country { get; set; }

    public string Region { get; set; }

    public string City { get; set; }

    public virtual ICollection<PersonPlace> PersonPlaces { get; set; } = new List<PersonPlace>();
}
```
**PersonPlace**
```
public partial class PersonPlace
{
    public int PersonId { get; set; }

    public int PlaceId { get; set; }

    public virtual Person Person { get; set; }

    public virtual Place Place { get; set; }
}
```

**Comment by ErikEJ** [comment]
@AlexVPerl  The three generated classes is what is expected to be generated with your settings,.

I you uncheck "Use many to many entity" the PersonPlace class will not be generated.

**Comment by AlexVPerl** [comment]
Bingo! That worked. I don't know why I understood that option in reverse, I guess perhaps because it wasn't supported by EF Core in previous version so I figured it needed to be checked, but now that I think of it, it totally makes sense!

Thank you so much for clarifying this! 

I also left a 5 star rating in VS Marketplace :)
