### ISSUE TITLE
Reverse Engineering menu options not visible

### ISSUE THREAD

**Issue by efonsecab** [ErikEJ/EFCorePowerTools#2227]
Create a bug report, feature proposal, or ask a question.

NOTICE: A bug report without sufficient technical and repro details and version information WILL BE CLOSED WITHOUT ANY FURTHER ACTION.

### Provide steps to reproduce a bug

The usual options for reverse engineering are not showing up anymore.
<img width="469" alt="image" src="https://github.com/ErikEJ/EFCorePowerTools/assets/3481899/1adcac37-844c-4c08-8aca-2169d7c960a1">

### Provide technical details

- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
2.6.140
- Exact Visual Studio version: (e.g. Visual Studio 2022 17.6.5)
Microsoft Visual Studio Community 2022 (64-bit) - Preview
Version 17.10.0 Preview 2.0

- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)
SQL Server 
- EF Core version in use: (e.g. EF Core 7)
N/A
- Is Handlebars templates used: no/yes
N/A
- Is T4 templates used: no/yes
No
- Is a SQL Server .dacpac used: no/yes
N/A

**Comment by ErikEJ** [comment]
Show me your .csproj - I am guessing it does not target net6.0 or later..
@efonsecab

**Comment by efonsecab** [comment]
> Show me your .csproj - I am guessing it does not target net6.0 or later..
> @efonsecab 

It may have happened after I upgraded to NET 9 Preview

https://github.com/pticostaricags/FairPlayCombined/blob/dev-net90/src%2FFairPlayCombinedSln%2FFairPlayCombined.DataAccess%2FFairPlayCombined.DataAccess.csproj

**Comment by ErikEJ** [comment]
Try the latest daily build!

**Comment by ErikEJ** [comment]
If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by efonsecab** [comment]
> Try the latest daily build!

Thanks. Did not work, but temporarily setting back to NET 8, so the menu shows up gets the job done.

**Comment by ErikEJ** [comment]
Where did you get it from??
