### ISSUE TITLE
CORE80: OnModelCreatingGeneratedProcedures(modelBuilder) is generated but referencing method is not generated

### ISSUE THREAD

**Issue by marc577** [ErikEJ/EFCorePowerTools#2236]
With efcpt running on core 8 in the DBContext file there's a call of the method OnModelCreatingGeneratedProcedures(modelBuilder) created. But the preprocessor directives won't generate the referenced method.

See ReverseEngineerRunner.cs:113 for the call of the method
and 
See SqlServerStoredProcedureScaffolder.cs:108 for the not generated method via preprocessor directives.

This results in a non compilable state running on core 8.

**Comment by ErikEJ** [comment]
@marc577 Assume you are using the Nightly build?

**Comment by ErikEJ** [comment]
I implemented a fix for this in the latest nightly would be grateful if you could try it out.

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by marc577** [comment]
Works for me thank u :)

**Comment by ErikEJ** [comment]
@marc577 Cool, thanks for the heads up!
