### ISSUE TITLE
UiHint is written to config file with any update

### ISSUE THREAD

**Issue by kspdrgn** [ErikEJ/EFCorePowerTools#2237]
"UiHint" is written to the efpt.*.config.json file with any update. This is a team-shared file and causes clobbering changes between team members with different local database names.

This occurs whether "IncludeConnectionString" is true or false. In previous versions, setting "IncludeConnectionString" = false would leave "UiHint" as null, as well as its function of writing the connection string to the code or not..

Please add an option to prevent UiHint from being set at all, the UI could either pre-select the first option or no option.

Alternate solution may be to move "UiHint" to a separate file so it can be managed per user instead of team-shared.

Thanks for the tool!

### Provide technical details

- EF Core Power Tools version: 2.6.173
- Exact Visual Studio version: Visual Studio 2022 17.9.3
- Database engine: SQL Server
- EF Core version in use: EF Core 8
- Is Handlebars templates used: no
- Is T4 templates used: no
- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
You can disable this via Tools/Options as described in the wiki

**Comment by ErikEJ** [comment]
In hindsight, having it in a user specific file/setting would

**Comment by kspdrgn** [comment]
I might just set "Save connection name" to false by default, and let users turn it on if they are working solo. But yeah, moving that one value out of the team file would be the end-game solution. Thanks for the tool sir, we use it every day!

**Comment by ErikEJ** [comment]
Any thoughts about where would be a good place to store it?

- a seperate file next to the current config file? In that case it must be ignored or possibly have an existing ignorable name.

Somewhere else?

**Comment by ErikEJ** [comment]
Looks like it should just be existingname.user to be ignored

**Comment by kspdrgn** [comment]
*.user appears to be the best option, no fancy directory needed then

**Comment by ErikEJ** [comment]
- [ ] Implement .user file options
- [ ] Test with no config at all
- [ ] Test with config
- [ ] test with config and .user file
- [ ] Update wiki (remove Tools/Options option)

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by ErikEJ** [comment]
@kspdrgn Ping - did you manage to verify this?

**Comment by kspdrgn** [comment]
Tested in VS 2022 and I see the UiHint writing to .user file. It even gets auto-hidden from the Solution Explorer's Solution view, nice bonus of using *.user. Tested with multiple connections and it was picking the right one. No issues migrating to the new version, I'll get the rest of my team to try it out.

Thanks! I'll be sure to write a review and encourage my team to as well.

**Comment by ErikEJ** [comment]
Thanks, I will publish a new official release this weekend
