### ISSUE TITLE
Default value exception

### ISSUE THREAD

**Issue by zackhowe** [ErikEJ/EFCorePowerTools#2238]
When using the example t4 template from your repo(https://github.com/ErikEJ/EFCorePowerTools/blob/master/samples/CodeTemplates/EFCore/EntityType.t4), and using an enum type for a field, when generating DbContext, the default value will cause an error.

for example, the OnModelCreating entry for the class will produce something like:
modelBuilder.Entity<MyType>(entity =>
{
   entity.property(e => e.EnumField).HasDefaultValue((byte)0);
};

which will generate an exception when the DbContext is first referenced and the Model is built, as setting your EnumField to Byte 0 is not allowed.

When using the 703 Template, the model was build with

.HasDefaultSqlValue((0)) and worked.

Thoughts:  The DbContext.t4 doesn't know about the enums, so handling it in the OnModelCreating seems challenging (Also do you need to have an option to provide the name of the Default Enum?)

But if DataAnnotations are selected in EFPT, a 
[DefaultValue(EnumType.DefaultEnumValue)] could be added in the Entities...or even a [DefaultValue((EnumType)0)] perhaps?
### Provide technical details

- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
2.6.140

- Exact Visual Studio version: (e.g. Visual Studio 2022 17.6.5)
VS 2022 17.9.4

- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)
SqlServer

- EF Core version in use: (e.g. EF Core 7)
EF Core 8

- Is Handlebars templates used: no/yes
no

- Is T4 templates used: no/yes
yes

- Is a SQL Server .dacpac used: no/yes
no

**Comment by ErikEJ** [comment]
Remove the default value?

**Comment by zackhowe** [comment]
A simple and elegant solution, except I don't "own" the database in this case, so changing the table DDL is not really any option for me.  I'll pursue that with the DB team, but would love to find a way to make the EFPT work even if they want to keep the default value set....  I think the Data Annotation method would be a nice way, but it still leaves an issue if the OnModelCreating method is used for defaults..and am I correct in my guess that the DbContext.t4 knows nothing about the enumList, let alone anything about which value might be "default"?  ie, if my database default was 1 because my enum was enum : byte { Error = 0, Default = 1, AnotherValue = 2 ....}

**Comment by ErikEJ** [comment]
> for example, the OnModelCreating entry for the class will produce something like:
modelBuilder.Entity(entity =>
{
entity.property(e => e.EnumField).HasDefaultValue((byte)0);
};

which will generate an exception when the DbContext is first referenced and the Model is built, as setting your EnumField to Byte 0 is not allowed.

When using the 703 Template, the model was build with

.HasDefaultSqlValue((0)) and worked.

@ajcvickers Thoughts?

**Comment by ErikEJ** [comment]
@zackhowe Wonder if a feature to remove default values from tinyint columns would work? Like I have today for bit columns.

**Comment by ErikEJ** [comment]
I think your best option at this point is to add additional properties in a partial class and map to the underlying byte value.

**Comment by ajcvickers** [comment]
See https://github.com/dotnet/efcore/issues/32539
