### ISSUE TITLE
Reverse Engineer should support IEntityTypeConfiguration

### ISSUE THREAD

**Issue by QuanTran91** [ErikEJ/EFCorePowerTools#224]
Since EF Core 2.0 there is IEntityTypeConfiguration<TEntity>
class CustomerConfiguration : IEntityTypeConfiguration<Customer>
{
  public void Configure(EntityTypeBuilder<Customer> builder)
  {
     builder.HasKey(c => c.AlternateKey);
     builder.Property(c => c.Name).HasMaxLength(200);
   }
}

I would suggest Reverse Engineer should have a option to do that instead a bunch line of code when building entity configuration.
Thanks.

**Comment by bricelam** [comment]
See #100

**Comment by ErikEJ** [comment]
Duplicate
