### ISSUE TITLE
Collection has incorrect name in class generated from many-to-many relationship is a foreign key column is not named xxxId

### ISSUE THREAD

**Issue by philipstratford** [ErikEJ/EFCorePowerTools#2241]
I'm reverse engineering a database which has a many-to-many relationship between the tables `User` and `ContentArea`:
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/7631595/54213ece-3732-43e9-9262-bd20c05b5363)

The resulting `ContentArea` class which gets generated has an `ICollection` property named `Username` rather than the expected `User`:

`public virtual ICollection<User> Username { get; set; } = new List<User>();`

I might be able to overcome this issue by using the renaming feature, but my problem is that in order for that to work I need to uncheck the "Use table and column names directly from the database" option, and without that checked the tool does some pretty aggressive renaming of entities, in my opinion (e.g. `SystemUIText` becomes `SystemUitext`, which is just wrong. `SystemUiText` might be acceptable, but I appreciate that it's hard for the parser to recognise that).

I see from reading [this discussion](https://github.com/ErikEJ/EFCorePowerTools/issues/1053) that it's considered "expected behaviour" for the renaming feature not to work when the "Use table and column names directly from the database" option is enabled, but I'd argue that this is a case for when it would be useful if explicitly including a `efpt.renaming.json` file could still allow entitites to be renamed even with the "User table and column names..." option enabled.

The only option left open to me is to rename the `Username` column on my link table to `UserId` so that EFPT strips off the `Id` part and creates a class with a property named `User` as expected. That's not ideal though, because the name `UserId` doesn't match the primary key column it references or conform to my conventions for naming foreign key columns.

- EF Core Power Tools version: 2.6.140
- Visual Studio version: Community 2022 17.9.0
- Database engine: SQL Server
- EF Core version: EF Core 7
- Is Handlebars templates used: No
- Is T4 templates used: No
- Is a SQL Server .dacpac used: No

**Comment by ErikEJ** [comment]
There are some many ways and opinions here, and I can/will not support them all. If you are very opinionated, t4 templates will be the way to go.
