### ISSUE TITLE
EF Core Power Tools not working

### ISSUE THREAD

**Issue by mhung21** [ErikEJ/EFCorePowerTools#2245]
- EF Core Power Tools version: 2.6.199

- Exact Visual Studio version: VMicrosoft Visual Studio Enterprise 2022 (64-bit) - Version 17.9.3

- Database engine: SQL Server

- EF Core version in use:  EF Core 3

I'm utilizing the Visualize Database Schema (preview) feature. After selecting the data connection and clicking "Ok," nothing happens.

**Comment by ErikEJ** [comment]
What are you connecting to? Can you browse that connection in Server Explorer?

**Comment by mhung21** [comment]
I'm using Server Explorer to interact with the database, so, of course, I can browse in Server Explorer. I've been using EF Core Power Tools version 2.5 normally until yesterday when I updated to version 2.6.199, and since then, I've been unable to use it.

**Comment by ErikEJ** [comment]
Unable to use it with reverse engineering or only the database diagram feature?

Do you have the Firebird DDEX provider installed? Or any other DDEX providers?

**Comment by mhung21** [comment]
I've installed the EF Core Power Pack, so I already have some DDEX providers. When I select reverse engineering, a dialog box pops up briefly and then disappears immediately, so I'm not sure what the content is. Then, when I choose EF Core Power Tools, I only see three options: Visualize Database Schema (preview), Options, and About. 
Note: I'm using .NET Core 3.1

**Comment by ErikEJ** [comment]
Try to remove the Npgsql and Firebird DDEX provider extensions. (And EF Core Power Pack)

Also note that you have limted optiosn, as NET Core 3.1 is no longer supported (I have an old unsupported build if you really need it)

**Comment by mhung21** [comment]
> Try to remove the Npgsql and Firebird DDEX provider extensions. (And EF Core Power Pack)
> 
> Also note that you have limted optiosn, as NET Core 3.1 is no longer supported (I have an old unsupported build if you really need it)

Yes, I really need the old version of EF Core Power Pack, like version 2.5 that I used before. Please share it with me.

**Comment by ErikEJ** [comment]
I assume you mean EF Core Power Tools?

**Comment by mhung21** [comment]
> I assume you mean EF Core Power Tools?

Yes, I meant EF Core Power Tools.

**Comment by ErikEJ** [comment]
In the tools folder in the "archive" branch in the repo you will find an old unsupported installer. But you need to move on from .NET Core 3.1!

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by mhung21** [comment]
Thank you very much
