### ISSUE TITLE
[Bug] Error trying to create model from database

### ISSUE THREAD

**Issue by JulianoAlexandre** [ErikEJ/EFCorePowerTools#2246]
I update the extension with the version 2.6.199, now when I try create EF Core DbContext from my database project, I am receiving this error message: "System.NullReferenceException: Object reference not set to an instance of an object.
   at async Task<List<TableModel>> EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.GetTablesAsync(DatabaseConnectionModel dbInfo, CodeGenerationMode codeGenerationMode, SchemaInfo[] schemas)
   at async Task<bool> EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.LoadDataBaseObjectsAsync(ReverseEngineerOptions options, DatabaseConnectionModel dbInfo, Tuple<List<Schema>, string> namingOptionsAndPath) x 2
   at async Task EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.ReverseEngineerCodeFirstAsync(Project project, string optionsPath, bool onlyGenerate, bool fromSqlProj)"

Simple tables are in my db project, any try to create it generate the error.

My Visual Studio 2022 17.9.5
Database engine: Azure SQL
EF Core version 8.0.2
Is Handlebars templates used: no
Is T4 templates used: no
Is a SQL Server .dacpac: yes

**Comment by ErikEJ** [comment]
Can you share the .dacpac ? (privately)

**Comment by JulianoAlexandre** [comment]
> Can you share the .dacpac ? (privately)

Yes, should I forward it to your email address?

**Comment by ErikEJ** [comment]
@JulianoAlexandre Yes, you can do that

**Comment by JulianoAlexandre** [comment]
Any database project that contains only one table is enough to generate this error message when creating an EF Core DbContext. A workaround is to navigate to efpt.config.json, right-click, select 'EF Core Power Tools - Edit,' and a popup screen will appear.
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/915807/cb3414da-e8ec-4ec5-b2c0-11654a605e4f)
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/915807/6010aab5-7469-46ab-bc93-ab19de67262e)

**Comment by ErikEJ** [comment]
@JulianoAlexandre Could you PLEASE explain how to trigger the error then (not how to work around it) - I do not understand the circumstances.

**Comment by JulianoAlexandre** [comment]
> @JulianoAlexandre Could you PLEASE explain how to trigger the error then (not how to work around it) - I do not understand the circumstances.

After right click in the Database1 project, selecting "Create EF Core DbContext...", I choose the project, in this case, "ClassLibrary1". It directly creates the efpt.config.json file with default values, without showing me the popup to select the tables and parameters I need. The error I mentioned is shown here, in the Extensions. Can you understand the steps I took for this to happen?

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/915807/a68732e2-4a66-4df8-9013-5f28fc19be3b)
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/915807/23cdaa65-b25d-4635-b88b-9d64ef6fcc18)
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/915807/4d5531be-3453-47ea-9ccf-dcbc3c52c172)
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/915807/26362f36-00b7-4038-ad80-98d6756c9e54)
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/915807/7a4f57d4-51d6-4ed0-ad9b-29fd92c7e53f)

**Comment by ErikEJ** [comment]
@JulianoAlexandre Yes,I can now. Will investigate

**Comment by ErikEJ** [comment]
I was not able to repro your exact issue, butI implemented a fix for some related issues in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

**Comment by JulianoAlexandre** [comment]
> I was not able to repro your exact issue, butI implemented a fix for some related issues in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

Hi Erik, thank you, everything is working fine with the 2.6.200 version. :)

**Comment by ErikEJ** [comment]
Thanks for confirming- I will Update the MarketPlace version with this Bug fix soon
