### ISSUE TITLE
Map Postgres stored procedures and functions

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#2251]
- [x] Get list of sprocs/functions
- [x] Get parameters
- [x] Get result set shape
- [x] Create list of NpgsqlParameter with a map of parameter type to NpgSqlDbType
- [x] Inject mapper interface to procedure scaffolder
- [x] Scaffold DbContext and procedure calls
- [x] Scaffold result sets
- [x] Run some smoke testing
- [x] Quote handling!
- [ ] Get someone to test it!

List stored procs and the parameters:

https://dataedo.com/kb/query/postgresql/list-stored-procedures

https://dataedo.com/kb/query/postgresql/list-stored-procedure-parameters

Get result shape:

https://github.com/vb-consulting/NpgsqlRest/blob/master/NpgsqlRest/RoutineSourceQuery.cs

Type mapping:

https://www.npgsql.org/doc/types/basic.html#read-mappings

Data types and aliases:

https://www.postgresql.org/docs/current/datatype.html

**Comment by aarondglover** [comment]
Yes please. No more executeRawSql for.stored procs pls

**Comment by ErikEJ** [comment]
Get result set shape and name:

```sql
    with cte1 as (
        select
            lower(r.routine_type) as type,
            quote_ident(r.specific_schema) as schema,
            quote_ident(r.routine_name) as name,
            proc.oid as oid,
            r.specific_name,
            des.description as comment,
            proc.proisstrict as is_strict,
            proc.provolatile as volatility_option,
            proc.proretset as returns_set,
            (r.type_udt_schema || '.' || r.type_udt_name)::regtype::text as return_type,

            coalesce(
                array_agg(quote_ident(p.parameter_name::text) order by p.ordinal_position) filter(where p.parameter_mode = 'IN' or p.parameter_mode = 'INOUT'),
                '{}'::text[]
            ) as in_params,

            case when r.data_type = 'USER-DEFINED' then null
            else
                coalesce(
                    (array_agg(quote_ident(p.parameter_name::text) order by p.ordinal_position) 
                    filter(where p.parameter_mode = 'INOUT' or p.parameter_mode = 'OUT')),
                    '{}'::text[]
                )
            end as out_params,

            coalesce(
                array_agg(
                    case when p.data_type = 'bit' then 'varbit' else (p.udt_schema || '.' || p.udt_name)::regtype::text end
                    order by p.ordinal_position
                ) filter(where p.parameter_mode = 'IN' or p.parameter_mode = 'INOUT'),
                '{}'::text[]
            ) as in_param_types,

            case when r.data_type = 'USER-DEFINED' then null
            else
                coalesce(
                    (array_agg(case when p.data_type = 'bit' then 'varbit' else (p.udt_schema || '.' || p.udt_name)::regtype::text end 
                               order by p.ordinal_position) 
                    filter(where p.parameter_mode = 'INOUT' or p.parameter_mode = 'OUT')),
                    '{}'::text[]
                )
            end as out_param_types,

            coalesce(
                array_agg(p.parameter_default order by p.ordinal_position) filter(where p.parameter_mode = 'IN' or p.parameter_mode = 'INOUT'),
                '{}'::text[]
            ) as in_param_defaults,

            case when proc.provariadic <> 0 then true else false end as has_variadic,

            r.type_udt_schema,
            r.type_udt_name,
            r.data_type
        from
            information_schema.routines r
            join pg_catalog.pg_proc proc on r.specific_name = proc.proname || '_' || proc.oid
            left join pg_catalog.pg_description des on proc.oid = des.objoid
            left join information_schema.parameters p on r.specific_name = p.specific_name and r.specific_schema = p.specific_schema

        where
            r.specific_schema = any(
                select
                    nspname
                from
                    pg_catalog.pg_namespace
                where
                    nspname not like 'pg_%'
                    and nspname <> 'information_schema'
            )
            and proc.prokind in ('f', 'p')
            and not lower(r.external_language) = any(array['c', 'internal'])
            and coalesce(r.type_udt_name, '') <> 'trigger'
        group by
            r.routine_type, r.specific_schema, r.routine_name,
            proc.oid, r.specific_name, des.description,
            r.data_type, r.type_udt_schema, r.type_udt_name,
            proc.proisstrict, proc.procost, proc.prorows, proc.proparallel, proc.provolatile,
            proc.proretset, proc.provariadic

    ), cte2 as (

        select 
            cte1.schema, 
            cte1.specific_name,
            array_agg(quote_ident(col.column_name) order by col.ordinal_position) as out_params,
            array_agg(
                case when col.data_type = 'bit' then 'varbit' else (col.udt_schema || '.' || col.udt_name)::regtype::text end
                order by col.ordinal_position
            ) as out_param_types
        from 
            information_schema.columns col
            join cte1 on 
            cte1.data_type = 'USER-DEFINED' and col.table_schema = cte1.type_udt_schema and col.table_name = cte1.type_udt_name 
        group by
           cte1.schema, cte1.specific_name

    )
    select
        type,
        cte1.schema,
        cte1.name,
        is_strict,
        volatility_option,

        returns_set,
        coalesce(return_type, 'void') as return_type,

        coalesce(array_length(coalesce(cte1.out_params, cte2.out_params), 1), 1) as return_record_count,
        case 
            when array_length(coalesce(cte1.out_params, cte2.out_params), 1) is null 
            then array[cte1.name]::text[] 
            else coalesce(cte1.out_params, cte2.out_params) 
        end as return_record_names,

        case 
            when array_length(coalesce(cte1.out_param_types, cte2.out_param_types), 1) is null 
            then array[return_type]::text[] 
            else coalesce(cte1.out_param_types, cte2.out_param_types)
        end as return_record_types,

        coalesce(cte1.out_params, cte2.out_params) = '{}' as is_unnamed_record

    from cte1
    left join cte2 on cte1.schema = cte2.schema and cte1.specific_name = cte2.specific_name

```

**Comment by ErikEJ** [comment]
@roji Would you be willing to have a quick glance at the generated code once I get a smoke test up an running here (just for sanity check by an "expert") ? 🙏

**Comment by roji** [comment]
Of course! The coming couple of weeks are pretty easy (am going to be traveling again), but definitely ping me and I'll do my best.

**Comment by ErikEJ** [comment]
@roji (or anyone else) - I am trying to run the Northwind.sql script from the EF Core provider tests, but unable to do so, maybe because it contains the GO keyword - I am trying via both Query Tool and PSQL Tool in "pgadmin 4" 🍜

**Comment by ErikEJ** [comment]
@roji - solved - replaced GO with ;

**Comment by ErikEJ** [comment]
@roji (or others) - I am stuck calling a result returning function with the EF Core **6** provider:

```csharp
            var npgsqlParameters = new []
            {
                new NpgsqlParameter
                {
                    ParameterName = null,
                    Value = CustomerID ?? Convert.DBNull,
                    NpgsqlDbType = NpgsqlTypes.NpgsqlDbType.Varchar,
                },
            };

            var _ = await _context.Set<CustOrderHistResult>().FromSqlRaw("SELECT \"public\".\"CustOrderHist\" ($1)", npgsqlParameters).ToListAsync(cancellationToken);
```

I get this error: : '08P01: bind message supplies 0 parameters, but prepared statement "" requires 1'

**Comment by ErikEJ** [comment]
@roji I changed to using this, was unable to use positional parameters apparently ?

```csharp
 var npgsqlParameters = new []
 {
     new NpgsqlParameter
     {
         ParameterName = "CustomerID",
         Value = CustomerID ?? Convert.DBNull,
         NpgsqlDbType = NpgsqlTypes.NpgsqlDbType.Char,
     },
 };
 var _ = await _context.SqlQueryAsync<CustOrderHistResult>("SELECT * FROM \"public\".\"CustOrderHist\" (@CustomerID)", npgsqlParameters, cancellationToken);

 return _;

```

**Comment by ErikEJ** [comment]
This feature has now been implemented, supporting [SQL Functions returning sets](https://www.postgresql.org/docs/current/xfunc-sql.html#XFUNC-SQL-FUNCTIONS-RETURNING-SET) - will take it from there.

A sample smoke test project with examples of the generated code is available [here](https://github.com/ErikEJ/EFCorePowerTools/tree/master/test/ScaffoldingTester/PostgresTester)

@roji Would be very grateful if you could take a quick look

**Comment by roji** [comment]
@ErikEJ can you point me at the specific file you want me to look at?

Re positional parameters, they're indeed not yet supported in EF (see https://github.com/dotnet/efcore/issues/27377), even though they're supported at the Npgsql ADO.NET level (and are the proper way to do things with PG).

**Comment by roji** [comment]
OK thanks. Here are a couple notes:

* PG has both stored functions and stored procedures - they're two different things. Functions can be embedded anywhere in any query (like any function), and invoking them in isolation is done via `SELECT * FROM func()`. Procedures, on the other hand, are invoked via `CALL proc()`, and cannot be embedded in a larger SQL query (much like SQL Server sprocs); they can also do various things which functions cannot, like control transactions. So at the very least from a naming perspective, what you have in that file are stored functions, not stored procedures. In an ideal world you'd know how to reverse engineer both :)
* The PG provider doesn't generate quotes around identifiers unless they're needed ([see this](https://github.com/npgsql/efcore.pg/blob/main/src/EFCore.PG/Storage/Internal/NpgsqlSqlGenerationHelper.cs#L67)), so it doesn't quote e.g. `public` (that's not needed). Of course, you can absolutely quote it in your reverse-engineering, just saying.
* Regardless, I'd recommend using C# raw string literals (""") to avoid needing to escape double-quotes (unless you need to support old C# versions etc.)

Otherwise looks great!

**Comment by ErikEJ** [comment]
@roji Thanks again. I will most likely only map different function types for postgres then. I assume scalar functions will be simply mapped as DbFunctions?

**Comment by ErikEJ** [comment]
@roji I am mapping everything that returns a result set, and will look a actual stored procedures  and will try to come up with better naming.

**Comment by ErikEJ** [comment]
But first I will await feedback from some early adopters...

**Comment by roji** [comment]
Yeah, scalar functions are just regular functions, like in SQL Server.
