### ISSUE TITLE
Eager Loading (Include) Not Working with reverse engineer, it returning related entity as empty {}

### ISSUE THREAD

**Issue by SufyanHisok** [ErikEJ/EFCorePowerTools#2252]
Hi everyone,
I'm working with EF Core Power Tools for a reverse engineering (database first) approach. I'm trying to write a function that returns header and detail data together, essentially using eager loading to include related entities.

```
my c# code
[HttpGet]
public IActionResult Get()
{
    var obj = _context.Sales
                .Include(s => s.SaleDetails)
                .FirstOrDefault(s => s.SaleId == 224);

    return Ok(obj);
}
```

The problem is, I'm getting sale:detail:{} as empty even though there's data in the database. This only happens with my reverse-engineered project. In another project using a code-first approach (without power tool), the code works perfectly.

Is there something I'm missing with reverse engineering that might be causing this issue?

**Comment by ErikEJ** [comment]
I need a runnable repro, perferably a console app in order to help. Your code fragments and lack of any details are not what is asked for when you create issues here
