### ISSUE TITLE
Crashed for create reverse engineering for PostgreSQL

### ISSUE THREAD

**Issue by vancodocton** [ErikEJ/EFCorePowerTools#2253]
Create a bug report, feature proposal, or ask a question.

NOTICE: A bug report without sufficient technical and repro details and version information WILL BE CLOSED WITHOUT ANY FURTHER ACTION.

### Provide steps to reproduce a bug
After I tried to edit Host input to create new PostgreSQL Database Connection, VS is not responding, and then crashed.

### Provide technical details

- EF Core Power Tools version: 2.6.200

- EF Core Power Pack version: 2.6.140

- Npgsql PostgreSQL Integration 4.1.12

- Exact Visual Studio version: Visual Studio Enterprise 2022 17.9.5

- Database engine: Postgres

- EF Core version in use: EF Core 7

- Is Handlebars templates used: no

- Is T4 templates used: yes

- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
Make sure the Firbird extension is up to date or try to remove it.

**Comment by vancodocton** [comment]
I've already updated latest `BlackBirdSql`. Disabling it will fix my issue.

**Comment by ErikEJ** [comment]
@Blackbirdsql FYI

I will remove it from the EF Core Power Pack until the Npgsql DDEX provider has been updated.

Feel free to uninstall - I will publish a new Power Pack very soon

**Comment by ErikEJ** [comment]
I have published a EF Core Power Pack without the Firebird DDEXprovider
