### ISSUE TITLE
Oracle - reverse engineering - Database objects are still processing and not displayed at all

### ISSUE THREAD

**Issue by KonradBartnicki** [ErikEJ/EFCorePowerTools#2255]
Hello,
I have problem with displaying Database Objects while using reverse engineering with Oracle.
Query which is executed on DB:

```
select u.*, v.trigger_name, v.table_name, v.column_name, v.table_owner from (SELECT
   sys_context(:"SYS_B_0", :"SYS_B_1") as schema,
   c.table_name,
   c.column_name,
   c.column_id,
   c.data_type,
   c.char_length,
   c.data_length,
   c.data_precision,
   c.data_scale,
   c.nullable,
   c.identity_column,    c.collation,    c.data_default,
   c.virtual_column,
   c.hidden_column 
FROM user_tab_cols c
INNER JOIN  (select distinct object_name as table_name from user_objects where object_type in (:"SYS_B_2", :"SYS_B_3", :"SYS_B_4"))  t 
ON t.table_name=c.table_name
 
WHERE t.table_name <> :"SYS_B_5"  
```

The heaviest part of this query is selecting triggers. 
Is it possible to select only Views and tables?

### Provide steps to reproduce a bug

1. Click "Reverse engineering"
2. Connect to the Oracle database
3. Database objects do not displayed "Loading database objects"

### Provide technical details

- EF Core Power Tools version: 2..200

- Exact Visual Studio version: (Visual Studio 2022 17.8.5

- Database engine: ORACLE

- EF Core version in use: (e.g. EF Core 7)

- Is Handlebars templates used:NO

- Is T4 templates used: NO

- Is a SQL Server .dacpac used: NO

Best regards,
Konrad

**Comment by ErikEJ** [comment]
This is an Oracle provider implementation issue, you will have to contact Oracle support - /cc @alexkeh
