### ISSUE TITLE
can't install on Microsoft Visual Studio Enterprise 2022 (ARM 64-bit) - Current Version 17.9.5

### ISSUE THREAD

**Issue by sardar97** [ErikEJ/EFCorePowerTools#2257]
i can't install it on Microsoft Visual Studio Enterprise 2022 (ARM 64-bit) - Current
Version 17.9.5

**Comment by ErikEJ** [comment]
Did you check any of the existing issues here? 

Unfortunately, VS ARM64 is not supported because it is crippled.

You can use the command line version for reverse engineering.

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

**Comment by sardar97** [comment]
yes! it is working thank u so much.

**Comment by ErikEJ** [comment]
If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
