### ISSUE TITLE
SQL Server procedures - named parameters

### ISSUE THREAD

**Issue by spaasis** [ErikEJ/EFCorePowerTools#2258]
Hi!

The tool currently generates procedure calling SQL as `EXEC @returnValue = [dbo].[MyProc] @Param1, @Param2` which relies on the order of parameters being static.

It would be more robust if we were using the named parameter syntax, so if someone changes the order of parameters in the procedure (which unfortunately might happen...) the generated code still works: `EXEC @returnValue = [dbo].[MyProc] @Param1=@Param1, @Param2=@Param2`

Can this behavior be achieved via T4 templates, or possibly easy to implement as a configuration flag?

**Comment by ErikEJ** [comment]
I sounds like the code should just be updated to use this syntax always - interested in doing a PR?

**Comment by spaasis** [comment]
Sure, I could have a go 👌 Could you point me to the right direction on where to start looking? I could have a go later today

**Comment by ErikEJ** [comment]
You would need to update: GenerateProcedureStatement in the src\Core\RevEng.Core.60\Procedures\SqlServerStoredProcedureScaffolder.cs file.

You can F5 run the efcpt.8 CLI  project to generate the code (remeber to define a valid command line) and then verify the generated code.
