### ISSUE TITLE
Mark as Auto-Generated

### ISSUE THREAD

**Issue by Wasseratem** [ErikEJ/EFCorePowerTools#226]
I work with EFCorePowerTools and StyleCop.
StyleCop (and a bunch of other linters / analyzers) will respect the comment as Line 1 "// <auto-generated />" and don't lint / analyze the code in these files any more.

Please add the possiblity to add this comment on every auto-gen file EFCorePowerTools generate.

**Comment by ErikEJ** [comment]
I am reluctant to do this, see the discussion here: https://github.com/aspnet/EntityFrameworkCore/issues/5721

**Comment by Wasseratem** [comment]
Well, I see the point of it, but Auto-generated code is auto-generated, so why dont use it?

We could make it optional, so everyone CAN hide the warnings or not.

I mean, the point is: I will never ever change code in autoGen code just to solve warnings for them, because I would do it like 5 times a week, right?! So I could either live with the warnings (what I don't want), solve them (what I don't want) or disable them globaly per project (what is very hard as soon as you have just 1 file more in your whole project when you have autoGen code).

**Comment by ErikEJ** [comment]
Could you give a code example of the code changes required?

**Comment by Wasseratem** [comment]
Sorry, do you mean the code changes I would do to fix those warnings or the changes within the EFCorePowerTools to implement my idea?

**Comment by ErikEJ** [comment]
I mean the code change you want to appear in the generated code

**Comment by Wasseratem** [comment]
Yes, of course.

Just 1 line at the beginning of each file:

`// <auto-generated />`

or, if you want to be a bit more specific:

`// <auto-generated> 
// This code was generated by a EFCorePowerTools. 
// Runtime Version:2.0.50727.42 
// Date: 16.09.2019
//
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> `

Both versions will tell the Roselyn Code Analyzers that warnings are disabled for style code checks.

**Comment by ErikEJ** [comment]
Thanks, given that EF Core Power Tools promotes a workflow where you generate the files over and over this makes sense.

**Comment by Wasseratem** [comment]
That's what I thought. Nice to see that you like my idea.

**Comment by ErikEJ** [comment]
I am tempted to always add this - what do you think?

**Comment by Wasseratem** [comment]
Will be enough for the moment.

Thank you for your work done here. I am using EF Power Core Tools since month in several projects, because I really like the database first approach and it is really really good!

**Comment by ErikEJ** [comment]
Thanks a lot - I would be grateful for a rating or review on VS MarketPlace:

https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools

**Comment by ErikEJ** [comment]
Fixed in latest daily build, please let me know if that solves your issue.

**Comment by Wasseratem** [comment]
Hey Erik,
just downloaded the daily - works like charm! 
Thank you very much!

If you looking for contributors I would be ready to step into the code :)

**Comment by ErikEJ** [comment]
Thanks for confirming.

#197 or #135 would be good starter issues

**Comment by Wasseratem** [comment]
Hi Erik,

sorry for hacking intto this thread, I wanted to go deep into the code tomorow because we have public holiday, sadly I cant get the xaml file running in my VS 2019 prof - I installed WPF / Desktop-tools with Blend, but still gettting errors like:

The property 'DesignWidth' does not exist in XML namespace 'http://schemas.microsoft.com/expression/blend/2008'.

Any idea what to do?

The code itselfs compiles, just can't see any xaml file in the /dialogs

**Comment by ErikEJ** [comment]
Run package restore and build?

**Comment by Wasseratem** [comment]
If you mean with package the nuget packges - yes.
Clean, build, rebuil etc.
I can compile it and even run it (a new vs instance will open when I run), but when I open a xaml in editor mode I got "Invalip markup" with errors (which will not be there when I build)

https://imgur.com/a/LE9J3gI

**Comment by ErikEJ** [comment]
@herdo ?

**Comment by Herdo** [comment]
@Wasseratem Looks like it fails to load the VS SDK assemblies. Do you have that workspace installed?

**Comment by ErikEJ** [comment]
Of course, you

**Comment by ErikEJ** [comment]
Of course, you need to have those installed!
Maybe I need to update the readme?

**Comment by Herdo** [comment]
> 
> 
> Of course, you need to have those installed!
> Maybe I need to update the readme?

Well, that _should_ be obvious when developing a VS extension.
If this isn't the problem, I'll look into it.

**Comment by Wasseratem** [comment]
Well, that was obvious and yes, I installed them :) 
If one of you guys have Discord, would be nice to be able to contribute to this package :) 

Discord: MissedLethalAgain#4938

**Comment by ErikEJ** [comment]
So you are able to proceed now?

**Comment by Wasseratem** [comment]
Sadly not =/ SDK installed, I can build and start in theory, but without having a designer view in xaml this will be a bit harder to develop ;)

**Comment by Herdo** [comment]
> 
> 
> Sadly not =/ SDK installed, I can build and start in theory, but without having a designer view in xaml this will be a bit harder to develop ;) Sorry, if my last message sounded like it!

I highly recommend you to stay away from the XAML designer, as that thing will almost always mess things up in an unexpected way. The XAML code is your friend 😉

**Comment by Wasseratem** [comment]
I see, but it is also not helpfull to have errors shown when the designer are open, that will not lead to a failed build when building it... so I want to solve this issue, to get a clean start, sorry to bother u boys.

**Comment by Herdo** [comment]
> 
> 
> I see, but it is also not helpfull to have errors shown when the designer are open, that will not lead to a failed build when building it... so I want to solve this issue, to get a clean start, sorry to bother u boys.

You can just collapse the designer.

**Comment by ErikEJ** [comment]
@Wasseratem Are you working on a specific new feature? In that case, maybe we should have a deisgn chat first? 
We can chat on Gitter: https://gitter.im/EFCorePowerTools/community?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by Varorbc** [comment]
@ErikEJ whether it can be used as an option, I do not want to generate this mark.

**Comment by ErikEJ** [comment]
Just remove the line, and the file will be left

**Comment by Varorbc** [comment]
@ErikEJ My database has many tables, if I delete them one by one, it will become very complicated

**Comment by ErikEJ** [comment]
Why do you want to not have the autogenerated tag?

**Comment by Varorbc** [comment]
Because it will not be formatted by VS, I suggest adding this tag to the custom template. I generated it through a custom template. Obviously there is no such tag, but the generated file does carry this tag

**Comment by ErikEJ** [comment]
I did not understand any of that, sorry. Maybe you need to provide some examples.

**Comment by Varorbc** [comment]
As an option, it might be better for users to choose

**Comment by ErikEJ** [comment]
@herianp this is a closed issue and I have no idea what "message" you are referring to. Please open a new issue with requested details and repro steps.
