### ISSUE TITLE
Table Renaming is not working (or im doing wrong?)

### ISSUE THREAD

**Issue by M4rtinSc** [ErikEJ/EFCorePowerTools#2260]
### Provide steps to reproduce a bug
- Open Existing EFCPT Config by rightclick and edit.
- Go to tables press [F2] and give a new name
- Refresh
- Context ist not set with new name

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/72416103/10b12bc8-3e8b-496b-9d84-a313c07e8d5e)

### Provide technical details
- EF Core Power Tools version: 2.6.140
- Exact Visual Studio version: 17.9.3
- Database engine: SQL Server
- EF Core version in use: EFcore 8
- Is Handlebars templates used: no
- Is T4 templates used: yes
- Is a SQL Server .dacpac used: yes --> Databaseproject

**Comment by M4rtinSc** [comment]
Just the official VS Extension, launched from the context menu in VS

**Comment by ErikEJ** [comment]
Can you provider a simple SQL script for a sample table, and I will have a look

**Comment by ErikEJ** [comment]
I am unable to repro

**Comment by M4rtinSc** [comment]
The problem is the setting "UseDatabaseNames": true

Sample project attached
[Database1.zip](https://github.com/ErikEJ/EFCorePowerTools/files/14913975/Database1.zip)

**Comment by ErikEJ** [comment]
This is by design, you can't have both.
