### ISSUE TITLE
#nullable -annotations not set for procedures

### ISSUE THREAD

**Issue by spaasis** [ErikEJ/EFCorePowerTools#2261]
### Provide steps to reproduce a bug

Reverse engineering a SQL Server database with procedures generates the `#nullable` annotations to the file start as expected for the entities, but the `IContextProcedures` interface or the implementation do not have the annotations. This leads to type confusion when the application at large expects nullable references to work.

Is this something to be added to WriteDbContextInterface/WriteDbContext in SqlServerStoredProcedureScaffolder? 

### Provide technical details

- EF Core Power Tools version: 2.6.200

- Exact Visual Studio version: Visual Studio 2022 Version 17.8.6

- Database engine: SQL Server

- EF Core version in use: EF Core 8

- Is Handlebars templates used: no

- Is T4 templates used: no

- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
@spaasis Yes, it looks like an ommision from when the Interface class was introduced. A PR? 😄

**Comment by spaasis** [comment]
@ErikEJ Setting the actual annotation is simple enough, but how should this thing actually work..

If I have a proc with:
```
CREATE PROCEDURE [dbo].[USP_MyProc]
				@MyParam varchar(50) = NULL,
```
Then the generated interface is
`Task<List<USP_MyProcResult>> USP_MyProcAsync(string MyParam, CancellationToken cancellationToken = default);`

Note that `string MyParam` is not `string?` so the nullability of the param is currently not correctly set.
Is this a bug or intended behavior?

If it's intended, we could always set `#nullable disable` to signify that all parameters are nullable by default.

**Comment by spaasis** [comment]
And the implementation of the above proc:

```
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                    ParameterName = "MyParam",
                    Size = 50,
                    Value = KuntaNimi ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },

```

**Comment by spaasis** [comment]
@ErikEJ okay, so it should be sufficient then to just hardcode the `#nullable disable` in these two files. I'll have a PR up soon

**Comment by ErikEJ** [comment]
Correct

**Comment by ErikEJ** [comment]
Wonder why no one else has reported this?

**Comment by spaasis** [comment]
I wondered about the same thing.. Possibly the combination of nullable reference types + stored procs is rare?
