### ISSUE TITLE
Project table relationships are not generating correctly

### ISSUE THREAD

**Issue by kinetiq** [ErikEJ/EFCorePowerTools#2264]
### Provide steps to reproduce a bug

Hard to say exactly... I just run Reverse Engineer. We have a database with around 100 tables, and starting today, regeneration works fine everything  *except* for relationships for the Project table.

Some of the nav properties generate with no problems. Others are just missing.

All other tables are fine, except to the extent that they should have relationships to Project and those nav properties are gone.

I've confirmed that the table appears in the efpt.config.json as expected.

Here's the script for generating the table, if that helps: [Project.txt](https://github.com/ErikEJ/EFCorePowerTools/files/14890903/Project.txt)

Possibly worth noting: we are still generating for EF Core 7 even though we're running 8. The reason is it looked like there were breaking changes when we tried to generate for 8, and we haven't had time to check them out.

Any ideas?

### Provide technical details

- EF Core Power Tools version: 2.6.200 (and also tried it with a previous version)

- Exact Visual Studio version: Visual Studio 2022 17.9.3

- Database engine: Azure SQL

- EF Core version in use: EF Core 8

- Is Handlebars templates used: no

- Is T4 templates used: not here

- Is a SQL Server .dacpac used: no

**Comment by kinetiq** [comment]
I found this warning in Output:

Exception thrown: 'Microsoft.Data.SqlClient.SqlException' in Microsoft.EntityFrameworkCore.Relational.dll
An exception of type 'Microsoft.Data.SqlClient.SqlException' occurred in Microsoft.EntityFrameworkCore.Relational.dll but was not handled in user code
Invalid column name 'ProjectFirmAdminPermissionId'.


That isn't one of our column names.

**Comment by ErikEJ** [comment]
I need a full set of scripts in order to help, not fragments that cannot run. 

Will reopen if you share a usable repro.
