### ISSUE TITLE
Stored Procedures stopped working in new version

### ISSUE THREAD

**Issue by Theunsgk** [ErikEJ/EFCorePowerTools#2265]
I am not 100% sure what the bug is, but I will explain it as well as I can, so hopefully someone can figure it out.
Up to now, all of my projects have all worked perfectly, but yesterday I think the extenstion updated itself, (it got disabled and I just had to enable it), and the all of a sudden when I reverse engineered my usual SQL Express 2022 database, the stored procedures stopped working. Error given: "_The element type 'bethal_auctions_api.DataModels.FetchLoginUsersResult' used in 'SqlQuery' method is not natively supported by your database provider. Either use a supported element type, or use ModelConfigurationBuilder.DefaultTypeMapping to define a mapping for your type._".
To be clear I changed literally nothing surrounding this, or any other, stored procedure, all of them just stopped working. All I did was add another table, which got pulled through perfectly fine.
I thought Id revert the changes made to **bethalauctionsContextProcedures.cs** and **DbContextExtensions.cs** as I could see those were the only files with changes surrounding procedures. This did not fix it however, I get this new error: "_Cannot create a DbSet for 'FetchLoginUsersResult' because this type is not included in the model for the context._"
As a last resort I tried reverting all the files generated by the tool. This made no difference and I still got the above error.

### Technical details

- EF Core Power Tools version: 2.6.211 (also happened exactly the same with 2.6.200, I updated to the daily version to check if it could fix it)

- Exact Visual Studio version: Visual Studio 2022 17.9.5 (Community)

- Database engine: SQL Server 2022 (Express)

- EF Core version in use: EF Core 8 (Project is .NET 8.0)

- Is Handlebars templates used: no

- Is T4 templates used: no

- Is a SQL Server .dacpac used: no

I hope this leads to someone sorting out the issue, or helping me sort it out if its something I am doing wrong. I am pretty  much 
 stuck until this is fixed either way.
 
 Thank you

**Comment by ErikEJ** [comment]
I assume this is a runtime error?

In that  case, which exact EF Core version do you use?

**Comment by Theunsgk** [comment]
Yes it is a runtime error.
I have Microsoft.EntityFrameworkCore.SqlServer 7.0.9 installed. Should I update to the latest version?

**Comment by ErikEJ** [comment]
@Theunsgk I do not understand- you wrote EF Core 8 in the initial post.  If you want to use EF Core 8 you should use EF Core 8.

**Comment by Theunsgk** [comment]
I realize that now. I think the confusion came because I havent changed any settings (Or versions, manually) for EF Core, or Power tools since I started the project, and overlooked updating EF Core itself.
Thank you for your help

**Comment by ErikEJ** [comment]
You are very welcome. 

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
