### ISSUE TITLE
Poco names are pluralized

### ISSUE THREAD

**Issue by Revsol** [ErikEJ/EFCorePowerTools#227]
The current version of pluralization changes the Poco names with 'Data' to 'Datum'.
`ModuleIotData` becomes `ModuleIotDatum`
`ErrorMasterData` becomes `ErrorMasterDatum`
In previous versions it worked correctly and `Data` were at the end of the name.
If i deactivate pluralization, the names are correct but the navigation properties loses their plural.
`Devices = new HashSet<Device>();` becomes `Device = new HashSet<Device>();`

### Expectation
The poco names should be the same as the table names and not be pluralized. In my opinion it makes no sense to pluralize the poco names.
The poco `User` represents a single User and not multiple of them. But the navigation properties should be pluralized.

### Steps to reproduce
- Create a table with `Data` at the end of the name e.g. `MasterData`.
- Use EF Core Powertools to reverse engineer. Choose your Database and the created table.
- Check 'Pluralize or singularize generated object names'
- Click 'OK'

### Further technical details
Visual Studio 19 Enterprise: 16.1.3
EF Core Power Tools version: 2.2.63.0
Database engine: Azure Microsoft SQL Server

**Comment by ErikEJ** [comment]
Sorry, I changed the pluralizer (breaking change), and the conclusion is there is no perfect pluralizer.

**Comment by Revsol** [comment]
Is it possible that some options could be added to:
- Use the table names as poco names
- Pluralize navigation properties

that work independently from each other?

**Comment by ErikEJ** [comment]
Maybe, PRs are accepted

**Comment by ErikEJ** [comment]
I will consider making the previous pluralizer availalable as an option.

**Comment by ErikEJ** [comment]
I have added an option to use the EF6 pluralizer in the latest daily build

Add this to efpt.config.json:

      "UseLegacyPluralizer": true,

Please let me know if that solves your issue

**Comment by jespersh** [comment]
Our current pluralizer doesn't offer much in the way of configuration to adjust to our various demands, and they are many. So I suggest Humanizer.
https://github.com/Humanizr/Humanizer could be configured like this, although I am unsure if it could be used like a drop-in replacement (https://github.com/Humanizr/Humanizer#adding-words):
```csharp 
Vocabularies.Default.AddUncountable("data");
```
I foresee the indexes/indices problem could be solved with this and a checkbox:
```csharp 
Vocabularies.Default.AddSingular("(vert|ind)ices$", "$1ex");
```

Possibly add these configurations to efpt.config.json

**Comment by ErikEJ** [comment]
@Revsol Ping?

**Comment by Revsol** [comment]
@ErikEJ Pong!
Sorry for the late answer, i was around 1000km away ;)
It seems that `"UseLegacyPluralizer":true` is ignored, i have the same result like stated before. And after creating the models with the power tools, the setting is set automatically to `false`.

Tested with EF Core Power Tools version: 2.22.77.0

**Comment by ErikEJ** [comment]
Fixed (to some extent) in latest daily

**Comment by ErikEJ** [comment]
For anyone following this: I have now switched to using Humanizer in the latest daily build (and also have the option to use the EF6 pluralizer)

**Comment by ryanohs** [comment]
Is it possible to access Humanizer's Vocabularies? I have some unusual table names that it is not handling well.

**Comment by ErikEJ** [comment]
No, not at the moment. You could try the legacy pluralizer?

**Comment by ryanohs** [comment]
Yes, I switched to the legacy pluralizer so it at least matches my EF 6 data context now.

An example of the Humanizer problem I had are table names ending in POS (point of sale) all drop the S. The legacy pluralizer converts Campus into "Campu", but I'm used to that bug.
