### ISSUE TITLE
Add an option to strip a prefix from Model names during Reverse Engineering

### ISSUE THREAD

**Issue by jscarle** [ErikEJ/EFCorePowerTools#2271]
It would save a lot of manual renaming if it would be possible to specify one or more prefixes from the entity names. I have a situation where I'm scaffolding hundreds of entities and stored procedures that all have one of several prefixes. For example:
- Authentication_Groups
- Authentication_Users
- Products_Products
- Products_Products_Properties
- Products_Products_Images
And so on...

So, obviously that becomes:
- AuthenticationGroups
- AuthenticationUsers
- ProductsProducts
- ProductsProductsProperties
- ProductsProductsImages

It would be great if I could specify:
- Authentication_
- Products_

To be stripped so that I end up with:
- Groups
- Users
- Products
- ProductsProperties
- ProductsImages

EF Core Power Tools version: 2.6.200
Exact Visual Studio version: Visual Studio 2022 17.9.5
Database engine: Azure SQL
EF Core version in use: EF Core 8
Is Handlebars templates used: no
Is T4 templates used: no
Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
Have you considered regex based renaming - should be able to do the job.

**Comment by jscarle** [comment]
That worked, thanks!

I used the following:

```json
   {
      "ColumnPatternReplaceWith": "",
      "ColumnRegexPattern": "",
      "SchemaName": "dbo",
      "TablePatternReplaceWith": "$1$2$3$4$5",
      "TableRegexPattern": "^([^_]*)_?([^_]*)_?([^_]*)_?([^_]*)_?([^_]*)",
      "UseSchemaName": false
   }
```
