### ISSUE TITLE
Oracle Data source not listed  

### ISSUE THREAD

**Issue by rajeshkotekar** [ErikEJ/EFCorePowerTools#2274]
Oracle Data source not listed to select to proceed further steps.  

NOTICE: A bug report without sufficient technical and repro details and version information WILL BE CLOSED WITHOUT ANY FURTHER ACTION.

### Provide steps to reproduce a bug

Please include a **complete** description of the issue or link to a project that I can run to reproduce the issue.

### Provide technical details

- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)

- Exact Visual Studio version: (e.g. Visual Studio 2022 17.6.5) - VS 2022

- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL) - Oracle 12C

- EF Core version in use: (e.g. EF Core 7)  EF Core 8

- Is Handlebars templates used: no/yes

- Is T4 templates used: no

- Is a SQL Server .dacpac used: no
<img width="429" alt="Oracle Data Source Missing" src="https://github.com/ErikEJ/EFCorePowerTools/assets/19171079/92f80a81-7ab4-4542-ad25-ece883fe679c">

**Comment by ErikEJ** [comment]
Have you installed the Oracle DDEX provider, as described in the docs?

https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#choose-data-source

**Comment by ErikEJ** [comment]
Ping?

**Comment by rajeshkotekar** [comment]
its working !!!

**Comment by ErikEJ** [comment]
Wonderful!

**Comment by ErikEJ** [comment]
If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
