### ISSUE TITLE
Code error in DbContextExtensions.Sync.cs

### ISSUE THREAD

**Issue by chrisclarkecloudappointmentsconz** [ErikEJ/EFCorePowerTools#2277]
Version 2.6.200, run Reverse Engineer against database

This section of DbContextExtensions.Sync.cs changes from;

![Screenshot 2024-04-12 092113](https://github.com/ErikEJ/EFCorePowerTools/assets/112600075/f4f0e9e6-9084-4776-b8ae-362b6834e467)

To;

![Screenshot 2024-04-12 092342](https://github.com/ErikEJ/EFCorePowerTools/assets/112600075/9c7c3a81-8d0c-4ea4-b079-dd852f1b6e92)

Which doesn't compile.
Only started happening recently.
Coincided with MS deciding to upgrade PC from Windows 10 to 11.

Steps to produce bug shown below;

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/112600075/eec617cf-b80f-44e2-86e9-349225f129a3)
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/112600075/5a510e63-1880-4279-8d30-77dbb3080a6c)
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/112600075/f924c177-eba5-4977-9cab-813b72df1f2e)

- EF Core Power Tools version: 2.6.200

- Exact Visual Studio version:  
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/112600075/f7391719-899a-4a7d-8692-2ccc53c261f4)

- Database engine:  SQL Server 2019

- EF Core version in use: 8.0.3

- Is Handlebars templates used: no

- Is T4 templates used: no

- Is a SQL Server .dacpac used: no

Thanks

Chris C.

**Comment by ErikEJ** [comment]
Do you really need to use the non async api?

At any rate fixed in latest daily

**Comment by chrisclarkecloudappointmentsconz** [comment]
Hi Erik,

 

Thanks for your fix, we do appreciate the software.

Where can I get hold of the recent release?

 

We’re looking after ten year old application that was developed before C# had async.

It’s working perfectly well, clients are happy and the software is stable.

 

Updating it to use async would take time, money and undermine the stability of the software.

So, for the moment, we’ll stay with old faithful. 

Regards

Chris Clarke

Consultant

DDI: +64 210 663385
Mobile: +64 2 106 63385
Phone NZ: +64 7 281 1991
Phone AU: +64 2 9098 5971
Email:  ***@***.***> ***@***.*** 
Web:  <http://www.cloudappointments.co.nz/> www.cloudappointments.co.nz

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

**Comment by chrisclarkecloudappointmentsconz** [comment]
Hi Erik,

 

All working well now, thank you.

Regards

Chris Clarke

Consultant

DDI: +64 210 663385
Mobile: +64 2 106 63385
Phone NZ: +64 7 281 1991
Phone AU: +64 2 9098 5971
Email:  ***@***.***> ***@***.*** 
Web:  <http://www.cloudappointments.co.nz/> www.cloudappointments.co.nz

**Comment by ErikEJ** [comment]
If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
