### ISSUE TITLE
How to add Metadata to identity column when create dbcontext

### ISSUE THREAD

**Issue by lijunjiang-amentum** [ErikEJ/EFCorePowerTools#2279]
I am using EF Core 7 template, and try to add Metadata.SetAfterSaveBehavior(PropertySaveBehavior.Ignore)  to entity.Property(e => e.NID).ValueGeneratedOnAdd() for identity column. How can I do that in T4 template? 

Without that metadata code, if identity column is not primary key, EF Core will throw error about can't update identity column when do the entity update. 

Thanks

**Comment by ErikEJ** [comment]
No sure I understand why you need to do this - can yp provide an example that causes this issue.

You should be able to modify the model in a partial class in the OnModelCreatingPartial method anyway.

**Comment by lijunjiang-amentum** [comment]
I find out a way to modify the T4 template to add .Metadata.SetAfterSaveBehavior(PropertySaveBehavior.Ignore) to the autogenerated Identity property. Without this code, the update entity will failed due to the EF try to update the autgenerated identity column if that column is not primary key.


Thanks
