### ISSUE TITLE
Missing Message when Exception is thrown 

### ISSUE THREAD

**Issue by Wasseratem** [ErikEJ/EFCorePowerTools#228]
While working in the codebase it occurs to me, that in a case of a problem within the reverse engineering the try-catch-clause correctly handles the error with a logging but then didn't inform the user about a error. The process breaks silently.

### Steps to reproduce
Hard to reproduce, because it just happened in a case which leads to another bug.

### Further technical details
Latest Version, daily code from 20.06.2019

I would expect a MessageBox een in the case of an error.

**Comment by ErikEJ** [comment]
Please point to the relevant code...

**Comment by Wasseratem** [comment]
ReverseEngineerHandler.cs, Method ReverseEngineerCodeFirst, Line 275-285.
The try catch in this code handles a lot of cases and problems very well, but breaks without e.g. a ShowMessage.

(And - maybe another problem - didn't attempt to try to save the options. 
Just because the rev eng fails, why didn't save the users settings for the next try or just because the user wants to know what he has e.g. missclicked to cause an error)

**Comment by ErikEJ** [comment]
Look at the implementation of _package.LogError

**Comment by Wasseratem** [comment]
Got it, sorry for that!
Btw.: Im finished with the first bug I implemented, but need access to the repo, see GItter :)

**Comment by ErikEJ** [comment]
You do not need access, you fork this repo, create a feature/bug branch, make and test your code changes, and submit a PR for code review
