### ISSUE TITLE
*Procedures.cs missing OnModelCreatingGeneratedProcedures method

### ISSUE THREAD

**Issue by chrisclarkecloudappointmentsconz** [ErikEJ/EFCorePowerTools#2280]
Bug Report 

As part of our EF Power Tools, Reverse Engineer we include a list of Stored Procedures.

In the previous version the generated file CloudAppointmentsEntitiesProcedures.cs would include a OnModelCreatingGeneratedProcedures method;

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/112600075/8440f61a-595b-446f-aa4d-ee85adef2be5)

This is missing from the newly generated file CloudAppointmentsEntitiesProcedures.cs file;

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/112600075/fd434a21-a9e8-42a5-8546-d86268b300d1)

EF Power Tools Version: 
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/112600075/f8846c24-6321-43b3-8727-b1ca3e470436)

Visual Studio: 2022 v17.9.6

No T4 Templates

No Handlebars

SQL Server 2019 database

**Comment by ErikEJ** [comment]
It is no longer needed with EF Core 8

**Comment by chrisclarkecloudappointmentsconz** [comment]
Hi Erik,

 

I am running EF V8;

 



 

But when I start the application it takes exception to the result from the first Stored Procedure (cdCustomData);

 



 

In a different solution, running EF V8 too, I had to get round this by defining the following;

 



 

The EF Power Tools behaviour has changed recently and is causing problems.

Your help would be appreciated.

Regards

Chris Clarke

Consultant

DDI: +64 210 663385
Mobile: +64 2 106 63385
Phone NZ: +64 7 281 1991
Phone AU: +64 2 9098 5971
Email:  ***@***.***> ***@***.*** 
Web:  <http://www.cloudappointments.co.nz/> www.cloudappointments.co.nz

**Comment by ErikEJ** [comment]
Please do not reply on email with screenshots. I cannot see anything on Github.

Please post text of error message and your exact EF Core 8 version.

**Comment by chrisclarkecloudappointmentsconz** [comment]
I am running EF V8;

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/112600075/20b44942-4508-458a-8800-05e022e0f67d)

But when I start the application it takes exception to the result from the first Stored Procedure (cdCustomData);

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/112600075/7557aabb-d437-4dee-b09a-a7a3dd3ff90a)

In a different solution, running EF V8 too, I had to get round this by defining the following;
(Luckily it's only using one store procedure at the moment.)

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/112600075/03a9d1a1-035e-493f-a60a-b4e990dd43c6)

The EF Power Tools behaviour has changed recently and is causing these problems.
Your help would be appreciated.

**Comment by ErikEJ** [comment]
Why was this closed?.

Pls update to EF Core 8.0.4

**Comment by chrisclarkecloudappointmentsconz** [comment]
My apologies for closing it, I've no recollection of doing so.

Entity Framework updated to the most recent version (8.0.4);

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/112600075/fc4477c8-4157-4fca-ac35-98adbd459274)

Unfortunately it hasn't fixed the problem;

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/112600075/5b708826-db8a-45f8-87e6-759c8c70edd0)

**Comment by ErikEJ** [comment]
I need a full runnable repro in order to investigate...

**Comment by chrisclarkecloudappointmentsconz** [comment]
Part of our previous development included a couple of Stored Procedures that used #temp temporary, not variable tables, see below.  Temp tables were required as part of the code was dynamic SQL which updated table values.

We added the following so we could access these procedures;

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/112600075/c0e0ac3c-03fe-4842-9056-312e75b82839)

With the new version of EF Power Tools this causes the crash detailed above.
We're now accessing the procedures outside of EF and all's well - thank you for your help.
(and an invaluable software tool.)

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/112600075/e9aa743f-61bb-4614-823f-a68e20109564)
