### ISSUE TITLE
Wrong generation or conceptual error?

### ISSUE THREAD

**Issue by LudovicoSupernova** [ErikEJ/EFCorePowerTools#2282]
Good morning,

The problem arises when I insert the relationship FK_CarrierRules_UsersCarriers between the tables UsersCarriers and CarrierRules. The goal is to maintain integrity between the "UserId" and "CarrierId" columns, which together form a unique key in both tables.
Conceptually this should all be correct, but by reverse engineering I would expect to get an ICollection of "Carriers" and one of "CarrierRules" within the "Users" entity instead of just one of "UsersCarriers".
I don't understand if I'm doing something wrong.

I enclose the script for generating the tables...
[script.sql.txt](https://github.com/ErikEJ/EFCorePowerTools/files/14994182/script.sql.txt)

...the DB diagram...
![Diagram](https://github.com/ErikEJ/EFCorePowerTools/assets/110176888/83b3601e-6c62-4dd4-9e53-f7d5b0c1bc96)

...the EF Core Advanced option
![EFcore_Advanced](https://github.com/ErikEJ/EFCorePowerTools/assets/110176888/4f52c1d8-5a4f-4cbf-9a4b-b95c86ebfc0e)

Thanks

- EF Core Power Tools version: 2.6.200

- Visual Studio version: Visual Studio 2022 17.9.6

- Database engine: SQL Server Management Studio 15.0.18424.0
                               SQL Server Management Objects (SMO) - 16.100.47021.0+7eef34a564af48c5b0cf0d617a65fd77f06c3eb1
                               Strumenti client di Microsoft Analysis Services - 15.0.19750.0
                               Microsoft Data Access Components (MDAC) - 10.0.19041.4291
                               Microsoft MSXML - 3.0 5.0 6.0 
                               Microsoft .NET Framework - 4.0.30319.42000
                               Sistema operativo - 10.0.19045

- EF Core version in use: EF Core 7

- Is Handlebars templates used: no

- Is T4 templates used: yes

- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
Are you selecting all three tables?

**Comment by LudovicoSupernova** [comment]
Yes, the tables are all selected

**Comment by ErikEJ** [comment]
I will take a look next week.

**Comment by ErikEJ** [comment]
@LudovicoSupernova Issue is the many to many table also references Carriers  so it is not a simple many to many relationship.
