### ISSUE TITLE
Feature: Generate ER diagram (Mermaid)

### ISSUE THREAD

**Issue by sonnemaf** [ErikEJ/EFCorePowerTools#2290]
It would be very nice if the DGML Database diagram could look like an real ER diagram. 

For example this diagram in which you see the Columns in a table together with the type and `PK`, `FK` and maybe `AK` indications.

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/9335559/f0b0f081-d927-4806-9408-eedbb55cd572)

It would also be nice if the PK was shown in bold and if NOT NULL columns would be Italic (for example).

**Comment by ErikEJ** [comment]
@sonnemaf Interesting suggestion - interested in doing a PR?

**Comment by ErikEJ** [comment]
@sonnemaf 

PK/ FK / NULL is already indicated - what are you missing?

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/4169187/f9dbba23-7bf6-4276-8ddc-9bab113d05f2)

Agree the label could be improved, but the data type is available in the tool tip.

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/4169187/863809d3-9d78-4623-a73f-001115e116c6)

**Comment by ErikEJ** [comment]
I will add the data type to the label..

**Comment by ErikEJ** [comment]
And always show the legend if possible

**Comment by ErikEJ** [comment]
@sonnemaf Ping?

**Comment by sonnemaf** [comment]
@ErikEJ can you tell me where the designer can be found in the code. I will have a look at it. I hope it is WPF, I'm good at it.

**Comment by ErikEJ** [comment]
@sonnemaf There is no "designer", I am using the built-in DGML viewer - so it is "just" an XML file.

To update the label, this line just need to be changed to include "shortType" for the label parameter

https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/Core/RevEng.Core.60/Dgml/DatabaseModelToDgml.cs#L65

**Comment by sonnemaf** [comment]
Bummer, I was hoping for an easy implementation. It is not so I think it is not do-able for me. Maybe we should close this Issue.

**Comment by ErikEJ** [comment]
There is no such thing a s "an easy implementation" 😄 

I updated the labels and the legend:

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/4169187/6469f544-1cf7-41df-9190-715b6ede2707)

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

**Comment by ErikEJ** [comment]
@sonnemaf How about this?

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/4169187/f53e9776-8c9e-4e5c-9676-169befe072c4)

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out. (Also install the latest Power Pack)
