### ISSUE TITLE
Reverse Engineer - Mysql database has a table that cannot generate entities

### ISSUE THREAD

**Issue by FANG-Zhiguo** [ErikEJ/EFCorePowerTools#230]
Mysql database has a table that cannot generate entities and has no error messages,
Other tables can generate entities normally

### Steps to reproduce
1. Right-click the project

2. Select "EF Core Power Tools"

3. Choose Reverse Engineer

TABLE DDL:

CREATE TABLE `sys_member_info` (
  `id` int(12) unsigned zerofill NOT NULL AUTO_INCREMENT COMMENT '用户信息主键ID',
  `user_id` int(12) NOT NULL COMMENT '用户ID',
  `id_card` varchar(100) DEFAULT NULL COMMENT '身份证',
  `id_card_is_pass` tinyint(4) DEFAULT '0' COMMENT '身份证是否审核通过：未上传0"／“审核中1”／“审核失败2”／“已认证3”/"已过期4"/"自动认证成功5"/"自动认证失败6"',
  `id_card_pass_time` datetime DEFAULT NULL COMMENT '身份证是否审核通过时间',
  `user_idcard_img` varchar(200) DEFAULT '' COMMENT '用户身份证路径',
  `address` varchar(200) DEFAULT NULL COMMENT '地址',
  `postal` varchar(12) DEFAULT NULL COMMENT '邮政编码',
  `apply_time` datetime DEFAULT NULL COMMENT '身份证申请时间',
  `driver_license` varchar(100) DEFAULT NULL COMMENT '驾驶证',
  `driver_license_is_pass` tinyint(4) DEFAULT '0' COMMENT '驾照是否审核通过：未上传0"／“审核中1”／“审核失败2”／“已认证3”/驾驶证过期4/"自动认证成功5"/"自动认证失败6"',
  `driver_license_pass_time` datetime DEFAULT NULL COMMENT '驾照审核通过时间',
  `driver_license_type` varchar(4) DEFAULT NULL COMMENT '驾驶证类型',
  `user_driver_license_img` varchar(200) DEFAULT NULL COMMENT '用户驾照路径',
  `license_time` datetime DEFAULT NULL COMMENT '驾照领证时间',
  `verify_time` datetime DEFAULT NULL COMMENT '驾照审核时间',
  `is_verify_pass` tinyint(1) DEFAULT '0' COMMENT '人证合一的照片是否审核通过：未上传0"／“审核中1”／“审核失败2”／“已认证3”/"自动认证成功5"/"自动认证失败6"',
  `witness_one_img` varchar(200) DEFAULT NULL COMMENT '认证合一的照片',
  `registration_time` datetime DEFAULT NULL COMMENT '注册时间',
  `user_class` int(5) DEFAULT NULL COMMENT '会员级别',
  `user_car_num` varchar(50) DEFAULT NULL COMMENT '会员卡号',
  `take_time` datetime DEFAULT NULL COMMENT '领身份证日期',
  `expiry_time` datetime DEFAULT NULL COMMENT '身份证证失效日期',
  `licensing_address` varchar(300) DEFAULT NULL COMMENT '身份证领证地址',
  `driving_expiry_time` datetime DEFAULT NULL COMMENT '驾照证失效日期',
  `driving_licensing_address` varchar(400) DEFAULT NULL COMMENT '驾照领证地址',
  `is_delete` tinyint(1) DEFAULT '0' COMMENT '删除 0不删除 1删除',
  `is_show` tinyint(1) DEFAULT '1' COMMENT '0不显示 1显示',
  `operate_user_id` int(12) DEFAULT NULL COMMENT '操作用户ID',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `false_reason` varchar(100) DEFAULT NULL COMMENT '审核不通过原因记录',
  `audit_time` datetime DEFAULT NULL COMMENT '会员审核时间',
  `audit_status` int(1) DEFAULT '0' COMMENT '用户审核状态（0 待提交资料 1 待审核 2 审核通过 3待补充资料）',
  `user_idcard_reverse_img` varchar(200) DEFAULT NULL COMMENT '身份证反面图片路径',
  `comments` varchar(200) DEFAULT NULL COMMENT '备注',
  `sync_middleware_status` tinyint(2) DEFAULT '0' COMMENT '是否已同步到中间件，0：未同步，1：已同步',
  `sync_middleware_time` datetime DEFAULT NULL COMMENT '同步到中间件时间',
  `is_certified` tinyint(1) DEFAULT '1' COMMENT '是否实名认证：1未认证；2已认证',
  `certified_way` tinyint(1) DEFAULT NULL COMMENT '认证方式：1自助认证，2芝麻认证，3京东认证',
  `auto_coupon` int(2) NOT NULL DEFAULT '0' COMMENT '自动发送优惠券，0：未发送，1已发送',
  `top_operator_id` int(12) DEFAULT NULL COMMENT '顶级运营商ID',
  `id_card_input_way` int(1) DEFAULT NULL COMMENT '身份证号码输入方式：1=自动识别，2=手动输入',
  `driver_license_input_way` int(1) DEFAULT NULL COMMENT '驾照号码输入方式：1=自动识别，2=手动输入',
  `hd_certified_result` varchar(2048) DEFAULT NULL COMMENT '华道征信认证结果',
  `td_certified_result` varchar(64) DEFAULT NULL COMMENT '同盾认证结果',
  `meet_status` int(11) unsigned DEFAULT '0' COMMENT '三见面是否审核通过/0 未通过 1 通过',
  `user_driver_license_reverse_img` varchar(200) DEFAULT NULL COMMENT '驾驶副页照路径',
  `driver_license_num` varchar(25) DEFAULT NULL COMMENT '驾驶证档案编号',
  `has_lllegal_records` int(2) DEFAULT NULL COMMENT '是否存在犯罪记录',
  `false_idcard_type` tinyint(2) DEFAULT NULL COMMENT '身份证类型：0 未选中， 1被选中',
  `false_driver_license_type` tinyint(2) DEFAULT NULL COMMENT '驾驶证类型：0 未选中，1被选中',
  `false_witness_one_type` tinyint(2) DEFAULT NULL COMMENT '认证合一类型：0 未选中，1被选中',
  `false_idcard_msg` varchar(200) DEFAULT NULL COMMENT '身份证失败原因',
  `false_driver_license_msg` varchar(200) DEFAULT NULL COMMENT '驾驶证失败原因',
  `false_witness_one_msg` varchar(200) DEFAULT NULL COMMENT '认证合一失败原因',
  PRIMARY KEY (`id`),
  UNIQUE KEY `user_id` (`user_id`),
  KEY `operate_user_id` (`operate_user_id`),
  KEY `idx_id_card` (`id_card`),
  KEY `idx_registration_time` (`registration_time`),
  KEY `idx_driver_license` (`driver_license`)
) ENGINE=InnoDB AUTO_INCREMENT=5056664 DEFAULT CHARSET=utf8 COMMENT='会员扩展信息表';

### Further technical details
EF Core Power Tools version: 2.2.63.0

Database engine:MySQL 5.7 

MySQL for Visual Studio version: 1.2.8

Visual Studio version: Visual Studio 2019 16.1.3

**Comment by ErikEJ** [comment]
@jespersh ???

**Comment by ErikEJ** [comment]
Does the table have a primary key?
Have you looked at the Output window in VS for any error messages?

**Comment by FANG-Zhiguo** [comment]
@ErikEJ 
Thank you for your interest in this issue.

> Does the table have a primary key?
The first column (id) is the primary key of the table.

> Have you looked at the Output window in VS for any error messages?
There are no error messages in the VS output window or completion dialog

**Comment by jespersh** [comment]
I think your problem is the zerofill id. Zerofill is an idea from the devil ;)
https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/753

**Comment by ErikEJ** [comment]
Closing this based on @jespersh comments
