### ISSUE TITLE
entity.HasComment causes a CS0252 under NET 8.0.4

### ISSUE THREAD

**Issue by ercormier** [ErikEJ/EFCorePowerTools#2302]
Create a bug report, feature proposal, or ask a question.

NOTICE: A bug report without sufficient technical and repro details and version information WILL BE CLOSED WITHOUT ANY FURTHER ACTION.

### Provide steps to reproduce a bug

Please include a **complete** description of the issue or link to a project that I can run to reproduce the issue.

### Provide technical details

- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)

- Exact Visual Studio version: (e.g. Visual Studio 2022 17.6.5)

- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)

- EF Core version in use: (e.g. EF Core 7)

- Is Handlebars templates used: no/yes

- Is T4 templates used: no/yes

- Is a SQL Server .dacpac used: no/yes

**Comment by ercormier** [comment]
EF Core Power Tools version: 2.6.200
VS Version: 17.9.6
EF Version: 8.0.4

Connection:
optionsBuilder.UseSqlServer("Data Source=MSSQLDB;Initial Catalog=DB;Integrated Security=True");


Config:
"CodeGenerationMode": 4,
"ContextNamespace": null,
"FilterSchemas": false,
"IncludeConnectionString": true,
"ModelNamespace": null,
"OutputContextPath": null,
"PreserveCasingWithRegex": true,
"Schemas": null,
"SelectedHandlebarsLanguage": 2,
"SelectedToBeGenerated": 0,
"T4TemplatePath": null,

"UiHint": null,
"UncountableWords": null,
"UseBoolPropertiesWithoutDefaultSql": false,
"UseDatabaseNames": false,
"UseDateOnlyTimeOnly": false,
"UseDbContextSplitting": false,
"UseDecimalDataAnnotationForSprocResult": true,
"UseFluentApiOnly": true,
"UseHandleBars": false,
"UseHierarchyId": false,
"UseInflector": true,
"UseLegacyPluralizer": false,
"UseManyToManyEntity": false,
"UseNoDefaultConstructor": false,
"UseNoNavigations": false,
"UseNoObjectFilter": false,
"UseNodaTime": false,
"UseNullableReferences": false,
"UsePrefixNavigationNaming": false,
"UseSchemaFolders": false,
"UseSchemaNamespaces": false,
"UseSpatial": false,
"UseT4": false

**Comment by ErikEJ** [comment]
Ping?

**Comment by ErikEJ** [comment]
@ercormier Please share you .csproj file also

**Comment by ercormier** [comment]
It appears there is something weird going on with my GIT tool , Windows, or VS.  I manually was changing the trouble code in the Context file when I mistakenly deleted extra coding.  When I tried to use GIT to help restore what I deleted it was saying there were no changes to the file.  I finally removed the file from the project and reran EF Power Tools.  This time the Context file did not have the trouble code.


Sent from my iPhone

On May 2, 2024, at 03:44, Erik Ejlskov Jensen ***@***.***> wrote:

﻿

@ercormier<https://github.com/ercormier> Please share you .csproj file also

**Comment by ErikEJ** [comment]
If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
