### ISSUE TITLE
Prefer 'non-async' calls causes invalid code generation

### ISSUE THREAD

**Issue by TimKras** [ErikEJ/EFCorePowerTools#2303]
When using the Code generation with this (global) setting:
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/5257192/35076c8c-5fba-45c2-b723-81462c1d5f45)
There is a problem in the 'DbContextExtensions.Sync.cs' file. The 'await' should be removed.
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/5257192/a6a4ec6f-49c3-4fa9-97fb-bbdc7f59b7ba)

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

**Comment by TimKras** [comment]
Confirmed it is working in the latest daily build.
Thanks a lot!
