### ISSUE TITLE
EF Core 7 cannot be seleted

### ISSUE THREAD

**Issue by janseris** [ErikEJ/EFCorePowerTools#2306]
Hi we use EF Core 7 because there are breaking changes in EF Core 8 which we do not need/want to implement.
I cannot select EF Core 7. I don't know what the difference is but I'd rather generate schema for 7 when using 7.
![obrazek](https://github.com/ErikEJ/EFCorePowerTools/assets/64279914/5ccf0184-ed70-4f89-bcc8-a28c45e0023b)

Version: 2.5.1718

- Visual Studio Community 2022 (64-bit) 17.9.5
- Database engine: MSSQL (SQL Server)
- EF Core version: 7
- Is Handlebars templates used: no
- Is T4 templates used: no
- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
That is an old unsupported extension version  and this is fixed in the latest.

**Comment by janseris** [comment]
Thank you, it latest version it displays correctly.
