### ISSUE TITLE
Many to many entity is scaffolded but it should be navigation property

### ISSUE THREAD

**Issue by janseris** [ErikEJ/EFCorePowerTools#2307]
![obrazek](https://github.com/ErikEJ/EFCorePowerTools/assets/64279914/b76b791a-fe3e-42c1-947a-0be220eca09b)

![obrazek](https://github.com/ErikEJ/EFCorePowerTools/assets/64279914/ed4efdcd-c8d6-4ddb-8af2-1474fe35519c)

Incorrectly generates join entity. Expected result: User has GlobalRole navigation property and the entity is not generated.
![obrazek](https://github.com/ErikEJ/EFCorePowerTools/assets/64279914/64f6b331-3057-49c3-b2e3-13258efd5ec7)

The schema goes like this (primary key consists of two foreign keys in the M:N join table):
![obrazek](https://github.com/ErikEJ/EFCorePowerTools/assets/64279914/c9e5e915-a0e2-4b63-a79b-893decc5d61f)

- EF Core Power Tools version: 2.5.1718

- Exact Visual Studio version: (e.g. Visual Studio 2022 17.9.5)

- Database engine: SQL Server

- EF Core version in use: EF Core 7 but used schema generating option EF Core 8 because there is none else

- Is Handlebars templates used: no

- Is T4 templates used: no

- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
If you want free support, you must provide repro scripts,  not screenshots, and you must use the latest released version of the tool.

**Comment by janseris** [comment]
Thanks I will try latest version

**Comment by janseris** [comment]
> If you want free support, you must provide repro scripts, not screenshots, and you must use the latest released version of the tool.

I have been sponsoring you on GitHub for 21 months btw.

**Comment by ErikEJ** [comment]
Your sponsorship is highly appreciated.

Thanks for the scripts  I will have a closer look.

**Comment by ErikEJ** [comment]
@janseris  This foreign key is wrong, so the table is not a proper many to many table:

```sql
ALTER TABLE [dbo].[V_USER__GLOBAL_ROLE]  WITH CHECK ADD  CONSTRAINT [FK_V_USER__GLOBAL_ROLE_USER] FOREIGN KEY([GlobalRoleID])
REFERENCES [dbo].[USER] ([ID])
```
It should most likely be something like:

```sql
ALTER TABLE [dbo].[V_USER__GLOBAL_ROLE]  WITH CHECK ADD  CONSTRAINT [FK_V_USER__GLOBAL_ROLE_USER] FOREIGN KEY([UserID])
REFERENCES [dbo].[USER] ([ID])
```

**Comment by ErikEJ** [comment]
after making that changes, it get this:

```csharp
public partial class User
{
    public int Id { get; set; }

    public string Email { get; set; }

    public virtual ICollection<GlobalRole> GlobalRoles { get; set; } = new List<GlobalRole>();
}
```

**Comment by janseris** [comment]
Ohhhhhh I am sorry. Thanks for pointing it out.

**Comment by ErikEJ** [comment]
No problem, there usually is a good explanation! 😄
