### ISSUE TITLE
Debugging migrations tools

### ISSUE THREAD

**Issue by SimaoDolores** [ErikEJ/EFCorePowerTools#2308]
Hello. 
I have a big solution and i don't want to compile all the solution every time i want to add a migration. I found that this extension does that. My problem is when I'm doing debugging the error doesn't show which migration failed and i cant copy the error. Is there a workaround? Like showing the error on the console?

**Comment by ErikEJ** [comment]
Have you looked in the Extensions output window?

**Comment by ErikEJ** [comment]
Could you provide more detailed repro steps/ samples code?

**Comment by ErikEJ** [comment]
@SimaoDolores Ping?
