### ISSUE TITLE
ajout composant Razor entityFramework CRUD erreur exception of type system.invalidOperationException

### ISSUE THREAD

**Issue by omarcharifgit** [ErikEJ/EFCorePowerTools#2309]
Create a bug report, feature proposal, or ask a question.
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/27146286/34a6f7e6-b9a4-415a-a326-aa4c67063ef1)

Erreur lors de l’execution du générateur de code selectionné : «exception of type system.invalidOperationException »

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/27146286/4951c9a3-2902-4171-a55e-0e29c4df44a3)

**Comment by ErikEJ** [comment]
This is a Visual Studio and/or Razor question and not related to Power Tools

**Comment by omarcharifgit** [comment]
Dear Erik,

I hope this email finds you well.

Could you please provide me with the appropriate link or contact information where I can report this issue for assistance? I would greatly appreciate any guidance or support you can offer.

Thank you very much for your time and assistance. I look forward to your response.

Best regards,

M. Omar CHARIF KHALIFI / Morocco
Consultant en organisation et système d'information

ALPHA C.S.D.
Tel: 0522 45 00 45
Email: alphacsd1@***@***.***>gmail.com<http://gmail.com/>
Site web: www.alpha.net.ma<http://www.alpha.net.ma/>
________________________________
De : Erik Ejlskov Jensen ***@***.***>
Envoyé : mardi 7 mai 2024 06:28
À : ErikEJ/EFCorePowerTools ***@***.***>
Cc : Charif ***@***.***>; Author ***@***.***>
Objet : Re: [ErikEJ/EFCorePowerTools] ajout composant Razor entityFramework CRUD erreur exception of type system.invalidOperationException (Issue #2309)


This is a Visual Studio and/or Razor question and not related to Power Tools

**Comment by ErikEJ** [comment]
Hi Charif,

I think this repo would be a good placeto start, but you must porvide full detais about your issue, including a reproduction and a full error message.

dotnet/razor: Compiler and tooling experience for Razor ASP.NET Core apps in Visual Studio, Visual Studio for Mac, and VS Code. (github.com)<https://github.com/dotnet/razor>

Mvh / Regards

Erik Ejlskov Jensen
http://twitter.com/erikej
________________________________
