### ISSUE TITLE
Reverse Engineering Model Builder missing ToTable extension method on each entity

### ISSUE THREAD

**Issue by Sejuukhar** [ErikEJ/EFCorePowerTools#231]
Each entity generated in DbContext's OnModelCreating method is missing the "ToTable()" extension method when using table and column names directly from the database. 

### Steps to reproduce
1. Right-click on project and select "EF Core Power Tools" -> "Reverse Engineer"
2. Select or add database connection.
3. Select the tables (not all were chosen), and click OK.
4. On the final prompt, choose "Use table and column names directly from the database" under the "Naming" section.
5. Click OK. 

### Further technical details
EF Core Power Tools version: 2.2.63.0

Database engine: SQL Server 2014

Visual Studio version: Visual Studio 2017 15.9.13

**Comment by ErikEJ** [comment]
I think this is by design, could you show me an example of a CREATE table statement, the generated fluent code, and the code you would expect.

**Comment by Sejuukhar** [comment]
Here's the CREATE table statement:


```
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[sampletable](
        [samplecolumn] [char](10) NULL,
        [id_col] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_sampletable] PRIMARY KEY CLUSTERED 
(
        [id_col] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[sampletable] ADD  CONSTRAINT [df_sampletable_SAMPLECOLUMN]  DEFAULT ('') FOR [samplecolumn]
GO
```


Here's the generated fluent code:

            modelBuilder.Entity<sampletable>(entity =>
            {
                entity.HasKey(e => e.id_col)
                    .HasName("PK_sampletable");

                entity.Property(e => e.samplecolumn)
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasDefaultValueSql("('')");
            });


Here's what I expected:

            modelBuilder.Entity<sampletable>(entity =>
            {
                entity.ToTable("sampletable");

                entity.HasKey(e => e.id_col)
                    .HasName("PK_sampletable");

                entity.Property(e => e.samplecolumn)
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasDefaultValueSql("('')");
            });

**Comment by Sejuukhar** [comment]
I just tried scaffolding my database with PMC using the "-UseDatabaseNames" switch and it produced the same results as your tool. Perhaps this is by design. Is "ToTable()" not needed?

**Comment by Sejuukhar** [comment]
I'm closing this issue because the true cause of the problem has to do with pluralization and the "-UseDatabaseNames" option. It would seem that you can't pluralize your DbSets while preserving the original names. This problem has nothing to do with your tool.
