### ISSUE TITLE
Entity level attributes should use nameof() to facilitate refactoring

### ISSUE THREAD

**Issue by InsanePup** [ErikEJ/EFCorePowerTools#2313]
Not a bug per se, but a definite improvement to usability. When specifying property names, nameof() should be used to facilitate refactoring. Example of where this should be done...

```
[Table("ec_code")]
**[Index("CodeId", Name = "code_id", IsUnique = true)]**
[MySqlCharSet("utf8mb3")]
[MySqlCollation("utf8mb3_general_ci")]
public partial class EcCode
{
```

**Comment by ErikEJ** [comment]
I think this is by design, as nameof us not always correct.

**Comment by ErikEJ** [comment]
See this issue for more context: https://github.com/dotnet/efcore/issues/26588
