### ISSUE TITLE
throw new NotSupportedException("This method can only be called from Entity Framework Core queries"); as the definition of a 

### ISSUE THREAD

**Issue by abukres** [ErikEJ/EFCorePowerTools#2314]
I have a SQL function defined as 

```
CREATE FUNCTION [dbo].[DoSomething]
(
	@param1 VARCHAR(255)
)
RETURNS VARCHAR(255)
AS
BEGIN
	RETURN @param1
END
GO
```

and the EF Power Tool created a C# method:
```
[DbFunction("DoSomething", "dbo")]
public static string DoSomething(string param1)
{
    throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
}
```

Why did the tool create an exception for it and what does the message mean?

A [similar issue](https://github.com/ErikEJ/EFCorePowerTools/issues/1295) has a link to some MS docs link which I didn't understand nor how it's related to the method the tool created.

**Comment by ErikEJ** [comment]
That is how DbFunctions are declared and to prevent it from being called directly (you can only call it in a LINQ query)
