### ISSUE TITLE
SQL Server table valued functions disappeared

### ISSUE THREAD

**Issue by Dimigergo** [ErikEJ/EFCorePowerTools#2317]
In the new version 2.6.262 the functions disappeared. The 2.6.200 is was ok.

[EFCoreFuncBigintPK.zip](https://github.com/ErikEJ/EFCorePowerTools/files/15275206/EFCoreFuncBigintPK.zip)

The db.sql file is my db with "funcGetRes" table valued function.
The "old" version of the EF Core Power Tools generate the funcGetResResult.cs with the properties.
Please check the generated (if generated) ResId property because sometimes it was generated to int? not long?!

Is it a "magic" switch on the new config?

Thanks in advance!

**Comment by ErikEJ** [comment]
It is most likely a bug due to refactroing for Postgres support _ i will investigate

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out. (Build .265 or later)

Once you have verified the fix I will push a new version to VS MarketPlace

**Comment by Dimigergo** [comment]
Thanks, I have tried it, and works well. :)

**Comment by ErikEJ** [comment]
@Dimigergo Thanks for the heads up!

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
