### ISSUE TITLE
Hi Erik, While I'm trying to access the Reverse Engineer the problem I'm facing is either I'm getting the error stating as "'EFCorePowerToolPackage' Package did not load correctly " or I'm getting not error no pop up no nothing just empty it feels exhausting keep on clicking the Reverse engineer for more than 100 times. Can I get the help here. Kind Regards

### ISSUE THREAD

**Issue by krishnna49** [ErikEJ/EFCorePowerTools#2321]
Create a bug report, feature proposal, or ask a question.

NOTICE: A bug report without sufficient technical and repro details and version information WILL BE CLOSED WITHOUT ANY FURTHER ACTION.

### Provide steps to reproduce a bug

Please include a **complete** description of the issue or link to a project that I can run to reproduce the issue.

### Provide technical details

- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)

- Exact Visual Studio version: (e.g. Visual Studio 2022 17.6.5)

- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)

- EF Core version in use: (e.g. EF Core 7)

- Is Handlebars templates used: no/yes

- Is T4 templates used: no/yes

- Is a SQL Server .dacpac used: no/yes

**Comment by krishnna49** [comment]
![Screenshot 2024-05-12 140102](https://github.com/ErikEJ/EFCorePowerTools/assets/120034173/1902561f-f378-4b84-8bfc-de1507453adb)

**Comment by krishnna49** [comment]
This is pop up I'm receiving even though I've tried this using SSMS, MYSQL both are showing the same error.

**Comment by ErikEJ** [comment]
Share your Activitylog.xml file

**Comment by vishwa-sage** [comment]
Can you help me to know the location of this file please?

**Comment by ErikEJ** [comment]
It is shown in the error message, that you can copy to the clipboard
