### ISSUE TITLE
Table Valued Parameters in Stored Procedures from a .dacpac

### ISSUE THREAD

**Issue by HAK-Logos** [ErikEJ/EFCorePowerTools#2322]
### Question:

Does EF Core Power Tools support Table Valued Parameters in Stored Procedures? 
As far as I can see, it only supports simple SQL Types, but I could be wrong.

### Steps to reproduce:

1. Create a stored procedure, having a Table Valued Parameter as input.
2. Include the stored procedure, when choosing "Choose Your Database Objects" in the EF Core Power Tools menu.

#### User Defined Type:

`CREATE TYPE [SomeSchema].[IntegerList] AS TABLE (
    [I] INT NOT NULL,
    PRIMARY KEY CLUSTERED ([I] ASC));`

#### Stored Procedure:

`CREATE PROCEDURE [SomeSchema].[SomeStoredProcedure]
	@SomeParameter1 BIGINT,
	@SomeParameterList1 [SomeSchema].[IntegerList] READONLY
AS
...`

### Exception shown:

`System.ArgumentOutOfRangeException: cleanedTypeName: Constant (Parameter 'storeType')
   at RevEng.Core.Routines.Extensions.SqlServerSqlTypeExtensions.GetSqlDbType(String storeType) in C:\Code\Github\EFCorePowerTools\src\Core\RevEng.Core.60\Routines\Extensions\SqlServerSqlTypeExtensions.cs:line 215
   at RevEng.Core.Routines.Extensions.SqlServerSqlTypeExtensions.GetClrType(String storeType, Boolean isNullable, Boolean asParameter) in C:\Code\Github\EFCorePowerTools\src\Core\RevEng.Core.60\Routines\Extensions\SqlServerSqlTypeExtensions.cs:line 91
   at RevEng.Core.Routines.Extensions.SqlServerSqlTypeExtensions.ClrTypeFromSqlParameter(ModuleParameter storedProcedureParameter, Boolean asMethodParameter) in C:\Code\Github\EFCorePowerTools\src\Core\RevEng.Core.60\Routines\Extensions\SqlServerSqlTypeExtensions.cs:line 72
   at RevEng.Core.Routines.Extensions.SqlServerClrTypeMapper.GetClrType(ModuleParameter parameter) in C:\Code\Github\EFCorePowerTools\src\Core\RevEng.Core.60\Routines\Extensions\SqlServerClrTypeMapper.cs:line 10
   at RevEng.Core.Routines.Procedures.ProcedureScaffolder.<>c__DisplayClass15_0.<CreateUsings>b__4(ModuleParameter p) in C:\Code\Github\EFCorePowerTools\src\Core\RevEng.Core.60\Routines\Procedures\ProcedureScaffolder.cs:line 172
   at System.Linq.Enumerable.Any[TSource](IEnumerable'1 source, Func'2 predicate)
   at RevEng.Core.Routines.Procedures.ProcedureScaffolder.CreateUsings(ModuleScaffolderOptions scaffolderOptions, RoutineModel model, List'1 schemas) in C:\Code\Github\EFCorePowerTools\src\Core\RevEng.Core.60\Routines\Procedures\ProcedureScaffolder.cs:line 172
   at RevEng.Core.Routines.Procedures.ProcedureScaffolder.WriteDbContextInterface(ModuleScaffolderOptions scaffolderOptions, RoutineModel model, List'1 schemas) in C:\Code\Github\EFCorePowerTools\src\Core\RevEng.Core.60\Routines\Procedures\ProcedureScaffolder.cs:line 195
   at RevEng.Core.Routines.Procedures.ProcedureScaffolder.ScaffoldModel(RoutineModel model, ModuleScaffolderOptions scaffolderOptions, List'1 schemas, List'1& errors) in C:\Code\Github\EFCorePowerTools\src\Core\RevEng.Core.60\Routines\Procedures\ProcedureScaffolder.cs:line 118
   at RevEng.Core.ReverseEngineerScaffolder.GenerateStoredProcedures(ReverseEngineerCommandOptions options, List`1 schemas, List`1& errors, String outputContextDir, String modelNamespace, String contextNamespace, Boolean supportsProcedures) in C:\Code\Github\EFCorePowerTools\src\Core\RevEng.Core.60\ReverseEngineerScaffolder.cs:line 215
   at RevEng.Core.ReverseEngineerRunner.GenerateFiles(ReverseEngineerCommandOptions options) in C:\Code\Github\EFCorePowerTools\src\Core\RevEng.Core.60\ReverseEngineerRunner.cs:line 102
` 

### Technical details

- EF Core Power Tools version: 2.6.268

- Exact Visual Studio version: Visual Studio 2022 17.9.2

- Database engine: SQL Server

- EF Core version in use: EF Core 8

- Is Handlebars templates used: no

- Is T4 templates used: yes

- Is a SQL Server .dacpac used: yes

**Comment by ErikEJ** [comment]
Correct, that is not supported, but can you provide a proper repro, you should see a message like this in the outptu window, not an error like above:

`Unable to scaffold FUNCTION 'dbo.FuncWithTvpParameter' as it has TVP parameters.`

**Comment by HAK-Logos** [comment]
Thanks for quick reply! 
I'll try to setup a repro soon and link it to you.

**Comment by HAK-Logos** [comment]
Out of curiosity, will TVP be implemented in the future?

**Comment by ErikEJ** [comment]
> Out of curiosity, will TVP be implemented in the future?

You can map a tvp returning function today. 

But how would you manually code a call using a TVP parameter today (using ADO.NET fo example) ?

**Comment by ErikEJ** [comment]
@HAK-Logos Sorry! Actually, the error above is from Functions with tvp parameters - as far as I can see, stored procedure tvp parameters should be supported (as DataTable), but there could be a regression and I am lacking a good sample for my regression test!

**Comment by HAK-Logos** [comment]
Good, then I'm not going crazy. I was wondering why you were referring to Functions :-) 

So it is possible to include TVP in Stored Procedures, but I'm getting the above error.
Is there anything I can do to help you locate the issue? 

Just for reference, this is the code where it throws the exception:
https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/Core/RevEng.Core.60/Routines/Extensions/SqlServerSqlTypeExtensions.cs 
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/165911292/79145ef2-a19b-4709-8506-659103a02582)

**Comment by ErikEJ** [comment]
I can see that you should NOT be using "legacyResultSetDiscovery" in order for the parameters to be discovered.

For help, please provide a runnable set of SQL scripts that creates the required objects and I can step through the code.

**Comment by HAK-Logos** [comment]
Here's a script for the user defined type:

`CREATE TYPE [dbo].[IntegerList] AS TABLE(`
	`[I] INT NOT NULL,`
	`PRIMARY KEY CLUSTERED ([I] ASC)`
`);`

And here's a sproc:

`CREATE PROCEDURE [dbo].[SomeStoredProcedure]`
`@SomeParameter1 BIGINT,`
`@SomeParameterList1 [dbo].[IntegerList] READONLY`
`AS`
`BEGIN`
	`SET XACT_ABORT ON `
	`SELECT 1`
`END`

Is that enough?

**Comment by HAK-Logos** [comment]
Yes, it should

**Comment by ErikEJ** [comment]
@HAK-Logos But it does not! Please provide a repro that actually causes the error you reported above.

```csharp
public virtual async Task<List<SomeStoredProcedureResult>> SomeStoredProcedureAsync(long? SomeParameter1, DataTable SomeParameterList1, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "SomeParameter1",
                    Value = SomeParameter1 ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.BigInt,
                },
                new SqlParameter
                {
                    ParameterName = "SomeParameterList1",
                    Value = SomeParameterList1 ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Structured,
                    TypeName = "[dbo].[IntegerList]",
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SomeStoredProcedureResult>("EXEC @returnValue = [dbo].[SomeStoredProcedure] @SomeParameter1 = @SomeParameter1, @SomeParameterList1 = @SomeParameterList1", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

```

**Comment by HAK-Logos** [comment]
Intriguing.. Let me setup a project that replicates the issue and link it to you. Unfortunately I can't link the current project to you. It might take some time, but I will get back to you.

**Comment by ErikEJ** [comment]
Ah, I missed this "Is a SQL Server .dacpac used: yes" 😄

**Comment by HAK-Logos** [comment]
Oh fair enough, that's alright 😄 

Sorry, had to remove my previous comment. Uploaded the wrong .zip file. 

Here's the right one. 

[EFCPT.zip](https://github.com/ErikEJ/EFCorePowerTools/files/15292395/EFCPT.zip)

**Comment by HAK-Logos** [comment]
> Potentially not supported (yet) with a .dacpac

So only potentially, that's better than "not supported" 😄 

I hope it's not that big of a deal to make it work, otherwise I have to put this branch on hold for now. 

We are changing some "old" code from passing comma separated strings to SQL, to now use TVP. Converting that string to something edible in SQL is kind of performance heavy, when we pass around 10k values.. So it would be nice to have this working 🙂

**Comment by ErikEJ** [comment]
Workaround would be to publish the .dacpac a generate code from the published database

**Comment by HAK-Logos** [comment]
> Workaround would be to publish the .dacpac a generate code from the published database

Hmm.. That is a solution, but I just don't see it being practical in a live environment, fully integrated with CI/CD.

Do you already know, what is required for TVP to be compatible with .dacpac? Or if you're planning to implement it in the near future? 🙂

**Comment by ErikEJ** [comment]
I only recently implemented support for stored prcedure discovery with a .dacpac, so I am hoping this is just a feature gap. If it is urgent for you I accept sponsorships! 😄

**Comment by HAK-Logos** [comment]
I understand 😉 I will get back to you sooner or later! 

Anyways, thanks for the help for now 👍

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by HAK-Logos** [comment]
Well that was fast 😄

I appreciate it! And ofc. I'll as a minimum review your tool.

Have a great evening 🙂

**Comment by HAK-Logos** [comment]
@ErikEJ Works like a charm 😄

Again, thank you!
