### ISSUE TITLE
Inappropriate Navigation Property name generated by EF Core reverse engg.

### ISSUE THREAD

**Issue by vishwa-sage** [ErikEJ/EFCorePowerTools#2326]
Create a bug report, feature proposal, or ask a question.

NOTICE: A bug report without sufficient technical and repro details and version information WILL BE CLOSED WITHOUT ANY FURTHER ACTION.

### Provide steps to reproduce a bug

Please include a **complete** description of the issue or link to a project that I can run to reproduce the issue.
I have a scenario where i have created a table named CM_Companies with multiple table relation, i have created another table called
CC_Change in which i have created two FK keys with CM_Companies named
CC_Change: FK_CC_Change_CM_Companies
CC_Change: FK_CC_Change_CM_Companies1

When reverse engg generates the class this gives very unexpected output like:
for CC_Change class this generates below property name:
public virtual CM_Companies? OwnerCompany { get; set; }
public virtual CM_Companies? PrimeCompany { get; set; }

and when this generated CM_Companies, this gives:
public virtual ICollection<CC_Change> CC_ChangeOwnerCompany { get; set; } = new List<CC_Change>();
public virtual ICollection<CC_Change> CC_ChangePrimeCompany { get; set; } = new List<CC_Change>();

why this decides the property name on their own. i have never decided this.
### Provide technical details

- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
   2.6.200
- Exact Visual Studio version: (e.g. Visual Studio 2022 17.6.5)
  Microsoft Visual Studio Enterprise 2022 (64-bit) - Version 17.9.6
- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)
  Microsoft SQL Azure (RTM) - 12.0.2000.8   Apr  3 2024 14:04:26   Copyright (C) 2022 Microsoft Corporation 
- EF Core version in use: (e.g. EF Core 7)
  EF 8
- Is Handlebars templates used: no/yes
  no (Not sure)
- Is T4 templates used: no/yes
 Yes
- Is a SQL Server .dacpac used: no/yes
  No

**Comment by ErikEJ** [comment]
Please share scripts to create your schema

**Comment by vishwa-sage** [comment]
/****** Object:  Table [dbo].[TableA]    Script Date: 13-05-2024 16:51:27 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TableA](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ChangeTypeId] [int] NOT NULL,
	[OrderNumber] [smallint] NOT NULL,
	[ProjectId] [int] NULL,
	[RecordNumber] [nvarchar](25) NOT NULL,
	[IssueDate] [datetime] NOT NULL,
	[PrimeContractId] [int] NULL,
	[PrimeCompanyId] [int] NULL,
	[PrimeContactId] [int] NULL,
	[PrimeDefaultAddress] [tinyint] NOT NULL,
	[OwnerCompanyId] [int] NULL,
	[OwnerContactId] [int] NULL,
	[OwnerDefaultAddress] [tinyint] NOT NULL,
	[InitiatedById] [int] NULL,
	[Subject] [nvarchar](255) NOT NULL,
	[Description] [nvarchar](max) NOT NULL,
	[SpecSectionRef] [nvarchar](50) NULL,
	[DrawingRef] [nvarchar](50) NULL,
	[RFIRef] [nvarchar](50) NULL,
	[OtherRef] [nvarchar](50) NULL,
	[LocationRef] [nvarchar](255) NULL,
	[LocationId] [int] NULL,
	[FollowUpDate] [datetime] NULL,
	[ReqdCompletionDate] [datetime] NULL,
	[ActualCompletionDate] [datetime] NULL,
	[Status] [smallint] NOT NULL,
	[StatusDate] [datetime] NULL,
	[BidLocked] [bit] NOT NULL,
	[ScheduleImpactTBD] [bit] NOT NULL,
	[ScheduleImpact] [smallint] NOT NULL,
	[OrgMultiplier] [real] NOT NULL,
	[ProjectMultiplier] [real] NOT NULL,
	[ChangeId] [int] NULL,
	[LockTransaction] [bit] NOT NULL,
	[LockedByUser] [nvarchar](110) NULL,
	[LockDate] [datetime] NULL,
	[Exported] [bit] NOT NULL,
	[ExportedByUser] [nvarchar](110) NULL,
	[ExportDate] [datetime] NULL,
	[ExportFileId] [int] NULL,
	[ExportId] [nvarchar](255) NULL,
	[CreatedUser] [nvarchar](110) NULL,
	[ModifiedUser] [nvarchar](110) NOT NULL,
	[Created] [datetime] NULL,
	[Modified] [datetime] NOT NULL,
 CONSTRAINT [PK_TableA] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UK_TableA] UNIQUE NONCLUSTERED 
(
	[ChangeTypeId] ASC,
	[ProjectId] ASC,
	[PrimeContractId] ASC,
	[RecordNumber] ASC,
	[OrderNumber] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[TableA] ADD  CONSTRAINT [DF_TableA_OrgMultiplier]  DEFAULT ((1)) FOR [OrgMultiplier]
GO

ALTER TABLE [dbo].[TableA] ADD  CONSTRAINT [DF_TableA_ProjectMultiplier]  DEFAULT ((1)) FOR [ProjectMultiplier]
GO

ALTER TABLE [dbo].[TableA]  WITH NOCHECK ADD  CONSTRAINT [FK_TableA_TableAInitiatedBy] FOREIGN KEY([InitiatedById])
REFERENCES [dbo].[TableAInitiatedBy] ([Id])
GO

ALTER TABLE [dbo].[TableA] CHECK CONSTRAINT [FK_TableA_TableB]
GO

ALTER TABLE [dbo].[TableA]  WITH NOCHECK ADD  CONSTRAINT [FK_TableA_TableB1] FOREIGN KEY([OwnerCompanyId])
REFERENCES [dbo].[TableB] ([Id])
GO

ALTER TABLE [dbo].[TableA] CHECK CONSTRAINT [FK_TableA_TableB1]
GO

ALTER TABLE [dbo].[TableA]  WITH NOCHECK ADD  CONSTRAINT [FK_TableA_TableC] FOREIGN KEY([PrimeContactId])
REFERENCES [dbo].[TableC] ([Id])
GO

ALTER TABLE [dbo].[TableA] CHECK CONSTRAINT [FK_TableA_TableC]
GO

ALTER TABLE [dbo].[TableA]  WITH NOCHECK ADD  CONSTRAINT [FK_TableA_TableC1] FOREIGN KEY([OwnerContactId])
REFERENCES [dbo].[TableC] ([Id])
GO

ALTER TABLE [dbo].[TableA] CHECK CONSTRAINT [FK_TableA_TableC1]
GO

**Comment by ErikEJ** [comment]
I need all the tables pls.

**Comment by vishwa-sage** [comment]
but this world be security breach, i cant post schema on public forum. You need to either connect to me 1-1.

**Comment by ErikEJ** [comment]
You can email me ejlskov at Hotmail dot com

**Comment by vishwa-sage** [comment]
the code and the schema is the comp proprietary, and per compliance this should not go beyond company network. But i bliv the given schema would work for you, where you only need to create Table B and Table C, you can create Table B and Table C with any number of columns and reference Table A with B and C

**Comment by vishwa-sage** [comment]
You are not doing well closing the issue without any consent, same thing your EF tool doing this generating the property name without any consent :). This should have not been closed @ErikEJ , this tool must provide the proper output else this kind of tool actually the wastage of time.

**Comment by ErikEJ** [comment]
Feel free to not use it, but I cannot offer free support with a complete repro. 

FYI I use the standard EF Core command line tooling underneath, feel free to use that instead.

**Comment by vishwa-sage** [comment]
must be reported, better not to promote this tool. Thanks

**Comment by ErikEJ** [comment]
This is a free tool, and it your choice alone if you find it useful.

Have a nice day!
