### ISSUE TITLE
[Question] How to disable generation of readme in EF Core Power Tools CLI ?

### ISSUE THREAD

**Issue by davidpetric** [ErikEJ/EFCorePowerTools#2329]
Hi,

First of all thanks for making our lives easier with these tools.

I am trying to disable the generation of  `efcpt-readme.md` using the latest version of EF Core Power Tools CLI, but I couldn't find any option.

Thanks

**Comment by ErikEJ** [comment]
There is not option for that..

Write a script to remove my small ad after code generation.

**Comment by davidpetric** [comment]
Sorry, I did not see it's an ad, I thought it was printing configuration steps.

**Comment by ErikEJ** [comment]
Well, it is kind of both...

**Comment by Daniel-Healy-J7** [comment]
Hello Erik,

Would you consider adding an option to make the connection string section of the readme more obfuscated? 

While I appreciate that the readme does not include the connection password, I would prefer to also keep the database server names out of my repositories. Currently, that requires me to gitignore the efcpt-readme.md file and your attribution.

Thanks
