### ISSUE TITLE
Enable getting views from schema query (for EF Core 3.0)

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#233]
If EF Core 3.0, get at concatenated list of:
1: tables sorted by named
2: views sorted by name

- [x] Implement for SQL Server @ErikEJ
 - [x] Implement for Dacpac @ErikEJ
- [x] Implement for SQLite @ErikEJ 
- [x] Implement for Postgres
- [x] Implement for MySQL

**Comment by ErikEJ** [comment]
Parts implemented in https://github.com/ErikEJ/EFCorePowerTools/commit/63f712944ee268d519711d484e07ef5f66e0255d 
@jespersh @roji Maybe you could help?

**Comment by jespersh** [comment]
Sure thing. Do you have an example Create view statement and its expected code generation?

Probably won't need it, but nice for verification

**Comment by ErikEJ** [comment]
It is just for reverse engineering, and this is just the first, inactive baby step.

The new fluent property is .HasNoKey()

**Comment by jespersh** [comment]
My part for MySQL is already showing views in the list actually, but it is showing them up as "This table has no primary key and will be ignored", so I am unsure if there's more to be done for me?

**Comment by ErikEJ** [comment]
@jespersh great. The message is a UI issue.

**Comment by ErikEJ** [comment]
@roji Ping?

**Comment by roji** [comment]
Sorry for not responding on this.

@ErikEJ this is about having EFCore.PG scaffold views right (like https://github.com/aspnet/EntityFrameworkCore/issues/1679)? If so I've opened https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/issues/972 to track and will probably complete this for preview8. Thanks for poking me on it :)

**Comment by roji** [comment]
So it turns out I'm getting senile, and already did this (https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/issues/878). Is there anything else you need from me here?

**Comment by ErikEJ** [comment]
@roji No, I meant this: https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/EFCorePowerTools/Helpers/EnvDTEHelper.cs#L192 - this should be updated to also include views

**Comment by ErikEJ** [comment]
@jespersh There is not "VIEW" object in MySQL?

**Comment by jespersh** [comment]
@ErikEJ I can easily pick out the data here: https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/EFCorePowerTools/Helpers/EnvDTEHelper.cs#L244
The TableInformationModel doesn't seem to allow for a View property to indicate it is a view and not a table?

**Comment by ErikEJ** [comment]
It has a HasPrimaryKey property => views have no primary key!

**Comment by jespersh** [comment]
> It has a HasPrimaryKey property => views have no primary key!

So what do you wish for to do with tables without a primary key?
I am currently treating primary-keyless tables and views the same.

**Comment by ErikEJ** [comment]
The can now be scaffoled as Entities with not key (HasNoKey)

**Comment by roji** [comment]
@ErikEJ can you please provide more details on exactly what you need? [Npgsql exposes view information](https://github.com/npgsql/npgsql/blob/f2dd3f7d0db4594c9220eca728f94acded9fd76c/src/Npgsql/NpgsqlSchema.cs#L293) via the "views" schema collection, in a way that seems to be compatible with [the way SqlClient does it](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql-server-schema-collections#views). Let me know what exactly is missing and I'll look into it.

**Comment by ErikEJ** [comment]
@roji thanks, I will just implement the changes myself

**Comment by roji** [comment]
Ok @ErikEJ, let me know if you need anything from my side.

**Comment by ErikEJ** [comment]
@roji Would be grateful if you could check this! https://github.com/ErikEJ/EFCorePowerTools/pull/265/commits/f67ab72c0ae6b7a9dcdc847806d648b6d74b0208

**Comment by roji** [comment]
@ErikEJ yep, that looks like it should work! Let me know if you hit any issues with it.

**Comment by ErikEJ** [comment]
@roji thanks, I will let some Postgres users test it!

**Comment by ErikEJ** [comment]
@roji Any ideas in relation to this: "// TODO: Check if the table has a primary key" ?

**Comment by roji** [comment]
Hmm... I don't know exactly what your code does, but you can have tables with and without primary keys - that may be important (or not). However, AFAIK in PG views cannot have primary keys (or any kind of constraint), so this may just be a copy-paste.

**Comment by ErikEJ** [comment]
@roji I mean: how do I detect if a table (not a view) has a primary key?

**Comment by roji** [comment]
I think you need to get a different metadata schema. [Looking at the source](https://github.com/npgsql/npgsql/blob/dev/src/Npgsql/NpgsqlSchema.cs#L40), getting "CONSTRAINTS" or possibly "CONSTRAINTCOLUMNS" should be it (not in front of my computer so can't dig deeper)...

**Comment by ErikEJ** [comment]
@roji are you able to get the latest daily and test this? https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/EFCorePowerTools/Helpers/EnvDTEHelper.cs#L203 (I do not have a server installed)

**Comment by roji** [comment]
@ErikEJ I can try to find some time during this week, but it's gonna be tight (dotnetos conference). But it's super easy to install PostgreSQL and test stuff: https://www.postgresql.org/download/windows, I'd rather help you do that :trollface:

**Comment by jespersh** [comment]
Seems like I can only select View/Tables without primary keys right now 
Version: 2.3.47.0
Is that the newest version? I can't tell what was fixed/changed in what version

![image](https://user-images.githubusercontent.com/1004198/66304693-1b5e1a80-e8fe-11e9-8f2d-113ec52a4598.png)

**Comment by ErikEJ** [comment]
@jespersh That looks like a bug in the latest daily build! (I am working on EF Core 3.0 support)

**Comment by ErikEJ** [comment]
Should be fixed now (2.3.48 or later)

**Comment by ErikEJ** [comment]
@jespersh I *really* appreciate that you are running the latest daily build!

**Comment by jespersh** [comment]
I tried with 2.3.49.0 and got the same window. Can't select regular tables with primary keys.
This IsEnabled 
https://github.com/ErikEJ/EFCorePowerTools/blob/cc23919591acc6035981c5a1ed6a28898b655eab/src/GUI/EFCorePowerTools/Dialogs/PickTablesDialog.xaml#L109
should:
* always be true for 3.0
* only be true for tables with primary keys for 2.x

**Comment by ErikEJ** [comment]
That is correct! What am I doing wrong?

**Comment by ErikEJ** [comment]
I think I found the bug! 😊

**Comment by jespersh** [comment]
Wait, are these new?
https://github.com/ErikEJ/EFCorePowerTools/blob/cc23919591acc6035981c5a1ed6a28898b655eab/src/GUI/RevEng.Shared/TableInformationModel.cs#L55-L64

I notice that "_isKeyless" is the inverse of "HasKey", so which is it? :-) 
I think your issue might be some flipping of the bool

For mysql am I just setting 
https://github.com/ErikEJ/EFCorePowerTools/blob/8d40124e145cb2fbab47be369e00e175742e6b00/src/GUI/EFCorePowerTools/Helpers/EnvDTEHelper.cs#L255

**Comment by jespersh** [comment]
And you can delete these lines:
https://github.com/ErikEJ/EFCorePowerTools/blob/8d40124e145cb2fbab47be369e00e175742e6b00/src/GUI/EFCorePowerTools/Helpers/EnvDTEHelper.cs#L251-L254

They appear to have no effect and I don't remember why I put it twice. Think a mistake was made that I always included views in the list, but it never bothered me.

**Comment by jespersh** [comment]
Just noticed you added it yourself :-)
https://github.com/ErikEJ/EFCorePowerTools/commit/8d40124e145cb2fbab47be369e00e175742e6b00

`info` is unused.
Maybe it'll just work if you replace
`result.Add(new TableInformationModel(table, hasPrimaryKey));`
with
`result.Add(info);`

**Comment by ErikEJ** [comment]
@jespersh Does the latest daily fix it?

**Comment by jespersh** [comment]
@ErikEJ I don't see a mysql related commit after https://github.com/ErikEJ/EFCorePowerTools/issues/233#issuecomment-538981835
I can test again if you think I should

**Comment by ErikEJ** [comment]
Doh - never pushed the fix - just did it now!

**Comment by jespersh** [comment]
It works again. Thanks!
