### ISSUE TITLE
Support for Many-to-many and join table with payload

### ISSUE THREAD

**Issue by VR-Architect** [ErikEJ/EFCorePowerTools#2333]
Thank you for an excellent project! Question:

Does the current version support many-to-many and join table with payload as defined by [Microsoft ](https://learn.microsoft.com/en-us/ef/core/modeling/relationships/many-to-many#many-to-many-with-named-join-table) which the many-to-many table contains additional fields? 

I have successfully used EF Core Power Tools for my many-to-many tables without a payload, but as soon as I added an extra field in one of my many-to-many tables and re-ran the reverse engineer feature, the direct link to the skip table was removed from the parent table and a link to the many-to-many table was put in. Ideally, I would like both the skip table reference and the direct many-to-many table reference from my parent table. 

Thanks for the feedback.

**Comment by ErikEJ** [comment]
You can only use one or the other, a payload forces (unsurprisingly) a seperate entity
