### ISSUE TITLE
Ability to use migrations tool without providing a connection string

### ISSUE THREAD

**Issue by blahDL** [ErikEJ/EFCorePowerTools#2334]
I have a web application which dynamically sets the connection string used by the EF contexts based on request headers. When I start the Migrations Tool it spits out an application exception because the connection string has not been initialised (which is expected as the web application sets the connection string in the dependency injection registration using `DbContextOptionsBuilder`). 

Is it possible to make the database connection string optional when using the migrations tool?
Being able to specify/override a connection string in the options somewhere might work too if the database connection is required

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/24240705/f034c5f2-db96-499e-ad73-f72b8113da33)
On a side note, the error message dialog seems to have a fixed width which makes it insanely long :-|

I currently type commands like these in the command prompt, it would be nice to have a GUI to to simplify these :-)
`dotnet ef migrations add --context=[DatabaseContext] [MigrationName]`
`dotnet ef migrations script --context=[DatabaseContext] --idempotent --output script.sql`

**Comment by ErikEJ** [comment]
Regarding the missing connection string - look at the advise here: https://learn.microsoft.com/en-us/ef/core/cli/dbcontext-creation?tabs=dotnet-core-cli (I think you would encounter the exact same issues with the standard CLI tools=

`dotnet ef migrations add --context=[DatabaseContext] [MigrationName]`

- does the tool not do that for you already?

`dotnet ef migrations script --context=[DatabaseContext] --idempotent --output script.sql`

- Please create a seperate issue for this, seems like a good idea.

**Comment by ErikEJ** [comment]
@blahDL Ping?

**Comment by blahDL** [comment]
Weird, I didn't get a notification email from the response or the ping :-|

We always generate the SQL files and run them against our databases, I don't think we have ever tried to run the migrations against a database via the CLI. We have a build step to generate the SQL and commit it to the repository to make it easier for everyone. I'll see what I can get working using that documentation though.

> does the tool not do that for you already?

The connection string exception currently prevents me from getting to this functionality :-(

> Please create a seperate issue for this, seems like a good idea.

Will do

**Comment by blahDL** [comment]
I was able to get the migration tool opening up now without throwing the exception by implementing `IDesignTimeDbContextFactory` for all of the database contexts from the documentation available at https://learn.microsoft.com/en-us/ef/core/cli/dbcontext-creation?tabs=dotnet-core-cli#from-a-design-time-factory 

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/24240705/631e4cc9-95f3-479f-9712-a2ae9d74c584)

**Comment by ErikEJ** [comment]
Amazing!

**Comment by ErikEJ** [comment]
If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
