### ISSUE TITLE
Latest update fails to load.

### ISSUE THREAD

**Issue by WaltDaniels** [ErikEJ/EFCorePowerTools#2335]
Create a bug report, feature proposal, or ask a question.

NOTICE: A bug report without sufficient technical and repro details and version information WILL BE CLOSED WITHOUT ANY FURTHER ACTION.

### Provide steps to reproduce a bug

Extension fails to load with this error.
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/1422934/84508289-1f18-466f-a40a-9f5cdb3aae69)

### Provide technical details

- EF Core Power Tools version: 2.6.282

- Exact Visual Studio version: Visual Studio 2022 17.9.7

- Database engine: SQL Server

- EF Core version in use: EF Core 7

- Is Handlebars templates used: no

- Is T4 templates used: no

- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
Please provide the Activitylog.xml file. 

Try restarting/ repairing VS.

**Comment by WaltDaniels** [comment]
I tried restarting.
The message does not appear when I start VS "with no code", but when I open a solution it shows up.

[ActivityLog.zip](https://github.com/ErikEJ/EFCorePowerTools/files/15326036/ActivityLog.zip)

I will try repairing next and update here.

**Comment by WaltDaniels** [comment]
I ran Visual Studio repair which reset my environment.  Now the extension installs, does not generate any errors, but is unavailable.  It shows as installed, but does not appear in the context menu nor options.

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/1422934/4bdf7902-e9bb-4df8-a281-e19807e61c08)

Attaching the install log:
[dd_VSIXInstaller_20240515154028_3134.zip](https://github.com/ErikEJ/EFCorePowerTools/files/15326886/dd_VSIXInstaller_20240515154028_3134.zip)

**Comment by ErikEJ** [comment]
Maybe it is disabled and must be enabled

**Comment by ErikEJ** [comment]
It only loads when you have a solution open, btw

**Comment by ErikEJ** [comment]
I see this in the ActivityLog:

```
CreateInstance failed for package [EFCorePowerToolsPackage]Source: 'mscorlib' Description: Could not load file or assembly 'file:///C:\Users\WalterDaniels\AppData\Local\Microsoft\VisualStudio\17.0_7c6dcbb8\Extensions\h2xnvun0.fdv\EFCorePowerTools.dll' or one of its dependencies. The system cannot find the file specified.
System.IO.FileNotFoundException: Could not load file or assembly 'file:///C:\Users\WalterDaniels\AppData\Local\Microsoft\VisualStudio\17.0_7c6dcbb8\Extensions\h2xnvun0.fdv\EFCorePowerTools.dll' or one of its dependencies. The system cannot find the file specified.
File name: 'file:///C:\Users\WalterDaniels\AppData\Local\Microsoft\VisualStudio\17.0_7c6dcbb8\Extensions\h2xnvun0.fdv\EFCorePowerTools.dll'

```

**Comment by WaltDaniels** [comment]
That ActivityLog was from the initial error.  After uninstalling/reinstalling the files are here:
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/1422934/8b521b8f-6017-471f-bee5-82ee0e40c0fd)

**Comment by FranCordeiro** [comment]
I'm facing the same error.
As a workaround I tried to install a previous version, however, the real version is the last one available:

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/144599368/d098c47b-eb4b-45c2-b302-464f307fc0aa)

**Comment by ErikEJ** [comment]
@FranCordeiro pls share the ActivityLog.xml file

**Comment by ErikEJ** [comment]
Try to manually remove all files in the extension folder and download and install outside VS

**Comment by FranCordeiro** [comment]
ActivityLog details:
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/144599368/84b4cc2b-0a42-429e-a4d4-a89b50b42157)

**Comment by ErikEJ** [comment]
@FranCordeiro Which exact VS version do you have?

**Comment by FranCordeiro** [comment]
@ErikEJ 17.3.6
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/144599368/28c9203d-da95-451d-981a-9df1b35cfa34)

**Comment by ErikEJ** [comment]
@FranCordeiro I think you have to update to 17.5 or later (current is 17.9.7)

**Comment by ErikEJ** [comment]
@FranCordeiro Great news!

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
