### ISSUE TITLE
Unable to reverse engineer because it cannot find data provider

### ISSUE THREAD

**Issue by OpusKrokus** [ErikEJ/EFCorePowerTools#2337]
Create a bug report, feature proposal, or ask a question.

NOTICE: A bug report without sufficient technical and repro details and version information WILL BE CLOSED WITHOUT ANY FURTHER ACTION.

### Provide steps to reproduce a bug
Right click on project
Go to EF Core Power Tools -> Reverse Engineer
In my case the drop down on the left is empty
Click add
Select Add Database Connection
An error popup will immediately appear with the text 'Failed to find or load the registered .NET Framework Data Provider.

I am almost certain that the problem is on my end, but I could not find anything while searching on the web that really applied.  I can successfully run the scaffolding commands manually, but that does not do everything I want it to do, and your tool does.

Please include a **complete** description of the issue or link to a project that I can run to reproduce the issue.

I am trying to reverse engineer a SQL Server database for a new .NET 8 application.

### Provide technical details

- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
2.6.282

- Exact Visual Studio version: (e.g. Visual Studio 2022 17.6.5)
Visual Studio 2022 19.9.7

- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)
Sql Server (although I don't think it is getting that far
- EF Core version in use: (e.g. EF Core 7)
Behaves the same for both 7 and 8
- Is Handlebars templates used: no/yes
no
- Is T4 templates used: no/yes
no
- Is a SQL Server .dacpac used: no/yes
no

**Comment by ErikEJ** [comment]
Could be a bad Server Explorer connection. Remove it.

**Comment by tiger2014** [comment]
> Create a bug report, feature proposal, or ask a question.
> 
> NOTICE: A bug report without sufficient technical and repro details and version information WILL BE CLOSED WITHOUT ANY FURTHER ACTION.
> 
> ### Provide steps to reproduce a bug
> Right click on project Go to EF Core Power Tools -> Reverse Engineer In my case the drop down on the left is empty Click add Select Add Database Connection An error popup will immediately appear with the text 'Failed to find or load the registered .NET Framework Data Provider.
> 
> I am almost certain that the problem is on my end, but I could not find anything while searching on the web that really applied. I can successfully run the scaffolding commands manually, but that does not do everything I want it to do, and your tool does.
> 
> Please include a **complete** description of the issue or link to a project that I can run to reproduce the issue.
> 
> I am trying to reverse engineer a SQL Server database for a new .NET 8 application.
> 
> ### Provide technical details
> * EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
>   2.6.282
> * Exact Visual Studio version: (e.g. Visual Studio 2022 17.6.5)
>   Visual Studio 2022 19.9.7
> * Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)
>   Sql Server (although I don't think it is getting that far
> * EF Core version in use: (e.g. EF Core 7)
>   Behaves the same for both 7 and 8
> * Is Handlebars templates used: no/yes
>   no
> * Is T4 templates used: no/yes
>   no
> * Is a SQL Server .dacpac used: no/yes
>   no

Have you reulted it? I encountered the same issue when I wanted to add a new database connection:
![image](https://github.com/user-attachments/assets/647e3a11-e5b7-4997-a57e-9014941c838e)
