### ISSUE TITLE
Reverse Engineer - Bug Report : Namespace is not generated correctly

### ISSUE THREAD

**Issue by melihsen** [ErikEJ/EFCorePowerTools#234]
### Steps to reproduce

![image](https://user-images.githubusercontent.com/25493160/60672841-16ad4480-9e7f-11e9-8a64-ec70fded380f.png)

### Further technical details
EF Core Power Tools version: 2.2.63.0
Database engine: SQL Server 2012 SP3
Visual Studio version: Community 2019 - 16.1.5
OS: Windows 10 En x64

**Comment by saitguzel** [comment]
I have the same problem.

**Comment by ErikEJ** [comment]
Remove Models.Db part from the namespace?

**Comment by melihsen** [comment]
It does not solve the problem because
Expected Namespace: Bilsanet_Web.Models.Db
Tool generates: Bilsanet_Web.Models.Db.**Entities**

**Comment by ErikEJ** [comment]
Hmmm… So you want the namespace to be different from the folder path, against all conventions?

**Comment by melihsen** [comment]
I think you mean that namespace area in the settings is top level (main) namespace. I think your algorithm combine main namespace with folder structure.  
I expect that the generated namespace is the same with Namespace area in the settings. I think it is simpler than your algorithm. Maybe you can add additional checkbox is that "Use only this Namespace (Do not combine with folder structure)" in the settings window.

**Comment by ErikEJ** [comment]
Maybe submit a PR?

**Comment by ErikEJ** [comment]
Proposed solution: Add checkbox to Naming section:

Do not combine Namespace with Project Path (default false, as this is current behaviour)

**Comment by ErikEJ** [comment]
I have attempted a fix in the lates daily build, please let me know if that works for you

**Comment by ErikEJ** [comment]
@melihsen Ping?

**Comment by melihsen** [comment]
I am sorry for my late response. I have installed and tried daily build. It works well. Thank you very much for all.

**Comment by ErikEJ** [comment]
Thanks!
