### ISSUE TITLE
Add script generation to migrations tool

### ISSUE THREAD

**Issue by blahDL** [ErikEJ/EFCorePowerTools#2344]
It would be great to be able to generate migration SQL scripts from the migration tool instead of having to write commands likes this in a command line:
`dotnet ef migrations script --context=[DatabaseContext] --idempotent --output script.sql`

CLI documentation is available here: https://learn.microsoft.com/en-us/ef/core/cli/dotnet#dotnet-ef-migrations-script

Having drop down lists to select the migrations to use for `<FROM>` and `<TO>` would be awesome :-D

(From https://github.com/ErikEJ/EFCorePowerTools/issues/2334#issuecomment-2111663371)

**Comment by ErikEJ** [comment]
The Migrations tool should support scripting already, but it looks like there is a bug with EF Core 8, where the tool continues to detect pending changes - I will have a closer look

**Comment by ErikEJ** [comment]
@blahDL This is already available in the Migrations tool - but only visible once migrations have been applied

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/4169187/6ab79b7b-96e1-46fd-a343-c8e2fb31a185)

**Comment by ErikEJ** [comment]
There is also a bad pattern if the database does not exist, wonder if I should just attempt to create it if it does not exist. 

Let me try that.

**Comment by blahDL** [comment]
> @blahDL This is already available in the Migrations tool - but only visible once migrations have been applied

It would be better if the scripting options were available without requiring the database to be up to date, that is probably why I didn't see the scripting options available. Unfortunately we have occasional issues with the migrations fail because of indexes or statistics that exist in a database but not in the context (we have multiple client databases that existed 20 years before we started using EF on them and were manually maintained in that time) so we sometimes need to comment out individual lines in the SQL to update the client databases.

**Comment by ErikEJ** [comment]
@blahDL Makes sense, I will make them available earlier

**Comment by ErikEJ** [comment]
I am seriously considering dropping this feature, as it is now built into VS: 

https://youtu.be/UEqx0c-Dnec?si=4R6q_ubN693iUM1U&t=162

**Comment by ErikEJ** [comment]
I have dropped this feature now...

**Comment by ErikEJ** [comment]
@
