### ISSUE TITLE
[Question] Compare DbContext to Database Using CLI

### ISSUE THREAD

**Issue by davidpetric** [ErikEJ/EFCorePowerTools#2345]
Hello,

Is there a way to compare a DbContext to a database using the CLI version?

Thanks!

**Comment by ErikEJ** [comment]
Not at the moment, no. CLI is only reverse engineering just now.

What would the output of a CLI based compare look like, and what would the command line options be?

**Comment by davidpetric** [comment]
> Not at the moment, no. CLI is only reverse engineering just now.
> 
> What would the output of a CLI based compare look like, and what would the command line options be?

For me It's important to simply know if there are any differences between the DbContext and the database, given that my app is not the single source of truth.

Ensuring that columns and queries are aligned.

**Comment by davidpetric** [comment]
> You can use this library in a Unit test or Console app: https://github.com/JonPSmith/EfCore.SchemaCompare (That is the one I use!)

Thank you I will have a try and see.
