### ISSUE TITLE
[Feature request] Add refresh option to rightclick csproj

### ISSUE THREAD

**Issue by janseris** [ErikEJ/EFCorePowerTools#2346]
Hi,
I was wondering if you could add functionality for refresh in rightclick (context) menu.
The option is currently present when right-clicking the efpt.config.json, however this file is usually buried deep down in the project when it's a large one with lots of folders etc.
It would be easier to rightclick project and click Refresh similar to when clicking in efpt.config.json.

![obrazek](https://github.com/ErikEJ/EFCorePowerTools/assets/64279914/87c130e3-93c4-421f-8191-7bb01bff5432)

Something like this:
![obrazek](https://github.com/ErikEJ/EFCorePowerTools/assets/64279914/d07dbd1a-c7e8-49a4-bdd9-d105deda8553)

Thanks for considering!

**Comment by ErikEJ** [comment]
@janseris This is not something I am planning to do, as a project can contain multiple config files.

**Comment by janseris** [comment]
And showing it conditionally if there is only 1?

**Comment by ErikEJ** [comment]
Possibly, but seems superflous given that most people place it directly in the project root folder. (where the tool always creates it)

**Comment by janseris** [comment]
Well yes but large projects will hide that file deep down in the Solution Explorer.
I am currently in 1/2 or 1/3 of the number of folders in the data access layer project.
When I open more projects like this, the .json file goes quickly out of sight deep into scroll.
![obrazek](https://github.com/ErikEJ/EFCorePowerTools/assets/64279914/72806f1c-81db-4f4d-8ffb-79b588b814a2)

**Comment by ErikEJ** [comment]
And you only have 1 efpt.config.json file in the project?

**Comment by janseris** [comment]
> And you only have 1 efpt.config.json file in the project?

Yes. The database data access layer uses 1 database only.

**Comment by ErikEJ** [comment]
A PR for this would be welcome

**Comment by ErikEJ** [comment]
@janseris Did you manage to try this out?

**Comment by janseris** [comment]
@janseris Hi thank you. I've tried it out and it does the right job.

**Comment by ErikEJ** [comment]
@janseris Great, and thanks for letting me know
