### ISSUE TITLE
Support for Postgres version 10 (column p.prokind does not exist)

### ISSUE THREAD

**Issue by fletcher-arnold** [ErikEJ/EFCorePowerTools#2362]
I had been happily using this tool to reverse engineer a postgres database on a linux server but recently I had to re-install the visual studio extension and now I can't get it to work at all.

When I right click on the efpt.config.json file and go to edit, the initial screen works (where you select the connection string and EF version) but the next step fails with the error:

Npgsql.PostgresEception....column p.prokind does not exist.

From what I understand this is because the version of postgres (version 10) does not have some new column.

If I cannot upgrade the database, can I get an earlier version of the tool?

I would be grateful for any help or advice you can offer.

Fletcher

Visual Studio
PostgreSQL 10.23 (Ubuntu 10.23-1.pgdg22.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0, 64-bit

Microsoft Visual Studio Professional 2022
Version 17.9.6
VisualStudio.17.Release/17.9.6+34728.123
Microsoft .NET Framework
Version 4.8.09037
Installed Version: Professional
ASP.NET and Web Tools   17.9.199.22661

**Comment by ErikEJ** [comment]
@fletcher-arnold Have you tried targeting an older EF Core version?

**Comment by fletcher-arnold** [comment]
Hi Erik
Thanks for the response. If I create a brand new solution (Console App) for, say .net 6, and choose 'Reverse Engineer' I get a choice of 'EF Core 6' or 'EF Core 7' but it makes no difference, the error is the same.
So I know the issue is not connected to the project itself, but its something about the extension trying to analyze my version 10 database.

![PowerTools](https://github.com/ErikEJ/EFCorePowerTools/assets/104638937/f586bf11-ccd8-49ec-b955-7b1c4b7ebcc3)

**Comment by ErikEJ** [comment]
@fletcher-arnold Ah, it is a bug in the stored procedure schema detection (should be a noop on older Postgres versions), I will look into a fix. In the meantime you can get an older build from the tools folder in the archive branchnin this repo

**Comment by ErikEJ** [comment]
@roji what is a reliable way to detect the Postgres server version with the ADO.NET provider?

**Comment by ErikEJ** [comment]
@roji Found it: https://github.com/npgsql/npgsql/blob/main/src/Npgsql/NpgsqlConnection.cs#L1056

**Comment by ErikEJ** [comment]
@tlc-alex-lawrence  I know very little about Postgres - will that also work with Postgres 11 and later?

**Comment by fletcher-arnold** [comment]
Fantastic! Thank you, Erik, for your prompt response. I will try installing an older version and look forward to a fix whenever you can find the time :-)
Fletcher

**Comment by tlc-alex-lawrence** [comment]
> @tlc-alex-lawrence I know very little about Postgres - will that also work with Postgres 11 and later?

Ah, no, it'd just be after the postgres version check. It'd be the fix for Postgres 10 and below so you can still get the same functionality without resorting to it being a noop.

**Comment by ErikEJ** [comment]
@tlc-alex-lawrence I am not planning to support an unsupported Postgres version.

**Comment by ErikEJ** [comment]
Well you need .315 - what does "didn't work" mean exactly?

**Comment by tlc-alex-lawrence** [comment]
> @paulgood1 @fletcher-arnold Maybe my version check does not work? I do not have access to any Postgres 10 servers, could you check this code against your server to see what version number is returned?
> 
> https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/Core/RevEng.Core.60/Routines/PostgresRoutineModelFactory.cs#L39

I've confirmed that the version check works, but the error is still on the same line as before. I'm trying to figure out what the issue is now, but it's tough to replicate on my machine. I'll have some more info in a moment.

I'm also trying to build the project but I'm getting an issue with signing the dlls through msbuild `"ALINK : error AL1078: Error signing assembly -- The process cannot access the file because it is being used by another
process. [C:\Development\DotNet Code\EFCorePowerTools\src\GUI\EFCorePowerTools\EFCorePowerTools.csproj]"`, have you come across this before?

**Comment by ErikEJ** [comment]
Maybe there were some issues with building the .zip files for the internal command line tool, I will refresh jus now.

**Comment by ErikEJ** [comment]
Finally build .318 is out

**Comment by fletcher-arnold** [comment]
I have installed .318 and can confirm it is now working!
Thanks again for fixing this so promptly...I will post product rating later today.
Cheers :-)
Fletcher

**Comment by ErikEJ** [comment]
Great and thanks for the heads up

**Comment by ErikEJ** [comment]
@fletcher-arnold @tlc-alex-lawrence 
If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
