### ISSUE TITLE
"Failed to find or load the registered .Net Framework Data Provider".

### ISSUE THREAD

**Issue by Andywmm9** [ErikEJ/EFCorePowerTools#2364]
Fresh install, and I receive the following error in the title when clicking the Add Database Connection.

**Comment by ErikEJ** [comment]
Could you share the full error text, pls? Then I can help others avoid it.

It us most likely a bad connection in Server Explorer, try to remove it.

**Comment by Hevgen** [comment]
The same problem/ Worked before.
Error box text: "Failed to find or load the registered .Net Framework Data Provider".

**Comment by ErikEJ** [comment]
@Hevgen "It is most likely a bad connection in Server Explorer, try to remove it." - did you try that?

**Comment by Hevgen** [comment]
I have added some details in the previous message.
I don't use Server Explorer directly.  But I have tried to "Connect to Database" there with data source "Microsoft SQL Server" and data provider ".NET Framework Data Provider for SQL Server". I have got the same error message-box.
My application works ok with the DB in the same time (eF model was created months ago using the same VS instance and your extension.

**Comment by ErikEJ** [comment]
@Hevgen Sounds like you need a VS repair

**Comment by ErikEJ** [comment]
In your case, I think it is more: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.exe.config that you need to check.

```xml
    <system.data>
      <DbProviderFactories>

        <add name="Microsoft SqlClient Data Provider" invariant="Microsoft.Data.SqlClient" description="Microsoft SqlClient Data Provider for SQL Server" type="Microsoft.Data.SqlClient.SqlClientFactory, Microsoft.Data.SqlClient, Version=5.0.0.0, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5"/>
      </DbProviderFactories>
    </system.data>

```

**Comment by zeta520** [comment]
> In your case, I think it is more: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.exe.config that you need to check.
> 
> ```
>     <system.data>
>       <DbProviderFactories>
> 
>         <add name="Microsoft SqlClient Data Provider" invariant="Microsoft.Data.SqlClient" description="Microsoft SqlClient Data Provider for SQL Server" type="Microsoft.Data.SqlClient.SqlClientFactory, Microsoft.Data.SqlClient, Version=5.0.0.0, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5"/>
>       </DbProviderFactories>
>     </system.data>
> ```

Dear sir,
I have the same problem, but I've checked the devenv.exe.config, it just has only one 
```
<add name="Microsoft SqlClient Data Provider" invariant="Microsoft.Data.SqlClient" description="Microsoft SqlClient Data Provider for SQL Server" type="Microsoft.Data.SqlClient.SqlClientFactory, Microsoft.Data.SqlClient, Version=5.0.0.0, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5"/>
```
My IDE: Visual Studio 2022 17.11.2
