### ISSUE TITLE
Can't Custom T4 Template Path

### ISSUE THREAD

**Issue by jeeshenlee** [ErikEJ/EFCorePowerTools#2366]
I'm using the configuration below, but the generated files do not follow the T4 template.
```json
{
    "CodeGenerationMode": 4,
    "ContextClassName": "IExtranetDbContext",
    "ContextNamespace": "",
    "FilterSchemas": false,
    "IncludeConnectionString": false,
    "ModelNamespace": "",
    "OutputContextPath": "IDatabase\/DbContext",
    "OutputPath": "",
    "PreserveCasingWithRegex": true,
    "ProjectRootNamespace": "Si.Application",
    "Schemas": null,
    "SelectedHandlebarsLanguage": 2,
    "SelectedToBeGenerated": 1,
    "T4TemplatePath": "..\/CodeTemplates\\DbContext.t4",
    "Tables": [
		...
    ],
    "UiHint": null,
    "UncountableWords": null,
    "UseAsyncStoredProcedureCalls": true,
    "UseBoolPropertiesWithoutDefaultSql": false,
    "UseDatabaseNames": true,
    "UseDateOnlyTimeOnly": true,
    "UseDbContextSplitting": false,
    "UseDecimalDataAnnotationForSprocResult": true,
    "UseFluentApiOnly": true,
    "UseHandleBars": false,
    "UseHierarchyId": false,
    "UseInflector": true,
    "UseLegacyPluralizer": false,
    "UseManyToManyEntity": false,
    "UseNoDefaultConstructor": false,
    "UseNoNavigations": false,
    "UseNoObjectFilter": false,
    "UseNodaTime": false,
    "UseNullableReferences": false,
    "UsePrefixNavigationNaming": false,
    "UseSchemaFolders": false,
    "UseSchemaNamespaces": false,
    "UseSpatial": false,
    "UseT4": true
}
```

Here's a screenshot of my folder structure and the path of the json file.
![file](https://github.com/ErikEJ/EFCorePowerTools/assets/1011777/de8b6380-a09e-4414-baf2-335536cabc15)

The generated file `IExtranetDbContext.cs` does not follow the T4 template.

The first line of my `DbContext.t4` output a file with a .g.cs extension.
```
<#@ output extension=".g.cs" #>
```

How do I customize the `T4TemplatePath` so EFPT picks up the T4 templates? Is it possible to have more than two templates? How?

**Comment by ErikEJ** [comment]
please consult the wiki, the template path should point to a path, not a file:

https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#customize-code-using-t4-templates

**Comment by ErikEJ** [comment]
@jeeshenlee Ping?

**Comment by wzuqui** [comment]
@ErikEJ, acredito que ele esteja procurando algo como eu. Preciso que os arquivos gerados tenham a extensão ".g.cs"

**Comment by ErikEJ** [comment]
@wzuqui I think you can use the output directive: https://learn.microsoft.com/en-us/visualstudio/modeling/t4-output-directive?view=vs-2022

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
