### ISSUE TITLE
[Feature request] Description for navigation property

### ISSUE THREAD

**Issue by janseris** [ErikEJ/EFCorePowerTools#2367]
Hi,
I use SQL Server where I put comments on foreign keys in database schema.
I noticed that they are scaffolded on the int property.
However there is nothing displayed on the navigation property which is directly related.
Moreover, I thought that adding Description to the FK constraint itself might add description to the navigation property but that did not do anything either.

My feature request then is that if the Description for the foreign key could be shown on navigation property as well?

```
/// <summary>
/// Určuje ještě kategorizování oborů, je-li definováno a je-li to potřeba kvůli počtu oborů
/// </summary>
public int? SkupinaOboruUrednichOpravneniID { get; set; }

public virtual SKUPINA_OBORU_OPRAVNENI SkupinaOboruUrednichOpravneni { get; set; }
```

![obrazek](https://github.com/ErikEJ/EFCorePowerTools/assets/64279914/05b0cb45-7917-43cf-8881-acdb2b926335)

Why (my own scenario but I believe there are countless uses for this):
- I needed to put a note that the navigation property might be null so that backend programmer can see it when making queries.
So the note would be showing here:
![obrazek](https://github.com/ErikEJ/EFCorePowerTools/assets/64279914/74e170b5-ee7c-4daa-bc09-73b5a0691987)

Thank you

**Comment by ErikEJ** [comment]
Looks similar to #1640

**Comment by ErikEJ** [comment]
@janseris Are you OK with a T4 based solution, then I will try to create a sample similar to issue #1640

**Comment by janseris** [comment]
> @janseris Are you OK with a T4 based solution, then I will try to create a sample similar to issue #1640

It would be better if this was an option in the options when creating database.
Me and my colleagues are not familiar with T4 and I think that anyone other who possibly would like this feature, would see that as obstacle.

**Comment by ErikEJ** [comment]
Got it, but for this it is either T4 or an EF Core change. It is not something I plan to special case in EF Core Power Tools.

**Comment by ErikEJ** [comment]
You can modify the T4 template for EntityType like this:

```csharp
            var comment = navigation.ForeignKey.Properties.FirstOrDefault()?.GetComment();
            if (!string.IsNullOrEmpty(comment))
            {
#>
    /// <summary>
    /// <#= code.XmlComment(comment, indent: 1) #>
    /// </summary>
<#
            }

            var needsNullable = Options.UseNullableReferenceTypes && !(navigation.ForeignKey.IsRequired && navigation.IsOnDependent);
```
(Last line is original)
