### ISSUE TITLE
Unable to do "Update Database" in Migrations Tool dialog

### ISSUE THREAD

**Issue by doggy8088** [ErikEJ/EFCorePowerTools#2374]
### Provide steps to reproduce a bug

I'm using Visual Studio 2022 17.10.0.

1. New -> Project -> ASP.NET Core Web App (Model-View-Controller)

    Project name: `IdentityDemo`

    Framework: `.NET 8.0`

    Authentication type: `Individual Accounts`

2. In this project template in the VS2022, there is already have a `Migrations` folder but under `Data` folder. See below screenshot:

    ![image](https://github.com/ErikEJ/EFCorePowerTools/assets/88981/b9bcbd34-7bbf-4965-b14d-9f5b1f1ee81d)

3. I'm trying to do **database update**, but I can't see the **Update Database** button.

    ![image](https://github.com/ErikEJ/EFCorePowerTools/assets/88981/185010a7-1b2a-4cc1-92e8-8c924bbe1b09)

4. I tried move `Migrations` folder to the project root, still not working.

    ![image](https://github.com/ErikEJ/EFCorePowerTools/assets/88981/9b5a0d92-a06c-404c-8cc1-31793b8e5266)

### Additional Note

I realized that when database is not exist at the project created moment. The **database update** button will not shown. This might be counted as a bug. It because any new project that is using EF Core Code First might not have a database been created initially.

### Provide technical details

- EF Core Power Tools version: `2.6.287`

- Exact Visual Studio version: `Visual Studio 2022 17.10.0`

- Database engine: `SQL Server`

- EF Core version in use: `EF Core 8`

- Is Handlebars templates used: no

- Is T4 templates used: no

- Is a SQL Server .dacpac used: no

**Comment by doggy8088** [comment]
Wow, I never know that. 

Put the link you mentioned here: https://github.com/ErikEJ/EFCorePowerTools/wiki/Migrations-Tool

**Comment by ErikEJ** [comment]
Thanks, but I decided it did not have the energy to maintain it. Are you volunteering?

**Comment by doggy8088** [comment]
Sure, I'll find sometime to improve it.

**Comment by ErikEJ** [comment]
This was my fix for this bug, just before I decided to remove the tool: https://github.com/ErikEJ/EFCorePowerTools/commit/b578f507a12defb95d959985f57e63a6ddb32b56
