### ISSUE TITLE
[Feature] Map TVP parameters to a class, not just a DataTable

### ISSUE THREAD

**Issue by egiorgioPatagonian** [ErikEJ/EFCorePowerTools#2375]
Hi there,
I have the problem. The tools doesn't generate a parameter when I pass table type.

```
But the types doesn't create in the interface input. I only ataTable FilterTable
public virtual async Task<(List<GetLibraryData_v6Result1> Result1,....., List<GetLibraryData_v6Result4> Result4)> GetLibraryData_v6Async(DataTable FilterTable, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)

```
```
-- Create the new table type
CREATE TYPE dbo.BookFilterTableType_v4 AS TABLE
(
    Title NVARCHAR(100),
    AuthorID INT
);
GO

-- Create the new stored procedure
ALTER PROCEDURE [dbo].[GetLibraryData_v6]
    @FilterTable dbo.BookFilterTableType_v4 READONLY
AS
BEGIN
    -- Test query to verify that the procedure can be executed

    -- First query
    SELECT AuthorID, Name, BirthDate 
    FROM Authors;

    -- Second query
    SELECT b.BookID, b.Title, b.AuthorID, b.PublisherID, b.PublishDate 
    FROM Books b
    INNER JOIN @FilterTable ft ON 
        (ft.Title IS NULL OR b.Title LIKE '%' + ft.Title + '%')
        AND (ft.AuthorID IS NULL OR b.AuthorID = ft.AuthorID);

    -- Third query
    SELECT PublisherID, Name, Country 
    FROM Publishers;

    -- Fourth query
    SELECT Country 
    FROM Publishers;
END;
GO
```
I have already checked "Always include all database objects" and Discover multiple result sets Sql stored procedures.
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/132367158/676e82e2-0282-4af9-b57e-6af235464ab1)
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/132367158/245f0229-2011-497d-b977-091b3381eccd)
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/132367158/03cacbd6-aafa-4cf3-bf92-9117b1dd8f6f)

Do you know if I need to check something else or I need to modify teh store procedure..
Details:
- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
- Exact Visual Studio version: (e.g. Visual Studio 2022 17.6.5)
- Database engine: SQL Server
- EF Core version in use: (e.g. EF Core 8)

**Comment by ErikEJ** [comment]
@egiorgioPatagonian The DataTable is the parameter!

**Comment by egiorgioPatagonian** [comment]
But I thought I would generate a list as a parameter.
Like this
```
List<BookFilterTableTypeV3> FilterTable = new List<BookFilterTableTypeV3>();
var FilterTable1 = new BookFilterTableTypeV3();
FilterTable1.Title = "";
FilterTable1.AuthorId = 1;
FilterTable.Add(FilterTable1);
// Call the stored procedures
var results = await context.Procedures.GetLibraryData_v6Async(FilterTable);  
```

Not like this.
```
DataTable FilterTable = new DataTable();
FilterTable.Columns.Add("Title ", typeof(string));
FilterTable.Columns.Add("AuthorID", typeof(int));
FilterTable.Rows.Add("", 1);

// Call the stored procedures
var results = await context.Procedures.GetLibraryData_v6Async(FilterTable);  
```

**Comment by ErikEJ** [comment]
Does the DataTable not work?

**Comment by egiorgioPatagonian** [comment]
Datatable works perfectly.

My question is if it is possible to generate a list of objects instead of a datatable. Since that would expose me to the parameters which should be passed without any type of doubt.

**Comment by ErikEJ** [comment]
Maybe, I think I just went for the simpler solution when I added support for this: https://learn.microsoft.com/en-us/dotnet/framework/data/adonet/sql/table-valued-parameters#configuring-a-sqlparameter-example

**Comment by egiorgioPatagonian** [comment]
Ok.
I understand the solution is based table-valued-parameters.  
So it doesn't have the capability to generate as like a clases of parameters.

Is it possible to add that funcionality in future or do you think it is no make sense?

Thanks ErikEJ

**Comment by ErikEJ** [comment]
It probably makes sense, interested in foibg a PR?

**Comment by egiorgioPatagonian** [comment]
Sure!
Why not.

**Comment by egiorgioPatagonian** [comment]
Hi @ErikEJ 
I tried to push new branch called egiorgio-issue-2375. 
This is a Idea how to implement this feature and I would like to share with you. Probaly is not complete.
But I couldn't push new branch. 
Could you give me permissions to be able to use the repository?

**Comment by ErikEJ** [comment]
@egiorgioPatagonian Did you create a fork and follow the pull request workflow described here? https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

I also noted that this might be not som simple to add, but let us  have a look at your PR

**Comment by ErikEJ** [comment]
@egiorgioPatagonian Any news?

**Comment by ErikEJ** [comment]
@egiorgioPatagonian Ping??
