### ISSUE TITLE
Reverse engineering a non-nullable bit column with DEFAULT constraint incorrectly ignores the default value

### ISSUE THREAD

**Issue by wsigel** [ErikEJ/EFCorePowerTools#2376]
This is a variation of #1438 and happens when using EF Core 8. The problem does not arise with EF Core 7 (therefore I'm not sure whether it's an issue with the power tools or EF Core 8.

I've created a demo databse table like this:

```
CREATE TABLE [dbo].[Dummy](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Col1] [bit] NULL,
	[Col2] [bit] NOT NULL,
	[Col3] [tinyint] NULL,
	[Col4] [tinyint] NOT NULL,
	[Col5] [int] NULL,
	[Col6] [int] NOT NULL,
 CONSTRAINT [PK_Dummy_ID] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Dummy] ADD  CONSTRAINT [DF_Dummy_Col1]  DEFAULT ((1)) FOR [Col1]
GO
ALTER TABLE [dbo].[Dummy] ADD  CONSTRAINT [DF_Dummy_Col2]  DEFAULT ((1)) FOR [Col2]
GO
ALTER TABLE [dbo].[Dummy] ADD  CONSTRAINT [DF_Dummy_Col3]  DEFAULT ((1)) FOR [Col3]
GO
ALTER TABLE [dbo].[Dummy] ADD  CONSTRAINT [DF_Dummy_Col4]  DEFAULT ((1)) FOR [Col4]
GO
ALTER TABLE [dbo].[Dummy] ADD  CONSTRAINT [DF_Dummy_Col5]  DEFAULT ((1)) FOR [Col5]
GO
ALTER TABLE [dbo].[Dummy] ADD  CONSTRAINT [DF_Dummy_Col6]  DEFAULT ((1)) FOR [Col6]
GO
```

When using **EF Core 7** to do the reversing the generated model class is as follows:

```
public partial class Dummy
{
    public int Id { get; set; }

    public bool? Col1 { get; set; }

    public bool? Col2 { get; set; }

    public byte? Col3 { get; set; }

    public byte Col4 { get; set; }

    public int? Col5 { get; set; }

    public int Col6 { get; set; }
}
```

The DbContext class renders like this:

```
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<Dummy>(entity =>
    {
        entity.HasKey(e => e.Id).HasName("PK_Dummy_ID");

        entity.ToTable("Dummy");

        entity.Property(e => e.Id).HasColumnName("ID");
        entity.Property(e => e.Col1).HasDefaultValueSql("((1))");
        entity.Property(e => e.Col2)
            .IsRequired()
            .HasDefaultValueSql("((1))");
        entity.Property(e => e.Col3).HasDefaultValueSql("((1))");
        entity.Property(e => e.Col4).HasDefaultValueSql("((1))");
        entity.Property(e => e.Col5).HasDefaultValueSql("((1))");
        entity.Property(e => e.Col6).HasDefaultValueSql("((1))");
    });

    OnModelCreatingPartial(modelBuilder);
}
```

Reversing using **EF Core 8** renders the following model class:

```
public partial class Dummy
{
    public int Id { get; set; }

    public bool? Col1 { get; set; }

    public bool Col2 { get; set; }

    public byte? Col3 { get; set; }

    public byte Col4 { get; set; }

    public int? Col5 { get; set; }

    public int Col6 { get; set; }
}
```

and the DbContext generated is this:

```
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<Dummy>(entity =>
    {
        entity.HasKey(e => e.Id).HasName("PK_Dummy_ID");

        entity.ToTable("Dummy");

        entity.Property(e => e.Id).HasColumnName("ID");
        entity.Property(e => e.Col1).HasDefaultValue(true);
        entity.Property(e => e.Col2).HasDefaultValue(true);
        entity.Property(e => e.Col3).HasDefaultValue((byte)1);
        entity.Property(e => e.Col4).HasDefaultValue((byte)1);
        entity.Property(e => e.Col5).HasDefaultValue(1);
        entity.Property(e => e.Col6).HasDefaultValue(1);
    });

    OnModelCreatingPartial(modelBuilder);
}
```

When newing up a Dummy-object and calling the Save() on the context the database shows the following:

<img width="201" alt="SqlDemo" src="https://github.com/ErikEJ/EFCorePowerTools/assets/10357745/8c01014b-c5c8-459d-a40a-b7fe09947a03">

The first 3 rows - using EF Core 8 show that in Col2 the default of 1 is ignored. Rows 4-6 - using EF Core 7 are taking
the default of 1 into account.

 Obviously the default of 1 is ignored when the column is rendered as a 'bool' (like in EF Core 8) und is incorporated when
 rendered as a 'bool?' (like in EF Core 7).

So as I said I'm not sure whether this is an issue with the power tools or with EF Core 8. But since we've encountered this
issue when changing from EF Core 7 to EF Core 8 I thought it might be valid to bring up this point.

### Provide technical details

- EF Core Power Tools version: 2.6.287

- Exact Visual Studio version: Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.9.2

- Database engine: Microsoft SQL Server Express (64-bit), 15.0.4153.1

- EF Core version in use: EF Core 7 & EF Core 8

- Is Handlebars templates used: no

- Is T4 templates used: no

- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
@wsigel  I think it is an EF Core change: https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-8.0/breaking-changes#scaffold-bools

**Comment by wsigel** [comment]
Thank you Eric for your quick response pointing out the root of this issue.
