### ISSUE TITLE
Changes to t4 don't affect filename

### ISSUE THREAD

**Issue by mmelendez21** [ErikEJ/EFCorePowerTools#2379]
Here is what I want.  I want to generate EF models with the suffix of 'Data' ie... User -> UserData, but any navigation property should be named 'User' and not 'UserData'.  If I do regex rename with the json files my navigation properties include the Data suffix, and if its plural it becomes Datum.  So I turned off the regex renaming and went into the t4 files to customize it.  Now the classes are renamed but the properties remain as they were just as I wanted.  The only problem is that now the class is called UserData, but the file is still called User.  I'm not sure how you are writing the files, but it would make sense to read the class name from the generated file (using roslyn?), then rename the file accordingly.  

I thought about doing the reverse, renaming using the regex, but then removing the suffix on navigation properties, but doing so means the properties are no longer pluralized.  

So I either need to be able to rename files without changing the navigation properties or access the pluralizer from the t4 file?  Is there a way to do either?

**Comment by ErikEJ** [comment]
Have you tried to use uncountable words? (See the wiki)

**Comment by ErikEJ** [comment]
@mmelendez21 Ping?
