### ISSUE TITLE
The `.csproj` alwasy unable to write at first attempt on Reverse Engineer

### ISSUE THREAD

**Issue by doggy8088** [ErikEJ/EFCorePowerTools#2389]
### Provide steps to reproduce a bug

I'm always get the following error when I do Reverse Engineer in the new project.

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/88981/fdbccb73-47e9-47cf-83e2-8195a3e293e9)

> One or more projects ('WebApplicationl.csproj') have been changed outside of the project system, and conflict with unsaved changes. The external changes have been discarded but have been saved in a backup file if you need t0 manually restore them.

I recorded a short video clip for reproduce this issue. It's always happened on my machine.

https://github.com/ErikEJ/EFCorePowerTools/assets/88981/6c428654-f338-43c6-833a-e063419e9787

When I close the solution, re-open again. Then, I do it again. It will work.

### Provide technical details

- EF Core Power Tools version: `2.6.287`

- Exact Visual Studio version: `17.10.1`

- Database engine: `SQL Server`

- EF Core version in use: `EF Core 8`

- Is Handlebars templates used: `no`

- Is T4 templates used: `no`

- Is a SQL Server .dacpac used: `no`

**Comment by ErikEJ** [comment]
Could it be the entry for the .user file, never seen it before?

I will try to repro, thanks for the video

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

**Comment by doggy8088** [comment]
What's the `efpt.config.json.user` file for? Is that necessary add to the `.csproj`?

**Comment by ErikEJ** [comment]
No, I do not add it, the project system does (for Web projects only) - looks like a project system issue to me. 

It stores the UI hint for the last used database.
