### ISSUE TITLE
See the scaffold string generated by EF core power tools

### ISSUE THREAD

**Issue by nikiGagliardi** [ErikEJ/EFCorePowerTools#2397]
Hi,
Is it possible to have the database scaffold string generated by ef core power tools available?

**Comment by ErikEJ** [comment]
@nikiGagliardi I am not sure what you mean by that, I do not invoke the standard CLI tool.

You could use the PowerTools CLI edition if you want a command line experince.

**Comment by nikiGagliardi** [comment]
@ErikEJ I want to say that behind the power tool there will be the command for the CLI, is it possible to see it?

**Comment by ErikEJ** [comment]
I do not invoke the CLI, I run my own tool to support the additional features in EF Core Power Tools.

**Comment by nikiGagliardi** [comment]
Ah ok. Thank you for replay.
