### ISSUE TITLE
Data Annotations for non-nullable fields doesnt include "AllowEmptyStrings" attribute?

### ISSUE THREAD

**Issue by netbitshift** [ErikEJ/EFCorePowerTools#240]
Is there a way when you reverse engineer with data annotations, the resulting [Required] attribute to include instead [Required(AllowEmptyStrings=true)] ?

**Comment by ErikEJ** [comment]
No, not that I know of.

**Comment by netbitshift** [comment]
I suppose what I was thinking about was to enable this via the handlebar templates, specifically this section.  Can this be modified to enable the [Required] attribute to be rendered as having the option     [Required(AllowEmptyStrings =true)]

```
{{#if class-annotation}}
{{{class-annotation}}}
```

**Comment by ErikEJ** [comment]
Maybe - @tonysneed  ??

**Comment by tonysneed** [comment]
Yes this is possible. Created this [issue](https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars/issues/77) to continue the discussion over on the Handlebars Scaffolding repo.
