### ISSUE TITLE
[Feature] Add ability to use SQL field description as display name attribute

### ISSUE THREAD

**Issue by JayTee-2024** [ErikEJ/EFCorePowerTools#2408]
Feature proposal:

Please add a checkbox /functionality to use the SQL field description property as the content of the component model Display attribute, for EF properties.  The SQL field description is already added as a summary meta tag if it's specified.

For instance, a field with "Value of contract" as the SQL description would result in something similar to this when generating the EF model:

    [Display(Name = "Value of contract")]
    public decimal ContractValue { get; set; }

This would be useful so that descriptions don't need to be re-established when regenerating the model.

**Comment by ErikEJ** [comment]
This is something that you can do in a T4 templates, see the sample in the samples folder in this repo

**Comment by JayTee-2024** [comment]
Amazing - I'll take a look into this.  Thanks so much for this fantastic tool!
