### ISSUE TITLE
handlebar template by db context/new db context template data

### ISSUE THREAD

**Issue by jan-diputado** [ErikEJ/EFCorePowerTools#2409]
- EF Core Power Tools version: 2.6.287
- Exact Visual Studio version: Visual Studio 2022 17.9.0
- Database engine: SQL Server
- EF Core version in use: EF Core 7
- Is Handlebars templates used: yes
- Is T4 templates used: no
- Is a SQL Server .dacpac used: no

Can I define a separate handlebar template files for different configs/db contexts?
If not, how do I add new template data/property? 
I want to capture the context class name and reference it in the Class.hbs file.
Basically, I want to add a separate base class depending on different configs/db contexts

If I can't define a separate handlebar template for each db context, this is what I want to do
**`public partial class {{class}} : {{db-context}}Entity`**
`{`
`    {{{> constructor}}}`
`    {{{> properties}}}`
`}`

I also tried using the T4 templates, but I run into issues when I define the path of the T4 template.
The tool just breaks and doesn't follow the config and T4 template definition

**Comment by jan-diputado** [comment]
@ErikEJ, Sorry, I should have put more details; I was hopeful that there was a handlebars solution.

For T4 approach, I don't understand what is to be placed in T4 template path; I tried the following on my project:

```
..\..\
DB1
DB1\CodeTemplates
DB1\CodeTemplates\EFCore
DB1\CodeTemplates\EFCore\
/DB1/CodeTemplates/EFCore
```
but none of them worked. The CodeTemplates\EFCore folders are not created.

It only works when the path is blank.
Then, when I move the folder to the correct location and change the T4 template path, the tool just ignores it and places all models and db context on the base folder (DB1 folder), instead of folder paths I defined on the tool.

Below is the content of `efpt.db1.config.json`

```
{
   "CodeGenerationMode": 3,
   "ContextClassName": "DB1Context",
   "ContextNamespace": null,
   "FilterSchemas": false,
   "IncludeConnectionString": false,
   "ModelNamespace": null,
   "OutputContextPath": "DB1\\Context",
   "OutputPath": "DB1\\Models\\Entities",
   "PreserveCasingWithRegex": true,
   "ProjectRootNamespace": "Project1.EntityFrameworkCore",
   "Schemas": null,
   "SelectedHandlebarsLanguage": 2,
   "SelectedToBeGenerated": 0,
   "T4TemplatePath": "DB1\\CodeTemplates\\EFCore\\",
   "Tables": [
      {
         "Name": "[dbo].[TAB1]",
         "ObjectType": 0
      },
      {
         "Name": "[dbo].[TAB2]",
         "ObjectType": 0
      }
   ],
   "UiHint": null,
   "UncountableWords": null,
   "UseAsyncStoredProcedureCalls": true,
   "UseBoolPropertiesWithoutDefaultSql": false,
   "UseDatabaseNames": true,
   "UseDateOnlyTimeOnly": false,
   "UseDbContextSplitting": false,
   "UseDecimalDataAnnotationForSprocResult": true,
   "UseFluentApiOnly": true,
   "UseHandleBars": false,
   "UseHierarchyId": false,
   "UseInflector": false,
   "UseLegacyPluralizer": false,
   "UseManyToManyEntity": false,
   "UseNoDefaultConstructor": false,
   "UseNoNavigations": false,
   "UseNoObjectFilter": false,
   "UseNodaTime": false,
   "UseNullableReferences": false,
   "UsePrefixNavigationNaming": false,
   "UseSchemaFolders": false,
   "UseSchemaNamespaces": false,
   "UseSpatial": false,
   "UseT4": true
}
```

Let me know if you need more info.

**Comment by ErikEJ** [comment]
@jan-diputado Thanks.

The path should point to a folder where there is a CodeTemplates folder below, I have updated the docs

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
