### ISSUE TITLE
Ef Power tools not appearing on the Context Menu

### ISSUE THREAD

**Issue by fahad198** [ErikEJ/EFCorePowerTools#2412]
Create a bug report, feature proposal, or ask a question.

NOTICE: A bug report without sufficient technical and repro details and version information WILL BE CLOSED WITHOUT ANY FURTHER ACTION.

### Provide steps to reproduce a bug

Not sure what happened. Ef power tools used to appear on my visual studio and it has stopped appearing. I have reinstalled the tool again and still nothing. I am trying it on .Net 8 project.

### Provide technical details

- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
Cant get it
- Exact Visual Studio version: (e.g. Visual Studio 2022 17.6.5)
Microsoft Visual Studio Enterprise 2022 (64-bit) - Current
Version 17.8.5

- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)
SQL Server
- EF Core version in use: (e.g. EF Core 7)
EF Core 7
- Is Handlebars templates used: no/yes

- Is T4 templates used: no/yes
no
- Is a SQL Server .dacpac used: no/yes
no

**Comment by ErikEJ** [comment]
Please share your .csproj, could be an unsupported project type.

Are you sure the extensio  is enabled - check in Extension Manager

**Comment by fahad198** [comment]
that's it that was the issue ... I don't know how it got disabled .. Thanks for the swift reply :)
