### ISSUE TITLE
Smoother Typing/Search on the "Choose Your Database Objects" Panel

### ISSUE THREAD

**Issue by HaydenJolly** [ErikEJ/EFCorePowerTools#2413]
I think something like the following in `PickTablesViewModel.HandleSearchTextChange` could make the typing experience smoother on the "Choose Your Database Objects" Panel.
```
_ = Task.Delay(300).ContinueWith(
    _ =>
    {
        if (text != SearchText)
        {
            return;
        }

        ObjectTree.Search(SearchText, searchMode);
    },
    TaskScheduler.Default);
```
rather than the current code
```
Thread.Sleep(300);
if (text != SearchText)
{
    return;
}

ObjectTree.Search(SearchText, searchMode);
```

I tested a similar scenario with both on the AdventureWorks data. I purposefully make a typo in each to see how much easier it is to catch and fix in the second scenario. In the first scenario I'm finished typing before the typo even renders.

Before

https://github.com/ErikEJ/EFCorePowerTools/assets/15185399/006452f7-2b00-4328-81dd-aefb257797d5

After

https://github.com/ErikEJ/EFCorePowerTools/assets/15185399/51348283-0b1d-4588-a4fa-d33c5e24aa5a

It's worth noting I think that the delayed tasks aren't _guaranteed_ to run in order but I don't think that should be an issue. 

Example:
5 characters are typed and tasks queued and somehow the tasks execute in reverse order 5,4,3,2,1. Since task 5 was queued that means that `SearchText` will be up to date with the most recently typed value. Therefore, task 5 will execute and the following tasks will return early since the `text` captured in their scope won't be equal to `SearchText` anymore. So I think the last `Search` to run in any given debounce period should always be correctly based on the last value of `SearchText`. 

Let me know if I'm missing something here or my logic doesn't work out.

**Comment by ErikEJ** [comment]
Looks great, interested in doing a PR?

**Comment by ErikEJ** [comment]
@HaydenJolly Thanks, I have implemented this now!
