### ISSUE TITLE
Reverse Engineering causes System.IO.FileNotFound exception

### ISSUE THREAD

**Issue by davequinn** [ErikEJ/EFCorePowerTools#2414]
I am using VS Community 2022 17.10.3.  Since upgrading to 17.10.3 I cannot reverse engineer ANY database table.  When I click ok on the Choose Your Data Connection screen after choosing ANY database connection I get an exception.

### Provide steps to reproduce a bug
As described ANY TIME I use reverse engineering I get the error.

The error in my eventlog is:

Application: dotnet.exe
CoreCLR Version: 8.0.624.26715
.NET Version: 8.0.6
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Data.SqlClient, Version=5.0.0.0, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5'. The system cannot find the file specified.
File name: 'Microsoft.Data.SqlClient, Version=5.0.0.0, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5'
   at EfReveng.Program.Main(String[] args)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at EfReveng.Program.Main(String[] args)
   at EfReveng.Program.<Main>(String[] args)

There is a reported severe vulnerability with Microsoft.Data.SqlClient 5.0.0.0. but my nuget package directory seems to have it and these other 2 releases of Microsoft.Data.SqlClient 5.1.5 and 5.2.1.  The application currently runs without complaints although I have updated my database and would like to match it in my code.

### Provide technical details

- EF Core Power Tools version: 2.6.287
- Exact Visual Studio version: (e.g. Visual Studio 2022 17.6.5): VS Community 2022 17.10.3
- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL): SQL Server express
- EF Core version in use: (e.g. EF Core 7): EF Core 8
- Is Handlebars templates used: no/yes: no
- Is T4 templates used: no/yes: no
- Is a SQL Server .dacpac used: no/yes: no

**Comment by ErikEJ** [comment]
Maybe a virus scanner or similar interferred with the unzipping of the tool, try to remove the %temp%\efreveng8.x folders

**Comment by davequinn** [comment]
Thanks for the unexpected super-quick response.  I uninstalled and reinstalled ef core tools – no joy.  As you suggested I removed the efreveng8 folders and am back up and running!

 

Thanks a bunch!

 

Dave

**Comment by ErikEJ** [comment]
You are welcome, glad you got it working!

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
