### ISSUE TITLE
Permits break execution

### ISSUE THREAD

**Issue by MauroVevy** [ErikEJ/EFCorePowerTools#2415]
I accidentally ran efpct.exe without config file on our large database (ours has 3587 tables, 2520 stored procedures, 668 views, 513 functions).
There is no way to stop the processing. 
I have to wait for the creation of the 7288 objects.

Thanks

**Comment by ErikEJ** [comment]
Pressing Ctrl+C does not work?

**Comment by ErikEJ** [comment]
@MauroVevy Ping?

**Comment by MauroVevy** [comment]
> Pressing Ctrl+C does not work?

I've tried every ctrl possible. :)
Anyone works

**Comment by ErikEJ** [comment]
@MauroVevy  "Anyone works" - do you mean none of them works?

**Comment by ErikEJ** [comment]
@MauroVevy  Looks like the EF Core reverse engineering process is synchronous, so now way to send a CancellationToken.

Possible solution could be to add a command line switch to not add any objects to the config file on first run. 

Thoughts?

**Comment by MauroVevy** [comment]
Excuse me,
No ctrls works.

If the problem is the process being synchronous, don't change anything.
I'm sure anyone forgets to run reverse enginering with one more parameter the first time.

**Comment by ErikEJ** [comment]
I guess the size of your database is outside the "normal" range...
