### ISSUE TITLE
problem to install EF Core Power Tools on Visual Studio 2019

### ISSUE THREAD

**Issue by aevivasabril** [ErikEJ/EFCorePowerTools#2416]
Hi, 

I have to change my computer and i have to duplicate all my developpement environnement to this new computer.
on my old computer i used a VS2019 (16.11.5) and i have the package EF Core Power Tools (Version 2.4.217), i need The Core tools to continue the mainteneance of my website. I installed this on 2020.

On my new computer i install a VS 2019 professional (16.11.37) and i want to install the same version of EF core power tools but it's impossible, i already install the version propose with the manage packages on VS => Entity Framework 6 power tools community edition, but this package it doesn't provide the same menu that i know :(, clicking right on the projet i have => Entity framework 6 => customize reverse engineer...

How can i install the good version to have right click => EF Core Power Tools => image on attach file 
![Sans titre](https://github.com/ErikEJ/EFCorePowerTools/assets/56883800/59b0750f-a92c-4e45-aac0-39e428f9c968)? 

i hope that you can help me, please :) 

Thanks in advance

**Comment by robgwinkler** [comment]
Download from here:
https://github.com/ErikEJ/EFCorePowerTools/tree/archive/tools/VS2019Support

**Comment by ErikEJ** [comment]
@robgwinkler Thanks!

**Comment by aevivasabril** [comment]
Thanks a lot @robgwinkler it works! :)
