### ISSUE TITLE
SQL Table Function primary key issue

### ISSUE THREAD

**Issue by ghendric** [ErikEJ/EFCorePowerTools#2417]
I encountered an issue in the latest version of EF Core Power Tools v2.6.287 when referencing a SQL table function. Here is the error message I received:

"The entity type '_EntityTypeName_' requires a primary key to be defined. If you intended to use a keyless entity type, call 'HasNoKey' in 'OnModelCreating'. For more information on keyless entity types, see https://go.microsoft.com/fwlink/?linkid=2141943."

HasNoKey was being generated and called when executing the code, but the error occurred when trying to execute anything unrelated to the SQL function. It appears to be connected to how the code was generated by EF Core Power Tools. I downgraded to v2.6.140, ran the reverse engineer option, and this resolved the issue. The generated code layout differed from that of v2.6.287. I'm not sure if this difference is the cause, but I wanted to report the issue.

I'm using VS 2022 Pro 64-bit, Windows 11 64-bit, and the project solution is .NET 8.

**Comment by ErikEJ** [comment]
Which EF Core version exactly do you use at runtime?

**Comment by ghendric** [comment]
> Which EF Core version exactly do you use at runtime?

Version 8.0.0

**Comment by ErikEJ** [comment]
Have you tried 8.0.6??

**Comment by ghendric** [comment]
> Have you tried 8.0.6??

No. I can't do that without affecting the solution and causing problems without first making sure the update doesn't break anything for anyone else working on the code. The solution is over a 1.5 million lines of code.

**Comment by ErikEJ** [comment]
8.0.6 is just a minor bug fix update from 8.0.0 - surely you can test your issue against that version locally??

I believe you are facing a bug that has been fixed in 8.0.6

**Comment by ErikEJ** [comment]
https://github.com/dotnet/efcore/issues/32680

**Comment by ghendric** [comment]
So is your suggestion to upgrade to EF Core 8.0.6?

**Comment by ErikEJ** [comment]
@ghendric  Yes! As I understand, you are running EF Core version 8.0.0 which has a bug, that you are hitting. Updating to 8.0.2 or later will fix that bug - update locally and run a test to verify that it works.

**Comment by ghendric** [comment]
ok got it.. thanks!

**Comment by ErikEJ** [comment]
If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
