### ISSUE TITLE
Reverse engineering doesn't pick up key

### ISSUE THREAD

**Issue by nevernerdlet** [ErikEJ/EFCorePowerTools#2418]
I am reverse engineering a view that is built on top of a table with a primary key. 

Just some back info in case you care:
1. View is in database named Agent
2. Table is in separate database on same server called LegacyDataLake

Reverse engineering creates the entity with this line:

` entity
     .HasNoKey()
     .ToView("MainframeAgentCopy", "Agent");`

Which breaks unit tests with this:
` Message: 
System.InvalidOperationException : Unable to track an instance of type 'MainframeAgentCopy' because it does not have a primary key. Only entity types with a primary key may be tracked.`

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/120412840/3c978f5d-2e13-47b7-ab40-064eda01ad94)
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/120412840/2f3308bf-fe75-4895-9b7c-305188386d34)

Version: 2.6.287
Visual Studio: Microsoft Visual Studio Enterprise 2022 64-bit 17.10.3
Database Engine: MS SQL Server
EF Core Version: EF Core 7
Handlebars: no
T4: not right now. I tried to force it to write out the line that states "haskey" and forced it to not write the entity.hasNoKey line but then .net threw errors saying it cannot find the object "MainframeAgentCopies"
Is a SQL Server .dacpac used: No

**Comment by nevernerdlet** [comment]
FYI, I can get it to update the entity correctly, but any query then fails during runtime.
I can do this by converting the agent code field to long and assigning it "ID" as alias. 

Entity:
`public partial class AgentEntities : DbContext
{
    public AgentEntities(DbContextOptions<AgentEntities> options)
        : base(options)
    {
    }

    public virtual DbSet<MainframeAgentCopy> MainframeAgentCopies { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<MainframeAgentCopy>(entity =>
        {
            entity.HasKey(e => e.ID); // Set ID as the primary key for MainframeAgentCopy
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}`

But that gives me the following error:

`13:40 [Error] (13) Failed executing DbCommand ("38"ms) [Parameters=["@__agentCode_0='?' (Size = 4000)"], CommandType='Text', CommandTimeout='30']"\r\n""SELECT TOP(1) [m].[CanSellDI]\r\nFROM [MainframeAgentCopies] AS [m]\r\nWHERE [m].[AgentCode] = @__agentCode_0"
13:40 [Error] (13) An exception occurred while iterating over the results of a query for context type '"IML.DAL.Agent.AgentEntities"'."\r\n""Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid object name 'MainframeAgentCopies'.\r\n   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__211_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location ---\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location ---\r\n   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)\r\n   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)\r\n   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()\r\nClientConnectionId:68418488-111b-42c6-b6fd-33b4b174c02c\r\nError Number:208,State:1,Class:16"
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid object name 'MainframeAgentCopies'.`

**Comment by nevernerdlet** [comment]
After dozens of changes, turns out it's a problem with entity framework because the schema was named the same as the database. Exhausting.

**Comment by ErikEJ** [comment]
If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
