### ISSUE TITLE
Scaffolding uncaps acronyms in table/column names

### ISSUE THREAD

**Issue by NiamorEllievel** [ErikEJ/EFCorePowerTools#242]
We use a number of uppercase acronyms in our database and application, which we can't realistically spend time renaming at this point. EF6 was keeping them uppercase. But the Power Tools treat them as the same word as the next and change their case.
For example, AChannel, BChannel etc... become Achannel, Bchannel etc... and AbcXYZDef becomes AbcXyzdef.

Could we get an option to keep the original case but still Pluralize the names where needed ?
This is preventing me from using your otherwise great tools.

### Steps to reproduce
Have a table name and a column name with successive uppercase letters in your database, then scaffold it and compare names.

### Further technical details
EF Core Power Tools version : 2.2.63.0

**Comment by ErikEJ** [comment]
Have you tried "Keep database names" ? There is also custom renaming - unsure it that would work.

**Comment by NiamorEllievel** [comment]
Unfortunately, "Keep database names" doesn't pluralize them, which is another bummer.
Custom renaming introduces another place to maintain, which is not ideal in a large-scale development context.

**Comment by ErikEJ** [comment]
That is the available options at the moment...

**Comment by NiamorEllievel** [comment]
I ended up bypassing completely both the CandidateNamingService.GenerateCandidateIdentifier(original) methods, where the PascalCasing happens, immediately returning original.Name.

After pluralizing, the generated entities are spelled exactly as they used to be by EF 6.

Giving users that option would make the Power Tools more popular with those who need to generate a DbContext compatible with older consuming code, when upgrading from EF 6 to EF Core, but can't manage lists of hundreds of entities and all their spellings.

**Comment by ErikEJ** [comment]
Great news, by overriding the CandidateNamingService I can support "Use Database Names" with pluralizing - I guess that would be the way to do it - in addition you can opt in to use the EF6 pluralizer (I assume you have no issues with the current pluralizer)

BTW: I plan to move away from Pluralize.NET and switch to Humanizer instead (and continue to have the EF6 pluralizer as a "hidden" option for now)

**Comment by ErikEJ** [comment]
I am not planning to implement this, given the available renaming options
