### ISSUE TITLE
Version 2.5.908 of EFCorePowerTools.vsix needed

### ISSUE THREAD

**Issue by billtang1** [ErikEJ/EFCorePowerTools#2420]
Hi Erik, do you know where I can download Version 2.5.908 of  the EFCorePowerTools.vsix extensions?  We still ahve a few .net core 2.1 web application that the current version of the EFCorePowerTools no longer support.    Thanks in advance!

**Comment by ErikEJ** [comment]
I have some older, unsupported packages in the tools folder in the archive branch. 2.1 is completely out of support.
