### ISSUE TITLE
Limitation of sp_describe_first_result_set...

### ISSUE THREAD

**Issue by GearTheWorld** [ErikEJ/EFCorePowerTools#2422]
Create a bug report, feature proposal, or ask a question.

Not a BUG but a LIMITATION.  We would need a solution that autogenerate the model even if a stored procedure uses temp table

### Provide steps to reproduce a bug

Create a stored procedure that uses a temp table and select from that temp table.  EF will generate the class name but empty.
Based on the following :

https://github.com/ErikEJ/EFCorePowerTools/issues/539

I tried a variable table or even doing a select of variables set from the result and despite every solution on the web or from the AI nothing seems to work because of the limitation of 

**sp_describe_first_result_set**

### Provide technical details

- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/8614008/5b95e3ef-b1a1-4f1b-91da-002c0ae3ae1c)

- Exact Visual Studio version: (e.g. Visual Studio 2022 17.6.5)
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/8614008/65d74d57-ab63-4c0d-8941-bc0e89d134a3)

- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)
SQL Server
- EF Core version in use: (e.g. EF Core 7)
8
- Is Handlebars templates used: no/yes
no
- Is T4 templates used: no/yes
no
- Is a SQL Server .dacpac used: no/yes
no

**Comment by ErikEJ** [comment]
I see no clear repro details here - and the workarounds are described in the linked issue - you can also try the alternative discovery method as described in the wiki,
