### ISSUE TITLE
Scaffolding Reverse Engineering 

### ISSUE THREAD

**Issue by StefanIvovic** [ErikEJ/EFCorePowerTools#2423]
Create a bug report, feature proposal, or ask a question.

Is it possible to separate generated code into projects, for example

i have structure like this 
```C#
EasyShop.EntityFrameworkCore -> DbContext
EasyShop.Doman -> Entities
```

Would it be possible to generate DbContext into EasyShop.EntityFrameworkCore project and Entities into EasyShop.Doman. Also would it be possible to change generated code from t4 template?

### Provide technical details

- EF Core Power Tools version: 2.6.287

- Exact Visual Studio version: Visual Studio 2022 (64-bit) Version 17.10.3

- Database engine: SQL Server

- EF Core version in use: EF Core 8

- Is Handlebars templates used: not sure what is this

- Is T4 templates used: no (but i am planning to add it)

- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
yes and yes. Please have a look at the [wiki](https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering)

**Comment by StefanIvovic** [comment]
@ErikEJ i am having trouble generating files in correct locations
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/20303370/399ba2e3-176c-4853-a542-b551cb85bc63)

Entites are generated correctly but DbContext is not. After reading documentation i was under impression that i show add path into 'DbContext path' textbox and it should generate it there ?

**Comment by ErikEJ** [comment]
It should be a relative path to the current config file location or full path

**Comment by StefanIvovic** [comment]
Nice thank you. 
Is it possible to generate script instead of doing it via GUI. Like for example when i run gui can i see script that its generating ?

**Comment by ErikEJ** [comment]
Not sure what you mean by script? I have a CLI version of the tool that relies on a json config file...

**Comment by ErikEJ** [comment]
If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by StefanIvovic** [comment]
What would you suggest here
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/20303370/5d53e24a-a859-496c-9434-c7fc81cb72da)
I have 2 partial DbContext. Left one is generated and right one is existing. How should i handle this

**Comment by ErikEJ** [comment]
1. Add your additional changes in OnModelCreatingPartial in a partial class
