### ISSUE TITLE
Link to Download EF Power Tools Package 2.5.1236 or a version that supports .Net Core 3.1

### ISSUE THREAD

**Issue by caype** [ErikEJ/EFCorePowerTools#2425]
Create a bug report, feature proposal, or ask a question.
Ask a Question
NOTICE: A bug report without sufficient technical and repro details and version information WILL BE CLOSED WITHOUT ANY FURTHER ACTION.

### Provide steps to reproduce a bug
Please include a **complete** description of the issue or link to a project that I can run to reproduce the issue.

Hello, I am working with a .Net Core 3.1 Project and want to use EF Power Tools with it. My team is utilizing the EF Power Tools version 2.5.1236, that works with .Net Core 3.1. I'm unable to find the download links to old packages, so trying to see if I can get that link.

### Provide technical details

- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
EF Power Tools: **2.6.287**
- Exact Visual Studio version: (e.g. Visual Studio 2022 17.6.5)
Microsoft Visual Studio Professional 2022 (64-bit) - **Current Version 17.10.3**
- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)
SQL Server
- EF Core version in use: (e.g. EF Core 7)
EF Core 3.1.31
- Is Handlebars templates used: no/yes
no
- Is T4 templates used: no/yes
no
- Is a SQL Server .dacpac used: no/yes
no

**Comment by ErikEJ** [comment]
You can find an older unsupported package in the tools folder in the archive branch..

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
