### ISSUE TITLE
Update of EFCorePowerTools Update fails

### ISSUE THREAD

**Issue by MagicAndre1981** [ErikEJ/EFCorePowerTools#2427]
### Provide steps to reproduce a bug

Try to update the extension from VSIX gallary inside VS extension manager

### Provide technical details

- EF Core Power Tools version: 2.6.397

- Exact Visual Studio version: VS2022 17.10.4

- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL) **not related to issue**

- EF Core version in use: (e.g. EF Core 7) **not related to issue**

- Is Handlebars templates used: no/yes **not related to issue**

- Is T4 templates used: no/yes  : **not related to issue**

- Is a SQL Server .dacpac used: **not related to issue**

> 11.07.2024 09:12:46 - The extension will be upgraded from version 2.6.397.
> 11.07.2024 09:12:46 - Extension Details...
> 11.07.2024 09:12:46 - 	Identifier         : EFCorePowerToolsExtensionPack.b2aaf4e1-5424-4a30-9228-7fe89f03f816
> 11.07.2024 09:12:46 - 	Name               : EF Core Power Pack
> 11.07.2024 09:12:46 - 	Author             : ErikEJ
> 11.07.2024 09:12:46 - 	Version            : 2.6.398
> 11.07.2024 09:12:46 - 	Description        : A package that contains EF Core Power Tools and some DDEX providers and DGML tools that improve your experience when using EF Core Power Tools.
> 11.07.2024 09:12:46 - 	Locale             : en-US
> 11.07.2024 09:12:46 - 	MoreInfoURL        : 
> 11.07.2024 09:12:46 - 	InstalledByMSI     : False
> 11.07.2024 09:12:46 - 	SupportedFrameworkVersionRange : [4.8,)
> 11.07.2024 09:12:46 - 	SignatureState     : Unsigned
> 11.07.2024 09:12:46 - 	Supported Products : 
> 11.07.2024 09:12:46 - 		Microsoft.VisualStudio.Community
> 11.07.2024 09:12:46 - 			Version : [17.0,18.0)
> 11.07.2024 09:12:46 - 			ProductArchitecture : amd64
> 11.07.2024 09:12:46 - 	References         : 
> 11.07.2024 09:12:46 - 	Prerequisites      : 
> 11.07.2024 09:12:46 - 		-------------------------------------------------------
> 11.07.2024 09:12:46 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
> 11.07.2024 09:12:46 - 		Name         : Visual Studio core editor
> 11.07.2024 09:12:46 - 		Version      : [17.0,)
> 11.07.2024 09:12:46 - 		-------------------------------------------------------
> 11.07.2024 09:12:46 - 		Identifier   : Microsoft.VisualStudio.Component.GraphDocument
> 11.07.2024 09:12:46 - 		Name         : DGML editor
> 11.07.2024 09:12:46 - 		Version      : [17.0,)
> 11.07.2024 09:12:46 - Signature Details...
> 11.07.2024 09:12:46 - 	Extension is not signed.
> 
> 11.07.2024 09:12:54 - "EF Core Power Tools" wird aktualisiert, **Version 2.6.397 auf Version 2.6.398**.
> 
> 11.07.2024 09:13:14 - Skipping cache of package 'Microsoft.VisualStudio.Component.Git,version=17.10.34803.213' since the package or a parent package had a vital failure.
> 11.07.2024 09:13:50 - **Installationsfehler: System.AggregateException:** Mindestens ein Fehler ist aufgetreten. ---> Microsoft.VisualStudio.Setup.PackageFailureException: Package '**GitV2**' failed to install
>    bei Microsoft.VisualStudio.Setup.InstallOperation.Run(CancellationToken token)
>    bei Microsoft.VisualStudio.Setup.Engine.RunOperation(InstallOperation installOperation, CancellationToken token, ExecuteAction action, ITelemetryOperation telemetryOperation)
>    bei Microsoft.VisualStudio.Setup.Engine.RunCoreOperation(InstallOperation coreOperation, ExecuteAction action, ITelemetryOperation telemetryOperation, CancellationToken token)
>    bei Microsoft.VisualStudio.Setup.Engine.Install(Product product, String destination, CancellationToken token)
>    bei Microsoft.VisualStudio.ExtensionManager.SetupEngineService.<Install>b__14_0()
>    bei System.Threading.Tasks.Task`1.InnerInvoke()
>    bei System.Threading.Tasks.Task.Execute()
>    --- Ende der internen Ausnahmestapelüberwachung ---
>    bei System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
>    bei System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
>    bei Microsoft.VisualStudio.ExtensionManager.SetupEngineService.Install()
>    bei Microsoft.VisualStudio.ExtensionManager.InstallModule.PerformSetupEngineInstall(InstallableExtensionImpl extensionToInstall, Boolean installPerMachine, Boolean isPackComponent, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion, IInstalledExtension& newExtension)
>    bei Microsoft.VisualStudio.ExtensionManager.InstallModule.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress, Version targetedVsVersion)
>    bei Microsoft.VisualStudio.ExtensionManager.InstallModule.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion)
>    bei Microsoft.VisualStudio.ExtensionManager.InstallModule.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)
> ---> (Interne Ausnahme #0) Microsoft.VisualStudio.Setup.PackageFailureException: Package 'GitV2' failed to install
>    bei Microsoft.VisualStudio.Setup.InstallOperation.Run(CancellationToken token)
>    bei Microsoft.VisualStudio.Setup.Engine.RunOperation(InstallOperation installOperation, CancellationToken token, ExecuteAction action, ITelemetryOperation telemetryOperation)
>    bei Microsoft.VisualStudio.Setup.Engine.RunCoreOperation(InstallOperation coreOperation, ExecuteAction action, ITelemetryOperation telemetryOperation, CancellationToken token)
>    bei Microsoft.VisualStudio.Setup.Engine.Install(Product product, String destination, CancellationToken token)
>    bei Microsoft.VisualStudio.ExtensionManager.SetupEngineService.<Install>b__14_0()
>    bei System.Threading.Tasks.Task`1.InnerInvoke()
>    bei System.Threading.Tasks.Task.Execute()<---

Why does your extension require Git? I already have git installed 

```
C:\>git -v
git version 2.45.2.vfs.0.0
```

Or is this a VS2022 issue?

**Comment by ErikEJ** [comment]
@MagicAndre1981 VS issue, try to run a repair

**Comment by MagicAndre1981** [comment]
ok, I'll try this and when next update is available I'll look what happens. I'll keep this open and comment what happened.

**Comment by MagicAndre1981** [comment]
strange thing is that VS2022 no longer shows the update and the DLL inside the extension folder is 2.6.398.0 

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/8274816/b4de5f5d-233a-4c14-987f-8f59275afe58)

**Comment by MagicAndre1981** [comment]
I think this is [my issue](https://developercommunity.visualstudio.com/t/GitV2-hangs-in-visual-studio-installer/10519499#T-N10529352). I was using the [Microsoft Git](https://github.com/microsoft/git/releases/latest) version. Now I'll wait for a new build on VSIX Gallery and look if this was really my issue or not.

**Comment by ErikEJ** [comment]
@MagicAndre1981 A new build is now available

**Comment by MagicAndre1981** [comment]
I don't see a new build only 398 which I already have as you can see in the picture. I need to wait until you release .399 maybe next month when new EF Core package updates are out.

**Comment by MagicAndre1981** [comment]
ok, Dependabot created PR #2428, so I'll test the new version after this PR got merged.

**Comment by ErikEJ** [comment]
@MagicAndre1981 That change only affects the CLI edition

**Comment by MagicAndre1981** [comment]
ok, so I have to wait for change that also effects the extension and test it.

**Comment by MagicAndre1981** [comment]
updating to 2.6.400 works:

![image](https://github.com/user-attachments/assets/20ee0250-dc37-4005-af6f-163552667bef)

So, for all people finding this via search engine, if you get extension install/update failures with the entries **Microsoft.VisualStudio.Setup.PackageFailureException: Package 'GitV2' failed to install** in the log, make sure you use the normal [Git for windows](https://github.com/git-for-windows/git/releases/latest) and **NOT** the [Microsoft git](https://github.com/microsoft/git) version.
