### ISSUE TITLE
Emit System.CodeDom.Compiler.GeneratedCodeAttribute on generated classes

### ISSUE THREAD

**Issue by IanKemp** [ErikEJ/EFCorePowerTools#2429]
The [`GeneratedCodeAttribute`](https://learn.microsoft.com/dotnet/api/system.codedom.compiler.generatedcodeattribute) is extremely useful to indicate to end-users the name of the tool that generated said code and, perhaps more importantly, the version. The latter is particularly useful given that (unlike NuGet packages) there is no central way to declare which version of the tool should be used, and different people can have different versions of the extension installed, leading to potentially unexpected results. This attribute would allow such a mismatch to be caught during code reviews.

**Comment by ErikEJ** [comment]
You mean add this in addition to the auto-generated xml tag?

Sure, I think it should be optional (something the user can opt in to)

Interested in doing a PR?

**Comment by ErikEJ** [comment]
As an alternative, the header could (optionally) be from

`// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>`

to:

`// <auto-generated> This file has been auto generated by EF Core Power Tools 2.6.398.</auto-generated>`

**Comment by ErikEJ** [comment]
@IanKemp ^^

**Comment by ErikEJ** [comment]
This is not something I plan to do, the assumption is that everyone is always using the latest or a curated version of the extension.

**Comment by CZEMacLeod** [comment]
I think the attribute can affect the IDE and how it works with the code. Some code analysis warnings etc. don't apply the same to generated code as to 'normal' code.
I think the XML tag is used for code documentation generation, rather than analysis, and it would probably be 'good practise' to have both.

**Comment by ErikEJ** [comment]
It is my understanding that the current XML tag is respected by the Roslyn analyzers

**Comment by ErikEJ** [comment]
@CZEMacLeod Link: https://github.com/dotnet/roslyn/blob/cf55f3a58e47298426fa971d3bd9d8857c746c65/src/Compilers/Core/Portable/InternalUtilities/GeneratedCodeUtilities.cs

**Comment by CZEMacLeod** [comment]
@ErikEJ Very interesting.
Looks like the file is here in `main` - https://github.com/dotnet/roslyn/blob/main/src/Compilers/Core/Portable/SourceGeneration/GeneratedCodeUtilities.cs

**Comment by ErikEJ** [comment]
@CZEMacLeod Based on that, do you still think this is important?

**Comment by ErikEJ** [comment]
@CZEMacLeod Thanks. The thing is - in reality I only support the latest version.

And adding the version number due to tool version bumps will cause Unneeded changes to source files. 

An opt in to add GeneratedCode attribute seems the way forward.

**Comment by ErikEJ** [comment]
@IanKemp @CZEMacLeod This is not something I plan to do, but feel free to submit a PR if you feel this is important
