### ISSUE TITLE
Consider switching Pluralizer to Humanizer

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#243]

**Comment by bricelam** [comment]
Send a PR to EF Core making it the default pluralizer!

**Comment by ErikEJ** [comment]
@bricelam Not sure what you mean - EF Core does not have a pluralizer??

**Comment by bricelam** [comment]
Nope, we “pluralize” table names by using the name of the DbSet property. We just added the IPluralizer interface as a hook for reverse engineering, but there’s no real implementation that ships “in the box” (I provide one in my Bricelam.EFCore.Pluralizer package)

**Comment by ErikEJ** [comment]
So you propose that EF Core should include an implementation?

**Comment by bricelam** [comment]
Yes, that leverages Humanizer. The Roslyn team also uses it at design time for variable name prediction, so it seems like a good fit.

**Comment by ErikEJ** [comment]
Has now been implemented in the latest daily build
