### ISSUE TITLE
DatabaseFacade - SqlQueryRaw not found

### ISSUE THREAD

**Issue by agsy** [ErikEJ/EFCorePowerTools#2430]
Hi there,
I switched from using EF6 to EF8 and I've regenerated my classes (Reverse Engineer) but I am now getting this error - "DatabaseFacade does not contain a definition for SqlQueryRaw..." from the auto generated file called "DBContextExtensions.cs". Do you know how I can fix it?

Thanks.

Regards,
Allan

**Comment by ErikEJ** [comment]
Have you updated your project(s) to use EF Core 8? Share your .csproj file

**Comment by agsy** [comment]
Yes I did. Here is the screenshot of my .csproj

![csproj_screenshot](https://github.com/user-attachments/assets/7a4881db-d341-4a46-a1c6-48cd2d165a7e)

**Comment by ErikEJ** [comment]
No you did not update your packages. You use EF Core 5 still. Look at the PackageReference section!

**Comment by agsy** [comment]
Ah ok, sorry I missed understood, I will use EF8 and regenerate the classes. Thanks.

**Comment by ErikEJ** [comment]
No need to re-generate, just update your packages

**Comment by agsy** [comment]
It works, thanks Erik. I tried re-generating just to see if there is any difference and I noticed that the DBContext doesn't have any parameterless base constructor anymore? Would you know how to automatically add it when re-generating the classes?

**Comment by ErikEJ** [comment]
You can add it in a partial class. But why do you need it?

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
