### ISSUE TITLE
Any way to set a default value for a property? (Question, not a bug)

### ISSUE THREAD

**Issue by mejobloggs-cw** [ErikEJ/EFCorePowerTools#2431]
Example EFCorePowerTools generated class:

```
public partial class Region
{
    public Region()
    {
        Branch = new HashSet<Branch>();
    }

    public int Id { get; set; }
    public string Name { get; set; }
    public bool Enabled { get; set; }

    public virtual ICollection<Branch> Branch { get; set; }
}
```

I tried setting `public bool Enabled { get; set; } = true;` but of course, next time EFCorePowerTools is run, it will reset it back to default.

I also tried creating another partial class like so:

```
public partial class Region
{
    public bool Enabled { get; set; } = true;
}
```
or
```
public partial class Region
{
    public Region()
    {
        Enabled = true;
    }
}
```

But C# doesn't allow this because either Enabled already exists, or the default constructor already exists.

Is there any way to set a default value in c#?

It's not a big deal, I'm just curious.

Thanks

**Comment by ErikEJ** [comment]
Unless you use t4 templates, I cannot think of any way to do it.
