### ISSUE TITLE
Reverse engineering is stuck in a loop that crashes visual studio 2022 Version 17.10.4.

### ISSUE THREAD

**Issue by afeslava** [ErikEJ/EFCorePowerTools#2433]
# Problem with Version EF_Core_Power_Tools_v2.6.398
## To reproduce:
Simply need to create a c# library application in Core 8 or console type, try to reverse engineer a database with sql 2019 and the problem occurs. 
### It is necessary to kill the process of the VS2022 instance to terminate it.
I have tried with 2 simple databases and the problem is repeated.
I do not have a version of EF Core Power Tools to install.
I have not found any log created after killing the process.

**Comment by ErikEJ** [comment]
@afeslava There is nothing to help with here, and you say that PowerTools are not installed !??

Have you tried the CLI ?

**Comment by afeslava** [comment]
> @afeslava There is nothing to help with here, and you say that PowerTools are not installed !??
> 
> Have you tried the CLI ?

Yes. And the problem is not with the tools, but with vs2022 version. I uninstall it, then install the latest vs2022 preview version, reinstall de ef core power tools, and it start working find again.
Thanks a lot.

**Comment by ErikEJ** [comment]
If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by afeslava** [comment]
Yes I will. It is a great tool.
Congratulations.
Thanks for taking the time to answer.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
