### ISSUE TITLE
[Feature] Reverse Engineering with configurable OutputDirectories

### ISSUE THREAD

**Issue by saigkill** [ErikEJ/EFCorePowerTools#2437]
I like the EF Core Powertools and its Reverse Engineering function.

But could it be possible, to add a feature for configuring the Output Directories? Anything like:

* Infrastructure/DataContext
* Infrastructure/Entities

So the RE Function places the Output in the right directories?

**Comment by ErikEJ** [comment]
I think it is already there under options/ advanced options - https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#file-layout

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by saigkill** [comment]
@ErikEJ Oh indeed. I haven't noticed that button. Your solution is perfect.

**Comment by ErikEJ** [comment]
You are very welcome!

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
