### ISSUE TITLE
Option "Prefer async calls" is missing

### ISSUE THREAD

**Issue by JimF42** [ErikEJ/EFCorePowerTools#2445]
I recently upgraded to 2.6.403 and I am only seeing async calls for stored procedures.

I do not code in an environment where keeping track of async calls would be useful (no users waiting for data, steps must be lockstep, etc.), so I have never used them. Not having synchronous calls will force me to rewrite several existing projects every time I have to touch them in the future.

How do I get back to non-async calls?

### Technical details

- EF Core Power Tools version: 2.6.403
- Exact Visual Studio version: Visual Studio 2022 17.10.5
- Database engine: SQL Server
- EF Core version in use: EF Core 6
- Is Handlebars templates used: no
- Is T4 templates used: no
- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
Set the option in efpt.config.json to false?

**Comment by JimF42** [comment]
Thank you for the extremely quick response. Yes, that worked just fine, but I was expecting a GUI option for that.

Thanks,
Jim

**Comment by ErikEJ** [comment]
There is no GUI option for it. 

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
