### ISSUE TITLE
Errors every time when connecting to localDB in a code first VS2020 blazor web app project.

### ISSUE THREAD

**Issue by DrHoneyBear** [ErikEJ/EFCorePowerTools#2447]
Create a bug report, feature proposal, or ask a question.

NOTICE: A bug report without sufficient technical and repro details and version information WILL BE CLOSED WITHOUT ANY FURTHER ACTION.

Create an empty VS Blazor web app project.

Create a data class, anything will do.

In VS in the Project, right click Add -> New Scaffolded Item.
Select Razor Component using Entity Framework (CRUD). Click Add.

For Template keep CRUD. Select the model class you created. Create a new DbContext Class. Click Add.

A (localdb)\\mssqllocaldb instance is created. In my case under C:\Users\daz.smith\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\mssqllocaldb

Run the app. Test data can be added and viewed , and persists.

All good. Basic stuff.

Now try to connect to that db instance in EF Core Power Tools. Whatever i do doesnt work.  I keep getting an error. It does not matter what connection settings I use or options, it yields the same error every time. VS Blazor scaffolding has created the localDB connection and data. It is there.  There connection string is for a localDB ...

"Server=(localdb)\\mssqllocaldb;Database=Licenses;Trusted_Connection=True;MultipleActiveResultSets=true"

... but power tools just won't connect.

I cannot populate database name because the connection to the instance isn't working so nothing is retrieved here.
 
![image](https://github.com/user-attachments/assets/7d715439-204a-4b79-9434-1bba628b68e7)

If i try custom connection , using connection string as above  with MYSQL selected, another error is generated:

![image](https://github.com/user-attachments/assets/9c2bf54c-cdb5-403e-a40d-2e45b1982e0d)

### Provide technical details

- EF Core Power Tools version: 2.6.417

- Exact Visual Studio version: (e.g. Visual Studio 2022 17.10.4

- Database engine:  not sure! NET8 has it's own configured from the DbContext you use. I'm a beginner so not sure. Think it's MYSQL
- 
- EF Core version in use: (e.g. EF Core 8)

- Is Handlebars templates used: no

- Is T4 templates used: no

- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
I think you have an extra `\` in the name

**Comment by DrHoneyBear** [comment]
Hi..
But that is the connection string from VS. it works in sql sever studio.
so..?

**Comment by ErikEJ** [comment]
Have you tried with double \ ??

**Comment by DrHoneyBear** [comment]
hi
hang on!
just realised, the \\ is to escape the \ in the connection string i think.

I have left home so will try this later with a single \ in your app.

**Comment by DrHoneyBear** [comment]
Hi Erik
YES, YOU ARE CORRECT
There was 2x \ instead of 1
All works
perfect🤟

**Comment by ErikEJ** [comment]
Great! 


If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by DrHoneyBear** [comment]
No prob Erik
I use this tool once to scaffold the code then i expect to be working with
my code for about a year
So I've made a one time sponsorship today
Cheers!
