### ISSUE TITLE
[Feature Request] Support for IncludeColumns (rather than ExcludeColumns)

### ISSUE THREAD

**Issue by jwyza-pi** [ErikEJ/EFCorePowerTools#2449]
### Feature description

Presently we can exclude columns for a table using the `excludeColumns` property.  However, sometimes it would be cleaner to be able to do the opposite and just specify the columns we want to include.  (like if we have a table that has 50 columns but we really only want to map 3 or 4 of them).

I know that it's up to the developer to ensure that the included columns are the minimum needed to make a valid mapping, but that's OK imo.

### Provide technical details

- EF Core Power Tools version: EF Core Power Tools CLI 8.1.330 for EF Core 8

- Exact Visual Studio version: N/A

- Database engine: Azure SQL

- EF Core version in use: EFCore 8

- Is Handlebars templates used: no

- Is T4 templates used: yes

- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
Or you could just create a view?

**Comment by jwyza-pi** [comment]
That is certainly an option as well.  Just seemed like if we're going to allow excluding columns, you could make the same argument, of "why not create a view rather than exclude columns". :)

**Comment by ErikEJ** [comment]
I aldo prefer not to add more complexity to the codebase with two opposing options...

**Comment by jwyza-pi** [comment]
Understandable.  Thanks for your consideration :)
