### ISSUE TITLE
Improvements in generating calls for stored procedures

### ISSUE THREAD

**Issue by danutbelu** [ErikEJ/EFCorePowerTools#2453]
We need your support regarding an issue we are facing with while using EF Core Power Tools. Below is an example of how a stored procedure must be called correctly.
The class spu_GetEmployersResult is the entity used to map the result of the stored procedure. The async function spu_GetEmployersAsync is the one that is responsible for the execution of the stored procedure and for mapping the result to the above mentioned class.

public partial class spu_GetBigEmployersResult
{
    public string CUI { get; set; } = default!;
}

Task<List<spu_GetEmployersResult>> spu_GetEmployersAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);

public virtual async Task<List<spu_GetEmployersResult>> spu_GetEmployersAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
{
    var parameterreturnValue = new SqlParameter
    {
        ParameterName = "returnValue",
        Direction = System.Data.ParameterDirection.Output,
        SqlDbType = System.Data.SqlDbType.Int,
    };

    var sqlParameters = new []
    {
        parameterreturnValue,
    };
    var _ = await _context.SqlQueryAsync<spu_GetBigEmployersResult>("EXEC @returnValue = [dbo].[spu_GetEmployers]", sqlParameters, cancellationToken);

    returnValue?.SetValue(parameterreturnValue.Value);

    return _;
}

The problem is that for some reasons the generated code looks different for other stored procedures. Instead of creating a model class for mapping the result, the tool generates a call that returns a scalar(integer). The differences between the 2 approaches are:
- the result is int instead of a class like spu_GetStatusResult
- the stored procedure is executed using ExecuteSqlRawAsync instead of SqlQueryAsync

Below is the example of how the code looks like.

public virtual async Task<int> spu_GetStatusAsync(OutputParameter<bool?> Started, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
{
    var parameterStarted = new SqlParameter
    {
        ParameterName = "Started",
        Direction = System.Data.ParameterDirection.InputOutput,
        Value = Started?._value ?? Convert.DBNull,
        SqlDbType = System.Data.SqlDbType.Bit,
    };
    var parameterreturnValue = new SqlParameter
    {
        ParameterName = "returnValue",
        Direction = System.Data.ParameterDirection.Output,
        SqlDbType = System.Data.SqlDbType.Int,
    };

    var sqlParameters = new []
    {
        parameterStarted,
        parameterreturnValue,
    };
    var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [PaymentsLists].[spu_GetStatus] @Started = @Started OUTPUT", sqlParameters, cancellationToken);

    Started.SetValue(parameterStarted.Value);
    returnValue?.SetValue(parameterreturnValue.Value);

    return _;
}

Do you think it is possible for calls to certain stored procedures to be made in a specific manner as previously mentioned? This would save a lot of time in our work.

Thank you in advance.

Best regards,
Daniel Belu

**Comment by ErikEJ** [comment]
Have you checked the wiki for the different options for result set discovery?? That is most likely what you are facing.

At any rate I need create scripts in order to help you..

**Comment by danutbelu** [comment]
Hi Erik,

Thank you for your quick answer.
I checked the Wiki page and I already found something interesting regarding this topic that can help me to manually map the result set of an existing stored procedure to a class. I will try it out to see if it works.
In my opinion, providing a fix for this common issue could be a major improvement of this awesome product and worth the effort if you agree with me. I am looking forward to seeing the new version with the fix in place. Thank you for your valuable help.

Best regards,
Daniel Belu

**Comment by ErikEJ** [comment]
What kind of "fix" do you have in mind??

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by danutbelu** [comment]
I imagine a new option in the form of a check box - "Map stored procedures to result set" or "Do not map stored procedures to scalar". If this option is checked, then we generate the call to stored procedures as described in the code above.

**Comment by ErikEJ** [comment]
@danutbelu  Did you not read the wiki? It is a question of result set discovery
If you have unmappable stored procedure, just hand code the mapping or try the alternate methods described in the wiki. 

You are also not sharing any repro details dispute being asked to do so..

**Comment by ErikEJ** [comment]
https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#sql-server-stored-procedures
