### ISSUE TITLE
Renaming with efpt.renaming.json doesn't work if "Use table and column name directy from the database" is checked

### ISSUE THREAD

**Issue by UseMuse** [ErikEJ/EFCorePowerTools#2454]
Describe what is not working as expected.
Coloums and tables names renamed as per efpt.renaming.json config

Steps to reproduce
Simply check "Use table and column name directy from the database" in the option

Further technical details
EF Core Power Tools version: V2.6.417

Database engine: SQL Server

Microsoft Visual Studio Enterprise 2022 (64-bit) - Current
Version 17.10.5

Microsoft.EntityFrameworkCore 6.0.22

the need is the same as in the issue 4 years ago

**Comment by ErikEJ** [comment]
Please provide a schema, options file and expected versus actual results.

**Comment by UseMuse** [comment]
```json 
//efpt.config.json
{
  "CodeGenerationMode": 2,
  "ContextClassName": "ReadOnlyMsSqlDbContext",
  "ContextNamespace": "MyApiCore",
  "FilterSchemas": false,
  "IncludeConnectionString": false,
  "ModelNamespace": "MyApiCore",
  "OutputContextPath": "DAL\\MsSql\\DbContext",
  "OutputPath": "DAL\\Entity",
  "PreserveCasingWithRegex": true,
  "ProjectRootNamespace": "",
  "Schemas": null,
  "SelectedHandlebarsLanguage": 0,
  "SelectedToBeGenerated": 0,
  "T4TemplatePath": null,
  "Tables": [
    {
      "Name": "[dbo].[t_tag]",
      "ObjectType": 0
    },
    {
      "Name": "[dbo].[t_Product]",
      "ObjectType": 0
    }
  ],
  "UiHint": null,
  "UncountableWords": null,
  "UseAsyncStoredProcedureCalls": true,
  "UseBoolPropertiesWithoutDefaultSql": true,
  "UseDatabaseNames": true,
  "UseDateOnlyTimeOnly": false,
  "UseDbContextSplitting": false,
  "UseDecimalDataAnnotationForSprocResult": true,
  "UseFluentApiOnly": true,
  "UseHandleBars": true,
  "UseHierarchyId": false,
  "UseInflector": false,
  "UseLegacyPluralizer": false,
  "UseManyToManyEntity": false,
  "UseNoDefaultConstructor": true,
  "UseNoNavigations": true,
  "UseNoObjectFilter": false,
  "UseNodaTime": false,
  "UseNullableReferences": true,
  "UsePrefixNavigationNaming": false,
  "UseSchemaFolders": false,
  "UseSchemaNamespaces": false,
  "UseSpatial": false,
  "UseT4": false
}
//efpt.renaming.json
[
  {
    "SchemaName": "dbo",
    "Tables": [
      {
        "Columns": [
          {
            "Name": "id",
            "NewName": "Id"
          },
          {
            "Name": "title",
            "NewName": "Title"
          }
        ],
        "Name": "t_Tag",
        "NewName": "TTag"
      }
    ],
    "UseSchemaName": false
  }
]
```
```sql
CREATE TABLE [dbo].[t_tag](
	[id] [int] NOT NULL,
	[title] [varchar](255) NULL)

CREATE TABLE [dbo].[t_Product](
[ID_Product] [int] NOT NULL,
[Title] [varchar](255) NULL)
```
Expected result, c# classes
```c#
//
    public partial class TTag
    {
        public int Id { get; set; }
        public string? Title { get; set; }
    }
    public partial class t_Product
    {
        public int ID_Product { get; set; }
        public string? Title { get; set; }
    }
```
Historically, all models in the api project had the same class name as in db ms sql (example t_Product), there was a need to use snake case for all new tables (example t_tag).
How to make the majority use naming rules like "Use table and column name directly from the database"
And the smaller part (new entities in the db) used camel case for c#

**Comment by UseMuse** [comment]
Are there other ways to achieve the result I need in the current reality?

**Comment by ErikEJ** [comment]
@UseMuse Alternative would be to use a T4 template and fix the names there. Seems like a reasonable workaround you have found.

**Comment by UseMuse** [comment]
> @UseMuse Alternative would be to use a T4 template and fix the names there. Seems like a reasonable workaround you have found.

Unfortunately, ef core 6 not supports T4 template, transition to 7 and higher is not planned yet, thanks for the feedback

**Comment by ErikEJ** [comment]
Assume you are aware that EF Core 6 goes out of support in November, and EF Core 7 is already out of support?

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by UseMuse** [comment]
@ErikEJ when using two configuration files with the same context name and executing these configuration files, the context is overwritten, I expected summation, it looks like I'll have to give them different names and somehow combine them into one context, since they should all be accessible through one class and interface when injecting a dependency

**Comment by ErikEJ** [comment]
Don't assume summation, this is generated code. You can create partial classes to modify the configuration
