### ISSUE TITLE
Problem with executing stored procedure

### ISSUE THREAD

**Issue by heroult** [ErikEJ/EFCorePowerTools#2455]
Hello,
today I updated to version '2.6.417', and afterwards, the following issue was noticed when executing a stored procedure.
The entries for "HasNoKey" are being removed from every function and procedure.

`protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<BlogPostsCount>().HasNoKey();
}`

When I then call any stored procedure, the following error message appears:

_The entity type 'functionTestResult' requires a primary key to be defined. If you intended to use a keyless entity type, call 'HasNoKey' in 'OnModelCreating'. For more information on keyless entity types, see https://go.microsoft.com/fwlink/?linkid=2141943._

It does not matter, if the functionTestResult-Class has the "Keyless"-Attribute or not.

When I call the same procedure again after removing all functions from the model, everything works fine.
I could easily remove all functions from the model, but I would like to understand the reason behind this.

[efpt.config.json](https://github.com/user-attachments/files/16588481/efpt.config.json)

### Provide technical details
- EF Core Power Tools version: 2.6.417
- Exact Visual Studio version: Microsoft Visual Studio Community 2022 (64-bit) - Version 17.10.5
- Database engine: Microsoft SQL Server Standard (64-bit) 13.0.4001.0
- EF Core version in use: EF Core 8
- Is Handlebars templates used: no
- Is T4 templates used: yes
- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
What exact EF Core version do you use at runtime??

**Comment by ErikEJ** [comment]
@heroult Ping?

**Comment by heroult** [comment]
Thank you very much for the unexpectedly quick response.

```
<TargetFramework>net8.0-windows7.0</TargetFramework>
<PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="8.0.0" />
<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.0" />
```

P.S.: I wrote the last message in the evening after a very long and hot European summer day.

**Comment by ErikEJ** [comment]
You need to update to the latest EF Core 8 release, 8.0.7 or later. It is a bug in 8.0.0.

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by heroult** [comment]
Thank you, it is working, that simple fix ...

**Comment by ErikEJ** [comment]
@heroult  You are very welcome!

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
