### ISSUE TITLE
Unclear prompts when uninstalling EF Core Power Pack

### ISSUE THREAD

**Issue by peteraritchie** [ErikEJ/EFCorePowerTools#2458]
When I uninstall EF Core Power Pack (to re-install), I get the following obtuse prompt:
![image](https://github.com/user-attachments/assets/0769028d-7fa5-4a26-82cf-a0558e3193d3)

**Yes**, **No**, or **Cancel** doesn't appropriately answer the question _You are about to schedule EF Core Power Pack for uninstall. What would you like to do with the 5 included extensions we found?_ so it's not clear what will happen next.

And when I click *Yes* I get this prompt:
![image](https://github.com/user-attachments/assets/c134ba0a-4c72-4d5f-9f5e-9cd0a6a9a20b)
Similarly, Yes, or No does not make it clear what will happen next.

### Provide steps to reproduce a bug

Uninstall EF Core Power Pack via Visual Studio Extension Manager.

### Provide technical details

- EF Core Power Tools version: 2.6.417

- Exact Visual Studio version: Visual Studio 2022 17.11.10

- Database engine: Postgres

- EF Core version in use: 8.0.3

- Is Handlebars templates used: no

- Is T4 templates used: no

- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
You need to adress this feedback to VS community feedback  - it is completely out of my control...

**Comment by peteraritchie** [comment]
I was hoping that wasn't the case :(
