### ISSUE TITLE
Error: Could not open options file: dabbuilder

### ISSUE THREAD

**Issue by emiliosanchis** [ErikEJ/EFCorePowerTools#2459]
When running the "Data API Builder Scaffold" option, after selecting the table/tables I get the following error:

System.InvalidOperationException: Result error: 
Could not open options file: dabbuilder

   at string EFCorePowerTools.Handlers.ReverseEngineer.ResultDeserializer.BuildDiagramResult(string output)
   at async Task<string> EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.GetDiagramInternalAsync(string arguments)
   at async Task<string> EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.GetDabConfigPathAsync(string optionsPath, string connectionString)
   at async Task EFCorePowerTools.Handlers.ReverseEngineer.DabBuilderHandler.GenerateFilesAsync(string optionsPath, string connectionString)
   at async Task EFCorePowerTools.Handlers.ReverseEngineer.DabBuilderHandler.BuildDabConfigAsync(Project project)

### Provide technical details

- EF Core Power Tools version: 2.6.422

- Exact Visual Studio version: 17.11.0

- Database engine: SQL Server

- EF Core version in use: EF Core 8

- Is Handlebars templates used: no

- Is T4 templates used: no

- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
Could you try downgrading to the latest official build? .420 

Also  try to remove the efreveng folders in the %temp% folder

**Comment by emiliosanchis** [comment]
I have installed the stable version 2.6.420 and I have deleted the efreveng folders and it still gives me the error. I use Visual Studio in Spanish and Windows in Spanish

System.InvalidOperationException: Result error: 
Could not open options file: dabbuilder

   at string EFCorePowerTools.Handlers.ReverseEngineer.ResultDeserializer.BuildDiagramResult(string output)
   at async Task<string> EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.GetDiagramInternalAsync(string arguments)
   at async Task<string> EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.GetDabConfigPathAsync(string optionsPath, string connectionString)
   at async Task EFCorePowerTools.Handlers.ReverseEngineer.DabBuilderHandler.GenerateFilesAsync(string optionsPath, string connectionString)
   at async Task EFCorePowerTools.Handlers.ReverseEngineer.DabBuilderHandler.BuildDabConfigAsync(Project project)

**Comment by ErikEJ** [comment]
I will try to reproduce next week.. Sorry for the inconvienience

**Comment by ErikEJ** [comment]
Try to go to the efreveng8 temp folder and run:

efreveng8 dabbuilder "path to dab-options.json" "your connection string"

**Comment by emiliosanchis** [comment]
I have created a dab-config.json file with the statement
dab init --database-type "mssql" --host-mode "Development" --connection-string "Server=server6;User Id=XXX;Database= Borrar;Password=XXXX;TrustServerCertificate=True ;Encrypt=True;"

I have added a table with the statement

dab add QF_Alertas --source "dbo.QF_Alertas" --permissions "anonymous:*"

It has generated the following file for me:

{
  "$schema": "https://github.com/Azure/data-api-builder/releases/download/v1.2.10/dab.draft.schema.json",
  "data-source": {
    "database-type": "mssql",
    "connection-string": "Server=server6;User Id=XXXXDatabase=Borrar;Password=XXX;TrustServerCertificate=True;Encrypt=True;",
    "options": {
      "set-session-context": false
    }
  },
  "runtime": {
    "rest": {
      "enabled": true,
      "path": "/api",
      "request-body-strict": true
    },
    "graphql": {
      "enabled": true,
      "path": "/graphql",
      "allow-introspection": true
    },
    "host": {
      "cors": {
        "origins": [],
        "allow-credentials": false
      },
      "authentication": {
        "provider": "StaticWebApps"
      },
      "mode": "development"
    }
  },
  "entities": {
    "QF_Alerts": {
      "source": {
        "object": "dbo.QF_Alertas",
        "type": "table"
      },
      "graphql": {
        "enabled": true,
        "type": {
          "singular": "QF_Alertas",
          "plural": "QF_Alertas"
        }
      },
      "rest": {
        "enabled": true
      },
      "permissions": [
        {
          "role": "anonymous",
          "actions": [
            {
              "action": "*"
            }
          ]
        }
      ]
    }
  }
}

When running 

efreveng80 dabbuilder "c:\users\esanchis\source\repos\ConsoleApp3\consoleApp3\dab-config.json" "Data Source=server6;Initial Catalog=Borrar;TrustServerCertificate=True;user id=XXXX;Pwd=XXXX"

It gives me the following error:

Error:
System.ArgumentOutOfRangeException: unsupported database type: Undefined (Parameter 'options')
   at IServiceCollection RevEng.Core.ServiceProviderBuilder.AddEfpt(IServiceCollection serviceCollection, ReverseEngineerCommandOptions options, List<string> errors, List<string> warnings, List<string> info) in C:/Code/Github/EFCorePowerTools/src/Core/RevEng. Core.60/ServiceProviderBuilder.cs:line 151
   at new RevEng.Core.DabBuilder(DataApiBuilderOptions dataApiBuilderCommandOptions) in C:/Code/Github/EFCorePowerTools/src/Core/RevEng.Core.80/DabBuilder.cs:line 38
   at async Task<int> EfReveng.Program.Main(string[] args) in C:/Code/Github/EFCorePowerTools/src/Core/efreveng60/Program.cs:line 147


All tests are with an "On Premise" SQL Server

**Comment by ErikEJ** [comment]
Thanks for trying, but you should have a dab-options.json file in your project folder. Use that.

**Comment by ErikEJ** [comment]
Wonder if you have a special character like a quotation mark (") in your password?

**Comment by emiliosanchis** [comment]
No, I do not have any dab-options.json file in the project folder, that is why I have looked for how to create the file with the dab utility.

I do not have special characters in the password or the username

**Comment by ErikEJ** [comment]
Thanks for all your help. I will have a closer look beginning of next week.

**Comment by ErikEJ** [comment]
I am unable to repro, but have added som additionl tracing to a efrevengparams.txt file in your temp folder to the latest daily build, could you give that a try?

**Comment by emiliosanchis** [comment]
I have installed the latest daily build 2.6.432 and it produced the following efrevengparams.txt file
[efrevengparams.txt](https://github.com/user-attachments/files/16759461/efrevengparams.txt)

The error is still:

System.InvalidOperationException: Result error: Could not open options file: dabbuilder at string EFCorePowerTools.Handlers.ReverseEngineer.ResultDeserializer.BuildDiagramResult(string output) at async Task<string> EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.GetDiagramInternalAsync(string arguments) at async Task<string> EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.GetDabConfigPathAsync(string optionsPath, string connectionString) at async Task EFCorePowerTools.Handlers.ReverseEngineer.DabBuilderHandler.GenerateFilesAsync(string optionsPath, string connectionString) at async Task EFCorePowerTools.Handlers.ReverseEngineer.DabBuilderHandler.BuildDabConfigAsync(Project project)

**Comment by emiliosanchis** [comment]
Installed version 2.6.437 and it worked correctly. Thank you very much

**Comment by ErikEJ** [comment]
@emiliosanchis Thanks for your patience and help! I will create a new official release

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
