### ISSUE TITLE
Question: Can i Comment fields that were in generation v1 and preserve the comments in regeneration of entities in v2?

### ISSUE THREAD

**Issue by mwardell-Katmai** [ErikEJ/EFCorePowerTools#2466]
Hello EFCore Power Tools:
   I am wondering if i can set a marker for preserving comments so that regeneration will not overwrite comments in generated files.

Mark Wardell

**Comment by ErikEJ** [comment]
Add the comments in your database

**Comment by ErikEJ** [comment]
@mwardell-Katmai Ping?

**Comment by mwardell-Katmai** [comment]
Thanks my team will give that a shot!
