### ISSUE TITLE
EF Tools while reverse engineering Oracle schema is not enumerating Function objects.

### ISSUE THREAD

**Issue by HowardFedTec** [ErikEJ/EFCorePowerTools#2469]
Thank you for your time to review this issue.

When using EF Core Power Tools 2.6.422 to reverse engineer my Oracle 19c database the schema "Function" objects are not displaying in the enumeration of objects.

### Provide steps to reproduce a bug
I tried connecting using the named user/owner of the schema in my connection. It did not work for me.
I tried connecting using SYS as SYSDBA in my connection with filtering on specific schema. It did not work for me. Both attempts returned the same results in the image below.

The Oracle function is compiled and valid. I can execute the function with SQL Developer and SQLPlus using the named user and the SYS account. I am also able to successfully execute the "function" using VS2022 Server Explorer.

Using VS2022 server explorer I can view my function, tables, and view objects that are in the schema I am reverse engineering.
![image](https://github.com/user-attachments/assets/353787cb-aeb7-424d-8eb7-085fad109e04)

When running EFCPT during selection of my database schema objects, my database schema functions are not being enumerated for reverse engineering.
![image](https://github.com/user-attachments/assets/a7c7a205-01a1-4883-bce5-01b92024f557)

### Provide technical details

- EF Core Power Tools version: 
EF Core Power Tools 2.6.422
![image](https://github.com/user-attachments/assets/a15e788d-3d85-4147-999a-7524cebda4e9)

- Exact Visual Studio version: 
Microsoft Visual Studio Enterprise 2022 (64-bit) - Current
Version 17.10.6

- Database engine: 
Oracle 19c 19.23.0.0.0

- EF Core version in use:
EF Core 7 or EF Core 8. I tried both configurations on the version selection dialog.

- Is Handlebars templates used: no/yes
No
- Is T4 templates used: no/yes
No
- Is a SQL Server .dacpac used: no/yes
No

**Comment by ErikEJ** [comment]
I have not implemented support for mapping Oracle functions. But happy to review a PR some anyone willing to contribute this feature

**Comment by HowardFedTec** [comment]
It's going to take me time to be able to spin up on something like this. Would my best path be to get the repository and work on my own local branch or to fork the project and work in that first? I've begun reading the documentation on your site about contributing and just want to make sure anything I do fulfills the project requirements.

Thanks!

**Comment by ErikEJ** [comment]
Standard way is to create a branch in your own fork: https://docs.github.com/en/get-started/exploring-projects-on-github/contributing-to-a-project
