### ISSUE TITLE
Getting Error while loading solution

### ISSUE THREAD

**Issue by arunprasathv** [ErikEJ/EFCorePowerTools#247]
@ErikEJ 
Getting this message now while loading solution and from the project when right-click and select reverse engineer, it was working before. I uninstalled and reinstalled again but still getting the same issue. 

![image](https://user-images.githubusercontent.com/7142390/63179793-ebd81380-c01a-11e9-9af7-6afa48e8b885.png)

Visual Studio version:  Visual Studio 2017 15.7.4.

**Comment by ErikEJ** [comment]
What is in the activitylog.xml ??

**Comment by arunprasathv** [comment]
<type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [EFCorePowerToolsPackage]Source: &apos;EFCorePowerTools&apos; Description: Could not load file or assembly &apos;Microsoft.VisualStudio.Threading, Version=15.8.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;System.IO.FileNotFoundException: Could not load file or assembly &apos;Microsoft.VisualStudio.Threading, Version=15.8.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;File name: &apos;Microsoft.VisualStudio.Threading, Version=15.8.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos;&#x000D;&#x000A;   at EFCorePowerTools.EFCorePowerToolsPackage.InitializeAsync(CancellationToken cancellationToken, IProgress`1 progress)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass17_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.GetResult()&#x000D;&#x000A;&#x000D;&#x000A;WRN: Assembly binding logging is turned OFF.&#x000D;&#x000A;To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.&#x000D;&#x000A;Note: There is some performance penalty associated with assembly bind failure logging.&#x000D;&#x000A;To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].&#x000D;&#x000A;</description>

**Comment by ErikEJ** [comment]
Looks like you should consider a VS update, I Will update the required versioner.

**Comment by arunprasathv** [comment]
doesn't EFCore  support VS 2017 ?

**Comment by ErikEJ** [comment]
It does, but you are not running the latest VS 2017 update

**Comment by UweR70** [comment]
Error ocours again (in VS 2019)

**Comment by ErikEJ** [comment]
@UweR70 repair VS?

**Comment by ErikEJ** [comment]
@UweR70 this is a very old issue, please create a new one with proper details
