### ISSUE TITLE
UseSchemaFolders + UseSchemaNamespaces works for Entities, not for Configurations (mappings)

### ISSUE THREAD

**Issue by hidegh** [ErikEJ/EFCorePowerTools#2470]
Create a bug report, feature proposal, or ask a question.

NOTICE: A bug report without sufficient technical and repro details and version information WILL BE CLOSED WITHOUT ANY FURTHER ACTION.

### Provide steps to reproduce a bug
select a database with multiple schemas
in the ef power tools select:
   "UseSchemaFolders": true,
   "UseSchemaNamespaces": true
   
Please include a **complete** description of the issue or link to a project that I can run to reproduce the issue.

🆗  The entities are split into folders, each entity also has the namespace extended (although a Schema suffix is added to the schema name).
❌  But the Configurations are not handled the same way - see attached file (with "trimmed" configurations)

![image](https://github.com/user-attachments/assets/6a7e97ef-58e4-488e-9923-fbac4817984e)

### Provide technical details

- EF Core Power Tools version: 2.6.420

- Exact Visual Studio version: Visual Studio 2022 17.10.6

- Database engine: Azure SQL

- EF Core version in use: EF Core 8

- Is Handlebars templates used: NO

- Is T4 templates used: NO

- Is a SQL Server .dacpac used: NO

**Comment by hidegh** [comment]
Have you considered to use customization via placeholders, like:
namespace: MyProject.Data.Persistence.{schema}
folder: ./Model/{schema}

**Comment by ErikEJ** [comment]
No. I am open to a design proposal and a PR, but keep in mind this is only a preview feature
