### ISSUE TITLE
Disable pluralisation in power tools cli

### ISSUE THREAD

**Issue by saigkill** [ErikEJ/EFCorePowerTools#2471]
### Provide steps to reproduce a bug

As example we have a table called "ExtraData" what holds some additional information about anything. So the cli gives me on the end a "ExtraDatum" entity. So a developer who searches for "ExtraData" he cant find it directly. 
The Visual Studio Tool provides a feature, to disable that happening. For the cli tool i have used the "use-database-names": true setting. So far as i can see, the cli config doesn't provide another setting of this.
Could it be possible to get that feature in the cli too?

### Provide technical details

- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
ErikEJ.EFCorePowerTools.Cli 8

- Exact Visual Studio version: (e.g. Visual Studio 2022 17.6.5)
Visual Studio 2022

- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)
SQL Server

- EF Core version in use: (e.g. EF Core 7)
EF Core 8

- Is Handlebars templates used: no/yes
no

- Is T4 templates used: no/yes
no

- Is a SQL Server .dacpac used: no/yes
no

**Comment by ErikEJ** [comment]
https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#pluralization appears to be missing docs for the CLI.

You can of course disable pluralization with the CLI:

**Comment by ErikEJ** [comment]
See this: https://github.com/ErikEJ/EFCorePowerTools/blob/master/samples%2Fefcpt-config.json#L48

**Comment by saigkill** [comment]
Thank you Eric. That works as expected. Thank you very much.

**Comment by ErikEJ** [comment]
Keeping open to update the docs

**Comment by ErikEJ** [comment]
@saigkill It was already documented here, let me know how you missed it: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#choose-options
