### ISSUE TITLE
Generate README with warnings

### ISSUE THREAD

**Issue by saigkill** [ErikEJ/EFCorePowerTools#2472]
Hello Eric,

just one question.
By using the VS extension the tool creates after finish  a README file, what contains all errors what happened. The CLI tool has just the README without that errors. Is it possible to enable this?
It would be nice as reference, where users can check if their stuff is affected without check the build log.

**Comment by ErikEJ** [comment]
With the CLI tool you can just pipe the output of running it to a file - would that work for you?

**Comment by saigkill** [comment]
Hi Eric. That works perfectly. Thank you very much.
