### ISSUE TITLE
Stored Procedure mapping issues

### ISSUE THREAD

**Issue by startovernow** [ErikEJ/EFCorePowerTools#2474]
For stored procedures, I am having following issues:
 
1. No matter what I try, the stored procedure result sets are all empty partial class. I understand that I can add the missing properties in a partial class. I am just wondering what I missed, since we have a lot of stored procedures...

2.  For stored procedures returning a simple value like int or decimal, how can I force those generated stored procedure code return a value, such as Task<int> or Task<decimal>, instead of  Task<List<somePartialClass>> ?

Thanks!

Below are some details

- EF Core Power Tools version: 2.6.420

- Exact Visual Studio version: 2022 Version 17.10.6

- Database engine: SQL Server

- EF Core version in use: EF Core 8

- Is Handlebars templates used: no

- Is T4 templates used: no
- Is a SQL Server .dacpac used: yes

**Comment by ErikEJ** [comment]
Please provide a sample schema that repros the issue, there could be room for improvements. Sproc discovery from a .dacpac is a new feature, and there could be some rough edges.

For any type of non standard stored procedure result set discovery, use a live database rather than a .dacpac, and of course refer to the advice and tips in the wiki.

**Comment by startovernow** [comment]
Hello Erik,
For example, I have a sp return a decimal, in old EF, the generated code:
`public virtual ObjectResult<Nullable<decimal>> sp_Get_Rate(string code, Nullable<decimal> bal, Nullable<decimal> adj)
{
//setup parameters
return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("sp_Get_Rate", parm1, parm2, parm3);
}`

After converting, new generated code:
`public virtual async Task<List<sp_GetRateResult>> sp_Get_RateAsync(string Code, decimal? Bal, decimal? Adj, OutputParameter<int> erturnValue = null, CancellationToken cancellationToken = default)
{
//setup parameters
var _ = await _context.SqlQueryAsync<sp_Get_RateResult>("EXE @returnValue = [dbo].[sp_Get_Rate] ...;
...
}`

How can I force new code to just return 
`Task<decimal?> or Task<Nullable<decimal>>, instead of Task<List<sp_GetRateResult>>, where sp_GetRateResult is generated empty partial class?`

Many thanks!

**Comment by ErikEJ** [comment]
@startovernow that looks like a quirky stored procedure. In order to help I also need the script to create the referenced tables.

Did you try the alternate discovery method.

**Comment by startovernow** [comment]
Thank you. Those SPs were done by someone else long time ago...
Sorry I couldn't find it, What is the "alternate discovery method"?  

    On Tuesday, August 27, 2024 at 10:29:12 AM CDT, Erik Ejlskov Jensen ***@***.***> wrote:  
 
 


@startovernow that looks like a quirky stored procedure. In order to help I also need the script to create the referenced tables.

Did you try the alternate discovery method.

**Comment by ErikEJ** [comment]
I strongly suggest you read the wiki!!

**Comment by ErikEJ** [comment]
Link to wiki: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering
