### ISSUE TITLE
Exception on Migrations Tool option click

### ISSUE THREAD

**Issue by Janek91** [ErikEJ/EFCorePowerTools#248]
Migrations Tool window is not showing. Instead an exception is thrown.

### Steps to reproduce
Click on "Migrations Tool" option

### Further technical details
EF Core Power Tools version: 2.3.8

Database engine: **SQL Server**

Visual Studio version: Visual Studio 2019 16.2.2

[StackTrace.txt](https://github.com/ErikEJ/EFCorePowerTools/files/3515412/StackTrace.txt)
[FusionLog.txt](https://github.com/ErikEJ/EFCorePowerTools/files/3515413/FusionLog.txt)

**Comment by ErikEJ** [comment]
You are using the daily build - how about the release version?

**Comment by Janek91** [comment]
Using release version 2.2.63 I get this error:
![obraz](https://user-images.githubusercontent.com/7473827/63330738-9f4f4980-c334-11e9-8477-c998c8974346.png)

**Comment by Janek91** [comment]
When I use release version 2.2.63 - everything works fine

**Comment by ErikEJ** [comment]
Thanks, I made some major changes to the build process, I will investigate

**Comment by ErikEJ** [comment]
Note: Revert to .NET FX 4.7.1

**Comment by jespersh** [comment]
Oh and this is the same issue I had that just required the version to match to the exact letter. (2.3.0 vs 2.3.0.0 vs. 1.0.0.0)

**Comment by ErikEJ** [comment]
Brittle! Fixed in latest daily build
