### ISSUE TITLE
No Default Constructor

### ISSUE THREAD

**Issue by JimF42** [ErikEJ/EFCorePowerTools#2480]
### Provide steps to reproduce a bug

Open a project and with a EFCorePowerTools and (re)generate the config.json. It doesn't matter the value of `UseNoDefaultConstructor` (mine is set to `"UseNoDefaultConstructor": false,`, no default constructor is created.

### Provide technical details

- EF Core Power Tools version: 2.6.437

- Exact Visual Studio version: Visual Studio 2022 17.11.2

- Database engine: SQL Server

- EF Core version in use: EF Core 8

- Is Handlebars templates used: no

- Is T4 templates used: no

- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
This only works under certain conditions, see https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#code-generation

**Comment by JimF42** [comment]
OK, I see.  I had been using EF 6 until recently when I changed to EF 8. It appears this change is specific to 7+.

I will have to create a `partial` class then.
