### ISSUE TITLE
Add support for numeric RowVersions (EF8 only)

### ISSUE THREAD

**Issue by jwyza-pi** [ErikEJ/EFCorePowerTools#2485]
In EF8 RowVersion columns can now be defined as ulongs via HasConversion. ([MS documentation](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-8.0/whatsnew#numeric-rowversions-for-sql-azuresql-server)).

It would be nice to be able to have a config that tells the scaffolding to include the `HasConversion<byte[]>()` and change the entity type from `byte[]` to `ulong`.

Something like `use-numeric-rowversion`.

### Provide technical details

- EF Core Power Tools version: 8.1.330+fc50f86365213b71a8119335d68035d03a06e734

- Exact Visual Studio version: N/A

- Database engine: Azure SQL

- EF Core version in use: EF8

- Is Handlebars templates used: no

- Is T4 templates used: yes (DbContext.t4, EntityType.t4)

- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
Sounds great!

**Comment by ErikEJ** [comment]
@jwyza-pi is this something you plan to submit a PR for - not sure exactly how to do this for reverse engineering though

**Comment by jwyza-pi** [comment]
Sorry, you didn't put the `help-wanted` label on it so was assuming it was something you'd look into.  I can try to take a look and see if it's possible to make this work.

**Comment by ErikEJ** [comment]
@jwyza-pi  That would be great!

**Comment by jwyza-pi** [comment]
So I think this is likely possible by creating a derivation of [CSharpEntityTypeGeneratorBase](https://github.com/dotnet/efcore/blob/main/src/EFCore.Design/Scaffolding/Internal/CSharpEntityTypeGenerator.cs) and [CSharpDbContextGenerator](https://github.com/dotnet/efcore/blob/main/src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs).  

However, I don't know we'd want to go that deep.  It's doable by customizing the T4 templates though.  So I'm thinking the suggestion might just be to put this in the documentation as an option for someone who wants it.  I was able to get it working by making the following change in the EntityType.t4 and DbContext.t4 files:

EntityType.t4
**Before:** (around Line 104)
```csharp
#>
    public <#= code.Reference(property.ClrType) #><#= needsNullable ? "?" : "" #> <#= property.Name #> { get; set; }<#= needsInitializer ? " = null!;" : "" #>
<#
```

**After:**
```csharp
        // Custom to use Convert RowVersion to long. 
        // https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-8.0/whatsnew#numeric-rowversions-for-sql-azuresql-server
        var propertyType = code.Reference(property.ClrType);
        if (
            property.FindTypeMapping() is Microsoft.EntityFrameworkCore.Storage.RelationalTypeMapping m
            && m.StoreType == "rowversion")
        {
            propertyType = "ulong";
            needsInitializer = false;
        }
        
#>
    public <#= propertyType #><#= needsNullable ? "?" : "" #> <#= property.Name #> { get; set; }<#= needsInitializer ? " = null!;" : "" #>
<#
```

DbContext.t4
**Before:** (around Line 197)
```csharp
#>
            entity.Property(e => e.<#= property.Name #>)<#= code.Fragment(propertyFluentApiCalls, indent: 4) #>;
<#
```

**After:**
```csharp
            // Custom to use Convert RowVersion to long. 
            // https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-8.0/whatsnew#numeric-rowversions-for-sql-azuresql-server
            string conversion = string.Empty;

            if (
                property.FindTypeMapping() is Microsoft.EntityFrameworkCore.Storage.RelationalTypeMapping m
                && m.StoreType == "rowversion")
            {
                conversion = ".HasConversion<byte[]>()";
            }
#>
            entity.Property(e => e.<#= property.Name #>)<#= code.Fragment(propertyFluentApiCalls, indent: 4) #><#= conversion #>;
<#
```

**Comment by ErikEJ** [comment]
@jwyza-pi Thanks, I do not plan to pull in (and maintain) this addtional code. I will add a link to this in the docs.

**Comment by jwyza-pi** [comment]
I kind of assumed that would be the case.  Thanks!

**Comment by ErikEJ** [comment]
I have added a link to this from #1499
