### ISSUE TITLE
PostgreSQL procedures are not generated in code

### ISSUE THREAD

**Issue by onurbural** [ErikEJ/EFCorePowerTools#2492]
I am attempting to reverse engineer PostgreSQL stored procedures and functions using EF Core Power Tools, but they are not being generated in the code, which makes them unusable. Despite including the procedures and functions in the reverse engineering process, they do not appear in the generated models or context.

Provide technical details
EF Core Power Tools version: 2.6.398

Exact Visual Studio version: Visual Studio 2022 17.9.0

Database engine: PostgreSQL (pgAdmin used)

EF Core version in use: EF Core 8.0

Is Handlebars templates used: No

Is T4 templates used: No

Is a SQL Server .dacpac used: No

**Comment by onurbural** [comment]
![image](https://github.com/user-attachments/assets/13458c07-c89c-4536-84df-39728c0e6cff)

![2Ekran Alıntısı](https://github.com/user-attachments/assets/8c3c0ca0-d124-4d88-80d9-3dbe7e0259a2)

![3Ekran Alıntısı](https://github.com/user-attachments/assets/47296f00-38b2-4da5-b692-edf1c98b5602)

There is no field where procedures are listed like in SQL.
![4Ekran Alıntısı](https://github.com/user-attachments/assets/07e2d58c-fb7f-42b3-a95c-9149ca8a43ca)


MSSQL view was as follows:
![Uploading 5Ekran Alıntısı.PNG…]()

**Comment by ErikEJ** [comment]
As requested when creating issues  please provide scripts to create the stored procedures and I will have a look.

**Comment by onurbural** [comment]
For example i have this procedure at my postgresql
BEGIN
    CREATE TEMP TABLE IF NOT EXISTS TempCategoryHierarchy (
        CategoryID INT,
        CategoryName VARCHAR,
        ParentCategoryID INT,
        FullPath VARCHAR,
        Level INT
    );

    TRUNCATE TABLE TempCategoryHierarchy;

    WITH RECURSIVE CategoryHierarchy AS (
        SELECT 
            c."CategoryID",
            c."CategoryName",
            cr."ParentCategoryID",
        	c."CategoryName"::varchar AS FullPath, 
            0 AS Level
        FROM public."Categories" c
        LEFT JOIN public."CategoryRelations" cr 
        ON c."CategoryID" = cr."ChildCategoryID"

        UNION ALL

        SELECT 
            c."CategoryID",
            c."CategoryName",
            cr."ParentCategoryID",
        	(ch.FullPath || ' -> ' || c."CategoryName")::varchar AS FullPath, 
            ch.Level + 1
        FROM public."Categories" c
        INNER JOIN public."CategoryRelations" cr 
        ON c."CategoryID" = cr."ChildCategoryID"
        INNER JOIN CategoryHierarchy ch 
        ON cr."ParentCategoryID" = ch."CategoryID"
    )
    INSERT INTO TempCategoryHierarchy
    SELECT * FROM CategoryHierarchy
    ORDER BY FullPath;

    PERFORM * FROM TempCategoryHierarchy;
END;

*/*/*/*/*/*/*/*/*/*/*/*/*/*/*//*/*/*/*/*/*//*/*/*/*/*/*/

AND I HAVE THIS FUNCTION

CREATE OR REPLACE FUNCTION public.tumunulistele(
	)
    RETURNS TABLE(categoryid integer, categoryname character varying, parentcategoryid integer, fullpath text, level integer) 
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE PARALLEL UNSAFE
    ROWS 1000

AS $BODY$
BEGIN
    RETURN QUERY
    WITH RECURSIVE CategoryHierarchy AS (
        SELECT 
            c."CategoryID",
            c."CategoryName",
            cr."ParentCategoryID",
            c."CategoryName"::varchar AS FullPath, 
            0 AS Level
        FROM public."Categories" c
        LEFT JOIN public."CategoryRelations" cr 
        ON c."CategoryID" = cr."ChildCategoryID"

        UNION ALL

        SELECT 
            c."CategoryID",
            c."CategoryName",
            cr."ParentCategoryID",
            (ch.FullPath || ' -> ' || c."CategoryName")::varchar AS FullPath,
            ch.Level + 1
        FROM public."Categories" c
        INNER JOIN public."CategoryRelations" cr 
        ON c."CategoryID" = cr."ChildCategoryID"
        INNER JOIN CategoryHierarchy ch 
        ON cr."ParentCategoryID" = ch."CategoryID"
    )
    SELECT * FROM CategoryHierarchy
    ORDER BY FullPath;
END;
$BODY$;

ALTER FUNCTION public.tumunulistele()
    OWNER TO postgres;

**Comment by ErikEJ** [comment]
I need the create statements for the referenced tables as well

**Comment by onurbural** [comment]
First of all, thank you for your interest.


I have 2 table in my db
![image](https://github.com/user-attachments/assets/37fb7f8b-499c-44fc-b9da-f702e1750eb6)


Cateogry Table =>
-- Table: public.Categories

-- DROP TABLE IF EXISTS public."Categories";

CREATE TABLE IF NOT EXISTS public."Categories"
(
    "CategoryID" integer NOT NULL,
    "CategoryName" text COLLATE pg_catalog."default",
    CONSTRAINT "Categories_pkey" PRIMARY KEY ("CategoryID")
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."Categories"
    OWNER to postgres;







----------------------------------------




Categoryrelations => 
-- Table: public.CategoryRelations

-- DROP TABLE IF EXISTS public."CategoryRelations";

CREATE TABLE IF NOT EXISTS public."CategoryRelations"
(
    "ParentCategoryID" integer NOT NULL,
    "ChildCategoryID" integer NOT NULL,
    CONSTRAINT "CategoryRelations_pkey" PRIMARY KEY ("ParentCategoryID", "ChildCategoryID")
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."CategoryRelations"
    OWNER to postgres;

**Comment by ErikEJ** [comment]
Thanks, I will have a closer look soon

**Comment by ErikEJ** [comment]
Ah. You are not using the latest version of the extension!! Please update if you want support, I believe this is already fixed.

**Comment by onurbural** [comment]
I am sorry for a lot of questions but where is postgresql ? 
![image](https://github.com/user-attachments/assets/61099eb6-8d41-44f3-91d7-726950ff5b71)

**Comment by ErikEJ** [comment]
Did you install the DDEX provider/ Power Pack??

**Comment by onurbural** [comment]
> Did you install the DDEX provider/ Power Pack??

yes
![image](https://github.com/user-attachments/assets/3f2849d6-b784-4f86-b282-8237d1663c3f)

**Comment by ErikEJ** [comment]
Then you should be able to pick that from the bottom drop down list

**Comment by onurbural** [comment]
Yes but i cant see postgresql selection

![image](https://github.com/user-attachments/assets/2c455d48-ab99-4590-93e2-95777d6bbf7e)

**Comment by ErikEJ** [comment]
Is it installed and enabled in your Extensions list?

Do you use VS ARM64?

**Comment by onurbural** [comment]
yes i use. i enabled my extension. still procedurs not listed

**Comment by ErikEJ** [comment]
Ah! I need the stored procedure create script causing this.

**Comment by ErikEJ** [comment]
@onurbural can you share the result of this query??

https://github.com/ErikEJ/EFCorePowerTools/blob/master/src%2FCore%2FRevEng.Core.60%2FRoutines%2FPostgresRoutineModelFactory.cs#L130

**Comment by ErikEJ** [comment]
@onurbural Ping?

**Comment by ErikEJ** [comment]
@onurbural I am going to close this, as I need the a stored procedure definition causing this issue in order to help further.
