### ISSUE TITLE
Add rev eng support for EF Core 9

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#2496]

**Comment by DickBaker** [comment]
I was confused that my .NET-9 console project only offered the DAB option (not Reverse Engineer).
I even uninstalled + reinstalled EFPT but no change.
However, changing TFM to .NET-8 unlocked the full list again.
seriously, you should grey-out the RE option and include advice to revert to get desired behaviour.

**Comment by ErikEJ** [comment]
@DickBaker Thanks for the feedback - I think I will rather just add support for EF Core 9 - but it is not an easy problem to solve...
