### ISSUE TITLE
EFPT renaming and Mysql

### ISSUE THREAD

**Issue by VaanRatsbane** [ErikEJ/EFCorePowerTools#250]
This is a follow up to #193 

Using the daily build (id 5a7c2525-ddd8-4c44-b2e3-f57ba01a0d81) I was finally able to properly add the connection and scaffold the database and context.

However, I noticed that the efpt renaming is not fully working. Single object properties are translated correctly, but the class names and collection properties still keep the original table names. I attempted this with a structurally identical database in another platform (Mssql) and it translated the names correctly, so I assume the issue is specific to Mysql.

**Comment by jespersh** [comment]
Could you provide a db structure sql-dump (create table statements, just a single table with 2-3 columns is fine), generated code and your intended code? :-)

**Comment by VaanRatsbane** [comment]
I have further read the documentation and it was an issue with the renaming file, removing the UseSchemaName (even if it was false) made it work again.
