### ISSUE TITLE
Reverse Engineer option not displaying

### ISSUE THREAD

**Issue by JosephWJMaxwell** [ErikEJ/EFCorePowerTools#2500]
Create a bug report, feature proposal, or ask a question.

NOTICE: A bug report without sufficient technical and repro details and version information WILL BE CLOSED WITHOUT ANY FURTHER ACTION.

### Provide steps to reproduce a bug

Unable to get the option to run reverse engineer 
![image](https://github.com/user-attachments/assets/2c702804-3fd3-475d-951b-017ee18ee9cf)

### Provide technical details

- EF Core Power Tools version: 2.6.437

- Exact Visual Studio version: Visual Studio 2022 17.1.2

- EF Core version in use: 3.1.32

**Comment by ErikEJ** [comment]
EF Core 3.1 is long out of support. I have an older unsupported build in the archive branch tools folder that you might be able to use when you transition to EF Core 8 or later.

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by ErikEJ** [comment]
How did you "run" it and what was the exact error??

**Comment by ErikEJ** [comment]
@JosephWJMaxwell Ping?
