### ISSUE TITLE
The file efpt.config.json keeps being overwritten.

### ISSUE THREAD

**Issue by ileadingpoint** [ErikEJ/EFCorePowerTools#2501]
The file efpt.config.json keeps being overwritten.

### Steps to produce the scenario:

- Do reverse engineer for db (the efpt.config.json will be generated)
- Do reverse engineer for another db the file efpt.config.json will be overwritten (that causes you to lose the history for the first db added).

**Comment by ErikEJ** [comment]
See the wiki for various ways to handle this, for example by renaming the file after a specific pattern

**Comment by ErikEJ** [comment]
If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by ileadingpoint** [comment]
And there is more point that the efpt.config.json will be overwritten wherever you put it.
if you tried to hide it ;)

**Comment by ileadingpoint** [comment]
I think there should be a way to create a multiple file in different directory

**Comment by ErikEJ** [comment]
There is - did you read the wiki??

**Comment by ErikEJ** [comment]
@ileadingpoint Ping?

https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#using-multiple-dbcontexts-in-the-same-project
