### ISSUE TITLE
Possible feature: automatic trimming of varchar fields in the model

### ISSUE THREAD

**Issue by dchillman123** [ErikEJ/EFCorePowerTools#2502]
feature proposal

### Provide technical details

- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
2.6.420
- Exact Visual Studio version: (e.g. Visual Studio 2022 17.6.5)
visual studio 17.11.3
- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)
SQL Server
- EF Core version in use: (e.g. EF Core 7)
EF Core 8

an option to create the models with automatic trimming of varchar fields would be useful

**Comment by dchillman123** [comment]
In several of my projects we access a sql server that has data written to
it by a third party application.  That application does not trim user input
so that tables contain string data that is not “trimmed”.  We have to add
code to trim data before use as it can cause issues further down the line.
I was wondering if it is possible to update the ef core to create models
that trim data automatically



e.g.,

current model for varchar fields created by your wonderful tool;

public string DigitalEvidence { get; set; }

 if an option existed for trimming varchar fields, the model might look
like this;

 protected string _DigitalEvidence;

public String DigitalEvidence

{

                get { return this._DigitalEvidence; }

                set { this._DigitalEvidence = (value == null ? value :
value.Trim()); }

}





Then when we retrieve the data it is automatically trimmed.





*From:* Erik Ejlskov Jensen ***@***.***>
*Sent:* Wednesday, September 11, 2024 8:39 AM
*To:* ErikEJ/EFCorePowerTools ***@***.***>
*Cc:* dchillman123 ***@***.***>; Author <
***@***.***>
*Subject:* Re: [ErikEJ/EFCorePowerTools] Possible feature: automatic
trimming of varchar fields in the model (Issue #2502)



Please provide more details..

—
Reply to this email directly, view it on GitHub
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ErikEJ_EFCorePowerTools_issues_2502-23issuecomment-2D2343871278&d=DwMFaQ&c=sdnEM9SRGFuMt5z5w3AhsPNahmNicq64TgF1JwNR0cs&r=EaMiT8Pm9Ou6ZL7-b18rNDVT7IQJCk19B_xDGLFZ54o&m=p1SYSKwZQPx7dKIKJbFMt3_6Ip06eUtu41l8SxbhwbkwIsIrk8ngxLpMMpON8YFk&s=peDJsTH6uOQVyDXQ1aJ_d23cxMpju3y61mGBXlO9fiQ&e=>,
or unsubscribe
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AG6LTJCN6WGUKOX32ZQD2LTZWBIZ7AVCNFSM6AAAAABOBD4VUOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGNBTHA3TCMRXHA&d=DwMFaQ&c=sdnEM9SRGFuMt5z5w3AhsPNahmNicq64TgF1JwNR0cs&r=EaMiT8Pm9Ou6ZL7-b18rNDVT7IQJCk19B_xDGLFZ54o&m=p1SYSKwZQPx7dKIKJbFMt3_6Ip06eUtu41l8SxbhwbkwIsIrk8ngxLpMMpON8YFk&s=Ua2IPJX5XEr1rfU1kVDSH_ZyXu5wrPapLbIPrVP9GKE&e=>
.
You are receiving this because you authored the thread.Message ID: <
***@***.***>

**Comment by ErikEJ** [comment]
This does not sound like something a lot of other users would benefit from. You should be able to do this with the t4 templates.

**Comment by dchillman123** [comment]
Ok.  Thanks for considering it.



*From:* Erik Ejlskov Jensen ***@***.***>
*Sent:* Thursday, September 12, 2024 3:24 AM
*To:* ErikEJ/EFCorePowerTools ***@***.***>
*Cc:* dchillman123 ***@***.***>; Author <
***@***.***>
*Subject:* Re: [ErikEJ/EFCorePowerTools] Possible feature: automatic
trimming of varchar fields in the model (Issue #2502)



This does not sound like something a lot of other users would benefit from.
You should be able to do this with the t4 templates.

—
Reply to this email directly, view it on GitHub
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ErikEJ_EFCorePowerTools_issues_2502-23issuecomment-2D2345735069&d=DwMFaQ&c=sdnEM9SRGFuMt5z5w3AhsPNahmNicq64TgF1JwNR0cs&r=EaMiT8Pm9Ou6ZL7-b18rNDVT7IQJCk19B_xDGLFZ54o&m=BqXOG4MFTQ8JyjzqAawz4g7Fo8DycJCraPoSc01zv4ISt1hhsAhaNdF1b7QJlB8N&s=-XWXWU2cSRjxmpb0aQlIzVCgtNjZDPiCtI0Fti8Rgik&e=>,
or unsubscribe
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AG6LTJEXLNBJBIZ2Q7HB62DZWFMSBAVCNFSM6AAAAABOBD4VUOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGNBVG4ZTKMBWHE&d=DwMFaQ&c=sdnEM9SRGFuMt5z5w3AhsPNahmNicq64TgF1JwNR0cs&r=EaMiT8Pm9Ou6ZL7-b18rNDVT7IQJCk19B_xDGLFZ54o&m=BqXOG4MFTQ8JyjzqAawz4g7Fo8DycJCraPoSc01zv4ISt1hhsAhaNdF1b7QJlB8N&s=_J_0UGrSqyGazen0PkHO-MIpgCZBWqslfxc1_rPf-I0&e=>
.
You are receiving this because you authored the thread.Message ID: <
***@***.***>
