### ISSUE TITLE
NotNull varchar column being mapped to property with default value of Null

### ISSUE THREAD

**Issue by Germs2004** [ErikEJ/EFCorePowerTools#2503]
### Provide steps to reproduce a bug

If I create a not-null varchar column in my table, I notice EF Core Power Tools maps that to a not-null "string" datatype, but also sets its default value to "null!".  If the column is supposed to be not-null, shouldn't it set the default value for those to string.Empty?  If the current behavior is intended, can I configure it somehow to use string.Empty instead of null?

The issue I'm having is when writing these objects to database using CsvHelper.  Since some properties are set to Null when the database doesn't allow nulls, it causes an error.  Letting them default to string.Empty instead seems it would fix that.

Example table
```
CREATE TABLE `aaaPerson` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`FirstName` VARCHAR(50) NOT NULL DEFAULT '' COLLATE 'latin1_swedish_ci',
	`MiddleName` VARCHAR(50) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`LastName` VARCHAR(50) NOT NULL DEFAULT '' COLLATE 'latin1_swedish_ci',
	`Nickname` VARCHAR(50) NOT NULL DEFAULT '' COLLATE 'latin1_swedish_ci',
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;
```

EfPowerTools creates this Class:
```
[Table("aaaPerson")]
public partial class aaaPerson
{
    [Key]
    [Column(TypeName = "int(11)")]
    public int id { get; set; }

    [StringLength(50)]
    public string FirstName { get; set; } = null!;

    [StringLength(50)]
    public string? MiddleName { get; set; }

    [StringLength(50)]
    public string LastName { get; set; } = null!;
}
```

### Provide technical details

- EF Core Power Tools version: 2.6.437

- Exact Visual Studio version: Visual Studio 2022 17.11.3

- Database engine: MariaDB 11.5

- EF Core version in use: EF 8

- Is Handlebars templates used: no

- Is T4 templates used: no

- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
Sounds like an issue with your input data / csvhelper that is entirely unrelated to EF Core...

**Comment by ErikEJ** [comment]
I will go ahead a close, since you found a workaround.

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
