### ISSUE TITLE
Microsoft SQL DB TimeOnly fields are recognized as TimeSpan

### ISSUE THREAD

**Issue by kbcowboy777** [ErikEJ/EFCorePowerTools#2505]
Create a bug report, feature proposal, or ask a question.

NOTICE: A bug report without sufficient technical and repro details and version information WILL BE CLOSED WITHOUT ANY FURTHER ACTION.

### Provide steps to reproduce a bug

Please include a **complete** description of the issue or link to a project that I can run to reproduce the issue.

### Provide technical details

- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)

- Exact Visual Studio version: (e.g. Visual Studio 2022 17.6.5)

- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)

- EF Core version in use: (e.g. EF Core 7)

- Is Handlebars templates used: no/yes

- Is T4 templates used: no/yes

- Is a SQL Server .dacpac used: no/yes

**Comment by ErikEJ** [comment]
@kbcowboy777 Which Power Tools version?? Are you on latest?

**Comment by ErikEJ** [comment]
This was fixed in 2.6.417
