### ISSUE TITLE
Add support for complex types

### ISSUE THREAD

**Issue by edavis1993** [ErikEJ/EFCorePowerTools#2507]
Would be great to add support for generating complex types

https://devblogs.microsoft.com/dotnet/announcing-ef8-rc1/#complex-types-as-value-objects

**Comment by ErikEJ** [comment]
How would that work/look for database first??

**Comment by edavis1993** [comment]
Looks like from their examples they just store the object in the database with an underscore.

`public class Customer
{
    public int Id { get; set; }
    public required string Name { get; set; }
    public required Address Address { get; set; }
    public List<Order> Orders { get; } = new();
}`
becomes
`[Customers] ([Name], [Address_City], [Address_Country], [Address_Line1], [Address_Line2], [Address_PostCode])`
So you could map the type by splitting at the underscore.

However, this would be limited as there second example of Order would cause an issue since the property names for Address don't match the type
`public class Order
{
    public int Id { get; set; }
    public required string Contents { get; set; }
    public required Address ShippingAddress { get; set; }
    public required Address BillingAddress { get; set; }
    public Customer Customer { get; set; } = null!;
}`

**Comment by edavis1993** [comment]
You could add the complex types into the OnModelCreatingPartial
`modelBuilder.Entity<Customer>()
        .ComplexProperty(e => e.Address);

    modelBuilder.Entity<Order>(b =>
    {
        b.ComplexProperty(e => e.BillingAddress);
        b.ComplexProperty(e => e.ShippingAddress);
    });`

but still how would it know that BillingAddress and ShippingAddress are of type Address

**Comment by ErikEJ** [comment]
This is not something I pakn to implement
