### ISSUE TITLE
Regex Renaming for reverse engineering?

### ISSUE THREAD

**Issue by hastarin** [ErikEJ/EFCorePowerTools#251]
Is it possible to override something somewhere to use a series of Regex patterns to rename tables/columns?  Or custom code?  This would be very handy for dealing with a database with common abbreviations used throughout.

Some examples of what I'm dealing with.
comp -> Competition
desc -> Description
phy -> Physical
etc

Or more specifically comp_r table with comp_id, comp_name, comp_desc, etc column names.

I started down the road of using _efpt.renaming.json_ and for table names it wasn't so bad but getting into the individual columns it's going to get tedious.

**Comment by ErikEJ** [comment]
My approach would be to create a tool to generate the efpt.renaming.json file.

**Comment by hastarin** [comment]
@ErikEJ First up, thanks for a great tool.

A tool is exactly what I did. Two CSV files, one with tables/column names and one with regex/replacement and a LINQPad script using Humanizer to generate the efpt.renaming.json file.

I was just checking in case I'd missed something.  Perhaps consider it as a future feature if it fits in your view of what you're offering.

To give you an idea of the replacements I used see the following.
```
From,To
Comm(?![a-z]),Commercial
Phy(?![a-z]),Physical
Comp(?![a-z]),Competition
Conf(?![a-z]),Conference
Dup(?![a-z]),Duplicate
Db(?![a-z]),Database
Ply(?![a-z]),Player
Blst(?![a-z]),Blacklist
Param(?![a-z]),Parameter
Loc(?![a-z]),Location
Stat(?![a-z]),Statistic
List$,ListedPerson
No(?![a-z]),Number
Desc(?![a-z]),Description
NendName,NorthEndName
SendName,SouthEndName
```

**Comment by ErikEJ** [comment]
That looks great, maybe you could share your scripts here or in your own repo, and I could document in the wiki?

**Comment by hastarin** [comment]
To share it I'd have to choose another approach for the CSV since I used [a bit of code from Code Project ](https://www.codeproject.com/Articles/436406/Power-of-Dynamic-Reading-XML-and-CSV-files-made-ea) for the Linqpad query/program that I had handy from past experiments.

If you think it's of benefit I will see if I can make time this weekend to throw together a simple dotnet core console app that does the same thing just with CsvHelper.

**Comment by ErikEJ** [comment]
No rush - any contribution will be appreciated!

**Comment by ErikEJ** [comment]
Any update?

**Comment by ErikEJ** [comment]
Closing this for now, feel free to submit a PR when you are ready

**Comment by hastarin** [comment]
@ErikEJ Sorry have been flat out with work.

This is the closest I'll get to putting anything up any time soon.
https://gist.github.com/hastarin/7e61d262171a73ec95fe938abf729085
