### ISSUE TITLE
Workaround for Bug in Default Scaffolding

### ISSUE THREAD

**Issue by jwyza-pi** [ErikEJ/EFCorePowerTools#2518]
### Provide steps to reproduce a bug

The base EF Core reverse engineering has had a bug in it for quite a while here: https://github.com/dotnet/efcore/issues/11298.  Given that they haven't fixed it in 6 years, I don't have high hopes.  I know that this tool does some stuff to alter the behavior of the default scaffolding (though as I understand it, it's intentionally limited when it can be).

I am wondering with your new code added [here](https://github.com/ErikEJ/EFCorePowerTools/commit/85434013d180a7d088b8773f8a9635a8d4bdbdd3#diff-43b9a29a5871bc3a50fecfe3c50b7e9b109e71bc904826b88b6a92c60306e4ee) that it might be possible to prevent the bad behavior.

### Provide technical details

- EF Core Power Tools version: efcpt.8 8.1.343+2cccdc05b3276f3b391c95eecf53b1aae9844bd2

- Database engine: Azure SQL

- EF Core version in use: EF Core 8

- Is Handlebars templates used: no

- Is T4 templates used: yes (very minimal changes)

- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
Interesting. It is unclear whether altering the DatabaseModel is sufficient?

**Comment by jwyza-pi** [comment]
I guess I see a couple ways to go about it, at least within the scope of what we _can_ do in this tool:

Could either 

A: Alter the model to remove unique indexes from the model when they have a filter so that when the actual generation doesn't know about them and thus doesn't incorrectly determine the relationship is one-to-one and instead one-to-many.  This could be a global config or a per table config.
B: Similar to A, but add a config on a table that lets you just exclude indexes by name.  So instead of it being a generalized thing, if you know a specific scenario will trigger this, you can explicitly exclude that index from the model so that again, it doesn't determine it's one-to-one.  (similar to the `excludedColumns` property.)

I don't think we can or should try to fix the actual generator here, just what model it gets fed.

**Comment by ErikEJ** [comment]
I like the "excludedIndexes" option is quite compelling. 

Given that the original issue only has 4 upvotes, I assume it is quite limited how many get bitten by this.

**Comment by jwyza-pi** [comment]
Opened up a PR that handles this: https://github.com/ErikEJ/EFCorePowerTools/pull/2520

**Comment by ErikEJ** [comment]
@jwyza-pi Highly appreciated, will have a look this weekend
