### ISSUE TITLE
Add option to run PowerShell script after generation

### ISSUE THREAD

**Issue by Nuklon** [ErikEJ/EFCorePowerTools#2519]
I modify some bits of the generated code using PowerShell, I can run this manually afterwards, but it's prone to be forgotten, so if there was an option to run a PowerShell script that'd be nice (or just a command).

### Provide technical details

- EF Core Power Tools version: 2.6.482
- Visual Studio version: 17.11.4
- Database engine: SQL Server
- EF Core version in use: 9.0 RC1
- Is Handlebars templates used: no
- Is T4 templates used: no
- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
There already is: efpt.postrun.cmd

**Comment by Nuklon** [comment]
I didn't find that option, is it configurable per setting?

**Comment by ErikEJ** [comment]
@Nuklon did you read the wiki?

**Comment by Nuklon** [comment]
I didn't find it initially, but I found it now, thanks. Would it be possible to pass the currently run file as a parameter to the cmd file?

**Comment by ErikEJ** [comment]
@Nuklon Great! What could I do better to make it possible for you to discover it?

 No parameters are passed, why do you need it? If you have multiple efpt.config.json files, suggest you put them in individual folders.

**Comment by Nuklon** [comment]
I think a separate block with the command option would be helpful, I didn't expect it under `Saving options and running the second time`.
The parameter is useful so I can take an action based on the generated settings file. Putting them in individual folders is an OK workaround I guess.

**Comment by ErikEJ** [comment]
@Nuklon Thanks for the good suggestion! I have added a seperate section to the docs: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#post-processing

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
