### ISSUE TITLE
Uncheck "Include connection string in generated code"

### ISSUE THREAD

**Issue by marchica** [ErikEJ/EFCorePowerTools#252]
Is it possible to uncheck "Include connection string in generated code"? The checkbox is disabled and checked for me.

I am using your extension to update our DbContext and Models that were generated previously with your extension. (So awesome - thanks!) But it seems to have changed OnConfiguring to include the connection string (perhaps another dev changed it manually) and I'd like not to have to keep undoing that change upon regenerating the DbContext.

![image](https://user-images.githubusercontent.com/141490/63863146-bbc63400-c97b-11e9-9c5b-c8e173465da1.png)

### Further technical details
EF Core Power Tools version: 1.0

Database engine: SQL Server

Visual Studio version: Enterprise 2019 v16.2.3

**Comment by ErikEJ** [comment]
Manually modify the config.json file?

**Comment by ErikEJ** [comment]
Are you creating the code from a database project.

**Comment by ErikEJ** [comment]
Why do you need to overide OnConfiguring? Just use the constructor that takes Options.

>> Also, would it be possible to prettyprint/format efpt.config.json please?

Fixed in latest daily build, yes.

**Comment by ErikEJ** [comment]
Why do you want to throw here??
