### ISSUE TITLE
DBFirst Reverse: using Mysql as data source  causing ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by iccfish** [ErikEJ/EFCorePowerTools#2521]
- EF Core Power Tools version: 2.6.482
- Exact Visual Studio version: Visual Studio 2022 Preview (17.12.0 Preview 1.0)
- Database engine: MySQL
- EF Core version in use: EF Core 9 RC1
- Is Handlebars templates used: no
- Is T4 templates used: no
- Is a SQL Server .dacpac used: no

After choosing data source, then an exception dialog was shown.

```
---------------------------
Microsoft Visual Studio
---------------------------
EF Core Power Tools

Table list error: 

System.ArgumentOutOfRangeException: unsupported database type: Mysql (Parameter 'options')

   at IServiceCollection RevEng.Core.ServiceProviderBuilder.AddEfpt(IServiceCollection serviceCollection, ReverseEngineerCommandOptions options, List<string> errors, List<string> warnings, List<string> info) in D:/a/EFCorePowerTools/EFCorePowerTools/src/Core/RevEng.Core.60/ServiceProviderBuilder.cs:line 160

   at async Task<int> EfReveng.Program.Main(string[] args) in D:/a/EFCorePowerTools/EFCorePowerTools/src/Core/efreveng60/Program.cs:line 53

---------------------------
OK 
---------------------------
```

![image](https://github.com/user-attachments/assets/77e4975e-aafc-4797-a8b0-d634191c0168)

If change EF Core version to EF8, works well as excepted.

**Comment by ErikEJ** [comment]
@iccfish There is no MySQL provider for EF Core 9 yet, as the error message indicates. Use the EF Core 8 tooling for now (in reality no difference)

**Comment by iccfish** [comment]
> @iccfish There is no MySQL provider for EF Core 9 yet, as the error message indicates. Use the EF Core 8 tooling for now (in reality no difference)

I think the package `Pomelo.EntityFrameworkCore.MySql 9.0.0-9.0.0-preview.1` should support EF Core 9 cause it depends on package 'Microsoft.EntityFrameworkCore.Relational >= 9.0.0-preview.1.24081.2 && <= 9.0.0-preview.1.999999' 😄

**Comment by iccfish** [comment]
> @iccfish If you like my free tools, I would be very grateful for a rating/review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) and/or a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

Roger that. I would like to do that laterly, thanks for your awesome powerful tool 👍

**Comment by ErikEJ** [comment]
Cool,

**Comment by ErikEJ** [comment]
I will get that package added in the latest daily!

**Comment by ErikEJ** [comment]
@iccfish I cannot add it, as the latest daily uses 9.0 RC 1
