### ISSUE TITLE
is the usage of fmtonly for stored procedures result set detection new since last version(s)?

### ISSUE THREAD

**Issue by NormanGiHu** [ErikEJ/EFCorePowerTools#2523]
We have an old database for which we created models of its tables via ef core PT.

It worked always perfectly, but since last PT version(s) not anymore.
Now we use PT version 2.6.420

Instead of expected results sets PT is now generating only an int value as result on some tables.

![image](https://github.com/user-attachments/assets/097d8cd3-84be-4cef-b7a8-fc612c49aab4)
![image](https://github.com/user-attachments/assets/89f05379-b96d-4995-a74c-893e4bf850df)

I testet  a SP for one of this tables and FMTONLY  actually doesn't return a value. 
Which is very strange, because even with a simple statement in the SP, like that

```
ALTER PROCEDURE [dbo].[sp_test]
@pal int,
@pal_lfd_nr int = 1
AS
			SELECT nr, Rollennummer
		        FROM    Rollen
			WHERE (Palette = @pal) AND 
				(Palette_lfd_Nr = @pal_lfd_nr)
			ORDER BY	nr
```
FMTONLY fails.

So I created a new table with same properties as [Rollen] -Table, changed the table in the SP and then FMTONLY works.
So the old [Rollen] - Table is somehow "broken" for FMTONLY ?

Even putting the variables @pal and @pal_lfd_nr on the left side of the equal operator 
```
WHERE (@pal = Palette) AND 
	(@pal_lfd_nr = Palette_lfd_Nr)
```
is making FMTONLY working for the old [Rollen] again.

So FMTONLY has unexplainable behavior here.

One question now is:
is PT using fmtonly already for a long time and FMTONLY broke down recently for our tables
or
is PT using FMTONLY recently and our FMTONLY may already been broken for a long time for our tables

Visual Studio 2022 17.6.5
SQL Server 2022
EF Core 7
Handlebars templates: no
T4 templates used: no
SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
@NormanGiHu  Formatonly has been is use for a long time. Originally it was not used. 

But you can turn it on again, for everything or for individual stored procedures as described in the wiki: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#sql-server-stored-procedures

**Comment by NormanGiHu** [comment]
@ErikEJ so Formatonly is per default in use for RE? Right?
So why should i turn Formatonly on "again", when it already is?

Is I read the wiki 'UseLegacyResultSetDiscovery'  enforces the use of sp_describe_first_result_set instead of SET FMTONLY.

**Comment by ErikEJ** [comment]
Sorry  meant you can turn sp_describe on again, as you correctly read from the wiki

**Comment by NormanGiHu** [comment]
ok. 
But why you switched to FormatOnly, while it's deprecated for SQL Server?

**Comment by ErikEJ** [comment]
@NormanGiHu Because it works better for everyone in most cases

**Comment by NormanGiHu** [comment]
ok.
