### ISSUE TITLE
Is it possible to install the Power Tools/Pack vsix offline?

### ISSUE THREAD

**Issue by p0013638** [ErikEJ/EFCorePowerTools#2526]
im trying to install it on a station which has no internet connection and the installations process takes forever and in the end it fails.
duriing the installation it keeps showing the message of downloading stuff (which is impossible...but each component download takes several minutes and in the end the entire installation fails.

sorry but i can not attach the installation log.
but it has a lot of entries of skipping cache packages of all kinds, as well as lots of failures of downloading packages.

also, the ef power pack vsix is only about 10kb...so again, on an offline computer - is is possible to install it which will install the power tools vsix?

thanks.

**Comment by ErikEJ** [comment]
The Power Pack simply points to a collection of other extensions, you can go to each and download the .vsix file and install offline.

The extensions are listed in the file here: https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/PowerToolsExtensionPack/Extensions.vsext

**Comment by ErikEJ** [comment]
If you like my free tools, I would be very grateful for a rating/review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) and/or a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by p0013638** [comment]
Thank you dear for the quick response. 
so for the power pack, i guess you are right - i will try installing each internal package separately.
but my biggest problem right now is that i can not seems to be able to install the main POWER TOOLS extension
because when i run the vsix it tries to executes all sorts of downloads which can not be done. (i was hoping the vsix itself include everything that it needed for working with the cool extension...from what i have seen in the video and some of the tutorials...this is a very neat awesome tool which will probably makes a lot of thing much easier.

I will surely give the best rating/review for this tool after i finish "PLAYING" with it...and i'll ask my managers to consider contribute to your awesome project....hopefully they will agree to use it and donate to your your work.

thank you again.

**Comment by ErikEJ** [comment]
@p0013638 I am not sure I understand, maybe you have some pre-requisites missing in your VS install:

```xml
  <Installation>
        <InstallationTarget Id="Microsoft.VisualStudio.Community" Version="[17.0,18.0)">
            <ProductArchitecture>amd64</ProductArchitecture>
        </InstallationTarget>
        <InstallationTarget Id="Microsoft.VisualStudio.Community" Version="[17.0,18.0)">
            <ProductArchitecture>arm64</ProductArchitecture>
        </InstallationTarget>
    </Installation>
    <Dependencies>
        <Dependency Id="Microsoft.Framework.NDP" DisplayName="Microsoft .NET Framework" d:Source="Manual" Version="[4.8,)" />
    </Dependencies>
    <Prerequisites>
        <Prerequisite Id="Microsoft.VisualStudio.Component.CoreEditor" Version="[17.0,)" DisplayName="Visual Studio core editor" />
        <Prerequisite Id="Microsoft.VisualStudio.Component.SQL.DataSources" Version="[17.0,)" DisplayName="Data sources for SQL Server support" />
    </Prerequisites>

```

**Comment by p0013638** [comment]
hi again.
thank you for the support.
as you guessed it, you were right.
i was missing the 
<Prerequisite Id="Microsoft.VisualStudio.Component.SQL.DataSources" Version="[17.0,)" DisplayName="Data sources for SQL Server support" />
from my VS installation, and i guess this is what the vsix installation tried to download which failed (all the required components thats comes with it)
after i manually updated the VS installtion then the problem was fixed and the power tool vsix installation was successful.

today I hope to start trying this tool for a bit and im sure it will help a lot with our needs to use DB access in our new .net (core) projects.
i will sure give the best review/rating for this awesome tool.
Thanks again dear. :-)
