### ISSUE TITLE
efpt.renaming.json has no effect

### ISSUE THREAD

**Issue by escher4096** [ErikEJ/EFCorePowerTools#253]
I have added a efpt.renaming.json file to my project (it is right beside the efpt.config.json) and it does not seem to have any effect when I run the reverse engineer process.

The efpt.renaming.json file looks like:
```
[
  {
    "UseSchemaName": false,
    "SchemaName": "dbo",
    "Tables": [
      {
        "Name:": "PREFIX_Data",
        "Columns": [
          {
            "Name": "PREFIX_DataId",
            "NewName": "DataId"
          }
        ]
      }
    ]
  }
]
```

The column is always generated as PREFIX_DataId instead of DataId

EF Core Power Tools version: 2.2.63.0
Database engine: SQL Server
Visual Studio version: 2019 Professional

I am sure I am just doing something wrong. I have tried various combinations of of the check boxes in the UI. Is there something I need to do to enable this feature? Is there a combination of checkboxes that are incompatible with the renaming option. I have tried with with and without the 'use table and column names directly from database' and it doesn't cause the renaming to occur. 

I had started off with the file having:

"UseSchemaName": true

And it renamed the navigation properties to include 'dbo' which makes me think it is loading the file.

Does the extension log debugging messages anywhere so that I could check for warnings or anything like that?

**Comment by ErikEJ** [comment]
Any news or still an issue?

**Comment by escher4096** [comment]
I gave up attempting to get it to work and ended up injecting a custom CandidateNamingService instead.

**Comment by HolisticDeveloper** [comment]
Some other devs on my team were reporting the symptom that the renaming was not working. It seemed there was some problem if the entity code files were open in VS... After closing them they were able to see the renaming changes.

Also, I noticed that the code swallows any exceptions that occur when trying to read the `tftp.renaming.json` file:
https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/EFCorePowerTools/Extensions/CustomNameOptionsExtensions.cs#L28

Maybe it would be better to log these to the output window?
