### ISSUE TITLE
Multiple DbContexts in the same project

### ISSUE THREAD

**Issue by pwolfson** [ErikEJ/EFCorePowerTools#2534]
Hello,

Does EF Core Power Tools support multiple DbContext.t4 and EntityType.t4 templates as well as multiple eft.config.json files for multiple DbContexts (each serving a different SQL Server Database)?

For purposes of Reverse Engineering, I would like to be able to reverse engineer multiple databases into the same "Persistence" project, but it seems that there would be a conflict as EF Core Power Tools generates "settings files" based on the the configurations selected in Power Tools, which is always names a constant anemia -- "efpt.config.json".

Some details of how we use the tool.
We use the tool to rename certain table columns. We use the efpt.config.json file to specify ExcludedColumns from various Tables. We specify specific context name, namespaces, output folders, pluralize vs singularize settings, and "Customize code using templates - T4".

### Provide technical details

- EF Core Power Tools version: 2.5.1595

- Exact Visual Studio version: Visual Studio 2022 17.8.6

- Database engine: SQL Server

- EF Core version in use: EF Core 8

- Is Handlebars templates used: no

- Is T4 templates used: yes

- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
Yes and yes. It is described in detail in the wiki.

**Comment by pwolfson** [comment]
I found it, thank you so much Erik.

[Using ultiple DbContexts in the same project](https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#using-multiple-dbcontexts-in-the-same-project)
