### ISSUE TITLE
Enhance Dataverse reverse engineering

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#2535]
improve Dataverse schema discovery by using the Dataverse client

I have tried to add 

`<PackageReference Include="Microsoft.PowerPlatform.Dataverse.Client" Version="1.1.32" />`

 to the EF Core 8 main library, only adds 2 MB of extra payload, not an issue.

@MarkMpn FYI!

**Comment by MarkMpn** [comment]
Thanks, hoping to have a look this week.

**Comment by ErikEJ** [comment]
@MarkMpn Still planning to do this in the future?

**Comment by MarkMpn** [comment]
Definitely, other priorities came up but still meaning to get back to it
