### ISSUE TITLE
Bug: Different db schema behavior between 2 users in CLI

### ISSUE THREAD

**Issue by jwyza-pi** [ErikEJ/EFCorePowerTools#2536]
### Provide steps to reproduce a bug

I don't know how to necessarily reproduce it.  Basically I have a project that has the efcpt-config.json file checked in.  If I run the `efcpt` command, it will go generate all the configurations with the ToTable line looking like `entity.ToTable("AnonymizationStatus");`, however if another engineer uses the same command in the same repository, their ToTable looks like `entity.ToTable("AnonymizationStatus", "dbo");`.  "dbo" is the correct schema, but I don't understand why when he runs it, it specifies it, but when I run it, it doesn't.

The EF Core Power Tools Versions are identical, The efcpt command is identical (because it's wrapped in a powershell script).  The only difference I can see is different DB users (since we use Managed Identities).  In this example, I'm a server admin, but he's a dbowner.

### Provide technical details

- EF Core Power Tools version: 8.1.391 (though the previous version behaved this way too, so it's not new)

- Exact Visual Studio version: N/A

- Database engine: Azure SQL

- EF Core version in use: EF Core 8

- Is Handlebars templates used: no

- Is T4 templates used: yes

- Is a SQL Server .dacpac used: no

truncated version of efcpt-config.json

```json
{
  "$schema": "https://raw.githubusercontent.com/ErikEJ/EFCorePowerTools/master/samples/efcpt-schema.json",
  "code-generation": {
    "enable-on-configuring": false,
    "generate-mermaid-diagram": false,
    "merge-dacpacs": false,
    "refresh-object-lists": false,
    "remove-defaultsql-from-bool-properties": true,
    "soft-delete-obsolete-files": false,
    "t4-template-path": null,
    "type": "all",
    "use-alternate-stored-procedure-resultset-discovery": false,
    "use-data-annotations": false,
    "use-database-names": true,
    "use-decimal-data-annotation-for-sproc-results": true,
    "use-inflector": true,
    "use-legacy-inflector": false,
    "use-many-to-many-entity": false,
    "use-nullable-reference-types": true,
    "use-prefix-navigation-naming": false,
    "use-t4": true
  },
  "file-layout": {
    "output-dbcontext-path": "Database",
    "output-path": "Models",
    "split-dbcontext-preview": true
  },
  "names": {
    "dbcontext-name": "EFDBContext",
    "dbcontext-namespace": null,
    "model-namespace": null,
    "root-namespace": "EF.SQL"
  },
  "tables": [
    {
      "exclusionWildcard": "*"
    },
    {
      "name": "[dbo].[AnonymizationStatus]",
      "exclude": false
    }
],
  "views": [
    {
      "exclusionWildcard": "*"
    }
  ],
  "functions": [
    {
      "exclusionWildcard": "*"
    }
  ],
  "stored-procedures": [
    {
      "exclusionWildcard": "*"
    }
  ]
```

**Comment by ErikEJ** [comment]
I think it depends on the users default schema - based on this query:   https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/Core/RevEng.Core.80/PatchedSqlServerDatabaseModelFactory.cs#L252

**Comment by jwyza-pi** [comment]
Awesome, I can take that and run then.  Thanks :)
