### ISSUE TITLE
Add missing EF Core 9 dependencies

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#2538]
- [x] Firebird provider @cincuranet 
- [x] Oracle provider @alexkeh 
- [x] MySql Pomelo provider @lauxjpn
- [x] Handlebars @tonysneed 
- [x] EFCore.SchemaCompare @JonPSmith  
- [x] NodaTime for SQL Server @stevenrasmussen
- [x] NodaTime for SQLite @khellang

**Comment by khellang** [comment]
I will probably hold off until RTM as I have very limited time these days 😅

**Comment by alexkeh** [comment]
Our planned release will be not too long after EF Core 9 RTM.

**Comment by StevenRasmussen** [comment]
I'll see about knocking this out in the next week or so.

**Comment by StevenRasmussen** [comment]
I just released an RC1 candidate for SQL Server NodaTime: [https://www.nuget.org/packages/SimplerSoftware.EntityFrameworkCore.SqlServer.NodaTime/9.0.0-rc.1.24451.1](https://www.nuget.org/packages/SimplerSoftware.EntityFrameworkCore.SqlServer.NodaTime/9.0.0-rc.1.24451.1)

**Comment by khellang** [comment]
SQLite support [has been shipped](https://www.nuget.org/packages/EntityFrameworkCore.Sqlite.NodaTime/9.0.0)

**Comment by ErikEJ** [comment]
See https://github.com/JonPSmith/EfCore.SchemaCompare/issues/40

**Comment by ErikEJ** [comment]
https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars/pull/247

**Comment by alexkeh** [comment]
@ErikEJ Oracle EF Core 9 provider has shipped on [NuGet Gallery](https://www.nuget.org/packages/Oracle.EntityFrameworkCore/9.23.60).
