### ISSUE TITLE
When i go to reverse engineer, i select the server and choose the tables i want to manage, after that visual studio is restarted. 

### ISSUE THREAD

**Issue by jorgearana** [ErikEJ/EFCorePowerTools#254]
Describe what is not working as expected.

### Steps to reproduce
Include a complete description that I can redo to reproduce the issue.

### Further technical details
EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)

Database engine: (SQlite, SQL Compact, SQL Server, Postgres)

Visual Studio version: (e.g. Visual Studio 2017 15.7)

**Comment by ErikEJ** [comment]
Please provide the requested details asked for

**Comment by jorgearana** [comment]
Hi, i am trying to learn Blazor, and i want to add EF Core Power Tools, I am going to send you the image of the steps i  do.


I create a new project, Blazor App, and only want to add EF Core Power Tools, add the server, the connection is ok and select the tables, when i pressed the button Visual Studio not respond and finally visual studio restart.



Ing. Jorge A. Arana Neyra
980 599 023
www.jorgearananeyra.com<http://www.jorgearananeyra.com>
"Bienvenido a la nube, programas y datos que pueden ser vistos por todos sin gastar en servidores "
________________________________
De: Erik Ejlskov Jensen <notifications@github.com>
Enviado: jueves, 5 de setiembre de 2019 15:05
Para: ErikEJ/EFCorePowerTools <EFCorePowerTools@noreply.github.com>
Cc: jorgearana <jorgearananeyra@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [ErikEJ/EFCorePowerTools] When i go to reverse engineer, i select the server and choose the tables i want to manage, after that visual studio is restarted. (#254)


Please provide the requested details asked for

**Comment by ErikEJ** [comment]
Which VS version?

**Comment by jorgearana** [comment]
Visual Studio 2019 version 16.3 Preview 2

Saludos

Ing. Jorge A. Arana Neyra
980 599 023
www.jorgearananeyra.com<http://www.jorgearananeyra.com>
"Bienvenido a la nube, programas y datos que pueden ser vistos por todos sin gastar en servidores "
________________________________
De: Erik Ejlskov Jensen <notifications@github.com>
Enviado: miércoles, 18 de setiembre de 2019 11:07
Para: ErikEJ/EFCorePowerTools <EFCorePowerTools@noreply.github.com>
Cc: jorgearana <jorgearananeyra@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [ErikEJ/EFCorePowerTools] When i go to reverse engineer, i select the server and choose the tables i want to manage, after that visual studio is restarted. (#254)


Which VS version?

**Comment by ErikEJ** [comment]
Please share a project that reproduces this issue.

**Comment by jorgearana** [comment]
Hi. i solved it deleting the diagram in Sql Server.

I don't understand what happened but in the end it was resolved.

Thanks
________________________________
