### ISSUE TITLE
MySQL bit(1) type column is mapped to ulong instead of bool

### ISSUE THREAD

**Issue by sufyannisar** [ErikEJ/EFCorePowerTools#2540]
### Steps to reproduce

Create a table in mysql that has a `bit(1)` type column. 
Reverse engineer to generate classes.
Generated field for `bit(1)` type column is `ulong` instead of `bool`.

### Technical details

- EF Core Power Tools version: `2.6.437`
- Exact Visual Studio version: `Visual Studio 2022 17.11.4`
- Database engine: `MySQL`
- EF Core version in use: `EF Core 8`
- Is Handlebars templates used: `no`
- Is T4 templates used: `no`
- Is a SQL Server .dacpac used: `no`

**Comment by ErikEJ** [comment]
@sufyannisar I think you ask in the MySql provider repository (Pomelo provider)
