### ISSUE TITLE
Table Builder does not contain definition HasTrigger 

### ISSUE THREAD

**Issue by Coder-IsiahJones** [ErikEJ/EFCorePowerTools#2541]
Question:

Our current project is running .Net 6 with all the versions installed on 6.0.3. The approach is using reverse engineering to scaffold the database. When doing so it's pulling the triggers created on the table but the version of ef core does not support HasTrigger. Is there a setting inside the efpt.config where you can tell it to not add the trigger to the context?

`
entity.ToTable(tb => tb.HasTrigger("trg_UpdateDate"));
`

Any information would be very helpful.

- EF Core Power Tools version: 2.6.437

- Exact Visual Studio version: Visual Studio 2022 Preview

- Database engine: SQL Server, Azure SQL

- EF Core version in use: EF Core 6

- Is Handlebars templates used: NO

- Is T4 templates used: YES

- Is a SQL Server .dacpac used: NO

**Comment by Coder-IsiahJones** [comment]
Using EF Core Power Toys to target version 7.

**Comment by ErikEJ** [comment]
You must target the EF Core version you use at runtime! And EF Core 7 is out of support.
