### ISSUE TITLE
Unable to get result set shape for procedure. Invalid object name

### ISSUE THREAD

**Issue by subchannel13** [ErikEJ/EFCorePowerTools#2542]
### Provide steps to reproduce a bug

I've run `efcpt "<connection string>"` and got a few warnings in style of `warning: Unable to get result set shape for procedure 'dbo.sp_Rec_GetXyzInPeriod'. Invalid object name '#period'..`. For stored procedures with such warning no useful models were created. The result was an empty partial class. I suspect that this is the same issues as in https://github.com/ErikEJ/EFCorePowerTools/issues/1381#issuecomment-1176649789 where a stored procedure creates a temporary table. Unfortunately I can't do the suggested measure of editing the stored procedures. I'd don't own the DB, I don't have necessary permissions for editing, and there is no budget for validating those edits.

### Provide technical details

- EF Core Power Tools version: 8.1.391

- Exact Visual Studio version: used CLI, not VS extension

- Database engine: MS SQL Server

- EF Core version in use: EF Core 8.0.8

- Is Handlebars templates used: no

- Is T4 templates used: no

- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
What is your question? And did you read the wiki?

**Comment by ErikEJ** [comment]
@subchannel13 Ping?

**Comment by subchannel13** [comment]
No question, issue report, I got no reverse engineering result for stored procedures that generated warning.

I did check the wiki, and I've tried using "UseLegacyResultSetDiscovery" in efpt.config.json for those SPs, as described here: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#sql-server-stored-procedures. But there was no improvement.

**Comment by ErikEJ** [comment]
@subchannel13 in that case you can manually add the properties in a partial result set class, assuming you know the shape of the result set.

**Comment by subchannel13** [comment]
Yeah, going manual seems to be the only option left. I don't know the shape of result set but I can infer it by observing output. Column names are easy but types require some trickery. I do have a watch expression for extracting them from internal data reader when exception occurs. But man, of only there was a tool to automate such reverse engineering.

**Comment by ErikEJ** [comment]
There IS tooling, and it does not always work with quirky, dynamic stored procedures.  And executing the sp to get a datareader back in a tool seems dangerous to me. Also, it will be complex to inform the tool of parameters and their values. 

But maybe tool with a query dialog allowing you to run the stored procedure and then generating the result C# class could be an option?

**Comment by ErikEJ** [comment]
@subchannel13 If you share a runnable sample of a stored procedure  I can try to create a tool to generate the result class.

**Comment by subchannel13** [comment]
Unfortunately I don't know how to get the source code of those stored procedures and it's quite possible I don't have permission to do so.

> But maybe tool with a query dialog allowing you to run the stored procedure and then generating the result C# class could be an option?

This would be handy. Would that work from CLI (say, by supplying such query in confing.json)?

As far as I'm concerned my needs are served. Your tool has helped me with about half of SPs and by now I've hand crafted tools for reverse engineering the other half (mostly as a side effect of having to support SPs with multiple result sets).

**Comment by ErikEJ** [comment]
My tool supports multiple result sets as well. I will not do anything further unless you can provide a sample stored procedure. Actually executing the stored procedure and the parameters to do so would be in a config file  yes, if I decide to go further
