### ISSUE TITLE
When name of the database project is the same with the table name

### ISSUE THREAD

**Issue by maxisam** [ErikEJ/EFCorePowerTools#2543]
### Provide steps to reproduce a bug

my project name is like

`DataAccess.Product`

but there is a table name like

`Product` (mine is actually `Products` here)

So when generate through CLI, it causes an issues like `'Product' is a namespace but is used like a type`

However this is being handled in UI.

in UI, it creates

```
using Schema = DataAccess.Product.Models.dboSchema;
```

and access it like `Schema.Product`

### Provide technical details

- EF Core Power Tools CLI version: 8.1.391

- Database engine: (SQL Server)

- EF Core version in use: (e.g. EF Core 8)

- Is Handlebars templates used: no

- Is T4 templates used: no

- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
Please provide a full repo - table CREATE statement and you config file.

Ask you were asked to when you created this issue!

**Comment by maxisam** [comment]
Sorry, I just throw it out quickly, in case this is a known issue and you can answer it right away. I am still checking the repo and see if there is a settings for this in the CLI, since I think the underlying engine is the same for both. I will reopen it when I add more information
