### ISSUE TITLE
Renaming doesn't work if UseDatabaseNames is set to true, add warning if you try to use both

### ISSUE THREAD

**Issue by jwyza-pi** [ErikEJ/EFCorePowerTools#2545]
So it turns out that if you have `use-database-names` set to true, having a efpt.renaming.json file won't do you any good.  Since I had EFCPT building locally already, I wanted to figure out why.  

It successfully gets into https://github.com/ErikEJ/EFCorePowerTools/blob/2793e2ae457f8d765176479a51d1dcd6deccb468/src/Core/RevEng.Core.60/ServiceProviderBuilder.cs#L73 with the `options.CustomReplacers` passed in as expected.  But it would never hit breakpoints in  https://github.com/ErikEJ/EFCorePowerTools/blob/2793e2ae457f8d765176479a51d1dcd6deccb468/src/Core/RevEng.Core.60/ReplacingCandidateNamingService.cs#L37

and 
https://github.com/ErikEJ/EFCorePowerTools/blob/2793e2ae457f8d765176479a51d1dcd6deccb468/src/Core/RevEng.Core.60/ReplacingCandidateNamingService.cs#L92

It will hit for 

https://github.com/ErikEJ/EFCorePowerTools/blob/2793e2ae457f8d765176479a51d1dcd6deccb468/src/Core/RevEng.Core.60/ReplacingCandidateNamingService.cs#L147

so I know the service gets hit.  What it turns out is that if you have usedatabasenames set to true, EF itself skips using the ICandidateNamingService

https://github.com/dotnet/efcore/blob/bb583a91d7269510ecb09a4466fee61bc62280d1/src/EFCore.Design/Scaffolding/Internal/RelationalScaffoldingModelFactory.cs#L69-L77

```csharp
        _tableNamer = new CSharpUniqueNamer<DatabaseTable>(
            options.UseDatabaseNames
                ? (t => t.Name)
                : t => _candidateNamingService.GenerateCandidateIdentifier(t),
            _cSharpUtilities,
            options.NoPluralize
                ? null
                : _pluralizer.Singularize,
            caseSensitive: false);
```

So my thought would be to add something to the startup that will print a warning if you try to use both the renaming file and 
`use-database-names` at the same time since they are incompatible with eachother.

### Provide technical details

- EF Core Power Tools version: 8.1.391

- Exact Visual Studio version: N/A

- Database engine: Azure SQL

- EF Core version in use: EF Core 8

- Is Handlebars templates used: no

- Is T4 templates used: yes

- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
Adding a warning to the ReverseEnginerResult would be helpful here, yes. And maybe also mention in the docs.

**Comment by jwyza-pi** [comment]
PR to add the warning.  Didn't see any tests that needed to be updated around the service. https://github.com/ErikEJ/EFCorePowerTools/pull/2546
