### ISSUE TITLE
Exclude Schema level objects or set of tables

### ISSUE THREAD

**Issue by vansree** [ErikEJ/EFCorePowerTools#2547]
Hi,
I could not find the details and am seeking information to see if this has already been addressed.

I am using SQL Server as the backend, and all objects have their own schema, such as Code, Foundation, and more.

Is there a way to completely exclude the schema of tables or a set of objects from being included? For example, I have dbo.DDL_Schema_EventAuditLog and dbo.BuildVersionDetails to track schema changes and build version details.

I would like to either exclude all tables in a particular schema or exclude a specific list of tables.

Please advise. 

Thanks

I can write like this. But want to check if there is setting or some kind of easy way:

`
public class MyDbContext : DbContext
{
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        // Exclude specific tables
        modelBuilder.Ignore<DDL_Schema_EventAuditLog>();
        modelBuilder.Ignore<BuildVersionDetails>();

        // Exclude all tables in a specific schema
        foreach (var entityType in modelBuilder.Model.GetEntityTypes())
        {
            if (entityType.GetSchema() == "SchemaToExclude")
            {
                modelBuilder.Ignore(entityType.ClrType);
            }
        }

        base.OnModelCreating(modelBuilder);
    }
}

`

**Comment by ErikEJ** [comment]
Are you referring to the VS Tool  - then it is very easy to pick the tables you want to include.

There is also filtering I'm the CLI tool

**Comment by ErikEJ** [comment]
You can also define which schemas to include: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#choose-data-source

**Comment by vansree** [comment]
Thanks for the reply.

I read the link before posting the issue. I was thinking a way to exclude.

My use case is that we have tables for dml log tables, like AWBuildVersion table in adventure works. These tables are not needed for app or other data exchange purposes. So, pls. could you consider as UI improvement .. .some what like as below

https://oracle-base.com/articles/misc/images/sqldev31-dp/06-exp-schema.jpg
https://oracle-base.com/articles/misc/sql-developer-31-data-pump-wizards

You dont have to do the same. Just giving an example.

Thanks

**Comment by ErikEJ** [comment]
Is that not what the schema filters are there for? 

Also, you never mentioned Oracle in your initial post  even if I requested you to provide that information
