### ISSUE TITLE
Configurations without DbContext

### ISSUE THREAD

**Issue by MatteoZampariniDev** [ErikEJ/EFCorePowerTools#2555]
Hi, when using the reverse engineering tool is it possible to generate IEntityTypeConfigurations and the DbContext in a separated project? Also, is it possible to generate IEntityTypeConfigurations when "What to generate" is set to "EntityTypes only"?

When generating the DbContext class is it possible to set a custom base class? I have a project that needs to inherit from IdentityDbContext and I have to fix it after each reverse engineering.

Thank you

**Comment by ErikEJ** [comment]
> is it possible to generate IEntityTypeConfigurations and the DbContext in a separated project? 

Yes - did you read the wiki?

>  is it possible to generate IEntityTypeConfigurations when "What to generate" is set to "EntityTypes only"

No, IEntityTypeConfigurations are part of the DbContext

>  is it possible to set a custom base class

Yes, you can use T4 templates of run efpt.postrun.cmd and do some file manipulation after eacg reverse engineering

**Comment by ErikEJ** [comment]
If you like my free tools, I would be very grateful for a rating/review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) and/or a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by MatteoZampariniDev** [comment]
I must have missed it, sorry 

Mmh ok I think I'll exclude that DbContext from the solution then.

Thank you
