### ISSUE TITLE
Migration Tool doesn't support EF Core 2.2.6

### ISSUE THREAD

**Issue by Janek91** [ErikEJ/EFCorePowerTools#256]
Migration Tool window crashes complaining about unsupported Microsoft.EntityFrameworkCore.dll version when target project has higher than 2.2.4 EF Core package version installed. 

### Steps to reproduce
- install Microsoft.EntityFrameworkCore package in 2.2.6 version
- click Migration Tool option in EF Core Power Tools context menu

### Further technical details
EF Core Power Tools version: 2.3.25.0

Database engine: SQL Server

Visual Studio version: Visual Studio 2019 16.2.5

**Comment by ErikEJ** [comment]
Pls share your csproj file.

Pls share the full error message.

**Comment by Janek91** [comment]
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="2.2.4" />
  </ItemGroup>

</Project>
```

**Comment by ErikEJ** [comment]
Support for .NET Framework and 2.2.6 has not been implemented yet
