### ISSUE TITLE
Multiple Database handling

### ISSUE THREAD

**Issue by sholma** [ErikEJ/EFCorePowerTools#2565]
Create a bug report, feature proposal, or ask a question.

NOTICE: A bug report without sufficient technical and repro details and version information WILL BE CLOSED WITHOUT ANY FURTHER ACTION.

### Provide steps to reproduce a bug

Please include a **complete** description of the issue or link to a project that I can run to reproduce the issue.

### Provide technical details

- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)

- Exact Visual Studio version: (e.g. Visual Studio 2022 17.6.5)

- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)

- EF Core version in use: (e.g. EF Core 7)

- Is Handlebars templates used: no/yes

- Is T4 templates used: no/yes

- Is a SQL Server .dacpac used: no/yes

**Comment by sholma** [comment]
Is there a way to handle multiple databases in the same class library?

**Comment by ErikEJ** [comment]
Yes, did you read the wiki??

**Comment by ErikEJ** [comment]
@sholma Ping?

**Comment by sholma** [comment]
I wish I had that kind of time.  Do you have a specific link or what to look for in there?

**Comment by ErikEJ** [comment]
> I wish I had that kind of time.

No problem, I will help you for free with using my free software 😜 

https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#using-multiple-dbcontexts-in-the-same-project

If you like my free tools, I would be very grateful for a rating/review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) and/or a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
