### ISSUE TITLE
Visual Studio fails during launch to a solution when that solution was previously closed while viewing a dgml diagram

### ISSUE THREAD

**Issue by tom-puckett** [ErikEJ/EFCorePowerTools#2566]
Create a bug report, feature proposal, or ask a question.

NOTICE: A bug report without sufficient technical and repro details and version information WILL BE CLOSED WITHOUT ANY FURTHER ACTION.

### Provide steps to reproduce a bug

Initial state is working on a solution containing an EF Core context for a PostgreSQL database. The DGML Editor is installed to Visual Studio. 

- Create a dgml diagram file from the context class using EF Power Tools. 
- Display the dgml diagram in the active tab in Visual Studio
- Close Visual Studio
- Launch Visual Studio directly to the same solution.
- A modal error dialog is displayed (screen shot attached)
- After dismissing the modal dialog, the tab contains exception details (screen shot attached)

Please include a **complete** description of the issue or link to a project that I can run to reproduce the issue.

- A zip file with a sample solution is attached to this issue. 
- No problem occurs if the loaded solution did not have a dgml file displayed when the solution was previously closed.
- If I open VS with a solution that did not have a dgml file open previously, I can then open a dgml file and view the diagram with no problem.
- If I open VS with a solution that did have a dgml file open previously, then encounter and dismiss the described error, I cannot subsequently open a dgml file (nothing happens / fails silently).
- Regarding my VS configuration, I added the following 2 items to create and manage dgml diagrams:
   - “DGML Editor” as an individual component in Visual Studio Installer. The “Data Storage and Processing” workload is not otherwise installed.
   - “EF Core Power Tools” extension

### Provide technical details

I initially submitted [this feedback](https://developercommunity.visualstudio.com/t/VS-17111-fail-to-launch-when-a-solutio/10733716) to the Microsoft Developer Community. The latest response there was to submit an issue here.  

- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
   - Not sure of the version when the original issue was written but currently I have v2.6.497

- Exact Visual Studio version: (e.g. Visual Studio 2022 17.6.5)
   The issue was discovered in v17.11.1 and reproduced with 17.11.2

- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)
   PostgreSQL 11

- EF Core version in use: (e.g. EF Core 7)
   8 (included as a dependency of Npgsql.EntityFrameworkCore.PostgreSQL 8.0.4)

- Is Handlebars templates used: no/yes
   No

- Is T4 templates used: no/yes
   No

- Is a SQL Server .dacpac used: no/yes
   No

[BlazorApp2.zip](https://github.com/user-attachments/files/17298265/BlazorApp2.zip)

![VS dgml Error](https://github.com/user-attachments/assets/f97a40d8-3f0c-46c1-9cb8-c33525a60ef5)

![Second VS dgml error](https://github.com/user-attachments/assets/58ec4d94-7abb-44c4-ac9b-39889523e2dc)

**Comment by ErikEJ** [comment]
I do not see a lot of thing indicating that this is related to EF Core Power Tools. make sure to update your VS install to the latest.

**Comment by ErikEJ** [comment]
What happens if you remove Power Tools?

**Comment by ErikEJ** [comment]
Please share the ActivityLog.xml file
