### ISSUE TITLE
VS Extension DB Improvement Suggestions 

### ISSUE THREAD

**Issue by barnuri** [ErikEJ/EFCorePowerTools#2568]
give the ability to add connection by connectionString

give the ability to duplicate connection

**Comment by ErikEJ** [comment]
Could you be more specific or maybe share a screenshot?

**Comment by barnuri** [comment]
when you use reverse engineer you need to select db connection
is the fifth step I want to be able to add connections via connections string and not fill the form

**Comment by ErikEJ** [comment]
That would be a step back, and something I deliberately try to avoid.

**Comment by barnuri** [comment]
both things i suggested ? 
and why ?

**Comment by ErikEJ** [comment]
> both things i suggested ?

Not sure what you mean by that?

why: I do not want to support that feature which seems not needed and also not spend time providing support when users are not able to create a proper connection string
