### ISSUE TITLE
VS Extension Config File & CLI Config File Not The Same

### ISSUE THREAD

**Issue by barnuri** [ErikEJ/EFCorePowerTools#2569]
I want to be able to use the same config from CLI tool and from visual studio extension 

justifications:
when I want to select which resources to scaffold I will use the vs extension and when I need to just sync (I have multiple scaffolding) I will use a script that did it via CLI

**Comment by ErikEJ** [comment]
The VS extension can read the CLI config. I have no plans to take that any further

**Comment by barnuri** [comment]
but the format is not the same it's different schemas 
saw that I can't use the same config for both features

**Comment by ErikEJ** [comment]
> but the format is not the same it's different schemas

Yes, I made an effort to make the CLI schema more human readable, and have intellisese in VS Code.

As I said, is a CLI config exists in your project, the VS extension can read it

**Comment by barnuri** [comment]
ok thanks i will try
