### ISSUE TITLE
EPFT installation directory is missing EF Core 2.2.4 DLL

### ISSUE THREAD

**Issue by Janek91** [ErikEJ/EFCorePowerTools#257]
When project is targeting 2.2.4 EF Core package version, any EF Core Power Tools action complains about missing 2.2.4 Microsoft.EntityFrameworkCore.Design.dll file in extension installation directory.

### Steps to reproduce
- install EF Core package in 2.2.4 version
- try to open i.e. Migration Tool

### Further technical details
EF Core Power Tools version: 2.3.25.0

Database engine: SQL Server

Visual Studio version: Visual Studio 2019 16.2.5

**Comment by ErikEJ** [comment]
Any action? Also reverse engineering??

**Comment by Janek91** [comment]
Sorry, I've checked again. It was only Migration Tool.

**Comment by Janek91** [comment]
The problem is that there is missing:
```
<IncludeInVSIX>true</IncludeInVSIX>
```
line for
```
<Content Include="efpt\2.2.4\Microsoft.EntityFrameworkCore.Design.dll" />
```
entry in EFCorePowerTools.csproj file at line 186

**Comment by ErikEJ** [comment]
Fixed in latest daily build
