### ISSUE TITLE
Reverse engineering a SQLite database with spatialite tables fails

### ISSUE THREAD

**Issue by andrerav** [ErikEJ/EFCorePowerTools#2571]
### Provide steps to reproduce a bug

1. Create an empty sqlite database
2. Load the mod_spatialite extension: `SELECT load_extension('mod_spatialite');`
3. Initialize the spatial database: `SELECT InitSpatialMetaData();`
4. Reverse engineer using SQLite driver:

![image](https://github.com/user-attachments/assets/d9190458-f470-4220-85d3-8dadbe44402d)

5: Observe error message:

![image](https://github.com/user-attachments/assets/55b92dee-9b77-48a2-90b9-a8d1a31d4f86)

### Provide technical details

- EF Core Power Tools version: 2.6.497

- Exact Visual Studio version: Version 17.12.0 Preview 2.0

- Database engine: SQLite with Spatialite extension

- EF Core version in use: EF Core 8

- Is Handlebars templates used: no

- Is T4 templates used: no

- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
@andrerav First, EF Core Power Tools does not look at the code in your project. 

Currently I have not enabled support for spatial with Sqlite, but I can investigate the possibility of doing this.

https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#mapping

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

**Comment by ErikEJ** [comment]
@andrerav The dailiy build is taking longer than expected, I will keep you posted

**Comment by ErikEJ** [comment]
I was not able to do this, as the payload of my extension became unmanageable. I will revisit for EF Core 9, looks like the payload was smaller with that.

**Comment by andrerav** [comment]
Hi @ErikEJ,

I was unable to get around this using EF Power Tools, so I went back to dotnet ef dbcontext scaffold and manually specified the tables I wanted to scaffold (using multiple `-t` arguments) to circumvent the problem and only scaffold my own tables (and not any of the spatialite meta tables). 

Geometry columns are correctly generated as well provided that the `Microsoft.EntityFrameworkCore.Sqlite.NetTopologySuite` package is installed in the EF project. 

If I don't specify the tables manually I get the same error message using `dotnet ef` as with EF Power Tools. 

I think that being able to simply filter/specify the tables I want to scaffold could go a long way as a workaround for this issue.

**Comment by ErikEJ** [comment]
@andrerav The GUI is there to show all tables, perhaps the CLI will work better for you, though you might have to create the initial config file using a non spatial scracth database file.

**Comment by ErikEJ** [comment]
@andrerav  hang on, are you saying that the tool should avoid discovering the spatial system files as well (and then also support the spatial EF Core plugin) for this to work?

Can you tell me what the names of these table are?

**Comment by andrerav** [comment]
@ErikEJ If I create a new, empty Sqlite database, load the spatialite extension, and execute `select InitSpatialMetadata();`, I am left with these tables, indices and views:

![image](https://github.com/user-attachments/assets/fe69bb81-51d3-4305-82f6-37b51adffcd9)

A rather long list of triggers are created as well when initializing the spatial metadata.

**Comment by ErikEJ** [comment]
@andrerav Ping ^^

**Comment by andrerav** [comment]
Oops, apologies @ErikEJ! Yes, I can confirm that dropping the KNN2 table works. If other users come across this and consider dropping the KNN2 table as a non-option then manually specifying the tables to scaffold also works. I still think it would be nice if there was an option in `dotnet ef` to _omit_ tables when scaffolding, though :)
