### ISSUE TITLE
Error getting table-valued functions from dacpac

### ISSUE THREAD

**Issue by Califorro** [ErikEJ/EFCorePowerTools#2573]
Hi @ErikEJ

I tested the feature to get functions from dacpac ([#2477](https://github.com/ErikEJ/EFCorePowerTools/issues/2477)), and it worked perfectly, but with table-valued functions, I encountered this error:

> error: System.InvalidOperationException: Sequence contains no elements
>    at System.Linq.ThrowHelper.ThrowNoElementsException()
>    at System.Linq.Enumerable.First[TSource](IEnumerable1 source)
>    at 
> ErikEJ.EntityFrameworkCore.SqlServer.Scaffolding.SqlServerDacpacFunctionModelFac
> tory.GetTableValuedFunctions(String dacpacPath, ModuleModelFactoryOptions 
> options, Boolean mergeDacpacs) in 
> /_/src/Nupkg/ErikEJ.EntityFrameworkCore.SqlServer.Dacpac/Scaffolding/SqlServerDa
> cpacFunctionModelFactory.cs:line 136
>    at 
> ErikEJ.EntityFrameworkCore.SqlServer.Scaffolding.SqlServerDacpacFunctionModelFac
> tory.Create(String connectionString, ModuleModelFactoryOptions options) in 
> /_/src/Nupkg/ErikEJ.EntityFrameworkCore.SqlServer.Dacpac/Scaffolding/SqlServerDa
> cpacFunctionModelFactory.cs:line 39
>    at 
> RevEng.Core.ReverseEngineerScaffolder.GenerateFunctions(ReverseEngineerCommandOp
> tions options, List`1 schemas, List1& errors, String outputContextDir, String 
> modelNamespace, String contextNamespace, Boolean supportsFunctions) in 
> D:\a\EFCorePowerTools\EFCorePowerTools\src\Core\RevEng.Core.60\ReverseEngineerSc
> affolder.cs:line 136

Im using the EFCorePowerTools in the master branch updated to the commmit d8bdd715bf3d92f3bceff5be0ff702c2d6bd0c4f from 10-Oct-24
And Im using the efcpt.8 project with .Net sdk 8.0.4 version

I was debugging the code, and the issue occurs while retrieving the functions on line 112 of SqlServerDacpacFunctionModelFactory.cs:

`var functions = model.GetObjects<TSqlTableValuedFunction>(DacQueryScopes.UserDefined).ToList();`
               
the functions we retrieve don't contain the information about the DataType of the columns, which is why the exception occurs in

```
columnList.Add(new ModuleResultElement
{
    StoreType = column.DataType.First().Name.Parts[0],
    Nullable = column.Nullable,
    Name = column.Name.Parts[2],
    Ordinal = i++,
});
```

I attach a test DACPAC file with a table and a table-valued function where the error occurs. Perhaps you can find a solution to the problem :)

[ProblemGetTableValuedFunctions.zip](https://github.com/user-attachments/files/17330094/ProblemGetTableValuedFunctions.zip)

**Comment by ErikEJ** [comment]
@Califorro Thanks for a good error report, I will have a look!

**Comment by ErikEJ** [comment]
I think you are facing this issue (there were other issues discovered, bit this one remains) https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#sql-server-database-project-dacpac-mapping

**Comment by ErikEJ** [comment]
Due to this:

`IIF (LEN(VersNr) > 7, 1, 0) AS IsValidVersNr`

**Comment by ErikEJ** [comment]
I could of course skip the computed column, and you could add it manually in a partial class?

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

**Comment by Califorro** [comment]
Yes, it worked, and now the program execution completes successfully. I will manually add the remaining columns in a partial class.

Thank you very much for your quick response and solution. @ErikEJ

**Comment by ErikEJ** [comment]
Great, my approach is to map as much as possible and continue the flow...
