### ISSUE TITLE
Error while Reverse Engineer

### ISSUE THREAD

**Issue by KevinDebeil** [ErikEJ/EFCorePowerTools#2574]
Create a bug report, feature proposal, or ask a question.

NOTICE: A bug report without sufficient technical and repro details and version information WILL BE CLOSED WITHOUT ANY FURTHER ACTION.

### Provide steps to reproduce a bug
Reverse Engineer 
Select dacpac & EF Core 7

Please include a **complete** description of the issue or link to a project that I can run to reproduce the issue.
![image](https://github.com/user-attachments/assets/65ac4a37-cd47-4303-81a0-4095c08227b6)

### Provide technical details

- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
7
- Exact Visual Studio version: (e.g. Visual Studio 2022 17.6.5)
Microsoft Visual Studio Community 2022 (64 bits) - Current
Version 17.9.6

- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)
SQL Server

- EF Core version in use: (e.g. EF Core 7)
EF Core 7

- Is Handlebars templates used: no/yes
Yes

- Is T4 templates used: no/yes
Yes

- Is a SQL Server .dacpac used: no/yes
Yes

**Comment by ErikEJ** [comment]
Which extension version?

Have you tried with EF Core 8?

**Comment by KevinDebeil** [comment]
I'm using version 4.6.497
It works with EF Core 8, but I can't upgrade this project with to EF Core 8 for the moment.

**Comment by ErikEJ** [comment]
It looks like I broke support for EF Core 7, and I have stopped maintaining the tools for it. 

Might be able to extract the missing file from an old branch, but I assume you are aware that EF Core 7 is out of support..

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

If you like my free tools, I would be very grateful for a rating/review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) and/or a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by KevinDebeil** [comment]
It works fine.
Thanks a lot Erik :)
