### ISSUE TITLE
 efpt.renaming.json doesn't seem to support multiple contexts from the CLI

### ISSUE THREAD

**Issue by jwyza-pi** [ErikEJ/EFCorePowerTools#2579]
### Provide steps to reproduce a bug

1. Create 2 (or more) efctp-config.json files, for example with the names `efcpt-config.widget.json` and `efcpt-config.world.json`.  
2. Create 2 matching renaming files, for example `efpt.widget.renaming.json` and `efpt.world.renaming.json`
3. Run the CLI for each efcpt-config file.

Results will be that the renaming is not applied.  It appears to be [hard coded](https://github.com/ErikEJ/EFCorePowerTools/blob/c2b16f28e8b513c328efdc0060cf5b5b737832c7/src/GUI/RevEng.Shared/Cli/CliConfigMapper.cs#L483) to only look for `efpt.renaming.json`.

The expected functionality would be that it'd follow the same convention as the non-cli renaming.  IE, if the config file is `something.context.json`, it'd look for a renaming file of `efpt.context.renaming.json` (or `efcpt-config.renaming.json`).

Workaround is to have the efctp config and renaming files in different folders and run the tool from those folders. 

### Provide technical details

- EF Core Power Tools version: efcpt.8 8.1.391+18beaffe73ab78ead682ea390f83084ed6abc607

- Exact Visual Studio version: N/A

- Database engine: Azure SQL

- EF Core version in use: 8

- Is Handlebars templates used: no

- Is T4 templates used: no

- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
> Workaround is to have the efctp config and renaming files in different folders and run the tool from those folders.

The CLI tool in general does not support multiple DbContexts in same folder.

One solution would be to add an option to override the default renaming file name, similar to the option to override the config file name??

**Comment by jwyza-pi** [comment]
That'd probably be the simplest approach

**Comment by ErikEJ** [comment]
And much easier to discover than magic pattern matches.
