### ISSUE TITLE
PostgreSQL DbContext Model Diagram not working

### ISSUE THREAD

**Issue by ivansangines** [ErikEJ/EFCorePowerTools#258]
Hello,

Here is the description of my problem, while trying to generate a Diagram for my PostgreSQL DB: 

I am generating the DbContext as well as the EntityFrameworks using EFCorePowerTools without any issue. I am even selecting the box to install all EF Core Provider Packages (I thought it would be nice to avoid any dependencies). However, whenever I try to add the DBContext Diagram, it throws a **System.IO.FileNotFoundException: Could not find file 'c:\users....\Microsoft.EntityFrameworkCore.Design.dll'**

I tried installing the Microsoft.EntityFrameworkCore.Design NuGet but the same exception is thrown. I am Installing the latest version 3.0.0 and I observed Microsoft.EntityFrameworkCore.Design.dll does not appear as a reference in the Reference tab (even though the installation is completed with no error, not sure if that might be the issue)

### Steps to reproduce
1. Create a simple PostgreSQL database
2. Create new project in VS (Class Library)
3. Install Npgsql Nuget package (lates version)
4. Right click on project solution EF Core Power Tools -> Reverse engineer -> select DB connection -> choose all the tables 
5. Create the Model folder in order to store DBContext and EF (select Install EF Core provider package in the project)
**UNTIL HERE, EVERYTHING WORKS FINE AND EVERYTHING IS GENERATED PERFECTLY**
6. Right click on project solution EF Core Power Tools -> Add DBContext Model Diagram
7. NO diagram generated and exception thown

### Further technical details
EF Core Power Tools version: 2.2.63.0

Database engine: Postgres

Visual Studio version:  Visual Studio 2017 15.9

Thank you for your help!

**Comment by ErikEJ** [comment]
I am suspecting that it might be caused by the fact that 3.0 release version is not yet supported by the tool. I will update this when that happens (hoping for "soon")

**Comment by ivansangines** [comment]
Hello Erik,

Thank you for your fast response. I realized I was missing the NuGet Npgsql.EntityFrameworkCore.PostgreSQL.Design. However, it did not solve the issue, it now threw me a new error (please see below). I am currently using the following NuGet versions:
- EntityFrameworkCore 2.2.6
- EntityFrameworkCore.Design 2.2.6
- Npgsql 4.0.7
- Npgsql.EntityFrameworkCore.PostgreSQL 2.2.4
- Npgsql.EntityFrameworkCore.PostgreSQL.Design 1.1.1

Whenever I use those versions, the error thrown is: **System.Exception: Unable to find a supported version of Microsoft.EntityFrameworkCore.dll**

If I try to update to latest version of EntityFramework and Npgsql, I get this error: **You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.** That is why I am trying to use older versions, not the latest one, however I still cannot create the Diagram.

**Comment by ErikEJ** [comment]
2.2.6 should be supported in the latest daily build of the toolbox. You will have to create a repro project so I can investigate.

**Comment by ivansangines** [comment]
Hello Erik,

I just created a public repo, let me know if that is what you need:
https://github.com/ivansangines/ClassLibrary1

Thank you again!

**Comment by ErikEJ** [comment]
Thanks, you need the latest daily build for support for 2.2.6!

**Comment by ivansangines** [comment]
Hello Erik,

Thank you once again for the fast response. However, I tried installing the latest daily build and the same error message was thrown: **Unable to find a supported version of Microsoft.EntityFrameworkCore.dll in folder C:\Users\SangII\source\...bin\Debug**

I have downloaded the latest daily build from **https://github.com/ErikEJ/EntityFramework6PowerTools**

Thank you for your time!

**Comment by ErikEJ** [comment]
https://github.com/ErikEJ/EntityFramework6PowerTools is the EF 6 tool, not the EF Core Tool - see download link here: https://github.com/ErikEJ/EFCorePowerTools/wiki/Release-notes

**Comment by ivansangines** [comment]
Hello Erik,

It looks like I am getting there. However, I might be something wrong in the configuration or some small detail I cannot figure out. I am getting a new error while trying to create the diagram: **No database provider has been configured for this DbContext. A provider can be configured by overriding the DbContext.OnConfiguring method or by using AddDbContext on the application service provider. If AddDbContext is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.** 

I selected the option to generate entities and DBContext. Here is my auto-generated TestContext class, is there something missing? 

public partial class TestContext : DbContext
    {
        public TestContext()
        {
        }

        public TestContext(DbContextOptions<TestContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Enrollment> Enrollment { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<Subject> Subject { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            

            modelBuilder.Entity<Enrollment>(entity =>
            {
                entity.ToTable("enrollment");

                entity.Property(e => e.Id)
                    .HasColumnName("id")
                    .ValueGeneratedNever();

                entity.Property(e => e.Classid).HasColumnName("classid");

                entity.Property(e => e.Studentid).HasColumnName("studentid");

                entity.HasOne(d => d.Class)
                    .WithMany(p => p.Enrollment)
                    .HasForeignKey(d => d.Classid)
                    .HasConstraintName("enrollment_classId_fkey");

                entity.HasOne(d => d.Student)
                    .WithMany(p => p.Enrollment)
                    .HasForeignKey(d => d.Studentid)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("enrollment_studentid_fkey");
            });

            modelBuilder.Entity<Student>(entity =>
            {
                entity.ToTable("student");

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.Lastname)
                    .IsRequired()
                    .HasColumnName("lastname");

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasColumnName("name");
            });

            modelBuilder.Entity<Subject>(entity =>
            {
                entity.ToTable("subject");

                entity.Property(e => e.Id)
                    .HasColumnName("id")
                    .ValueGeneratedNever();

                entity.Property(e => e.Classname).HasColumnName("classname");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }

Thanks a lot for your help!

**Comment by ivansangines** [comment]
Hello Erik,

It looks like we are getting there. However, I am having problems with the Nugget versions.

In order to use:
- EntityFrameworkCore 2.2.6
- EntityFrameworkCore.Design 2.2.6
- Npgsql 4.0.7
- Npgsql.EntityFrameworkCore.PostgreSQL 2.2.4
- Npgsql.EntityFrameworkCore.PostgreSQL.Design 1.1.1

 Npgsql.EntityFrameworkCore.PostgreSQL 2.2.4 has a dependency on System.ValueTuple 4.5, which is version 4.0.3.0. However, whenever I try to generate the diagram, this error is thrown:

**System.ArgumentException: Error:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) ---> System.IO.FileLoadException: Could not load file or assembly 'System.ValueTuple, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)**

Am I overlapping any NuGet versions, which are not compatible to each other? Or what versions should I install if my project target is **.NET Framework4.6.1**

Thank you for your time and help!

**Comment by ErikEJ** [comment]
Make sure you are running a recent VS version, and consider targeting NEt 4.7.1 or later

**Comment by ivansangines** [comment]
I am running **VS 2017 15.9.16** and I just tried targeting **NET 4.7, NET 4.7.1 and .NET 4.7.2** and I get the same error while trying to generate the Diagram

**Comment by ErikEJ** [comment]
Does your ClassLibrary repository reflect your latest changes?

**Comment by ivansangines** [comment]
ClassLibrary2 has all the new changes using VS 2017 15.9.16, the daily extension, EF 2.2.6 and targeting .NET 4.7.1

Thank you!

**Comment by ErikEJ** [comment]
I just realised, .NET Framework based diagramming only supports SQL Server.
