### ISSUE TITLE
Programmatic scaffolding

### ISSUE THREAD

**Issue by ozzioma** [ErikEJ/EFCorePowerTools#2580]
Does this contain a library or package to programmatically generate a scaffolded dynamic DbContext given a connection string? 
Or generate the models programmatically to a folder?
I'm going through the EF Core design services and tools assemblies source code for scaffolding and having issues with transitive dependencies.

**Comment by ErikEJ** [comment]
@ozzioma  Yes, it has code to do this, and a command line tool - have you had a look at the documentation?

Not sure what exactly you are trying to do

**Comment by ozzioma** [comment]
Hi Erik,

I'm trying to generate a dynamic DbContext on demand..in code..from a connection string.
Not a command line tool.
There's a use case for that in the product specs I'm working on.
Already have a prototype but having issues with loading db specific features like hooking into the context life cycle to register custom types etc.

**Comment by ErikEJ** [comment]
I strongly advise you to not do that...

**Comment by ozzioma** [comment]
Please elaborate.
The context is a service that exposes OData and GraphQL endpoints on demand from a datasource connection string.

Basically using IReverseEngineerScaffolder and Roslyn compilation to emit an in memory assembly that's used to load the generated DbContext type.

Still investigating issues around collectible assemblies for .Net 8/9.
There are concerns that have been addressed around clustered/distributed deployment.

I think it's a valid use case and the overhead of Roslyn compilation is minimal.
There's no work around so far to the requirement, namely dynamically exposing endpoints at runtime.
Please elaborate and advise.

**Comment by ErikEJ** [comment]
Feel free to dive into the source of this project, a good starting point is the efreveng80 project

**Comment by ozzioma** [comment]
Ok thanks.
Browsing through the main branch and can't find the project you referenced.
What folder or branch is it in?
