### ISSUE TITLE
Add Support for EntityTypeConfiguration.t4

### ISSUE THREAD

**Issue by jwyza-pi** [ErikEJ/EFCorePowerTools#2583]
Ticket to track the ability to use EntityTypeConfiguration.t4 template files in EFCPT.  The goal here is to add the support for the item referenced in https://github.com/ErikEJ/EFCorePowerTools/issues/1499.

See this PR https://github.com/ErikEJ/EFCorePowerTools/pull/2582.  

If there are changes you'd like me to make, please let me know.  Tried to do this with the lowest impact possible.  

### Provide technical details

- EF Core Power Tools version: 8.1.current

- Exact Visual Studio version: N/A

- Database engine: Azure SQL

- EF Core version in use: EF Core 8

- Is Handlebars templates used: no

- Is T4 templates used: yes

- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
This is my thoughts on the design of this: Make the UX as smooth as possible, so no hand editing of .t4 files will be needed out of the box.

In the VS extension I currently have this:

![image](https://github.com/user-attachments/assets/c42827be-0d2f-460c-a701-bf14b9fdeb8e)

Corresponds to "use-t4" in the CLI config. 

I also include .zip files with the corresponding templates (.t4) files, on for EF Core 7 and one for EF Core 8 (I have logged: https://github.com/ErikEJ/EFCorePowerTools/issues/2584)

The .zip files are unpacked if not t4 files are present in the project, see the T4Helper class

So to add this feature, I think we could do this:

- [ ] Add a new set of .zip files for EF Core 8 and 9: `T4_800_Split.zip` (or similar)
- [ ] Add a new config option: use-t4-split / UseT4Spilt
- [ ] Warn if mixing both t4 split and current split option, and prefer T4 option
- [ ] Doing this will also avoid the breaking change of changing the rootNameSpace property usage
- [ ] Add a new option in the dropdown show above: "C# - T4 (Split DbContext)" (or similar)

**Question:** Are the entityconfiguration files created in a Configurations folder under the DbContext? (Like today)

**Comment by jwyza-pi** [comment]
Re; Configuration folder.  There is a section in the PR that is moving them into the Configurations folder such that the behavior is maintained.  (they get generated in the same folder in as the context, so a step to move them needed to be added). 

Overall, I think your approach works.  Might take a me a few days to get through the various pieces, but having this support is going to make my life a lot easier.  (I had some other post-processing I needed to do to the type configs and while it works, it's terrible powershell script filled with regex replacements and it would be alot cleaner to just make the adjustments in the type configs 😁)

**Comment by ErikEJ** [comment]
@jwyza-pi And then we can also get rid of the teriblle DbContextSplitter class some time!

Great that you are taking this on, just focus on the CLI related changes, I will take care of the VS extension part in a future PR

**Comment by jwyza-pi** [comment]
Apologies for the radio silence on this.  Primary job has pulled me away, but I do plan to circle back and tackle this next week as I do still need it.

**Comment by ErikEJ** [comment]
No rush...

**Comment by jwyza-pi** [comment]
@ErikEJ - found an issue.  If you never had a Configurations folder, it fails to check and create one first :( .  Do you want me to open up another PR or do you want to add the check when you do the .net9/VSIX stuff?
