### ISSUE TITLE
Integration of Stored Procedures into Existing DbContext

### ISSUE THREAD

**Issue by andrenevesgomes** [ErikEJ/EFCorePowerTools#2588]
Hi Erik,

First off, thanks again for the great work on EF Core Power Tools! I have a question related to reverse engineering stored procedures and how they integrate with the DbContext.

### Provide steps to reproduce a bug

1. Reverse engineer a SQL database including tables, views, and stored procedures.
2. The tool generates a DbContext for tables and views as expected.
3. However, stored procedures don't seem to be automatically wired into the same DbContext or integrated the same way as the tables or views.

### Provide technical details

- EF Core Power Tools version: 2.6.577
- Visual Studio version: Visual Studio 2022 17.11.5
- Database engine: SQL Server
- EF Core version in use: EF Core 8
- Is Handlebars templates used: No
- Is T4 templates used: No
- Is a SQL Server .dacpac used: No

I understand that a separate DbContext isn't generated, but I’m unsure of the correct process to fully integrate the stored procedures into the same DbContext. Am I missing a step, or is there some configuration I need to update?

Thanks again for your time and support!

https://github.com/user-attachments/assets/dddcf5c7-5170-41dc-877f-67b69b104723

**Comment by ErikEJ** [comment]
@andrenevesgomes Thanks for the kind words. On the "Choose Database Objects" select your stored procedures (you are only selectig your tables) 

https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#choose-database-objects

If you like my free tools, I would be very grateful for a rating/review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) and/or a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by andrenevesgomes** [comment]
Hi @ErikEJ , thank you for the quick response!

In the previous video I sent, I first scaffolded the tables and then the stored procedures separately, replicating my current scenario where I had all the tables set up and later needed to add a new stored procedure.

I've now created a new video where I select both the tables and stored procedures together in a single operation. However, it's still generating two separate contexts. Am I missing something in the process?

https://github.com/user-attachments/assets/0f754f34-64e9-42aa-b03c-3f034bce4575

**Comment by ErikEJ** [comment]
@andrenevesgomes It is the same "DbContext" just is a seperate file, looks at the docs for usage - and you must generate both tables and procedure at the same time, not one after the other!

Again, here is a link to the docs: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#sql-server-stored-procedures

**Comment by ErikEJ** [comment]
@andrenevesgomes Assume you got your questions answered?
