### ISSUE TITLE
When refreshing from the menu on the efpt file, all templates get run.

### ISSUE THREAD

**Issue by bdelany** [ErikEJ/EFCorePowerTools#2596]
I have 4 separate templates in my project.  I also use 3 separate  efpt files to run each template.

When I refresh just one of the efpt files, all of the other templates also get run.  Plus, it also sometimes puts each resulting file in each output path.  Beyond that sometimes it also overwrites the results from one template to another.

here's my project layout:
![image](https://github.com/user-attachments/assets/7e140169-dc85-4b95-b72a-4953e91fb3c2)

here's an example of one of my efpt files.  only the OutputPath and T4TemplatePath change for each template:

![image](https://github.com/user-attachments/assets/50c936be-60ae-430b-b559-7a91cb8589ab)

It has to be configuration right?  Can you tell me what i am doing wrong?

###  technical details

- EF Core Power Tools version: 2.6.577

- Exact Visual Studio version: 2022 17.11.5

- Database engine: SQL Server

- EF Core version in use: 8.0.10

- Is Handlebars templates used: no

- Is T4 templates used: yes

- Is a SQL Server no

**Comment by ErikEJ** [comment]
@bdelany How are you "refreshing" - I would suggest putting the efpt.config.json file in indviidual folder instead of having them all in the root folder. But in order to debug, I need a reproduction project.

**Comment by bdelany** [comment]
I use the context menu on the efpt file to do the refresh.  How can i ship you my project?

**Comment by ErikEJ** [comment]
@bdelany Thanks, You can email me a .zip file (remove bin and obj dfolders) to ejlskov at hotmail dot com

**Comment by bdelany** [comment]
Just wondering if you received my zip file last week?

**Comment by ErikEJ** [comment]
Never did, maybe caught in a filter

**Comment by ErikEJ** [comment]
@bdelany I finally figured it out - you are hit by the process multiple templates feature as documented in the wiki: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#customize-code-using-t4-templates

I think you best option is to split you code into multiple projects.
