### ISSUE TITLE
Data API Builder Scaffold Nullable types in schema's

### ISSUE THREAD

**Issue by ehilgenvs** [ErikEJ/EFCorePowerTools#2597]
Hello,

Thank you for sharing this great tool!

I have used Data API Builder Scaffold to generat an API and that works great, exept that the nullabale types are not set in the Schema.
So i call the API from swagger it goes OK and nullable fields retuser a value or null.
For the client i use the the Microsoft service reference / OpenAPI to consume the dab-API and tehat works fine unitl the internal JSON serilizer breaks  on the nullable fiels, i think this is caused by that the nullable fields are not set in the Schema.

### Provide steps to reproduce a bug
Create an database table with the some nullable fields, and staffold the API. 
.\dab-build.cmd
dab run
check the schema in Swagger.

### Provide technical details

- EF Core Power Tools version: 2.6.577

- Exact Visual Studio version: Visual Studio 2022 17.11.4

- Database engine: SQL Server

- EF Core version in use:  EF Core 8

- Is Handlebars templates used: yes

- Is T4 templates used: yes

- Is a SQL Server .dacpac used: no/yes

**Comment by ErikEJ** [comment]
@ehilgenvs Glad you like my free tools and have tried this preview feature!

Please post a CREATE TABLE statement that reproduces this issue and I will have a look.

**Comment by ErikEJ** [comment]
@ehilgenvs This sounds more like an unrelated tooling issue than anything to do with DAB or EF Core Power Tools, if the Swagger UI works as expected.

**Comment by ehilgenvs** [comment]
> @ehilgenvs Glad you like my free tools and have tried this preview feature!
> 
> Please post a CREATE TABLE statement that reproduces this issue and I will have a look.

CREATE TABLE [dbo].[Companies](
	[CompanyId] [uniqueidentifier] NOT NULL,
	[Name] [nvarchar](255) NULL,
	[Street] [nvarchar](255) NULL,
	[StreetNumber] [nvarchar](255) NULL,
	[Postalcode] [nvarchar](255) NULL,
	[City] [nvarchar](255) NULL,
	[DateCreated] [datetime2](7) NOT NULL,
	[UserCreated] [varchar](256) NULL,
	[DateModified] [datetime] NULL,
	[UserModified] [varchar](256) NULL,
	[IsDeleted] [bit] NOT NULL,
	[Gps] [char](50) NULL,
	[IsDisplayedOnMap] [bit] NULL,
	[StatusIoObject] [nchar](30) NULL,
	[StatusBitmapLocation] [nchar](30) NULL,
	[StatusIoChannelId] [uniqueidentifier] NULL,
	[Code] [varchar](256) NULL,
 CONSTRAINT [PK_Company] PRIMARY KEY CLUSTERED 
(
	[CompanyId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Companies] ADD  CONSTRAINT [DF_Company_DateCreated]  DEFAULT (getdate()) FOR [DateCreated]
GO

ALTER TABLE [dbo].[Companies] ADD  CONSTRAINT [DF_Company_UserCreated]  DEFAULT ('SQL') FOR [UserCreated]
GO

ALTER TABLE [dbo].[Companies] ADD  CONSTRAINT [DF_Company_IsDeleted]  DEFAULT ((0)) FOR [IsDeleted]
GO

ALTER TABLE [dbo].[Companies]  WITH CHECK ADD  CONSTRAINT [FK_Companies_Channels] FOREIGN KEY([StatusIoChannelId])
REFERENCES [dbo].[Channels] ([ChannelId])
GO

ALTER TABLE [dbo].[Companies] CHECK CONSTRAINT [FK_Companies_Channels]
GO

**Comment by ehilgenvs** [comment]
> @ehilgenvs This sounds more like an unrelated tooling issue than anything to do with DAB or EF Core Power Tools, if the Swagger UI works as expected.

It works as expected for returing the data, but in the Swagger schema the fields are not remarked as nullable

**Comment by ErikEJ** [comment]
Can you share a snippet from the Swagger schema that shows this?

**Comment by ErikEJ** [comment]
@ehilgenvs Thanks, the schema  and column types are is discovered during runtime by DAB, so you should report and issue here: https://github.com/Azure/data-api-builder/issues

**Comment by ehilgenvs** [comment]
Hi Erik,

Thank you for your support, at the end the service reference for OpenAPI client does not handle the null values correctly.
I switched over for the client side to NSwag and this client handles everything as suspected.

Regards,

Etienne

________________________________
