### ISSUE TITLE
Unable to add new tables to entities

### ISSUE THREAD

**Issue by arunprasathv** [ErikEJ/EFCorePowerTools#26]
Context and Entities exist already and  I want to add one more table to the context. but the context is overriding with the new table added and lost all other entities. 

### Steps to reproduce
Include a complete description that I can redo to reproduce the issue.

### Further technical details
EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
4.7.568.0
Database engine: (SQlite, SQL Compact, SQL Server, Postgres)
SQL  Server
Visual Studio version: (e.g. Visual Studio 2017 15.7)
2017

**Comment by ErikEJ** [comment]
could you share som screenshots please

**Comment by ErikEJ** [comment]
Select all the tabels you want to generate code for each time, not just the new tables(s)
