### ISSUE TITLE
Reverse Engineer MySQL database not saving

### ISSUE THREAD

**Issue by davidhendrickmb** [ErikEJ/EFCorePowerTools#260]
Hi there,

I'm trying to reverse engineer a MySQL database and have followed the instructions to "To use MySQL, install the MySQL Visual Studio Tools".

When I try to save the connection it doesn't work, any ideas?

Thanks,
David

**Comment by jespersh** [comment]
Version?
It is requested in the issue template: EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)

**Comment by davidhendrickmb** [comment]
Thanks for your response.
It's version 2.2.63.

**Comment by jespersh** [comment]
This issue was fixed in #249 and you'll need a build after Aug 21 (2.2.63 is from Jun 16)
Check with the daily builds: https://github.com/ErikEJ/EFCorePowerTools#downloadsbuilds

**Comment by davidhendrickmb** [comment]
OK thanks. Are the daily builds stable? It's the latest in Visual Studio.

**Comment by jespersh** [comment]
I find them pretty stable for mysql usage that I do
