### ISSUE TITLE
can't add new connect

### ISSUE THREAD

**Issue by tiger2014** [ErikEJ/EFCorePowerTools#2605]
when I wan to add new database connect:

![image](https://github.com/user-attachments/assets/336868c1-9b0b-4d6b-a4b2-9c7dd9047bbd)

I encounter this issue:

![image](https://github.com/user-attachments/assets/a139fec0-49b1-4a15-a2bf-aebf9fb4704d)

- EF Core Power Tools version: (2.6.577)

- Exact Visual Studio version: (e.g. Visual Studio 2022 17.11.5)

- Database engine: (SQL Server)

- EF Core version in use: (Microsoft.EntityFrameworkCore.SqlServer 8.0.10, Microsoft.EntityFrameworkCore 8.0.10)

**Comment by ErikEJ** [comment]
Which exact VS version do you use?

**Comment by ErikEJ** [comment]
@tiger2014 Ping?

**Comment by tiger2014** [comment]
> Which exact VS version do you use?

VS 2022 17.11.5 (the newest update)

![image](https://github.com/user-attachments/assets/bff82c10-a076-472e-acc2-8592e154afa6)

**Comment by ErikEJ** [comment]
I think you can try to repair your VS installation

**Comment by tiger2014** [comment]
> I think you can try to repair your VS installation

Thanks! Everything works after repair:

![image](https://github.com/user-attachments/assets/ce6b743f-6723-490a-b9c3-e5cdb550850d)

**Comment by ErikEJ** [comment]
Great news

If you like my free tools, I would be very grateful for a rating/review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) and/or a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by tiger2014** [comment]
> Great news
> 
> If you like my free tools, I would be very grateful for a rating/review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) and/or a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

I had reviewed it on Visual Studio Marketplace, and marked as 5 stars.
