### ISSUE TITLE
t4 can't generation custom class

### ISSUE THREAD

**Issue by tahasvc** [ErikEJ/EFCorePowerTools#2607]
hello,

Sure, here’s the English translation of your message: “I read the custom T4 document, but I really couldn’t understand it. The T4 files are present in the main directory of the project under the CoreTemplates/EFCore path. When I set UseT4 true and provide the template path, it likely doesn’t work because it uses its own logic to generate it. When I pass null for the path, it can be customized and read properly. At this point, my main goal is to generate repository classes through a different T4 file, apart from DbContext and EntityType, but I am unable to do so. Could you help me with that?” Let me know if you’d like further assistance in English or any additional details?

Also, it is stated in the document that you can create a custom structure with more than one folder. Is the basic requirement here to create files named dbcontext and entitytype under x-y-z/CodeTemplates/EFCore/?

  "T4TemplatePath": "CodeTemplates/EFCore", don't work, ->   "T4TemplatePath": null -> work,
  
  

![image](https://github.com/user-attachments/assets/730a988a-8592-4872-a360-0e1df0d3a846)

**Comment by ErikEJ** [comment]
Is the basic requirement here to create files named dbcontext and entitytype under x-y-z/CodeTemplates/EFCore/?

Yes!

**Comment by tahasvc** [comment]
How should I provide multiple paths in JSON on the config side?

**Comment by ErikEJ** [comment]
@tahasvc You do not need to provide paths in the config file, just place multiple folders with templates in your project (as documented in the wiki)
