### ISSUE TITLE
Reverse engineering with a dot (.) in the context name results in invalid classes

### ISSUE THREAD

**Issue by marijnz0r** [ErikEJ/EFCorePowerTools#2608]
While reverse engineering a database, when entering a dot (.) in the context name field, this will result in invalid classes.

#### Steps
1. Right click a project in a solution
2. Left click EF Core Power Tools
3. Left click Reverse Engineer
4. Select a Database Connection
5. Left click OK
6. Choose your database objects > OK
7. In the Context Name field: add any name including a dot (.), for example "Northwind.DbContext"
8. Left click OK

#### Result

- The partial classes containing the Procedures and Functions are generated invalidly (`public partial class Northwind.DbContext` `Compiler Error CS0116: A namespace cannot directly contain members such as fields or methods.`)
- The partial class containing the rest is correctly generated (`public partial class NorthwindDbContext : DbContext`)

### Technical details

- EF Core Power Tools version: 2.6.577

- Exact Visual Studio version: Visual Studio 2022 17.11.4

- Database engine: SQL Server

- EF Core version in use: EF Core 8

- Is Handlebars templates used: no

- Is T4 templates used: no

- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
Please share a full repro including your efpt.config.json file

**Comment by ErikEJ** [comment]
I think it might be the name "DbContext" as part of your namespace cauing issues.

**Comment by ErikEJ** [comment]
@marijnz0r Thanks for reporting this.

I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

If you like my free tools, I would be very grateful for a rating/review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) and/or a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by ErikEJ** [comment]
Thanks a lot. Let me know if the latest daily works for you.

**Comment by marijnz0r** [comment]
Yes, the latest daily build fixed my issue. Thanks again.
