### ISSUE TITLE
Dotnet Standard 2.1 not supported

### ISSUE THREAD

**Issue by frankhaugen** [ErikEJ/EFCorePowerTools#261]
EF Core Power Tools throws error on dotnet standard 2.1

This is probably easy to solve, because 2.1 does not, as far as I know, break functionality to 2.0. The fix should be requiring standard 2.0 or higher in the version validation, rather than just 2.0.

### Steps to reproduce
Try to use the modelling functionality on my EF Core 3 Classlib Project
![image](https://user-images.githubusercontent.com/13543585/66034159-00a83200-e509-11e9-8909-83906301652c.png)

### Further technical details
EF Core Power Tools version: 2.3.28.0
Database engine: SQL Server
Visual Studio version: Visual Studio 2019 16.3

### EFCore About
Version 2.3.28.0

SQL Server Compact 4.0 in GAC - No
SQL Server Compact 4.0 DbProvider - No

SQL Server Compact 4.0 DDEX provider - No
SQL Server Compact 4.0 Simple DDEX provider - Yes

SQLite ADO.NET Provider included: 1.0.110.0
SQLite EF6 DbProvider in GAC - No

System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes

**Comment by ErikEJ** [comment]
Neither .net standard 2.0 or 2.1 projects are supported.

**Comment by jespersh** [comment]
I'm currently targeting 2.0 without issues on 2.3.28.0
![image](https://user-images.githubusercontent.com/1004198/66048261-820fbc80-e529-11e9-92a1-490af1488820.png)

netstandard 2.1 reverse engineering worked as well. But maybe you're not talking about Reverse Engineer?

**Comment by ErikEJ** [comment]
This issue concerns model inspection, not reverse engineering.
