### ISSUE TITLE
Select top (@limit) fails

### ISSUE THREAD

**Issue by RangerHCInfo** [ErikEJ/EFCorePowerTools#2620]
When creating a stored procedure with a limit, generation fails to get the result properly.  

- EF Core Power Tools version: 2.6.420

- Exact Visual Studio version: Microsoft Visual Studio Enterprise 2022 (64-bit) - Current
Version 17.11.2

- Database engine: Azure SQL

- EF Core version in use: EF Core 8
- Is Handlebars templates used: no

- Is T4 templates used: yes

- Is a SQL Server .dacpac used: no

Repro:

CREATE PROCEDURE [dbo].[GetAll]
	@limit		INT = 10
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	SET NOCOUNT Off;

    -- Insert statements for procedure here
	DECLARE @TempTable TABLE
	(
		PlanID int PRIMARY KEY,
		Count int
	)

	INSERT INTO @TempTable (PlanID,Count) values (1,1);

	Select Top (@limit) * from @TempTable OPTION(RECOMPILE)
END
GO

**Comment by ErikEJ** [comment]
@RangerHCInfo Result set discovery is picky, and can easily fail, in particular with dynamic statements like yours. See the wiki for things to try and workarounds.

**Comment by RangerHCInfo** [comment]
Thanks Erik.  I removed the Option(Recompile) and it seems to like it better.  Clearly there is something there.  I use it elsewhere and it is fine.  It only seems to be in conjunction with top.

**Comment by ErikEJ** [comment]
So you are unblocked now?

If you like my free tools, I would be very grateful for a rating/review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) and/or a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
