### ISSUE TITLE
Why is EF Tools deleting existing entities from the project when adding a new context and entities from another database?

### ISSUE THREAD

**Issue by Tony20221** [ErikEJ/EFCorePowerTools#2624]
I am experiencing very unexpected behavior.

Let's say I have a database called database1 and a table called table1 in it.
I choose Reverse Engineer and EF Tools creates two files: Database1Context.cs and Table1.cs in a new Models folder. 
I am using all default selections.
So far so good.

I have another database called database2 and a table called table2.
I select reverse engineer database2 and the outcome is this:
The Database1Context.cs has the same name and it references Table2. Everything about Table1 is gone!
Table1.cs file is deleted!
Table2.cs is created.

What I expected is this:
The existing files should stay the same. I am reverse engineering a new database and I want to add to what is already in the project.
This means Database1Context.cs and Table1.cs should be untouched.

I expect these two new files to be created: Database2Context.cs and Table2.cs

Please explain why I am getting this unexpected behavior and how to reverse engineer different databases without each affecting files from another database?

Using version: 2.6.577

**Comment by ErikEJ** [comment]
There are multiple waus to do this, but have you read the wiki about using multiple DbContexts in the same project?

(The behaviour is the expected, default behaviour)

Also, the files are moved to the Recycle Bin, not deleted.

**Comment by Tony20221** [comment]
I suggest the tool displays a warning before it overwrites stuff and suggests using multiple config sites if using same project instead of directly doing a destructive action. You might have instructions in a wiki but not everyone is going to read it all before using the tool. 

The files are deleted from the project and folder and not showing anymore in the solution explorer. That's the formal definition of a file getting deleted. Like what file explorer does when you delete a file. If they are in the recycle bin, that just means they are recoverable.

Anyway, I will try the multiple config file option. Thanks.

**Comment by ErikEJ** [comment]
Sorry you had a bad experience, this has been back and forth many times, and I am not going to change anything at this point.

If you like my free tools, I would be very grateful for a rating/review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) and/or a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by Tony20221** [comment]
Solution was to use a different folder.
