### ISSUE TITLE
Compiled models and the reverse generation with store procedure

### ISSUE THREAD

**Issue by georgeemr** [ErikEJ/EFCorePowerTools#2625]
Hi, I'm using EF Core 9 (preview) 
![image](https://github.com/user-attachments/assets/4625224f-d13f-408a-9d0f-b66f7aff8734)
![image](https://github.com/user-attachments/assets/49703d62-d1f9-46f5-a78c-b083461a7dcd)

When I try to deploy the app I get the message:
![image](https://github.com/user-attachments/assets/df4e918f-9e3d-4c95-aefa-d458ff023a36)

The model has a store procedure.

![image](https://github.com/user-attachments/assets/ba555243-782c-4bdd-9b95-95e2354b98b8)

EF Core Power Tools 2.6.620
Visual Studio 17.12.0
SQL Server 2022
EF Core 9

Is there a way to make it work?

**Comment by ErikEJ** [comment]
This seems like a question you should post in the EF Core repo, but looks like a limitation of compiled models.

**Comment by georgeemr** [comment]
Thanks a lot @ErikEJ I will
