### ISSUE TITLE
T4 Template Problem

### ISSUE THREAD

**Issue by tahasvc** [ErikEJ/EFCorePowerTools#2638]
I couldn't figure out the t4 file. When I configure it as shown in the images below, the following errors occur.

- When I create a default path and then create the same path in x/, it does not create the configurations files, does not create procedure files. It just creates the model for x/.
- I couldn't give any path, it only works when I pass null. Otherwise it doesn't examine t4 at all.

-  My only goal is to make my work in dbcontext and entitytype files work and then I have a DataTemplate file and I can run it separately.
 I shared that file with you. I want to use the parameters as well. Can I run the 3rd t4 file in parallel while the framework you wrote runs these 2 files? Maybe if you guide me how to add it to the defaults, we can run it that way?

![image](https://github.com/user-attachments/assets/7385afe8-9028-447a-a3b1-b78d6b9d366f)
![image](https://github.com/user-attachments/assets/b0e53e65-c7f2-4c67-8cd5-c4b34ebf50f5)
![image](https://github.com/user-attachments/assets/23a93bed-a6ca-47e8-bc37-58977c0b1ccd)

**Comment by ErikEJ** [comment]
Only DbContext.t4 and EntityType.t4 files are executed. But what you do inside them is completely up to you.

**Comment by tahasvc** [comment]
Why can't I run t4templatepath properly? When I pass any value other than null, it doesn't create it according to the data in the file.
I have provided my path visually above, can you examine it? Also, does it have to be codetemplates/efcore file path?

**Comment by ErikEJ** [comment]
You do not really need to use T4TemplatePath, just place different sets of template in different folders in the project, as documented in the wiki.
