### ISSUE TITLE
ISSUE: Exclude indexes is being overwritten by reverse engineering in the efpt.config.json file

### ISSUE THREAD

**Issue by chassq** [ErikEJ/EFCorePowerTools#2640]
We are trying to use the deature noted in https://github.com/ErikEJ/EFCorePowerTools/pull/2520 and in the docs as 

_"You can also exclude indexes (SQL Server only), for example to work around this [EF Core bug](https://github.com/dotnet/efcore/issues/11298) - add a list of ExcludedIndexes strings to your table object in efpt.config.json. CLI: excludedIndexes"_

### Provide steps to reproduce a bug

Add the ExcludedIndexes section to a table definition in the efpt.config.json. For example:

```
{
  "name": "[dbo].[Folder]",
  "exclude": false,
  "ExcludedIndexes": [
    "UX_Folder_CompanyId_TopLevelFolder"
  ]
}
```

```
Our Config w/o the entry:
{
   "CodeGenerationMode": 4,
   "ContextClassName": "MyAppDbContext",
   "ContextNamespace": "",
   "FilterSchemas": false,
   "IncludeConnectionString": false,
   "ModelNamespace": "",
   "OutputContextPath": "Context",
   "OutputPath": "Model",
   "PreserveCasingWithRegex": true,
   "ProjectRootNamespace": "MyApp.Database.Sql",
   "Schemas": null,
   "SelectedHandlebarsLanguage": 2,
   "SelectedToBeGenerated": 0,
   "T4TemplatePath": null,
   "Tables": [
      {
         "Name": "[dbo].[Folder",
         "ObjectType": 0
      }
   ],
   "UiHint": null,
   "UncountableWords": null,
   "UseAsyncStoredProcedureCalls": true,
   "UseBoolPropertiesWithoutDefaultSql": false,
   "UseDatabaseNames": false,
   "UseDateOnlyTimeOnly": true,
   "UseDbContextSplitting": true,
   "UseDecimalDataAnnotationForSprocResult": true,
   "UseFluentApiOnly": true,
   "UseHandleBars": false,
   "UseHierarchyId": false,
   "UseInflector": false,
   "UseLegacyPluralizer": false,
   "UseManyToManyEntity": false,
   "UseNoDefaultConstructor": false,
   "UseNoNavigations": false,
   "UseNoObjectFilter": false,
   "UseNodaTime": false,
   "UseNullableReferences": false,
   "UsePrefixNavigationNaming": false,
   "UseSchemaFolders": true,
   "UseSchemaNamespaces": true,
   "UseSpatial": false,
   "UseT4": false,
   "UseT4Split": false
}

```
We run the reverse engineering, and the entry disappears from the efpt.config.json

### Provide technical details

- EF Core Power Tools version: 2.6.632

- Exact Visual Studio version: Visual Studio 2022 Version 17.12.0 Preview 5.0

- Database engine: Azure SQL

- EF Core version in use: EF Core 8

- Is Handlebars templates used: no

- Is T4 templates used: no

- Is a SQL Server .dacpac used: yes

**Comment by ErikEJ** [comment]
@chassq I am inestigateing this bug. Note that "exclude" has no effect in efpt.config.json.

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

**Comment by chassq** [comment]
I just pulled down version 2.6.653. Shut down VS 2022. Installed the new vsix file. I hand entered into the efpt.config.json file the following entry on the applicable table:

```
      "ExcludedIndexes": [
        "UIX_MyTable_Endpoint_Id_Type"
      ]
```

I then ran the reverse engineer and observed the entry was removed from the efpt.config.json file and the reverse engineer had not excluded the index. Did I perhaps do something wrong?

**Comment by ErikEJ** [comment]
You did nothing wrong, but you need build .655 or later.

**Comment by chassq** [comment]
Hey Erik,

So I did the same as above with version .655. The entries are now staying in the efpt.config.json when the reverse engineer runs but the indexes are not being ignored. They are still writing to the configuration files and the models are seeing the filtered unique indexes as a single object not a collection. I guess if the index was being ignored the configuration would not show it and the FK ref would be a collection in this case.

**Comment by ErikEJ** [comment]
Thanks for the feedback, I will have another look.

**Comment by ErikEJ** [comment]
@chassq Ah - are you using a .dacpac?

**Comment by chassq** [comment]
yes we are using a dacpac

**Comment by ErikEJ** [comment]
Sorry, I missed that. The feature was never added to .dacpac reverse engineering

**Comment by chassq** [comment]
Ah I see. Is it possible to do so?

**Comment by ErikEJ** [comment]
Oh yes, working on it!

**Comment by ErikEJ** [comment]
I did another attempt, pls try build. 656 or later

**Comment by chassq** [comment]
Trying now

**Comment by chassq** [comment]
Hey Erik, this looks good. Seems like it is working as expected.

**Comment by ErikEJ** [comment]
Wonderful and thanks for the heads up
