### ISSUE TITLE
Incorrect generated context class name for Functions in EFCore 9

### ISSUE THREAD

**Issue by vytautasziurlis** [ErikEJ/EFCorePowerTools#2644]
There was a change in behavior from efcpt8 to efcpt9. I need to set context name in the `dbcontext-name` property in `names` section:
```
  "names": {
    "dbcontext-name": "myEntities",
    "dbcontext-namespace": "DataModel",
    "model-namespace": "DataModel",
    "root-namespace": ""
  },
```

After running scaffolding, I get the following files generated:
* myEntities.cs
* MyEntities.Functions.cs

Notice that context name for functions starts with a capital letter. In addition to this, the actual class name is wrong, which then causes compilation problems.

This is new bahavior, `efcpt8` is working fine.

### Provide steps to reproduce a bug

1. Use the latest daily v9 dot net tool
2. Set DB context name in the efcpt-config json:
```
...
"names": {
  "dbcontext-name": "myEntities",
  "dbcontext-namespace": "DataModel",
  "model-namespace": "DataModel",
  "root-namespace": ""
},
...
```
3. Run scaffolding

### Provide technical details

- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu): efcpt.9 9.1.517+6c76d14ddf1b31fda782b9df6029989975583d10

- Exact Visual Studio version: Visual Studio 2022 17.11.4

- Database engine: SQL Server

- EF Core version in use: EF Core 9

- Is Handlebars templates used: no

- Is T4 templates used: no

- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
Thanks for reporting this issue with the daily build. You can revert the behaviour as described in the release notes.

**Comment by vytautasziurlis** [comment]
Sorry, did you mean this?

> Added support for proper naming of routines and routine results: UseDatabaseNamesForRoutines=false BREAKING - revert by setting to true +CLI #2623

**Comment by ErikEJ** [comment]
Yes

**Comment by vytautasziurlis** [comment]
I'm afraid that did not help, function db context still has incorrect name.
Just to clarify - the problem is not function names. It's the actual DbContext name.

**Comment by ErikEJ** [comment]
Why does your DbContext name start with lower case?

**Comment by ErikEJ** [comment]
@vytautasziurlis Fixed in latest nightly CLI build
