### ISSUE TITLE
EF Core Foreign Key Enum-to-Primitive Conversion Issue: "Cannot target primary key because it is not compatible"

### ISSUE THREAD

**Issue by yousafzainasir9** [ErikEJ/EFCorePowerTools#2645]
I have mapped field to following this. [video](https://www.youtube.com/watch?v=PUexkGWErNk)
entities generated now have enum mapping, but when I try to fetch, I get a runtime error.
basically, my enum field is a foreign key reference.

> The relationship from 'TempEntity.TempReferenceEntity' to 'TempReferenceEntity.TempEntities' with foreign key properties {'TempEnumID' : TempEnumType} cannot target the primary key {'TempEnumID' : short} because it is not compatible. Configure a principal key or a set of foreign key properties with compatible types for this relationship.

my enum is of type short **EvidenceTypeEnum**

also I am generating the conversion 

      modelBuilder.Entity<TempEntity>(entity =>
      {
          entity.Property(e => e.TempEnumID)
              .HasConversion<short>() // Converts enum to short
              .HasColumnType("smallint") // Matches the database type
              .IsRequired();
      
          entity.HasOne(d => d.TempReferenceEntity)
              .WithMany(p => p.TempEntities)
              .HasForeignKey(d => d.TempEnumID)
              .OnDelete(DeleteBehavior.ClientSetNull)
              .HasConstraintName("FK_TempEntity_TempReferenceEntity");
      });
 is the enum code 

    public enum TempEnumType : short
    {
        TypeA = 1,
        TypeB = 2,
        TypeC = 3
    }

    public class TempEntity
    {
        public int TempEntityID { get; set; } // Primary Key
        public TempEnumType TempEnumID { get; set; } // Foreign Key
        public virtual TempReferenceEntity TempReferenceEntity { get; set; } // Navigation Property
    }

    public class TempReferenceEntity
    {
        public short TempEnumID { get; set; } // Primary Key
        public string Name { get; set; }
        public virtual ICollection<TempEntity> TempEntities { get; set; } // Navigation Property
    }

**Comment by ErikEJ** [comment]
I assume the current solution does not work if the column if a foregin key

**Comment by ErikEJ** [comment]
I have updated the [docs here](https://github.com/ErikEJ/EFCorePowerTools/issues/1499)

**Comment by ErikEJ** [comment]
Great, and thanks for sharing.

If you like my free tools, I would be very grateful for a rating/review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) and/or a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
