### ISSUE TITLE
Change Solution & Reverse Engineer Uses Previous Database Connection

### ISSUE THREAD

**Issue by chrisclarkecloudappointmentsconz** [ErikEJ/EFCorePowerTools#2647]
We have various C# solutions running in Visual Studio 2022 and use Reverse Engineer in each of these.

I run Reverse Engineer in one solution and the 'Choose Database Connection' forms shows as;
![image](https://github.com/user-attachments/assets/f6d0161e-eb9d-412f-b320-86d20ea99ed1)

Which if fine and correlates with the value in efpt.config.json;
![image](https://github.com/user-attachments/assets/26af604b-e5f3-4090-94ec-7c57c0233caf)

I change the solution I'm working on to another, the efpt.config.json now shows as;
![image](https://github.com/user-attachments/assets/53a5f0fd-16c3-4f96-bfc3-32c2c616901f)

But when I run Reverse Engineer in this solution I get;
![image](https://github.com/user-attachments/assets/7f6ff45e-ed8d-4a24-8c09-7747965ef800)

Reverse Engineer is picking up the database connection from the last time it was run and not using the efpt.config.json value.

To get it to work in the new solution I have to Add the database connection again.
There's only one value in the Db Connections dropdown - the previously used one.

It's a UI bug that's frustrating and has caused errors - ran Reverse Engineer against the wrong database.

**Comment by ErikEJ** [comment]
I think you are looking in the wrong places - the extension lists connections from Server Explorer, and the name of these are stored in the UiHint property in the config file. (You are showing me something else, not sure what).

All Server Explorer connections are shared for the same VS edition on your Windows profile.

There is a general option under Tools/Options to NOT store a value in the UiHint property (always stored by default)

> To get it to work in the new solution I have to Add the database connection again.

**Comment by chrisclarkecloudappointmentsconz** [comment]
I can't find the UiHint property in Tools/Options, please can you enlighten me?

**Comment by ErikEJ** [comment]
@chrisclarkecloudappointmentsconz The UiHint property is in the `efpt.config.json.user` file. (sorry, forgot I was able to  remove from Tools/Options)

**Comment by ErikEJ** [comment]
I am going to close this, as there does not seem to be anything for me to do here - correct me if I am wrong.

If you like my free tools, I would be very grateful for a rating/review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) and/or a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by chrisclarkecloudappointmentsconz** [comment]
Fixed - defining the database connections in Server Explorer was the missing piece in the puzzle.
(I rarely use Server Explorer.)

Thank you for your help, please close the call.

**Comment by ErikEJ** [comment]
I could emit a warning if the UiHint conection cannot be found?

**Comment by chrisclarkecloudappointmentsconz** [comment]
I've not come across UiHint before so a warning about it would confuse me more.

It's not obvious (at least wasn't to me) that we had to define the database connections in Server Explorer.
That's the real issue - could the warning details this?

I only ever use Server Explorer to debug Stored Procedures (as they've dropped the debugger in SMSS).
All our database connections are always defined as ConnectionStrings in the appsettings.json file.

Hope this helps.

**Comment by ErikEJ** [comment]
You can use the Add connection button in the dialog to add a new connection, that will then be stored as a Server Explorer connection. This ensures that secrets are kept safe. 

Did you not discover the Add button, and if so, why not?

**Comment by ErikEJ** [comment]
https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering-Quick-Start

**Comment by ErikEJ** [comment]
Thinking more about this - if there is a UiHint and I cannot find it, I should not preselect the first item in the drop down!

**Comment by chrisclarkecloudappointmentsconz** [comment]
In reply to your two comments;
  1.  I had to use the delete then Add connection button when the database connection wasn't correctly assigned.
       This didn't add a Server Explorer connection.

  2.  Don't undertstand.

**Comment by ErikEJ** [comment]
> This didn't add a Server Explorer connection.

Oh yes, it did!

> Don't undertstand.

My proposed change will prevent the "wrong" connection from be selected in the drop down.

**Comment by ErikEJ** [comment]
And you should not use the Delete button first, just add the missing connection...

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

**Comment by ErikEJ** [comment]
@chrisclarkecloudappointmentsconz Use build .670 or later

**Comment by chrisclarkecloudappointmentsconz** [comment]
We tried compiling after using Reverse Engineer with this latest build and got numerous compiler errors.

They were caused by changed to the generated records for Stored Procedures;
  - There was a [column line for each field 
  - The field name had changed 
        - To mixed case
        - Underscores had been removed 

Errors were caused when the field name had changed.

We reverted back to version 2.6.632, ran Reverse Engineer and all compiled ok.

**Comment by ErikEJ** [comment]
@chrisclarkecloudappointmentsconz Yes, that is a breaking change in the latest daily as documented in the release notes. I will consider flipping the default value

If you like my free tools, I would be very grateful for a rating/review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) and/or a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
