### ISSUE TITLE
Reverse Engineering fails to discover Stored Procedure

### ISSUE THREAD

**Issue by BillDuffy** [ErikEJ/EFCorePowerTools#2662]
**This procedure within the Database got encoded properly in the last release. Now it does not. It is of note that the parameter "ClientID" was deprecated between my switching EF Revisions.**

```
CREATE PROCEDURE [dbo].[sp_ImpactTypeChoices]
	-- Required: Client_id
	-- @ClientID INT
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from interfering with SELECT statements.
	SET NOCOUNT ON;

	SELECT IT.name --'Impact Type'
			, ISEV.NAME --'Severity'
			, ISEV.description -- 'Severity Description'
			, ('Subcategory - ' + DMP.category) 'category' --AS 'Failure Probability'
			, DMP.name --'Failure Probability Description'
			, DSM.score --'Impact Score' 
			, DSM.deficiency_score_matrix_id 
	FROM impact_type IT 
		INNER JOIN impact_severity ISEV 
			ON IT.impact_type_id = ISEV.impact_type_id
		INNER JOIN deficiency_score_matrix DSM 
			ON ISEV.impact_severity_id = DSM.impact_severity_id
		INNER JOIN deficiency_mishap_probability DMP 
			ON DMP.deficiency_mishap_probability_id = DSM.deficiency_mishap_probability_id
	-- WHERE DSM.client_id = @ClientID   -- Filter on the client_id
	ORDER BY IT.name, ISEV.name, DMP.category  
END
```

**These are the installed EF Core Power ...**
![image](https://github.com/user-attachments/assets/c2f6e992-9faa-4b16-a63d-5a936ad9a63e)

**Comment by ErikEJ** [comment]
Could you please explain what is different/wrong?

**Comment by ErikEJ** [comment]
Have you tried "UseDatabaseNamesFor Routines" true ?

**Comment by BillDuffy** [comment]
Tried    and it changed the names of my output files, but did not correct this deficiency.

Here is my efpt.config.json :
```
 {
   "CodeGenerationMode": 5,
   "ContextClassName": "ParagonContext",
   "ContextNamespace": null,
   "FilterSchemas": false,
   "IncludeConnectionString": false,
   "ModelNamespace": null,
   "OutputContextPath": null,
   "OutputPath": "Models\/Database",
   "PreserveCasingWithRegex": true,
   "ProjectRootNamespace": "Paragon.DAL",
   "Schemas": null,
   "SelectedHandlebarsLanguage": 2,
   "SelectedToBeGenerated": 0,
   "T4TemplatePath": null,
   "Tables": [
      {
         "Name": "[dbo].[acm_condition]",
         "ObjectType": 0
      },
-- Lots of files
    {
         "Name": "[dbo].[sp_HierarchyTreeDataForUser]",
         "ObjectType": 1
      },
      {
         "Name": "[dbo].[sp_ImpactTypeChoices]",
         "ObjectType": 1
      },
      {
         "Name": "[dbo].[sp_SEC_Asset_id_List]",
         "ObjectType": 1
      },
-- Lots more files
      {
         "Name": "[dbo].[itvf_CodeUsage_ByClientID]",
         "ObjectType": 2
      }
   ],
   "UiHint": null,
   "UncountableWords": null,
   "UseAsyncStoredProcedureCalls": true,
   "UseBoolPropertiesWithoutDefaultSql": false,
   "UseDatabaseNames": false,
   "UseDatabaseNamesForRoutines": true,
   "UseDateOnlyTimeOnly": true,
   "UseDbContextSplitting": false,
   "UseDecimalDataAnnotationForSprocResult": true,
   "UseFluentApiOnly": false,
   "UseHandleBars": false,
   "UseHierarchyId": true,
   "UseInflector": true,
   "UseLegacyPluralizer": false,
   "UseManyToManyEntity": false,
   "UseNoDefaultConstructor": false,
   "UseNoNavigations": true,
   "UseNoObjectFilter": false,
   "UseNodaTime": false,
   "UseNullableReferences": true,
   "UsePrefixNavigationNaming": false,
   "UseSchemaFolders": false,
   "UseSchemaNamespaces": false,
   "UseSpatial": false,
   "UseT4": false,
   "UseT4Split": false
}
```

**Comment by ErikEJ** [comment]
What "deficiency" - you have not shared any C# code so far.

Please share runnable CREATE scripts that generates the issue and explain what the issue is, and I will have a look.

**Comment by BillDuffy** [comment]
This is the MS SQL CREATE SCRIPT
[sp_ImpactTypeChoices.txt](https://github.com/user-attachments/files/17923980/sp_ImpactTypeChoices.txt)

**Comment by ErikEJ** [comment]
I cannot run that script, as it refers to tables I do not have.  

Also, I still have no idea what the actual issue is...

**Comment by BillDuffy** [comment]
The issue is that EF Reverse Engineering failed to convert this file.
If you look in the resultant directory, there is no "Result" file shown.
And the .Procudures.cs doesn't have the function listed.

When I have time, I will make some scripts to create mock tables to satisfy the JOIN's.

**Comment by ErikEJ** [comment]
Ah - so nothing to do with naming, but the stored proc result cannot be discoveed?

Have you checked the Extensions output window for messages?

Have you tried switching to the alternate  dicsovery method for this stored procedure, as documented in the wiki?

```json
{
    "Name": "[dbo].[sp_ImpactTypeChoices]",
    "ObjectType": 1,
    "UseLegacyResultSetDiscovery": true
},

```
Odd that a change in EF Core Power Tools version makes this happen.

**Comment by BillDuffy** [comment]
The problem was discovered when I switched versions, however I'm beginning to think this was due to a DB change between passes of the EF RE (we are in initial development stages and the sands are shifting constantly).

I noticed within the SQL that there are 2 values which will decode as "Name", how does you code handle this? :
```
		, ISEV.NAME --'Severity'
		, DMP.name --'Failure Probability Description'
```

**Comment by ErikEJ** [comment]
Not well, please check the Extensions output window in VS for messages.

**Comment by BillDuffy** [comment]
You nailed it.
I will push-back on our SQL developer to fix the duplicate names.

Unable to scaffold PROCEDURE 'dbo.sp_ImpactTypeChoices' as it has duplicate result column names: 'name'.
