### ISSUE TITLE
Question about best way to copy a database schema

### ISSUE THREAD

**Issue by sam-wheat** [ErikEJ/EFCorePowerTools#2665]
We have a production database with many objects.  Only a few selected tables, views, and functions are of interest to us for some tests we need to do.  We want to create a new database on developer's local machine containing only the objects of interest.

We want to define one DbContext, an instance of which can be used to point to either production or the local database.

How can we use EFPT to accomplish this?

Done thus far:

We identified the tables, views, etc that we need using EFPT. EFPT creates a DbContext and models which work fine.

We tried use the the DbContext as the source of a migration, however the migration lacks the sql for the views and functions.

Is there some feature of EFPT, or perhaps some other tool, that we can use to get the sql for views and functions into the migration?

**Comment by ErikEJ** [comment]
Use a .dacpac instead, there is no support for views and functions other than hand crafted SQL with migrations.
