### ISSUE TITLE
Refresh or Edit views did not shown anymore with oracle 19c

### ISSUE THREAD

**Issue by Ptipoi-jf** [ErikEJ/EFCorePowerTools#2668]
### Provide steps to reproduce a bug

After updating the extension from 2.6.577 to 2.6.632, Refresh or Edit didn't work after validate the connection (infinite loading or look like infinite because it never end - more than hour versus 2min with the previous version). The next screen to select view to update will never appear.

There is a way to roll back to a previous version before the fix ? work fine with the 2.6.577

### Provide technical details

- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
2.6.632

- Exact Visual Studio version: (e.g. Visual Studio 2022 17.6.5)
Visual Studio 2022 17.12.1

- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)
Oracle 19c

- EF Core version in use: (e.g. EF Core 7)
EF Core 8

- Is Handlebars templates used: no/yes
No (idk what is it)

- Is T4 templates used: no/yes
Yes

- Is a SQL Server .dacpac used: no/yes
No

**Comment by ErikEJ** [comment]
@Ptipoi-jf I will revert to the previous provider in the latest daily, so you can see if that makes any difference

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

**Comment by Ptipoi-jf** [comment]
great, very thanks for the reactivity.

Your revert is working on the latest daily build (2.6.691)

for others, they need to stay on the previous version 2.6.577

Thanks !

**Comment by ErikEJ** [comment]
@Ptipoi-jf Others can use the daily build, will you make sure to report this to Oracle support. 

And I plan to release a new build to MarketPlace soon

**Comment by ErikEJ** [comment]
If you like my free tools, I would be very grateful for a rating/review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) and/or a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by Ptipoi-jf** [comment]
@ErikEJ did you know how to report this to oracle support ? Aren't you the most suitable person to make a ticket for this bug ?

**Comment by ErikEJ** [comment]
@Ptipoi-jf No, I am not an Oracle customer, I assume you are.

@alexkeh FYI!

**Comment by alexkeh** [comment]
What is the ODP.NET version that took two minutes to execute and the newer version that took an hour?

Can you share the SQL(s) and schema that caused this much longer execution time?

**Comment by Ptipoi-jf** [comment]
> What is the ODP.NET version that took two minutes to execute and the newer version that took an hour?
> 
> Can you share the SQL(s) and schema that caused this much longer execution time?

am i the recipient ?

i'm looking the diff (https://github.com/ErikEJ/EFCorePowerTools/pull/2670)
8.23.50 version is working fine (<1min loading)
8.23.60 version did not finish to load

I cannot share schema, it's too massive... many many tables (more than 1k), views, procedures, sequences,... and private database...

i'm trying to load as database first only few parts of the schema

**Comment by alexkeh** [comment]
@Ptipoi-jf 
It will be very difficult to resolve a performance problem without the schema and SQL that are causing it. Can your team open up an Oracle Support service request and share the information privately that way?

**Comment by ErikEJ** [comment]
@Ptipoi-jf Have you tried using the schema filter on the first dialog, it was created for scenarios like this
