### ISSUE TITLE
Remaining EF Core 3.0 rev engineer features

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#268]
Add missing EF Core 2 features:

- [x] Dacpac support
- [x] MySQL support
- [x] Custom renaming support
- [x] Test SQLite
- [x] Visualize keyless tables and views

**Comment by ErikEJ** [comment]
@jespersh Looks like MySQL provider is now RC - should I wait for RTM?

**Comment by jespersh** [comment]
I only just now noticed. 
Looking at https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/milestone/9 then it should be possible to use RC1.

Give me a poke if I should look into upgrading the packages. 
Will upgrading the packages prevent 2.x libraries from working?

**Comment by ErikEJ** [comment]
I will have a look at adding the RC provider. The EF Core 3 scaffolding runs completely out of process, so no conflict.

**Comment by ErikEJ** [comment]
@Herdo Do you have time to help, I need two additional text boxes with labels (below the 3 existing one) on this dialog - just need help with the XAML layout, I can do the viewModel /Databinding myself - TIA!


![efcreveng2](https://user-images.githubusercontent.com/4169187/66412214-63ac3400-e9f5-11e9-8630-176de90746ef.png)

**Comment by jespersh** [comment]
@ErikEJ https://github.com/ErikEJ/EFCorePowerTools/commit/8326d8f2d97d48798904c598c204633baa4c3b3a that's all you had to add? cool! Will look forward to testing.

**Comment by ErikEJ** [comment]
Yes, that's all. EF Core 3.0 reverse engineering is executed by a command line tool!

**Comment by Herdo** [comment]
@ErikEJ What should I use as upstream branch for this?
Want me to put the correct labels there? Whatever those are? 😄

**Comment by ErikEJ** [comment]
@herdo master - just add some dummy labels 😄

**Comment by ErikEJ** [comment]
And thanks :grateful:

**Comment by Alex-Torres** [comment]
What about null-able reference types? Is there a way to update the template engine to decorate class properties with ? if database fields are null?

**Comment by ErikEJ** [comment]
@Alex-Torres This issue is for feature parity with the EF Core 2 scaffolding.

If you have feature suggestions, please crate a new issue, with sample code that demonstrates the changes you are asking for.

**Comment by Alex-Torres** [comment]
I think I found a solution using by changing the scaffolding code to generate the POCO entities with "?".   There is an issue open on EFCore git repo here: (15520)https://github.com/aspnet/EntityFrameworkCore/issues/15520.
Thanks for the extension and everything you have done.

**Comment by doggy8088** [comment]
Hi @ErikEJ , does the daily build already support **Keyless Entity Types** for **Views**? I can't find this feature.

**Comment by ErikEJ** [comment]
@doggy8088 Yes, it support reverse engineering of views, yes

**Comment by doggy8088** [comment]
I found it. Thanks. :)
