### ISSUE TITLE
Reverse Engineered Function results missing column decimal attribute

### ISSUE THREAD

**Issue by BillDuffy** [ErikEJ/EFCorePowerTools#2682]
In the database I'm working with a Function ItvfClientCostCatalog is derived from the Table UniformatLevel, bringing over several of the columns. This is one of several similar cases.

In UniformatLevel the string columns are decorated with the [StringLength(xx)] attribute, and the decimal columns are decorated with the [Column("name", TypeName = "decimal(xx, x)"] attribute. 
e.g. (simplified for example)   
```
public partial class UniformatLevel
{
    [Column("name")]
    [StringLength(250)]
    public string Name { get; set; } = null!;

    [Column("UnitCost_Labor", TypeName = "decimal(18, 2)")]
    public decimal? UnitCostLabor { get; set; }
}
```

Examining the ItvfClientCostCatalog you can see that the columns have the appropriate properties Length (for StringLength) and Precision (for decimal(18,2)).
![image](https://github.com/user-attachments/assets/e0038b48-4ada-46e9-8ef8-57c6a44e427c)

![image](https://github.com/user-attachments/assets/6537bb3a-9b88-4c71-8e01-56a61adb7a21)

However, the EF Core Tools generated ItvfClientCostCatalogResult does not carry these attributes, as was done on the source table:
e.g. (simplified for example)
```
    public partial class ItvfClientCostCatalogResult
    {
        [Column("name")]
        public string Name { get; set; } = default!;
        [Column("UnitCost_Labor")]
        public decimal? UnitCostLabor { get; set; }
    }
```

Running the resultant code for ItvfClientCostCatalogResult results in Model.Validation warnings that the decimal precision has not been defined. Usages of UniformatLevel table do not generate these warnings.
```
warn: Microsoft.EntityFrameworkCore.Model.Validation[30000]
      No store type was specified for the decimal property 'UnitCostLabor' on entity type 'ItvfClientCostCatalogResult'. This will cause values to be silently truncated if they do not fit in the default precision and scale. Explicitly specify the SQL server column type that can accommodate all the values in 'OnModelCreating' using 'HasColumnType', specify precision and scale using 'HasPrecision', or configure a value converter using 'HasConversion'.
Microsoft.EntityFrameworkCore.Model.Validation: Warning: No store type was specified for the decimal property 'UnitCostLabor' on entity type 'ItvfClientCostCatalogResult'. This will cause values to be silently truncated if they do not fit in the default precision and scale. Explicitly specify the SQL server column type that can accommodate all the values in 'OnModelCreating' using 'HasColumnType', specify precision and scale using 'HasPrecision', or configure a value converter using 'HasConversion'.
```

Additionally, the lack of the StringLength attribute may present problems when code uses that to limit string lengths prior to sending them to the database.

**In general, I would like to see the Stored Procedures & Functions Reverse Engineering to have the same column attribute decorations as are done (most excellently) within the Table Reverse Engineering.**

Also of note, the proper default value for a non-nullable string is string.Empty (or ""), rather than null! or default!
Thus:
```
 public string  String1 { get; set; } = string.Empty;
 public string? String2 { get; set; } = null;
```

**Comment by ErikEJ** [comment]
It would be very nice with one issue per problem/issue you are raising so we can keep the discussion and resolution focused. 

For the decimal issue, you should be able to use UseDecimalDataAnnotationForSprocResult = true. Have you tried that?

I do not plan to put Unneeded attributes on the classes used for function and stored procedure mappings. 

For any other issues mentioned above, please create additional issues and provide all the requested information and reproduction code, thanks.

**Comment by BillDuffy** [comment]
"UseDecimalDataAnnotationForSprocResult": true,

 works for the Stored Procedures, but does not work for Functions.
The Function is where the warning messages are being generated.

Here is the definition of that function, as you can see, this returns a table result:

CREATE FUNCTION [dbo].[itvf_ClientCostCatalog] ***@***.***_ID INT)
RETURNS TABLE
AS
RETURN
(
      WITH
      CatalogType AS
      (     SELECT
                  is_uniformat_level_auto_update, -- 0: Full Custom / 1: Default or Hybrid
                  defaultCatalog_id                   -- If NULL or 0, no default catalog (so a full custom catalog)
            FROM client
            WHERE client_id = @Client_ID )

      SELECT UL.[code]
                  , UL.[uniformat_level_id]
                  , UL.[client_id]
                  , UL.[parent_uniformat_level_id]
                  , UL.[name]
                  , UL.[level_number]
                  , UL.[unit_of_measure_id]
                  , UL.[UnitCost_Labor]
                  , UL.[UnitCost_Material]
                  , UL.[UnitCost_Equipment]
                  , UL.UnitCost_TTL  -- Read-only
                  , UL.UnitCost_Demolition
                  , UL.[predicted_service_life]
                  , UL.predicted_service_life_replacement_percentage
                  , UL.update_date
                  , UL.isNoSelectionAllowed
                  , 1 as 'RowNbr'
            FROM uniformat_level AS UL
            WHERE (SELECT is_uniformat_level_auto_update from CatalogType) =0  -- Note this eliminates all results if catalog is Default/Hybrid
                        AND   UL.client_id = @Client_id --AND UL.a.ctive =1

      UNION ALL  -- While using UNION ALL, only 1 Select query is designed to return results

      SELECT *
            FROM (
                  SELECT UL.[code]
                  , UL.[uniformat_level_id]
                  , UL.[client_id]
                  , UL.[parent_uniformat_level_id]
                  , UL.[name]
                  , UL.[level_number]
                  , UL.[unit_of_measure_id]
                  , UL.[UnitCost_Labor]
                  , UL.[UnitCost_Material]
                  , UL.[UnitCost_Equipment]
                  , UL.UnitCost_TTL  -- Read-only
                  , UL.UnitCost_Demolition
                  , UL.[predicted_service_life]
                  , UL.predicted_service_life_replacement_percentage
                  , UL.update_date
                  , UL.isNoSelectionAllowed
                  , row_number() OVER (PARTITION BY CODE ORDER BY CODE ASC, UL.client_id DESC) as 'RowNbr'
                  FROM [dbo].[uniformat_level] AS UL
                  WHERE (SELECT is_uniformat_level_auto_update from CatalogType) =1  -- Note this eliminates all results if catalog is Full Custom
--                      AND   (UL.client_id = @Client_id OR UL.client_id I.S NULL) and UL.a.ctive =1
                        AND   (UL.client_id = @Client_id OR UL.client_id = ISNULL((SELECT defaultCatalog_id from CatalogType), 0))
                        --AND UL.a.ctive =1
                  ) ULOverride
            WHERE RowNbr=1  -- Ensure we get override Codes if they exist, for every other code use existing default

)


________________________________

**Comment by ErikEJ** [comment]
@BillDuffy Ah! Got it - please provide a runnable simplified repro and I will have a look (your function above refers to tables I do not have)

**Comment by ErikEJ** [comment]
@BillDuffy I have changed the title of this issue to: "Reverse Engineered Function results missing column decimal attribute"

**Comment by BillDuffy** [comment]
I believe this will suffice.

```
CREATE TABLE [dbo].[client] (
    [client_id]                         INT             IDENTITY (100, 1) NOT NULL,
    [is_uniformat_level_auto_update]    BIT,
    [defaultCatalog_id]                 INT             NULL,
);
```

```
CREATE TABLE [dbo].[uniformat_level] (
    [uniformat_level_id]                            INT             IDENTITY (100, 1) NOT NULL,
    [code]                                          NVARCHAR (50)   NOT NULL,
    [UnitCost_Labor]                                DECIMAL (18, 2) NULL,
    [UnitCost_Material]                             DECIMAL (18, 2) NULL,
    [UnitCost_Equipment]                            DECIMAL (18, 2) NULL,
    [client_id]                                     INT             NOT NULL,
);
```

```
CREATE FUNCTION [dbo].[itvf_ClientCostCatalog] (@Client_ID INT)
RETURNS TABLE
AS
RETURN
(
      WITH
      CatalogType AS
      (     SELECT
                  is_uniformat_level_auto_update, -- 0: Full Custom / 1: Default or Hybrid
                  defaultCatalog_id                   -- If NULL or 0, no default catalog (so a full custom catalog)
            FROM client
            WHERE client_id = @Client_ID )

      SELECT UL.[code]
                  , UL.[uniformat_level_id]
                  , UL.[client_id]
                  , UL.[UnitCost_Labor]
                  , UL.[UnitCost_Material]
                  , UL.[UnitCost_Equipment]
                  , 1 as 'RowNbr'
            FROM uniformat_level AS UL
            WHERE (SELECT is_uniformat_level_auto_update from CatalogType) =0  
                        AND   UL.client_id = @Client_id --AND UL.a.ctive =1

      UNION ALL  -- While using UNION ALL, only 1 Select query is designed to return results

      SELECT *
            FROM (
                  SELECT UL.[code]
                  , UL.[uniformat_level_id]
                  , UL.[client_id]
                  , UL.[UnitCost_Labor]
                  , UL.[UnitCost_Material]
                  , UL.[UnitCost_Equipment]
                  , row_number() OVER (PARTITION BY CODE ORDER BY CODE ASC, UL.client_id DESC) as 'RowNbr'
                  FROM [dbo].[uniformat_level] AS UL
                  WHERE (SELECT is_uniformat_level_auto_update from CatalogType) =1  
                        AND   (UL.client_id = @Client_id OR UL.client_id = ISNULL((SELECT defaultCatalog_id from CatalogType), 0))
                  ) ULOverride
            WHERE RowNbr=1  -- Ensure we get override Codes if they exist, for every other code use existing default

)
```

**Comment by ErikEJ** [comment]
@BillDuffy Thanks, I will have a look!

**Comment by ErikEJ** [comment]
@BillDuffy Thanks for reporting this bug.

I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.
