### ISSUE TITLE
EF Tools Reverse Engineering uses incorrect default for non-nullable strings.

### ISSUE THREAD

**Issue by BillDuffy** [ErikEJ/EFCorePowerTools#2683]
The proper default value for a non-nullable string is string.Empty (or ""), rather than null! or default!
If a blank record is created with a null in a non-nullable string and passed to the database, it causes an exception.

Thus:
```
 public string  String1 { get; set; } = string.Empty;
 public string? String2 { get; set; } = null;
```

**Comment by ErikEJ** [comment]
@BillDuffy Please share a runnable repro? Do you have #nullable enabled?

**Comment by BillDuffy** [comment]
This table:

```
CREATE TABLE [dbo].[uniformat_level] (
    [code]          NVARCHAR (50)   NOT NULL,
    [name]         NVARCHAR (250)  NOT NULL,
    [Comment]   NVARCHAR (100)  NULL,
);
```

Produces this code:

```
public partial class UniformatLevel
{
    [Column("code")]
    [StringLength(50)]
    public string Code { get; set; } = null!;

    [Column("name")]
    [StringLength(250)]
    public string Name { get; set; } = null!;

    [StringLength(100)]
    public string? Comment { get; set; }
}
```

**Comment by ErikEJ** [comment]
Please share the project file that contains the generated code - do you have nullable reference types enabled?

**Comment by BillDuffy** [comment]
Nullable is enabled.

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <SignAssembly>False</SignAssembly>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <DocumentationFile></DocumentationFile>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702,IDE0028;CS1591;CA1041</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>1701;1702,IDE0028;CS1591;CA1041</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.35" />
    <PackageReference Include="EfCore.SchemaCompare" Version="9.0.0" />
    <PackageReference Include="JetBrains.Annotations" Version="2024.3.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.HierarchyId" Version="9.0.0" />
    <PackageReference Include="Reinforced.Typings" Version="1.6.5" />
  </ItemGroup>

</Project>
```

**Comment by ErikEJ** [comment]
@BillDuffy No one else has ever brought this up, and I do not agree on your string.Empty assumption. 

You can create a constructor in a partial class that initializes the string.Empty value, or assign when you create a new instance.

**Comment by BillDuffy** [comment]
"You can create a constructor in a partial class that initializes the string.Empty value, or assign when you create a new instance."

I have done exactly that, to prevent the exceptions that will occur when assigning a null value to a database NOT NULL string. All you have to do is remove the "!" from the "`= null!;`" assignment and any code checker worth its salt will flag it as an error. You can use  `= "";`  if you wish.

**Comment by ErikEJ** [comment]
@BillDuffy Ok, that looks quite expected...

**Comment by ErikEJ** [comment]
@BillDuffy You can use a convention to set a default value for those properties, if you do not want to properly initialize new instances when you create them: https://learn.microsoft.com/en-us/ef/core/modeling/bulk-configuration#example-default-length-for-all-string-properties

**Comment by BillDuffy** [comment]
These non-null strings would be min_length=0, the max_length would vary by each defined field, I'm not sure how a convention would work. Can you provide me a working example?

**Comment by ErikEJ** [comment]
Set a default value, not the length. (The link is just an example)

**Comment by BillDuffy** [comment]
Since I already have some 60 classes within the database and I'm expecting another 100+, that is a whole lot of custome code for something that (IMO) is a programming error in the first place. 

Just remove the "!" from "`= null!;`" and this is what I see:
![image](https://github.com/user-attachments/assets/6e1acf22-ad9b-4093-9847-c2c2a564d5ff)

**Comment by ErikEJ** [comment]
You only add the 5 lines of convention in a single place !? 

If the null! concerns you, please discuss in the EF Core repo, it is not something I plan to change.
