### ISSUE TITLE
EF ore 7: rename from "data" in background to "datum"?

### ISSUE THREAD

**Issue by hagebu** [ErikEJ/EFCorePowerTools#2699]
I have created the following table
(using ms sql server)

`CREATE TABLE [plcbasedata]
   (
    [id_plcbasedata] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    [ts_plcbasedata] DATETIME NOT NULL DEFAULT (GETDATE()),
    [label_plcbasedata] NVARCHAR(64) NOT NULL,
    [description] NVARCHAR(128) NOT NULL,
    [variablename] NVARCHAR(128) NOT NULL,
    [url] NVARCHAR(128) NOT NULL,
    [accessdata] NVARCHAR(128) NULL
) ON [PRIMARY]`

The check on the SQL server was successful and as expected

`SELECT TOP (1000) [id_plcbasedata]
      ,[ts_plcbasedata]
      ,[label_plcbasedata]
      ,[description]
      ,[variablename]
      ,[url]
      ,[accessdata]
FROM [plcbasedata]`

The next step was to start the EF Power-Tool to read the database 
and create the required classes.
Microsoft Visual Studio Professional 2022 (64-Bit) - Current
Version 17.12.2

However, the result was surprising and not as expected.
(ef core 7)

The tablename **Plcbasedata** changed in c# to **Plcbasedatum**,
but the id_plcbasedata was correct translated to
IdPlcbasedata and not renamed to IdPlcbasedatum

`public partial class Plcbasedatum
{
    public int IdPlcbasedata { get; set; }

    public DateTime TsPlcbasedata { get; set; }

    public string LabelPlcbasedata { get; set; }

    public string Description { get; set; }

    public string Variablename { get; set; }

    public string Url { get; set; }

    public string Accessdata { get; set; }

}`

The result of the generated configurationfile 

`    public partial class PlcbasedatumConfiguration : IEntityTypeConfiguration<Plcbasedatum>
    {
        public void Configure(EntityTypeBuilder<Plcbasedatum> entity)
        {
            entity.HasKey(e => e.IdPlcbasedata).HasName("PK__plcbased__BE7509FD8FB560CB");

            entity.ToTable("plcbasedata");
......
`

The name really got lost in the DbContext

`public partial class SmtContext : DbContext
{
...

public virtual DbSet < Plcbasedatum > Plcbasedata { get; set; }
`

It seems that “data” is sometimes renamed to “datum”.

BTW:
Greetings from northern Germany to our neighbor in Denmark

**Comment by ErikEJ** [comment]
If you like my free tools, I would be very grateful for a rating/review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) and/or a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
