### ISSUE TITLE
Do you have code that creates a scaffolder that I can use in my EfSchemaCompare?

### ISSUE THREAD

**Issue by JonPSmith** [ErikEJ/EFCorePowerTools#270]
I'm trying to update all my libraries to NET Core 3/EF Core 3 and my [`EfCore.TestSupport`](https://github.com/JonPSmith/EfCore.TestSupport) has a feature I call EfSchemaCompare, which uses reverser engineering to compare a database to EF's `context.Model`.

I can't work out how to get an instance of the scaffolder to run in my code. I see you are also updating your code/tools to NET Core 3 and was trying to find what you did. I have found this code in [EFCoreReverseEngineer](https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/ReverseEngineer20/EFCoreReverseEngineer.cs) which looks useful.

```c#
            var serviceProvider = ServiceProviderBuilder.Build(reverseEngineerOptions);
            var scaffolder = serviceProvider.GetService<IReverseEngineerScaffolder>();
```

But when I go to the code behind `ServiceProviderBuilder.Build(reverseEngineerOptions);` it uses code that I don't find in EF Core 3.0, i.e. in my code the following types are shownas missing

```c#
var serviceCollection = new ServiceCollection();

serviceCollection
    .AddEntityFrameworkDesignTimeServices()
    .AddSingleton<IOperationReporter, OperationReporter>()
    .AddSingleton<IOperationReportHandler, OperationReportHandler>();
```

I expect its all buried in the different versions for supporting different standards/frameworks, but I can't figure it out. 

Any help would be appreciated!

**Comment by ErikEJ** [comment]
This works fine https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/efreveng/ReverseEngineer/ServiceProviderBuilder.cs 

Maybe your reference to Design has not been "fixed" :


      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="3.0.0" />

**Comment by JonPSmith** [comment]
Hi @ErikEJ,

I did have Microsoft.EntityFrameworkCore.Design, but I added it using " Manage NuGet packages" screen and that adds stuff that blocked the classes/interfaces I need (see below).

```
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="3.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
```

Once I knew it should work then I started looking, Thanks for your help.
