### ISSUE TITLE
Other names for the procedure result class name

### ISSUE THREAD

**Issue by UseMuse** [ErikEJ/EFCorePowerTools#2700]
2.6.698 (I don't know why the latest version is installed, I don't think I updated it, it probably updated itself)

Hello, from some point, when generating models and context, the result of the procedures began to generate a completely different name than before, and the configuration file did not change. How to return the old behavior?

Was c# class

p_GetViewModelResult

Now Was c# class

PGetViewModelResult

When
"UseDatabaseNames": true,
"UseDatabaseNamesForRoutines": true

The name of the procedure in the DB
p_GetViewModel

**Comment by UseMuse** [comment]
setting
"UseDatabaseNamesForRoutines": false

Solves the problem with the name and returns the class name as it was before
```c#
p_GetViewModelResult
```
But then another problem appears

Fields in p_GetViewModelResult start to have the PascalCase naming syntax, which also changes the original syntax of the field name

Was
```c#
public int ID {get;set;}
```
Becomes
```c#
public int Id {get;set;}
```
Expected result, I need the model of the resulting value of the procedure to be called like the procedure itself in the database with the Result postfix as it was p_GetViewModelResult and the fields there were named exactly as in the database
```c#
public int ID {get;set;}
```
For some reason this behavior has changed

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

**Comment by ErikEJ** [comment]
@UseMuse Make sure to set "UseDatabaseNamesForRoutines": true to maintain the old behavior

**Comment by UseMuse** [comment]
@ErikEJ within an hour

**Comment by UseMuse** [comment]
@ErikEJ it didn't help

**Comment by UseMuse** [comment]
I'll try to reinstall the extension

**Comment by UseMuse** [comment]
in case it matters, i use ef core 6

**Comment by UseMuse** [comment]
> I'll try to reinstall the extension

Reinstallation did not help

**Comment by ErikEJ** [comment]
Ah. EF Core 6 matters. I think this bug slipped through the crack when I dropped support for EF Core 6. 

EF Core 6 is out of support, but I will try to patch the current bits.

What happens if you choose EF Core 8?

**Comment by UseMuse** [comment]
> What happens if you choose EF Core 8?

There is no possibility


> I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

![image](https://github.com/user-attachments/assets/56d69409-d0e8-4588-a7ff-f0a540d4f7d8)

the problem persists, where can i get the lower version file to revert to the old behavior for core 6?

**Comment by ErikEJ** [comment]
You will have to wait for me to update the binaries for the now unsupported EF Core 6.

**Comment by UseMuse** [comment]
> You will have to wait for me to update the binaries for the now unsupported EF Core 6.

I'll wait, thank you.

**Comment by UseMuse** [comment]
> Or move to a supported version of EF Core 😎

This needs to be coordinated, it’s a long process, and I have to move the project forward.

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

**Comment by ErikEJ** [comment]
If you like my free tools, I would be very grateful for a rating/review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) and/or a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by ErikEJ** [comment]
Build .725 or later (on its way)

**Comment by UseMuse** [comment]
@ErikEJ Everything is working thanks
