### ISSUE TITLE
efpt.config.json file should Never CopyToOutputDirectory default

### ISSUE THREAD

**Issue by ahdung** [ErikEJ/EFCorePowerTools#2702]
### Provide steps to reproduce a bug

`efpt.config.json` file will Copy To Output Directory after compiled, I think it shouldn't copy.

### Provide technical details

- EF Core Power Tools version: 2.6.698

- Exact Visual Studio version: Visual Studio 2022 17.11.5

- Database engine: SQL Server

- EF Core version in use: EF Core 8

- Is Handlebars templates used: no

- Is T4 templates used: no

- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
@ahdung Why is this an issue for you?

**Comment by ErikEJ** [comment]
Actually, I do no see it being copied, and the properties look fine:

![image](https://github.com/user-attachments/assets/611038c0-a856-46b9-b9ce-7c4f8af2561a)

**Comment by ahdung** [comment]
@ErikEJ I tried console app, it's fine, same with yours, but in asp.net core webapi project, you will get:
Build Action: Content
Copy to Output Directory: PreserveNewest

**Comment by ErikEJ** [comment]
I think it is something you will have to address in the ASP.NET Core repo. Or manually change in your project file.

**Comment by ahdung** [comment]
I thought it's in your control, OK thx, I will.

**Comment by ErikEJ** [comment]
I could probably do something, but I am very reluctant to start special casing different project types.
