### ISSUE TITLE
Snowflake support

### ISSUE THREAD

**Issue by DanielL-SE** [ErikEJ/EFCorePowerTools#2704]
Is it possible to use EFCorePowerTools with a Snowflake DB? Maybe with [EFCore.Snowflake](https://github.com/Sielnix/EFCore.Snowflake)?

**Comment by ErikEJ** [comment]
Looks like the provider supports scaffolding  so yes, it could be implemented...

**Comment by ErikEJ** [comment]
@DanielL-SE Interested in doing a PR?

**Comment by DanielL-SE** [comment]
I'm not good as you but if I can do something to help you of course, without your extension my work would be a lot harder :)

**Comment by ErikEJ** [comment]
@DanielL-SE Well, I need a Snowflake user to test it - hoping you could help there?

**Comment by DanielL-SE** [comment]
@ErikEJ Absolutely yes!

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

If you like my free tools, I would be very grateful for a rating/review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) and/or a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by ErikEJ** [comment]
(Daily build in progress)

**Comment by ErikEJ** [comment]
Build .743 available now

**Comment by DanielL-SE** [comment]
My company Snowflake schema have a LOT of objects so it's taking hours to load... Is there any way to filter directly from the connection string based on table name or something like that?

**Comment by ErikEJ** [comment]
@DanielL-SE Any updates?

**Comment by DanielL-SE** [comment]
@ErikEJ It finished some minutes ago, normal table and views seems to work well, it doesn't get the "Functions" in particular "User Defined Function" but I think that is correct

**Comment by ErikEJ** [comment]
@DanielL-SE Correct, extra code is needed to support functions - and thanks for confirming
