### ISSUE TITLE
Default handling of Oracle NUMBER(1) field results in ORA-00904: invalid identifier error

### ISSUE THREAD

**Issue by Matthew--Townsend** [ErikEJ/EFCorePowerTools#2706]
### Reproduction steps

1. Start with an Oracle Database table with a NUMBER(1) column.
2. Use the Reverse Engineer option to generate a EFCore context
3. Have an EF LINQ query that checks the value of the generated NUMBER(1) --> bool column (e.g., entity.ColumnName == false)

Expected result: Generated SQL should use ."COLUMN_NAME" = 0 and work
Actually result: Generated SQL has "COLUMN_NAME" = False and gets this Oracle DB error: ORA-00904: "FALSE": invalid identifier

### Technical details:

- EF Core Power Tools version: 2.6.698
- Visual Studio version: Visual Studio Enterprise 2022 17.12.1
- Database : Oracle 19c
- Microsoft.EntityFrameworkCore: 8.0.11
- Oracle.EntityFrameworkCore: 8.23.60
- Oracle Developer Tools for Visual Studio 2022 version: 23.6.0.0
- Is Handlebars templates used: no
- Is T4 templates used: no
- Is a SQL Server .dacpac used: no

### More detailed steps on setting up EFCore Context (note pretty much all defaults)

1. Via Extension Manager, Install Oracle Deveoper Tools for Visual Studio 2022 (version 23.6.0.0)
2. Via Extension Manager, Install EF Core Power Tools (using version 2.6.698)
3. Via Nuget, install Microsoft.EntityFrameworkCore (version 8.0.11)
4. Via Nuget, install Microsoft.EntityFrameworkCore.Tools (version 8.0.11)
5. Via Nuget, insall Oracle.EntityFrameworkCore (version 8.23.60)
6. Setup Oracle Connection in Visual Studio:

   1.   Server Explorer --> Right click Data Connections --> Add Connection

        1.   Data Source: Oracle Database (ODP.NET, Managed Driver)
        2.   Connection Type: TNS Alias
        3.   TNS admin location: leave default
        4.   Data source name: nrtdev
        5.   Role: Non-Administrator
        6.   Username: your username
        7.   Password: your password

   2. Filters Tab, change display schemas to the schemas you want to use (always different than the user in our environment).
   

7. Right click on the project, select EF Core Power Tools --> Reverse Engineer
8. Pick the connection you just created, EF Core 8, Click the filters button
9. Add schemas from step 6.2 (and yes, casing matters), click OK
10. Click OK
11. Pick the tables you want on the next window, click ok
12. Set Namspace to the namespace you want
13. Set Entity Types path to the folder in which you want the generated classes

**Comment by ErikEJ** [comment]
@Matthew--Townsend Sorry, but this looks like a runtime error and should be addressed with Oracle support

**Comment by ErikEJ** [comment]
@alexkeh FYI

**Comment by alexkeh** [comment]
@ErikEJ It could also affect runtime, such as when values are used with the LINQ converted to SQL. The SQL will use TRUE and FALSE instead of 1 and 0.

**Comment by Matthew--Townsend** [comment]
options.UseOracleSQLCompatibility( OracleSQLCompatibility.DatabaseVersion19 ) fixed this.  Thank you for the advice!  I'm used to using Devart and everything just works.  I'm pretty sure that they detect the database version when you generate your context, so it handled it in the background.

**Comment by alexkeh** [comment]
@Matthew--Townsend DevArt is likely defaulting to the pre-23 version behavior. 

Unfortunately, there's no way for providers to retrieve the DB version on their own. We've confirmed this with the MS EF Core development team. Their recommendation is for provider writers, such as Oracle, to expose a way for the developer to tell the provider which DB version they are using. The provider will then adjust its SQL and feature use accordingly.

In NpgSQL, MS exposed the [SetPostgresVersion methods](https://www.npgsql.org/efcore/api/Npgsql.EntityFrameworkCore.PostgreSQL.Infrastructure.NpgsqlDbContextOptionsBuilder.html#Npgsql_EntityFrameworkCore_PostgreSQL_Infrastructure_NpgsqlDbContextOptionsBuilder_SetPostgresVersion_System_Int32_System_Int32_) for PostgreSQL. 

In SQL Server, [MS defaults to use the latest DB version](https://github.com/dotnet/efcore/issues/30163) promising not to use any "super-new feature" that would prevent backwards compatibility.
