### ISSUE TITLE
Oracle generated context is using null for index names on materialized views and getting Value cannot be null. (Parameter 'name') error.

### ISSUE THREAD

**Issue by Matthew--Townsend** [ErikEJ/EFCorePowerTools#2707]
### Reproduction steps

1. Start with an Oracle Database table with a materialized view into another oracle database (not sure if that level of detail is important)
2. Make sure that it has at least 2 indexes defined, which both have unique names
3. Use the Reverse Engineer option to generate a EFCore context
4. Run any EF query to get it to load the context.

Expected result: Context should load, validate, and execute the query.
Actually result: Generated code fails in Context.OnModelCreating(ModelBuilder modelBuilder) method.  It fails on any lines with .HasIndex on the materialized views (tables were fine)

Example Generated Code:
entity.HasIndex(e => new { e.EntityNameUpr, e.PerId, e.SeqNum }, null).IsUnique();
entity.HasIndex(e => new { e.PerId, e.NameTypeFlg, e.EntityName }, null);

Fixed code:
entity.HasIndex(e => new { e.EntityNameUpr, e.PerId, e.SeqNum }, "XM171S1").IsUnique();
entity.HasIndex(e => new { e.PerId, e.NameTypeFlg, e.EntityName }, "XM171S2");

### Technical details:

- EF Core Power Tools version: 2.6.698
- Visual Studio version: Visual Studio Enterprise 2022 17.12.1
- Database : Oracle 19c
- Microsoft.EntityFrameworkCore: 8.0.11
- Oracle.EntityFrameworkCore: 8.23.60
- Oracle Developer Tools for Visual Studio 2022 version: 23.6.0.0
- Is Handlebars templates used: no
- Is T4 templates used: no
- Is a SQL Server .dacpac used: no

### More detailed steps on setting up EFCore Context (note pretty much all defaults)

1. Via Extension Manager, Install Oracle Deveoper Tools for Visual Studio 2022 (version 23.6.0.0)
2. Via Extension Manager, Install EF Core Power Tools (using version 2.6.698)
3. Via Nuget, install Microsoft.EntityFrameworkCore (version 8.0.11)
5. Via Nuget, install Microsoft.EntityFrameworkCore.Tools (version 8.0.11)
6. Via Nuget, insall Oracle.EntityFrameworkCore (version 8.23.60)
7. Setup Oracle Connection in Visual Studio:

   1.   Server Explorer --> Right click Data Connections --> Add Connection

        1.   Data Source: Oracle Database (ODP.NET, Managed Driver)
        2.   Connection Type: TNS Alias
        3.   TNS admin location: leave default
        4.   Data source name: nrtdev
        5.   Role: Non-Administrator
        6.   Username: your username
        8.   Password: your password

   2. Filters Tab, change display schemas to the schemas you want to use (always different than the user in our environment).
   
7. Right click on the project, select EF Core Power Tools --> Reverse Engineer
9. Pick the connection you just created, EF Core 8, Click the filters button
10. Add schemas from step 6.2 (and yes, casing matters), click OK
11. Click OK
12. Pick the tables you want on the next window, click ok
13. Set Namspace to the namespace you want
14. Set Entity Types path to the folder in which you want the generated classes

**Comment by ErikEJ** [comment]
@Matthew--Townsend This looks like an issue with the database model generated by the Oracle provider and should be addressed with Oracle support

**Comment by ErikEJ** [comment]
@alexkeh FYI

**Comment by alexkeh** [comment]
@Matthew--Townsend This could be a new issue. I haven't seen this before, at least not based on the symptoms provided. Can you turn on EF Core tracing or ODP.NET tracing and share the trace?

**Comment by Matthew--Townsend** [comment]
I can't seem to get logging to output while running the "EFCore Power Tools --> Reverse Engineer" option.  Is there a wiki on enabling that specifically for EFCore Power Tools?  Everything I have found is for when the program is running.  I need to log before the program is even compiled, when the code is being generated.

**Comment by ErikEJ** [comment]
Have you checked the Extensions Output window?

**Comment by Matthew--Townsend** [comment]
Yes, Output --> Show Output from "Extensions" is completely empty.  I only even get the "Extensions" option if I disconnection from the oracle data connection so that it errors out on generation.  I'm guessing that I need to specify the log level to be more verbose somewhere, but can't find anything that tells me where.  I do have an appsettings.json file with the following, but I would expect that only to apply when running my application.

{
  "Logging": {
    "LogLevel": {
      "Default": "Trace",
      "Microsoft": "Trace",
      "Microsoft.EntityFrameworkCore.Database.Command": "Trace",
      "Microsoft.EntityFrameworkCore.Scaffolding": "Trace"
    }
  }
}

**Comment by Matthew--Townsend** [comment]
Ok, I'll give that a shot.  Thank you for confirming that I am not entirely crazy... :)

**Comment by Matthew--Townsend** [comment]
--verbose is not recognized.  

Here is what I did.  I set the option to use t4 templates.  Then enabled debugging.

In this (see below) part of the t4 template, index.Name has a value but index.GetDatabaseName() is null.  As a workaround for my use case I can just use the t4 templates and update the line with .GetDatabaseName() to have .Name instead.

this causes the generated context to have 

`entity.HasIndex(e` => new { e.PerId, e.AcctId, e.MainCustSw }, "XM150S1");`

instead of 

`entity.HasIndex(e` => new { e.PerId, e.AcctId, e.MainCustSw }, null);`

`foreach (var index in entityType.GetIndexes()
            .Where(i => !(Options.UseDataAnnotations && i.IsHandledByDataAnnotations(annotationCodeGenerator))))
        {
            if (anyEntityTypeConfiguration)
            {
                WriteLine("");
            }

            var indexFluentApiCalls = index.GetFluentApiCalls(annotationCodeGenerator);
            if (indexFluentApiCalls != null)
            {
                usings.AddRange(indexFluentApiCalls.GetRequiredUsings());
            }
#>
            entity.HasIndex(<#= code.Lambda(index.Properties, "e") #>, <#= code.Literal(index.GetDatabaseName()) #>)<#= code.Fragment(indexFluentApiCalls, indent: 4) #>;
<#
            anyEntityTypeConfiguration = true;
        }
`

from the immediate window in the debugger:
index.Name
"XM150S1"
index.GetDatabaseName()
null

**Comment by RickBogard** [comment]
I have a dbcontext for an oracle database where I am getting "null" for the index name on a materialized view table like you describe above.  I tried changing the DbContext.t4 template as you did, but I get an error

DbContext.t4(175,125) : error CS1955: Non-invocable member 'IReadOnlyIndex.Name' cannot be used like a method.

Any suggestions about how to resolve this issue?  Who maintains the T4 templates that are included in EFPT?  I don't know the syntax and have no success editing them or debugging them.

**Comment by ErikEJ** [comment]
This issue is closed and I am not providing free support for t4 programming issues.
