### ISSUE TITLE
Calculated column SQL Server - how not to allow the SET ...

### ISSUE THREAD

**Issue by vansree** [ErikEJ/EFCorePowerTools#2708]
Hi,

I have a SQL table with two sets of computed/calculated columns: The logic of calculated column can be embedded or using scalar function.

- One is a persisted column with some calculation logic. 
- The other is a non-persisted column that calculates age based on the birthdate column.

I don't want these columns to be set from C#. (only get is needed). Also, is there a setting that shows this is calculated column in C#. 

What setting in EFCorePowerTools should I use to achieve this?

Thanks

**Comment by ErikEJ** [comment]
@vansree Please share an example of such a table

**Comment by vansree** [comment]
Sure, I am taking examples from internet as it is easy to understand.

`
DROP Function dbo.fn_employee_promotion
DROP TABLE dbo.[Employee]

CREATE or alter FUNCTION dbo.fn_employee_promotion (@DOB DATE)
RETURNS DATE
AS
     BEGIN
         DECLARE @newdate DATE;
         SELECT @newdate = DATEADD(year, 60, @DOB)
         
         RETURN @newdate;
     END;
go

CREATE TABLE dbo.[Employee]
([EmpID]   [INT] NOT NULL, 
 [EmpSalutation] [VARCHAR](5) NULL,
 [EmpFirstName] [VARCHAR](50) NOT NULL,
 [EmpLastName] [VARCHAR](50) NOT NULL,
 [EmpName] as (IsNull([EmpSalutation] + ' ', '') + [EmpLastName] + ', ' + [EmpFirstName]) PERSISTED,
 [DOB]     [DATE] NOT NULL, 
 [Age] AS (DATEDIFF(yy, [DOB], GETDATE())), 
 [RetirementDate1] AS (DATEADD(year,60, [DOB])), 
 [RetirementDate2] AS dbo.fn_employee_promotion([DOB]), 

 CONSTRAINT [PK_Employee] PRIMARY KEY CLUSTERED([EmpID] ASC)
);
go
 

Insert into [dbo].[Employee] (EmpID,EmpSalutation, EmpFirstName, EmpLastName,DOB) values(1, 'Mr.', 'S', 'V','1987-01-01')
Insert into [dbo].[Employee] (EmpID,EmpSalutation, EmpFirstName, EmpLastName,DOB) values(2, 'Mr.', 'John', 'Doe','1985-06-07')
Insert into [dbo].[Employee] (EmpID,EmpSalutation, EmpFirstName, EmpLastName,DOB) values(3, 'Mrs.', 'Jane', 'Doe','1983-09-01')


SELECT * from dbo.Employee
`


Optional: For additional details, please refer to this links:
 
1. Table uses calculated value as persisted. 
https://www.mssqltips.com/sqlservertip/1682/using-computed-columns-in-sql-server-with-persisted-values/

Table: [dbo].[CCtest]
Column:  [DORetirement]

2. Tables uses calculated column (not-persisted)
https://dataedo.com/samples/redgate/lsrep17/User_databases/AdventureWorks/Tables/WorkOrder.html

Table:  [Production].[WorkOrder]
Calculated column: [StockedQty]

3. Table using the function.
https://www.sqlshack.com/an-overview-of-computed-columns-in-sql-server/
  
Requirements:
Requirement is to mark these columns as only get and not set (from C#). We dont want also manually adjusting the code either if possible or If there is a better way to handle this also, please advice and share the code.

Thanks for replying @ErikEJ

**Comment by ErikEJ** [comment]
Thanks, a t4 template where you do conditional processing if ComputedColumnSql is present for the entity seems a good solution to me.

**Comment by vansree** [comment]
Thanks @ErikEJ 

1) Is there any example on how to do it explicitly for this Computed Column SQL? Please kindly share. 

2) I upgraded my Visual Studio yesterday to 17.12.3 and Dot net framework. Do I need to upgrade the EF Core Power Tools? 

3) I tried using the power tools and t4 template and lost where to start and where to end.
![image](https://github.com/user-attachments/assets/092c13da-0684-40fb-a397-3108d6289cf8)

Tried editing EntityType.t4 as below:

`
        if (property.IsStoreGeneratedAlways) // Check for computed columns
        {
#>
    public <#= code.Reference(property.ClrType) #><#= needsNullable ? "?" : "" #> <#= property.Name #> { get; private set; }<#= needsInitializer ? " = null!;" : "" #>
<#
        }
        else
        {
#>
    public <#= code.Reference(property.ClrType) #><#= needsNullable ? "?" : "" #> <#= property.Name #> { get; set; }<#= needsInitializer ? " = null!;" : "" #>
<#
        }`

Any suggestions on acheiving it?

Regards

SV

**Comment by ErikEJ** [comment]
How did your attempt fail??

**Comment by vansree** [comment]
I am getting this error:

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.TextTemplatingModelGenerator.GenerateModel(IModel model, ModelCodeGenerationOptions options)
   at RevEng.Core.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions, Boolean removeNullableBoolDefaults, Boolean excludeNavigations, Boolean dbContextOnly, Boolean entitiesOnly, Boolean useSchemaFolders, Boolean useSchemaNamespaces) in D:\a\EFCorePowerTools\EFCorePowerTools\src\Core\RevEng.Core.60\ReverseEngineerScaffolder.cs:line 493
   at RevEng.Core.ReverseEngineerScaffolder.GenerateDbContext(ReverseEngineerCommandOptions options, List`1 schemas, String outputContextDir, String modelNamespace, String contextNamespace, String projectPath, String outputPath) in D:\a\EFCorePowerTools\EFCorePowerTools\src\Core\RevEng.Core.60\ReverseEngineerScaffolder.cs:line 94
   at RevEng.Core.ReverseEngineerRunner.GenerateFiles(ReverseEngineerCommandOptions options) in D:\a\EFCorePowerTools\EFCorePowerTools\src\Core\RevEng.Core.60\ReverseEngineerRunner.cs:line 86


Surprisingly I do NOT have D: drive

**Comment by ErikEJ** [comment]
That can be fixed, I will have a look sometime .

**Comment by vansree** [comment]
Thank you @ErikEJ .

With your experience, "Is my assumption correct that setting calculated columns as private set; or having no setter in T4 templates will meet my requirement? Or is there a better way? "

Basically, I want UI and EF Core to treat calculated columns as read-only and let SQL Server handle the logic for the calculated columns, whether it's persisted, using user-defined functions (UDFs), or built-in logic.

So, I was thinking as:
- The columns should be marked as read-only (get only) in C#.
- We want to avoid manually adjusting the code, if possible. We are OK to use your T4 Template suggestion but not using column names.
- Please provide any better approaches or share the relevant code.

Appreciate your help in advance.

Regards
SV

**Comment by ErikEJ** [comment]
I have no experience with this, but let's try to add a private set or no set via t4

**Comment by ErikEJ** [comment]
maybe try with 

`if (property.ValueGenerated == ValueGenerated.OnAddOrUpdate)`

**Comment by ErikEJ** [comment]
Going to close this, feel free to re-open if you are still facing issues.

**Comment by vansree** [comment]
@ErikEJ 

Thanks for your suggestion.

The moment I chose T4 and customize it, it is giving errors.

Step by step:
1) This works and no issues: I am using Visual Studio 2022 with EF Core Power Tools 2.6.698 and the project is ASP.NET Core Web App (Model-View-Controller).

![image](https://github.com/user-attachments/assets/d9547a07-0158-4e8e-ac60-39566ea4c55a)

2) Selecting T4 template option - This works!
![image](https://github.com/user-attachments/assets/507d710d-0442-4a4d-ab16-dda7829f95cb)

3) Customizing T4 template code - Errors!
    bool test = property.ValueGenerated;

It starts giving an error! 


`Some issues were discovered during reverse engineering, consider addressing them:

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.TextTemplatingModelGenerator.GenerateModel(IModel model, ModelCodeGenerationOptions options)
   at RevEng.Core.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions, Boolean removeNullableBoolDefaults, Boolean excludeNavigations, Boolean dbContextOnly, Boolean entitiesOnly, Boolean useSchemaFolders, Boolean useSchemaNamespaces) in D:\a\EFCorePowerTools\EFCorePowerTools\src\Core\RevEng.Core.80\ReverseEngineerScaffolder.cs:line 493
   at RevEng.Core.ReverseEngineerScaffolder.GenerateDbContext(ReverseEngineerCommandOptions options, List`1 schemas, String outputContextDir, String modelNamespace, String contextNamespace, String projectPath, String outputPath, String rootNameSpace) in D:\a\EFCorePowerTools\EFCorePowerTools\src\Core\RevEng.Core.80\ReverseEngineerScaffolder.cs:line 93
   at RevEng.Core.ReverseEngineerRunner.GenerateFiles(ReverseEngineerCommandOptions options) in D:\a\EFCorePowerTools\EFCorePowerTools\src\Core\RevEng.Core.80\ReverseEngineerRunner.cs:line 88

`

**Comment by ErikEJ** [comment]
It is an enum, not a boolean!

`bool test = property.ValueGenerated == ValueGenerated.OnAddOrUpdate;`

**Comment by vansree** [comment]
Same error. Please share if you have working template T4. 

For now, We decided to do manually change as we have only about 25 fields.

**Comment by ErikEJ** [comment]
This (alternative) approach works for me:

`var testIt = property.GetComputedColumnSql();`

**Comment by ErikEJ** [comment]
The path is from the build server, nothing to be concerned about

**Comment by vansree** [comment]
Awesome and thanks for the help @ErikEJ .

Much appreciated for your time.

**Comment by ErikEJ** [comment]
If you like my free tools, I would be very grateful for a rating/review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) and/or a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
