### ISSUE TITLE
Computed Column Reverse Engineering Problem

### ISSUE THREAD

**Issue by scorpion86** [ErikEJ/EFCorePowerTools#271]
There is two column on table which contains Name and Surname values which is not null. I have created a computed column using this two like this "Name + ' ' + Surname" .

When i try to reverse engineer with "Use DataAnnotation attributes to configure the model" option enabled it adds NameSurname property with Required attribute. 
Im trying to add a new record to table offcourse im not using computed column in createviewmodel. But ModelState.IsValid returns false because of the computed column. What should be the solution. Sould i set the value of computed column myself before ModelState.IsValid or is there any better solution. Thx.

### Further technical details
EF Core Power Tools version:2.2.63

Database engine: SQL Server 2014 Web Edition

Visual Studio version: Visual Studio 2019 16.3.2

**Comment by ErikEJ** [comment]
I do not recommend binding UI directly to the EF Core classes, but I think your suggested workaround is the best approach
