### ISSUE TITLE
Sticky Names for Ambiguous Foreign Keys

### ISSUE THREAD

**Issue by shadowfoxish** [ErikEJ/EFCorePowerTools#2710]
This is a sort of feature request/is there a better way, type issue.

Every so often, something about my project changes, maybe its a version of EFCorePowerTools, the targeting of which .NET framework/version, or the addition of a new column in a table, which causes a handful of reverse engineered navigation properties to change. Sometimes they change and I don't notice it, other times they change and break compilation. That's not really the problem though. I've learned to look out for these kind of gremlins with using the tool. What I'm wondering about is whether there's a better way to give "sticky" names of relationships to Navigational properties, perhaps by tagging index or foreign key names (or something along those lines).

In this particular case, I have a table (from a schema in an off-the-shelf product, I cannot control) which has multiple foreign keys to the same table. I have to make queries into it as part of my application, so here we are.

Here are some examples of how the names have changed periodically, and you can imagine this starts to get complicated or sometimes easy to miss.

Customer table
![image](https://github.com/user-attachments/assets/fb3dfb03-b9db-4352-ba73-7ceb89006db0)

OeHdr table
![image](https://github.com/user-attachments/assets/1f569436-bcde-4f89-95db-c361dc58adf6)

In the magenta here, I list out how I would kind of see the navigation property getting "Tagged" with a name I can set, which maybe is tied to the index's (constraint's) name. 
![image](https://github.com/user-attachments/assets/820f0b27-75f1-4a51-bf54-03dd3b100669)

I guess I'm wondering if this is worthwhile concept to build into the UI/config, or if it should just be a function of listing out a bunch of special cases in the t4 templates?

---------
- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
2.6.577

- Exact Visual Studio version: (e.g. Visual Studio 2022 17.6.5)
17.12.2

- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)
SQL Server 2016

- EF Core version in use: (e.g. EF Core 7)
EF 7, 8

- Is Handlebars templates used: no/yes
No

- Is T4 templates used: no/yes
Yes

- Is a SQL Server .dacpac used: no/yes
No

**Comment by ErikEJ** [comment]
Unless you switch the target EF Core version, and do not make schema changes, navigation names should stay the same. 

There was a change in EF Core 8, that you can revert with `"UsePrefixNavigationNaming": true,` 

Many attempts have been made to customize the navigation names with this tool, and they have all failed, so it is not something I plan to support/persue.

**Comment by ErikEJ** [comment]
Also notice that EF Core 7 is out of support

**Comment by shadowfoxish** [comment]
Thanks for the feedback. 

These in particular were composite foreign keys, which was interesting. The names in EF 7 were maybe worse than they are in EF 8, but either way they're all nonsense (thanks whoever created the database I'm forced to work with!). The problem persists.

I started digging into the templates as well, and it looks like most of the stuff is implemented in "do everything" methods `<#= code.Fragment(dataAnnotation) #>`, which seems to be dependent on the IModel instance, so there's really no way to get in the middle of that generation and do some simple name replacements. The other avenue I found was the IDesignTimeServices approach, which I found other issues in here and EFCore projects where that's a non starter. Initially it seemed like maybe I could define an IDesignTimeServices class in the t4, but the Model is already built by that point. I think I will just have to live with these names. 

One programmer had the idea of putting a summary comment on the data annotation of the FK name, which I think will be the next best thing. 
```
    /// <summary>
    /// FK: <#= navigation.ForeignKey["Relational:Name"] #>
    /// </summary>
```

![image](https://github.com/user-attachments/assets/6a354275-c531-4676-b4a0-b92e816c274d)

That's probably good enough for now.

**Comment by shadowfoxish** [comment]
I spent the morning with this, and I have a solution that works for my needs. I'll document what to do, maybe it will help someone or serve as some useful inspiration:

0) Caveats: I didnt know what "skipNavigations" were for so I didn't implement those, but its probably similar. This only updates the name of the Navigational property on the _foreign_ side of the relationship (that is, where the key is foreign and not principal), it can probably be extended fairly easily to work for both though.

1) Inside the CodeTemplates/EFCore folder, place the following file FkOverrides.ttinclude:
```csharp
<#@ import namespace="System.Collections.Generic" #>
<#@ import namespace="System.Linq" #>
<#@ import namespace="System.Text" #>
<#+
    public class ForeignKeyNameOverride {
        public string EntityTypeNameBeingCustomized { get; set; }
        public string DatabaseForeignKeyName { get; set; }
        public string DesiredNavigationName { get; set; }
    }

    //Make sure these are unique!
    public List<ForeignKeyNameOverride> FkOverrides = new List<ForeignKeyNameOverride> {
        /* example overrides; customize per your database needs */
        new ForeignKeyNameOverride() {
            EntityTypeNameBeingCustomized = "OeHdr",
            DatabaseForeignKeyName = "fk_oe_hdr_customer_architect_id",
            DesiredNavigationName = "CustomerArchitect"
        },
        new ForeignKeyNameOverride() {
            EntityTypeNameBeingCustomized = "OeHdr",
            DatabaseForeignKeyName = "fk_oe_hdr_customer_contractor_id",
            DesiredNavigationName = "ContractorCustomer"
        },
    };
    
    public string LookupOverrideName(string entityTypeName, string foreignKeyName, string defaultModelName) {
        var foundOverride = FkOverrides.FirstOrDefault(o => o.EntityTypeNameBeingCustomized == entityTypeName && o.DatabaseForeignKeyName == foreignKeyName);
        return foundOverride?.DesiredNavigationName ?? defaultModelName;
    }
#>
```

2) Add a reference to the ttinclude file in both DbContext.t4 and EntityType.t4:
```csharp
<#@ include file="FkOverrides.ttinclude" #>
```

3) Specific change to DbContext.t4:
Look for the for loop iterating the foreign keys. ```foreach (var foreignKey in entityType.GetForeignKeys())```
replace the "entity.HasOne..." line with this (the comments are optional, but can help you set up your overrides:
```csharp
            // [foreignKey.DependentToPrincipal.Name] <#= foreignKey.DependentToPrincipal.Name #> 
            // [foreignKey.PrincipalToDependent.Name] <#= foreignKey.PrincipalToDependent.Name #> 
            // [foreignKey["Relational:Name"]] <#= foreignKey["Relational:Name"].ToString() #> 
            // [entityType.Name] <#= entityType.Name #>
            entity.HasOne(d => d.<#= LookupOverrideName(entityType.Name, foreignKey["Relational:Name"].ToString(), foreignKey.DependentToPrincipal.Name) #>).<#= foreignKey.IsUnique ? "WithOne" : "WithMany" #>(<#= foreignKey.PrincipalToDependent != null ? $"p => p.{foreignKey.PrincipalToDependent.Name}" : "" #>)<#= code.Fragment(foreignKeyFluentApiCalls, indent: 4) #>;
```

4) Specific change to EntityType.t4:
Look for reference to ```navigation.Name```. There may be multiple.

Replace the ```<#= navigation.Name #>``` with:
```csharp
<#= LookupOverrideName(EntityType.Name, navigation.ForeignKey["Relational:Name"].ToString(), navigation.Name) #>
```

Optionally, add the diagnostic comments
```csharp
    /// <summary>
    // [navigation.Name] <#= navigation.Name #>
    // [navigation.ForeignKey.DependentToPrincipal.Name] <#= navigation.ForeignKey.DependentToPrincipal.Name #> 
    // [navigation.ForeignKey.PrincipalToDependent.Name] <#= navigation.ForeignKey.PrincipalToDependent.Name #> 
    // [navigation.ForeignKey["Relational:Name"].ToString()] <#= navigation.ForeignKey["Relational:Name"].ToString()#> 
    // [EntityType.Name] <#= EntityType.Name #>
    // [Annotations] 
    /* <#= navigation.ForeignKey.ToDebugString(Microsoft.EntityFrameworkCore.Infrastructure.MetadataDebugStringOptions.LongDefault, 0) #> */
    /// </summary>
```

My Results:
![image](https://github.com/user-attachments/assets/b88a9aad-c09b-41a8-99f6-67a86f3462f9)

![image](https://github.com/user-attachments/assets/e58937f5-62fb-4640-b3bf-2e4073818ec4)

**Comment by ErikEJ** [comment]
Beautiful - I will add a link to this from the umbrella T4 tips issue

**Comment by cbirch-bpb** [comment]
@shadowfoxish, you are a hero.
