### ISSUE TITLE
Procedures.cs no longer creating OnModelCreatingGeneratedProcedures

### ISSUE THREAD

**Issue by JayHonrath** [ErikEJ/EFCorePowerTools#2718]
Create a bug report, feature proposal, or ask a question.

NOTICE: **A bug report without sufficient technical and reproduction details and version information WILL BE CLOSED WITHOUT ANY FURTHER ACTION.**

### Provide steps to reproduce a bug

Recently upgraded our project from EF Core 9 to EF Core 9, and had to updae EFCorePowerTools to the latest.
Before, every time we Reverse Engineered, the following was created OnModelCreatingGeneratedProcedures, which included an entry for each Procedure, including .HasNoKey().ToView(null);

This no longer happens in the latest version of EFCorePowerTools.

Workaround was to create the following

  public partial class elitemovingContext : DbContext
    {
        partial void OnModelCreatingPartial(ModelBuilder modelBuilder)
       
And replicate all previous entries here, such as 

modelBuilder.Entity<GetWorkOrderImagesByWorkOrderIdResult>().HasNoKey().ToView(null);

For now this seems to be working, but if this is a bug in the new version of EF itself, maybe a future update will fix this.

### Provide technical details

- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)

- Exact Visual Studio version: (e.g. Visual Studio 2022 17.12.3)
- 17.12.3

- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)
- SQL Server

- EF Core version in use: (e.g. EF Core 9)
- EF Core 9

- Is Handlebars templates used: no/yes
- no

- Is T4 templates used: no/yes
- no

- Is a SQL Server .dacpac used: no/yes
- no

**Comment by ErikEJ** [comment]
You do not need it any more, if you run ED Core 8 ir later

**Comment by JayHonrath** [comment]
Thank you for the response.
Yes, I saw this same statement in some previous tickets with a similar issue.
However, when running our projects under EF Core 8, OR EF Core 9, we get the same runtime errors below. The only workaround we have found is to add the code in my above post.

System.InvalidOperationException: The entity type 'AppUserRoleSelectByAppUserIdResult' requires a primary key to be defined. If you intended to use a keyless entity type, call 'HasNoKey' in 'OnModelCreating'.

**Comment by ErikEJ** [comment]
@JayHonrath Which runtime version exactly? Please share a runnable repro and I will have a look

**Comment by ErikEJ** [comment]
I want the code generated by EF Core Power Tools to work out of the box, let me have a closer look.

**Comment by ErikEJ** [comment]
Have you tried 8.0.11 ?

**Comment by JayHonrath** [comment]
I have. Same issue. I have an old version of EFCorePowerTools that DOES generate OnModelCreatingGeneratedProcedures however it doesn't work with EF Core 9, only 8.
But yes even 8.0.11 has issues if OnModelCreatingGeneratedProcedures  isn't created. I just tested it.

**Comment by ErikEJ** [comment]
Old version of DbContextExtensions.cs could cause this.

**Comment by ErikEJ** [comment]
It must use SqlQuery  not FromSql

**Comment by JayHonrath** [comment]
public static async Task<List<T>> SqlQueryAsync<T>(this DbContext db, string sql, object[] parameters = null, CancellationToken cancellationToken = default)

This is currently in DbContextTextnsions.cs in my Core 9 version that is failing.

**Comment by ErikEJ** [comment]
@JayHonrath I am not able to reproduce (and if I was, 100s / 1000s of other users would be having the same issue):

This is my DbContextExtensions.cs file (partly)

```csharp
public static class DbContextExtensions
{
    public static async Task<List<T>> SqlQueryAsync<T>(this DbContext db, string sql, object[] parameters = null, CancellationToken cancellationToken = default)
       where T : class
    {
        if (parameters is null)
        {
            parameters = new object[] { };
        }

        if (typeof(T).GetProperties().Any())
        {
            return await db.Database
                .SqlQueryRaw<T>(sql, parameters)
                .ToListAsync(cancellationToken);
        }
        else
        {
            await db.Database.ExecuteSqlRawAsync(sql, parameters, cancellationToken);
            return default;
        }
    }
}

```

**Comment by JayHonrath** [comment]
That is identical to what I have. 
Alright. I will keep the workaround I have in for now. I will also try creating a new .Net 9 project and see if that helps anything out.
Thank you very much.

**Comment by ErikEJ** [comment]
```xml
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.11" />
  </ItemGroup>
```

**Comment by ErikEJ** [comment]
Personally, I will not recommend using EF Core 9 just now.

**Comment by JayHonrath** [comment]
Thank you so much for the information. I will let you know if anything sorts out with 8.0.11

**Comment by ErikEJ** [comment]
I am alos not abel to repro using 9.0.0 runtime

**Comment by JayHonrath** [comment]
Yes, and there were only 2 other bug submissions here with my same issue. So it's likely some odd edgecase. 
I will try a new project in 9 and let you know from there. We're still month from launch so I have time and see if any updates come out for 9. Thank you.

**Comment by SandroRiz** [comment]
I confirm I have this bug too with 2.6.820
Before to update the extension (I don't remember the version) I used .ef core 9.0.0 without problem

Now without the generation of HasNoKey and the call of OnModelCreatingGeneratedProcedures(modelBuilder); the application crashes at startup.

(same with Ef core 9.0.1)

workaround: correct after every generation Mydbcontext.cs and MydbContextProcedure.cs  (boring!)

![Image](https://github.com/user-attachments/assets/5f335af4-691c-415a-a4b2-ba40e6fbbd5a)
![Image](https://github.com/user-attachments/assets/48acb0bc-1564-4253-b9bd-d1a25d63909e)
![Image](https://github.com/user-attachments/assets/cb1af992-0419-43b2-8d0a-5ad077119866)

**Comment by ErikEJ** [comment]
Please provide a full runnable project, this was fixed by the EF Core team long time ago.

**Comment by ErikEJ** [comment]
@jayblackbean why did you remove your comment?
