### ISSUE TITLE
1. Create a new solution in VS 2022 v17.12.0 using the Console App Template (I don't think the template matters)

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#2722]
1. Create a new solution in VS 2022 v17.12.0 using the Console App Template (I don't think the template matters)
2. Right click the project in Solution Explorer, Select EF Core Power Tool and then Reverse Engineer
![image](https://github.com/user-attachments/assets/9f3e7fe3-6ad1-4cfa-aac7-4bcf555fd7c0)
3. Select Add, Add Database Connection
![image](https://github.com/user-attachments/assets/2138f0b7-8ba0-4371-bbdf-bc593c12f8a7)
4. Enter a server name and select a database
![image](https://github.com/user-attachments/assets/b373cde5-0afe-4403-a721-5ba0a0c15371)
5. Click Advanced... and set Multi Subnet Failover to True
![image](https://github.com/user-attachments/assets/ee40e9ac-b89e-4960-8f41-456d2947b974)
6. Click OK on the Advanced Properties Windows and the Connection Properties Window
7. Error message is displayed
![image](https://github.com/user-attachments/assets/54369416-a288-4620-aeed-6ddbc033f9ab)

If you skip step 5 is works, but may timeout connecting to the database depending on which IP comes back first from DNS. Starting from Server Explorer, right clicking Data Connections, clicking Add Connection... and then following steps 4-6 works without error and then can be used when reverse engineering a database with EF Core Power Tools
![image](https://github.com/user-attachments/assets/0f685500-ac0b-4525-a594-9987ca2107cb)

_Originally posted by @mikeholczer in https://github.com/ErikEJ/EFCorePowerTools/issues/1845#issuecomment-2536866482_

**Comment by ErikEJ** [comment]
@mikeholczer moved this to a new issue

**Comment by ErikEJ** [comment]
@mikeholczer  I think this works from Server Explorer as you are probably using another Datasource than Microsoft SqlClient (as seen in step 4)

**Comment by mikeholczer** [comment]
I'm using `Microsoft SQL Server (SqlClient)` in both cases. In fact, if I skip step 5 and save the connection made through the Reverse Engineer window, I can then go over to Server Explorer, select Modify Connection on it, do step 5 there without any other changes and then I'm able to save the connection and use it.

**Comment by ErikEJ** [comment]
Interesting! Thanks for the additional details

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

If you like my free tools, I would be very grateful for a rating/review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) and/or a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
