### ISSUE TITLE
Duplicate property names as a result of stored procedure

### ISSUE THREAD

**Issue by omccully** [ErikEJ/EFCorePowerTools#2727]
This is an ugly one, and I'm not sure how many of these edge cases we want to handle, but I figure I should report this. I'm using EFCPT on old database(s), so I've encountered several different edge case bugs that I've had to make my own workarounds for.

### Provide steps to reproduce a bug

Microsoft SQL Server stored procedure:

```sql
CREATE PROCEDURE GetExampleValues
AS
BEGIN
    SELECT 
        1.234 AS [Test ($$)], 
        5.123 AS [Test (%)]
END
```

Generates a Result class with duplicate properties "Test" with different Column attributes:

```csharp
[Column("Test ($$)")]
public double Test { get; set; }

[Column("Test (%)")]
public double Test { get; set; }
```

Proposed solution: have it detect duplicate property names, then attempt to resolve them using some basic rules. ex: if column name matches regex `\(?\$+\)?$`, add the "Dollars" suffix to the property name. Same with %, add "Percentage" as a suffix.

### Provide technical details

- EF Core Power Tools version: 9.1.624 CLI

- Exact Visual Studio version: 2022, 17.10.4

- Database engine: SQL Server

- EF Core version in use: EF Core 9

- Is Handlebars templates used: no

- Is T4 templates used: no

- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
Ouch! 😅

**Comment by ErikEJ** [comment]
Maybe just Test and Test1 ?

**Comment by ErikEJ** [comment]
Uniqify identifiers

**Comment by omccully** [comment]
> Maybe just Test and Test1 ?

As a last resort for getting it to compile, I think that would be okay. In my case, it's unlikely I will actually need to call this particular stored procedure any time soon.

Something like `Test_Duplicate1` and `Test_Duplicate2` would be better communicate to the person using the class that there are multiple with the same name. 

But if I did have to use this stored procedure, I wouldn't like to have to guess which is which when using the result. It would be easy to mix them up. Ideally, it should use whatever information it can to come up with a usable name for it.

**Comment by gbthakkar** [comment]
Hi,
I think, we should have practice to use underscore to join words in store
procedure itself, and not use simbol or special characters.

That is helpful even for other when using other ways of accessing data, may
be with dapper.

**Comment by ErikEJ** [comment]
> But if I did have to use this stored procedure, I wouldn't like to have to guess which is which when using the result.

You can inspect the [Column] attribute.

**Comment by ErikEJ** [comment]
sproc:

```sql
CREATE OR ALTER PROCEDURE NamingIsHard
AS
BEGIN
    SELECT 
        1.234 AS [Test ($$)], 
        5.123 AS [Test (%)],
        'Test Asdf' AS [#],
        'Test Asdf' AS [$#]
END
GO

```
after fix:


```csharp
    public partial class NamingIsHardResult
    {
        [Column("Test ($$)")]
        public decimal Test { get; set; }
        [Column("Test (%)")]
        public decimal Test_Duplicate0 { get; set; }
        [Column("#")]
        public string NumberSign { get; set; } = default!;
        [Column("$#")]
        public string DollarSignNumberSign { get; set; } = default!;
    }

```
