### ISSUE TITLE
Stored procedure result with invalid value names produces uncompilable code

### ISSUE THREAD

**Issue by omccully** [ErikEJ/EFCorePowerTools#2729]
### Provide steps to reproduce a bug

Unfortunately for us, SQL Server allows you to return a value with a column name with just "#". Unfortunately for me, I am working with a database where people have done this.

```sql
CREATE PROCEDURE GetExampleValues
AS
BEGIN
    SELECT 
        'Test Asdf' AS [#]
END
```

When scaffolded, it comes out as:

```csharp
[Column("#")]
public int # { get; set; }
```

This does not compile.

Suggestion: make it come up with a compilable property name for these kinds of column names. If "#", use "Number". If "$", use "Dollars", etc, as long as it does not conflict with another column with these names.

### Provide technical details

- EF Core Power Tools version: 9.1.624 CLI

- Exact Visual Studio version: 2022, 17.10.4

- Database engine: SQL Server

- EF Core version in use: EF Core 9

- Is Handlebars templates used: no

- Is T4 templates used: no

- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
Just wonderful! Thanks for the battle hardening proposals.

**Comment by ErikEJ** [comment]
Use https://learn.microsoft.com/en-us/dotnet/api/system.codedom.compiler.codedomprovider.isvalididentifier?view=windowsdesktop-9.0&viewFallbackFrom=dotnet-plat-ext-6.0 - but add more creativity

**Comment by gbthakkar** [comment]
Hi,
Please think of changing column alias in SP.

Even if you other methods of accessing database like ado.net or dapper, you
will realise that this awkward.

**Comment by ErikEJ** [comment]
@gbthakkar Changing the sp might not be possible!

**Comment by ErikEJ** [comment]
sproc:

```sql
CREATE OR ALTER PROCEDURE NamingIsHard
AS
BEGIN
    SELECT 
        1.234 AS [Test ($$)], 
        5.123 AS [Test (%)],
        'Test Asdf' AS [#],
        'Test Asdf' AS [$#]
END
GO

```
after fix:


```csharp
    public partial class NamingIsHardResult
    {
        [Column("Test ($$)")]
        public decimal Test { get; set; }
        [Column("Test (%)")]
        public decimal Test_Duplicate0 { get; set; }
        [Column("#")]
        public string NumberSign { get; set; } = default!;
        [Column("$#")]
        public string DollarSignNumberSign { get; set; } = default!;
    }

```

**Comment by ErikEJ** [comment]
If you like my free tools, I would be very grateful for a rating/review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) and/or a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.
