### ISSUE TITLE
Maintainability of TableInformationModel

### ISSUE THREAD

**Issue by Herdo** [ErikEJ/EFCorePowerTools#273]
I've seen that in the commit cc23919591acc6035981c5a1ed6a28898b655eab the class `TableInformationModel` was extended as follows:

```cs
/// <summary>
/// Gets or sets whether a key exists for the table/view or not.
/// </summary>
[IgnoreDataMember]
public bool HasKey
{
    get => _isKeyLess;
    set
    {
        if (value == _isKeyLess) return;
        _isKeyLess = value;
        OnPropertyChanged();
    }
}

[...]

public TableInformationModel(string name, bool hasPrimaryKey)
{
    [...]   
    HasKey = !hasPrimaryKey;
}
```

From a design and maintainability point of view, this looks like nobody will be able to understand why and how this property is called `HasKey`, while the backing field is called `_isKeyLess`.

Should the property probably be called `IsKeyLess`, and was just not renamed?

**Comment by Herdo** [comment]
@ErikEJ Further more, with the same commit selecting single tables was disabled? Is this a desired behavior?

**Comment by ErikEJ** [comment]
Work in progress, naming is hard. IsSelectable is probably a good name

**Comment by ErikEJ** [comment]
What do you mean by "selecting single tables was disabled" ?

**Comment by Herdo** [comment]
>  Work in progress, naming is hard. IsSelectable is probably a good name

Is this only for views?

**Comment by ErikEJ** [comment]
No. Also for keyless tables ( when using EF Core 2)

**Comment by Herdo** [comment]
> 
> 
> What do you mean by "selecting single tables was disabled" ?

![grafik](https://user-images.githubusercontent.com/651191/66432768-1fce2480-ea1f-11e9-910c-e1e5b03fb456.png)

The changes of https://github.com/ErikEJ/EFCorePowerTools/commit/cc23919591acc6035981c5a1ed6a28898b655eab#diff-371066cbe23060eb2dd9ddc30494c0c0 :
![grafik](https://user-images.githubusercontent.com/651191/66432904-6ae83780-ea1f-11e9-9ff1-76bd1f0ba415.png)

The checkbox there is now disabled, when a table has a primary key.

**Comment by ErikEJ** [comment]
And this is because there is only a single table in the list? That is a bug then!

**Comment by ErikEJ** [comment]
I think it works fine if there are multiple entries in the list...

**Comment by ErikEJ** [comment]
Fixed in latest daily build (I reverted these changes) - what I was trying to do was:

If we use EF Core 3.0 (includeViews = true) - for each table without a primary key, use the TableWarning.png and a related tooltip to inform the user that "this table or view does not have any keys"  - but everything is selectable!
