### ISSUE TITLE
Stored procedure with parameter named "System" creates uncompilable code

### ISSUE THREAD

**Issue by omccully** [ErikEJ/EFCorePowerTools#2730]
### Provide steps to reproduce a bug

Stored procedure with parameter named System:

```sql
CREATE PROCEDURE GetValuesBySystem
    @System NVARCHAR(50)
AS
BEGIN
    SELECT 
        @System AS SystemValue
END
```

After scaffolding, the ContextProcedures class does not compile because the name System conflicts with the System namespace.

### Provide technical details

- EF Core Power Tools version: 9.1.624 CLI

- Exact Visual Studio version: 2022, 17.10.4

- Database engine: SQL Server

- EF Core version in use: EF Core 9

- Is Handlebars templates used: no

- Is T4 templates used: no

- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
Looks like these issues could be combined to a single "bad resultset" issue...

**Comment by ErikEJ** [comment]
Use https://learn.microsoft.com/en-us/dotnet/api/system.codedom.compiler.codedomprovider.isvalididentifier?view=windowsdesktop-9.0&viewFallbackFrom=dotnet-plat-ext-6.0

**Comment by ErikEJ** [comment]
@omccully Exactly which line of generated code causes this issue?

**Comment by ePolSrl** [comment]
@ErikEJ this fix is a breaking change.

Instead of disabling capitalize for everyone, could this be handled with a parameter inside the efpt.config.json file?

In our case regenerating entities after this change broke several parts of our code.

**Comment by ErikEJ** [comment]
@ePolSrl Sorry, this was a bug, and I have no plans to allow it in future.
