### ISSUE TITLE
Update reverse engineered classes for legacy projects

### ISSUE THREAD

**Issue by JeffreyZolaVisibilEdi** [ErikEJ/EFCorePowerTools#2743]
I have a legacy .NET Framework V4.8 solution that uses both EntityFramework V6.2.0 & EntityFrameworkCore V3.1.14 (in a .NET Standard V2.0 project to allow it to be used in the .NET4.8 app). Each has a set of entity classes & a DbContext that needs to be updated to reflect database schema updates that have been made. 

I created the .NET Standard/Core 3.1 project several years ago using previous versions of the toolset. I don't recall or have documented the details of how I arrived at the efpt.config.json setup values.

This solution is slated to be retired in the next year, and we want to make changes that are absolutely required.

I am using EF Core Power Tools for VS V2.6.750 in an updated instance of VS2022, and tried to refresh the reverse engineering within the .NETStandard project without updating any of the configuration settings. The toolset is no longer able to refresh my entity classes as it used to. Looking at the history, the last time I generated updated anything with the tool was at the end of July, 2023.

Is the toolset not backward compatible for use with legacy .NETStandard/.NETCore 3.1 projects? 

The config file looks like this:

"CodeGenerationMode": 3,
 "ContextClassName": ....,
 "ContextNamespace": null,
 "DefaultDacpacSchema": null,
 "FilterSchemas": false,
 "IncludeConnectionString": false,
 "ModelNamespace": null,
 "OutputContextPath": null,
 "OutputPath": ....,
 "PreserveCasingWithRegex": true,
 "ProjectRootNamespace": ....,
 "Schemas": null,
 "SelectedHandlebarsLanguage": 0,
 "SelectedToBeGenerated": 0,
 "T4TemplatePath": null,
 "Tables": [ .... ],
 "UiHint": ....,
 "UncountableWords": null,
 "UseBoolPropertiesWithoutDefaultSql": false,
 "UseDatabaseNames": true,
 "UseDateOnlyTimeOnly": false,
 "UseDbContextSplitting": false,
 "UseFluentApiOnly": false,
 "UseHandleBars": true,
 "UseHierarchyId": false,
 "UseInflector": false,
 "UseLegacyPluralizer": false,
 "UseManyToManyEntity": false,
 "UseNoDefaultConstructor": false,
 "UseNoObjectFilter": false,
 "UseNodaTime": false,
 "UseNullableReferences": false,
 "UseSchemaFolders": false,
 "UseSchemaNamespaces": false,
 "UseSpatial": false,
 "UseT4": false

**Comment by ErikEJ** [comment]
@JeffreyZolaVisibilEdi 

> Is the toolset not backward compatible for use with legacy .NETStandard/.NETCore 3.1 projects?

Correct, I no longer provide free support for EF Core 3.1 which has been [out of support for two years now](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core)

In the archive branch you can find an old unsupported extension version in the tools folder that might help you.

If you like my free tools, I would be very grateful for a rating/review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) and/or a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
