### ISSUE TITLE
Warning About Missing Store Type for Decimal Properties

### ISSUE THREAD

**Issue by dsum27** [ErikEJ/EFCorePowerTools#2746]
### **Issue: Warning About Missing Store Type for Decimal Properties**

We are encountering frequent warnings like the following:

```
Microsoft.EntityFrameworkCore.Model.Validation: Warning: No store type was specified for the decimal property 'CodAmount' on entity type 'GetDropShipOrdersResult'. This will cause values to be silently truncated if they do not fit in the default precision and scale. Explicitly specify the SQL server column type that can accommodate all the values in 'OnModelCreating' using 'HasColumnType', specify precision and scale using 'HasPrecision', or configure a value converter using 'HasConversion'.
```

#### **Proposed Fix**
I have implemented a solution to address this issue by adding support for the `money` SQL column type in `RevEng.Core.Routines.Scaffolder`. The new code ensures that properties with `StoreType = "money"` are appropriately scaffolded with the `[Column(TypeName = "money")]` attribute when `useDecimalDataAnnotation` is enabled.

#### **Code Change**
```csharp
if (property.StoreType == "decimal" && useDecimalDataAnnotation)
{
    Sb.AppendLine($"[Column(\"{property.Name}\", TypeName = \"{property.StoreType}({property.Precision},{property.Scale})\")]");
}
else if (property.StoreType == "money" && useDecimalDataAnnotation)
{
    Sb.AppendLine($"[Column(\"{property.Name}\", TypeName = \"{property.StoreType}\")]");
}
else
{
    if (!string.IsNullOrEmpty(propertyNameAndAttribute.Item2))
    {
        Sb.AppendLine(propertyNameAndAttribute.Item2);
    }
}
```

#### **Request**
I would like to open a pull request to include this fix. It will enhance the scaffolding process by explicitly handling `money` types, reducing warnings and ensuring the generated models accurately reflect the database schema.

**Comment by ErikEJ** [comment]
This is fixed in the latest nightly/daily build
