### ISSUE TITLE
DateOnly

### ISSUE THREAD

**Issue by pcapozzi** [ErikEJ/EFCorePowerTools#2748]
Create a bug report, feature proposal, or ask a question.

NOTICE: **A bug report without sufficient technical and reproduction details and version information WILL BE CLOSED WITHOUT ANY FURTHER ACTION.**

### Provide steps to reproduce a bug

Now, when I do a reverse engineer I am getting a lot of DateOnly types.  Is there a way to control this.  This has not happened in the past.  I would like to stay with DateTime type

### Provide technical details

- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)

 2.6.750

- Exact Visual Studio version: (e.g. Visual Studio 2022 17.12.3)

2022 - 17.12.3

- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)

Sql server 2019

- EF Core version in use: (e.g. EF Core 9)

9

- Is Handlebars templates used: no/yes

not sure but I think no

- Is T4 templates used: no/yes

not sure but I think no

- Is a SQL Server .dacpac used: no/yes

not sure but I think no

**Comment by pcapozzi** [comment]
On further examination it seems that the fields in the database are marked as date.  Not sure where that came from.

**Comment by ErikEJ** [comment]
@pcapozzi You can adjust the DatOnly mapping as [described in the wiki](https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#mapping)

**Comment by ErikEJ** [comment]
@pcapozzi Ping?

**Comment by ErikEJ** [comment]
Yeah, that was a lot of work when you could just have checked a checkbox.
.

**Comment by pcapozzi** [comment]
Yes, I see that now but somehow missed the note to go to the advanced
options.
