### ISSUE TITLE
Reverse Engineer: How to turn off UseAsyncStoredProcedureCalls

### ISSUE THREAD

**Issue by parker1010** [ErikEJ/EFCorePowerTools#2749]
I have a question about a section from [this documentation](https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering).
It reads:

To generate synchronous procedures signatures, you can set this option:
"UseAsyncStoredProcedureCalls": false (not available in the CLI)

I'm wondering how to set this property to False when it's not available in the CLI, and I also don't see it available in Visual Studio. I want to use EFCorePowerTools, but if the resulting Stored Procedures are async, it would require a massive refactor of our codebase to make every method that calls a stored proc asynchornous.

- EF Core Power Tools version: 2.6.750
- Exact Visual Studio version: Visual Studio 2022 17.10.1
- Database engine: SQL Server
- EF Core version in use: N/A (.NET6.0)
- Is Handlebars templates used: Don't think so
- Is T4 templates used: no
- Is a SQL Server .dacpac used: Don't think so

**Comment by ErikEJ** [comment]
You can just edit the efpt.config.json file.

I have no plans to add synch support in the CLI

**Comment by parker1010** [comment]
I did not realize the efpt.config.json file contained that setting and could be edited directly. I don't plan to use the CLI. Thank you!

**Comment by ErikEJ** [comment]
You learned something new today!

If you like my free tools, I would be very grateful for a rating/review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) and/or a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
