### ISSUE TITLE
Reverse engineer EF Core 3 - enable Handlebars support 

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#275]
@tonysneed - what are your plans?

**Comment by tonysneed** [comment]
I plan to update to EF Core 3 in the next day or two.

**Comment by ErikEJ** [comment]
No pressure - but good news!

**Comment by tonysneed** [comment]
Done! https://www.nuget.org/packages/EntityFrameworkCore.Scaffolding.Handlebars/3.0.0

**Comment by ErikEJ** [comment]
Great! Are there changes to the templates?

**Comment by ErikEJ** [comment]
- I can see there are none.
