### ISSUE TITLE
 .ValueGeneratedOnAdd()

### ISSUE THREAD

**Issue by chandusekhar** [ErikEJ/EFCorePowerTools#2750]
Post oracle tables reverse engineer  .ValueGeneratedOnAdd() added to all the columns 

 entity.Property(e => e.Action)
     .HasMaxLength(50)
     .IsUnicode(false)
     .ValueGeneratedOnAdd()
     .HasColumnName("ACTION");
 entity.Property(e => e.Actionby)
     .HasMaxLength(50)
     .IsUnicode(false)
     .ValueGeneratedOnAdd()
     .HasColumnName("ACTIONBY");
 entity.Property(e => e.Actiondate)
     .HasPrecision(6)
     .ValueGeneratedOnAdd()
     .HasColumnName("ACTIONDATE");
 entity.Property(e => e.Activityname)
     .HasMaxLength(100)
     .IsUnicode(false)
     .ValueGeneratedOnAdd()
     .HasColumnName("ACTIVITYNAME");
 entity.Property(e => e.Drawingid)
     .HasMaxLength(50)
     .IsUnicode(false)
     .ValueGeneratedOnAdd()
     .HasColumnName("DRAWINGID");

**Comment by ErikEJ** [comment]
@chandusekhar This seems Oracle specific, please provide lot more details about your environment and address this with Oracle support - @alexkeh FYI

**Comment by chandusekhar** [comment]
Using Entity Framework 8 and Oracle 19, after reverse engineering tables .ValueGeneratedOnAdd()  added to all the columns in the tables. @ErikEJ . Thanks for the support and wonderful extension.

**Comment by alexkeh** [comment]
Which columns are not intended to use ValueGeneratedOnAdd()? Please share your table schema and reverse engineering logs to help me understand why ValueGeneratedOnAdd() gets added for each of those columns.

**Comment by chandusekhar** [comment]
CREATE TABLE TBLNWDESIGNREMARKHISTORY
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"DRAWINGID" VARCHAR2(50), 
	"DRAWINGTYPE" VARCHAR2(100), 
	"REMARKS" VARCHAR2(2048), 
	"PROCESSINSTANCEID" NUMBER, 
	"ACTIVITYNAME" VARCHAR2(100), 
	"ACTION" VARCHAR2(50), 
	"ACTIONBY" VARCHAR2(50), 
	"ACTIONDATE" TIMESTAMP (6), 
	"REASON" VARCHAR2(1024)
   )

**Comment by alexkeh** [comment]
I created the TBLNWDESIGNREMARKHISTORY table in my schema and used EF Core Power Tools 2.6.750 to reverse engineer for EF Core 8 with all default settings. I didn't see ValueGeneratedOnAdd() added to my properties. 

Can you provide the reproducible steps? If not, can you provide a trace in which we can see how the ValueGeneratedOnAdd() is added?

            entity.Property(e => e.Action)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("ACTION");
            entity.Property(e => e.Actionby)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("ACTIONBY");
            entity.Property(e => e.Actiondate)
                .HasPrecision(6)
                .HasColumnName("ACTIONDATE");
            entity.Property(e => e.Activityname)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("ACTIVITYNAME");
            entity.Property(e => e.Drawingid)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("DRAWINGID");
            entity.Property(e => e.Drawingtype)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("DRAWINGTYPE");
            entity.Property(e => e.Id)
                .HasColumnType("NUMBER(38)")
                .HasColumnName("ID");
            entity.Property(e => e.Processinstanceid)
                .HasColumnType("NUMBER")
                .HasColumnName("PROCESSINSTANCEID");
            entity.Property(e => e.Reason)
                .HasMaxLength(1024)
                .IsUnicode(false)
                .HasColumnName("REASON");
            entity.Property(e => e.Remarks)
                .HasMaxLength(2048)
                .IsUnicode(false)
                .HasColumnName("REMARKS");
