### ISSUE TITLE
Merge result set to single class? 

### ISSUE THREAD

**Issue by charanpasham** [ErikEJ/EFCorePowerTools#2756]
I have two database views, both returns the same object but have different logic in the view. Is there a way to merge the result of this object into a single class? 

` 

      modelBuilder.Entity<vw_ISFForm>(entity =>
      {
            entity
                .HasNoKey()
                .ToView("vw_form");

            entity.Property(e => e.CSS_Class).HasMaxLength(100);
            entity.Property(e => e.EnrollmentFormName).IsRequired();
            entity.Property(e => e.FormElementListName)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.GroupCSS_Class).HasMaxLength(100);
            entity.Property(e => e.GroupHTMLElementId).HasMaxLength(100);
        });

        modelBuilder.Entity<vw_ISFFormForPrinting>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vw_formWithDeletedRows");

            entity.Property(e => e.CSS_Class).HasMaxLength(100);
            entity.Property(e => e.EnrollmentFormName).IsRequired();
            entity.Property(e => e.FormElementListName)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.GroupCSS_Class).HasMaxLength(100);
            entity.Property(e => e.GroupHTMLElementId).HasMaxLength(100);
        });

`

**Comment by ErikEJ** [comment]
How would you differentiate calling one view versus the other??

**Comment by charanpasham** [comment]
Yeah, I don't think it is possible.  I can just execute a raw sql and map the models like this. 

`
var resultsFromView1 = await context.Set<FormResults>().FromSqlRaw("SELECT * FROM view1").ToListAsync();
var resultsFromView2 = await context.Set<FormResults>().FromSqlRaw("SELECT * FROM view2").ToListAsync();
`
