### ISSUE TITLE
is there a way to specify the output path for the stored procedures file ?

### ISSUE THREAD

**Issue by shikamu** [ErikEJ/EFCorePowerTools#2762]
### Provide steps to reproduce a bug

I have a solution in my asp .net core project, which uses entity framework and I'm using EFPT to reverse engineer the models of a sql server DB.

Until a recent update, the file which is created for the stored procedure was output at the same location as where the dbcontext is output, but now it seems to be output with the models.

My config looks like this:
```
{
   "CodeGenerationMode": 5,
   "ContextClassName": "BlablaDatabaseContextBase",
   "ContextNamespace": "Infrastructure.Common.Persistence",
   "FilterSchemas": false,
   "IncludeConnectionString": false,
   "ModelNamespace": "Domain.Models",
   "OutputContextPath": "..\\Blabla.Infrastructure\\Common\\Persistence\\",
   "OutputPath": "Models\\Team",
   "PreserveCasingWithRegex": true,
   "ProjectRootNamespace": "Blabla",
...
}
```

This is a bit problematic for me because I have several projects in the solution, the two of interest are Blabla.Models and Blabla.Infrastructure. Before that "update", the stored procedure file was going to the "Blabla.Infrastruture" project (hence following the OutputContextPath config variable) but now it seems to be following the "OutputPath", but the problem is that the stored procedure file relies on a type called OutputParameter which is automatically generated by EFPT in a file called DbContextExtensions, but this file is output to the "OutputContextPath", which in my case happens to be a different project from where "OutputPath" is generated, and this therefore feels a bit incoherent.

Is there a way to specficy where to store the stored procedure file ?

### Provide technical details

- EF Core Power Tools version: 2.6.750

- Exact Visual Studio version: Visual Studio 2022 17.12.0

- Database engine: SQL Server

- EF Core version in use: EF Core 9

- Is Handlebars templates used: no

- Is T4 templates used: no

- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
I am not aware of any 2.6.70 version of the tool. I only provide free support for the latest version, please install that

**Comment by ErikEJ** [comment]
Try to set the root namespace to null!

**Comment by ErikEJ** [comment]
Also, what do you mean by "stored procedure file" exactly??

**Comment by shikamu** [comment]
hi thanks for your replies!

sorry I'm using 2.6.750, the 5 got lost in translation ;)

setting the project root namespace to null does fix this issue, but then my models don't have the namespace I wish them to have :/

by "stored procedures file" I mean the file that the tool generates for the stored procedures that I chose to export.

```
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Domain.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Infrastructure.Common.Persistence
{
    public partial interface IBlablaDatabaseContextBaseProcedures
    {
        Task<int> Proc1Async(int? a, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetProNetworksForDisplayByDopIdResult>> Proc2Async(int? b, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
}
```

interestingly the implementation of that interface is generated where I want, it's just the interface that's "wrong".

anyway I guess this is it already because I changed the project root namespace to null, regenerated the models, and then reverted back to what it was, regenerated, and now the interface is generated where I wanted it to be.... I don't really understand what's happening here but it's working again...

**Comment by ErikEJ** [comment]
So you issue is solved?

**Comment by shikamu** [comment]
Yes, another one of these issues that solve themselves 😜

**Comment by ErikEJ** [comment]
If you like my free tools, I would be very grateful for a rating/review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) and/or a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
