### ISSUE TITLE
Problems in NET Core 3

### ISSUE THREAD

**Issue by sanmolhec** [ErikEJ/EFCorePowerTools#278]
Hi.

1) Generating the context diagram gives the error: "Currently only .NET Framewrok and .NET Core 2.0 projects are supported - TargetFrameworkMoniker: .NETCoreAPP, Version=v3.0"

[https://ibb.co/3F5Cprg](url)

Right-clicking on the project, in EF Core Power Tools, Add DbContext Model Diagram, displays the error described above.

2) In addition, it does not implement the AsDgml method in the context. It is marked as unknown. 

Following the steps to complete the example of this url: https://gist.github.com/redwards510/a26276218be2b9d104e5e590ebed5b92

[https://ibb.co/LrSXs98](url)

Within the controller that would generate and return the class diagram, the AsDgml() method is not recognized.

API type project with .NET Core 3.0.

As I understood in the wiki and in the issues the extension was already operative for Core 3.0.

EF Core Power Tools version: 1.0

Database engine: SQL Server or PostgreSQL

Visual Studio version: Visual Studio 2019 16.3.2

Thanks a lot.

Regards, Héctor.

**Comment by ErikEJ** [comment]
You need the latest daily build! And the AsDgml package has not been updated yet.

**Comment by sanmolhec** [comment]
> You need the latest daily build! And the AsDgml package has not been updated yet.

Okay, I'll try to update the packages later or on Monday and try again.

Thank you for the answer and thank you very much for the speed.

Greetings, Héctor.

**Comment by ErikEJ** [comment]
I have just released an update of the Dgml builder package
