### ISSUE TITLE
View Database Schema as Graph

### ISSUE THREAD

**Issue by emouawad** [ErikEJ/EFCorePowerTools#282]
Describe what is not working as expected.

`System.NullReferenceException: Object reference not set to an instance of an object.
   at EFCorePowerTools.Handlers.ServerDgmlHandler.GenerateServerDgmlFiles() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ServerDgmlHandler.cs:line 73`

### Steps to reproduce
Include a complete description that I can redo to reproduce the issue.
dotnet core 3.0
View Database Schema as Graph

### Further technical details
EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)

Database engine: (SQlite, SQL Compact, SQL Server, Postgres)
MySql

Visual Studio version: (e.g. Visual Studio 2017 15.7)
Visual Studio 2019 - 16.3.2

**Comment by ErikEJ** [comment]
Which extension version?

**Comment by emouawad** [comment]
It's version 2.3.63

**Comment by ErikEJ** [comment]
This feature is not supported with MySQL, sorry (I have added a check to inform the user)

**Comment by emouawad** [comment]
oh ok thanks
