### ISSUE TITLE
core 3.0 not supported?

### ISSUE THREAD

**Issue by ranjithkumarkakkarayil** [ErikEJ/EFCorePowerTools#283]
I'm getting below error

<img width="438" alt="Screen Shot 2019-10-11 at 2 38 53 PM" src="https://user-images.githubusercontent.com/15210504/66686651-f981d200-ec34-11e9-81cb-d641452f0bd9.png">

is .net core 3.0 not supported ?

**Comment by ErikEJ** [comment]
Yes, it is supported 

Which version of the tool?

Please share your csproj file.

**Comment by ranjithkumarkakkarayil** [comment]
Hi Erik,

PFB

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EntityFramework" Version="6.3.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.Design" Version="1.1.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="3.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.0.0" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Models\" />
  </ItemGroup>
  
  

</Project>

**Comment by ranjithkumarkakkarayil** [comment]
`<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EntityFramework" Version="6.3.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.Design" Version="1.1.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="3.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.0.0" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Models\" />
  </ItemGroup>
  
  

</Project>
`

**Comment by ranjithkumarkakkarayil** [comment]
[csprojfile.txt](https://github.com/ErikEJ/EFCorePowerTools/files/3719731/csprojfile.txt)

**Comment by ErikEJ** [comment]
Looks fine - you should remove the version 1 and 2 references - but are you using the latest daily build of the Power Tools?

**Comment by ranjithkumarkakkarayil** [comment]
Hi,

Yes. will check it now.

version installed : 2.2.63

**Comment by ranjithkumarkakkarayil** [comment]
tried removing the reference..
am using macbook. will that be of any problem?

**Comment by ErikEJ** [comment]
You need the latest daily build for .net Core 3 support.
