### ISSUE TITLE
Suffix for class generated in "Reverse Engineer"

### ISSUE THREAD

**Issue by Kris-I** [ErikEJ/EFCorePowerTools#284]
Hello,

I don't see any way to add a custom suffix to generated classes. In the database there is a table named "Customer" I'd like "CustomerEntity".

Is it possible to add this ?

Thanks,

**Comment by ErikEJ** [comment]
You can use the renaming feature: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#custom-renaming-with-epftrenamingjson

**Comment by Kris-I** [comment]
Ok but I have to define ALL tables one by one in this file :( It's new project then I'd like do it all at once.

**Comment by ErikEJ** [comment]
You could automate the process of creating the renaming file, as mentioned in the documentation.
