### ISSUE TITLE
Add support for IBM IDS(Informix Data Servers 11.5 and late) 

### ISSUE THREAD

**Issue by iliev72** [ErikEJ/EFCorePowerTools#285]
It's possible to add support for Informix Server 11.5 and late version ?!

**Comment by ErikEJ** [comment]
Potentially, see https://github.com/ErikEJ/EFCorePowerTools/issues/17 for requirements

**Comment by jespersh** [comment]
Anyone who wants to have fun with it, see to get the DDEX part installed: https://stackoverflow.com/questions/33328429/how-to-find-informix-datasource-in-visual-studio-to-connect-to

Looks complicated and licensed although a trial is available.

**Comment by ErikEJ** [comment]
Is there an Informix EF Core provider??

**Comment by iliev72** [comment]
yes :)
https://www.ibm.com/developerworks/community/forums/html/topic?id=18f76739-2637-466f-ae43-2558ca93db94&ps=100

**Comment by ErikEJ** [comment]
Duplicate of #288
