### ISSUE TITLE
VS 2017 error message - EFCorePowerToolsPackage not loaded correctly

### ISSUE THREAD

**Issue by MrNoswad** [ErikEJ/EFCorePowerTools#286]
Describe what is not working as expected.

### Steps to reproduce
Windows 7
Start VS 2017 -> Tools -> Extensions & Updates -> Installed -> Tools -> Online -> Type EF in search box -> Select  EF Core Power Tools -> click Download button ->
Your changes will be scheduled. The modifications will begin when all Microsoft Visual Studio Windows are closed. -> Exit VS 2017

VSIX Installer Opens -> Modify -> Attached Install Log Shows Successful install

Start VS 2017 -> Message Window says: EFCorePowerToolsPackage did not load correctly.
See attached screen shot. See attached error description entry extracted from ActivityLog.xml. 
[20191013 Install Log - EF Core Power Tools Successful.log](https://github.com/ErikEJ/EFCorePowerTools/files/3725553/20191013.Install.Log.-.EF.Core.Power.Tools.Successful.log)

### Further technical details
EF Core Power Tools version: 2.2.63
Database engine: I don't think any db is installed yet. 
Visual Studio version: Community 2017 Version 15.9.16
VisualStudio.15.Release/15.9.16+28307.858
Microsoft .NET Framework Version 4.7.02053

![EFCorePowerToolsPackage Error Screenshot](https://user-images.githubusercontent.com/56556490/66769766-ee70b100-ee83-11e9-9cf7-7bfe47fcb9ce.png)

[ActivityLog_xml error description.txt](https://github.com/ErikEJ/EFCorePowerTools/files/3725602/ActivityLog_xml.error.description.txt)

**Comment by ErikEJ** [comment]
Try to install .NET Framework 4.7.2 or 4.8

**Comment by ErikEJ** [comment]
ping?

**Comment by ErikEJ** [comment]
Closing as no follow up info was provided
