### ISSUE TITLE
Add support for more  database types

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#288]
See #17 for changes involved
 see https://github.com/ErikEJ/EFCorePowerTools/pull/182/files

**Comment by ErikEJ** [comment]
Oracle components are now available:

https://www.oracle.com/database/technologies/dotnet-odtvsix-vs2019-downloads.html 

https://www.nuget.org/packages/Oracle.ManagedDataAccess/

**Comment by ErikEJ** [comment]
Both need VS tooling

**Comment by MagicAndre1981** [comment]
> Both need VS tooling

as mentioned, [firebird has DDEX](https://www.tabsoverspaces.com/233604-installing-ddex-provider-for-firebird-into-visual-studio-2017), but install is a bit complicated

**Comment by ErikEJ** [comment]
A bit 😁

**Comment by ErikEJ** [comment]
One way to unblock: Stop using only DDEX providers:

Use DbConnectionStringBuilder (like in SQL CE Toolbox with SQLite) and credentials manager instead.

Needs remove feature as well.

This would lower the barrier for additional providers.

Potentially support both scenarios.

Credential manager C#: https://www.meziantou.net/how-to-store-a-password-on-windows.htm#uwp-application-or-d

**Comment by ErikEJ** [comment]
One way to unblock: Stop using only DDEX providers:

Simply allow free form text entry

And selection of provider type

Initially just make it ad-hoc!

**Comment by ErikEJ** [comment]
@MagicAndre1981 @sm15455 Thanks for the thumbs up!
I have now implemented this for SQLite (to avoid the pain of the SQLite GAC install).
Any providers on your list?

**Comment by MagicAndre1981** [comment]
> Any providers on your list?

Firebird would be nice. I hope that provider version 8, [which supports .net 5 EF Core](http://tracker.firebirdsql.org/browse/DNET-975), will be out in next weeks and so FB support would be nice

**Comment by ErikEJ** [comment]
@MagicAndre1981 are you able to help with testing?

**Comment by MagicAndre1981** [comment]
currently I have no EFCore experience as I still use EF6, but I could play a bit with it.

**Comment by ErikEJ** [comment]
@MagicAndre1981 Without assistance from a Firebird "expert", I am stuck..

@cincuranet ?

**Comment by MagicAndre1981** [comment]
cincuranet is the person for Firebird .net questions, so ask him

**Comment by cincuranet** [comment]
What do you need from me, @erikej?

**Comment by ErikEJ** [comment]
@cincuranet Once I have implemented support, would be great that you could confirm that reverse engineering against a sample database works as expected...

**Comment by cincuranet** [comment]
Sure. No problem.

**Comment by MagicAndre1981** [comment]
ok, the classes are generated from reverse engineer function. After I added the override of `OnConfiguring` and Called UseFirebird I can query data in .Net5 project with EFCore 5 and FB provider 8 beta.

Now I have to play with your extension to see how I can use it (I stopped playing with it when I saw missing FB support). In EF6 I used EDMX, imported the model from DB, customized the names of classes, keys, nav prop etc in the EDMX and next a T4 script to generate context + classes + mapping with Fluent API + overrides in 2nd partial class file.

**Comment by ErikEJ** [comment]
@MagicAndre1981 :

>> After I added the override of OnConfiguring and Called UseFirebird 

That is not necessary:

![image](https://user-images.githubusercontent.com/4169187/112936062-5ae97980-9125-11eb-803d-85c99a1c6bab.png)

Have a look at the wiki and my demo videos!

**Comment by MagicAndre1981** [comment]
> ![image](https://user-images.githubusercontent.com/4169187/112936062-5ae97980-9125-11eb-803d-85c99a1c6bab.png)
> 
> Have a look at the wiki and my demo videos!

ok, I'll watch the video and play a bit with it. Does this add the override of OnConfiguring?

**Comment by ErikEJ** [comment]
Yes

**Comment by MagicAndre1981** [comment]
> Yes

ok, so maybe change the text to reflect this.

**Comment by ErikEJ** [comment]
The preferred pattern is to create a Options builder, and construct the DbContext with that.

**Comment by ErikEJ** [comment]
Closing this as the new ad hoc dialog is now available.
