### ISSUE TITLE
Update Reverse Engineering wiki page

### ISSUE THREAD

**Issue by jespersh** [ErikEJ/EFCorePowerTools#290]
Looked at https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering as I just noticed the new dialog:
![image](https://user-images.githubusercontent.com/1004198/66991931-3a606780-f0c9-11e9-9adc-b246849871c7.png)

And I got a bit overwhelmed by all the options to be honest.

I think some screenshots of Solution Explorer with all the different options could help people (me) in the wiki.
My solution has a ***.Persistence project with DbContext and a ***.Domain project with entities. So I couldn't figure out this full control thing just by looking at it https://github.com/ErikEJ/EFCorePowerTools/issues/197#issuecomment-541343285

**Comment by ErikEJ** [comment]
Agree, this is something I need to do!

If you could make a screenshot / text description of your folder layout, I can try to help (and get the first entry in the wiki update drafted at the same time!)

**Comment by jespersh** [comment]
![image](https://user-images.githubusercontent.com/1004198/67004849-80c1c080-f0e1-11e9-86e5-fcf795030e99.png)

The references between the projects are like this:
![image](https://user-images.githubusercontent.com/1004198/67004914-abac1480-f0e1-11e9-83be-f24c7d93ab5a.png)

For a bit of context: The application layer is "talking" with the persistence layer through interfaces in the application layer and DI registered in the persistence layer.


What I normally do is just reverse engineering new entities and copying the parts from `AldenteDbContext2` (generated in Entities folder) to `AldenteDbContext`

**Comment by ErikEJ** [comment]
assuming that you are running EF Core Power Tools in the Aldente.Journal.Domain, the following values should work:

Namespace: Aldente.Journal
Entity path: Entities
Entity Sub-namespace: Domain.Entities
DbContext path :  c:\code\xxx\Aldenete.Journal.Persistence
DbContext sub-namepsace: Persistence

(and thanks for dog-fooding!)

**Comment by ErikEJ** [comment]
@jespersh did you try this out?

**Comment by jespersh** [comment]
Back in the work seat and tried this out. For the most part it worked as expected. 
Then I had this oddity in my `Aldente.Journal.Domain.csproj` added:
```xml
<Project Sdk="Microsoft.NET.Sdk">
...
  <ItemGroup>
    <Compile Include="..\Aldente.Journal.Persistence\AldenteDbContext.cs" Link="AldenteDbContext.cs" />
  </ItemGroup>
...
</Project>
```
This is the only thing I'd even consider an error.
The few other oddities I met are either because of my namespace (entity and namespace named `Journal`) or unhandled mysql datatypes (zerofill). 

Knowing what I know today, then I'd move the generated `AldenteDbContext.cs` into: `c:\code\xxx\Aldenete.Journal.Persistence\Generated\`, because I have some special bits too.

So the screenshots are these:
![image](https://user-images.githubusercontent.com/1004198/67185517-4ceae180-f3e6-11e9-93a0-4057e664d7df.png)

![image](https://user-images.githubusercontent.com/1004198/67185614-83c0f780-f3e6-11e9-8c3f-7280ed45deef.png)


What I am wondering about is this:
* My non-generated AldenteDbContext would have a dependency injected into its constructor. How do I avoid the constructors in the partial generated by the tool? Or am I using it incorrectly. Should this be done as a property injection instead?
```C#
...
    public AldenteDbContext(ISecrets secrets)
    {
        _secrets = secrets;
    }
...
```
Maybe a followup issue on this would be appropriate

**Comment by ErikEJ** [comment]
1: What is your target framework in Aldente.Journal.Domain.csproj ?

2: The constructor issue - is that something that just happended now? Otherwise it sounds like a feature request, so feel free to post a new issue.

3: "unhandled mysql datatypes (zerofill)." - is that a MySQL provider issue/bug?

**Comment by jespersh** [comment]
1. <TargetFramework>netstandard2.0</TargetFramework>

2. What I have been doing is using Reverse Engineer like this: 
 * Reverse engineer the specific table(s) I haven't yet added to get the Entity model(s) and a 2nd DbContext (the DbContext that always ended up in the Domain project) for the specific entity/entities.
 * Copy the parts from the DbContext that ends up in the Domain project into the DbContext I actually use in the Persistence project.

That way I always ended up a DbContext I was in control of because I was always cut/pasting the newly reverse engineered parts.
If I needed to only use your partial **as is**, now that it is able to end up in the right location, then I **think** I'd need a constructor-less generated partial and without the `OnConfiguring` method. That way I can create my own partial and not worry about having to re-generate the Reverse Engineered DbContext. 
My own partial would contain the `OnConfiguring` override and appropriate constructors. Do you think that's a reasonable feature request?

3. Yeah. I should look into fixing that for them so I don't hit that issue, because those properties are just silently skipped in the Entity model *yikes*.

**Comment by ErikEJ** [comment]
1: Looks like I should only be doing this for .NET Framework projects: https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/EFCorePowerTools/Handlers/ReverseEngineerHandler.cs#L247 

2: That is not how you are supposed to use it !! :smile:
So: 
a: Why do you need a constructorless partial?
b: Why do you need OnConfiguring removed? You can just use the constructor with a DbContextOptions class.

```
            var optionsBuilder = new DbContextOptionsBuilder<AssetManagementContext>();
            optionsBuilder = optionsBuilder.UseInMemoryDatabase(Guid.NewGuid().ToString());
            context = new AssetManagementContext(optionsBuilder.Options);
```

**Comment by jespersh** [comment]
I'll try and throw together a small example with my usage on how I intend to use it if I had to rework my persistence layer

**Comment by jespersh** [comment]
It'll also mostly be for my own sake to see what I've learned about working with EFCore. That others will benefit for it is a bonus 😄

**Comment by ErikEJ** [comment]
>> Then I had this oddity in my Aldente.Journal.Domain.csproj added:

Attempted to fix in latest daily build

**Comment by alexle1965** [comment]
Erik,  this is to let you know I love your tool.  I am trying out the .NET 5.0 features and I don't know how to tell the tool to move all of the Entity Configuration files to a specified directory and the same for the Result files for Stored Procedures.  For the domain entities and dbContext, they are easy to do.

**Comment by ErikEJ** [comment]
@alexle1965 Please create new issues for feature suggestions or bug reports.

The Entity Configuration proposal is a duplicate of #423 .

For the Stored Procedure result files, where would you like them to be placed? - if this matters to you, please create a new feature suggestion with a proposal.

**Comment by alexle1965** [comment]
Hi Erik, Once again, thank you for the wonderful tool and I use it all the times.  My new project is to migrate a legacy application from Webforms with a lot of stored procedures to .NET Core 3.1.x.  I used your tool to do the reverse engineering and all the SProc are generated for me.  My issue is that I do not know to invoke the auto-generated stored procedures from the controllers or how they are used.  I read through the documentation but I do not see anything about using the SP. Would you be kind enough to provide me guidance of where to go for the documentation? Thank you very much.  I love your tool. Alex Le316-371-8179 (mobile)“Be more concerned with your character then your reputation…”  From: Erik Ejlskov JensenSent: Friday, November 13, 2020 12:48 AMTo: ErikEJ/EFCorePowerToolsCc: Alex Le; MentionSubject: Re: [ErikEJ/EFCorePowerTools] Update Reverse Engineering wiki page (#290) @alexle1965 Please create new issues for feature suggestions or bug reports.The Entity Configuration proposal is a duplicate of #423 .For the Stored Procedure result files, where would you like them to be placed? - if this matters to you, please create a new feature suggestion with a proposal.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ErikEJ** [comment]
@alexle1965 It is documented here: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#sql-server-stored-procedures - wonder why you were not able to find it?

**Comment by alexle1965** [comment]
Erik, 

Thank you very much. I clicked on the documentation link in Github as well. 

⁣Alex Le
316-371-8179
