### ISSUE TITLE
Migrations Tool: Support for .NET Core 3.1 Preview 1

### ISSUE THREAD

**Issue by JeepNL** [ErikEJ/EFCorePowerTools#292]
### Describe what is not working as expected.
Migrations Tool: System.ArgumentException: Only .NET Core 2.1, 2.2 and 3.0 and 2.2 are supported
(I'm using .NET Core 3.1.0 Preview 1)

### Steps to reproduce
Running Migrations Tool

### Result:
System.ArgumentException: Only .NET Core 2.1, 2.2 and 3.0 and 2.2 are supported

### Further technical details
EF Core Power Tools version: (Daily Build) Version 2.3.74.0
Database engine: SQLite
Visual Studio version: 2019 / 16.4.0 Preview 2.0
.NET Core 3.1.0 Preview 1

**Comment by ErikEJ** [comment]
Could you share your .csproj?

**Comment by JeepNL** [comment]
> Could you share your .csproj?

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UserSecretsId>aspnet-ICTZ-0DB68A0B-D5E0-45AC-8BFC-3DD0B1DA19A9</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="3.1.0-preview1.19508.20" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="3.1.0-preview1.19508.20" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="3.1.0-preview1.19508.20" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="3.1.0-preview1.19506.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.1.0-preview1.19506.2" />
  </ItemGroup>

</Project>

```

**Comment by JeepNL** [comment]
It's a Blazor (Server Side) project.

**Comment by ErikEJ** [comment]
I tried to unblock you in the latest daily build (and fix the error message)

**Comment by JeepNL** [comment]
Thank you, it is working.
