### ISSUE TITLE
Need to be able to edit or at least delete a saved db connection

### ISSUE THREAD

**Issue by rkreisel** [ErikEJ/EFCorePowerTools#293]
When using a saved connection (in the "Choose Database Connection" dialog), certain connections fail. When this happens the Output window contains Login failed for user '{username here}'. I suspect a changed or incorrectly saved password is the culprit. 

A workaround would be to edit the connection information, but I see no way to do that. I also do not see a way to delete and re-add one.

I have tried to determine the location of the file that powers that dialog, but have not succeeded.

### Steps to reproduce
Click Reverse Engineer. Choose Database Connection dialog opens. Choose a particular connection and click OK. 
The connection fails with the error message above.

### Further technical details
EF Core Power Tools version: 2.2.63.0
Database engine: SQL Server

Visual Studio version: (e.g. Visual Studio 2017 15.9.17)

**Comment by ErikEJ** [comment]
You can find (and remove) the connections in Server Explorer

**Comment by rkreisel** [comment]
Why didn't I think of that?  :)
Thanks

**Comment by ErikEJ** [comment]
A button to remove the selected connection has been added to the latest daily build.
