### ISSUE TITLE
Update MySql 3.0 RevEng package once it finalizes

### ISSUE THREAD

**Issue by jespersh** [ErikEJ/EFCorePowerTools#294]
Pomelo.EntityFrameworkCore.MySql github was recently updated with these improvements. Nuget package is not yet updated:

> Add support to reverse engineer views.
Add comments for tables and columns.
Improve handling of default values.
Handle the CURRENT_TIMESTAMP default value for timestamp columns correctly.
Correctly implement CURRENT_TIMESTAMP with ON UPDATE clauses.
Introduce a workaround for the missing EF Core handling of ValueGenerated.OnUpdate.

The most important one being the first line.
https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/pull/896

**Comment by ErikEJ** [comment]
Looks like rc3-final is out, does that include above changes?

**Comment by ErikEJ** [comment]
@jespersh I have included rc3-final in the latest daily

**Comment by jespersh** [comment]
It seems like it. Thanks!

**Comment by ErikEJ** [comment]
Thanks for confirming, a release to marketplace will come very soon
