### ISSUE TITLE
Update database

### ISSUE THREAD

**Issue by SoftCircuits** [ErikEJ/EFCorePowerTools#295]
I'm sorry to ask such a basic question but I'm having trouble finding an answer. I've used EF Core Power Tools to extract the models from my database. Do the tools also provide support for creating/updating my database from the models?

Also, using the very latest version of Visual Studio, my Razor Pages application already has a `DbContext` class, and has migrations to create a number of classes like `AspNetUsers`, `AspNetRoles`, etc. (not yet added to my actual database). Do the tools play nice with that existing code/models?

I'm an experienced developer but new to code-first, and am at a complete loss as to why database-first appears to be losing support from Microsoft. If someone could answer a few questions and get me on track, I'd appreciate it.

**Comment by ErikEJ** [comment]
>> Do the tools also provide support for creating/updating my database from the models?

You can use Migrations to move your schema forward, and the tool can assist you with that - it can also generate a SQL script to create the current model.

>> Do the tools play nice with that existing code/models?

Maybe - I cannot tell without digging into your code

**Comment by SoftCircuits** [comment]
I don't have any code to speak of. I just created a new Razor Pages project.

I know I can use migrations. I'm trying to figure out if the tool provides features to update the database.

If I can't get information like that, is there any documentation that lays out in a very basic way for someone who knows nothing about tool exactly what tasks it can accomplish?

**Comment by ErikEJ** [comment]
I think you should start with some EF Core documentation.

**Comment by SoftCircuits** [comment]
@ErikEJ OMG, I was asking about the tools. If you don't want to answer my questions, wouldn't it make more sense just to say that?
