### ISSUE TITLE
Powertools Dialogs do not scale

### ISSUE THREAD

**Issue by fjeller** [ErikEJ/EFCorePowerTools#297]
Just a small thing that bothers me a bit with this extension ... 

I use a different font and font size for the visual studio environment (Calibri, 13pt). Setting this makes the extension almost unusable since the Model-Dialog is too small. None of the dialogs do scale, but the Model-Dialog turns out to be too small to see all settings and the buttons.

I had a quick look in the source code and saw that the resizemode is set to "noresize" and width and height are set to fixed values. I don't work much anymore with WPF, but I believe that either making the window resizable (resizeMode = "CanResize") would solve the problem. Or of course setting "SizeToContent" to "Height", that should work too.

This problem occurs in all versions, and to reproduce just choose a larger environment font. Current Workaround: Maximize the window, then I can see everything.

I attached a screenshot for reference.
![efcorepowertools](https://user-images.githubusercontent.com/23081625/68011997-1dab5e80-fc89-11e9-9ca6-fede7edaf1ff.PNG)

**Comment by ErikEJ** [comment]
@Herdo any thoughts?

**Comment by Herdo** [comment]
@fjeller Does this different font size also resize the font inside controls like `TextBox` and `ComboBox`? If so, just allowing more space to the window won't be enough. IIRC, every control is also hard-coded in width and height.

@ErikEJ Setting `SizeToContent = SizeToContent.WidthAndHeight;` would probably one of the better solutions. Of cause, it'd be greate to have a look at dialogs provided by Visual Studio itself, how they handle the different font sizes.

**Comment by fjeller** [comment]
@Herdo you are correct, the textbox has a fixed height, that must also be changed - it seems it's the same with buttons as well. So probably a bit more work than I thought ... :-(.

And of course `SizeToContext = SizeToContent.WidthAndHeight` would be the correct setting, adjusting only the height would not solve the problem.

**Comment by ErikEJ** [comment]
@Herdo Sadly, VS is not open source, so viewing their dialogs could be hard. The dialogs used by the tool already inherit from the VS style dialog, though.
