### ISSUE TITLE
Reverse Engineering adds UseNetTopologySuite

### ISSUE THREAD

**Issue by NetMage** [ErikEJ/EFCorePowerTools#299]
When using Reverse Engineering to create a database Context, the optionsBuilder.UseSqlServer statement is generated with UseNetTopologySuite.

### Steps to reproduce
Reverse Engineer a database.
See error in because Net Topology Suite isn't being used, but is called.

### Further technical details
EF Core Power Tools version: 2.3.76.0

Database engine: SQL Server 2016

Visual Studio version: Visual Studio Enterprise 2019 v16.3.7

**Comment by ErikEJ** [comment]
Reverse engineer without a connection string?

**Comment by ErikEJ** [comment]
Could you share some sample code?

**Comment by NetMage** [comment]
I had "Include connection string in generated code" checked. I had "Use Data Annotation attributes to configure the model" checked. I think "Install the EF Core provider package in the project" was checked automatically.

The generated DB Context class had the following method in it:

`
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) {
            if (!optionsBuilder.IsConfigured) {
                optionsBuilder.UseSqlServer("connection string", x => x.UseNetTopologySuite());
            }
        }
`

**Comment by ErikEJ** [comment]
Maybe avoid the connectionstring in the generated code?
