### ISSUE TITLE
Oracle 11g -  Showing empty connection

### ISSUE THREAD

**Issue by kuldip1490** [ErikEJ/EFCorePowerTools#301]
@ErikEJ  After connection, showing empty dropdown

### Steps to reproduce

-  Doing a connection using EFCorePowerTool

![ss-1](https://user-images.githubusercontent.com/22524273/68466510-8e7ae980-023a-11ea-8c1c-526438dd9842.png)

- After a successful connection

![ss-2](https://user-images.githubusercontent.com/22524273/68466523-976bbb00-023a-11ea-98f0-83340dca94e6.PNG)

### Further technical details
EF Core Power Tools version:  2.2.63

Database engine: Oracle 11g 

Visual Studio version: VS 2019

**Comment by ErikEJ** [comment]
There is no support for Oracle yet, see #288
