### ISSUE TITLE
Reverse Engineer History Not Loading

### ISSUE THREAD

**Issue by davidhendrickmb** [ErikEJ/EFCorePowerTools#304]
Hi there,

When I tried to reverse engineer my DB today, it didn't have any of the existing tables selected. I have an efpt.config.json file with all of the existing tables, but none of these are selected.
Can you help?

Thanks

**Comment by ErikEJ** [comment]
I guess you are using the latest version, which has some breaking changes in that area.

**Comment by davidhendrickmb** [comment]
Do you have any details on how to fix the issue or is it possible to get a download to an older version? 
The extension was set to auto update.

**Comment by ErikEJ** [comment]
Manually?

**Comment by ErikEJ** [comment]
IE open the existing file to see the list of selected tables

**Comment by davidhendrickmb** [comment]
So I have to re-add all of the tables I previously had? Is there a way to roll back the version?

**Comment by davidhendrickmb** [comment]
Or can you provide the new format/file?

**Comment by ErikEJ** [comment]
How many tables did you have??

**Comment by davidhendrickmb** [comment]
270 imported....some are not imported from the database.

**Comment by ErikEJ** [comment]
The new format should be easy to see if you create a new file in a new project, but assuming you are using SQL Server, it is "dbo.Mytable" => "[dbo].[Mytable]" - I will give a fix some thought, but it may take some time.

**Comment by davidhendrickmb** [comment]
Thank you for this. I made a simple HTML page to regenerate this if anyone else has this issue.

`<html>
<script
  src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
  crossorigin="anonymous"></script>
<div id="NewData"></div>

<script>

var efdata= {INSERT YOUR DATA HERE}

var eftables = efdata.Tables;
console.log(eftables);
var newTableStructure = new Array();
for(var i = 0; i < eftables.length; i++)
{
	var newName = "[" + String(eftables[i].Name).replace(".", "].[") + "]";
	eftables[i].Name = newName;
	
}

console.log(efdata);
$('#NewData').html(JSON.stringify(efdata))

</script>
</html>`

**Comment by ErikEJ** [comment]
Thanks for reporting this, it has been fixed in the latest daily build, and will be published to VS MarketPlace very soon
