### ISSUE TITLE
Use EF Core 3.1 reverse engineering

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#307]
https://github.com/aspnet/EntityFrameworkCore/issues/17847 
https://github.com/aspnet/EntityFrameworkCore/issues/17839
https://github.com/aspnet/EntityFrameworkCore/issues/18579

**Comment by doggy8088** [comment]
All these 3 issues looks like been closed.

**Comment by ErikEJ** [comment]
It is about using the update in the tool
