### ISSUE TITLE
Path being added to Name Space

### ISSUE THREAD

**Issue by Moorepheus** [ErikEJ/EFCorePowerTools#309]
I don't need or want the Path for the DbContext to be added DbContext Namespace.  Can you make this an option instead of a requirement?

EF Core Power Tools version 2.3.81.0

**Comment by ErikEJ** [comment]
You need to provide a repro project, I do not understand what you are referring to.

**Comment by Moorepheus** [comment]
Not sure how to give you a repo project. I will try to explain it better.
1. Run EF Core Reverse Engineer
2. Pick the database
3. Pick the tables to reverse engineer.
4. Fill in the Context Name: "MyDataContactBase"
5. Fill in the NameSpace: "My.DataContext"
6. Fill in EntityTypes Path: "Data\Models"
7. Fill in DbContext Path: "Data\DataContext\Abstract\"
8. Click "OK"

When I look at the resulting DbContext that is generated from this, it added the "DbContext path" to the "Namespace" value.  We don't want this.  Is there a way to make this optional?  Right now, after this process generates the DbContext, I now have to remove the DbContext Path from the NameSpace in the DbContext.

![image](https://user-images.githubusercontent.com/20537512/69270775-a3903a80-0ba1-11ea-8b69-0a8f5511f925.png)

**Comment by ErikEJ** [comment]
Pls show med the top of the DbContext class

**Comment by ErikEJ** [comment]
And show me the desired result!

**Comment by ErikEJ** [comment]
Ping?

**Comment by ErikEJ** [comment]
Pong?

**Comment by Moorepheus** [comment]
Sorry, didn't see your response....been really busy....
anyway, this is what is happening based on my previous e-mail

`using Microsoft.EntityFrameworkCore;namespace My.DataContext.Data.dataContext.Abstract`

this is what I desire
`using Microsoft.EntityFrameworkCore;
namespace My.DataContext`

**Comment by ErikEJ** [comment]
Try:

Namespace: My
EntityType sub-namespace: DataContext.Data.Models
DbContext sub-namespace: DataContext

(Leave the two paths as they are)

**Comment by Moorepheus** [comment]
The problem with that, is now all my models have only “MY” as the namespace.   I want my Model and DbContext to be in the same namespace.

————————————————
Mark Moore
Software Engineer
800.458.3820 x303
[cid:image001.png@01D5A437.A3D1CD50]

NTS Data Services, LLC

**Comment by ErikEJ** [comment]
EntityType sub-namespace: DataContext

Please share a screenshot!

**Comment by Moorepheus** [comment]
Ok, I get it now, sorry for the confusion. A lot going on here and didn’t get a change to read the update notes and when I ran it, it filled in some of the properties already.

Thanks for the heads up… Again, this is great update to what you already did.

Thanks again.

————————————————
Mark Moore
Software Engineer
800.458.3820 x303
[cid:image001.png@01D5A439.00E841D0]

NTS Data Services, LLC

**Comment by ErikEJ** [comment]
Glad you got it working!

if you like my tools, I would be very grateful for a rating or review here:
https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools#review-details
