### ISSUE TITLE
Reverse Engineer from previously working dacpac file now creates context with no DbSets

### ISSUE THREAD

**Issue by rcfearn** [ErikEJ/EFCorePowerTools#310]
Describe what is not working as expected.

### Steps to reproduce
Reverse engineer and select SQL Database Project in second dropdown. Window pops up with all previously reverse engineered tables selected as normal - select [OK].

On next UI:
"Use table and column names ..." : Checked
"Use data annotations" : Tried both Checked & Unchecked
Nothing else checked

Click [OK]
Modal appears stating context created successfully - Context file does not open though (it used to after generation)
Then project won't build because all Models (supposedly generated) are now missing from Context. E.g. Context.MyTableOne does not exists.

Diff Context.cs file and it is bare bones - all DbSets and modelBuilder.Entity declarations stripped from file.

<img width="750" alt="git-issue-context" src="https://user-images.githubusercontent.com/5847855/69478109-c725e000-0e42-11ea-8f24-5f000ac7bb9d.png">

### Further technical details
EF Core Power Tools version: 2.3.86

Database engine: (SQL Server DB project set to 2017)

Visual Studio version: (e.g. Visual Studio 2019 Preview 16.4 Preview 6.0 (and earlier version - upgraded to see if it resolved the issue))

**Comment by ErikEJ** [comment]
Are you using EF Core 3 option?

**Comment by rcfearn** [comment]
I tried both - it made no difference - I've reverted to reverse engineering from DB for the time being.

**Comment by ErikEJ** [comment]
Thanks for reporting this, fixed in latest daily build

**Comment by rcfearn** [comment]
Great! Thanks for creating it - it's a great tool and has saved me a lot of time.

**Comment by ErikEJ** [comment]
Build break, hang in there .- If you like my tools, I would be grateful for a review in VS MarketPlace!
