### ISSUE TITLE
Confusing error message on when Design package is not in dbcontext project

### ISSUE THREAD

**Issue by julielerman** [ErikEJ/EFCorePowerTools#311]
Error when attempting Add DbContext Model Diagram that says 
"Version string portion was too short or too long."

### Steps to reproduce
I have a multi-targeted project where dbcontext lives:

   <TargetFrameworks>netcoreapp3.0;netstandard2.1</TargetFrameworks>

It has only one package reference, to MS.EFCore.SqlServer  (I'm targeting 3.1.0-preview3)

The project is a separate dbcontext project. The startup project in the solution is an exe and references the dbcontext project. The startup project DOES have a ref to Tools for migrations to work.

Attempt to Add the model diagram results in the error below.

Adding the Design package to the dbcontext project fixes the problem.

The error is not coming from your code base, but a dependency. So I'm not sure i fyou can trap it and provide something ore helpful. Otherwise, maybe add this requirement to the wiki? (I can do a PR for the wiki :) ). 

System.ArgumentException: Version string portion was too short or too long.
   at System.Version.VersionResult.SetFailure(ParseFailureKind failure, String argument)
   at System.Version.TryParseVersion(String version, VersionResult& result)
   at System.Version.Parse(String input)
   at System.Version..ctor(String version)
   at EFCorePowerTools.Handlers.ModelAnalyzerHandler.Generate(String outputPath, Project project, GenerationType generationType) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ModelAnalyzerHandler.cs:line 48

### Further technical details
EF Core Power Tools version: 2.3.86
(note that in Help/About it says version 1.0 ...should I add another issue for that?)

Database engine: SQL Server

Visual Studio version: VS2019 16.3.8

**Comment by ErikEJ** [comment]
Hi Julie, thanks for reporting this.

I am unable to repro the version number issue:
![image](https://user-images.githubusercontent.com/4169187/69497685-25ed6700-0ee0-11ea-93cd-de3b92d9248e.png)

The error message is simply caused by the fact the I currently do not support preview versions - I have added an explicit error message to the latest daily build.

**Comment by julielerman** [comment]
totally reasonable and thanks for the quick change! :)
