### ISSUE TITLE
SQL Server views not remembered

### ISSUE THREAD

**Issue by John-teLintelo** [ErikEJ/EFCorePowerTools#312]
When reverse engineering a SQL server database, any selected views are not selected on subsequent runs.

### Steps to reproduce
Reverse engineer a SQL database and select at least one table and view.
Selected tables and views are correctly saved to efpt.config.json
Run reverse engineer again. Notice that the tables are selected but the views are not.

### Further technical details
EF Core Power Tools version: 2.3.89.0

The problem appears to be that views are loaded into the "Select Tables" dialog without any square brackets, but when the tables and views are loaded from the config file, square brackets are automatically added.

Database engine: SQL Server

Visual Studio version: Visual Studio 2019 16.3.9

**Comment by ErikEJ** [comment]
Thanks for reporting this - fixed in latest daily build, would be grateful if you could confirm

**Comment by John-teLintelo** [comment]
Apologies for the delay.  I can confirm that it is fixed.
