### ISSUE TITLE
SQL Server "geography" type is not being imported

### ISSUE THREAD

**Issue by davidhendrickmb** [ErikEJ/EFCorePowerTools#314]
Hi there,

Using Reverse Engineer, SQL Server geography type columns no longer import and are dropped from models. 
I've tried the latest build, 2.3.90 and it still doesn't work.

Thanks,
David

**Comment by ErikEJ** [comment]
Did it use to work?

**Comment by davidhendrickmb** [comment]
Yes, it used to import as an IGeometry and reference "using GeoAPI.Geometries;".

**Comment by ErikEJ** [comment]
I will make it an option.

**Comment by davidhendrickmb** [comment]
Thank you. Do you have an idea of when this might be available?

**Comment by ErikEJ** [comment]
I have tried to add support for this in the latest daily build.

Set: `UseSpatial: true` in the efpt.config.json file

If you like my tools, I would be very grateful for a rating or review here:
https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools#review-details

**Comment by davidhendrickmb** [comment]
Works perfectly, thank you! I've left a review!

**Comment by ErikEJ** [comment]
You are welcome, I will also update the wiki to document this!

**Comment by dyardyGIT** [comment]
I just ran and my sql geography fields came in as Geometry.  I was expecting it to be mapped to geography. Am i missing something or configuration?

"By default, spatial properties are mapped to geography columns in SQL Server. "

**Comment by ErikEJ** [comment]
Did you set useSpatial = true

**Comment by dyardyGIT** [comment]
yes..see below
I used the latest build and ef core 3.1 (on .net standard 2.1)
![2019-12-05_17-13-37](https://user-images.githubusercontent.com/3586830/70278609-9c148800-1782-11ea-8ae7-2416745de7b2.png)

![2019-12-05_17-14-11](https://user-images.githubusercontent.com/3586830/70278692-c23a2800-1782-11ea-854e-e0c5caf401a3.png)


configuration


{
   "ContextClassName": "DataDbContext",
   "ContextNamespace": null,
   "DefaultDacpacSchema": null,
   "DoNotCombineNamespace": false,
   "IdReplace": false,
   "IncludeConnectionString": false,
   "ModelNamespace": null,
   "OutputContextPath": "",
   "OutputPath": "Models",
   "ProjectRootNamespace": "DataAccess",
   "SelectedHandlebarsLanguage": 0,
   "SelectedToBeGenerated": 0,
   "Tables": [  
      {
         "HasPrimaryKey": true,
         "Name": "[tge].[Users]"
      }
   ],
   "UseDatabaseNames": false,
   "UseFluentApiOnly": true,
   "UseHandleBars": false,
   "UseInflector": true,
   "UseLegacyPluralizer": false,
   "UseSpatial": true
}

**Comment by ErikEJ** [comment]
Are you using a live database or a dacpac?

https://github.com/aspnet/EntityFrameworkCore/blob/0d76bbf45a42148924b413ef8f37bf49c1ce10d3/src/EFCore.SqlServer.NTS/Storage/Internal/SqlServerNetTopologySuiteTypeMappingSourcePlugin.cs#L57

**Comment by dyardyGIT** [comment]
I am using live database

**Comment by dyardyGIT** [comment]
Any idea as to what I can try

**Comment by ErikEJ** [comment]
No idea, lets Patiently await comments from @bricelam

**Comment by bricelam** [comment]
Everything is working as expected. NTS only has a Geometry type. It can map to both `geometry` and `geography` on SQL Server. The SQL Server EF Core provider maps them to geography by default.

You can explicitly configure the column type if it makes you feel better: 😉
```csharp
[Column(TypeName = "geography")]
public Geometry Location { get; set; }

**Comment by bricelam** [comment]
See also https://github.com/NetTopologySuite/NetTopologySuite/issues/314

**Comment by ErikEJ** [comment]
@bricelam This is from reverse engineering! @dyardyGIT Can you show us the relevant part of your DbContext (fluent API for that table) ?

**Comment by dyardyGIT** [comment]
Yes it was using reverse engineering, and when run it created my Sql Server Location (geography) field as Location (geometry)

@ErikEJ  this was the generated entity within dbcontext.  This is what you were looking for?

```
            modelBuilder.Entity<Photo>(entity =>
            {
                entity.HasKey(e => e.PhotoId);

                entity.ToTable("Photos", "tge");

                entity.Property(e => e.Altitude).HasColumnType("decimal(12, 6)");

                entity.Property(e => e.AmazonKey)
                    .IsRequired()
                    .HasMaxLength(200);

                entity.Property(e => e.Comment).HasMaxLength(2000);

                entity.Property(e => e.Direction).HasColumnType("decimal(9, 6)");

                entity.Property(e => e.FileName).HasMaxLength(200);

                entity.Property(e => e.GpsDateTime).HasColumnType("datetime");

                entity.Property(e => e.ImageThumb).HasColumnType("image");

                entity.Property(e => e.Latitude).HasColumnType("decimal(9, 6)");

                entity.Property(e => e.Longitude).HasColumnType("decimal(9, 6)");

                entity.Property(e => e.ModifiedDate).HasColumnType("datetime");

                entity.Property(e => e.PhotoType).HasMaxLength(25);

                entity.HasOne(d => d.Submission)
                    .WithMany(p => p.Photos)
                    .HasForeignKey(d => d.SubmissionId)
                    .OnDelete(DeleteBehavior.Cascade)
                    .HasConstraintName("FK_Photos_Submissions");
            });
```


@bricelam Are you saying that NTS does not have geography field and the extension will always map geography to geometry correct (using reverse engineering)?

The attribute (below) you are saying would allow me to do migrations forward to geography to generate the sql table.  Correct? (unfortunately I am reverse engineering) so it looks it is working as designed and we will need to modify our code to work with geometry now correct?
```
[Column(TypeName = "geography")]
public Geometry Location { get; set; }
```

**Comment by bricelam** [comment]
Correct. It’s super confusing, but a Geometry property in EF Core maps to a geography column in SQL Server be default.

Adding to the confusion, you can also map an EF Geometry property to a geometry column just by configuring its column type.
