### ISSUE TITLE
Smart config edit (automatic moving and deleting of autogenerated files)

### ISSUE THREAD

**Issue by Lonsarg** [ErikEJ/EFCorePowerTools#315]
Idea:
I suggest making .json config file for reverse engineered a "master", also handling deletes and moves when rerun, bringing generated files in sync with the config every time. In current logic config file is susceptible to being out of sync with the actual reverse engineered files everytime someone changes path or deletes a table from config, requiring manual handling of autogenerated files.

Implementation:
Currently if we make changes to path new path is created + old path stays and we have to delete it manually. We would change this so that any edits to path in config would move existing autogenerated files to new location automatically and even delete previous folder if we detect it is empty after moving the autogenerated files. Also more importantly any table that was unselected in reveng UI would also be automatically deleted. We would naturally only touch the autogenerated files, leaving manual ones user may have made alone.

Reasoning:
It seems more natural for config to be the master, if someone wants only one-time generation it makes more sense that he deletes the config after usage to avoid confusion. This would also bring the behaviour in-line with how .dbml and .edmx are also masters over generated files in their respective tools (and EF Power Tools is the best replacement for those). I am ready to make the necessary changes myself.

**Comment by ErikEJ** [comment]
Interesting - Do you often change the path? I never do.

>> would also be automatically deleted.  

I dont think that would be a good idea!

And if this was implemented, it would be off by default, and something the user should opt in to.

**Comment by Lonsarg** [comment]
Well path is not that important, i mainly change it when i play with settings when creating a new "Db project" to try different values and currently i just delete it all before regenerating every time to avoid duplicates.

But the main confusion happens if i unselect a table when it stays generated after going through the wizard. With lot of tables it is easy to forget to also manually delete when you uncheck it and you only notice the error at runtime (now or one year later when someone references the old obsolete table by accident). Maybe simply enabling auto-deletes is realy not ok without also changing the UI to make this clear. For example instead of checkboxes we could have 2 lists (available/currently added) and then add/delete buttons for actions. Maybe in that case actually deleting the table when clicking delete would seem appropriate?

I don't know if opt-in is worth it in my case, since the main problem is not me but many other developers at our company that will expect "click-to-change-model" funcionality always without touching .cs files manually. We are mostly using dbml/edmx designers at the moment and will try to consolidate on one 3rd party UI tool for projects that will use EF Core, and nothing compares to EF Core Power Tools.

**Comment by ErikEJ** [comment]
I think just an option saying "Remove obsolete model files" (or similar) - what do you think?

**Comment by Lonsarg** [comment]
Well if we really want to avoid any breaking changes than yes that would seem the best option.

**Comment by ErikEJ** [comment]
I will let this sit for a while to see if it gets any upvotes.

**Comment by ErikEJ** [comment]
I have implemented #358
