### ISSUE TITLE
Script Migrations generate unknown result

### ISSUE THREAD

**Issue by doggy8088** [ErikEJ/EFCorePowerTools#319]
I'm trying **Migrations Tool (preview)**. When I click on the **Script Migrations** button. It generate a YAML file but with `*.sql` extension. I don't understand what is this for?

![image](https://user-images.githubusercontent.com/88981/70148560-653a6580-16e1-11ea-813c-75a3454801ff.png)

![image](https://user-images.githubusercontent.com/88981/70148772-c7936600-16e1-11ea-8ef9-9e1590110413.png)

### Steps to reproduce

1. [**EF Core Power Tools**] / [**Migrations Tool (preview)**]
2. Hit **Add Migration** button
3. Hit **Update Database** button
4. Hit **Script Migrations** button

### Further technical details

EF Core Power Tools version: `2.3.92.0`

Database engine: SQL Server

Visual Studio version: Visual Studio 2019 16.4.0

**Comment by ErikEJ** [comment]
That is a bug!

**Comment by ErikEJ** [comment]
Which EF Core version?

**Comment by ErikEJ** [comment]
Attempted a fix in latest daily, thanks for reporting this
