### ISSUE TITLE
Update to 2.1 RTM (Migrations tool and Model inspection)

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#32]
Consider if 2..0 should still be supported - most likely not

**Comment by tonysneed** [comment]
@ErikEJ Is this working now?  I get an error saying that only v2.0 is supported (not 2.1) for modeling.

**Comment by ErikEJ** [comment]
have you tried the latest daily build (.614 or later) ?

**Comment by tonysneed** [comment]
I just installed from the marketplace. How do I install the daily build?

**Comment by ErikEJ** [comment]
Link iin readme: https://github.com/ErikEJ/EFCorePowerTools

**Comment by tonysneed** [comment]
Oh yes, it helps if I read the ReadMe. :)

**Comment by tonysneed** [comment]
Interesting thing is that after I uninstalled the version from the marketplace 1.0.604 and installed the daily build version 1.0.616, I got the assembly binding error:

```
System.IO.FileNotFoundException: Could not load file or assembly 'Handlebars, Version=1.9.4.0, Culture=neutral, PublicKeyToken=22225d0bf33cd661' or one of its dependencies. The system cannot find the file specified.
File name: 'Handlebars, Version=1.9.4.0, Culture=neutral, PublicKeyToken=22225d0bf33cd661'
   at EntityFrameworkCore.Scaffolding.Handlebars.HbsHelperService.RegisterHelpers()
   at EntityFrameworkCore.Scaffolding.Handlebars.HbsCSharpModelGenerator.GenerateModel(IModel model, String namespace, String contextDir, String contextName, String connectionString, ModelCodeGenerationOptions options)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, IEnumerable`1 tables, IEnumerable`1 schemas, String namespace, String language, String contextDir, String contextName, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions)
   at ReverseEngineer20.EfCoreReverseEngineer.GenerateFiles(ReverseEngineerOptions reverseEngineerOptions)
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__2.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 153
```

Can you check to see if the Handlebars.Net assembly has the right public key token?

**Comment by ErikEJ** [comment]
@tonysneed It does, and I am unable to repro - maybe you have two instances of the extension on disk - have a look - you can also use https://github.com/remcoros/DuplicateExtensionFinder

**Comment by tonysneed** [comment]
The tool tells me there are no duplicate extensions.  I only get the assembly binding error when installing extension.vsix from the VSIX Gallery link under Daily Builds in the ReadMe.  If I uninstall the daily build and install the latest version from the marketplace, then this error does not occur.  I've been able to repro several times on my end, so I imagine it should be relatively straightforward to repro on your end if you follow the same steps.

The way to troubleshoot this is to turn on assembly binding logging.

```
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
```

**Comment by ErikEJ** [comment]
I Will give it a try, but believe I am unable to repro. Which Windows version and VS version do you use?

**Comment by tonysneed** [comment]
Running visual studio 2017 on windows 10.

I’m curious now. :) it looks like fusion simply cannot locate the handlebars DLL, so I’m wondering if it does not search the nuget package cache?

**Comment by ErikEJ** [comment]
Does the extension folder contain the handlebars DLL,? In %appdata% local Microsoft VisualStudio ?

**Comment by tonysneed** [comment]
I’ll check ...

**Comment by tonysneed** [comment]
It looks like Handlebars.dll is missing from the installation folder.  And when I copy it to the folder, the error goes away. :-)

**Comment by ErikEJ** [comment]
Perfect! I will force it there!

**Comment by ErikEJ** [comment]
Fixed in latest daily build! Thanks for the help with debugging this
