### ISSUE TITLE
Tab index in Manage Migrations dialog

### ISSUE THREAD

**Issue by doggy8088** [ErikEJ/EFCorePowerTools#320]
In the **Manage Migrations** dialog, the tabindex is a little bit strange.

See below:

![image](https://user-images.githubusercontent.com/88981/70152980-20b2c800-16e9-11ea-87d0-f41f4980c0c5.png)

After I enter the **Migration Name** field, I was expected my keyboard focus jump to **Add Migration** button. I suggest change the tabIndex a bit to 1, 2, 4, 3.

### Steps to reproduce

1. [**EF Core Power Tools**] / [**Migrations Tool (preview)**]

### Further technical details
EF Core Power Tools version: `2.3.92.0`

Database engine: SQL Server

Visual Studio version: Visual Studio 2019 16.4.0

**Comment by ErikEJ** [comment]
You are a excellent beta tester!

**Comment by ErikEJ** [comment]
fixed in latest daily build
