### ISSUE TITLE
Geography field brought in as geometry field

### ISSUE THREAD

**Issue by dyardyGIT** [ErikEJ/EFCorePowerTools#321]
I just ran and my sql geography fields came in as Geometry. I was expecting it to be mapped to geography. Am i missing something or configuration?

I was using today's daily build version 2.3.102.0

"By default, spatial properties are mapped to geography columns in SQL Server. "

**Comment by ErikEJ** [comment]
@bricelam ?

**Comment by bricelam** [comment]
NetTopologySuite.Geometries.Geometry is used to represent both SQL Server geometry and geography columns.

**Comment by ErikEJ** [comment]
So by design!
