### ISSUE TITLE
Reverse Engineer 3.0 Crash.

### ISSUE THREAD

**Issue by pedrosanguineti** [ErikEJ/EFCorePowerTools#322]
Reverse Engineer checking "Use EF Core 3.0" crashes Visual Studio Community 2019

### Steps to reproduce
1. Right click a project.
2. Select EF Core Power Tools, then Reverse Engineer.
3. Choose the database connection.
4. Check "Use EF Core 3.0
5. Do not change anything and press Ok.
6. Do not change anything and press Ok.

Visual Studio will crash.

I wonder if it's related to some configuration in my project.

### Further technical details
EF Core Power Tools version: 2.3.92.0

Database engine: SQL Server

Visual Studio version: Visual Studio Community 2019, 16.4.0

.Net Core 3.0.0
EntityFrameworkCore 3.0.0

**Comment by ErikEJ** [comment]
Try uncheck use EF Core 3, what happens then?

**Comment by pedrosanguineti** [comment]
> Try uncheck use EF Core 3, what happens then?

It works correctly without checking EF Core 3.

**Comment by ErikEJ** [comment]
I am not able to reporduce, so need more information (logs/error messages) from you

**Comment by pedrosanguineti** [comment]
I attached vs activity log and the crash found in the event log. 
Visual Studio doesn't provide any information when it crashes, it just closes.

[log.txt](https://github.com/ErikEJ/EFCorePowerTools/files/3935140/log.txt)
[ActivityLog.txt](https://github.com/ErikEJ/EFCorePowerTools/files/3935141/ActivityLog.txt)

Thanks.

**Comment by ErikEJ** [comment]
Are you using a non-english VS installation?

**Comment by pedrosanguineti** [comment]
> Are you using a non-english VS installation?

Yes, spanish version.

**Comment by ErikEJ** [comment]
I attempted a fix (so we can see the real error) in the latest daily build

**Comment by pedrosanguineti** [comment]
> I attempted a fix (so we can see the real error) in the latest daily build

I installed the daily build ( Version 2.3.102.0) and followed the same steps, it's still crashing visual studio.
 
[EventLog.txt](https://github.com/ErikEJ/EFCorePowerTools/files/3935219/EventLog.txt)
[ActivityLog.txt](https://github.com/ErikEJ/EFCorePowerTools/files/3935220/ActivityLog.txt)

Thanks.

**Comment by ErikEJ** [comment]
The daily build is .103 !!

**Comment by pedrosanguineti** [comment]
Installed the last daily build, here is the error.

![image](https://user-images.githubusercontent.com/17322723/70377519-1add0280-18f4-11ea-9264-8d2cbfa66b95.png)

Thanks!

**Comment by pedrosanguineti** [comment]
Looks like a problem with the ralational model used in this project, which should be fixed, and not related to EF Core Power Tools.

Thanks a lot for your help!

**Comment by ErikEJ** [comment]
Yes, you have a duplicated foreign key, one should be removed.
