### ISSUE TITLE
Error: Could not load type 'ErikEJ.SqlCeScripting.Table' 

### ISSUE THREAD

**Issue by StevenBonePgh** [ErikEJ/EFCorePowerTools#323]
I am seeing an exception after selecting a sql lite database to reverse engineer

System.TypeLoadException: Could not load type 'ErikEJ.SqlCeScripting.Table' from assembly 'ISqlCeScripting, Version=3.5.2.15, Culture=neutral, PublicKeyToken=3681435cabd17ad2'.
   at ErikEJ.SqlCeToolbox.Helpers.RepositoryHelper.GetTablesFromRepository(DatabaseInfo dbInfo, Boolean includeViews)
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__3.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 117

### Steps to reproduce
Netstandard 2.0 library project
Microsoft.EntityFrameworkCore.Sqlite 2.26 package installed
Using SqlLite Provider (Simple for EF6 by ErikEJ)
Datasource set to valid .sqlite database
right-click on project, add/select the connection, use ef core 3.x unchecked press ok
output window shows above error
I tired with current version of package, then upgraded to the nightly build from link on project home page with same results.

### Further technical details
EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
Version 2.3.102.0

SQL Server Compact 4.0 in GAC - No
SQL Server Compact 4.0 DbProvider - No

SQL Server Compact 4.0 DDEX provider - No
SQL Server Compact 4.0 Simple DDEX provider - Yes

SQLite ADO.NET Provider included: 1.0.109.0
SQLite EF6 DbProvider in GAC - Yes

System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes

Database engine: SQlite

Visual Studio version:Visual Studio 2019 16.4.0

**Comment by ErikEJ** [comment]
@StevenBonePgh Do you also have my SQLite Toolbox installed?

**Comment by ErikEJ** [comment]
I have released an updated SQLite Toolbox to Marketplace, I believe that should solve the issue, pls re-one if not.

**Comment by StevenBonePgh** [comment]
That was the issue. Thank you for the quick turnaround!
