### ISSUE TITLE
SqlLite Reverse Engineer ValueGenerated for Autoincrement PK

### ISSUE THREAD

**Issue by StevenBonePgh** [ErikEJ/EFCorePowerTools#324]
I have a SqlLite db with a table with an autoincremented PK:
`[MyIdColumn] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL`

In OnModelCreating, I see this:
```
modelBuilder.Entity<MyEntity>(entity =>
            {
                entity.Property(e => e.MyIdColumn).ValueGeneratedNever();
            });
```
I would expect this to produce `ValueGeneratedOnAdd()` rather than `ValueGeneratedNever()`
Is there something I am missing?

### Further technical details
EF Core Power Tools version: 
Version 2.3.102.0

SQL Server Compact 4.0 in GAC - No
SQL Server Compact 4.0 DbProvider - No

SQL Server Compact 4.0 DDEX provider - No
SQL Server Compact 4.0 Simple DDEX provider - Yes

SQLite ADO.NET Provider included: 1.0.109.0
SQLite EF6 DbProvider in GAC - Yes

System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes

Database engine: SQlite
Microsoft.EntityFrameworkCore.Sqlite 2.2.6

Visual Studio version: Visual Studio 2019 16.4.0

**Comment by ErikEJ** [comment]
Could be a bug, this is how the PK is determined: https://github.com/aspnet/EntityFrameworkCore/blame/master/src/EFCore.Sqlite.Core/Scaffolding/Internal/SqliteDatabaseModelFactory.cs#L353 - what happens if you try with EF Core 3 scaffolding?

**Comment by ErikEJ** [comment]
Ah - it is an old bug: https://github.com/aspnet/EntityFrameworkCore/issues/11961 - with no immediate fix in sight. @bricelam

**Comment by StevenBonePgh** [comment]
Is this within the realm of something that can be overridden using handlebars?

**Comment by ErikEJ** [comment]
I doubt it.
