### ISSUE TITLE
Configuring Base Classes

### ISSUE THREAD

**Issue by GregRotman** [ErikEJ/EFCorePowerTools#325]
Is there a way to configure which base class an entity inherits from?  I would like to have different base classes for different entities.

For obviously contrived example:
public class EntityBase
{
    public byte[] Version
    public string VersionString { get => System.Text.Encoding.UTF8.GetString(Version);  } 
    public void SetVersion (string versionString)
    {
       Version = System.Text.Encoding.GetBytes(versionString);
    }
}

public class EntityBaseOther
{
     public void SomeOtherHelperMethod() 
     {
          DoStuff();
     } 
}

public class Account : EntityBase
{
 
} 
public class AccountType: EntityBaseOther
{

}

**Comment by ErikEJ** [comment]
I think the Handlebars templates only allow you to configure a single base class. But it sounds like you are moving away from Database First?

**Comment by GregRotman** [comment]
First off, thank you for such fast reply even on a weekend.  Rockstar!

Second, perhaps you're right on design.  However, I updated my example to better illustrate why I was trying to branch from alternative base classes.  Not every table would have a timestamp, so a common base class would not work.

Maybe this is a better question for Handlebars, then, but it didn't look like they could scaffold from a dacpac which is what I am doing.  Is it possible to introduce custom tags and maybe an if statement?  Something like this in the class.hbs file:

`{{> imports}}

namespace {{namespace}}
{
{{#if class-annotation}}
{{{class-annotation}}}
{{/if}}
{{if class-versionedBase}}
    public partial class {{class}} : EntityBase
{{else}}
   public partial class {{class}} : EntityBaseOther
{{/if}}
    {
        {{{> constructor}}}
        {{{> properties}}}
    }
}
`

**Comment by ErikEJ** [comment]
@tonysneed  ? Doubt it, though.

**Comment by tonysneed** [comment]
There are a few ways to accomplish this (custom template data, overriding some methods). You can open an issue on my repo and I’ll answer there. https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars
