### ISSUE TITLE
"Migration Tool Preview" crashes before showing actual error message

### ISSUE THREAD

**Issue by Kundan22** [ErikEJ/EFCorePowerTools#326]
Describe what is not working as expected.

### Steps to reproduce
**Right click on main .net core project and click "Migration Tool Preview" and it throws attached error before showing actual error messagebox**

![Err1](https://user-images.githubusercontent.com/31039343/70455296-56223180-1aac-11ea-9a7d-1d9ae297c7b1.PNG)
![msg](https://user-images.githubusercontent.com/31039343/70455297-56bac800-1aac-11ea-8ded-e0d7a622a089.PNG)

### Further technical details
EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
**2.3.92.0**
Database engine: (SQlite, SQL Compact, SQL Server, Postgres)
**SQLServer2017**
Visual Studio version: (e.g. Visual Studio 2017 15.7)
**VS2019**

**Comment by ErikEJ** [comment]
Fixed in latest daily build
