### ISSUE TITLE
Support for temporal tables

### ISSUE THREAD

**Issue by rs17x** [ErikEJ/EFCorePowerTools#328]
Hi!
Would it be possible to modify the reverse engineering, so that temporal tables are supported?
Currently I run the reverse engineer and then delete the SysStartTime and SysEndTime properties from the generated classes. If not, the insert/update commands will fail with this error:
_SqlException: Cannot insert an explicit value into a GENERATED ALWAYS column in table 'TradingPM.main.FundManager'. Use INSERT with a column list to exclude the GENERATED ALWAYS column, or insert a DEFAULT into GENERATED ALWAYS column._

Here is a sample table:

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[InitiatorHistory](
	[InitiatorID] [int] NOT NULL,
	[InitiatorName] [nvarchar](128) NOT NULL,
	[Comment] [nvarchar](256) NULL,
	[LastUpdatedBy] [nvarchar](128) NOT NULL,
	[LastUpdatedAt] [datetime] NOT NULL,
	[SysStartTime] [datetime2](7) NOT NULL,
	[SysEndTime] [datetime2](7) NOT NULL
) ON [PRIMARY]
GO
ALTER AUTHORIZATION ON [dbo].[InitiatorHistory] TO  SCHEMA OWNER 
GO
CREATE CLUSTERED INDEX [CIX_dbo_InitiatorHistory_ID_PERIOD_COLUMNS] ON [dbo].[InitiatorHistory]
(
	[SysEndTime] ASC,
	[SysStartTime] ASC,
	[InitiatorID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Initiator](
	[InitiatorID] [int] IDENTITY(1,1) NOT NULL,
	[InitiatorName] [nvarchar](128) NOT NULL,
	[Comment] [nvarchar](256) NULL,
	[LastUpdatedBy] [nvarchar](128) NOT NULL,
	[LastUpdatedAt] [datetime] NOT NULL,
	[SysStartTime] [datetime2](7) GENERATED ALWAYS AS ROW START NOT NULL,
	[SysEndTime] [datetime2](7) GENERATED ALWAYS AS ROW END NOT NULL,
 CONSTRAINT [PK_dbo_Initiator] PRIMARY KEY NONCLUSTERED 
(
	[InitiatorID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
	PERIOD FOR SYSTEM_TIME ([SysStartTime], [SysEndTime])
) ON [PRIMARY]
WITH
(
SYSTEM_VERSIONING = ON ( HISTORY_TABLE = [dbo].[InitiatorHistory] )
)
GO
ALTER AUTHORIZATION ON [dbo].[Initiator] TO  SCHEMA OWNER 
GO
SET ANSI_PADDING ON
GO
CREATE UNIQUE CLUSTERED INDEX [CIX_dbo_Initiator] ON [dbo].[Initiator]
(
	[InitiatorName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Initiator] ADD  CONSTRAINT [DF_dbo_Initiator_LastUpdatedBy]  DEFAULT (suser_name()) FOR [LastUpdatedBy]
GO
ALTER TABLE [dbo].[Initiator] ADD  CONSTRAINT [DF_dbo_Initiator_LastUpdatedAt]  DEFAULT (getdate()) FOR [LastUpdatedAt]
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Primary Key of table [dbo].[Initiator]' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'Initiator', @level2type=N'COLUMN',@level2name=N'InitiatorID'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Initiator name' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'Initiator', @level2type=N'COLUMN',@level2name=N'InitiatorName'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Any additional comment to [dbo].[Initiator]' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'Initiator', @level2type=N'COLUMN',@level2name=N'Comment'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'last updated by' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'Initiator', @level2type=N'COLUMN',@level2name=N'LastUpdatedBy'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'last updated at' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'Initiator', @level2type=N'COLUMN',@level2name=N'LastUpdatedAt'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Start period' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'Initiator', @level2type=N'COLUMN',@level2name=N'SysStartTime'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'End Period' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'Initiator', @level2type=N'COLUMN',@level2name=N'SysEndTime'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Initiator table' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'Initiator'
GO

Thanks and best regards

**Comment by ErikEJ** [comment]
Potentially, if you are generating from a data base project / dacpac

**Comment by scorpion86** [comment]
I have the same problem is there anyway?

**Comment by scorpion86** [comment]
ALTER TABLE [dbo].[Table] ALTER COLUMN [StartTime] ADD HIDDEN;
If you use this script then reverse engineer will not use this column.

**Comment by rs17x** [comment]
ADD HIDDEN works :-) Thanks a lot!!!
