### ISSUE TITLE
CodeTemplates.zip How to include

### ISSUE THREAD

**Issue by Hsu-Cheng-Wei** [ErikEJ/EFCorePowerTools#329]
Hello I track your code, because i want to develop some tools likes "EFCorePoewerTools", now I have a problem that is why your Extension Package CodeTemplates.zip can install with extension,
but in my project that can't include to executing path, when I use "Assembly.GetExecutingAssembly().Location" Could you tell me how did you do it?
I would appreciate it if you could help me with this problem.

### Further technical details
EF Core Power Tools version: 2.3.9.2.0

Database engine: SQL Server
Visual Studio version: Visual Studio 2019

**Comment by ErikEJ** [comment]
I set the .zip file to "Include in VSIX" in the csproj file:

    <Content Include="CodeTemplates.zip">
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
