### ISSUE TITLE
Consider "Remove Migration" 

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#33]
@bricelam - at what point in the GUI would a "remove migration" option make sense?

Maybe an additional button on step 2?

https://github.com/ErikEJ/EFCorePowerTools/wiki/Migrations-Tool

**Comment by bricelam** [comment]
On step 2 makes the most sense to me from a workflow perspective. Technically, it could be on all three. Maybe it's obscure enough to require a new option (next to Migration Tool)

**Comment by ErikEJ** [comment]
Think I will wait until there is a demand - looks like it just removes a few files from the project !?

**Comment by bricelam** [comment]
It removes the latest migration and uses the previous migration for the new model snapshot. Waiting for demand sounds good. I'm not sure how many people use it regularly. It's possible to use a workflow that avoids it entirely.

**Comment by ErikEJ** [comment]
Closing for now
