### ISSUE TITLE
DbContext is placed in Models path when DbContext path is not specified

### ISSUE THREAD

**Issue by jasoneisen** [ErikEJ/EFCorePowerTools#330]
When specifying a Model path and not a DbContext path, the DbContext is placed in the Models path rather than at the project root.

### Steps to reproduce
Reverse Engineer Models & DbContext only specifying a Models path.

### Further technical details
EF Core Power Tools version: 2.3.92.0

Database engine: SQL Server

Visual Studio version: 2019 (16.4.2)

**Comment by ErikEJ** [comment]
I think it is by design...

**Comment by jasoneisen** [comment]
How would one specify to put the DbContext at the project root while supplying a Models path?  I tried using "\" but it is still placed in the Models path.

**Comment by jasoneisen** [comment]
I was just able to get it to work by using "."

If this is by design, documentation about this would be helpful.

**Comment by ErikEJ** [comment]
Thanks, I will link to this issue from the wiki post.

**Comment by ErikEJ** [comment]
Docs updated, thanks!
