### ISSUE TITLE
broken: Customize code using handlebars templates

### ISSUE THREAD

**Issue by juergenil** [ErikEJ/EFCorePowerTools#331]
In the current daily build an exception is thrown, if option "customize code using handlebars templates" is selected.

### Steps to reproduce
- Library Project .Net Standard 2.0
- Select reverse engineer, mark use EF Core 3.x,, select a database and one table
- activate option "customize code using handlebars templates"
- press OK
- an exception is thrown:
System.Exception: Reverse engineer error: 
System.TypeLoadException: Method 'WriteCode' in type     
'EntityFrameworkCore.Scaffolding.Handlebars.NullCSharpDbContextGenerator' from assembly     
'EntityFrameworkCore.Scaffolding.Handlebars, Version=3.0.0.0, Culture=neutral,      
PublicKeyToken=b10b51e7b9be6a2e' does not have an implementation.     
at Microsoft.EntityFrameworkCore.Design.ServiceCollectionExtensions.AddHandlebarsScaffolding(IServiceCollection services, ReverseEngineerOptions options, LanguageOptions language)
   at ReverseEngineer20.ReverseEngineer.ServiceProviderBuilder.Build(ReverseEngineerCommandOptions options) in C:\Code\EFCorePowerTools\src\GUI\efreveng\ReverseEngineer\ServiceProviderBuilder.cs:line 32
   at ReverseEngineer20.ReverseEngineer.ReverseEngineerRunner.GenerateFiles(ReverseEngineerCommandOptions reverseEngineerOptions) in C:\Code\EFCorePowerTools\src\GUI\efreveng\ReverseEngineer\ReverseEngineerRunner.cs:line 19
   at efreveng.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efreveng\Program.cs:line 33
   bei    
ReverseEngineer20.ReverseEngineer.EfRevEngLauncher.BuildResult(String output)     
bei     
ReverseEngineer20.ReverseEngineer.EfRevEngLauncher.GetOutput()
bei    
ReverseEngineer20.EfCoreReverseEngineer.LaunchExternalRunner(ReverseEngineerOptions options)
bei     
ReverseEngineer20.EfCoreReverseEngineer.GenerateFiles(ReverseEngineerOptions reverseEngineerOptions, Boolean includeViews)
bei     
EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__3.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:Zeile 235.

### Further technical details
- EF Core Power Tools version: 2.3.104.0 (current daily build)
- Database engine: SQL Server 2017
- Visual Studio Community 2019 V 16.4.2 (German version)

### Remark
Reason seems to be related to the following commit (Use 3.1 to get the latest bug fixes):     
https://github.com/ErikEJ/EFCorePowerTools/commit/5f787cf3be4a1f2ce5b06b7fa4a3538a9ae0efd8
When rebuilding with this commit reverted, handlebars are working like expected.

**Comment by ErikEJ** [comment]
@tonysneed have you tested / updated to 3.1?

**Comment by tonysneed** [comment]
Not yet. I’ll update to 3.1 tomorrow.

**Comment by ErikEJ** [comment]
But I wonder if that is the issue?

**Comment by ErikEJ** [comment]
Looks like a general Handlebars issue: https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars/issues/94 and https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars/issues/95

**Comment by tonysneed** [comment]
@ErikEJ I'll look into the Handlebars issue. In the meantime, I updated to EF Core 3.1 with [v3.6 ](https://www.nuget.org/packages/EntityFrameworkCore.Scaffolding.Handlebars/3.6.0)of my NuGet package. Note that the package includes a new version of the DbImports.hbs template file.

**Comment by ErikEJ** [comment]
There is no general Handlebars issue, just 3.1 compat issue

**Comment by ErikEJ** [comment]
Fixed in latest daily build

**Comment by juergenil** [comment]
Thank you for the quick response.     
Unfortunately, for me current daily build V 2.3.105 shows the same behavior.     
Maybe it's necessary to include file efreveng.exe.zip into the commit?

**Comment by ErikEJ** [comment]
Of course, that needs to be updated!
