### ISSUE TITLE
Remove stored database connections from the Choose Database Connection window

### ISSUE THREAD

**Issue by intomneato** [ErikEJ/EFCorePowerTools#332]
I am using a C# core application and using this tool to reverse engineer my azure sql server database. When I right click on my project and select Reverse Engineer the "Choose Database Connection" window comes up. I have accumulated multiple stored connections. Some are simply not needed anymore, left over from development and beta environments that no longer exist. Now we have had to change the password for the connection to our current environment and I cannot see how to edit or remove stored connections to get down to just the one correct one needed. I have tried uninstalling and reinstalling the extension but the stored connections still persist. I have looked through the files in the extension installation location and the project folder and have not noticed any kind of file these connections would be stored in. How do I remove or edit these stored connections?  Thanks.

**Comment by ErikEJ** [comment]
Open Server Explorer

**Comment by intomneato** [comment]
That did it. Thank you!!

**Comment by ErikEJ** [comment]
A button to quickly remove a connection has been added to the latest daily build.
