### ISSUE TITLE
Adding Migration failed, MissingMethodException, DesignTimeServicesBuilder..ctor (EF Core 3.1)

### ISSUE THREAD

**Issue by 304NotModified** [ErikEJ/EFCorePowerTools#334]
After pressing "Add migration", I get a MissingMethodException

### Steps to reproduce

csproj relevant parts:

```xml
  <PropertyGroup>
    <TargetFrameworks>netcoreapp2.1;netstandard2.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="3.1.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.0" />
  </ItemGroup>
```

![image](https://user-images.githubusercontent.com/5808377/72159192-1eb0e880-33bc-11ea-99f9-d76737965e52.png)

![image](https://user-images.githubusercontent.com/5808377/72159215-2b354100-33bc-11ea-8465-7f79763674ac.png)

![image](https://user-images.githubusercontent.com/5808377/72159223-2e303180-33bc-11ea-8758-d1a6e7adb925.png)

### Further technical details
EF Core Power Tools version: 

(latest daily build, first  tried with VS marketplace version)

```
Version 2.3.106.0

SQL Server Compact 4.0 in GAC - No
SQL Server Compact 4.0 DbProvider - No

SQL Server Compact 4.0 DDEX provider - No
SQL Server Compact 4.0 Simple DDEX provider - Yes


SQLite ADO.NET Provider included: 1.0.110.0
SQLite EF6 DbProvider in GAC - No

System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes

```

Database engine: SQL Server

Visual Studio version:  Visual Studio 2019 16.3.5

related? https://github.com/dotnet/efcore/issues/19157

Note, also tried

```xml
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="3.1.0">
      <PrivateAssets>all</PrivateAssets>
      <!--<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>-->
    </PackageReference>
```

from: https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#dip

**Comment by ErikEJ** [comment]
It is because you are using EF Core 3.0 from a .NET Core 2.2 app

**Comment by 304NotModified** [comment]
So switch to .NET Core 3.1?

**Comment by ErikEJ** [comment]
Or 3.0, yes

**Comment by 304NotModified** [comment]
works! Thanks! 👍
