### ISSUE TITLE
Please update the wiki for EF Core 3.1

### ISSUE THREAD

**Issue by 304NotModified** [ErikEJ/EFCorePowerTools#335]
Please update the wiki (https://github.com/ErikEJ/EFCorePowerTools/wiki) for EF Core 3.1

(mention that .NET Core 3.0/3.1 is required)

See https://github.com/ErikEJ/EFCorePowerTools/issues/334

(or make it public editable)

**Comment by ErikEJ** [comment]
Sadly, wikis can only be edited by contributors

**Comment by 304NotModified** [comment]
You could make it public of course, 

- Repo settings: (should be https://github.com/ErikEJ/EFCorePowerTools/settings)
- uncheck "Restrict editing to users in teams with push access only "

![image](https://user-images.githubusercontent.com/5808377/72163024-4b1c3300-33c3-11ea-8bd2-1c62b62706ef.png)

**Comment by jespersh** [comment]
btw, there's various ideas on how to make wikis with pull requests. Here's one: https://www.growingwiththeweb.com/2016/07/enabling-pull-requests-on-github-wikis.html

**Comment by ErikEJ** [comment]
Thanks, will leave as is for now
