### ISSUE TITLE
Generate Entity and property comments

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#337]
See https://github.com/dotnet/efcore/issues/19113

**Comment by ErikEJ** [comment]
@bricelam What's your opinion: should I just always do this, or make it optional? 
I am leaning against always until someone gives a good reason not to.

**Comment by ErikEJ** [comment]
This is now in latest daily build (always enabled)

**Comment by Gambero81** [comment]
Hi @ErikEJ , there is a sample to use this feature?

Where are read comments added to classes and properties? there are some settings to do in sql server db schema?

Thanks

**Comment by ErikEJ** [comment]
You can use SSMS to set the extended property MS_Description or the table designer or use sp_addextendedproperty.

**Comment by Gambero81** [comment]
@ErikEJ thanks!
