### ISSUE TITLE
getting xml page instaed of model diagram

### ISSUE THREAD

**Issue by tnlthanzeel** [ErikEJ/EFCorePowerTools#338]
Hi  Erik, 

i dont understand why i get an xml page when i right click on my dbcontext class->ef core power tools->add dbconteext model diagram. i get huge xml view with the file extension .dgml

![image](https://user-images.githubusercontent.com/18216790/72768601-f0ce6e00-3c1d-11ea-8a7b-209bede89771.png)

**Comment by ErikEJ** [comment]
You need to add the DGML viewer to your VS installation: https://stackoverflow.com/questions/43405698/directed-graph-markup-language-no-longer-recognized-with-visual-studio-2017

**Comment by tnlthanzeel** [comment]
it worked!!! thanks @ErikEJ
