### ISSUE TITLE
Support excluding columns for reverse engineering

### ISSUE THREAD

**Issue by amtandon** [ErikEJ/EFCorePowerTools#339]
Need the ability to exclude columns from tables during reverse engineering.

**Comment by ErikEJ** [comment]
Please explain why you need this

**Comment by amtandon** [comment]
@ErikEJ The main use case that I need it for is to exclude temporal table columns. Other scenarios would be to exclude Id columns and audit columns like updatedby and updatedate as these can be abstracted out into a base class.

I understand that I can "HIDE" the column at the data base level, but that is not possible in my case as the DB control is not in my hands.

**Comment by ErikEJ** [comment]
This is something that needs to be implemented in EF Core. As a workaround, you can create a SQL Database project from the database that is not in your control, mark the relevant columns hidden, and generate the DbContext and Entity classes from the database project.

**Comment by ErikEJ** [comment]
@amtandon Implemented now!
