### ISSUE TITLE
[Feature] Make Reverse Engineer available as a .NET Core command line tool

### ISSUE THREAD

**Issue by ng-julien** [ErikEJ/EFCorePowerTools#340]
En tant qu'utilisateur de l'IDE Rider, je souhaite pouvoir utiliser l'extensions qui aujourd'hui est disponible que pour Visual Studio

**Comment by jespersh** [comment]
I got zero knowledge about Rider, its plugins or how they're developed. Is it even C#?

**Comment by ErikEJ** [comment]
I am planning a .net Core command line version of the reverse engineering feature.

**Comment by ErikEJ** [comment]
(Actually, that is what the EF Core 3.0 reverse engineering is now, just not with a published API/docs)

**Comment by divinebovine** [comment]
I would like a way to use this tool outside of VS, in particular the DGML graph generation.

**Comment by ErikEJ** [comment]
@divinebovine That feature is already available as a NuGet package!

**Comment by jamshally** [comment]
Hi @ErikEJ. Firstly, great tool, thanks for building and sharing.

I am also interested in a command-line option for the reverse-engineering feature. For context: I have a .Net Core WebAPI and TypeScript SPA stack, and have several points up the stack where I auto-generate, using your tool, and others (such as nSwag). It would be nice timesaver to be able to initiate these from the command line, as this would allow combining multiple actions into one command.

Related - I am trying to understand this comment you made:

> (Actually, that is what the EF Core 3.0 reverse engineering is now, just not with a published API/docs)

Is this saying that the EF Core 3.0 reverse engineering command is the same as the EFCorePowerTools command?

Thanks

**Comment by ErikEJ** [comment]
>> Is this saying that the EF Core 3.0 reverse engineering command is the same as the EFCorePowerTools command?

No, what I meant to say was, that internally in Power Tools, the EF Core 3 (and 5) reverse engineering functionality is a undocumented command line tool, that runs of a json file similar to the efpt.config.json file (but not the exact same format), obviously support the many more options available with EF Core Power Tools. (Hope that makes sense?)

**Comment by jamshally** [comment]
@ErikEJ - thanks for your reply. 

So, if I understand correctly, you are saying that there is a reverse engineering command line capability already, it is just not documented - and that, if I look at the code, I could use that as a guide for how to do it? I had a quick look, and couldn't easily see what source code was a good start point for understanding that. Could you point me at a good place to start?

So, does the EFCorePowerTools Reverse Engineering using EF Core Reverse Engineering under the hood, or is the command line tool to which you refer custom EFCorePowerTools code? Sorry if this should be obvious already from your answers - there is a lot of "EF Core" naming collision that is making me unsure!

**Comment by ErikEJ** [comment]
First, clone the repo and open in Visual Studio - navigating semi-complex code in GitHub is a bad idea!

This is the entry point for the 3.1 command line tool: https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/efreveng/Program.cs

As I said earlier, I am not planning to document this, so you must be able to read and understand.

The tool has two purposes: 
Provide a list of tables in the provider (based on a connection string and database type)
Generate code files, and return a list of the generated files.

when generating files, the tool is called with a a path to a json serialized file, containing an instance of this class:
https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/RevEng.Shared/ReverseEngineerCommandOptions.cs

The tools is incldued in the vsix package (which is just a .zip file) as this file: https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/lib/efreveng.exe.zip

If you want EF Core 5 (limited) reverse engineering, you must also unpack this .zip file on top:
https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/lib/efreveng50.exe.zip 

The unpacking happens here: (runs inside VS): https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/EFCorePowerTools/Handlers/ReverseEngineer/EfRevEngLauncher.cs#L179 

Please let me know if this makes things "clearer" - it's a slightly complicated (but required) way to do this.

Under the hood, I use the built-in reverse engineering (to avoid duplication of effort) - but EF Core Power Tools supports many more options than the built-in (EF Core) command line tool.
 


Let me know if this is unclear.

**Comment by jamshally** [comment]
@ErikEJ - makes sense, that is exactly what I was looking for. Thanks for taking the time to respond in detail like that!

**Comment by ErikEJ** [comment]
No current plans to do this

**Comment by murugaratham** [comment]
Would love to see a cli, as I use vscode rather than visual studio

**Comment by ErikEJ** [comment]
@murugaratham why are you unable to use the built-in EF Core Tools?

**Comment by MrMuMu** [comment]
@ErikEJ  is there anyway to select all tables on the runtime rather than passing from options file for the cli?
Also it would be very nice to have if we could install either as extension for vscode or as dotnet tool from nuget.

**Comment by ErikEJ** [comment]
@MrMuMu What are you missing from the built-in EF Core tools?

It includes all tables by default.

**Comment by MrMuMu** [comment]
splitting to EntityTypeConfiguration

**Comment by ErikEJ** [comment]
Thanks! 
Maybe one day, when things get more stable. You can do it today, just not documented/supported.

**Comment by MrMuMu** [comment]
What can I do today? I am not sure if I understood your answer.
1- I can not split in EF Core Tools
2- Is there anyway to make Power Tools to fetch all table if there are not tables provided?

**Comment by ErikEJ** [comment]
Ah, I see. 
That sounds like a useful feature request!

Please post a new issue with that, if it is something you would like to see.

**Comment by suntereo** [comment]
Erik, just wanted to say thank you for having a command line tool! I was able to get it working and am planning to include it in our Azure pipeline build process as a way of (1) ensuring our models are always up to date with the DB backend and (2) notifying us by way of build errors when changes are made to the DB that affect model expectations (fields renamed, stored proc parameters being added/removed, etc.). We have many hands in the code and sometimes mistakes like this happen, so I'm glad to find this undocumented solution!

**Comment by ErikEJ** [comment]
@suntereo you are welcome and glad you find it useful. 

And I hope you appreciate why I keep it "undocumented"

**Comment by ErikEJ** [comment]
For anyone watching this issue, this is now planned, and you can find a design proposal [here](https://github.com/ErikEJ/EFCorePowerTools/issues/1751) - looking forward to any comments/suggestions.

**Comment by ErikEJ** [comment]
Preview 1 of the CLI tool is [now available](https://www.nuget.org/packages/ErikEJ.EFCorePowerTools.Cli/7.0.0-preview1#readme-body-tab)

![image](https://user-images.githubusercontent.com/4169187/234258058-2b6def58-f87c-455a-93da-21cd09d9e3f7.png)
