### ISSUE TITLE
Add database connection not sticking

### ISSUE THREAD

**Issue by dyardyGIT** [ErikEJ/EFCorePowerTools#342]
Added connection choice does not appear in the dropdown list for connections (after setting one with Add)

### Steps to reproduce
Going to reverse engineer option
Select 'Add' and picking odbc option and dsn
Test Connection all good
It returns me back to 'Choose Database Connection' and it is not in the list of connections.

### Further technical details
version 2.3.102.0

Database engine: Postgres

Visual Studio version: 16.4.3

**Comment by dyardyGIT** [comment]
I **also** added to Server Explorer the connection, restarted the EF Power Tools and the connection is not in the list of connections.

**Comment by ErikEJ** [comment]
There is no "ODBC" EF Core provider, and the list only includes connections defined for supported providers.

**Comment by ErikEJ** [comment]
So you need to install the Postgres DDEX provider https://www.npgsql.org/doc/ddex.html

**Comment by dyardyGIT** [comment]
Let me try this. 

> So you need to install the Postgres DDEX provider https://www.npgsql.org/doc/ddex.html

**Comment by jespersh** [comment]
@ErikEJ are these required providers links written down somewhere? Asking because I can't seem to find it

**Comment by ErikEJ** [comment]
@jespersh They are documented here (in the reverse engineer manual, so to speak) - https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering
