### ISSUE TITLE
[Feature] Support a few DbContext in single projects

### ISSUE THREAD

**Issue by guffy1234** [ErikEJ/EFCorePowerTools#345]
Hi

Imagine that you have to develop a solution that deals with a few databases. 
With the current implementation, you have to create a separate VS project per database for reverse engineering those databases to EF contexts and models. Or manually change settings when you need to reverse each database.
I think it probably would be nice to have the more convenient ability to reverse engineer multiple databases to a single VS project. This means the config file has to have an array of settings.

**Comment by ErikEJ** [comment]
I actually think it makes sense to have a separate project per DbContext, for good separation of concerns.

**Comment by guffy1234** [comment]
ok then

**Comment by ErikEJ** [comment]
@guffy1234 
The latest daily build allows you to use multiple efpt.config.json files in the same project - https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#saving-options-and-running-the-second-time
