### ISSUE TITLE
Computed column appears when reverse engineered directly from database but not from database project

### ISSUE THREAD

**Issue by Thomasov** [ErikEJ/EFCorePowerTools#346]
I have a table that is roughly of this structure (yes I know it's very ugly I inherited it)
`CREATE TABLE [dbo].[Person](
	[Id] [uniqueidentifier] NOT NULL,
	[PersonnelId] [uniqueidentifier] NOT NULL,
	[FirstName] [varchar](25) NOT NULL,
	[LastName] [varchar](25) NOT NULL,
	[MiddleName] [varchar](25) NULL,
	[Title] [varchar](50) NULL,
	[Name]  AS (case when [PersonnelId]='C0DEC0DE-C0DE-C0DE-C0DE-C0DEC0DEC0DE' then concat(upper(substring([FirstName],(1),(1))),lower(substring([FirstName],(2),len([FirstName]))),' ',upper(substring([LastName],(1),(1))),lower(substring([LastName],(2),len([LastName])))) else concat(upper(substring([LastName],(1),(1))),lower(substring([LastName],(2),len([LastName]))),', ',upper(substring([FirstName],(1),(1))),lower(substring([FirstName],(2),len([FirstName]))),nullif(concat(' ',upper(substring([MiddleName],(1),(1))),lower(substring([MiddleName],(2),len([MiddleName])))),' '),nullif(concat(' ',upper([Title])),' ')) end),
 CONSTRAINT [PK_Person] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]`

When I generate entities for this table directly from the database, the generated entity has this property:
`        [Required]
        [StringLength(132)]
        public string Name { get; set; }`
But when i generate from the database project, which has been created directly from the database with the same schema including the computed column, the column does not appear and is erased if it already existed.

**Comment by ErikEJ** [comment]
I think it is a known (but not documented) limitation of the .dacpac approach. Could you create a repro dapac, and I can investigate?

**Comment by ErikEJ** [comment]
No repro provided, feel free to re-open if you can provide one.
