### ISSUE TITLE
Different namespaces in database first?

### ISSUE THREAD

**Issue by jordisan** [ErikEJ/EFCorePowerTools#347]
I think it's not possible to generate different namespaces depending on every table (in the same schema) when reverse engineering from database. That would be great; for example, as an extra property in ep.renaming.json:

```
[
  {
    "UseSchemaName": false,
    "SchemaName": "dbo",
    "Tables": [
      {
        "Name": "Tbl_settings_values",
        "NewName": "SettingValue",
        "Namespace": "Front.Settings"
[...]
```
Or... do you think it would be possible somehow using handlebars templates and helpers? I'm afraid this would affect the generated models but not their references in context class.

Thanks!

**Comment by ErikEJ** [comment]
Please provide a sample of what you would expect the generated classes to look like

**Comment by jordisan** [comment]
Using that sample, the generated class would be something like

```
namespace Front.Settings
{
[Table("Tbl_settings_values", Schema = "dbo")]
    public partial class SettingValue
    {

```
Every table might have a different namespace, and the references in the dbcontext would use them in order to make them work.

**Comment by ErikEJ** [comment]
This is not something I am planning to support
