### ISSUE TITLE
Allow non-nullable strings with default values to be not required when using DataAnnotations

### ISSUE THREAD

**Issue by peterhamilton-cpx** [ErikEJ/EFCorePowerTools#348]
Hi there.

We love the EF Core Power Tools.  However, I may have found an issue.  But, if there is a workaround, I would love hear it.

### Steps to reproduce
Design a table in SQL Server with a column as "not null" and add a default value.  When the Power Tools (3.1) reverse engineers the table, with the "Use Data Annotations" option, the [Required] annotation is added to the field in the generated code, and even though the database has a default value, the generated code just says the field is required and the Entity won't save records without removing the [Required] annotation..

### Further technical details
![image](https://user-images.githubusercontent.com/58074761/74964231-17c8bd00-53e1-11ea-89ab-63879da4f318.png)

Database engine: (SQlite, SQL Compact, SQL Server, Postgres)

Visual Studio version: (e.g. Visual Studio 2017 15.7)

**Comment by ErikEJ** [comment]
I think #160 is related

**Comment by peterhamilton-cpx** [comment]
Hi Erik,

Thanks for getting back to me so quickly.

I don't think that #160  is related.  The issue I am having is that any columns which are NOT NULL but have a default value set in the SQL table don't save unless I set a value in the payload prior to a PATCH or PUT request.  

Below is the script for the database (the Description column is in the 'Books' table, it is NOT NULL but has a default value of '':
[SimpleBooks_DBCreate.txt](https://github.com/ErikEJ/EFCorePowerTools/files/4236280/SimpleBooks_DBCreate.txt)

When I enter a Book directly through SQL Enterprise Manager the item is saved with an empty string as the value of the Description column.

Below are the settings I used to reverse-engineer with the EF Core Power Tools:
![image](https://user-images.githubusercontent.com/58074761/75039441-b824ed00-5486-11ea-83dc-76348d4530d4.png)

Below are the PATCH tests I ran through PostMan against the API:
![image](https://user-images.githubusercontent.com/58074761/75039343-74ca7e80-5486-11ea-8cf9-04c319d1460b.png)

**Comment by ErikEJ** [comment]
Please share a create table script!

**Comment by peterhamilton-cpx** [comment]
Hi again,

I included the script in the reply about (it is attached as SimpleBooks_DBCreate.txt).

I hope that helps!

**Comment by ErikEJ** [comment]
That file does not have a CREATE TABLE statement!

**Comment by peterhamilton-cpx** [comment]
My bad.  Sorry about that.  Here is the entire DB scripted out.

[SimpleBooks_DBCreate.txt](https://github.com/ErikEJ/EFCorePowerTools/files/4236652/SimpleBooks_DBCreate.txt)

**Comment by ErikEJ** [comment]
Still no create table statement !?

**Comment by peterhamilton-cpx** [comment]
All of the CREATE TABLE statements are in the previously attached SimpleBooks_DBCreate.txt file.  
The one to look for is:

CREATE TABLE [dbo].[Books](
	[BookId] [int] IDENTITY(1,1) NOT NULL,
	[BookName] [varchar](100) NOT NULL,
	[PublisherId] [int] NOT NULL,
	[CategoryId] [int] NULL,
	[Description] [varchar](100) NOT NULL,
	[LastUpdated] [datetime] NOT NULL,
	[LastUser] [varchar](100) NOT NULL,
 CONSTRAINT [PK__Table__3DE0C2075223FD78] PRIMARY KEY CLUSTERED 
(
	[BookId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BooksAuthors]    Script Date: 2/21/2020 9:55:58 AM ******/
SET ANSI_NULLS ON
GO

**Comment by ErikEJ** [comment]
I think this is because you are using DataAnnotations for validation, and the Required attribute also kicks in for empty strings: https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.requiredattribute?view=netframework-4.8#remarks - so basically for Validation to pass, you must have a non-empty string.

**Comment by peterhamilton-cpx** [comment]
Yes, you are correct, we are using the "Use Data Annotations" option.  We use this because if we don't, we manually have to manually add the [Key] attributes for EF/OData to work.  We are trying to avoid having to manually 'tweak' the models/context for obvious reasons.

That being said, the DBContext that EF Core Power Tools generated from this database have their ".HasDefaultSql()" attributes set correctly from the source DB columns:
> entity.Property(e => e.Description)
>                     .IsUnicode(false)
>                     .HasDefaultValueSql("('')");
> 
> entity.Property(e => e.LastUpdated)
>                     .HasDefaultValueSql("(getdate())");
> 
> entity.Property(e => e.LastUser)
>                     .IsUnicode(false)
>                     .HasDefaultValueSql("(suser_sname())");
>           

I manually commented out the [Required] annotation in the Model class(es):

> //[Required]
> [StringLength(100)]
> public string Description { get; set; }
> [Column(TypeName = "datetime")]
> public DateTime LastUpdated { get; set; }
> //[Required]
> [StringLength(100)]
> public string LastUser { get; set; }
> 
And this is working as we would like, without having to pass the element to the API if there is a default value specified in the database. 

Would it be possible to have the EF Core Power Tools _not_ generate the [Required] annotation if the DB column is NOT NULL, but there is a default value specified?  The tool seems to be able to read the default values as it has generated the .HasDefaultValue() or .HasDefaultValueSql() attributes properly.  

Thanks again...

**Comment by ErikEJ** [comment]
What I am saying is that the [Required] attribute does not consider a empty string a valid required value - see https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.requiredattribute.allowemptystrings?view=netframework-4.8#System_ComponentModel_DataAnnotations_RequiredAttribute_AllowEmptyStrings - but setting the AllowEmptyStrings to true would work for you. You could say that maybe this should be scaffolded when you have a default of empty string defined on your table? See releated EF Core issue here: https://github.com/dotnet/efcore/issues/14279.

**Comment by peterhamilton-cpx** [comment]
Thanks again.

I forgot to mention that I tried adding the "AllowEmptyString" parameter to the [Required] annotation, but that still required me to add the field to the payload for saving.  

What we are looking for is that this behaves the same was as if we executed and INSERT statement from SQL.  If we don't provide the column in the INSERT statement, the record gets saved with the value set as the default.  By removing the [Required] annotation, and having the HasDefaultValueSql() attribute in the context class, this works perfectly in our API, just like SQL.

That is why I am asking whether this behaviour can be part of the code generated by the EF Core Power Tools.

**Comment by ErikEJ** [comment]
So the logic could be: if there is a default value defined on a NOT NULL string column, do not make it required - would that wor

**Comment by peterhamilton-cpx** [comment]
Yes, that would work!  The less we have to tweak the generated code the better.

**Comment by ErikEJ** [comment]
And you are generating from a live database or a SSDT project?

**Comment by peterhamilton-cpx** [comment]
Not running from SSDT.  The SimpleBooks_DBCreate.txt script attached previously was running from the SQL Server Express instance which was installed with Visual Studio.

**Comment by melihsen** [comment]
Hi Eric ,as a proposal, is it possible to include an option for [Required] attribute for the projects that use DB entities as view models. Some required fields are automatically generated by the server before inserting to DB and they are not expected from the users. When we use some entities as view model, they cause model state error.

**Comment by ErikEJ** [comment]
@melihsen yes, is that not what this issue is about?

**Comment by melihsen** [comment]
@ErikEJ yes, you're right but I thought that title seems general and it can contain this proposal as a small note.

**Comment by ErikEJ** [comment]
I will look into it!

**Comment by ErikEJ** [comment]
I have added some discussion here: https://github.com/dotnet/efcore/issues/13613#issuecomment-611926879

**Comment by ajcvickers** [comment]
@ErikEJ I've been trying to understand this thread. From what I can gather, if a property is marked required and has a store default, but no value is supplied, then EF will fail to save the entity. Which if I put in code looks something like this:

```C#
public class Blog
{
    public int Id { get; set; }
    
    [Required]
    public string EmailAddress { get; set; }
    
    [Required]
    public string Name { get; set; }
}
```
```C#
modelBuilder
    .Entity<Blog>()
    .Property(e => e.EmailAddress)
    .HasDefaultValueSql("N'baxter@cat.planet'");
```
But when I try to insert a new entity:
```C#
context.AddRange(
    new Blog { Name = "Baxter"}
);

context.SaveChanges();
```
this works and generates the following SQL:
```sql
Executed DbCommand (24ms) [Parameters=[@p0='Baxter' (Nullable = false) (Size = 4000)], CommandType='Text', CommandTimeout='30']
SET NOCOUNT ON;
INSERT INTO [Blog] ([Name])
VALUES (@p0);
SELECT [Id], [EmailAddress]
FROM [Blog]
WHERE @@ROWCOUNT = 1 AND [Id] = scope_identity();
```

So now I'm not sure what the actual problem is that needs to be solved?

**Comment by ErikEJ** [comment]
@ajcvickers  the issue is that the EF Core generated Required attribute is being used by asp.net Core model validation, by the user exposing the EF Core entities directly in the API.

**Comment by ajcvickers** [comment]
@ErikEJ So does this boil down to not really wanting the data annotations, but using them just to get `[Key]` scaffolded for OData?

**Comment by ErikEJ** [comment]
No, I think they use Required as well for validation for properties that really are required. For properties with default database values, required should not be there. Do I guess iimt is a more holistic definition of required that is asked for.

**Comment by ErikEJ** [comment]
And by "really required" I mean NOT NULL columns with no default value.

**Comment by ajcvickers** [comment]
@ErikEJ To me, this seems like the fundamental problem that all data annotations have--they are interpreted slightly differently by different consumers. This is why the fluent API always overrides, and why it is preferred for cases like this.

I have no idea how you would decide when a Required attribute should be used based on this--it seems like the application is the only thing that would know if it's appropriate or not.

**Comment by ErikEJ** [comment]
@peterhamilton-cpx Based on the discussion above, this is not something I am planning to fix. You can stop using ASP.NET Core model validation, and use something like FluentValidation instead, which would give you complete control of special cases of validation (and not interfer with the generated code).

**Comment by peterhamilton-cpx** [comment]
Thanks Erik.  I will investigate FluentValidation.  I appreciate your looking into this very much.

I hope you are staying safe and sane in these very unusual times....
