### ISSUE TITLE
Column name case changed in generated entity class

### ISSUE THREAD

**Issue by jefferyp1138A** [ErikEJ/EFCorePowerTools#349]
Describe what is not working as expected.

### Steps to reproduce
Include a complete description that I can redo to reproduce the issue.

### Further technical details
EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)

Database engine: (SQlite, SQL Compact, SQL Server, Postgres)

Visual Studio version: (e.g. Visual Studio 2017 15.7)

**Comment by ErikEJ** [comment]
Could you add more details, please?

**Comment by jefferyp1138A** [comment]
I need to reverse engineer a database that has pluralized table names and a very poor Hungarian notation-type naming convention for columns. 

Examples:
- "s" prefix for string (char, varchar)
- "i" prefix for integer columns
- "utc" prefix for DateTime columns storing values as UTC

The problem is the option to "Pluralize or singularize generated object names" changes the case of the column name. "sName" is generated as "SName", "iMaxLength" becomes "IMaxLength," etc. Because I have existing tests "sName" and "iMaxLength", I need the column casing preserved. But if I select Use table and column names directly from the database, then the generated entity class names are the same as the collection names in the DbContext. 

Example: 
public virtual DbSet<CurrencyCode> CurrencyCodes { get; set; } // desired 
- becomes - 
public virtual DbSet<CurrencyCodes> CurrencyCodes { get; set; } //undesirable

What I wish to happen is to singularize the entity class names but preserve the (admittedly stupid) camel-cased column names. Otherwise, I have to edit the tests and change the case on every filed.

Environment

- Windows 10 Enterprise [18362.592]
- Entity Framework Core Power Tools v [1.0](url)
- Visual Studio Enterprise 2019 v 16.4.5
- .Net Core 2.2
- Microsoft.EntityFrameworkCore v3.1.2, Microsoft.EntityFrameworkCore.SqlServer v3.1.2 and Microsoft.EntityFrameworkCore.Tools v3.1.2

**Comment by ErikEJ** [comment]
Why did you close this?

**Comment by jefferyp1138A** [comment]
Hi Erik,

I had an epic fail with Chrome and I did not intend to close the item.

I realize my issue is probably an edge case. It all boils down to changing from Camel Casing to Pascal Case is not the same as Singularizing or Pluralizing the Entity and Property names.

I don’t mean to say I’m unhappy with the tool. It saved me a lot of work. I did have to rename the classes so the name is singular. But that’s a lot less work than I would have had to do otherwise.

Thanks

Jeffery Pyle | Senior Software Engineer
Alogent
Mobile 913-708-0685

**Comment by jefferyp1138A** [comment]
I had an issue with Chrome when trying to attach a file. I see my first post might be confusing.

In the generated DbContext, 

public virtual DbSet<CurrencyCodes> CurrencyCodes { get; set; } // not desirable for collection and entity to have the same name.

Here is the generated code (names preserved)

[Table("CurrencyCodes", Schema = "Cfg")]
    public partial class CurrencyCodes
    {
        public CurrencyCodes()
        {
            FIConfiguration = new HashSet<FIConfiguration>();
        }

        [StringLength(3)]
        public string sCurrencyCode { get; set; }
        [Required]
        [StringLength(2)]
        public string sCurrencySymbol { get; set; }

        [InverseProperty("sCurrencyCodeNavigation")]
        public virtual ICollection<FIConfiguration> FIConfiguration { get; set; }
    }

You can see the bad naming convention for the columns but I am required to preserve it. To fix this problem I renamed the entity class files by removing the "s" at the name of the name. That is, I renamed CurrencyCodes.cs to CurrencyCode.cs and let visual studio update the code references.

I realize my problem is likely unique. Is it possible to singularize or pluralize the names but preserve the case? Or give an option to convert to PascalCase or leave as exactly what is used in the database or tables.

Thanks

**Comment by ErikEJ** [comment]
Wonder if the remaining feature could help? Not sure.

**Comment by ErikEJ** [comment]
Ping - did you try table renaming?

**Comment by ErikEJ** [comment]
Closing this as no reply received, and it seems like an odd edge case.

**Comment by sm-FN** [comment]
> Describe what is not working as expected.
> 
> ### Steps to reproduce
> Include a complete description that I can redo to reproduce the issue.
> 
> ### Further technical details
> EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
> 
> Database engine: (SQlite, SQL Compact, SQL Server, Postgres)
> 
> Visual Studio version: (e.g. Visual Studio 2017 15.7)
