### ISSUE TITLE
Add feature to extend handlebars functionality

### ISSUE THREAD

**Issue by NickCullen** [ErikEJ/EFCorePowerTools#350]
From your wiki I can see you use https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars
 package when the "Use Handlebars" option is ticked. 

I have a dire need to add custom functionality when generating the entity files. 

As I use db first ASP Identity, I need to reverse engineer the ASP Identity tables and add the custom class inheritance's myself (IdentityUser/IdentityRole etc.) 

Unfortunately I can't simply do this to a partial class as it is duplicating all the properties (ones generated in the reverse-engineered entity, and again in the corresponding partial entity that derives from the relevant Identity class.). My current (really annoying) solution is to delete the generated properties in the reverse engineered entities every time I run EFCorePowerTools. Note: ignoring the tables is not a suggestion as I do want to keep the foreign key properties on related entities.

I see there have been similar issues/requests raised requesting the exposure of [helpers and transformers](https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#handlebars-helpers-and-transformers) and I can see the requests have been denied due to significant work.

I think it would be a simple implementation if the following can be implemented: 
If there is a .hbs file with the same name as the table being reverse-engineered, could that handlebars file take precedence over the current Class.hbs file for generating the class?

**Comment by ErikEJ** [comment]
I think yo may be asking for a HandleBars feature @tonysneed  ?

**Comment by tonysneed** [comment]
You can solve this problem by registering a custom Handlebars helper to simulate a switch statement.

Then update the properties hbs file with the handlebars helper and only add the property if the property name does not match a specific list of properties (those in your entity base class).

Unfortunately EFC PT does not support registration of handlebars helpers. To use that feature you need to fall back to the dotnet CLI.

If you have questions or need an example, please post an issue to my repo.

**Comment by ErikEJ** [comment]
Would it be possible for EFPT to register Handlebars helpers?

**Comment by NickCullen** [comment]
I ended up having to use the CLI and handlebars generator and bypassed EFCorePowertools unfortunately. I couldn’t find anyway of registering design time services with EFCPT. 

I had to look at what handlebars generator was doing and made custom loaders to dynamically load any .hbs file when it searched for the Class.hbs. 

Was a quick hack job but worked for my solution.
