### ISSUE TITLE
Some columns not being created in Context when reverse-engineering SQL Server 

### ISSUE THREAD

**Issue by peterhamilton-cpx** [ErikEJ/EFCorePowerTools#352]
Some columns not being added to generated Context.cs in EF Core Power Tools.

### Steps to reproduce
For both Table and View objects, some columns are not being created in the Context.cs file generated by EF Core Power Tools when reverse engineering SQL Server tables, but they are being created in the Model for the table/view.

From what I have found, it appears that the issue may be caused by underscores in the view/table column names.  For example, if we have a View/Table with the following columns:

	• Item_ID
	• Item
	• Item_Value_1
	• Item_Value_2
	• Value

The "Item_ID" and "Value" columns do not get generated in the Context.cs class for the database.  Below is a sample of the reverse-engineered view in the Context.cs class:
![image](https://user-images.githubusercontent.com/58074761/76078936-ad338780-5f71-11ea-8254-77bd912faff2.png)

This can be recreated by creating the VIEW object using the script below:

```
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VIEW_Items_With_Underscores]
AS
SELECT        1 AS Item_ID, 'Item' AS Item, 'Item Value 1' AS Item_Value_1, 'Item Value 2' AS Item_Value_2, 0 AS Value
GO
```

I have also found this issue exists with Table objects as well, if you reverse engineer a table created with the following script:

```
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TABLE_Items_With_Underscores](
	[Item_ID] [int] IDENTITY(1,1) NOT NULL,
	[Item_Value_1] [varchar](50) NULL,
	[Item_Value_2] [varchar](50) NULL,
	[Item] [varchar](50) NULL,
 CONSTRAINT [PK_TABLE_Items_With_Underscores] PRIMARY KEY CLUSTERED 
(
	[Item_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
```
The same exact issue exists, and the Item_ID and Value columns are not created in the Context.cs class:

![image](https://user-images.githubusercontent.com/58074761/76079015-d0f6cd80-5f71-11ea-8ee0-636250c19d3d.png)

All column properties are created in the model classes for these entities:

![image](https://user-images.githubusercontent.com/58074761/76079041-e0761680-5f71-11ea-8b06-89eeb4a46e6b.png)

Database engine: (SQL Server Express)

Visual Studio version: (e.g. Visual Studio 2019 16.4.5)

EF Core Power Tools version: 2.4.0 (2/18/2020)

**Comment by ErikEJ** [comment]
This is by design, as any property that follows conventions do not need to be configured in the DbContext. For example Id or <EntityName>Id is a key name by default.

**Comment by peterhamilton-cpx** [comment]
Hi Erik,

Thank you for your reply, however I don't fully understand how this could not be an issue.  **This is creating very real issues for us**, as we have Views and Tables in our databases in which their properties are not being created other than columns with "Id" in the name.  The "Value" was also not generated.  As such, we can't trust that the EF Core Power Tools are working as they should.

I have more examples from "real" databases, but I have provided a very simplified and reproducable example which demonstrates the issue.  It looks to me like something is happening with the renaming of columns with underscores and certain columns are being dropped in that procedure. 

If you feel this is not a bug, can you provide more clarity your reply above?  Specifically what would cause the "Value" column in both the View and Table examples above do not appear in the Context.cs class?

**Comment by ErikEJ** [comment]
So you are saying that no entity classes are being created for some of your tables? I doubt that! 
Suggest you consult the EF Core documentation: https://docs.microsoft.com/en-us/ef/core/modeling/

**Comment by peterhamilton-cpx** [comment]
Thanks Erik,

I am not saying that no entity classes are being created.  I am saying that the EF Core Power Tools are creating the Model classes fine (all of the columns from the View and Table are there), but...the properties which are in the model classes are not being added as properties in the Context.cs class.  We are letting EF Core Power Tools create both the Models and db context.  For most Tables/Views all is well, but for the samples I have specified, they do not.

I had a look at the documentation but there isn't much in that section.  Perhaps you can re-read the initial post and try the samples yourself.  (You can create the Table/View items in any SQL database).

**Comment by ErikEJ** [comment]
Trust me, this is all by design :smile:

**Comment by peterhamilton-cpx** [comment]
Upon further investigation I have found that the underscores are not the issue with the "Item_ID" column.  The reason why we are missing columns in the generated DB Context classes is that any "int" columns in the source VIEWs are not being generated.  

I have created an item for that issue [here](https://github.com/dotnet/efcore/issues/20219). 

Thanks for your help, and sending be back to school!  :)

**Comment by ErikEJ** [comment]
What you have reported is a non-issue.

**Comment by peterhamilton-cpx** [comment]
Thanks Erik.  I am still not entirely clear on why this is not an issue.  We have VIEW objects, when reverse-engineering VIEWs, any columns of type "int" to not get generated in the Context.cs class.  I fail to see why that is a non-issue.  The column names do not matter, all of the numeric columns are ignored in the DB Context.

If you can provide me with any details on why this would be expected behaviour, I would love to hear them.

FYI - I do **not** consider myself an expert at any of this, I am simply trying to use Entity Framework (and the EF Core Power Tools).  I haven't found why this behaviour would occur.  So I realize that I may be missing something, as this would be a very obvious bug.

**Comment by ErikEJ** [comment]
It is not a bug, it is by design, as stated in my comment to your EF Core issue. Are you facing any errors because of this, then please provide a sample project that demonstrates that error.

**Comment by vishwa-sage** [comment]
Due to this change, my entire code getting impacted while transitioning from .net 6 to ,net core upgrade. I am facing issue as EF core reverse engg tool decide the property name on their own and gives a very unexpected property name. Like when i do the reverse engg, I have table CM_Companies, which has tow relations with CC_Change table and FK name in tables is like CC_Change and CC_Change1, i am expecting this same name after reverse engg, so that when i transition my code from .NET 6 with EF 6, i dont require to look into this kind of change. I am surprised and did not get any solution yet.

**Comment by ErikEJ** [comment]
Have you tried "Use Database Names"?

**Comment by vishwa-sage** [comment]
Yes, "UseDatabaseNames": true,

**Comment by vishwa-sage** [comment]
Can you direct me that closed issue, i will see the solution you provided there.
