### ISSUE TITLE
Ignore columns with reverse engineering

### ISSUE THREAD

**Issue by ducman** [ErikEJ/EFCorePowerTools#353]
This isn't an issue but more of a question.

I'm able to edit the handlebar template to have the model inherit from a base model. The base model has some standard columns (properties) in all tables in the database (i.e. IsDeleted, CreatedDate, LastUpdatedDate, etc.). Is there a way to not generate these columns (properties) in the models (with or without using the handlebar template)?

**Comment by ErikEJ** [comment]
Are you generating from a database project or a live database?

**Comment by ducman** [comment]
Live database

**Comment by ErikEJ** [comment]
This is not currently possible, but I could consider it. 
Any ideas on how to configure the list of columns to be ignored - in the efpt.config.json - simply a comma seperated list of column names? - or [table].[column] ?

**Comment by ducman** [comment]
We have a list of standard columns to ignore (lives in the base model) so a comma-separated list of column names will do. But others may want and probably it is better to have it a bit more flexible.

Maybe [schema].[table].[column] to be very specific but *.*.[column] will work in my case if wildcard can be used.

**Comment by ErikEJ** [comment]
I am not sure it is something I plan to do, as you appear to be mixing domain modelling and database first. Added to the Backlog milestone

**Comment by AlexVPerl** [comment]
Also looking for way to ignore a column when doing rev. eng. - is there any recommended solution?
Thanks.

**Comment by ErikEJ** [comment]
@AlexVPerl not at the moment, no. Create a domain object over your Poco class?

**Comment by ErikEJ** [comment]
@ducman @AlexVPerl This is now implemented
