### ISSUE TITLE
How to use Reverse Engineering correctly.

### ISSUE THREAD

**Issue by marcoomeli** [ErikEJ/EFCorePowerTools#355]
Hi 
Im Working on a ASP.NET Core MVC Project with an existing database and startet using your cool tool. Parallel our team is Working on a WPF Project which uses the same database. There we are used to work with the edmx.
I already generated the first POCOS which worked fine.
From time to time i need to add more tables from the existing database, table by table.

Now i have the following issues:

Every time i reverse engineer a new table, the application will recreate the applicationcontext file with a default constructor which i dont need and with a hardcoded connectionstring and so on. So it doesnt make any sence to me to make any changes in this file.
Of course there is the option to just generate the Models without the appcontext. But this way i have to add all the DbSets manualy. 
I just want to find an easy way for my team to generate the POCOS without the need to change the appcontext everytime.

How should i use the tool correctly in this case?

### Further technical details
EF Core Power Tools version: 2.4.0.0
Database engine: (SQL Server)
Visual Studio version: (Microsoft Visual Studio Professional 2019 Version 16.4.2)
ASP.NET Core 3.1

**Comment by ErikEJ** [comment]
>> and with a hardcoded connectionstring 
Use the option to not generate the connection string!

>> So it doesnt make any sence to me to make any changes in this file.

You should never make changes to this file, it is a partial class, so any modification can be made in another file for the same partial class.

**Comment by marcoomeli** [comment]
Thank you very much for your fast reply.

I have the connectionstring in my appsettings.json which i use in the ConfigureServices() Method in the Startup.cs Class to register the context as a service. 
Since i should not make any changes in the generatet AppContext file, how can i use the OnConfiguring() Method?
Should i even use it anymore since i already registert the context as a service in the Startup.cs?
Sorry im a little confused now.

**Comment by ErikEJ** [comment]
I do not understand your issue! You do not need to use the OnConfiguring method! 
Just use the option in my tool to not generate the connection string!

If that is not clear, please provide some code demonstrating your question.

**Comment by marcoomeli** [comment]
Yes i use this option in your tool to not generate the connection string which works fine.
 I Just dont get it why it still generates the OnConfiguring Method if i cant use it anyway?

**Comment by ErikEJ** [comment]
Yes, you could argue that is should be removed.

**Comment by marcoomeli** [comment]
This way the method could be used in a partial class for eg.. Thank you a lot for your help and for your tool, i realy like it.

**Comment by ErikEJ** [comment]
Fixed in latest daily build
