### ISSUE TITLE
Renaming column doesn't work without renaming table

### ISSUE THREAD

**Issue by sgrickov** [ErikEJ/EFCorePowerTools#356]
I have tried to rename some columns with table renaming and I found that when I do renaming a table AND column for that table that works as expected. However, when I want to rename just a column without table renaming it doesn't work for me.

### Steps to reproduce
This is my efpt.renaming.json:
[
  {
    "UseSchemaName": false,
    "SchemaName": "rul",
    "Tables": [
      {
        "Name": "Location",
        "NewName": "Airport",
        "Columns": [
          {
            "Name": "LocationID",
            "NewName": "AirportId"
          },
          {
            "Name": "ICAO",
            "NewName": "AirportCode"
          }
        ]
      }
    ]
  },
//the code below has no effect:
  {
    "UseSchemaName": false, //also tried "UseSchemaName": true
    "SchemaName": "rul",
    "Tables": [
      {
        "Name": "Country",
        "Columns": [
          {
            "Name": "ICAO",
            "NewName": "CountryCode"
          }
        ]
      }
    ]
  }
]

### Further technical details
EF Core Power Tools version: 2.4.0.0

Database engine: SQL Server

Visual Studio version: Microsoft Visual Studio Professional 2019
Version 16.4.6

**Comment by ErikEJ** [comment]
Have you tried the latest daily build, there were some bugs in that feature.

**Comment by sgrickov** [comment]
Morning Erik,

 

Yes, that build is working as expected.

Thank you so much!

Have a nice day!

 

Regards,

Sergej Grickov.

**Comment by ErikEJ** [comment]
Perfect, I will release an update to MarketPlace soon
