### ISSUE TITLE
Referencing EntityFrameCore v2.2.6 causes "Microsoft.EntityFrameworkCore.Design, Version=3.0.0.0" FileLoadException

### ISSUE THREAD

**Issue by MrtnSys** [ErikEJ/EFCorePowerTools#357]
Referencing Microsoft.EntityFrameworkCore v2.2.6 and Microsoft.EntityFrameworkCore.Design v2.2.6 in Xamarin.Forms and calling EFCore Power Tools > Migration Tool (preview) or Add DbContext Model Diagram on the shared project, causes the error at the bottom. 

Visual Studio 2019 v16.5.1
EF Core Power Tools v2.4.2

[EFPowerToolsTest.zip](https://github.com/ErikEJ/EFCorePowerTools/files/4398928/EFPowerToolsTest.zip)

**Error**
System.ArgumentException: Error:
System.IO.FileLoadException: Could not load file or assembly **'Microsoft.EntityFrameworkCore.Design, Version=3.0.0.0**, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'Microsoft.EntityFrameworkCore.Design, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
at ReverseEngineer20.EfCoreModelBuilder.BuildResult(String outputPath, Boolean generateDdl)
at ReverseEngineer20.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efpt\Program.cs:line 44

**Comment by ErikEJ** [comment]
Probably because it is a Shared project.

**Comment by MrtnSys** [comment]
I meant the Xamarin Forms Cross Library. It's a NETStandard 2.0 dll.
Note, the target hack is included in it's csproj file.
<TargetFrameworks>netcoreapp3.1;netstandard2.0</TargetFrameworks>

Using EntityFrameworkCore 3.1.3 does not produce the error. A plain test solution for Visual Studio 2019 is linked above.

**Comment by ErikEJ** [comment]
Ah, I do not support EF Core 2 with projects that target net core 3.x

**Comment by MrtnSys** [comment]
Ok nice. Changing as follows work :-)

`<TargetFrameworks>netcoreapp2.2;netstandard2.0</TargetFrameworks>`

**Comment by ErikEJ** [comment]
Fantastic!
