### ISSUE TITLE
Do i have to reverse engineer junction tables?

### ISSUE THREAD

**Issue by marcoomeli** [ErikEJ/EFCorePowerTools#359]
Hi there

I have 3 tables:
-tblEmployee
-tblAuthorization
-tblEmploye_Authorization (junction table).

Since the relationship from tblEmployee to tblAuthorization is a many to many relationship, i have a 3rd table (junction table).

When i reverse engineer and just select the tables tblEmployee and tblAuthorization, it will not generate the navigationpropperties foreach other.

Is there a way to reverse engineer tables without to include junction tables like in the edmx files?

Thanks for your help!

Marco

**Comment by ErikEJ** [comment]
EF Core does not support many to many relations with a "shadow" table - it is coming in EF Core 5.
