### ISSUE TITLE
Reverse engineering fails with NullReferenceException

### ISSUE THREAD

**Issue by grzegorzosipiak** [ErikEJ/EFCorePowerTools#363]
_System.NullReferenceException: Object reference not set to an instance of an object.
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__3.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 235_

### Steps to reproduce
![obraz](https://user-images.githubusercontent.com/60744078/78637659-20028c00-78ab-11ea-9f69-18d98043f751.png)

### Further technical details
EF Core Power Tools version: 2.4.0.0

Database engine: SQL Server Express 13.0.5026

Visual Studio version: VS 2019 16.5.2

**Comment by ErikEJ** [comment]
Are you able to share a (private) repro?

**Comment by grzegorzosipiak** [comment]
Sure, what do you need? Where should I put it?

**Comment by ErikEJ** [comment]
Your project file, I think. You can email me.

**Comment by ErikEJ** [comment]
Are you using the latest daily build, or just the official build from VS Marketplace?

**Comment by grzegorzosipiak** [comment]
At the moment I am using official Marketplace release, yesterday i tried 
daily build with the same result.

W dniu 07.04.2020 o 11:43, Erik Ejlskov Jensen pisze:

**Comment by ErikEJ** [comment]
Ok, I probably need a VS solution that reproduces the issue.

**Comment by grzegorzosipiak** [comment]
I tested this issue on SqlSever LocalDB 13.0.4001  - database created from script (attached) using brand new VS project (attached). SqlServerProvider was installed manually using nuget.

Issue persists.
[TestCase.zip](https://github.com/ErikEJ/EFCorePowerTools/files/4444946/TestCase.zip)

**Comment by ErikEJ** [comment]
I have no issues with that project - what path is your project in?

**Comment by grzegorzosipiak** [comment]
The orignal one: D:\_Projekty\EkoStart
Test one: C:\Users\grzegorz\Desktop\

Can I do something to try to debug problem directly on my computer?

**Comment by ErikEJ** [comment]
Yes, you can get the source code, follow readme instructions for debugging, set breakpoint, press F5 and open your solution from the experimental/debug VS session.

Let me know if you get stuck, and I will try to advise.

**Comment by grzegorzosipiak** [comment]
Found out whats wrong.
I have Comodo Antivirus installed with automatic isolation turned on (unexpected processes are run in something like isolated sandbox). Turned out, that in the process extension is spawning **efreveng.exe** from temp folder that my antivirus automatically isolated (without notice). Because of this extension was unable to read this process's standard output. More to this files generated were saved in sandbox and not in  expected destination folder.

 `var revEngResult = revEng.GenerateFiles(options, includeViews);` in ReverseEngineerHandler.cs (line 239) returned null, as there were no standard output for underlying methods to work on. 
 Next, `foreach (var filePath in revEngResult.EntityTypeFilePaths) {  }` (line 241) loop tried to access EntityTypeFilePaths and generated null reference exception.

I suggest introducing checking if generation completed successfully and print to output when something went wrong.

Thank you for Your help.

**Comment by ErikEJ** [comment]
I will add a check and error message - thanks for debugging!

**Comment by ErikEJ** [comment]
I have improved error handling
