### ISSUE TITLE
Example "Custom renaming with epft.renaming.json" in documentation doesn't work as described.

### ISSUE THREAD

**Issue by marcoomeli** [ErikEJ/EFCorePowerTools#364]
Hi there

In your documentation in the section "**[Custom renaming with epft.renaming.json](https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#custom-renaming-with-epftrenamingjson)**", you write following:

> The following efpt.renaming.json sample file will generate these names in the model: 
> public virtual DbSet< CourseOffering> CourseOfferings { get; set; } 

But if i use your  **efpt.renaming.json sample file** i get this 

**Result i get:**
_public virtual DbSet< CourseOffering**s**> CourseOfferings { get; set; }_
Class and Filename: CourseOffering**s** and CourseOffering**s**.cs

**Result i would like to get:**
_public virtual DbSet< CourseOffering> CourseOfferings { get; set; }_
Class and Filename: CourseOffering and CourseOffering.cs

In my case i dont use the function 'Pluralize or singularize generated object names (English)' because we dont use english properties.

### Questions
1. Is there a way to rename the DbSet property name to get de described result?
2. Is there a way to rename the generated navigation properties?

Thanks for your help!

### Further technical details
EF Core Power Tools version: 2.4.0.0
Visual Studio version: (Visual Studio 2019 16.4.2)

**Comment by ErikEJ** [comment]
Is it not just a typo: "NewName":  "CourseOffering", ??

Otherwise, please provide a CREATE TABLE script and a json file, and I will have a look.

**Comment by marcoomeli** [comment]
**CREATE TABLE script:**

```
USE [DatabaseName]
GO

/****** Object:  Table [dbo].[tblButton]    Script Date: 08.04.2020 12:44:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[tblButton](
	[BuId] [char](3) NOT NULL,
	[BuText] [varchar](50) NOT NULL,
	[BuRolle] [bit] NOT NULL,
	[ModifiedDate] [datetime] NULL,
 CONSTRAINT [PK_tblButton] PRIMARY KEY CLUSTERED 
(
	[BuId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[tblButton] ADD  CONSTRAINT [DF_tblButton_BuRolle]  DEFAULT ((0)) FOR [BuRolle]
GO
```

**Jason File:**

```
[
 {
  "UseSchemaName": false,
  "SchemaName": "dbo",
  "Tables": [
  {
	"Name": "tblButton",
	"NewName": "ButtonBerechtigung",
	"Columns": [
	  {
		"Name": "BuId",
		"NewName": "Id"
	  },
	  {
		"Name": "BuText",
		"NewName": "Text"
	  },
	  {
		"Name": "BuRolle",
		"NewName": "Rolle"
	  }
	]
   }
 ]		
 }
]
```

**Result after reverse engineering:**
`public virtual DbSet<ButtonBerechtigung> ButtonBerechtigung { get; set; }`

**Result i would like to get:**
`public virtual DbSet<ButtonBerechtigung> ButtonBerechtigungEN { get; set; }`

ButtonBerechtigungEN is the plural in german.

Greetings from Switzerland.

**Comment by ErikEJ** [comment]
There is currently no non-English pluralization, so this is not at all possible.

**Comment by ErikEJ** [comment]
Maybe this PR would solve your issue, but I have not had a closer look at it yet.

**Comment by marcoomeli** [comment]
Ok thanks for your help i will find another solution. But keep in mind then your documentation is not correct. becaause the **efpt.renaming.json sample file:** which you provide [here](https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#custom-renaming-with-epftrenamingjson) will not lead to the shown result:

> The following efpt.renaming.json sample file will generate these names in the model:
> public virtual DbSet< CourseOffering> CourseOfferings { get; set; }

the results then would actualy contain an 's' in the typename aswell:
`public virtual DbSet< CourseOfferings> CourseOfferings { get; set; }`

**Comment by marcoomeli** [comment]
Oh and did you maybe forgot my 2. Question?

> Is there a way to rename the generated navigation properties?

**Comment by ErikEJ** [comment]
Thanks, I have removed all the "s" endings from the sample.

Re your second question: Potentially, if I decided to use/merge the above mentioned PR
