### ISSUE TITLE
Reverse engineer: failing with nested models folder

### ISSUE THREAD

**Issue by jburman** [ErikEJ/EFCorePowerTools#367]
I have a project where DbContext is generated to Data folder and models were going into Data/Models subfolder.
This was working fine until getting latest release (4/11 build). Now the models are failing to generate. Changing models path to just Data it works fine again.

Database engine: SQL Server 14.0.3238.1 (Linux)

Visual Studio version: Visual Studio 2019 16.5.3

**Comment by ErikEJ** [comment]
What does failing mean?

Could you share errors?

And a screenshot of your config?

**Comment by ErikEJ** [comment]
I was able to repro - woking on a fix. 
Use Data\Models instead of Data/Models as a workaround.

**Comment by jburman** [comment]
Thanks - is there a way to see logs from the tool? I wasn't able to find it.

**Comment by ErikEJ** [comment]
VS output pane - but this was a silent, deadly bug.
