### ISSUE TITLE
BIT NOT NULL with DEFAULT 1 is converted to bool?

### ISSUE THREAD

**Issue by rcfearn** [ErikEJ/EFCorePowerTools#373]
v3.1.3

If I have two BIT columns in sometable.sql in db project:

CREATE TABLE sometable (
     ID INT NOT NULL,
     IsActive NOT NULL DEFAULT 1,
     IsDeleted NOT NULL DEFAULT 0
)

When I reverse engineer these I get:

**[Required]**
public **bool?** IsActive { get; set; }
public bool IsDeleted { get; set; }

I did not expected IsActive to be nullable as it's a NOT NULL column.

If I removed the DEFAULT 1 from the IsActive column declaration I get:

public bool IsActive { get; set; }
public bool IsDeleted { get; set; }

I am reversing engineering from Database, not dacpac.

**Comment by ErikEJ** [comment]
This is by design, see https://github.com/dotnet/efcore/issues/10840#issuecomment-362047565 @bricelam

**Comment by rcfearn** [comment]
Thanks for the feedback.

**Comment by rcfearn** [comment]
Just one thing though... why is IsActive set to a bool? and IsDeleted is not, given they both have default values shouldn't the reasoning be the same for both?

**Comment by ErikEJ** [comment]
One defaults to false, the other defaults to true.

**Comment by rcfearn** [comment]
Yeah but aren't I supposed to be able to pass in NULL and let the database decide? Seems inconsistent

**Comment by ErikEJ** [comment]
I think it's complicated / overthought, but I will let @bricelam comment.

**Comment by rcfearn** [comment]
I understand @bricelam's reasoning but it's not consistent:

//Either it's
public bool IsActive { get; set; } = true;
public bool IsDeleted { get; set; }

//Or allow NULL for both (no required attribute):
public bool? IsActive { get; set; }
public bool? IsDeleted { get; set; }

**Comment by ErikEJ** [comment]
@rcfearn DEFAULT 0 is optimized to be bool (and not bool? )

**Comment by bricelam** [comment]
We ignore SQL DEFAULT constraints that match the CLR default value. This makes the DEFAULT 0 case more sane.

If we didn't make DEFAULT 1 nullable, you'd rip a lot more hair out when you finally found out that your app hasn't been inserting `false` values.

We would also like to see this experience improved: https://github.com/dotnet/efcore/issues/13613#issuecomment-429978794

**Comment by ErikEJ** [comment]
This is actually fixed via an advanced option now.
