### ISSUE TITLE
Reverse Engineer Adds [Key] Attribute

### ISSUE THREAD

**Issue by joshualuke** [ErikEJ/EFCorePowerTools#375]
Today, I used Reverse Engineer to update my model classes. I have been using it for several weeks. I haven't made any configuration changes, but today, it added the [Key] attribute to all of my generated model classes. This actually had some strange downstream affects on my application due to a certain component that I'm using. Is there any way to turn off the generation of the [Key] attribute while still using the other DataAnnotation attributes that were previously being generated?

### Further technical details
EF Core Power Tools version: 2.4.34.0

Database engine: SQL Server

Visual Studio version: Visual Studio Community 2019 v16.5.4

**Comment by ErikEJ** [comment]
Maybe because it is now defaulting to EF Core 3.0 reverse engineering?

**Comment by ErikEJ** [comment]
Ping?

**Comment by ErikEJ** [comment]
@joshualuke Ping?

**Comment by joshualuke** [comment]
Sorry, I honestly have no idea. I'm very new to EF Core.

**Comment by ErikEJ** [comment]
If you use EF Core 2 code generation, the key attribute will not be there.

I would really like to learn what kinds of issues it was causing!

**Comment by joshualuke** [comment]
Ohhh, okay - I figured out how to use EF Core 2 (via the very obvious checkbox that was staring directly at my face, haha), and yes, that resolved the issue. TBH, I would like to use the key attribute, but my application is using a set of 3rd party grid controls, and the grids auto-sort on the property with the key attribute (ignoring any sorting I may have done when getting the data). It's possible to set the sort order within the grid control by adding code to the column definition, but I have a LOT of grids and didn't feel like taking the time to retro-fit them. I'll probably do it in phase two.

At any rate, thanks for your help with this! It's a GREAT product! :)

**Comment by ErikEJ** [comment]
I am glad you figured it out. If you like my tools, I would be very grateful for a rating or review here:
https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools#review-details

**Comment by joshualuke** [comment]
Yep, I have already left a review. :) Thanks again!
