### ISSUE TITLE
Problem when using DesignTimeDbContextFactoryBase 

### ISSUE THREAD

**Issue by kiske1** [ErikEJ/EFCorePowerTools#376]
Hello Erik, and thank you for this fantastic tool! 
I've encountered a problem using it with a DesignTimeDbContextFactoryBase in place. In practice for example if I try to generate a DGML diagram, I get a System.notsupported exception stating that the format of the path is not supported. 
I then downloaded your repo and debug into the extension, and found that:
- The exception occours in ModelAnalyzerHandler at line 118
- The culprit seems to be in ProcessLauncher.cs at line 161 in which the process returns all of this: `"DesignTimeDbContextFactoryBase.Create(string): Connection string: 'Server=(localdb)\\mssqllocaldb;Database=TestDb001;Trusted_Connection=True;MultipleActiveResultSets=true;Application Name=TestEFCorePowerTools;'.\r\nDbContext:\r\nTestDbContext\r\nDebugView:\r\nModel: \r\n  EntityType: Table1\r\n    Properties: \r\n      Id (int) Required PK AfterSave:Throw ValueGenerated.OnAdd\r\n        Annotations: \r\n          SqlServer:ValueGenerationStrategy: IdentityColumn\r\n          TypeMapping: Microsoft.EntityFrameworkCore.Storage.IntTypeMapping\r\n      Column1 (string)\r\n        Annotations: \r\n          TypeMapping: Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerStringTypeMapping\r\n      Column2 (string)\r\n        Annotations: \r\n          TypeMapping: Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerStringTypeMapping\r\n    Keys: \r\n      Id PK\r\n    Annotations: \r\n      ConstructorBinding: Microsoft.EntityFrameworkCore.Metadata.ConstructorBinding\r\n      Relational:TableName: GolfClubs\r\nAnnotations: \r\n  ProductVersion: 3.1.3\r\n  Relational:MaxIdentifierLength: 128\r\n  SqlServer:ValueGenerationStrategy: IdentityColumn\r\n"
`

### Steps to reproduce
Simply create a project with a DesignTimeDbContextFactoryBase and nothing else. Here is a repo to reproduce the issue: https://github.com/kiske1/TestEFCorePowerTools 

### Further technical details
EF Core Power Tools version: 2.4.0
Visual Studio 2019 - 16.5.4 

The tests are made in EXP mode

Thank you very much in advance

**Comment by ErikEJ** [comment]
I looks like it is because you are writing this line: https://github.com/kiske1/TestEFCorePowerTools/blob/b1fd2a81e14742f43eaf3b1de046af6d2f652825/TestEFCorePowerTools/Data/DesignTimeDbContextFactoryBase.cs#L45

**Comment by kiske1** [comment]
Oh... Now that I see it was pretty obvious, damn cut&paste of the DesignTimeFactory!

Thank you for you time!
