### ISSUE TITLE
Unable to launch external process

### ISSUE THREAD

**Issue by karenpayneoregon** [ErikEJ/EFCorePowerTools#378]
When performing a reverse engineer on any SQL-Server database

### Steps to reproduce
Right click on class project, select reverse engineer, follow steps to completion and get
System.Exception: Reverse engineer error: Unable to launch external process: 
   at ReverseEngineer20.ReverseEngineer.EfRevEngLauncher.BuildResult(String output)
   at ReverseEngineer20.ReverseEngineer.EfRevEngLauncher.GetOutput()
   at ReverseEngineer20.EfCoreReverseEngineer.LaunchExternalRunner(ReverseEngineerOptions options)
   at ReverseEngineer20.EfCoreReverseEngineer.GenerateFiles(ReverseEngineerOptions reverseEngineerOptions, Boolean includeViews)
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__3.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 237

### Further technical details
EF Core Power Tools version: 1.0 

Database engine: SQL Server 2017

Visual Studio version:  Visual Studio 2017 15.9.18)

Windows 10

**Comment by karenpayneoregon** [comment]
Wrong version listed, it's 2.4.34.0
Version 2.4.34.0

SQL Server Compact 4.0 in GAC - No
SQL Server Compact 4.0 DbProvider - No

SQL Server Compact 4.0 DDEX provider - No
SQL Server Compact 4.0 Simple DDEX provider - Yes


SQLite ADO.NET Provider included: 1.0.110.0
SQLite EF6 DbProvider in GAC - No

System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes

**Comment by karenpayneoregon** [comment]
I tried something different, did not specify folders for model and context and not to install EF Core 3x and then reverse engineering worked.

**Comment by ErikEJ** [comment]
EF Core 2.0 reverse engineering runs in-process with Visual Studio. 
EF Core 3.0 reverse engineering is an external .NET Core executable.

I am guessing your issue could be related to https://github.com/ErikEJ/EFCorePowerTools/issues/363

**Comment by ErikEJ** [comment]
Ah! Have you tried VS 2019?

**Comment by karenpayneoregon** [comment]
I have not installed VS 2019 yet.  Didn’t get a chance to try using a new project today but promise to first thing in the morning.

**Comment by karenpayneoregon** [comment]
Just tried with install EF Core 3, specified folder, got the same error. Next tried not to install EF Core 3, no folders specified, this worked. Next removed generated code, installed via NuGet EF Core current version, got the error as first reported specifying folder.

**Comment by ErikEJ** [comment]
In your third scenario, did you specify Use EF Core 3.0 ?

**Comment by ErikEJ** [comment]
Have you looked at #363 ?

**Comment by scotteble** [comment]
I'm getting this error as well.  Erik - I have looked at #363, but the error message is different.  I even tried the latest daily build, but get the same issue.  I'm running Windows 10 with no other third party virus apps as mentioned in 363.  

I can confirm that it only happens when I check the "Use EF Core 3.x" box.  Runs fine without that option, but I'd prefer to be able to use the new features. 

My error is the same as the OP.  Any ideas on troubleshooting?

Thanks

**Comment by scotteble** [comment]
Disregard my post.  I'm an idiot and didn't have .net core 3 installed.  That fixed my problem.

**Comment by ErikEJ** [comment]
@scotteble Thanks for the info, I will add a check for the presence of .NET 3! 

@karenpayneoregon Do you have .NET Core 3.x installed?

**Comment by ErikEJ** [comment]
Added a check for .NET Core 3 being installed in the latest daily build

**Comment by karenpayneoregon** [comment]
No I don’t have .NET Core 3 installed on my machine. If that is the case I can install it next week as I’m inundated with COVID issues so making any changes to my machine is not possible currently.

**Comment by ErikEJ** [comment]
I have also updated the landing page - closing

**Comment by emamzadehm** [comment]
Same problem for me
VS 2019
Installed EF Core 3.1.5
get same error 
Please advice.

**Comment by ErikEJ** [comment]
Please share your csproj file and output of "dotnet --version"
