### ISSUE TITLE
how can i delete old Database Connection from current list

### ISSUE THREAD

**Issue by BCCGrace** [ErikEJ/EFCorePowerTools#379]
How can i delete old Database Connection from current list ?

Describe what is not working as expected.

### Steps to reproduce
Include a complete description that I can redo to reproduce the issue.

### Further technical details
EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)

Database engine: (SQlite, SQL Compact, SQL Server, Postgres)

Visual Studio version: (e.g. Visual Studio 2017 15.7)
![image](https://user-images.githubusercontent.com/64432718/80404549-f7a4f680-8886-11ea-8350-7427548520df.png)

**Comment by ErikEJ** [comment]
I will update the docs to tell how to do this?

**Comment by BCCGrace** [comment]
Thank you! 
I realize that they are listed on the "Data Connections" through tools "Connect to Database"
I thought it will be in a different place or a specific UI through the EF Tools.

**Comment by ErikEJ** [comment]
Docs updated
