### ISSUE TITLE
File content not refresh

### ISSUE THREAD

**Issue by funky81** [ErikEJ/EFCorePowerTools#38]
File content (*.cs) not refresh after file generated from EFCorePowerTools.
I have to  re-open the file in order to see the changes.
I dont know which issue is this, either VS2017 or EFCorePowerTools, but one thing for sure, if I change file content outside VS2017 then back to see it in VS2017 (already opened before), it will ask me to re-open the file

### Steps to reproduce
1. Open source code (tableX.cs - for example). tableX is generated file from SQL Server database with EFCorePowerTools 
2. Modify SQL Server table
3. Generate again with EFCorePowerTools
4. Dont see any differences
5. Close the tableX.cs then open again.
6. See the differences

### Further technical details
EF Core Power Tools version: 1.0.604.0
Database engine: SQL Server 2017 CU5 - Docker Version
Visual Studio version: VS2017 15.7.3 and VS2017 v15.8 preview 1

**Comment by ErikEJ** [comment]
Yes, I have seen the same behaviour, in particular with the new .NET Core (SDK based) project type. I will investigate if I am doing something wrong.

What type of project (.csproj file) do you have?

**Comment by funky81** [comment]
Currently I'm using Console .NET core project + ASPNET .core project.
Both behave the same result

**Comment by ErikEJ** [comment]
What happens if you try a old school C# class library?

**Comment by tonysneed** [comment]
I think this may be an issue with folder-based projects in VS 2017.

**Comment by ErikEJ** [comment]
Yes, but I think I should maybe always call .AddFromFile

**Comment by ErikEJ** [comment]
Closing, as this seems to be a fixed VS bug
