### ISSUE TITLE
exception occ when run migrations tool

### ISSUE THREAD

**Issue by jason-shi** [ErikEJ/EFCorePowerTools#380]
![图片](https://user-images.githubusercontent.com/1249955/80665021-e2200e80-8aca-11ea-87da-0f38403e1212.png)

Enviroment: VS2019
ConsoleApp

when use cmdlet add-migration, it run well, the output is:
Build started...
Build succeeded.
Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 3.1.3 initialized 'LineupDbContext' using provider 'Pomelo.EntityFrameworkCore.MySql' with options: None
To undo this action, use Remove-Migration.

but use the tool, is throw exception..

**Comment by ErikEJ** [comment]
Which exception?

**Comment by ErikEJ** [comment]
Ping?

**Comment by ErikEJ** [comment]
Closing, feel free to re-open if you can provide the requested information.
