### ISSUE TITLE
Lazy Loading Feature Checkbox

### ISSUE THREAD

**Issue by icedeocampo** [ErikEJ/EFCorePowerTools#381]
Have a checkbox that adds:

optionsBuilder.UseLazyLoadingProxies();

onto the generated DBContext object.

**Comment by ErikEJ** [comment]
Why not simply use the DbContext constuctor that takes an OptionsBuilder ?

**Comment by icedeocampo** [comment]
Just doing it from an EF6 perspective where LazyLoader is on by default - and that developers need not enable it manually. 

Apparently a lot of people miss this and end up with a lot of empty collections.

Just a great help for people who are porting (and those who are starting to develop on EFCore). Not really a necessity.

**Comment by ErikEJ** [comment]
EF Core lazy loading is something that you must opt-in to, so I prefer not to make any changes in this respect.
