### ISSUE TITLE
Can't reverse engineer an existing DB / DB Project.

### ISSUE THREAD

**Issue by dsxp** [ErikEJ/EFCorePowerTools#382]
Can't reverse engineer an existing db.

###Background:
Been using EF core power tools (and i f*king love it) for a while but last week started giving me issues, please advice or let me know how I can contribute.

### Steps to reproduce
Right click on project, ef core power tools, reverse engineer, fill out the GUI, Ok, a wild error appeared! This is system wide, tried with existing projects and empty / new.

### Error Output:
System.Exception: Reverse engineer error: 
System.IO.FileLoadException: Could not load file or assembly 'Microsoft.EntityFrameworkCore.Design, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'Microsoft.EntityFrameworkCore.Design, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at ReverseEngineer20.ReverseEngineer.ReverseEngineerRunner.GenerateFiles(ReverseEngineerCommandOptions reverseEngineerOptions)
   at efreveng.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efreveng\Program.cs:line 33

   at ReverseEngineer20.ReverseEngineer.EfRevEngLauncher.BuildResult(String output)
   at ReverseEngineer20.ReverseEngineer.EfRevEngLauncher.GetOutput()
   at ReverseEngineer20.EfCoreReverseEngineer.LaunchExternalRunner(ReverseEngineerOptions options)
   at ReverseEngineer20.EfCoreReverseEngineer.GenerateFiles(ReverseEngineerOptions reverseEngineerOptions, Boolean includeViews)
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__3.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 237

###Workaround:
Uninstall / Install Extension (It gets old after a while), after a VS Restart the wild exception appears again.

### Further technical details
EF Core Power Tools version: 
Version 2.4.43.0

SQL Server Compact 4.0 in GAC - No
SQL Server Compact 4.0 DbProvider - No

SQL Server Compact 4.0 DDEX provider - No
SQL Server Compact 4.0 Simple DDEX provider - Yes

SQLite ADO.NET Provider included: 1.0.109.0
SQLite EF6 DbProvider in GAC - No

System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes

Database engine: SQL Server 2014 /  Visual Studio SQL Server Project

Visual Studio version: (e.g. Visual Studio 2017 15.7)
Microsoft Visual Studio 2019 Version 16.5.4

###Random Stuff:
GUI details and packages 
<img width="272" alt="Deps" src="https://user-images.githubusercontent.com/4210565/81412355-59782280-9109-11ea-98c8-e5381a5ca097.png">
<img width="302" alt="Options" src="https://user-images.githubusercontent.com/4210565/81412361-5aa94f80-9109-11ea-8c5e-4e53b7560c31.png">

Thank you!

**Comment by dsxp** [comment]
After more testing I found that I have been re-installing the 2.4.34 version ( EFCorePowerTools2.4.34.vsix ) that silently updated to the 2.4.43 (EF Core Power Tools v2.4.43.vsix) that throws the error, disabling the automatic updates will do the trick for now.

<img width="122" alt="Version" src="https://user-images.githubusercontent.com/4210565/81416533-79124980-910f-11ea-85cc-28a41595b985.png">

**Comment by ErikEJ** [comment]
So the latest daily is broken ? I will look into it.

**Comment by ErikEJ** [comment]
I really appreciate that you subscribe to the latest daily build, btw. But sometimes it breaks.

**Comment by dsxp** [comment]
> I really appreciate that you subscribe to the latest daily build, btw. But sometimes it breaks.

And I totally understand that, tbh didn't notice that I had the VSIX Gallery - nightly builds enabled that has been silently updating all my extensions.

Anyway so many thanks for this extension, I can't say how many time and plumbering time it has saved me (if you accept founding let me know).

**Comment by ErikEJ** [comment]
Thanks! I accept reviews on VS marketplace, no payment. I have a well paid daytime job 😊

**Comment by dsxp** [comment]
Thank you again, plesae stay safe and keep your loveds one safe too! Kind regards!
