### ISSUE TITLE
Doing it again? Reverse engineer just one entity but deletes the others

### ISSUE THREAD

**Issue by netbitshift** [ErikEJ/EFCorePowerTools#388]
When I make a table change, then try to reverse engineer and select just that table (and entities only), the end result is that most of my other entities are deleted, along with the data context.

### Steps to reproduce
Have an existing EF model and entities
Make a change to a table 
Revserse engineer, un-check 'use EF 3.x', choose Entities only

### Further technical details
EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
2.4.34

Database engine: (SQlite, SQL Compact, SQL Server, Postgres)
SQL Server

Visual Studio version: (e.g. Visual Studio 2017 15.7)
VS 2019

**Comment by ErikEJ** [comment]
You must select all the tables every time, as described in the docs.

**Comment by ErikEJ** [comment]
In addition, you can remove the file header to avoid deletion of the autogenerated files. I have added this fact to the docs.

**Comment by NetMage** [comment]
Where in the docs does it say how to avoid deletion of the autogenerated files?

**Comment by ErikEJ** [comment]
@netmage in the wiki
