### ISSUE TITLE
ReverseEngineer option crashes (to build output) if server connection doesn't have a password saved.

### ISSUE THREAD

**Issue by Allsetra-RB** [ErikEJ/EFCorePowerTools#390]
I don't have a password saved on any of my SQL connections in Visual Studio's Server Explorer. When I need a connection, Visual Studio prompts me to supply a password before continuing. However, the Power Tools extension does not and just tries accessing the connection with the available credentials (some username and no password) and consequently crashes a StackTrace into the build Output.

### Steps to reproduce
1. Create a connection to a SQL Server, but select all available options to not save passwords. I believe there is one to not save sensitive information to e.g. app.config or project settings, and there is one to not save sensitive information in the connection itself.
2. Reverse Engineer through Power Tools using this connection.

### Further technical details
EF Core Power Tools version: 2.4.34.0
Database engine: SQL Server
Visual Studio version: 2017 15.9.3

PS: Nice tool though, I was worried we'd have to do this over command line. :)

**Comment by ErikEJ** [comment]
![image](https://user-images.githubusercontent.com/4169187/84634816-a57d6a80-aef2-11ea-8c1e-be360b1e1682.png)

**Comment by ErikEJ** [comment]
```
 private static bool ContainsSensitiveData(IVsDataConnection dataConnection)
        {
            if (dataConnection == null)
            {
                return false;
            }
                // need to compare ignoring case as DecryptConnectionString() can turn e.g. 'Integrated Security' into 'integrated security'
            else if (dataConnection.DisplayConnectionString.Equals(
                DataConnectionUtils.DecryptConnectionString(dataConnection), StringComparison.CurrentCultureIgnoreCase))
            {
                return false;
            }
            else
            {
                return true;
            }
        }
```

**Comment by ErikEJ** [comment]
Fixed in the latest daily build. Please let me know if it works for you.

**Comment by Allsetra-RB** [comment]
Uhhh, kind of. It's now making me fill in the password for every connection I have before showing me the list of connections and letting me pick one. It should be letting me pick the connection and then make me fill in the password for only that connection.

**Comment by ErikEJ** [comment]
Great, I think I know the proper solution know!
