### ISSUE TITLE
Is it possible to map PostgreSQL timestamp with time zone to NodaTime.OffsetDateTime?

### ISSUE THREAD

**Issue by chrisr45** [ErikEJ/EFCorePowerTools#391]
I am looking for advice on how to reverse engineer an existing database with columns of type 'timestamp with time zone'  to a model with properties of type NodaTime.OffsetDateTime?

Any help would be much appreciated. 

### Steps to reproduce
Currently i can only generate classes with property of type DateTime.

### Further technical details
EF Core Power Tools version: (2.4.34.0)

Database engine: ( Postgres)

Visual Studio version: (e.g. Visual Studio 2019 16.5.3)

**Comment by ErikEJ** [comment]
Maybe in a partial class??

**Comment by chrisr45** [comment]
Not sure how that would work? 
If in the startup class the context is defined as follow:
            services.AddDbContext\<xxDbContext\>(options =>
                options.UseNpgsql(Configuration.GetConnectionString("DefaultConnection")
                , o => { o.UseNodaTime(); }
                ));
from what I understand the generated classes need to have NodaTime typed properties? 
Or they would need to be marked as [NotMapped].  
I cant figure out how to achieve this.  
I looked at using Handlebar templates but without a way of registering a helper ( to extend \#if ) I don't know how to change selected properties types.

**Comment by ErikEJ** [comment]
Yes, my proposal was a NonMapped property in a partial class, that then mapped to the underlying mapped property @roji ??

**Comment by roji** [comment]
This is really more a question for the Npgsql provider than for @ErikEJ.

You can definitely scaffold to NodaTime types; however, EF Core's scaffolding scaffolds each database type to its *default* CLR type, as mapped by the EF Core provider. When the NodaTime plugin is active, the Npgsql provider maps `timestamp with time zone` to NodaTime's Instant by default, and not OffsetDateTime. The only way to override this behavior would be to inherit from the plugin and override the mappings to specify OffsetDateTime as the default.

However, keep in mind that scaffolding is meant to be a "first step", after which it's fine to edited the generated entities and modify types as you wish.

**Comment by chrisr45** [comment]
That is not what I am observing 'timestamp with time zone' is being mapped to System.DateTime.  I think this is because  .UseNodaTime() is not being set on the connection used by the Reverse Engineering tool.  Is there a way to do this? 
If 'timestamp with time zone'  was being mapped to NodaTime's Instant I could probably use a partial class to expose an OffestDateTime property which could be persisted to the db via the generated property.

As for editing the generated files.
We are working in a major change to an application which is already in production- needless to say we do frequent schema changes.  
I have been using the Reverse Engineering tool to keep the db and model in sync , we manage schema updates via FluentMigrate scripts hence the db first approach. This means after each reverse engineering run an additional manual step is required, which is not ideal.

**Comment by roji** [comment]
@chrisr45 this should definitely work. Have you tried just using `dotnet ef dbcontext scaffold`, without the Power Tools (just to see where the problem is)? If you still have an issue with the CLI, keep in mind that you still need a minimal design-time context where you use the NodaTime plugin - otherwise the scaffolding process is unaware of the plugin.

**Comment by ErikEJ** [comment]
@roji EF Core Power Tools need to be told to load the plugin - could you share the package name of it - I do something similar for spatial SQL server support: https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/efreveng/ReverseEngineer/ServiceProviderBuilder.cs#L67

**Comment by roji** [comment]
The package in question is [Npgsql.EntityFrameworkCore.PostgreSQL.NodaTime](https://www.nuget.org/packages/Npgsql.EntityFrameworkCore.PostgreSQL.NodaTime), but it shouldn't be implicitly loaded all the time (in case you do that). Unlike with spatial, this package overrides mappings which already exist (for the regular BCL types). In other words, there are many users out there which want to scaffold to the BCL DateTime and not to NodaTime Instant, so this should be an opt-in.

**Comment by ErikEJ** [comment]
@roji Yes, just like spatial is opt-in as demonstrated in the linked code, I presume ???

**Comment by roji** [comment]
Did not actually click :) Yeah, that looks good - it's just another plugin (just like spatial), and as long as it's an opt-in everything should be fine.

**Comment by ErikEJ** [comment]
I will look into this.

**Comment by chrisr45** [comment]
Thank you for the time you have taken to help me and thank you for making these tools available to the community.  This is the second project I am using it on.  It saves me a lot of time.

**Comment by ErikEJ** [comment]
Implemented in latest daily build - I have not been able to test.

Add:

    "UseNodaTime": true,

to your efpt.config.json file.

(I will update the wiki when you can confirm it works)

**Comment by chrisr45** [comment]
Did not seem to work.  I add ,
`,"UseNodaTime": true`
to my  efpt.config.json file. Ran the tool.  but the generated classes still had DateTime properties eg.
`       public DateTime EffectiveFrom { get; set; }`
I did notice that after the run my efpt.config.json had been overwritten and the "UseNodaTime": true was missing.

EF Core Power Tools version: (2.4.51.0)

**Comment by ErikEJ** [comment]
You need build 2.4.54 for this to work.

**Comment by chrisr45** [comment]
Sorry my bad,  I did an update after seeing your comment that which me to 2.4.51 that I incorrectly assumed that was the latest.  
I have now updated to 2.4.54 and the generated classes now have Instant properties

`public Instant EffectiveFrom { get; set; }`

Thank you

**Comment by ErikEJ** [comment]
Excellent news - I have also logged https://github.com/ErikEJ/EFCorePowerTools/issues/396 and will update the wiki now
