### ISSUE TITLE
A table named "Staff" is always rendered with a lower case "s" and the collection is not pluralized.

### ISSUE THREAD

**Issue by jmmobley** [ErikEJ/EFCorePowerTools#392]
### Issue
I have a table named Staff. When using the Reverse Engineer feature, the resulting Entity that is generated is always lower case and the corresponding collection name is not pluralized.

Expected behavior: Entity name will begin with an upper case letter as with all other tables, and the pluralized "Staffs" will be used to represent the collection.

### Steps to reproduce
Create a  SQL Server database with a table named Staff. Ensure that it is upper case in the database. From the "Reverse Engineer" menu option, select your database, and generate a new Context and Entities. Notice that the Staff table is generated with a lower case character and the collection name is not pluralized correctly.

Database engine: SQL Server

Visual Studio version: Visual Studio 2019 (latest)

**Comment by ErikEJ** [comment]
Interesting!
Please provide a CREATE TABLE script for the table and either a screenshot of your options in use, or a copy of your efpt.config.json file.

**Comment by ErikEJ** [comment]
Ping?

**Comment by ErikEJ** [comment]
Closing, feel free to re-open if you can provide repro material
