### ISSUE TITLE
Generate .dacpac view columns with correct name

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#393]
Thank you for your tray. I don't know if it is possible with your library but with the raw data (model.xml) it is possible. I think you get it but only for clarification I attached an image with 1/2;
1 is the alias (Name to use in the generated class)
2 is the original name/key to get the type.
Thanks
Eric

![ScreenShot_2020-05-27_11-18-32](https://user-images.githubusercontent.com/8658679/83001454-10cacf80-a00c-11ea-8d38-930e036ef3bd.png)

**Comment by ErikEJ** [comment]
@webereric

**Comment by ErikEJ** [comment]
Already fixed in latest daily build, my testing was just bad.

**Comment by WeberEric** [comment]
Thank you very much. It works.
