### ISSUE TITLE
Convention Id/Guid

### ISSUE THREAD

**Issue by WeberEric** [ErikEJ/EFCorePowerTools#394]
Is it possible to add the guid to the "ID"-convention.

![image](https://user-images.githubusercontent.com/8658679/83007927-abc7a780-a014-11ea-9760-b43efa87fb92.png)

**Comment by ErikEJ** [comment]
What do you mean by the "ID convention" ??

**Comment by WeberEric** [comment]
I mean there have to be a convention which handles the id. In my sample you see that the "id" on the end is cuted off, thats good. And I like to ask if it is possible that we also cut the enire "Guid" in "public virtual" like the id. I don't know if it common to use Guid on the end but we do it to difference between int (id) and uniqueidentifier (guid).

**Comment by ErikEJ** [comment]
Please share your options via a screenshot or your efpt.config.json file.

**Comment by WeberEric** [comment]
![image](https://user-images.githubusercontent.com/8658679/83017443-f43a9180-a023-11ea-9d53-cadb27710250.png)

**Comment by ErikEJ** [comment]
Not sure it is something I can change - have you tried "UseDatabaseNames" ?

**Comment by WeberEric** [comment]
Now i checked the code and realized that you use the default ms scaffolder to create the model. I thought that you create the generated code. I think we can close this ticket for now. I modified your code for my needs. I think my changes are specific to my problem and not very common and they will create other problems in diffenet project.

private void PostProcessContext(string contextFile, ReverseEngineerCommandOptions options, string fixedNamespace)
        {
...
                finalLines.Add(line.Replace("Gu)", ")"));
...
        }

private void PostProcess(string file)
        {
            var text = File.ReadAllText(file, Encoding.UTF8);

            text = text.Replace("Gu =", " =");
            text = text.Replace("Gu {", " {");

            File.WriteAllText(file, PathHelper.Header + Environment.NewLine + text.TrimEnd(), Encoding.UTF8);
        }
