### ISSUE TITLE
Comment and Attribute  reverse

### ISSUE THREAD

**Issue by git-net** [ErikEJ/EFCorePowerTools#398]
[Table("tbl")]
    /// <summary>
    ///  some xxx
    /// </summary>
    public partial class tbl

=====>
  /// <summary>
    ///  some xxx
    /// </summary>
  [Table("tbl")]
    public partial class tbl

---------------------
for vs type tips.

**Comment by ErikEJ** [comment]
Are you saying the comment comes after the attribute, and should not?

**Comment by ErikEJ** [comment]
Thanks for reporting this. fixed in the latest daily build.
