### ISSUE TITLE
How to clear Reverse Engineer dropdown list of previous DBs

### ISSUE THREAD

**Issue by rcfearn** [ErikEJ/EFCorePowerTools#399]
Just wondering if there's a way to clear the Choose Database Connection dropdown list when reverse engineering?

![image](https://user-images.githubusercontent.com/5847855/83507573-13e22600-a50c-11ea-8929-1ba75089fafa.png)

**Comment by ErikEJ** [comment]
Duplicate of #293 - also see the wiki: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#reverse-engineer---workflow

**Comment by rcfearn** [comment]
Thanks sorry - I didn't find anything in Google and didn't realise the wiki was there.
