### ISSUE TITLE
Enable virtual on preperties to support lazy loading proxies

### ISSUE THREAD

**Issue by statler** [ErikEJ/EFCorePowerTools#40]
EF Core 2.1 introduces lazy loading. To use in its easiest configuration requires the collections / properties to be virtual. Am i right in saying this is not currently configurable, or is it something that needs to be done in Handlebars? If it is through handlebars, is it better treated as an option in the main program - this will be a pretty common use case.

https://docs.microsoft.com/en-au/ef/core/querying/related-data#lazy-loading

**Comment by ErikEJ** [comment]
How about just documenting how to do that with Handlebars?

**Comment by statler** [comment]
That would probably do the trick :)

**Comment by ErikEJ** [comment]
This will be fixed in EF Core 2.2

**Comment by ErikEJ** [comment]
Updated wiki https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering
