### ISSUE TITLE
Reverse engineer, separate projects for entities and dbContext : default settings

### ISSUE THREAD

**Issue by juergenil** [ErikEJ/EFCorePowerTools#400]
I have a Visual Studio solution, which contains two projects.     
One for entity types and another for db context.

Two wishes for improvements of the dialog "Generate EF Core Model in Project":
- A project, which contains entity types only, doesn't need to reference the EF core provider package.
The current behaviour is, that the dialog enables the corresponding check box, if the package isn't referenced yet. 

- In the same dialog the selection "what to generate" every time is set to "Entity type & DbContext".
The value of SelectedToBeGenerated in efpt.config.json isn't considered.
This is by design, see file ModelingOptionsViewModel.cs, line 79.
   ```csharp
   private void Loaded_Executed()
   {
    Model.SelectedToBeGenerated = 0;
   }
   ```
   Is there a reason for this behaviour?

### Steps to reproduce
- Create a solution with 2 projects (DotNet Standard 2.0)
- Right click to the first project, select "EF Core Power Tools / Reverse Engineer", select a Sql Server database, select a table, change "What to generate" to "Db Context only". Press OK.
- Do the same with the second project, but change "What to generate" to "Entity types only" and  uncheck "Install EF Core provider package in the project". Click OK.
- Repeate the previous two steps. The Field "What to generate" shows "Entity Types & DbContext".
For the project which contains the entity types, "Install EF Core provider package in the project" is checked.

### Further technical details
EF Core Power Tools version: 2.4.51.0
Database engine: (SQL Server 2019)
Visual Studio version: (Visual Studio Community 2019 16.6.1)

**Comment by ErikEJ** [comment]
@Herdo Re the second issue above, this was the old code before moving to MVVM. How can this be re-implemented? Just remove the snippet above??

``` csharp
textBox1.Focus();
            cmbLanguage.ItemsSource = new List<string> { "EntityTypes & DbContext", "DbContext only", "EntityTypes only" };
            cmbLanguage.SelectedIndex = 0;
            if (_options != null)
            {
                cmbLanguage.SelectedIndex = _options.SelectedToBeGenerated;
            }

```

**Comment by Herdo** [comment]
The initial value of 0 is just the fallback.The settings value should be taken into account when `ApplyPresets` is called.

**Comment by ErikEJ** [comment]
Thanks, I will check if I can repro. It might be a save settings issue.

**Comment by ErikEJ** [comment]
Hmm.. The value is persisted OK, but never reflected in the UI !?

```
        <ComboBox Grid.Row="12"
                  TabIndex="6"
                  ItemsSource="{Binding GenerationModeList}"
                  Style="{StaticResource GenerationMethodComboBoxStyle}"
                  SelectedIndex="{Binding Model.SelectedToBeGenerated, Mode=TwoWay}" />

```

**Comment by ErikEJ** [comment]
@Herdo I came to to the same conclusion, looking forward to your PR

**Comment by ErikEJ** [comment]
Your second issue is fixed in the latest daily build.

Not sure I can come up with a good solution for your first issue, there are too many "what if"s

**Comment by juergenil** [comment]
Thank you for the fast response. And I can understand your doubts.
