### ISSUE TITLE
Unable to Generate Computed Columns from . dacpac

### ISSUE THREAD

**Issue by mikehelsel** [ErikEJ/EFCorePowerTools#402]
I generated a set of entities, which includes a SQL table with a computed column.  The generated Entity and DbContext did not include the computed column and its configuration.

### Steps to reproduce
- Create a sqlproj database project that targets SQL 2008 or higher
- Create an Infrastructure/Persistence project to generate the entities
- Build the sqlproj to generate a dacpac
- Right click the Persistence project, select "EF Core Power Tools / Reverse Engineer", choose the Database project and click OK.
- Choose the table
- Generate the DbContext and Entities

### Further technical details
EF Core Power Tools version: 2.4.51.0
Database engine: SQL Server
Visual Studio version: Visual Studio 2019

**Comment by ErikEJ** [comment]
Support for computed columns from a .dacpac is currently not implemented, and under investigation (if possible at all)

**Comment by ErikEJ** [comment]
Would be very useful if you could share a .dacpac, so I can investigate.

**Comment by mikehelsel** [comment]
Thank you for the update.  I will use the database itself to generate the computed columns.  Also, I will work on setting up a local dacpac sample that I can share here.  Thanks again!

**Comment by mikehelsel** [comment]
Here is a sample of a very simple dacpac, in which the behavior can be reproduced easily.

[EntityFramework.Core.PowerTools.Database.zip](https://github.com/ErikEJ/EFCorePowerTools/files/4774709/EntityFramework.Core.PowerTools.Database.zip)

**Comment by ErikEJ** [comment]
Sadly, this is not possible. as you can see below, there is no information about the data type of the computed column in the dacpac:

![image](https://user-images.githubusercontent.com/4169187/84587408-426ed380-ae1f-11ea-9b63-866489cb3407.png)
