### ISSUE TITLE
How can i update an existing table without creating all new classes ?

### ISSUE THREAD

**Issue by kimdan157** [ErikEJ/EFCorePowerTools#404]
Describe what is not working as expected.

### Steps to reproduce
Include a complete description that I can redo to reproduce the issue.

### Further technical details
EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)

Database engine: (SQlite, SQL Compact, SQL Server, Postgres)

Visual Studio version: (e.g. Visual Studio 2017 15.7)

**Comment by kimdan157** [comment]
I just want to generate a class from an existing table. But when I use "Reverse Engineer" feature, I have no choice to do it. I must add new all tables in the database. So Do you have an idea to update it in the future?

**Comment by ErikEJ** [comment]
Yes, you must choose all tables to be generated each time, but your selection is saved from time to time in the efpt.config.jsob file. You should not start to modify the classes, but extend them with another partial class.

**Comment by ErikEJ** [comment]
Please feel free to re-open if that is unclear
