### ISSUE TITLE
Intellisense conflict with auto-generated comment

### ISSUE THREAD

**Issue by karenpayneoregon** [ErikEJ/EFCorePowerTools#405]
Describe what is not working as expected.

### Steps to reproduce
Perform reverse engineer, then on models generated intellisense acts strange with Resharper installed. Generally when code is dropped into a class an requires specific using statements not present Reshaper prompts to add them which it does but never works. Take out

` // <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
`
And now Reshaper works. So this could be a issue with Resharper? The rule of thumb with Reshaper at least for me is they want their log file sent to them and never had a solution afterwards.

This is something I can live with, keep a copy of the auto generated line in the Visual ToolBox so I can remove it to get intellisense working then if a new reverse engineering is needed put it back in first.

Visual Studio version: (e.g. Visual Studio 2017 15.9.18)

**Comment by ErikEJ** [comment]
Normally you should never edit the generated classes, but create a new partial class instead.

Have you tried disabling/pausing R# to find out if it is a R# issue?

**Comment by karenpayneoregon** [comment]
> Normally you should never edit the generated classes, but create a new partial class instead.
> 
> Have you tried disabling/pausing R# to find out if it is a R# issue?

In regards to using a new partial class, in this case that would not make sense as the only change is implementing INotifyPropertyChanged Interface with backing fields.  Have not tried disabling R# yet, on a roll on a code sample I'm working on. But one last thing, simply using // does not interfere with intellisense. 

Any ways it's not causing me any issues, just wanted to bring this to your attention.
