### ISSUE TITLE
Renaming with efpt.renaming.json doesn't work if "Use table and column name directy from the database" is checked

### ISSUE THREAD

**Issue by pmonte** [ErikEJ/EFCorePowerTools#407]
Describe what is not working as expected.
Coloums and tables names renamed as per efpt.renaming.json  config

### Steps to reproduce
Simply check "Use table and column name directy from the database" in the option

### Further technical details
EF Core Power Tools version: V2.4.5.1.0

Database engine: SQL Server

Visual Studio version: 2019 V 16.6.2

**Comment by ErikEJ** [comment]
Unfortunately this is by design, as the Interface I override to do the custom renaming is never called when the above option is selected.

**Comment by pmonte** [comment]
> Unfortunately this is by design, as the Interface I override to do the custom renaming is never called when the above option is selected.
Is this something that could be changed? I'm sure I'm not alone in a situation where you have hundreds of tables and thousands of columns, need to keep them with th DB names, and have to rename just some virtual navigation properties.

**Comment by ErikEJ** [comment]
It is just software, so anything can be changed, but it requires changes in EF Core, so don't hold your breath.

**Comment by UseMuse** [comment]
I am also interested in such functionality. 
What if provide it in the settings tools => options => ef core power tools?

**Comment by ErikEJ** [comment]
@UseMuse this issue is 4 years old and closed. If you have an issue, please create a new one with full repro details.

**Comment by UseMuse** [comment]
@ErikEJ https://github.com/ErikEJ/EFCorePowerTools/issues/2454
