### ISSUE TITLE
another indirect link

### ISSUE THREAD

**Issue by DickBaker** [ErikEJ/EFCorePowerTools#408]
on page
https://github.com/ErikEJ/SqlCeToolbox/wiki/EntityFramework-Reverse-POCO-Code-First-Generator
there is a "EF Core Power Tools" link to
https://github.com/ErikEJ/SqlCeToolbox/wiki/EF-Core-Power-Tools
that states
"This page has moved to https://github.com/ErikEJ/EFCorePowerTools/wiki"

please make the 1st link go there directly

**Comment by ErikEJ** [comment]
Removed several obsolete pages, thanks
