### ISSUE TITLE
Feature Request: vscode support

### ISSUE THREAD

**Issue by divinebovine** [ErikEJ/EFCorePowerTools#409]
This looks like a great tool are there any plans to add support for vscode? I know there's probably a lot pre-requisites in order for that to work, but it'd be great to be able use it there as well.

**Comment by ErikEJ** [comment]
No current plans, I am considering a command line tool for reverse engineering, but see no upvotes for that feature either

**Comment by divinebovine** [comment]
Where do I upvote?

**Comment by ErikEJ** [comment]
#340

**Comment by ErikEJ** [comment]
Preview 1 of the CLI tool is [now available](https://www.nuget.org/packages/ErikEJ.EFCorePowerTools.Cli/7.0.0-preview1#readme-body-tab)

![image](https://user-images.githubusercontent.com/4169187/234258058-2b6def58-f87c-455a-93da-21cd09d9e3f7.png)
