### ISSUE TITLE
[Feature] Add option to not remove model class when unchecked from Table selection. 

### ISSUE THREAD

**Issue by tylerwp** [ErikEJ/EFCorePowerTools#412]
We reuse this often when we update our database. 
Many of our model classes have validation added later but when we run the tool again it overwrites when checked and removes if unchecked. 
For now, we just make a backup of that model class and add it back after the tool is run again.

**Comment by ErikEJ** [comment]
The model classes are partial - could you not take advantage of that?

Could you show an example of the modification you make?

**Comment by ErikEJ** [comment]
If you remove the auto-generated comment, the file will not be deleted, but unchecked items must be added manually to the DbContext

**Comment by tylerwp** [comment]
@ErikEJ Thanks! After your comment, I did a little research and found how to take advantage of the partial classes using DataAnnotations. After learning this I guess this feature is not even necessary ;)

**Comment by ErikEJ** [comment]
Perfect - can you share an example of what you did? 
I think it could be very useful for others?

**Comment by tylerwp** [comment]
[Using DataAnnotations with entity models that are dynamically generated](https://ryanhayes.net/data-annotations-for-entity-framework-4-entities-as-an-mvc-model/)

Here is another example nesting the classes

```csharp

using System.ComponentModel.DataAnnotations;

namespace Validate.Models
{
    [MetadataType(typeof(MetaData))]
    public partial class Person
    {
        public class MetaData
        {
            [Required]
            [Display(Name = "Enter Your Name")]
            public string FirstName;

          
        }
    }
}

```

**Comment by ErikEJ** [comment]
And this also works with .NET Core / ASP.NE Core?

**Comment by tylerwp** [comment]
> And this also works with .NET Core / ASP.NET Core?

Yes, but it looks to be a messy workaround. I hope to find a better solution, but this is all I have been able to come up with for Core.
https://stackoverflow.com/questions/34576921/asp-net-core-metadatatype-attribute-not-working

**Comment by netbitshift** [comment]
I have since switched my Db models to use the Fluent api approach.  This also lets me take advantage of column default values.  Tested with a dummy app & db and it works.  No more worrying about putting annoations "allowemptystrings=true" after a rev eng step
