### ISSUE TITLE
How to #if property-name == 'Description'

### ISSUE THREAD

**Issue by danielegithub** [ErikEJ/EFCorePowerTools#413]
HI,
This tools is fantastic.
I have a difficulty, I would like to understand how to do a #if in Handlbars, for compare property-name with string.
Thanks.

**Comment by ErikEJ** [comment]
Thanks - maybe @tonysneed can help?

**Comment by danielegithub** [comment]
thanks. 
Why would I need to put an if to have the base-classes.

**Comment by tonysneed** [comment]
@danielegithub Happy to answer your question! Best to open an issue over on the [Handlebars Scaffolding repo](https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars/issues).
