### ISSUE TITLE
IDesignTimeServices for Handlebars

### ISSUE THREAD

**Issue by jryutzy** [ErikEJ/EFCorePowerTools#416]
Is there anyway to leverage Handlebars Helpers and Transformers and use EF Core Power Tools?
https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#handlebars-helpers-and-transformers

I like the EF Core Power Tools but I want to do some things that require me to use the Helper methods.

I didn't see how to add a ScoffoldingDesignTimeServices : IDesignTimeServices class and have EF Core Power Tools call it.

I'm running the scaffolding from command line in PS and it uses my customizations as shown in the article.

I love the Power Tools though and wish I could have the best of both worlds ;-)

**Comment by ErikEJ** [comment]
No, it is not possible. But if you describe your customizations, maybe they can be achieved in another way?

**Comment by jryutzy** [comment]
I want to be able to generate a list of Foreign Key include classes for each Class so when you do eager loading you can Reference Model. ForeignKeyIncludes.Country.Many for example and that would include all relationships that have an ICollection for object. I got it working with Tony’s handlebars and healer methods.
This saves you from having to remember each include on eager loading


-----Original Message-----

**Comment by ErikEJ** [comment]
Could you show me a code sample?

**Comment by jryutzy** [comment]
Sure.. below is what I'm trying to accomplish. I think i can get close enough with the IDesign 
![image](https://user-images.githubusercontent.com/67274124/86389707-bd7c1a80-bc64-11ea-8451-faa05422d175.png)

**Comment by ErikEJ** [comment]
Thanks. This is not possible, sorry.
