### ISSUE TITLE
How to supply values for handlebar tags 

### ISSUE THREAD

**Issue by tlowry00** [ErikEJ/EFCorePowerTools#421]
Describe what is not working as expected.
Not able to get base classes working for reverse engineering

### Steps to reproduce
Include a complete description that I can redo to reproduce the issue.
- I have enabled Customizing code using Handlebar templates by checking the box

- added code to Class.hbs in CSharpEntityType --> Partials
   public partial class {{class}} : {{base-class}}
                      {
                        {{{> constructor}}}
                        {{> properties}}
                       }
- added code to initialize value for base-class in the Startup  ConfigureServices
           services.AddHandlebarsScaffolding(options =>
            {
                // Add custom template data
                options.TemplateData = new Dictionary<string, object>
                {
                   { "base-class", "McfBaseEntity" }
                };
            });
- When I Reverse Engineer with EF Core Power Tools - it generates the POCO classes with the construction as indicated in the template - but the base-class name is empty (as if it didn't get the value for the base-class tag. 

          // <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
          using System;
          using System.Collections.Generic;
          using System.ComponentModel.DataAnnotations;
          using System.ComponentModel.DataAnnotations.Schema;

          namespace Server.Models
          {
          [Table("User")]

          public partial class User : 
          {
                  public User()
                  {
                      UserLocations = new HashSet<UserLocation>();
                  }

                  [Key]
                  public int UserId { get; set; }
                  public bool IsActive { get; set; }
                  [Column(TypeName = "datetime")]

                    ...
          }

          }

Which leads me to believe that I am probably supplying the tag value in the wrong place

I've checked in the all the documentation I could find and I think the syntax I have is correct but I couldn't find where the AddHandlebarsScaffolding should be implemented to supply the tag values

### Further technical details
EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
- 2.4.51

Database engine: (SQlite, SQL Compact, SQL Server, Postgres)
- SQL Server

Visual Studio version: (e.g. Visual Studio 2017 15.7)
- VS Professional 2019 Version 16.6.3

**Comment by ErikEJ** [comment]
EF Core Power Tools does not interact with your design time code, you must use "Scaffold-DbContext" for this to work.

**Comment by tafs7** [comment]
@ErikEJ  - it's me again :)  I'm just trolling thru closed issues looking for answers for those who have gone before me...ha

so, I need to add a base class type to the Class.hbs entity template, but my base type is generic where the "T" is the name of the DbContext.  E.g.:

`public partial class SomeEntity : MyApp.Data.DataAccessObjectBase<NorthwindEntities>{ }`

I'm not sure I followed your comment to use the `Scaffold-DbContext` tool.  Is there a way to either have access to the name of the DbContext type in the Class.hbs template (e.g. `{{db-context-name}}`, or set a dictionary of template data that can be used in the hbs template files, as @tlowry00 was describing, and that can be applied per DbContext?

**Comment by ErikEJ** [comment]
I don't know much about Handlebars. If you have proposals or issues, please raise an new issue.
