### ISSUE TITLE
[Feature] Reverse Engineering to put Configurations classes into a separate Folder

### ISSUE THREAD

**Issue by szabczy** [ErikEJ/EFCorePowerTools#423]
Thank You for the Excellent product!

As a minor improvement it would be nice to generate the configuration classes into another folder, with its own namespace:
The DBContext could go to **PROJECT/Persistence** and the configurations to **PROJECT/Persistence/Configurations**, each using their own namespace.

**Comment by ErikEJ** [comment]
Yes, as you noticed, that feature is currently not fully backed, but in preview.

I assume there will be many variations of this requirement, so thanks for your feedback so far.

**Comment by ErikEJ** [comment]
Just to be sure: what would be an advantage of this (more than just "nice") ?

**Comment by szabczy** [comment]
I am trying to implement a kind of Clean Architecture pattern.

My solution consists of several projects: Domain, Application, Infrastructure, WebApp, etc.

With the existing Reverse Engineering I succeeded to put the (unannotated) table definitions into the project **Domain** folder **Entities** , whereas the remaining stuff is put under **Infrastructure/Persistence**. This way I should be able to separate the data models used in business logic from the actual database implementation.

In the examples I am working from, the Configuration classes have their own folder under Persistence, due to their specific role. Currently I have some 260 tables and it would really help if I could put the DBContext class into a separate folder.

Right now I am doing it manually by generating DBContext+Conf into **Infrastructure/Persistence/Configurations** and moving the DBContext up to folder Persistence and adjusting the namespaces.

**Comment by ErikEJ** [comment]
So maybe always put them in a Configurations sub folder/namespace for now?

**Comment by szabczy** [comment]
Also there is a minor annoyance: Reverse Engineering generates duplicate **using**-s.
As I mentioned earlier I try to organize my solution based on the Clear Architecture principle.
My projects look like this:
![image](https://user-images.githubusercontent.com/13044346/88375541-0e7eba80-cd9c-11ea-93c5-1634d61ae483.png)
(Reverse engineered entities and configurations go into the highlighted folders.)

To achieve this I use the following configuration:
![image](https://user-images.githubusercontent.com/13044346/88375881-abd9ee80-cd9c-11ea-8fef-daa4e32a2988.png)

The generated output is excellent, with one small issue: 
![image](https://user-images.githubusercontent.com/13044346/88375315-a62fd900-cd9b-11ea-9b24-973d40d7f4f9.png)
The code compiles fine, but I get an extra 267 warnings.

I have already tried to play around with the configuration settings, but so far I haven't found a solution.

Maybe some sort of filtering should be applied when generating the usings.

**Comment by ErikEJ** [comment]
Looks like the usings should be distinct and sorted!

**Comment by ErikEJ** [comment]
I have created #430

**Comment by ErikEJ** [comment]
@szabczy "usings" issue fixed in latest daily build

**Comment by ErikEJ** [comment]
@szabczy Have a look at this PR https://github.com/ErikEJ/EFCorePowerTools/pull/530

**Comment by zatanboy** [comment]
> Thank You for the Excellent product!
> 
> As a minor improvement it would be nice to generate the configuration classes into another folder, with its own namespace:
> The DBContext could go to **PROJECT/Persistence** and the configurations to **PROJECT/Persistence/Configurations**, each using their own namespace.

**Comment by ErikEJ** [comment]
Fixed in latest daily build, please let me know if that works for you.
