### ISSUE TITLE
Scaffold not handling startup assembly, therefore not discovering custom DesignTimeService

### ISSUE THREAD

**Issue by Herdo** [ErikEJ/EFCorePowerTools#427]
We're having a custom `IDesignTimeServices` implementation in our EF core project to perform some additional customizations when scaffolding from the database. This customization is changing the handlebar behavior by excluding some additional tables and changing property types.

When scaffolding from command line with `dotnet scaffold` the design time services are applied correctly.
When using EF Core Power Tools "Reverse Engineer", the services are not applied. Assumption what's causing this issue is stated below in "Analysis".

### Steps to reproduce
1. Create blank solution.
2. Add empty database project and empty C# project to scaffold context and entities into, including NuGet packages for EF Core and handlebars.
3. Add table `dbo.User` with `UserId INT NOT NULL PRIMARY KEY` column to the database project.
4. Add custom design time services to C# project.
5. Configure handlebar transformers in custom design time services:

```language:c#
public class ScaffoldingDesignTimeServices : IDesignTimeServices
{
    public void ConfigureDesignTimeServices(IServiceCollection services)
    {
        services.AddHandlebarsTransformers(propertyTransformer: p =>
        {
            // Map to strong types
            var nullable = p.PropertyType.Contains("System.Nullable") || p.PropertyType.Contains("?");
            if (p.PropertyName.Contains("UserId"))
                return new EntityPropertyInfo(CreateNewPropertyType<UNITS.Shared.StrongTypes.InternalUserId>(nullable), p.PropertyName);
        });
    }

    private static string CreateNewPropertyType(string propertyType) => propertyType == "string" ? "string?" : propertyType;

    private static string CreateNewPropertyType<TType>(bool nullable)
    {
        var fullName = typeof(TType).FullName;
        if (fullName == null)
            throw new InvalidOperationException();
        return nullable ? $"{fullName}?" : fullName;
    }
```

6. Scaffold the database project into the C# project with handlebars using the "Reverse Engineer" command of EF Core Power Tools.
7. Generated entity for the `User` table will have a property `int UserId { get; set; }` (**this is wrong, design time service was not applied**).
8. Scaffold the database project into the C# project with handlebars using the command line dbcontext scaffold.
9. Generated entity for the `User` table will have a property `UNITS.Shared.StrongTypes.InternalUserId UserId { get; set; }` (**this is correct, design time service was applied**).

### Further technical details
EF Core Power Tools version: 2.4.51.0
Database engine: SQL Server / Scaffold from DACPAC
Visual Studio version: Visual Studio 2019 16.6.2

### Analysis
I had a look at the verbose command line logs of the `dbcontext scaffold` command and at the source code of the EF Core scaffold pipeline.
The verbose output points out that the custom design time services class is found:
```
Using assembly 'UNITS.Server.Database'.
Using startup assembly 'UNITS.Server.Database'.
Using application base 'S:\herdo-opensource\HoU UNITS\src\Server.Database\bin\Debug\netcoreapp3.1'.
Using working directory 'S:\herdo-opensource\HoU UNITS\src\Server.Database'.
Using root namespace 'UNITS.Server.Database'.
Using project directory 'S:\herdo-opensource\HoU UNITS\src\Server.Database\'.
Finding design-time services for provider 'Microsoft.EntityFrameworkCore.SqlServer'...
Using design-time services from provider 'Microsoft.EntityFrameworkCore.SqlServer'.
Finding design-time services referenced by assembly 'UNITS.Server.Database'.
No referenced design-time services were found.

---> These two lines are important:
Finding IDesignTimeServices implementations in assembly 'UNITS.Server.Database'...
Using design-time services from class 'ScaffoldingDesignTimeServices'.
```

Looking at the source code of the pipeline in the [`Microsoft.EntityFrameworkCore.Design.Internal.DesignTimeServicesBuilder` ](https://github.com/dotnet/efcore/blob/master/src/EFCore.Design/Design/Internal/DesignTimeServicesBuilder.cs) class the `IDesignTimeServices` implementations are searched for in three steps:

1. `ConfigureProviderServices` --> which would be the EF Core Power Tools [DACPAC provider](https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/ErikEJ.EntityFrameworkCore.SqlServer.Dacpac/Design/SqlServerDacpacDesignTimeServices.cs) in the scenario above.
2. `ConfigureReferencedServices` --> probably none?
3. `ConfigureUserServices` --> this is not working with EF Core Power Tools

[`ConfigureUserServices`](https://github.com/dotnet/efcore/blob/644d3c8c3a604fd0121d90eaf34f14870e19bcff/src/EFCore.Design/Design/Internal/DesignTimeServicesBuilder.cs#L90-L107) however is the important part. This method is loading the `IDesignTimeServices` implementation from the **startup project**:

```language:c#
private void ConfigureUserServices(IServiceCollection services)
{
    _reporter.WriteVerbose(DesignStrings.FindingDesignTimeServices(_startupAssembly.GetName().Name));

    var designTimeServicesType = _startupAssembly.GetLoadableDefinedTypes()
        .Where(t => typeof(IDesignTimeServices).IsAssignableFrom(t)).Select(t => t.AsType())
        .FirstOrDefault();
    if (designTimeServicesType == null)
    {
        _reporter.WriteVerbose(DesignStrings.NoDesignTimeServices);
        return;
    }

    _reporter.WriteVerbose(DesignStrings.UsingDesignTimeServices(designTimeServicesType.ShortDisplayName()));
    ConfigureDesignTimeServices(designTimeServicesType, services);
}
```

**Therefore, I assume there's an issue that EF Core Power Tools is not passing the startup assembly correctly to the scaffold pipeline.**

**Comment by Herdo** [comment]
After some debugging, it looks like the [`Microsoft.EntityFrameworkCore.Design.Internal.DesignTimeServicesBuilder`](https://github.com/dotnet/efcore/blob/master/src/EFCore.Design/Design/Internal/DesignTimeServicesBuilder.cs) is not used at all, and instead the `ReverseEngineer20.ReverseEngineer.ServiceProviderBuilder` is used, right?

I guess that one needs to be extended with the option to load the custom `IDesignTimeServices`?

**Comment by Herdo** [comment]
Falling back to command line scaffolding until this issue is fixed 😕

**Comment by ErikEJ** [comment]
This is not something I plan to support, too many pits of failure.

**Comment by Herdo** [comment]
That's too bad 😢 
Maybe at least add an information to the readme.md, that using custom `IDesignTimeServices` with EF Core Power Tools is not supported? Maybe at the handlebars section?

**Comment by ErikEJ** [comment]
Yes, I will do that, at the Handlebars section, as this seem to come up again and again.

**Comment by ErikEJ** [comment]
I will also investigate the possibility of doing this. One of the issues here will be that suddenly EF Core Power Tools will require the project to build. And I think it is no as simple as just loading a single DLL file.

**Comment by Herdo** [comment]
> I will also investigate the possibility of doing this. One of the issues here will be that suddenly EF Core Power Tools will require the project to build. And I think it is no as simple as just loading a single DLL file.

Yeah, of cause. That's the same that's already going on with the command line scaffolding. When the project doesn't build, the scaffold won't work. This has certainly some drawbacks.

**Comment by ErikEJ** [comment]
Yes, and one of the Power Tools selling points is exactly that - but if course all the above should be opt-in and not automagic.

**Comment by ErikEJ** [comment]
I you make this optional, I am willing to accept a PR 😎

**Comment by ErikEJ** [comment]
This can be done with the command line tooling, not something I plan to implement.
