### ISSUE TITLE
Migration Tool Error

### ISSUE THREAD

**Issue by bbehling** [ErikEJ/EFCorePowerTools#428]
To open the migration tool without it crashing.

### Steps to reproduce
Open Migration Tool. Tool will crash with this error:

---------------------------
Microsoft Visual Studio
---------------------------
EF Core Power Tools

Error:

System.MissingMethodException: Method not found: 'Boolean Microsoft.EntityFrameworkCore.Migrations.IMigrationsModelDiffer.HasDifferences(Microsoft.EntityFrameworkCore.Metadata.IModel, Microsoft.EntityFrameworkCore.Metadata.IModel)'.

   at ReverseEngineer20.EfCoreMigrationsBuilder.GetMigrationStatus(DbContext context)

   at ReverseEngineer20.EfCoreMigrationsBuilder.GetMigrationStatus(String outputPath) in C:\Code\EFCorePowerTools\src\GUI\efpt\EFCoreMigrationsBuilder.cs:line 79

   at ReverseEngineer20.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efpt\Program.cs:line 26

**Comment by ErikEJ** [comment]
Can you share your project file?

Which Power Tools version?

**Comment by mawibo** [comment]
I have the exact same issue. I'm using EF Core 5.0.0-preview.6.20312.4 and Power Tools 2.4.51
Please have a look at the attached .csproj file.
[SimLauncherX.csproj.zip](https://github.com/ErikEJ/EFCorePowerTools/files/4965677/SimLauncherX.csproj.zip)

**Comment by ErikEJ** [comment]
Which Power Tools version? Unless you are trying the latest daily build, EF Core 5 model inspection is not supported.

**Comment by ErikEJ** [comment]
@mawibo You need the latest daily build for EF Core 5 support

**Comment by bbehling** [comment]
Why is this closed? Its not fixed, I'm using version 0.9.65 and I'm trying to model inspection. I simply righted clicked in solution explorer to launch Migrations Tool (preview) and it crashed.
