### ISSUE TITLE
Configuration classes are not added to classic .NET Framework project

### ISSUE THREAD

**Issue by karenpayneoregon** [ErikEJ/EFCorePowerTools#429]
Configuration classes not created

### Steps to reproduce

- Using Visual Studio 2017 with all update on Windows 10
- Create a new C# class project
- Using NuGet package manager install  Microsoft.EntityFrameworkCore.SqlServer 3.1.5
- SQL-Server database https://github.com/karenpayneoregon/NorthWind-2020/blob/master/North2020Script.sql
- Select "reverse engineer", select above database, "Use EF Core 3x" checked
- Select tables (see attachment)
- Configuration (see attachment)
- Perform reverse engineering
- The code below is generated but none of the configuration classes like BusinessEntityPhoneConfiguration

**Note images are out of order**

![errors](https://user-images.githubusercontent.com/17032797/88285063-540b8c80-cca3-11ea-809b-a0a67f1186c5.png)

```csharp
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.ApplyConfiguration(new BusinessEntityPhoneConfiguration());
    modelBuilder.ApplyConfiguration(new CategoriesConfiguration());
    modelBuilder.ApplyConfiguration(new ContactDevicesConfiguration());
    modelBuilder.ApplyConfiguration(new ContactTypeConfiguration());
    modelBuilder.ApplyConfiguration(new ContactsConfiguration());
    modelBuilder.ApplyConfiguration(new CountriesConfiguration());
    modelBuilder.ApplyConfiguration(new CustomersConfiguration());
    modelBuilder.ApplyConfiguration(new EmployeesConfiguration());
    modelBuilder.ApplyConfiguration(new OrderDetailsConfiguration());
    modelBuilder.ApplyConfiguration(new OrdersConfiguration());
    modelBuilder.ApplyConfiguration(new PhoneTypeConfiguration());
    modelBuilder.ApplyConfiguration(new ProductsConfiguration());
    modelBuilder.ApplyConfiguration(new ShippersConfiguration());
    modelBuilder.ApplyConfiguration(new SuppliersConfiguration());


    OnModelCreatingPartial(modelBuilder);
}
```

![settings](https://user-images.githubusercontent.com/17032797/88284688-abf5c380-cca2-11ea-8843-9bcf2d644169.png)

![models](https://user-images.githubusercontent.com/17032797/88284504-5caf9300-cca2-11ea-9eaa-abb1f56e39c8.png)

### Further technical details
EF Core Power Tools version: 

Version 2.4.51.0

SQL Server Compact 4.0 in GAC - No
SQL Server Compact 4.0 DbProvider - No

SQL Server Compact 4.0 DDEX provider - No
SQL Server Compact 4.0 Simple DDEX provider - Yes

SQLite ADO.NET Provider included: 1.0.110.0
SQLite EF6 DbProvider in GAC - No

System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes

**efpt.config.json**
```json
{
   "ContextClassName": "NorthwindContext",
   "ContextNamespace": null,
   "DefaultDacpacSchema": null,
   "DoNotCombineNamespace": false,
   "IdReplace": false,
   "IncludeConnectionString": true,
   "ModelNamespace": null,
   "OutputContextPath": "Context",
   "OutputPath": "Models",
   "ProjectRootNamespace": "NorthEntityFrameworkCoreLibrary",
   "SelectedHandlebarsLanguage": 0,
   "SelectedToBeGenerated": 0,
   "Tables": [
      {
         "HasPrimaryKey": true,
         "Name": "[dbo].[BusinessEntityPhone]"
      },
      {
         "HasPrimaryKey": true,
         "Name": "[dbo].[Categories]"
      },
      {
         "HasPrimaryKey": true,
         "Name": "[dbo].[ContactDevices]"
      },
      {
         "HasPrimaryKey": true,
         "Name": "[dbo].[Contacts]"
      },
      {
         "HasPrimaryKey": true,
         "Name": "[dbo].[ContactType]"
      },
      {
         "HasPrimaryKey": true,
         "Name": "[dbo].[Countries]"
      },
      {
         "HasPrimaryKey": true,
         "Name": "[dbo].[Customers]"
      },
      {
         "HasPrimaryKey": true,
         "Name": "[dbo].[Employees]"
      },
      {
         "HasPrimaryKey": true,
         "Name": "[dbo].[OrderDetails]"
      },
      {
         "HasPrimaryKey": true,
         "Name": "[dbo].[Orders]"
      },
      {
         "HasPrimaryKey": true,
         "Name": "[dbo].[PhoneType]"
      },
      {
         "HasPrimaryKey": true,
         "Name": "[dbo].[Products]"
      },
      {
         "HasPrimaryKey": true,
         "Name": "[dbo].[Shippers]"
      },
      {
         "HasPrimaryKey": true,
         "Name": "[dbo].[Suppliers]"
      }
   ],
   "UseDatabaseNames": false,
   "UseDbContextSplitting": true,
   "UseFluentApiOnly": true,
   "UseHandleBars": false,
   "UseInflector": false,
   "UseLegacyPluralizer": false,
   "UseSpatial": false
}
```
Database engine: **Microsoft SQL Server** 2017 (RTM) - 14.0.1000.169 (X64) 
	Aug 22 2017 17:04:49 
	Copyright (C) 2017 Microsoft Corporation
	Express Edition (64-bit) on Windows 10 Enterprise 10.0 <X64> (Build 18363: )

**Visual Studio** version: 15.9.18

**Comment by ErikEJ** [comment]
Is this a .NET Framework or Core class library?

**Comment by karenpayneoregon** [comment]
This is a standard .NET Framework class library.

**Comment by ErikEJ** [comment]
Ah! No one uses .net framework anymore😄

I bet the files are there, just not added to the project.

I will get it fixed, thanks for reporting.

**Comment by karenpayneoregon** [comment]
You are correct about the configuration files being there and not in the project, never thought to check that. In regards nobody using .NET Framework anymore, there are many still using the .NET Framework and that is something I'm looking to change as I'm just about done with it article wise and will be pushing to .NET Core Framework. Thanks for taking time on this.

**Comment by ErikEJ** [comment]
This is a bug, and I need to fix it 😊
