### ISSUE TITLE
Handlebars files not very useful

### ISSUE THREAD

**Issue by MgSam** [ErikEJ/EFCorePowerTools#43]
First off, thank you for your great work on this tool! It is very useful in generating a model from an existing database.

That said, I don't think the handlebars files that EF Core Power Tools generates are particularly useful. They seem to reference elements that are not exposed.

```
{{> dbimports}}

namespace {{namespace}}
{
    public partial class {{class}} : DbContext
    {
{{> dbsets}}
{{#if entity-type-errors}}
{{#each entity-type-errors}}
{{spaces 8}}{{{entity-type-error}}}
{{/each}}

{{/if}}

{{{on-configuring}}}
{{{on-model-creating}}}
    }
}
```
In this snippet- only 'dbsets' and 'dbimports' are actually exposed as files. Everything else is just a magic string that is calling some hidden code somewhere. This extremely limits how much we can use this file to customize.

On a related note- this is a Visual Studio extension- so why not use T4 templates instead of handlebar templates? T4 templates are totally transparent as to what is generated and where the data comes from, they are consistent with what the EF6 tooling does, and I also find them much easier to read. These handlebar templates seem much harder to read (since they seem to be inserting spaces with a function, and can just reference magic strings somewhere else)

**Comment by ErikEJ** [comment]
Agree, but it is not something I can change

**Comment by MgSam** [comment]
@ErikEJ Can you elaborate a little?

**Comment by ErikEJ** [comment]
Not really, see my comment to the view support issue.

The scaffolding provided by EF Core is not T4 based for various reasons, and I do not have the time or resources to invent another scaffolding approach. The current approach is supported by many providers: SQLite, SQL Server, SQL CE, Npgsql and potentially MySQL

**Comment by tonysneed** [comment]
FYI, Handlebars has an extensibility mechanism called helpers, which allows you to fully customize the output.  See [here](https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#handlebars-helpers).
