### ISSUE TITLE
TableAttribute not generated on models when scaffolding

### ISSUE THREAD

**Issue by manuel-fernandez-rodriguez** [ErikEJ/EFCorePowerTools#435]
I am using your library to scaffold a dacpac file and it doesn't include the expected TableAttribute on the generated models.

If I scaffold using the real Sql Server database, those attributes are properly generated.

### Steps to reproduce
1. Create a dacpac which contains tables in a given  schema
2. Create a powershell file like this one:
```
$DACFileName='"..\relativepath.to\file.dacpac"'

dotnet ef dbcontext scaffold $DACFileName ErikEJ.EntityFrameworkCore.SqlServer.Dacpac --force --data-annotations `
--context ConsumptionDbContextBase --context-dir ObjectAccessContext/Consumption `
-o Models/Consumption `
--schema General
```
3. Execute it

4. Check that no TableAttribute like the following one has been generated on any of the model classes:

```
[Table("Contract", Schema = "General")]
```
![image](https://user-images.githubusercontent.com/48520205/88913619-99125e80-d261-11ea-90a5-d8d674c1176a.png)

### Further technical details
EF Core Power Tools version: nuget package 3.1.6

Database engine: DacPac from SQL Server

Visual Studio version: Visual Studio 2019 16.6.3

Entity Framework Core tools (dotnet-ef): 3.1.6

**Comment by ErikEJ** [comment]
Hmmmm...
Currently, the scaffolder considers the first schema passed to it as the default schema:

https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/ErikEJ.EntityFrameworkCore.SqlServer.Dacpac/Scaffolding/SqlServerDacpacDatabaseModelFactory.cs#L54 

And since you are passing "General" this is interpeted as the default (so no need to add the attribute).

Maybe you can change your command line to:

```cmd
dotnet ef dbcontext scaffold $DACFileName ErikEJ.EntityFrameworkCore.SqlServer.Dacpac --force --data-annotations `
--context ConsumptionDbContextBase --context-dir ObjectAccessContext/Consumption `
-o Models/Consumption `
--schema NonExistingName --schema General

```

**Comment by manuel-fernandez-rodriguez** [comment]
Thank you so much for the quick reply.

Tried your suggestion and it worked like a charm!

In spite there's an inconsistency between both behaviors, I think the workaround is satisfactory, so closing the issue right away.

**Comment by ErikEJ** [comment]
I will leave this open to update the docs here https://github.com/ErikEJ/EFCorePowerTools/wiki/ErikEJ.EntityFrameworkCore.SqlServer.Dacpac  with this workaround.

**Comment by ErikEJ** [comment]
Docs updated
