### ISSUE TITLE
Exception : System.ArgumentException: Illegal characters in path. No actionable information provided.

### ISSUE THREAD

**Issue by kdawg1406** [ErikEJ/EFCorePowerTools#436]
Describe what is not working as expected.
When I run any of the commands from the context menu I get the below exception.
The error message in the output window does not provide any actional information.  
Project is a .NET Core 3.1 web API project.

Can you please wrap the code in a try-catch block and test for `System.ArgumentException: Illegal characters in path.` so that you can report to the user the exact path causing the exception.  

I have no weird characters in my file names or with my codebase.  I just created this project yesterday from scratch.

### Steps to reproduce
Right clicked on my project, selected EF CORE POWER TOOLS.  any of the men subitems display this exception in the output window.

```
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at EFCorePowerTools.Extensions.ProjectExtensions.GenerateFiles(Project project, List`1 result, String extension) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Extensions\ProjectExtensions.cs:line 178
   at EFCorePowerTools.Handlers.ModelAnalyzerHandler.Generate(String outputPath, Project project, GenerationType generationType) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ModelAnalyzerHandler.cs:line 84
```

### Further technical details
Version 2.4.51.0

SQL Server Compact 4.0 in GAC - No
SQL Server Compact 4.0 DbProvider - No

SQL Server Compact 4.0 DDEX provider - No
SQL Server Compact 4.0 Simple DDEX provider - Yes

SQLite ADO.NET Provider included: 1.0.109.0
SQLite EF6 DbProvider in GAC - No

System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes

Database engine: (SQlite, SQL Compact, SQL Server, Postgres)  `SQL SERVER 2017 with 2018 tools.`

Visual Studio version: (e.g. Visual Studio 2017 15.7)  `16.6.5`

**Comment by kdawg1406** [comment]
Seems this has happened to other developers as well.  I'm not using any shares, my path to temp is `C:\Users\saved\AppData\Local\Temp`  Would really like to be able to use these awesome tools, thank you.  

[https://github.com/ErikEJ/EFCorePowerTools/issues/341](https://github.com/ErikEJ/EFCorePowerTools/issues/341)

**Comment by ErikEJ** [comment]
@kdawg1406 Glad you would like to try my tools! Have you tried to install the latest daily build, I think it has a fix for your issue?

**Comment by ErikEJ** [comment]
Link to fix: https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/EFCorePowerTools/Extensions/ProjectExtensions.cs#L179

**Comment by kdawg1406** [comment]
@ErikEJ  the daily build works perfectly on my machine!  Thank you.

Suggestion:  The ReadMe.md link to the VSIX Gallery incorrect.  Clicking on the current one yields a browser warning to an unsecured site.  Also, the vsix name is incorrect.  If you send them to the correct link, they can read the information page and download the correctly named vsix.

**Current**: [https://vsixgallery.com/extensions/f4c4712c-ceae-4803-8e52-0e2049d5de9f/extension.vsix](https://vsixgallery.com/extensions/f4c4712c-ceae-4803-8e52-0e2049d5de9f/extension.vsix
)
**Correct**:  [https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f)

Do you leave this open or should I close it since it's not in the production build?

**Comment by ErikEJ** [comment]
I have updated the readme and links in the wiki - this is due to VSIX gallery just haveing been updated.

I have also updated the release notes with the exact error message, so closing this.

Thanks for the review!
