### ISSUE TITLE
Feature Request - Reverse Engineer UDFs

### ISSUE THREAD

**Issue by DawgCoder** [ErikEJ/EFCorePowerTools#437]
Please consider adding the ability to reverse engineer stored procedures and user defined functions. My current customer only allows DB access via these methods and we have well over 300 SP/UDFs. We are currently modernizing the application and unfortunately have to revert back to EF 6.4.4 for the time being.

### Steps to reproduce
N/A

### Further technical details
EF Core Power Tools version: 2.4.51.0

Database engine: SQL Server

Visual Studio version: Visual Studio 2019 16.6.5

**Comment by ErikEJ** [comment]
The latest daily build enables you to reverse enginner stored procs - https://github.com/ErikEJ/EFCorePowerTools/wiki/Release-notes
For UDFs, maybe you could provide a sample of your vision /API for the functionality for scalar value and table valued functions ?

**Comment by DawgCoder** [comment]
Erik,

Thanks for the response. I'll download the daily build and test. As for UDFs, I've listed a sample for each below of how we currently handle using EF 6.4.4. For Scalars (which fortunately we don't have many) we have to manually code but EF 6.4.4 designer generates our Table UDFs. Hope this helps and thanks again.

*****************************
SCALAR
*****************************
FUNCTION [Schema].[Get_Cust_Info]
(
@Attribute nvarchar(256),
@CustomerId int
)
RETURNS nvarchar(max)

// NOTE! - Custom Code
public string GetCustInfo(string attribute, int customerId)
{
    return Database.SqlQuery<string>("Select [Schema].[Get_Cust_Info](@p0,@p1)", attribute, customerId).FirstOrDefault();
}

*****************************
TABLE
*****************************
FUNCTION [Schema].[udf_Get_Authenticated_User_Authorization]
(
)
RETURNS @returntable TABLE
(
[SystemId] int
)

// NOTE! - Generated using EF 6.4.4 reverse engineer
[DbFunction("Entities", "udf_Get_Authenticated_User_Authorization")]
public virtual IQueryable<Nullable<int>> udf_Get_Authenticated_User_Authorization()
{
    return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Nullable<int>>("[Entities].[udf_Get_Authenticated_User_Authorization]()");
}
________________________________

**Comment by ErikEJ** [comment]
Scalar function mapping looks very simple: https://anthonygiretti.com/2018/01/11/entity-framework-core-2-scalar-function-mapping/

**Comment by DawgCoder** [comment]
Erik, I do not see the "Generated stored procedure mappings (preview)" context menu item and I installed today's (8/14/2020) daily build. Thoughts? 

EF Core Power Tools Version 2.4.159.0
VS 2019 Version 16.7.1
EF Core Version 3.1.7

**Comment by ErikEJ** [comment]
It's not a context menu item, it's a checkbox in the Options dialog.

**Comment by DawgCoder** [comment]
Ok, I think I may be blind or losing it. Where is the Options dialog?

**Comment by ErikEJ** [comment]
Last step of reverse engineering !!

**Comment by DawgCoder** [comment]
Ok, I see. It forces me to choose at least one table before I can get to the last step.

**Comment by ErikEJ** [comment]
Ok, so you are proposing a feature to scaffold an empty DbContext with just procedure mappings?

**Comment by DawgCoder** [comment]
That would be awesome and I wouldn't mind a pick list of all the sprocs/udfs to choose from. We have a very large database and lots of sprocs are there that other applications utilize that we don't. Hope this makes sense.

**Comment by ErikEJ** [comment]
It makes sense, could I ask you to create to issues for those two feature requests?

**Comment by DawgCoder** [comment]
Yes sir I can do that.

**Comment by ErikEJ** [comment]
SELECT SCHEMA_NAME(schema_id), name, m.object_id
FROM sys.sql_modules AS m
JOIN sys.objects AS o ON m.object_id = o.object_id
    AND type IN ('FN');
GO

SELECT * FROM sys.parameters
where object_id = 18099105

**Comment by ErikEJ** [comment]
@DawgCoder Would the above solution work for you?

**Comment by ErikEJ** [comment]
Closing in favor of #543

**Comment by ErikEJ** [comment]
@DawgCoder Ping?

**Comment by DawgCoder** [comment]
Yes sir, how can I help?
________________________________

**Comment by ErikEJ** [comment]
Look at my question above..

**Comment by DawgCoder** [comment]
Yes, that would work.
________________________________
