### ISSUE TITLE
Geography column not being added

### ISSUE THREAD

**Issue by georgeemr** [ErikEJ/EFCorePowerTools#438]
When I select a table that contains a Geography type it's no being imported.

### Steps to reproduce
• Create a table with geography.
![image](https://user-images.githubusercontent.com/3822009/89310255-aea4d100-d631-11ea-9a00-01c312433f0e.png)
• Import using reverse engineering.

### Further technical details
EF Core Power Tools version: 2.4.51

Database engine: SQL Server 2016

Visual Studio version: VS2019 16.6.5

**Comment by ErikEJ** [comment]
Did you update the efpt.config.json file as described here: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#sql-server-and-postgres-spatial-types ?

**Comment by georgeemr** [comment]
You are great. Thanks a lot!
