### ISSUE TITLE
Not able to install on latest Visual studio community version

### ISSUE THREAD

**Issue by akmansingani** [ErikEJ/EFCorePowerTools#441]
Describe what is not working as expected.
![Error - ef core](https://user-images.githubusercontent.com/41659182/89652605-57c62280-d8e3-11ea-8046-3ab240d92e12.png)

Not able to install on latest Visual studio community version

Can you please check and update.

**Comment by ErikEJ** [comment]
Pls share the log file!

**Comment by akmansingani** [comment]
Thanks for quick reply, please find attached log file.
[dd_VSIXInstaller_20200807212045_2414.log](https://github.com/ErikEJ/EFCorePowerTools/files/5042404/dd_VSIXInstaller_20200807212045_2414.log)

**Comment by ErikEJ** [comment]
No idea - try to repair your VS install - or try on another machine...
