### ISSUE TITLE
Add "Advanced Options" dialog to Options dialog

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#447]
@Herdo 😄 

Add button to buttons at bottom: "Advanced"

Show options:

Split DbContext into Configuration classes (preview)
Generate stored procedure mappings (preview)
Map spatial types
Map Noda Time types
Use EF6 pluralizer

(and remove first two options from main screen)

See https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#pluralization

**Comment by ErikEJ** [comment]
@ProH4Ck Interested?

**Comment by ProH4Ck** [comment]
Yes. I can do it... It's only a new dialog to group all the "extra" options located on the main screen.

**Comment by ErikEJ** [comment]
@ProH4Ck No, only remove two checkbox options from main screen, and add 3 additional options, that do not have any UI currently - see the issue description above.

**Comment by ProH4Ck** [comment]
Ok understood! I'll do it in next couple of days. I'll make a PR when ready.

**Comment by ErikEJ** [comment]
Fantastic, thanks so much!
