### ISSUE TITLE
Support for stored procedures that do not have a return value

### ISSUE THREAD

**Issue by intomneato** [ErikEJ/EFCorePowerTools#449]
My project is built in Visual Studio 2019 using .Net Core 3.1 and Azure Sql Server. EF Power Tools version 2.4.140.0. When I reverse engineer my database including stored procedures only stored procedures with a return value are included in the ContextProcedures.cs file. I have several procedures that manage bulk data operations but do not need to return a value. These procedures are missed in the ContextProcedures.cs file generation.  Original issue discovery process is in the comments from 8/10/2020 in issue #18

**Comment by ErikEJ** [comment]
See logic here: https://www.github.com/DarioN1/SPToCore/tree/master/SPToCore%2FT4%2FSPToCoreT4.tt

**Comment by ErikEJ** [comment]
@intomneato What would be the value of the generated code??

**Comment by intomneato** [comment]
I think it would benefit coding speed, consistency and readability. It's just cleaner and easier to write all database calls in the same format, especially since the proc calls are one-liners, and get intellisense help in Visual Studio. Then also easier on anyone reading the code later on for code reviews or enhancements. 

How I use procs these days... and why I don't need data back...
I currently do full stack work in a small shop (3 developers) and we reverse engineer our entire database then use Entity Framework for nearly all database interaction from our api layer, but there are some operations in our flagship app that are just too intensive for EF. For example, part of our app lives in the supply chain management world where a product price update may cascade through many layers of suppliers and customers with customized margin and discount adjustments, touching an exponentially larger data set at each level deeper. EF fails miserably at this kind of bulk operation so I wrote a proc (and indexes) that can adjust tens of thousands of customized price records in seconds, but I don't need any data back, my front end already knows what the user just told it to save, I just need the proc to run. My C# catch block catches exceptions if it fails to execute and returns an error message.  

I've also worked in bigger shops where some developers didn't have database access or just had read access and the dba's did all sql server work. In that kind of environment with the object from the reverse engineer there and ready code-side with params as properties to guide them they can just keep coding, otherwise they have to stop and research (ideally just looking in documentation but in my experience usually means walking around the cubes till you find a dba and hoping they're there and feeling helpful that day). 

My current approach to calling procedures looks like this:
SqlParameter[] spa = new[] {
    new SqlParameter("@Param1", value1),
    new SqlParameter("@Param2", value2),
    new SqlParameter("@Param3", value3),
    new SqlParameter("@Param4", value4),
    new SqlParameter("@Param5", value5)
};
_context.Database.ExecuteSqlRaw("EXEC abc.ProcName @Param1, @Param2, @Param3, @Param4, @Param5", spa);    

It'd be ideal if I had both of the following options available for calling procs (you've already accomplished the first): 
ProcNameResult result = _contextProcedures.ProcName(value1, value2, value3, value4, value5); 
_contextProcedures.ProcName(value1, value2, value3, value4, value5); 

I guess I could modify my non-returning procs to return something like @@TRAN_COUNT or ERROR_STATE() as a work around if this request is an enormous pain. I love the new update to EF PowerTools regardless, but I would regularly use this next suggested evolution of it.

**Comment by ErikEJ** [comment]
Fixed in latest daily build

**Comment by intomneato** [comment]
Almost there, one simple build error, it just needs to return void not Task...
![image](https://user-images.githubusercontent.com/50207204/90265527-51bacf00-de18-11ea-83e5-7b4eb497a776.png)

**Comment by intomneato** [comment]
Oh yeah, also, the function params might need to all be non-nullable. At least in my stumbling through it the ExecuteSqlRaw function always throws an error if any of my values are null. Maybe I've just been doing something wrong, but we shouldn't represent the function params as if they could be null if they really can't be.

**Comment by ErikEJ** [comment]
The schema inspection tells me they can be nulll. I need to respect that

**Comment by intomneato** [comment]
That's fair

**Comment by ErikEJ** [comment]
I should actually return Task<int> !!

**Comment by intomneato** [comment]
That works too :)

**Comment by intomneato** [comment]
something like this would work for me too...
![image](https://user-images.githubusercontent.com/50207204/90268355-80d33f80-de1c-11ea-8c9a-62802fa802bd.png)

**Comment by ErikEJ** [comment]
Don't like catching random errors like that. Will change to Task(int)

**Comment by intomneato** [comment]
However you want to handle it, I'm just happy the proc support is here. Thanks for your interaction on this!

**Comment by ErikEJ** [comment]
Should be fixed in latest daily.
