### ISSUE TITLE
identity specifications not reverse engineered correctly?

### ISSUE THREAD

**Issue by ingodan** [ErikEJ/EFCorePowerTools#45]
For some reason the properties always translate to 
public int? Id { get; set; }

Shouldn't they translate to
[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int? Id { get; set; }

**Comment by ErikEJ** [comment]
Please fill all the details on the issue form..

No - by convention, EF knows that SQL Server properties called Id autoincrement.

**Comment by Gambero81** [comment]
Hi @ErikEJ, i have the same problem:

this column definition

`UserId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID()`

generate:

```
[Key]
public Guid UserId { get; set; }
```

it would be glad to generate:

```
[Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
public Guid UserId { get; set; }
```

**Comment by ErikEJ** [comment]
Are you enabling data Annotations?

**Comment by ErikEJ** [comment]
And please create a new issue, it is not the same problem at all.

**Comment by Gambero81** [comment]
@ErikEJ yes i enabled dataannotation, i just open a new issue: https://github.com/ErikEJ/EFCorePowerTools/issues/913

Thanks
