### ISSUE TITLE
8/6 Update broke Reverse Engineer with Handlebars templates

### ISSUE THREAD

**Issue by drabb1956** [ErikEJ/EFCorePowerTools#450]
Since the 8/6/2020 update, I'm finding that reverse engineer is no longer working.  I'm getting a file not found error on .\CodeTemplates\CSharpDbContext\Partials\DbOnConfiguring.hbs.

Running against a SQL Server database.  VS 2019

**Comment by ErikEJ** [comment]
I think you may have to remove / move your codetemplates folder

**Comment by jli-lhm** [comment]
We're also experiencing the same error.

**Comment by ErikEJ** [comment]
@jli-lhm and did you remove/move the code templates folder?

**Comment by jli-lhm** [comment]
Thanks Erik, yep that did the trick. I only deleted all the contents in the folder but not the folder itself.

**Comment by ErikEJ** [comment]
I will add this to the release notes as a breaking change. Sorry for the inconvenience, remember to add back any customizations.

**Comment by ErikEJ** [comment]
Release notes updated

**Comment by MenaceSan** [comment]
just create a blank file named DbOnConfiguring.hbs in your CodeTemplates\CSharpDbContext\Partials folder and the error will go away. Its a new option that got added . but unfortunately they didnt make it optional.
