### ISSUE TITLE
Table list error - Could not open options file: 3 - EF Core Power Tools version: 2.4.140

### ISSUE THREAD

**Issue by TimKras** [ErikEJ/EFCorePowerTools#453]
I get the following error when running the reverse engineering option in the context menu (In the connection configuration step I was successful when clicking on the test connection option).
Database is hosted on Azure.
The connectionstring in the Server Explorer is:
Data Source=***;Initial Catalog=***;User ID=***;Password=***;Authentication="Active Directory Password"

Seems like the Authentication parameter is the problem since the quotes aren't escaped.

![image](https://user-images.githubusercontent.com/5257192/89880850-02309500-dbc5-11ea-9f5a-ee68c1297f23.png)

**Comment by ErikEJ** [comment]
Attempted a fix in the latest daily build, please let me know if that solves your issue

**Comment by ErikEJ** [comment]
Feel free to re-open if the fix did not work.

**Comment by TimKras** [comment]
I can confirm that this problem is solved in the latest daily build.
Thanks!

**Comment by ErikEJ** [comment]
@TimKras Thanks for the heads up and thanks for your assistance with troubleshooting and proposing a fix!
