### ISSUE TITLE
Method not found: IServiceCollection AddHandlebarsScaffolding

### ISSUE THREAD

**Issue by miguelhughes** [ErikEJ/EFCorePowerTools#46]
Hi! Great tool, I use it daily for updating my model from db changes. It's the best one I've used so far.
From some days ago, I'm unable to reverse engineer my db. I get the following exception when I try to do so:

```
System.MissingMethodException: Method not found: 'Microsoft.Extensions.DependencyInjection.IServiceCollection Microsoft.EntityFrameworkCore.Design.ServiceCollectionExtensions.AddHandlebarsScaffolding(Microsoft.Extensions.DependencyInjection.IServiceCollection, Microsoft.EntityFrameworkCore.Design.ReverseEngineerOptions, System.ValueTuple`2<System.String,System.Action`3<System.IO.TextWriter,System.Object,System.Object[]>>[])'.
   at ReverseEngineer20.EfCoreReverseEngineer.GenerateFiles(ReverseEngineerOptions reverseEngineerOptions)
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__2.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 153
```

from the looks of it, it is similar to issue #35 

### Steps to reproduce
I guess the error started happening when I uninstalled another related tool, but to be honest, I really don't know, so I'm asking for help. This my guess of the steps that would cause it again:

1. install https://github.com/ErikEJ/SqlCeToolbox
2. install https://github.com/ErikEJ/EFCorePowerTools
3. uninstall SqlCeToolbox
4. right click on project
5. select ef core power tools -> reverse engineer
6. click ok in the next 3 modals until the model generation is triggered
7. The exception is shown on the output window

First I used  sqlcetoolbox for a few months. then I had to stop using it due to project requirements, so I went to using the old scaffold-dbcontext. After some months I came across efcorepowertools which made us very happy for some months. and now I'm having this issue. I hope I can go back to using it soon!

### Further technical details
EF Core Power Tools version: 
Version 1.0.612.0

SQL Server Compact 4.0 in GAC - Yes - 4.0.8876.1
SQL Server Compact 4.0 DbProvider - Yes

SQL Server Compact 4.0 DDEX provider - No
SQL Server Compact 4.0 Simple DDEX provider - Yes

SQLite ADO.NET Provider included: 1.0.107.0
SQLite EF6 DbProvider in GAC - No

System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes

Database engine: SQL Server

Visual Studio version: Visual studio enterprise 2017 version 15.6.6

**Comment by ErikEJ** [comment]
Do you have Handlebars option selected?

**Comment by ErikEJ** [comment]
Have you tried build 613? Or the latest build on Marketplace? (Not daily)

**Comment by ErikEJ** [comment]
I have made som updates in the latest daily build - could you try that out?

**Comment by miguelhughes** [comment]
thanks for the quick responses!

> Do you have Handlebars option selected?
I didn't. now I tried with and without, same error.
> Have you tried build 613? Or the latest build on Marketplace?
I was up to date when I was having the issue (latest build). Then I switched to the daily build - same behaviour
> I have made som updates in the latest daily build - could you try that out?
thanks! trying now.

**Comment by miguelhughes** [comment]
Now I'm at version 1.0.614.0. I get the same error:

```
System.MissingMethodException: Method not found: 'Microsoft.Extensions.DependencyInjection.IServiceCollection Microsoft.EntityFrameworkCore.Design.ServiceCollectionExtensions.AddHandlebarsScaffolding(Microsoft.Extensions.DependencyInjection.IServiceCollection, Microsoft.EntityFrameworkCore.Design.ReverseEngineerOptions, System.ValueTuple`2<System.String,System.Action`3<System.IO.TextWriter,System.Object,System.Object[]>>[])'.
   at ReverseEngineer20.EfCoreReverseEngineer.GenerateFiles(ReverseEngineerOptions reverseEngineerOptions)
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__2.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 153
```

I find it strange that the callstack is the same, with exact line numbers, but the about dialog confirms that I'm updated to 614.

I also tried deleting all the dlls of the output from my project, doing clean& rebuild of the solution, and even downloading my repo to a new location and trying there. This was to rule out any local problems related to the solution.

Is it possible this is some sort of GAC/dll problem? Are there any dlls I should look for and try to remove?

**Comment by ErikEJ** [comment]
@bricelam Any ideas?

**Comment by miguelhughes** [comment]
I'm tempted to install sqlcetoolbox back, but I don't want to break things further

**Comment by ErikEJ** [comment]
I think I know what is happening:

For some reason, Visual Studio loads an older version of the EntityFrameworkCore.Scaffolding.Handlebars.dll, that does not have a recent overload, but has the same AssemblyVersion (a pre-release dll).

1: Locate any instances of the EntityFrameworkCore.Scaffolding.Handlebars.dll file, and remove any older versions (would like to know if you find any, and where you find them)

2: A longer term solution is to ask the library author to increase the assembly version due to the "breaking" change. @tonysneed ??

**Comment by tonysneed** [comment]
I see. I can rev the assembly version and released the rev’d package. I’ll post here when done.

**Comment by ErikEJ** [comment]
@tonysneed  Do you think my assumption sounds likely?

**Comment by tonysneed** [comment]
His call stack indicates that the Handlebars template source is included with the power tools source. Did you configure the power tools to use NuGet packages instead of source?

**Comment by ErikEJ** [comment]
Yes, not using source any longer

**Comment by tonysneed** [comment]
I can see that now .. I would like to know if he can find and remove any instances of the EntityFrameworkCore.Scaffolding.Handlebars.dll file.  Nevertheless, it wouldn't hurt to rev the assembly version.

**Comment by miguelhughes** [comment]
The only one I could find is in `AppData\Local\Microsoft\VisualStudio\15.0_d39a94c9\Extensions\dvazcsgy.aog` which seems to be this extension itself. I backed it up and removed it, the error I get is:

```System.IO.FileNotFoundException: Could not load file or assembly 'EntityFrameworkCore.Scaffolding.Handlebars, Version=1.0.0.0, Culture=neutral, PublicKeyToken=b10b51e7b9be6a2e' or one of its dependencies. The system cannot find the file specified.
File name: 'EntityFrameworkCore.Scaffolding.Handlebars, Version=1.0.0.0, Culture=neutral, PublicKeyToken=b10b51e7b9be6a2e'
   at ReverseEngineer20.EfCoreReverseEngineer.GenerateFiles(ReverseEngineerOptions reverseEngineerOptions)
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__2.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 153

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].```


I tried searching in the GAC, for what it's worth...
```C:\>gacutil -l EntityFrameworkCore.Scaffolding.Handlebars
Microsoft (R) .NET Global Assembly Cache Utility.  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

The Global Assembly Cache contains the following assemblies:

Number of items = 0```

now searching in c:
```C:\>dir EntityFrameworkCore.Scaffolding.Handlebars.dll /s /p
 Volume in drive C has no label.
 Volume Serial Number is 4C18-6074
File Not Found```

Some additional info, in case it matters:
I'm using EntityframeworkCore 1.1.5 in my solution.
I did have at one time have the nuget source "ASP.NET Core "dev" branch feed" (https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json) but I can't recall at the moment what it was for. Nevertheless it was disabled before I installed EFCorePowerTools.

**Comment by ErikEJ** [comment]
Your project is not related to this issue, it is a VS / EF Core Power Tools issue only.

I have no idea what is going on, TBH. Try removing the extension folder, restart VS and install EF Core Power Tools.

**Comment by miguelhughes** [comment]
Now we're back to :

```
System.MissingMethodException: Method not found: 'Microsoft.Extensions.DependencyInjection.IServiceCollection Microsoft.EntityFrameworkCore.Design.ServiceCollectionExtensions.AddHandlebarsScaffolding(Microsoft.Extensions.DependencyInjection.IServiceCollection, Microsoft.EntityFrameworkCore.Design.ReverseEngineerOptions, System.ValueTuple`2<System.String,System.Action`3<System.IO.TextWriter,System.Object,System.Object[]>>[])'.
   at ReverseEngineer20.EfCoreReverseEngineer.GenerateFiles(ReverseEngineerOptions reverseEngineerOptions)
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__2.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 154
```

Any other ideas? something else I should try?

**Comment by ErikEJ** [comment]
Try the latest daily build, a file was missing in build 616

**Comment by miguelhughes** [comment]
Thanks for your patience. 
I just tried the latest, regrettably the error is still the same:

```
System.MissingMethodException: Method not found: 'Microsoft.Extensions.DependencyInjection.IServiceCollection Microsoft.EntityFrameworkCore.Design.ServiceCollectionExtensions.AddHandlebarsScaffolding(Microsoft.Extensions.DependencyInjection.IServiceCollection, Microsoft.EntityFrameworkCore.Design.ReverseEngineerOptions, System.ValueTuple`2<System.String,System.Action`3<System.IO.TextWriter,System.Object,System.Object[]>>[])'.
   at ReverseEngineer20.EfCoreReverseEngineer.GenerateFiles(ReverseEngineerOptions reverseEngineerOptions)
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__2.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 153
```
current version is 617.

I see the new file in the latest one - handlebars.dll, right?

**Comment by ErikEJ** [comment]
Yes, that was the missing file

Could you update Visual Studio to 15.7.3 or later?

**Comment by miguelhughes** [comment]
Updated to 15.7.3, got same error
Uninstalled the extension, installed again 617; same error

What I don't understand is why my environment got so broken

**Comment by ErikEJ** [comment]
I have no idea - fusion log viewer, procmon etc are next steps

**Comment by rsnider19** [comment]
I am seeing the same issue, and I have tried all of the suggestions. My Visual Studio is set to auto-update extensions, and it was working on Friday. So it seems that something between the previous version and 604 changed.

**Comment by tonysneed** [comment]
I’ll see if I can reproduce with the latest daily build.

**Comment by ErikEJ** [comment]
I have not been able to repro anything similar so far...

**Comment by rsnider19** [comment]
I believe it is happening in `EFCoreReverseEngineer`:
```
if (reverseEngineerOptions.UseHandleBars)
{
    //TODO Consider being selective based on SelectedToBeGenerated
    serviceCollection.AddHandlebarsScaffolding();
    serviceCollection.AddSingleton<ITemplateFileService>(provider => new CustomTemplateFileService(reverseEngineerOptions.ProjectPath));
}
```

I am unable to run EFPT locally, but could it be that `reverseEngineerOptions.UseHandleBars` isn't coming correctly from the modal (and is always true), which triggers this code?

Also, I uninstalled/reinstalled Visual Studio and it is still not working for me.

**Comment by tonysneed** [comment]
I downloaded the daily build today (v 1.0.617) and installed it in Visual Studio Community 2017 (v 15.7.4). I used the [DuplicateExtensionFinder](https://github.com/remcoros/DuplicateExtensionFinder) to validate the install and observe that Handlebars.dll was located in the extension directory.  Then I use the EF Core Power Tools to reverse engineer an existing database.  The process completed without error.

However, when I attempted to add a DbContext model diagram, I received the following error:
```
System.ArgumentException: No EF Core DbContext types found in the project
   at ReverseEngineer20.EfCoreModelBuilder.GetDbContextTypes(DbContextOperations operations) in C:\Code\EFCorePowerTools\src\GUI\efpt\EFCoreModelBuilder.cs:line 76
   at ReverseEngineer20.EfCoreModelBuilder.BuildResult(String outputPath, Boolean generateDdl) in C:\Code\EFCorePowerTools\src\GUI\efpt\EFCoreModelBuilder.cs:line 34
   at ReverseEngineer20.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efpt\Program.cs:line 44

Parameter name: processResult
   at EFCorePowerTools.Handlers.ModelAnalyzerHandler.Generate(String outputPath, Project project, GenerationType generationType) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ModelAnalyzerHandler.cs:line 49
```

The same error occurred when executing any of the other DbContext related commands in EF Core Power Tools, even though a DbContext does indeed exist in the project.

**Comment by tonysneed** [comment]
I synced the package and assembly versions with release v1.1.1: https://www.nuget.org/packages/EntityFrameworkCore.Scaffolding.Handlebars/1.1.1

@ErikEJ If you use this version we should be able to validate the correct version.

**Comment by tylersherbeyn** [comment]
I'm also having this same error message. Tried with the recent daily build. Still having the same error. 

Question though, the error message seems to be referencing a directory that doesn't exist on my computer. Is that normal? 

C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:

**Comment by ErikEJ** [comment]
How recent a build? Yes, that is normal...

**Comment by tylersherbeyn** [comment]
The latest daily build.

**Comment by ErikEJ** [comment]
Sadly, I am unable to repro - so no clue what to do in order to release support for 2.1 other than remove handlebars support or get close to a machine/VM that exhibits this issue

**Comment by ErikEJ** [comment]
@rsnider19 @miguelhughes  any status updates?

**Comment by miguelhughes** [comment]
In a desperate attempt I installed SqlCeToolbox, still same error
I installed the daily build, with sqlcetoolbox in place - same error.
Uninstalled both, installed daily build - same error. 

I am working on a Parallels VM. would it help If I tried to upload a snapshot of it somewhere for you to take a look?

I guess my best shot is to uninstall & install visual studio again and apply the daily build?

**Comment by ErikEJ** [comment]
@miguelhughes  

>> I guess my best shot is to uninstall & install visual studio again and apply the daily build?

That should not be required. Have you checked for duplicate extensions ? https://github.com/remcoros/DuplicateExtensionFinder

>> I am working on a Parallels VM. would it help If I tried to upload a snapshot of it somewhere for you to take a look?

A VM sounds great - can I run a parallels VM on Windows?

**Comment by miguelhughes** [comment]
I just need to get this working again. Any suggestions?

I tried duplicate extension finder. there are a couple there (appinsights, azure) but none related to your tools. should I fix those errors anyway?

> A VM sounds great - can I run a parallels VM on Windows?
It doesn't look like there's an easy one for that, i've googled it a bit. But If you're willing to give it a shot I can upload it somewhere for you.

Perhaps some of the other users having this are an easier option...

**Comment by ErikEJ** [comment]
>> I just need to get this working again. Any suggestions?

Let me try to completly remove/disable handlebars from a daily build - will let you know when I have done so

**Comment by tonysneed** [comment]
In case you guys want to use an VM in Azure with VS 2017 community: https://docs.microsoft.com/en-us/azure/virtual-machines/windows/using-visual-studio-vm.

**Comment by tonysneed** [comment]
However, this sounds like it's specific to the setup for @miguelhughes.  Here is what I would suggest to troubleshoot:
- Use [DuplicateExtensionFinder](https://github.com/remcoros/DuplicateExtensionFinder) to locate the installation directory where the latest daily build was installed on your machine.
- Locate the EntityFrameworkCore.Scaffolding.Handlebars.dll file in that folder and use [Ildasm.exe](https://docs.microsoft.com/en-us/dotnet/framework/tools/ildasm-exe-il-disassembler) or [JetBrains dotPeek](https://www.jetbrains.com/decompiler/) to open the file.
- Verify that the assembly version of the file is 1.1.1

That should help us diagnose the issue with regard to the missing method exception.

**Comment by rsnider19** [comment]
Still not working for me. DuplicateFileFinder is clean, and here is my dotPeek:
![image](https://user-images.githubusercontent.com/13546759/41730182-2ac9a540-7549-11e8-8c26-5767a9c0d3a5.png)

**Comment by ErikEJ** [comment]
I am clueless atm, will try a daily build with no Handlebars support soon

**Comment by tonysneed** [comment]
@ErikEJ Is anything installed to the GAC?

**Comment by ErikEJ** [comment]
Packages.config = assembly references, and nothing in GAC

**Comment by tonysneed** [comment]
I'm wondering if somehow there are multiple installations of the extension (although DuplicateExtensionFinder would flag those).  @miguelhughes Can you check the version of ECF PT that is in the installation folder you're inspecting, versus the version that is in the about box in VS?

**Comment by kachalkov** [comment]
We have the same issue, what we don't understand is how issue is still happening if we not select to use handlebar templates?

We have it working fine on laptop, but fails on virtual machine and it looks like related to handler service for custom one...

**Comment by ErikEJ** [comment]
I have attached a preview build with Handlebars disabled here, for you all to try out.

[EFCorePowerTools.1.0.623.vsix.zip](https://github.com/ErikEJ/EFCorePowerTools/files/2126937/EFCorePowerTools.1.0.623.vsix.zip)

**Comment by tonysneed** [comment]
Since a lot of folks are having this issue, perhaps I can remove the overload of the extension method and instead create a separate extension method for adding Handlebars helpers.

**Comment by ErikEJ** [comment]
I have been thinking the same, maybe you could bring back a plain extension method..

**Comment by tonysneed** [comment]
I’ll get that done today and publish a new version.

**Comment by rsnider19** [comment]
Success!!! 623 work for me now!!

**Comment by ErikEJ** [comment]
@rsnider Yes, but it has no handlebars :-( 

@tonysneed Great!

**Comment by miguelhughes** [comment]
Sorry for my late responses
@tonysneed 
Duplicate extension finder shows no duplicates related to the extension, but there are about a dozen. I'm not sure if its worth posting them here.

ildasm: 
```
.assembly EntityFrameworkCore.Scaffolding.Handlebars
{
  .ver 1:1:1:0
}
```
```
.assembly Handlebars
{
  .ver 1:9:4:0
}
```

> Can you check the version of ECF PT that is in the installation folder you're inspecting, versus the version that is in the about box in VS? 
ildasm:
```
.assembly EFCorePowerTools
{
  .ver 1:0:622:0
}
```

about info:
Version 1.0.622.0

**Comment by miguelhughes** [comment]
@ErikEJ the pre-release  623 worked!!
success!! thanks for your effort and patience guys - It's really appreciated

**Comment by tonysneed** [comment]
> Duplicate extension finder shows no duplicates related to the extension, but there are about a dozen.

That may help explain the behavior. Where are they located?

However, I plan to refactor the extension method to avoid this issue.

**Comment by miguelhughes** [comment]
attaching the complete output of duplicate extension finder with the -dupes flag

[dupes.txt](https://github.com/ErikEJ/EFCorePowerTools/files/2128020/dupes.txt)

**Comment by tonysneed** [comment]
@miguelhughes Oh I get it, there are a dozen dups of other extensions, but not EFC PT.

**Comment by ErikEJ** [comment]
I am not able to use 1.5, as it depends on 2.1.1, and all my dependencies are not ready for 2.1.1 yet

**Comment by tonysneed** [comment]
Oops. 😬  I’ll change to NET Core 2.1.0 then! Look for v1.4.0.

**Comment by tonysneed** [comment]
@ErikEJ Done: https://www.nuget.org/packages/EntityFrameworkCore.Scaffolding.Handlebars/1.4.0.

**Comment by ErikEJ** [comment]
Latest daily build updated with EFCore.HandleBars 1.4 @miguelhughes @rsnider19

**Comment by miguelhughes** [comment]
Daily build 629. Model generated successfully!

**Comment by ErikEJ** [comment]
Great news, Miguel, getting closer to a release now!!
