### ISSUE TITLE
PropertyBuilder<int> does not contain a definition for HasComment'

### ISSUE THREAD

**Issue by Ottokan** [ErikEJ/EFCorePowerTools#464]
With the latest version of EFCorePowerTools when i'm using reverse engineer i had the following error 

Error	CS1061	'PropertyBuilder<int>' does not contain a definition for 'HasComment' and no accessible extension method 'HasComment' accepting a first argument of type 'PropertyBuilder<int>' could be found (are you missing a using directive or an assembly reference?)

asp core 2.2
VS2019 and VS2017

**Comment by ErikEJ** [comment]
It is because you are using .NET Core 2.2, which is no longer supported!

You can manually remove the offending code, or download and install an old version of the extension - see the release notes in the wiki.
