### ISSUE TITLE
Reverse engineer with two databases

### ISSUE THREAD

**Issue by karenpayneoregon** [ErikEJ/EFCorePowerTools#466]
Describe what is not working as expected.

- Performed a reverse engineer on one database, worked (Item 1 in green).
- In the same project reverse engineered another database (item 2 in yellow)
- First item classes are gone while the first are still present

![1111](https://user-images.githubusercontent.com/17032797/90254755-1ad4c100-ddf8-11ea-9fc5-7c81bbac67a9.png)

### Steps to reproduce
Performed two reverse engineering back to back in a class project using .NET Framework 4.7.2

### Further technical details
EF Core Power Tools version: 
Version 2.4.157.0

SQLite ADO.NET Provider included: 1.0.99.0
SQLite EF6 DbProvider in GAC - No

System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes

Database engine: SQL Server

Visual Studio version 15.9.8

**Comment by ErikEJ** [comment]
This is not supported, unless you put files in separate folders.

**Comment by karenpayneoregon** [comment]
So to be clear the following is not supported
- Create folder for DbContexts, reverse engineer two databases with two different class names for the dbContext
- Same for models.

If that is the case no problem, just need verification.

Thanks Erik

**Comment by ErikEJ** [comment]
Correct, mixing multiple models or dbcontexts in the same folder is not supported.

**Comment by ErikEJ** [comment]
Also, having 2 dbcontexts in the same project is possible, but not recommended. 

You will not make much use of the saved settings, and it also seems like an anti-pattern.

**Comment by karenpayneoregon** [comment]
I completely understand, this was done only to see if the reverse engineering was working, could had done a partial reverse process on one database then continue with the remaining models. In short would have not done this for a production application.

**Comment by ErikEJ** [comment]
Ok! I will close this, then

**Comment by ErikEJ** [comment]
@karenpayneoregon  

The latest daily build allows you to use multiple efpt.config.json files in the same project - https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#saving-options-and-running-the-second-time
