### ISSUE TITLE
[Feature] Scaffold an empty DbContext with just procedure mappings

### ISSUE THREAD

**Issue by DawgCoder** [ErikEJ/EFCorePowerTools#467]
Hello I would like to suggest the following feature request. Add a context menu to the EF Core Power Tools to scaffold an empty DbContext with stored procedure and udf mappings.

EF Power Tools Version 2.4.159.0
Visual Studio 2019 Version 16.7.1
Microsoft SQL Server 2016

**Comment by ErikEJ** [comment]
I basically just need to allow you to proceed without choosing any tables..

**Comment by ErikEJ** [comment]
Bummer - the scaffolding API does not support this.

**Comment by DawgCoder** [comment]
We aren't planning to release the new version of our application until .NET 5.0 is released and we will probably wait until 5.3 so there's not a huge rush at the moment. I appreciate you having a look into this.

**Comment by ErikEJ** [comment]
Yes, I have some ideas on how to hack it.

**Comment by ErikEJ** [comment]
I have done some investigation, and there is no way of doing this without breaking stuff.
