### ISSUE TITLE
[Feature] Add ability to choose stored procedures from a pick list

### ISSUE THREAD

**Issue by DawgCoder** [ErikEJ/EFCorePowerTools#468]
Stage 1:

- [x] Enable selection of stored procedures in Table Picker
- [x] Verify that selection is properly persisted
- [x] Treat selected tables correctly when calling runner (split tables and procedures)

Stage 2:

- [x] Respect selection of procedures when scaffolding them
- [ ] Remove advanced option to scaffold stored procedures

I would like the ability to have a pick list of the stored procedures and udfs that I could choose to generate code for.

**Comment by tscilipoti** [comment]
would love to see this too

**Comment by ErikEJ** [comment]
@tscilipoti Why is this important?

**Comment by tscilipoti** [comment]
> @tscilipoti Why is this important?

My database has dozens and dozens of stored procs. In my current project I only need to write code against a small handful of them. The way the tools are written now, it generates classes and data access code for ALL the sprocs every time I run the reverse engineer routine. So I have to go in behind the tool and delete all those unneeded classes and all that unneeded code. 

Moreover, in the next iteration I will want to pull in 4 more of the sprocs (not 104). It would be nice to be able to run the tool again and point it at only those four.

**Comment by ErikEJ** [comment]
Thanks, makes sense...

**Comment by ErikEJ** [comment]
Why is it important to delete the autogenerated code ?

**Comment by tscilipoti** [comment]
> Why is it important to delete the autogenerated code ?

We follow a best practice of not having a bunch of unexercised, unused, untested code in our codebase.

**Comment by ErikEJ** [comment]
Thanks, I will prioritize this feature.

**Comment by ErikEJ** [comment]
Implemented in latest daily build
