### ISSUE TITLE
VS Code Extension

### ISSUE THREAD

**Issue by blogcraft** [ErikEJ/EFCorePowerTools#469]
My team uses VS Code for development. It would be nice to have EF Power Tools as a VS Code extension so I don't have to get Visual Studio installed just to be able to use Power Tools. 

I know I could use directly the reverse engineer directly from EF but I love how Power Tools keeps everything configured and organized en it's own json and I don't want that to change. 😊

**Comment by ErikEJ** [comment]
This is not something I am planning to do, unless I get help. But I do plan to publish a .NET Core command line tool.

**Comment by ErikEJ** [comment]
see #340

**Comment by ErikEJ** [comment]
For anyone watching this issue, this is now planned, and you can find a design proposal [here](https://github.com/ErikEJ/EFCorePowerTools/issues/1751) - looking forward to any comments/suggestions.

**Comment by ErikEJ** [comment]
Preview 1 of the CLI tool is [now available](https://www.nuget.org/packages/ErikEJ.EFCorePowerTools.Cli/7.0.0-preview1#readme-body-tab)

![image](https://user-images.githubusercontent.com/4169187/234258058-2b6def58-f87c-455a-93da-21cd09d9e3f7.png)
