### ISSUE TITLE
Update available notification not cleared after updating

### ISSUE THREAD

**Issue by psijkof** [ErikEJ/EFCorePowerTools#47]
Describe what is not working as expected.

I keep seeing this notification in vs 2017 ce, 15.7.3

![image](https://user-images.githubusercontent.com/25638593/41321572-707ef4a4-6e9c-11e8-92cb-26e8bcdeec11.png)

Is this because I subscribed to daily/nightly builds? (vsx gallery). But anyway, immediately after updating, it appears again (while other update notifications have disappeared).

UPDATE:
This happens on 3 pcs. On Insider and Regular builds of Windows. In Preview and Regular version of VS.
Am I the only one seeing this?

**Comment by ErikEJ** [comment]
Remove the daily builds feed and see what happens - anyway, it is not something I ca fix in any way

**Comment by psijkof** [comment]
The thing is, if you close an item, I don't get an update... I see it only now, to discover what happened with my issues. 

Anyway, I will try and see if that sorts the problem.
