### ISSUE TITLE
scaffolded Stored procedure transaction issue

### ISSUE THREAD

**Issue by lkmcelik** [ErikEJ/EFCorePowerTools#470]
the issue is when i working transaction as context.database.begintransaction() and if i call procedure in this transaction it is throw s exception, i fixed the issue with changing generated dbcontextextension class like this, i hope it works for you

    `public static class DbContextExtensions
    {
        public static async Task<T[]> SqlQuery<T>(this DbContext db, string sql, params object[] parameters) where T : class
        {
            DbConnection conn = db.Database.GetDbConnection();
            using (var db2 = new ContextForQueryType<T>(conn, db.Database.CurrentTransaction))
            {
                return await db2.Set<T>().FromSqlRaw(sql, parameters).ToArrayAsync();
            }
        }
        public static DbTransaction GetDbTransaction(this IDbContextTransaction source)
        {
            return (source as IInfrastructure<DbTransaction>).Instance;
        }
        private class ContextForQueryType<T> : DbContext where T : class
        {
            private readonly DbConnection connection; 
            public ContextForQueryType(DbConnection connection, IDbContextTransaction tran)
            {
                this.connection = connection; 
                this.Database.UseTransaction(GetDbTransaction(tran));
            } 
            protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            {
                optionsBuilder.UseSqlServer(connection);
            } 
            protected override void OnModelCreating(ModelBuilder modelBuilder)
            {
                modelBuilder.Entity<T>().HasNoKey().ToView(null);
            }
        }
    }`

**Comment by ErikEJ** [comment]
Thanks, could you show me how you use this?

**Comment by lkmcelik** [comment]
sure, this is one of the save command that i use   

    `using (var tran = context.Database.BeginTransaction())
            {
                try
                { 
                        try
                        {
                            if (txtFirmaKodu.Text == string.Empty)
                                txtFirmaKodu.Text = await cariService.GenearetCode();//**procedure**
                            cariService.Add(SeciliObj);
                            context.SaveChanges();
                            SeciliObjOdemeYontemi.CariID = SeciliObj.ID;
                            cariOdemeYontemiService.Add(SeciliObjOdemeYontemi);

                            var pList = (IEnumerable<CariPazarlamaBilgileri>)gvPazarlamaBilgileri.DataSource;
                            cariPazarlamaService.Remove(pazarlamaBilgileriRemoveinen);
                            pList.ToList().ForEach(x => x.CariID = SeciliObj.ID);
                            cariPazarlamaService.Add(pList.Where(x => x.ID == 0).ToList());

                            var bList = (IEnumerable<CariBankaHesaplari>)gvBankaBilgileri.DataSource;
                            bList.ToList().ForEach(x => x.CariID = SeciliObj.ID);
                            cariBankaService.Add(bList.Where(x => x.ID == 0).ToList());

                            var cList = (IEnumerable<CariFirmaCalisanlari>)gvCariCalisanlari.DataSource;
                            cList.ToList().ForEach(x => x.CariID = SeciliObj.ID);
                            cariFirmaCalisanlariService.Add(cList.Where(x => x.ID == 0).ToList()); 
                            ...
`

**Comment by ErikEJ** [comment]
Where do you call the new public GetDbTransaction method?

**Comment by lkmcelik** [comment]
in DbContextExtensions class
`public ContextForQueryType(DbConnection connection, IDbContextTransaction tran)
        {
            this.connection = connection; 
            this.Database.UseTransaction(GetDbTransaction(tran));//here
        } `

**Comment by ErikEJ** [comment]
Thanks, so no need for it to be public, then?

**Comment by ErikEJ** [comment]
Fixed in latest daily build, please try it out and let me know if it works for you - and thanks for the contribution!

**Comment by lkmcelik** [comment]
you are welcome. Thank you for this plugin, it's very good.
