### ISSUE TITLE
Multiline comments not working

### ISSUE THREAD

**Issue by CShark** [ErikEJ/EFCorePowerTools#479]
Multiline comments on an sql column are not properly prefixed with '///' when reverse engineering. Only the first comment line is prefixed, while the rest is not.

### Steps to reproduce
Reverse Enginer a Table where the column in question has an extended property of type "MS_Description" containing an entry with multiple newlines. The Result will look something like

    ///<summary>
    /// First comment line
    Second comment line
    3. line
    ///</summary>

### Further technical details
EF Core Power Tools version: 2.4.157.0

Database engine: SQL Server 2016

Visual Studio version: VS 2019 16.7.2

**Comment by ErikEJ** [comment]
Have you tried the latest daily build?

**Comment by CShark** [comment]
Nope did not, but its fixed in the daily build.
