### ISSUE TITLE
Making EF Core even more easy for beginners

### ISSUE THREAD

**Issue by psijkof** [ErikEJ/EFCorePowerTools#48]
Considering the code-first approach.
Starting with defining entities in a 'Model' project, using DataAnnotations.
In your 'Data' project, it would be nice to have the option via the power tools,
to 'Create DbContext'.
This would create the DbContext class, and generate DbSet<T> for each class in the appointed 'Model' namespace.

I know, it's not that hard to create a DbContext yourself, while you model your entities, but, a little help can be useful :)

What are your thoughts on this?

**Comment by ErikEJ** [comment]
Given that there are many approaches to this, I think it will be hard to create a general purpose tool.
Have you seen how it is done in the EF6 wizard?

**Comment by psijkof** [comment]
No. Just ASP.NET Core and EF Core since last year. 
Used the Revere Engineer feature, and had very good experiences with it. (Existing DB to Model/Data classes(. That scenario is like from start to finish to have your app data store enabled.

So, on the topic of Code First, I think the process is more gradual and evolving, and coding being the way, creating a DbContext derived class shouldn't be a big deal...

**Comment by ErikEJ** [comment]
Closing for now
