### ISSUE TITLE
Double quotes from query filter not escaped in dgml

### ISSUE THREAD

**Issue by oliveira-marcello** [ErikEJ/EFCorePowerTools#482]
When I tried to open a generated model diagram, I got this error: 

> 'DateDeleted' is an unexpected token. Expecting white space.

This was caused by a query filter not being escaped in the xml:

`
<Node ... Annotations="ConstructorBinding: Microsoft.EntityFrameworkCore.Metadata.ConstructorBinding
QueryFilter: Param_0 => (Property(Param_0, "DateDeleted") == null)
Relational:TableName: BoxRegistrations" ...>
`

When I replaced `Param_0, "DateDeleted"` by `Param_0, &quot;DateDeleted&quot;`, the diagram opened correctly.

### Steps to reproduce

`modelBuilder.Entity<Product>().HasQueryFilter(p => EF.Property<DateTime?>(p, "DateDeleted") == null);`

### Further technical details
EF Core Power Tools version: 2.4.157.0

Database engine: Postgres

Visual Studio version: Visual Studio Community 2019 16.7.2

**Comment by ErikEJ** [comment]
Please share more of your broken XML file, thanks.

**Comment by ErikEJ** [comment]
I have attempted a fix in the latest daily build.

**Comment by oliveira-marcello** [comment]
Thanks @ErikEJ! It's fixed in the latest build. 

Here is the broken xml (generated before the fix) with more details:
[dgml.zip](https://github.com/ErikEJ/EFCorePowerTools/files/5130317/dgml.zip)
