### ISSUE TITLE
Consider adding AsNoTracking() to StoredProcedures call

### ISSUE THREAD

**Issue by micdenny** [ErikEJ/EFCorePowerTools#483]
https://github.com/ErikEJ/EFCorePowerTools/blob/26f1cbc99c457f82b38ce1f91d6e201e98562f7e/src/GUI/RevEng.Core/DbContextExtensions#L14

consider to add an `AsNoTracking()` before the `ToArrayAsync()` as the [ef core docs states that](https://docs.microsoft.com/en-us/ef/core/querying/raw-sql#change-tracking):

>Queries that use the FromSqlRaw or FromSqlInterpolated methods follow the exact same change tracking rules as any other LINQ query in EF Core.

This can improve query with a lot of data, avoid to consume too much memory and cpu to manage the tracking of all the records.

**Comment by ErikEJ** [comment]
It is not required: https://docs.microsoft.com/en-us/ef/core/querying/tracking

**Comment by micdenny** [comment]
ok it's clarified by this note:

> Keyless entity types are never tracked. Wherever this article mentions entity types, it refers to entity types which have a key defined.

thank you

**Comment by mkgn** [comment]
Based on @ErikEJ  comment it's not needed as long as [KeyLess] is specified which can be used mainly to return data. However, the current classes generated to return data when calling stored procedures doesn't use [KeyLess] attribute. So this optimization will still be needed I suppose? In my case I had to use this tool to query an old database having lot of stored procedures. DbContextExtentions.SqlQueryAsync<>() can be a place where we want to use AsNoTracking(). What is your opinion on this?

**Comment by ErikEJ** [comment]
@mkgn Not needed.
