### ISSUE TITLE
Comment problem on column description with new line

### ISSUE THREAD

**Issue by kennfarbe** [ErikEJ/EFCorePowerTools#487]
We used new lines in the column descriptions in the SQL server. Unfortunately, these are not interpreted correctly by EF Power Tools.

### Steps to reproduce
Example column description:
```
Hello
world
```

Output:
```
         /// <summary>
         /// Hello
world
         /// </summary>
```

### Further technical details
EF Core Power Tools version: 2.4.157.0

Database engine: MS SQL 2017 14.0.3192.2

Visual Studio version: Visual Studio 2019 16.7.2

**Comment by ErikEJ** [comment]
Have you tried the latest daily build.

**Comment by kennfarbe** [comment]
Many thanks. With the version 2.4.180.0 works it!

**Comment by ErikEJ** [comment]
You are welcome, will update the official release version soon.
