### ISSUE TITLE
Enumerate references to *.dacpac files in solution (or browse any .dacpac file)

### ISSUE THREAD

**Issue by lesowin370** [ErikEJ/EFCorePowerTools#489]
I have a nuget package that contains *.dacpac file. It's added to the solution as a link, so the file remains in nuget cache folder physically.
![image](https://user-images.githubusercontent.com/69253471/91999652-4c7ce000-ed45-11ea-8d9a-d469923c853a.png)

Is it possible to enumerate all such referenced files and show them in this window?
![image](https://user-images.githubusercontent.com/69253471/91999195-ca8cb700-ed44-11ea-9191-a86934cd4154.png)

### Steps to reproduce
1. Add an existing item to solution as a reference to *.dacpac file
2. Launch EF Core Power Tools

### Further technical details
EF Core Power Tools version: 2.4.157

Database engine: SQL Server

Visual Studio version: Visual Studio 2019 16.7.1

**Comment by ErikEJ** [comment]
If the file is included as Content, and you have "Copy Always", then it should be discoverable.

Suggest you share your .csproj file.

**Comment by lesowin370** [comment]
It becomes available right after the build, which may be quite not convenient because you have to remember to build the project first.
Also it pollutes output folder and I have to clean it manually if I don't want to expose database structure to the user.
csproj file contains nothing except for reference to Test.Database package. Physically the file is in C:\Users\<username>\.nuget\packages\test.database\1.0.0\contentFiles\any\any\Database\Test.Database.dacpac

[ConsoleApp12.zip](https://github.com/ErikEJ/EFCorePowerTools/files/5168535/ConsoleApp12.zip)

**Comment by ErikEJ** [comment]
Unsure, but I need a PR or a full repro in order to assist (including a sample NuGet package)

**Comment by lesowin370** [comment]
1. Unpack *.nupkg file in any folder and specify the folder in Tools -> Options -> NuGet Package Manager -> Package Sources of Visual Studio
2. Open the Application/Application.sln in Visual Studio 2019
3. Run EF Core Power Tools and try to find TestDb.dacpac

AR: although the solution shows it's linked from the unpacked Nuget package, EF Core Power Tools doesn't show anything in dropdown

[Project.zip](https://github.com/ErikEJ/EFCorePowerTools/files/5169208/Project.zip)

**Comment by ErikEJ** [comment]
You can do this:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TestDb" Version="1.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="C:\Users\user\.nuget\packages\testdb\1.0.0\contentFiles\any\any\Database\TestDb.dacpac">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="if $(ConfigurationName) == Release del $(TargetDir)Database\TestDb.dacpac" />
  </Target>

</Project>

```

**Comment by ErikEJ** [comment]
Alternatively, I could allow you to browse for any .dacpac file on your disk.

**Comment by ErikEJ** [comment]
The latest daily build allows you to pick any .dacpac file from anywhere
