### ISSUE TITLE
 Cannot add datasource with PostgreSQL

### ISSUE THREAD

**Issue by BlueSky16st** [ErikEJ/EFCorePowerTools#491]
### Steps to reproduce

ODBC driver psqlodbc_09_02_0100.zip installed

'Reverse Engineer' - In 'Choose Database Connection' window - 'Add' - 'Change' - Select 'Microsoft ODBC Data Source'

Enter connection string:
Driver={PostgreSQL UNICODE};server=39.xx.xx.xx;port=5432;database=xxx;uid=xxx;pwd=xxxx

and 'Test Connection', it work
and then click 'OK'
But.. nothing change.. it still empty list

### Further technical details
here are my screenshot -v
![step1](https://user-images.githubusercontent.com/22427590/92194052-52d1a000-ee9c-11ea-9be1-b7da5c4a7bf8.png)
![step2](https://user-images.githubusercontent.com/22427590/92194058-5533fa00-ee9c-11ea-86a2-ce8ddc9a807e.png)
![step3](https://user-images.githubusercontent.com/22427590/92194206-b5c33700-ee9c-11ea-8952-9d556fb006a1.png)

in ODBC Data Sources (32-bit) window
![step4](https://user-images.githubusercontent.com/22427590/92194212-b6f46400-ee9c-11ea-8824-ab5b22271547.png)

in Server Explorer window
![step5](https://user-images.githubusercontent.com/22427590/92194494-63cee100-ee9d-11ea-8a42-4e01e63088b5.png)

EF Core Power Tools version: 2.4.157
Database engine: PostgreSQL 9.2.24 on x86_64-redhat-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39), 64-bit
Visual Studio version: Visual Studio 2019 16.7.2

**Comment by ErikEJ** [comment]
You must install the Postgres Visual Studio Tools, as stated in the [docs](https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#reverse-engineer---workflow)
