### ISSUE TITLE
Enhance sprc scaffolding to prepend schema names to methods and result classes if there are duplicates

### ISSUE THREAD

**Issue by EvgenyBelokurov** [ErikEJ/EFCorePowerTools#497]
In the EF repository(https://github.com/dotnet/efcore), the question was raised about the presence in the database of two tables with the same names but in different schemas.

dotnet/efcore#3988
dotnet/efcore#12432
https://github.com/ErikEJ/EFCorePowerTools/issues/488

The problem was solved by creating efpt.renaming.json.

I have a question about the existence of two stored procedures in a database with the same name, but in different schemas. Is it possible to solve this problem with your tool?

EF Core Power Tools version: 2.4.157
Database engine: SQL Server
Visual Studio version: Visual Studio 2019 15.7

**Comment by ErikEJ** [comment]
What have you tried?

Are you facing a concrete issue?

**Comment by EvgenyBelokurov** [comment]
I want to add stored procedures from an existing database using your tool.  They have the same names but different schemas. I select the "Generate stored procedure mapping (preview)" item.

I would like the schema names to be appended to the name of the stored procedures. How can I solve this?

**Comment by EvgenyBelokurov** [comment]
I have identically named stored procedure names in a table that are in different schemas:

schema1.Get_Attribute
schema2.Get_Attribute

By generating them I get EntityContextProcedures:



        public async Task<int> Get_Attribute(Guid? ID)
        {
          // ...

            return await _context.Database.ExecuteSqlRawAsync("EXEC [schema1].[Get_Attribute] @ID  ",parameterID);
        }

             public async Task<int> Get_Attribute(Guid? ID)
        {
          // ...

            return await _context.Database.ExecuteSqlRawAsync("EXEC [schema2].[Get_Attribute] @ID  ",parameterID);
        }

**Comment by ErikEJ** [comment]
Which does not compile - I get it.

**Comment by ErikEJ** [comment]
It's a bug, and I will look into a fix

**Comment by ErikEJ** [comment]
As a workaround, you can just rename manually

**Comment by EvgenyBelokurov** [comment]
Thanks for your reply! You may be right, but when I update the database, don't I get the same names again?

**Comment by ErikEJ** [comment]
>> don't I get the same names again?

Correct, until someone fixes the bug, yes

**Comment by EvgenyBelokurov** [comment]
Thank you very much for your response! Hopefully the bug will be fixed quickly.

**Comment by ErikEJ** [comment]
Who knows? Maybe someone will create a pull request with a fix?

**Comment by EvgenyBelokurov** [comment]
I have a large number of such stored procedures in my database. Changing manually will take a very long time. :-)
Can this topic be closed? 

I wish you success!

**Comment by ErikEJ** [comment]
>> Can this topic be closed?

No, it should be left open until the bug has ben fixed.
