### ISSUE TITLE
EFPT: Improve .NET Core process launcher 

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#50]
C:\Code\EntityFramework\src\dotnet-ef\RootCommand.cs

**Comment by bricelam** [comment]
This code is more appropriate if you have access to EnvDTE: https://github.com/aspnet/EntityFrameworkCore/blob/dev/src/EFCore.Tools/tools/EntityFrameworkCore.psm1#L757-L872

**Comment by ErikEJ** [comment]
I do not, but thanks

**Comment by ErikEJ** [comment]
@bricelam  I actually do have access to EnvDTE, thanks for the hint!

**Comment by ErikEJ** [comment]
@bricelam Does this mean I must intall EFCore.Design in order to make this work?

    dotnet exec --depsfile "C:\Users\Erik\Downloads\ConsoleApp3\ConsoleApp3\bin\Debug\netcoreapp2.2\ConsoleApp3.deps.json" --additional-deps "C:\Users\Erik\AppData\Local\Temp\efpt\epft.deps.json" --additionalprobingpath "C:\Users\Erik\.nuget\packages" --additionalprobingpath "C:\Program Files\dotnet\sdk\NuGetFallbackFolder" --runtimeconfig "C:\Users\Erik\Downloads\ConsoleApp3\ConsoleApp3\bin\Debug\netcoreapp2.2\ConsoleApp3.runtimeconfig.json" "C:\Users\Erik\AppData\Local\Temp\efpt\efpt.dll"  "C:\Users\Erik\Downloads\ConsoleApp3\ConsoleApp3\bin\Debug\netcoreapp2.2\ConsoleApp3.dll"

```
Error:
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.EntityFrameworkCore.Design, Version=2.2.4.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
File name: 'Microsoft.EntityFrameworkCore.Design, Version=2.2.4.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at ReverseEngineer20.EfCoreModelBuilder.BuildResult(String outputPath, Boolean generateDdl)
   at ReverseEngineer20.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efpt\Program.cs:line 44
```

**Comment by bricelam** [comment]
All dependencies of efpt.dll must be installed in the app. I think you can relax assembly version requirements by hooking `AppDomain.CurrentDomain.AssemblyResolve`:

``` csharp
AppDomain.CurrentDomain.AssemblyResolve += (sender, args) =>
{
    var fullName = new AssemblyName(args.Name);
    
    // Ignore Version, Culture, and PublicKeyToken
    return Assembly.Load(fullName.Name);
}
```

**Comment by ErikEJ** [comment]
Thanks, just now I refer to version 2.1.0 and 2.2.0 of EfCore.Design, and it seems to work fine.

**Comment by ErikEJ** [comment]
Does AppDomain exist in .NET Core??

**Comment by bricelam** [comment]
Parts of it were added to 2.0. You can't create new ones though, so there is only ever one app domain per process.

**Comment by bricelam** [comment]
As an alternative they've added custom load contexts and enabled unloading assemblies.
