### ISSUE TITLE
Could not load file or assembly 'MySql.Data, Version=8.0.18.0, Culture=neutral

### ISSUE THREAD

**Issue by picozzo92** [ErikEJ/EFCorePowerTools#500]
Hello,

after your latest updates I have problems when I am a Reverse Engineer.

In detail, the following error is returned despite the fact that I have the nuget package in the project dependencies: Could not load file or assembly 'MySql.Data, Version = 8.0.18.0, Culture = neutral

**Comment by ErikEJ** [comment]
Reverse engineer does not use any of your project references. Do you have the MySqL VS Tools installed? Are you trying EF Core 5 reverse  engineering?

**Comment by picozzo92** [comment]
I do not understand why until a few days ago everything worked properly, and now without any modification on the reference of my project does not work!

**Comment by picozzo92** [comment]
MySqL VS Tools is installed on my machine. Is it possible to have a version of the vsix from a few weeks ago?

**Comment by ErikEJ** [comment]
Please provide more context on when you get the error, and the full stack trace/error message. Reverse engineering does not use the MySQL provider, it uses the Pomelo provider.

**Comment by picozzo92** [comment]
I found what the error was, uninstalling and reinstalling MySqL VS Tools I was able to do the reverse Reverse engineer.
Sorry for wasting your time!
