### ISSUE TITLE
Reverse engineer many to many navigations with EF Core 6

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#501]
see https://github.com/dotnet/efcore/issues/22475

**Comment by REMjn832** [comment]
May I ask a question? I am getting ready to reverse engineer a slightly complex SQLServer database that has about a dozen join-tables for many-to-many relationships. Will 'EFCPT-ReverseEngineer' know how to reverse these into the proper navigational properties on their respective entities? Also, is there a naming convention I need to follow for the join-tables themselves? I think right now, they are named using the convention of "TableOnLeftSide_TableOnRightSide".
Thanks very much!
-josh

**Comment by ErikEJ** [comment]
@REMjn832 This feature is not implemented yet. Currently entities for your join tables will also be generated.

**Comment by REMjn832** [comment]
Thanks for the quick response @ErikEJ. Ok, I will set those up manually.
-josh

**Comment by ErikEJ** [comment]
You can do it in a partial class based on the generated DbContext

**Comment by ErikEJ** [comment]
This will happen for EF Core 6 RC1

**Comment by ErikEJ** [comment]
Correction: RC 2, actually (RC 1 was buggy)

**Comment by ErikEJ** [comment]
Fixed using daily builds.
