### ISSUE TITLE
Unhandled ArgumentException in FilePathToDisplayNameConverter when click cancel when select .dacpac file

### ISSUE THREAD

**Issue by yyjdelete** [ErikEJ/EFCorePowerTools#504]
Describe what is not working as expected.
Crashes with unhandled ArgumentException in FilePathToDisplayNameConverter

### Steps to reproduce
Include a complete description that I can redo to reproduce the issue.
1. Click `EF Core Power Tools/Reverse Engineer`;
2. Click `Choose SQL Server Database project (.dacpac) Add...`;
3. Click cancel directly;

https://github.com/ErikEJ/EFCorePowerTools/blob/bdef84ab2f187dd687ab5660df4211fd794dfd35/src/GUI/EFCorePowerTools/Converter/FilePathToDisplayNameConverter.cs#L15-L19
Seems `value == null` should be handled by the latter one, but also hit the first, and throw an exception.

### Further technical details
EF Core Power Tools version: 2.4.182.0

Database engine: SQL Server

Visual Studio version: 2019 16.8preview2.1

**Comment by ErikEJ** [comment]
Fixed in latest daily build
