### ISSUE TITLE
Inverse Property not created for a AspNetUsers.Id column

### ISSUE THREAD

**Issue by DevCisse** [ErikEJ/EFCorePowerTools#505]
I created a new table Say Students with Id and Name etc. I then made it PK and FK to AspNetUsers.Id column when I did reverse engineering, inverse property was not created for the Id

**Comment by ErikEJ** [comment]
Please provide proper details about your issue, thanks.

**Comment by DevCisse** [comment]
> I created a new table Say Students with Id and Name etc. I then made it PK and FK to AspNetUsers.Id column when I did reverse engineering, inverse property was not created for the Id

**Comment by DevCisse** [comment]
> Please provide proper details about your issue, thanks.

I have done that.

**Comment by ErikEJ** [comment]
Ok, please provide SQL Scripts to create the involved changes, and a sample of the generated code and pint out the missing navigation.

**Comment by DevCisse** [comment]
It is generating the inverse property now. While selecting tables, I just selected the tables I created myself since I can use `UserManager<T>` and `RoleMananger<T>` for the Identity. So, I didn't select them. But when I selected all tables it got generated. Thanks.
