### ISSUE TITLE
In the Context file, Getting message HasName is Obsolete, use HasDatabaseName() instead

### ISSUE THREAD

**Issue by KayakFisher205** [ErikEJ/EFCorePowerTools#511]
Describe what is not working as expected.

### Steps to reproduce
Using the 2.4.217.0 version to reverse engineer a SQL 2016 database, some tables that has the entity.HasIndex, flags the .HasName as Obsolete and to replace with HasDatabaseName
Warning	CS0618	'RelationalIndexBuilderExtensions.HasName<TEntity>(IndexBuilder<TEntity>, string)' is obsolete: 'Use HasDatabaseName() instead.

Replaceing the HasName with HasDatabaseName seems fine, but I've not really tested it and if I run EF Core Power Tools again, the changes are reverted anyways.

### Further technical details
EF Core Power Tools version: 2.4.217.0

Database engine: (SQL Server)

Visual Studio version: (e.g. Visual Studio 2019 Version 16.8.0 Preview 3.1)

**Comment by ErikEJ** [comment]
Are you trying to use EF Core 2 scaffolding with EF Core 5?

**Comment by KayakFisher205** [comment]
lol, yes I am. I didn't think I had the 5.0 preview installed.
