### ISSUE TITLE
Reverse Engineering - [Key] attribute is not generated

### ISSUE THREAD

**Issue by StefanFalz** [ErikEJ/EFCorePowerTools#512]
Prior versions of EFCore Power Tools generated a [Key] attribute for properties mapped to primary key columns in the table. The current version does not.

I use .NET Core 3.1 (SDK 3.1.402 is installed).

Please add the [Key] attribute again. Perhaps as an optional setting.

### Steps to reproduce
Create a Microsoft SQL Server database with a table "Test", add a column "ID" and mark this column as primary key. Reverse engineer this database.

Prior versions (unfortunately I don't know which version exactly because I didn't use the reverse engineering for a few months as there were no database changes) generating the following code:

```csharp
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace <Namespace>
{
    public partial class Test
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
    }
}
```

The current version produces:

```csharp
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace <Namespace>
{
    public partial class Test
    {
        [Column("ID")]
        public int Id { get; set; }
    }
}
```

### Further technical details
EF Core Power Tools version: 2.4.217.0 (none of the preview options are checked in the settings dialog)

Database engine: SQL Server 2017

Visual Studio version: VS 2019, 16.7.4

**Comment by ErikEJ** [comment]
Which EF Core version did you pick when reverse engineering? 

Have you selected to use Data annotations?

**Comment by ErikEJ** [comment]
If DataAnnotations have been selected, Key should always be generated:

https://github.com/dotnet/efcore/blob/main/test/EFCore.Design.Tests/Scaffolding/Internal/CSharpEntityTypeGeneratorTest.cs#L532

**Comment by StefanFalz** [comment]
I didn't pick any specific EF Core version.

![grafik](https://user-images.githubusercontent.com/41260292/94147164-3d391000-fe75-11ea-95a8-7c1a110ce721.png)

The DataAnnotions option is selected.

![grafik](https://user-images.githubusercontent.com/41260292/94147083-1d095100-fe75-11ea-877c-b30575a9be3a.png)

**Comment by StefanFalz** [comment]
> 
> 
> If DataAnnotations have been selected, Key should always be generated:
> 
> https://github.com/dotnet/efcore/blob/main/test/EFCore.Design.Tests/Scaffolding/Internal/CSharpEntityTypeGeneratorTest.cs#L532

Shame on me :( I'm stupid and blind. Sorry :(

I mixed the diff views up. Left side old, right side new. Of course the current version creates [Key] attributes while the old versions does not.

All is fine and sorry again :(
