### ISSUE TITLE
[Feature] Reverse Engineering - Save all selections to a file

### ISSUE THREAD

**Issue by KayakFisher205** [ErikEJ/EFCorePowerTools#514]
On the 'Select Tables to Script' there is the ability to Load and Save Selections. It would be very helpful that the data on the screen 'Generate EF Core Model in Project XXXXXXX', along with the selections in the Advanced button, to be stored along with the tables. The program does remember the last settings and for one database connection that works, but we have multiple layers of tables, from Production, MES, and ERP. If the camel case is wrong when trying to load a different database is wrong, the code breaks.
If all the setting are saved to some file (xml, JSON, txt, etc), it would be easier to reload and send the file to another user to use in there code, where they might have a need for different tables.

### Steps to reproduce
Save selection on saves a list of tables and Views selected.

### Further technical details
Version 2.4.220.0

SQLite ADO.NET Provider included: 1.0.109.0
SQLite EF6 DbProvider in GAC - No

System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes

Database engine: (SQlite, SQL Compact, SQL Server, Postgres)

Visual Studio version: (e.g. Visual Studio 2017 15.7)

**Comment by ErikEJ** [comment]
Not sure I understand your issue, edit.config.json already contains all relevant setting !?

**Comment by ErikEJ** [comment]
Ping?

**Comment by KayakFisher205** [comment]
Sorry, I didn't see the email. It think Issue 517 would resolve my issue. I will close this one.
