### ISSUE TITLE
[Feature] Enable support for multiple saved config files in same project

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#517]
1. Allow user to create initial efpt.config.json file, and rename to for example efpt.MyContext.config.json

2. Upon launch of reversen engineer, check if there are files following the efpt.xxx.config.json pattern (including the original "efpt.config.json".

3. If there are files other than efpt.config.json, display a dialog with a dropdown list of each found file name.

4. Use the selcted file for getting and saving options during the "run".

**Comment by ErikEJ** [comment]
@kayakfisher205 Fixed, please try the latest daily build

**Comment by KayakFisher205** [comment]
I found you must have a efpt.config.json file, the copy it and create the efpt.xxxContext.json file. After that, I got the dropdown at the start of Reverse Engineer. Once I had everything set, it worked perfectly. My only request would be to save the Database Connection from the 'Choose Database Connection' popup, along with the Use EF Core 5 (preview). I don't use Filter Schemas, but saving that would be helpful too. If I sent the json file to a coworker, they might not know the server name or the extra selections I had made.

**Comment by ErikEJ** [comment]
Saving database connection is not something I plan to do, as it could expose sensitive information. 

I will consider the other options based on feedback.

**Comment by ErikEJ** [comment]
@KayakFisher205 Happy for any feedback on the docs here: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#saving-options-and-running-the-second-time

**Comment by KayakFisher205** [comment]
> @KayakFisher205 Happy for any feedback on the docs here: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#saving-options-and-running-the-second-time

Looks good. I find myself copying and pasting the current efpt.config.json and renaming to match the Context I'm creating. I didn't know if there was a better way
