### ISSUE TITLE
[Feature] Add possibility to mention full namespace for entities location

### ISSUE THREAD

**Issue by Marmotor** [ErikEJ/EFCorePowerTools#518]
Hi! 

I have the following scenario: Generating the table structure (Entities) in one project, and generating the DbContext and configuration files in another project. The result of this approach is that the context and configuration files need a reference to the namespace where the entity files are located. 
I tried using the `EntityTypes sub-namespace` feature, but this just appends the input namespace to the destination project's own namespace - which I assume is what it is meant to do.

The only solution I currently have is to manually edit the DbContext and configuration files to add the reference to where the entities are located. 

It would be nice to be allowed to specify exactly where the entities are or will be located so that their full namespace can be added to the generated context and configuration files, without the need to manually edit them.

I know you already heard this a lot, but this extension is such an time-saver, thank you very much for doing this!

If you need extra print screens or other details, I'll happily provide them.

### Further technical details
EF Core Power Tools version: 2.4.217.0

Database engine: SQL Server 2016

Visual Studio version: Visual Studio 2019 v. 16.4.2

**Comment by ErikEJ** [comment]
I think there are links to examples of doing this in the wiki ...

**Comment by ErikEJ** [comment]
You should be able to do this in a single run...

**Comment by Marmotor** [comment]
Thanks for the hint, I managed to partially solve the issue by using handlebars. At this point the namespace is hardcoded in the handlebar file, but it's indeed a step forward.

**Comment by ErikEJ** [comment]
Handlebars should definitely not be required. 

Did you look at the links in the wiki?

**Comment by Marmotor** [comment]
That is where I came up with the idea to use the handlebars. 
The second time I looked after you mentioned handlebars are not required, I noticed a link to this same issue someone else mentioned and that's where I found the following solution: Top namespace input should be the common namespace part for the two projects. Then specify in the `EntityTypes sub-namespace` input the rest of the namespace to where your entities are located and in the `DbContext sub-namespace` input the rest for the `DbContext` location. This results in the concatenation of the common namespace and the `Entity` namspace in a  `using` statement which will be injected in your context and configuration files.

**Comment by ErikEJ** [comment]
So this can be closed now?

**Comment by Marmotor** [comment]
Yes, I'll do it. If possible, maybe update the wiki with this info? It's taken me a bit of time to figure it out, so maybe adding it there might help others. 
Thanks for your input and tips!

**Comment by ErikEJ** [comment]
Would be great if you could provide more details with a sample perhaps?
