### ISSUE TITLE
EF Core Power Tools does not keep identity column name

### ISSUE THREAD

**Issue by laksh-parab** [ErikEJ/EFCorePowerTools#519]
I have <s>.NET Core 3.1</s>  .NET Standard 2.0 class library with Microsoft.EntityFrameworkCore.SqlServer 3.1.8. I am using VS 2019 with EF Core Power Tools 2.4.217

All my SQL table names are pluralize and have identity column with the following naming convention {TableName}ID. So for example **Documents** table has identity column **DocumentID**

When I use reverse engineering to generate entities, the power tool generate property name as **DocumentId** instead of **DocumentID**

Same issue happens with foreign key column.

How do tell power tool not to change **ID** to **Id**?

**Comment by ErikEJ** [comment]
Maybe you can use the [renaming feature](https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#custom-renaming-with-epftrenamingjson) ?

**Comment by laksh-parab** [comment]
In SQL the table name is pluralized and all the ID columns ( PK and FK) has affix ID.  I want corresponding class name to be singular and no change in the column/property name. There are more ID columns than number of tables. So during reverse engineering,  i selected `Use table and column names directly from the database` option. This generates property name correctly. But it creates pluralize class name. So i added the `efpt.renaming.json` file with the following configuration 

```
[
  {
    "UseSchemaName": false,
    "SchemaName": "dbo",
    "Tables": [
      {
        "Name": "Documents",
        "NewName": "Document"
      }
    ]
 }
]
```

However it still creates class name as `Documents`  (With `User table and column name.....` option selected)

If i unselect `Use table and column names directly from the database`  option then it use the json file and creates class name as `Document` but then ID columns get renamed as `Id`

So looks like we cannot use json file along with other provided option

**Comment by ErikEJ** [comment]
It is not something that is currently supported.

**Comment by ErikEJ** [comment]
Maybe fixed with EF Core 5 ?

**Comment by florinciubotariu** [comment]
Still doesn't work on my side.

**Comment by ErikEJ** [comment]
@florinciubotariu ??? What do you mean? Did you try "Use Database Names" with EF Core 5 and it did not work?

**Comment by florinciubotariu** [comment]
@ErikEJ You are right. I overlooked it.

If you have the following settings then your db columns will translate the same in this XID case.

![image](https://user-images.githubusercontent.com/18595953/94987431-0945a500-056f-11eb-85c5-f44db31dd4de.png)

Sorry for wasting your time.

**Comment by ErikEJ** [comment]
@florinciubotariu no wasting of time at all! Thanks for confirming. @laksh-parab  FYI!

**Comment by laksh-parab** [comment]
As i mentioned `Use table and column names directly from the database` does translate `ID` to `ID`, however it also keeps the  entity class name pluralized.

**Comment by ErikEJ** [comment]
@laksh-parab see #473

**Comment by ErikEJ** [comment]
@laksh-parab Implemented in latest daily build, but for EF Core 5 only
