### ISSUE TITLE
Support for net5?

### ISSUE THREAD

**Issue by julielerman** [ErikEJ/EFCorePowerTools#522]
Hi Erik,
 I imagine that at some point you'll be supporting projects targeting NET5.  
I tried searching issues  but didn't find anything. 
Just updating my EF Core course but I am in early days and can defer this part until later.
Thanks!

**Comment by ErikEJ** [comment]
Assume you are referring to model inspection?

**Comment by julielerman** [comment]
Sorry yes. I have only tried my favorite feature so far...generating the dgml.

**Comment by ErikEJ** [comment]
Fixed in latest daily build

**Comment by julielerman** [comment]
THANK YOU !!!! :) I hope it was super easy and quick.

**Comment by ErikEJ** [comment]
Not too hard; https://github.com/ErikEJ/EFCorePowerTools/commit/3a8426f4e83c802c8d05fb18491ae84c0ec67ba2
