### ISSUE TITLE
Stored procedure is not generated if it uses a #temp table

### ISSUE THREAD

**Issue by PureConsulting** [ErikEJ/EFCorePowerTools#526]
Stored procedure is not generated if it uses a #temp table

### Steps to reproduce
Create a stored procedure that uses a #temp table

exec dbo.sp_describe_first_result_set N'dbo.usp_SwapReservations'

returns the following results

Msg 11526, Level 16, State 1, Procedure dbo.sp_describe_first_result_set, Line 1 [Batch Start Line 18]
The metadata could not be determined because statement 'UPDATE LotHistory SET ExitDate = GETDATE() WHERE LotHistoryID IN (
SELECT LotHistoryID FROM LotH' in procedure 'usp_SwapReservations' uses a temp table.

We feel at least a warning should be generated.

### Further technical details
2.4.228

Database engine: (SQlite, SQL Compact, SQL Server, Postgres)
SQL Server 2017 Express

Microsoft Visual Studio Professional 2019 Preview
Version 16.8.0 Preview 3.1
VisualStudio.16.Preview/16.8.0-pre.3.1+30516.212
Microsoft .NET Framework
Version 4.8.03761

Installed Version: Professional

.NET Portability Analyzer   1.1.10808.0
Evaluates portability of assemblies across .NET platforms.

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   16.8.442.31521
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2046102+2078c50b948ee8c2e2072fc69f5147b15e456b56
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.8.442.31521
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.8.442.31521
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.6.1000.1
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.8.442.31521
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.1000.1
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   3.8.0-3.20458.6+b446afd34759150c2ea3b86ab794104e12e64db1
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Entity Framework Core Power Tools   2.4
Adds useful design-time EF Core DbContext features to the Visual Studio Solution Explorer context menu. 

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure HDInsight Azure Node   2.6.1000.1
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.6.1000.1
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   16.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.6.1000.1
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30701.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.79+ge3567815aa.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

NuGet Package Manager   5.8.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62009.04150
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.20902.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.8.0-3.20458.6+b446afd34759150c2ea3b86ab794104e12e64db1
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.8.0-beta.20428.2+068ebd3c599bc5a47163a18b8b90d2fe5517186e
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions (Preview)   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Kubernetes   1.0
Visual Studio Tools for Kubernetes

**Comment by ErikEJ** [comment]
Agree, I will look into generating a warning. Could you create a sample sproc?

**Comment by ErikEJ** [comment]
And thanks for trying out this preview feature and providing feedback, btw

**Comment by PureConsulting** [comment]
CREATE PROCEDURE usp_GetUserTables
AS
BEGIN
	SELECT * INTO #temp1 FROM sys.tables;
	SELECT * FROM #temp1
END

**Comment by PureConsulting** [comment]
Alternatively, you could generate the stored procedure with an empty resultset but warn the user that the stored procedure was generated with an empty resultset.  That would be my choice.

**Comment by ErikEJ** [comment]
How and where would the user be warned?

**Comment by PureConsulting** [comment]
Keep a list of them while you are processing and the pop up a dialog box at the end and say something like "The following procedures contained temp tables which prevented the extraction of the result-sets.  These procedures were created but contain empty result-sets.

<<List of Stored Procedures>>
