### ISSUE TITLE
Reverse Engineer view skips columns with Cast

### ISSUE THREAD

**Issue by biiiipy** [ErikEJ/EFCorePowerTools#528]
If a view has a column with `Cast`, the generated model skips that column

### Steps to reproduce

```sql
CREATE VIEW [dbo].[View2]
AS SELECT 
          Id, 
          CAST(Id as varchar(max)) IDSTRING 
          FROM TABLE1
```

Reverse Engineer result:
```csharp
public partial class View2
{
    public int Id { get; set; }
}
```

### Further technical details
EF Core Power Tools version: 2.4.217

Database engine: SQL Server 2016

Visual Studio version: 16.7.4

**Comment by ErikEJ** [comment]
From a dacpac or live db?

**Comment by biiiipy** [comment]
It doesn't work with .dacpac file or dacpac project (can reproduce with the same project in my previous issue), BUT it seems that reverse engineering from a MDF (that has the dacpac deployed), works correctly.
Is it preferable to reverse engineer from a DB than a dacpac?

**Comment by ErikEJ** [comment]
There are a number of limitations in relation to views when using a dacpac, do if you rely on them, publish to a live db.

**Comment by biiiipy** [comment]
Thank you very very much for clarification! Closing.
