### ISSUE TITLE
Error - Unable to find requested .Net Framework Data Provider

### ISSUE THREAD

**Issue by bairog** [ErikEJ/EFCorePowerTools#529]
I have WinForms application targeting .NET Framework 4.8.
I'm using Visual Studio 2019 16.7.5 Enterprise and have Microsoft.EntityFrameworkCore.SQLite 3.1.8 nuget reference.  
I've installed latest version of your extension from Extentions -> Manage Extentions menu
![image](https://user-images.githubusercontent.com/44995181/95192945-a73da780-07db-11eb-8197-e257055d3488.png)
After that I used EF Core Power Tools -> Reverse Engineer menu, selected SQLite provider, filled Data Source in connection string
![image](https://user-images.githubusercontent.com/44995181/95193241-2b902a80-07dc-11eb-979c-be5b7ebdb6e3.png)
(connection Test was OK) but clicking OK button results in _Unable to find requested .Net Framework Data Provider_ error
![image](https://user-images.githubusercontent.com/44995181/95193461-86c21d00-07dc-11eb-9ac7-3737f7494605.png)

Sample application is uploaded **[here](https://yadi.sk/d/Q4JJ1ZDbEOIXfA)**

### Steps to reproduce
Click EF Core Power Tools -> Reverse Engineer. Click Add, select SQLite provider, fill Data Source in connection string and click OK button.

### Further technical details
EF Core Power Tools version: 2.4.217
Database engine: SQLite3
Visual Studio version: Visual Studio 2019 16.7.5 Enterprise

**Comment by ErikEJ** [comment]
The SQLite provider is not installed, you must follow this guide very carefully, if you do that, then the dialog will look like this instead:

![image](https://user-images.githubusercontent.com/4169187/95196171-000b4100-07d8-11eb-93fc-d709789db8fd.png)

**Comment by bairog** [comment]
@ErikEJ Follow which guide?

**Comment by ErikEJ** [comment]
With the latest daily build, you can avoid installing the provider!
