### ISSUE TITLE
Reverse Engineer - Nullable varchar bug

### ISSUE THREAD

**Issue by TanguyPa** [ErikEJ/EFCorePowerTools#534]
I'm trying to call a stored procedure that has varchar as parameter.
When I pass a NULL string to the corresponding method in C#, an exception occurs :
The parameterized query '(@p1 varchar(40) @p2 varchar(40) @p3 vnvarchar(4' expects the parameter '@p1' which was not supplied.

I solved my problem by manually changing each parameter value by adding :
Value = (object)myParam?? DBNull.Value

I don't know if I'm doing something wrong, but at the request execution the parameters are not passed without the DBNull.Value.

EF Core Power Tools version: 2.4.217

Database engine:  SQL Server

Visual Studio version: 2019 16.7.2

**Comment by ErikEJ** [comment]
Please share the stored procedure decalration, and also the line of code where you call it, and I will have a look.

**Comment by TanguyPa** [comment]
So i get this error message : 

> La requête paramétrable '(@testParameter1 int,@testParameter2 varchar(255))EXEC [dbo].[Te' attend le paramètre @testParameter2, qui n'a pas été fourni.
I think the error message in english is :
The parameterized query '(@testParameter1 int @p2testParameter2 varchar(255))EXEC [dbo].[Te' expects the parameter '@testParameter2' which was not supplied

Here is the code of my stored procedure, I made a test procedure that does nothing.
```sql
ALTER PROCEDURE [dbo].[TestMethod]
	@testParameter1 as int,
	@testParameter2 as varchar(255)
AS
BEGIN
	SET NOCOUNT ON;
	--Nothing
	return 0
END
```

Here is the C# code to called it in async method :
```csharp
SapclientContext sapclientContext = new SapclientContext();
SapclientContextProcedures sapclientContextProcedures = new SapclientContextProcedures(sapclientContext);
string mystring = null;
int? myInt = 2;
await sapclientContextProcedures.TestMethod(myInt, mystring);
```

And this is the generated code : 
```csharp
        public async Task<int> TestMethod(int? testParameter1,string testParameter2)
        {
            var parametertestParameter1 = new SqlParameter
            {
                ParameterName = "testParameter1",
                Precision = 10,
                Size = 4,
                SqlDbType = System.Data.SqlDbType.Int,
                Value = testParameter1,
            };

            var parametertestParameter2 = new SqlParameter
            {
                ParameterName = "testParameter2",
                Precision = 255,
                Size = 255,
                SqlDbType = System.Data.SqlDbType.VarChar,
                Value = testParameter2,
            };

            return await _context.Database.ExecuteSqlRawAsync("EXEC [dbo].[TestMethod] @testParameter1,@testParameter2  ",parametertestParameter1,parametertestParameter2);
        }
```

**Comment by ErikEJ** [comment]
You are not forgetting things, you found a bug! Fix coming up 😄

**Comment by ErikEJ** [comment]
Fixed in latest daily build

**Comment by TanguyPa** [comment]
It works fine, thank you.

**Comment by ErikEJ** [comment]
Thanks for reporting this, and for confirming the fix.
