### ISSUE TITLE
Can there be a way to set a suffix for the generated files? 

### ISSUE THREAD

**Issue by yomer** [ErikEJ/EFCorePowerTools#54]
Thank you Erick for this useful tool. 

I'm trying to use it to create my db model, as expected, but I'm also using it to generate DTOs faster. 

Would it be possible to add the option to add a suffix(and a prefix) to the generated classes? 

I can use handlebars to name the classes my way, with a suffix, but the file names keep the table names. 

It would be very useful to be able to set primarily a suffix and also the prefix for the class files. 

What are your thoughts about this?

**Comment by ErikEJ** [comment]
Generally, generating DTOs directly from the database is not a good pattern, IMHO.

Are you referring to just the file names?

**Comment by kachalkov** [comment]
We found that handlebars are not as easy to modify especially for suffix, end up using GeCo (Generator Console) for that:

https://github.com/iQuarc/Geco

**Comment by yomer** [comment]
Can't this be added via the GUI interface, to add the suffix to the filename?

**Comment by ErikEJ** [comment]
@yomer How would that affect the class Name? Or are you referring to just the file name?

**Comment by yomer** [comment]
It's just for the file name. The class Name, I can set it by modifying the handlebar templates. I was looking into adding a suffix for the sake of having the class Names and filenames with the same suffix.

I know that my request is a bit specific. Maybe someone else could eventually need to add either a prefix or a suffix to their classes.

_A small reminder: I'm using EF CorePowerTools to generate my model for data access. And, since I would have to type in a lot of code to make my DTOs, my intention is to use this tool to generate suffixed classes (and filenames) which then I will alter to end up with said DTOs._

**Comment by RefX32** [comment]
I made an issue about this but I closed it since this already exist. I also would like to see something exactly the same as what the OP is requesting. Being able to add suffix to filename only. This was my message:

_I think it would be a good idea to implement a way we can add prefix/suffix to generated classes from table. Let's say we have a "Blogs" table. When I run the power tool, it'll generate "Blog" class. However, in my project I already have a "Blog" class as well. Sure, I can easily reference the correct namespace and do ToPOCO conversion. However, it'll be much easier to differentiate if I could add suffix to my generated class name, something like "BlogDTO" or "BlogEF". Maybe an option, where we can pick the generated classnaming? E.g. "{class}DTO"._ My closed issue: https://github.com/ErikEJ/EFCorePowerTools/issues/75

**Comment by RefX32** [comment]
Any update on this? It's a big help because you can have 3 different types of class with the same name. For example, Blogs (local class), Blogs (Database/EF Class), and Blogs (DTO Class). So if we can add a suffix like "BlogsDBO", it can help in differentiating which class we are looking for.

**Comment by ErikEJ** [comment]
@RefX32  You could put the files in different name spaces and/or projects - having them all in the same folder seems like a wrong pattern

**Comment by ErikEJ** [comment]
@RefX32 Some users in this thread are referring to just the file names, but if I understand you correctly, you are referring to the class names - so there are two issues here? Or am I misunderstanding?

**Comment by ErikEJ** [comment]
Modifying the file names is just a question about getting the required input about what to do, and the modify the code here: https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/EFCorePowerTools/Handlers/ReverseEngineerHandler.cs#L186

**Comment by RefX32** [comment]
Sorry, I was not aware people were referring to file names. Why have a file name different than class name though? If they create a file name like "BlogsDTO.cs", why have a class name like "Blogs" inside it? This does not feel clean to me. 

One of the suggestion was having a "Suffix/Prefix input" when the option pops up. It could be "{tableName}" by default, and if we want to add any suffix/prefix to it, we can change it to something like "{tableName}DBO", which will generate "Blogs" table name as "BlogsDBO". Once again, just a suggestion.

**Comment by ErikEJ** [comment]
@RefX32  I think this feature will be able to help you: https://github.com/ErikEJ/EFCorePowerTools/issues/128#issuecomment-439692246

**Comment by RefX32** [comment]
So that is kind of  like a configuration file? We have over 100 tables at our work, is there a way I can define every class we generate, we want it named {tableName}DBO on that file?

**Comment by ErikEJ** [comment]
How you create and maintain the file is entirely up to you and your imagination.

**Comment by dharmaturtle** [comment]
I accomplished OP's request here: https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars/issues/34#issuecomment-479703960
