### ISSUE TITLE
Unable to scaffold stored procedure: Invalid column name 'is_nullable'.

### ISSUE THREAD

**Issue by NutmegAdam** [ErikEJ/EFCorePowerTools#541]
Now that the config file issue is resolved, the reverse engineering proceeds and gets me to the error I was originally looking into.

I get a long list of the same error:

```
Unable to scaffold apStoredProcName1
Invalid column name 'is_nullable'.
Unable to scaffold apStoredProcName2
Invalid column name 'is_nullable'.
Unable to scaffold apStoredProcName3
Invalid column name 'is_nullable'.
```

Some of those procedures have params, some don't. Some return data, some don't. But given that this isn't happening with other databases I connect to, and since the error seems to be an internal confusion over a column name vs. a column parameter, I suspect this may be due to a version difference in SQL Server or something along those lines, with the schema data being returned in a slightly different format?

I can PM you the schema for some of the procs, but my guess is this isn't due to the procedures themselves, given that it happens to 100% of the procedures in this database, but 0% of the procedures in another database.

### Steps to reproduce

1. Right-click project -> EF Core Power Tools -> Reverse Engineer
2. Have tried with and without selecting "Use EF Core 5 (preview)"
3. Select all tables
4. Advanced -> "Generate Stored Procedure Mappings (preview)"

### Further technical details
EF Core Power Tools version: 2.4.245 (daily)

Database engine: SQL Server

Visual Studio version: Visual Studio 2019 16.7.6

**Comment by ErikEJ** [comment]
You need to share the sprocs.

Which SQL Server version?

**Comment by NutmegAdam** [comment]
Microsoft SQL Server 2008 R2 (RTM) - 10.50.1600.1 (X64)

What email should I send the definitions to?

**Comment by ErikEJ** [comment]
SQL Server 2008 is not supported!

**Comment by NutmegAdam** [comment]
Aha! Well then that's one more reason to add to the list of reasons for them to upgrade, like we've been trying to get them to do for years! :)

Thanks very much for all your help today - keep up the good work!

**Comment by ErikEJ** [comment]
I will update the docs to make it clear that only SQL Server 2012 or later is supported
