### ISSUE TITLE
efpt.config.json not appearing to work

### ISSUE THREAD

**Issue by rasaconsulting-sandy** [ErikEJ/EFCorePowerTools#542]
I'm trying to use the EF Core Power Tools to generate a SQL Server view into a C# class with a different name (i.e. view name = "shared.vw_Person" and I want a resulting Entity class = "PersonViewModel".  I've created a 'efpt.config.json' file in the project root - see below for file contents.  The power tools appear to ignore the 'efpt.config.json' file....

![Screenshot 2020-10-20 135055](https://user-images.githubusercontent.com/69283328/96526903-59e13000-12db-11eb-89aa-5c1e02b82163.png)

I've tried different combinations of 'Naming' options on the form (i.e. Pluralize versus Use table and column names directly)

### Further technical details
EF Core Power Tools version: 2.4.217

Database engine: SQL Server (local db)

Visual Studio version: Visual Studio 2019 community edition 16.7.6

My efpt.config.json file contents:

[
	{
		"UseSchemaName": true,
		"SchemaName": "shared",
		"Tables": [
			{
				"Name": "vw_Person",
				"NewName": "PersonViewModel"
			}
		]
	}
]

**Comment by NutmegAdam** [comment]
This might be related to issue #540 - the problem I had was writing the file, but presumably would affect reading it as well, due to the issue getting the name. If it was that, then the nightly build should fix it.

**Comment by ErikEJ** [comment]
Looks like you got the filename wrong - it should be efpt.renaming.json - is there an issue with my documentation?

**Comment by rasaconsulting-sandy** [comment]
Oh awesome thanks!  It was an issue with my file name - no problems with the documentation - I just ran it successfully now.

**Comment by rasaconsulting-sandy** [comment]
I just found a discrepancy in the documentation (https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering) which is where I got things wrong - the section heading is "Custom renaming with e**pf**t.renaming.json" but the filename needs to be e**fp**t.renaming.json

**Comment by ErikEJ** [comment]
Docs typo fixed, thanks!

**Comment by rasaconsulting-sandy** [comment]
Thanks for your help - I love the tool!

**Comment by ErikEJ** [comment]
You are welcome - If you enjoy my free tools, I would be very grateful for a rating or review here:

https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details

**Comment by CalvinQuark** [comment]
I am encountering the following issue which may be related to this thread.

Whereas the EF Core Power Tools Visual Studio Extension's *Reverse Engineer* action, when triggered via the *Solution Explorer* context menu, does comply with the settings specified in an existing `epft.config.json` file, the CLI, by contrast, ignores the existing `epft.config.json` file and overwrites its settings.

I am triggering the CLI command from a Console App sibling project. Here is my launch code:

```cs
static void ScaffoldRepo() {
    IConfiguration configuration = new ConfigurationBuilder()
        .SetBasePath(Directory.GetCurrentDirectory())
        .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
        .Build();
    
    string? connectionString = configuration.GetConnectionString("WordArtDbConnection");
    
    if (string.IsNullOrWhiteSpace(connectionString)) {
        Console.WriteLine("The `WordArtDbConnection` connection string is not found in the `appsettings.json` file.");
        return;
    }
    
    Console.WriteLine($"\n Scaffolding the `{_wordArtRepo}` project...\n");
    string baseDirectory = AppContext.BaseDirectory;
    string repoDirectory = Path.GetFullPath(Path.Combine(baseDirectory, $@"..\..\..\..\{_wordArtRepo}"));
    string configFilePath = Path.Combine(repoDirectory, "Data", "efpt.config.json");
    const string efCoreProviderAbbreviation = "sqlserver";
    
    ProcessStartInfo startInfo = new() {
        FileName = "efcpt",
        Arguments = $"\"{connectionString}\" {efCoreProviderAbbreviation} --input \"{configFilePath}\"",
        WorkingDirectory = repoDirectory,
        RedirectStandardOutput = true,
        UseShellExecute = false,
        CreateNoWindow = true,
    };
    
    using Process? process = Process.Start(startInfo);
    
    if (process is null) {
        Console.WriteLine($"Failed to start the `{_wordArtRepo}` scaffolding process.");
        return;
    }
    
    string output = process.StandardOutput.ReadToEnd();
    process.WaitForExit();
    
    Console.WriteLine(output);
}
```

The `efpt.config.json` file is down one level in the `Data` subfolder. But whether it is in the project's root folder or in the `Data` subfolder, the same behavior is encountered. The VS Extension respects the configuration. But the CLI overwrites it.

```
> efcpt --version
efcpt.8 8.1.100+a78519c6255d38cb75b7efbf9a79f0e21fe4db59
```

**Comment by ErikEJ** [comment]
The CLI uses a different file name and format as you can see in the CLI readme.

@CalvinQuark
