### ISSUE TITLE
EntityOnly for POCO generates context related classes

### ISSUE THREAD

**Issue by mbharodia** [ErikEJ/EFCorePowerTools#544]
I got the latest daily build today with VS 2019 Enterprise. I wanted to generate Entity type (POCO) only. Beside entity types, it also added DB context related classes.

![image](https://user-images.githubusercontent.com/10344641/96805383-c6892700-13ce-11eb-98dc-7a040ffa7897.png)

![image](https://user-images.githubusercontent.com/10344641/96805424-e1f43200-13ce-11eb-910c-aa1eb62aaec9.png)

### Steps to reproduce
Provided the following input to generate only entity types
![image](https://user-images.githubusercontent.com/10344641/96805540-19fb7500-13cf-11eb-93ab-f1b57cd33165.png)

### Further technical details
Version 2.4.260.0 (latest daily build)

SQLite ADO.NET Provider included: 1.0.109.0
SQLite EF6 DbProvider in GAC - No

System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes

Database engine: (SQlite, SQL Compact, SQL Server, Postgres)

Visual Studio Enterprise version: (e.g. Visual Studio 2019 16.7.1)

**Comment by ErikEJ** [comment]
Thanks for reporting, fixed in latest daily build.

**Comment by mbharodia** [comment]
Okay. Thanks. It worked; I tested this with the latest daily build.
