### ISSUE TITLE
Add localization

### ISSUE THREAD

**Issue by Varorbc** [ErikEJ/EFCorePowerTools#546]
Add localization

Current status: 

- [x] Simplified Chinese
- [x] French
- [x] Italian
- [x] Turkish
- [ ] ???

![image](https://user-images.githubusercontent.com/4169187/111023313-97ed0680-83d8-11eb-8f13-bebfe61580a8.png)

**Comment by ErikEJ** [comment]
Do you mean of the UI?

**Comment by Varorbc** [comment]
yes

**Comment by ErikEJ** [comment]
I am open to a PR to do this...

**Comment by ErikEJ** [comment]
https://docs.microsoft.com/en-us/visualstudio/extensibility/localizing-vsix-packages?view=vs-2019 

https://docs.microsoft.com/en-us/visualstudio/extensibility/localizing-menu-commands?view=vs-2019 

(And error messages etc.)

**Comment by sm15455** [comment]
@ErikEJ I could work on this. (I need to understand how translation works for labels and messages but it shouldn't be hard). I can also translate messages in italian, but would definitely need help for other languages.

**Comment by ErikEJ** [comment]
Sounds great, first step would be to move all current messages to the current default resx file.

Adding VsLanguagePack seems out of scope.

**Comment by Varorbc** [comment]
I can help with Chinese translationI can help with Chinese translation

**Comment by sm15455** [comment]
@ErikEJ there are exceptions that are thrown inside exe.

```
throw new ArgumentException("No type mapping exists for " + objectType.Name);
```

Should I localize their message?

**Comment by ErikEJ** [comment]
Let's not focus on that now.

I will create a separate issue for that.

**Comment by sm15455** [comment]
@ErikEJ, now that we moved all strings into resource files, we need to find a way to test other cultures. Should I create a VM, install italian version of VS and test localization on that machine? Do you know a simpler way?

**Comment by ErikEJ** [comment]
I wonder if it is just a question of setting the current culture in control panel, or it is depending on the VS SKU?

**Comment by ErikEJ** [comment]
Localization is now in, see PR   https://github.com/ErikEJ/EFCorePowerTools/pull/850

@tiomny @omatrot @pedromcrocha @theprateik @Herdo ???

**Comment by omatrot** [comment]
I could help for French obviously ;)

**Comment by ErikEJ** [comment]
Closing and moving to Backlog milestone
