### ISSUE TITLE
[Feature] Reverse Engineer - Add schema name in class/method/property name

### ISSUE THREAD

**Issue by TanguyPa** [ErikEJ/EFCorePowerTools#547]
When views have the same name but different schema names, the names of the generated classes and methods are not very explicit.
For example, if you have three schemas: dev, stag, prod and you have a view "VMyView" defined on each schemas: dev.VMyView, stag.VMyView, prod.VMyView.
The generated classes will be named as follows: 
VMyView, VMyView1, VMyView2, the same thing happens for the property name in the DbContext.
It is difficult to know which class is associated with which schema.

I think the same thing should happen for tables, but I haven't tested it.
I noticed something is that the classes are named according to the alphabetical order of the schema. For example, dev is before stag and prod, it will have the VMyView class, prod is before stag it will have the VMyView1 class... but I'm not sure what I'm saying.

My suggestion would be to add the schema name as a prefix or suffix to the class/property name. 
This is already the case for stored procedures, for example MyStoredProcedure in each schema will generate the following methods and classes names:
MyStoredProcedureDev, MyStoredProcedureStag, MyStoredProcedureProd.

EF Core Power Tools version: 2.4.239

Database engine: SQL Server

Visual Studio version: 2019 16.7.2

**Comment by ErikEJ** [comment]
I think you can use the renaming feature to fix this.
https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#custom-renaming-with-efptrenamingjson

**Comment by TanguyPa** [comment]
It's exactly what i was looking for. Thank you
