### ISSUE TITLE
Error converting System.DBNull in OutputParameter.SetValue

### ISSUE THREAD

**Issue by tiomny** [ErikEJ/EFCorePowerTools#548]
Exception is thrown in OutputParameter.SetValue when value is System.DBNull

### Steps to reproduce
```SQL
CREATE PROCEDURE [CALCULATIONS].[SOME_CHECK](
       @RESPONSESTATUS VARCHAR(20) OUTPUT,
       @RESPONSEMESSSAGE  VARCHAR(200) OUTPUT )  
AS 
SET NOCOUNT ON
BEGIN
  set @responsestatus = 'yes'
END
GO
```

### Further technical details
EF Core Power Tools version: 2.4.266.0

Database engine: (SQL Server)

Visual Studio version: (e.g. Visual Studio 2019 16.7.7)

### Possible solution
```C#
    _value = null == value || Convert.IsDBNull(value) ? default : (TValue)value;
```

**Comment by ErikEJ** [comment]
Thanks for reporting this, fixed in latest daily build
