### ISSUE TITLE
Unable to use with a project that targets x64

### ISSUE THREAD

**Issue by jmoleary** [ErikEJ/EFCorePowerTools#55]
I'm not sure if this is a bug or intentional design but if it is the latter I'm hoping for a workaround if you know of one. 

I have a .NET class library that targets x64 as its build target.  Whenever I try to do "View DbContext Model DDL SQL" from the EFCore Power Tools (EFCPT) menu the build fails with the error that it cannot load my file or assembly because it was "compiled for a different processor"

If I change the build target to "Any CPU", then  EFCPT works fine.  Unfortunately I cannot change the target of my project for other reasons.

### Steps to reproduce

1. Take that sample project I gave you in Issue #52 (which you just fixed, thank you).  
2. In Project Properties >> Build Change the "Platform Target" to "x64".
3. Build the project - it builds
4. From the EFCore Power Tools context menu, choose "View DbContext Model DDL SQL".  You will get the following output:

> System.ArgumentException: Error:
> System.BadImageFormatException: Could not load file or assembly 'TestEFPowerTools, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. This assembly was compiled for a different processor.
>    at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
>    at System.Reflection.Assembly.LoadFile(String path)
>    at ReverseEngineer20.EfCoreModelBuilder.Load(String assemblyPath)
>    at ReverseEngineer20.EfCoreModelBuilder.GetOperations(String outputPath)
>    at ReverseEngineer20.EfCoreModelBuilder.BuildResult(String outputPath, Boolean generateDdl)
>    at ReverseEngineer20.EfCoreModelBuilder.GenerateDatabaseCreateScript(String outputPath)
>    at ReverseEngineer20.Program.Main(String[] args)

> Parameter name: processResult
>    at EFCorePowerTools.Handlers.ModelAnalyzerHandler.Generate(String outputPath, Project project, GenerationType generationType) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ModelAnalyzerHandler.cs:line 49

### Further technical details
EF Core Power Tools version: Version 1.0.618.0
SQL Server Compact 4.0 in GAC - Yes - 4.0.8876.1
SQL Server Compact 4.0 DbProvider - Yes
SQL Server Compact 4.0 DDEX provider - No
SQL Server Compact 4.0 Simple DDEX provider - Yes
SQLite ADO.NET Provider included: 1.0.107.0
SQLite EF6 DbProvider in GAC - No
System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes
Database engine: (SQlite, SQL Compact, SQL Server, Postgres)
Visual Studio version: 15.7.3

**Comment by ErikEJ** [comment]
Please explain why you cannot target AnyCPU? 
Can you move your x64 dependencies to another project?

**Comment by jmoleary** [comment]
Engineering resources.  We make (and my .NET code uses) a 64-bit only C++ SDK that we access through C++/CLI.  We cannot isolate it.

**Comment by jmoleary** [comment]
If this (Any CPU or bust) is just the way it is, I understand and still appreciate your effort.  I just wanted to check

**Comment by ErikEJ** [comment]
You are unable to isolate your DbContext in a separate project??

Never give up, I will add the feature to generate SQL scripts to my dgml Nuget library!

**Comment by jmoleary** [comment]
My DbContext already is in a different project.  I can change the target for it right now if I want.  But then it makes bad things start happening with my tools, and all of the other third-party assemblies and DLLs I use.  It was a myriad of problems that I struggled with months ago when setting up the project and was only able to get running when I finally forced everything to 64 bits.  Hell even XAML Design View was having issues.

 

I do not doubt for a second that given enough time I could iron out out all of these issues.  It’s not like it’s some insurmountable technical problem.   The problem is I simply do not have any time to do that or anything else right now and am unlikely to have it for several months.    

 

I am a sole developer under a development schedule that frankly could use three people.   I can’t take a day or two off to work this stuff out unless it is critical path.  As cool as EF Power Tools seem to be making them work with my project is not critical path.

 

I would not have bothered with the report but I figured that this tool was something you would eventually want to make work for any sort of build, be it 32 bit, 64 bit or Any CPU.   However if “Any CPU” is the way it remains, that’s not a problem.   I can still get my job done.  I did not mean to waste your time.  Please, by all means close this issue.  There are more important things for you to work on I’m sure.  

 

I’ll just come back when I have time to work this all out.

**Comment by ErikEJ** [comment]
I have added a AsSqlScript extension method to my NuGet package here: https://www.nuget.org/packages/ErikEJ.EntityFrameworkCore.DgmlBuilder/2.1.1
