### ISSUE TITLE
Power tool not rename navigation property if foreign key column has similar name

### ISSUE THREAD

**Issue by merallisa** [ErikEJ/EFCorePowerTools#550]
Power tool not rename navigation property if foreign key column has similar name
`
efpt.renaming.json:
{
            "Name": "SourceOfTreatment",
            "NewName": "SourceOfTreatment"
 },
 {
            "Name": "SourceOfTreatmentNavigation",
            "NewName": "AL_ReferralSource"
 }
`
generated class:

        ....
        public long? SourceOfTreatment { get; set; }

        [ForeignKey(nameof(SourceOfTreatment))]
        [InverseProperty(nameof(AlReferralSource.AL_Project))]
        public virtual AlReferralSource SourceOfTreatmentNavigation { get; set; }
        ...

EF Core Power Tools version: last
Database engine: SQL Server,
Visual Studio version: 2019 Community

**Comment by ErikEJ** [comment]
The renaming feature does not apply to navigation names, as documented.
