### ISSUE TITLE
Enhancement : Reverse Engineer from an EDMX file?

### ISSUE THREAD

**Issue by omatrot** [ErikEJ/EFCorePowerTools#551]
I'm wondering if we could in the future reverse engineer from an existing edmx file ? 
Would it be difficult to port the code that existed in the initial EF Power tools ?
I may have some time to dedicate to this task in the near future.

**Comment by ErikEJ** [comment]
I think it could be quite difficult, as the current reverse engineering is based on a database model, not a conceptual edmx model... But interesting thought. 

Your task would be to create a class that can create a DatabaseModel from an edmx, have a look at the code that does this from a .dacpac. (that has been serialized into a TSqlModel)

**Comment by ErikEJ** [comment]
Maybe you could use this? https://archive.codeplex.com/?p=linqtoedmx

**Comment by omatrot** [comment]
All right, let me see what I can do.

**Comment by ErikEJ** [comment]
Perfect, ping me with any design questions.

**Comment by ErikEJ** [comment]
Found this - LINQ to EDMX looks vry old: https://github.com/robertmclaws/EDMXParsingSample/blob/master/src/EdmxParsingSample.Data/EdmxLoader.cs

**Comment by omatrot** [comment]
@ErikEJ Just to let you know that I've started the porting process of the old LinqToEdmx to [.NET Standard 2.1](https://github.com/omatrot/LinqToEdmx).

**Comment by ErikEJ** [comment]
Wauw!

**Comment by omatrot** [comment]
I've published the [Linq2Edmx](https://www.nuget.org/packages/linq2edmx/0.0.1-pre) and [Linq2xsd](https://www.nuget.org/packages/linq2xsd/0.0.1-pre) nugets packages.
Do you want me to create a branch corresponding to the issue in my forked repo to start the integration process?

**Comment by ErikEJ** [comment]
If you think it adds value, sure, it will mainly be an implementation of DatabaseModelFactory.

i suggest you start with the code generation parts, and verify by running the console app.

**Comment by omatrot** [comment]
I also have to say that I'm using Visual Studio 2019 for Mac. The EFCorePowerTools project is unrecognised in this environment. I'm open to some alternative guidelines. Thanks in advance.

**Comment by ErikEJ** [comment]
This is a Visual Studio project, but you could maybe run the code generation parts on Mac... 

The end result could be a package similar to the Nuget package for .dacpac support.

But being able to open the solution file is most likely a must, are you able to do that?

If not, we could take a Teams call and I can walk you through the moving parts?

**Comment by omatrot** [comment]
The solution file opens fine. VS complains that this project is an unknown solution item type.

**Comment by ErikEJ** [comment]
Yes, that is expected for the Vsix project, but you should be able to open the .net Core projects, and they are the important ones...

We are talking in the blind here, is my impression

**Comment by omatrot** [comment]
All the other projects are loading correctly ;)

**Comment by ErikEJ** [comment]
Ok, then you are good to proceed!

**Comment by omatrot** [comment]
Yep !

Correct me if I'm wrong but I think I should create two new projects:
 - ErikEJ.EntityFrameworkCore.5.Edmx
 - ErikEJ.EntityFrameworkCore.Edmx
To follow what has been done for Dacpac?

I'll let you validate the namespaces and project names though.

**Comment by ErikEJ** [comment]
Yes, that would be the final outcome.

**Comment by ErikEJ** [comment]
Hmmm... What provider will this target? 

The DatabaseModel is provider specific?

**Comment by omatrot** [comment]
No, it will be provider agnostic.

**Comment by ErikEJ** [comment]
Curious how that will pan out in real life... And runtime it will execute against some database, I presume??

**Comment by omatrot** [comment]
I think it will depends on what is missing in the Edmx file.

For instance, Index informations are not there, but we may optionally connect to the database to get them. Primary and foreign keys are there of course.

For me the main idea is to never create the database from the scaffolding data, just be able to work with generated context of an existing database from which one had generated an edmx in the past.

**Comment by ErikEJ** [comment]
Thanks for the explanation! Makes sense to me...

**Comment by omatrot** [comment]
Hi @ErikEJ 
Quick question just to clarify something: [Microsoft.EntityFrameworkCore.Scaffolding.Metadata.DatabaseModel](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.scaffolding.metadata.databasemodel?view=efcore-5.0) is about the storage part of the relational database? Is there an equivalent for the conceptual part? The EDMX contains both and the mapping between the two.

**Comment by ErikEJ** [comment]
@omatrot I assume it could be this one: https://github.com/dotnet/efcore/blob/main/src/EFCore.Relational/Metadata/IRelationalModel.cs

**Comment by omatrot** [comment]
I would provide both then, if that make sense to the tooling. That makes sense to me anyway.

**Comment by ErikEJ** [comment]
Tooling does not use the IRelationalModel, but feel free to expose it, we should consider publishing a NuGet package.

**Comment by omatrot** [comment]
I'm not done yet ;)
If I understand correctly, the tooling expose an IDatatabaseModel that is later processed by EF scaffolding to produce the entities, their configurations and the context?
The EDMX file already contains all that is needed to produce the entities, their configurations and the context.

**Comment by ErikEJ** [comment]
Correct, look at the .dacpac Databasefactory

**Comment by omatrot** [comment]
Hi @ErikEJ
I think I'm ready to prepare a pull request for this.
Stay tuned.
Thanks for your patience.

**Comment by ErikEJ** [comment]
Wauw - exciting!

**Comment by omatrot** [comment]
I may have spoken too fast...
I'm confused about what I've done around the IRelationalModel Interface. There seems to be no factory available to create instances of this interface. Could you double check to confirm? And may be provide an alternative?
Thanks in advance.

**Comment by ErikEJ** [comment]
I sincerely doubt there will be many consumers of the IRelationalModel - but do a PR so we can have a fact based discussion?

**Comment by omatrot** [comment]
PR opened.

**Comment by ErikEJ** [comment]
The PR is now merged, and you can test it by picking an EDMX file via the Select Data Source dialog.

Thanks for your patience!

**Comment by ErikEJ** [comment]
Could you describe this selling point of this feature in a sentence? I plan to tweet that it is now available in the latest daily build.

**Comment by omatrot** [comment]
I’ll do that.
I may be wrong but I suspect that you now allow to select an edmx, then process as usual to select what to reverse engineer ?
The edmx file already contains that information in the so called conceptual model.
We could bypass this step, if I provide you what you need.

Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Erik Ejlskov Jensen <notifications@github.com>
Envoyé : Thursday, February 25, 2021 6:17:36 PM
À : ErikEJ/EFCorePowerTools <EFCorePowerTools@noreply.github.com>
Cc : Olivier MATROT <omatrot@free.fr>; Mention <mention@noreply.github.com>
Objet : Re: [ErikEJ/EFCorePowerTools] Enhancement : Reverse Engineer from an EDMX file? (#551)


Could you describe this selling point of this feature in a sentence? I plan to tweet that it is now available in the latest daily build.

**Comment by ErikEJ** [comment]
Why don't you try it out?

**Comment by omatrot** [comment]
I've tried it out ;)
As I was saying, the 'Choose Database Object' step could be avoided completely or displayed as readonly because I can provide you with what the .edmx file contains in the conceptual model, which may contains excluded columns and custom renaming, and is not used so far.

Selling point:
Now you can leverage your existing/maintained .edmx files to scaffold EF Core entities and context.
