### ISSUE TITLE
Cannot reverse engineer multiple DBContexts in the same directory

### ISSUE THREAD

**Issue by janissimsons** [ErikEJ/EFCorePowerTools#554]
Tool deletes the first DbContext and replaces it with another when I run it again.

### Steps to reproduce
1. Generate entities in a separate directory, for example, ''Data\Products'' and ProductsDbContext in a common directory: "Data\Contexts".
2. Now run the tool again and generate for a different set of tables, place them in "Data\Customers" and CustomersDbContext in the same common directory: "Data\Contexts".

What happens: ProductsDbContext is deleted during the 2nd step and it is replaced by CustomersDbContext.
Previous entities are not touched - they generate correctly.

Further technical details
Version 2.4.217.0

SQLite ADO.NET Provider included: 1.0.109.0
SQLite EF6 DbProvider in GAC - No

System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes

Database engine: SQL Server

Visual Studio version: VS 2019, 16.7.7

**Comment by ErikEJ** [comment]
This is really not supported, but if you must do this, you can preserve previously generated files as described here: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#saving-options-and-running-the-second-time
