### ISSUE TITLE
Reverse Engineering: space in property in SP result class

### ISSUE THREAD

**Issue by tiomny** [ErikEJ/EFCorePowerTools#555]
Classes are generated with spaces in properties when stored procedure returns a dataset with columns containing space.

### Steps to reproduce
Source SP
```SQL
ALTER   PROCEDURE [CALCULATIONS].[GET_DATASET] 
AS SET
NOCOUNT ON
BEGIN
	SELECT
	id_results_log  "ID Results Log",
	sector "Sector"
FROM
	results.SOME_TABLE p
END
GO
```

Generated code
```C#

public partial class GET_DATASETResult
{
    public int ID Results Log { get; set; }
}
```

### Further technical details
EF Core Power Tools version: 2.5.270

Database engine: MS SQL Server 

Visual Studio version: Visual Studio 2019

**Comment by ErikEJ** [comment]
OMG !! Did not see this coming. what happens if you rename - can you get any results?

**Comment by tiomny** [comment]
Haven't tried that yet as I don't use mappers of such SPs yet.
I can test that for you if that's really needed.
BTW, renaming rules are not applied to these classes.

**Comment by ErikEJ** [comment]
I will test it - doubt it will work at all.

And renaming is not supported at all with stored procedure rev eng, that is correct

**Comment by ErikEJ** [comment]
This is not supported with EF Core, as the returned column name must match the C# property name when using FromSql. 
Workaround is to modify the stored procedure (or call via another procedure, which returns columns without spaces)

**Comment by tiomny** [comment]
It works perfectly when I use [Column] attribute in results class:
```C#
public partial class GET_DATASETResult
{
    [Column("ID Results Log")]
    public int ID_Results_Log { get; set; }
}
```

**Comment by ErikEJ** [comment]
Fixed in latest daily build, let me know if that solves your issue, and thanks for reporting this.

**Comment by tiomny** [comment]
Will you implement applying renaming rules to SP result classes?

**Comment by ErikEJ** [comment]
No current plans to do that, feel free to create an feature request.

**Comment by tiomny** [comment]
Generated properties are duplicating:
```C#
public partial class GET_DATASETResult
{
    [Column("ID Results Log")]
    public int ID_Results_Log { get; set; }
    [Column("ID Results Log")]
    public int ID_Results_Log { get; set; }
}
```

**Comment by ErikEJ** [comment]
Please create a new issue with a CREATE PROCEDURE statement.

**Comment by ErikEJ** [comment]
I am not able to reproduce with build .274

**Comment by tiomny** [comment]
Sorry - it is a duplicated column in SP itself.

**Comment by ErikEJ** [comment]
Maybe there is an issue with two identical names in the result set,?

**Comment by tiomny** [comment]
Yes there was - fixed that and reverse engineering worked like a charm.

**Comment by ErikEJ** [comment]
I mean, maybe the tools should uniquefy duplicate result set columns?

**Comment by tiomny** [comment]
That might be needed in some case - but not in mine :)
