### ISSUE TITLE
Autogenerated code is using methods not supported

### ISSUE THREAD

**Issue by thomasyde** [ErikEJ/EFCorePowerTools#556]
Describe what is not working as expected.
Generating code from SQL server 
![image](https://user-images.githubusercontent.com/3297418/98000899-4c549b80-1ded-11eb-8433-2df1ab69baf3.png)

I've added the Microsoft.EntityFrameworkCore.Relational (google was kind to suggest that) but that did not help.

### Further technical details
EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
Version 2.4.217.0

Database engine: (SQlite, SQL Compact, SQL Server, Postgres)
SQL server 2017

Visual Studio version: (e.g. Visual Studio 2017 15.7)
Microsoft Visual Studio Professional 2019
Version 16.7.4

**Comment by ErikEJ** [comment]
Are you mixing EF Core 5 code with 3.1 binaries, or vice versa?

**Comment by thomasyde** [comment]
No just basic EF 2.2.6 and just used the EFPT since it looks really good.

**Comment by ErikEJ** [comment]
2.x is no longer supported!

**Comment by ErikEJ** [comment]
I can offer a download with an older version that supports 2.2

**Comment by thomasyde** [comment]
Thanks Erik, I think I'll wait with that and see if I can upgrade to latest version instead. Thanks for the fast response. :)
