### ISSUE TITLE
Reverse engineering - Tables not mapped, tables names contains danish characters

### ISSUE THREAD

**Issue by mikaelbnielsen** [ErikEJ/EFCorePowerTools#557]
Hi Erik 

First of all, thanks for a nice tool. 

When i reverse engineer a database, some tables are not mapped. 

After a closer look, i suspect the problem is the tables contains an letter 'æ' in the name

Do you have an workaround on this ?

Does the power tool provide an output log for helping identifying the issue ?

Thank you in advance

Regards
Mikael

### Further technical details
EF Core Power Tools version: 2.4.217.0

Database engine: SQL Server 14.0.2027.2

Visual Studio version: Visual Studio 2019 16.7.7

**Comment by ErikEJ** [comment]
Please share a create table script for the unmapped table.

Something is causing it to be excluded, and therefore no errors are logged.

**Comment by mikaelbnielsen** [comment]
Database and table sql: 
CREATE DATABASE [testdb]
GO

create schema MySchema
GO

CREATE TABLE [MySchema].[MinÆndring](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FK_StatusTypeId] [int] NOT NULL
 CONSTRAINT [PK_MinÆndring] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO

The generated context

// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace MyNameSpace.Models2
{
    public partial class MyContext : DbContext
    {
        public MyContext()
        {
        }

        public MyContext(DbContextOptions<MyContext> options)
            : base(options)
        {
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}


How to reproduce

![2020-11-04 09_44_30-Generate EF Core Model in Project repository](https://user-images.githubusercontent.com/7123634/98089801-8cfef400-1e83-11eb-9943-91a83767b98f.png)
![2020-11-04 09_46_47-Repository - Microsoft Visual Studio](https://user-images.githubusercontent.com/7123634/98089804-8d978a80-1e83-11eb-8dc8-657b0a654066.png)
![2020-11-04 09_20_10-Choose Database Connection](https://user-images.githubusercontent.com/7123634/98089807-8d978a80-1e83-11eb-874e-7f36c571f994.png)
![2020-11-04 09_43_18-Select Tables to Script](https://user-images.githubusercontent.com/7123634/98089808-8d978a80-1e83-11eb-8e9b-ebdebc82f351.png)


It looks like the UI does not support the danish character

**Comment by ErikEJ** [comment]
Are you generating from a live database or .dacpac?

**Comment by mikaelbnielsen** [comment]
It from a live database.



Med venlig hilsen Mikael Braad Nielsen Bakkevej 2, Ølsted  8723 Løsning Tlf: 25303467  

    Den onsdag den 4. november 2020 09.58.45 CET skrev Erik Ejlskov Jensen <notifications@github.com>:  
 
 


Are you generating from a live database or .dacpac?

**Comment by ErikEJ** [comment]
Unable to reproduce,  works fine on my DB :smile: 

What is your database collation? Mine is: SQL_Latin1_General_CP1_CI_AS

**Comment by mikaelbnielsen** [comment]
Hopefully it is just setting then ;-)

I am using Danish_Norwegian_CI_AS.

I have just tried SQL_Latin1_General_CP1_CI_AS, but with the same result.

![2020-11-04 13_04_41-Select Tables to Script](https://user-images.githubusercontent.com/7123634/98110038-cbee7300-1e9e-11eb-8dd7-9868cdf2f303.png)
![2020-11-04 13_06_58-Database Properties - testdb2](https://user-images.githubusercontent.com/7123634/98110039-cc870980-1e9e-11eb-96a1-c8352c84f1d6.png)

All my settings is set to danish, and the sql server is running on the same local computer

**Comment by ErikEJ** [comment]
Please try to run (from %temp% folder)

    efreveng.exe 3 "Data Source=(local);Initial Catalog=MyDatabase;Integrated Security=true" 

and share the output - it could be an issue with console output encoding. 

(https://stackoverflow.com/questions/2062875/show-utf-8-characters-in-console )

**Comment by ErikEJ** [comment]
Hi, I have attempted a fix in the latest daily build: https://github.com/ErikEJ/EFCorePowerTools/wiki/Release-notes

**Comment by mikaelbnielsen** [comment]
Here is the out for both databases with different collations

![2020-11-04 14_17_53-C__WINDOWS_system32_cmd exe](https://user-images.githubusercontent.com/7123634/98116716-f6ddc480-1ea8-11eb-925b-f349b6d996ab.png)

I will go test you daily build right away.

**Comment by mikaelbnielsen** [comment]
Version 2.5.272.0

SQLite ADO.NET Provider included: 1.0.109.0
SQLite EF6 DbProvider in GAC - No

System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes

No, the daily build did not solve the problem.

![2020-11-04 14_42_15-Window](https://user-images.githubusercontent.com/7123634/98118955-3eb21b00-1eac-11eb-8b3e-44b0e9e9e496.png)
![2020-11-04 14_43_02-Window](https://user-images.githubusercontent.com/7123634/98118958-3f4ab180-1eac-11eb-9c0f-93b92ab50d09.png)

**Comment by ErikEJ** [comment]
But the encoding made a difference, though!

what is your default codepage - type:

  chcp 

from a cmd prompt

**Comment by ErikEJ** [comment]
I have just updated the daily build, maybe I set the output encoding in the wrong end of the pipeline.

**Comment by mikaelbnielsen** [comment]
Hi again

Yes, it did change, my code page is 850

![2020-11-04 15_33_31-Window](https://user-images.githubusercontent.com/7123634/98124236-36111300-1eb3-11eb-94df-439e0978c883.png)

I will try installing the new build.

**Comment by ErikEJ** [comment]
Thanks, I can now try to repro with that code page set.

**Comment by mikaelbnielsen** [comment]
Version 2.5.273.0

SQLite ADO.NET Provider included: 1.0.109.0
SQLite EF6 DbProvider in GAC - No

System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes

Hi again

Now it looks much better, the table is now mapped correct into the class 

But now there is some C#  8.0 code in the generated code
![2020-11-04 15_41_57-Window](https://user-images.githubusercontent.com/7123634/98125528-e03d6a80-1eb4-11eb-8a2e-b81bfec687cf.png)

I am using entityframework core in a .net standard 2.0 project.

**Comment by ErikEJ** [comment]
What prevents you from using C# 8?

**Comment by mikaelbnielsen** [comment]
I am using the .net standard repository project in some .net 4.8 projects, so i can't change the version from 2.0 to 2.1.

**Comment by ErikEJ** [comment]
There probably something I missed - so C# 8 does not work with .NET Standard 2.0 projects??

**Comment by mikaelbnielsen** [comment]
Hi again

.net standard 2.0 supports c# 7.3
.net standard 2.1 supports c# 8.0

Reference
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version

.net standard 2.0 project can be used in .net framework 4.6.1.
.net standard 2.1 project can not be used in .net framework projects.

Reference
https://docs.microsoft.com/en-us/dotnet/standard/net-standard

We are on the way to migrate to the new versions, but there is a lot of work ahead of us, so for now we are locked with the 4.8 projects.

**Comment by ErikEJ** [comment]
I will fix this, thanks for the info!

**Comment by ErikEJ** [comment]
Fixet i seneste build - tak for hjælpen!

**Comment by mikaelbnielsen** [comment]
Selv tak og tak for hurtigt respons.
