### ISSUE TITLE
Proposal: Can we have an Identical Tool that is not bound to EF?

### ISSUE THREAD

**Issue by mikependon** [ErikEJ/EFCorePowerTools#558]
Hi @ErikEJ , hope your day went well. The tools you developed is very awesome and thank you for this. It is a great help to the community.

You know, I am also an OSS contributor and is maintaining a Micro-ORM that is open for .NET Community and such tool is an alternative to EF as we speak. Though, I am also thinking to build the similar tools you had created for the EF Core, but it seems appropriate to just instead tap you and collaborate with you the desired tools we are trying to build.

It is also an option to combine the knowledge to develop such tools.

### Proposal

We would like to propose if you can create a tool that is dedicated to an ORM that is of micro-ORM kind. Such tool should address the case if the .NET community uses the Dapper or RepoDB ORM as an alternative to EF. We saw that there is a lot of users who will gonna use such tool. In the case of Dapper, see the statistics of the downloads [here](https://nugettrends.com/packages?months=12&ids=Dapper). This is a testament that the .NET community has a lot of use-case outside the coverage of EF itself.

Therefore, I am personally thinking that, it is good if YOU can cover this well.

### Disclaimer

The current tool you had develop can also address the use-case, but the end-user needs to tweak the template by using the handle bars and simply eliminating all the EF related stuffs.

### Benefits

It much easier and direct to the end-users if the tool is not bound to EF, in the case of users that are using the other ORM. The tool you developed has the code base that is well tested and might be easy to port to a new Project/Solution and create such new thing - with a different target users. We can leverage on that maturity and well-tested functionality by the community.

### How Should It Be?

**To start with:**

There should be an additional context menu like below.

PowerTools -> Generate Schema/Reverse Engineer

Keeping it as simple as possible, you can just eliminate all the `DbContext` related thing.

![image](https://user-images.githubusercontent.com/591015/98126056-740f3680-1eb5-11eb-9f6b-91d81966c3f4.png)

**Connection Screen:**

Just an enhancement, not really needed. There should be remove button on this page.

![image](https://user-images.githubusercontent.com/591015/98128362-1e885900-1eb8-11eb-81bb-5963ee0b2c9f.png)

**Selection Screen:**

It is good if we can as well consider the columns?

![image](https://user-images.githubusercontent.com/591015/98127875-7e323480-1eb7-11eb-8f1d-e146f3506186.png)

**Generate Screen:**

In the generate screen, only the following is present.

- Namespace
- Entity Types
- Sub-Namespaces
- What to Generate (EntityTypes = Table, Views)
     - It is also good if there is an option to select the columns to generate per table (only if needed)
- Data annotation attributes
- Connection string

![image](https://user-images.githubusercontent.com/591015/98128004-a5890180-1eb7-11eb-90b7-58a04468ad2b.png)

**Note:** The relationship must also be an option, though this can be done via template as well. But it is really good if we can control it in UI.

**Advance Screen:**

The following should only be present.

- Map spatial types
- Map Noda Time types

![image](https://user-images.githubusercontent.com/591015/98127174-af5e3500-1eb6-11eb-97dc-f88bdf885aa0.png)

**When OK is clicked:**

The following folders will be created.

- EntityType

![image](https://user-images.githubusercontent.com/591015/98127349-e3395a80-1eb6-11eb-865a-69dc21dc9685.png)

All of the the DB Contexts related thing will be eliminated on the generation.

**Comment by ErikEJ** [comment]
Just some thoughts:

1: Maybe just add an additional menu item, to keep it a single codebase:

Reverse Engineer POCO (Dapper, RepoDB etc.)

2: Connection string - not needed, as this is generated in the DbContext.

3: Removing stuff from Server Explorer is .... complicated.

**Comment by mikependon** [comment]
> 1: Maybe just add an additional menu item, to keep it a single codebase: Reverse Engineer POCO (Dapper, RepoDB etc.)

This would do, TBH, for as long it can simplify the way we generate the POCO classes and/or needed columns for Micro-ORMs without tweaking the template behind handle-bars. Remember, when working with micro-ORM, you do not need all the columns most of the time (you only manipulate the needed columns), but we/you can always default it to "all-columns".

I also agree with your comment in relation to the project/solution single-codebase, I can relate how difficult and tedious it is maintaining a multiple projects/solutions. I would say, if this proposal will be accepted by you, then it is up to you then, to the best case as long you are convenient with it.

Installing your tools on behalf of other ORM even with EF prefix is not a problem, it also solves the case of "Hybrid Solution" in which some use-cases are needing to combine the EF with micro-ORM (i.e. Dapper, RepoDB, etc).

> 2: Connection string - not needed, as this is generated in the DbContext.

Yeah, you're correct, I missed this actually. And even we are using the Repository pattern, we tend to use DI here. So this inclusion request is invalid.

**Comment by ErikEJ** [comment]
Can you share the modifications you do to the HandleBars templates?

**Comment by mikependon** [comment]
Sure, below are the modified templates, and it is running as expected.

**Properties.hbs**

```
{{#each properties}}
{{#if property-comment}}
{{spaces 8}}/// <summary>
{{spaces 8}}/// {{property-comment}}
{{spaces 8}}/// </summary>
{{/if}}
{{#each property-annotations}}
{{spaces 8}}{{{property-annotation}}}
{{/each}}
{{spaces 8}}public {{property-type}} {{property-name}} { get; set; }{{#if nullable-reference-types }}{{#unless property-isnullable}} = default!;{{/unless}}{{/if}}
{{/each}}
{{#if nav-properties}}
{{/if}}
```

**Contructor.hbs**

```
{{#if lines}}
{{/if}}
```

**Comment by ErikEJ** [comment]
Would those modifications apply to both Dapper and Repo?

**Comment by mikependon** [comment]
Yes, it would work I am pretty sure. But it would be nice if we can also filter the columns to be provisioned on the Entity Types during the 'Reverse Engineer'.

**Comment by ErikEJ** [comment]
Yes, I understand you column filter request, but it is quite complex to fulfill.

**Comment by mikependon** [comment]
No worries of eliminating our request of column filtering. For as long we have the tools like this that could generate the models, it is much easier to just simply delete the unnecessary columns from the models, than writing everything from scratch 😉

**Comment by ErikEJ** [comment]
Latest daily allows you to remove columns.

**Comment by mikependon** [comment]
@ErikEJ - cool updates as I just tested it. I liked the fact that you can search from it as well. Thanks!

**Comment by mikependon** [comment]
One thing that I notice, the unstructured table names seems to have been generated wrongly.

![image](https://user-images.githubusercontent.com/591015/101545089-0324d800-39a7-11eb-8733-7062830b8b57.png)

Generated models.

```csharp
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace RawSqlExecutionForEnum.Models.Models
{
    public partial class DottedTable
    {
        public long Id { get; set; }
        public Guid SessionId { get; set; }
        public int? ColumnInt { get; set; }
        public string ColumnNvarChar { get; set; }
    }
}
```

I would expect that the class is annotated with the `Table` attribute with vaue `Dotted.Table`, like `[Table("Dotted.Table", schema = "dbo")]`, or something?

Please do let me know if I need to report it separately.

**Comment by ErikEJ** [comment]
@mikependon Pls. create a seperate issue, as this has no relevance here.

**Comment by ErikEJ** [comment]
@mikependon For the Generate screen, could you clarify what is actually needed versus what should simply be set to default values - maybe you can draw/strike over on top of the screenshot.

It is not entirely clear to me at the moment.

**Comment by ErikEJ** [comment]
Ping?

**Comment by mikependon** [comment]
@ErikEJ - apology, but I really overlooked this due to some thing on my OSS. In relation to the Generate Screen, the updates you made to the tool seems to have address our needs, to be honest. Though some small adjustment is needed, but that is something that we can live.

Would you be able to give more time to explore the tools? I will definitely give more updates (hopefully) here soon (if there are).

**Comment by ErikEJ** [comment]
Thats great news, I also really enjoy the flexibility the new dialog gives.

**Comment by ErikEJ** [comment]
@mikependon If I add an option to generate entity classes without constructor and navigations, would that fulfill your needs?

**Comment by mikependon** [comment]
@ErikEJ - we can already do the same if we are just to modify the Handlebars customization. But, it is a bit tedious as first, we need to generate the models with default settings, through this, the HBS will be created. Then, we will modify these HBS customizations, delete the models and regenerate it again based on the newly updated customizations.

By having an option to eliminate the headers is a good decision for this TBH, so we will never do this tedious process moving forward. Other than that, your latest update with the Field selections are seems to be enough.

If you however enable the option to exclude the ctors, then I guess that would fix this request in general.

**Comment by ErikEJ** [comment]
@mikependon What about the Navigation properties?
I was thinking about adding an option called: Plain POCO, that would generate entities without constructor and navigations?

Or is it better to have two options:
- Exclude entity constructors
- Exclude entity navigations 

@sm15455 #692 is related to this, I guess?

**Comment by mikependon** [comment]
@ErikEJ - it is not occurring a problem, but that's being said, I would agree to that as well to make it as an option for easy generation. Thanks a lot 🚀 🚀

**Comment by sm15455** [comment]
> @sm15455 #692 is related to this, I guess?

Yes. Waiting for the end of the month to start working on that.

**Comment by ErikEJ** [comment]
@sm15455 2 options then? ( I plan to do this very soon) ?

**Comment by sm15455** [comment]
I investigated ctor removal, didn't investigate navigation properties. But I can take a look at that too.

**Comment by ErikEJ** [comment]
I will implement both, and add two options for now.

**Comment by sm15455** [comment]
As far as I remember, to remove ctor we had to inherit from CSharpEntityTypeGenerator and override GenerateConstructor method. 
HTH

**Comment by ErikEJ** [comment]
With the changes coming in  #692 this seems to be no longer needed
