### ISSUE TITLE
System.ArgumentException: Only .NET Core 2.2 and 3.0, and 3.1 are supported

### ISSUE THREAD

**Issue by chassq** [ErikEJ/EFCorePowerTools#559]
Using EF Core PT to reverse engineer and create a diagram for our Database. Seems to work fine so far but when we try to create a diagram we get teh following error in the Output window.

```
System.ArgumentException: Only .NET Core 2.2 and 3.0, and 3.1 are supported
   at EFCorePowerTools.Handlers.ProcessLauncher..ctor(Project project) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ProcessLauncher.cs:line 23
   at EFCorePowerTools.Handlers.ModelAnalyzerHandler.Generate(String outputPath, Project project, GenerationType generationType) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ModelAnalyzerHandler.cs:line 67
```
Did not know if this is a known issue or not. Here are our project references.

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EntityFrameworkCore.Scaffolding.Handlebars" Version="5.0.0-rc.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="5.0.0-rc.2.20475.6">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.0-rc.2.20475.6" />
  </ItemGroup>

</Project>
```

### Steps to reproduce
Create a Class file with a TFM of net5.0
Add packages above
Install EF Core Power Tools
Run reverse engineer
Try to create a Diagram

### Further technical details

Database engine: SQL Azure

Microsoft Visual Studio Enterprise 2019 Preview
Version 16.8.0 Preview 6.0
VisualStudio.16.Preview/16.8.0-pre.6.0+30626.31
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Enterprise

Visual C++ 2019   00435-60000-00000-AA196
Microsoft Visual C++ 2019

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   16.8.548.22527
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2051307+8b3a790c543a3ce99e92c63a4769988a6a95eddf
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.8.548.22527
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.8.548.22527
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.6.2000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.8.548.22527
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.2000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

Bundler & Minifier   2.8.396
Adds support for bundling and minifying JavaScript, CSS and HTML files in any project.

C# Tools   3.8.0-5.20519.18+4c195c3ac1974edcefa76774d7a59a2350ec55fa
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Entity Framework Core Power Tools   2.4
Adds useful design-time EF Core DbContext features to the Visual Studio Solution Explorer context menu. 

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

GhostDoc   20.2.20270.0
Generate XML Comments from your code, maintain clean and up-to-date documentation, produce help documentation in multiple formats, use intelligent source code Spell Checker in Visual Studio.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure HDInsight Azure Node   2.6.2000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.6.2000.0
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   16.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.6.2000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30924.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   5.8.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62010.06180
Microsoft SQL Server Data Tools

SQLite & SQL Server Compact Toolbox   4.7
SQLite & SQL Server Compact Toolbox adds scripting, import, export, rename, query execution and much more to SQL Server Compact & SQLite Data Connections.

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.21016.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.8.0-5.20519.18+4c195c3ac1974edcefa76774d7a59a2350ec55fa
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.8.0-beta.20507.4+da6be68280c89131cdba2045525b80890401defd
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Kubernetes   1.0
Visual Studio Tools for Kubernetes

Web Compiler   1.12.394
Compiler for LESS, Sass and CoffeeScript files

**Comment by ErikEJ** [comment]
Have you tried the latest daily build?

**Comment by ErikEJ** [comment]
Ping?

**Comment by ErikEJ** [comment]
Verified that latest daily build works as expected.

**Comment by chassq** [comment]
I just ran it with teh latest build and got this:

1>------ Build started: Project: OneMarket.Srv.Dal.Sql, Configuration: Debug Any CPU ------
1>You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
1>OneMarket.Srv.Dal.Sql -> C:\Users\charl\source\repos\OneWaterMarketplace\OneMarket.Srv.Dal.Sql\bin\Debug\net5.0\OneMarket.Srv.Dal.Sql.dll
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

System.ArgumentException: Error:
Microsoft.EntityFrameworkCore.Design.OperationException: Unable to create an object of type 'OmDevSqldbAppContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728
 ---> System.InvalidOperationException: Unable to resolve service for type 'Microsoft.EntityFrameworkCore.DbContextOptions`1[OneMarket.Srv.Dal.Sql.Context.OmDevSqldbAppContext]' while attempting to activate 'OneMarket.Srv.Dal.Sql.Context.OmDevSqldbAppContext'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetServiceOrCreateInstance(IServiceProvider provider, Type type)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass13_4.<FindContextTypes>b__13()
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass13_4.<FindContextTypes>b__13()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at ReverseEngineer20.EfCoreModelBuilder.BuildResult(String outputPath, Boolean generateDdl) in C:\Code\EFCorePowerTools\src\GUI\efpt\EFCoreModelBuilder.cs:line 39
   at ReverseEngineer20.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efpt\Program.cs:line 42

Parameter name: processResult
   at EFCorePowerTools.Handlers.ModelAnalyzerHandler.<GenerateAsync>d__2.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ModelAnalyzerHandler.cs:line 78

**Comment by chassq** [comment]
Also seeing an issue whereby if I exclude the Connection string I am getting this code int eh context file.

```
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
{
if (!optionsBuilder.IsConfigured)
{
optionsBuilder;
 }
 }
```

**Comment by ErikEJ** [comment]
Please avoid mixing unrelated issues.

Look at the link in the error message for the diagram issue, and also refer to the wiki.

**Comment by ErikEJ** [comment]
For the OnConfiguring issue, please provide repro steps.

**Comment by chassq** [comment]
Ok well I guess the daily build addressed the original issue above. Diagrams are a separate issue we will add after looking at info in wiki.

The repro steps for OnConfiguring are as follows:
1. Choose ReverseEngineer from power tools context menu
2. Select the database connection and select Use EF Core 5 (preview).
3. See setting selections below. Have removed tables for brevity.
```
{
   "ContextClassName": "AppDbContext",
   "ContextNamespace": null,
   "DefaultDacpacSchema": null,
   "FilterSchemas": false,
   "IncludeConnectionString": false,
   "ModelNamespace": null,
   "OutputContextPath": "Context",
   "OutputPath": "Model",
   "ProjectRootNamespace": "Om.Srv.Dal.Sql",
   "Schemas": null,
   "SelectedHandlebarsLanguage": 0,
   "SelectedToBeGenerated": 0,
   "Tables": [],
   "UseDatabaseNames": true,
   "UseDbContextSplitting": true,
   "UseFluentApiOnly": true,
   "UseHandleBars": true,
   "UseInflector": false,
   "UseLegacyPluralizer": false,
   "UseNodaTime": false,
   "UseSpatial": false
}

```
Hope that helps.

**Comment by ErikEJ** [comment]
Perfect, thanks, I will investigate

**Comment by ErikEJ** [comment]
@chassq I am unable to repro, maybe you have made some changes to the Handlebars templates that breaks the Entity configuration splitter? Make sure you are using the latest EF Core 5 handlebars templates (rename the codetemplates folder temporarily)

**Comment by ErikEJ** [comment]
Yes, confirmed, this code fragment comes from the Handlebars template - workaround is to remove the fragment and references to it.

**Comment by ErikEJ** [comment]
Actually look like a bug in HandleBars (or my usage of it), in terms of respecting the no-onconfiguring option. Maybe @tonysneed can help me ?

**Comment by ErikEJ** [comment]
Looks like you were using 3.1 Handlebars templates - please rename or delete the CodeTemplates folder.

**Comment by chassq** [comment]
That worked. Thanks Erik!

**Comment by ErikEJ** [comment]
Great, thanks for the heads up.
