### ISSUE TITLE
When a table has an index, the scaffolding generates an erroneous statement in modelbuilder

### ISSUE THREAD

**Issue by ghisbo** [ErikEJ/EFCorePowerTools#565]
Describe what is not working as expected.

### Steps to reproduce
SQL Table

CREATE TABLE [dbo].[Vat] (
    [Id]             BIGINT     NOT NULL,
    [VatNumber]      CHAR (40)  NOT NULL,
    [CountryCode]    CHAR (10)  NULL,
    [Number]         NCHAR (30) NULL,
    [ValidationDate] DATE       NULL,
    [IsCompanyHash]  BIT        NOT NULL,
    CONSTRAINT [PK_Vat] PRIMARY KEY CLUSTERED ([Id] ASC)
);

GO
CREATE NONCLUSTERED INDEX [IX_VatNumber]
    ON [dbo].[Vat]([VatNumber] ASC);

#######
Correctly generated via PM, Scaffolding command 
 
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Vat>(entity =>
            {
                entity.HasIndex(e => e.VatNumber)
                    .HasName("IX_VatNumber");

###
code generated via EFCorePowerTools

     protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Vat>(entity =>
            {
                entity.ToTable("Vat");

                entity.HasIndex(e => e.VatNumber, "IX_VatNumber");

This produces the following error 
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1660	Cannot convert lambda expression to type 'string' because it is not a delegate type	t

Include a complete description that I can redo to reproduce the issue.

### Further technical details
EF Core Power Tools version: 2.1.2170

Database engine: , SQL Server

Visual Studio version: 2019 16.8 prev 6

**Comment by ErikEJ** [comment]
You are mixing EF Core 5 scaffolding with the 3.1 runtime.
