### ISSUE TITLE
Option to Generate DbContent and Entities in Different Locations

### ISSUE THREAD

**Issue by tonysneed** [ErikEJ/EFCorePowerTools#57]
As of v2.1 EF Core tooling has a `--context-dir` option which allows generation of DbContext and Entities in different locations.  It would be nice to have both `--output-dir` and `--context-dir` options via the UI for EFC PT.

**Comment by ErikEJ** [comment]
Could you elaborate a bit?

Are these project folders? EF Core PT addresses a single project..

How would this look in the UI (There already is a "Project Path" property (text box with folder name)

**Comment by tonysneed** [comment]
Yes, so instead of a single text box for "Project Path", you would have two text boxes: "DbContext Path" and "Entities Path".  You would want to disable one or the other if they select the option to generate DbContext only or Entities only.

The user could specify just a folder name for either of these, which would indicate folders within the current project, for example, Context and Models.

Or the user could enter a relative path for the Entities Path, pointing to another project within the same solution, for example, ..\MyApp.Entities.  In that case, the DbContext Path would default to "." for the local project.  The beauty of this is that entities can be output to a NET Standard library, which can be referenced by a project that has repository interfaces and has no dependency on EF Core or any other persistence stack.

See this [repo](https://github.com/tonysneed/Demo.EFCorePowerTools.DbContextError), which I repurposed to demonstrate the kind of project structure which separates entities from context.

**Comment by ErikEJ** [comment]
This workflow is already supported, just requires you to run the tool twice...

**Comment by tonysneed** [comment]
Thanks, I’m going to try this out.

**Comment by tonysneed** [comment]
I think running the reverse engineer process twice is good in terms of workflow (although the EF team disagrees).  But I did run into some issues when trying this.

I entered a relative path to the Entities project to generate entities only.

![gen-entities](https://user-images.githubusercontent.com/2836367/41674267-1b3d0e42-7485-11e8-9eb3-9da605b8c408.png)

But then I noticed that the DbContext class is still generated in the target project, even though I selected Entities Only in the wizard.

![entities-project](https://user-images.githubusercontent.com/2836367/41674322-48efec88-7485-11e8-8503-d484db8d0c32.png)

More significantly, however, the namespace for the generated entities includes the path I specified.

![gen-namespace](https://user-images.githubusercontent.com/2836367/41674365-631c3238-7485-11e8-99ea-13afa9bf264a.png)

I did notice an error in the output window.

```
Microsoft.Assumes+InternalErrorException: Did not find new element in the hierarchy for item "C:\Users\Tony\Source\repos\ClassLibrary1\ClassLibrary1.Data\../ClassLibrary1.Entities\Category.cs". The item would have been added with type "Compile". The project item schema service knows about this item type. The item does not exist in the project file.
   at Microsoft.Assumes.Fail(String message, Boolean showAssert)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProjectItems.<EvaluateAddResultAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProjectItems.<AddItemAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProjectItems.<>c__DisplayClass4_0.<<AddFromFile>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
   at Microsoft.VisualStudio.ProjectSystem.ProjectMultiThreadedService.ExecuteSynchronously[T](Func`1 asyncAction)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProjectItems.AddFromFile(String fileName)
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__2.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 159
```

**Comment by ErikEJ** [comment]
I do not support this scenario...

**Comment by tonysneed** [comment]
> This workflow is already supported, just requires you to run the tool twice...

What did you mean?

**Comment by ErikEJ** [comment]
I meant;

In project A, launch Power Tool, Rev Eng, select tables, select to only generate DbContext.

In project B, launch Power Tool, Rev Eng, select tables, select to only generate Entity Types.

Done

(I need the project reference, in particular for .NET Framework projects, in order to add the files.)

**Comment by tonysneed** [comment]
So the main limitation is that both projects need a) to be .NET Core or full .NET  (vs NET Standard) and b) each project needs to reference EF Core.

The EF Core CLI doesn’t have this limitation. It would be nice if generating to different projects could be done with file based projects.

**Comment by ErikEJ** [comment]
>> So the main limitation is that both projects need a) to be .NET Core or full .NET  (vs NET Standard) and b) each project needs to reference EF Core.

No, that's not the case, neither is required. What makes you think it is?

**Comment by tonysneed** [comment]
I see, it looks like the EFC PT has different requirements than the EF Core CLI, which requires .NET Core vs NET Standard. Reverse engineering with the CLI from a .NET Standard class library produces the following message:

```
Startup project 'ClassLibrary1.Entities.csproj' targets framework '.NETStandard'. There is no runtime associated with this framework, and projects targeting it cannot be executed directly. To use the Entity Framework Core .NET Command-line Tools with this project, add an executable project targeting .NET Core or .NET Framework that references this project, and set it as the startup project using --startup-project; or, update this project to cross-target .NET Core or .NET Framework.
```

If I change the project type from `netstandard2.0` to `netcoreapp2.1` and reverse engineer, the EF Core CLI still requires both Microsoft.EntityFrameworkCore.SqlServer and `Microsoft.EntityFrameworkCore.SqlServer` packages.  So it's a pleasant surprise that EFC PT does not have this requirement.

I assumed that EFC PT would also have these requirements, but I'm happy to discover that it does not.  The only misleading message is a dialog that appears after reverse engineering Entities Only:

![install-ef-provider](https://user-images.githubusercontent.com/2836367/41689063-738173de-74b4-11e8-9480-d05b8cd448c9.png)

Obviously the Entities project will build fine without installing the provider package.

**Comment by ErikEJ** [comment]
Yes, these are some of the main advantages of EFC PT for rev eng:

EF Core allows you to use the Scaffold-DbContext or the dotnet ef dbcontext scaffold commands to reverse engineer a database and create entity and DbContext classes for your database tables.
This approach has a number of disadvantages, however:
- You must add design time components to your project, that you can easily end up deploying to production, thus increasing your app footprint (size) for no reason
- It is not easy to specify which tables to scaffold, and there is no easy way to generate only entity (POCO) or DbContext classes.
In addition, the reverse engineering offered in EF Core Power Tools has a number of additional options, 
not available from the command line.

Only a fixed subset of database providers are supported: SQL Server, SQLite, SQL Compact, Npgsql

Regarding the message, yes, if only Entity Types are generated, it is not required.

**Comment by tonysneed** [comment]
Thanks @ErikEJ for the clear explanation and for the fix -- and bravo for your improvements over the CLI tooling.  I had a discussion with the EF Core team about allowing for generation of the entities and context independently, but they pushed back that both needed to be generated at the same time.  I can see how that might avoid getting out of sync, but I agree with your approach that the workflow of running the generator twice is much more intuitive than specifying the current directory for the context and a relative directory for the entities.
