### ISSUE TITLE
How do I get the option to Reverse Engineer Stored Procedures?

### ISSUE THREAD

**Issue by chriswitt75** [ErikEJ/EFCorePowerTools#573]
I have a .NET Core Web application, where I am using a Database Project to define my SQL Server database.  Then I have a DataAccess project that I use EFCPT to reverse engineer to.  Even though my database has stored procedures, I cannot get EFCPT to generate any code for them.  The table entities and db context are generated just fine, but no stored procedure code at all is generated.  

### Steps to reproduce
1. Create a simple solution in VS with only a SQL Server Database project, and a class library to hold the context/models.  
2. Add a simple table, and a simple stored procedure to the database project.  
3. Build the db project. 
4. Right-click on the class library project, select EFCPT, Reverse Engineer.
5. Under "Choose SQL Server Database Project (.dacpac)" select the db project.  
6. Check "Use EF Core 5" and click "OK"
7. In the "Select Objects to Script" dialog, select all the tables (I think SP's are supposed to show up here, but I see none) and click "OK"
8. The following prompt does not seem to affect this issue; I looked at all the settings on the dialog, as well as "Advanced" and nothing mentions "stored procedures".  
9. Click "OK"

The model and context are generated into the class library, but no mention of the stored procedure is in any of the code.  I feel like I'm missing something, but I can't find anything more about it.  

### Further technical details
EF Core Power Tools version: 2.5.277.0
Database engine: SQL Server, but using a Database Project (.dacpac file) to do the reverse engineer
Visual Studio version: Visual Studio 2019 16.7.7
Microsoft.EntityFrameworkCore.SqlServer version: 5.0.0

**Comment by ErikEJ** [comment]
This is not supported, as it is not possible to get any information about the shape of the result of the stored procedure from model.xml inside the .dacpac.

I will update the wiki post to clarify that you must reverse engineer form a live database to get stored procedure scaffolding.

**Comment by ErikEJ** [comment]
@chriswitt75 I discovered a way to do this, coming soon, see #659

**Comment by ErikEJ** [comment]
@chriswitt75 Implemented in latest daily build
