### ISSUE TITLE
'Keyword not supported: 'multiple active result sets'

### ISSUE THREAD

**Issue by PA256** [ErikEJ/EFCorePowerTools#576]
After the last reverse engineering the key word 'multiple active result sets' was added to the connection string in "Context.cs". This was never added before in previous reverse engineerings. This leads to the error 'Keyword not supported: 'multiple active result sets'.
Can i disable the key word being added? Otherwise i would have to remove it manually with each reverse engineering.

EF Core Power Tools version: 2.5.277
Database engine: (MS SQL Server)
Visual Studio version: (Visual Studio 2019 16.7.5)

**Comment by ErikEJ** [comment]
I dont see that, could you please provide detailed repro steps?

Also, it is better to not include the connection string in the generated code.

**Comment by ErikEJ** [comment]
Any updates?

**Comment by PA256** [comment]
Hello Erik, yes you are right. That was a beginner mistake of mine. I moved the connection string outside of the generated code.
Thanks
