### ISSUE TITLE
Feature request: provide CancellationToken to SP mappers

### ISSUE THREAD

**Issue by tiomny** [ErikEJ/EFCorePowerTools#577]
ExecuteSqlRawAsync has the overloaded implementation:
```C#
public static async Task<int> ExecuteSqlRawAsync(
    [NotNull] this DatabaseFacade databaseFacade,
    [NotNull] string sql,
    [NotNull] IEnumerable<object> parameters,
    CancellationToken cancellationToken = default)
```
Is that possible to create mapping methods with CancellationToken as well? Method signature might be the following:
```C#
public async Task<int> LONG_RUNNING_SP(int? param1, int? param2, 
    OutputParameter<int> returnValue = null, 
    CancellationToken cancellationToken = default)
```

**Comment by ErikEJ** [comment]
Why is that important (excuse my ignorance) ?

**Comment by tiomny** [comment]
SP may run slowly/implement complicated business logic/get a deadlock. In that case I would like to have a possibility to terminate SP manually.

**Comment by ErikEJ** [comment]
Got it - interested in doing a PR for this?

**Comment by tiomny** [comment]
Yes.

**Comment by ErikEJ** [comment]
Great, you need to make changes to

src\GUI\RevEng.Core\Procedures\SqlServerStoredProcedureScaffolder.cs

(GenerateProcedure and GenerateMethodSignature methods)

And also to DbContextExtensions file.

Let me know if you cannot figure out how to do a manual test - it is a little bit quirky.

**Comment by ErikEJ** [comment]
@tiomny is this still something you plan to do?

**Comment by tiomny** [comment]
Yes, sir. Was busy at my other project, and just today I've started playing around with the code.
