### ISSUE TITLE
System.MissingMethodException: Method not found: 'Microsoft.Extensions.DependencyInjection.IServiceCollection Microsoft.EntityFrameworkCore.Design.ServiceCollectionExtensions.AddHandlebarsScaffolding(Microsoft.Extensions.DependencyInjection.IServiceCollection, Microsoft.EntityFrameworkCore.Design.ReverseEngineerOptions, System.ValueTuple`2<System.String,System.Action`3<System.IO.TextWriter,System.Object,System.Object[]>>[])'

### ISSUE THREAD

**Issue by kachalkov** [ErikEJ/EFCorePowerTools#58]
Describe what is not working as expected.

### Steps to reproduce
Keep getting during reverse engineer even

### Further technical details
EF Core Power Tools version: (1.0.622)

System.MissingMethodException: Method not found: 'Microsoft.Extensions.DependencyInjection.IServiceCollection Microsoft.EntityFrameworkCore.Design.ServiceCollectionExtensions.AddHandlebarsScaffolding(Microsoft.Extensions.DependencyInjection.IServiceCollection, Microsoft.EntityFrameworkCore.Design.ReverseEngineerOptions, System.ValueTuple`2<System.String,System.Action`3<System.IO.TextWriter,System.Object,System.Object[]>>[])'.
   at ReverseEngineer20.EfCoreReverseEngineer.GenerateFiles(ReverseEngineerOptions reverseEngineerOptions)
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__2.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 154

Database engine: (SQL Server)

Visual Studio version: (2017 15.7.3)

**Comment by kachalkov** [comment]
Duplicate

**Comment by MortezaSefidiSomarin** [comment]
سلام
یک مرد پیدا بشه مشکل مارو رفع کنه


No one solves our problem

**Comment by ErikEJ** [comment]
Did you try the latest daily build?
