### ISSUE TITLE
UI freeze while loading tables

### ISSUE THREAD

**Issue by MizardX** [ErikEJ/EFCorePowerTools#580]
When running the extension against a large Oracle 12c database, the UI freezes for several minutes.

With some digging in the source-code, I found the command that is executing:
```
> Measure-Command { .\efreveng.exe 7 $constr > ..\tables.json }

Days              : 0
Hours             : 0
Minutes           : 6
Seconds           : 48
Milliseconds      : 610
Ticks             : 4086108370
TotalDays         : 0,00472929209490741
TotalHours        : 0,113503010277778
TotalMinutes      : 6,81018061666667
TotalSeconds      : 408,610837
TotalMilliseconds : 408610,837

> (gc ..\tables.json | select -Skip 1 | ConvertFrom-Json).GetEnumerator() | measure HasPrimaryKey -Sum

Count    : 807
Average  :
Sum      : 360
Maximum  :
Minimum  :
Property : HasPrimaryKey
```

Could you please add some caching of the table list, and run the command in a background thread?

### Further technical details
EF Core Power Tools version: 2.5.277

Database engine: Oracle 12c 12.2.0.1.0

Visual Studio version: Visual Studio 2019 16.8.1

**Comment by ErikEJ** [comment]
I cannot influence the query to list the tables, but I will investigate making it more background.

**Comment by ErikEJ** [comment]
Where could table list caching be added??

**Comment by MizardX** [comment]
Your question is ambiguous if you mean where in the source the code should be written, or where on disk the cache should be saved. I choose to answer the latter.

If the file was stored in the user's home directory, it would get really large from multiple projects.

If you place it in the project directory as a normal file, or included it in `efpt.config.json`, it could generate many merge conflicts.

I think it should be in the project directory, but named something like `efpt.config.json.user`. It should then get ignored by most `.gitignore` files.

**Comment by ErikEJ** [comment]
Fixed UI freeze - suggest you take up why it takes more than 5 minutes to perform the schema queries with the maintainers of the Oracle provider and/or your database administrator. 

/cc @alexkeh
