### ISSUE TITLE
The tool deletes unchecked files 

### ISSUE THREAD

**Issue by thenrich2009** [ErikEJ/EFCorePowerTools#583]
I have a folder called Data which had the dbContext file and some entities. I used the tool to reverse engineer a new table from the database. I selected Data as the path for dbContext.

When the tool was done I noticed the following:
- The Data folder was gone from the Solution Explorer!
- I can see the folder in File Explorer. The folder was empty. All the files that were in there are gone. The date of the folder is the current time so it seems the tool deleted the previous Data folder and created a new one.
- The files were not in the recycle bin.

That was a destructive action without giving any warnings! Is this a bug? I can't think this is an expected behavior.

When I give it a path for the dbContext, what am I telling the tool to do exactly?

I suggest adding an information tip next to each option explaining what the option is used for and  maybe examples for an input and what the outcome would look like.

I was able to repeat the whole process with the same outcome.

**Comment by ErikEJ** [comment]
I assume you are using souce control?

The behavior and tips for usage is available here: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#saving-options-and-running-the-second-time - and there is a link to this GitHub repo from the About dialog in the tool.

**Comment by thenrich2009** [comment]
> I assume you are using souce control?
> 
> The behavior and tips for usage is available here: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#saving-options-and-running-the-second-time - and there is a link to this GitHub repo from the About dialog in the tool.

I am not using any source control. Even if I am using source control, why did the delete happen?

**Comment by ErikEJ** [comment]
>> why did the delete happen?

Because the files are marked with the autogenerated tag, as explained in the link.

**Comment by thenrich2009** [comment]
> > > why did the delete happen?
> 
> Because the files are marked with the autogenerated tag, as explained in the link.

There's too much dependency on explaining stuff on some site. In the UI it asks which tables I want to script. That fact I uncheck some tables means I don't want to script them. It doesn't mean the tool goes and deletes the entities.  I can simply delete them from Solution Explorer if I need to or the tool specifically has a function to delete them. The UX is confusing.

How many people are going to remember or be even aware they have to manually edit the .cs file in order not to get them deleted?  Maybe a checkbox for each table 'Keep File/Entity' in the UI. 

I am saying this because many developers, and I am one of them, use tools right away, especially if they are simple ones. without reading the manual or instructions. It's best to put things in the UI. 

Thanks for the free tool. I am interested in making it better.

**Comment by ErikEJ** [comment]
Thanks for the feedback..

**Comment by ErikEJ** [comment]
How about a messagebox if you uncheck a file, warning you against the consequences, and if you press OK, the messagebox will not be show again ?

**Comment by ErikEJ** [comment]
Ping?

**Comment by thenrich2009** [comment]
> How about a messagebox if you uncheck a file, warning you against the consequences, and if you press OK, the messagebox will not be show again ?

OK. You mean the message will show only once ever even during future use of the tool?

**Comment by ErikEJ** [comment]
Yes.

**Comment by ErikEJ** [comment]
Possibly a Status Bar would work better!

**Comment by ErikEJ** [comment]
```
 <StackPanel VerticalAlignment="Bottom">
            <StatusBar Background="LemonChiffon">WARNING: Unchecking an item will cause the related file to be deleted!</StatusBar>
        </StackPanel>
    </Grid>

```
