### ISSUE TITLE
DbContextSplitting not working

### ISSUE THREAD

**Issue by JHBonarius** [ErikEJ/EFCorePowerTools#585]
I saw the dotNETconf talk and wanted to check out this great tool. However, DbContextSplitting did non split my DbContext into seperate files.

### Steps to reproduce
New project. Run EF CorePowerTools with DbContextSplitting enabled.

### Further technical details
EF Core Power Tools Version 2.5.277.0

SQLite ADO.NET Provider included: 1.0.109.0
SQLite EF6 DbProvider in GAC - No

System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes

Database engine: SQL Server 14.0.2027

Visual Studio version: VS 2019 16.8

My efp.config.json:
```
{
   "ContextClassName": "...removed...Context",
   "ContextNamespace": null,
   "DefaultDacpacSchema": null,
   "FilterSchemas": false,
   "IncludeConnectionString": false,
   "ModelNamespace": null,
   "OutputContextPath": "Data",
   "OutputPath": "Models",
   "ProjectRootNamespace": "...removed...",
   "Schemas": null,
   "SelectedHandlebarsLanguage": 0,
   "SelectedToBeGenerated": 0,
   "Tables": [
      {
         "HasPrimaryKey": true,
         "Name": "[dbo].[log]",
         "ObjectType": 0
      },
      {
         "HasPrimaryKey": true,
         "Name": "[dbo].[magazine]",
         "ObjectType": 0
      },
      {
         "HasPrimaryKey": true,
         "Name": "[dbo].[size]",
         "ObjectType": 0
      }
   ],
   "UseDatabaseNames": false,
   "UseDbContextSplitting": true,
   "UseFluentApiOnly": false,
   "UseHandleBars": false,
   "UseInflector": true,
   "UseLegacyPluralizer": false,
   "UseNodaTime": false,
   "UseSpatial": false
}
```

Generated Context:
```
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using ...removed....Models;

#nullable disable

namespace ...removed....Data
{
    public partial class ...removed...Context : DbContext
    {
        public ...removed...Context()
        {
        }

        public ...removed...Context(DbContextOptions<...removed...Context> options)
            : base(options)
        {
        }

        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<Magazine> Magazines { get; set; }
        public virtual DbSet<Size> Sizes { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
```

**Comment by ErikEJ** [comment]
Can you share a repro project, works fine for me...

**Comment by ErikEJ** [comment]
Maybe there was nothing to split?

**Comment by JHBonarius** [comment]
Maybe I understand the functions incorrectly? I was expecting each DbSet to get their own context.
About sharing the repro. I need to make a new version, which doesn't have the name of our customer in it, give me some time.

**Comment by ErikEJ** [comment]
If there is nothing in this section (without splitting), nothing will happen.

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            OnModelCreatingPartial(modelBuilder);
        }

**Comment by JHBonarius** [comment]
OK, sorry for raising this issue then. I misunderstood.
Thanks for the tool and the talk!
