### ISSUE TITLE
Support SQL 2008?

### ISSUE THREAD

**Issue by netbitshift** [ErikEJ/EFCorePowerTools#587]
Any chance of supporting SQL 2008 or getting an older build that supports that version?  I just updated our tool version and have lost support for sql 2008.  We really cant update just yet.

**Comment by ErikEJ** [comment]
I am not sure any previous version intentionally supported 2008.

What is not working now?

**Comment by netbitshift** [comment]
I was helping one of the team when I ran into this.  We had not updated our schema in a few months till now.  So when the need came up after changing a few tables, I was helping him do the reverse eng step.  This is when we got the following alert.  The window closes and no changes are done.
![image](https://user-images.githubusercontent.com/17503279/99395256-ca14ae80-28a5-11eb-992b-c35bfd563d19.png)

**Comment by ErikEJ** [comment]
I is just a warning, the process should complete

**Comment by netbitshift** [comment]
Yes, thank you.  It was in fact just a warning.  Back in business.
