### ISSUE TITLE
Add UI to exclude columns from reverse engineering

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#588]
- [x] Create new class to exchange the table list (stop using TableInformation).
- [x] Add columns to this class.
- [x] Add columns to the output from TableList command if EFPT CLI tool.
- [x] Extend TableInformation with a new, non-serialized `List<ColumnInformation>`, where ColumnInformation has: string Name, bool Excluded
- [x] Construct the ExcludeColumns property when loading options, and set when saving options.
- [x] Bind ColumnInfomation to UI - no idea how...

@sm15455 FYI

**Comment by sm15455** [comment]
These steps looks ok to me. Regarding binding to UI, a treeview with checkboxes should work. Do you know if treeview virtualizes rendering? I'm afraid that for database with lots of tables and columns, rendering could slow slow down interface. In that case we could load columns on demand.

**Comment by ErikEJ** [comment]
I do not know much about WPF, but lazy loading the columns is maybe something we should just do anyway.

**Comment by sm15455** [comment]
Deal. Do you want me to work on the missing points?

**Comment by sm15455** [comment]
TableInformationViewModel has TableInformationModel property and a Selected property. If I add a Columns property (list of string [name], bool [selected]) to TableInformationModel we will have Selected property in the model for columns and Selected property  in the view model for tables. This looks weird to me. 

I still haven't fully analyzed the code, but I was thinking to:
- Remove TableInformationModel in TableInformationViewModel.
- Splatter TableInformationModel properties in TableInformationViewModel.
- Create a ColumnInformationViewModel class with Name and Selected Property.
- Add a Columns (List<ColumnInformationViewModel>) property to TableInformationViewModel.
- Change the AddTable and SelectTables methods in TableInformationViewModel to accept a TableModel parameter and populate the properties of TableInformationViewModel.
- Change the GetResult methods in TableInformationViewModel to return a list of TableModel

This would make thing less coupled between models and view models but would require lots of changes in code. What do you think?

**Comment by ErikEJ** [comment]
I think it would be a healthy refactor - maybe you could do that in a separate PR before making any actual UI changes?

**Comment by sm15455** [comment]
If I make a PR with these changes only, UI would be in inconsistent state. I should at least make the minimal changes to align it with the TableInformationViewModel changes.

**Comment by ErikEJ** [comment]
Got it!

**Comment by sm15455** [comment]
I refactored the code. I touched more files than I thought, but now everything work as before. The biggest problem is that TableInformationModel is no longer needed so I have to modify the tests to use the TableModel class. Do you want me to push a branch so you can check modifications before I adapt the tests?

**Comment by ErikEJ** [comment]
Will you comment out the tests then or what? A PR with failing tests will not work.

**Comment by sm15455** [comment]
I just want you to validate my changes before I fix tests. I don't know what's the best way to do that.   Of there's no way, I'll fix the tests and create PR.

**Comment by ErikEJ** [comment]
Ah, I see, just create a PR then, we can always just abandon (or fix the tests in a later commit)

**Comment by sm15455** [comment]
#597 

This PR "almost" complete the task. I have to add some tests.

Furthermore, 
- In Load selection and save Selection buttons should we save columns too or just leave table names?
- Should columns of unselected tables be disabled in the treeview?

**Comment by ErikEJ** [comment]
>> In Load selection and save Selection buttons should we save columns too or just leave table names?

Given that you can now use different efpt.config.json files in the same project, I plan to remove this feature entirely (in a future PR), so just leave as is.

>> Should columns of unselected tables be disabled in the treeview?

That would be a nice feature to have, if possible, I think?

**Comment by sm15455** [comment]
> That would be a nice feature to have, if possible, I think?

Done

**Comment by ErikEJ** [comment]
Thanks for your effort, guess we can close this now?

**Comment by sm15455** [comment]
I think there's one last thing to do: disable primary columns so that they cannot be unchecked in the treeview. This would require lots of work so maybe we can ignore it or open another issue.

**Comment by ErikEJ** [comment]
I will open a new issue.

I guess it includes: 

adding a list of primary key columns to table model

Using this list to select and disable column nodes that are primary key columns

Anything else?

**Comment by sm15455** [comment]
Please don't think too bad of me. I would take a "harder" path. I would separate the model that holds table information  from database **(DatabaseTableModel)** from the model used to serialize table information to efpt.config.json file **(SerializationTableModel)**. This might sound overkill but would completely separate these functionalities. If in the future you want to show column type in the treeview, you can touch the DatabaseTableModel and the view model, but would leave the SerializationTableModel untouched.
I would also change the columns property in the DatabaseTableModel from list of string to a list of ColumnInformationModel which is a class that contains the name and a bool specifying if it's a primary key. This class and can be easily extended to add other information in the future.

Of course I can work on it, but I totally understand if you think it's an overkill.

**Comment by ErikEJ** [comment]
Not overkill, makes a lot of sense. 

Let me look into the DatabaseModel changes.

**Comment by ErikEJ** [comment]
On second thoughts, feel free to start work on this. I will create a new issue now.

**Comment by ErikEJ** [comment]
Created #600
