### ISSUE TITLE
Option to overwrite existing files

### ISSUE THREAD

**Issue by tonysneed** [ErikEJ/EFCorePowerTools#59]
If I reverse engineer more than once and have not deleted generated files, those files are not overwritten. Should there be an option to overwrite files if they exist (aka force option)?

**Comment by ErikEJ** [comment]
Everything is always overwritten… But you must select all tables every time...

**Comment by tonysneed** [comment]
What I saw is that the old file was not being overwritten. Let me try it again with the latest daily build.

**Comment by ErikEJ** [comment]
Could be a VS refresh issue?

**Comment by tonysneed** [comment]
Looks like the latest daily build disables Hbs templates.  Can you please provide a link to a version that includes the Hbs support?

**Comment by ErikEJ** [comment]
Now back in latest daily build

**Comment by tonysneed** [comment]
Alright, I can see that the files are overwritten as expected.  Although I do need to close and re-open the file to see changes, which is simply a VS refresh issue.

**Comment by ErikEJ** [comment]
Possible duplicate of #38
