### ISSUE TITLE
DbContextExtensions.SqlQuery() method should be named DbContextExtensions.SqlQueryAsync() 

### ISSUE THREAD

**Issue by sonnemaf** [ErikEJ/EFCorePowerTools#595]
The SqlQuery method is an Async method which returns a Task. The common naming convention says you should add the Async suffix to the name. You may consider adding an extra "overload". The SqlQuery() method uses ToArray() to execute the procedure. The SqlQueryAsync() method should use the ToArrayAsync().

```cs
public static T[] SqlQuery<T>(this DbContext db, string sql, params object[] parameters) where T : class {
    using (var db2 = new ContextForQueryType<T>(db.Database.GetDbConnection(), db.Database.CurrentTransaction)) {
        return db2.Set<T>().FromSqlRaw(sql, parameters).ToArray();
    }
}

public static async Task<T[]> SqlQueryAsync<T>(this DbContext db, string sql, params object[] parameters) where T : class
{
    using (var db2 = new ContextForQueryType<T>(db.Database.GetDbConnection(), db.Database.CurrentTransaction))
    {
        return await db2.Set<T>().FromSqlRaw(sql, parameters).ToArrayAsync();
    }
}
```

The generated methods in the ...DbContextProcedures class should also have an Async suffix in the name if they call the SqlQueryAsync() method. Maybe you can add a option in the UI whether you want sync and/or async calls.

**Comment by ErikEJ** [comment]
Thanks, are you interested in creating a PR for the name change? 

Not so sure about having a sync method, as this will increase the amount of generated code, and you can always call the async method in a sync way.
