### ISSUE TITLE
Unable to exclude columns from model.

### ISSUE THREAD

**Issue by tjackadams** [ErikEJ/EFCorePowerTools#596]
When I'm attempting to exclude a column using the following snippet from efpt.config.json

```json
   "Tables": [
    {
      "ExcludedColumns": [
        "AssetNumber"
      ],
      "HasPrimaryKey": true,
      "Name": "[DataLogger].[Logger]",
      "ObjectType": 0
    }
   ],
```

The excluded column is not excluded from the model. The efpt.config.json is also updated to the following (after scaffold).

```json
   "Tables": [
      {
         "Columns": [ ],
         "HasPrimaryKey": true,
         "Name": "[DataLogger].[Logger]",
         "ObjectType": 0
      }
   ],
```

### Steps to reproduce

- Add a column to the ExcludedColumns array of the table - from testing it doesn't matter what column you provide.
- Scaffold the database.

The ExcludedColumns array in efpt.json will be replaced with an empty Columns array. The requested property will still be part of the final model.

Configuration syntax is based on the release notes example https://github.com/ErikEJ/EFCorePowerTools/wiki/Release-notes

### Further technical details
EF Core Power Tools version: 2.5.312.0

Database engine: SQL Server

Visual Studio version: Visual Studio 16.8.0

**Comment by ErikEJ** [comment]
I think this may be temporarily broken...
@sm15455 FYI

**Comment by sm15455** [comment]
Thanks for feedback. I'm working on it right now and can confirm this is temporarily broken.

**Comment by ErikEJ** [comment]
@tjackadams thanks for trying out this preview feature, will ping you when things are stable again.
