### ISSUE TITLE
Context menu not present in VS 16.8.1

### ISSUE THREAD

**Issue by jstrawther** [ErikEJ/EFCorePowerTools#599]
I'm not seeing the context menu in Visual Studio 16.8.1.  I haven't used the extension in a while, so don't know when it disappeared, but would guess it occurred when upgrading from 16.7.x to 16.8.x. 

### Steps to reproduce
Create a new .net core console app in VS 16.8.1.  Right-click the project in Solution Explorer.  Can't find EFPT context menu. 

### Further technical details
EF Core Power Tools version: 2.5.312 (originally discovered issue in an older version. updated to the latest version from the marketplace, then updated to the daily build)

Database engine: SQL Server

Visual Studio version: 16.8.1

**Comment by ErikEJ** [comment]
The context menu is on the Project mode.

Have you checked if the extension is disabled?

**Comment by jstrawther** [comment]
It’s not disabled.  I’ve uninstalled and reinstalled it, and tried different versions. I installed .net sdk 3.1. Also tried updating to VS 16.8.2.  I still don’t see it. I’m not sure what to do to troubleshoot.

On Nov 21, 2020, at 00:34, Erik Ejlskov Jensen <notifications@github.com> wrote:

﻿

CAUTION: This email originated from outside your organization. Exercise caution when opening attachments or clicking links, especially from unknown senders.

The context menu is on the Project mode.

Have you checked if the extension is disabled?

**Comment by ErikEJ** [comment]
You can help by:

Showing me screen shot of the install status.

Showing me your project context menu for a csproj (C# project).

**Comment by jstrawther** [comment]
![EFPT Install Status](https://user-images.githubusercontent.com/981617/99877879-bfac2a80-2bad-11eb-9289-b3139cd26678.png)

![Context Menu](https://user-images.githubusercontent.com/981617/99877883-c5097500-2bad-11eb-938c-ddd0b193fde2.png)

**Comment by ErikEJ** [comment]
That is weird, and not seen from any other user.

Maybe try to run ths? https://github.com/remcoros/DuplicateExtensionFinder

**Comment by ErikEJ** [comment]
Have you tried on another machine?

**Comment by jstrawther** [comment]
All good.  I uninstalled and reinstalled Visual Studio, added the extension, and it's working now.  Sorry for taking your time, thanks for your help.
