### ISSUE TITLE
Feeding pluralizer before reverse engineering

### ISSUE THREAD

**Issue by GuidoNeele** [ErikEJ/EFCorePowerTools#60]
Is it possible to feed the pluralizer when reverse engineering? I've got a table name called 'CourseStatus' and it's being changed to CourseStatu.

### Further technical details
EF Core Power Tools version: 1.0.604.0
Database engine: SQL Server
Visual Studio version: Visual Studio 2017 15.7.3

**Comment by ErikEJ** [comment]
What were you expecting?

**Comment by ErikEJ** [comment]
@theprateik any plans to update your PR?

**Comment by GuidoNeele** [comment]
I did bump into one issue while using the updated ReverseEngineer20.dll from @theprateik. It no longer used the CSharpEntityType code template when reverse engineering. Not sure what was going on there so reverted back to the current marketplace version. With the code changes renaming CourseStatus to CourseStatuses was solved. Thanks @theprateik!

**Comment by GuidoNeele** [comment]
Maybe had to do with me only replacing ReverseEngineer20.dll and not the other dll's. I didn't build the complete project because I haven't got the VS extensions SDK installed.

**Comment by theprateik** [comment]
@ErikEJ yes, I will update the PR later tonight. I had been out for few days. 
Current PR doesn't account for words with both space and Upper case. I will update for this as well.

**Comment by theprateik** [comment]
@GuidoNeele could you be give me little more details on "It no longer used the CSharpEntityType code template when reverse engineering". I don't think my pull request has anything to do it, but I could be wrong.

**Comment by GuidoNeele** [comment]
@theprateik I also don't think your changes had anything to do with it. I downloaded your repository, build the ReverseEngineer20 project and replaced the dll in %AppData%\Local\Microsoft\VisualStudio\15.0_040b922d\Extensions\a4cmkcgu.yxx\. It probably had to do with me mixing dll's from different versions.
