### ISSUE TITLE
Disable Primary key columns in table/column UI

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#600]
Separate the model that holds table information from database (`TableModel`) from the model used to serialize table information to efpt.config.json file by introducing a `SerializationTableModel`, and use that in the ReverseEngineerOptions class.

So not:

    public List<TableModel> Tables { get; set; }

But:

    public List<SerializationTableModel> Tables { get; set; } 

In ReverseEngineerOptions class.

Change the columns property in the TableModel class from list of string to a list of ColumnModel which is a class that contains the name and a bool specifying if it's a primary key column. This class and can be easily extended to add other information in the future.

Use information from the updated TableModel to disable primary key nodes in the UI.

No worries about the breaking nature of this at this point in time.

**Comment by ErikEJ** [comment]
@sm15455 FYI (Small design changes, let me know what you think)

**Comment by ErikEJ** [comment]
We can also stop roundtripping HasPrimaryKey in the efpt.config.json file then.

**Comment by sm15455** [comment]
Sounds reasonable. I am starting to work on it and hope to finish very soon.

**Comment by ErikEJ** [comment]
Hold your horses!  I am working on the TableModel part as we speak!

**Comment by ErikEJ** [comment]
Sorry for not letting you know earlier!

**Comment by ErikEJ** [comment]
@sm15455 PR is in now, maybe we should consider if TableModel.HasPrimary is needed any longer (can be calculated instead) ?

So the remaining part is to disable the primary and check the primary key columns in the UI.

**Comment by sm15455** [comment]
Yes I think HasPrimaryKey can be removed. I'll first fix UI and create a PR, then will add a commit to remove HasPrimaryKey.

**Comment by sm15455** [comment]
#606

**Comment by ErikEJ** [comment]
Thanks for a great contribution!

**Comment by sm15455** [comment]
It was fun, but I have another idea. Do you think It woul be good to organize the treeview in table, view, function and procedure?

**Comment by ErikEJ** [comment]
Potentially! That is what Microsoft does in their wizard.

**Comment by sm15455** [comment]
I have to stop for a couple of days since tomorrow I have a presentation of efcore 5 and  have to prepare material. After that, I can work on It. Should we open a new issue?

**Comment by ErikEJ** [comment]
Yes, just go ahead and do that. Good luck with your presentation!
