### ISSUE TITLE
Improve UI in Objects list

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#608]
Something similar to this - I think the "schema" (dbo) level is unnecessary.

![image](https://user-images.githubusercontent.com/4169187/99938441-1493a080-2d68-11eb-9014-406be957d223.png)

Current UI

![image](https://user-images.githubusercontent.com/4169187/99936978-c4ffa580-2d64-11eb-962d-bb934aa5065f.png)

@sm15455 FYI

**Comment by sm15455** [comment]
I have finished preparing my session. I can start working on it if it's ok for you.

**Comment by ErikEJ** [comment]
Sounds great!

**Comment by sm15455** [comment]
![image](https://user-images.githubusercontent.com/5398631/100089948-c3141000-2e52-11eb-9366-aed2fa69d720.png)

What do you think?

**Comment by sm15455** [comment]
The parent nodes are: tables, views, stored procedures, functions. If the parent node has no children (because there are no objects or the search excluded them), the parent is hidden. When the parent node is selected, children selection is updated. When a child is selected, parent node selection enters in three state mode. Window is now resizable.

**Comment by ErikEJ** [comment]
This looks great! 
A few comments - 

also have image on top level nodes? What do you think?

Views => Views/Keyless Tables

**Comment by sm15455** [comment]
> also have image on top level nodes? What do you think?

Ok, but I'm very bad at finding images. If you have good ones, let me know.

> Views => Views/Keyless Tables

Views => Database views. Tables => Database tables with and without PK. We can easily change it

**Comment by ErikEJ** [comment]
EF Core does not differentiate between views and tables! There are DatabaseTable objects with or without a primary key.

For images, just use the ones for the nodes.

**Comment by sm15455** [comment]
> EF Core does not differentiate between views and tables! There are DatabaseTable objects with or without a primary key.
I know, but this screen shows database objects. I think it would be more clear to group objects using database meaning rather than EF meaning.
 
> For images, just use the ones for the nodes.

Ok

**Comment by sm15455** [comment]
![image](https://user-images.githubusercontent.com/5398631/100232940-54ee4c80-2f29-11eb-97ce-12e4e5294183.png)

I added images in main node. The whole tree required lots of changes in the ViewModels and need to fix the tests. Do you want me to create a PR so you can play with it? I'll fix the tests later with another commit.

**Comment by ErikEJ** [comment]
Yes, please create a PR, and I will have a look at it! 
Looks great!

**Comment by sm15455** [comment]
I think that we miss only one feature to pair EF6 wizard experience: the ability to move between screens. The back and next buttons. What di you think?

**Comment by ErikEJ** [comment]
I think it is a lot of work, that no user (except you) has requested.

**Comment by sm15455** [comment]
Got It :D

**Comment by ErikEJ** [comment]
Thanks for a great improvement to the tool!

**Comment by sm15455** [comment]
It was really fun. Thanks for letting me be part of it! I have some ideas to improve usability by giving user the ability to rename objects and columns using the UI. But, as you said before, it's something no user asked but me. I'll consider it in the future if other ask.

**Comment by ErikEJ** [comment]
Are you thinking about this: https://github.com/ErikEJ/EFCorePowerTools/issues/152 ?

**Comment by sm15455** [comment]
Exactly. 
I was thinking it could be done in two ways: 

1. In the current tree we add a small icon next to tables and column name. When the user clicks on the icon, a textbox appears next to the name and let the user enter the new name. 
2. Do something similar to previous solution, but in a new wizard screen.

**Comment by ErikEJ** [comment]
Certainly more possible now, when all columns are shown in the UI
