### ISSUE TITLE
Stored procedure execution throws error if return values are null

### ISSUE THREAD

**Issue by nssidhu** [ErikEJ/EFCorePowerTools#610]
var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[sp_AddOrUpdateOrgLocation] 
..................
..................................
@OrgLocationID_PK, @OrgID_FK, @UserID_FK, @LocationName, @LocationCode, @ContactPersonName, , parameterPaymentRequired, parameterNewOrgLocationID_PK, parameterErrorMessage, parameterreturnValue);

The line Below throws Error
            NewOrgLocationID_PK.SetValue(parameterNewOrgLocationID_PK.Value);
            ErrorMessage.SetValue(parameterErrorMessage.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

Expecting it ti return Null back the calling procedure.
In my case the SP would return new GUID is it was successful or error message if it was unsuccessful.
In my case since it is unsuccessful, the GUID is null and it throws error instead of passing back Null to the callee.

Update:
Even in success full case it is not passing back Guid. during Debug i can see value being returned from SP, but not being returned back to the calling function.

**Comment by ErikEJ** [comment]
Please provide a full repo. 

Which line exactly throws error??

**Comment by ErikEJ** [comment]
Ping?

**Comment by ErikEJ** [comment]
Closed as no repro provided, feel free to re-open if you can provide one.
