### ISSUE TITLE
Show views using new icon

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#611]
VS2015 Image Library\2015_VSIcon\View\View_16x.png

**Comment by ErikEJ** [comment]
@sm15455 Maybe something for you?

**Comment by sm15455** [comment]
AFAIK, in sql server views cannot have PK, but in oracle they can. 
If the object is a view and has PK use the view icon.
If the object is a view and doesn't have a PK use the keyless icon

Is it ok or I should use the view icon for all views?

**Comment by ErikEJ** [comment]
Just use the view icon for now, have no idea how the Oracle provider treats views with a primary key.
