### ISSUE TITLE
Cannot select all stored procedures

### ISSUE THREAD

**Issue by LiviuShiva** [ErikEJ/EFCorePowerTools#612]
![IssueEFTools](https://user-images.githubusercontent.com/3812469/100323749-e19f1600-2fce-11eb-9d94-56fc999751ba.gif)
![IssueEFTools2](https://user-images.githubusercontent.com/3812469/100324670-3beca680-2fd0-11eb-8058-6e8f975e3414.gif)

### Steps to reproduce
When I try to select all objects (tables and SPs) from the database,  the tool select only the tables. More, when I want to check manualy all the stored procedures, it don't let me or even uncheck them.

### Further technical details
EF Core Power Tools version 2.5.333.0

Database engine: (SQL Server)

Visual Studio version: (e.g. Visual Studio 2019 16.8.2)

**Comment by ErikEJ** [comment]
Please await an update of the daily build, in the meantime use the version released on MarketPlace @sm15455  FYI

**Comment by LiviuShiva** [comment]
I will do so. Thank you for work and this great and useful tool!
