### ISSUE TITLE
Database connection does not appear in the reverse engineering tool

### ISSUE THREAD

**Issue by maximeozenne** [ErikEJ/EFCorePowerTools#613]
Hello ! Looks like it's a common problem, sorry to duplicate, I'm unable to spot my mistake.

### Steps to reproduce
I created a .sdf database file from the SQL Server compact toolbox extension. I was able to create a table and so on.
Now I want to scaffold the DbContext. I right-click on my project then choose "EF Core Power Tool" > "Reverse Engineer"

Here I have a form "Choose a Database Connection". But my SQL Server compact connection does not show up. But It's shown up in the Server Explorer Window.

I tried to delete it from the Server Explorer then I tried to add it from the "Choose a Database Connection" > "Add" Button, I pick the "SQL Server Compact 4.0 (Simple by ErikEJ)" Provider.

When I test my connection, it's successful. But it isn't added to the dropdown list of available connections.

What did I do wrong ? Thanks for your help and your amazing tools !

### Further technical details
EF Core Power Tools version: 4.7.670.0 

SQL Server Compact 4.0 in GAC - Yes - 4.0.8876.1
SQL Server Compact 4.0 DbProvider - Yes

SQL Server Compact 4.0 DDEX provider - No
SQL Server Compact 4.0 Simple DDEX provider - Yes

Database engine: SQL Compact 4.0

Visual Studio version: 
- Microsoft Visual Studio Community 2019 - Version 16.7.6
- Microsoft .Net Framework 4.7.03190
- Project Type : Windows Forms App (.Net Core)
- Target Framework : .Net Core 3.1
- Nuget Packages :
    - Microsoft.EntityFrameworkCore v5.0.0
    - Microsoft.EntityFrameworkCore.SqlServer v5.0.0
    - Microsoft.EntityFrameworkCore.Tools v5.0.0
    - EntityFrameworkCore.SqlServerCompact40 v2.2.0.7
    - EntityFrameworkCore.SqlServerCompact40.Core v2.2.0.7
    - EntityFrameworkCore.SqlServerCompact40.Design v1.1.0.1

**Comment by ErikEJ** [comment]
SQL Server Compact is only supported with EF Core 2 - you may be able to download an older version of the extension from here, and use that: https://github.com/ErikEJ/EFCorePowerTools/wiki/Release-notes#24140-august-6-2020 

Also, you cannot mix EF Core 1, 2 and 3 packages.

The EntityFrameworkCore.SqlServerCompact40.Design is no needed at all

**Comment by maximeozenne** [comment]
Thanks for your answer.

I firstly removed EntityFrameworkCore.SqlServerCompact40.Design.

But I have to admit that I'm a bit lost avec the EF Core versions. I am using EF Core 5 actually ?

In the release note you pointed, It's said that your EFCorePowerTools is working with EF Core 5. So do I have to only downgrade the version of your tool I am using, or do I have to also downgrade some of the packages I am using too ?

**Comment by ErikEJ** [comment]
You must use only version 2.2 packages!

**Comment by maximeozenne** [comment]
Ok I installed the previous version of your PowerTool then downgraded all EntityFramework packages to 2.2.6. Everything worked like a charm !
Thanks a lot for your help !
