### ISSUE TITLE
Cannot open PickTableDialog in the designer

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#615]
@sm15455 Maybe you can help?

**Comment by sm15455** [comment]
Can you tell me the steps to reproduce the problem?

**Comment by ErikEJ** [comment]
Check out latest master

Open PickTablesDialog in WPF designer.

Severity	Code	Description	Project	
File	Line	Suppression State
Error	XDG0008	Binding is not supported in a Windows Presentation Foundation (WPF) project.	EFCorePowerTools	C:\Code\EFCorePowerTools\src\GUI\EFCorePowerTools\Dialogs\PickTablesDialog.xaml	1	


Severity	Code	Description	Project	File	Line	Suppression State
Error	XDG0008	The name "Interaction" does not exist in the namespace "http://schemas.microsoft.com/xaml/behaviors".	EFCorePowerTools	C:\Code\EFCorePowerTools\src\GUI\EFCorePowerTools\Dialogs\PickTablesDialog.xaml	21	

![image](https://user-images.githubusercontent.com/4169187/100364558-969cf700-2ffe-11eb-81b5-da55e19a8b1e.png)

**Comment by sm15455** [comment]
Try removing the whole section. I can't check right now

**Comment by ErikEJ** [comment]
Fixed with a VS restart
