### ISSUE TITLE
Reverse Engineer not using specified Namespace when a Project path is selected

### ISSUE THREAD

**Issue by JFesta** [ErikEJ/EFCorePowerTools#62]
Greetings.
I'm trying to generate my POCO classes into a specified folder, called "Generated", inside my Entities project.
Because these POCOs are partial classes and some of them have custom partial implementations in the same project (and that's why I want to generate them in a subfolder in the first place), I want the namespace to not change at all.
But when I generate the classes specifying both the Namespace and the Project path, Reverse Engineer seems to just append the .Generated part to the namespace instead of assigning exactly the specified Namespace.

Is this the intended behaviour? If that's the case, I think it's not correct, because it doesn't cover a scenario like this.

![immagine](https://user-images.githubusercontent.com/8626893/41851819-74838046-7889-11e8-9117-1630f01ad400.png)

**Comment by ErikEJ** [comment]
Could you show the actual and expected results, pls

**Comment by JFesta** [comment]
Sorry, I should have been more clear.

Actual result:

`namespace MyProject.Repository.Entities.Generated`

Expected result:

`namespace MyProject.Repository.Entities`

**Comment by ErikEJ** [comment]
Avoid specifying Generated, and then move the files to the desired folder - standard convention in VS is that folder name reflects namespace..

**Comment by ErikEJ** [comment]
Any comments?

**Comment by theprateik** [comment]
I think I have to agree with @JFesta. A lot of projects out there don't follow the standard namespace naming convention in VS. 
I think it will be a good approach to let the user select the desired namespace and the full project path.
In case, the project path is empty, standard VS convention can be followed.

**Comment by JFesta** [comment]
In the meantime I got around this issue through the Handlebars template by manually modifying the `Class.hbf file`, but I think that's not optimal because it forces you to use the Handlerbars template.

`namespace MyProject.Generated`

**Comment by ErikEJ** [comment]
I believe that this is exactly what Handlebars templates are for
