### ISSUE TITLE
Enforcement of ID column name casing - EntityID -> EntityId

### ISSUE THREAD

**Issue by stevestokes** [ErikEJ/EFCorePowerTools#627]
Describe what is not working as expected.
Power tools is forcing the column casing in the models. In the database an identity column is set as EntityID casing and when the model renders it changes it to EntityId

### Steps to reproduce
Include a complete description that I can redo to reproduce the issue.
Build a model from a table with capital casing on ID

### Further technical details
EF Core Power Tools version: 2.5.277.0

Database engine: SQL Server

Visual Studio version: 2019

**Comment by ErikEJ** [comment]
It is actually the EF Core design library that suggests this.

If you use "Use database names" and EF Core 5, it should work as expected.

**Comment by stevestokes** [comment]
> It is actually the EF Core design library that suggests this.
> 
> If you use "Use database names" and EF Core 5, it should work as expected.

So, it sort of does. If I use "Use database names" the ID fields are preserved. However, a table name like Users is preserved as Users. In previous versions, this was singularized to "User".

So with "Use database names"
ID columns = ID
Users = Users 
db.Users.Add(...)
new Users()
{
...
}

Without "Use database names"
IS columns = Id
Users = User
db.User.Add(...)
new User()
{
...
}

As you can see it flips between resulting in massive code changes either way (assuming an existing large codebase).

**Comment by ErikEJ** [comment]
Have you enabled Pluralization? That should fix the Users <> User issue, I think

**Comment by ErikEJ** [comment]
>> As you can see it flips between resulting in massive code changes either way (assuming an existing large codebase).

What generated that codebase?? You can opt-in to use the EF6 pluralizer...

**Comment by stevestokes** [comment]
![image](https://user-images.githubusercontent.com/30118739/100905042-9d5fba00-3495-11eb-8f4e-94c4765552cd.png)

**Comment by stevestokes** [comment]
If I uncheck "User table and column names directly from the database" it results in 

User
{
UserId
}

If that is checked it results in 
Users
{
UserID
}

**Comment by stevestokes** [comment]
DB:
![image](https://user-images.githubusercontent.com/30118739/100905566-3989c100-3496-11eb-824f-ab8dbbb0a75f.png)


Option 1:
![image](https://user-images.githubusercontent.com/30118739/100905684-58885300-3496-11eb-8b35-212d8bd9cc0c.png)

results in:
![image](https://user-images.githubusercontent.com/30118739/100905766-70f86d80-3496-11eb-9824-5332668fc7c8.png)


Option 2:
![image](https://user-images.githubusercontent.com/30118739/100905946-a1400c00-3496-11eb-9775-477e6ed0afb8.png)

results in:
![image](https://user-images.githubusercontent.com/30118739/100906025-b452dc00-3496-11eb-8dc8-38d3fcade197.png)

**Comment by ErikEJ** [comment]
Yes, those are the current options.

What is the actual issue?

**Comment by stevestokes** [comment]
In previous versions of this software I was able to pluralize **and** preserve tables names/id columns:

```
public partial class User
{
 public int UserID { get; set;}
}
```

Notice User is singular on the class and ID is not Id

**Comment by ErikEJ** [comment]
Which EF Core version did you pick??

**Comment by ErikEJ** [comment]
Please provide a sample CREATE Table script, and I will have a look.

**Comment by stevestokes** [comment]
Thanks!

> EF Core 3.1.10

```
CREATE TABLE [dbo].[Users](
	[UserID] [int] IDENTITY(1,1) NOT NULL,
	[Username] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
```

**Comment by ErikEJ** [comment]
I wonder what "previous version of the tool" you are referring to - this has never worked until EF Core 5.

**Comment by stevestokes** [comment]
I recently updated it but it was about a year old, still on vs2019

**Comment by ErikEJ** [comment]
Ah, I used to have an quirky option to fix Id => ID. I removed that.

Please try EF Core 5 scaffolding.

**Comment by ErikEJ** [comment]
Any update with trying EF Core 5?

**Comment by ErikEJ** [comment]
As expected, this works with EF Core 5 scaffolding:

    public partial class User
    {
        public int UserID { get; set; }
        public string Username { get; set; }
    }

**Comment by ErikEJ** [comment]
@MisinformedDNA are you not able to use on of the many renaming options?

**Comment by MisinformedDNA** [comment]
Sorry, I honestly didn't think this would work.

```json
"ColumnPatternReplaceWith": "ID",
"ColumnRegexPattern": "ID$",
```

**Comment by MisinformedDNA** [comment]
Yep. Thanks for your hard work on this awesome project.

**Comment by ErikEJ** [comment]
@MisinformedDNA really appreciate your feedback and help.
