### ISSUE TITLE
Reverse Engineer: Setting indentation character as Tab

### ISSUE THREAD

**Issue by melihsen** [ErikEJ/EFCorePowerTools#629]
In Visual Studio Text Editor preferences, I'm using "Keep Tabs" indentation option for all source files. But auto-generated files are created with space character for indentation. Is there any way to set Tab character for indentation?

**Comment by ErikEJ** [comment]
Have you tried the Handlebars templates?

**Comment by ErikEJ** [comment]
I have no other suggestions.

**Comment by melihsen** [comment]
@ErikEJ 
Handlebars templates solve the problem partially. Entity files is OK but inside of 
OnModelCreating(ModelBuilder modelBuilder)
function created with spaces
I cannot find and correct it in Handlebars templates. It causes tabs and spaces together in DbContext file.
