### ISSUE TITLE
Any way to not generate [key] attributes?

### ISSUE THREAD

**Issue by netbitshift** [ErikEJ/EFCorePowerTools#630]
Had upgraded my extension recently.  Had been a while since I had updated the schema for a project.  When I did I started running into errors (not with the extension) but EF-related.  I noticed by comparing to the previous version of my code, that the [key] entity attributes were not present before, but after running the reverse engineering step with the updated extension, the [key] attributes were present.  
The project is using EF Core 2.2.4 and with the EF Core PowerTools, I select to use Data annotations.

Running the code, I get errors at runtime like this...
`...has composite primary key defined with data annotations. To set composite primary key, use fluent API.`

One of our next tasks is to switch over to the Fluent api for our model, but wasn't planning on doing it right now.
Is there any way to avoid having the [key] attributes being added?

**Comment by ErikEJ** [comment]
No, not that I know of, what is throwing that error?
The Key attribute was added always to help with OData scenarios

**Comment by netbitshift** [comment]
As mentioned above, the error is being thrown when I run my code (after rev eng the model ).  Its not the extension that is blowing up, but my code.  The only difference is now there are [key] annotations added where there were none before.  They were added on just about all entities that define a primary key, and looks like they were added for FK fields also.  That error I shared above is complaining about a table that I had not dealt with in a long time and no changes have been made to it. Again the only difference was before/after with the [key] annotation applied.

**Comment by ErikEJ** [comment]
If you would like me to investigate, please provide a sample SQL script and a simple code sample that fails.

**Comment by ErikEJ** [comment]
EF Core 2.2 is no longer supported, I have a link in the release notes to a old version that you may be able to use with Ef Core 2.2.

**Comment by netbitshift** [comment]
Thanks Erik, but I just dove in and brought all the projects up to the latest packages - .net 5 & ef fore 5.  Had some cleanup/refactoring to do, then switched over to using the fluent api and do some more cleanup.  Had to purge a few classes I had created to retrofit views into the EF model, but things seem to be working now.  We needed to do this sooner or later.

**Comment by ErikEJ** [comment]
Great news!
