### ISSUE TITLE
[Proposal] Reverse Engineering - Always return TEntity[] from SP mapper

### ISSUE THREAD

**Issue by tiomny** [ErikEJ/EFCorePowerTools#636]
At this point if an output column list could not be retrieved (SP uses temp table/dynamic SQL, etc), SP mapper returns Task<int>. SP mapper body calls ExecuteSqlRawAsync.
Other SP mappers return Task<procedurenameRESULT[]>. Since procedurenameRESULT class is partial, user can extend this class with custom properties in order to obtain data from SP with temp tables/dynamic SQL.

My proposal is to use SqlQueryAsync&lt;procedurenameRESULT&gt; despite the errors while retrieving data structure.

### Further technical details
EF Core Power Tools version: 2.5.358

Database engine: MS SQL 

Visual Studio version: Visual Studio 2019 Professional v 16.8.2.

**Comment by ErikEJ** [comment]
I am not sure I understand - the issue is that procedurenameRESULT is not generated, so it cannot be returned.

**Comment by tiomny** [comment]
In this case an empty partial procedurenameRESULT class might be generated.

**Comment by tiomny** [comment]
I know exactly what columns my SP returns. What I have to do currently:
1. Create class procedurenameRESULT with corresponding properties;
2. Create file in my project MydbContextProcedures.cs. As MydbContextProcedures class is partial, I just write
```C#
public partial class MydbContextProcedures
...
```
3. Add method to this class:
```C#
public async Task<procedurenameResult[]> procedurename_with_data(int? MY_PARAMETER, OutputParameter<int> returnValue = null)
```
and implement mentioned way above.

**Comment by ErikEJ** [comment]
I looks like the empty XxxResult class is always generated anyway, so it is just the method signature that needs to be changed.

Happy to get take PR for this - also makes the code simpler!
