### ISSUE TITLE
Table-Per-Type Support

### ISSUE THREAD

**Issue by cosswift** [ErikEJ/EFCorePowerTools#644]
Add support for the Table-Per-Type.
  In the table tree have a combo box that allow you to pick another table in the list that will be the base class
    Pick a base table will ensure that the it is checked in the tree and will disable it form being unchecked
    Pick a base table will then uncheck any columns that exist in the base table, including the PK
  The generation of the tables will exclude the to and from navigation properties and have it derive from the base entity that was chosen
  The context will need to make need to add the "ToTable" to the entities that are being derived from a base table and the obvious not to generate the navigation properties.

**Comment by ErikEJ** [comment]
This type of domain driven design is not possible with the database first approach of this tool.

**Comment by RannyMeier** [comment]
Can an EF6 EDMX file be used to get an EF Core model with Table-per-type Inheritance?

**Comment by ErikEJ** [comment]
No, this tool has no knowledge of EDMX. What have you tried?

**Comment by ErikEJ** [comment]
@RannyMeier I think there is a tool output there somewhere that attempt this. As stated above, this tool is database first centered, and maps one entity for each table. You can build other models in top if database model as you desire

**Comment by RannyMeier** [comment]
When the scaffolding tool is directed to an EDMX file with an inherits description, will the resulting EF Core DbContext model have the inheritance?

EDMX file
`    <AssociationSet Name="FK_EntityAttribute_inherits_ObjectAttribute" Association="RM.Acct.Model.Store.FK_EntityAttribute_inherits_ObjectAttribute">
      <End Role="ObjectAttribute" EntitySet="ObjectAttributes" />
      <End Role="EntityAttribute" EntitySet="ObjectAttributes_EntityAttribute" />
    </AssociationSet>
`

CS file
`//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RM.Acct.Model
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class EntityAttribute : ObjectAttribute
    {
        public int ObjId { get; set; }
    
        public virtual Entity Obj { get; set; }
    }
}
`

**Comment by ErikEJ** [comment]
@RannyMeier The scaffolding tool cannot be directed at an EDMX file. What makes you think it does?

**Comment by RannyMeier** [comment]
At a point in this EF Community Standup
Entity Framework Community Standup - EF Core Power Tools: the New Batch from about 4 years ago.
https://youtu.be/3-Izu_qLDqY?t=1660

Reverse engineer a SQL Server Database project (.dacpac)

Why: Re-use rich schema description from Database project without need for a live database — short “inner loop”
How: Point to project or .dacpac file in Data Source selection
Demo!
Bonus: Also possible for an EF6 EDMX (*experimental)

**Comment by ErikEJ** [comment]
LOL - yeah, had to remove that broken experimental feature 😅

As I wrote, there are some tools out there, never tried any.

You are aware of the fact that you can run EntityFramework under .NET, I even created a driver for the latest SqlClient

**Comment by RannyMeier** [comment]
Yes, we do use an EF6 NET 8 assembly in Visual Studio NET 8 and NET 9 projects easily.  We were unable to get that to work in LINQPad. Can you do consulting by video call and sharing the screen? We have tried several times in the last few years to move this EF6 model to EF Core. We tried to scaffold it first and then manually edit it into a Code-First model. We would like to try it again with some good advice while working on it.

**Comment by ErikEJ** [comment]
@RannyMeier Sure, you are a sponsor so happy to help. Please email me so we can discuss further: ejlskov at Hotmail dot com

**Comment by ErikEJ** [comment]
@RannyMeier no payment is required, as a sponsor you have a free hour from me!

**Comment by ErikEJ** [comment]
@RannyMeier I get 404 on the invite
