### ISSUE TITLE
Renaming SQL objects with schema not working anymore

### ISSUE THREAD

**Issue by TanguyPa** [ErikEJ/EFCorePowerTools#645]
Since the last update (yesterday it worked), I can't generate the models of my SQL objects with the right name anymore.
I was using the efpt.renaming.json file like this: 
```json
[
  {
    "UseSchemaName": true,
    "SchemaName": "dev"
  },
  {
    "UseSchemaName": true,
    "SchemaName": "test
  },
  {
    "UseSchemaName": true,
    "SchemaName": "prod"
  }
]
```
Before the update, it worked and generated the objects for me using the schema name as a suffix.
For example theses views: dev.myView ,test.myView ,prod.myView became myViewDev, myViewTest, myViewProd model in C#.
Now when I generate the models with the "Reverse engineer" option, my efpt.renaming.json file is empty and the models are not renamed (by default they are named myView, myView1, myView2).
My question is : how to configure the file since the update (if it is not a bug)? And how can I make it behave like before, i.e. rename all SQL object models of a schema with a suffix (stored procedure,view and table).

I also saw this comment in the wiki: ```(This file will be created for you if you use the UI based renaming feature)```.
How does it work from the interface? I don't seem to have seen the option. 
(This file will be created for you if you use the UI based renaming feature).

---

EF Core Power Tools version: 2.5.376

Database engine: SQL Server 2019

Visual Studio version: Visual Studio 2019 16.8.2

**Comment by ErikEJ** [comment]
Thanks for trying the preview version, I am guessing it could be a bug.

@sm15455 FYI

I will try to replicate base on your description.

**Comment by sm15455** [comment]
I will investigate the issue. 
@TanguyPa Keep in mind that regex and UseSchemaName options are not available in the UI right now. In any case, the file shouldn't have been deleted and your settings should have been preserved.  
@ErikEJ Should we find a way to add support for UseSchemaName and regex options in the UI?

**Comment by ErikEJ** [comment]
Let's hear more people ask for it first.

But we should investigate the roundtripping issue

**Comment by ErikEJ** [comment]
@TanguyPa You can rename tables and columns directly in the UI now, just press F2 on table and column label

**Comment by ErikEJ** [comment]
@sm15455 I can see the roundtripping from the view model fails, I will let you look into a fix.

**Comment by sm15455** [comment]
@ErikEJ I'll be able to give a look later in the afternoon.

**Comment by TanguyPa** [comment]
> @TanguyPa You can rename tables and columns directly in the UI now, just press F2 on table and column label

Thanks for this, but with the UI i get lot of bug, when i try to rename objects or check object, some other objects get uncheck randomly. For example i check some views, then i checks some  stored procedure and randomly some or every views that i check before are uncheck

So i have to fill file config manually.

**Comment by ErikEJ** [comment]
Thanks for trying out the preview, and reporting this.

**Comment by ErikEJ** [comment]
@TanguyPa Just go back to using the official release version from VS MarketPlace in the meantime

**Comment by TanguyPa** [comment]
Yes that's what i did.
Thank you for your work

**Comment by ErikEJ** [comment]
Sorry, not fixed yet

**Comment by sm15455** [comment]
@ErikEJ the latest PR didn't fix it?

**Comment by ErikEJ** [comment]
Nope, working on a PR with various bug fixes

**Comment by sm15455** [comment]
Uhm, ok I'll have a look when it's ready. Did work in my case, but I must have missed something. Sorry!
