### ISSUE TITLE
Reverse Engineer Pluralization Issue

### ISSUE THREAD

**Issue by ThomasAG** [ErikEJ/EFCorePowerTools#65]
Issue:
AxResponses reverses into type AxRespons

Provide a method to correct for pluralization issues.

Version:
1.0.604.0

VS Enterprise:
15.7.4

**Comment by ErikEJ** [comment]
Pls show generated code, and highlight actual versus expected, thanks

**Comment by ThomasAG** [comment]
SQL Server Table Name:  "AXResponses"

Reverse Engineer Tool Generates Type Class:

  public partial class Axrespons
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
    }

Instead of "Axrepons"  I would expect  "AxResponse"

The generated DBContext:
  public virtual DbSet<Axrespons> Axresponses { get; set; }

If possible i would expect AxResponses.     
Again, the initial SQL Table name is "AXResponses"

I know the pluralization endings _wordsEndingWithSeReverseList  are in Pluralizer.cs,  adding a feature to include additional items in the list may provide additional user flexibility.   

Thanks for the great tool. I've used Simon Hughes poco generator for years,  your tool is is becoming my standard reverse engineer tool for Core.

**Comment by ErikEJ** [comment]
Have you tried the latest daily build? - it has some pluralization changes

**Comment by ThomasAG** [comment]
Using .. 1.0.604  I believe that's the latest.

**Comment by ThomasAG** [comment]
Ok, I'll setup usage of the daily build and report my findings.

**Comment by ThomasAG** [comment]
Version 1.0.635.  Same issue as reported previously.

**Comment by theprateik** [comment]
#67

**Comment by ThomasAG** [comment]
Thanks
