### ISSUE TITLE
AsDgml() extension method code sample on wiki page

### ISSUE THREAD

**Issue by dpvreony** [ErikEJ/EFCorePowerTools#652]
Greetings

using the current code sample on https://github.com/ErikEJ/EFCorePowerTools/wiki/Inspect-your-DbContext-model#add-asdgml-extension-method can fail in a test with

```
System.ComponentModel.Win32Exception
The specified executable is not a valid application for this OS platform.
```

unfortunately github doesn't allow pr's to wiki's otherwise i'd have generated one :)

using shellexecute resolves the issue

```
    using (var myContext = new MyDbContext())
    {
        var path = Path.GetTempFileName() + ".dgml";
        File.WriteAllText(path, myContext.AsDgml(), Encoding.UTF8);
        var startInfo = new ProcessStartInfo(path)
        {
            UseShellExecute = true,
        };

        Process.Start(startInfo);
    }

```

Thanks :)

**Comment by ErikEJ** [comment]
Updated, thanks for the update
