### ISSUE TITLE
Bug: The generated model for the unstructured Table name seems not correct

### ISSUE THREAD

**Issue by mikependon** [ErikEJ/EFCorePowerTools#656]
The unstructured table names is being generated wrongly.

### Steps to reproduce

I have a table in the red square below.

![image](https://user-images.githubusercontent.com/591015/102013643-c7e12b00-3d51-11eb-93bd-8fe2a69786d5.png)

The generated model is below.

```csharp
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace RawSqlExecutionForEnum.Models.Models
{
    public partial class DottedTable
    {
        public long Id { get; set; }
        public Guid SessionId { get; set; }
        public int? ColumnInt { get; set; }
        public string ColumnNvarChar { get; set; }
    }
}
```

I would expect that the class is annotated with the Table attribute with vaue Dotted.Table, like [Table("Dotted.Table", schema = "dbo")], or something? See below

```csharp
namespace RawSqlExecutionForEnum.Models.Models
{
    [Table("[dbo].[Dotted.Table]", schema = "dbo")]
    public partial class DottedTable
    {
        public long Id { get; set; }
        public Guid SessionId { get; set; }
        public int? ColumnInt { get; set; }
        public string ColumnNvarChar { get; set; }
    }
}
```

Database engine: SQL Server 2016

Visual Studio version: 2019

**Comment by ErikEJ** [comment]
What options do you use?

(For example "UseDatabaseNames") ?

And which EF Core version (3 or 5) ?

**Comment by mikependon** [comment]
It is Reverse Engineer.
- For the `Choose Database Objects`, I only checked the `Dotted.Table` leaving the others unchecked. All columns were checked.
- For the `Generate...` screen
     - Context Name = TestDbContext (this is required, even I only choose the EntityTypes only).
     - Namespace = EFCorePowerTools (RawSqlExecutionForEnum on my previous test)
     - EntityTypes = Models
     - What to generate = EntityTypes only

**Comment by mikependon** [comment]
If I can recommend, the `What to generate` field must be on the top most and have it tweak the fields that are necessary for generation based on the selection?

So if I used EntityTypes only, I would only expect that the enabled fields from the dialog would be `Namespace`, `Naming`, `Data Annotation` and `Include Constr...` only.

**Comment by mikependon** [comment]
Ooops, apology. I tried selecting the `Data Annotation` and it seems generating it correct, except for the EF references (even I unchecked it).

```csharp
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace EFCorePowerTools.Modes2
{
    [Keyless]
    [Table("Dotted.Table")]
    public partial class DottedTable
    {
        public long Id { get; set; }
        public Guid SessionId { get; set; }
        [Column("Column.Int")]
        public int? ColumnInt { get; set; }
        [Column("Column.NVarChar")]
        [StringLength(128)]
        public string ColumnNvarChar { get; set; }
        [Column("Column.DateTime")]
        public DateTime? ColumnDateTime { get; set; }
    }
}
```

It is working, but it we just need to make some small modifications to remove the unnecessary `using` and code.

**Comment by mikependon** [comment]
I as well notice that the generated annotations for non-dbo tables are correct, except that not all columns has the annotations.

**Is that expected and why is that?**

See this generated model.

```csharp
namespace EFCorePowerTools.Models4
{
    [Keyless]
    [Table("IdentityTable", Schema = "sc")]
    public partial class IdentityTable
    {
        public long Id { get; set; }
        public Guid RowGuid { get; set; }
        public bool? ColumnBit { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ColumnDateTime { get; set; }
        public DateTime? ColumnDateTime2 { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? ColumnDecimal { get; set; }
        public double? ColumnFloat { get; set; }
        public int? ColumnInt { get; set; }
        [Column("ColumnNVarChar")]
        public string ColumnNvarChar { get; set; }
    }
}
```

**Comment by ErikEJ** [comment]
Yes, the attributes are only added if they are not the conventions.
