### ISSUE TITLE
Problem with NVARCHAR PARAMETER WITH STORED PROCEDURE

### ISSUE THREAD

**Issue by chpo69** [ErikEJ/EFCorePowerTools#657]
Hello,
There is an exception when we have varchar or nvarchar as parameter of a procedure because the size is missing in the parameter of SqlParameter.

Excetion : String[2]: the Size property has an invalid size of 0.

Solution :
When using an nvarchar or varchar parameter with a procedure, you must set the size parameter to SqpPArameter. When it's NVARCHAR (MAX) you must put the parameter size = -1.

### Steps to reproduce
Juste use a stored procedure with nvarchar(max) parameter.

### Further technical details
EF Core Power Tools version: 2.5.277.0

Database engine:  SQL Server

Visual Studio version: Visual Studio 2019

Thanks for advan

**Comment by ErikEJ** [comment]
Thanks for reporting this, fixed in latest daily build.

**Comment by chpo69** [comment]
👍
