### ISSUE TITLE
Demo video link does not work

### ISSUE THREAD

**Issue by kesmith21** [ErikEJ/EFCorePowerTools#660]
Describe what is not working as expected.

The demo video link (https://www.youtube.com/watch?v=uph-AGyOd8c) gives an error:
![image](https://user-images.githubusercontent.com/37251063/102080587-b2651300-3ddc-11eb-848e-8100e592d597.png)

**Comment by ErikEJ** [comment]
From which page? (Url)

**Comment by ErikEJ** [comment]
It actually work for me - better link is: https://youtu.be/uph-AGyOd8c
