### ISSUE TITLE
Azure functions result in runtime error.  

### ISSUE THREAD

**Issue by RogWeber** [ErikEJ/EFCorePowerTools#662]
Running Azure function with a powertool created database .dll throws runtime errors.  

System.Private.CoreLib: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
Value cannot be null. (Parameter 'provider')

### Steps to reproduce
0) Assumes an existing azure DB of some sort.  

1)  create a simple Azure function.  see: https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-your-first-function-visual-studio (run solution to confirm it works.)

2) add a project to the solution created above -- Class Library (.NET core) C#

3) follow the process reverse engineer the assumed DB from 0)

4) add a reference to the project in 2) from the function in 1) 

5) run the updated solution....  

### Further technical details
EF Core Power Tools version: (2.5.277)

Database engine: (Azure SQL)

Visual Studio version: (e.g. Visual Studio 2019 16.8.3)

**Comment by RogWeber** [comment]
Note:  Same error occurs without the separate class library.  Generating the context and model into the the function's project results in the same error.

**Comment by ErikEJ** [comment]
Azure Functions does not support .NET 5, so make sure you have no 5.0 dependencies

**Comment by ErikEJ** [comment]
Closing as external.
