### ISSUE TITLE
[SQLite] Reverse Engineer database error

### ISSUE THREAD

**Issue by mohaaron** [ErikEJ/EFCorePowerTools#663]
I am trying to reverse engineer a SQLite database in a class library project that is part of a WPF application. I am running the reverse engineer on the class library project and when creating a new connection to my SQLite database file I am getting the following error.

Could not load file or assembly 'System.Data.SQLite, Version=1.0.113.0, Culture=neutral, PublicKeyToken=db937bc2d44ff139' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference.

It looks to me like I need to use System.Data.Sqlite 1.0.113.0 for the versions to match, but it's not available on Nuget. I downloaded it from https://system.data.sqlite.org/index.html/doc/trunk/www/downloads.wiki and manually installed it, but it didn't fix the error.

### Steps to reproduce

- Add SQLite/Compact Toolbox extension
- Add EF Core PowerTools extension
- https://github.com/ErikEJ/SqlCeToolbox/wiki/EF6-workflow-with-SQLite-DDEX-provider#install-sqlite-in-gac
- Download - Setups for 64-bit Windows (.NET Framework 4.6)
	- sqlite-netFx46-setup-bundle-x64-2015-1.0.113.0.exe
- Install System.Data.Sqlite 1.0.113.6 Nuget package in class library project. Version 1.0.113.0 is not listed in Nuget.
- Reverse Engineer from the SQLite database file
- Add connection to SQLite database file
	- Could not load file or assembly 'System.Data.SQLite, Version=1.0.113.0, Culture=neutral, PublicKeyToken=db937bc2d44ff139' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference.

### Further technical details

EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)

- EF Core Power Tools
Version 2.5.277.0

SQLite ADO.NET Provider included: 1.0.109.0
SQLite EF6 DbProvider in GAC - Yes

**System.Data.SQLite DDEX provider - No**
SQLite Simple DDEX provider - Yes

- SQL Toolbox
Version 4.7.670.0 - 1,668,302 downloads

SQL Server Compact 4.0 in GAC - No
SQL Server Compact 4.0 DbProvider - No

SQL Server Compact 4.0 DDEX provider - No
SQL Server Compact 4.0 Simple DDEX provider - Yes

SQL Server Compact 3.5 in GAC - No
SQL Server Compact 3.5 DbProvider - No

SQL Server Compact 3.5 DDEX provider - No

Sync Framework 2.1 SqlCe 3.5 provider - No

SQLite ADO.NET Provider included: 1.0.109.0
SQLite EF6 DbProvider in GAC - Yes
**System.Data.SQLite DDEX provider - No**
SQLite Simple DDEX provider - Yes

- Machine.config

```
<system.data>
<DbProviderFactories> 
    <add name="SQLite Data Provider" 
         invariant="System.Data.SQLite.EF6" 
         description=".NET Framework Data Provider for SQLite" 
         type="System.Data.SQLite.EF6.SQLiteProviderFactory, 
                System.Data.SQLite.EF6, 
                Version=1.0.113.0, 
                Culture=neutral, 
                PublicKeyToken=db937bc2d44ff139" 
    />  
</DbProviderFactories> 
</system.data>
```

Database engine: (SQlite, SQL Compact, SQL Server, Postgres)
SQLite

Visual Studio version: (e.g. Visual Studio 2017 15.7)
Visual Studio 2019 Version 16.8.3

**Comment by ErikEJ** [comment]
Look at and carefully follow the instructions here: https://github.com/ErikEJ/SqlCeToolbox/wiki/EF6-workflow-with-SQLite-DDEX-provider (install the x86 package, not the x64 one, for example!)

**Comment by mohaaron** [comment]
Hi Erik,

I have uninstalled the x64 version and installed sqlite-netFx46-setup-bundle-x86-2015-1.0.113.0.exe now. I still see that SQLite/Compact Toolbox and EF Core PowerTools show System.Data.SQLite DDEX provider - No in their help screen. I also can only find the nugget package System.Data.SQLite version 1.0.113.6. The only nuget package in version 1.0.113.0 that I see is System.Data.SQLite.EF6.

I'm not sure what I'm doing wrong.

**Comment by ErikEJ** [comment]
Based on past experience, you are not following caarefully all the steps in the guide (sorry, I did not create the Sqlite VS tools)

**Comment by mohaaron** [comment]
Erik,

The directions (https://github.com/ErikEJ/SqlCeToolbox/wiki/EF6-workflow-with-SQLite-DDEX-provider#install-sqlite-in-gac) don't say if the System.Data.SQLite DDEX provider - No in the help screen needs to say Yes. Can you clarify if this value needs to be Yes for the SQLite connection for reverse engineer to work? The functions of the SQLite/Compact Toolbox all work without issue.

**Comment by ErikEJ** [comment]
Yes, the DDEX provider must be installed.

**Comment by mohaaron** [comment]
Thank you for your help.

**Comment by ErikEJ** [comment]
You are welcome, sorry that connecting to SQLite is so complicated.

**Comment by ErikEJ** [comment]
With the latest daily build, you can avoid installing the provider!
