### ISSUE TITLE
Issue with comments in latest update

### ISSUE THREAD

**Issue by chassq** [ErikEJ/EFCorePowerTools#668]
### Steps to reproduce
We had a comment a the top of a model file from the last reverse engineer we did prior to the version updating (now 2.5.406). 

The old comment was:
`    /// <summary>
    /// Table contains category information for entities in the system (e.g. InventoryCategory).
    /// </summary>
`

The new comment is:
`    /// <summary>
    ///     /// Table contains category information for entities in the system (e.g. InventoryCategory).
    /// </summary>
`

Added extra triple slash to the comment it looks like. There was not a change in the db from the last reverse engineer. 

Just an fyi.

Thanks!

### Further technical details
Microsoft Visual Studio Enterprise 2019 Preview
Version 16.9.0 Preview 2.0
VisualStudio.16.Preview/16.9.0-pre.2.0+30803.129
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Enterprise

Visual C++ 2019   00435-60000-00000-AA196
Microsoft Visual C++ 2019

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   16.9.311.8738
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2057006+e0968ea4b5f5c523cc7efea1d91fec21e0adc648
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.9.311.8738
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.9.311.8738
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.6.3000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.9.311.8738
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.3000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

Bundler & Minifier   2.8.396
Adds support for bundling and minifying JavaScript, CSS and HTML files in any project.

C# Tools   3.9.0-2.20602.2+eb0a7ff1c241695e17b07b096593804fdd5cfcfd
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Entity Framework Core Power Tools   2.5
Adds useful design-time EF Core DbContext features to the Visual Studio Solution Explorer context menu. 

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

GhostDoc   20.2.20270.0
Generate XML Comments from your code, maintain clean and up-to-date documentation, produce help documentation in multiple formats, use intelligent source code Spell Checker in Visual Studio.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure HDInsight Azure Node   2.6.3000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.6.3000.0
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   16.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.6.3000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.31203.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   5.9.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62011.24130
Microsoft SQL Server Data Tools

SQLite & SQL Server Compact Toolbox   4.7
SQLite & SQL Server Compact Toolbox adds scripting, import, export, rename, query execution and much more to SQL Server Compact & SQLite Data Connections.

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.21120.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.9.0-2.20602.2+eb0a7ff1c241695e17b07b096593804fdd5cfcfd
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.9.0-beta.20567.7+c02b2ef997f1dd07993e1f85b017c858bdf82530
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Kubernetes   1.0
Visual Studio Tools for Kubernetes

Web Compiler   1.12.394
Compiler for LESS, Sass and CoffeeScript files

**Comment by ErikEJ** [comment]
There were no changes made in that area...

**Comment by chassq** [comment]
That is what we are seeing after the update.

**Comment by ErikEJ** [comment]
Let me check - can you provide a CREATE script with the extended properties included?

**Comment by chassq** [comment]
`
CREATE TABLE [scFile].[File] (
    [FileId]							BIGINT						CONSTRAINT [DF_scFile_File_FileId]		DEFAULT (NEXT VALUE FOR [scFile].[seqFile]) NOT NULL,
	[FileParentId]						BIGINT						NOT NULL,
	[Uid]								UNIQUEIDENTIFIER			CONSTRAINT [DF_scFile_File_Uid]			DEFAULT (newid()) NOT NULL,
    [FileTypeId]						INT							NOT NULL,	--Specifes a typed context for the file (e.g. Inventory Image, Evaluation Image or Not Specified).
	[FileStorageTypeId]					INT							NOT NULL,	--Specifies the files storage type.
	[FileName]							NVARCHAR(255)				NOT NULL,	--Human readable display name for file.
	[Description]						NVARCHAR(500)				NULL,		--Human readable display description for file.
	[FileStorageContainerInfo]			NVARCHAR(255)				NULL,		--Storage Container Info For the File.
	[FileContentType]					NVARCHAR(150)				NOT NULL,	--File Content Type (MIME).
	[FilePath]							NVARCHAR(1024)				NOT NULL,	--Reference path to a file resource.
	[FileLengthInBytes]					BIGINT						NOT NULL,	--Length of the file ref in bytes.	
	[SortOrder]							INT							CONSTRAINT [DF_scFile_File_SortOrder]	DEFAULT ((1)) NOT NULL,
    [IsActive]							BIT							CONSTRAINT [DF_scFile_File_IsActive]	DEFAULT ((1)) NOT NULL,
    [IsDeleted]							BIT							CONSTRAINT [DF_scFile_File_IsDeleted]	DEFAULT ((0)) NOT NULL,	
	[CopiedFromId]						BIGINT					    NULL,		--Id of File from which record was copied
    [ModifyUser]						BIGINT						CONSTRAINT [DF_scFile_File_ModifyUser]	DEFAULT (suser_id()) NOT NULL,
    [ModifyDate]						DATETIMEOFFSET (7)			CONSTRAINT [DF_scFile_File_ModifyDate]	DEFAULT (sysutcdatetime()) NOT NULL,
    [CreateUser]						BIGINT						CONSTRAINT [DF_scFile_File_CreateUser]	DEFAULT (suser_id()) NOT NULL,
    [CreateDate]						DATETIMEOFFSET (7)			CONSTRAINT [DF_scFile_File_CreateDate]	DEFAULT (sysutcdatetime()) NOT NULL,
	[SysStart]							DATETIME2 (7)				GENERATED ALWAYS AS ROW START HIDDEN NOT NULL,
	[SysEnd]							DATETIME2 (7)				GENERATED ALWAYS AS ROW END HIDDEN NOT NULL,
	PERIOD FOR SYSTEM_TIME ([SysStart], [SysEnd]),
    CONSTRAINT [PK_scFile_File] PRIMARY KEY CLUSTERED ([FileId] ASC),
	CONSTRAINT [FK_scFile_File_FileType] FOREIGN KEY ([FileTypeId]) REFERENCES [scFile].[FileType] ([FileTypeId]),
	CONSTRAINT [FK_scFile_File_FileStorageTypeId] FOREIGN KEY ([FileStorageTypeId]) REFERENCES [scFile].[FileStorageType] ([FileStorageTypeId]),
	CONSTRAINT [FK_scFile_File_Uid] UNIQUE ([Uid])
)
WITH (SYSTEM_VERSIONING = ON(HISTORY_TABLE=scFile.FileHist, DATA_CONSISTENCY_CHECK=ON));

GO
CREATE NONCLUSTERED INDEX [IX_scFile_File_FileTypeId]
    ON [scFile].[File]([FileTypeId] ASC);

GO
CREATE NONCLUSTERED INDEX [IX_scFile_File_FileStorageTypeId]
    ON [scFile].[File]([FileStorageTypeId] ASC);

GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', 
								@value = N'Table contains information for File Reference entites.', 
								@level0type = N'SCHEMA', @level0name = N'scFile', 
								@level1type = N'TABLE', @level1name = N'File';
`

**Comment by ErikEJ** [comment]
Unable to repro, and no changes made to this code since august 14.

**Comment by ErikEJ** [comment]
I have added a regression test to the codebase.
