### ISSUE TITLE
Return int type when stored procedure doing update and delete

### ISSUE THREAD

**Issue by mkidsc1603** [ErikEJ/EFCorePowerTools#669]
### Issue
A stored procedure like this:
```sql
CREATE PROCEDURE [spc_User_Update] (
   @parameters
) 
AS
BEGIN
   UPDATE user
      SET name = @NAME
    WHERE ID = @ID
END
```

C# After reverse engeineer => 
```csharp
 var db = new  DBContext();
 var sp = new DBContextProcedures();
 var result = sp.spc_User_Update(@ID,@NAME).Result; // **return empty class spc_User_UpdateResult , but expected int type**
```

issue:
How to return int type when stored procedure doing update,delete command?
Thank you 👍 

### Enviroment
EF Core Power Tools version: 2.5.406.0

Database engine: SQL Server 2017

Visual Studio version: vs 2019

**Comment by ErikEJ** [comment]
This is a breaking change in the latest version, what would you want to use the int value for?

**Comment by mkidsc1603** [comment]
In .net framework, I generate stored procedure code from .edmx file and it will return int type.
we tell update/delete success from the return int number > 0

Or there are other ways to achieve? 
Thank you for the prompt reply.

**Comment by ErikEJ** [comment]
Makes sense. @tiomny  - thoughts? Maybe differentiate between failure to get result set vs no result set at all?

**Comment by tiomny** [comment]
There is OutputParameter<int> returnValue = null.
It gets the result of executing SQL "EXEC @returnValue = ..."
@mkidsc1603 I believe this is exactly what you are looking for.

**Comment by ErikEJ** [comment]
@tiomny That did not work, does not return the number of rows affected.

**Comment by ErikEJ** [comment]
@tiomny PR created, would be grateful if you could have a look: https://github.com/ErikEJ/EFCorePowerTools/pull/672

**Comment by mkidsc1603** [comment]
@ErikEJ @tiomny  It's so nice,  thank you ! 💯
