### ISSUE TITLE
Ability to Save the Object Selection

### ISSUE THREAD

**Issue by surfpunkfl** [ErikEJ/EFCorePowerTools#673]
Latest release removed the save & load table selection from new selection interface. This is heavily used in my environment. Please consider adding back in.

EF Core Power Tools version: 2.5.406

Database engine: SQL Server

Visual Studio version: Visual Studio 2019

**Comment by ErikEJ** [comment]
Not needed any more, the table selection is saved in the efpr.config.json, and you can have multiple of these in the project.

**Comment by ErikEJ** [comment]
Docs here: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#using-multiple-dbcontexts-in-the-same-project 

Please feel free to re-open if docs are unclear
