### ISSUE TITLE
Renaming feature (Table name and ColumnName) is not working post update in EF Core Power Tool for MySql

### ISSUE THREAD

**Issue by phaniaaduri** [ErikEJ/EFCorePowerTools#676]
Table Name and column name changes are not reflecting as given in “efpt.renaming.json”. We are expecting table name change from “departmentdetail” to “DepartmentDetail”. 

### Steps to reproduce
1.	Create table as per below details
`create database department;`
`create table department.departmentdetail1(
id int,
departmentname varchar(20)
)`

2.	Create .NetCore Console App and Generate Context and Models using power tool as per below screenshot
![image](https://user-images.githubusercontent.com/5255424/102767107-1a9b9200-43a5-11eb-95fb-695b79a88b21.png)

3.	Added “efpt.renaming.json” in project path and added below code
`[
   {
     "SchemaName": "department",
      "Tables": [
        {
          "Name": "departmentdetail",
          "NewName": "DepartmentDetail",
          "Columns": [
            {
              "Name": "departmentname",
              "NewName": "DepartmentName"
            }
          ]
        }
      ],
      "UseSchemaName": false
   }
]`
4.	Re-run the power tool, still we could see there is no change in Class and Property name
![image](https://user-images.githubusercontent.com/5255424/102767249-43bc2280-43a5-11eb-98c6-c9a232a8f943.png)
5.	Renaming was working previously as per the expectation before(Last scaffolding was done on **11th November 2020**) the update in Tool. SchemaName was not mentioned in the “efpt.renaming.json”, PFB screenshot of old file. In latest update if we don’t send SchemaName we get error while running tool as “Object reference Not Set to an instance”
![image](https://user-images.githubusercontent.com/5255424/102767458-9990ca80-43a5-11eb-9762-da73bc5b0f0a.png)

### Further technical details
1.	 EF Core Power Tools version: 2.5.406
2.	 Database engine: MySQL  V8
3.	MySQL for Visual Studio 1.2.9
4.	MySQL Connector Net 8.0.20
5.	Visual Studio version: Visual Studio 2019 16.8.3
6.      EF Core 3.1.8

**Comment by ErikEJ** [comment]
Try with schemaname: null,

**Comment by phaniaaduri** [comment]
I tried passing null, i get below error while running powertool
`System.NullReferenceException: Object reference not set to an instance of an object.
   at EFCorePowerTools.ViewModels.ObjectTreeViewModel.<>c__DisplayClass20_1.<AddObjects>b__2(Schema c) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\ViewModels\ObjectTreeViewModel.cs:line 146
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at EFCorePowerTools.ViewModels.ObjectTreeViewModel.AddObjects(IEnumerable`1 objects, IEnumerable`1 customReplacers) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\ViewModels\ObjectTreeViewModel.cs:line 146
   at EFCorePowerTools.ViewModels.PickTablesViewModel.AddObjects(IEnumerable`1 objects, IEnumerable`1 customReplacers) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\ViewModels\PickTablesViewModel.cs:line 112
   at EFCorePowerTools.Dialogs.PickTablesDialog.EFCorePowerTools.Contracts.Views.IPickTablesDialog.AddTables(IEnumerable`1 tables, IEnumerable`1 customReplacers) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Dialogs\PickTablesDialog.xaml.cs:line 59
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirstAsync>d__3.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 156`

**Comment by ErikEJ** [comment]
Please share your renaming file (as text, not s screenshot)

**Comment by ErikEJ** [comment]
Could you also share a screenshot of your table selection dialog?

**Comment by phaniaaduri** [comment]
[
   {
      "SchemaName": null,
      "Tables": [
         {
            "Columns": [
               {
                  "Name": "departmentname",
                  "NewName": "DepartmentName"
               }
            ],
            "Name": "departmentdetail",
            "NewName": "DepartmentDetail"
         }
      ],
      "UseSchemaName": false
   }
]

**Comment by phaniaaduri** [comment]
> Could you also share a screenshot of your table selection dialog?
If i pass SchemaName null then i wont get table selection dialog, it will throw error as soon i start reverse engineering, for below one i had passed schemaname as department
![image](https://user-images.githubusercontent.com/5255424/102774472-137a8100-43b1-11eb-9c63-65528d8a805a.png)

**Comment by ErikEJ** [comment]
It is a bug, I will provide a fix - could you also share your efpt.config.json file, thanks ?

**Comment by phaniaaduri** [comment]
> It is a bug, I will provide a fix - could you also share your efpt.config.json file, thanks ?

{
   "ContextClassName": "DepartmentContext",
   "ContextNamespace": null,
   "DefaultDacpacSchema": null,
   "FilterSchemas": false,
   "IncludeConnectionString": false,
   "ModelNamespace": null,
   "OutputContextPath": null,
   "OutputPath": null,
   "ProjectRootNamespace": "DepartmentTest",
   "Schemas": null,
   "SelectedHandlebarsLanguage": 0,
   "SelectedToBeGenerated": 0,
   "Tables": [
      {
         "Name": "departmentdetail",
         "ObjectType": 0
      }
   ],
   "UseDatabaseNames": false,
   "UseDbContextSplitting": false,
   "UseFluentApiOnly": false,
   "UseHandleBars": true,
   "UseInflector": true,
   "UseLegacyPluralizer": false,
   "UseNodaTime": false,
   "UseSpatial": false
}

**Comment by ErikEJ** [comment]
Fixed in latest daily build, thanks for reporting this

**Comment by phaniaaduri** [comment]
> Fixed in latest daily build, thanks for reporting this

Thanks @ErikEJ for quick response, I have verified the changes, its working as expected for table name changes
