### ISSUE TITLE
[Feature] Add hbs supporting for the "{entityName}Configuration : IEntityTypeConfiguration<{entityName}>" class, if not present.

### ISSUE THREAD

**Issue by craigskeat** [ErikEJ/EFCorePowerTools#678]
I've seen hard-coded manner in src\GUI\RevEng.Core\DbContextSplitter.cs,
that generates the split entity configuration cs file.
I'm not so sure hbs is currently supported by now.

I'm requesting this feature if not present.
♥

### Further technical details
EF Core Power Tools version: 2.5.406.0

Database engine: SQL Server

Visual Studio version: Visual Studio 2019 16.9.0 Preview 1.0

**Comment by ErikEJ** [comment]
This is something that should be done in the Handlebars library, and I am unsure that it is likely to happen, given the current hacky implementation
@tonysneed
