### ISSUE TITLE
Renaming feature (ColumnName) is not working post update in EF Core Power Tool for MySql

### ISSUE THREAD

**Issue by phaniaaduri** [ErikEJ/EFCorePowerTools#679]
### Steps to reproduce
1.	Create table as per below details
create database department;
create table department.departmentdetail(
Id int,
DepartmentName varchar(20),
DEPTCode varchar(20)
)
2.	Create .NetCore Console App and Generate Context and Model using power tool as per below screenshot
 
![image](https://user-images.githubusercontent.com/5255424/102856061-d6af9800-444b-11eb-96dc-156b2811d497.png)

3.	Added “efpt.renaming.json” in project path and added below code

```
[
   {
      "Tables": [
         {
          "Columns": [
            {
              "Name": "DEPTCode",
              "NewName": "DEPTCode"
            }
          ],
            "Name": "departmentdetail",
            "NewName": "DepartmentDetail"
         }
      ],
      "UseSchemaName": false
   }
]
```
4.	Re-run the power tool, still we could see there is no change in Property name
 
![image](https://user-images.githubusercontent.com/5255424/102856115-e9c26800-444b-11eb-8544-0a145740f4f9.png)

Once reverse engineering is completed, renaming file is getting overwritten as below, we can see change in Table name, but not for column name
 
![image](https://user-images.githubusercontent.com/5255424/102856144-f1820c80-444b-11eb-8da9-b87d02742224.png)

5.	Renaming was working previously as per the expectation before the update in Tool(Last scaffolding was done on 11th November 2020). 

### Further technical details
1.	 EF Core Power Tools version: 2.5.406
2.	 Database engine: MySQL  V8
3.	MySQL for Visual Studio 1.2.9
4.	MySQL Connector Net 8.0.20
5.	Visual Studio version: Visual Studio 2019 16.8.3
6.	EF Core 3.1.8

**Comment by ErikEJ** [comment]
The new and old names are the same !?

**Comment by phaniaaduri** [comment]
> The new and old names are the same !?

yes, because in models generated its not coming as it is in database
![image](https://user-images.githubusercontent.com/5255424/102860473-f3e86480-4453-11eb-8eba-6241dbc70c11.png)

**Comment by ErikEJ** [comment]
Could you try with:

```
 "Columns": [
            {
              "Name": "DeptCode",
              "NewName": "DEPTCode"
            }
          ],
```

**Comment by phaniaaduri** [comment]
I tried that, but no luck

**Comment by ErikEJ** [comment]
I have to think about a good solution, in the meantime you must fix manually

**Comment by phaniaaduri** [comment]
Is it possible to get older version- 2.5.277? as this requirement was working perfectly fine with that version

**Comment by ErikEJ** [comment]
Yes, but that is just a stop gap solution.

**Comment by ErikEJ** [comment]
Fixed in latest daily build

**Comment by ErikEJ** [comment]
@sm15455 FYI - Had not seen this coming!!

**Comment by phaniaaduri** [comment]
Thank you so much @ErikEJ  for fixing issue quickly, it saved our manual effort. One observation i would like to highlight here, post running reverser engineering renaming file is overwritten and i could see redundancy in file. PFB renaming files

Before running reverse engineering
[
   {
      "Tables": [
         {
            "Columns": [
               {
                  "Name": "DEPTCode",
                  "NewName": "DEPTCode"
               }
            ],
            "Name": "departmentdetail",
            "NewName": "DepartmentDetail"
         },
         {
            "Columns": [
               {
                  "Name": "EMPCode",
                  "NewName": "EMPCode"
               }
            ],
            "Name": "employeedetail",
            "NewName": "EmployeeDetail"
         }
      ],
      "UseSchemaName": false
   }
]


After running reverse engineering
[
   {
      "Tables": [
         {
            "Columns": [
               {
                  "Name": "DEPTCode",
                  "NewName": "DEPTCode"
               },
               {
                  "Name": "EMPCode",
                  "NewName": "EMPCode"
               }
            ],
            "Name": "departmentdetail",
            "NewName": "DepartmentDetail"
         },
         {
            "Columns": [
               {
                  "Name": "DEPTCode",
                  "NewName": "DEPTCode"
               },
               {
                  "Name": "EMPCode",
                  "NewName": "EMPCode"
               }
            ],
            "Name": "employeedetail",
            "NewName": "EmployeeDetail"
         }
      ],
      "UseSchemaName": false
   }
]

**Comment by ErikEJ** [comment]
Thanks for the heads up - looks like a minor issue, I will look into that.

BTW: Please use the code formatting when posting json and c# code.

**Comment by sm15455** [comment]
> 
> 
> @sm15455 FYI - Had not seen this coming!!

I definitely didn't see this coming. Looks like an aggressive StringComparison.OrdinalIgnoreCase issue to me. Glad you fixed it.

**Comment by phaniaaduri** [comment]
> Thanks for the heads up - looks like a minor issue, I will look into that.
> 
> BTW: Please use the code formatting when posting json and c# code.

Sure!!!

**Comment by ErikEJ** [comment]
"Redundancy" issue fixed in latest daily build, you have to manually remove once.
