### ISSUE TITLE
Reverse engineer SQLite database datatype conversion

### ISSUE THREAD

**Issue by mohaaron** [ErikEJ/EFCorePowerTools#683]
I have a SQL Server database with tables using decimal(18,0) column types. I am using the Toolbox to convert the SQL database into a SQLite database where the column type becomes numeric(18,0). Then I'm using EF Core PowerTools to reverse engineer the SQLite database into entities to use in my WPF project. For some reason, the numeric types are being converted to byte[] type properties on my ef core models. This is causing problems. I've done some looking and notice that there are some SQLite float type columns that are being converted into .net double property types. Why are the numeric types converted to bytes?

### Steps to reproduce
I haven't made another project to reproduce this issue, but I will if needed.

### Further technical details
Toolbox/Power Tools version: (found in About dialog - blue questionmark icon)
- ToolBox
Version 4.7.670.0

SQL Server Compact 4.0 in GAC - No
SQL Server Compact 4.0 DbProvider - No

SQL Server Compact 4.0 DDEX provider - No
SQL Server Compact 4.0 Simple DDEX provider - Yes

SQL Server Compact 3.5 in GAC - No
SQL Server Compact 3.5 DbProvider - No

SQL Server Compact 3.5 DDEX provider - No

Sync Framework 2.1 SqlCe 3.5 provider - No

SQLite ADO.NET Provider included: 1.0.109.0
SQLite EF6 DbProvider in GAC - Yes
System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes

- PowerTools
Version 2.5.406.0

SQLite ADO.NET Provider included: 1.0.109.0
SQLite EF6 DbProvider in GAC - Yes

System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes

Database engine: (SQlite, SQL Compact or SQL Server)
SQL Server -> SQLite

Visual Studio or SSMS version: (e.g. Visual Studio 2017 15.3, SSMS 17.3)
Visual Studio 16.8.3

**Comment by mohaaron** [comment]
After doing some digging I've found this post on the EF Core Github repo. https://github.com/dotnet/efcore/issues/8824#issuecomment-372715916. This makes it sound to me like it's expected that reverse engineered models will have to be manually adjusted afterwords.

**Comment by ErikEJ** [comment]
SQLite only has a very limited number of "data types"
