### ISSUE TITLE
Many to may representation in Model Diagram

### ISSUE THREAD

**Issue by LucVK** [ErikEJ/EFCorePowerTools#687]
The representation of one of the many-to-many relationships is not as expected. (see attached file). 
This is only the case for one of the multiple many-to-many relationships in the schema.
![mmrel](https://user-images.githubusercontent.com/350118/103216169-b2552f00-4915-11eb-9c78-514cd6f16279.gif)

If required I can provide the source code for the entities and dbcontext classes.

EF Core Power Tools version: 2.5.406.0

Database engine: (SQL Server)

Visual Studio version: (e.g. Visual Studio 2019 6.8.3)

**Comment by ErikEJ** [comment]
A simplified repro (with a minimum amount of entities) would be great, thanks.

**Comment by LucVK** [comment]
This archive contains the entity classes and the dbcontext.  (some classes still need to be optimized - it's still work in progress)

[sp.zip](https://github.com/ErikEJ/EFCorePowerTools/files/5747467/sp.zip)


> A simplified repro (with a minimum amount of entities) would be great, thanks.

**Comment by LucVK** [comment]
Forgot the classes for entity localization support.

[sp.zip](https://github.com/ErikEJ/EFCorePowerTools/files/5747501/sp.zip)
