### ISSUE TITLE
Proposals: Options to remove default constructor from generated code

### ISSUE THREAD

**Issue by sm15455** [ErikEJ/EFCorePowerTools#692]
When an entity is generated, the default constructor is added. In some cases, especially in DDD approach, this behavior is not correct. Having the option to remove the default constructor gives us the possibility to create only the constructors we need.

I have investigated a bit and this feature could be added by creating a class that inherits from **CSharpEntityTypeGenerator** and overrides **GenerateConstructor** method. 
https://github.com/dotnet/efcore/blob/68d54dd79a798ff85f91778897087aa85de00c0e/src/EFCore.Design/Scaffolding/Internal/CSharpEntityTypeGenerator.cs#L233

**Comment by ErikEJ** [comment]
I am not so sure about the idea of mixing DDD concerns with POCO code generation. But if it was an advanced option, maybe...

**Comment by sm15455** [comment]
You're right about DDD, not the best example. I was exactly thinking about an advanced option.

**Comment by ErikEJ** [comment]
- Exclude entity constructors
- Exclude entity navigations
