### ISSUE TITLE
The file created when Add DbContext Model Diagram is clicked stored in the project. Is there a way to specify the folder location? 

### ISSUE THREAD

**Issue by prince272** [ErikEJ/EFCorePowerTools#694]
The file created when Add DbContext Model Diagram is clicked saved in the project. Is there a way to specify the folder location inwhich the file should be saved? 

### Steps to reproduce
Right click on the project were the dbcontext is configured and click "Add DbContext Model Diagram". the dbcontext.dgml is created inside the root of the project. how to specify a folder to store the generated file instead.

### Further technical details
EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)

Database engine: (SQlite, SQL Compact, SQL Server, Postgres)

Visual Studio version: (e.g. Visual Studio 2017 15.7)

**Comment by ErikEJ** [comment]
There is no way to specify an alternate location, but you can move the file anywhere you want. If you want more control, you can use the Nuget package.

**Comment by prince272** [comment]
Thanks
