### ISSUE TITLE
[Feature] Support Stored Procedures and Functions for other providers

### ISSUE THREAD

**Issue by pgkdev** [ErikEJ/EFCorePowerTools#697]
Tested EF Core Power Tools to reverse engineer an Oracle Database, I was able to create models for tables and views but **not for Stored Procedures included in Oracle Packages.**

### Steps to reproduce
Create Oracle Database with a Package and a Stored procedure.
Using EF Core Power Tools, try to reverse engineer to create model for Stored Procedure inputs and outputs.
(Maybe it only supports SQL Server SPs for now, like shown in project pages, but Oracle support for SPs will be implemented soon? Need it, thanks :)

### Further technical details
EF Core Power Tools version: 5.2.406

Database engine: Oracle XE 184 Win64

Visual Studio version: (e.g. Visual Studio 2019 16.8.3)

**Comment by ErikEJ** [comment]
Not something I plan to implement, as I no nothing about Oracle, and had no test server. 

But a PR would be welcome, if you want to do that, I can provide more implementation details.

**Comment by pgkdev** [comment]
Unfortunately I don't have the time and the knowledge to implement a complicated piece of software like this.

I was liking so much this tool, it seem perfect but then notice this missing feature for Oracle, and I have lots of SPs :s
Do you have some alternative solution for this?

Thanks and great project "EF Core Power Tools".

**Comment by ErikEJ** [comment]
It is actually not that complicated. But maybe someone else can step up @ProH4Ck ?

**Comment by ProH4Ck** [comment]
Ok... I'll check in the next few days if this is possible but I remember that something is not yet implemented in Oracle EF Core provider (UDTs for example)...
I need to check if basic stored procedures work and if they'll work, I'll add support to EF Core Power Tools.

**Comment by ErikEJ** [comment]
Fantastic! Feel free to ask me for implementation suggestions/advice.

**Comment by Giorgi** [comment]
In Oracle, it is common to group stored procedures and functions in packages. In the project that I had to deal with Oracle, I had a separate static class for each Oracle package that contained an extension method on `DbContext` for every sproc/function found in that package.

I can help with adding support for Oracle too.

**Comment by ErikEJ** [comment]
I would prefer an implementation that resembles the SQL Server implementation as closely as possible

**Comment by Giorgi** [comment]
How do you deal with sprocs that have the same name but have different schema?

**Comment by ErikEJ** [comment]
Specify the schema name when calling them...

But I think schema may mean something completely different in Oracle

**Comment by Giorgi** [comment]
Yes, the schema is a different thing in Oracle. In Oracle, you can have sprocs with the same name but in different packages. Specifying the package name every time you call a sproc means having to type it manually, but we can have it generated by grouping the sprocs in separate classes instead of having one giant class holding all sprocs/functions.

**Comment by ErikEJ** [comment]
Ah, I think I get your question now. I name the method SchemaMethodName if there are duplicates.

Have a look at the current implementation.

**Comment by Giorgi** [comment]
I see. Well, I would prefer to have 

```cs
var procedures = new NorthwindContextProcedures(db);
procedures.SchemaName.SprocName(param1, "param2");
```

But I guess it's too late to change? It would help clean up intellisense too.

Also, what do you think about returning a tuple when the sproc has multiple output parameters instead of using `OutputParameter`?

**Comment by ErikEJ** [comment]
It is actually SprocnameSchemaname.

Tuples would be a breaking change as well, and changing the API is also not what this feature is about.

**Comment by pgkdev** [comment]
> In Oracle, it is common to group stored procedures and functions in packages. In the project that I had to deal with Oracle, I had a separate static class for each Oracle package that contained an extension method on `DbContext` for every sproc/function found in that package.
> 
> I can help with adding support for Oracle too.

**Comment by pgkdev** [comment]
> In Oracle, it is common to group stored procedures and functions in packages. In the project that I had to deal with Oracle, I had a separate static class for each Oracle package that contained an extension method on `DbContext` for every sproc/function found in that package.
> 
> I can help with adding support for Oracle too.

I can confirm this, we have Procedures and Functions in packages.

**Comment by ErikEJ** [comment]
@pgkdev why was this closed?

**Comment by ErikEJ** [comment]
I think you must try to implement something, or explain with examples, my Oracle knowledge is zero.

**Comment by pgkdev** [comment]
> @pgkdev why was this closed?

It was a click mistake, sorry :s

**Comment by pgkdev** [comment]
> I think you must try to implement something, or explain with examples, my Oracle knowledge is zero.

It's +- like me, I'm using what other IT team provided for Oracle DB schema. But noticed that, stored procedures inside packages.

**Comment by pgkdev** [comment]
@ProH4Ck any news on the implementation? 
Need that :)

**Comment by kevinvenclovas** [comment]
Is someone working on this issue? I need this for my projekt now otherway i need to use a other framework/tool

**Comment by ErikEJ** [comment]
No, this issue needs help from experts in the various RDBMS systems.

**Comment by kevinvenclovas** [comment]
Oke thanks. Is there a workaround?
Is there a option to execute a raw sql string to execute my procedur?

**Comment by ErikEJ** [comment]
Sure, you can just hand code what the stored procedure mapping does (run against a SQL Server db, or see the code in the GitHub repo ( in the ScaffoldingTester project)

**Comment by ErikEJ** [comment]
Closing and moving to Backlog milestone

**Comment by ErikEJ** [comment]
@andrewdci03 Correct, only SQL Server / Azure SQL stored procedures are supported, but I am willing to help anyone with a PR

**Comment by ErikEJ** [comment]
I am going to close this general issue, and wait for community PRs now that I have implemented Postgres stored function / stored procedure support (and laid the groundwork for others)

**Comment by MPITech** [comment]
Hello.  I think this issue is the latest one discussing MySql stored procedures.  I would contribute to the developer if stored procedures in MySql databases were implemented.  I was just checking this extension out for the first time but it looks like we can't use it for SPs in MySql.  Is this still the case or am I missing something?  Thanks a lot, and forgive me if this is covered elsewhere, I cannot find it.

**Comment by ErikEJ** [comment]
@MPITech Correct, Mysql stored procedures are not supported at the moment.

**Comment by ErikEJ** [comment]
Postgres stored procedures are now supported
