### ISSUE TITLE
Add ability to control which data annotations are auto-generated.

### ISSUE THREAD

**Issue by ccrookston** [ErikEJ/EFCorePowerTools#702]
When I select the option to add Data Annotations to my reversed engineered models, I would like some control over which annotations are created. At the very least, two options would be awesome:

1) [Key] only
2) All

But even better would be the ability to approve or block each possible annotation type.

This request stems from this SO post:
https://stackoverflow.com/questions/65589003/how-to-control-dataannotations-when-using-scaffold-dbcontext/65592535#65592535

And that SO post is the result of this one, which describes the root of the issue:
https://stackoverflow.com/questions/65588487/an-object-or-column-name-is-missing-or-empty-for-select-into-statements-verify

Please let me know if any more details are needed.

Thank you!

**Comment by ErikEJ** [comment]
Should this be fixed in SimpleCRUD perhaps?

**Comment by ErikEJ** [comment]
"All" is already an option, btw.

**Comment by ErikEJ** [comment]
It look like SimpjeCRUD is not very well maintained.

**Comment by ccrookston** [comment]
"It looks like SimpjeCRUD is not very well maintained."

You are correct that SimpeCRUD is not well maintained. That's a bummer. I have my own NUGET package that depends on SimpeCRUD: Dapper.SimpleRepository. I may have to swap out SimpeCRUD for something else. Or become a contributor and fix it myself. Originally, a lot of truly wonderful work was put into this.

"All" is already an option, btw."

Good point. Right now the options are "All" or "None". A third option for "Only [Key]" would be wonderful.

**Comment by ErikEJ** [comment]
what if a database column has a name that is not a valid c# identifier, would it not be useful to have the 

```csharp
[Colum(Name = "La la"]
public string Lala { get; set;}

```

**Comment by ccrookston** [comment]
Overall, yes. For sure.
And again, it would be nice to have the option to use it or not.

**Comment by ErikEJ** [comment]
Given the background and discussion here, this is not something I plan to implement.

**Comment by ccrookston** [comment]
Understood. Thank you. I will do my best to resolve it w/ Dapper.SimpleCrud.

**Comment by ErikEJ** [comment]
I would just include the SimpleCrud .cs in your own repo, and then get the bug fixed.

**Comment by ccrookston** [comment]
Done. Thanks for the suggestion.
