### ISSUE TITLE
Use Schema compare lib

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#706]
https://github.com/JonPSmith/EfCore.SchemaCompare 

@jonpsmith

**Comment by JonPSmith** [comment]
Hi @ErikEJ,

I see you have found my new EfSchemaCompare. Finally made it into its own library because it was getting really complex, especially with EF Core 5. 

Is there any reason for the issue?

**Comment by ErikEJ** [comment]
Yes, considering adding it as a feature to EF Core Power Tools...

**Comment by JonPSmith** [comment]
I feel honoured that you would want to do that.

First thoughts: Should be find but to be useful users need to be able to ignore certain errors. I allow the user to ignore certain error, either because EfSchemaCompare gets wrong (e.g currently required Owned type), can't check (I put out a NOT CHECKED error for `ToSqlQuery` mapping), or errors they don't care about. 

You might want to add that same feature to your app. Let them put the error strings into a file, rather like you remembering the setting for their reverse engineering.

PS. Currently updating all my libraries to EF Core 5 and going though loads of work on the book to get to publication. Sometime I hope to improve EfSchemaCompare later (see [my current issue](https://github.com/dotnet/efcore/issues/23758)).

**Comment by ErikEJ** [comment]
Initially, i just want to display the result of the compare...

**Comment by JonPSmith** [comment]
Good start. See what people think.

**Comment by sm15455** [comment]
@ErikEJ great idea. Let me know of you need help with the UI

**Comment by ErikEJ** [comment]
@sm15455 sure, please think about it, the output from it is quite RAW.

**Comment by sm15455** [comment]
Glad to help. I won't be able to give it a look before the end of the month. I have a deadline and a conference 29th. After that I'm all yours :D

**Comment by JonPSmith** [comment]
> @sm15455 sure, please think about it, the output from it is quite RAW.

EfCore.SchemaCompare's `CompareEfSql` has a `Logs` property that returns a list of `CompareLog` which contain the detailed information uses to create the text output. For unit testing text output is the best approach as it can be output to the xRunner's window, but if you want to build something more visual then that's possible.

**Comment by ErikEJ** [comment]
@JonPSmith Perfect, I was just looking at `GetAllErrors`  - I am thiniking about showing some kind of dialog with the errors, potentially with a Save function, that just uses `GetAllErrors`

**Comment by sm15455** [comment]
@ErikEJ at last I'm free from urgent business and conferences and will be able to help with this task. What experience do you want to give to end users?

**Comment by ErikEJ** [comment]
Sounds great! I have not given it much thought yet, some useful info from a list of `CompareLog` entries

**Comment by sm15455** [comment]
I have given a look at the EfSqCompare tool response. 
I have seen the NOT IN DATABASE for table, columns, index. I guess there are other messages for difference between column/property types, different index columns, different  primary key columns, missing primary key columns and so on. Do we have a list of all possible errors so that I can recreate them in my database analyze them and create UI?

**Comment by JonPSmith** [comment]
Hi guys, 

Here are some info/links that should help you:

* The README file has all the documentation, especially look at
  * [What does EfSchemaCompare check?](https://github.com/JonPSmith/EfCore.SchemaCompare/blob/master/README.md#what-does-efschemacompare-check)
  * [Understanding the error messages](https://github.com/JonPSmith/EfCore.SchemaCompare/blob/master/README.md#understanding-the-error-messages)
* The [CompareLog class](https://github.com/JonPSmith/EfCore.SchemaCompare/blob/master/EfSchemaCompare/CompareLog.cs) contains enums for all the errors - especially look at the `CompareAttributes ` enum
* The `CompareEfSql` class, which contains the method(s) to do the compare has a `Logs` property which contains all the check/steps it goes through. 
   * Any log that doesn't have a `State` of `Ok` is an error
   * The logs are hierarchical, e.g. an log with a `Type` of `DbContext` will have a `SubLogs` containing `Entity`s , will have a `SubLogs` containing `Property`s. 
   * The last top level log is of type `Database` - unlike the other logs it only contains errors.

I think that's a good starting point.

**Comment by sm15455** [comment]
@JonPSmith thank you for the info. @ErikEJ should we create a new exe for this feature or reuse efpt?

**Comment by ErikEJ** [comment]
@sm15455 Assume that efpt provides a list of Comparelogs.

**Comment by sm15455** [comment]
@JonPSmith I have a strange behavior when a DbSet points to a table that doesn't exists on the database. The compare fails with a KeyNotFoundException, The key not found is the table name. Do you want me to open an issue in the issue tracker of your project?

**Comment by JonPSmith** [comment]
Yes please. Especially include the stacktrace and the version you are using. Thanks.

**Comment by JonPSmith** [comment]
I did a very simple delete of a table and I didn't get an exception. Therefore can you provide a complete code solution that fails. Thanks.

**Comment by sm15455** [comment]
I opened an issue on your side with a complete example. Hope this helps.

**Comment by JonPSmith** [comment]
Thanks. Fixed and issued to NuGet.

I just wanted to point out that the EfCore.SchemaCompare only works with EF Core 5. I know that EFCorePowerTools works with other versions of of EF Core so I thought I should point that out.

**Comment by sm15455** [comment]
Tested the new package and everything works now. Thanks.
I think that the EFCore-5-only feature is something will emphasize in UI and maybe docs.

**Comment by ErikEJ** [comment]
I check the installed EF Core version in the project, so it is easy to make clear that only 5 is supported.

**Comment by sm15455** [comment]
@ErikEJ do you think we should show only the differences between database and context? Or maybe we should show everything and give an option to show differences only?

**Comment by ErikEJ** [comment]
Not sure what you mean by your last sentence, but what about differences with an option to show everything?

**Comment by sm15455** [comment]
That's what I was thinking about.

**Comment by sm15455** [comment]
@ErikEJ I created the UI. Now I need to clean up code and integrate with efpt. Do you want me to push the code on the master branch or maybe another branch?

![image](https://user-images.githubusercontent.com/5398631/107113758-4396ba00-6861-11eb-8f7d-2698d1bbc9b6.png)
![image](https://user-images.githubusercontent.com/5398631/107113779-704ad180-6861-11eb-994a-c3b82f7f80e4.png)

**Comment by sm15455** [comment]
@ErikEJ  I created the UI. Now I need to clean up code and integrate with efpt. Do you want me to push the code on master branch or maybe another branch?

![image](https://user-images.githubusercontent.com/5398631/107113869-139be680-6862-11eb-9f49-3c4796edba9b.png)
![image](https://user-images.githubusercontent.com/5398631/107113866-04b53400-6862-11eb-9f10-c937ad53e528.png)

**Comment by ErikEJ** [comment]
Beautiful! 
I can integrate with efpt.

Have you integrated with the project context menu? If not, I can also do that.

Just create a PR...

**Comment by sm15455** [comment]
I integrated with project context menu. It Just needs efpt integration. I'll create a PR and leave that to you

**Comment by ErikEJ** [comment]
Perfect! Thanks.

**Comment by JonPSmith** [comment]
Looks good @sm15455 ! One question - what do you show when there are no differences, as that will be the typical output.

**Comment by sm15455** [comment]
The grid is hidden and a message is shown.
