### ISSUE TITLE
Migrations Tool and modelling should handle separate startup project & migrations project

### ISSUE THREAD

**Issue by karam94** [ErikEJ/EFCorePowerTools#707]
Hi,

Sometimes the scenario may occur where one may have their migrations & DbContext in a separate project to their application's Startup.cs.

For example the usual solution would be to use:
`dotnet ef migrations add AddDogModel --startup-project ./IdentityTest/ --project ./IdentityTest.Infrastructure/`

At the moment, the Migrations Tool first asks for manual setting of the Migrations Assembly within Startup.cs such as:
```
var migrationsAssemblyName = "IdentityTest.Infrastructure";
services.AddDbContext<ApplicationDbContext>(options =>
                options.UseSqlServer(
                    Configuration.GetConnectionString("DefaultConnection"),
                    b => b.MigrationsAssembly(migrationsAssemblyName)));
```

Upon doing this, it eventually leads to another error message asking for it to be switched back to - in this case - `IdentityTest` as that is the solution where the Migrations Tool has to be invoked in.

I don't think this is a bug as such, rather maybe the lack of a feature?
Therefore could it possibly be a feature to be added in the future to support specification of the startup project & migrations project?

Thanks!

**Comment by ErikEJ** [comment]
Are you referring to the command line tool?

**Comment by karam94** [comment]
> Are you referring to the command line tool?

Nope sorry, I'm referring to the Visual Studio extension.

**Comment by ErikEJ** [comment]
Ah - yes, it is something I have considered, but never got around to (there were some challenges):
https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/EFCorePowerTools/Handlers/ProcessLauncher.cs#L99

**Comment by ErikEJ** [comment]
@karam94 Can you share a repro project?

**Comment by ErikEJ** [comment]
I have attempted a fix in the latest daily build, can you verify it?
