### ISSUE TITLE
Proposals: Add Ignore columns, Include columns, Read-only mode.

### ISSUE THREAD

**Issue by Lechus** [ErikEJ/EFCorePowerTools#708]
1) I do not see an option that says something like: Exclude these columns (by a name) from all tables/views when generating code.
Need to do it manually at the moment.

So got a property like:
                entity.Property(e => e.MsreplTranVersion)
                    .HasDefaultValueSql("(newid())")
                    .HasComment("REPLICATION COLUMN");

2) Add option to not EXCLUDE columns, but to INCLUDE? So that will generate only required columns.

3) Add option generate Read-only mode?
That will not add unnecessary properties and settings, and could add NoTracking things, etc.?

### Steps to reproduce
Click to reverse db, EF 5 mode;

### Further technical details
EF Core Power Tools version: 2.5.454.0.

Database engine: SQL Server

Visual Studio version:  Visual Studio 2019 16.8.1

**Comment by ErikEJ** [comment]
Thanks! 
re 1: You could create a tool to do this (to manipulate the efpt.config.json file).

If there was a GUI option, how would that look?

re 3: see https://github.com/dotnet/efcore/issues/7586

**Comment by sm15455** [comment]
@ErikEJ I was thinking about point 1 and 2. Maybe we could improve search and selection in the objects page.
We could expand search capabilities enabling the user to search by multiple strings by dividing words using a special char (maybe a comma). For instance, if I want to search orderid and customerid, I could enter "orderid, customerid". We could also add options to enable user to select the search type (starts with, equals, ends with, include, exclude, threat string as regex). 
As for selection capabilities, so far, when the user select a node with children, the selection/deselection is reflected on all children (visible or not). We could improve selection to let it work on visible objects only (of course the user should enable such options).
The problem I see with this improvements is that UI would get a bit more complicated. 
Any thought?

**Comment by ErikEJ** [comment]
I would like to see more votes for this, but some sort of simple filtering capability would probably fit the bill.

**Comment by sm15455** [comment]
I'll try to create something and will show you the result.

**Comment by ErikEJ** [comment]
Sounds great!

**Comment by sm15455** [comment]
The image is self explanatory. The regular expression mode should cover all advanced search needs.

![image](https://user-images.githubusercontent.com/5398631/107999234-3c04ad00-6fe7-11eb-9707-e582e706b21f.png)

**Comment by ErikEJ** [comment]
Simple and elegant - and should cover both 1 and 2 here @Lechus

**Comment by ErikEJ** [comment]
Read Only should be possible to implement by adding HasNoKey in the OnModelCreatingPartial implementation in a partial DbContext class. https://docs.microsoft.com/en-us/ef/core/modeling/keyless-entity-types?tabs=data-annotations#keyless-entity-types-characteristics

**Comment by ErikEJ** [comment]
![image](https://user-images.githubusercontent.com/4169187/108247909-8a36bf00-7153-11eb-96d6-6ec372d8b099.png)

@sm15455 Is this by design?

**Comment by sm15455** [comment]
Definitely not... but here's how I see it.
![image](https://user-images.githubusercontent.com/5398631/108263077-0f2ad400-7166-11eb-90fc-944d9dc1f048.png)

Maybe something about resolution?

**Comment by ErikEJ** [comment]
Yes, I have large fonts/zoom enabled.

**Comment by sm15455** [comment]
In the PickTablesDialog.xaml file at line 133, try changing this
            <Popup x:Name="ContextPopup" 
                   PlacementTarget="{Binding ElementName=MainButton}" 
                   Placement="Left" 
                   VerticalOffset="{Binding ActualHeight, ElementName=MainButton}" 
                   HorizontalOffset="{Binding ActualWidth, ElementName=MainButton}" 
                   StaysOpen="False">

with this

            <Popup x:Name="ContextPopup" 
                   PlacementTarget="{Binding ElementName=MainButton}" 
                   Placement="Bottom" 
                   StaysOpen="False">
 
Should become this.
![image](https://user-images.githubusercontent.com/5398631/108265749-79914380-7169-11eb-9c29-153dd014c1d0.png)

**Comment by ErikEJ** [comment]
@sm15455 Yes, that fixed it for me.

**Comment by ErikEJ** [comment]
@sm15455 Should I change to this in master branch?

**Comment by sm15455** [comment]
It's ok for me.
