### ISSUE TITLE
Unsupported .NET 2.1

### ISSUE THREAD

**Issue by boris008** [ErikEJ/EFCorePowerTools#71]
Hello, I have problem with generating database model diagram. When I try that, I get error:
_Currently only .net framework and .net core 2.0 projects are supported - TargetFrameworkMoniker: .NETCoreApp, version=v2.1_
When you plan support of newest .NET?
Thank you very much

**Comment by ErikEJ** [comment]
Have you tried the latest daily build?

**Comment by boris008** [comment]
Hello, I have version 1.0.604 installed today. So I think that I have latest build.

**Comment by ErikEJ** [comment]
No, look at the readme for link to the latest build.
