### ISSUE TITLE
Does not display table selection for Reverse Engineer UI. Null reference exception in Output window

### ISSUE THREAD

**Issue by philicomus** [ErikEJ/EFCorePowerTools#710]
Hi,

I've started experiencing the folllowing error today out of the blue; I originally added a new connection but now none of the existing connections worked. I've tried:

- updating power tools
- updating visual studio
- uninstalling and reinstalling power tools
- deleting and recreating all the connections

I can from the stacktrace that this line appears to be the culprit, but I'm not sure how the Name property could be NULL:

` if (shouldFix && !table.Name.StartsWith("[", StringComparison.OrdinalIgnoreCase))`

Many Thanks

### Steps to reproduce
Right click project > EF core power tools >Reverse Engineer > Choose Database Connection > OK
An error occured.See the output window for details

Output window error:

System.NullReferenceException: Object reference not set to an instance of an object.
   at EFCorePowerTools.Helpers.ReverseEngineerHelper.NormalizeTables(List`1 tables, Boolean shouldFix) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Helpers\ReverseEngineerHelper.cs:line 19
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirstAsync>d__3.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 153

### Further technical details
EF Core Power Tools version: 2.5.277

Database engine: SQL Server 2016

Visual Studio version:Microsoft Visual Studio Community 2019 Version 16.8.4
csproj file:
TargetFramework:.NET Standard 2.0
Microsoft.EntityFrameworkCore.Design Version="3.1.7"
Microsoft.EntityFrameworkCore.SqlServer Version="3.1.7"
Microsoft.EntityFrameworkCore.Tools Version="3.1.7"

**Comment by ErikEJ** [comment]
Issue with your EFPT.config.json file, pls share it.

**Comment by philicomus** [comment]
```
{
   "ContextNamespace": null,
   "DefaultDacpacSchema": null,
   "FilterSchemas": false,
   "IncludeConnectionString": false,
   "ModelNamespace": null,
   "OutputContextPath": null,
   "OutputPath": null,
   "ProjectRootNamespace": "CompanyName.Integration.Data",
   "Schemas": null,
   "SelectedHandlebarsLanguage": 0,
   "SelectedToBeGenerated": 0,
   "Tables": [
      {
         "HasPrimaryKey": true,
      }
   ],
   "UseDatabaseNames": false,
   "UseDbContextSplitting": false,
   "UseFluentApiOnly": true,
   "UseHandleBars": false,
   "UseInflector": false,
   "UseLegacyPluralizer": false,
   "UseNodaTime": false,
   "UseSpatial": false,
   "UseStoredProcedures": false
}``
```

**Comment by ErikEJ** [comment]
Rename / move the file, look s broken.

**Comment by philicomus** [comment]
That was it! I made the error to committing it to source control so it had stayed around after uninstall/reinstall.

Thanks for the prompt reply and thanks for maintaining the power tools - I've found them very useful over the years.
