### ISSUE TITLE
Required inputs to stored procedures

### ISSUE THREAD

**Issue by charlesroddie** [ErikEJ/EFCorePowerTools#711]
Currently all value-type inputs to stored procedures are nullable. But almost always they are required. We don't have any inputs to stored procedures or functions which are optional.

Perhaps the easiest way to make them required would be through a setting.

This would avoid the risk of missing out inputs. It would also make procedures usable from F# without having to call `StoredProcedureName(Nullable(1), Nullable(DateTime.UtcNow),...)`.

**Comment by ErikEJ** [comment]
Stored procedure parameters are always nullable, according to the metadata I use.

**Comment by charlesroddie** [comment]
OK. A version of the methods with non-nullables would be nice to have, but it's far from the most important thing and can be worked around.

**Comment by ErikEJ** [comment]
I really dont think that non-nullable stored procedure parameters are possible, according to this: https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-parameters-transact-sql?view=sql-server-ver15 - but maybe I am reading it wrong?
