### ISSUE TITLE
Nullable reference types

### ISSUE THREAD

**Issue by charlesroddie** [ErikEJ/EFCorePowerTools#712]
Optional value-type results of stored procedures are correctly given as Nullable by EFCorePowerTools.
It would be good to have this apply to reference types too, e.g. `string?` in Result classes.
This would make use of this library much more type-safe.

**Comment by ErikEJ** [comment]
That would require you to support nullable types in your project, and use a new C# version??

**Comment by charlesroddie** [comment]
```
Auto-generated code requires an explicit #nullable directive in source
```
So uses shouldn't have to explicitly enable anything.

**Comment by ErikEJ** [comment]
But it would still require a new C# version??

**Comment by charlesroddie** [comment]
Yes C# 8. For netstandard2.1 and netcore3.0 and above, users won't need to do anything.
For netstandard 2.0, users will need to add `<LangVersion>8.0</LangVersion>` to the .csproj.

**Comment by ErikEJ** [comment]
Ok, so could you give a simple example of the changes required on the generated code?

**Comment by charlesroddie** [comment]
A procedure `UsersInClass` returns an `Email(nvarchar, null)`. Currently this class is created:
```csharp
public partial class UsersInClassResult
{
    public int Id { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string Email { get; set; }
    public byte? Role { get; set; }
}
```
The change would be to add a `?` in Email:
```
    public string? Email { get; set; }
```

**Comment by ErikEJ** [comment]
Thanks, and the #nullable directive??

**Comment by charlesroddie** [comment]
```csharp
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
```

**Comment by ErikEJ** [comment]
Hmm what is the code after FirstName, is byte not a value type??

**Comment by charlesroddie** [comment]
If you have
```
public string FirstName { get; set; }
```
then you are saying that FirstName is not null, but there is no non-null value it's being initialized to, so `= null!` is a way to apologise. I think it's the way to deal with traditional C# classes with default values and setters. Anything wrong with my C# @Happypig375 ?

**Comment by ErikEJ** [comment]
How would the code generation tool distinguish between FirstName/LastName and Email??? 😕 

They are all strings ???

        public string FirstName { get; set; } = null!;
        public string LastName { get; set; } = null!;
        public string? Email { get; set; }

**Comment by charlesroddie** [comment]
Presumably it gets info on nullability from SQL. It's certainly getting it correctly for value types at present (e.g. in the above, `Id(int, non null)` is an `int`, while `Role(tinyint, null)`, is a `byte?`).

**Comment by ErikEJ** [comment]
Sorry, I was mixing parameters and result set shape.

So for a non-nullable string (and other reference types) , generate:

    public string LastName { get; set; } = null!;

and for a nullable string (and other reference types), generate

    public string? Email { get; set; }

Is that correctly understood?

**Comment by ErikEJ** [comment]
OK, interested in doing a PR?

**Comment by charlesroddie** [comment]
Currently I'm investigating 3 options for improving our database process (EFCorePowerTools / FSharp.Data.Sqlclient / SqlPlus.net). If we decide on EFCorePowerTools I can do a PR but if not I will not be able to.

**Comment by ErikEJ** [comment]
No worries, I will make the proposed change!

**Comment by Happypig375** [comment]
@charlesroddie All good.

**Comment by ErikEJ** [comment]
I plan to implement this as an advanced option initially.

**Comment by stgenov** [comment]
Please add a row
#nullable enable
directive after the <auto-generated> row
because without it VS 2022 (.net Core 6.0) gives a warning:
CS8669: The annotation for nullable reference types should only be used in code within a '#nullable' annotations context. Auto-generated code requires an explicit '#nullable' directive in source.

the warning appears on every row with string?

**Comment by ErikEJ** [comment]
@stgenov pls create an new issue with details about your csproj.
