### ISSUE TITLE
Procedure-only scaffolding

### ISSUE THREAD

**Issue by charlesroddie** [ErikEJ/EFCorePowerTools#713]
> feature to scaffold an empty DbContext with just procedure mappings

https://github.com/ErikEJ/EFCorePowerTools/issues/437#issuecomment-674142704

In some contexts (including ours and @DawgCoder 's), database access is through stored procedures and UDFs. This would enable accessing stored procedures and UDFs in a type-safe way. There is no need in this context to have EF classes representing tables.

If this were done, would this give good performance similar to ADO.net / SQLPlus.net? Or would some of the performance penalties of EF remain?

**Comment by ErikEJ** [comment]
There is quite an overhead in the current implementation, so for (slightly) better performance, use raw ADO.NET, if you do not need any EF Core features.

As a workaround, select a single table and remove it manually after code generation.

**Comment by ErikEJ** [comment]
I attempted a fix/hack in the latest daily
