### ISSUE TITLE
What .Net Frameworkdataprovider to install for reverse engenieer a SQLite Database 

### ISSUE THREAD

**Issue by BiediCode** [ErikEJ/EFCorePowerTools#717]
I installed your EF core power tools. And I want to reverse engenieer a SQLite .db file.

I use your Provider but it looks like I must install something else. What to install exactly?

SQLite Provider (Simple for EF6 by ErikEJ) (SQLite Provider (Simple for EF6 by ErikEJ))

connectonstring: Empty or the real path to the Database. Testconnection say always success.

Testconnection is allways: German "Die Testverbindung war erfolgreich" 
                           englisch "The test connection was successful"

ErrorMessage: German "Der angeforderte .Net Framework.Datenprovider kann nicht gefunden werden. Er ist ggf. nicht installiert."
              Englisch " .Net Framework-Data provider not found. maybe not installed"

I use Microsoft Visual Studio Community 2019 Version 16.8.3 on Windows 10.

And I don't know if this is a problem from your extension or from Visual Studio, but after installing a had a errormessage inside Visual Studio

German -> Fehler beim Aktivieren des Remotesprachservers "Client des c#-/VisualBasic-Sprachservers" For more details, please examine the ..\AppData\Roming\Microsoft\VisualStudio\16.0_09a4b275\ActivityLog.xml file" 
English -> Error on activating Remote Language[or speach] server. for more details....

And yes it is funny the Message is half German and half english. Maybe that problem is because I change my language of the Computer and install your app without relogin. 

Here are the errors and warnings from the XML file. And thanks for your tool I have see the Demo. Great Work! 
This is what i missed on EF CORE. Thank you.

Regards Michael

Activity Monitor Log 
infos 107 
warnings 3 
errors 26 

28 ERROR CPkgDefCacheNonVolatileBase: PkgDef cache creation failed. Going volatile and trying again.  8000ffff - E_UNEXPECTED VisualStudio 2021/01/20 13:31:22.617 
2106 ERROR Failed to set Public Key Token  80070057 - E_INVALIDARG VisualStudio 2021/01/20 13:31:45.516 
2107 ERROR Binding Redirect / CodeBase entry from configuration hive is malformed, ignoring.
          Software\Microsoft\VisualStudio\16.0_09a4b275_Config_2472\RuntimeConfiguration\dependentAssembly\codeBase\{0746BB9F-4F6E-4C38-BCF0-8F601D6AD0C1}  80070057 - E_INVALIDARG VisualStudio 2021/01/20 13:31:45.516 
2108 ERROR Failed to set Public Key Token  80070057 - E_INVALIDARG VisualStudio 2021/01/20 13:31:45.526 
2109 ERROR Binding Redirect / CodeBase entry from configuration hive is malformed, ignoring.
          Software\Microsoft\VisualStudio\16.0_09a4b275_Config_2472\RuntimeConfiguration\dependentAssembly\codeBase\{167AF614-476E-4BDF-952E-57A6C7CF39A5}  80070057 - E_INVALIDARG VisualStudio 2021/01/20 13:31:45.526 
2110 ERROR Failed to set Public Key Token  80070057 - E_INVALIDARG VisualStudio 2021/01/20 13:31:45.583 
2111 ERROR Binding Redirect / CodeBase entry from configuration hive is malformed, ignoring.
          Software\Microsoft\VisualStudio\16.0_09a4b275_Config_2472\RuntimeConfiguration\dependentAssembly\codeBase\{7A9AEA02-2F54-493C-8E45-580D66D02799}  80070057 - E_INVALIDARG VisualStudio 2021/01/20 13:31:45.583 
2112 ERROR Failed to set Public Key Token  80070057 - E_INVALIDARG VisualStudio 2021/01/20 13:31:45.584 
2113 ERROR Binding Redirect / CodeBase entry from configuration hive is malformed, ignoring.
          Software\Microsoft\VisualStudio\16.0_09a4b275_Config_2472\RuntimeConfiguration\dependentAssembly\codeBase\{7E3052B2-FB42-4E38-B22C-1FD281BD4413}  80070057 - E_INVALIDARG VisualStudio 2021/01/20 13:31:45.584 
2114 ERROR Failed to set Public Key Token  80070057 - E_INVALIDARG VisualStudio 2021/01/20 13:31:45.600 
2115 ERROR Binding Redirect / CodeBase entry from configuration hive is malformed, ignoring.
          Software\Microsoft\VisualStudio\16.0_09a4b275_Config_2472\RuntimeConfiguration\dependentAssembly\codeBase\{938D3E45-5067-45C4-9349-5E939A639CBF}  80070057 - E_INVALIDARG VisualStudio 2021/01/20 13:31:45.600 
2116 ERROR Failed to set Public Key Token  80070057 - E_INVALIDARG VisualStudio 2021/01/20 13:31:45.633 
2117 ERROR Binding Redirect / CodeBase entry from configuration hive is malformed, ignoring.
          Software\Microsoft\VisualStudio\16.0_09a4b275_Config_2472\RuntimeConfiguration\dependentAssembly\codeBase\{C8992C7B-8D67-41E9-ADD1-D44D1ACDD139}  80070057 - E_INVALIDARG VisualStudio 2021/01/20 13:31:45.633 
2191 ERROR Loading UI library {F5D4BB28-24EB-4FC7-BDEC-BF96BA99A8EE} 800a006f VisualStudio 2021/01/20 13:31:54.332 
2192 ERROR Error loading UI library for package Microsoft.VsSDK.ExtensibilityProjectFlavor.ExtensibilityProjectFlavorPackage. HrLoadNativeUILibrary failed with 0x800a006f.   VisualStudio 2021/01/20 13:31:54.333 
2193 ERROR Loading UI library {10CA1B00-C23A-4B59-BCE7-512501F4E68A} 800a006f VisualStudio 2021/01/20 13:31:54.863 
2194 ERROR Error loading UI library for package CommandsClientPackage. HrLoadNativeUILibrary failed with 0x800a006f.   VisualStudio 2021/01/20 13:31:54.863 
2195 ERROR Loading UI library {2FFE45C4-5C73-493C-B187-F2E955FF875E} 800a006f VisualStudio 2021/01/20 13:31:56.135 
2196 ERROR Error loading UI library for package Microsoft.VisualStudio.LanguageServices.TypeScript.TypeScriptPackage, Microsoft.VisualStudio.LanguageServices.TypeScript, Version=16.0.0.0, Culture=neutral. HrLoadNativeUILibrary failed with 0x800a006f.   VisualStudio 2021/01/20 13:31:56.136 
2198 ERROR Failed to find CTMENU resource '#1000' in loaded UI library.   VisualStudio 2021/01/20 13:31:56.213 
2199 ERROR Loading UI library {C78CA057-CC29-421F-AD6D-3B0943DEBDFC} 800a006f VisualStudio 2021/01/20 13:31:56.284 
2200 ERROR Error loading UI library for package Windows Forms Remote Designer Hosting Package. HrLoadNativeUILibrary failed with 0x800a006f.   VisualStudio 2021/01/20 13:31:56.285 
2201 ERROR Loading UI library {2EF1EC52-C8BF-4FE0-8ECE-BA9C0D5D1603} 800a006f VisualStudio 2021/01/20 13:31:56.360 
2202 ERROR Error loading UI library for package XamlLanguagePackage. HrLoadNativeUILibrary failed with 0x800a006f.   VisualStudio 2021/01/20 13:31:56.361 
2203 ERROR Loading UI library {71054795-27FD-4816-9AEA-667FE14EDD2A} 800a006f VisualStudio 2021/01/20 13:31:56.645 
2204 ERROR Error loading UI library for package New Project Dialog. HrLoadNativeUILibrary failed with 0x800a006f.   VisualStudio 2021/01/20 13:31:56.646 
2875  End package load [Code Analysis Package] {B20604B0-72BC-4953-BB92-95BF26D30CFA}  VisualStudio 2021/01/20 13:33:07.653 
2876  End package load [Microsoft.VisualStudio.PlatformUI.InfoBadgePackage] {33EE6583-8B97-4F6A-8B2A-6B14007FA249}  VisualStudio 2021/01/20 13:33:07.720 
2877 Warning MainWindowFrameControls\{042609f5-f636-4666-9cbc-9c4bcd9676c2} doesn't specify NoToolbarAlignment, defaulting to TitleBarRight   FrameControl 2021/01/20 13:33:08.272 

2957 Warning Request for "Microsoft.VisualStudio.Shell.Internal.SettingsManager (1.0)" from Process denied because the service is only exposed RemoteExclusiveClient, LiveShareGuest.   GlobalBrokeredServiceContainer 2021/01/20 13:33:41.902 
2958 Warning Request for proxy to "Microsoft.VisualStudio.Shell.Internal.SettingsManager (1.0)" is declined: ServiceAudienceMismatch.   GlobalBrokeredServiceContainer 2021/01/20 13:33:41.903

**Comment by ErikEJ** [comment]
You must install and register the System.Data.SQLite ADO.NET provider, as described in the wiki: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering

**Comment by BiediCode** [comment]
Thank you!

**Comment by ErikEJ** [comment]
With the latest daily build, you can avoid installing the provider!
