### ISSUE TITLE
Support for SQLExpress

### ISSUE THREAD

**Issue by Dinand-mmit** [ErikEJ/EFCorePowerTools#718]
Describe what is not working as expected.
In VS SQLExporer finds the SQLExpress(2019 or version 15 as you wish) and connect to the db's. Unfortunately (reverse engineer for example) EF Core power tools won't. It won't even retrieve the list of Servers and tables. Odd. 

By adding the connectionstring, it ask for the DB file? 

### Steps to reproduce
Include a complete description that I can redo to reproduce the issue.

Look if you can connect to the SQLExpress DB with SQLExporer. if so, 
Try to find SQLExpress DB server (2019) with the  tool in VS2019.

### Further technical details
EF Core Power Tools version: 2.5.454.0.

Database engine: (SQL Express 2019)

Visual Studio version: (Visual Studio 2019 16.8.4)

Looks really like a cool tool, but can't use it now. I do have small projects and work on my development machine always with SQLExpress. Thank you.
Dinand

**Comment by ErikEJ** [comment]
I use this with SQL Express daily, so you must be doing something differently/wrong.

Maybe share some screenshots?

**Comment by ErikEJ** [comment]
Closing as requested info was not provided, feel free to re-open if you can provide it.
