### ISSUE TITLE
Reverse Engineer - EF Core 5 Model generator probleme

### ISSUE THREAD

**Issue by chpo69** [ErikEJ/EFCorePowerTools#719]
When I use the Reverse Engineer for EF Core 5 there are no longer the Table and Shcema attributes in the model classes. So that in the generated SQL the shema is missing and sql server returns => Invalid object name 'xxxx'.

### Steps to reproduce
Example of model class with Reverse Engineer EF Core 3
```csharp
[Table("MesEtatAcquisition", Schema = "Acq")]
public partial class MesEtatAcquisition
{
        public MesEtatAcquisition()
        {
            MesAcquisition = new HashSet<MesAcquisition>();
        }

        [Key]
        public int NoEtat { get; set; }
        [Required]
        [StringLength(50)]
        public string RefEtat { get; set; }
        [Required]
        [StringLength(50)]
        public string LbEtat { get; set; }

        [InverseProperty("NoEtatNavigation")]
        public virtual ICollection<MesAcquisition>
MesAcquisition { get; set; }


}
```
Example of model class with Reverse Engineer EF Core 5
```csharp
public partial class MesEtatAcquisition
{
        public MesEtatAcquisition()
        {
            MesAcquisition = new HashSet<MesAcquisition>();
        }

        [Key]
        public int NoEtat { get; set; }
        [Required]
        [StringLength(50)]
        public string RefEtat { get; set; }
        [Required]
        [StringLength(50)]
        public string LbEtat { get; set; }

        [InverseProperty("NoEtatNavigation")]
        public virtual ICollection<MesAcquisition>
MesAcquisition { get; set; }


}
```
I manually added the table and shema row in the class generated in EF Core 5 and the generated SQL query is correct.

So I think we need to add the Table and shema attributes to the model class generated in Reverse Engineer for EF Core 5

thank you in advance

### Further technical details
EF Core Power Tools version: 2.5.454.0

SQLite ADO.NET Provider included: 1.0.109.0
SQLite EF6 DbProvider in GAC - No

System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes

Database engine: (SQL Server)

Visual Studio version: (e.g. Visual Studio 2019 Version 16.8.2)

**Comment by ErikEJ** [comment]
I am not able to reproduce, are you using a different user for scaffolding?

What is the result of this for the user that runs scaffolding

     SELECT SCHEMA_NAME()

**Comment by ErikEJ** [comment]
Are you generating from a live database or a dacpac?

Thanks for the provided script, that is exactly my failed attempt at a repro.

**Comment by chpo69** [comment]
I use a one user  for scaffolding. I use a different  SCHEMA for the table.

**Comment by chpo69** [comment]
I use a live database for my generating.

**Comment by ErikEJ** [comment]
Could you try the latest daily build?

**Comment by chpo69** [comment]
I have install the latest daily build Version 2.5.461.0

I have a same result when chexkBox 'Use EF Core 5' is checked the attribut Table and Shema is not generated in model. When checkBox  'Use EF Core 5' is unchecked  the attribut Table and Shema is generated in model.

**Comment by ErikEJ** [comment]
I am sorry, I tried to replicate, but I am unable to replicate, unless the default schema of the account used for scaffolding is not dbo:

https://docs.microsoft.com/en-us/sql/t-sql/functions/schema-name-transact-sql?view=sql-server-ver15#a-returning-the-name-of-the-default-schema-of-the-caller

**Comment by chpo69** [comment]
I don't understand why you were staring at the default account scheme? It is the schema of the table that counts for the generation of its model and to fill in the shema attribute of the table!
Also in the table selection dialog there are indeed the shemas before the tables, so why will it not work by checking the use EF CORE 5 box and it works with this box unchecked?

For reminder, below is the query to get the schemas of the database tables. But I don't think that's the problem because the shema and table tree is good in the UI. I think that in the Use EF core 5 checkBox, the generation of C # forgets to add the shema atribu line at the start of the class is checked.

`SELECT [SCHEMA] = SCHEMA_NAME(schema_id),  [TABLE] = name
FROM sys.tables`

**Comment by ErikEJ** [comment]
>> I don't understand why you were staring at the default account scheme?¨

Because the scaffolding code uses this to determine whether to include the schema name in the Table attribute!

**Comment by chpo69** [comment]
Ok, but why is the C # model generated with the schema of the table when the chekBox is not checked 'Use EF Core 5'?
I didn't have this problem with EF Core 3.

**Comment by ErikEJ** [comment]
As I have already said, I have no idea why it fails for you, and I am not able to replicate.

**Comment by ErikEJ** [comment]
I need a repro project with schema creation and generated code in order to investigate.

**Comment by chpo69** [comment]
Ok, how can I send this to you privately?

**Comment by ErikEJ** [comment]
You are using Handlebars, and the templates must be initialized and redone for 5.0 (breaking change) - renaming the CodeTemplates folder in your repro project fixes the issue. (Or stop using Handlebars)

**Comment by chpo69** [comment]
Great, it works, thanks

**Comment by ErikEJ** [comment]
Thanks for the heads up.
