### ISSUE TITLE
DbContextExtensions Timeout

### ISSUE THREAD

**Issue by johannvantaak** [ErikEJ/EFCorePowerTools#725]
Hi There. I am making use of the ContextProcedures function to run some of my stored procedures against the database. What I have found is that the timeout of the original context is ignored. So even setting the _context.Database.SetCommandTimeout to a high value is not taken into account and it goes back to the default of 30 seconds. Going into the DbContextExtensions class, it appears that the portion where a new ContextForQueryType either resets or creates a copy of the Context which goes back to the defaults. Simply doing a db2.SetCommandTimeout works for me, however, when rescaffolding happens this file is then replaced. Any chance of making the db2 variable in SqlQueryAsync in the DbContextExtensions class inherit the Command timeout from the original context?

### Steps to reproduce
Scaffold a stored procedure that will run for more than 30 seconds.
Use context.Database.SetCommandTimeout(TimeSpan.FromMinutes(2)) to set the original context's timeout occurrence.
Run the procedure - A timeout will occur after the default time of 30 seconds.

### Further technical details
EF Core Power Tools version: 2.5

Database engine: SQL Server 2016

Visual Studio version: Visual Studio 2019 Professional 16.8.4

**Comment by ErikEJ** [comment]
Fixed in latest daily build

**Comment by johannvantaak** [comment]
Thanks!
