### ISSUE TITLE
Add animation to the status bar when getting schema from database

### ISSUE THREAD

**Issue by viktorszekeress** [ErikEJ/EFCorePowerTools#731]
In case that db is really large, after clicking on OK button in the first dialog (dialog with connection string), the dialog is dismissed and it takes about 30 secs for the second dialog (dialog with tables) to show up. That is really confusing, because user might think that tool doesn't work. He may even open Reverse Engineer dialog again, while the first one is still being processed.

I suggest that after clicking OK button:
1. leave the dialog open
2. make everything disabled
3. display a busy indicator

The same user unfriendly behavior can be observed after clicking on OK in 3rd dialog, when tool generates the code. Here it takes about 5 seconds before confirmation dialog appears.

**Comment by ErikEJ** [comment]
Dont you see messages in the VS statusbar?

**Comment by ErikEJ** [comment]
What is a "busy indicator" in the context of Visual Studio ?? I always treated status bar messages as an unobtrusive way of doing that.

**Comment by viktorszekeress** [comment]
I mean standard indeterminate progress bar/circle. But if you think that VS status bar is the way to go, then I'm okay with that, just please don't allow user to reopen Reverse Engineer dialog while there is one being processed.

**Comment by ErikEJ** [comment]
Thanks for your feedback, I will add animation to the status bar! 

https://docs.microsoft.com/en-us/visualstudio/extensibility/extending-the-status-bar?view=vs-2019#display-an-animation

**Comment by ErikEJ** [comment]
Implemented in latest daily build

**Comment by viktorszekeress** [comment]
That was fast. Thanks!
