### ISSUE TITLE
Reverse engineer not visible

### ISSUE THREAD

**Issue by ltemimi** [ErikEJ/EFCorePowerTools#733]
Hi

I am unable to see the reverse engineer context menu when I right click my blazor server app. (I have of course installed the ef core power tools)

Please help

Laz Temimi

**Comment by ErikEJ** [comment]
Can you see it with other project types?
Is it Disabled (Check Extensions dilaog) ?

**Comment by ltemimi** [comment]
Hi 

I can't see it with other project types, disabled ? I checked the dialog and cannot see how to find out if it is disabled or not.

regards

Laz
