### ISSUE TITLE
Null Reference Exception in ReverseEngineerHandler

### ISSUE THREAD

**Issue by mhsimkin** [ErikEJ/EFCorePowerTools#739]
Describe what is not working as expected.
Reverse Engineering throws an error message.

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirstAsync>d__3.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 86

```
I have attached a sample project demonstrating the issue.

[EFCorePowerToolsIssue.zip](https://github.com/ErikEJ/EFCorePowerTools/files/5896755/EFCorePowerToolsIssue.zip)

### Steps to reproduce
1) Use the Visual Studio Project Wizard to create the initial Windows Form project for .NET Core.
2) Change to .NET 5
3) Add Microsoft.EntityFrameworkCore.SqlServer v5.0.2 package to the project.
4) Right click on the project file and select EF Core Power Tools -> Reverse Engineer
5) Look in the VS Output Windows for the error message.

### Further technical details
EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
Version 2.5.477

Database engine: (SQlite, SQL Compact, SQL Server, Postgres)
SQL Server 2019 Developer

Visual Studio version: (e.g. Visual Studio 2017 15.7)
VS Enterprise 2019 Version 16.8.4

**Comment by ErikEJ** [comment]
Fixed in latest daily build, thanks for reporting!

**Comment by mhsimkin** [comment]
Thank you.  It is working now.

**Comment by ErikEJ** [comment]
You are welcome, and thanks for trying out the daily builds.
