### ISSUE TITLE
Use nameof() for all navigation properties

### ISSUE THREAD

**Issue by mortensp** [ErikEJ/EFCorePowerTools#740]
When performing a revers engenering on an existing database the tool puts many of the InversePropertyAttribute names in quotes like here;

      [ForeignKey("TournamentId,Section,DealNo,TableNo")]
        [InverseProperty("OpeningLead")]
        public virtual Result Result { get; set; }

It would be nice if it would use nameof instead like here:

      [ForeignKey("TournamentId,Section,DealNo,TableNo")]
        [InverseProperty(nameof(BridgeModel.Result.OpeningLead))]
        public virtual Result Result { get; set; }

Please note that I had to qualify the Result class name by the namespace.
As of now I can't se any way to do the same with the ForeignKeyAttibute, but that would be nice to...

This change will help a lot when one later change any of the Class og Property names

**Comment by ErikEJ** [comment]
The tool already uses nameof as much as possible !?

Are you using Handlebars with obsolete templates perhaps?

If not, please share a repro database schema and efpt.config.json file, and I will investigate.

**Comment by mortensp** [comment]
Hello Erik   (eller skal jeg sige Hej Erik?)

Here is a copy of my (empty) database and a small demo project.
If you look at the TeamResult class you see the problem.

I have included three screenshots of my answers to your Reenginering forms!

Another thing is your pluralizer isn’t doing a great job, whet the name ends with a number.
I believe you should place the ‘s’ before the last number!

Vh Morten S.
[EFCorePowerTools.zip](https://github.com/ErikEJ/EFCorePowerTools/files/5897831/EFCorePowerTools.zip)

**Comment by mortensp** [comment]
The ForeignKeyAttributes could also use nameof, like her:

[ForeignKey(nameof(TournamentId)+","+ nameof(Section) + ","+ nameof(PartnershipId))]

**Comment by ErikEJ** [comment]
The tool uses the standard Humanizer english pluralizer, if you believe it has a bug, please file an issue on the Humanizer repo. The tool also supports the EF 6 pluralizer for backwards compatiblilty.

**Comment by ErikEJ** [comment]
It is because you are using Pluralization: https://github.com/dotnet/efcore/blob/main/src/EFCore.Design/Scaffolding/Internal/CSharpEntityTypeGenerator.cs#L485
