### ISSUE TITLE
Remember choice for "Use EF Core 5"

### ISSUE THREAD

**Issue by fepettersen** [ErikEJ/EFCorePowerTools#745]
Every time I chose reverse engineer I have to remember to un-check the "Use EF Core 5" checkbox. Since this checkbox is not part of the config-options, this is often forgotten, and it results in the generated code not working.

### Steps to reproduce
On a dotnet core 3.1 project, choose reverse engineer. Complete the process, and then chose reverse engineer agian. The checkbox "Use EF Core 5" is now checked again.

### Further technical details
EF Core Power Tools version: 2.5.454

Database engine: SQL Server

Visual Studio version: Visual Studio 2019 16.8.4

**Comment by ErikEJ** [comment]
Thanks for reporting this, fixed in latest daily build
