### ISSUE TITLE
Unchecking an item may cause the related file to be removed

### ISSUE THREAD

**Issue by 1gurucoder** [ErikEJ/EFCorePowerTools#748]
Can you make it so existing models that are already generated aren't deleted if unchecked?  This way I can generate a one-off for a new table and not have to generate for all.

**Comment by ErikEJ** [comment]
You can undo any unwanted changes / deletions as you of course use source control. Or you can avoid deletions as described here: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#saving-options-and-running-the-second-time - but I do not understand the issue, you should never be making any changes to the generated code, but use partial classes and partial methods.

**Comment by ErikEJ** [comment]
Ping?

**Comment by 1gurucoder** [comment]
Ok makes sense, I'm coming from a My2ndGeneration world.  I do use partial classes so none of my custom code is touched.  I just didn't know if there was a way to generate a one-off for a new table that way several hundred existing tables wouldn't have to be regenerated.  This is a non-issue and thank you for your feedback.
