### ISSUE TITLE
MissingMethodException Error : Unable to scaffold

### ISSUE THREAD

**Issue by arunprasathv** [ErikEJ/EFCorePowerTools#76]
@ErikEJ 

getting this error while scaffolding,

System.MissingMethodException: Method not found: 'Microsoft.Extensions.DependencyInjection.IServiceCollection Microsoft.EntityFrameworkCore.Design.ServiceCollectionExtensions.AddHandlebarsScaffolding(Microsoft.Extensions.DependencyInjection.IServiceCollection, Microsoft.EntityFrameworkCore.Design.ReverseEngineerOptions, System.ValueTuple`2<System.String,System.Action`3<System.IO.TextWriter,System.Object,System.Object[]>>[])'.
   at ReverseEngineer20.EfCoreReverseEngineer.GenerateFiles(ReverseEngineerOptions reverseEngineerOptions)
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__2.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 154

**Comment by ErikEJ** [comment]
have you tried the latest daily build?

**Comment by arunprasathv** [comment]
yes, i did. still fails. using EF Core 2.1 and .Net core 2.0

**Comment by arunprasathv** [comment]
i've 2.0 and ef core 2.1 it works fine. with the same config on another machine, it doesn't work.

**Comment by ErikEJ** [comment]
Different VS versions and/or .NET Core SDK versions?

**Comment by arunprasathv** [comment]
yes.

**Comment by arunprasathv** [comment]
anyway , it works fine for me at least. I always get this message,

![image](https://user-images.githubusercontent.com/7142390/43226620-56f89652-902a-11e8-8e0d-121225420bf0.png)

**Comment by ErikEJ** [comment]
So this can be closed now??
