### ISSUE TITLE
Pascal case and defining words via dictionary?

### ISSUE THREAD

**Issue by dyardyGIT** [ErikEJ/EFCorePowerTools#762]
I am doing reverse engineering.

The database column is   
public int **LsdLocationId** { get; set; } // LSDLocationId (Primary key)

however after running this field is coming across with different casing
public int LsdlocationId { get; set; }

Notice Location vs location

Is there any way to identify Lsd as a word to keep the Pascal casing?

**Comment by ErikEJ** [comment]
Yes, you can use the renaming feature (manually!) - see https://github.com/ErikEJ/EFCorePowerTools/issues/679

**Comment by ErikEJ** [comment]
Ping?

**Comment by ErikEJ** [comment]
The renaming feature should cover this, if not, feel free to reopen
