### ISSUE TITLE
Getting error while installation.

### ISSUE THREAD

**Issue by abisheksharma** [ErikEJ/EFCorePowerTools#763]
Describe what is not working as expected.
I am trying to add this extension to my Visual Studio 2019 community edition and I am getting install failed.
### Steps to reproduce
Include a complete description that I can redo to reproduce the issue.
Download extension from market place and install it.
### Further technical details
EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
Here are the logs:
2/9/2021 4:46:47 PM - Microsoft VSIX Installer
2/9/2021 4:46:47 PM - -------------------------------------------
2/9/2021 4:46:47 PM - vsixinstaller.exe version:
2/9/2021 4:46:47 PM - 16.8.3036
2/9/2021 4:46:47 PM - -------------------------------------------
2/9/2021 4:46:47 PM - Command line parameters:
2/9/2021 4:46:47 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\vsixinstaller.exe,/appidinstallpath:C:\Program Files (x86)\Microsoft Visual Studio\2019\Common7\IDE\devenv.exe,/skuName:Community,/skuVersion:16.8.30907.101,/appidname:Microsoft Visual Studio Community 2019,/culture:en-US,/noep,C:\Users\User\AppData\Local\Temp\VSIXb1ir5rzs.vsix
2/9/2021 4:46:47 PM - -------------------------------------------
2/9/2021 4:46:47 PM - Microsoft VSIX Installer
2/9/2021 4:46:47 PM - -------------------------------------------
2/9/2021 4:46:48 PM - System.NullReferenceException: Object reference not set to an instance of an object.
   at VSIXInstaller.SetupExtensions.GetLaunchableInstances(IQuery query)
   at VSIXInstaller.SupportedSKUs.EnumerateIsolatedInstalls(Action`1 callback)
   at VSIXInstaller.SupportedSKUs.AddInstalledLocationBasedSKUs(IntPtr userToken)
   at VSIXInstaller.SupportedSKUs.InitializeSupportedSKUs(IntPtr userToken)
   at VSIXInstaller.ExtensionService.InitializeSupportedSKUs(ICommandLineData cmdLineData, IntPtr duplicatedUserToken)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

Database engine: (SQlite, SQL Compact, SQL Server, Postgres)

Visual Studio version: (e.g. Visual Studio 2017 15.7)
2019

**Comment by ErikEJ** [comment]
Repair your VS installation

**Comment by ErikEJ** [comment]
Ping?

**Comment by abisheksharma** [comment]
Hey Erik. thanks for your reply. I used this link to fix my issue.
https://developercommunity.visualstudio.com/content/problem/869732/vsix-installer-fails-with-object-reference-not-set.html

**Comment by ErikEJ** [comment]
Thanks for the heads up. So it is working now?

**Comment by abisheksharma** [comment]
Yes, it's working now. thanks
