### ISSUE TITLE
How to reverse engineer with a single DBContext with Identity and EF migrations 

### ISSUE THREAD

**Issue by ameador1** [ErikEJ/EFCorePowerTools#764]
I am working on a .NET Core 5.0 MVC Web App project that has Identity and EF added. This creates an ApplicationDbContext. I need to use Identity User data in my other data tables where I want to link database information to the Identity User that was logged in at the time. The ApplicationDbContext inherits IdentityDBContext - which in turn inherits DBContext - so my understanding is that I can thus use ApplicationDbContext to access the User data as well as my Models/Tables in my project outside of the Identity models/tables. As such, I want to be able to use your tool to reverse engineer my database tables into models I can use in my app. But, everything I am trying is causing me problems.

If I include ApplicationDbContext in your tool (top line) and don't tell it to generate the DBContext (Entity types Only) - it deletes the ApplicationDBContext - breaking the application. If I tell it to generate both the Entity types and DBContext, then it overwrites the ApplicationDbContext - which drops some Using statements and sets ApplicationDbContext to inherit from DBContext instead of IdentityDBContext. 

If I leave it inheriting DbContext - it will compile, but if I run the application and try to login, the application crashes saying:

`An unhandled exception occurred while processing the request.
InvalidOperationException: Cannot create a DbSet for 'IdentityUser' because this type is not included in the model for the context.
Microsoft.EntityFrameworkCore.Internal.InternalDbSet<TEntity>.get_EntityType()`

If I change it back to inheriting IdentityDbContext (which requires adding the following using statement: using Microsoft.AspNetCore.Identity.EntityFrameworkCore;), then it gives the following error when I run the app and try to login:

`An unhandled exception occurred while processing the request.
InvalidOperationException: The entity type 'IdentityUserLogin<string>' requires a primary key to be defined. If you intended to use a keyless entity type, call 'HasNoKey' in 'OnModelCreating'. For more information on keyless entity types, see https://go.microsoft.com/fwlink/?linkid=2141943.`

If I try using the Advanced option in your tool "Split DbContext into Configuraiton classes (preview)", then it goes back to making ApplicationDbContext inherit from DbContext and throws the error below (same as before) when I run the app and try to login:

`An unhandled exception occurred while processing the request.
InvalidOperationException: Cannot create a DbSet for 'IdentityUser' because this type is not included in the model for the context.
Microsoft.EntityFrameworkCore.Internal.InternalDbSet<TEntity>.get_EntityType()`

Again, if I change ApplicationDbCOntext back to inherity from IdentiyDbContext and add the using statement back, I also get the same error as before when running the app and trying to login:

`An unhandled exception occurred while processing the request.
InvalidOperationException: The entity type 'IdentityUserLogin<string>' requires a primary key to be defined. If you intended to use a keyless entity type, call 'HasNoKey' in 'OnModelCreating'. For more information on keyless entity types, see https://go.microsoft.com/fwlink/?linkid=2141943.`

So, I am at a loss on how to use the single DbContext while using your tool. But, I also want to be able to use migrations still to pick up on the changes in the models so I can use the EF features of migrations and altering code to push those changes back to the database. Am I trying to do something not possible? Do I have to use 2 DbContexts and have 2 separate migration chains? If so, how does my new DbContext get access to the Identity user information that is connected to the ApplicationDbContext within my application Views?

I am still somewhat new to dealing with Identity and EF so please bear with me! ;)

Thanks!
Andrew

**Comment by ErikEJ** [comment]
Mixing database first and migrations it not something I recommend.

Why not just create a new Context from the database, and modify it to inherit from ApplicationDbContext ?

**Comment by ameador1** [comment]
> Mixing database first and migrations it not something I recommend.
> 
> Why not just create a new Context from the database, and modify it to inherit from ApplicationDbContext ?

So you suggest leaving the ApplicationDbContext class, and then using your tool to generate a second one (say NewDbContext)  and then edit the context file for NewDbContext and change it to inherit from ApplicationDbContext any time the NewDbContext is re-generated on reverse engineering additional tables or table changes?

Since NewDbContext is inheriting from ApplicationDbContext, NewDbContext would have access to the Identity User information of the logged in user?

**Comment by ErikEJ** [comment]
I would imagine so, why not give it a try?

**Comment by ameador1** [comment]
(Based on a clean ASP.Net Core 5.0 MVC - Web Application with Identity)

Ok. So here's what I ended up doing that seems to be working and what I was after. I am only using the ApplicationDbContext - no additional. I figured if I'm going to have to edit a newly created DbContext (by EF Core Tools - EFCT), then I may as well edit ApplicationDbContext. It is the same edits in either case, so I see no reason the deal with 2 DbContexts - in terms of having a new one created by EFCT and inherit from ApplicationDbContext.

So, after I run EFCT and set the ApplicationDbContext as the Context Name, and set Models and Data as the paths for EntityTypes path and DbContext path - respectively, and then click Ok - it generates a new ApplicationDbContext.cs

I then edited the file as follows:

```c#
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;   // Changed - Added this line
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using NV5_MVC_EFCoreTools_OnlyAppDbContext.Models;

#nullable disable

namespace NV5_MVC_EFCoreTools_OnlyAppDbContext.Data
{
    public partial class ApplicationDbContext : IdentityDbContext   // Changed from ApplicationDbContext : DbContext
    {
        public ApplicationDbContext()
        {
        }

        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<TestTable1> TestTable1 { get; set; }
        public virtual DbSet<TestTable2> TestTable2 { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);   // Changed - Added this line

            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.Entity<TestTable1 >(entity =>
            .
            .
            .
```

This seems to be working fine, and I had to make those same edits to the second DbContext file if I have EFCT to create a new. 

I am still fumbling through much of this - single DbContext, customizing Identity UI an classes from the Razor Class Library (RCL) extractions/scaffolding... so hopefully this is correct in the longer term - but it appears to be working for me at the moment.

Do you have any opinion on whether or not to include the Identity database tables in the EFCT reverse engineering process? I'm not sure I really understand this well enough yet, but I'm thinking that using the Identity classes (IdentityDbContext and IdentityUser (well, my inherited customized version ApplicationUser) that these can 'talk' to the database tables and I don't need the Identity tables modeled by EFCT. So at the moment, I'm not reverse engineering these database tables. I need to create some Admin type pages to deal with these tables though - that's why I'm asking.

Thanks!

**Comment by ErikEJ** [comment]
I have not worked with ASP.NET Identity / EF Core,sorry.

**Comment by marchchad** [comment]
What you can do @ameador1 is enable the option to use the handlebars templates, then customize the following files as follows:

*project_root/CSharpDbContext/DbContext.hbs*
```hbs
{{> dbimports}}

namespace {{namespace}}
{
    public partial class {{class}} : IdentityDbContext<ApplicationUser>
    {
    {{{> dbconstructor}}}

    {{{> dbsets}}}
    {{#if entity-type-errors}}
    {{#each entity-type-errors}}
    {{{entity-type-error}}}
    {{/each}}

    {{/if}}

    {{#unless suppress-on-configuring}}
    {{{> dbonconfiguring}}}
    {{/unless}}
{{{on-model-creating}}}
    }
}
```

*project_root/CSharpDbContext/Partials/DbImports.hbs*
```hbs
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using SMP.Models;
{{#if model-namespace}}
using {{model-namespace}};
{{/if}}
{{#each model-imports}}
using {{model-import}};
{{/each}}
```

Also create an `ApplicationDbContextExtensions.cs` next to `ApplicationDbContext.cs` and include the following so it includes the Identity models:
```cs
namespace <YourProjectName>.Context
{
    public partial class ApplicationDbContext
    {
        partial void OnModelCreatingPartial(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            ...
        }
    }
}
```

This also assumes you've mapped your custom identity user in the `ConfigureServices` method of your `Startup.cs`. Something like this:
```cs
services.AddIdentity<ApplicationUser, IdentityRole>()
      .AddEntityFrameworkStores<ApplicationDbContext>()
      .AddDefaultTokenProviders();
```

This **should** generate what you need so you don't have to worry about restoring these when rescaffolding.
