### ISSUE TITLE
Proposal: store efpt.config.json in diferent folder

### ISSUE THREAD

**Issue by pedromcrocha** [ErikEJ/EFCorePowerTools#765]
Propose to read and save efpt.config.json from / to other folder than root project.

I have a huge database that need to reverse engineer, and I prefer to create smaller dbcontext in several folders.
I think it’s better archive efpt.config.json in dbcontext folder that in root project.
or in EntityTypes path.

Thanks in advance.

**Comment by ErikEJ** [comment]
I assume you are aware of [this feature?](https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#using-multiple-dbcontexts-in-the-same-project) 

if that is not sufficient, a PR would be welcome.

Some enhancements here: https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/EFCorePowerTools/Extensions/ProjectExtensions.cs#L72 
and here:
https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/EFCorePowerTools.Shared/Models/ConfigModel.cs#L26

**Comment by pedromcrocha** [comment]
Hi Erik

Yes, read about the feature and use , but…

I read the code that you point, and believe that is not difficult.

But I don’t have the knowledge and experience to debug this type of project (extensions is VS)

Regards,
Pedro Rocha

De: Erik Ejlskov Jensen <notifications@github.com>
Enviada: 11 de fevereiro de 2021 16:43
Para: ErikEJ/EFCorePowerTools <EFCorePowerTools@noreply.github.com>
Cc: pedromcrocha <pedro.rocha@outlook.pt>; Author <author@noreply.github.com>
Assunto: Re: [ErikEJ/EFCorePowerTools] Proposal: store efpt.config.json in diferent folder (#765)


I assume you are aware of this feature?<https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#using-multiple-dbcontexts-in-the-same-project>

if that is not sufficient, a PR would be welcome.

Some enhancements here: https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/EFCorePowerTools/Extensions/ProjectExtensions.cs#L72
and here:
https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/EFCorePowerTools.Shared/Models/ConfigModel.cs#L26

**Comment by ErikEJ** [comment]
It is quite simple, just look at the readme

**Comment by ErikEJ** [comment]
Fixed in https://github.com/ErikEJ/EFCorePowerTools/pull/773
