### ISSUE TITLE
Feature to load selected tables from a saved text file has been removed

### ISSUE THREAD

**Issue by DrumHeadTed** [ErikEJ/EFCorePowerTools#767]
Feature to load selected tables from a saved text file has been removed.

### Steps to reproduce
EF Core Power Tools
Reverse Engineer
Unselect Use Ef Core 5
Select Database and then OK.
Choose Database Objects dialog appears. No option to load or save a text file exists.  

### Further technical details
EF Core Power Tools version: (found in About dialog 
Version 2.5.454.0

SQLite ADO.NET Provider included: 1.0.109.0
SQLite EF6 DbProvider in GAC - No

System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes

Database engine: (SQlite, SQL Compact, SQL Server, Postgres)

Visual Studio version: (e.g. Visual Studio 2017 15.7)

**Comment by DrumHeadTed** [comment]
This also incorrectly detected the VS version.  I am in VS 2019 16.8.4

**Comment by ErikEJ** [comment]
>>This also incorrectly detected the VS version. I am in VS 2019 16.8.4

I do not detect any VS version numbers !? Are you referring to this [issue template](https://github.com/ErikEJ/EFCorePowerTools/blob/master/.github/ISSUE_TEMPLATE.md)?

**Comment by ErikEJ** [comment]
I am sorry to hear that you are missing the removed feature - The removed feature has been replaced [by this](https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#using-multiple-dbcontexts-in-the-same-project) more useful feature, hope you agree?

**Comment by DrumHeadTed** [comment]
Hello Erik!

I do not see this now.  I think perhaps that may have been in the issue
template, and I thought it had copied in from the clipboard.  I will remove
my comment if I can.

**Comment by ErikEJ** [comment]
Yes, I just updated the template to the latest VS version.

**Comment by DrumHeadTed** [comment]
I DO agree!  Thank you!

May I change my rating on the site and close the issue or do you do that?

I really appreciate your responsiveness on this matter.  My teammate
thought this was broken.  But - this has been an amazing tool to work
with which is why it was so surprising that it seemed to leave out such an
important feature for us.

What should I do next to up the rating and close the two issues?

**Comment by ErikEJ** [comment]
I will close this now, and thanks for the feedback! Maybe I should have communicated better that this was changed...

If your colleagues would also post a review, that would be highly appreciated.

**Comment by DrumHeadTed** [comment]
I will ask them to do so!  We are big fans!

One thing that is curious, and I will follow up on is that not all of the
tables and views seem to be in the list of choices any more.  But I will
follow up with my DBA in the morning and see if there is something about
the permissions of these that the EFCPT may see as a difference.    If
there seems to be an issue I will log it.  Thank you again, and have a
great day/night!
