### ISSUE TITLE
Possibility to ignore Graph-table ID column in reverse engineering

### ISSUE THREAD

**Issue by perhederos** [ErikEJ/EFCorePowerTools#768]
Graph-tables creates a very specific NodeID-column. This column gets a specific name per database, which causes problems in development scenario. The workaround is to manually remove the column. [NotMapped] might also work, but that also requries manually modifying the file.

If it is possible please add a possiblity in the reverse engineering to skip this column.

Thank you!

![image](https://user-images.githubusercontent.com/44907202/107747831-62d98f80-6d18-11eb-95ae-a7fdb377d473.png)

### Steps to reproduce
Reverse engineer any graph table.

**Comment by ErikEJ** [comment]
You can uncheck the column in the UI.

**Comment by ErikEJ** [comment]
What would the pattern to look for be?

**Comment by perhederos** [comment]
What do you know? I totally missed that. Thank you!

Sorry for wasting  your time...

**Comment by ErikEJ** [comment]
But that that work well enough for you? You mentioned random names.

**Comment by perhederos** [comment]
It works well enough! My database does not change often so that column name is constant. As I am the only one generating the code it works!

And the other people using the code via an application does not have any problems since that column is not existing since I have unchecked the column.

**Comment by ErikEJ** [comment]
Great, thanks for the additional info. 
Glad you were able to take advantage of this new feature!

**Comment by perhederos** [comment]
And thank you for the great tool! Mange tak!
