### ISSUE TITLE
Proposal: option to create procedures as extensions of context

### ISSUE THREAD

**Issue by pedromcrocha** [ErikEJ/EFCorePowerTools#769]
instead of 

    public partial class DBContextProcedures
    {
        private readonly DBContext _context;

        public DBContextProcedures(DBContext context)
        {
            _context = context;
        }

        public async Task<ProcedureResult[]> ProcedureAsync( OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
      .........

create

    public static partial class DBContextProcedures
    {
        public async Task<ProcedureResult[]> ProcedureAsync( this DBContext context, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
     ........

**Comment by ErikEJ** [comment]
Interesting suggestion, wonder if that should be the default?

**Comment by ErikEJ** [comment]
I will go with this for now, avoids intellisense pollution, and is backwards compatible:

Adding this to the existing scaffolded code:

```
 public static class NorthwindContextProceduresExtensions
    {
        public static NorthwindContextProcedures GetProcedures(this NorthwindContext context)
        {
            return new NorthwindContextProcedures(context);
        }
    }

``` 

allows you to do this:

`var result = await db.GetProcedures().GetXxxAsync();`
