### ISSUE TITLE
incompatibility with character 'ñ' when reverse engineering

### ISSUE THREAD

**Issue by Goldman1337** [ErikEJ/EFCorePowerTools#77]
when trying to reverse engineer a DB with a column with the character 'ñ', the character will be translated as "&#241;"

### Steps to reproduce
create a column in the database with  the character 'ñ' (in my case, the column name was "Contraseña") and then reverse engineer the database. The corresponding POCO property will be named "Contrase&#241;a"

### Further technical details
Version 1.0.604.0

SQL Server Compact 4.0 in GAC - No
SQL Server Compact 4.0 DbProvider - No

SQL Server Compact 4.0 DDEX provider - No
SQL Server Compact 4.0 Simple DDEX provider - Yes

SQLite ADO.NET Provider included: 1.0.107.0
SQLite EF6 DbProvider in GAC - No

System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes

Database engine:
SQL Server
Visual Studio version: 
vs 2017

**Comment by ErikEJ** [comment]
I cannot see any difference?

**Comment by Goldman1337** [comment]
my bad, of course the code translates to "ñ" in most situations:
 & # 2 4 1 ; 
(without the spaces)

**Comment by ErikEJ** [comment]
So this can be closed?

**Comment by Goldman1337** [comment]
sorry, it seems i'm not making myself clear, in my last post i meant that this page is translating that code to "ñ", but the addon isn't.
the result i'm getting when reverse engieniering the field "Contraseña" is this:
![image](https://user-images.githubusercontent.com/13630814/43364295-e8ed5924-92ed-11e8-92a3-adf4ea6e810f.png)

**Comment by ErikEJ** [comment]
>> that this page 

What page??

**Comment by ErikEJ** [comment]
I am not able to reproduce, can you share a SQL script for the table that is causing issues?

**Comment by Goldman1337** [comment]
[SQLQuery1.zip](https://github.com/ErikEJ/EFCorePowerTools/files/2243030/SQLQuery1.zip)

**Comment by ErikEJ** [comment]
Thanks, still unable to reproduce - can you share a VS project that demonstrates the issue?

**Comment by ErikEJ** [comment]
Now you are telling me!! 😄  

Please clarify what you mean by this, maybe the templates should be updated:

>> also unrelated, but when using the templates constructors are not being created on the context class

**Comment by ErikEJ** [comment]
It is a Handelbars issue! https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars/issues/30

**Comment by Goldman1337** [comment]
awesome, my bad, that should've been the first thing i mentioned.

what i meant by that was that this code:

```
public SanitariosContext()
        {
        }

        public SanitariosContext(DbContextOptions<SanitariosContext> options)
            : base(options)
        {
        }
```
is not being created when using templates.

(SanitariosContext is my dbcontext name)

**Comment by ErikEJ** [comment]
I suggest you report that in the EF Core Handlebars repo, looks like they are missing from the template:

https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars/blob/master/src/EntityFrameworkCore.Scaffolding.Handlebars/CodeTemplates/CSharpDbContext/DbContext.hbs

**Comment by ErikEJ** [comment]
Fixed in latest daily!
