### ISSUE TITLE
Unsupported provider with EF Core 5.0: Oracle

### ISSUE THREAD

**Issue by mariohik** [ErikEJ/EFCorePowerTools#770]
Now that Oracle realesed their Oracle.EntityFrameworkCore for EFCore 5.0, could you please make it available on EF Power Tools?

![image](https://user-images.githubusercontent.com/38980017/107804029-2cb10580-6d42-11eb-8c3a-661d4c99693b.png)

### Steps to reproduce
I'm trying to Reverse Engenieer on Oracle database using EFCore 5.0

### Further technical details
EF Core Power Tools version: 2.5.454.0

Database engine: Oracle

Visual Studio version: Visual Studio 2019 - 16.9.0 Preview 4

**Comment by ErikEJ** [comment]
Thanks, I was not aware it had been released.

**Comment by ErikEJ** [comment]
Please give the latest daily a try, and let me know if it works for you (I have no way of testing it)

**Comment by mariohik** [comment]
Hi @ErikEJ ,
I did some tests and so far everything worked perfectly.

**Comment by ErikEJ** [comment]
Thanks for confirming!
