### ISSUE TITLE
[Key] attribute gets overwritten on view object model

### ISSUE THREAD

**Issue by balajeek** [ErikEJ/EFCorePowerTools#776]
Thanks for the great tool, very very useful on my .net core webapi, using the latest version of yours.

I have been using it for few months, recently I added two views from ms-sql, webapi controller want a [key] column to be present in order for me to use it, so I go and edit the model and add [key] attribute and all works fine, but then when I do the reverse engineer again for some other object, my other view [key] attribute disappears.  So what I have been doing now is after I do the reverse engineer option, I go back again to my 3 views and add the [key] attribute.

Are there any better way?

Database engine:  SQL Server 2019

Visual Studio version: Visual Studio 2019 16.8

**Comment by ErikEJ** [comment]
You can remove the header to preserve the file, as described in the docs: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#saving-options-and-running-the-second-time - or maybe use a buddy metadata class.

**Comment by ErikEJ** [comment]
Ping?

**Comment by balajeek** [comment]
Sorry I am a way from computer on this long weekend, will be back tonight and will let you know. 

Thank you for your fast response as always. 


🅱

**Comment by balajeek** [comment]
I followed the instruction said under section "Saving options and running the second time" where it says to remove the first line of the model which is already a commented line "// <auto-generated>..."  

After removing the line entirely I re-run the reverse engineer and just clicked okay without adding/removing any objects, but still my view lost the [Key] attribute I added.

Next, you also gave link for doing buddy classes, I checked it out and I see an example but I still did not understand where and how I would do this. sorry.

**Comment by ErikEJ** [comment]
>> After removing the line entirely I re-run the reverse engineer and just clicked okay without adding/removing any objects, but still my view lost the [Key] attribute I added.

That sounds like a bug! I will try to reproduce

**Comment by ErikEJ** [comment]
Sorry, you will either have to unselect the file, or rename it - it will make the docs clearer

**Comment by balajeek** [comment]
No problem, thank you.
