### ISSUE TITLE
Increased User-Control for OnModelCreating

### ISSUE THREAD

**Issue by svernyi** [ErikEJ/EFCorePowerTools#78]
Would it be possible to expand the Handlebars customization for OnModelCreating to support users implementing their own extensions inside of it? For example, I need to configure some views in the ModelBuilder. Doing so would result in them being erased every time I regenerate the DB.

If I could change the OnModelCreating to call a class method, and then implement the method in a separate partial class file, I would be able to configure my views in a separate file from the reverse generator. More importantly, it wouldn't require any additional manual copy-pasting of code to fix the then-overwritten OnModelCreating method.

If there's another systematic approach to this that I'm overlooking that currently works, please let me know. Thank you! 

### Technical Details 
EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
1.0.643
Database engine: (SQlite, SQL Compact, SQL Server, Postgres)
SQL Server
Visual Studio version: (e.g. Visual Studio 2017 15.7)
2017 15.4

**Comment by svernyi** [comment]
I'm envisioning something like.. 
`
{{{on-model-creating}}}
`
->

```
protected override void OnModelCreating(ModelBuilder modelBuilder)  
{  
    {{{on-model-creating}}}  
}  
```

**Comment by ErikEJ** [comment]
Have you tried the latest release without Handlebars involved?
 - you should have OnModeCreatingPartial method

**Comment by svernyi** [comment]
In the wise words of Homer Simpson: D'oh! 

Thank you!
