### ISSUE TITLE
Hints to generate list of interfaces

### ISSUE THREAD

**Issue by SandroRiz** [ErikEJ/EFCorePowerTools#784]
I would like to use EF Power Tool to generate other types of classes beyond the Models (eg. autogenerated biz, dal, services, etc)

Eg foreach table generate an interface called I{{class}}Service.cs with this content 

```
namespace MyCustom.Namespace.Services
{
    public partial interface IOrderService : IBaseService<Order, **int**>
    {

    }
}
```

Playing with the Class.hbs codetemplate I wasn't able to;
- change the filename (IOrderService.cs instead Order.cs)
- discover the type of Primary Key (int in my sample)

I don't know if it is doable with the current release, if not consider a suggestion

**Comment by ErikEJ** [comment]
This is not something I plan to do, have a look at the T4 solution https://github.com/bricelam/EFCore.TextTemplating
