### ISSUE TITLE
data context list error

### ISSUE THREAD

**Issue by Varorbc** [ErikEJ/EFCorePowerTools#791]
![image](https://user-images.githubusercontent.com/5714438/108298685-505bcc00-71d8-11eb-8d4c-f0dbd9fe547b.png)

suggestion:

use `ActiveSolutionProjects`   instead of `StartupProjects`

https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/EFCorePowerTools/Extensions/EnvDTEExtensions.cs#L63

use `Regex`   instead of `Split`
https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/EFCorePowerTools/Handlers/ProcessLauncher.cs#L48
https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/EFCorePowerTools/ViewModels/MigrationOptionsViewModel.cs#L232

### Further technical details
EF Core Power Tools version: 2.5.523

Database engine: SQL Server

Visual Studio version: Visual Studio 2019 16.8

**Comment by ErikEJ** [comment]
I need a repro solution in order to fix this, is that something you can provide - otherwise I am in the blind?

>> use ActiveSolutionProjects instead of StartupProjects

This method is about getting the startup project, so I do not understand your suggestion.

>> use Regex instead of Split

In order to provide a proper fix, I need a repro project.

**Comment by Varorbc** [comment]
```csharp

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EfCore.SchemaCompare" Version="5.1.3" PrivateAssets="All" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.3" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="5.0.0" />
  </ItemGroup>

</Project>

using System;
using Microsoft.EntityFrameworkCore;

namespace ConsoleApp1
{
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args);
        }

        public static void CreateHostBuilder(string[] args)
        {
            Console.WriteLine("莫名其妙的问题");
        }
    }

    public class TestContext : DbContext
    {
    }
}


```

**Comment by ErikEJ** [comment]
And that results in the output in your screenshot?

What OS language and version are you on?

**Comment by Varorbc** [comment]
> This method is about getting the startup project, so I do not understand your suggestion.

If there are multiple projects in the solution, and the reverse engineering project is not the startup project

**Comment by ErikEJ** [comment]
>> If there are multiple projects in the solution, and the reverse engineering project is not the startup project

This method has nothing to do with reverse engineering, it is used with model inspection / migrations tool. And I know the current project, but the tool works better in some scenarios if it also know the startup project.

**Comment by Varorbc** [comment]
![image](https://user-images.githubusercontent.com/5714438/108326169-e73e7d80-7204-11eb-95fa-7c03471ce894.png)
![image](https://user-images.githubusercontent.com/5714438/108326193-eefe2200-7204-11eb-8f88-04a53fc35cf5.png)
![image](https://user-images.githubusercontent.com/5714438/108326389-21a81a80-7205-11eb-8cc3-42a0aac530db.png)

windows 10.0.19042

**Comment by ErikEJ** [comment]
Sorry for my ignorance, but is that Chinese? And if so, which variant?

I think it is going to be very difficult for me to repro, are you willing to do a PR?
