### ISSUE TITLE
Migrations tool error

### ISSUE THREAD

**Issue by MuTsunTsai** [ErikEJ/EFCorePowerTools#792]
Upon opening the migrations tool, the following error appears. I haven't been using the tool for a while and I'm sure since when this started to happen.

![image](https://user-images.githubusercontent.com/39870664/108302785-a7b16a80-71df-11eb-9a34-9734f036c179.png)

### Further technical details
EF Core Power Tools version: 2.5.513.0

Database engine: MySQL

Visual Studio version: Visual Studio 2019 16.8.4

**Comment by ErikEJ** [comment]
Should be fixed in latest daily build, are you able to try that out and confirm?
https://github.com/ErikEJ/EFCorePowerTools/wiki/Release-notes

**Comment by MuTsunTsai** [comment]
After installed the daily build, a different error appeared. I couldn't quite figure out how to solve this either.

![image](https://user-images.githubusercontent.com/39870664/108330870-1951de80-7209-11eb-8af3-298ec75e2981.png)

**Comment by MuTsunTsai** [comment]
Yes it is fixed! Thank you.
