### ISSUE TITLE
reverse engenieer -  EntityTypes path with dot

### ISSUE THREAD

**Issue by pedromcrocha** [ErikEJ/EFCorePowerTools#794]
question 
when use EntityTypes path with dot ex 'Main.Model'
now creates folder 
.\Main.Model
but is not suppose create 
.\Main
.\Main\Model

**Comment by ErikEJ** [comment]
Hmmm... Good question

**Comment by ErikEJ** [comment]
Does it not work as expected if you use: `Main/Model` ??

**Comment by ErikEJ** [comment]
Ping?

**Comment by pedromcrocha** [comment]
works fine, my mistake
