### ISSUE TITLE
How can I register a Handle Bar Helper?

### ISSUE THREAD

**Issue by HSchwichtenberg** [ErikEJ/EFCorePowerTools#796]
Hi Eric,

a question: I like to register a handle bar helper (as described in https://github.com/Handlebars-Net/Handlebars.Net#registering-helpers). I have no idea where to do that so that the Power Tools pick that up when regenerating the code.

Thanks
Holger

**Comment by ErikEJ** [comment]
Currently, you must use the command line tooling to do this, see #166 

Why do you need handlebars helpers?

**Comment by ErikEJ** [comment]
Ping?

**Comment by HSchwichtenberg** [comment]
>Why do you need handlebars helpers?

The requirement is to change some (!) class names ( public partial class {{class}} -->  public partial class {{rename class}} based on a config file. How can I do this?

**Comment by ErikEJ** [comment]
Rename the tables/views (F2 in the UI) ??

**Comment by HSchwichtenberg** [comment]
;-) No, too many tables. 

It should be an automatic, repeatable process based on the existing list of desired class names.

**Comment by HSchwichtenberg** [comment]
Annother requirement: Print the datetime of class generation into the files. I think, I need a  handlebar helper for this too. Don't I?

**Comment by ErikEJ** [comment]
For rename, you could use a regex?
Can be defined in the renaming file.

For time-stamping the file - never been asked to do that before, but currently not implemented.

Don't understand that requirement - do you not use source control?
