### ISSUE TITLE
Reverse Engineer deletes all dacpacs from database project folder

### ISSUE THREAD

**Issue by scalablecory** [ErikEJ/EFCorePowerTools#80]
If a database project references DACPAC files that are inside the database projects folder, attempting to reverse engineer the database project deletes the DACPAC files without warning and gives an error message "build failed".

### Steps to reproduce
1. Create a database project.
2. Put a DACPAC into the database project's folder, and add it as a reference to the database project.
3. Create a new project using EF Core.
4. Attempt to Reverse Engineer the database project.

### Further technical details
EF Core Power Tools version: 1.0.643.0

Database engine: SQL Server (SSDT)

Visual Studio version: 15.7.5

**Comment by ErikEJ** [comment]
Wauw, I did not know you could do that. I will look into a fix, and thanks for reporting

**Comment by ErikEJ** [comment]
Fixed in latest daily build
