### ISSUE TITLE
The 'EFCorePowerToolsPackage' package did not load correctly

### ISSUE THREAD

**Issue by wottevanger** [ErikEJ/EFCorePowerTools#806]
When I start up my visual studio project I get this error message:

![afbeelding](https://user-images.githubusercontent.com/69509342/108709094-8e2b5e00-7512-11eb-8ca2-a769898c06fd.png)

Not sure what is causing this issue, the error message says it might be cause by another extension, so I disabled all the extensions I could. Only disabling Xamarin templates 16.4.25 was impossible.
Disabling all extensions did not help.

In ActivityLog.xml there are a lot of records, but only 2 mention EFCorePowerTools:

```
<entry>
    <record>898</record>
    <time>2021/02/22 12:20:11.791</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [EFCorePowerToolsPackage]</description>
    <guid>{F4C4712C-CEAE-4803-8E52-0E2049D5DE9F}</guid>
  </entry>
  <entry>
    <record>899</record>
    <time>2021/02/22 12:20:11.859</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [EFCorePowerToolsPackage]Source: &apos;Microsoft.ApplicationInsights&apos; Description: The type initializer for &apos;Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration&apos; threw an exception.&#x000D;&#x000A;System.TypeInitializationException: The type initializer for &apos;Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration&apos; threw an exception. ---&gt; System.TypeLoadException: Could not load type &apos;System.Diagnostics.Activity&apos; from assembly &apos;System.Diagnostics.DiagnosticSource, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51&apos;.&#x000D;&#x000A;   at Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration.&lt;&gt;c.&lt;.cctor&gt;b__13_0()&#x000D;&#x000A;   at Microsoft.ApplicationInsights.ActivityExtensions.TryRun(Action action) in E:\A\_work\13\s\BASE\src\Microsoft.ApplicationInsights\ActivityExtensions.cs:line 31&#x000D;&#x000A;   at Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration..cctor() in E:\A\_work\13\s\BASE\src\Microsoft.ApplicationInsights\Extensibility\TelemetryConfiguration.cs:line 59&#x000D;&#x000A;   --- End of inner exception stack trace ---&#x000D;&#x000A;   at Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration.get_Active()&#x000D;&#x000A;   at EFCorePowerTools.Helpers.Telemetry.Initialize(DTE2 dte, String version, String vsVersion, String telemetryKey) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Helpers\Telemetry.cs:line 27&#x000D;&#x000A;   at EFCorePowerTools.EFCorePowerToolsPackage.&lt;InitializeAsync&gt;d__11.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\EFCorePowerToolsPackage.cs:line 146&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass20_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Threading.JoinableTask.&lt;JoinAsync&gt;d__68.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.GetResult()System.TypeLoadException: Could not load type &apos;System.Diagnostics.Activity&apos; from assembly &apos;System.Diagnostics.DiagnosticSource, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51&apos;.&#x000D;&#x000A;   at Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration.&lt;&gt;c.&lt;.cctor&gt;b__13_0()&#x000D;&#x000A;   at Microsoft.ApplicationInsights.ActivityExtensions.TryRun(Action action) in E:\A\_work\13\s\BASE\src\Microsoft.ApplicationInsights\ActivityExtensions.cs:line 31&#x000D;&#x000A;   at Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration..cctor() in E:\A\_work\13\s\BASE\src\Microsoft.ApplicationInsights\Extensibility\TelemetryConfiguration.cs:line 59</description>
    <guid>{F4C4712C-CEAE-4803-8E52-0E2049D5DE9F}</guid>
    <hr>80131534</hr>
    <errorinfo></errorinfo>
  </entry>
</activity>
```

### Steps to reproduce
I dont know how to reproduce this issue, EFCorePowerTools used to work. I noticed that Visual studio had the update automatically option checked, so maybe it stopped working after a certain update. I havent used EFCorePowerTools in a couple of months, so I couldnt exactly say when it stopped working.

### Further technical details
EF Core Power Tools version: 2.5.536

Database engine: MS SQL Server (but this does not really matter since the extension wont start)

Visual Studio version: Visual Studio Enterprise 2019 16.4.5

**Comment by ErikEJ** [comment]
Fixed in latest daily (on its way to MarketPlace)

**Comment by WesselOttevangerElvy** [comment]
Hi, I am having this issue again. Im the same person, just a different Github account.
I had auto update enabled, but I guess this issue is in the newer version.

Is there a way for me to download the fixed version from 22 feb again?

**Comment by ErikEJ** [comment]
I am not planning to disable application insights in the future.

Please try to repair your VS install.

Which VS version do you use?

Is this isolated to a single machine?

**Comment by WesselOttevangerElvy** [comment]
Wait I think I messed up sorry, I thought it was the same exception, but I double checked and it seems to be different. Do you want me to make a separate issue?

the new exception is:

`<entry>
    <record>928</record>
    <time>2021/04/29 13:58:58.308</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>CreateInstance failed for package [EFCorePowerToolsPackage]Source: &apos;mscorlib&apos; Description: Exception has been thrown by the target of an invocation.&#x000D;&#x000A;System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---&gt; System.IO.FileNotFoundException: Could not load file or assembly &apos;Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;   at EFCorePowerTools.EFCorePowerToolsPackage.CreateServiceProvider()&#x000D;&#x000A;   at EFCorePowerTools.EFCorePowerToolsPackage..ctor() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\EFCorePowerToolsPackage.cs:line 60&#x000D;&#x000A;   --- End of inner exception stack trace ---&#x000D;&#x000A;   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean&amp; canBeCached, RuntimeMethodHandleInternal&amp; ctor, Boolean&amp; bNeedSecurityCheck)&#x000D;&#x000A;   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark&amp; stackMark)&#x000D;&#x000A;   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark&amp; stackMark)&#x000D;&#x000A;   at System.Activator.CreateInstance(Type type, Boolean nonPublic)&#x000D;&#x000A;   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark&amp; stackMark)&#x000D;&#x000A;   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)&#x000D;&#x000A;   at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)&#x000D;&#x000A;   at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName)System.IO.FileNotFoundException: Could not load file or assembly &apos;Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;File name: &apos;Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51&apos;&#x000D;&#x000A;   at EFCorePowerTools.EFCorePowerToolsPackage.CreateServiceProvider()&#x000D;&#x000A;   at EFCorePowerTools.EFCorePowerToolsPackage..ctor() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\EFCorePowerToolsPackage.cs:line 60&#x000D;&#x000A;&#x000D;&#x000A;WRN: Assembly binding logging is turned OFF.&#x000D;&#x000A;To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.&#x000D;&#x000A;Note: There is some performance penalty associated with assembly bind failure logging.&#x000D;&#x000A;To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].&#x000D;&#x000A;</description>
    <guid>{F4C4712C-CEAE-4803-8E52-0E2049D5DE9F}</guid>
    <hr>80004005 - E_FAIL</hr>
    <errorinfo></errorinfo>
  </entry>
`

**Comment by ErikEJ** [comment]
What .NET version on your PC?

Which VS version?

**Comment by WesselOttevangerElvy** [comment]
.NET version: .NET core 3.1

VS version: 16.4.5

**Comment by ErikEJ** [comment]
I meant .net framework version.

But please update your VS install.

**Comment by WesselOttevangerElvy** [comment]
Updating my VS worked, thanks for the quick reponses!
