### ISSUE TITLE
ASP.NET/EF Core 2.1.1 - Crash on Add DbContext Model Diagram

### ISSUE THREAD

**Issue by scottpage** [ErikEJ/EFCorePowerTools#81]
Describe what is not working as expected.
Add DbContext Model Diagram

### Steps to reproduce
Include a complete description that I can redo to reproduce the issue.
1) Install EF Core Power Tools from Visual Studio 2017 Extensions and Updates.
2) Close VS, wait for EFCPT to finish installing.
3) Open VS and open existing solution, with existing DbContext (actually two (2) contexts exist in the project I'm working with).
4) Right click project and select 'Add DbContext Model Diagram'.
5) Observe "System.IO.FileNotFoundException", referencing Microsoft.AspNetCore.Hosting.Abstractions.

### Further technical details
EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
1.0

Database engine: (SQlite, SQL Compact, SQL Server, Postgres)
SQL Server 14.0.1000

Visual Studio version: (e.g. Visual Studio 2017 15.7)
Visual Studio Community 2017 15.7.5

See this gist for the exception:  https://gist.github.com/scottpage/4a6c26898033c141f9c14d5b7359470b#file-efcpt1_0-crash-aspnetefcore211-txt

**Comment by scottpage** [comment]
FYI, I added the referenced library, Microsoft.AspNetCore.Hosting.Abstractions, with NuGet, and tried again.  Same exception is thrown again.  Maybe I'm missing something.  I have an update pending in VS to 15.7.6, I'll have a go at installing it and running it again.

Further, I'll fork your repository and attempt to give you a hand locating the failure.

Thanks, BTW, for the exceptional work on getting a tool like this out to the community.  It's a shame that MS hasn't done this yet.  It was a gift in .NET EF.

**Comment by ErikEJ** [comment]
I think your issue may be related to: https://github.com/ErikEJ/EFCorePowerTools/issues/50 

Please let me know if I can help, if you decide on an attempt to fix!

Also, this workaround might be able to unblock you for now: https://github.com/ErikEJ/EFCorePowerTools/wiki/Inspect-your-DbContext-model
