### ISSUE TITLE
Compare database and contexts - add support for other providers (MySQL, Npgsql)

### ISSUE THREAD

**Issue by giuseppe-terrasi** [ErikEJ/EFCorePowerTools#810]
If I try to detect changes between DbContext and DB I get this error: 

![image](https://user-images.githubusercontent.com/5776240/109025874-6cbba500-76bf-11eb-8d05-d4a90bc4e32d.png)

### Steps to reproduce
Right-click on project -> EF Core Power Tools -> Compare DbContext to database
Select both and then click OK

### Further technical details
EF Core Power Tools version: 2.5.537.0

Database engine: MySQL

Visual Studio version: Visual Studio 2019 16.9.0 Preview 5.0

**Comment by ErikEJ** [comment]
That should already be improved in the latest daily build. Could you please give that a try.

**Comment by giuseppe-terrasi** [comment]
I've installed the daily version 2.5.540.0 and the problem is still present. The error is the same but the version of the searched packages changed to 5.1.3.0.
Thanks.

**Comment by ErikEJ** [comment]
Please share the contents of your .csproj file.

**Comment by ErikEJ** [comment]
Ping?

**Comment by giuseppe-terrasi** [comment]
Sorry for the delay. Here is my .csproj file:
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EfCore.SchemaCompare" Version="5.1.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Grpc.AspNetCore" Version="2.35.0" />
    <PackageReference Include="Grpc.AspNetCore.Server.Reflection" Version="2.35.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="5.0.3" NoWarn="NU1605" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="5.0.3" NoWarn="NU1605" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="5.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="5.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="5.0.0-alpha.2" />
    <PackageReference Include="Serilog" Version="2.10.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="3.4.0" />
    <PackageReference Include="Serilog.Enrichers.Environment" Version="2.1.3" />
    <PackageReference Include="Serilog.Enrichers.Thread" Version="3.1.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="3.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="4.1.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.0.7" />
  </ItemGroup>

  <ProjectExtensions><VisualStudio><UserProperties appsettings_1development_1json__JsonSchema="https://json.schemastore.org/appsettings" /></VisualStudio></ProjectExtensions>

</Project>
```
After restarting Visual Studio I received a new error:

![image](https://user-images.githubusercontent.com/5776240/109126948-26615700-774e-11eb-92c2-bbac32948c17.png)

**Comment by ErikEJ** [comment]
Based on feedback I will investiagte support for additional providers

**Comment by ErikEJ** [comment]
Need to avoid having to load all providers !?

**Comment by giuseppe-terrasi** [comment]
I didn't understand your question. I've added the nuget package Pomelo in order to use MySql and I've have used the extension to compare DB and context receiving the error. If you are referring to the Ef.SchemaCompare package with the option <PrivateAssets>all</PrivateAssets> it was included automatically by your extension.

**Comment by ErikEJ** [comment]
Sorry, it was just a note for myself!

**Comment by ErikEJ** [comment]
Idea: add conditional compiled project and zip file per provider.

**Comment by ErikEJ** [comment]
Closing and moving to Backlog milestone

**Comment by ErikEJ** [comment]
This is actually possible in EF Core 8 now
