### ISSUE TITLE
FileNotFoundException while launching Migration Tool

### ISSUE THREAD

**Issue by mikethibault** [ErikEJ/EFCorePowerTools#816]
Suddenly I'm getting a FileNotFoundException for Microsoft.Extensions.Hosting.Abstractions when I try to launch the Migration Tool.
![efCorePowerToolsError](https://user-images.githubusercontent.com/284372/109255294-b391c380-77c1-11eb-9659-0d71f74a6d0e.PNG)

### Steps to reproduce
I've used the tool successfully dozens of times in this same project.  The only appreciable change I made before it stopped working was adding another project to the same solution which references the context-containing project.  Still, previously I had two other projects making the same reference, this is the third in the same solution.

### Further technical details
EF Core Power Tools version: 2.5.537

Database engine: SQL Server

Visual Studio version: Visual Studio 2019 16.8.3

**Comment by ErikEJ** [comment]
Make sure to set the correct startup project in your solution.

**Comment by mikethibault** [comment]
That did it!  Thank you!  Although I don't think I ever had the project with my context in it as the default before.

**Comment by ErikEJ** [comment]
I have added logic to make better use of the startup project recently to the tool.
