### ISSUE TITLE
[question]virtual relationships

### ISSUE THREAD

**Issue by Goldman1337** [ErikEJ/EFCorePowerTools#82]
is there any change when using "virtual" for relationships even when not using lazy loading?
if there isn't, wouldnt it be more practical to add the keyword always, to avoid using the handlebar templates only for that?

**Comment by ErikEJ** [comment]
It will come when I update Reverse Engineering to use EF Core 2.2

https://github.com/aspnet/EntityFrameworkCore/blob/release/2.2/src/EFCore.Design/Scaffolding/Internal/CSharpEntityTypeGenerator.cs#L315

**Comment by ErikEJ** [comment]
Fixed in latest daily build
