### ISSUE TITLE
Bug: the "Install EF Core provider package in the project" flag is not stored to the configuration file

### ISSUE THREAD

**Issue by not-authorized** [ErikEJ/EFCorePowerTools#822]
The "Install EF Core provider package in the project" flag is always checked. Needs to be unchecked every time you run the tool.

### Steps to reproduce
Uncheck the flag and generate the model. The flag remains checked on subsequent runs.

### Further technical details
EF Core Power Tools version: 2.5
Database engine: Postgres
Visual Studio version: 16.8.5

**Comment by ErikEJ** [comment]
It has never be stored in the .config file.

Is it checked if the provider package is installed in the project?

**Comment by not-authorized** [comment]
I don't need a provider for the project. A clean model is required.

**Comment by ErikEJ** [comment]
So you are in this case choosing to generate Entities only?

**Comment by not-authorized** [comment]
Correct

**Comment by ErikEJ** [comment]
Ok, in that case, I can just uncheck the option in the UI, if not unchecked already.
