### ISSUE TITLE
Unable to remove connection

### ISSUE THREAD

**Issue by yangbodevp** [ErikEJ/EFCorePowerTools#831]
Two questions:
1. I successfully connected to my database using PowerTools ,But when my database connection string changes, I can't add to the database select box again .This happened after the `user` of my database connection string changed.

**first connection string:**
`Server=127.0.0.1;port=3306;database=mydb;user=root;password=123456a;Pooling=True;Max Pool Size=10;Min Pool Size=5`
success
**modified connection string:**
`Server=127.0.0.1;port=3306;database=mydb;user=dbuser;password=123456a;Pooling=True;Max Pool Size=10;Min Pool Size=5`
error
2. About deleting, I want to delete the selected database, when i click the X button, it doesn't work. Alert: `Unable to remove connection`.
I want to know where is the data in the database selection box stored?

### Further technical details

EF Core Power Tools version: 2.5.537
Database engine: MYSQL
Provider: Pomelo.EntityFrameworkCore.MySql 3.2.4
Visual Studio version: Visual Studio 2019 16.8

**Comment by ErikEJ** [comment]
You can remove connections from Server Explorer.

Please provide more info/ error message for the first question

**Comment by ErikEJ** [comment]
Ping??

**Comment by ErikEJ** [comment]
Closing this, feel free to re-open if you can provide actual error information.

**Comment by yangbodevp** [comment]
After I found the problematic Connection from Server Explorer and deleted it, the problem was resolved.Thank you very much.

**Comment by ErikEJ** [comment]
Great, thanks for the heads up.
