### ISSUE TITLE
Pluralizer issue

### ISSUE THREAD

**Issue by MrMuMu** [ErikEJ/EFCorePowerTools#832]
Describe what is not working as expected.
Although some properties are created fine, pluralizer is not working as expected, look below:

```
public virtual DbSet<AccountStatu> AccountStatus { get; set; } // this is not ok, it should be `AccountStatus` for type and `AccountStatuses` or `AccountStatus` for property name
public virtual DbSet<AccountType> AccountTypes { get; set; } // this ok
```

Also the configurations are generated with wrong file name as well, same as above

### Steps to reproduce
Include a complete description that I can redo to reproduce the issue.
Do a reverse engineer with `ReverseEngineerCommandOptions` configured as follows:

```
UseFluentApiOnly = true,
UseDbContextSplitting = true,
UseLegacyPluralizer = true,
UseNoObjectFilter = true,
... rest
```

### Further technical details
Using from cli
Database engine:  Postgres

**Comment by ErikEJ** [comment]
That is how the legacy pluralizer works, and no changes will happen to it to stay compatible with EF6 - maybe try not to use the legacy pluralizer?

**Comment by MrMuMu** [comment]
I did not know `UseInflector` option was for it. Your comment lead me to that thank you!
