### ISSUE TITLE
Add support for initial data on reverse engineering

### ISSUE THREAD

**Issue by MrMuMu** [ErikEJ/EFCorePowerTools#835]
We have some tables that are mostly static and it would be very nice if there was an option to pass in order to reverse engineer certain tables with `HasData` functions.

For example:

I have `MyType` table which has the following structure.

```
public class MyType
{
    public long Id { get; set; }
    public string Field1 { get; set; }
    public string Field2 { get; set; }
}
```
This table has records in it and I would like to tell reverse engineer to create the initial data for `MyType` table. So it would look like this in `DbContext`or `MyTypeConfiguration` file:

```
...
builder.HasData(
    new MyType { Id = 1, Field1 = "Power", Field2 = "Tools" },
    new MyType { Id = 2, Field1 = "EF", Field2 = "Core" }
);
```

As a suggestion we can pass these table names as parameter to reverse engineer so that it will only create initial data for only those tables.

**Comment by ErikEJ** [comment]
Are you not able to do that with a partial DbContext and then implementing the OnModelCreatingPartial method ?
See link to an example in the docs here:
https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#extending-the-generated-dbcontext-class-and-entity-classes

**Comment by ErikEJ** [comment]
Ok, I think I understand better now - interesting suggestion.

I thought that HasData was only used by migrations - not sure I understand how it would work with Reverse Engineering.

**Comment by MrMuMu** [comment]
We will use it for migration actually. We are configuring on dev database and reverse engineer that. After that, we create migration to apply those changes to test and prod environments.

**Comment by ErikEJ** [comment]
I that case it is not something I plan to implement, also given you can do it manually already
