### ISSUE TITLE
[Feature Request] Reverse Engineer copies script code to clipboard

### ISSUE THREAD

**Issue by Vizehase** [ErikEJ/EFCorePowerTools#84]
In my review I reported about my reverse engineering experiences. I have working custom code and Handlebars templates for our database which works with a call of Scaffold-DbContext in Package Manager console. However, EF Core Power Tools is designed to do a similar job using HandleBars templates without looking for code in the user's project, but it handles everything internally such that the target project does not need to reference some Nuget packages. Thus, **no custom Handlebars helpers** can be used.
If directly calling my code from EF Core Power Tools cannot be done easily, then another simple approach would be very convenient: In the "Reverse Engineer" GUI's last screen, add another button **"Copy script call"** which copies the user input done so far to the clipboard, e.g.
`Scaffold-DbContext "Data Source=srv-sql01;Initial Catalog=MyDb;Integrated Security=True" -Provider Microsoft.EntityFrameworkCore.SqlServer -DataAnnotations -UseDatabaseNames -o Scaffolding -Context ScaffoldedContext -tables t_m_prod,t_notes,x_mprod_mprod -f`

**Comment by ErikEJ** [comment]
Thanks, that is actually a very good suggestion regardless of handlebar helper issues

**Comment by ErikEJ** [comment]
Not deemed useful enough, closing and moving to backlog, I anybody wants to do it.

**Comment by ErikEJ** [comment]
@Vizehase The CLI edition should solve this for you
