### ISSUE TITLE
Split DbContext not working in .NET Framework 4.8 projects

### ISSUE THREAD

**Issue by kogelnikp** [ErikEJ/EFCorePowerTools#840]
The option "Split DbContext into Configuration classes (preview)" produces configuration classes, which are not compilable in .NET Framework 4.8. This is because the directive "#nullable disable" is included in every configuration file. Unfortunately, C# 8 is not supported in .NET Framework projects, so this leads to compiler errors.

![grafik](https://user-images.githubusercontent.com/8058487/110501318-5a4b5d80-80fa-11eb-9fa0-87858848d1b6.png)

![grafik](https://user-images.githubusercontent.com/8058487/110497765-0b4ff900-80f7-11eb-91ed-e61e6b3ce21e.png)

For projects which still use a C# version older than 8, this line should not be included:
https://github.com/ErikEJ/EFCorePowerTools/blob/3adb32f6c657bbd66a039b5c7e620f218d65e1be/src/GUI/RevEng.Core/DbContextSplitter.cs#L75

### Steps to reproduce
* "Reverse engineer" in a .NET Framework 4.8 project
* Select tables
* Select "Split DbContext into Configuration classes (preview)" in advanced options
* Try to compile generated code

### Further technical details
EF Core Power Tools version: 2.5.537
Database engine: SQL Server
Visual Studio version: Visual Studio 2019 16.8

**Comment by kogelnikp** [comment]
Works perfectly, thanks!

**Comment by ErikEJ** [comment]
You are welcome, and thanks for confirming
