### ISSUE TITLE
Function and stored procedure files not added to .NET Framework project file

### ISSUE THREAD

**Issue by kogelnikp** [ErikEJ/EFCorePowerTools#844]
When doing reverse engineering in a .NET Framework 4.8 project, the resulting function and stored procedure files are not getting included in the project file. 

![grafik](https://user-images.githubusercontent.com/8058487/110755626-74478600-8249-11eb-8b8f-80b0738f72e4.png)

The reason seems to be that these files are not added to the ReverseEngineeringResult:

https://github.com/ErikEJ/EFCorePowerTools/blob/f8ec0a7b3b7b2befb9add83ae887376dbce831f6/src/GUI/RevEng.Core/ReverseEngineerRunner.cs#L110-L117

Sorry for causing so many troubles with my .NET Framework requirements :grinning:

### Steps to reproduce
* Reverse engineer database in .NET Framework project
* Include functions or stored procedures

### Further technical details
EF Core Power Tools version: 2.5.557.0
Database engine: SQL Server
Visual Studio version: Visual Studio 2019 16.9

**Comment by ErikEJ** [comment]
Why are you still using .NET Framework??

😅

As a workaround, you can just add the manually ?

**Comment by kogelnikp** [comment]
Yep, that works for me. I just wanted to document it somewhere in case anyone else faces the same issue.

> Why are you still using .NET Framework??
> 
> 😅

For common reasons I guess: old project and too large and complex to upgrade it all at once :sweat_smile:

**Comment by ErikEJ** [comment]
I attempted a fix in the latest daily build
