### ISSUE TITLE
Unable to collect model information - Contoso University Tutorial

### ISSUE THREAD

**Issue by ctdevaughn** [ErikEJ/EFCorePowerTools#847]
I am working my way through the Microsoft tutorial [Get started with EF Core in an ASP.NET MVC web app](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/intro?view=aspnetcore-5.0) and came across mention of the EF Core Power Tools extension, but am unable to get it to work.  I get this error no matter which option I select from the context menu...

System.ArgumentException: Unable to collect model information
Parameter name: processResult
   at EFCorePowerTools.Handlers.ModelAnalyzerHandler.<GenerateAsync>d__2.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ModelAnalyzerHandler.cs:line 72

Steps to reproduce:

I have completed the tutorial through the "Many-to-Many relationships" section of the "Create a complex data model" section.

Technical details:

Environment: VS 2019 v16.9.0, Extension Version: 2.5.537, SQL Local DB, Target Framework .NET 5.0, Microsoft.EntityFrameworkCore v5.0.4

Any ideas?

**Comment by ErikEJ** [comment]
Suggest you share your project.

**Comment by ErikEJ** [comment]
Suggest you share your project.

**Comment by ErikEJ** [comment]
Suggest you share your project.

**Comment by ErikEJ** [comment]
Suggest you share your project.

**Comment by ctdevaughn** [comment]
Public...
https://github.com/ctdevaughn/ContosoUniversity

**Comment by ErikEJ** [comment]
Works fine on my PC - do you have the 3.1 runtime installed?

`dotnet --list-runtimes`

**Comment by ErikEJ** [comment]
Sorry, forget my last question. Still works fine on my PC though.

**Comment by ErikEJ** [comment]
I have added some additional debugging to the latest daily build, you can use that to test running the model inspection tool by hand - just run the contents witkh "dotnet"

**Comment by ErikEJ** [comment]
https://github.com/ErikEJ/EFCorePowerTools/commit/1edd0f7442d0fba1224dcc574de70ea8599efe04

**Comment by ErikEJ** [comment]
Any update?

**Comment by ctdevaughn** [comment]
Sorry, back in the office today.  I am not sure if it is what fixed my issue, but I updated to VS 16.9.1 (from 16.9.0) and it seems to be fine now.  Thanks for the quick responses.
