### ISSUE TITLE
ASP.NET Core 2.1 Error EF Power Tools - Migrations Tool

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#85]
_From @rehaddad on August 22, 2018 14:26_

Hi, I created a new ASP.NET Core 2.1.0 project, add a class and the Context:

public class Produto
{
    public int ProdutoID { get; set; }
    public string Descricao { get; set; }
    public decimal Preco { get; set; }
    public decimal Qtde { get; set; }
    public decimal ValorEstoque => Preco * Qtde;
}

public class DBContexto : DbContext
{
    public DBContexto (DbContextOptions<DBContexto> options)
        : base(options)
    {
    }

    public DbSet<Produto> Produto { get; set; }
}

---------
appsettings.json - declare database
"ConnectionStrings": {
    "DBContexto": "Server=local;Database=PBIBanco;Trusted_Connection=True;MultipleActiveResultSets=true"
  }

---------
Package:
<PackageReference Include="Microsoft.AspNetCore.App" />

When I build the Project it's OK. But when I try to use Migrations Tool (preview), right click into the Project / EF Core Power Tools / Migrations Tool (preview), show me the messagebox:
could not load file or assembly 'microsoft.aspnetcore.hosting.abstractions, version=2.1.0.0

My goal is use EF Power Tools to generate migrations scripts. Can you help me, please?
Best.

Versions: 
EF Power Tools - Version 1.0.643.0
SQL Server Compact 4.0 in GAC - No
SQL Server Compact 4.0 DbProvider - No
SQL Server Compact 4.0 DDEX provider - No
SQL Server Compact 4.0 Simple DDEX provider - Yes
SQLite ADO.NET Provider included: 1.0.107.0
SQLite EF6 DbProvider in GAC - No
System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes

Visual Studio Enterprise 15.7.6

_Copied from original issue: ErikEJ/SqlCeToolbox#735_

**Comment by ErikEJ** [comment]
What if you move the context and migrations to a .net Core class library?

**Comment by ErikEJ** [comment]
_From @rehaddad on August 22, 2018 18:45_

I tried to move to a DLL. And then, when I click at Add Migration button, shows me: System.IndexOutOfRangeException: Index was outside the bounds of the array. 
in https://1drv.ms/f/s!Aiq_G0V2u7eXg0UNCCkYOvH2vzvl I put the Picture error (F1) and the zip Project (ASPCore_PBI.ZIP)
Best.

**Comment by ErikEJ** [comment]
I will have a look

**Comment by ErikEJ** [comment]
will add support for 2.1.3 in #91

**Comment by ErikEJ** [comment]
This is fixed (for .NET Core) in latest daily build /cc @ralmsdeveloper : https://github.com/ErikEJ/EFCorePowerTools/commit/0e1a8cdf7ac59b7cd46c1983d06bd5791e8d32b5

**Comment by TeamAKTUERP** [comment]
I am using windows 10 and have tls 2.0 enabled. Still i get the following message from EF Core Power tool

System.Exception: Table list error: Unable to launch external process: Security Warning: The negotiated TLS 1.0 is an insecure protocol and is supported for backward compatibility only. The recommended protocol version is TLS 1.2 and later.


Pls help

**Comment by ErikEJ** [comment]
@TeamAKTUERP this issue is closed and may not be related at all. Please create a new issue, and share the provider and extension version.
