### ISSUE TITLE
Rename and Use table and column names directly from database together

### ISSUE THREAD

**Issue by marcziss** [ErikEJ/EFCorePowerTools#854]
I have a need to have classes generated that keep fidelity to the casing in the table name, but ( of course there had to be a but) I also need to prefix table names with the schema name for a number of schemas.

The problem is right now it seems that there is a choice of one or the other but not both (when I select the Use table and column names directly from database together it ignores the efpt.renaming.json file.)

Is there a clever way, perhaps a flag in the efpt.renaming.json file to have renaming respect DB table casing?

**Comment by ErikEJ** [comment]
Which EF Core version?

**Comment by marcziss** [comment]
I am using EF Core 5.0 but figured out a way around my issue I just used
`   {
      "SchemaName": "SchemaToPrefix",
      "TableRegexPattern": "^",
      "TablePatternReplaceWith": "SchemaToPrefix",
      "UseSchemaName": false
   },
   {
      "SchemaName": "SchemaToNotPrefix",
      "TablePatternReplaceWith": "",
      "TableRegexPattern": "^",
      "UseSchemaName": false
   }`

in the efpt.renaming.json file. This way it is kinda a no op for the second (SchemaToNotPrefix) schema but it respects the casing as it does it the SchemaToPrefix operation. 
Thanks for your quick response Erik!
