### ISSUE TITLE
ColumnRegexPattern / ColumnPatternReplaceWith is being ignored

### ISSUE THREAD

**Issue by marcziss** [ErikEJ/EFCorePowerTools#855]
Thanks for a great Tool! Just having one issue.

Either I'm doing something very dumb or there's an issue with ColumnPatternReplaceWith

   {
      "ColumnPatternReplaceWith": "TEST_COLUMN_",
      "ColumnRegexPattern": "^",
      "SchemaName": "dbo",
      "UseSchemaName": false
   }

In this example using .net 5 (and latest version of vsix installed today)  Is there something I'm missing?

To Reproduce
1) Right click on project in visual studio 
2) Choose EF Core Power Tools / Reverse Engineer
3) Choose Database + check Use EF Core 5 + Ok
4) select Tables / dbo schema + ok
5) Type in Context name, Namespace, EntityTypes paths, and DB Context path
6) No Checkboxes checked (to help distill problem down)

Generates classes like this:

    public partial class DeDiscount
    {
        public string CarrierNbr { get; set; }
        public string DiscountTypeCode { get; set; }
        public string Column3 { get; set; }
        public string DiscountNote { get; set; }
    }

rather than expected 

    public partial class DeDiscount
    {
        public string TEST_COLUMN_CarrierNbr { get; set; }
        public string TEST_COLUMN_DiscountTypeCode { get; set; }
        public string TEST_COLUMN_Column3 { get; set; }
        public string TEST_COLUMN_DiscountNote { get; set; }
    }

### Further technical details

Visual Studio (2019 16.8.2)
EF Core Power Tools version: 2.5.537
Sql Server 14.0.2027.2

**Comment by ErikEJ** [comment]
Please provide at least a CREATE TABLE statement.

**Comment by ErikEJ** [comment]
I am not able to reproduce, please provide:
efpt.config.json, efpt.renaming.json and a CREATE TABLE statement.

**Comment by marcziss** [comment]
Erik,
I tried to distill it down, so only using a test table here. The reason I have the need to use column regex is I have inherited code and a DB with "interesting" column naming conventions such as TestTableID. 
Thanks for looking at this!
Marc

[FilesRequested.zip](https://github.com/ErikEJ/EFCorePowerTools/files/6141457/FilesRequested.zip)

**Comment by ErikEJ** [comment]
@marcziss You need an empty Tables array!

https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/RevEng.Core/ReplacingCandidateNamingService.cs#L86 

```json
{
      "SchemaName": "dbo",
      "ColumnPatternReplaceWith": "TEST_COLUMN_",
      "ColumnRegexPattern": "^",
      "Tables": [],
      "UseSchemaName": false
}
```

**Comment by marcziss** [comment]
In the immortal words of Homer Simpson ..."DOH!"
Thanks Erik, what threw me off was I was using TablePatternReplaceWith and TableRegexPattern successfully without the empty "Tables": [], so it never occurred to me it was needed.

**Comment by ErikEJ** [comment]
Leaving as by design...
