### ISSUE TITLE
Problems related to EF Core Power Tools and MySql providers

### ISSUE THREAD

**Issue by CliffConway** [ErikEJ/EFCorePowerTools#860]
Previous use of EF Core Power Tools related to a MySql database generated a working solution some months back. The database has changed so decided to reverse engineer again. This time I get many errors in the auto generated DbContext related to the statement 'HasCharSet' in all of my entities

### Steps to reproduce
Using:-
- VS 2019 Preview
- MySql 5.6
- EF 5
- Include="Microsoft.EntityFrameworkCore" Version="5.0.3" />
- Include="MySql.Data" Version="8.0.23" />
- Include="MySql.Data.EntityFramework" Version="8.0.23" />
- Include="MySql.EntityFrameworkCore" Version="5.0.0" />
- MySql Connnector NET 8.0.23
- EF Power Tools 2.5.567.0

Then used 'Reverse Engineer' option in Power tools and the errors appear for each entity in the DbContext

any thoughts would be much appreaciated.

C

**Comment by ErikEJ** [comment]
Maybe it is an Oracle specific extension, and a using statement is missing?

**Comment by CliffConway** [comment]
thanks Erik for the very fast response. I am reasonably sure that I am not missing a using directive. As I mentioned it all worked with my previous reverse engineering attempt and I have checked all the previous using statements used and I don't believe anything else has changed other than some new tables on DB.

I have noticed that intellisense does have "ForMySQLHasCharset" and "ForMySQLHasCollation" extensions with the "Microsoft.EntityFrameworkCore". I this something you are aware of?

**Comment by ErikEJ** [comment]
I need a repro project, I don't follow.

**Comment by ErikEJ** [comment]
Hang on! The reverse engineering uses the Pomelo driver, not the Oracle driver!

**Comment by CliffConway** [comment]
I am using:-
    <PackageReference Include="MySql.Data" Version="8.0.23" />
    <PackageReference Include="MySql.Data.EntityFramework" Version="8.0.23" />
    <PackageReference Include="MySql.EntityFrameworkCore" Version="5.0.0" />

Are these what you call Oracle driver? I must be honest my knowledge of Oracle is close to zero - I know how to spell it ;-)

**Comment by CliffConway** [comment]
apologies should have been
I am using:-
  Include="MySql.Data" Version="8.0.23" 
   Include="MySql.Data.EntityFramework" Version="8.0.23" 
   Include="MySql.EntityFrameworkCore" Version="5.0.0" 

Are these what you call Oracle driver? I must be honest my knowledge of Oracle is close to zero - I know how to spell it ;-)

**Comment by ErikEJ** [comment]
You must use the Pomelo provider with EF Core Power Tools

**Comment by CliffConway** [comment]
I'll give that a go. Thanks Eric and congratulations on a great and much needed tool.
