### ISSUE TITLE
Avoid saving reverse engineered files to disk that are not used

### ISSUE THREAD

**Issue by GearTheWorld** [ErikEJ/EFCorePowerTools#863]
**Describe what is not working as expected.**

https://user-images.githubusercontent.com/8614008/111685838-f7289c00-885a-11eb-92a7-90054ca488fa.mp4

When doing a Reverse Engineer and having a Context name called ApplicationDbContext, once the reverse starts, it generates the ApplicationDbContext in the project and 1 sec. after it deletes it thus having the file added to TFS which is orphan.

To best describe in more detail, I provide a video which can be seen here and also attached to this issue
[](https://youtu.be/ywyy8_WAfsA)
 
### Steps to reproduce
**Include a complete description that I can redo to reproduce the issue.**

I have a class called DataStore.cs in which I have my ApplicationDbContext class.  When I reverse engineer on the whole project and click ok, the process generates the ApplicationDbContext.cs file and immediately after it deletes it but this file is registered in TFS which become orphan and have to be deleted.

### Further technical details
**EF Core Power Tools version: (found in About dialog - blue question mark icon on context menu)**

Version 2.5.567.0

SQLite ADO.NET Provider included: 1.0.109.0
SQLite EF6 DbProvider in GAC - No

System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes

**Database engine: (SQlite, SQL Compact, SQL Server, Postgres)**

SQL Server Management Studio			   15.0.18369.0
SQL Server Management Objects (SMO)	   16.100.46041.41
Microsoft Analysis Services Client Tools		   15.0.19342.0
Microsoft Data Access Components (MDAC)	   10.0.19041.1
Microsoft MSXML						   3.0 6.0 
Microsoft .NET Framework				   4.0.30319.42000
Operating System						   10.0.19042

**Visual Studio version: (e.g. Visual Studio 2019 16.8)**

Microsoft Visual Studio Professional 2019
Version 16.9.2
VisualStudio.16.Release/16.9.2+31112.23
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Professional

**Comment by ErikEJ** [comment]
Have you tried moving it to another folder?

**Comment by ErikEJ** [comment]
What does the first lines of the file look like?

**Comment by GearTheWorld** [comment]
I would like to tell you what you want but the file disappears immediately after creation so I can't move it or see inside
Did you see what is happening in the video?

**Comment by ErikEJ** [comment]
Could you try creating the files in a folder not under source control?

**Comment by GearTheWorld** [comment]
Wait, it is already non existant in source control when I perform the action and then it creates the file in VS and then source control sees the new file and add it but sadly it added a file which was created for 1 second.

However, I tried what you said.  I created the file in a new folder inside the project but still, the EFPT creates the file anyway and I end up with the same issue.  The problem here looks like the "Context name" set in the first EFPT dialog creates a .cs file but immediately after it deletes it.

![image](https://user-images.githubusercontent.com/8614008/111751100-a77fba00-88c6-11eb-9d1c-711403f7b33d.png)

**Comment by ErikEJ** [comment]
Please share your efpt.config.json file, and I will have a look.

**Comment by GearTheWorld** [comment]
Here it is
[efpt.config.json.zip](https://github.com/ErikEJ/EFCorePowerTools/files/6170617/efpt.config.json.zip)

**Comment by ErikEJ** [comment]
Could you explain this, I do not understand:

I have a class called DataStore.cs in which I have my ApplicationDbContext class.

**Comment by GearTheWorld** [comment]
Yes, originally, EFCPT was supposed to do the job of creating the Context for me but I did it myself everything manually before I knew such a tool existed.  Here's the code inside DataStore.cs

```
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace CubiDataStore
{
    #region ' Interface '
    public interface IApplicationDbContext
    {
        DatabaseFacade Database { get; }
        int SaveChanges();

        DbSet<Addresses> Addresses { get; set; }
        DbSet<Divisions> Divisions { get; set; }
        DbSet<Logs> Logs { get; set; }
        DbSet<Pickups> Pickups { get; set; }
        DbSet<Products> Products { get; set; }
        DbSet<Rights> Rights { get; set; }
        DbSet<Tokens> Tokens { get; set; }
        DbSet<Shipments> Shipments { get; set; }
        DbSet<Users> Users { get; set; }
        DbSet<UsersRights> UsersRights { get; set; }
    }
    #endregion

    #region ' ApplicationDbContext '
    public class ApplicationDbContext : DbContext, IApplicationDbContext
    {
        public ApplicationDbContext(DbContextOptions<DbContext> options) : base(options)
        {
        }
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
            : base(options)
        {
        }

        public override DatabaseFacade Database => base.Database;

        public DbSet<Addresses> Addresses { get; set; }
        public DbSet<Divisions> Divisions { get; set; }
        public DbSet<Logs> Logs { get; set; }
        public DbSet<Pickups> Pickups { get; set; }
        public DbSet<Products> Products { get; set; }
        public DbSet<Rights> Rights { get; set; }
        public DbSet<Tokens> Tokens { get; set; }
        public DbSet<Shipments> Shipments { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<UsersRights> UsersRights { get; set; }

    }
    #endregion
}

```

**Comment by GearTheWorld** [comment]
Since we are forced to enter a CONTEXT NAME, there's no way for me to tell that I don't want any context because I already have one so it's creating a file but the strange part is that it deletes it right after it creates it.  However the need is to make sure EFCPT do not generates a such file because we already have it.

**Comment by ErikEJ** [comment]
???? So you do not want the file to be created / included?

**Comment by ErikEJ** [comment]
In other word, the end result from EFPT is correct, but TFS gets confused in the process - is that your actual issue?

**Comment by GearTheWorld** [comment]
Yes because when we try to do a CHECK-IN of our project, we have an error saying that the file wasn't found and we have to go in Source Control and delete that file in order to do the CHECK-IN

**Comment by GearTheWorld** [comment]
Can you elaborate on why the file is created and immediately deleted?

**Comment by ErikEJ** [comment]
I am using the EF Core reverse engineer components, and they have no option to not generate a DbContext file, so the feature is implemented by code if the extension that deletes the file after the fact.

Looks like there is no way to work around this TFS issue, other than changing to a modern source control system.

**Comment by GearTheWorld** [comment]
I don't agree that there is no way.  If you modify the app in order to avoid creating the file if Context name is empty rather than forcing to enter something in that textbox would solve the problem.

**Comment by ErikEJ** [comment]
Could you share a .csproj file with an Orphan dbcontext?

Also, what is the impact of this TFS issue?

**Comment by GearTheWorld** [comment]
Attached, the entire project for which the file is created and deleted and the impact is obvious.  We can't do a check-in; we have to go in SC and delete the file there and it's time consuming and not very funny to do each time for something that could have a small fix to help avoid this problem because it really is a problem.

[CubiDataStore.zip](https://github.com/ErikEJ/EFCorePowerTools/files/6176698/CubiDataStore.zip)

Now I gave you everything.  Hope you can do a small fix but giant leap for mankind.
Thank you

**Comment by ErikEJ** [comment]
As I wrote yesterday, there is no "small fix", as I use the EF Core components for reverse engineering, and they are not designed for "no DbContext" file. Also, you are the first and only user reporting this, and you have a workaround.

In  addition, I do not have immediate access to a TFVC based project, so even if I could provide a fix, I would have additional work verifying the fix.

I will investigate what can be done... And of course happy to accept a PR to fix this.

**Comment by ErikEJ** [comment]
I had a third look, and believe if I have found a possible solution...

**Comment by ErikEJ** [comment]
@GearTheWorld A fix is now available, please let me know if it solves your issue.

**Comment by GearTheWorld** [comment]
@ErikEJ How do I get this update?  When I look in VS there's no update for the extension.

**Comment by GearTheWorld** [comment]
I have version 2.5.573 and the same problem exists so I assume I'm not with the latest version!

**Comment by ErikEJ** [comment]
Look at the readme and/or release notes.

**Comment by GearTheWorld** [comment]
;) Thanx

**Comment by GearTheWorld** [comment]
Hey it works like a charm.  Excellent!
