### ISSUE TITLE
MissingMethodException when trying to run AsDgml() extension

### ISSUE THREAD

**Issue by RichardDanvers** [ErikEJ/EFCorePowerTools#864]
I am trying to use the AsDgml extension method like so:

```csharp
private void GenerateDatabaseDiagram(IServiceCollection services)
{

    using (var context = services.BuildServiceProvider().GetService<MyDbContext>())
    {
        File.WriteAllText(
            Path.GetTempFileName() + ".dgml",
            context.AsDgml(),
        Encoding.UTF8);
    };
}
```

However, when running the application. I get the following error:
```
System.MissingMethodException: 'Method not found: 'Microsoft.EntityFrameworkCore.Metadata.Internal.DebugView`1<Microsoft.EntityFrameworkCore.Metadata.Internal.Model> Microsoft.EntityFrameworkCore.Metadata.Internal.Model.get_DebugView()'.'
```

I am running this application on .NET Core 3.1.407, using Entity Framework Core 5.0 and the latest version of DgmlBuilder available on NuGet (3.1.1)

**Comment by ErikEJ** [comment]
Which package are you using?

**Comment by RichardDanvers** [comment]
Here is my package reference in my project file:
```
<PackageReference Include="ErikEJ.EntityFrameworkCore.DgmlBuilder" Version="3.1.1" />
```

**Comment by ErikEJ** [comment]
Ah, I never updated that package for EF Core 5...

**Comment by RichardDanvers** [comment]
Ah I see, that would make sense. I just attempted to use the v5 preview release and that didn't have any issues.

Will close the ticket as I guess it would make sense to use v5 with v5 of EF!
