### ISSUE TITLE
Cannot compile project when used OutputPath different than the project where DbContext is placed

### ISSUE THREAD

**Issue by miroslav-hristov** [ErikEJ/EFCorePowerTools#866]
Cannot build project in case of OutputPath(for EntityTypes path) is set and it is different than the "default" path. The compiler throws

### Steps to reproduce
1. Use reverse engineer GUI to auto-generate DbContext and other files as setting up path for "EntityTypes path (f.ex. Models) - optional" to be set with relative path to another project
2. Click button to generate models, configuration files, DbContext,etc. 
3. Try to build project - there are compilation errors

> NOTE:
It is caused by the included linked files from the project which contains mapped(from the database) entity models. For example in csproj file(the project which contains DbContext and not only) it is added new <ItemGroup> tag with linked file:
```XML
<ItemGroup>
    <Compile Include="..\..\Domain\<MyOtherProject>\Data\Entities\Campaign.cs" Link="Campaign.cs" />
    ...
</ItemGroup>
```

### Further technical details
EF Core Power Tools version: 2.5.573

Database engine: MS SQL Server 2016(no matter)

Visual Studio version: Microsoft Visual Studio Professional 2019 Version 16.6.3

**Comment by ErikEJ** [comment]
Please share repro project/steps.

**Comment by miroslav-hristov** [comment]
> Please share repro project/steps.
---
NOTE: I have used till now EF Core Power Tools version 2.4.0
---

So I have solution which has (not only) 2 projects - one which holds models(representing database models) - let's call it "*DataModelsProject*" and another one which holds DbContext(and configuration files) - let's call it "*InfrastructureProject*". Also I have configured my data models to be placed in project *DataModelsProject*. So after updating EF Core PowerTools(version 2.5.573) I am following the same steps to reverse engineer my models:
1. Reverse engineer using GUI of EF Core PowerTools ("starting" from project *InfrastructureProject*)
2. After successfully generating all models - the compiler "throws" errors.(you can see my latter description what causes these errors)

---
Thanks for quick response - later I will try to create new repro project(from scratch).

**Comment by ErikEJ** [comment]
This was a bug in the latest release, fixed in latest daily build

**Comment by miroslav-hristov** [comment]
> This was a bug in the latest release, fixed in latest daily build

Thanks Erik for your quick response(and quick fix) - we will check it :)
