### ISSUE TITLE
Scaffolding database modes into c# records types

### ISSUE THREAD

**Issue by adopilot** [ErikEJ/EFCorePowerTools#867]
As docs says _[C# 9 introduces records, a new reference type that you can create instead of classes or structs](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/exploration/records)._
It will be nice to build up database context , models for tables and sprocs models using this new record types.
Is there any plan to implement scaffolding database using record types.

When records was interdicted for first time my first thought was this something in relation with database end entity framework. The  term  record for most of developers always is in common with database.
Most of my models coming from database first (scaffolding) approach, So I was hoping that I can build up my entities using  record types and adopt this new feature faster.

**Comment by ErikEJ** [comment]
Have you verified that records work well with EF Core 5?

**Comment by ErikEJ** [comment]
@roji is this under consideration in Core- I could not find any open issue?

**Comment by roji** [comment]
There's https://github.com/dotnet/efcore/issues/23236, which was closed in favor of the general https://github.com/dotnet/efcore/issues/4038.

I had a conversation at some point about using C# records in EF Core, can no longer find it (could have been in the discussions tab). The bottom line is that records are a poor choice for EF Core entities in anything but purely non-tracking query scenarios; the point of records is to provide value semantics (e.g. equality), which do not fit well with change tracking (at least not right now).

**Comment by ErikEJ** [comment]
Thanks, @roji !
