### ISSUE TITLE
OK instead of Ok buttons

### ISSUE THREAD

**Issue by sonnemaf** [ErikEJ/EFCorePowerTools#868]
The reverse engineer dialogs contain 'Ok' (lowercase k) buttons which should be 'OK' according to the [Windows Guidelines](https://docs.microsoft.com/en-us/windows/win32/uxguide/text-ui).

All dialogs in Visual Studio with an OK button are like this:
![image](https://user-images.githubusercontent.com/9335559/111865708-d64e6c80-8968-11eb-89cd-5617ff8f1fb9.png)

It is a small thing. Sorry, don't have time to create a PR.

**Comment by ErikEJ** [comment]
Have you tried the latest daily build? 😁

**Comment by ErikEJ** [comment]
Actually in latest official release...
