### ISSUE TITLE
"Reverse Engineer" adds links for entity types that is not wanted. There must be choice on Advanced... screen

### ISSUE THREAD

**Issue by cetindogu** [ErikEJ/EFCorePowerTools#875]
"Reverse Engineer" adds links for entity types generated on other "Shared.Entites Project"
      into the "DataLayer Project" 

### Steps to reproduce
Include a complete description that I can redo to reproduce the issue.
Right Click any "Data Layer Project" that is .net Standard 2.1
Ef Core Power Tools -> Reverse Engineer
Enter Any "Entity Types path" that is another project named "Shared.Entites Project" that is also same  .net standard 2.1

![image](https://user-images.githubusercontent.com/7325611/112152068-f09b7b00-8bf2-11eb-84d5-dd423ed3f76d.png)

And you will see entity types are also linked to main data layer project (that is i dont want to see entity types here)
![image](https://user-images.githubusercontent.com/7325611/112152550-76b7c180-8bf3-11eb-8c42-71b8f6f4f45f.png)

### Further technical details
EF Core Power Tools version:  2.5.573

Database engine: (
Microsoft SQL Server 2016 (SP2) (KB4052908) - 13.0.5026.0 (X64)   Mar 18 2018 09:11:49   Copyright (c) Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2012 R2 Standard 6.3 <X64> (Build 9600: ) (Hypervisor) 
)

Visual Studio version: (e.g. Visual Studio 2019 16.8)

**Comment by ErikEJ** [comment]
Please provide a repro solution.

**Comment by ErikEJ** [comment]
This was a bug in the latest release, fixed in latest daily build
