### ISSUE TITLE
DateTime not null if HasDefaultValueSql

### ISSUE THREAD

**Issue by joooon57** [ErikEJ/EFCorePowerTools#876]
Hello,
It is not an issue from this tool, the scaffolfing with the Scaffold-DBContext command has the same result.
But it is similary with #160.
When there is a DATETIME column in SQL Server with default value (getdate()) the scaffolding result is : DateTime.
The default value of a .net DateTime is 01/01/0001 so when SaveChanges is applied there is an error because the min value for a SQL DATETIME is 01/01/1753.
The workaround is to remove (unselect) the column for scaffolding but we cannot force a value when is necessary.
Is it possible to have an option to make nullable a not nullable column with a default value?

PS: Sorry for my English. It's not my mother tongue.

**Comment by ErikEJ** [comment]
I am not sure I understand why you cannot set the value explicitly?

**Comment by joooon57** [comment]
For exemple to have the created date from the server where sql server is installed and not from the client where the insert data is executed.

**Comment by ErikEJ** [comment]
I think I need to see an example

**Comment by ErikEJ** [comment]
Closing as requested additional information was not provided, feel free to re-open if you can provide it.
