### ISSUE TITLE
Reverse engineer stored procedure no generate EntityResult

### ISSUE THREAD

**Issue by ignaciosalazarcalle** [ErikEJ/EFCorePowerTools#878]
Hi, 

I have created the netx Stored Procedure:
`CREATE PROCEDURE dbo.TestPA
    @informeId INT,
    @checkResult BIT
AS
BEGIN
    SET NOCOUNT ON;

    IF (@checkResult = 'False')
    BEGIN
        SELECT *
        INTO #tempTable
        FROM TABLE1;

        IF @informeId = 0
        BEGIN
            SELECT Column1,
                   Column2
            FROM #tempTable;
        END;

        IF @informeId = 1
        BEGIN
            SELECT Column1,
                   Column2
            FROM #tempTable
            WHERE column3 = 'Test'
            ORDER BY dsprom_pro;
        END;
    END;
END;`

When I use Reverse Engineering, I expected the tool creates an entity with the columns in the selects, but I doesn´t.
The tool creates an entity but withouts properies.

I have other similar Stored Procedures and it works correctly.

### Further technical details
EF Core Power Tools version: 2.5.573.0
Database engine: SQL Server v18.8
Visual Studio version: 2019 Community Versión 16.9.2

Regards,

**Comment by ErikEJ** [comment]
The metadata API is unable to discover the result shape, when using temp tables.

You should see a warning in the Output window.

Just add a partial class with the correct properties and off you go.

**Comment by ignaciosalazarcalle** [comment]
When i do the reverse Engineering EF Power Too creates the entity, but without properties.
Added to that entity the properties that the procedure is supposed to return?

**Comment by ErikEJ** [comment]
Add another partial class in a new file, and add the properties to that class.

Provide an example of the empty class,  if it  is unclear.

**Comment by ignaciosalazarcalle** [comment]
This is el method EFPT generates:
` public async Task<PA_Anexo1Result[]> PA_Anexo1Async(int? Informe, bool? Comprueba, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Informe",
                    Value = Informe ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Comprueba",
                    Value = Comprueba ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<PA_Anexo1Result>("EXEC @returnValue = [dbo].[PA_Anexo1] @Informe, @Comprueba", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }`
        
And this is the empty class:
`public partial class PA_Anexo1Result
    {
    }`

**Comment by ErikEJ** [comment]
Ok, so just create a new file with a partial class and add your properties!

**Comment by ignaciosalazarcalle** [comment]
OK. Thanks!!

**Comment by amir9131** [comment]
@ignaciosalazarcalle  did this fix the issue ? I made this change but I got an error while calling the SP. Something around data cant be null from DBContextExtensions

**Comment by ErikEJ** [comment]
@amir9131 please create a new issue with full repro details

**Comment by ignaciosalazarcalle** [comment]
> @ignaciosalazarcalle did this fix the issue ? I made this change but I got an error while calling the SP. Something around data cant be null from DBContextExtensions

Yes, it did fix it to me.
