### ISSUE TITLE
Last version result incompatible with 2.4.217

### ISSUE THREAD

**Issue by stammaja** [ErikEJ/EFCorePowerTools#879]
There is a difference between .json files and Entity files generated by 2.4.217 and newest version, for the same database
EF 3.1

**Is it possible to download version 2.4.217 .vsix somewhere?**

### Steps to reproduce
Instead of "HasPrimaryKey": true,
"ObjectType": 0 is added for every table

Naming of entities is changed when there's name like TShirt (2 consecutive uppercase letters)

and a lot of other changes.

### Further technical details
EF Core Power Tools version: 2.5.573.0
compared to 2.4.217.0

Database engine: MS SQL

Visual Studio version: 16.8.4

**Comment by ErikEJ** [comment]
Difference in efpt.config.json should be irrelevant for you.

Are you using the correct EF Core version when reverse engineering (,default is now EF Core 5)

**Comment by ErikEJ** [comment]
Older versions are not available.

What are the "entity changes" ??

**Comment by stammaja** [comment]
Hi, here are more details:
efpt.config.json changes are irrelevant, it's just difficult to discard all unneeded changes when working in a medium team and everyone else having different version.
In both cases EF Core 5 checkbox is off.

Entity changes: if table is named TShirt previous version names entity the same, and the new Tshirt. Maybe i missed to check some option?

Until colleagues update their version, we managed to circumvent the issue by finding the older version of extension in %LocalAppData%\Microsoft\VisualStudio\

**Comment by ErikEJ** [comment]
>> everyone else having different version.

You should ensure to always stay up to date with your tools ;-)

>> Maybe I missed to check some option?

I cannot see how that could have changed, but there are various options and tweaks you can try:

Option to use Pluralization (will use Humanizer) (on/off)
Option to use Legacy pluralizer (will use EF6 pluralizer) (on/off)
Option to use Database names as is.
Finally, you can fix casing issue by using the renaming feature (manually add the same name as Name and NewName in the desired casing)

**Comment by ErikEJ** [comment]
Let me know if you need further advice...

**Comment by ErikEJ** [comment]
Closing, feel free to post a new issue if you have further questions.
