### ISSUE TITLE
Add option to replace table prefixes

### ISSUE THREAD

**Issue by rposener** [ErikEJ/EFCorePowerTools#88]
New Feature Add: Desire ability to replace "tbl" from Sql Tables to be another string instead in the generated models.

### Steps to reproduce
Create a database with "tbl" or any other prefix on table names.  Scaffold it, and have it produce altered files and names.

### Further technical details
Visual Studio version: (e.g. Visual Studio 2017 15.7)

Provided on Pull Request #87.

**Comment by ErikEJ** [comment]
Will be done in #14
