### ISSUE TITLE
Store Procedure implementation precludes unit testing

### ISSUE THREAD

**Issue by GPetrites** [ErikEJ/EFCorePowerTools#880]
Currently, stored procedures are accessed using extension method GetProcedures() added to the DBContext using the following code:

```
    public static class DatabaseContextProceduresExtensions
    {
        public static DatabaseContextProcedures GetProcedures(this DatabaseContext context)
        {
            return new DatabaseContextProcedures(context);
        }
    }
```

Assuming that a system under test calls two stored procedures, this introduces two problems with unit testing:

1. The system under test is likely to call GetProcedures() for every stored procedure call.  Each call will create a new instance of DatabaseContextProcedures which will need to be mocked, which will overly complicate the mocking.
2. Because this is an extension method, there is no way to mock the GetProcedures() method to return a mock DatabaseContextProcedures object.

An easy, non-breaking solution would be to rework the code above as follows:

```
    public partial class DatabaseContext
    {
        private DatabaseContextProcedures _procedures;
        public DatabaseContextProcedures Procedures
        {
            get
            {
                _procedures ??= new DatabaseContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }
        public DatabaseContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }
```

This protects the integrity of procedure isolation for intellisense while supporting an easy path to mock DatabaseContextProcedures.  The public setter on Procedures might be questionable, but we need some way to replace the default implementation of the DatabaseContextProcedures with a mocked one when using an un-mocked DatabaseContext object.

In addition to the above changes, the **virtual** keyword needs to be added to every stored procedure method so tools such as Moq can provide a custom implementation.

With the above changes, we can create a DatabaseContext using an in-memory provider while stubbing out the stored procedure calls allowing us to do something like this:

```
        [Fact]
        public async Task CanMock_EFContext()
        {
            // arrange
            var builder = new DbContextOptionsBuilder<DatabaseContext>();
            builder.UseSqlite("DataSource=:memory:");
            var dbContext = new DatabaseContext(builder.Options);
            dbContext.Database.OpenConnection();
            dbContext.Database.EnsureCreated();

            var procedures = new Mock<DatabaseContextProcedures>(dbContext);
            dbContext.Procedures = procedures.Object;

            procedures
                .Setup(p => p.Procedure1Async(It.IsAny<int>(), It.IsAny<int>(), It.IsAny<OutputParameter<int>>(), It.IsAny<CancellationToken>()))
                .Returns(Task.FromResult((Procedure1Result[])null));

            // act
            var result = await dbContext.Procedures.Procedure1Async(1, 1);

            dbContext.Table1.Add(new Table1 { TextValue = "test", NumberValue = 3 });
            dbContext.SaveChanges();
        }
```

**Comment by ErikEJ** [comment]
PR in progress?

**Comment by GPetrites** [comment]
I can/will.  I threw the example output together fairly quickly.  Are you happy with the design?

**Comment by ErikEJ** [comment]
@GPetrites I am working on a PR now, the design seems fine!

**Comment by ErikEJ** [comment]
Fixed in latest daily, please let me know if that solves your issue.
