### ISSUE TITLE
Enable Firebird reverse engineering support

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#884]
- [x] Add support in Adhoc form
- [x] Enable in command line tools
- [x] Verify (and fail)
- [x] Integration test

@cincuranet FYI! 😄

**Comment by ErikEJ** [comment]
Now in latest daily build.

**Comment by cincuranet** [comment]
I confirm it works.

**Comment by ErikEJ** [comment]
Thanks, @cincuranet 😁
