### ISSUE TITLE
Reverse Engineering - Synonyms

### ISSUE THREAD

**Issue by AndyISmith** [ErikEJ/EFCorePowerTools#894]
When using the Reverse Engineering tool (which is amazing by the way, incredibly useful and many thanks for everyone's hard work), is it possible to see and select from the synonyms configured at the SQL Server end?

**Comment by ErikEJ** [comment]
I have never used synonyms, please elaborate how they would be used in reverse engineering?

**Comment by ErikEJ** [comment]
See discussion here: https://github.com/dotnet/efcore/issues/23395

**Comment by AndyISmith** [comment]
Thanks for the super fast reply!  In our use case we have 20+ databases but each backend service connects to a single database only (single connection string) because mystical reasons lost in the fog of time.  So if a service needs data from a table in a different database, that ends up being a synonym on to a view.  e.g. if we have Customers and Product databases, and the Customer service needs Product Item data, we end up with a synonym in Customers onto Product.dbo.ItemView.

After reading the thread you linked to above I can see how this would be tricky to implement with synonyms linking to such a wide range of things.  And we could well be an edge case.  From a reverse engineering point of view, if it was possible to query the list of synonyms, check if they were tables/views/functions/procs then perhaps the tool could scaffold the entities out in a similar fashion to the regular database objects?

**Comment by ErikEJ** [comment]
I understand your technical debt, but I think a general solution to this is not possible.

 You could create views in the single db on top, and they would be scaffolded as keyless read-only entities.

**Comment by AndyISmith** [comment]
That's a good idea - could still use the tool to generate the entities, just with a small tweak afterwards.  Many thanks!
