### ISSUE TITLE
Maintaining DisplayFormatAttibutes when Updating Table columns

### ISSUE THREAD

**Issue by KayakFisher205** [ErikEJ/EFCorePowerTools#895]
When I add new columns to a table, and I run the Reverse Engineer, the class for the table and its fields is auto-generated.
I use DataAnnotations like [Display(Name = "North or South")] and [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:0.##0}")] to help with displaying and formatting the columns. These are lost on the regeneration. 

I was thinking with standard EF, there was a type of MetaData file that was 'attached' to the context or table class that has the ability to specify certain fields to have the DataAnnotations, but I can't remember what it is. If something like that was in EF Core, that would be the best option.

### Steps to reproduce
Add Data Annotations like [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:0.##0}")] and run the Reverse Engineer. The Data Annotations will be deleted.

### Further technical details
EF Core Power Tools version: 2.5.602.0

Database engine: (SQL Server)

Visual Studio version: (e.g. Visual Studio 2019 Version 16.10.0 Preview 1.0)

**Comment by ErikEJ** [comment]
You should still be able to do that, see the wiki.

**Comment by KayakFisher205** [comment]
Do you mind pointing me to it? I can't seem to find it.

**Comment by ErikEJ** [comment]
Sure: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#extending-the-generated-dbcontext-class-and-entity-classes

**Comment by ErikEJ** [comment]
Any update?

**Comment by KayakFisher205** [comment]
Sorry, I had a chance to read up and it seems to work. I am off today but
when I return Monday I can confirm the display part was working. The
partial classes help to fix one thing. I have a field that is derived from
one of the database fields so I was able to put it anotger partial class
and not have it removed. Thanks for all the help and I'll confirm monday

**Comment by ErikEJ** [comment]
Ping?

**Comment by KayakFisher205** [comment]
Sorry hectic day.
In any case, yes, my issue was solved with that wiki info.

Thanks for the help.
