### ISSUE TITLE
Investigate switch to DataSnnotations

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#898]

**Comment by bhideghety-SPC** [comment]
I've reverse engineered an existing DB model. The aim is to:
- have separate POCO classes
- separate mappings

The result:
- for some reason entity classes do use data annotations
- some entity classes do not have corresponding configuration class (like AspNetUsers in our case)
- also entities that have that extra data annotation mapping, do have same fluent mapping in config
- inside configuration files I saw keys and relations being mapped, but not the properties (I know EF is different to Fluent NHibernate and that some mappings are there by def., but the old EF6 scaffolder I've used did a full map)

![image](https://user-images.githubusercontent.com/80129237/113340267-f1878780-932b-11eb-9287-f0f40bfe6625.png)

**Comment by ErikEJ** [comment]
Please share your efpt.config.json file?

**Comment by ErikEJ** [comment]
Also, EF Core conventions may sometime cause no configuration to be required.

**Comment by ErikEJ** [comment]
I suspect a regression in the latest daily build - if you are using that, why not try the official release version instead?

**Comment by ErikEJ** [comment]
Just remove the checkmark to use Data Annotations, for some reason it was made default, this has now been reverted.

>> Some entity classes do not have corresponding configuration class (like AspNetUsers in our case)

If everything is by convention, it may not be required. And only mappings that are outside on convention is included in the fluetn mapping - this is not EF6!

**Comment by bhideghety-SPC** [comment]
> If erything is by convention, it may not be required. And only mappings that are outside on convention is included in the fluetn mapping - this is not EF6!

Seems it's not just me, but also Microsoft who does not share your views regards mapping:
![image](https://user-images.githubusercontent.com/80129237/113403796-7fed1f00-93a7-11eb-89ef-ee77ce00a67e.png)

**Comment by ErikEJ** [comment]
I do not have "views" about the mapping, simply run of top of the EF Core mapping. 

Also your screenshots are a very unhelpful way to ask for support.

Are you facing any runtime issues or errors?

**Comment by bhideghety-SPC** [comment]
@ErikEJ
1. Well, I described the issue in the 1st comment. Noted that property mappings are missing from the IEntityTypeConfiguration are missing
2. You reacted "If everything is by convention, it may not be required. And only mappings that are outside on convention is included in the fluetn mapping - this is not EF6!"
3. On that I posted you a screenshot of the results that I got from the classic dotnet ef dbcontext scaffolder, where you can see, that even columns that have default mapping are listed in their mapping (which in your output were not there).

Now to Nr. 3: that issue might have been related to the DataAnnotation usage, but based on your answer (see Nr. 2) there was a chance of a different behaviour.

Anyhow, I'm downloading updated Extension to Visual Studio, will do a test and leave a comment here.

**Comment by ErikEJ** [comment]
Make sure to get at least build 608, or uncheck the Data Annotations option.

If you still encounter any issues after that, please provide the schema for your database, and I will investigate.

**Comment by bhideghety-SPC** [comment]
**The 2.5.606 worked as expected.** I think with the DataAnnotation issue the other things also were fixed.

**It's 100% usable,** these options could improve usability:
1. add a folder option (and custom namespace) for the generated mappings
2. the existing namespace options should be probably namespace prefixes
3. and schema could be used (option) as a new sub-folder in the entity/mapping with namespace suffixed by it

Thanx and have a great weekend.

**Comment by ErikEJ** [comment]
You are welcome, glad you figured it out.
