### ISSUE TITLE
Add Demystifier to reduce noise in exceptions

### ISSUE THREAD

**Issue by MagicAndre1981** [ErikEJ/EFCorePowerTools#903]
When something is wrong I see an exception in output, but it includes a lot of noise. With [Ben.Demystifier this noise can be reduced](https://github.com/benaadams/Ben.Demystifier#make-error-logs-more-productive) to only show relevant data in callstack

### Further technical details
EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)

2.5.608.0

Database engine: (SQlite, SQL Compact, SQL Server, Postgres)

Firebird

Visual Studio version: (e.g. Visual Studio 2019 16.8)

16.9.3

**Comment by ErikEJ** [comment]
A demo of the potential difference would be nice to see..

**Comment by MagicAndre1981** [comment]
> A demo of the potential difference would be nice to see..

the link shows the difference:

![image](https://aoa.blob.core.windows.net/aspnet/stacktrace-demystified.png)

**Comment by ErikEJ** [comment]
Thanks for the proposal!
