### ISSUE TITLE
No handlebars for split DbContext configuration classes

### ISSUE THREAD

**Issue by oyemanuel** [ErikEJ/EFCorePowerTools#905]
If we have for example two tables named "table" and "tableConfiguration" while using the "Split DbContext into configuration classes (preview)". the class that implements IEntityTypeConfiguration<tableConfiguration> will point to the entity configuration of the first table, rather than to the entity of the second table. And there are no handlebars template for Configuration classes to fully qualify the implementation IEntityTypeConfiguration.

**Comment by ErikEJ** [comment]
Why do you need to use Handlebars?

**Comment by ErikEJ** [comment]
I read this a second time, and I think I understand better now - will investigate, and thanks for trying out this preview feature.

**Comment by ErikEJ** [comment]
Fixed in latest daily build, please let me know if that solves your issue.
