### ISSUE TITLE
Missing properties

### ISSUE THREAD

**Issue by TSCarterJr** [ErikEJ/EFCorePowerTools#907]
Describe what is not working as expected.

I am trying to retrieve stored procedures. By doing so, I am seeing the auto generated partial class being made, but it's blank.
```
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Stanley.EServices.Web5.Data.Models
{
    public partial class GetReportRequestsResult
    {
    }
}
```

However, I am looking for something similar to: 
```
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stanley.EServices.Web3.Data
{
    using System;
    
    public partial class GetGlobalContacts_Result
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Title { get; set; }
        public string PasscardNumber { get; set; }
        public Nullable<short> AuthorityLevel { get; set; }
        public bool IsHighSecurity { get; set; }
        public string EmailAddress { get; set; }
    }
}
```

### Steps to reproduce
Reverse Engineer -> (Live Dev Server) -> (Select All (Tables, Stored Procedures, etc.).

Options Selected:
Pluralize or singularize generated object names.
Use table & column names directly from db.
Use data annotation
customize code using handlebars template (C#)
Advanced: Stored procedures return list

### Further technical details
EF Core Power Tools version: 2.5.611.0

Database engine: SQL Server

Visual Studio version: VS 2019 - 16.9.3

**Comment by TSCarterJr** [comment]
I will note: We're upgrading from EF6 .net 4.6 to .NET 5.

**Comment by ErikEJ** [comment]
Check the output window in VS, this is most likely because the metadata cannot be determined, maybe because you are using temp tables.

If so, create a new partial class, and add the properties if you know them.

**Comment by ErikEJ** [comment]
There is no such thing as a "upgrade" from EF6!

**Comment by TSCarterJr** [comment]
Even if we're using temp tables, is there a workaround to have them generated?

I'm concerned about the overall flow going forward.

**Comment by TSCarterJr** [comment]
The previous workflow was to update the model via the edmx viewer.

**Comment by ErikEJ** [comment]
There is no EDMX in EF Core.

I am using sp_ describe_first_result_set, if you can make that work, it will work!

**Comment by TSCarterJr** [comment]
Thank you @ErikEJ !
