### ISSUE TITLE
HierarchyId and computed columns are not being included at sqldbroj scaffold

### ISSUE THREAD

**Issue by pedro-gilmora** [ErikEJ/EFCorePowerTools#911]
Hi @ErikEJ ... I realized you fixed the #883 .. thaks so much. It's just that HierarchyId are not being reflected in model after scaffold a SqlDbProj. My project actually use some HierarchyId fields.

As you can see in this JetBrains Rider comparison, it took away the field
![image](https://user-images.githubusercontent.com/33942331/114107639-65331280-989f-11eb-8a60-56bb07267111.png)

So, any extra step to make it happen?

### Steps to reproduce
I ran the scaffold command. Last line describes my issue.
```
D:\Code\System\DataModel>dotnet ef dbcontext scaffold ..\DB\bin\Debug\DB.dacpac ErikEJ.EntityFrameworkCore.SqlServer.Dacpac -o DataModel -c "ERPDbContext" -f --sta
rtup-project "../Api/Api.csproj" --no-onconfiguring -d
Build started...
Build succeeded.
Could not find type mapping for column 'dbo.Location.LevelId' with data type ''. Skipping column.
```
Also, computed fields are not being included 
**SQL Definition**
![image](https://user-images.githubusercontent.com/33942331/114117142-09bf4f80-98b4-11eb-9e04-6d7e5e8adbad.png)
**After scaffold**
You can see my version doesn't include the QuoteNumber property
![image](https://user-images.githubusercontent.com/33942331/114117210-2e1b2c00-98b4-11eb-81b7-80b19f4bd8c7.png)

### Further technical details
DataModel project file has the package reference
![image](https://user-images.githubusercontent.com/33942331/114108746-c0660480-98a1-11eb-9a5e-508cfa11b40e.png)

My DataModel Context class has a partial class with its own OnConfiguring definition for HierarchyId usage
![image](https://user-images.githubusercontent.com/33942331/114108838-facfa180-98a1-11eb-98b4-09fea342dbab.png)

### Database engine: 
SQL Server

**Comment by ErikEJ** [comment]
What happens when you scaffold this from a live database?

**Comment by ErikEJ** [comment]
- Computed columns are not supported, as documented.

**Comment by ErikEJ** [comment]
Ping?

**Comment by ErikEJ** [comment]
It looks like the HeirarchyId package you use does not support reverse engineering, I have raised a question in the package repo: https://github.com/efcore/EFCore.SqlServer.HierarchyId/issues/52

**Comment by pedro-gilmora** [comment]
Ok, I didn't know about not supporting computed properties... Seems like it won't be suitable for the version I created based on your solution.. but thank you so much and great job!!
