### ISSUE TITLE
Reverse engineer newsequentialid does not add DatabaseGenerated attribute on property

### ISSUE THREAD

**Issue by Gambero81** [ErikEJ/EFCorePowerTools#913]
This column definition

`UserId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID()`

generate:

```
[Key]
public Guid UserId { get; set; }
```

it would be glad to generate:

```
[Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
public Guid UserId { get; set; }
```

### Steps to reproduce
1. Create a sql server table with a uniqueidentifier column with default set to newsequentialid.

2. Do reverse engineer (include dataannotation generation option)

### Further technical details
EF Core Power Tools version: 2.5.612

Database engine: SQL Server 2017

Visual Studio version: Visual Studio 2019 16.9

**Comment by ErikEJ** [comment]
This is by design, more info here: https://github.com/dotnet/efcore/issues/23991#issuecomment-768275437
