### ISSUE TITLE
Running REVERSE ENGINEER against a *REMOTE* sql server database just stops

### ISSUE THREAD

**Issue by Duelbat** [ErikEJ/EFCorePowerTools#916]
I have a remote database (not on my PC) against which I am running the "reverse engineer". This has been working flawlessly in the past, but has just stopped working. It does not hang the IDE, but just stops. This happens when I add the AspNetUsers table to be scaffolded. Otherwise it works fine.

Update: If I leave out the primary key, then it gives above behavior. If I include primary key then it works fine.

Thanks
Luke

**Comment by ErikEJ** [comment]
What does "just stop" mean?

Have you checked the Output window for errors?

**Comment by ErikEJ** [comment]
Ping?

**Comment by ErikEJ** [comment]
Closing as the requested information was not supplied - feel free to reopen when available.
