### ISSUE TITLE
Stored procedure model, must include DBContext and at least one table

### ISSUE THREAD

**Issue by RajNZ** [ErikEJ/EFCorePowerTools#917]
Hi,

Great project, saves a lot of time and one of the few ways to reverse engineer sp's.
What I have found in version 2.5.612 is that I cannot simply create a model from a stored procedure alone -
1. have to select at least one table in addition to the sp, otherwise the Ok button is disabled and cannot continue
2. have to select EntityTypes & DbContext, not just EntityTypes only, for the model to be created

Thanks
Paul

**Comment by ErikEJ** [comment]
re 1: The stored procedure mapping takes advantage of a number of EF Core / DBContext features like connection string, DbConnection, and result serialization, and the procedures are accessed via the DbContext.

Unfortunately, there is no simple way to generate a DBContext without any tables/views.

re 2: See above!

**Comment by ErikEJ** [comment]
Do you have any proposals for how to do result mapping and connection handling without a DbContext?

**Comment by RajNZ** [comment]
No proposals unfortunately, I am a complete n00b at this!
I can certainly understand how the DBContext & a table has to be in place in order to have the infrastructure available to access other db objects.  Short of deleting unwanted files at the end of the process if only sp's and models are selected, I have no suggestions.
For the occasional use case this is I'm happy to manually deal with the extra things created.
