### ISSUE TITLE
Stored Procedure not general code when using update

### ISSUE THREAD

**Issue by royaldragonit** [ErikEJ/EFCorePowerTools#918]
CREATE PROCEDURE [dbo].[DS_Login]
         @username NVARCHAR(100) = 'admin',
	@password NVARCHAR(100) = N'21232f297a57a5a743894a0e4a801fc3',
	@lang NVARCHAR(3)		= 'vi'
AS
BEGIN
	-- Update Language for User if Login successfully
	UPDATE dbo.Users SET Lang=@lang WHERE IsActive = 1 AND Username = @username AND Password = @password;
	--RESELECT
	SELECT u.Fullname,p.PermissionName AS RoleName,
		p.Description AS RoleDescription,u.UsersId AS UserId,u.Username,u.Lang,'' AS Token
			FROM dbo.Users u
			JOIN dbo.Permission p
			ON p.PermissionId = u.PermissionId AND u.IsActive = 1 AND u.Username = @username AND u.Password = @password;
END

#Remove Update 
If only select --->working

**Comment by ErikEJ** [comment]
This is most likely by design - I have updated the docs here: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#sql-server-stored-procedures
