### ISSUE TITLE
Request: add/keep enums in EF reverse-engineered entities

### ISSUE THREAD

**Issue by REMjn832** [ErikEJ/EFCorePowerTools#919]
First of all Erik - thank you! The work you have put into this project is great!

My question may be answered already, but I wasn't able to find it. I watched both videos, and looked through the documentation and couldn't find an answer to this. I apologize if this is already handled, and I just didn't see it. 

I am going to be reverse engineering a SQL-Server database. Many columns in the DB have int32 (_enum_) values. So normally, I would add those enums in the EF Model (in the entities). How do you advise I approach solving this problem? I am assuming any changes/edits I make to my entities will be removed, the next time I "Reverse Engineer", or "Refresh"? So if I added my enums to the entities, they would be gone. What would you suggest in this use-case?

Thank you,
Josh

**Comment by ErikEJ** [comment]
There is this, which I have just added to the wiki: https://github.com/ErikEJ/EFCorePowerTools/issues/572#issuecomment-725603917

**Comment by ErikEJ** [comment]
Ping?

**Comment by REMjn832** [comment]
Hi Erik, thanks for the quick followup.
I think that is just the thing I was looking for. You had mentioned updating the wiki, but I couldn't find the update. I think the premise for the solution will work just fine - but I am struggling to see how to implement the hidden columns feature Stefano and you worked on. I see how to rename the column, but how would you modify the file to ignore a column so I can create the column/enum code in my own partial class?
Thanks!

**Comment by ErikEJ** [comment]
Just use the UI! See the updated docs section here: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#choose-database-objects

**Comment by REMjn832** [comment]
WOW! That is perfect, Erik! I didn't realize the UI portion had been completed already. WELL DONE, and THANK YOU very much! This can be be closed.

**Comment by ErikEJ** [comment]
Custom [enum mapping](https://github.com/ErikEJ/EFCorePowerTools/issues/1472#issuecomment-1220273164) is now available with EF Core 7 and T4 templates
