### ISSUE TITLE
[Feature Request] Make usage of "Guid" instead of "Id" as FK-suffix possible

### ISSUE THREAD

**Issue by sharpdevel** [ErikEJ/EFCorePowerTools#92]
I name all my primary keys "Guid" and use the suffix "Guid" for all foreign key columns too. 

```
class Customer {
    public Guid Guid {get;set;}
    public String Name {get;set}
    public Guid AddressGuid {get;set}

    public Address Address {get;set;}
}

class Address {
    public Guid Guid {get;set;}
}
```

When I reverse engineer this from the database the navigation property "Address" in the "Customer" class will be named "AddressGu" instead of "Address" because only the word "id" is stripped from the column name.

This is also the behaviour of scaffold-dbcontext and very unfortune. 

I would love to see this feature.

### Further technical details
EF Core Power Tools version: 1.0.643.0

EF Core: 2.1

Database engine: SQL Server

Visual Studio version: VS 2017

**Comment by ErikEJ** [comment]
Maybe the new custom naming feature can help you #14
