### ISSUE TITLE
Cannot Set Non-Nullable Integer to 0 When Using a SQL Default

### ISSUE THREAD

**Issue by jim-brown-fst** [ErikEJ/EFCorePowerTools#922]
You cannot set a non-nullable integer to 0 if SQL Server has a -1 default value for it. EF detects this as a "default" value for a non-nullable int and ignores sending it in the SQL statement. The effect is that you set the int to 0 but get the default SQL value instead (-1). This would probably happen with any default value, not just -1, but I haven't tested others.

If you had a default of 0 it would work fine of course.

### Steps to reproduce
In SQL Server create a non-nullable int with a default value of -1 (from an old Access application).
Use EFCorePowerTools to reverse engineer it.
You will get a non-nullable C# property with HasDefaultValueSql("((-1))").
You can try to set this property to 0 but since that is the default value for an int the value is ignored and it gets a default of -1!

This is essentially the same type of issue described here for booleans:
https://github.com/ErikEJ/EFCorePowerTools/issues/373

We would also want non-nullable int SQL columns which have a default value to be Nullable<int> in C# as well.

### Further technical details
EF Core Power Tools version: 2.5.616.0

Database engine: SQL Server

Visual Studio version: Visual Studio 2019 16.9.2

**Comment by ErikEJ** [comment]
Could you share a piece of code to show the update of the value?

**Comment by ErikEJ** [comment]
What you are asking for sounds like the exact opposite of #373 - or am I misunderstanding?

**Comment by jim-brown-fst** [comment]
@ErikEJ yes exactly. We want it to behave like it does with booleans where it makes the C# int nullable if there is a default value. Otherwise there is no way to set it to 0.

**Comment by jim-brown-fst** [comment]
> Could you share a piece of code to show the update of the value?

var someObject = new SomeEfClass();
someObject.IsIntPropWithDefaultSqlValue = 0;
db.SomeTable.Add(someObject);
db.SaveChanges();
// ^^saves -1 instead

**Comment by ErikEJ** [comment]
@roji ?

**Comment by roji** [comment]
I'm assuming IsIntPropWithDefaultSqlValue is configured in EF Core to have the default value (with HasDefaultValue).

When you use HasDefaultValue (and various other value generation setups), EF Core assumes that a default value (0 in the case of int) means "unset", and uses that as the trigger to not send any value for the column; this is what allows the database-configured default value to actually be used.

You can disable this behavior by configuring the column with ValueGeneratedNever - this makes EF Core always send whatever value is set, including 0. But if you do this, you can no longer ask for the database default value to be used (-1).

[This is the doc page](https://docs.microsoft.com/en-us/ef/core/modeling/generated-properties?tabs=data-annotations#default-values) which covers most of this.

/cc @ajcvickers to make sure I got this right.

**Comment by ErikEJ** [comment]
@roji This is Reverse engineering - not manual modelling...

**Comment by roji** [comment]
Sorry, I guess I read this too quickly.

I wasn't present when these discussions happened, so I'll defer to @ajcvickers on this - the ask here is basically for int to be reverse-engineered the same way as bools, i.e. if there's a database default, we would scaffold a nullable int property.

**Comment by ajcvickers** [comment]
Starting with 5.0, nullable backing fields are a better pattern for this: https://docs.microsoft.com/en-us/ef/core/change-tracking/miscellaneous#using-nullable-backing-fields

It would not be unreasonable to do this for any type where the default value is a problem, but it's not easy to tell when the default value is going to be a problem without knowing how it is going to be used.

**Comment by christian-brubaker-562** [comment]
Will this make it into a future release? We have implemented a partial class that overrides the mappings as a stop gap in the meantime: 
modelBuilder.Entity<TEntity>().Property(e => e.IntegerProperty).ValueGeneratedNever();

**Comment by ErikEJ** [comment]
@christian-brubaker-562 I think not, this is the first time I hear about this issue, and there is a workaround, as you describe. I currently do this for bool columns, but I am not sure it will be wise to do it for all defaultSql values: https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/RevEng.Core/ReverseEngineerScaffolder.cs#L182
