### ISSUE TITLE
Navigation names not working as expected with multi-column foreign keys

### ISSUE THREAD

**Issue by Leopoldo-Rangel** [ErikEJ/EFCorePowerTools#923]
Hi, first of all kudos for your work!

With the following DB schema for a multi-tenant project:

```
CREATE TABLE [dbo].[Portfolios]
(
[AccountId] [int] NOT NULL,
[Id] [uniqueidentifier] NOT NULL,
[Name] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
)
GO

ALTER TABLE [dbo].[Portfolios] ADD CONSTRAINT [PK_Portfolios] PRIMARY KEY CLUSTERED  ([AccountId], [Id])
GO

CREATE TABLE [dbo].[PortfolioItemRelationships]
(
[AccountId] [int] NOT NULL,
[PortfolioId] [uniqueidentifier] NOT NULL,
[ParentPortfolioId] [uniqueidentifier] NOT NULL
)
GO

ALTER TABLE [dbo].[PortfolioItemRelationships] ADD CONSTRAINT [PK_PortfolioItemRelationships] PRIMARY KEY CLUSTERED  ([AccountId], [PortfolioId], [ParentPortfolioId])
GO
ALTER TABLE [dbo].[PortfolioItemRelationships] ADD CONSTRAINT [FK_PortfolioItemRelationships_Portfolios_AccountId_ParentPortfolioId] FOREIGN KEY ([AccountId], [ParentPortfolioId]) REFERENCES [dbo].[Portfolios] ([AccountId], [Id])
GO
ALTER TABLE [dbo].[PortfolioItemRelationships] ADD CONSTRAINT [FK_PortfolioItemRelationships_Portfolios_AccountId_PortfolioId] FOREIGN KEY ([AccountId], [PortfolioId]) REFERENCES [dbo].[Portfolios] ([AccountId], [Id])
GO
```
The following navigation properties are generated when doing reverse engineer for table PortfolioItemRelationships:

![image](https://user-images.githubusercontent.com/82784026/115165778-3540f780-a075-11eb-8597-62d6a15a4ad9.png)

It looks like EF Core Power tools is unable to differentiate one relationship from the other and for the second one it only appends "Navigation" suffix. If AccountId is ommited from both Primary Keys and Foreign Keys the code generation looks like this (which is what I would like to see on both cases): 

![image](https://user-images.githubusercontent.com/82784026/115165714-d4b1ba80-a074-11eb-9749-c7dc5fbb7681.png)

I attempted to rename the navigation properties using efpt.renaming.json:

```
     {
        "Columns": [ ],
        "Name": "PortfolioItemRelationships",
        "Navigations": [
           {
              "Name": "Portfolios",
              "NewName": "Portfolio"
           },
           {
              "Name": "PortfoliosNavigation",
              "NewName": "ParentPortfolio"
           }
        ],
        "NewName": "PortfolioItemRelationships"
     }
```

But it only seems to correct the first relationship:

![image](https://user-images.githubusercontent.com/82784026/115165892-cf08a480-a075-11eb-8916-31dc158469ae.png)

Any suggestions or workarounds ?
Thank you!

### Further technical details
EF Core Power Tools version: 2.5.616

Database engine: SQL Server 2019

Visual Studio version: Visual Studio 2019 16.9.4

**Comment by ErikEJ** [comment]
Thanks for trying out the experimental Navigation rename feature - sadly, this is not supported with/is a bug in the current implementation.
What happens is a candidate name is generated based on the foreign key, and then the renamer kicks in, but in this case, the candidate name is exactly the same, as the ...Navigation suffix is only added later to distinguish/uniquefy the name.

So a name of "PortfolioNavigation" is never matched!

**Comment by Leopoldo-Rangel** [comment]
Thank you for your time!

**Comment by ErikEJ** [comment]
I am going to remove this broken feature for now.
