### ISSUE TITLE
Missing equal sign when creating DBContextExtensions

### ISSUE THREAD

**Issue by KayakFisher205** [ErikEJ/EFCorePowerTools#924]
When adding Stored procedures, the file DBContextExensions.cs is created for the calls. When checking for null on the parameters, the code for the Task<T[]>SqlQueryAsync<T> is missing an Equal sign after the ??

### Steps to reproduce
Connect to a database, select some stored procedures and select OK

Note: There was a warning that for one of the stored procedures, 

Unable to get result set shape for procedure 'dbo.proc_GetNextQ3IDx2'
The metadata could not be determined because statement 'exec @ret = sys.sp_sequence_get_range_internal @sequence_name, @range_size, @range_first_value outpu' in procedure 'sp_sequence_get_range' invokes an extended stored procedure.

I don't know if that had some effect or not.

### Further technical details
EF Core Power Tools version: 2.5.616

Database engine: (SQL Server)

Visual Studio version: (Visual Studio 2019 16.10.0 Preview 2.0)
![image](https://user-images.githubusercontent.com/71768711/115396627-d087b900-a1aa-11eb-82ed-8a5dfd1368db.png)

**Comment by ErikEJ** [comment]
Its a bug in the latest daily build!

**Comment by ErikEJ** [comment]
Thanks for using the daily builds!
