### ISSUE TITLE
Stored Procedure not working

### ISSUE THREAD

**Issue by GearTheWorld** [ErikEJ/EFCorePowerTools#925]
Describe what is not working as expected.

**Steps to reproduce**
I just try to add a stored procedure and despite having a message of success I have nothing, no function import, no complex type.  I don't know what I'm doing wrong.  I attached my Stored Procedure and the config file

[Files.zip](https://github.com/ErikEJ/EFCorePowerTools/files/6347166/Files.zip)

**EF Core Power Tools Version**
Version 2.5.612.0
SQLite ADO.NET Provider included: 1.0.109.0
SQLite EF6 DbProvider in GAC - No
System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes

**Database engine: (SQlite, SQL Compact, SQL Server, Postgres)**
SQL Server 2016

**Visual Studio version: (e.g. Visual Studio 2019 16.8)**
Microsoft Visual Studio Professional 2019
Version 16.9.4
VisualStudio.16.Release/16.9.4+31205.134
Microsoft .NET Framework
Version 4.8.04084

**Comment by ErikEJ** [comment]
Have you checked the output window for errors?

**Comment by GearTheWorld** [comment]
The output window shows nothing

**Comment by GearTheWorld** [comment]
There's a something written about the SP in the config files
```

      {
         "Name": "[dbo].[GetShipments]",
         "ObjectType": 1
      }
```

**Comment by ErikEJ** [comment]
Are you able to generate other stored procedures from the same database?

Can you run: sp_describe_first_result_set against it?

**Comment by GearTheWorld** [comment]
I ran the script and it generates the data beautifully with everything described correctly

![image](https://user-images.githubusercontent.com/8614008/115510803-5f2f2f80-a2aa-11eb-963b-ce13095eb683.png)

**Comment by ErikEJ** [comment]
Could you share your generated code, I cannot implement the stored procedure without the referenced tables

**Comment by GearTheWorld** [comment]
What do you mean by generated code?

**Comment by ErikEJ** [comment]
The code generated by power Tools.

**Comment by GearTheWorld** [comment]
Sadly, it generates nothing

**Comment by GearTheWorld** [comment]
I can give you a video of what is going on if you want

**Comment by ErikEJ** [comment]
What makes you think no code is generated? I prefer a repo project / schema

**Comment by GearTheWorld** [comment]
Ok let me prepare you a repo.  Hold on

**Comment by GearTheWorld** [comment]
Here it is.  In the main project, you have a folder called Files in which I added the entire database script
and the project CubiDataStore is the one to use the EF Core Power Tool

Hope this helps
[RepoForErik.zip](https://github.com/ErikEJ/EFCorePowerTools/files/6349098/RepoForErik.zip)

**Comment by ErikEJ** [comment]
Yes, that helped, the stored procedures depend on a DbContext, and you have selected to only generate Entity Types!

You need to refactor your "DataStore.cs" so at least some parts of it is generated by EF Core Power Tools!

**Comment by GearTheWorld** [comment]
Thank you Erik

**Comment by GearTheWorld** [comment]
Finally, my DataStore.cs is useless.  I removed it and now I'm using the tool to generates the ApplicationDbContext

**Comment by ErikEJ** [comment]
I will log an error if sprocs or functions are selected when generating entities only.
