### ISSUE TITLE
Reverse Engineer Stored Procedures that call sp_sequence_get_range

### ISSUE THREAD

**Issue by KayakFisher205** [ErikEJ/EFCorePowerTools#926]
I have a stored procedure that gets 2 Sequence numbers for a job.
SQL Sequences - https://docs.microsoft.com/en-us/sql/relational-databases/sequence-numbers/sequence-numbers?view=sql-server-ver15
To get one sequence number, its straightforward, select SELECT Col0=NEXT VALUE FOR dbo.ExternalSeq

You can get a range of sequences, lets say you want 2 numbers, then you have to do:
ALTER PROCEDURE [dbo].[proc_GetNextQ3IDx2] 
	-- Add the parameters for the stored procedure here

AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    -- Insert statements for procedure here
	DECLARE    
  @FirstSeqNum sql_variant  
, @LastSeqNum sql_variant  
, @CycleCount int  
, @SeqIncr sql_variant  
, @SeqMinVal sql_variant  
, @SeqMaxVal sql_variant ;  
  
EXEC sys.sp_sequence_get_range  
@sequence_name = N'q3recordcounter'  
, @range_size = 2  
, @range_first_value = @FirstSeqNum OUTPUT   
, @range_last_value = @LastSeqNum OUTPUT   
, @range_cycle_count = @CycleCount OUTPUT  
, @sequence_increment = @SeqIncr OUTPUT  
, @sequence_min_value = @SeqMinVal OUTPUT  
, @sequence_max_value = @SeqMaxVal OUTPUT ;  
  
-- The following statement returns the output values  
SELECT  
  FirstVal=@FirstSeqNum 
,  LastVal=@LastSeqNum  
END

When you run Reverse Engineer on this stored procedure, then there is an error,
The metadata could not be determined because statement 'exec @ret = sys.sp_sequence_get_range_internal @sequence_name, @range_size, @range_first_value outpu' in procedure 'sp_sequence_get_range' invokes an extended stored procedure.

### Steps to reproduce
Create the Stored Procedure (after creating a SQL Sequence) and try to Reverse Engineer

### Further technical details
EF Core Power Tools version: 2.5.618

Database engine:  SQL Server

Visual Studio version: (e.g. Visual Studio 2019 16.8)

**Comment by ErikEJ** [comment]
This is by design, the result set cannot be determined.

There is an empty result set class generated. You can create a new partial class of this, and add the expected property.

**Comment by KayakFisher205** [comment]
No problem. Just wanted to see if it was something in the works or not. Thanks for the help.
