### ISSUE TITLE
Offline install hangs

### ISSUE THREAD

**Issue by DreamU1952** [ErikEJ/EFCorePowerTools#929]
Downloaded EF_Core_Power_Tools_v2.5.612.vsix and copied to an offline Visual Studio computer (secure environment not connected to the web.) When I try to install it hangs for quite some time trying to download 'Microsoft.VisualStudio.GraphDocument.Resource...' (cannot see rest of the package name). Since I am offline no download is going to succeed. Any way to install the product when offline?

**Comment by ErikEJ** [comment]
Yes, you must add the required DGML viewer component first.

**Comment by DreamU1952** [comment]
If by DGML viewer you mean: 
     Tools > Get tools and features... > Individual Component > Code tools > DGML Editor
that is already installed.

Here is the output from the log which identifies two downloads which will necessarily fail:

4/22/2021 3:28:34 PM - Package 'Microsoft.VisualStudio.GraphDocument.Resources,version=16.8.30608.117,language=en-US' failed to download from 'https://download.visualstudio.microsoft.com/download/pr/7a819910-6bf6-4e7b-838c-97c15e850629/3da6a8efe4dfdad35a5ff04e3ef3b60e3dc9606aa3089d86c74f535dcea9da59/payload.vsix'. WebClient download failed: The remote name could not be resolved: 'download.visualstudio.microsoft.com'. Bits download failed: File not found.. WinInet download failed: Function: InternetOpenUrl, HR: -2147012889, Message: Unknown error 12007, Signature: PackageId=Microsoft.VisualStudio.GraphDocument.Resources;PackageAction=DownloadPackage;ReturnCode=0x80131500
4/22/2021 3:28:34 PM - Skipping Install of 'Microsoft.VisualStudio.GraphDocument.Resources,version=16.8.30608.117,language=en-US' since the package or a parent package had a vital failure.
4/22/2021 3:28:34 PM - Skipping cache of package 'Microsoft.VisualStudio.GraphDocument.Resources,version=16.8.30608.117,language=en-US' since the package or a parent package had a vital failure.
4/22/2021 3:28:34 PM - Skipping download of package 'Microsoft.VisualStudio.Vmp,version=16.8.30509.167' since the package or a parent package had a vital failure.
4/22/2021 3:32:34 PM - Package 'Microsoft.VisualStudio.GraphDocument,version=16.8.30608.117' failed to download from 'https://download.visualstudio.microsoft.com/download/pr/7a819910-6bf6-4e7b-838c-97c15e850629/0ef4665917161add9443a02e1cc7e2484b34a86fdbb6be62e855fcadfe0c5662/payload.vsix'. WebClient download failed: The remote name could not be resolved: 'download.visualstudio.microsoft.com'. Bits download failed: File not found.. WinInet download failed: Function: InternetOpenUrl, HR: -2147012889, Message: Unknown error 12007, Signature: PackageId=Microsoft.VisualStudio.GraphDocument;PackageAction=DownloadPackage;ReturnCode=0x80131500
4/22/2021 3:32:34 PM - Skipping Install of 'Microsoft.VisualStudio.GraphDocument,version=16.8.30608.117' since downloading it failed.

**Comment by ErikEJ** [comment]
I assume the conclusion is that this is not possible then.

**Comment by tHesTx** [comment]
There is no way around this? I need to install it offline, and my Visual Studio already has DGML installed.

**Comment by madskristensen** [comment]
@tinaschrepfer Do you know?
