### ISSUE TITLE
Empty ProjectRootNamespace in efpt.config.json will be replaced by project name

### ISSUE THREAD

**Issue by HSchwichtenberg** [ErikEJ/EFCorePowerTools#930]
### Steps to reproduce
efpt.config.json with  "ProjectRootNamespace": "",
When I rerun Reverse Engineering it will be replaced by the project name in the dialog. However, it should stay empty.

![2021-04-23_10-11-28](https://user-images.githubusercontent.com/3673169/115841113-bfde7980-a41c-11eb-9838-34f0c135e99a.jpg)

### Further technical details
EF Core Power Tools version: 2.5.612 (April 6, 2021)
Visual Studio version: Visual Studio 2019 16.9.3

**Comment by ErikEJ** [comment]
Fixed in latest daily build https://github.com/ErikEJ/EFCorePowerTools/commit/83825b9adc02cae5394b3420cdd7dbbc90533c39
