### ISSUE TITLE
Question: Select tables with wildcard in efpt.config.json

### ISSUE THREAD

**Issue by flensrocker** [ErikEJ/EFCorePowerTools#931]
I have a legacy application with a lot of tables. And this application is still in use and will get updates to its database schema.
Mostly we are adding some fields, but from time to time we add a new table.

It would be great if I can specify a wildcard in the config file, so all tables of a specific schema are used for the code generation.
Something like
```
   "Tables": [
      {
         "Name": "[dbo].*",
         "ObjectType": 0
      }
   ],
```

I'm using an existing database as the source, not a dacpac project.

**Comment by ErikEJ** [comment]
Have you tried the advanced "Include all objects" option?

**Comment by flensrocker** [comment]
In the database are multiple schemas, I just want to import one (the other ones are from new source which already uses EF Core).

But I will try it!

**Comment by ErikEJ** [comment]
Ok, that is a very specialized requirement!

**Comment by flensrocker** [comment]
I know :)

**Comment by flensrocker** [comment]
I can live with manual selecting the new tables - we are a small team and mostly it will get recognized, if someone adds a new one.

Thank you!

**Comment by ErikEJ** [comment]
But seems like a useful feature. Not sure how easy/simple to implement

**Comment by flensrocker** [comment]
That would be nice!

Each of my DbContext has its own schema so I know which tables belong together.  

BTW: I use these extensions to use the generated code with EF Core 2.1 (the legacy project is .Net 4.6.1)  
With "include all objects" there are some missing - but since I don't use functions, stored procedures etc. I didn't look into it.
```
  public static class EFCore21Extensions
  {
#if NETSTANDARD2_0
    public static EntityTypeBuilder<TEntity> HasComment<TEntity>(this EntityTypeBuilder<TEntity> entityTypeBuilder, string comment)
      where TEntity : class
    {
      return entityTypeBuilder;
    }

    public static PropertyBuilder<TProperty> HasComment<TProperty>(this PropertyBuilder<TProperty> propertyBuilder, string comment)
    {
      return propertyBuilder;
    }

    public static KeyBuilder IsClustered(this KeyBuilder keyBuilder, bool clustered = true)
    {
      return keyBuilder.ForSqlServerIsClustered(clustered);
    }
#endif
  }
```

**Comment by ErikEJ** [comment]
Given how easy it is to select all tables from the UI, and given the feature to include all objects, and given that if you forgot to add a table, you will notice, this is not something I plan to implement.
