### ISSUE TITLE
Edmx -> Context/Model

### ISSUE THREAD

**Issue by boone34** [ErikEJ/EFCorePowerTools#939]
Trying to generate context/model from EF6 edmx file. I want to do this to capture:

- Entity naming/mapping to tables & views
- Property naming/mapping to columns
- Added associations not in the database, specifically tables to views

All my attempt to achieve this fail, with the entities created using the database table/view/column names not the entity/property names in the edmx file. Also associations between views/tables defined in the edmx file are not captured.

I have also found that after selecting an edmx file and then selecting a subset of tables from the tree view does not work. entities for all tables are generated.

### Steps to reproduce

1. Select [Project]->EF Core Power Tools->Reverse Engineer
2. Clear any database connection
3. Add an edmx file. Note the edmx file is not part of the project.
4. Check Use EF Core 5
5. Click OK
6. Select all tables or a sub set
7. Click OK
8. Select Pluralize or singularize ... Note: This should not be necessary since it should take the names in the edmx file which have already been pluralized or singularized or renamed
9. Click OK

### Further technical details
EF Core Power Tools version: 2.5.612

Database engine: SQL Server/Edmx

Visual Studio version: Visual Studio 2019 16.9.4

**Comment by ErikEJ** [comment]
Thanks for trying out this experimental feature.

@omatrot  Any comments?

**Comment by omatrot** [comment]
@boone34 Right now, the conceptual part of the model (naming/pluralization...) is simply ignored in favor of the schema model.
The fact that all entities are generated even when deselected is a bug.

If you could share your EDMX for me to reproduce the issues, that would be a plus.

Thanks in advance.

**Comment by boone34** [comment]
> Right now, the conceptual part of the model (naming/pluralization...) is simply ignored in favor of the storage model.

Unfortunately this is the main functionality I am looking for. I want to port an existing EF6 system that connects to an old legacy database. Considerable work has been done to cleanup the conceptual/entity side of the equation. Also relationships to views can only be added to the conceptual side. I was hoping to not have to re-do this for my EF Core port. From my point of view it would make more sense to ignore the storage model in favor of the conceptual and in include the mappings in the generated EF core context. I would think this would be true of most EDMX users, if you make changes to the conceptual side you probably want those ported to EF core.

See attached Model.zip for edmx file. Look for the conceptual entity _DispatchCustomer_ maps to view _CustomersVw_. In the model this is associated with various other entities/tables.

Thanks for your attention to this ...

[Model.zip](https://github.com/ErikEJ/EFCorePowerTools/files/6386151/Model.zip)

**Comment by omatrot** [comment]
Be reassured, the conceptual model will be be processed, we were proceeding step by step.
Thank you so much for sharing the model, I'll take a look this coming weekend.
Cheers,
Olivier.

**Comment by omatrot** [comment]
All right, as promised, I'm looking into this issue.
What comes to mind right now is to process the conceptual model of the EDMX produce a configuration file to be used by the CLI. I'll get back to you as I progress towards this goal. @ErikEJ feel free to comment on this as we already discussed it in the main issue concerning the EDMX support.

**Comment by ErikEJ** [comment]
@omatrot I think I need to see an example of that to understand the concept.

**Comment by omatrot** [comment]
To put it simply, the conceptual model is the result of what you choose to import/rename in the 'Choose Database objects' dialog box after you choose the EDMX model. This will be filled by why is discovered in the database schema included in the model. In between the two there is is a mapping model that connects both sides.

This is what will produce the various contexts and entities.

Except that in our case, as explained by @boone34 the DispatchCustomer entity is not in the storage model. We have a view instead:

```
        <EntityType Name="CustomersVw">
          <Key>
            <PropertyRef Name="Key" />
          </Key>
          <Property Name="Key" Type="int" Nullable="false" StoreGeneratedPattern="Identity" />
          <Property Name="SiteCustomer" Type="int" Nullable="false" />
          <Property Name="SiteBusiness" Type="int" Nullable="false" />
          <Property Name="Name" Type="nvarchar" MaxLength="255" Nullable="false" />
          <Property Name="PONumber" Type="nvarchar" MaxLength="50" />
          <Property Name="Created" Type="datetime" StoreGeneratedPattern="Computed" />
          <Property Name="Status" Type="int" Nullable="false" />
          <Property Name="SalesPerson" Type="int" Nullable="false" />
          <Property Name="Commission" Type="int" Nullable="false" />
          <Property Name="Attention" Type="nvarchar" MaxLength="50" />
          <Property Name="Address1" Type="nvarchar" MaxLength="50" />
          <Property Name="Address2" Type="nvarchar" MaxLength="50" />
          <Property Name="City" Type="nvarchar" MaxLength="50" />
          <Property Name="State" Type="nvarchar" MaxLength="50" />
          <Property Name="Zip" Type="nvarchar" MaxLength="50" />
          <Property Name="Phone" Type="nvarchar" MaxLength="50" />
          <Property Name="Tax" Type="int" Nullable="false" />
          <Property Name="InvoiceAction" Type="int" Nullable="false" />
          <Property Name="InvoiceCopies" Type="int" Nullable="false" />
          <Property Name="InvoiceReceiver" Type="int" />
          <Property Name="UsageFee" Type="float" />
          <Property Name="MaxJobs" Type="int" />
          <Property Name="BillingInstructions" Type="nvarchar(max)" />
          <Property Name="EMail" Type="nvarchar" MaxLength="50" />
          <Property Name="WarehouseStorageAccount" Type="bit" Nullable="false" />
        </EntityType>
```

Then we have a 'designed by hand' Entity in the Conceptual model:

```
        <EntityType Name="DispatchCustomer">
          <Key>
            <PropertyRef Name="Key" />
          </Key>
          <Property Name="Key" Type="Int32" Nullable="false" annotation:StoreGeneratedPattern="Identity" />
          <Property Name="SiteCustomerKey" Type="Int32" Nullable="false" />
          <Property Name="SiteBusinessKey" Type="Int32" Nullable="false" />
          <Property Name="Name" Type="String" Nullable="false" MaxLength="255" FixedLength="false" Unicode="true" />
          <Property Name="PONumber" Type="String" MaxLength="50" FixedLength="false" Unicode="true" />
          <Property Name="Created" Type="DateTime" Precision="3" annotation:StoreGeneratedPattern="Computed" />
          <Property Name="CustomerStatusKey" Type="Int32" Nullable="false" />
          <Property Name="SalesPersonKey" Type="Int32" Nullable="false" />
          <Property Name="CommissionKey" Type="Int32" Nullable="false" />
          <Property Name="Attention" Type="String" MaxLength="50" FixedLength="false" Unicode="true" />
          <Property Name="Address1" Type="String" MaxLength="50" FixedLength="false" Unicode="true" />
          <Property Name="Address2" Type="String" MaxLength="50" FixedLength="false" Unicode="true" />
          <Property Name="City" Type="String" MaxLength="50" FixedLength="false" Unicode="true" />
          <Property Name="State" Type="String" MaxLength="50" FixedLength="false" Unicode="true" />
          <Property Name="Zip" Type="String" MaxLength="50" FixedLength="false" Unicode="true" />
          <Property Name="Phone" Type="String" MaxLength="50" FixedLength="false" Unicode="true" />
          <Property Name="TaxKey" Type="Int32" Nullable="false" />
          <Property Name="InvoiceAction" Type="Int32" Nullable="false" />
          <Property Name="InvoiceCopies" Type="Int32" Nullable="false" />
          <Property Name="InvoiceReceiverKey" Type="Int32" />
          <Property Name="UsageFee" Type="Double" />
          <NavigationProperty Name="SiteCustomer" Relationship="DispatchModel.SiteCustomerDispatchCustomer" FromRole="DispatchCustomer" ToRole="SiteCustomer" />
          <NavigationProperty Name="SiteBusiness" Relationship="DispatchModel.SiteBusinessDispatchCustomer" FromRole="DispatchCustomer" ToRole="SiteBusiness" />
          <NavigationProperty Name="CustomerStatus" Relationship="DispatchModel.CustomerStatusDispatchCustomer" FromRole="DispatchCustomer" ToRole="CustomerStatus" />
          <NavigationProperty Name="Commission" Relationship="DispatchModel.CommissionDispatchCustomer" FromRole="DispatchCustomer" ToRole="Commission" />
          <NavigationProperty Name="DispatchTax" Relationship="DispatchModel.DispatchTaxDispatchCustomer" FromRole="DispatchCustomer" ToRole="DispatchTax" />
          <NavigationProperty Name="DispatchCustomerContacts" Relationship="DispatchModel.DispatchCustomerDispatchCustomerContact" FromRole="DispatchCustomer" ToRole="DispatchCustomerContact" />
          <NavigationProperty Name="Jobs" Relationship="DispatchModel.DispatchCustomerJob" FromRole="DispatchCustomer" ToRole="Job" />
          <NavigationProperty Name="AdHocBills" Relationship="DispatchModel.DispatchCustomerAdHocBill" FromRole="DispatchCustomer" ToRole="AdHocBill" />
          <NavigationProperty Name="JobLocations" Relationship="DispatchModel.DispatchCustomerJobLocation" FromRole="DispatchCustomer" ToRole="JobLocation" />
          <NavigationProperty Name="SalesPerson" Relationship="DispatchModel.EmployeeDispatchCustomer" FromRole="DispatchCustomer" ToRole="Employee" />
          <NavigationProperty Name="CustomerResourceRates" Relationship="DispatchModel.DispatchCustomerCustomerResourceRate" FromRole="DispatchCustomer" ToRole="CustomerResourceRate" />
          <NavigationProperty Name="CustomerStatusChanges" Relationship="DispatchModel.DispatchCustomerCustomerStatusChange" FromRole="DispatchCustomer" ToRole="CustomerStatusChange" />
          <Property Name="MaxJobs" Type="Int32" />
          <NavigationProperty Name="CustomerBillers" Relationship="DispatchModel.DispatchCustomerCustomerBiller" FromRole="DispatchCustomer" ToRole="CustomerBiller" />
          <Property Name="BillingInstructions" Type="String" MaxLength="Max" FixedLength="false" Unicode="true" />
          <Property Name="EMail" Type="String" MaxLength="50" FixedLength="false" Unicode="true" />
          <Property Name="WarehouseStorageAccount" Type="Boolean" Nullable="false" />
        </EntityType>
```

And a mapping between the two:

```
          <EntitySetMapping Name="DispatchCustomers">
            <EntityTypeMapping TypeName="DispatchModel.DispatchCustomer">
              <MappingFragment StoreEntitySet="CustomersVw">
                <ScalarProperty Name="WarehouseStorageAccount" ColumnName="WarehouseStorageAccount" />
                <ScalarProperty Name="EMail" ColumnName="EMail" />
                <ScalarProperty Name="BillingInstructions" ColumnName="BillingInstructions" />
                <ScalarProperty Name="MaxJobs" ColumnName="MaxJobs" />
                <ScalarProperty Name="UsageFee" ColumnName="UsageFee" />
                <ScalarProperty Name="InvoiceReceiverKey" ColumnName="InvoiceReceiver" />
                <ScalarProperty Name="InvoiceCopies" ColumnName="InvoiceCopies" />
                <ScalarProperty Name="InvoiceAction" ColumnName="InvoiceAction" />
                <ScalarProperty Name="TaxKey" ColumnName="Tax" />
                <ScalarProperty Name="Phone" ColumnName="Phone" />
                <ScalarProperty Name="Zip" ColumnName="Zip" />
                <ScalarProperty Name="State" ColumnName="State" />
                <ScalarProperty Name="City" ColumnName="City" />
                <ScalarProperty Name="Address2" ColumnName="Address2" />
                <ScalarProperty Name="Address1" ColumnName="Address1" />
                <ScalarProperty Name="Attention" ColumnName="Attention" />
                <ScalarProperty Name="CommissionKey" ColumnName="Commission" />
                <ScalarProperty Name="SalesPersonKey" ColumnName="SalesPerson" />
                <ScalarProperty Name="CustomerStatusKey" ColumnName="Status" />
                <ScalarProperty Name="Created" ColumnName="Created" />
                <ScalarProperty Name="PONumber" ColumnName="PONumber" />
                <ScalarProperty Name="Name" ColumnName="Name" />
                <ScalarProperty Name="SiteBusinessKey" ColumnName="SiteBusiness" />
                <ScalarProperty Name="SiteCustomerKey" ColumnName="SiteCustomer" />
                <ScalarProperty Name="Key" ColumnName="Key" />
              </MappingFragment>
            </EntityTypeMapping>
            <EntityTypeMapping TypeName="DispatchModel.DispatchCustomer">
              <ModificationFunctionMapping>
                <DeleteFunction FunctionName="NorcalMasterModel.Store.CustomersVwsDelete">
                  <ScalarProperty Name="Key" ParameterName="Key" />
                </DeleteFunction>
                <InsertFunction FunctionName="NorcalMasterModel.Store.CustomerVwsInsertEF">
                  <ScalarProperty Name="WarehouseStorageAccount" ParameterName="WarehouseStorageAccount" />
                  <ScalarProperty Name="EMail" ParameterName="EMail" />
                  <ScalarProperty Name="BillingInstructions" ParameterName="BillingInstructions" />
                  <ScalarProperty Name="MaxJobs" ParameterName="MaxJobs" />
                  <ScalarProperty Name="InvoiceReceiverKey" ParameterName="InvoiceReceiver" />
                  <ScalarProperty Name="TaxKey" ParameterName="Tax" />
                  <ScalarProperty Name="CommissionKey" ParameterName="Commission" />
                  <ScalarProperty Name="SalesPersonKey" ParameterName="SalesPerson" />
                  <ScalarProperty Name="CustomerStatusKey" ParameterName="Status" />
                  <ScalarProperty Name="SiteBusinessKey" ParameterName="SiteBusiness" />
                  <ScalarProperty Name="SiteCustomerKey" ParameterName="SiteCustomer" />
                  <ScalarProperty Name="UsageFee" ParameterName="UsageFee" />
                  <ScalarProperty Name="InvoiceCopies" ParameterName="InvoiceCopies" />
                  <ScalarProperty Name="InvoiceAction" ParameterName="InvoiceAction" />
                  <ScalarProperty Name="Phone" ParameterName="Phone" />
                  <ScalarProperty Name="Zip" ParameterName="Zip" />
                  <ScalarProperty Name="State" ParameterName="State" />
                  <ScalarProperty Name="City" ParameterName="City" />
                  <ScalarProperty Name="Address2" ParameterName="Address2" />
                  <ScalarProperty Name="Address1" ParameterName="Address1" />
                  <ScalarProperty Name="Attention" ParameterName="Attention" />
                  <ScalarProperty Name="PONumber" ParameterName="PONumber" />
                  <ScalarProperty Name="Name" ParameterName="Name" />
                  <ResultBinding Name="Key" ColumnName="Key" />
                  <ResultBinding Name="Created" ColumnName="Created" />
                </InsertFunction>
                <UpdateFunction FunctionName="NorcalMasterModel.Store.CustomerVwsUpdateEF">
                  <ScalarProperty Name="WarehouseStorageAccount" ParameterName="WarehouseStorageAccount" Version="Current" />
                  <ScalarProperty Name="EMail" ParameterName="EMail" Version="Current" />
                  <ScalarProperty Name="InvoiceReceiverKey" ParameterName="InvoiceReceiver" Version="Current" />
                  <ScalarProperty Name="TaxKey" ParameterName="Tax" Version="Current" />
                  <ScalarProperty Name="CommissionKey" ParameterName="Commission" Version="Current" />
                  <ScalarProperty Name="SalesPersonKey" ParameterName="SalesPerson" Version="Current" />
                  <ScalarProperty Name="CustomerStatusKey" ParameterName="Status" Version="Current" />
                  <ScalarProperty Name="SiteBusinessKey" ParameterName="SiteBusiness" Version="Current" />
                  <ScalarProperty Name="SiteCustomerKey" ParameterName="SiteCustomer" Version="Current" />
                  <ScalarProperty Name="BillingInstructions" ParameterName="BillingInstructions" Version="Current" />
                  <ScalarProperty Name="MaxJobs" ParameterName="MaxJobs" Version="Current" />
                  <ScalarProperty Name="UsageFee" ParameterName="UsageFee" Version="Current" />
                  <ScalarProperty Name="InvoiceCopies" ParameterName="InvoiceCopies" Version="Current" />
                  <ScalarProperty Name="InvoiceAction" ParameterName="InvoiceAction" Version="Current" />
                  <ScalarProperty Name="Phone" ParameterName="Phone" Version="Current" />
                  <ScalarProperty Name="Zip" ParameterName="Zip" Version="Current" />
                  <ScalarProperty Name="State" ParameterName="State" Version="Current" />
                  <ScalarProperty Name="City" ParameterName="City" Version="Current" />
                  <ScalarProperty Name="Address2" ParameterName="Address2" Version="Current" />
                  <ScalarProperty Name="Address1" ParameterName="Address1" Version="Current" />
                  <ScalarProperty Name="Attention" ParameterName="Attention" Version="Current" />
                  <ScalarProperty Name="PONumber" ParameterName="PONumber" Version="Current" />
                  <ScalarProperty Name="Name" ParameterName="Name" Version="Current" />
                  <ScalarProperty Name="Key" ParameterName="Key" Version="Current" />
                </UpdateFunction>
              </ModificationFunctionMapping>
            </EntityTypeMapping>
          </EntitySetMapping>
```

Now I have to say I do not know exactly how EF Core scaffolding works internally but there has to be a way to configure it to do this as well...

The storage part helps define and run the queries against the database, the mapping en entities helps builds the result sets.

Am I clear enough ?

**Comment by ErikEJ** [comment]
I think what you are hoping for is simply not possible.

**Comment by omatrot** [comment]
Why? Is this because of the view? The mapping is just the configuration of entities in EF Core.
I'll try to do something with the existing tooling and get back to you.

**Comment by ErikEJ** [comment]
If you create a mapping that does not correspond to a table, how will EF core generate valid SQL?

**Comment by omatrot** [comment]
With the proper [HasColumnName](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.relationalpropertybuilderextensions.hascolumnname?view=efcore-5.0) call?

AFAIK you can rename any view/table/column to whatever you want. But What I do not know yet, is how you influence the process in EFCorePowerTools. I think that a configuration file is one way to do it with the CLI.

**Comment by ErikEJ** [comment]
I think domain modelling is beyond the scope of this tool.

**Comment by omatrot** [comment]
On the contrary I would have said that EF domain modeling is a core component that is used during scaffolding with the model builder fluent API.

You’re the boss here. Just le me if you want to go further or not.

@boone34 has a need that needs to be fullfilled, even if this should be with another set sod tooling.

Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Erik Ejlskov Jensen ***@***.***>
Envoyé : Saturday, May 1, 2021 6:11:56 PM
À : ErikEJ/EFCorePowerTools ***@***.***>
Cc : Olivier MATROT ***@***.***>; Mention ***@***.***>
Objet : Re: [ErikEJ/EFCorePowerTools] Edmx -> Context/Model (#939)


I think domain modelling is beyond the scope of this tool.

**Comment by ErikEJ** [comment]
>> core component that is used during scaffolding with the model builder fluent API.

Agree, but that is done in order to match the physical database table correctly.

Name changes can be done with the renaming support...

**Comment by boone34** [comment]
Thanks for looking into this. Some comments:

1. @omatrot mentioned that the _DispatchCustomer_ conceptual entity was designed by hand. This is not entirely the case. The EF6 designer will import views and create conceptual entities for them. However in general you need to  manually specify:

The primary key (usually views have no primary key so EF assigns all applicable columns as keys).
Assign appropriate CRUD functions.
Create any desired associations/relationships.

This is in addition to any cleanup/renaming you desire.

2. In terms of _scope of this tool_. Seems to me that this depends on what the purpose of the tool is. If the purpose is to reverse engineer a database then it would be out of scope. If its purpose is too facilitate migration from EF6 to EF Core I would say it is very much in scope. What is used in EF6 and EF Core models is the conceptual entity model, not the storage model/database schema.

**Comment by ErikEJ** [comment]
The scope of this tool is to reverse engineer an existing database.

**Comment by ErikEJ** [comment]
I am considering removing this feature, un-listing the current 2 NuGet packages and then @omatrot can publish and maintain the 2 NuGet packages under his own name.

**Comment by omatrot** [comment]
I was also thinking of the right way to provide the best scaffolding experience starting from an EDMX file.

I agree that this does not fit best in here, and honestly a simple CLI would be enough.

@ErikEJ What do you think? How can I start from here?

**Comment by ErikEJ** [comment]
I would start with the two potential NuGet packages, they provide a simple port of the tables used in an EDMX to an EF Core DbContext.

I would steal the command line tool from this repo, and add code to for example populate the Renaming objects based on what is defined in the EDMX.

**Comment by omatrot** [comment]
> I would start with the two potential NuGet packages, they provide a simple port of the tables used in an EDMX to an EF Core DbContext.
> 
> I would steal the command line tool from this repo, and add code to for example populate the Renaming objects based on what is defined in the EDMX.

FYI @ErikEJ https://github.com/omatrot/EFCoreEDMXPowerTools/blob/master/README.md
