### ISSUE TITLE
Reverse Engineer error when choose database connection

### ISSUE THREAD

**Issue by mkidsc1603** [ErikEJ/EFCorePowerTools#940]
VS 2019 throw exception window when choose database connection

### Steps to reproduce
Step1 Open Reverse Enginner
Step2 Choose database and click ok => throw exception!

### Enviroment
- EF Core Power Tools version: 2.5.268.0
- Database engine: MSSQL 2017
- Visual Studio version: 2019 - 16.9.4

### Reference
Here is  message it throw:
![image](https://user-images.githubusercontent.com/17141905/116189046-f4bf3900-a75a-11eb-997f-6694aef225c7.png)

It's weird that work fine before today, but I update the latest version of  EFCorePowerTool and Visual stdio 2019
thanks in advance

**Comment by ErikEJ** [comment]
Thanks for trying out the daily build.

In your %temp% folder, navigate to the efreveng... folder and try to run:

`efreveng 3 "My connection string"`

**Comment by mkidsc1603** [comment]
@ErikEJ 

Execute result :
![image](https://user-images.githubusercontent.com/17141905/116194388-5be0eb80-a763-11eb-9b72-115cec1fe48c.png)

Is the problem related to some package's  version?
thks!

**Comment by ErikEJ** [comment]
Possibly just a bug in the latest daily.

I will investigate

**Comment by ErikEJ** [comment]
I cannot repro, but have updated the command line tools in the latest daily build, please try that.

**Comment by mkidsc1603** [comment]
How can I update the command line tools?

**Comment by ErikEJ** [comment]
Get the latest daily!

**Comment by mkidsc1603** [comment]
I reinstall EFCorePowerTools from VS extension. still have the error message 😢

**Comment by ErikEJ** [comment]
So what version are you using now?

Maybe your dotnet installation is broken - I cannot replicate.

Try on another machine to investigate, perhaps?

**Comment by mkidsc1603** [comment]
Version : 2.5.628.0

OK, I will try on another.

**Comment by ErikEJ** [comment]
Why not try the official release version from Marketplace?

**Comment by mkidsc1603** [comment]
I thinks the reason is location, so it not update the extension immediately.
I change to version 2.5.612.0 , it work perfect !!

thank you so much! 😄

**Comment by Varorbc** [comment]
@ErikEJ I have the same problem

**Comment by ErikEJ** [comment]
@Varorbc also with .612?

**Comment by ErikEJ** [comment]
I will do some more testing with the latest daily, I did make some changes in this area.

**Comment by Varorbc** [comment]
![image](https://user-images.githubusercontent.com/5714438/116218697-5ee8d580-a77d-11eb-9e46-5f67f810ed62.png)
yes,If I use efcore 3, everything works fine

**Comment by ErikEJ** [comment]
Maybe I broke the file cleanup code...

**Comment by ErikEJ** [comment]
Fixed in latest daily - thank you both for using the daily builds!

It was a bad reference that should have been updated.

**Comment by Varorbc** [comment]
@mkidsc1603 您能幫忙做下這個軟件的繁體中文翻譯工作嗎？

**Comment by mkidsc1603** [comment]
@Varorbc 可以來研究看看
