### ISSUE TITLE
some suggestions for migration tools

### ISSUE THREAD

**Issue by Varorbc** [ErikEJ/EFCorePowerTools#942]
- Migration management, such as add, remove
- Generate migration script, support from starting migration to target migration
- update database
	- support from starting migration to target migration 
	- Support to view and modify the update script

**Comment by CaiusJard** [comment]
Here's my +1 vote for migration remove :)

**Comment by ErikEJ** [comment]
PRs accepted 😉

**Comment by ErikEJ** [comment]
Closing and moving to Backlog milestone

**Comment by ErikEJ** [comment]
I have decided to remove the Migration tool and refer users to the built in VS tooling
