### ISSUE TITLE
recommended to move auto-generated tags to code template files 

### ISSUE THREAD

**Issue by Varorbc** [ErikEJ/EFCorePowerTools#943]

**Comment by ErikEJ** [comment]
Are you referring to the Handlebars third party templates?

**Comment by Varorbc** [comment]
yes

**Comment by ErikEJ** [comment]
The code template files come from this repo, please create a suggestion there: https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars

**Comment by Varorbc** [comment]
Thank you, so after using the code template file, you should not write the header information again, it will cause duplicate tags

**Comment by ErikEJ** [comment]
The tool does not use templates, unless you enable Handlebars.

So could you clarify what you are asking for?

**Comment by Varorbc** [comment]
I mean, I enabled Handlebars and added tags to the template, and the generated code has duplicate tags

**Comment by Varorbc** [comment]
My suggestion is that if the user enables Handlebars, the generated code should be exactly the same as the template, and there should be no additional code

**Comment by ErikEJ** [comment]
It is hard for the tool to tell if the generated code was processed by Handlebars or not.

**Comment by Varorbc** [comment]
https://github.com/ErikEJ/EFCorePowerTools/commit/5855cdc8ce8c7f84f55b40d3785afa05975d7846
