### ISSUE TITLE
The naming in reverse engineering should be single choice 

### ISSUE THREAD

**Issue by Varorbc** [ErikEJ/EFCorePowerTools#944]

**Comment by ErikEJ** [comment]
Not sure what you mean.

Share a screenshot perhaps?

**Comment by Varorbc** [comment]
![image](https://user-images.githubusercontent.com/5714438/116370040-966a8700-a83c-11eb-8c2b-cf66065503c2.png)
It should be a radio button, not a check box

**Comment by ErikEJ** [comment]
You can actually combine the two with EF Core 5!

**Comment by Varorbc** [comment]
Sorry, I missed that
