### ISSUE TITLE
Option to disable opening DbContext file in VS after reverse engineering

### ISSUE THREAD

**Issue by GearTheWorld** [ErikEJ/EFCorePowerTools#947]
### Describe what is not working as expected.
More like a suggestion but I don't know where to ask.  Having an option to uncheck in order to avoid EFCPT to open ApplicationDbContext after generation is complete

### Steps to reproduce
Reverse Engineer and when it's finished, ApplicationDbContext is open and each time we have to close it

### Further technical details
Version 2.5.612.0

SQLite ADO.NET Provider included: 1.0.109.0
SQLite EF6 DbProvider in GAC - No

System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes

### Database engine: (SQlite, SQL Compact, SQL Server, Postgres)
SQL 2016

### Visual Studio version: (e.g. Visual Studio 2019 16.8)
Visual Studio 2019 Version 16.9.4

**Comment by ErikEJ** [comment]
Why is that an issue?

**Comment by GearTheWorld** [comment]
As I said since I don't know where to post a suggestion I post in Issue.  Tell me where I can suggest feature.
The problem is that opening this file each time which doesn't need to be modify at all have to be close every time.  Why you open this file each time the generation is completed ?

**Comment by ErikEJ** [comment]
Oh, you are posting in the right place. I am just trying to understand what the requirement is.

**Comment by GearTheWorld** [comment]
Here's a video

https://user-images.githubusercontent.com/8614008/116523466-76040080-a900-11eb-9a58-3632b9656e59.mp4

**Comment by ErikEJ** [comment]
Thanks, I got the message already!

**Comment by GearTheWorld** [comment]
I'm not too familiar with GitHub in regards to the entire process until the version is available

I downloaded the Daily build 2.5.634 and I don't see the option.
**Add option to disable opening generated DbContext #947**

Maybe I'm too fast and have to wait?

**Comment by ErikEJ** [comment]
It is under Tools, Options, EF Core Power Tools...

**Comment by ErikEJ** [comment]
Did you find it?

**Comment by GearTheWorld** [comment]
Oh all right yes I found it thank you very much !
