### ISSUE TITLE
efpt.renaming.json file is overwritten after Reverse Engineer

### ISSUE THREAD

**Issue by melihsen** [ErikEJ/EFCorePowerTools#948]
I try to rename navigation property names via efpt.renaming.json file. I use this sample json for efpt.renaming.json file:

`[
  {
    "Navigations": [
      {
        "Name": "JobNavigation",
        "NewName": "Product"
      }
    ],
    "SchemaName": "dbo",
    "Tables": [
      {
        "Columns": [
          {
            "Name": "Picture",
            "NewName": "Image"
          }
        ],
        "Name": "Categories",
        "NewName": "MyCategories"
      }
    ],
    "UseSchemaName": false
  },
  {
    "SchemaName": "dev",
    "UseSchemaName": true
  },
  {
    "SchemaName": "test",
    "UseSchemaName": true
  },
  {
    "SchemaName": "prod",
    "UseSchemaName": true
  }
]`

After "Reverse Engineer" process is completed, efpt.renaming.json file is overwritten and "Navigations" property in json file is removed. Saved last content of json file is:

`[
   {
      "SchemaName": "dbo",
      "Tables": [
         {
            "Columns": [
               {
                  "Name": "Picture",
                  "NewName": "Image"
               }
            ],
            "Name": "Categories",
            "NewName": "MyCategories"
         }
      ],
      "UseSchemaName": false
   },
   {
      "SchemaName": "dev",
      "UseSchemaName": true
   },
   {
      "SchemaName": "test",
      "UseSchemaName": true
   },
   {
      "SchemaName": "prod",
      "UseSchemaName": true
   }
]`

**Comment by ErikEJ** [comment]
Your json is not correct, thats why it does not roundtrip

**Comment by melihsen** [comment]
@ErikEJ I get this sample json from this commit:

[https://github.com/ErikEJ/EFCorePowerTools/commit/45419ec49d22c47c6bfd2e6998d01e9a459db6f0#diff-61e157bf117d2c7aae65b26202c7288143385649c9430f40b6fddd3707cd407b](url)

Is it changed or updated?

**Comment by ErikEJ** [comment]
Yes, wrong format, as mentioned in the release notes: https://github.com/ErikEJ/EFCorePowerTools/wiki/Release-notes#25513-february-14-2021 - I will add a link to the docs!

**Comment by ErikEJ** [comment]
I have updated the docs: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#custom-renaming-with-efptrenamingjson

**Comment by melihsen** [comment]
@ErikEJ 
I got new json from the document. I think there is a bug in navigation remaming but I am not sure. So I did'nt open new issue.

When Table Name is the same in json <Name = NewName>, navigation settings under this table are ignored.

For example, I want to rename "JobNavigation" >> Product

This json is not work (Navigation renaming is ignored, table name -Job- is the same):
`[
   {
      "SchemaName": "dbo",
      "Tables": [
         {
            "Columns": [ ],
            "Name": "Job",
            "Navigations": [
               {
                  "Name": "JobNavigation",
                  "NewName": "Product"
               }
            ],
            "NewName": "Job"
         }
      ],
      "UseSchemaName": false
   },
   {
      "SchemaName": "dev",
      "UseSchemaName": true
   },
   {
      "SchemaName": "test",
      "UseSchemaName": true
   },
   {
      "SchemaName": "prod",
      "UseSchemaName": true
   }
]`

This json works (new table name is different):
`[
   {
      "SchemaName": "dbo",
      "Tables": [
         {
            "Columns": [ ],
            "Name": "Job",
            "Navigations": [
               {
                  "Name": "JobNavigation",
                  "NewName": "Product"
               }
            ],
            "NewName": "Job2"
         }
      ],
      "UseSchemaName": false
   },
   {
      "SchemaName": "dev",
      "UseSchemaName": true
   },
   {
      "SchemaName": "test",
      "UseSchemaName": true
   },
   {
      "SchemaName": "prod",
      "UseSchemaName": true
   }
]`

**Comment by ErikEJ** [comment]
Please share a create table script, and I will have a look.

Remember that this feature is highly experimental, and could be removed.

**Comment by melihsen** [comment]
@ErikEJ 
This feature is very useful and practical. I think it is not a big problem to remove it.

To help you, I prepared sample Asp.Net Core 5 MVC project which includes two epft.renaming.json (active current does not work) and sample MS SQL Db which name is "TestDb". DB tables seems nonsense but it is only sample. 

Project:
[WebApplicationTest.zip](https://github.com/ErikEJ/EFCorePowerTools/files/6409692/WebApplicationTest.zip)

DB SQL Dump
[TestDbSqlDump.zip](https://github.com/ErikEJ/EFCorePowerTools/files/6409694/TestDbSqlDump.zip)

Thank you for all

**Comment by ErikEJ** [comment]
As I wrote, this feature is problematic in it's current state!

This file works!

```
[
  {
    "SchemaName": "dbo",
    "Tables": [
      {
        "Columns": [],
        "Name": "Job",
        "Navigations": [
          {
            **"Name": "Job",**
            "NewName": "Product"
          }
        ],
        "NewName": "Job"
      }
    ],
    "UseSchemaName": false
  }
```
This issue is that the "Navigation" postfix is added after code in EF Core Power Tools process the navigations.

**Comment by MelihSen** [comment]
@ErikEJ 
I have corrected json file and it is OK. Thank you very much for your help

**Comment by ErikEJ** [comment]
I will put this feature on hold for now, until someone comes up with a working solution.
