### ISSUE TITLE
Suggestion EF Core 5 New Many-To-Many Relationship Feature for Reverse Engineer

### ISSUE THREAD

**Issue by MelihSen** [ErikEJ/EFCorePowerTools#953]
It is only suggestion or enhancement

EF Core 5 handles many-to-many relationships hiding and skipping relation table in Linq query. It is mentioned in this video:
[https://youtu.be/BIImyq8qaD4?t=1114](https://youtu.be/BIImyq8qaD4?t=1114)

For example there are users and groups. And they are connected with many-to-many relationship via Membership table.

`modelBuilder.Entity<User>()
.HasMany(u => u.Groups)
.WithMany(g => g.Users)
.UsingEntity<Membership>(
    j=> j.HasOne(m => m.Group).WithMany(g => g.Memberships),
    j=> j.HasOne(m => m.User).WithMany(u => u.Memberships));
`
Linq query can be here without using Membership table

`var users = await db.Users.Where(w => w.Groups.Any(g => g.Name == "Movies")`

**Comment by ErikEJ** [comment]
Duplicate of #501 ?

**Comment by MelihSen** [comment]
Sorry, I missed it. I closed.
