### ISSUE TITLE
Reverse engineering SPROC does not used specified name

### ISSUE THREAD

**Issue by MisinformedDNA** [ErikEJ/EFCorePowerTools#959]
When I am choosing database objects to reverse engineer, I can change the name of a stored procedure, but it has no affect on the generated output.

### Steps to reproduce

1. Right-click `efpt.config.json` and click on EF Core Power Tools - Edit"
2. Choose a DB and click OK.
3. Expand the stored procedures and rename one.
4. Click though until code is generated.

**EXPECTED:**

The new, renamed name is used

**ACTUAL:**

The rename is completely ignored.

### Further technical details
EF Core Power Tools version: 2.5.636

Database engine: SQL Server

Visual Studio version: Visual Studio 2019 16.9.4

**efpt.renaming.json**

```json
[
   {
      "ColumnPatternReplaceWith": "Id",
      "ColumnRegexPattern": "ID$",
      "SchemaName": "dbo",
      "TablePatternReplaceWith": "$1",
      "TableRegexPattern": "^[t|v]_(.+)",
      "Tables": [
         {
            "Columns": [ ],
            "Name": "t_Location",
            "NewName": "LocationDetail"
         },
         {
            "Columns": [ ],
            "Name": "r_OrderSearchSales",
            "NewName": "OrderSearchSales2"
         }
      ],
      "UseSchemaName": false
   }
]
```

Generated class and method:

```csharp
public virtual async Task<r_OrderSearchSalesResult[]> r_OrderSearchSalesAsync
```

**Comment by ErikEJ** [comment]
Renaming of stored procedure has not been implemented, but agree it is a bug that the UI allows it.

@sm15455 I will investigate if renaming of stored procedures is feasible.

**Comment by ErikEJ** [comment]
I plan to enable renaming of stored procedures.

**Comment by ErikEJ** [comment]
Fixed in latest daily build
