### ISSUE TITLE
The EfCorePowerToolsPackage package did not load correctly

### ISSUE THREAD

**Issue by lwheeler** [ErikEJ/EFCorePowerTools#961]
Describe what is not working as expected.
This extension has been working fine for months until I updated to the latest version and now I get this error. I uninstalled this version and installed version 2.5.454 and I get the same error now so something happened during the upgrade. 

### Steps to reproduce
Include a complete description that I can redo to reproduce the issue.
I can create a new project and when I try to reverse engineer I get the error.

### Further technical details
I am using the latest VS 2019.

The full error is:

SetSite failed for package [EFCorePowerToolsPackage]Source: 'EFCorePowerTools' Description: Could not load file or assembly 'Microsoft.VisualStudio.Threading, Version=16.9.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Threading, Version=16.9.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. File name: 'Microsoft.VisualStudio.Threading, Version=16.9.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'at EFCorePowerTools.EFCorePowerToolsPackage.InitializeAsync(CancellationToken cancellationToken, IProgress`1 progress)at Microsoft.VisualStudio.Shell.AsyncPackage.<>c__DisplayClass20_0.<<Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize>b__1>d.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)at Microsoft.VisualStudio.Threading.JoinableTask.<JoinAsync>d__68.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)at Microsoft.VisualStudio.Services.VsTask.GetResult() WRN: Assembly binding logging is turned OFF. To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1. Note: There is some performance penalty associated with assembly bind failure logging. To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

**Comment by ErikEJ** [comment]
See #960 - are you running VS 16.9?

**Comment by lwheeler** [comment]
Yes 16.9.1

**Comment by ErikEJ** [comment]
If you downgraded to .454, I doubt you succeeded in doing that.

Are you subscribing to updates from VSIX gallery?

**Comment by lwheeler** [comment]
Oh wait. I have 2 machines and the one with the error is 16.8.3. I will upgrade.

**Comment by ErikEJ** [comment]
I have bumped the VS requirement to be 16.9

**Comment by lwheeler** [comment]
It works now! Sorry for the confusion.

**Comment by ErikEJ** [comment]
Sorry for the disruption, I have made the 16.9 requirement explicit in the package now
