### ISSUE TITLE
"A Task Was Canceled" with Stored Procedures

### ISSUE THREAD

**Issue by blogcraft** [ErikEJ/EFCorePowerTools#966]
Describe what is not working as expected.

### Steps to reproduce
create a procedure that only returns a string

`CREATE PROCEDURE test AS SELECT 'text' AS salida`

Using reverse engineer add the procedure to the project.

Execute the procedure:
`var value = await _context.Procedures.testAsync();`

also tried with
`var value = await _context.Procedures.testAsync(cancellationToken: System.Threading.CancellationToken.None);`

An Exception is thrown with a message "A task Was Canceled".

### Further technical details
EF Core Power Tools version: 2.5.636.0

Database engine: (SQL Server

Visual Studio version: Visual Studio 2019 16.9.4

**Comment by blogcraft** [comment]
Also tried:
```
using (var db = _context)
{
    var value = await db.GetProcedures().testAsync();
}
```
Same exception.

**Comment by blogcraft** [comment]
Now this is weird. Without changing the code, I just restarted the app, executed `testAsync` again ant I get another error.

"Invalid attempt to call ReadAsync when reader is closed".

**Comment by ErikEJ** [comment]
Please provide a repro project in order for me to assist, I have not heard about this before.
