### ISSUE TITLE
Nullable References Foreign Keys inverted behavior

### ISSUE THREAD

**Issue by NickNiebling** [ErikEJ/EFCorePowerTools#968]
Thanks for taking the time to add the experimental feature "Nullable References". We have been exploring this and found one "major" issue - at least if you have any FK (Foreign Key, red)

When using experimental feature "Nullable References", all FKs seems to be mapped incorrectly as the opposite of "null" vs "not null".

### Steps to reproduce

1. Create 3 tables, where 1 table has as nullable FK and a not null FK to 2 other tables - e.g. using this MS SQL script: [EFCorePowerTools-NullableReference-Issue-SQL.txt](https://github.com/ErikEJ/EFCorePowerTools/files/6439613/EFCorePowerTools-NullableReference-Issue-SQL.txt)

2. Run EFCorePowerTools with nullable references (experimental feature) set to true
3. See generated MainTable model below

```
public class MainTable {
    public int MainTableId { get; set; }
    public int FooTableId { get; set; }
    public int? BarTableId { get; set; }

     public virtual FooTable? FooTable { get; set; }
     public virtual BarTable BarTable { get; set; } = default!;
}
```

#### Expected result

```
public class MainTable {
    public int MainTableId { get; set; }
    public int FooTableId { get; set; }
    public int? BarTableId { get; set; }

     public virtual FooTable FooTable { get; set; } = default!;
     public virtual BarTable? BarTable { get; set; }
}
```

It could be debated if expected result should have more changes than outlined above; to handle "not null reference" (e.g. FooTable above), as it might be better to throw exception when get accessor is used prior to proper initialization or lazy loading - or even in the case where initialization/lazy loading happened, but the FK lookup didn't get a hit (in case of no SQL constraint and FK is referencing a deleted entity). This point was also mentioned by @roji in [review comment](https://github.com/ErikEJ/EFCorePowerTools/pull/716#pullrequestreview-573333339) when nullable references experimental feature was introduced. The issue posted here however is not focusing on that - only on the fact that we at least need a simple change to invert the current behavior of nullable references, to make the feature useable with FK as well.

### Further technical details
EF Core Power Tools version: 2.5.636

Database engine: MS SQL

Visual Studio version: 2019 16.9.4

## Suggested change
I'll briefly outline suggested change below - and will try to make a PR later.

In 3 files:
`src/GUI/RevEng.Core.XXX/CommentCSharpEntityTypeGenerator.cs `

We currently have:
```
                        if (navigation.ForeignKey?.IsRequired == true)
                        {
                            nullableAnnotation = "?";
                        }
                        else
                        {
                            defaultAnnotation = $" = default!;";
                        }
```

And to invert logic we could simple change to:
```
                        if (navigation.ForeignKey?.IsRequired == true)
                        {
                            defaultAnnotation = $" = default!;";
                        }
                        else
                        {
                            nullableAnnotation = "?";
                        }
```

I'm not fully aware of how to best handle ForeignKey being null (or when that's even the case). It seems like what we need is the inverted behavior, but maybe below is actually the better option? 🤷‍♀️
```
                        if (navigation.ForeignKey?.IsRequired == false)
                        {
                            nullableAnnotation = "?";
                        }
                        else
                        {
                            defaultAnnotation = $" = default!;";
                        }
```

**Comment by ErikEJ** [comment]
Does this PR fix the issue? https://github.com/ErikEJ/EFCorePowerTools/pull/967

**Comment by cceuroform** [comment]
Yes it does.

**Comment by euroform-pa** [comment]
@NickNiebling Thanks for explaining the issue and suggesting changes to fix it. 
@ErikEJ I've tried the PR #967 and it does fixes above issue with nullable FKs.

Thanks 👍
