### ISSUE TITLE
Not working properly

### ISSUE THREAD

**Issue by TheForgetTime** [ErikEJ/EFCorePowerTools#97]
Only `reverse engineer`, `view database schema as Graph` and `Add AsDgml() method` are normal.

Migrations Tools(preview):
![default](https://user-images.githubusercontent.com/26455845/46253956-365fa880-c4ba-11e8-9980-8e285b07de8d.png)

`Add DbContext Model Diagram`、`ViewDbContext Model DDL SQL` and `View DbContext Model as DebugView` :
Parameter error. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))

### Further technical details
Version 1.0.653.0

SQL Server Compact 4.0 in GAC - No
SQL Server Compact 4.0 DbProvider - No

SQL Server Compact 4.0 DDEX provider - No
SQL Server Compact 4.0 Simple DDEX provider - Yes

SQLite ADO.NET Provider included: 1.0.107.0
SQLite EF6 DbProvider in GAC - No

System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes

EF Core Power Tools version: (1.0.653.0)

Database engine: (SQL Server)

Visual Studio version: (Visual Studio 2017 15.8.5)

**Comment by ErikEJ** [comment]
Have you tried the latest daily build?

**Comment by TheForgetTime** [comment]
Yes, this is

**Comment by ErikEJ** [comment]
Wonder if it is the non-latin characters? I will try to repro later today

**Comment by TheForgetTime** [comment]
The latest build is available, 
but when I remove the connection string from the DbContext class I get the following error:

No Valid DbContext classes found in the current project

**Comment by ErikEJ** [comment]
@TheForgetTime That is by design, EF Core cannot create a DbContext without it.
