### ISSUE TITLE
Feature request: Extract data from selected tables as seeding code

### ISSUE THREAD

**Issue by guffy1234** [ErikEJ/EFCorePowerTools#971]
Hi

It would be nice to have an abiltity to extract data of selected distionary tables as HasData code or InsertData equivalent.

Thanks

**Comment by ErikEJ** [comment]
Interesting, could you share an example of how the code could look like?

**Comment by guffy1234** [comment]
these are examples how to seed on database creation or with a migration:
https://www.tektutorialshub.com/entity-framework-core/ef-core-data-seeding/
https://dejanstojanovic.net/aspnet/2020/july/seeding-data-with-entity-framework-core-using-migrations/

these just FYI:
https://levelup.gitconnected.com/easy-database-seeding-in-net-core-applications-f8bcc7a15112
https://dejanstojanovic.net/aspnet/2020/september/seeding-data-in-ef-core-using-sql-scripts/

**Comment by ErikEJ** [comment]
Closing and moving to Backlog milestone
