### ISSUE TITLE
bit(ulong) type generate error on mysql?

### ISSUE THREAD

**Issue by 246850** [ErikEJ/EFCorePowerTools#974]
**why mysql column type (bit)  ? csharp entity property type(ulong) ?**

### table 
CREATE TABLE `demo` (
	`Id` INT(10,0) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(50) NOT NULL COLLATE 'utf8mb4_general_ci',
	**`deleted` BIT(1) NOT NULL,**
	PRIMARY KEY (`Id`) USING BTREE
)
### entity
public partial class Demo
    {
        public int Id { get; set; }
        public string Name { get; set; }
        **public ulong Deleted { get; set; }**
    }
### Visual Studio version: (e.g. Visual Studio 2019 16.8)

_Please help me ! 3q_

**Comment by ErikEJ** [comment]
Suggest you ask in the MySQL support forum

**Comment by ErikEJ** [comment]
Or try the Pomelo provider

**Comment by Flithor** [comment]
Solution here: https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/917
