### ISSUE TITLE
'EFCorePowerToolsPackage' package did not load correctly

### ISSUE THREAD

**Issue by AnthonySzy-dot** [ErikEJ/EFCorePowerTools#975]
Hello, I cannot access to EF Core Power Tools options (Reverse Engineer,  Migration Tool etc.)
When I try, a popup display this warning : 

![image](https://user-images.githubusercontent.com/84072320/117952946-f1f54400-b315-11eb-82b6-d4c4438a0687.png)

there's my ActivityLog.xml

[ActivityLog.txt](https://github.com/ErikEJ/EFCorePowerTools/files/6465167/ActivityLog.txt)

`<?xml version="1.0" encoding="utf-16"?>
<?xml-stylesheet type="text/xsl" href="ActivityLog.xsl"?>
<activity>  
  <entry>
    <record>3138</record>
    <time>2021/05/12 09:28:02.959</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing Fusion (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3139</record>
    <time>2021/05/12 09:28:02.959</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing NGen (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3140</record>
    <time>2021/05/12 09:28:02.959</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing NGenQueue (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3141</record>
    <time>2021/05/12 09:28:02.959</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing policy (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3142</record>
    <time>2021/05/12 09:28:02.959</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing Security (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3143</record>
    <time>2021/05/12 09:28:02.959</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing Windows Presentation Foundation (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3144</record>
    <time>2021/05/12 09:28:02.960</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing Advertised (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3145</record>
    <time>2021/05/12 09:28:02.960</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing AssemblyFolders (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3146</record>
    <time>2021/05/12 09:28:02.960</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing Fusion (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3147</record>
    <time>2021/05/12 09:28:02.960</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing NGen (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3148</record>
    <time>2021/05/12 09:28:02.960</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing NGenQueue (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3149</record>
    <time>2021/05/12 09:28:02.960</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing policy (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3150</record>
    <time>2021/05/12 09:28:02.960</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing Security (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3151</record>
    <time>2021/05/12 09:28:02.960</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing Windows Presentation Foundation (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3152</record>
    <time>2021/05/12 09:28:02.960</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing Advertised (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3153</record>
    <time>2021/05/12 09:28:02.960</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing AssemblyFolders (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3154</record>
    <time>2021/05/12 09:28:02.960</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing Fusion (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3155</record>
    <time>2021/05/12 09:28:02.960</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing NGen (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3156</record>
    <time>2021/05/12 09:28:02.960</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing NGenQueue (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3157</record>
    <time>2021/05/12 09:28:02.960</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing policy (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3158</record>
    <time>2021/05/12 09:28:02.960</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing Security (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3159</record>
    <time>2021/05/12 09:28:02.960</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing Windows Presentation Foundation (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3160</record>
    <time>2021/05/12 09:28:02.960</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing Advertised (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3161</record>
    <time>2021/05/12 09:28:02.960</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing AssemblyFolders (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3162</record>
    <time>2021/05/12 09:28:02.960</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing Fusion (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3163</record>
    <time>2021/05/12 09:28:02.960</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing NGen (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3164</record>
    <time>2021/05/12 09:28:02.961</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing NGenQueue (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3165</record>
    <time>2021/05/12 09:28:02.961</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing policy (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3166</record>
    <time>2021/05/12 09:28:02.961</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing Security (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3167</record>
    <time>2021/05/12 09:28:02.961</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing Windows Presentation Foundation (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3168</record>
    <time>2021/05/12 09:28:02.961</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing Advertised (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3169</record>
    <time>2021/05/12 09:28:02.961</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing AssemblyFolders (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3170</record>
    <time>2021/05/12 09:28:02.961</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing Fusion (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3171</record>
    <time>2021/05/12 09:28:02.961</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing NGen (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3172</record>
    <time>2021/05/12 09:28:02.961</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing NGenQueue (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3173</record>
    <time>2021/05/12 09:28:02.961</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing policy (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3174</record>
    <time>2021/05/12 09:28:02.961</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing Security (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3175</record>
    <time>2021/05/12 09:28:02.961</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing Windows Presentation Foundation (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3176</record>
    <time>2021/05/12 09:28:02.961</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing Advertised (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3177</record>
    <time>2021/05/12 09:28:02.961</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing AssemblyFolders (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3178</record>
    <time>2021/05/12 09:28:02.961</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing Fusion (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3179</record>
    <time>2021/05/12 09:28:02.961</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing NGen (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3180</record>
    <time>2021/05/12 09:28:02.961</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing NGenQueue (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3181</record>
    <time>2021/05/12 09:28:02.961</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing policy (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3182</record>
    <time>2021/05/12 09:28:02.961</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing Security (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3183</record>
    <time>2021/05/12 09:28:02.961</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing Windows Presentation Foundation (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3184</record>
    <time>2021/05/12 09:28:02.961</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing Advertised (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3185</record>
    <time>2021/05/12 09:28:02.961</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing AssemblyFolders (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3186</record>
    <time>2021/05/12 09:28:02.961</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing Fusion (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3187</record>
    <time>2021/05/12 09:28:02.961</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing NGen (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3188</record>
    <time>2021/05/12 09:28:02.961</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing NGenQueue (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3189</record>
    <time>2021/05/12 09:28:02.961</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing policy (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3190</record>
    <time>2021/05/12 09:28:02.961</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing Security (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3191</record>
    <time>2021/05/12 09:28:02.961</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing Windows Presentation Foundation (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3192</record>
    <time>2021/05/12 09:28:02.962</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing Advertised (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3193</record>
    <time>2021/05/12 09:28:02.962</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing AssemblyFolders (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3194</record>
    <time>2021/05/12 09:28:02.962</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing Fusion (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3195</record>
    <time>2021/05/12 09:28:02.962</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing NGen (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3196</record>
    <time>2021/05/12 09:28:02.962</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing NGenQueue (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3197</record>
    <time>2021/05/12 09:28:02.962</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing policy (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3198</record>
    <time>2021/05/12 09:28:02.962</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing Security (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3199</record>
    <time>2021/05/12 09:28:02.962</time>
    <type>Error</type>
    <source>ToolboxControlsInstaller</source>
    <description>Exception parsing Windows Presentation Foundation (under HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework) as a version</description>
  </entry>
  <entry>
    <record>3200</record>
    <time>2021/05/12 09:28:03.425</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Done loading new toolbox content, total time = 7141 ms</description>
  </entry>
  <entry>
    <record>3201</record>
    <time>2021/05/12 09:28:07.034</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [VSPackage]</description>
    <guid>{1A4EFADE-F6B2-4490-A2EF-21D5F3D1C8E0}</guid>
  </entry>
  <entry>
    <record>3202</record>
    <time>2021/05/12 09:28:08.432</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>End package load [VSPackage]</description>
    <guid>{1A4EFADE-F6B2-4490-A2EF-21D5F3D1C8E0}</guid>
  </entry>
  <entry>
    <record>3203</record>
    <time>2021/05/12 09:28:08.476</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [ManagedProjectSystemPackage]</description>
    <guid>{860A27C0-B665-47F3-BC12-637E16A1050A}</guid>
  </entry>
  <entry>
    <record>3204</record>
    <time>2021/05/12 09:28:08.610</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>End package load [ManagedProjectSystemPackage]</description>
    <guid>{860A27C0-B665-47F3-BC12-637E16A1050A}</guid>
  </entry>
  <entry>
    <record>3205</record>
    <time>2021/05/12 09:28:08.616</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [TestWindowPackage]</description>
    <guid>{BFC24BF4-B994-4757-BCDC-1D5D2768BF29}</guid>
  </entry>
  <entry>
    <record>3206</record>
    <time>2021/05/12 09:28:08.689</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>End package load [TestWindowPackage]</description>
    <guid>{BFC24BF4-B994-4757-BCDC-1D5D2768BF29}</guid>
  </entry>
  <entry>
    <record>3207</record>
    <time>2021/05/12 09:28:08.726</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [NpgsqlVSPackage]</description>
    <guid>{EF991DC4-3119-4ED6-BDB3-C160CA562560}</guid>
  </entry>
  <entry>
    <record>3208</record>
    <time>2021/05/12 09:28:08.735</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>End package load [NpgsqlVSPackage]</description>
    <guid>{EF991DC4-3119-4ED6-BDB3-C160CA562560}</guid>
  </entry>
  <entry>
    <record>3209</record>
    <time>2021/05/12 09:28:08.914</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [EFCorePowerToolsPackage]</description>
    <guid>{F4C4712C-CEAE-4803-8E52-0E2049D5DE9F}</guid>
  </entry>
  <entry>
    <record>3210</record>
    <time>2021/05/12 09:28:08.984</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [EFCorePowerToolsPackage]Source: &apos;EFCorePowerTools&apos; Description: Impossible de charger le fichier ou l&apos;assembly &apos;Microsoft.VisualStudio.Threading, Version=16.9.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; ou une de ses d&#x00E9;pendances. Le fichier sp&#x00E9;cifi&#x00E9; est introuvable.&#x000D;&#x000A;System.IO.FileNotFoundException: Impossible de charger le fichier ou l&apos;assembly &apos;Microsoft.VisualStudio.Threading, Version=16.9.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; ou une de ses d&#x00E9;pendances. Le fichier sp&#x00E9;cifi&#x00E9; est introuvable.&#x000D;&#x000A;Nom de fichier&#x00A0;: &apos;Microsoft.VisualStudio.Threading, Version=16.9.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos;&#x000D;&#x000A;   &#x00E0; EFCorePowerTools.EFCorePowerToolsPackage.InitializeAsync(CancellationToken cancellationToken, IProgress`1 progress)&#x000D;&#x000A;   &#x00E0; Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass20_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()&#x000D;&#x000A;--- Fin de la trace de la pile &#x00E0; partir de l&apos;emplacement pr&#x00E9;c&#x00E9;dent au niveau duquel l&apos;exception a &#x00E9;t&#x00E9; lev&#x00E9;e ---&#x000D;&#x000A;   &#x00E0; System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   &#x00E0; System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   &#x00E0; Microsoft.VisualStudio.Threading.JoinableTask.&lt;JoinAsync&gt;d__68.MoveNext()&#x000D;&#x000A;--- Fin de la trace de la pile &#x00E0; partir de l&apos;emplacement pr&#x00E9;c&#x00E9;dent au niveau duquel l&apos;exception a &#x00E9;t&#x00E9; lev&#x00E9;e ---&#x000D;&#x000A;   &#x00E0; System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   &#x00E0; Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)&#x000D;&#x000A;   &#x00E0; Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)&#x000D;&#x000A;   &#x00E0; Microsoft.VisualStudio.Services.VsTask.GetResult()&#x000D;&#x000A;&#x000D;&#x000A;AVT&#x00A0;: la journalisation de liaison d&apos;assembly est d&#x00E9;sactiv&#x00E9;e.&#x000D;&#x000A;Pour activer la journalisation des &#x00E9;checs de liaison d&apos;assembly, attribuez la valeur 1 &#x00E0; la valeur de Registre [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD).&#x000D;&#x000A;Remarque&#x00A0;: une certaine perte de performance est associ&#x00E9;e &#x00E0; l&apos;enregistrement dans le journal des &#x00E9;checs de liaison d&apos;assembly.&#x000D;&#x000A;Pour d&#x00E9;sactiver cette fonctionnalit&#x00E9;, supprimez la valeur de Registre [HKLM\Software\Microsoft\Fusion!EnableLog].&#x000D;&#x000A;</description>
    <guid>{F4C4712C-CEAE-4803-8E52-0E2049D5DE9F}</guid>
    <hr>80070002</hr>
    <errorinfo></errorinfo>
  </entry>
  <entry>
    <record>3211</record>
    <time>2021/05/12 09:28:08.989</time>
    <type>Error</type>
    <source>VisualStudio</source>

    <description>End package load [EFCorePowerToolsPackage]</description>
    <guid>{F4C4712C-CEAE-4803-8E52-0E2049D5DE9F}</guid>
    <hr>80070002</hr>
    <errorinfo></errorinfo>
  </entry>
</activity>
`

**Comment by ErikEJ** [comment]
Try the latest daily, or update VS to 16.9

**Comment by AnthonySzy-dot** [comment]
It works with VS 16.9 thank you

**Comment by GearTheWorld** [comment]
VS and all extensions were up to date.
I had to uninstall and install the extension again to get rid of this popup.

Very annoying...

Microsoft Visual Studio Enterprise 2022
Version 17.8.3
Microsoft .NET Framework
Version 4.8.09032

Entity Framework Core Power Tools   2.5
Adds useful design-time EF Core DbContext features to the Visual Studio Solution Explorer context menu.
