### ISSUE TITLE
Add Oracle.EntityFramework provider for reverse engineering request

### ISSUE THREAD

**Issue by MaherJendoubi** [ErikEJ/EFCorePowerTools#979]
Describe what is not working as expected.

I can not add a connection string for Oracle data base.

### Steps to reproduce
Include a complete description that I can redo to reproduce the issue.

![image](https://user-images.githubusercontent.com/1798510/118183504-79d46e80-b43a-11eb-815f-a885b5f5f32b.png)

### Further technical details
EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)

![image](https://user-images.githubusercontent.com/1798510/118184218-5fe75b80-b43b-11eb-95d7-50d26a78dd8b.png)

Database engine: Oracle

Visual Studio version: Visual Studio 2019 16.9.5

**Comment by ErikEJ** [comment]
As mentioned in the docs in the wiki, you need to install the Oracle VS tools.

**Comment by MaherJendoubi** [comment]
![image](https://user-images.githubusercontent.com/1798510/118261047-526db800-b4b3-11eb-8e13-e2caf957004e.png)

**Comment by ErikEJ** [comment]
Yes, then just use the standard Add connection feature (not Ad-hoc)

**Comment by MaherJendoubi** [comment]
The Add button in the middle ?

![image](https://user-images.githubusercontent.com/1798510/118265751-eb073680-b4b9-11eb-90d3-ff20adc00ea3.png)

**Comment by ErikEJ** [comment]
The add button at the top (not the drop down)

**Comment by ErikEJ** [comment]
Ping?

**Comment by MaherJendoubi** [comment]
I apologize for my late reply. I am suspecting an issue with the ODT for VS2019.
https://github.com/oracle/dotnet-db-samples/issues/169#issuecomment-841249536
Does your reversing tool work for a big database?

**Comment by ErikEJ** [comment]
The tool just uses the standard Oracle EF Core provider, so if that is broken it must be fixed.

**Comment by MaherJendoubi** [comment]
@ErikEJ I fixed the broken tool. Which button should I use? 

![image](https://user-images.githubusercontent.com/1798510/118375482-39076180-b5c2-11eb-8a38-36d895832bad.png)

**Comment by MaherJendoubi** [comment]
![image](https://user-images.githubusercontent.com/1798510/118375499-4ae90480-b5c2-11eb-8448-008c84e660ad.png)

**Comment by ErikEJ** [comment]
Use the top right Add button!

**Comment by MaherJendoubi** [comment]
I used it but I can not choose the tables. It generates all by default...

**Comment by ErikEJ** [comment]
Bug in the Oracle provider?
Exclude schemas?
(I know very little about Oracle)

**Comment by MaherJendoubi** [comment]
I don't think it's a bug in the Oracle provider.

![image](https://user-images.githubusercontent.com/1798510/118377262-8092eb00-b5cc-11eb-8e02-2c8b68cfda63.png)

**Comment by ErikEJ** [comment]
I do not understand the relevance of that screenshot

**Comment by MaherJendoubi** [comment]
There is no option in EFCore CLI to exclude tables.

**Comment by ErikEJ** [comment]
Correct, you can only include with the CLI.

But how does that relate to Power Tools?

**Comment by MaherJendoubi** [comment]
There is no such a GUI/feature for Oracle in Power Tools : 

https://user-images.githubusercontent.com/4169187/101766977-df1ae100-3ae3-11eb-864a-2bc4d010a81b.png

**Comment by ErikEJ** [comment]
Not sure I understand, you can include/exclude tables with Power Tools.

And you can do regex based filtering, as described in the docs.

**Comment by ErikEJ** [comment]
You need to provide repro steps and screenshots for me to understand your issue.

**Comment by MaherJendoubi** [comment]
Sorry I can not share the database.
