### ISSUE TITLE
Remove dependency from folder scaffolding class

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#984]
Remove src/GUI/RevEng.Core/Tables/CSharpModelGeneratorExtend.cs and replace with simple loop

**Comment by ErikEJ** [comment]
@eminmesic FYI!

**Comment by ErikEJ** [comment]
I am looking into this.

**Comment by eminmesic** [comment]
@ErikEJ any progress on your side, I think I have created some pretty simple solution to remove overridden EF Core class. I just have to go through the testing process to see potential problems.

**Comment by ErikEJ** [comment]
Looks quite good and simple, maybe move the code with the if clause to a seperate method?

I will await your PR then.

**Comment by ErikEJ** [comment]
Let me know if you need any help with testing.

**Comment by eminmesic** [comment]
I have sent a pull request for this issue [https://github.com/ErikEJ/EFCorePowerTools/pull/985](https://github.com/ErikEJ/EFCorePowerTools/pull/985)
