### ISSUE TITLE
UseSchemaName Does Not Respect Table Rename

### ISSUE THREAD

**Issue by mcavagnaro** [ErikEJ/EFCorePowerTools#988]
When `UseSchemaName` is set to `true` table renaming is not respected.

In my `efpt.renaming.json` I want to combine a schema prefix of "Pet" with the ability to rename a table. It appears that `"UseSchemaName": true` and the ability to rename a table are mutually exclusive.

EFCorePowerTools output:
```
public partial class PetGuineapig
{
	public int Id { get; set; }
	public string OwnerName { get; set; }
}
```

Desired output (`PetGuineapig` vs `PetGuineaPig`):
```
public partial class PetGuineaPig
{
	public int Id { get; set; }
	public string OwnerName { get; set; }
}
```

### Steps to reproduce
Table definition:
```
CREATE TABLE [pet].[GUINEAPig](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[OWNERName] varchar(255) NOT NULL
	CONSTRAINT [PK_GUINEAPigs] PRIMARY KEY CLUSTERED 
	(
		[Id] ASC
	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO
```

efpt.renaming.json:
```
[
	{
		"SchemaName": "pet",
		"Tables": [
			{
				"Columns": [
					{
						"Name": "OWNERName",
						"NewName": "OwnerName"
					}
				],
				"Name": "GUINEAPig",
				"NewName": "GuineaPig"
			},
		],
		"UseSchemaName": true
	}
]
```

### Further technical details
EF Core Power Tools version: 2.5.649

Database engine: SQL Server

Visual Studio version: Visual Studio 2019 16.6.5

**Comment by eminmesic** [comment]
I will take a look at this part. Thank you @mcavagnaro.

**Comment by ErikEJ** [comment]
I will have a look.

**Comment by ErikEJ** [comment]
Thanks for reporting this, I attempted a fix in the latest daily build

**Comment by mcavagnaro** [comment]
@ErikEJ Thank you!

About how long does it usually take between deployments?

**Comment by ErikEJ** [comment]
It is available from VSIX gallery now, the releases to Market place needs a mature daily (usually)
