### ISSUE TITLE
Reverse Engineer Model Creator. Default value of Boolean not created when set to true

### ISSUE THREAD

**Issue by michaelkunzler** [ErikEJ/EFCorePowerTools#99]
### Steps to reproduce:
Create a model with Reverse Engineer from column with bit (boolean) with default value (true)
3 tests:

Columns:
TestTrue (Default = 1)
TestFalse (Default = 0)
TestNull (Default empty = null)

Returns as model:
public bool? TestTrue { get; set; }
public bool TestFalse { get; set; }
public bool? TestNull { get; set; }

AND with Data Annotation:
[Required]
public bool? TestTrue { get; set; }
public bool TestFalse { get; set; }
public bool? TestNull { get; set; }

Should be: public bool TestTrue { get; set; } without question mark????

AND:
entity.Property(e => e.TestTrue ).HasDefaultValueSql("((1))");
entity.Property(e => e.TestFalse ).HasDefaultValueSql("((0))");
???

Database engine: MS SQL 2014

Visual Studio version: (e.g. Visual Studio 2017 latest)

**Comment by ErikEJ** [comment]
This will be fixed when 2.2 is released..

**Comment by ErikEJ** [comment]
Fixed in latest daily build
