### ISSUE TITLE
ContextFactory - 'Multiple constructors accepting all given argument types have been found

### ISSUE THREAD

**Issue by werwin81** [ErikEJ/EFCorePowerTools#991]
I have a Blazor project and I'm using a context class generated with the "Reverse Engeneer" option.

In use the following DbContextFactory Service in the startup class.

....
  services.AddDbContextFactory<MyContext>(options => options
      .UseSqlServer(
        Configuration.GetConnectionString("MyDbConnection"),
          o => o.EnableRetryOnFailure())
      .EnableSensitiveDataLogging(true)
      .EnableDetailedErrors(true));

  services.AddScoped<ZamContext>(p =>
      p.GetRequiredService<IDbContextFactory<MyContext>>().CreateDbContext()
  );
...

If I start the programm, the instruction
            services.AddScoped<ZamContext>(p =>
                p.GetRequiredService<IDbContextFactory<ZamContext>>().CreateDbContext()
            );
produces the following error:

System.InvalidOperationException: 'Multiple constructors accepting all given argument types have been found in type 'MyContext'. There should only be one applicable constructor.'

If I remove the empty default constructor from the generated class, everything works.
Is it possible to prevent the creation of the default constructor?

### Further technical details
EF Core Power Tools version: 2.5.659
Database engine: SQL Server

Visual Studio version: 16.9.6

**Comment by ErikEJ** [comment]
Which EF Core version?

**Comment by werwin81** [comment]
EF Core 5.0.6

**Comment by ErikEJ** [comment]
Looks like is is an EF Core bug: https://github.com/dotnet/efcore/issues/24124

**Comment by ErikEJ** [comment]
Manually remove the constructor??

**Comment by ErikEJ** [comment]
Fixed in latest daily buidl: https://github.com/ErikEJ/EFCorePowerTools/commit/b85c77de011ecc8e7a714938d840cff6bef7e66a
