### ISSUE TITLE
Change in Table Name Did Not Propagate to Configuration File

### ISSUE THREAD

**Issue by kenbo017** [ErikEJ/EFCorePowerTools#993]
In creating my new database to start with I decided to use singular names for the tables.  Unfortunately, after I ran the tool, I realized I had used one plural name for a table.  I went into SQL and changed the name of the table to be singular.  Then I ran the tool.  I saw the singular table name I had created was unchecked so I checked it.  When the tool was done it looked like all was good as the class was changed.  But then I saw that there was a new configuration file (I had selected in the options to create separate files for each table) with the singular name as well as the configuration file in the plural name.  Shouldn't the tool replace the entity class and the configuration class if I'm renaming them in SQL?

Also, on another note, I am starting from scratch and have created a class with a "Seed" method to populate the empty database that I created using the tool.  Since I'm using the database first approach with the tool, how will I seed the database with the seed data?  Also, once I have it all set-up properly, how will I remove the seed data?  This will happen after many changes to the SQL database as I grow it.

**Comment by ErikEJ** [comment]
Is the Orphan configuration file used by the DbContext? 

If not, you can just remove it.

Seed data should probably be included in a SQL script with MERGE statements.

**Comment by kenbo017** [comment]
Hi Erik,

Thank you for your quick reply!

No... the orphan configuration file is not used by the DbContext.  I
actually checked this and deleted the file.  I just thought I should report
it so you know for future upgrades.

Regarding the seed data, I'm not familiar with what you're saying.
Unfortunately, I'm not a real programmer.  I am working on an invention of
a fitness machine which I'm trying to get to market.  It is very high-tech
so I will be acquiring a lot of data, etc. so I need to store lots of
things in a database.  I've been trying, not so successfully, to create a
WPF application.  In starting fresh after realizing I didn't design the
original database too well, I thought I would switch to Core 5 because
"everyone" said that, if starting a new application I should use the latest
and greatest - which is CORE 5.  Unfortunately, there's very little
documentation with respect to WPF.  It seems as though Core 5 was
really designed for ASP.net.  As an example, in WPF they've eliminated the
start-up files and other things so I'm having difficulty getting going with
a "clean" application.  In your tool you gave the information that you
should not include your connection string in your code.  Unfortunately, the
links do not give any information as to how to move the string in a Core 5
application so I'm lost and left just leaving the connection string as
you've placed it in your tool.  Anyhow, I will try to figure out how to get
the test data I have from my old database into the new one.  It is not much
data so I might just give up and manually add it into the tables so I can
try moving forward.

Per above, I was wondering if I'm using your tool and the database first
approach, whether I could somehow create a migration that has my Seed
method in it and then use the migration tool to seed the database I created
with your tool.

Regards,

KS

Ken Schneider
Schneider Sales and Marketing
312 West Hillcrest Blvd.
Inglewood, CA 90301
ph: 310-680-9544
cell: 310-722-8827
e-mail: ***@***.***


CONFIDENTIALITY NOTICE. This electronic mail transmission may contain
privileged, confidential and/or protected information and is intended only
for the review of the party to whom it is addressed. Any unauthorized use
or disclosure of the information contained herein may be a violation of
federal law. If you have received this transmission in error, please
immediately return it to the sender, delete it and destroy it without
reading it. Unintended transmission shall not constitute the waiver of the
attorney-client or any other privilege.

**Comment by ErikEJ** [comment]
I is quite complicated to mix database first and migrations.
