### ISSUE TITLE
Feature Request - Optional Don't generate constructors for dbContext

### ISSUE THREAD

**Issue by CodeTile** [ErikEJ/EFCorePowerTools#995]
When I reverse engineer a database, the tool generates the constructors for database Context.  
Would it be possible to have an option to not generate the constructors?
In my code I have setup a partial class with constructors and the connection string.  The tool gives an option to not generate the connection string but there is none for not generating constructors.

**Comment by ErikEJ** [comment]
Why are you unable to use the constructor that takes DbContextOptions?

**Comment by CodeTile** [comment]
I can't remember exactly why, but having just tested again with the autogenerated constructors, it works.
I think it might of been an issue with DI for IConfiguration.  I was using Microsoft.DependancyInjection, but have switched to AutoFac recently.

**Comment by ErikEJ** [comment]
Fixed in latest daily build: https://github.com/ErikEJ/EFCorePowerTools/commit/b85c77de011ecc8e7a714938d840cff6bef7e66a
