### ISSUE TITLE
Is there a way to run EFCorePowerTools from command line?

### ISSUE THREAD

**Issue by Eternal21** [ErikEJ/EFCorePowerTools#996]
I've migrated away from Visual Studio to JetBrains Rider, and am really missing the functionality.  Is there a way to run this tool from command line, or is Visual Studio the only option?  Thanks.

**Comment by ErikEJ** [comment]
Yes, you can, see #340 with details here: https://github.com/ErikEJ/EFCorePowerTools/issues/340#issuecomment-670929754

**Comment by ErikEJ** [comment]
For anyone watching this issue, this is now planned, and you can find a design proposal [here](https://github.com/ErikEJ/EFCorePowerTools/issues/1751) - looking forward to any comments/suggestions.

**Comment by ErikEJ** [comment]
Preview 1 of the CLI tool is [now available](https://www.nuget.org/packages/ErikEJ.EFCorePowerTools.Cli/7.0.0-preview1#readme-body-tab)

![image](https://user-images.githubusercontent.com/4169187/234258058-2b6def58-f87c-455a-93da-21cd09d9e3f7.png)
