### ISSUE TITLE
Cannot convert lambda expression to type 'string' because it is not a delegate type

### ISSUE THREAD

**Issue by devhomecali** [ErikEJ/EFCorePowerTools#999]
The index expressions of dbcontext are incorrects:

Cannot convert lambda expression to type 'string' because it is not a delegate type:

            modelBuilder.Entity<ConsecutivosDocumentos>(entity =>
            {
                **entity.HasIndex(e => e.Consecutivo, "IX_ConsecutivosDocumentos_Consecutivo");**

SOLUTION: delete name of index, ej. IX_ConsecutivosDocumentos_Consecutivo

            modelBuilder.Entity<ConsecutivosDocumentos>(entity =>
            {
                **entity.HasIndex(e => e.Consecutivo);**

### Steps to reproduce
Execute reverse engeneer

### Further technical details
EF Core Power Tools version: 2.5.665
Database engine: (SQL Server LOCALDB 2016)

Visual Studio version: VS2019 16.9.4

**Comment by ErikEJ** [comment]
I think you are mixing EF Core 5 reverse engineering with EF Core 3 runtime, or vice versa.

**Comment by ErikEJ** [comment]
Ping?

**Comment by ErikEJ** [comment]
Closing, feel free to re-open if you can provide more info/resolution.
